### ISSUE TITLE
When to call stopSimulation.

### ISSUE THREAD

**Issue by irumgodil** [almende/vis#1000]
If I have a very heavy chart, I want it to lay out decently enough and then want the Simulation to end. I want the chart to render in a decent time as well. 

For now, I am adding a stabilization value of 400, but in some cases, the chart still keeps organizing itself even when all Stabilizations are done. These simulations are useful, as the chart is actually organizing itself in a clearer way. But I want to auto-detect the point of a clear visualization and simulation to stop at this point. I am not sure if I can figure that out generically for any kind of graph. 

If I call stopSimulation on stabilizationIterationsDone, sometimes the chart is still pretty convoluted, and it would benefit from more simulations. How can I know the chart is looking reasonable and at that point stop the simulation?

http://jsbin.com/xavivicezu/1/edit?html,output

**Comment by AlexDM0** [comment]
Hi,

There is no way to automatically detect the quality of the solution. There is not a total energy value available somewhere. 

You could set a random seed manually so the solution will be the same each time you show it and you can then judge how many iterations it needs by manually checking. You mention that you have a lot of dynamic data so I guess this isn't feasible for you. 

There's nothing we can do for this I'm afraid. 

Regards,

Alex
