### ISSUE TITLE
[Timeline] Group style gets a head cut

### ISSUE THREAD

**Issue by kixam** [almende/vis#1001]
Hi,

In Timeline, when I set a `style` for a group, the first style I put there does not make it to the DOM.

To reproduce:
- Please refer to the [jsbin](http://jsbin.com/jajimohife/edit?html,output);
- "Group 1" style is set to `style: 'border: 10px solid black; color: white; background-color: pink;'` *==> border style is not enforced !*
- try removing  `border: 10px solid black;` *==> text color becomes black (default) instead of white !*
- try inserting a style in first position instead: `style: 'fill: green; border: 10px solid black; color: white; background-color: pink;'` *==> border style gets applied !*

Am I missing something obvious ?

**Comment by brichbe** [comment]
Being curious I looked at your example and I'd say you're not missing anything obvious;  it does indeed seem to be an issue where the first 'key: value;' chunk is being dropped from the `style` property when being applied to the group's `vis-label`.

The same issue does not occur when setting that style string for an item, or when defining it as a CSS style and applying it to the group using the `className` attribute.

**Comment by kixam** [comment]
bump ?

**Comment by AlexDM0** [comment]
Hi,

We're a little busy at the moment and half our team is on holiday. Well get back to all outstanding issues once we have time. Not to worry, we will respond to all questions eventually. 

Regards,

Alex

**Comment by josdejong** [comment]
Thanks, this has been fixed in the develop branch (dist files are not yet up to date)

**Comment by kixam** [comment]
Thank you very much
