### ISSUE TITLE
Difference Between Version 3.12 and 4.3

### ISSUE THREAD

**Issue by chase1991** [almende/vis#1002]
Hi,

Happy Saturday.

Yesterday I experienced a really frustrating case: the version of visjs used in my company is 3.12, while that i used for local testing is 4.3. When i integrate my code based on 4.3 with an existing project of my company, i noticed there are some big differences:

1. In 4.3, i can use color: {inherit: "from"} to define the color of edge, but it does not work in 3.12 since all the edges are grey.
2. Meantime, the graph COMPLETELY loses the hierarchy i predefined. In 4.3, i defined my layout as: 
layout: {
        hierarchy: {
                     direction: "LR",
                     levelSeparation: 600 
        }
}
It works well: each level of nodes are in the same vertical line. However, in 3.12 the nodes randomly locate in graph without indicating the expected layout. 

I tried to download latest version and place it but i have no permission. Also, due to time limit, the best option for me is to compliant my code with 3.12 rather than 4.3. 

There are also some other differences and luckily, i figured them out.

Anyone has suggestions on how to solve the 2 problems above? 

Thank you so much.

**Comment by AlexDM0** [comment]
Hi,

If you download 3.12 from git releases, the documentation is included. You should read the documentation. We do not support the v3 branch anymore. 

Regards,

Alex

**Comment by chase1991** [comment]
Thank you Alex
