### ISSUE TITLE
Multiple lines and surfaces in Graph3d

### ISSUE THREAD

**Issue by nithingit** [almende/vis#1005]
Is there a way to create groups in graph3d? .

I saw an example of creating groups in graph2d (barssidebysidegroups). I was wondering whether the same could be implemented in bargraph generated using graph3d?

**Comment by josdejong** [comment]
Sorry for the late reply. Graph3d does not have support for groups, and you can only draw a single surface.

**Comment by zhulik** [comment]
It is sad to hear it, i looking for ability to draw multiple 3d lines. Is it possible without groups?

**Comment by josdejong** [comment]
No, this isn't supported right now. 

Shall I put this as a feature request?...

**Comment by zhulik** [comment]
I think, i am not alone in my desire to draw multiple 3d lines. Please, create feature request. Thanks!

**Comment by josdejong** [comment]
I've marked this issue as "enhancement", and changed the title to better reflect the feature request.

**Comment by shahimclt** [comment]
Yup. I would like to see that too..

**Comment by mojoaxel** [comment]
duplicate of #524
