### ISSUE TITLE
Update nodes and edge without resetting physics simulation

### ISSUE THREAD

**Issue by HRogge** [almende/vis#1006]
Hi,

I am using vis.js for a life-view on a distributed mesh network. I am loading new data which is converted into edge labels every few seconds and set it with the "update" command on the Datasets.

Unfortunately this triggers a reset of the physics simulation, which redistributes the nodes and edges again. Is there a way to update things like labels for edges and nodes without disturbing the current position?

**Comment by AlexDM0** [comment]
Hi,

Try disabling the physics by:
```
network.setOptions({physics:false})
```

Regards

**Comment by HRogge** [comment]
turning off physics completely didn't really helped, but it got me on the right track.

It seems that "dynamic edges" are doing crazy things when you update the node/edge dataset. Switching the mode to "continuous edges" helped a lot.

**Comment by AlexDM0** [comment]
Hi,

That should be fixed in the next release, there was a bug in not completely cleaning up the support nodes.

Regards,

Alex

**Comment by AlexDM0** [comment]
Added in release v4.4.0
