### ISSUE TITLE
Network topology display bi-directional links between nodes on the same level

### ISSUE THREAD

**Issue by sachin-samel** [almende/vis#1007]
I am creating hierarchy wise display of the network. I am adding bi-directional link between nodes on the same level, but it is displayed as straight line overlapping over each other. I tried with curved links as well, but my topology contains 50 nodes on the same level at a time, so cannot display it properly.

Can I get any solution for this?

Thanks

**Comment by AlexDM0** [comment]
Hi,

I've pushed a fix to the develop branch for the static smooth curves. You can use all kinds of static smooth curves for your hierarchical view. Try diagonalCross with the fix on the develop branch.

Regards,

Alex

**Comment by sachin-samel** [comment]
Hi Alex,

Please see the bin example at

http://jsbin.com/giwixorodi/edit?html,output

There is bi-directional link between node 1 and node 6, but it appears to be overlapping straight line.

I have used curved link with type :diagonalCross.

I am using vis version 4.3.0

Regards,
Sachin

**Comment by AlexDM0** [comment]
Hi,

As I said, there is a fix for this on the develop branch. Well include it in the next release. 

Regards

**Comment by sachin-samel** [comment]
Thanks Alex.

What should be the tentative date of release for next version?

Regards

**Comment by AlexDM0** [comment]
Hi,

I think within 2 weeks. You can already download it to setup your system. 

Regards

**Comment by sachin-samel** [comment]
Can you please suggest me the steps to download it?

Thanks

**Comment by AlexDM0** [comment]
Hi,

It's all on Git. 

https://github.com/almende/vis/tree/develop?files=1

Regards

**Comment by sachin-samel** [comment]
Hi Alex,

I tested on the develop branch that you shared. But it still shows the straight bidirectional link, also arrows are now shown for those links

I made following changes in hierarchicalLayoutUserdefined.html file:

1.   var options = {
        edges: {
			arrows:{
						to: true
					},
					smooth:{
						enabled: true,
						type: 'diagonalCross'
					}
        },
        layout: {
            hierarchical:{
                direction: directionInput.value
            }
        }
    };

2.  edges.push({from: 1, to: 6 });
     edges.push({from: 6, to: 1 });

Please see the image for you reference:
https://cloud.githubusercontent.com/assets/12997464/8348536/fc83115e-1b31-11e5-9e27-f09e72110913.png
.
Thanks

**Comment by AlexDM0** [comment]
Hi,

Did you use the minified or the vis.js file?

We don't compile the minified version in develop... Sorry, should have mentioned that. 

Regards

**Comment by sachin-samel** [comment]
Hi,

I have used vis.js file.

 <script type="text/javascript" src="../../../dist/vis.js"></script>

Regards

**Comment by AlexDM0** [comment]
This happens with the version from the dev branch:
http://jsbin.com/tawesotehi/1/edit?html,output

**Comment by sachin-samel** [comment]
Hi,

If you add a link  edges.push({from: 6, to: 1 }); then in that case, it does not show two different links. Those links are overlapping over each other.

Regards

**Comment by AlexDM0** [comment]
Yes, that is true, there is nothing we can do about that except for manually changing the smooth type like so:http://jsbin.com/miqeyigazi/1/edit?html,output

Regards

**Comment by sachin-samel** [comment]
Hi Alex,

Can this be a part of vis feature request?

Regards

**Comment by AlexDM0** [comment]
Hi,

It can be a feature request but at the moment I'm not sure this can be fixed.

We'll consider it in the future.

Regards

**Comment by sachin-samel** [comment]
Hi,

I am seeing this as close. 

I am not sure whether it is available in current release or not.

Can this be consider as a part of feature request?

Thanks,
Sachin

**Comment by AlexDM0** [comment]
Hi,

As I said. We could consider it as a feature request but I do not think this will be done. The reason is that the computational power required for this would not weigh against the benefits. 

Regards
