### ISSUE TITLE
Network topology load dynamic data

### ISSUE THREAD

**Issue by sachin-samel** [almende/vis#1008]
Hi,

Can we load the the data from server dynamically, by clicking on the particular node and append the loaded nodes as children of the clicked node?

Thanks

**Comment by AlexDM0** [comment]
Yes.

Take a look at the dataset, it's what it is designed for:
http://visjs.org/docs/data/

How it works in the network:
http://visjs.org/examples/network/data/datasets.html

more examples with it: 
http://visjs.org/network_examples.html

Regards
