### ISSUE TITLE
Support custom data in Timeline items

### ISSUE THREAD

**Issue by veger** [almende/vis#1010]
Hello,

I am using the Timeline component and would like to perform some checks when an items is moving. So I added a custom callback function to onMoving.
When the function is called, I am unable to 'find' the Timeline instance or any other custom data (that conveniently contains the timeline instance).
I am implementing a jQuery widget that uses the Timeline, so I cannot (and will not) use global variables to store such data. Especially since I need multiple of these 'timeline widgets' on one page.

Is there any way to obtain a reference to the timeline instance from the callback function?

If not, I would like to request support to add either the timeline instance to the callback function call, or to add custom data to the item. The latter is more conviently, I think, as it allows users to add any custom data to any item. On the other hand, I suppose that all/most users would like to have a reference to the timeline instance the object belongs to.

Regards,
  Maarten

**Comment by josdejong** [comment]
When you create the `onMoving` callback, you have a reference to your timeline instance, so you could just wrap this callback and add the timeline instance as extra parameter, something like

```js
function onMoving(item, callback, timeline) {
  // ...
}

var timeline = new vis.Timeline(container, items, {
  onMoving: function (item, callback) {
    onMoving(item, callback, timeline);
  }
});
```

**Comment by veger** [comment]
That is basically what I am doing.
I store my jQuery widget instance in a 'self' variable and use that one.

But this kind of goes against my wishes, as it is an ugly 'hack' to solve the problem that there is no way to have an additional data field to properly provide additional information to the callback functions.

**Comment by josdejong** [comment]
We could pass the Timeline instance by default as third parameter of the callback function.

**Comment by yotamberk** [comment]
@veger Is this still something you need?

**Comment by veger** [comment]
That would help a lot yes

**Comment by mojoaxel** [comment]
> But this kind of goes against my wishes, as it is an ugly 'hack' to solve the problem that there is no way to have an additional data field to properly provide additional information to the callback functions.

I actually think this is a solid solution in functional programming. You have a scope problem that you have to solve in your jQuery widget. That's the way to do it!

> We could pass the Timeline instance by default as third parameter of the callback function.

@josdejong To be consistent we hat to do this for every callback function in vis.js. I don't like this :confused:

**Comment by yotamberk** [comment]
@mojoaxel agreed... I think this issue should be closed.
