### ISSUE TITLE
Fine-graining editable override on individual items

### ISSUE THREAD

**Issue by veger** [almende/vis#1012]
Thanks for implementing issue #363.

I would like to ask to further expand this feature.
The Timeline allows to further specify what parts of the items are editable, using

```
var options = {
  editable: {
    add: true,         // add new items by double tapping
    updateTime: true,  // drag items horizontally
    updateGroup: true, // drag items from one group to another
    remove: true       // delete an item by tapping the delete button top right
  }
};
```

I would like to have these additional options to be available for individual items as well, so it would be easily possible fine-grain the editable control per items.
So it becomes, for example, possible to prevent a single item to get removed (while still allowing the other items to be removeable).

**Comment by josdejong** [comment]
The `editable` options are indeed globally applied. What you can do is us the [event listeners](http://visjs.org/docs/timeline/#Editing_Items) `onMove`,  `onMoving`, `onRemove`, `onAdd`, `onUpdate` to control whether individual items can actually be changed and how.

**Comment by veger** [comment]
True, but as a result the UI shows indications that the item is editable. Which is not the case when the item option editable is set to false. I can probably override them all using some clever CSS, but having this support build in, seemed a good idea to me.

It was just an feature request, now the editable option was added to the item options. If you guys do not feel like it to implement it, fine by me and I'll keep on using the method described above.

**Comment by josdejong** [comment]
I think you can indeed do some CSS adjustments. I'm not sure if it's worth implementing more options for this in the Timeline.

Besides that, you can also provide a property `editable: boolean` for individual items ([see example](http://visjs.org/examples/timeline/editing/individualEditableItems.html)).
