### ISSUE TITLE
Reaction on updateGroup is very slow

### ISSUE THREAD

**Issue by Bayees** [almende/vis#1013]
In the example in this link it can be seen that when tying to move items from one group to another appears to be sticky and not very fast.
http://visjs.org/examples/timeline/groups/groupsOrdering.html

**Comment by AlexDM0** [comment]
Hi,

I think this was caused due to a bug in the hammer usage. It should be fixed in the develop branch now. Could you verify this? The problem was that a drag was not detected if it was only vertical.

Regards

**Comment by Bayees** [comment]
It solved the problem. Thanks.
