### ISSUE TITLE
[Network] Question: Layouting help with dynamically generated graph

### ISSUE THREAD

**Issue by ostraconify** [almende/vis#1015]
Hello,

I've recently started a project that includes some functionality similar to the product Maltego, specifically that you start with seed entities on a graph and run transforms to dynamically generate new entities (nodes) and relationships (edges) - you can see sort of how this work in Maltego [in this video](https://youtu.be/FJzqRqM8lEo?t=77) - although ignore the hierachical layout, there is a demo of other layouts around 1:50.

I have a couple of issues here. Firstly when adding new entities (I use nodes.add( my_entity_object) for a network graph, and then add corresponding edges), they all initially appear in the centre of the graph, and are then pulled into a stable position by the physics engine. While this works somewhat, the physics of the edges means that the nodes gravitate towards the centre, even without centralGravity, for example [here](http://imgur.com/pCxbUgj,q1inoey#1), whereas I'm looking for a layout more like [this](http://imgur.com/pCxbUgj,q1inoey#0).

The way that [this example](http://marvl.infotech.monash.edu/webcola/examples/browsemovies.html) in webcola works in somewhat similar to what I'd like to achieve, but I vastly prefer visjs so far :smile: 

I guess my questions are;
1. Is it possible to have nodes spawn at a certain point/defined area - ideally near to a specified node that I know I'm about to add an edge to?
2. Can you recommend a layout solver/parameters to emulate the webcola example above?

Many thanks!

**Comment by AlexDM0** [comment]
Hi,

1) You can supply an x and y coordinate to nodes to make them spawn there. You can use the ID of the node you clicked on (with the click event or selectNode event) to get its position using the vis API methods (I'm on mobile, it's in the docs). You could make a best guess for the positions, say in an arc around the node with distance similar to edge length in the direction away from the center of all nodes.

2) I guess it doesn't really work on mobile but in general the forceAtlas2Based solver is less chaotic than the BarnesHut. It is a different approach than web cola has so we cannot reproduce the exact behaviour. Take a look at the physics example on our webpage and play with the settings to achieve what you are looking for. 

Going by your images I think your edges are too long compared to your repulsion. The edges will stretch from the repulsion too so again, use the configure:'physics' option and play with it :). 

Finally, the super smooth animations in the video and in web cola are nice but they are not possible in vis. The webcola approach doesn't really scale past 100 nodes so we do it differently. 

Regards

Alex

**Comment by ostraconify** [comment]
Thanks for the swift response - appreciated!

1) Thanks - I'd actually tried to set x and y on adding and not noticed a diference in testing, my playing with one of the network examples I can see it does indeed work, so I'll guess I'll try some stuff based on that.

2) I feared I'd have to spend some time playing with the physics options.. will try my best not to OCD too much about getting the perfect config :smiley: Thanks for the tip about edge length, will bear that in mind. The lack of scaling in the webcola approach was putting me off, I'm not fussed about pretty animations but getting a usable layout is important for my use case.

Cheers!
