### ISSUE TITLE
Stabilization needed?

### ISSUE THREAD

**Issue by irumgodil** [almende/vis#1016]
Hi,
In my chart I want to render about 5000 edges and 1000 nodes. Currently with the stabilization mechanism that I am using, it takes a good 20-30 seconds for the whole chart to stabilize at 400 iterations (Which is where I feel it is a reasonable viewing image). 

Ideally, I want the perf. to be really low and the chart as a basic snapshot to just appear right away - in a decent viewable format. I am just not able to figure out if there is something I am doing, or are stabilizations really that slow.

One thing I have now changed is that instead of adding single nodes/edges, I am adding them all at once through: this.nodes.update() and this.edges.update().

But is this expected? Can I do something to make things appear right away?

Thanks.

**Comment by Tooa** [comment]
Hi,

once your network is stabilized (`stabilized` event), you can store the node positions (`network.storePositions`) using a Dataset. This enables you to load the network with fixed positions instantly :) Have a look at this issue [here](https://github.com/almende/vis/issues/867#event-334378043). Alex explained this to me a while ago.

**Comment by irumgodil** [comment]
My problem is that getting to "stabilized" is taking that long....

**Comment by Tooa** [comment]
Yes, I know. But you need to take this time once into account.  Which solver are you using? Maybe the forceAtlas solver is faster.

**Comment by AlexDM0** [comment]
Hi,

Apart from what Uli mentioned, the dynamic smooth edges are much slower than the static ones. If you havent already, use smooth:{type:'continuous'} or any of the other ones except dynamic. 

It's a hard problem to solve. It takes time and there is no getting around it. Saving the positions is the only solution. 

Uli, thanks for responding as well :)

Regards,

Alex

**Comment by irumgodil** [comment]
so I am now trying to do the first simulations using "continuous" edges, and then change to dynamic. However, the node positions are not persisting and everything is starting from scratch in the new simulation. Is there anything I am missing:

this.network.on("stabilizationIterationsDone", function (params) {        
        
        if (g.stopSimulation) {
            g.network.stopSimulation();

            if (g.stabilizationIteration == 1) {
                g.network.storePositions();

                g.options.edges.smooth.type = "dynamic";

                g.network.setOptions(g.options);
                g.stabilizationPercent = 10;
                g.startPercentage = 90;
                g.stabilizationIteration++;
                g.network.stabilize(100);
            }
            else {
                g.stabilizationIteration = 1;
                g.viewModel.updateStatus("Loading Complete" + " - (100% Done)...");
                g.viewModel.hideLoading();
                g.fitOnDone = true;
            }
        }

**Comment by Tooa** [comment]
Hi,
maybe you got something wrong. You need to manually store the dataset yourself after calling storePositions. This method only annotates `x` and `y` attributes in your node dataset. There is no "memory" when you restart your application. 

     network.on("stabilizationIterationsDone", function (params) {
          console.log("finished stabilization interations");
          network.storePositions();

          var nodeItems = nodesDataset.get();
          //store this on your disk
          var nodesJson = JSON.stringify(nodeItems);

The next time you start your application use the previously stored nodes dataset and disable the physics `options:{physics:{stabilizations:false}}}`.

**Comment by irumgodil** [comment]
ok thanks.

**Comment by AlexDM0** [comment]
If you only want to stabilise the dynamic edges there is an option in physics:{stabilization:onlyDynamicEdges}

This will lock the nodes in place and only stabilise the dynamic edges. 

For your case though, I'd just keep the edges static. Dynamic means an invisible support node gets added to each edge. This makes your system 6000 nodes to simulate. 

Regards
