### ISSUE TITLE
Bar width depending on zoom

### ISSUE THREAD

**Issue by mschallar** [almende/vis#1017]
Hello,

how can I achieve the following goal: My bars should be as width as the month is wide, e.g.,
1st bar: Apr to May
2nd bar: Mai to June

and so on. I can define a width of e.g., 1000px but the bars do overlap each other when i zoom out. When I zoom in and the bars have a fixed width there will be a gap between the bars and the next month.

Space: ![image](https://cloud.githubusercontent.com/assets/6470225/8324397/7a6d9afe-1a50-11e5-8365-53d82c7b4f9d.png)
Overlap: ![image](https://cloud.githubusercontent.com/assets/6470225/8324423/ae46e0c4-1a50-11e5-982b-51d72316d1b3.png)

Any ideas how to achieve this?

Regards,
Manuel

**Comment by AlexDM0** [comment]
Hi Manuel,

The bars should not overlap when you zoom out.. could you make a jsbin to show this?

Regards

**Comment by mschallar** [comment]
I've recreated the problem. Only occurs (ofc) when you define 

    barChart: {
      width: 1000
    }


My mistake. So the 'overlap' does not occur anymore, but how can i get rid of the 'space' problem mentioned above? I would like to make the bars as wide as possible.

**Comment by AlexDM0** [comment]
Hi,

How about when you make it 1000000 instead of 1000?

It's ugly but it should work?

You should be able to set the width to anything but still overlap shouldn't occur... 

Regards

**Comment by mschallar** [comment]
I've created a jsbin: http://jsbin.com/cuzofejido/edit?html,js,output

Quite a simple example, bars do overlap if you set width at e.g., 1000.

**Comment by AlexDM0** [comment]
I'll look into it soon, sorry for the inconvenience.

**Comment by mschallar** [comment]
Have you found the problem? Or narrowed it down?

**Comment by AlexDM0** [comment]
Hi,

Its been quite busy recently and I have not had the time to look into it.

Sorry, I cant promise when I'll get around to it.

Regards

**Comment by ludost** [comment]
We are still contemplating if we should introduce some form of "fill" bars, where the width is always fitting to the next bar. Biggest problem is how to handle the last bar consistently. Anybody knows a use-case that looks like that?

**Comment by mschallar** [comment]
What do you mean by "that"? My use case above, or the use case about the first and last bar's width?
In case 2:
bar.lastBarWith: [width as the previous one | fixed with | ??]

**Comment by ludost** [comment]
What I'm looking for is some real-life examples where such a filled-in bar chart would be useful. How do such examples handle the side-by-side bars, how do such examples handle the last bar, etc.? It could be argued that such a diagram is no longer a bar chart....  Given the right use-case we can introduce more support for such bars, but currently it's a bit unclear what should be provided. (That said, as far as I can tell your specific use-case is now fixed)
