### ISSUE TITLE
Draw points only if they have an itemlabel

### ISSUE THREAD

**Issue by mschallar** [almende/vis#1018]
Hello,

It would be nice if there would be an option like:

    var options = {
      drawPoints: "onlyIfLabelExists" // [true, false, onlyIfLabelExists]
    };

which is availabel for the Graph2D as well as for the Groups.

I'm adding a label to my points every e.g., month and it's becoming unreadable if I zoom out

![image](https://cloud.githubusercontent.com/assets/6470225/8325736/0df1a3aa-1a5c-11e5-90d0-3215c908f5f4.png)

(I don't wanne use X and Y offsets in this example)

Regards,
Manuel

**Comment by AlexDM0** [comment]
Thank you for your feature request. We want to redo the graph2d this year and we'll keep this in mind. 

Regards
