### ISSUE TITLE
Network topology add node and edges

### ISSUE THREAD

**Issue by sachin-samel** [almende/vis#1019]
Hi,

Can we override the default manipulation functions and look and feel? 

I want to have a html button and clicking this button will create a node. After selecting this node and dragging will draw a link to another dropped node.

Can I make the use of manipulation functions like addNode, addEdge etc. to achieve this?

Thanks,
Sachin

**Comment by AlexDM0** [comment]
Hi,

I think it would be much much easier if you use the dataset for this together with the events. The addNode only adds a node to the dataset with a callback. If you manage the dataset yourself you have much more freedom. There are a number of examples on our website regarding the dataset. 

Cheers

**Comment by sachin-samel** [comment]
Thanks Alex.

I saw an example http://visjs.org/examples/network/data/dynamicData.html, where we add nodes and edges using dataset. Adding nodes is fine for me. To add an edge, can we provide the behavior of selecting a node and drag and drop edge to another node to connect? (like one shown in data manipulation example).

Regards

**Comment by AlexDM0** [comment]
Hi, 

All the methods of the manipulation are in the API.

network.addEdgeMode() will toggle that mode.
http://visjs.org/docs/network/

Regards

**Comment by sachin-samel** [comment]
Hi

I played around with addEdgeMode().

I have called addEdgeMode() when node is clicked. For that I added "selectNode" event on node. In this case, we need to first select the node and then again click on the same node to start drawing the link.

Can we have a functionality so that when we click on the node once and start dragging, to draw the link?

Please see the example on http://jsbin.com/hukefenaju/edit?html,output

Regards

**Comment by AlexDM0** [comment]
Hi,

Yes, just make sure that mode is always on:

http://jsbin.com/jocuyavizu/1/edit?html,output

Regards

**Comment by sachin-samel** [comment]
Thanks.
Its working.
