### ISSUE TITLE
Feature request: Add a method to reset the manipulation bar

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#1020]
Hi Guys,

Maybe related to #949 but not fixed by this in develop.

Passing a null pointer to the callback doesn't make the manipulation bar reset (e.g. for the add node handler). http://jsbin.com/titeza/edit?html,output

Thanks

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

We don't claim it should reset the manipulation bar do we? Passing null cancels the proposed change. Clicking back is something else entirely :). 

We currently do not have a "back substitute method".

Regards

**Comment by AlexDM0** [comment]
Also, shame on you, thats not a valid option

http://jsbin.com/luzokehini/1/edit?html,output

**Comment by felixhayashi** [comment]
> We don't claim it should reset the manipulation bar do we? Passing null cancels the proposed change. Clicking back is something else entirely :). 

Ahhhhh true. Yes I just checked my code. What I did back in v3.x.x was to call 

    // make the manipulation bar disapper again
    this.network.selectNodes([]);

This doesn't work anymore :( But is there any way I can cancel the manipulation process (=reset the manipulation bar) programatically in v4? The network method `network.disableEditMode()` does only hide it.

One workaround is to call enable right after disable

      this.network.disableEditMode();
      this.network.enableEditMode();

but maybe there is something more elegant?

> Also, shame on you, thats not a valid option (=P)
> http://jsbin.com/luzokehini/1/edit?html,output

ehm, what option exactly are you talking about? I only copy pasted from the docs page... Also strange, I did not create a bin of that name.. Also I cannot open it as Dave the jsbin bot seems down... ahh

**Comment by AlexDM0** [comment]
```
 options.onEditEdge = function(data, callback) {
    callback(null);
  };
  ```

**Comment by AlexDM0** [comment]
At the moment no, but I'll put this as a feature req for such a function

Regards

**Comment by felixhayashi** [comment]
> At the moment no, but I'll put this as a feature req for such a function

Thanks!

**Comment by AlexDM0** [comment]
Hi Felix, 

We've discussed this internally and we feel that 

```
network.disableEditMode();
network.enableEditMode();
```

is so easy that we dont want to inflate the API with a reset function just to replace this.

Sorry!

**Comment by felixhayashi** [comment]
Hi Alex

> is so easy that we dont want to inflate the API with a reset function just to replace this.

Ok, no problem.
