### ISSUE TITLE
timeline setItems() slow in iOS?

### ISSUE THREAD

**Issue by GluedToTheScreen** [almende/vis#1021]
Has anyone else experienced SLOW responsiveness of the timeline under iOS?

Specifically, the step where it setItems() takes MUCH longer to complete on an ipad ---20+ seconds--- than on desktop or android -- less than 1 second--- and panning is the same way.

This is with only 100 items in the timeline.  HOWEVER, they do contain HTML and images which I suspect is part of the issue as I don't see this in a stripped down version of the timeline.  Is there something about the handling/rendering of HTML that might cause poor performance?

This problem will probably end up being on my end as I am mashing together a lot of moving parts... but I have run into something that is puzzling and am looking to fill in some blanks.

Thanks for this absolutely great project!

**Comment by AlexDM0** [comment]
Hi,

Could you provide an example, code or anything else to go on? I'm not exactly sure what you expect here :)

I have not experienced this myself but then I'm not working much on iOS..

Regards
