### ISSUE TITLE
datasets vs. dataviews

### ISSUE THREAD

**Issue by GluedToTheScreen** [almende/vis#1022]
Could someone please explain the distinction between DataSets and DataViews?  

At first I thought views where filtered/sorted datasets but the doc says you can do that within datasets.  What is the difference with using dataviews?  

I am not clear on how/when to use which.

Thanks!

**Comment by AlexDM0** [comment]
Hi,

Views are not ment for adding, editing and removing data. They are only ment as "views" on the data.

Regards
