### ISSUE TITLE
Prevent stabilization on drag/move.

### ISSUE THREAD

**Issue by irumgodil** [almende/vis#1024]
Hi,

I do not want my chart to start stabilizing when I move around nodes/edges. I only want it to stabilize with the "stabilize" call. I am not clear on what is the right option there?

these are my options currently: 

    this.options = {
        nodes: {
            shape: 'dot',
            scaling: {
                label: {
                    min: weve.cg.view.ChartVisual.minFont_largeGroup,
                    max: weve.cg.view.ChartVisual.maxFont_largeGroup
                },
            }
        },

        edges: {
            smooth: {
                enabled: true,
                type: "dynamic",
                //   roundness: 0.5
            },
        },

        interaction: {

            multiselect: false,
            navigationButtons: true,
            selectable: true,
            selectConnectedEdges: true,
            tooltipDelay: 100,
            zoomView: true
        },
        physics: {
            solver:'repulsion',
            stabilization: {
                enabled: true,
                iterations: 250, // maximum number of iteration to stabilize
                updateInterval: 2,
                onlyDynamicEdges: false,
                fit: true
            }
        }
    };
thanks.

**Comment by AlexDM0** [comment]
Hi,

You'll have to turn off physics.(setOptions(physics: false))

You can enable it before calling stabilise and disable it when stabilizationIterationsDone. 

You have a lot of nodes, the repulsion solved is very slow in this case. I recommend either BarnesHut or ForceAtlas2Based. Those scale with O(NlogN) whereas repulsion scales with O(N!)

Regards

**Comment by abhisheksimion** [comment]
@AlexDM0: I am trying to stop animation once the nodes and edges are aligned properly, I followed your approach but looks like I am missing something. Please check below plunker link
http://plnkr.co/edit/8G4TtjLBu8lSHCuKOQOr?p=preview

**Comment by AlexDM0** [comment]
Hi,

You need to actually SET the options using the setOptions method. You only change the JSON.

Regards
