### ISSUE TITLE
Selecting many nodes with a mouse drag

### ISSUE THREAD

**Issue by idrissou** [almende/vis#1025]
Apparently the selecting a node/many nodes with a mouse hover in a network feature does not exist, at least according to the documentation. (Something like that: http://bl.ocks.org/mbostock/raw/4566102/)

Am I wrong?

**Comment by AlexDM0** [comment]
This does indeed not exist. There are no plans to add this in the near future.

Regards,

Alex

**Comment by idrissou** [comment]
Thanks for the swift reply. I may be interested in adding this feature, but first let me finish those damn finals on the door. Will keep you posted on this!

Idriss

**Comment by AlexDM0** [comment]
Hi,

sounds good! Thanks for wanting to contribute! There is another issue on this #977 but the implementation is very much tied into other frameworks.

I think a great implementation could be done with just the render events and the drag events. If you have any questions on the source just let me know.

Cheers

**Comment by AlexDM0** [comment]
closing this as a duplicate of 977, lets continue there
