### ISSUE TITLE
Dragging nodes vertically in LR/RL hierarchical layout

### ISSUE THREAD

**Issue by atima** [almende/vis#1026]
I am unable to drag a node vertically in the LR/RL hierarchical layout (the node does not move). However, if I drag a node horizontally and then vertically, it works. This may confuse users. It would be great if this is fixed.

Thanks and regards.

**Comment by AlexDM0** [comment]
Hi,

This is fixed in the develop branch and will be included in the next release. We expect this to be around the end of next week. 

Regards

**Comment by AlexDM0** [comment]
Added in release v4.4.0
