### ISSUE TITLE
find only outgoing nodes in network

### ISSUE THREAD

**Issue by ksrkk** [almende/vis#1029]
is there any way to find only outgoing nodes for specific node in network?

**Comment by AlexDM0** [comment]
Hi,

What exactly do you mean by outgoing? Based on the edges? You can use the methods to get the connected edge ids, you can then get the information of those specific edges from the data you put in the network. Loop over those and check which nodes are on the side you need. 

Regards

**Comment by ksrkk** [comment]
Hi Alex,

I am sorry. Yes its based on the edges only. If i use connectedEdges() or connectedNodes() methods, it is returning all the nodes and edges which are away-off and away-in from the node. But i need only which are away-off edges from one node.

Thank you.

**Comment by AlexDM0** [comment]
Hi,

All our methods give you IDs of edges and nodes. You have to use these ids to look up the data and you can use the data to do whatever you want. 

This answer also applies to you other issues. 

Regards,

Alex
