### ISSUE TITLE
Allow creation of custom shapes for Networks

### ISSUE THREAD

**Issue by synthomat** [almende/vis#1031]
Hey!

Am I missing somethin or are all shapes and their selection hard [coded in the Node-Class](https://github.com/almende/vis/blob/master/lib/network/modules/components/Node.js#L228)?
I would like to use custom shapes in my Network Graph.

Maybe the [default-branch](https://github.com/almende/vis/blob/master/lib/network/modules/components/Node.js#L273) of the switch statement where shapes are selected should first look into the Network options if there are custom shapes declared and take them instead of the Ellipse.

Thanks!

**Comment by AlexDM0** [comment]
Hi,

Currently all the shapes are hard coded yes. Since we do not have the support for custom shapes in the API the default will remain as it is for the moment. 

You could easily extend vis to allow your shape though. What exactly did you have in mind?

Regards,

Alex

**Comment by synthomat** [comment]
@AlexDM0 how do you mean, that you don't have support in the API?

We wanted to position the label on the right side of the node, change some shapes a bit and put more text and images to it.
Here is a concept, not showing all our ideas, though
![concept](http://synthomat.de/tmp/xzn9y.png)

Regards,
Synth

**Comment by AlexDM0** [comment]
Hi,

With the API I refer to the options, methods and events we have in the documentation. Those are not designed for custom shapes and that's what I mean with not supported. 

Some of the things can be done using the render events but that does not seem to be what you're looking for. Although you could do the multiple circles and outlines with render events and the white boxes with HTML through SVG (example on our website). 

On the other hand, vis is open source and the network is nice and modular now. You can fork vis and add what ever you want. The current shapes should give you a pretty detailed idea of how that should work. 

There are a few methods that need to be implemented per shapes so it doesn't really suit a single callback. 

If you come up with a nice new shape we'd be happy to accept a pull request to add it to vis. 

We do want to add label settings for on top, left, right and inside for all shapes. If there would be an offset too that would allow your white boxes as well. 

If you'd like to contribute we could look into which ways would be most efficient. 

Hope that clears it up. 

Regards,

Alex

**Comment by synthomat** [comment]
Cool, thanks! I think I'll try to extend vis and if something usefull comes out of it, I'll get back to you :)

Best Regards,
Anton

**Comment by AlexDM0** [comment]
Sure :) if you have any questions relating to the source, let me know!
