### ISSUE TITLE
override stack method in timeline

### ISSUE THREAD

**Issue by fahussain** [almende/vis#1032]
First of all thank you so much for the wonderful work. 

We are using Timeline to display data in our application. To accommodate some requirements we need to make some changes to the stack method. What would be the best way to override only the stack method(load that as a separate patch) and not tinker with the source code. Also is there any way to bundle only the Timeline and not the other components since we don't need them?

Thanks.

**Comment by AlexDM0** [comment]
Hi,

As for custom building, I'd like to refer you to the readme on our github page.
https://github.com/almende/vis#example-1-bundle-a-single-visualization

As for the overriding the stack method, I would recommend you look into the source. 
https://github.com/almende/vis/blob/master/lib/timeline/Stack.js

The reason I do not give you a simple method to overrule is that there could be auxiliary consequences when you're overriding something. You'll have to read the code to understand what it's doing to be able to change it without conflicts.

Regards,

Alex

**Comment by fahussain** [comment]
Hi Alex,

Thank you so much for your response and the links you have provided are very helpful. I have looked into the code and I know what stack is doing and have the changes that we need to override stack method. For the moment this is what I am doing:

// Load vis then load the following patch
var newStack = function(items, margin, force) {
    // custom codes goes here
    // references to exports. are replaced with this.
 }; 
vis.timeline.stack.stack = function (){
    newStack.apply(vis.timeline.stack,arguments); 
} 

I just wanted to know if this is the right way of doing this or I should take some other recommended approach.

Best,
Faheem

**Comment by yotamberk** [comment]
@fahussain Is this issue still relevant? Did you manage to achieve what you wanted?
