### ISSUE TITLE
onMove not triggering dataSet update properly

### ISSUE THREAD

**Issue by lBowlin** [almende/vis#1033]
In the Timeline the onMove callback pushes any changed item to "changes", but dataset.update(changes) is not run after the callback. It's present in the code several lines later, but is not being hit from the callback.

```js
me.options.onMove(itemData, function (itemData) {
          if (itemData) {
            // apply changes
            itemData[dataset._fieldId] = id;
            changes.push(itemData);
          }
```
[line reference](https://github.com/almende/vis/blob/dae3c3d893b839987c4444bf7b05a4d0923515eb/lib/timeline/component/ItemSet.js#L1374)

but this never calls the corresponding (because it is outside of the anonymous callback):
```js
if (changes.length) {
      dataset.update(changes);
    }
```
[line reference](https://github.com/almende/vis/blob/dae3c3d893b839987c4444bf7b05a4d0923515eb/lib/timeline/component/ItemSet.js#L1392)

**Comment by josdejong** [comment]
Good point, this will not work when the `onMove` function is asynchronous.

**Comment by josdejong** [comment]
Fixed it in the develop branch
