### ISSUE TITLE
viewChanged event is gone

### ISSUE THREAD

**Issue by ojotoxy** [almende/vis#1034]
Last seen in 3.12.

It was useful.

**Comment by AlexDM0** [comment]
Hi,

We figured the zoom and drag events should be sufficient for this?

Do you have a case where you need the viewChanged?

Regards

**Comment by ojotoxy** [comment]
The dragging event in particular seems to be delayed several compared to viewChanged.
Zoom events didn't fire when the scale was changed programmatically, which I also do.

Currently I work around this by checking the scale and position on beforeDrawing  -- it didn't turn out to be much of a performance hit.

Thanks

**Comment by AlexDM0** [comment]
Hi,

Dragging may be a little slower but dragStart should do the trick?

You sound like you want a viewChange instead of a viewChanged event (as in one that fires repeatedly). 

Just for my understanding of the issue, what do you do with this data?

Regards

**Comment by ojotoxy** [comment]
Right, it would need to fire immediately whenever the view as used for rendering has changed.

It's for manipulating custom DOM objects as a layer underneath the canvas. They are supposed to sync up.

I realize an alternative could be adding custom canvas drawing code instead of DOM elements. (some objects are easier to draw outside a canvas...) It's just the way I originally wrote it for v3 of vis.js and I was upgrading to 4.

**Comment by AlexDM0** [comment]
I see, well that is exactly what the render events are for :). 

Regards
