### ISSUE TITLE
do we have any methods like to get previous edge, next edge, previous node, next node in the network?

### ISSUE THREAD

**Issue by ksrkk** [almende/vis#1035]
I would like to get the information of the previous and next edges, nodes in the network.
Are there any method to achieve these information?

Thank you.

**Comment by AlexDM0** [comment]
Hi,

All our methods give you IDs of edges and nodes. You have to use these ids to look up the data and you can use the data to do whatever you want. 

This answer also applies to you other issues. 

Regards,

Alex
