### ISSUE TITLE
Error in function _lockedRedraw

### ISSUE THREAD

**Issue by vges** [almende/vis#1036]
Hi,
I think there  is a bug in Function _lockedRedraw (Line 35584 in vis.js 4.3.0) causing a cascade of "undefined function" errors for me. The line 
`var viewCenter = this.DOMtoCanvas({ x: 0.5 * this.frame.canvas.clientWidth, y: 0.5 * this.frame.canvas.clientHeight });`
should look like this:
`var viewCenter = this.canvas.DOMtoCanvas({ x: 0.5 * this.canvas.frame.clientWidth, y: 0.5 * this.canvas.frame.clientHeight });`

Regards
Volker

**Comment by AlexDM0** [comment]
Hi Volker,

You're absolutely right! I've pushed your fix to develop. 

Regards,

Alex

**Comment by vges** [comment]
Hi Alex,
I think you need to reopen the issue: In 4.4.0 only the first error is corrected. The twisted frame/canvas calling is in there still and produces  a bunch of "undefined" errors for me. After replacing it by canvas.frame everything runs fine.

Regards,
Volker

**Comment by AlexDM0** [comment]
Hi Volker,

I see now I misread the issue. I indeed only changed one thing. 

I'll push a fix to develop today, or you can do a pull req if you'd like to contribute :). 

Thanks for letting me know. 

Regards,

Alex

**Comment by AlexDM0** [comment]
Fix has been pushed.  It'll be in the next release. Sorry for the partial fix in 4.4.0.

Regards

**Comment by AlexDM0** [comment]
released in 4.5
