### ISSUE TITLE
Timeline 'currentTimeChange' event

### ISSUE THREAD

**Issue by nabsky** [almende/vis#1037]
I need to draw some items which ends at current time, so their length permanently changes. Can you please suggest any solution for this case? Currently I add my event emmiting in CurrentTime.prototype.redraw, then I listen to this event, set proper item.end and perform items.update(item). But it looks weird.

**Comment by AlexDM0** [comment]
Hi,

What do you mean with "looks weird"? Is there a visual artifact or jitter or is it the code style that you do not like.

Regards

**Comment by nabsky** [comment]
Thanks for response! There is no any visual artifacts or jitters, it's all about code style, because in my workaround:

1) I have to modify vis.js to add 
`this.body.emitter.emit('currentTime');`
in CurrentTime.prototype.redraw

2) I have to add external listener to modify timeline items in my view, like that:
`                this.timeline.body.emitter.on("currentTime", function (e) {
                    that.items.forEach(function (item) {
                        if (item.isActive()) {
                            item.end = moment();
                            that.items.update(item);
                        }
                    });
                });
`
It works without any jitters but it looks wrong. Can you please give me advice how to make it better?

Thanks again!

**Comment by AlexDM0** [comment]
Hi,

Would a setInterval of half a second maybe be cleaner?

Regards

**Comment by nabsky** [comment]
It looks much cleaner but in this case item is not drawing so smooth, it permanetly "jumps" to current time. But I think I prefer this way. Sorry for disturbing and thank you so much for the great library!

**Comment by AlexDM0** [comment]
Hi,

Yes but it would jump either way I'm afraid. Hence my suggestion for half a second to make it less noticeable. 

Have fun using vis!

Regards
