### ISSUE TITLE
Head of arrow for edge to node with icon shape drawn at false ending

### ISSUE THREAD

**Issue by vges** [almende/vis#1039]
Hi,
for a node with icon shape an edge with a arrow to this node is drawn at the 'from' node instead of the 'to' node. (version 4.3.0)

Regards,
Volker

**Comment by AlexDM0** [comment]
Hi Volker,

Thanks for letting us know! We'll fix this for the next release.

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi Volker,

I've pushed a fix for this to develop! Thanks for letting us know!

Regards,

Alex
