### ISSUE TITLE
Network issue after integrating to another framework

### ISSUE THREAD

**Issue by sachin-samel** [almende/vis#1041]
HI,

I am trying to integrate the vis library into our existing application. But it is giving an error "vis in not defined" when I tried to create the Network.

I checked for the file and it is at proper path.

But it gives error when I try to call vis.Network(...).

Any suggestions would be helpful.

Thanks

**Comment by AlexDM0** [comment]
Hi,

I'm guessing something goes wrong with scoping. You're trying to access something in global (or window scope) while you are in another context. Try:
```
console.log(this);
```
Without code I cannot help you any further.

Regards

**Comment by sachin-samel** [comment]
Hi,

You are right. This is the scope issue.

We traced "this.vis" and it is returning undefined.

In our case "this" contains object called "wap" and also other objects, but it does not contain "vis" object.

Not getting how to deal with it.

Thanks

**Comment by AlexDM0** [comment]
If this is a scoping issue, this really does not have anything to do with vis specifically.

I'd recommend you read up on javascript scoping.
http://www.smashingmagazine.com/2009/08/01/what-you-need-to-know-about-javascript-scope/

Regards,

Alex

**Comment by sachin-samel** [comment]
Thanks Alex.

Issue resolved.
