### ISSUE TITLE
Option to disable dragging custom times on timeline

### ISSUE THREAD

**Issue by ahmadsoe** [almende/vis#1042]
Hello,

I don't see a way to disable dragging custom times in the docs.
Is it possible to add a new option for this?

**Comment by AlexDM0** [comment]
Hi,

You could change the css pointer-events of the custom time to do this. I don't believe there is an options for this.

https://developer.mozilla.org/en/docs/Web/CSS/pointer-events

Regards,

Alex

**Comment by ahmadsoe** [comment]
@AlexDM0 thanks, didn't know about pointer-events before.
