### ISSUE TITLE
Selected Icon Node

### ISSUE THREAD

**Issue by hazelGranger** [almende/vis#1043]
Well, the selected icon node is overstroke (its font-weight becomes large) which result thst some hollow icons are not obvious......
Hope this can be controlled outside...

**Comment by AlexDM0** [comment]
Hi,

Icons have the text below them? I'm not sure what you mean. You cannot disable the bold font at the moment. 

Regards

**Comment by AlexDM0** [comment]
Hi,

I've just added the labelHighlightBold option to nodes and edges on develop. This will be included in the next release.

Cheers
