### ISSUE TITLE
AddEdgeMode does not work with navigation buttons

### ISSUE THREAD

**Issue by sachin-samel** [almende/vis#1044]
Hi,

Can we control the zooming operations from the HTML buttons?

Does vis have methods to control zooming externally?

Thanks

**Comment by AlexDM0** [comment]
Hi,

I think you're looking for the methods moveTo and fit. 

As for the controlling the buttons, you can hide some of them with CSS but that's it. What do you want to control?

Regards

**Comment by sachin-samel** [comment]
Hi 

I want to have zoom in, zoom out and reset buttons in html.

On click on those buttons I want to achieve the respected functionality.

Thanks

**Comment by AlexDM0** [comment]
Like so:
http://visjs.org/examples/network/other/navigation.html

**Comment by sachin-samel** [comment]
Thanks Alex.

I tried with options
interaction:{
			navigationButtons: true
		}

I am adding the nodes dynamically by using dataSet.

The problem I am facing is that, once I clicked on "+" button (zoom in), it starts zooming without any control. Same happens with any of the control buttons. Also, the action on buttons works only once.

Please see the js bin example
http://jsbin.com/xebujicuzo/edit?html,output

Regards

**Comment by AlexDM0** [comment]
I see, the addEdgeMode does not like the navigation buttons.. I'll look into this. 

Regards

**Comment by AlexDM0** [comment]
This has been fixed on develop now.

Regards,

Alex

**Comment by sachin-samel** [comment]
Thanks Alex.

One more question. I have used moveTo method to move the viewport, so that nodes will get placed from top, instead of from the center.

When i clicked on Reset button, it moves viewport to center of the canvas, instead of what we have set using moveTo

Regards

**Comment by AlexDM0** [comment]
Hi,

The moveTo method moves the camera, like you can by dragging the view and zooming. 

The fit method fits everything to the view. You'll have to make your own button that resets the view using moveTo, you cannot change the center point of fit. 

Regards
