### ISSUE TITLE
Connected Edges Look and feel

### ISSUE THREAD

**Issue by mmcsivakumar** [almende/vis#1047]
Hi,

I need to use VisJS to be draw like attached visual. Is that possible to bring the same look and feel of edges.

![mock-img](https://cloud.githubusercontent.com/assets/11782502/8448590/0dac821c-1fe7-11e5-8665-c5dff4a07e72.png)

**Comment by AlexDM0** [comment]
Hi,

Those are cubic Bézier curves whereas the smooth curves in vis are quadratic Bézier curves. This means it is not possible to get these exact curves at the moment unless you're willing to extend vis and add them. 

We might add them in the future but I cannot promise anything at this point. 

Regards

**Comment by mmcsivakumar** [comment]
Thanks for the update.

**Comment by mmcsivakumar** [comment]
can it be possible to add it to your roadmap in future releases?

**Comment by AlexDM0** [comment]
I can't promise that this will happen so at the moment, no. 

Regards

**Comment by AlexDM0** [comment]
Hi,

I've added these edges, they'll be released either today or next week.

Regards

**Comment by mmcsivakumar** [comment]
Thank you very much Alex.

BYW, one clarification, Will the gap between the nodes configurable?

![image](https://cloud.githubusercontent.com/assets/11782502/8898851/bcb55128-3449-11e5-9aab-127ea92e162a.png)

**Comment by AlexDM0** [comment]
Hi,

Yes. The distance between levels can be set in the layout setting, the distance between nodes on the same level is determined by the physics which can also be customised. 

Regards

**Comment by mmcsivakumar** [comment]
Thanks for the update Alex.
