### ISSUE TITLE
Group didnt clear items from subgroups

### ISSUE THREAD

**Issue by ChenMachluf** [almende/vis#1048]
I have application that add and remove data dynamically from the timeline.
After profiling i discover that the i have dom nodes leak , that was held by RangeItem.
The RangeItem was held  by subgroups member in Group.

In the  add method in Group, if the item have a subgroup it add it to the subgroups member.
But in the remove method it just remove it from the items and visibleItems members and there is a todo there of "// TODO: also remove from ordered items?"

```
Group.prototype.add = function(item) {
  this.items[item.id] = item;
  item.setParent(this);

  // add to
  if (item.data.subgroup !== undefined) {
    if (this.subgroups[item.data.subgroup] === undefined) {
      this.subgroups[item.data.subgroup] = {height:0, visible: false, index:this.subgroupIndex, items: []};
      this.subgroupIndex++;
    }
    this.subgroups[item.data.subgroup].items.push(item);
  }
  this.orderSubgroups();

  if (this.visibleItems.indexOf(item) == -1) {
    var range = this.itemSet.body.range; // TODO: not nice accessing the range like this
    this._checkIfVisible(item, this.visibleItems, range);
  }
};
```

```
Group.prototype.remove = function(item) {
  delete this.items[item.id];
  item.setParent(null);

  // remove from visible items
  var index = this.visibleItems.indexOf(item);
  if (index != -1) this.visibleItems.splice(index, 1);

  // TODO: also remove from ordered items?
};
```

I change the remove method locally to this one and the memory & dom leak solved:

```
Group.prototype.remove = function(item) {
  delete this.items[item.id];
  item.setParent(null);

  // remove from visible items
  var index = this.visibleItems.indexOf(item);
  if (index != -1) this.visibleItems.splice(index, 1);

  if (item.data.subgroup !=== undefined) {
    var subgroup = this.subgroups[item.data.subgroup];
    if (subgroup) {
        var itemIndex = subgroup.items.indexOf(item);
        subgroup.items.splice(itemIndex,1);
       }
  }

};
```

**Comment by AlexDM0** [comment]
Hi,

Thanks for finding this! If you'd like to contribute, you could make a pull request for this? We happily accept pull requests to the develop branch. 

If not I'll see if I find time to fix this before the next release (planned Friday). 

Regards,

Alex

**Comment by AlexDM0** [comment]
Thanks for the pull req! I'll include it in the release Friday.

Cheers

**Comment by AlexDM0** [comment]
Added in release v4.4.0
