### ISSUE TITLE
addItem method for Timeline

### ISSUE THREAD

**Issue by jthrilly** [almende/vis#105]
Hi. I'm looking for the best way to programmatically add events to the timeline. I was hoping to find something simple like an `addItem` method, so I could do (for example) `timeline.addItem({properties});` in my application. Unfortunately this doesn't seem to be included. Do you have plans for this functionality? If not, is there a simple way I can achieve it?

**Comment by daattali** [comment]
I came here to also ask for a "addItem()" method.  It seems very bizarre to not have a clear intuitive way to programmatically add an item.  I realized that I could do so by accessing the underlying data, but is there any reason not to expose a "addItem()" API that would simply do that for us?  It would be a lot more clear and intuitive.  And until such a function is implemented, it'd be very useful to add an example to the documentation on how to add an item via the data.

Amazing widget nonetheless!!!
