### ISSUE TITLE
Extra Edges when clustering

### ISSUE THREAD

**Issue by chetank88** [almende/vis#1050]
When forming a cluster in the network module extra edges are being formed.
In the given example at the website for clustering by zoom also this is happening.
The image below shows extra edge from node 7 and Cluster 3
![image](https://cloud.githubusercontent.com/assets/5725063/8456116/e89d482c-2026-11e5-86a6-4afb1ee7a831.png).

Is this a bug or it happens intentionally?

Is there a way to fix this?

**Comment by AlexDM0** [comment]
Hi,

It is intentional when there are multiple edges from a node to any node in the cluster. In this case however, it should not happen as seven only has 2 connections. 

I thought I fixed this a while back but apparently it's broken again. 

Thanks for letting me know, hopefully I can fix it this Friday before the release. 

Regards,

Alex

**Comment by chetank88** [comment]
Hi,
Thanks for the replay.
Hoping for a fix soon.

Regards,
Chetan

**Comment by AbhishekSen** [comment]
Extra edge issue:
![image](https://cloud.githubusercontent.com/assets/5207189/8475365/2e5fcfc0-20d5-11e5-83bc-d33a484542e4.png)
This is my initial graph. My logic is on "doubleClicking" 3. 3-4 should be clustered as in:
![image](https://cloud.githubusercontent.com/assets/5207189/8475413/6d93a96e-20d5-11e5-801e-17bb39a75898.png)
Now I'm spliting it again by a single click on 3 as in:
![image](https://cloud.githubusercontent.com/assets/5207189/8475432/957ec35a-20d5-11e5-9b81-eec98f87f284.png)
But when My clustering again it is showing an extra third edge between node 1 and sys1, and between sys1 and node 6.
![image](https://cloud.githubusercontent.com/assets/5207189/8475468/c62a6b08-20d5-11e5-919a-48b47bbdba7e.png)
node id of sys1 is h_3.1. It shows extra "clusterEdges" while printing network.getConnectedEdges("h_3.1")
![sena deshaw com_20150702_155040962](https://cloud.githubusercontent.com/assets/5207189/8475484/e1952856-20d5-11e5-9b50-660edbc40d12.png)

Also is there a support for showing only one edge out of cluster to a particular node ?

**Comment by AlexDM0** [comment]
Hi,

All the edges that should go into the cluster will be drawn, this cannot be changed at the moment. The extra edges is a bug though, I'll see if I can fix it tomorrow.

Regards,

Alex

**Comment by AlexDM0** [comment]
Added in release v4.4.0

**Comment by chetank88** [comment]
Thanks for the fix :+1:

**Comment by AlexDM0** [comment]
You're welcome :) thank you all for reporting! These things are hard to find for us! So many cases :)

Have fun using vis!
