### ISSUE TITLE
To get Time and Date On Click Of Time Axis in Vis.timeLine

### ISSUE THREAD

**Issue by DivyashreeMS** [almende/vis#1051]
Hi Alex,

Is there any API readily available to get the time and date on clicking on the time in x- axis as shown in the sceenshot.
As for now I am using the following mentioned code(Event) to get the time which is causing me a lot of problem. 

window.onclick = function(e) {
var event = e || window.event;
		var target = event.target || event.srcElement;
		var time = target.innerHTML;
}

I tried finding the API for this in VIS document but could not find one which meets my requirement. So Please suggest if there is any API which meet my requirement or a better way of doing it.
For Example: If i click on 11:40 the API should get me the time along with Date, like 11:40 1st Jul 2015.

![onclickoftimeevent](https://cloud.githubusercontent.com/assets/10521928/8460758/4f31804e-1ff5-11e5-9437-001587db9fe6.jpg)

Thanks & Regards
Divya

**Comment by AlexDM0** [comment]
Hi,

Isnt the event from click that you can put into this method 
http://visjs.org/docs/timeline/#getEventProperties

Exactly what you need? It gives the time and all other things an event could provide, even the things you do on the window click. 

Regards

**Comment by DivyashreeMS** [comment]
Thank you Alex,

the method getEventProperties solved the purpose.

Thanks
Divya
