### ISSUE TITLE
Fonts not displaying properly.

### ISSUE THREAD

**Issue by irumgodil** [almende/vis#1053]
Hi,

I am finding that the font for my chart is not rendering exactly as I want it. In some cases it is too big, and sometimes it becomes very vague too. 

Here are my options and I change this based on the total # of nodes - Note, I am using a 'package font-lato'. Is there anything else I can do so that it automatically decides the font size based on the layout and never overlays one text on top of another?

     this.options = {
        nodes: {
            shape: 'dot',
            scaling: {
                label: {
                    min:minFont_largeGroup,
                    max:maxFont_largeGroup
                },
            },
            font: {
                face: 'Lato',
            },

        },

        edges: {
            smooth: {
                enabled: true,
                type: "dynamic",
                //   roundness: 0.5
            },
        },

        interaction: {

            multiselect: false,
            navigationButtons: true,
            selectable: true,
            selectConnectedEdges: true,
            tooltipDelay: 100,
            zoomView: true
        },
        physics: {
            solver: 'repulsion',
            stabilization: {
                enabled: true,
                iterations: 50, // maximum number of iteration to stabilize
                updateInterval: 2,
                onlyDynamicEdges: false,
                fit: true
            }
        }
    };

minFont_smallGroup = 10;
maxFont_smallGroup = 15;

minFont_largeGroup = 15;
maxFont_largeGroup = 20;
  
    if (nodeLength <= 25) {        
        this.options.nodes.scaling.label.min = minFont_smallGroup;
        this.options.nodes.scaling.label.max = maxFont_smallGroup;
        console.log("font small");
    }
    else {
        this.options.nodes.scaling.label.min = minFont_largeGroup;
        this.options.nodes.scaling.label.max =maxFont_largeGroup;
        console.log("font large");
    }

    g.stopSimulation = true;
    if (nodeLength < 500) {
        stabilizationFactor = 300;
    }
    
    g.network.setOptions(this.options);
    g.network.stabilize(stabilizationFactor);

**Comment by AlexDM0** [comment]
Hi,

There is no way to make sure the labels do not overlap. I'm not sure what you mean with:
>I am finding that the font for my chart is not rendering exactly as I want it. In some cases it is too big, and sometimes it becomes very vague too.

Could you show me using jsbin? Does this also occur when using a normal font?

Regards,

Alex

**Comment by irumgodil** [comment]
Yes, it happens with normal font too. My main issue is around the overlap - but looks like cannot avoid that. I will reopen the issue once I have a jsbin.
