### ISSUE TITLE
Edge 'to' and 'from' Label

### ISSUE THREAD

**Issue by ReignInChaos** [almende/vis#1054]
Adding 'to' and 'from' labels for edges allows users to add information regarding the connection between an edge and node.  A use case for this enhancement is displaying a computer network topology where the edge end labels are interface names.

**Comment by AlexDM0** [comment]
Hi,

How would you avoid text overlap?

Regards

**Comment by ReignInChaos** [comment]
Due to the information that can be displayed, overlap may be unavoidable.
Unless there is a way to accomplish it using physics. For example, one edge
end label may be GigabitEthernet0/1, or an abbreviated version. One
mechanism could be to scale these labels down comparatively to the main
edge label. This would considerably reduce the footprint of these labels.

Thoughts?

**Comment by AlexDM0** [comment]
That is not feasible computationally. It's not just the overlap of the node's labels and the edge's labels but also those with all other nodes and edges (with multiple labels). This becomes O((2N)!) for all labels. Unless your edges are very very long, this is only ever a messy solution. I'd argue you'd be better off embedding this information into edge colors as they can be a different color on either end using inherit:both.

I don't think this will be implemented as there are many more downsides than the added benefit.

Regards

**Comment by ReignInChaos** [comment]
I feel the benefits are actually quite substantial. Currently I use vis to
display computer network topologies ( sometimes upwards 300 nodes ). At
this point, I have used the main edge label to store the interface
information on either side which causing confusion. I was unaware that it
would have been that computationally hard. Although it may have have been
messy to display with overlap, the information doesn't lend itself to edge
colors. For instance a network of 300 network devices may have around 800
unique interface names. I am open to other suggestions on implementation if
available.

**Comment by AlexDM0** [comment]
I would personally go for a custom mouse over popup information div when moving over an edge... messy networks are horrible to work with. For all larger networks I have I dont show most of the labels (using scaling of labels) and go with tooltips.

If you want to build it yourself, you'll have to look into the edge classes. The drawLabel in edge (in modules/components) draws the label. You'll have to change the setOptions to accept your new options.

Good luck!
