### ISSUE TITLE
Edges stuck after clustering/declustering

### ISSUE THREAD

**Issue by seb-at-nzrs** [almende/vis#1055]
Hi:

I'm working on a visualization where you can cluster/uncluster the nodes in a network. The network starts with no clustering, if a node is clicked it will cluster all the nodes that belong to the same group. If you click in a cluster, it will open the cluster.

The bug is the creation of an edge that connects a cluster with nothing. if the cluster is opened, the edge dissapears. If click back a node of a cluster, it will appear again.

There is a working version here http://jsfiddle.net/w8Lqqg1b/11/

Steps to reproduce:
1. Press button "Cluster nodes by AS"
2. Click on any of the clusters, it will open up
3. Click on any of the nodes that came from the cluster, it will cluster back leaving a phantom node and corresponding edge.
4. Repeat steps 2 and 3 for more fun.

BTW, this is a great tool. I was using something else previously for the sample problem, and with visjs is far more simple and more powerful.

**Comment by AlexDM0** [comment]
Hi, 

Thanks for the jsfiddle! I think this is the same issue as #1050 though? You're getting phantom edges, not phantom nodes right?

Regards

**Comment by AlexDM0** [comment]
Hi,

Sorry, I just had the chance to view the fiddle. I'll try to solve this tomorrow before the release.

Regards

**Comment by AlexDM0** [comment]
Hi,

I just tested your code against the vis.js file on the develop branch and it seems to be fixed! I'm not sure why exactly (there have been a lot of bug fixes on develop) but it looks like everything is working now. It's likely the cleaning of support nodes in this case.

We will release a new version today that will contain all these fixes.

Regards,

Alex

**Comment by dragonzone** [comment]
I have his same problem about a week ago. Initially, I thought it was my code but later, I was able to reproduce it every single time so I never reported it. I finally figure what the problem was. It was the cluster ID. Somehow, you CANNOT re-use the same cluster ID. To work around this, I had to randomly generate a unique new cluster ID everytime, which will work.

**Comment by AlexDM0** [comment]
Hi,

Thats probably a left over edge somewhere that is not being cleaned correctly, your solution is basically a memory leak as the edges will stack but will not be shown. The edge would see its "old" cluster and reconnect.

I'd be interested to hear if this is solved with the develop branch version for you as well.

Regards

**Comment by AlexDM0** [comment]
Added in release v4.4.0

**Comment by seb-at-nzrs** [comment]
Just to leave my gratitude for the quick fix!
