### ISSUE TITLE
Arrow head of edge to node with icon shape  hides inside the icon

### ISSUE THREAD

**Issue by DeviNagaraj** [almende/vis#1056]
Hi,

While creating a network with shape as icon arrow head goes inside the icon because of  icon's tranparency(I think).So arrow head is not visible in some times.Please give me a suggestion to overcome this issue.

**Comment by AlexDM0** [comment]
Hi,

This issue has is a duplicate of #1039. It has been fixed on develop and will be released tomorrow. 

Regards

**Comment by DeviNagaraj** [comment]
Hi

Ok thanks
