### ISSUE TITLE
styling the left axis.

### ISSUE THREAD

**Issue by bartwitt** [almende/vis#1057]
I use "height: 45px;" on vis-inner in the left axis to make sure all the rows in the timeline have a minimum height. As long as the rows in the timeline actually have this height, everything in the label looks great. However, as soon as the content of the rows grows (with more items in the bar at the same time) there is no way to make the label responsive since the 45px height is already set. 

I was wondering if there is any solution for this, maybe using one of the options I missed? I'm thinking of changing the template for the left axis, or maybe setting the minimum row height using options instead of using a child div for this?

**Comment by josdejong** [comment]
Did you try `min-height: 45px;` ?

**Comment by yotamberk** [comment]
@bartwitt still relevant?
