### ISSUE TITLE
Scroll bar in the timeline

### ISSUE THREAD

**Issue by almusawi** [almende/vis#1060]
Hi,
First I want to thanks you for this amazing work.

In my timeline, I made a fixed hieght so the timeline will not become big. but in this case some of the items will be up or down, hidden in the timeline window.
my question is, would it be possible to add scroll bar on the right side of the timeline to show that they can see the items by draging up and down?

Thanks in advance

**Comment by AlexDM0** [comment]
Hi,

Glad you like it :).

At the moment it is not possible to display a scrollbar for vertical scrolling. There is a longstanding feature request for this (#273) but we haven't gotten around implementing a custom scrollbar yet. 

Regards,

Alex

**Comment by almusawi** [comment]
Hi again,

Thanks for your answer :)

Best regards,
Mohammed

**Comment by micmeemac** [comment]
Thank you, Alex, for considering this feature for future development. 

The drag gesture feels a bit tedious in the desktop context and a scroll would be comparatively heavenly. 

Do you have any pointers for if I want to implement this myself? Obviously I'd want to be able to configure the pan to happen on either mouse scroll or drag depending on context.

**Comment by josdejong** [comment]
@micmeemac the vertical scroll position is handled via the `Core.props.scrollTop` property and some helper functions `Core._setScrollTop`, `Core._getScrollTop`, `Core._updateScrollTop`, at the bottom of Core.js: https://github.com/almende/vis/blob/master/lib/timeline/Core.js

**Comment by micmeemac** [comment]
Cool :) Thank you

**Comment by daniel-pfeiffer** [comment]
@micmeemac very glad you're picking this topic up!  When panning up and down I find it confusing/frustrating that groups scroll along.  Ideally I would see the scrolling within each group, while all groups are always visible.
This might not be ideal for everybody, so there might be a choice to scroll either the whole body or each group that doesn't fit.

**Comment by daniel-pfeiffer** [comment]
Oops, outlined my solution in #273, which is still the one listed in Feature requests.
