### ISSUE TITLE
Get  SecurityError: The operation is insecure. when trying to save network canvas that has icon reference to another server

### ISSUE THREAD

**Issue by dragonzone** [almende/vis#1061]
This is based on your network image example, http://visjs.org/examples/network/nodeStyles/images.html, but i tweaked it here. Instead of the Internet icon, I change it to a 'tree' icon, which is on another server. The problem arises when I try to save the network canvas as an image, the browser will not let me do it since it's cross-domain violation when you click the 'Create Image' in code below. This also happen for canvas.getImageData() and cavas.putImageData(). Here is the tweaked code:
```
<!doctype html>
<html>
<head>
  <title>Network | Images</title>

  <style type="text/css">
    #mynetwork {
      width: 600px;
      height: 600px;
      border: 1px solid lightgray;
    }
  </style>

  <script type="text/javascript" src="../../../dist/vis.js"></script>
  <link href="../../../dist/vis.css" rel="stylesheet" type="text/css" />

  <script type="text/javascript">
    var nodes = null;
    var edges = null;
    var network = null;

    var DIR = '../img/refresh-cl/';
    var EDGE_LENGTH_MAIN = 150;
    var EDGE_LENGTH_SUB = 50;

    // Called when the Visualization API is loaded.
    function draw() {
      // Create a data table with nodes.
      nodes = [];

      // Create a data table with links.
      edges = [];

      nodes.push({id: 1, label: 'Main', image: DIR + 'Network-Pipe-icon.png', shape: 'image'});
      nodes.push({id: 2, label: 'Office', image: DIR + 'Network-Pipe-icon.png', shape: 'image'});
      nodes.push({id: 3, label: 'Wireless', image: DIR + 'Network-Pipe-icon.png', shape: 'image'});
      edges.push({from: 1, to: 2, length: EDGE_LENGTH_MAIN});
      edges.push({from: 1, to: 3, length: EDGE_LENGTH_MAIN});

      for (var i = 4; i <= 7; i++) {
        nodes.push({id: i, label: 'Computer', image: DIR + 'Hardware-My-Computer-3-icon.png', shape: 'image'});
        edges.push({from: 2, to: i, length: EDGE_LENGTH_SUB});
      }

      nodes.push({id: 101, label: 'Printer', image: DIR + 'Hardware-Printer-Blue-icon.png', shape: 'image'});
      edges.push({from: 2, to: 101, length: EDGE_LENGTH_SUB});

      nodes.push({id: 102, label: 'Laptop', image: DIR + 'Hardware-Laptop-1-icon.png', shape: 'image'});
      edges.push({from: 3, to: 102, length: EDGE_LENGTH_SUB});

      nodes.push({id: 103, label: 'network drive', image: DIR + 'Network-Drive-icon.png', shape: 'image'});
      edges.push({from: 1, to: 103, length: EDGE_LENGTH_SUB});

      nodes.push({id: 104, label: 'Internet', image: 'http://www.veryicon.com/icon/png/System/Farm%20Fresh/tree.png', shape: 'image'});
      edges.push({from: 1, to: 104, length: EDGE_LENGTH_SUB});

      for (var i = 200; i <= 201; i++ ) {
        nodes.push({id: i, label: 'Smartphone', image: DIR + 'Hardware-My-PDA-02-icon.png', shape: 'image'});
        edges.push({from: 3, to: i, length: EDGE_LENGTH_SUB});
      }

      // create a network
      var container = document.getElementById('mynetwork');
      var data = {
        nodes: nodes,
        edges: edges
      };
      var options = {};
      network = new vis.Network(container, data, options);

    }

  function createImage() {
      var canvas = network.canvas.frame.canvas;
	  var ctx = canvas.getContext('2d');
	  var img = canvas.toDataURL("image/png");
	  window.open(img, '_blank');
  }
  </script>
  <script src="../../googleAnalytics.js"></script>

<body onload="draw()">
<input type="button" onclick="createImage()" value="Create Image"> <br />

<p>
  Display nodes as images.
</p>
<div id="mynetwork"></div>

</body>
</html>
```
How did you overcome this since I see in vis.js that you also use getImageDate() and putImageData()?

**Comment by AlexDM0** [comment]
on the.... ?

**Comment by dragonzone** [comment]
Sorry, cut & paste problem. :)

**Comment by AlexDM0** [comment]
Sorry, I'm not sure how this relates to vis. 

http://stackoverflow.com/questions/22710627/tainted-canvases-may-not-be-exported

Regards

**Comment by dragonzone** [comment]
Sorry, typo again, it's canvas.getImageData(), not getImageDate(). But how are you able to load the icon into the canvas and even drag that particular icon around? Isn't when you do a mouse drag start, you have to getImageData(), to save it's state, and when while dragging, you have to putImageData(), to redraw the image back? Since the canvas contains an icon from another domain, you will get the same error as I do, but vis.js doesn't seems to have that problem.

**Comment by AlexDM0** [comment]
Are referring to the icon type nodes? We do not use getImageData anywhere except for the color picker which does not use icons. 

The icon type nodes are actual font glyphs, not images. The image type nodes are just drawn on the canvas with ctx.drawImage.

On dragging, we translate and/or scale the canvas context and redrawing the image using drawImage again.

We never use the methods you are referring to.

Sorry to disappoint, 

Cheers

**Comment by cdbierl** [comment]
I think this comes down to how visjs fetches the cross-domain icon/images. If visjs does not set the crossOrigin property for the Image, the canvas will become tainted on draw and we will not be able to export its data.

For reference: https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image
