### ISSUE TITLE
this.getNodes() instead this.body.nodes And this.getNodeById(node_id) methods.

### ISSUE THREAD

**Issue by Fi1osof** [almende/vis#1062]
Hi! 
Thanks for cool lib! Really!

If possible, add these methods. Thanks!

**Comment by AlexDM0** [comment]
Hi,

The node objects in this.body.nodes are internal objects and those are not ment for use by the user. 

Why do you want those?

Regards

**Comment by Fi1osof** [comment]
this.clustering.clusterByConnection uses those.
```javascript
var node = this.body.nodes[nodeId];
options = this._checkOptions(options, node);
        if (options.clusterNodeProperties.x === undefined) {
          options.clusterNodeProperties.x = node.x;
        }```

i want to check nodes some properties before create cluster.

```javascript
        var essence_id = params.nodes[0];
        var node = this.body.nodes[essence_id];
....
        var level = node.options.level || 0;
        var title = node.getTitle() || node.options.label;
...
        network.clusterByConnection(essence_id, {
            clusterNodeProperties:{
                id: "cluster-" + level + '-' + id,
                label: title,
                level: level,
                title: title,
                shape: 'database',
                color:{
                    background: '#d6b8ea'
                }
            }
        });
```

**Comment by AlexDM0** [comment]
Internally yes, but all the relevant properties are copied and provided to the callbacks. 

I will not open up the internals through API. 

Regards

**Comment by Fi1osof** [comment]
Please tell me how I should do it.
Thanks!

**Comment by AlexDM0** [comment]
It would really help if you told me what exactly you want to do :)

The cluster options can be given a joinCondition
http://visjs.org/docs/network/#optionsObject

This will give you function arguments of all nodes that will be clustered and you can decide if you want to include them or not in the cluster. 

If you want to check things beforehand it's easy, you know what you want to check or get an ID from the events (click etc). Use that ID to look up the specific node you yourself put into the network and look at its options for what you are looking for. 

Regards

**Comment by Fi1osof** [comment]
Oh, i think processProperties() - it`s all i need. Thanks! :)
