### ISSUE TITLE
Selecting a node and immediately dragging it does not make the node shape grow to fit the bigger text.

### ISSUE THREAD

**Issue by ojotoxy** [almende/vis#1063]
If clicking and dragging on a non-selected node, the node will become selected, and the font size increases, but the shape of the node does not get bigger to accommodate the larger text. Clicking on a node without dragging does not show the same problem.

Can be experienced here: http://visjs.org/examples/network/nodeStyles/shapes.html
Can be seen here: https://www.youtube.com/watch?v=c_Mykkjo_0k&feature=em-upload_owner

**Comment by AlexDM0** [comment]
Hi,

Thanks for the clear report! Interesting case you have here, I never noticed. 

I'll send a fix to develop today. 

Regards,

Alex

**Comment by AlexDM0** [comment]
Fix has been pushed to develop.

Cheers

**Comment by AlexDM0** [comment]
released in 4.5
