### ISSUE TITLE
Has the way to redraw a network changed in 4.x?

### ISSUE THREAD

**Issue by edallen** [almende/vis#1065]
In 3.6 I had a Redraw button that called DG.network.redraw() where DG was my namespace, and this would redraw the network if it got screwed up by window resizing. This seems to be the one thing still broken in my update to using 4.4.

Should I be calling redraw() differently now or doing something else?

**Comment by AlexDM0** [comment]
Hi,

V4 automatically listens to window resize events. It should just work really :/. 

Can you post some code for this?

Regards

**Comment by AlexDM0** [comment]
is this still an issue?
