### ISSUE TITLE
How to change the scale and step parameters for snap function?

### ISSUE THREAD

**Issue by paolovalladolid** [almende/vis#1066]
How do I change the scale and step parameters for the Timeline snap function without having to rewrite the whole function?

**Comment by josdejong** [comment]
There is a static function `vis.timeline.TimeStep.snap(date, scale, step)` which you can use ([see code](https://github.com/almende/vis/blob/master/lib/timeline/TimeStep.js#L321-L429))

**Comment by paolovalladolid** [comment]
Thanks.  I tried calling the static function in this manner, but then I was no longer able to drag and drop timeline items.  Am I calling it wrong or is there some other bug in my Javascript code?

```javascript
var options = {
    snap: function (date, scale, step) {
      var clone = new Date(date.valueOf());
      scale = 'minute';
      step = 15;
      
      return TimeStep.snap(clone, scale, step);
    }
  }
```
On the other hand, when I copied the TimeStep snap code and modified it so I could snap items to 15-minute intervals, the drag and drop behaved as expected:

```javascript
var options = {
    snap: function (date, scale, step) {

      var clone = new Date(date.valueOf());
      scale = 'minute';
      step = 15;

      if (scale == 'hour') {
        switch (step) {
          case 4:
            clone.setMinutes(Math.round(clone.getMinutes() / 60) * 60);
            break;
          default:
            clone.setMinutes(Math.round(clone.getMinutes() / 30) * 30);
            break;
        }
        clone.setSeconds(0);
        clone.setMilliseconds(0);
      } else if (scale == 'minute') {
        switch (step) {
          case 15:
            clone.setMinutes(Math.round(clone.getMinutes() / 15) * 15);
            break;
          case 10:
            clone.setMinutes(Math.round(clone.getMinutes() / 5) * 5);
            clone.setSeconds(0);
            break;
          case 5:
            clone.setSeconds(Math.round(clone.getSeconds() / 60) * 60);
            break;
          default:
            clone.setSeconds(Math.round(clone.getSeconds() / 30) * 30);
            break;
        }
        clone.setMilliseconds(0);
      }
      return clone;
    }
  };
```

**Comment by josdejong** [comment]
I tried your snap function (the first in your last comment), seems to work just fine. Sounds weird if that would influence being able to drag the items. Can you make a simple jsbin demonstrating the issue?

**Comment by paolovalladolid** [comment]
I might be able to do it at a later date. I work with the author of Timeline For Vaadin and was trying out possible modifications to include snapping.  TFV reuses the Vis JS Timeline library within the Vaadin web framework.  I'll be showing our team what I was able to do today, and then some decisions will be made about what direction to go.

Thanks for your help!

**Comment by obattalov** [comment]
maybe "return **vis.timeline.**TimeStep.snap(clone, scale, step);"

**Comment by mojoaxel** [comment]
@paolovallafolid Can we close this issue?

**Comment by paolovalladolid** [comment]
Sorry for the late response.  Yes the issue can be closed.

**Comment by MarkPajak** [comment]
I have found that when the snap function is enabled, it effects dropping events onto the timeline - it fails to read the snapped date from the drop event

**Comment by mojoaxel** [comment]
> I have found that when the snap function is enabled, it effects dropping events onto the timeline - it fails to read the snapped date from the drop event

@MarkPajak If you think that is a bug please feel free to create a new issue.
