### ISSUE TITLE
Is there a proper way to use vis with nodejs/iojs?

### ISSUE THREAD

**Issue by dumpsters** [almende/vis#1067]
I've tried with jsdom and following a tutorial for d3 but using vis but it will give me errors, any way at all to use it?

**Comment by AlexDM0** [comment]
Hi,

PhantomJS seems to go a good job for this. 

Regards,

Alex

**Comment by dumpsters** [comment]
I'll look into it, thanks. Since I already opened this issue, I have another question. Is there a way to completely freeze the graph once it's rendered? so I can just zoom in/out but not move things around etc? Even if I don't move anything at all it will never stop moving, when I zoom out I can see it very slowly moving and with something like 1k nodes and 3k+ edges it becomes really laggy.

**Comment by AlexDM0** [comment]
Hi,

You can use setOptions({physics:false}). Alternatively call stopSimulation but they'll continue moving once you drag one around. 

Take a look at the physics options and the methods in the docs. 

Regards,

Alex

**Comment by dumpsters** [comment]
network.setOptions({physics:false}); returns undefined.
network.stopSimulation() makes it less laggy but when I zoom it it will freeze for a couple seconds and then do the zoom in.

**Comment by AlexDM0** [comment]
yes it returns nothing. 

Stop simulation stops the simulation, I cant do anything with the information you give me.

Do you have an example that shows this behaviour?

Regards

**Comment by dumpsters** [comment]
Do you have an e-mail where can send it to you? it has sensitive data

**Comment by AlexDM0** [comment]
I'd recommend you anonimize the data and post it on here, maybe others can be helped by the process as well.

Regards

**Comment by dumpsters** [comment]
I'm afraid there's no way to do that without re-doing the entire thing

**Comment by AlexDM0** [comment]
you can just export the data you're showing, replace all labels with random strings and send me the data and the options you used.

**Comment by dumpsters** [comment]
Forget it then, I don't have the knowledge to pull this off
