### ISSUE TITLE
[Network] How to prevent event bubbled for click event?

### ISSUE THREAD

**Issue by rwu823** [almende/vis#1068]
Please look the example:
http://jsfiddle.net/xueenocq/1

`event.stopPropagation()` doesn't work for `click`. Seem current network bind event with `tap`?

**Comment by AlexDM0** [comment]
Hi,

There is a srcEvent in the hammer event, which is the original DOM event. In this case it is the mouseup event. I'm not sure if you can stop the click event from bubbling.. 

You could probably put a check in your document click function?

Regards

**Comment by AlexDM0** [comment]
@josdejong  what do you think?

**Comment by josdejong** [comment]
The `event` passed by the click event of Network is indeed not the original DOM event but a hammer.js event (or even more precise: an event of the `propagating-hammerjs` extension on top of hammer.js. The `stopPropatation()` on this synthetic event only work for listeners created via the hamme.js extension, not for "regular" DOM events.

Try to replace:

```js
$(document).on('click', function(e){
    alert('document clicks')
})
```

with:

```js
new vis.Hammer(document.body).on('tap', function (e) {
  alert('tap');
});
```
