### ISSUE TITLE
Timeline - group content is being appended inside setData () if it's an Element

### ISSUE THREAD

**Issue by AmadejSI** [almende/vis#1071]
Hi!

I'm not sure if what I'll describe is a bug, so I'll talk about it as my own problem of not understanding the design decision. It seems that the content of a group in the timeline component is always append, when a group is updated via the DataSet that holds the group objects, and if the content is Element.

This is the code block from the vis Timeline I am talking about.
```
Group.prototype.setData = function (data) {
  // update contents
  var content = data && data.content;
  if (content instanceof Element) {
    this.dom.inner.appendChild(content);
  } else if (content !== undefined && content !== null) {
    this.dom.inner.innerHTML = content;
  } else {
    this.dom.inner.innerHTML = this.groupId || ''; // groupId can be null
  }
```

Is this by design? Because it's impossible to have a DataSet as the source of a group and use the update() method on a DataSet to update group content like that (two updates are a workaround, setting the first to set content to ''). Or is it simply a bug, since from what I understand, you do call element.innerHTML = '' before updating an item content. :)

**Comment by josdejong** [comment]
Thanks, this was simply a bug. Should be fixed on the develop branch new (dist files are not up to date though).
