### ISSUE TITLE
Timeline does not work with dojo 

### ISSUE THREAD

**Issue by csakis** [almende/vis#1077]
I am trying to use timeline with dojo. I noticed that if I do
```
 <script src="../../dist/vis.js"></script>
 <script src="../../dist/dojo.js"></script>
```
Everything is fine. If I change the order 
```
  <script src="../../dist/dojo.js"></script>
  <script src="../../dist/vis.js"></script>
```
then unfortunately, I get this error
```
vis is not defined.
```
Unfortunately, I am trying to use the timeline in the context of XPages and dojo loads independently from me right at the top of the page. I am not sure how to fix this problem and why dojo breaks vis,js.

**Comment by josdejong** [comment]
Doesn't dojo use AMD modules? I guess you have to load vis.js using `require` or something like that.

**Comment by csakis** [comment]
Thanks. I solved the problem using Sven Hasselbach's solution
http://hasselba.ch/blog/?p=1216

I had to add this code to the top of my XPage
```
<xp:this.properties>
        <xp:parameter
            name="xsp.resources.aggregate"
            value="true" />
    </xp:this.properties>
  <xp:this.resources>
    <xp:headTag tagName="script">
      <xp:this.attributes>
        <xp:parameter name="type" value="text/javascript" />
        <xp:parameter name="src" value="bootstrap/js/vis-custom.js" />
      </xp:this.attributes>
    </xp:headTag>
  </xp:this.resources>
```

**Comment by josdejong** [comment]
Thanks for sharing your solution!

**Comment by YMA-MDL** [comment]
would this be a better solution : 
```
require([
    "../../dist/vis.js"
], function(vis) {
    console.log(vis);
});
```
