### ISSUE TITLE
How can I apply node scaling per group of nodes in a network? 

### ISSUE THREAD

**Issue by vikramkone** [almende/vis#1080]
Is this possible to do in a network graph using visjs library? If yes then please show me an example. From what I understand, scaling is for the entire network and can't be done per group basis.

**Comment by AlexDM0** [comment]
Hi,

Yes this is possible. As stated in the documentation:
http://visjs.org/docs/network/groups.html

```
You can add multiple groups containing styling information that applies to a certain subset of groups. All options described in the nodes module that make sense can be used here (you're not going to set the same id or x,y position for a group of nodes). 
```

What did you try so far?

Regards

**Comment by vikramkone** [comment]
Here is sample jsfiddle with my issue http://jsfiddle.net/4stg0poe/
AS you can see , scaling seems to apply only to one group (diamonds group) and not for the other 2 groups

**Comment by AlexDM0** [comment]
http://jsfiddle.net/2m47Lxco/3/ Scaling works for all groups except icons at the moment. Icons are not supported for scaling currently, this is on our todo list.

I'd recommend you refer back to the documentation on how the scaling is calculated. Your value distribution makes it look like only the big values scale, which is not the case really.

Regards

**Comment by vikramkone** [comment]
Hi Alex,
Understood for the icons. What I want is, the scaling to be done per group and not per network which is precisely my issue here. I understand that since the diamonds group has high values their scaling is discernible and the scaling of other groups whose values are less compared to diamonds group don't seem to scale (even though they are scaling but not distinguishable by naked eye).
So my request is that visjs should provide a way to apply scaling at per group basis in addition to the current method of per network. Thereby the other groups scale based on the values in that group only and not affected by other groups. I hope this ask is clear

**Comment by AlexDM0** [comment]
You realize that you can just supply any option that you supply for the nodes per group right? Just like the example, just put the scaling configuration into the groups you create.

http://jsfiddle.net/2m47Lxco/4/

**Comment by vikramkone** [comment]
Didn't realize I can apply scaling in a group. Cool :+1:

**Comment by vikramkone** [comment]
Actually, that didn't work..even when I apply scaling per group, the group with higher values appear to be scaling while other groups with lower values appear not to scale. Did I miss something?
http://jsfiddle.net/vikramkone/dgump2g9/

**Comment by AlexDM0** [comment]
I see, it seems like the totals are still shared. You can get around it by either applying your own scaling function with the totals corresponding the the group or adapting the min max to suit the offset.

It is not possible to supply an option so the totals are not shared over the entire network, if that was your question then I'm sorry, I misunderstood.

Regards,

Alex

**Comment by vikramkone** [comment]
Do you mind sharing an example of using custom scaling function that can take different total's based on group? I couldn't find an example of this one in the docs

**Comment by AlexDM0** [comment]
http://visjs.org/docs/network/nodes.html 

http://visjs.org/examples/network/data/scalingCustom.html

You see in the docs how the total is used, you can just precalculate the total of your groups and supply it in the functions.

Regards
