### ISSUE TITLE
Beer App example for the showcase

### ISSUE THREAD

**Issue by kellnerotem** [almende/vis#1086]
Hey.

I wrote this BEER app using vis.js. 

you may want to put it on the showcase...

http://www.beergraph.xyz/

Cheers,
Rotem Kellner

**Comment by AlexDM0** [comment]
Hi,

Looks nice, I'll see if I can put it on next week. 

Few pointers, I would give the leaf nodes a smaller fontsize so they don't overlap as much and be a bit more careful with the colors as the sour ale's edges are not that visible.

You can use the randomSeed to make sure the layout is the same every time it is opened.

What would you like as a description?

Regards

**Comment by kellnerotem** [comment]
Heya

Sure ill add what you mentioned.

Description:

"An application that shows the different styles of beers. Each beer style
with its own specifications, beers brands and beer family which it belongs
to.
Feel free to contribute your knowledge and build a better graph using the
forms"

Thanks,
Rotem

**Comment by kellnerotem** [comment]
Hey Alex,
I optimized the app to work on mobile, people want to use it mostly in bars
:)

so you can add that to the description above

Cheers,
Rotem

**Comment by aytech** [comment]
@kellnerotem: nice app :)
I wanted to check description of some beer types, the description appears if you click on the header of the the row (like "Aroma", "Flavour", etc.), but the whole left column is emptied if you click on the arrow image inside that header. Is it supposed to be like that?

**Comment by kellnerotem** [comment]
Hey!

It really was a bug,Thanks!
Caused by a bug in the core of Angular UI Mobile. I'll update them as they
should know about it.

Fixed it, arrows will be static.

Need any additional info?

Cheers,
Rotem

**Comment by aytech** [comment]
Nah, it's ok. Looks cool :)

**Comment by kellnerotem** [comment]
Thanks :)

**Comment by kellnerotem** [comment]
@AlexDM0

**Comment by AlexDM0** [comment]
Hi,

You could look into adding icons of glasses (maybe using the font awesome icons) or colouring the nodes according to hue of the beer?

On iPhone I don't know how to get out of the information panel that pops up when I touch a node. A swipe to the left as dismissal would be awesome.

I'd maybe go with a darker background, but then I just prefer our dark examples over our light ones :). 

If you know the positions of the nodes up front, I'd recommend you have them start there, thereby greatly reducing the loading times. Look into the storePositions method. 

Regards

**Comment by kellnerotem** [comment]
Hey, 
Regarding the first Idea of coloring the beers,

the leaf nodes are not beers, they are sub-styles.

Once you click on a sub-type you will be able to view examples of beers, on the right sidebar.
Due to this, I though keeping leaf colors matching the containing family would be more intuitive

**Comment by AlexDM0** [comment]
:) also fine, just an idea

**Comment by kellnerotem** [comment]
Hey,

Thanks for the tips!
Updated swipe to close the panels, both left and right.

This graph is dynamic, its supposed to be expanded by the community (using the forms).
If I use getPositions I can only set a static chunk of data for next time, but the data might be different.

for now, Im keeping the background as is because AngularMobile css's go along better with the lighter ones.

Cheers

**Comment by AlexDM0** [comment]
You could just store it when loaded, then when data has been changed, you only have to calculate the new positions. If anyone from the community has to wait it saves the time for the next one. 

Seems like a good deal to me :)

**Comment by kellnerotem** [comment]
Hi Alex,

Graph currently loads in 3-4 sec, good enough In my opinion.
But I do want to understand exactly what you meant, so fix me if i'm wrong.

1. after  'new vis.Network(container, data, options)' is called - use storePositions() to get .x.y properties.

2. update the dataset and send it back to server? (I currently do not save this, calculated only in client)

3. Now every new user who comes will get the positions object from server and do the following:
'new vis.Network(container, data, options)' and immediatly after that setPositions() in order to minimize loading time?

The data object in my DB is changed with my private api, not through client.
This means I will have to go over steps 1+2 for every add of content in my DB...

another interpretation I had is using storePos updating local cache, Did u mean that?
Thanks

**Comment by AlexDM0** [comment]
Hi,

On my phone it took longer (like 15 sec, iphone5) and I imagine it would be used in a bar? :)

You're partly right in the methodology:

1. You listen for the stabilized event (the one that clears your loading screen). At that point you call storePositions(). I assume you're using a dataset for the data. (make sure this part is done only once in the entire session! When the nodes are moved by the user they will stabilize again!)

2. You send the updated positions to the server, maybe check if the loading time was less than 2 seconds, if not, send to server.

3. Since a community can update this, I assume there's a database somewhere? If theres an update, keep the positions of the nodes you know then solve for the new node. If the check in 2 is surpassed, the server gets an update.

This way, you will only give a delay to one person in your community and his processing power will be appreciated by the rest :).

Since I don't know your data model, I'm not sure where you want to store anything.

Does this make it more clear? Basically, you ALWAYS do this. If someone, somewhere has to wait for a time longer than threshold, you update the positions.

Regards

**Comment by kellnerotem** [comment]
Excellent, Got it now.

Working on it...

**Comment by kellnerotem** [comment]
Hi again,

Done implementing, slightly better performance here, and there?

Instead of sending updates position updates when a timer threshold passes, I do it once the current number of positions I get from server is smaller than the current number of nodes I get.

When is the position computation costly?
My nodes dataset contains x+y axis data for all nodes, am I fine or does it still calculate everything?

Concrete Example: 
1. I have 95 nodes which all contain x+y data. 
2. Node I have 96 nodes and one misses x+y data.

What happens in the second example?

Thanks

**Comment by AlexDM0** [comment]
Hi,

I suggest you turn off stabilization and see for yourself, that really is the best way to see what happens. 

Regards

**Comment by AlexDM0** [comment]
By the way, on my phone, the loading bar flies out of the screen at 100%. End width not right?

**Comment by josdejong** [comment]
> By the way, on my phone, the loading bar flies out of the screen at 100%. End width not right?

Your iPhone 5 screen is just too small to be taken serious ;)

**Comment by kellnerotem** [comment]
Alex, 
I managed to take ur iPhone 5 seriously, somehow...

Bug fixed.

**Comment by AlexDM0** [comment]
All iPhone users everywhere will rejoice!

**Comment by AlexDM0** [comment]
Hi,

Sorry we've not put your app on the website yet. We hope to get around to it this week.

Regards

**Comment by kellnerotem** [comment]
:)

**Comment by AlexDM0** [comment]
Hi,

It's in:
http://visjs.org/showcase/index.html

I noticed there is one beer with the name something something D-sseldorf. That should be a u?

Regards

**Comment by kellnerotem** [comment]
Yup,

Probably a bad bad German character..
Data is collected from various sources....

Looks cool!

**Comment by sachaudh** [comment]
Nice work on the beer graph! I'm starting to get the hang of vis.js but was wondering how you were able to separate both groupings of nodes?

<img width="959" alt="screen shot 2015-12-11 at 12 53 37 am" src="https://cloud.githubusercontent.com/assets/4805485/11739636/c9bd28b4-9fa1-11e5-809d-24d608c360a3.png">

I want to do something similiar to this, where I have a group of nodes (not all are connected to each other/may be connected to other nodes from a different grouping) together in a certain space.

**Comment by AlexDM0** [comment]
Hi,

Even though I didn't make the beer graph I may be able to shed a little light on this. 

If you have unconnected groups the physics should automatically separate them! The physics use an inverted gravity model to repel nodes from one another. If you do not get this effect, maybe increase the repulsion?

If you post a jsbin with your problem we may be able to help. 

Regards

**Comment by sachaudh** [comment]
I don't have a jsbin for you yet, just thinking out loud. Lets say that for the image I posted above: I don't want any edges, and I want nodes with the same `group` number to be automatically pulled into the same region. I can see that the edges will automatically pull nodes that are connected to the same regions, and by adjusting the repulsion I can have it so interconnected groupings of nodes won't mix with other interconnected nodes. But, will the effect still occur when, for example, you have no edges?

**Comment by AlexDM0** [comment]
No it will not. 

You could make the edges invisible though. Just set the color to be rgba(0,0,0,0)

The nodes repel and the edges attract. Thats all we can do ;)

Regards

**Comment by sachaudh** [comment]
Ah yes I was thinking of using invisible edges to achieve the same effect. Thanks for your quick responses!

**Comment by The-Penultimate-Defenestrator** [comment]
Quick question, how exactly did you "optimize for mobile?" I'm having trouble getting vis.js to play nicely with iOS.
