### ISSUE TITLE
Changing layouts using network.setOptions has issues

### ISSUE THREAD

**Issue by dragonzone** [almende/vis#1087]
Based on your Network Example, Hierarchical Layout, There is a a weird bug if you dynamically change the layout. Go here to see the modified example:

http://jsbin.com/wupabe/edit?html,output

If you click on Up-Down, or Down-Up initially, it will work, but if you click on Left-Right or Right-Left, you will a straight line AND some missing nodes.

You example uses random nodes every time you click the button, therefore, never see this issue.

BTW, This happens in a few versions back

**Comment by AlexDM0** [comment]
Hi Dragon,

I'll see if I can fix this before the next release. I think it's because the items are fixed in one direction and then also become fixed in the other direction, causing overlap. 

We're aiming for a release this Friday. 

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi,

This has been fixed on develop. We'll be releasing tomorrow.

Regards,

Alex
