### ISSUE TITLE
Sometimes appears when doing meta tag refreshes: Permission denied to access property type

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#1088]
I cannot deterministically reproduce this, it happens extremely rarely in Firefox (only firefox!).

Because this error only occurs in connection with a `http-equiv="refresh"` that redirects to another page and because it's an permission error I am starting to believe this is a firefox bug...

In any case, here is a screenshot.

![selection_406](https://cloud.githubusercontent.com/assets/4307137/8660126/4f0e7d9c-29af-11e5-845e-ec0c484b7da6.png)

If you guys have no clue and don't want to investigate further, I can totally understand that.

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

That looks to be in the hammerjs we ship with vis isn't it?

Regards

**Comment by felixhayashi** [comment]
Hi @AlexDM0 

Yes, true. I'll close this issue then as it is not vis who seems to be causing this...

I stopped using http-equiv for refreshes and used javascript's `location.href` instead and the error seems gone... weird stuff.

-Felix
