### ISSUE TITLE
Evenly spaced items on timeline

### ISSUE THREAD

**Issue by pchaganti** [almende/vis#1089]
I have a timeline with items that are exactly 5 min apart. When I add them to the timeline, they overlap. I would like to display them evenly spaced on the timeline. Tried adjusting the time scale. Am I going about this the right way? Can anyone point me in the right direction?

thx!

**Comment by josdejong** [comment]
If you zoom too much out, items will overlap. If you don't want them to stack you can set the option `stack` to false. If you don't want them to overlap, you will just have to make sure you don't zoom in that much. You can limit zooming using options `zoomMin` and  `zoomMax`, [see docs](http://visjs.org/docs/timeline/) for more information.

**Comment by AlexDM0** [comment]
Alternatively you can use range items, those have absolute sizes. 

Regards

**Comment by pchaganti** [comment]
Ah, got it!

thanks
