### ISSUE TITLE
Focusing on specific node and highlighting it?

### ISSUE THREAD

**Issue by inctor** [almende/vis#1090]

**Comment by AlexDM0** [comment]
http://visjs.org/docs/network/

the methods are called focus and selectNodes

Please read the documentation for more information.

Regards,

Alex

**Comment by inctor** [comment]
Hey Alex,

Thanks for the fast response (and closing).

However, it doesn't do what i want it to. I want it to highlight it, change it's color or make it "bigger" or something, so it visually shows who the current user is.

I'm showing the user relations from a specific user's POV, and i want that one user to "stand out" from the others.

However i fixed that, by making the POV user a seperate group, and then styling that group on it's own, which makes it stand out nicely now! :)

[skaermbillede 2015-07-14 kl 11 32 55](https://cloud.githubusercontent.com/assets/1939469/8670307/21ad2912-2a1c-11e5-85d5-2d20a822178a.png)

**Comment by AlexDM0** [comment]
Hi, 

I see, you could also use the dataset and update the specific node. Take a look at
http://visjs.org/examples/network/data/datasets.html

Regards
