### ISSUE TITLE
Node Grouping by Drag & Drop

### ISSUE THREAD

**Issue by mmcsivakumar** [almende/vis#1092]
Hi,

Is that possible to drag a node to another node to create a link between these node, which means grouping the nodes?

**Comment by AlexDM0** [comment]
Hi,

What do you mean by grouping? The manipulation system allows creating links by dragging. If you want to do it yourself you can disable physics, listen to the release event and get nodes at that point. It could be a problem that you get only the node you're already holding though. To get around that you can get the positions of all nodes and manually do the check. 

Regards

**Comment by mmcsivakumar** [comment]
Dragging a node and dropping to another node will create the link automatically between the nodes.

This is my request.

**Comment by AlexDM0** [comment]
Hi,

As I've stated in my response, it is not available as default functionality but you can use the available methods to implement this behaviour yourself.

Regards

**Comment by mmcsivakumar** [comment]
Ok. Thanks for your Update. We will do it. Just to ensure whether any straight fwd method is available.
