### ISSUE TITLE
When cluster nodes, should auto retain edges colors instead of default blue.

### ISSUE THREAD

**Issue by dragonzone** [almende/vis#1093]
Not sure if it's done on purpose or not, but I believe it's a bug. Take a look at your showcase example, http://visjs.org/examples/network/other/clustering.html. If you click on button, "Cluster all nodes with CID = 1", all the edges to the cluster default to blue. I think it should be the original color it came from.

**Comment by AlexDM0** [comment]
The colors of the edges are set to inherit. By default, inherit takes the color of the border of the from node. In this case, the cluster node's border has a blue color so everything works as expected.

Regards

**Comment by dragonzone** [comment]
Because when I cluster 2 nodes, let says, node1 and node2, if node1 from edge is red and node2 from edge is green, I want it to retain those two colors instead of just 1. Can we have option or something configure to handle that?

**Comment by AlexDM0** [comment]
You do have that. Inherit: both

Its more computationally intensive though!

**Comment by dragonzone** [comment]
Would you tell me how it's done or give me an example. I don't seem to see that documented anywhere. Thanks!

**Comment by AlexDM0** [comment]
http://visjs.org/examples/network/edgeStyles/colors.html

http://visjs.org/docs/network/edges.html --> in the color settings

I may have misunderstood you, what exactly do you imagine this to look like?

Regards

**Comment by AlexDM0** [comment]
If you give an edge explicit colors instead of using inherit, the cluster edges should just give you the color of the edges they replace.

**Comment by dragonzone** [comment]
No, I want it to inherit ALL the "to" and "from" edges colors from the nodes that was selected to be clustered. The new cluster "to" and "from" edges will inherit all those colors. Right now, the "from" cluster to another node will be just what the "color" attribute is set to, which can only be one.

Not if you under, otherwise, i'll try to create an example. Let me know.

**Comment by AlexDM0** [comment]
You want to be able to set two colors per edge? The inherit both inherits two colors, one from "from" and one from "to". It then blends these two colors over the length of the edge. You cannot set two colors without using inherit.

If that is not what you ment, please make an example.

Regards

**Comment by dragonzone** [comment]
I understand what is happening now. Thanks for your help!.
