### ISSUE TITLE
Is Hierarchical FSM visualisation possible?

### ISSUE THREAD

**Issue by prok5reaper** [almende/vis#1094]
Hello, I am developing an FSM debugger, so that I can see what's the current state of an FSM. Take a  look here: 
![fsm](https://cloud.githubusercontent.com/assets/6319132/8698192/5d58e21a-2b04-11e5-996c-fe9411c9ab8b.png)

This is simple FSM. I want to support Hierarchical State Machine. By that I mean, a set of states and transitions should be inside a "parent" state. For example: 
![hsm](https://cloud.githubusercontent.com/assets/6319132/8698229/cfd255d8-2b04-11e5-94b9-e7bbb4d663d2.png) 

I would like to know if there is a way so that this can be accomplished with vis.js

**Comment by AlexDM0** [comment]
Hi,

We do not support nested nodes, so no, this is not possible. You could use the render events (see examples) for drawing custom shapes on the canvas. Our physics solver also does not support bounded areas so the automatic positioning of nodes inside boundaries is also not possible.

Regards

**Comment by prok5reaper** [comment]
Thanks a lot for your fast response
