### ISSUE TITLE
After clustering nodes, if changing network edges length, cluster edges should change

### ISSUE THREAD

**Issue by dragonzone** [almende/vis#1095]
If you cluster 2 or more nodes, then change the length of the edges, using network.setOptions, all the edges will change except ones that are connected to the cluster. Then, if you uncluster it, all those edges in the cluster will be back to normal.
Here is the example I created. There is a time delay for each step. However, the last step, you have to click on the cluster node to see the edges back to normal.

http://jsbin.com/fisaci/edit?html,output

**Comment by AlexDM0** [comment]
Hi,

There is nothing I can do about this at the moment. The clusters and the clusterEdges are not in the list of nodes and edges available for alteration. You do however have the clusterEdgeProperties which you can use to set the options of the cluster edges.

I would however recommend that if you want to have 'longer edges' connected to the cluster, that you increase the mass of the cluster instead. This increases its repulsion, resulting in longer edges as well.

Regards

**Comment by dragonzone** [comment]
Not a big thing, just wanted to you guys to be aware of it.

**Comment by dragonzone** [comment]
Btw, just out of curiosity, what country/location are you from?

On Wed, Jul 15, 2015 at 12:37 PM, Alex <notifications@github.com> wrote:

> Hi,
>
> There is nothing I can do about this at the moment. The clusters and the
> clusterEdges are not in the list of nodes and edges available for
> alteration. You do however have the clusterEdgeProperties which you can use
> to set the options of the cluster edges.
>
> I would however recommend that if you want to have 'longer edges'
> connected to the cluster, that you increase the mass of the cluster
> instead. This increases its repulsion, resulting in longer edges as well.
>
> Regards
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/almende/vis/issues/1095#issuecomment-121603262>.
>



-- 
Long "Andy" Do

**Comment by AlexDM0** [comment]
The Netherlands, what about you?

**Comment by dragonzone** [comment]
I am from Virginia, USA.
