### ISSUE TITLE
Upload license info in package.json

### ISSUE THREAD

**Issue by stanleyxu2005** [almende/vis#1101]
In package.json the license info is written as `"license": "Apache-2.0 or MIT",`. Could you please update it as `"license": ["Apache-2.0", "MIT"],`, so that webjars is able to recognize it for their npm deploy system?

**Comment by josdejong** [comment]
We're following the npm specs here with `"license": "(Apache-2.0 or MIT)"`, it's an SPDX expression. I would say that an array is more logic too, but npm considers this invalid. See https://docs.npmjs.com/files/package.json#license

**Comment by stanleyxu2005** [comment]
Ops. Really sorry to hear that. I'm pretty love the npm rather than bower. I'm contacting the webjars folks. https://github.com/webjars/webjars/issues/1139

**Comment by stanleyxu2005** [comment]
Seems fixed
