### ISSUE TITLE
delete multiselect nodes

### ISSUE THREAD

**Issue by srikanthbbl** [almende/vis#1103]
Hii Alex, i am new to vis.js. I want to delete multiple selected nodes at a time

**Comment by AlexDM0** [comment]
Hi,

I'd recommend you start with the documentation. 

Basically you're looking for the method getSelectedNodes and the dataset or the method deleteSelected. 

There are examples on the dataset also available on our website. 

Regards

**Comment by srikanthbbl** [comment]
I have gone through documentation. but i am not able to get how to use
getselectednodes method.if you dont mine can you give one simple example



Thanks,
Srikanth

**Comment by AlexDM0** [comment]
Hi,

I think it would be beneficial for you to also look through the examples on our website and look in their code for help. It's like this:

```
network.getSelectedNodes()
```

Regards

**Comment by AlexDM0** [comment]
(assuming you call the thing you instantiate "network")

```
var network = new vis.Network(...)
```

**Comment by srikanthbbl** [comment]
Thanks Alex

**Comment by srikanthbbl** [comment]
Hi Alex,
I am using Network Manipulation Module,When i select the single node it is showing all the manipulation buttons i.e add node,edit node,add edge,delete selected.

my problem is when i select the multiple nodes, delete button is disabled.

I want to enable that delete button and i have to delete multiple nodes at atime
is it possible in vis ?

Thanks,
Srikanth

**Comment by srikanthbbl** [comment]
Hi Alex,
I am using Network Manipulation Module,When i select the single node it is
showing all the manipulation buttons i.e add node,edit node,add edge,delete
selected.

my problem is when i select the multiple nodes, delete button is disabled.

I want to enable that delete button and i have to delete multiple nodes at
atime
is it possible in vis ?

Thanks,
Srikanth

**Comment by AlexDM0** [comment]
You do not need to ask your question 3 times. I'll reply in the issue you made for this.
