### ISSUE TITLE
Custom builds?

### ISSUE THREAD

**Issue by JulianHidalgo** [almende/vis#1104]
Not sure if this is  the correct place to ask this, I apologize if not. I'd like to use the timelime feature of the library in one of my projects. I see the js file is quite big, so I'm wondering if there's a way to generate a custom build that only includes the timeline component. Thanks :)!

**Comment by AlexDM0** [comment]
Hi,

Please refer to the readme file on our git homepage.
https://github.com/almende/vis#custom-builds

Regards,

Alex

**Comment by JulianHidalgo** [comment]
Oh I totally missed that. Maybe it would be a good idea to add a note in the download section of the website? Thanks Alex :).

**Comment by AlexDM0** [comment]
We'll be adding seperate files in the near future, that should solve a lot :)
