### ISSUE TITLE
Style grid lines in Graph2D

### ISSUE THREAD

**Issue by MBrunoS** [almende/vis#1106]
Hi, I wanted to customize the grid lines of the Graph2D, i.e., be able to remove them or change their color, but I couldn't make it. I know I can change the background of the container, but I wanted, at least, to change the color of the grids, because they are poluting the view.

Am I missing something?

**Comment by AlexDM0** [comment]
Hi,

I think you are in fact missing something :)

Here you go:

http://jsbin.com/cicufevida/edit?html,output

Regards,

Alex
