### ISSUE TITLE
network manipulation

### ISSUE THREAD

**Issue by srikanthbbl** [almende/vis#1107]
Hi Alex,
I am using Network Manipulation Module,When i select the single node it is
showing all the manipulation buttons i.e add node,edit node,add edge,delete
selected.

my problem is when i select the multiple nodes, delete button is disabled.

I want to enable that delete button and i have to delete multiple nodes at
atime
is it possible in vis ?

Thanks,
Srikanth

**Comment by AlexDM0** [comment]
Hi,

I will add this to the next release. We will release a hotfix today.

Regards
