### ISSUE TITLE
Event after Graph is built

### ISSUE THREAD

**Issue by redskate** [almende/vis#1108]
Hi Alex

very nice implementation.
I need to load many nodes and this takes obviously time. While this happens the canvas is white and one can ask... "is something going on at all"? ... 

So while loading I would show a picture or similar. But how javascript can know that the graph has been built? Is there some callback / hook / method to use in order to trigger an action as the graph was built?

Thank you
Cheers
Fabio

**Comment by AlexDM0** [comment]
Hi Fabio,

Im not sure what you mean by built but I guess you mean stabilized. 

Look at the loading bar example. The event you're looking for is stabilized. 

Regards

**Comment by redskate** [comment]
Hi Alex

yes it was right that! Thank you very much!

Regards
Fabio




Am 19.7.15 um 12:27 schrieb Alex:
> Hi Fabio,
>
> Im not sure what you mean by built but I guess you mean stabilized.
>
> Look at the loading bar example. The event you're looking for is
> stabilized.
>
> Regards
>
>
>
