### ISSUE TITLE
Edges changing on update.

### ISSUE THREAD

**Issue by irumgodil** [almende/vis#1111]
Hi,

I have posted a bin here: http://jsbin.com/yojirupuwo/1/edit?html,output

Essentially, on clicking a node, I want to only show the selected nodes and edges and dim out others. That is working fine, but the edges get inverted in the process too. 

I do not want the edges to change at all, or restabilize anything, but only gray things out. 

I am not sure what is causing this behavior, if someone can take a look that will be great. 

thanks.

**Comment by AlexDM0** [comment]
Hi,

I could help you right now but my phone does not like he jsbin. This means I can't see the code at the moment. If I were to guess you are either using setData to change the node's option or clearing the dataset. We have an example doing this exact behaviour, are you using that implementation?

If you don't mind waiting a few days I'll take a look at the code tomorrow or the day after :)

Regards

**Comment by irumgodil** [comment]
Thanks Alex.
I can wait. This is my code in case it helps:
neighbourhoodHighlight:function(params) { // if something is selected: var allNodes = this.nodes.get({returnType:"Object"}); var allEdges = this.edges.get({returnType:"Object"}); if (params.nodes.length > 0) { this.highlightActive = true; var i,j; var selectedNode = params.nodes[0]; var degrees = 1; // mark all nodes as hard to read. for (var nodeId in allNodes) { allNodes[nodeId].originalColor = allNodes[nodeId].color; allNodes[nodeId].color = 'rgba(200,200,200,0.5)'; allNodes[nodeId].hiddenLabel = allNodes[nodeId].label; allNodes[nodeId].label = undefined; //allNodes[nodeId].hidden = true; } var connectedNodes = this.network.getConnectedNodes(selectedNode); var allConnectedNodes = []; // all first degree nodes get their own color and their label back for (i = 0; i < connectedNodes.length; i++) { allNodes[connectedNodes[i]].color = allNodes[connectedNodes[i]].originalColor; if (allNodes[connectedNodes[i]].hiddenLabel !== undefined) { allNodes[connectedNodes[i]].label = allNodes[connectedNodes[i]].hiddenLabel; allNodes[connectedNodes[i]].hiddenLabel = undefined; //allNodes[nodeId].hidden = false; } } // the main node gets its own color and its label back. allNodes[selectedNode].color = allNodes[selectedNode].originalColor; if (allNodes[selectedNode].hiddenLabel !== undefined) { allNodes[selectedNode].label = allNodes[selectedNode].hiddenLabel; allNodes[selectedNode].hiddenLabel = undefined; //allNodes[nodeId].hidden = false; } var selectedEdges = params.edges; for (var edgeId in allEdges) { var edge = allEdges[edgeId]; edge.regularWidth = edge.width; //store the original width.  if (selectedEdges.indexOf(edge.id) == -1)  { edge.width = 0.01; // edge.hidden = true; } }　 } else if (this.highlightActive === true) { // reset all nodes for (var nodeId in allNodes) { allNodes[nodeId].color = allNodes[nodeId].originalColor; if (allNodes[nodeId].hiddenLabel !== undefined) { allNodes[nodeId].label = allNodes[nodeId].hiddenLabel; allNodes[nodeId].hiddenLabel = undefined; //allNodes[nodeId].hidden = false; } } for (var edgeIds in allEdges) { var edge = allEdges[edgeIds]; edge.width = edge.regularWidth; //restore the original width.  //edge.hidden= false; } this.highlightActive = false } // transform the object into an array var updateArray = []; for (nodeId in allNodes) { if (allNodes.hasOwnProperty(nodeId)) { updateArray.push(allNodes[nodeId]); } } // transform the object into an array var updateEdgesArray = []; for (edgeId in allEdges) { if (allEdges.hasOwnProperty(edgeId)) { updateEdgesArray.push(allEdges[edgeId]); } } this.nodes.update(updateArray);  this.edges.update(updateEdgesArray); //this.refreshUILayout(1000); },

**Comment by AlexDM0** [comment]
Hi,

I've deleted our conversation of yesterday for clarity for future readers. I have found the problem and pushed a fix to develop. We'll include it in the next release.

Thanks for reporting!

Regards,

Alex

**Comment by irumgodil** [comment]
Hi,
Ok, I thought it was just between us, did not realize it was on the newsgroup. 
When is the next release scheduled?
thanks.

**Comment by AlexDM0** [comment]
This has just been released in v4.6.0

**Comment by irumgodil** [comment]
This works like a charm in the new update. Thanks for quickly addressing it. I am really thankful to you for all your responses.
-Irum.
