### ISSUE TITLE
Issue when using vis.js in Mozilla Firefox

### ISSUE THREAD

**Issue by shantanoo-desai** [almende/vis#1112]
Hello.
First of all some awesome work with vis.js. It looks really awesome and eager to try it in my project. 
I am using Ubuntu 15.04 and somehow the node diagrams are no able to be displayed correctly on the browser. 
the diagram is just showing up in bits and pieces. I checked it on Windows in Chrome and Firefox, there it shows up perfectly? 
Am I missing a hint in the CSS files where I need to set something for Firefox or is this a genuine glitch? 
**Current version of Mozilla Firefox used: 39.0**
Error in my application:

![visjs_error_app](https://cloud.githubusercontent.com/assets/12070966/8802289/bcf7590c-2fc0-11e5-816e-12b4181fdb0b.png)

Error in the website while browsing:
![visjs_error_website](https://cloud.githubusercontent.com/assets/12070966/8802291/bde59d24-2fc0-11e5-851d-649e067367fc.png)

if you could help me out this would be great!
Thanks 

Shan

**Comment by felixhayashi** [comment]
Can confirm this (Linux Mint and FF 39.0). Also all the examples are "bits and pieces".

This is how http://visjs.org/examples/network/nodeStyles/colors.html looks like:

![selection_417](https://cloud.githubusercontent.com/assets/4307137/8802931/68f1df36-2fc4-11e5-9c47-36407a3c9ede.png)

**Comment by felixhayashi** [comment]
Plus nothing can be dragged or clicked.

**Comment by shantanoo-desai** [comment]
Can we use any other web browser in Ubuntu except for Firefox and check if the glitch still exists?

**Comment by felixhayashi** [comment]
Well, `sudo aptitude install chromium` ;) The problem only exists with firefox not with chrome. But this is bad enough as Firefox is quite an important browser... @josdejong, since you are a fellow linux user, any ideas what is causing this?

**Comment by shantanoo-desai** [comment]
Yes I checked it on Chrome and it works. But wouldn't be actually Open Source unless one does not use Firefox. What might be causing the problem? Any hints?

**Comment by AlexDM0** [comment]
Do you guys get any error messages? @felixhayashi, do you know how long this has been going on?

Regards

**Comment by felixhayashi** [comment]
Hi @AlexDM0 

I just upgraded from v4.4 to v4.5.1... so must have been introduced after v4.4.

No error message unfortunately. Visually it reminds me a bit of https://github.com/almende/vis/issues/526 where Firefox also caused problems and you fixed it.

**Comment by AlexDM0** [comment]
Hi All,

I found the problem, turns out it came from the pull req for dashed borders that we didnt screen sufficiently.

I have cleaned the code and made it safe for use again. We'll probably release next Friday to get this one out there as soon as we can. Breaking a browser is not allowed, our apologies.

The fix can be found in the develop branch. Thank you both for reporting this!

Regards,

Alex

**Comment by felixhayashi** [comment]
No problem, many thanks fixing this @AlexDM0!

**Comment by shantanoo-desai** [comment]
Thanks @AlexDM0

**Comment by AlexDM0** [comment]
This has just been released in v4.6.0

**Comment by OACDesigns** [comment]
It looks like this bug has resurfaced.
Firefox 50.1.0 on Ubuntu.
Is anyone else experiencing this issue?

**Comment by Tooa** [comment]
Can you please open a new issue? We may miss this otherwise. Please also provide a jsbin that shows the issue and add the steps to reproduce the error. I will look into this later.

**Comment by OACDesigns** [comment]
👍 will do
