### ISSUE TITLE
[Website] Links to network modules not functioning

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#1115]
Hi guys,

The links to the modules in http://visjs.org/docs/network/ are broken.

Seems like a search'n'replace gone wrong: The a-tags now became `<td href="./edges.html">edges</td>`

-Felix

**Comment by AlexDM0** [comment]
lets just pretend no one saw that :) thanks for the heads up!

**Comment by felixhayashi** [comment]
> lets just pretend no one saw that

Putting the `href`-attribute on `td` tags is quite inventive :) I'll create a pull request at the w3c's HTML-Spec repo, maybe they accept it.

**Comment by AlexDM0** [comment]
it was a side effect of the regex putting ids in tds for reference :)
