### ISSUE TITLE
Timeline: Start date of event is inaccurate at certain zoom level when panning.

### ISSUE THREAD

**Issue by theromulanz** [almende/vis#1118]
The events shift slightly when panning from a certain zoom level. 
![state0](https://cloud.githubusercontent.com/assets/9732078/8839192/01deb7d2-3088-11e5-85b9-f10d6a3af014.png)
![state1](https://cloud.githubusercontent.com/assets/9732078/8839193/05a6c9ea-3088-11e5-8bd1-1e83f6732f71.png)

**Comment by josdejong** [comment]
Ouch that's a terrible bug, thanks for bringing this up. This bug was introduced in the latest version I see (v4.6.0), we will fix it asap.

**Comment by josdejong** [comment]
This issue is fixed in the `develop` branch now (see https://github.com/almende/vis/commit/116244c421f6379133d3f2f569fb3321ec690042)

**Comment by theromulanz** [comment]
Great! Hoping to use Timeline in production application.
