### ISSUE TITLE
Network node postion dynamically with animation

### ISSUE THREAD

**Issue by aneeshmj** [almende/vis#1120]
Hi,

I am new to vis.js. My requirement is to add a new node dynamically (by drag and drop) which I am able to. After adding the node, I want to move the node to a particular position (say {x: 10, y: 10}) from where I dropped it with some animation. I searched through the doc and I couldn't find any individual node animation sample. Is this possible? if yes, how ? Please help.

Thanks in advance.

 aspect.after(canvas, "onDrop", function(){
    addNode(label, x, y, color); // adds the node, which is done.
   // now I want to move this to a new position x: 10, y: 10 with some easing effect.
}

**Comment by AlexDM0** [comment]
Hi,

This is not possible nor do I think it will be in the near future. 

Regards

**Comment by aneeshmj** [comment]
Ohh..ok :) thanks Alex!!

**Comment by AlexDM0** [comment]
Hmm come to think of it, all that's needed is a method moveNode and the usage of the initRedraw event. 

Maybe I can add this in the next release. 

I was thinking along more complex lines before. 

Regards

**Comment by aneeshmj** [comment]
That would be really great Alex!! :) Awaiting for this. Thanks a lot!!

**Comment by AlexDM0** [comment]
It has been added in v4.7.

Regards
