### ISSUE TITLE
Timeline: is it possible to set a scale parameter for the mouse wheel zoom

### ISSUE THREAD

**Issue by mast0r** [almende/vis#1121]
Hello guys,
is it possible to set somehow a scale parameter for the mouse wheel zoom? While I am zooming with a mouse wheel it gets zoomed too fast. 
Background: I have to load items dynamically for the new date ranges and want that my customers are not overload the database with too many calls.

Thanks!

**Comment by josdejong** [comment]
I don't think that making the zooming slower will solve your issue. Maybe you should limit how far a user can zoom out (options `zoomMin`, `zoomMax`). And maybe you need to throttle the amount of calls you make to your database (see https://lodash.com/docs#throttle).

**Comment by AlexDM0** [comment]
Hi,

There has been a similar request for the network but that was based on the high sensitivity of macbook trackpads. A pinch there is zooming VERY quickly. For this, a zoom parameter would be beneficial. However, for the usecase presented here, I agree with Jos that throttling is the way to go.

Regards

**Comment by mast0r** [comment]
Thank you Jos and Alex! I think will end up with underscore (already used in my project) and it throttle/debounce functions.
On the other hand it would be nice to have some parameter that could controll the zooming "speed". I think I will try to implement some kind of range controll for it.

Please close this "issue". Thank you.

**Comment by josdejong** [comment]
you're welcome!
