### ISSUE TITLE
Style Timeline item with multiple CSS classes

### ISSUE THREAD

**Issue by florianplag** [almende/vis#1122]
Hi,

just a short question: Is it possible to style a timeline item with multiple CSS classes (because I have several combinations of styles I want to use)? I tried this (like in CSS), but it didn't work. 

	{
	content: 'My Item',
	start: '2015-10-01',
	end: '2015-12-31',
	className:'styleOne styleTwo', group: 33},			
	{

Thanks!

**Comment by josdejong** [comment]
Yes, you do it the correct way and this will add two extra class names to the item. You can verify the applied class name of the rendered item with the developer tools of your browser.

**Comment by florianplag** [comment]
Sorry, my fault. Yes, of course .. it works :-) Thanks!

**Comment by josdejong** [comment]
ok!
