### ISSUE TITLE
Collapse & Enable Nodes

### ISSUE THREAD

**Issue by mmcsivakumar** [almende/vis#1123]
Dear Alex,

We need the functionality like collapse the particular level of nodes and can enable by clicking the nodes.

It would be better dynamically load the data when enable the node.

Please advise if already exists.

**Comment by AlexDM0** [comment]
Hi,

Please take a look at the dataset in the examples and documentation. There is a click event or selectNode event which you listen to to trigger this. 

Regards

**Comment by mmcsivakumar** [comment]
Thanks for the update Alex.
