### ISSUE TITLE
styling a group item

### ISSUE THREAD

**Issue by jrviz** [almende/vis#1125]
It may be that I am missing something but if I set a style: string on a group definition in a timeline (vis 4.2, it worked in 3.x)  then it now seems to omit the first element. e.g.

`style:'background-color: #3366FF; color: #ff0000;'`

sets the text color but not the background colour in the group.

**Comment by josdejong** [comment]
I think this issue is already fixed in the latest version of vis.js, v4.7.0. Can you try that?

**Comment by jrviz** [comment]
Yes, 4.7 works. 

Sorry, I did not see anything in the change logs which showed a change in this area.

**Comment by josdejong** [comment]
ok!

its here in the changelog: https://github.com/almende/vis/blob/master/HISTORY.md#timeline-2, 4th bullet, #1001.
