### ISSUE TITLE
doubleClick event not firing in timeline.

### ISSUE THREAD

**Issue by sherming** [almende/vis#1127]
doubleClick event not firing in timeline with editable option.

**Comment by josdejong** [comment]
Thanks, I see the `doubleClick` event is fired when double clicking on the the TimeAxis but not when in the contents area.

**Comment by rudott** [comment]
@josdejong I also came across this issue (when upgrading to the latest version). When setting editable true or specifying the attributes, the doubleClick is not fired.

**Comment by josdejong** [comment]
Thanks for the detailed report. It's fixed now in the `develop` branch.
