### ISSUE TITLE
mutating the [[Prototype]] of an object will cause your code to run very slowly....

### ISSUE THREAD

**Issue by redskate** [almende/vis#1128]
Hi Alex 

running your last version of visjs I noted the following warning (Firefox on Mac):

mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create - vis.js:28435:392

Do you think you can improve something?

Regards
Fabio

**Comment by AlexDM0** [comment]
Hi Fabio,

I've seen this message as well. It points to the constructs used by our es6 to es5 compilation engine and/or webpack or browserify. It happens outside of the inner loops so it does not really affect anything. 

There's nothing we can do to remove this warning as far as I know. There's also no need to. The Unix Firefox has a terrible canvas performance in my experience and there's nothing we can do to fix this (I'm not sure if the Mac variant suffers from the same issues). I have the same warning on windows and the performance there is much much better. 

We could argue that we sacrificed performance to work in ES6 but the backend of network is so much more cleaner than it was before (granted, most improvements have been from the architectural change, but es6 was a pleasure to work with and we have to keep it fun to do right??). 

Sorry to let you down here, there's no magic fix that will quadruple the performance and we are REALLY not planning to stop using build tools and work in a 35k lines file haha. 

Regards,

Alex
