### ISSUE TITLE
Cluster support

### ISSUE THREAD

**Issue by bartvdo** [almende/vis#113]
Hi,

I have an enhancement for the Graph functionality.
Would it be possible to include cluster support (like http://graphviz.org/content/cluster )?
So you can define nodes that are in a box (cluster) and define edges between them?

Thanks!

**Comment by SenthilKumarasamy** [comment]
In general, is it possible to make the clusters transparent, showing all the internal nodes and edges. Presently they are hidden inside the cluster.

**Comment by AlexDM0** [comment]
Hi,

This is not possible nor do I think it will be in future releases. Our physics model does not support boundaries, making it all very computationally expensive. 

Regards

**Comment by jenicar** [comment]
I have a similar request. Are there any work arounds available for this at the moment?
My end goal is to keep types of nodes grouped together on the network but I'm struggling to find a way to do this...
