### ISSUE TITLE
[Network] Full Screen

### ISSUE THREAD

**Issue by andrea-bologna** [almende/vis#1130]
How can I have a button to redraw a network in full screen mode?

**Comment by AlexDM0** [comment]
Hi,

You make a button, and on click do the redraw method.

Regards

**Comment by andrea-bologna** [comment]
I did some attempts, but when I resize the container div, the graph is plotted only on the top left corner and not resized to fill the screen

**Comment by AlexDM0** [comment]
What version are you using?

We do plan to change the behaviour of the increase of the window. The current behaviour is just increasing the workspace, not scaling the graph. You can do this yourself if you want using the moveTo method or the fit method.

Regards

**Comment by AlexDM0** [comment]
also see #915

**Comment by dragonzone** [comment]
I integrated http://sindresorhus.com/screenfull.js/ with Vis.js Network, seems to work pretty well.

**Comment by AlexDM0** [comment]
I see, if that was what you ment then @dragonzone has answered the issue correctly. If not, please let me know so we can reopen this issue.

Thanks dragon!
