### ISSUE TITLE
moveNode?

### ISSUE THREAD

**Issue by englandrp** [almende/vis#1134]
There's a moveNode method described in the documentation (http://visjs.org/docs/network/). It doesn't appear to exist in the source. Was it removed? Is there an alternative method?

**Comment by AlexDM0** [comment]
It does appear in the source. Try any example and type in the console network.moveNode(1,0,0).

You'll have to have the latest version naturally.

Regards

**Comment by englandrp** [comment]
I'll double check. Apologies if it's a daft mistake on my part (which no doubt it is) :-)

**Comment by AlexDM0** [comment]
I'm guessing your cache didnt update after updating vis? The documentation only ever reflects the latest version of vis.js. We're only 2 people so we can't keep up with all the legacy stuff :).

Cheers

**Comment by englandrp** [comment]
It was a node/package.json related thing. Thank you :-)
