### ISSUE TITLE
Showcase projects - OneProfile

### ISSUE THREAD

**Issue by wyvernnot** [almende/vis#1136]
Hello, I just created a tool called OneProfile using Visjs

Here is the link:
http://wyvernnot.github.io/javascript_performance_measurement/cpuprofile_topology/

This tool is used to visualize the CPU profile generated by JavaScript v8 engine. Allowing JavaScript developers to see the call hierarchy of each sample taken. It also highlights de-optimization reason of  JavaScript functions, working as tips for improving performance.

**Comment by AlexDM0** [comment]
Hi, 

This looks like a cool tool! It could help to have a little design love though. Improving the color scheme, buttons and general user interface would greatly help.

Regards
