### ISSUE TITLE
Dos vis can draw this type of diagram?

### ISSUE THREAD

**Issue by zhenyuan2015** [almende/vis#1137]
http://image79.360doc.com/DownloadImg/2014/10/1120/46042822_7.jpg
![image](https://cloud.githubusercontent.com/assets/12582196/8978164/292128b6-36d2-11e5-9336-4d4cf8e81d8e.png)

and  another type is sunburst
![image](https://cloud.githubusercontent.com/assets/12582196/8978179/3c713cda-36d2-11e5-9b97-891d50b870bb.png)

http://image79.360doc.com/DownloadImg/2014/10/1120/46042623_7.jpg

I'd like to develop these two type diagram, other libraries I was considering are d3.js, gojs.js,arbor.js.

**Comment by AlexDM0** [comment]
Vis could draw the first, definitely not the second. 

Regards

**Comment by zhenyuan2015** [comment]
Thanks for your reply.Is there some demos like the first?I did not find this type on vis web site.

**Comment by AlexDM0** [comment]
You'd have to do the layout yourself but the edges can be set to smooth type curvedCW to get this effect. 

Regards

**Comment by AlexDM0** [comment]
Take a look at this example
http://visjs.org/examples/network/edgeStyles/smooth.html
