### ISSUE TITLE
After a label is shifted, it gets shifted back after the code is run

### ISSUE THREAD

**Issue by dizou** [almende/vis#1140]
This is related to the StackOverflow question I posted here: https://stackoverflow.com/questions/31705721/in-my-vis-js-stacked-bar-chart-how-do-i-move-my-labels-to-the-correct-location

I was able to write some code that shifted the labels to the positions I want them in. However, after the labels are shifted, they get shifted back to their original position after all the custom JavaScript is completed.

Here is the JS that I wrote to shift the labels into the right positions:

            var yOffset = 14; //yOffset so that the text labels will appear below the bar chart div line
            var barChartDivsDict = {};
            var barChartTextDivsDict = {};
            var barChartDivs = barGraphDiv.find('.vis-bar');
            for (var index = 0; index < barChartDivs.length; index++) {
                var barChartDiv = $J(barChartDivs[index]);
                var x = barChartDiv.attr('x');
                var x_value = x.baseVal.value;
                if (!(x_value in barChartDivsDict)) {
                    barChartDivsDict[x_value] = [];
                }
                barChartDivsDict[x_value].push(barChartDiv.attr('y').baseVal.value);
            }
            var barChartTextDivs = barGraphDiv.find('text');

            for (var index = 0; index < barChartTextDivs.length; index++) {
                var barChartTextDiv = $J(barChartTextDivs[index]);
                var x_value = barChartTextDiv.attr('x').baseVal[0].value;
                if (!(x_value in barChartTextDivsDict)) {
                    barChartTextDivsDict[x_value] = [];
                }
                barChartTextDivsDict[x_value].push(barChartTextDiv.attr('y').baseVal.value);
                var divIndex = barChartTextDivsDict[x_value].length - 1;
                barChartTextDiv[0].setAttribute('y', barChartDivsDict[x_value][divIndex] + yOffset);
            }

What's causing the labels to shift back to their original position and what can I do to stop that? Thanks!

**Comment by AlexDM0** [comment]
There is a redraw cycle in the background which probably causes this. Redraws are managed by the graph2d. There are no events to listen to to trigger your code to run again. I'll see if I can fix the bug.

Regards

**Comment by AlexDM0** [comment]
I pushed the fix to the develop branch. We'll include it in the next release.

Regards

**Comment by dizou** [comment]
Awesome, thank you!
