### ISSUE TITLE
mousedown, mouseup event does not fire on the timeline on IE11

### ISSUE THREAD

**Issue by allayli** [almende/vis#1143]
I am using the Timeline module with visjs 4.3.0 or 4.7.0.
It works fine on Chrome/Safari. But on IE11, the mousedown/mousedown events are not fired. But mousemove event can be fired.

**Comment by AlexDM0** [comment]
Can you provide more details? I don't believe we provide events for those anywhere. Which module are you referring to?

**Comment by allayli** [comment]
Hi Alex,
I am using Timeline module. The mousedown/mouseup event cannot be fired on anywhere of the timeline when using IE 11.

**Comment by AlexDM0** [comment]
Hi,

Why do you need these events? We have our own events that should be enough. Could you give me a usecase?

Regards

**Comment by allayli** [comment]
Hi,
I am trying to use the mousedown/mouseup events to distinguish the click event and drag event.
In particular, I want to set the customer time marker by clicking on the timeline.
Is there any suggestion?
Thanks.

**Comment by AlexDM0** [comment]
Hi,

I would suggest looking into the documentation and examples. The events are made for these things:
http://visjs.org/docs/timeline/#Events

Regards

**Comment by allayli** [comment]
Thanks. Let me try the click event.

**Comment by allayli** [comment]
The click event on timeline works fine. Thanks!
