### ISSUE TITLE
Gravity towards center

### ISSUE THREAD

**Issue by redskate** [almende/vis#1147]
Hi Alex
Hi community

:)
My compliments again Alex for the smart lib!

I have to visualise a graph with nodes containing some tags. The nodes containing "1" for example should be attracted by the center, the other nodes simply stay around as the network "knows".

Any idea how to let attract nodes toward a fixed point on the canvas?

Thanks a lot in advance
Fabio

**Comment by AlexDM0** [comment]
Hi Fabio,

There is the central gravity that pulls all nodes to 0,0. Other then that, you cannot really do attraction.

You could however use the moveTo method to physically move the node?

Regards
