### ISSUE TITLE
Configurator slider jumps back to scale's center when set above middle value

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#1150]
Hi guys,

To reproduce go to http://visjs.org/examples/network/other/configuration.html and set the first slider to e.g. max. It will change the numeric value and jump back again.

-Felix

**Comment by felixhayashi** [comment]
I tested this 11270646 times to really make sure

---

![2015-08-02 15 27 58](https://cloud.githubusercontent.com/assets/4307137/9026308/181addea-392b-11e5-8adc-f55f96641607.png)

**Comment by AlexDM0** [comment]
Hi Felix,

This may seem unclear but it's actually a feature. It lets you go above the max default value. For playing with physics this can be quite valuable. 

Regards

**Comment by felixhayashi** [comment]
Ah ok, I get it. Thanks for the clarification.

**Comment by josdejong** [comment]
At first I too thought this was a bug until Alex explained the behavior to me. 

Should we reconsider this behavior? Maybe instead we could display a small "+" button on the right side of the slider which allows you to enlarge the max value of the slider?

**Comment by AlexDM0** [comment]
I agree it could be improved. When designed the configurator was ment as development aid... Once we have time we can look into improving it.

**Comment by josdejong** [comment]
Yes, this doesn't have high priority. But maybe someone wants to pick this one up and improve on it :)

**Comment by felixhayashi** [comment]
Hi @josdejong,

I'd like to pick this up but I am totally out of capacity for the next time, looks like I started working on too many projects at once :(

I hope it's still ok for you guys if I create issues without being able to contribute to the solutions. Apart from bug reports, I just think it often makes sense to create issues as a means to give user experience feedback. I completely understand that some topics are just not a priority.

-Felix

**Comment by josdejong** [comment]
Thanks Felix.

I have made an issue for this topic here https://github.com/almende/vis/issues/1159, so we can pick this up later.

**Comment by AlexDM0** [comment]
Hi Felix,

We greatly appreciate any and all feedback on vis, so don't worry about just reporting! We are quite busy at the moment though so it would be great if people contribute (and they do!).

Regards
