### ISSUE TITLE
How to dynamically update node or edge values based on selection

### ISSUE THREAD

**Issue by EricPoitras** [almende/vis#1151]
Hi,

I'm having difficulties to update the value of a specific node or edge when the user selects a specific node.  

I'm using the following function once a double click event is triggered:

var newnodevalue = 1 + data.nodes.get(2,fields:'value');
nodes.update({id:2, value: newnodevalue});

However, the graph does not load on the screen. Does anyone have any suggestions?

**Comment by AlexDM0** [comment]
Hi,

What do you mean the graph doesn't draw? Without seeing it is hard to guess. 

Why are you using data.nodes.get to get the data (so I assume that's your dataset) and nodes.update to update? It seems like a weird way to to your data structure. 

regards,

Alex

**Comment by EricPoitras** [comment]
I'm guessing that my reference to the data object is the problem, what would be the proper way to get the value of a specific node in the dataset? I would like to use the function to update that value.

**Comment by AlexDM0** [comment]
Hi,

Without actually seeing your code or an example thereof, I cant really help you. There's an example on how to work with datasets on our website. If that's not clear enough, please provide some code so I can understand what the problem is. A jsbin would be great.

Regards

**Comment by EricPoitras** [comment]
![screenshot 2](https://cloud.githubusercontent.com/assets/13616997/9042006/fe7fd6da-39c8-11e5-8f6d-8eb9fc65a8b8.png)

Best I can do is this screenshot, I'm working on the local website now and modifying the interactive networks html example document. At the bottom of the screenshot, you can see the nodes.update() function. I'd like to refer back to the dataset to get a value of a specific node, and update that value using a function that adds a value of 1.

Is this helpful? I've tried reading the documentation and different variations on the function but cant seem to figure it out.

Thanks for your help,

**Comment by AlexDM0** [comment]
Hi,

Could you make a JSBin to show the problem?

Regards
