### ISSUE TITLE
Dynamic groups

### ISSUE THREAD

**Issue by pliablepixels** [almende/vis#1155]
Hi, I am trying to instantiate a new vis object with both dynamic dataSets as well as dynamic groups.
I understand I can use DataSets to modify the data. How do I dynamically modify groups after the graphs are created?

thanks

**Comment by josdejong** [comment]
You can add/update/remove data in the DataSet. The visualizations listen for changes to the DataSet and automatically update the view accordingly.

Here are the docs of the DataSet: http://visjs.org/docs/data/dataset.html

**Comment by AlexDM0** [comment]
Hi,

The groups are options, setOptions should be able to change them. I'm not 100% sure it will be propagated to the nodes though, you may have to update them too. 

Regards

**Comment by pliablepixels** [comment]
Thanks. What finally worked for me was to instantiate timeline with just a container, then individually call these APIs to ensure the visual kept changing as data changed:

```
var timeline = new vis.Timeline(container[0]);    
var graphData = new vis.DataSet();
    timeline.setItems(graphData);
    timeline.setOptions(options);
   timeline.setGroups(groups);
```

**Comment by josdejong** [comment]
ok great!
