### ISSUE TITLE
title for range timeline

### ISSUE THREAD

**Issue by pliablepixels** [almende/vis#1157]
Hello, I noticed there is an existing issue: https://github.com/almende/vis/issues/778 that discusses that that "title" element as described in http://visjs.org/docs/timeline/ for background items don't work.

I am facing the same problem with range timelines. Here is how I am adding:

```
graphData.add({id:graphIndex, 
                                    content: '', 
                                    start:myevents[i].Event.StartTime,
                                    end:myevents[i].Event.EndTime,
                                    group:myevents[i].Event.MonitorId,
                                    type:"range",
                                    style:"background-color:"+colors[parseInt(myevents[i].Event.MonitorId) % colors.length]+";border-color:"+colors[parseInt(myevents[i].Event.MonitorId) % colors.length],
                                   title:"Hello"
                                   
                                   });
```

According to the documentation, if I tap (mobile) or touch (desktop) the item, it should display the title of "Hello", but it does not.

Given this is not a background item but a range item, I've created a new issue - please feel free to merge if fit.

What I am trying to do is when a user 'taps' on a range in the timeline, it should show a label with more details.

**Comment by josdejong** [comment]
Titles are only shown when hovering an item with a mouse. It's not a fully fledged popup, if you want that you will have to implement something for that yourself using a popover library or something like that.

I'm not sure where you found the tapping thing in the docs, the docs say about `title`:

> Add a title for the item, displayed when holding the mouse on the item. The title can only contain plain text.
