### ISSUE TITLE
Mobile responsiveness tips?

### ISSUE THREAD

**Issue by pliablepixels** [almende/vis#1158]
Hi, would you have any tips on mobile responsiveness?

I have integrated vis into a mobile app (uses ionic) for iOS 8. While the timeline draws fine, I've noticed the following issue:

Panning/zooming the timeline is _very_ slow -- some times it responds in 1-2 seconds, sometimes it takes several seconds.

When I enabled debug, I saw this:
Touch: Failed to receive system gesture state notification before next touch
Gesture: Failed to receive system gesture state notification before next touch

This is for a small dataset - around 100 items. Any ideas on what I can do to spiff up the speed? Note that data is local (not from network)

**Comment by pliablepixels** [comment]
BTW, I've noticed CPU reaches 100% very often while trying to pan and zoom --> memory remains constant

**Comment by pliablepixels** [comment]
Setting autoresize to FALSE (in options) seems to result in significant performance improvement.
I can easily call redraw() if resize happens. 

I'll keep this ticket open and keep posting things I discover for a few days if that is ok. It may help others.

**Comment by pliablepixels** [comment]
Hello, unfortunately, I am still being plagued by significant performance issues. Each time I pan or zoom, my CPU hits 99%.

This is for 100 data items in the timeline.

I am going to try and disable pan and zoom via touch, but I don't see any API to zoom in. I only see moveTo. Any thoughts?

**Comment by AlexDM0** [comment]
Hi,

Since JavaScript is single threaded and moving the timeline needs a redraw, the cpu will run the sequential code for the redraw, taking 100 percent of a core. This is normal and it's the way JavaScript works. 

As for the performance, it could be that stacking takes up a lot of the time? What type of items do you use? Could we see the timeline in question?

Regards,

Alex

**Comment by AlexDM0** [comment]
Did you also test this outside of your "app" using safari?

Regards

**Comment by pliablepixels** [comment]
Hello, so far what I am seeing is that the performance is worst when we are zoomed out - when we zoom in, I guess there is lesser images to draw at a given time, so that may explain it.

It is good to know that 99% is normal. I am running some tests as follows:

a) I am running the visjs performance example on plain mobile safari 
b) I have integrated the visjs performance code into my app as is
c) I am refactoring my own graph code to match the performance code exactly

I'll report soon with findings

**Comment by AlexDM0** [comment]
What do you mean by images? Do you have multiple DOM elements inside of each item?

There are optimisations to reduce calculation when zoomed in. From what I gather your bottleneck is the drawing. This is all done by the browser. We cannot optimise this process. 

Regards

**Comment by pliablepixels** [comment]
@AlexDM0 , it does not look like drawing I've been trying different approaches and I have a strong feeling its more to do with touch processing and potential conflicts with ionic (a mobile framework)

Here is my analysis:
a) I ran http://visjs.org/examples/timeline/other/groupsPerformance.html on mobile safari (outside of my app) -- what I observed was performance was better than running the same graph in my mobile app (using ionic). However, when I zoom out of the graph (pinch) and make more elements show the performance gets worse (not as bad as in my app). I have a question on this - when you are rendering the graph and there are overlapping items in the zoomed out view, do you draw each item none-the-less or skip items to optimize on drawing time?

b) I integrated the same graph above into my app and ran it. The performance is good when you zoom in, but as you zoom out it gets worse and then when you are fully zoomed out (pinched) for every move the CPU sticks at 99% for 4-5 seconds making it unresponsive. When I ran a profiler, I saw this:http://imgur.com/Ndz6EEb --> note that its getting stuck in gesture recognition not drawing!

c) The performance or the graph http://visjs.org/examples/timeline/other/groupsPerformance.html when integrated into my app is reasonably better than my own graph. Here is my graph data --> https://gist.github.com/pliablepixels/1ec9c3631a576af0486b#file-gistfile1-txt

The big difference is that my events are very closely packed in timeline -often separated by just seconds while the random data generated by your example graph is better spaced out - does that make a difference when it is being rendered in zoomed out (pinched out) view?

**Comment by AlexDM0** [comment]
Hi,

To answer your question, we draw everything in view. More has to be drawn when you zoom out, so that takes longer. Phones may benefit from some zoom throttling because each pinch gesture thats handled (which I think is what you refer to) is triggering a redraw cycle to show the zoom result.

Maybe @josdejong can shed more light on this.

Regards

**Comment by pliablepixels** [comment]
@AlexDM0  thank you. Look forward to more thoughts from @josdejong 

A quick update, if code makes a difference on how I am invoking the graph
template: https://github.com/pliablepixels/zmNinja/blob/master/www/templates/timeline.html
Controller: https://github.com/pliablepixels/zmNinja/blob/master/www/js/TimelineCtrl.js

drawDummyGraph() draws the vis performance graph with the same dummy data as in your example
https://github.com/pliablepixels/zmNinja/blob/master/www/js/TimelineCtrl.js#L161

drawGraph() draws my graph: https://github.com/pliablepixels/zmNinja/blob/master/www/js/TimelineCtrl.js#L226

**Comment by pliablepixels** [comment]
@AlexDM0 when you say "Phones may benefit from some zoom throttling" --> can you point me to where I need to look to enable that?

**Comment by AlexDM0** [comment]
Hi,

The throttling is not something you can enable, but it is something we could look at in the backend.

Regards

**Comment by pliablepixels** [comment]
Thanks. In the mean time, I want to try and see if disabling movable and zoom in the graph helps. But I need to add external sliders to move and zoom.

a) As far as pan goes, what is the best way to implement it?  Looking at your APIs, there is a getWindow that returns a start and endTime. One way to implement move is a.1) x  = getWindow() b.2) call setWindow after incrementing start and end time. What I can't seem to figure out is how to know by how much to increment as I don't really know level of zoom (is it displaying months, days, seconds)

b) As far as zoom in/out goes, what API can I use to implement this?

thanks

**Comment by AlexDM0** [comment]
the window is a start and end timestamp. You can subtract them to get the range. Similar for zoom.
window:
|-----------------|

zoomedWindow:
|..|-------------|..|

Cheers

**Comment by pliablepixels** [comment]
@AlexDM0 can you see what I am doing wrong? This is the code to pan to the right - I'm gettingWindow() adding 1 month to both and doing a setWindow followed by redraw

console.log prints the right times but the graph does not move (and next time I do getWindow it shows the old values, not the +1 month values)

Thanks

```
 $scope.zoomPan = function (str) 
    {
        var x= timeline.getWindow();
        console.log (JSON.stringify(x));
        
        if (str=='PR')
        {
            var mystart = x.start;
            var myend = x.end;
            mystart = moment(mystart).add(1,'month').format ("YYYY-MM-DD HH:mm:ss");
            myend = moment(myend).add(1,'month').format("YYYY-MM-DD HH:mm:ss");
            
            console.log ("New Times " + mystart + " " + myend);
            timeline.setWindow(mystart,myend);
            timeline.redraw();
        }
    };
```

**Comment by AlexDM0** [comment]
http://visjs.org/docs/timeline/#Methods

The expected value is not moment format

**Comment by pliablepixels** [comment]
Thanks. I am using string format (calling .format after moment) not moment format. The error was I was advancing by a month but had a min/max that was stopping it. Fixed. I'll report soon on performance differences (if any) after disabling internal drag/zoom

**Comment by pliablepixels** [comment]
@AlexDM0, Some results of my analysis:

a) Disabling touch and zoom on the map and moving the map via external controls (like buttons) results in _significantly_ more consistent performance. The CPU still takes 99% to draw (which as you said is fine) and there is a delay but it never gets stuck in a long delay. The time it takes to draw a screen in full zoom out mode is consistent. 

In terms of suggestions of feature improvements for mobile devices, may I suggest the following for future consideration
1) When in zoom out view, some drawing optimization will help a lot --> especially avoiding redrawing items if there are items already drawn in that place (typical with zoom out situations where the data is more than the screen can show)

2) touch throttling as Alex points to above will certainly help

Thanks! Should I close this ticket or keep it open?

**Comment by AlexDM0** [comment]
Hi,

> When in zoom out view, some drawing optimization will help a lot --> especially avoiding redrawing items if there are items already drawn in that place (typical with zoom out situations where the data is more than the screen can show)

This is not really relevant. We do keep DOM elements so we don't delete and recreate them all the time but we don't "draw" anything. This is done by the browser. Apart from that, the redraws are only called if things have moved, so they will never be "in place" for partial redrawing. 

The fluidity of the touch devices causes a lot of draw calls. This cannot be avoided without throttling but throttling will cause a jittery experience. There is some automatic throttling in there (redraws do not stack I think). @josdejong could you share your opinion on this? Anything we can do to improve?

Regards

**Comment by pliablepixels** [comment]
>We do keep DOM elements so we don't delete and recreate them all the time but we don't "draw" anything. This is done by the browser.

Hello, yes I know. I should have reworded to say 'DOM optimizations' -  too many draws when there is no visual difference leading to performance issues, especially visible on mobiles. I know this possibly means more memory to keep a smaller list (visible DOM) in addition to the full list, but as far as my testing goes, memory is not the problem, CPU is. Thanks.

**Comment by josdejong** [comment]
Makes sense to enable throttling, shouldn't be too hard to implement.

**Comment by josdejong** [comment]
I've implemented throttling for the Timeline in the `develop` branch. You can adjust it like:

```js
timeline.setOptions({
  throttleRedraw: 10   // maximum one redraw every 10 milliseconds. Zero by default.
});
```

It's not yet working for Graph2d, the redraw of the SVG lines is now not in sync with redrawing the grid and axis.

**Comment by pliablepixels** [comment]
@josdejong  this is absolutely fantastic. I've set throttle redraw to 300 (as a test) and I see excellent and consistent  CPU performance - I see at full zoomed out view with 200 items CPU occasionally going to 99% but very quickly going down. Is it possible that threshold has improved performance even better than setting moveable: false, zoomable: false or are my eyes deceiving me?

**Comment by josdejong** [comment]
Ok great to hear that. And how is it doing with say 10ms throttle? 

I don't see a reason why the performance should have improved with `{moveable: false, zoomable: false}`, but if you really want to be sure you will have to do a benchmark :)

**Comment by pliablepixels** [comment]
I set it to 20 and the performance is comparable, actually. Incidentally, changing from 300 to 20 does not make the graph movement any more fluid, so I am going to keep it at 100. In mobile devices, the time  to redraw 200 nodes is the dominant delay so adjusting threshold for fluidity does not seem to matter much. What threshold is doing is eliminating the touch/gesture loops very effectively.

**Comment by AlexDM0** [comment]
Hi all,

This actually sounds like a deep bug. 

Jos maybe we should make sure that the redraw cycle cannot be started when there is one in progress? I assume that is what throttling does but I take it this works the same as dataset updates? You ask for a redraw, see one is already scheduled and ignore the request? If this is not the case it should be! A hard redraw can be very heavy indeed!

Regards

**Comment by josdejong** [comment]
@AlexDM0 there is only one place in Graph2d where this `redraw` is called outside of the "controlled" loop:

https://github.com/almende/vis/blob/master/lib/timeline/component/LineGraph.js#L136-L140

Do you know what this code was for? If I remove it, nothing breaks on first sight, but I guess it was there for a reason.

**Comment by AlexDM0** [comment]
that part is VERY important :) the graph2d draws on a screen that is 3 times the size of the visible timeline so scrolling is just an offset of that inner SVG DOM element. Those lines snap it back into place after the range has been changed. The redraw is required to reposition the SVG elements after shifting the container.

**Comment by AlexDM0** [comment]
this is the part where the shifting happens: 
https://github.com/almende/vis/blob/master/lib/timeline/component/LineGraph.js#L595

**Comment by josdejong** [comment]
> that part is VERY important :) 

hm, weird that I can't get Graph2d to break when removing this VERY important code ;)

anyway, we need to take a closer look at this.

**Comment by AlexDM0** [comment]
Maybe a redraw triggered somewhere else is sorting it out now, which was not the case when I made the graph2d?

The only other option is that resized is somehow always on in the redraw cycle that you're testing with, causing this line to reset the position:
https://github.com/almende/vis/blob/master/lib/timeline/component/LineGraph.js#L563

This needs to be sorted out, graph2d has not been updated for a while, even though timeline is actively worked on..

**Comment by AlexDM0** [comment]
Is this still an issue? There has been a lot of work done on graph2d...

**Comment by pliablepixels** [comment]
Alex, I am still using the old vis.js module from Aug 2015 - with that version -  drawing over 200 events on iPhone/Android make it unusable (but less than that is very usable). With desktops, it seems it is dependent on configuration, but a couple of thousand is where the line is drawn - see https://github.com/pliablepixels/zmNinja/issues/88#issuecomment-158511558


I'll grab the latest version and report in a few days.

**Comment by pliablepixels** [comment]
Wow, initial feedback is very positive. I just rendered around 900 events on my iPhone 5s and it handled it well. It used to choke on 200 in the earlier version. I am noticing an exception with 4.11 when there are no events - this was not occurring in the old version. I'll get to that later - but for now, initial testing shows significant improvement. I'll continue testing over the next few days.

**Comment by pliablepixels** [comment]
I am closing this. I've been handling 5000 events in my iPhone (within the ionic app) with ease. Incredible stuff folks from where the older release was (struggling with 300). Thank you!
