### ISSUE TITLE
Find a more user friendly way to dynamically adjust the max value of sliders in the configurator

### ISSUE THREAD

**Issue by josdejong** [almende/vis#1159]
As discussed in https://github.com/almende/vis/issues/1150, it would be nice to improve on the way the max value of sliders are scaled right now, as it's not very transparent what's happening.

**Comment by AlexDM0** [comment]
suggestions?

**Comment by josdejong** [comment]
- One possibility is to show a button `+` on the right of the slider which extends the max value with say `25%` when clicked. We could only display this button when the slider value equals the max value.
- We could make the text input displaying the value editable, so people can enter the value they like. If the value is larger than the max value of the slider, the max value is adjusted.

**Comment by AlexDM0** [comment]
I think I'll go with the + button. Thanks

**Comment by josdejong** [comment]
I would go for the editable input box, but it's no big deal to me.

**Comment by AlexDM0** [comment]
how about a small notification behind the input box explaining what happened? and set the snap at 85% instead of 50%?

**Comment by josdejong** [comment]
yeah but if you need to add a notification to explain something like this it may be a sign that it doesn't work intuitive enough on its own. Only having this behavior from say 85% would indeed help I think.

**Comment by AlexDM0** [comment]
I think this is in now
