### ISSUE TITLE
Timeline layout bug

### ISSUE THREAD

**Issue by daniel-pfeiffer** [almende/vis#1161]
Hi, I enable overflow and display this:

    [ { start: "2015-08-04 00:00", end: "2015-08-04 01:00", content: '1: scroll me out to the left' },
      { start: "2015-08-04 00:00", end: "2015-08-04 01:00", content: '2: scroll me out to the left' },
      { start: "2015-08-04 00:00", end: "2015-08-04 01:00", content: '3: scroll me out to the left' },
      { start: "2015-08-05 00:00", end: "2015-08-05 01:00", content: 'visible event' } ]

Something is **causing two empty rows** (for example – but more than a screen high empty when there are many events scrolled out).

Yesterday I thought the overflow area is responsible for reserving extra height even if the event itself is no longer visible.  But if so, the empty rows should at least collapse around when scrolling past 9:30 (the end of the overflowing text).  Now, when illustrating it, I had a different zoom level, and see in fact it only becomes correct around 20:00.  At different zoom levels it can happen even later than that.
![overflow-bug](https://cloud.githubusercontent.com/assets/9517524/9082242/f63b504e-3b62-11e5-8336-9a4ed975b53f.png)
Even with overflow turned off, it happens, but then the empty rows collapse a lot earlier.
regards -- Daniel

**Comment by josdejong** [comment]
Can you create a jsbin demonstrating the issue?

**Comment by daniel-pfeiffer** [comment]
http://jsfiddle.net/SQL_Steno/bapcqueq/
The 1st 3 events should stop affecting the total height once you scroll past 1:00.  But they are only ignored after about 7:30.

**Comment by josdejong** [comment]
Ah ok, I get it. This is the same issue as #1179.

This is because the items are drawn from the left of the timeline window minus 1/4th of the screen with to the right of the window plus 1/4th of the screen width.

**Comment by daniel-pfeiffer** [comment]
Since I occasionally need filtering anyway, I use a DataView with a permanent filter.  It does my stuff when I need it, but additionally there is an initial condition always filtering on the visible time range, to work around the above bug.  This causes a nasty bug that took me quite some time to understand:
In ItemSet.prototype._onUpdate you do
```javascript
      var itemData = me.itemsData.get(id, me.itemOptions);
      var item = me.items[id];
      var type = me._getType(itemData);
```
Now because of the itemOptions, when adding an item outside of the visible range, the 1st line returns null, and then the 3rd line throws.  This aborts rendering, leaving the timeline a mess (though if I rerender, it becomes nice again).

**Comment by josdejong** [comment]
I doubt if that is the cause: `me.itemOptions` is just making sure that `start` and `end` of the item are returned as a `Date`, it's not doing any filtering.

**Comment by daniel-pfeiffer** [comment]
I tried it in the console: `me.itemsData.get(id)` returns it, `me.itemsData.get(id, me.itemOptions)` returns null.

**Comment by josdejong** [comment]
That's odd. How can I reproduce that?

**Comment by daniel-pfeiffer** [comment]
I use a filter starting with (viewRange being my Angular wrapper ng-model for timeline range)
```javascript
function (i) {
		    if( i.end < $scope.viewRange.startDate || i.start > $scope.viewRange.endDate )
			return false;
```
The `items` are `new vis.DataView(myDataSet, itemsOpts )`.
And then I add to `myDataSet` several items, one of which is completely outside of the `viewRange`.  I have stripped that one down completely, it still caused a null exception in `_getType`.
The counter proof is that I have now instructed my server developer to send me only exactly the items in my requested viewRange (sending a few more was a bug on his side) after each `rangechanged`: The bug has disappeared ;-)
So if the above helps you, fine!  If not, I now have a workaround, so it's not urgent any more.
Thank you either way!

**Comment by josdejong** [comment]
I found the reason for this: the type of the fields `item.start` and `item.end` passed to `filter` can differ depending on where the filter function was called from: either the DataView or the update method in the Timeline. When you created your items with ISODates, like:

```js
var items = new vis.DataSet([
    {id: 1, content: 'item 1', start: '2014-04-20', end: '2014-04-23'},
    // ...
]);
```

The filter function can be called with this exact start and end values, but if an item is created/updated in the Timeline, the Timeline changes the start/end fields to a `Date`. So to solve this, you can either have the DataSet convert the dates internally to `Date`:

```js
var dataOptions = {
  type: {
    start: 'Date',
    end: 'Date'
  }
};
var items = new vis.DataSet([
    {id: 1, content: 'item 1', start: '2014-04-20', end: '2014-04-23'},
    // ...
], dataOptions);
```

or make your filter function robust against different types of dates:

```js
var moment = vis.moment;

function filter(item) {
  return moment(item.end) >= moment($scope.viewRange.startDate) && 
         moment(item.start) <= moment($scope.viewRange.endDate);
}
```

**Comment by daniel-pfeiffer** [comment]
Hi Jos, good on you!  Since our server is now giving what I want, I tried to reproduce the error situation by faking it client side -- alas to no avail.  But what you write makes sence, so I'll take your word for it ;-)
thanks -- Daniel

**Comment by yotamberk** [comment]
@daniel-pfeiffer  This issue is solved and in the `develop` branch. If you're still having this bug, please reopen this issue.
