### ISSUE TITLE
Network: Cannot toggle node shape

### ISSUE THREAD

**Issue by dragonzone** [almende/vis#1162]
Here is the example: http://jsbin.com/xibure/edit?html,output

When you select an icon, it will change to an icon, if you select another one, where the deselect will call the old node, it should change back to an circularImage, but it isn't.

**Comment by AlexDM0** [comment]
Hi,

I think you misread the docs: 

http://visjs.org/docs/network/index.html#event_deselectNode

http://jsbin.com/puyeqoboxi/1/edit?html,output

Regards

**Comment by dragonzone** [comment]
Now that it works, you may want to update the http://visjs.org/examples/network/nodeStyles/circularImages.html example, showing the different icon shapes vis.js handles. I plan to use this feature in our project.

However, in our project, the default will be an image and when selected, it will become a circularImage. Since in one of your posting, you said that I cannot put border around image. So when selected, I will turn it into a circular Image and put bolder borders around it so it stands out better.

**Comment by AlexDM0** [comment]
Hi, 

I'm not sure what you want me to update in that example. That example is used to show circular images. For this it is fine. 

In your case though, you may want to look into the render events to draw something behind your image to have it stand out?

http://visjs.org/examples/network/events/renderEvents.html

Regards

**Comment by dragonzone** [comment]
Yea, I saw that example and have used that idea to do our highlighting selection I mentioned awhile back, https://github.com/almende/vis/issues/977 (reading the last posting which I have the code), which I currently use in our network (it's a modified version). I wanted a simpler way just to configure or with a switch since our code is getting larger.

**Comment by AlexDM0** [comment]
We could look into making an extra image type "boxImage" which could have rounded corners like the box shape (configurable) and have a border?

**Comment by dragonzone** [comment]
Yes, that was what I am looking for, before, although you have lots of event, but some of those are used for some other purpose.

Network is a powerful tool, eventually, if all goes correctly, there will be lots of features, which you can't always let the event listener do b/c they are use for some other purposes.

BTW, I believe your tool is now consider a de facto in our organization. Before, we were competing with D3.js, but shortly after I join and utilize your tool, they went with this. It is currently in use, users love it w/ all the tools and features I built for them. Kudos to you guys for making the network to be easily use and good documentation..

**Comment by AlexDM0** [comment]
Glad to hear that!

A note on the events though, you can stack them! 

You do not have to make one handler for the events:

```
network.on("click", function() {/*do something*/});
network.on("click", function() {/*do something else*/});
```

This could make the code much cleaner!

Regards

**Comment by dragonzone** [comment]
Also, we have some timeline feature in our app, however I was not the main developer for it, someone else was. They went with another tool which they picked instead of your Vis Timeline (which I mentioned to them). You can take a look and see. http://www.highcharts.com/stock/demo

Hopefully by looking at some of their examples, this will give you guys some idea how to improve the timeline. Good luck.

**Comment by AlexDM0** [comment]
Hi,

The graph2d is in dire need of an update and a decent expansion of features. Most of all it needs to be completely redesigned. Our timeline is different from the Graph2d, I assume you're referring to that module.

Regards

**Comment by dragonzone** [comment]
I remember talking w/ our main developer of our timeline feature. I believe he said he look at both timeline and Graph2d. He said it still did not impressive him as Highstock. Not enough interactive features. So, as a suggestion, when you guys have time go through some of the demo from the link I mentioned and see all the interesting features they have and see if you can incorporate them into yours.
