### ISSUE TITLE
Network: node label styling

### ISSUE THREAD

**Issue by dragonzone** [almende/vis#1163]
When a node is selected, the label is automatically in bold black. Is there a way to change it to increase the font and change the color of the label to say red or green so that it will stand out?

**Comment by AlexDM0** [comment]
You can use the select event to set the font colour or size of the specific node. 

Regards

**Comment by dragonzone** [comment]
Yea, I was wondering if I can just config it instead of having another listener event do it.

**Comment by AlexDM0** [comment]
Hi,

If we were to make special options for everything we would get a horrendously huge set of options that cannot be maintained, tested or documented.

Callbacks and events wherever possible :)

Regards

**Comment by dragonzone** [comment]
You already have a huge set of options, that are powerful, which I love. :D
