### ISSUE TITLE
Timeline documentation issue: setWindow(...) animate, NOT animation

### ISSUE THREAD

**Issue by mast0r** [almende/vis#1166]
I've just realized, why I can't turn animation off while zooming or moving the timeline useing method `timeline.setWindow(...)`

The documentation says: `animation: boolean or {duration: number, easingFunction: string}`

So I've tried to use it like this:
`timeline.setWindow(start, end, { animation : false });`

But that didnt work! Only today purely by chance I found an old issue with Jos's comment where he used another syntax for the parameter:
`timeline.setWindow(start, end, { animate : false });` https://github.com/almende/vis/issues/541#issuecomment-69541668

I've tried it again like Jos and now it works well... So the right syntax for animation parameter should be:
setWindow(start, end,  { **animate** : false })

Guys, please correct the timeline documentation. Many Thanks!

**Comment by AlexDM0** [comment]
Hi,

Which version of vis are you using? The documentation is only ever for the newest version. For old docs you can download them bundled with the files on the releases page of git. 

Regards

**Comment by mast0r** [comment]
Right, shame on me :) 
I am using 3.12.0 and the docs are okay for this version (animate, not animation).
