### ISSUE TITLE
Check for overlapping range items

### ISSUE THREAD

**Issue by marcortw** [almende/vis#1168]
Is there a built-in possibility to check if a range item overlaps with another item after a rangechanged event? I can currently only think of iterating through all my items within my onMove function. It would actually be nice if it was the other way round. An existing item on the timeline would fire a callback function itself (e.g. onOverlap) when another item overlaps.

**Comment by josdejong** [comment]
There is no such built in functionality, as this sort of logic is typically quite application specific. The right way would indeed be to loop over your items and see if they overlap with the dragged item. Shouldn't be that complicated. I'm not sure about and event like `onOverlap`: this could be fired from multiple items at the same time, it would be hard to keep control and prevent unstable situations.

**Comment by marcortw** [comment]
Thanks, you're probably right that it's too application-specific and handling the events would be complicated.

**Comment by josdejong** [comment]
Ok then, good luck with it. Thanks for your input.
