### ISSUE TITLE
Compatibility with Kibana 4.0

### ISSUE THREAD

**Issue by aacamp** [almende/vis#1169]
Is there a simple way to get vis.js to work well with a large scale open source project like Kibana? I have a simple network model built with vis externally, but I have tried with no avail to get it to work internally in Kibana.

The problem I am having is getting the vis.js and vis.css files to load properly. I have no issue actually loading them in the proper order (tested with FireFox developer). But, I get a reference error for vis not being defined. So, clearly it is not loading properly. 

script src includes are not compatible with Kibana and I have tried to use require.js to include vis but still isn't working. Any advice? I am new to web dev.

Thanks!

**Comment by josdejong** [comment]
If I understand it correctly you have troubles loading vis.js in your webpage using require.js, which not related to Kibana. There is an example showing how to load vis.js using require.js:

http://visjs.org/examples/timeline/other/requirejs/requirejs_example.html (live)
https://github.com/almende/vis/tree/master/examples/timeline/other/requirejs (source)

Does that help?
