### ISSUE TITLE
Automatic updation of Node coordinates inside a cluster when cluster is dragged

### ISSUE THREAD

**Issue by bharatjosh** [almende/vis#1171]
Hi,

I have started using clusters for a big network. Currently, if I move cluster from one location to another and then open the cluster, nodes inside the cluster move to their old position.

Is there any settings that can be used to move nodes inside a cluster also if the cluster is dragged to a different location?

If there is no such settings available, is there a plan to do this?

Regards,
Bharat

**Comment by AlexDM0** [comment]
Hi,

Please refer to the documentation of the openCluster method. It has a releaseFunction option just for this. 

Regards

**Comment by bharatjosh** [comment]
Hi,

Thanks for the quickest response I have received when I raised an issue anywhere.

I had looked at the releaseFunction and I agree that this can be used to update Node's coordinates but what I am looking for is an automatic update.

Let me quote an example. Let us assume there is a cluster with 1 node in it. Cluster is Cx, Cy and node is at Nx, Ny. When we move cluster to Cxx and Cyy position, it is displaced by (Cxx - Cx), (Cyy - Cy) so when we open the cluster, if a setting is enabled, node automatically moves to (Nx + (Cxx-Cx), (Ny + (Cyy-Cy).

Another way could be that we keep relative coordinates of node with respect to cluster node and when we open cluster, we use releaseFunction to update each node coordinates based on cluster nodes coordinates and add relative coordinate of each node.

What do you think?

Your advise will be very useful. Thanks a lot in advance for your time.

Regards,
Bharat

**Comment by AlexDM0** [comment]
Hi,

When you make a cluster, you can store its position. On opening use that and its current position to do the offset. 

It will be automatic, just not out of the box. 

We could maybe add the position when the cluster was created to the list of arguments in future releases. 

Regards

**Comment by bharatjosh** [comment]
Hi,

Thanks for your response.

I will try this out and let you know how I could do it.

For me, I am planning to put the cluster 'x' and 'y' in backend so that I can get the same map on every load if someone has arranged the cluster to his/her choice. So I will have this information available but it would be good to have it during the creation also.

Regards,
Bharat

**Comment by AlexDM0** [comment]
Hi,

You cannot load clusters using the normal setData or the constructors. The clusters have to be created after initialization. Just something to keep in mind. We do want to allow clusters during construction later on.

Regards

**Comment by bharatjosh** [comment]
Hi,

Yes, I understand this. Will keep it in mind.

I am closing this issue.

Thanks a lot for your time and advise on this.

Regards,
Bharat
