### ISSUE TITLE
Hierarchical network with nodes in LR and RL

### ISSUE THREAD

**Issue by AlexZeitler** [almende/vis#1172]
Is it possible to create a hierarchical network with nodes in LR and RL at the same time (the nodes should not be mirrored)?
![image](https://cloud.githubusercontent.com/assets/287480/9142344/5cdadd5a-3d3f-11e5-870e-7342a79d4ef6.png)

**Comment by AlexDM0** [comment]
Hi,

This is not possible... You could manually allocate the levels and inverse them for one set of the nodes. 

Regards

**Comment by AlexDM0** [comment]
Sorry, the image loaded in later and I misunderstood. 

You can do this if you manually allocate the levels. Directed method could work but I can't see how your edges flow in this network. 

Regards

**Comment by AlexZeitler** [comment]
@AlexDM0 Thanks for your fast reply.
The edges flow from the centered `2` to the right as well as to the left.

**Comment by AlexDM0** [comment]
In that case, you'll have to manually setup the levels. 

Regards

**Comment by AlexZeitler** [comment]
Thanks. That means I also have to position all nodes manually?

**Comment by AlexDM0** [comment]
Hi,

No just the levels. Pick one side, the first one is level 0. Set it to LR and count from the left. 

Regards

**Comment by AlexZeitler** [comment]
Thanks, got it:

````js
for (var i = 0; i <= 4; i++) {
    nodes.push({id: i,label: String(i)});
}
edges.push({from: 0, to: 2 });
edges.push({from: 1, to: 2 });
edges.push({from: 2, to: 3 });
edges.push({from: 2, to: 4 });
nodes[0]["level"] = 0;
nodes[1]["level"] = 0;
nodes[2]["level"] = 1;
nodes[3]["level"] = 2;
nodes[4]["level"] = 2;
````

![image](https://cloud.githubusercontent.com/assets/287480/9149873/6c059fb0-3dbf-11e5-8f1f-640fb9f645d0.png)
