### ISSUE TITLE
Drag the Entire 3d graph

### ISSUE THREAD

**Issue by nithingit** [almende/vis#1176]
Is it possible to drag the entire 3d graph.For example-- if I zoom the graph I cannot see the entire graph.Is there an option to drag the graph to its left ,right and so on.

**Comment by josdejong** [comment]
There is no functionality to drag the Graph3D left/right/up/down, but what you could do is create your own navigation buttons (left, right, up, down) and call `graph3d.setOptions({xCenter: '50%', yCenter: '45%'})` and change the center position dynamically that way by setting an other percentage.

**Comment by mojoaxel** [comment]
This was implemented with #2357
