### ISSUE TITLE
How to set range of right axis?

### ISSUE THREAD

**Issue by mrquincle** [almende/vis#1177]
It seems to be the case that setting the range of the right axis shouldn't be done like this:

```
var options = {                                                                                                         
  drawPoints: true,                                                                                                     
  dataAxis: {visible: true,                                                                                             
    left: {range: { min: -2, max: 3} },                                                                                 
    right: {range: { min: -2, max: (3-2)} }}, // mistake in max?     
```

Because to get a `max` value of `3`, I'll need to set it to `3+left.range.min`.

You can see the result in http://www.annevanrossum.com/blog/2015/08/08/legendre-transform/ and the code in http://www.annevanrossum.com/javascripts/legendre.js.

**Comment by AlexDM0** [comment]
Hi,

That's a cool application! We could add it to the vis showcase if you'd like?

http://visjs.org/showcase/index.html

We'll look into the issue as soon as we can, it's quite busy lately :)

Regards
