### ISSUE TITLE
Network - click event - nodeValues

### ISSUE THREAD

**Issue by dockstreet** [almende/vis#1178]
For the click event we get back the nodeIds & edgeIds.

Can the Node and Edge values come back as well? Not sure how to easily cross reference the node and edges to the Ids, without extra effort? Could just be user error on my part. 

Something like ? returning maybe an array of objects instead of just ids?
{
  nodes: [Array of selected nodeIds - nodeValues],
  edges: [Array of selected edgeIds - edgeValues],
  event: [Object] original click event,
  pointer: {
    DOM: {x:pointer_x, y:pointer_y},
    canvas: {x:canvas_x, y:canvas_y}
  }
}

**Comment by AlexDM0** [comment]
Hi,

If you were to use the vis dataset for the nodes and edges as shown in all our examples you could do: 

Nodes.get(nodeId)

This is the reason we only give the ID. 

Regards,

Alex
