### ISSUE TITLE
Will it be possible to use HTML template via URL in content?

### ISSUE THREAD

**Issue by maximou4391** [almende/vis#1181]
Hi, my name is Maxime and I'm a beginner programmer using vis js timeline and I wanted to know if it will be possible to load html template from a given url into the timeline item content?

Thanks a lot.

**Comment by maximou4391** [comment]
Another problem is also to be able to put scope data inside the content of an item. It will be so perfect :)

**Comment by AlexDM0** [comment]
Hi,

I assume you figured this out by the examples? 

Regards

**Comment by maximou4391** [comment]
Yes that's true :) sorry about that


Sent by Outlook for Android





On Tue, Aug 11, 2015 at 12:20 PM -0700, "Alex" <notifications@github.com> wrote:
Hi,

I assume you figured this out by the examples?

Regards

---
