### ISSUE TITLE
Timeline: custom properties for the item

### ISSUE THREAD

**Issue by mast0r** [almende/vis#1182]
Is it possible to add custom properties to the item object? 
Many thanks!

**Comment by josdejong** [comment]
Yes, you can just add whatever properties you like to item objects, the Timeline just ignores them. Just try it :)

**Comment by mast0r** [comment]
Ahhh.... :100:  The item object is still a javascript object. I tink I need to take a pause...
Many Thanks Jos!

**Comment by josdejong** [comment]
If you need to use these custom properties what you display as item `content` in the timeline, you may be interested in using templates: 

example: http://visjs.org/examples/timeline/styling/itemTemplates.html
docs: http://visjs.org/docs/timeline/#Templates
