### ISSUE TITLE
add label to edges in 'from'、'to'、'middle' 

### ISSUE THREAD

**Issue by kevindu1993** [almende/vis#1184]
i want to add 3 labels at an edge in 'from'、'to'、'middle' places respectively, is there any way to handle this problem?

**Comment by AlexDM0** [comment]
Hi,

You can use the render events to draw your own stuff:
http://visjs.org/examples/network/events/renderEvents.html

We do not support multiple labels anywhere, nor do I think we will. I personally also think it is very bad design as it will clutter up your network. The text will overlap with nodes and edges, making it an illegible mess. I would suggest going for a popover type solution for more information.

Regards

**Comment by kevindu1993** [comment]
thank you~
