### ISSUE TITLE
[Timeline] : Static heights for non-stacked groups

### ISSUE THREAD

**Issue by DChau10** [almende/vis#1186]
I just started using the Timeline and really enjoy working with it. However, one thing that I'd like to see is the ability to maintain a height for a group even  when none of its items are currently displayed in the window. The default behavior is to collapse the group, but that doesn't work for my use-case. I am working with a table and timeline and the rows become misaligned when this collapsing occurs.

Additionally, I'd like to see the ability to keep the axis header in place while the rest of the content scrolls.

When at least one item is displaying in every group:
![timeline - desired](https://cloud.githubusercontent.com/assets/2339766/9261839/e3739efa-41cd-11e5-8aec-abcd5752da9d.png)

When no items are being displayed in some groups:
![timeline - misaligned](https://cloud.githubusercontent.com/assets/2339766/9261846/f2ee2b84-41cd-11e5-9823-d58bdc7017f0.png)

**Comment by josdejong** [comment]
The height of a group is determined by the max of the group label height and the height of the (stacked) items of the group. If you want to keep some minimum height for the group, you can for give the group label this required height.

If you mean the time-axis with "axis header", you can do so by giving the Timeline a limited height, look up the options `height` and `maxHeight`. If the content's do not fit, the contents will become scrollable.

As for the vertical scroll bar: I guess something is messing up here. vis.js itself doesn't show a scroll bar here. Do you have an unmodified version of vis.js? Or can it be that there is some conflicting CSS in your application?

**Comment by DChau10** [comment]
Thank you for the response! I did as you suggested with setting a min-height on the group label. However, is there a way to enforce this if there is no content for the group label? As you can see in my example, I have no group label. That being said, the styling rules don't seem to apply when there is no content being displayed. Even when I put something like an empty div in the group content, it doesn't register the styling. So far, putting the group numbers in the label has worked, but I'd really like to avoid that.

As for the timeline, I think maybe I miscommunicated. I'm interested in making the time-axis stay in place while the actual group content scrolls vertically. As you said, vis.js doesn't show a scrollbar. So for the time being, I have applied "overflow:scroll" to my timeline container. As a result, the entire timeline scrolls within my container--whereas ideally, vis.js would have its own scrolling mechanism to ensure that content is scrollable when it has more content than it can display based on the container's height.

I'm simply stating that in addition to the often requested scrolling feature, I would like to see the ability to keep the time-axis fixed in place while the groups/items are vertically scrollable.

The image below shows what I'm after. The blue 'containers' stay static while the red 'containers' scroll.

![timeline scroll](https://cloud.githubusercontent.com/assets/2339766/9275293/4d25ad58-4259-11e5-9251-0714165a4f81.png)

**Comment by josdejong** [comment]
> is there a way to enforce this if there is no content for the group label?

You can try something like `.vis-label .vis-inner {min-height: 100px;}`.

When the height of the Timeline is fixed and contents do not fit, the contents become vertically scrollable and the time-axis *is* fixed in place. Until the vertical scrollbar is implemented by Timeline itself, there was a hack posted for making a vertical scrollbar visible in one of these topics about vertical scrolling which you could use.

It's not clear to me though why you don't use the group labels of the Timeline to display your "table header" with dates, and create a separate left panel with a list with dates instead. This second panel complicates your life way quite a bit.

**Comment by DChau10** [comment]
Thank you! That css worked just as you said.

I will have to dig around and find the hack for vertical scrolling until it is embedded into the Timeline, itself.

What you do not see in the image that I've provided is that there is a lot of other data in the left-hand table. This is a server-paginated table of 10+ columns. My table pictured on the left does have a row label, so there is--at the moment--not a purpose for me to use the group labels on the Timeline. However, I do appreciate your concern. There are reasons for which I could not share this entire table.

**Comment by yotamberk** [comment]
@DChau10  `verticalScroll` is now an option in v4.17.0! You are welcome to try it out =)
