### ISSUE TITLE
[Timeline]: Hide overlapping items instead of stack them

### ISSUE THREAD

**Issue by allayli** [almende/vis#1187]
Hi,
Currently, the timeline can set the options "stack" to stack items, but there is no way to hide those items. It will cause lagging when there are many items (above 5000).
Any other suggestion for handling huge number of items?

Regards

**Comment by allayli** [comment]
Is there any suggestion for handling huge number of items?
Would the Timeline be drawn via canvas?
Thanks.

**Comment by josdejong** [comment]
There are performance improvements possible by only rendering items and/or groups which are visible vertically. Currently only the horizontal visibility is taken into account when determining which items to render.

If you need to handle thousands of items you have two problems: the browser can't handle it, and it's just too much information to present to a user. There is only one solution: display less items. one solution would be to display a different level of detail when zooming in/out. You can listen for the `rangechanged` events and when zooming out, display daily/weekly/monthly averages or something.

**Comment by allayli** [comment]
Thanks, @josdejong .
I try to use `setItems()` to render less items when `rangechanged` event is triggered. It works fine, expect when zooming out mutually using `setWindow()`. So I call `setItems()` before `setWindow`. Is it expected?
Looking forward to more improvements! Thanks again!

**Comment by josdejong** [comment]
Ok great. What goes wrong exactly when calling both `setItems` and `setWindow`?

**Comment by yotamberk** [comment]
@allayli vertical hiding of items has been implemented in v4.17.0. performance has improved immensely. Hope this is sufficient for your needs =)

**Comment by yotamberk** [comment]
@mojoaxel this issue is kind of weird. The real solution is to loading less itema at a time (as jos recommended). The vertical hidden items intriduced helps the performance of the timeline. I think this issue is irrelevant

**Comment by mojoaxel** [comment]
@yotamberk I think the issue is hiding items that are covered by other items. These are not out of the view and therefore not hidden by the new functionality. Not sure if we should close this one...
