### ISSUE TITLE
Migrating Network JSON from 3.x to 4.x

### ISSUE THREAD

**Issue by Lennyman** [almende/vis#1188]
Hi there,

Do you have a 'simple' cheat sheet to identify what objects/JSON markup has changed between 3.x and 4.x (mainly on 'Network') - I only just finished coding under 3.x when the 4.x was released, so I have a ton of code to go back through and any assistance would be appreciated.

I know you have the hints to show changes, but a crib-sheet would be good.

Regards,

Paul

**Comment by AlexDM0** [comment]
Hi,

We don't have that. The changes are quite substantial, but the option suggesting should help. The documentation is ample so it shouldnt be too difficult to get everything working.

Regards,

Alex
