### ISSUE TITLE
Edge label

### ISSUE THREAD

**Issue by Chroedde** [almende/vis#1190]
Hi,
Unfortunately you deleted my last question. I think it isn't a pure JavaScript question:

1) My json file is completely fine. I also tested it with json editor online.
2) Look at the Gephi-exported json file you have in your examples (http://visjs.org/examples/network/data/importingFromGephi.html). It has the same structure ("source" instead of "from", "target" instead of "to", "attributes", etc.) and it works fine.

But why doesn't vis import the edge labels?

I really would be happy if you could help me.

Best regards
Christoph

**Comment by Chroedde** [comment]
I got it.
Just add:
	  edge['label'] = gEdge.label;
at line 41821 of vis.js

However, thank you!

BR
Christoph

**Comment by Chroedde** [comment]
And maybe also: 	  edge['title'] = gEdge.attributes.title;

**Comment by AlexDM0** [comment]
That does not sound like a fix.. If you can share your JSON data we can check what's going wrong. 

Regards

**Comment by AlexDM0** [comment]
Let's continue this in #1189
