### ISSUE TITLE
network setOptions: font changes not propagated

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#1192]
Hi @ devteam,

I noticed that when using setOptions on font properties, the changes are not reflected in the graph. For an example see http://visjs.org/examples/network/other/configuration.html and change the font config (e.g. size).

Other changes like shadow etc. work fine.

Thanks
-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

I noticed this too and I've fixed it for the next release. Thanks for reporting!

Regards

**Comment by felixhayashi** [comment]
Much thanks Alex!

**Comment by AlexDM0** [comment]
fixed in 4.8
