### ISSUE TITLE
How to increase vertical space between timelines

### ISSUE THREAD

**Issue by miguelpragier** [almende/vis#1194]
Hi all.

I have a single container with several timelines.
How to customize/increase the space between those timelines?

I've tried $(timeline).css('margin-bottom','20px'), but without result, and unsure about to be the best approach.

Thank you in advance!

Best,

Miguel
![howtoincreasethatspace](https://cloud.githubusercontent.com/assets/555840/9313816/785f5182-44fb-11e5-8352-84c063111e26.jpg)

**Comment by josdejong** [comment]
The container of a Timeline has a class name `vis-timeline`, so you can set a margin-bottom for this class.

**Comment by miguelpragier** [comment]
Yeap, that solution worked nicely!
Thank you very much!
