### ISSUE TITLE
[Timeline] Stack items the way earlier items always go before later ones

### ISSUE THREAD

**Issue by artim** [almende/vis#1195]
Hi, I do not have any custom order function. But I still want timeline to stack items according to order by their start time. So look at the screenshot

![pic1](https://cloud.githubusercontent.com/assets/3962010/9327060/f0b324c8-45a6-11e5-9578-c406cd816902.PNG)

but for me it could be better if it looked like the following

![pic2](https://cloud.githubusercontent.com/assets/3962010/9327103/1f050f94-45a7-11e5-8d3f-07bb09def130.PNG)

Currently I just ordered items by start before sending in to stack function in Group.prototype.redraw

// no custom order function, lazy stacking
this.visibleItems = this._updateVisibleItems(this.orderedItems, this.visibleItems, range);
stack.orderByStart(this.visibleItems);

because _updateVisibleItems returns items disordered by start time

**Comment by josdejong** [comment]
> Hi, I do not have any custom order function. But I still want timeline to stack items according to order by their start time. 

To achieve what you want you have to provide a custom ordering function (option `order`). Why don't you use this?

**Comment by artim** [comment]
I'm not sure why should I provide custom order function (by start time) since they are already ordered by start time. And from your documentation it is not recomended -

 'WARNING: Use with caution. Custom ordering is not suitable for large amounts of items. On load, the Timeline will render all items once to determine their width and height. Keep the number of items in this configuration limited to a maximum of a few hundred items.'

**Comment by josdejong** [comment]
The Timeline does not render the items from start to end. On initial draw, it will filter the visible items and render these ordered from start to end. When moving/zooming the timeline and new items become visible, the timeline will leave the rendered items as they are, and find a new (stacked) position for the new items. This is important for performance, and prevents items from "jumping" to new stacking levels all the time when new items become visible on the left side.

**Comment by robinp** [comment]
Not strictly related, but for posterity I remark that the margin added to the events can also cause them to jump out-of-order when tightly packed. Can be mitigated somewhat by setting the margin option to near-zero.

**Comment by mojoaxel** [comment]
@artim Is this issue still relevant?

**Comment by yotamberk** [comment]
closed due to inactivity. If still relevant, please reopen.
