### ISSUE TITLE
Draw a Network using JSON (datasource)

### ISSUE THREAD

**Issue by devgitk** [almende/vis#1196]
Hi,
Just wanted to know if we will be able to load/parse a JSON containing Nodes and Edges and draw a Network. Looking for a straight forward simple approach! 
- Checked the 'World cup' example and seems like the data is getting loaded from a JS library.
- JSON looks like : 
 {
    "nodes": [
        {
        // Node properties
        }
    ],
    "edges": [
        {
        // Edge properties
         }
    ]
 }

Thanks

**Comment by Tooa** [comment]
This is more like a pure Javascript question. You can parse a string as json with `JSON.parse()` [1].  

[1] https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse

**Comment by AlexDM0** [comment]
Hi, 

I think Uli is right, this is a JavaScript question. The worldcup is using AJAX to get a json file. 

If you look at our documentation and any of the other examples it should answer your question. 

Regards

**Comment by devgitk** [comment]
@Tooa  : What I meant was, I already have a JSON file and I want to load that file which contains the nodes and edges and draw a network. Does vis js support this? is there any library to load JSON apart from the normal JS and jQuery JSON parsers?

**Comment by Tooa** [comment]
What's wrong about using jQuery as external dependency? You could also use it to load the JSON from a file:

     $.getJSON("yourfile.json", function(json) {
         //here you can use your json
     });

Visjs doesn't offer such a feature and it's unlikely to get such a feature implemented in future. There is just no need, because the library is about visualization and not loading content from files. 

[1] http://api.jquery.com/jQuery.getJSON/

**Comment by AlexDM0** [comment]
I would even go as far as to say it's rediculous to use a library for this (unless you already use one for other purposes). 

https://github.com/almende/vis/blob/master/examples/network/exampleUtil.js#L5

We provide the function we use, it's pure JavaScript and only a few lines. No dependencies at all. 

This will never get into vis itself for the exact reasons mentioned by @Tooa

Regards,

Alex

**Comment by devgitk** [comment]
@Tooa  & @AlexDM0  Thanks for ur time :)

**Comment by victoriastuart** [comment]
Good question, poor answers.  See a working solution, here (StackOverflow 42722856): [import json file to create a network in vis.js](https://stackoverflow.com/questions/42722856/import-json-file-to-create-a-network-in-vis-js/50591818#50591818)
