### ISSUE TITLE
Custom network edge 

### ISSUE THREAD

**Issue by PMaynard** [almende/vis#1197]
Hey, 

If there is an IRC channel please send me there and delete this.

I'm looking to generate a graph with custom edge arrows. In which the edge points to another edge. See below picture. 

![Example of edge pointing](http://port22.co.uk/images/SAND.png)

So how I'd explain the above image, is that there are three nodes and three edges. ftp and rsh have edges to the root node. Then there is a third edge which points from the ftp->root edge to the rsh->root edge.

Is this possible, make any sense?

**Comment by AlexDM0** [comment]
Hi,

This is not possible I'm afraid.. You could try the renderEvents (http://visjs.org/examples/network/events/renderEvents.html) to implement it yourself but I cant promise anything.

Good luck!
