### ISSUE TITLE
clone.mlliseconds is not a function

### ISSUE THREAD

**Issue by SuberFu** [almende/vis#1200]
This bug occurred when using the Timeline module.
There appear to be a typo in TimeStep.snap function (line 19165 in vis.js) where it's trying to call clone.mlliseconds(0).

Should it be clone.milliseconds(0)?

**Comment by softwarespot** [comment]
Yeah I just was about to report this issue too.

**Comment by josdejong** [comment]
Thanks for bringing this up. This issue is fixed in the `develop` branch, see https://github.com/almende/vis/pull/1146. We expect to do a release containing this fix next week.
