### ISSUE TITLE
Exclude groups from legend

### ISSUE THREAD

**Issue by Bernd0** [almende/vis#1202]
Hi,

is it possible to exclude a group from being displayed in the legend?

I'm using two additional groups to display a min and max value. But this groups should not appear in the legend.

![image](https://cloud.githubusercontent.com/assets/13885946/9382257/6446a362-473f-11e5-823f-a09ab5787a28.png)

**Comment by AlexDM0** [comment]
Hi,

At the moment, no. You could however take a look at the external legend example and make your own legend using that. 

Regards

**Comment by Bernd0** [comment]
Hi,

I just modified the source of visjs to avoid adding a group into the legend. But this will be broken if I update to a new release of visjs.

I'm simply checking if the group content is an empty string to avoid adding it. But I think it would be better for backward compatibility to introduce a new group option like 'excludeFromLegend: true'.

Any chance that this feature make it into a future release?

Regards

**Comment by AlexDM0** [comment]
Hi,

The graph2d is planned for a very large redesign. Until then I'm not sure if we'll add many new features. 

If you want to implement it yourself though, I'd be happy to merge it in. 

We accept pull req to the develop branch. 

Regards

**Comment by Bernd0** [comment]
Hi,

I created a pull request.

Regards
