### ISSUE TITLE
X and Y coordinates on hoverNode event

### ISSUE THREAD

**Issue by devgitk** [almende/vis#1203]
Hi,

Any idea as to how I would be able to get the X and Y coordinates of the node on hover?

Thanks!

**Comment by AlexDM0** [comment]
Hi,

Let's go look at the documentation:
http://visjs.org/docs/network/#methods

It would be something along the lines of "get a position" and then you'll have to transform the canvas coordinates to the DOM space, maybe something like canvasToDOM.

Now there are events for hover, like http://visjs.org/docs/network/#Events

Please refer to the documentation for more information.

Regards

**Comment by devgitk** [comment]
@AlexDM0  : I would want the X,Y coordinates on hoverNode event. Went through the doc, not sure as how ill be able to implement with the mentioned methods. Any help is much appreciated!

Cheers.

**Comment by AlexDM0** [comment]
Hi,

Take a look at the events example. 

Regards
