### ISSUE TITLE
How freeze coordinates of all nodes, but stay elastic all connectors.

### ISSUE THREAD

**Issue by NTMan** [almende/vis#1204]
How freeze coordinates of all nodes, but stay elastic all connectors.
I want same behavior: http://gojs.net/latest/samples/stateChart.html

var options = {physics: {enabled: false}};
freeze and connectors too :(

**Comment by AlexDM0** [comment]
Hi, the edges and nodes are moved by the physics and indeed, if you turn physics off altogether the edges will also not adapt anymore. 

There are a few ways to handle this. One is using different types of edges. All edge types except the dynamic ones are not using the physics for their shape. 

Another is to disable the physics on all nodes: setOptions({nodes:{physics:false}})

And finally you can fix the nodes in place: setOptions({nodes:{fixed:true}})

If the nodes are fixed, you can not drag them. 

Hope that helps. 

Regards

**Comment by NTMan** [comment]
Thanks, but how make curved connectors?

I want get same result with vis library:

![screenshot from 2015-08-24 05-03-14](https://cloud.githubusercontent.com/assets/200750/9436799/644416f4-4a6b-11e5-95bf-76370d8cc9c7.png)

**Comment by NTMan** [comment]
Actual result:

![screenshot from 2015-08-24 05-02-46](https://cloud.githubusercontent.com/assets/200750/9436821/83e0d876-4a6b-11e5-9c09-9288cd59dee2.png)

**Comment by AlexDM0** [comment]
Hi,

We have a range of smooth curves:
http://visjs.org/examples/network/edgeStyles/smooth.html

Regards

**Comment by NTMan** [comment]
Thank you, already much better.

![screenshot from 2015-08-24 14-33-02](https://cloud.githubusercontent.com/assets/200750/9437253/b79b15a2-4a6e-11e5-8ce4-72d0974f6c7c.png)

But if set curve manually it turns out better.
Is it possible to define curve manually (WYSIWYG)?

**Comment by AlexDM0** [comment]
Hi,

No that is not possible. I would expect the best result for your graph is using the nodes:fixed:true and using the dynamic edges type. You can play with the physics to get the "roundness" you want.

Regards

**Comment by NTMan** [comment]
If I will use option nodes:fixed:true I not able to arrange nodes.

![screenshot from 2015-08-24 14-54-55](https://cloud.githubusercontent.com/assets/200750/9437540/75c30138-4a70-11e5-8dd6-516b46c39a41.png)

in initial state they not have coordinates.

**Comment by AlexDM0** [comment]
Well yes, you'll have to listen for the stabilize command before changing those settings. You can also listen to the dragStart event to momentarily set fixed: false for the node you're dragging.

**Comment by NTMan** [comment]
Please, can you show example. I read documentation http://visjs.org/docs/network/#Events
And see that options not available from functions `params`.
```
{
  nodes: [Array of selected nodeIds],
  edges: [Array of selected edgeIds],
  event: [Object] original click event,
  pointer: {
    DOM: {x:pointer_x, y:pointer_y},
    canvas: {x:canvas_x, y:canvas_y}
  }
}
```
And I don't have idea how call `setOptions` function in anonymous function without network object.

**Comment by AlexDM0** [comment]
Hi,

I'd suggest you read up on javascript scoping. The events give you the ids of all the affected items. In this case you'd need the node Id

Take a look at #939 

That jsbin has code that does exactly that. 

Regards

**Comment by NTMan** [comment]
Not a good example because in order to access a particular Node is required to store the data in the global scope.
It would be better if the function has received instead of list of Nodeid, list of Nodeobj.
```
  network.on("dragStart", function(properties) {
    if(properties.nodes.length) {
      var node = data.nodes.get(properties.nodes[0]); 
      setNodesMoveable([ node ], true);
    }
  });
```

here `data.nodes` is in global scope


if `properties.nodes[0]` will be node obj I can write:

```
  network.on("dragStart", function(properties) {
    if(properties.nodes.length) {
      var node = properties.nodes[0]; 
      setNodesMoveable([ node ], true);
    }
  });
```
and global scope is not needed

**Comment by AlexDM0** [comment]
Feel free to improve this yourself. It is an example, do with it what you want.

**Comment by NTMan** [comment]
Thank you, I understood with an example.
I do not understand why only
```
network.on ("stabilized", function (properties) {
if (! hasNetworkStabilized) {
hasNetworkStabilized = true;
network.storePositions ();
setNodesMoveable (data.nodes.get (), false);
network.fit ();
}
```
});
triggered immediately and does not allow the scheme to expand:
http://jsbin.com/guside/2/edit?html,output

Result was a bit better but for the connectors between far placed nodes "too tense".
![screenshot from 2015-08-24 18-34-26](https://cloud.githubusercontent.com/assets/200750/9441543/3ddf95a4-4a90-11e5-9c30-81e48ec34c8f.png)


Can't I write issue for feature request for manual control curvature of connectors?

**Comment by NTMan** [comment]
Example with real data:
http://jsbin.com/pejohi/3/edit?html,output

**Comment by AlexDM0** [comment]
There is a bug in the current network, firing the stabilised event before initialising, this is fixed in the next release.

We have a roundness options for all non-dynamic smooth curve types. We will not provide more control then this. For now, try listening to the stabilizationIterationsDone event.

Regards

**Comment by NTMan** [comment]
Alex, can you add new type of smooth similar cubicBezier, but having two separate roundness settings for start and end arrow?

I want reproduce this kind of editing: https://drive.google.com/file/d/0B0nwzlfiB4aQcDZ6M3lwY0hwZFU/view?usp=sharing on visjs library.

**Comment by AlexDM0** [comment]
Hi,

Allowing a user to drag the control nodes is not possible with vis since they do not exist as nodes. They are not stored so you would not be able to reload the network as you dragged it out before. 

What happens to the control points if you move the to or from nodes? Would they move respectively to the nearest nose? Stay in place? What if there is only one control node?

You'll need to change more then adding a edge type, you would need to add the infrastructure for storing and loading the edges. 

This should probably go in something similar to shapeProperties for nodes. We'd have to add it to the manipulation API as well and document everything. 

All in all this is not a small task and we have no use for it internally. I really don't see why you would want to drag your edges manually! If you set your edges and physics the way you want them, everything would be automatic. Why would you want to burden your user to do it himself?

You could try to implement this yourself?

Regards,

Alex
