### ISSUE TITLE
Custom scaling for edges doesn't seem to be working

### ISSUE THREAD

**Issue by MercyfulFate** [almende/vis#1208]
Hey,
I've been trying to get the edge's customScalingFunction to work without any success. Before I start digging around through your codebase I thought I'd double check here first.

Here is a canned example using the latest 4.7.0 code and one of your examples on your website:
https://jsfiddle.net/m56mu9cy/2/
I would expect it to set all the edges to the same width (in this case, max).
From what I can tell, the function is not being called at all (shown by console.log not being called)

We also have the same issue in 4.4.0.

Thanks

**Comment by AlexDM0** [comment]
Hi,

Thats odd, I'll look into it.

Regards

**Comment by AlexDM0** [comment]
Hi,

I've pushed a fix for this to develop. It will be added to the next release which will be soon!

Sorry for the delay!

**Comment by MercyfulFate** [comment]
Awesome. Thank you :)

**Comment by AlexDM0** [comment]
Just released in v4.8.2
