### ISSUE TITLE
Create Node Containers and drag Nodes inside them

### ISSUE THREAD

**Issue by vramali1** [almende/vis#1210]
Hello, I have a requirement where I create nodes using Drag and Drop. But I need to use Node Containers like a Logical Box with Nodes inside them and connect to other logical Box with nodes inside them too. Could you please tell me how I can achieve this functionality of One Node acting as a container to hold multiple nodes.

Thanks

**Comment by AlexDM0** [comment]
Hi,

What you're looking for is a flow editor. We do not support this use case with the network. We may have a vis component for this in the future. 

Regards

**Comment by vramali1** [comment]
Thanks for your response Alex, Could you please suggest any other framework similar to Vis.js which can achieve this. Right now we are using Vis.js.

**Comment by AlexDM0** [comment]
Hi,

I suggest you'd Google around to find what fits your use case :)

I cant judge what you need. 

Regards

**Comment by vramali1** [comment]
Sure Alex, Could you please suggest how can cluster/grouping of nodes can be created. I can click and Drag a node on to a group.
Thanks.

**Comment by AlexDM0** [comment]
Hi,

Take a look at the dataset and the click event.

Regards

**Comment by burhanusman** [comment]
Hey @vramali1, I currently have the same requirement. Have you found anything interesting?

**Comment by LauJon** [comment]
@AlexDM0 
Hey, I currently have the same requirement too. Have you found anything interesting?  may have a vis component for this in the future?

**Comment by Vincent-CIRCL** [comment]
Still the same. Would be nice :)
