### ISSUE TITLE
[Timeline] Drag current time

### ISSUE THREAD

**Issue by hdlopesrocha** [almende/vis#1212]
It would be nice to drag the current time, in my case each time interval represents a video and I need to play the current videos, dragging the present would be perfect. Thanks ;-)

Edit: It would be interesting to have an handler for when the present hits one interval.

**Comment by hdlopesrocha** [comment]
Forget it, I implemented it with a customTimer.
;-)

**Comment by josdejong** [comment]
Ah, indeed nice and smooth :)
