### ISSUE TITLE
VisNetwork | search by tags or label ?

### ISSUE THREAD

**Issue by koraykaradas** [almende/vis#1213]
Hi,
I want to search by tag or label,
Do you have a working example of your hand?
How can I do?
Thank you so much...

**Comment by AlexDM0** [comment]
Hi,

What do you want to search for? Tags of what? If you want to have a search box to find a node with a certain label, all you do is loop over your data, match the label and if you decide that one is the one you want you can select it or focus on it or something. 

The select and focus methods are in the documentation. The rest is pure JavaScript, that's up to you to figure out. 

Good luck

**Comment by koraykaradas** [comment]
I want to search by the label on the node.
for example: (just search box)
http://projects.flowingdata.com/tut/interactive_network_demo/

**Comment by AlexDM0** [comment]
In that case, all you need from vis is the data you put into the network, possibly the dataset (see docs), and if you want to select the data that matches the select method and if you want to move the camera to the node, the focus method. 

The rest is pure JS, which is not something we can assist you with. 

Regards
