### ISSUE TITLE
[Timeline] timeline set all itemSet as dirty on rangeChange

### ISSUE THREAD

**Issue by ChenMachluf** [almende/vis#1214]
Hi , 
I found out that the timeline marks all the itemSet as dirty on every rangeChange event.
It calls to his redraw method .

```javascript
Timeline.prototype.redraw = function() {
  this.itemSet && this.itemSet.markDirty({refreshItems: true});
  this._redraw();
};
```

And I see that in every item in the redraw method there is the following remark:
```javascript
  // Update DOM when item is marked dirty. An item is marked dirty when:
  // - the item is not yet rendered
  // - the item's data is changed
  // - the item is selected/deselected
```

and rangeChange event didn't apply to neither of them.
maybe on rangeChange it shouldn't need really do the markDirty thing?
I removed this line in my code (just to test it) and it work perfectly , the performance become insane , 20 ms to redraw 40k~ objects (its took 250 ms before).

**Comment by ChenMachluf** [comment]
Btw , i think it caused by mistake cuz Core is register to the rangeChange event  with his own redrew and Timeline derived from it.

**Comment by josdejong** [comment]
Good point, thanks a lot! We will fix this. This issue is introduced recently and is only there in the `develop` branch, not in the last released version.

**Comment by josdejong** [comment]
Should be fixed now in the `develop` branch
