### ISSUE TITLE
[Timeline] Item end time is not converted

### ISSUE THREAD

**Issue by mikaeljorhult** [almende/vis#1215]
I've been working with the callback functions to have an REST API updated when items is moved or changed. I've got it mostly working and everything is visually correct but I've noticed that the items end time seems to get invalid, and therefore not converted, when passed to the callback function.

Start time is converted correctly to a moment instance but end time is just output as a string regardsless of options set in the DataSet.

I've set up a small [test case](http://codepen.io/mikaeljorhult/pen/YXmPRo?editors=101) over at CodePen in which I experience the issue when moving the item to next group (see console for output).

![vis-console](https://cloud.githubusercontent.com/assets/215694/9429095/ee8da25a-49c4-11e5-9a79-4fa9b421a0e0.png)

**Comment by josdejong** [comment]
Thanks @mikaeljorhult for bringing this up. This should be fixed now in the `develop` branch (only the non-minified bundle is updated in `/dist`). 

By default, dates are now created/updated as `Date`. When the DataSet with items has configured types for `start` and `end`, these configured types are used instead.

**Comment by mikaeljorhult** [comment]
It's working fine now. Thank you for taking the time and fixing this!
