### ISSUE TITLE
Show case on SystemModeling.net

### ISSUE THREAD

**Issue by paulsimon99** [almende/vis#1216]
Hi, I'd like to thank you for your good work and it is what my project of System Modeling is based on:

http://systemmodeling.net

I will be glad to post a link to vis so you get credits for your work if that is OK with you guys.

Paul

Best

**Comment by AlexDM0** [comment]
Hi Paul,

Thats a cool app, small pointer: do not only set the edge length. In your case, I think you may be better off by increasing the repulsion (or gravitational constant) along with the edge length. It makes the edges not as overly curved.

Design is subjective but maybe look into bootstrap for design elements? I always liked http://www.famfamfam.com/ for icons.

We'd appreciate the link!

Regards

**Comment by mojoaxel** [comment]
> http://systemmodeling.net

Domain no longer availible. Closing..
