### ISSUE TITLE
Is there a way to know position of nodes and edges without rendering the network?

### ISSUE THREAD

**Issue by mingyin** [almende/vis#1219]
I'm using Network in vis.js to visualize a large-scale network that is constantly growing (the network currently has thousands of nodes and edges, and the number will keep increasing over time). 

To optimize the display, I would like to fix the position of nodes and edges when loading the page to a relatively optimal layout (for example, some layout after many iterations of physical interactions). So I wonder is there a way to get the position of nodes and edges given a physics simulation solver, WITHOUT actually rendering the network? Thanks a lot!

**Comment by AlexDM0** [comment]
you mean like with the stabilization system? 

http://visjs.org/docs/network/physics.html

use the stabilization iterations and listen to either the stabilizationIterationsDone or the stabilized event to store all positions. The network will be drawn exactly once.

Regards

**Comment by mingyin** [comment]
Hey, thanks for the quick reply!

I understand that if stabilization is set to be true and if the we have coordinates for nodes and edges in the network data, then the network will be shown pretty much according to the coordinates. 

I guess my problem is slightly different, and it may actually has two parts in it:

(1) Am I correct that to get all coordinates, I have to open a page to render the network at least once and then store the positions? That is, there is no way to know the positions of nodes and edges ONLY according to the dataset and the physic simulation solver?

(2) As the network keeps GROWING, say I save the positions for the network at some point, then one hour later when I want to display the network again, there are some (likely a lot of) new nodes and edges coming in which have no initial positions, and the initial positions for the existing nodes and edges (which are stored a hour before) may not be optimal anymore. So if I am right for question (1), then it seems that if I still want to supply the new network with some initial coordinates, I should always keep a browser open to render the growing network, and periodically save the positions into the database? Are there any other possible solutions?

Thanks a lot for your help!

**Comment by AlexDM0** [comment]
Hi,

You can look into phantomjs to run it without a browser. On adding you could make a decent estimate of where the node would be to increase performance, for example, x of the connected node + 1.

Regards

**Comment by mingyin** [comment]
Thanks a lot for the pointer!
