### ISSUE TITLE
Edge color reset bug

### ISSUE THREAD

**Issue by vukk** [almende/vis#1220]
The manual at <http://visjs.org/docs/network/edges.html> notes that:
> "When you have given an edge an option, you will override the global option for that property. If you then set that option to null, it will revert back to the default value."

However, trying to reset edge colors by setting them null results in the following issue: <http://jsfiddle.net/vukk/Lzae0k3p/>.
The expected result is that edge 1 to 2 is yellow, and 2 to 1 is default color. However both edges end up yellow on the screen.
It seems that somehow the edge colors are somehow referencing the same "address" or object after setting them null, but I'm not proficient enough in JavaScript and using HTML Canvas to find the problem (I did try).
The data on "edges" DataSet is correct, but the data on screen is not.
I debugged it so far as to note that edge update seemed to do the correct thing, but lib/network/modules/components/edges/util/EdgeBase.js#L36 gets the wrong colors to draw.
I'm not quite sure what's happening in between, or if I just missed something.

I have not checked if node coloring suffers from similar issues.

**Comment by AlexDM0** [comment]
You found a bug :) I'll see if I can fix this soon but its rather busy lately

Regards

**Comment by AlexDM0** [comment]
Hi,

Sorry it took so long but I've pushed a fix for this to develop.

It should be released shortly.

Regards

**Comment by AlexDM0** [comment]
Just released in v4.8.2
