### ISSUE TITLE
Question on Problem, Ports are reversed if map elements moved

### ISSUE THREAD

**Issue by vitalisator** [almende/vis#1221]
the description of ports should change respectively if devices placed on the other side.

http://snag.gy/DAol5.jpg

http://snag.gy/mnJFv.jpg
http://snag.gy/ddtDU.jpg

can someone suggest a solution for this problem?

**Comment by AlexDM0** [comment]
Hi,

This is not possible, the labels are independent of which side they are on, nor will this be supported. 

I would suggest using the arrows of the edges to indicate direction.  

Regards,

Alex

**Comment by vitalisator** [comment]
thx for an answer.
