### ISSUE TITLE
network.getPositions() also returns positions of support nodes?

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#1223]
Hi @ Dev Team,

I recently noticed that since 4.4 network.getPositions() behaves differently than it used to do. It not only returns the node positions (as stated in the api docs and which is the behaviour I would expect) but also returns the positions of the support nodes and adds a prefix "edgeId:" in front of the id. How can I prevent this because I only want to store real node positions?

Thanks!
-Felix

P.S. Congratulations on the 3000 stars!!

**Comment by AlexDM0** [comment]
Hi Felix,

thats seems to be a bug... sorry about that. We'll fix it as soon as we have time, it's a little busy at the moment :/

Regards

**Comment by AlexDM0** [comment]
Hi, 

I've pushed a fix for this to develop.

Regards,

Alex

**Comment by felixhayashi** [comment]
> We'll fix it as soon as we have time, it's a little busy at the moment :/

Now that was a fast fix, thanks again!

-Felix

**Comment by AlexDM0** [comment]
fixed in 4.8
