### ISSUE TITLE
Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#1224]
Hi,

I just switched the vis javascript code from v4.6.0 to "4.7.1-SNAPSHOT" (develop branch) and I get the following error. In my setup it happens when I replace a graph and call afterwards call network.stabilize().

![2015-08-25 15 20 53](https://cloud.githubusercontent.com/assets/4307137/9467909/080f2598-4b3f-11e5-8551-50bb488050f7.png)

Switching the code back to v4.6.0, everything works fine.

-Felix

**Comment by AlexDM0** [comment]
Hi Felix, 

Do you have a node setup that shows this? The develop branch does need more testing but I'm surprised something like this came up!

Regards

**Comment by AlexDM0** [comment]
I've sent a possible fix for this to develop, could you check if you get the same behaviour?

**Comment by felixhayashi** [comment]
Yes, works! Hurray!

**Comment by felixhayashi** [comment]
Thanks Alex. Should I close this?

**Comment by AlexDM0** [comment]
yea, its a bug in develop so not relevant for most people. Thanks for reporting!

**Comment by AlexDM0** [comment]
keep in mind that another bug was fixed in develop, which counted the iterations during stabilisation double. It may look like its taking longer but now one iteration, really is 1 iteration
