### ISSUE TITLE
Dangling color picker when network is destroyed

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#1225]
Hi Alex,

Looks like the color picker is now attached to the body of the page. However, this means that when a graph is removed/destroyed while the color picker is active, the picker does not automatically disappear since it is not bound to the networks container…

Somewhat related to #1145

Thanks

-Felix

**Comment by AlexDM0** [comment]
Hi Felix, 

I think I'll put the color picker back in the container the rest is in.. I don't know how I can solve the issue for popup containers but that was not working either way.

Regards

**Comment by felixhayashi** [comment]
Ah ok. Thanks Alex.

At the moment, I do the following:

> What I do is to simply assign static the left and top css properties that make the picker appear at the top of the dialog regardless of the scrolling...
> https://github.com/almende/vis/issues/1145#issuecomment-127023937

So for me, this is not a big issue at the moment.

-Felix

**Comment by AlexDM0** [comment]
By moving this back, this issue is solved, we are back to square 1 in 1145 though..
