### ISSUE TITLE
Reset of node properties in dataset causes crash

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#1226]
Hi Alex,

sorry for firing all these issues at you, but I found another bug:

https://jsbin.com/qojeva/edit?html,console,output

When you press the button, the nodes dataset will receive an update which shall reset the font and color properties, instead, vis crashes :(

Much thanks!

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

no worries, seems we messed up while you were away ;)

I'll take a look at it when I can.

Regards

**Comment by felixhayashi** [comment]
> no worries, seems we messed up while you were away ;)

:D Comparing the increasing level of awesomeness of vis with the few bugs I find, it is quite the opposite of messing up ;)

> I'll take a look at it when I can.

Thanks.

**Comment by felixhayashi** [comment]
Hi @AlexDM0

**Comment by felixhayashi** [comment]
Hi @AlexDM0 

do you know when you can look into this? It is one of the last issues that prevents me from publishing a new version of TiddlyMap. If you are too busy at the moment, it's no problem and I don't want to pressure you, just wanted to say I would appreciate if this gets picked up :)

Thanks in advance
-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

It's very busy since I'm helping out my colleagues prepare for their Kickstarter campaign. :) I hope to get to this next week. Seems 4.8 is not stable though.. Might be smart to wait till 4.9 ;)

Regards

**Comment by felixhayashi** [comment]
Hi Alex

> It's very busy since I'm helping out my colleagues prepare for their Kickstarter campaign

Ah ok. I hope it's going to be a success then!!

> I hope to get to this next week. Seems 4.8 is not stable though.. Might be smart to wait till 4.9

Hmm, maybe I will, but as for my case, all critical vis features work in v4.8. I also like the new stabilization algorithm, its quite fast!

-Felix

**Comment by AlexDM0** [comment]
Thanks :) we will probably put some banners up on visjs to help them out soon. 

I made the videos and the 3d renderings so I will try to get some help from the vis community to make it a success :)

www.crownstone.rocks

Check it out! (shameless self promotion) ;)

Regards

**Comment by felixhayashi** [comment]
Nice innovative idea, and very professionally communicated to the consumer. The 3d images look great. Must have been much time invested to bring the product to this level already. Also nice that the the code is available at GitHub. Will surely be a success.

**Comment by AlexDM0** [comment]
Don't suppose we can get a little banner on tiddlywiki once the project is live? ;)

**Comment by felixhayashi** [comment]
Hi Alex,

unfortunately http://tiddlywiki.com does not do any advertising on its page :(
I am only in charge of the TiddlyMap-plugin and despite its popularity in the community it would appear rude if I ask for advertisements on the main page.

But as far as http://tiddlymap.org is concerned, I'll certainly add a link on the startpage to the Crownstone project and the DoBots introduction video. I'll also tell other people about the product that might have an interest in it.

Really hope you guys are successful with this.

-Felix

P.S.

I looked at the press material and the teaser video is awesome! Very well done with the music and the effects. You should do a whole movie, Alex :)

**Comment by felixhayashi** [comment]
Hi @AlexDM0

I just announced the crownstone project on our TiddlyWiki community discussion board the link is below :)

**Visjs developers are launching a kickstarter campaign!**
https://groups.google.com/forum/#!topic/tiddlywiki/Ei_LNQGqbY0

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

Thanks for this!

The actual code is found here:
www.github.com/dobots/bluenet

We are very excited about the Kickstarter and hope it can go live soon (verification phase at the moment). 

Cheers!

**Comment by AlexDM0** [comment]
Hi Felix,

I've pushed a fix for this to develop. We'll add it to the release next week.

Cheers

**Comment by AlexDM0** [comment]
Just released in v4.8.2
