### ISSUE TITLE
[Network] Release navigation API?

### ISSUE THREAD

**Issue by rwu823** [almende/vis#1228]
Turn on navigation buttons are get through `interaction. navigationButtons`: true.
Is there have navigation API now? sometimes we need more controllable.

**Comment by AlexDM0** [comment]
Hi,

What do you need to do exactly?

Regards

**Comment by danilvalov** [comment]
Hi @rwu823 

Use `.moveTo({scale: 0.1})` and `.moveTo({position: {x: 0, y: 0}})`.

All params:
```
{
  position: {x:Number, y:Number},
  scale: Number,
  offset: {x:Number, y:Number}
  animation: { // -------------------> can be a boolean too!
    duration: Number
    easingFunction: String
  }
}
```

Docs: http://visjs.org/docs/network/#method_moveTo

**Comment by AlexDM0** [comment]
Hi,

Does this solve the issue?

Regards
