### ISSUE TITLE
[Timeline] grouping performance 

### ISSUE THREAD

**Issue by 1o4** [almende/vis#1229]
There is a huge performance difference in timeline grouping (vis.js example) between ie & ff vs. chrome. It seems that the changes between 3.x <-> 4.x are responsible for this.

...more precisely: zoom out (vis ~100-200+ items) and then moving left or right becomes, unlike timeline performance example (without groups), extremely slow and jerky. in v 3.x it works like a charm

**Comment by 1o4** [comment]
...more precisely: zoom out (vis ~100-200+ items) and then moving left or right becomes, unlike timeline performance example (without groups), extremely slow and jerky.

**Comment by josdejong** [comment]
On which browser and OS do you have this performance issue? How to reproduce this exactly? Do you mean to say that the performance is degraded since 3.x, or that in 4.x chrome is way faster than other browsers?

**Comment by josdejong** [comment]
Maybe this performance issue is the same as reported in #1214.

**Comment by josdejong** [comment]
Nevermind, that's not possible as regression of #1214 was introduced after the last release, and is only there in the `develop` branch.

**Comment by 1o4** [comment]
The performance in IE/FF is degraded since 3.x. Tried out in Win7/8.1 with FF 31.2.0 and IE 11.0.96 (Chrome 44.0.24).
How to reproduce: Use vis-3.12.0 and vis 4.7.0 examples 
  vis-4.7.0/examples/timeline/other/groupsPerformance.html?count=300
  vis-3.12.0/examples/timeline/14_group_performance.html?count=300

Zoom out, so that all items are visible - then dragging the time axis left or right

Thanks in advance for your support

**Comment by josdejong** [comment]
Thanks for your clarification. Let's see if we can do something about it.

**Comment by 1o4** [comment]
closed, way better in 4.8.0

**Comment by josdejong** [comment]
Good to hear, thanks for the feedback.
