### ISSUE TITLE
Question about hierarchical layout and how to avoid overlapping nodes

### ISSUE THREAD

**Issue by neothor** [almende/vis#123]
I have been playing around with this great library but I have run into a little problem. I try to visualize the structure of different companies and want to use the 'hierarchicalLayout'. But as you can see in the following screenshot my nodes are overlapping.

![overlappingnodes](https://cloud.githubusercontent.com/assets/1047029/2925846/0c3ea848-d753-11e3-87ff-71d1d4264179.PNG)

I have been looking into the physics section and playing with physics configuration example but can't seem to get the node seperate from each other.

**Comment by yuvraj11** [comment]
Hi Alex, In my scenario, I have the physics turned off. Is it possible to use nodeDistance or otherwise keep a minimum distance of fixed length between nodes?
