### ISSUE TITLE
[Timeline] options timeAxis scale 'weekday'

### ISSUE THREAD

**Issue by 1o4** [almende/vis#1230]
Since version > 4.5.0. the visualization of 'weekday' scale doesn't works right at a lower zoom level . Only the first 9 weekdays of a month are visualized (see screenshot).

![image](https://cloud.githubusercontent.com/assets/13534918/9488326/75749682-4bd9-11e5-86ed-5e3508f89f97.png)

**Comment by josdejong** [comment]
Thanks, this is already fixed in `develop`, we will do a release soon.

**Comment by 1o4** [comment]
Still exists in 4.8.0

**Comment by josdejong** [comment]
@1o4 are you really sure? I can't reproduce this anymore in 4.8 (example [groupsPerformance.html](http://localhost:63342/vis/examples/timeline/other/groupsPerformance.html)), whilst I could before the fix.

**Comment by 1o4** [comment]
![image](https://cloud.githubusercontent.com/assets/13534918/9652516/865bfe06-521c-11e5-8102-6c934b02557a.png)

**Comment by josdejong** [comment]
Ah, thanks, I see you're manually setting the scale to `weekday` and then things go wrong. I will reopen this issue, we will have a look into it.

**Comment by 1o4** [comment]
@josdejong yep, really sure ;-) - btw thanks for this great piece of code, you guys are doing a real good job!

**Comment by josdejong** [comment]
Thanks, you're welcome :)

**Comment by aske-cph** [comment]
+ 1, still exists in 4.9.0. I also set weekday in options. ( And thanks for the project by the way! )

**Comment by yotamberk** [comment]
fixed in 4.16.1
