### ISSUE TITLE
[Network] Move values of minScale and maxScale to options

### ISSUE THREAD

**Issue by danilvalov** [almende/vis#1231]
Please, move these values (minScale = 0.00001 and maxScale = 10) to options.
I can't change it in my app without fork.

File `vis/lib/network/modules/InteractionHandler.js`:
```
zoom(scale, pointer) {
    if (this.options.zoomView === true) {
      let scaleOld = this.body.view.scale;
      if (scale < 0.00001) {
        scale = 0.00001;
      }
      if (scale > 10) {
        scale = 10;
      }
...
```

**Comment by AlexDM0** [comment]
Why would you want to change these?

**Comment by danilvalov** [comment]
For my app a current minScale is very small. I don't see my network in the current minScale (0.00001). I need dynamical minScale and maxScale. Now i can make it with event `zoom` (for example, change scale after getScale < 0.1) but it's very bad decision.

**Comment by AlexDM0** [comment]
those min max are not really ment as user bounds but as system bounds. In order to avoid impossible cases. Why do you need a dynamic minScale and maxScale specifically?
