### ISSUE TITLE
DataView.length ignores filtering

### ISSUE THREAD

**Issue by daniel-pfeiffer** [almende/vis#1233]
`myTimeline.items.length` should be smaller than `myTimeline.items.getDataSet().length` when filtering was successful.  But it's uselessly always the same.

**Comment by josdejong** [comment]
Can you elaborate?

**Comment by daniel-pfeiffer** [comment]
I query the DataView's length attribute before and after activating a filter.  I would expect it to shrink with the filtering, to reflect that the view is now showing less items.  But it still reports the original number.
