### ISSUE TITLE
Node is not visible when new node is added and visible only on zoom out

### ISSUE THREAD

**Issue by vramali1** [almende/vis#1235]
Hello, When I create a new node using code node.add() , the node is not visible. The node is visible when i use mouse zoom out. The node is created outside the visibility. Could you please tell me how to solve this issue. I need to see the node when I add the node to the graph.
Thanks

**Comment by AlexDM0** [comment]
Hi,

I'll assume node is a dataset. 

The network is drawn on a canvas. Think of this as a sheet of paper with a camera over it. Nodes have x and y positions on this paper and the camera has a position. 

If you add a node it will spawn around 0,0 on the canvas. Your camera may not see that. You can use getViewPosition to see where the camera's center is. 

Just give the node you add a x and y position that will be in your view. Also look at the canvasToDOM and DOMtoCanvas methods in the docs. 

Regards
