### ISSUE TITLE
[Network] stabilization

### ISSUE THREAD

**Issue by p1erce** [almende/vis#1236]
Hi, I just run into problems with the stabilization of module network.
 1. In the physicsEvents example, the console log first got a `stabilized! Object {iterations: 0}`. where is it from? does it mean the graph is stabilized at the beginning? if so, why it got `startStabilizing` event after that?
 2. I set a max stabilization iterations, `option.physics.stabilization.iterations: 400` and add call `stopSimulation()` in `stabilizationIterationsDone` event. When the page first load up, it stop simulation correctly when the iteration number reach 400. **But how can I stop the stabilization process fired by drag event?** After I drag a node, there is not `stabilizationProgress` event nor `stabilizationIterationsDone` event and so I can not `stopSimulation()`. If lucky, it will stop after 400+ iterations and get a `stabilized!` event . But in many cases it seems just rotate forever. How can I set that iteration limit globally?

Thanks.

**Comment by AlexDM0** [comment]
Hi,

The first firing of the stabilised event is a bug and has been fixed on the develop branch. We will include it in the next release. 

Stabilizationprogress and stabilizationiterationsDone are only for the stabilization that does not draw on the screen, like the initial one or if you manually call stabilize. This means your second question is not possible using these events and they are working correctly. 

I would suggest you listen to the dragEnd event and set a timeout. 

Regards

**Comment by p1erce** [comment]
Hi, Alex, 

Thanks for your suggestion. A timeout is similar to the limit of stabilization iterations, which solves my problem. great work~

**Comment by p1erce** [comment]
Hi, after read the doc of network again,  here is one suggestion and one question. 

The `stabilizationIterationsDone` event can be fired under different conditions. One is the iteration number exceed the limit in `options:physics:stabilization:iterations`, and graph may not be stable. The other one is that it gets stable within the limit. **So it will be useful if this function returns an object with iteration times.** I can then call `stopSimulation` if the iteration times exceed limit.

And about the `options:physics:stabilization:fit`, what exactly does it mean by _when the stabilization is finished_? Does it listen to `stabilizationIterationsDone`? if so, since it may be unstable, it may `fit` for a second and then some nodes go away.

**Comment by AlexDM0** [comment]
Hi,

I'm not sure what you mean with the stabilizationIterationsDone suggestion. In once case the simulation is stable, hence no need to call stop, on the other it's not and you can stop it yourself if you want. 

Stabilization is a sped up, hidden, precalculation phase. The fit will be called after this phase if the option is true. It can happen that nodes go out of bounds later, yes. 

The fit is called before the stabilizationIterationsDone event. 

Regards

**Comment by p1erce** [comment]
Hi,

by the suggestion I mean that I don't want to call a `stopSimulation` when it is stable, but would like to call it when it is not after it exceeds iteration limit. But I can not tell which is the case just from the `stabilizationIterationsDone` event. 
Maybe I can infer that it is stable when get `stabilized` after `stabilizationIterationsDone`, and it is not when only get `stabilizationIterationsDone`. But the `stabilized` event will also be used in later drag/movement. So it would be nice if we do not couple these two event.

As far as I said, it jumps into my head that, it might also be better if we distinguish the `stabilized` in hidden phase apart from the later visible one. To some extent, they **are** different. 
Well, that is kind of function design philosophy thing. Just forget it if that's not appropriate.

According to your last two paragraph, am i right on the order? 
`stabilization -> fit() -> stabilizationIterationsDone -> stabilized if stable`

Guess I should dive into javascript and source code. Sorry for the bother~

**Comment by AlexDM0** [comment]
Hi,

I don't really think that makes sense. 

The stabilised event means that the network has stabilized. If that happens during the stabilization phase, that phase will also end (and thus trigger a stabilizationIterationsDone event). 

You can stopSimulation all you want if it's stable. Nothing will happen. There is no need to catch this case. 

As I see it, all you need is a stopSimulation on the stabilizationIterationsDone event and whatever else you want to do. Fit is not required as that is already triggered after stabilization (if not disabled in the settings). 

So: when the stabilization process (the hidden one) ends, (ending means either iterations are done or stabilized) the following will happen. 

1) fit is done if not disabled. 
2) stabilizationIterationsDone triggered 
3) if stable, stabilized will be triggered. 

So if you call stopSimulation once iterations are done, you're all set. 

Regards

**Comment by p1erce** [comment]
Hi,

that is what I do in my code, stop simulation anyway in stabilizationIterationsDone. And it works. 
> Nothing will happen.

It's just like said that 5.0 is nothing more than 5. It's true but they are different in some sense, float vs int.

Anyway, really thanks for the great work and detailed explanation~

**Comment by AlexDM0** [comment]
True some code is executed, it is about 6 lines which check if they should do anything else. I figured that would count as nothing. Especially if we compare it with a redraw which is running many thousands of lines of JavaScript (added looped code for dramatic effect ;)

Have fun using vis :)
