### ISSUE TITLE
Network Redraw doesn't redraw(?)

### ISSUE THREAD

**Issue by Blixia** [almende/vis#1238]
I copied a basic example and tried a few options but no matter what I do redraw doesn't do anything (I think). Only by refreshing which is what I expect of a redraw.

What is vis.Network.redraw() supposed to do? Besides the the obvious redrawing which I don't see happening? Are there options that restrict it?

**Comment by josdejong** [comment]
`Network.redraw()`  re-renders the network. This can be needed for example when the DIV container where the Network has been rendered was resized or has become visible in an earlier invisible tab or something like that.

**Comment by Blixia** [comment]
I am still not sure what the redraw does. It redraw what? It zooms? Renders nodes that were not visible before?

Also is there an option that basically simulates the refresh to 'redraw' from scratch? (without randomSeed)

**Comment by josdejong** [comment]
Normally you never need to redraw. Redraw only re-renders what's already there on screen. It does not change the state of the nodes/edges, it only re-renders them on screen. So typically, when you call re-render, "nothing" happens. You only need to call redraw when the size of the div where the Network is rendered has changed or was hidden but now visible. In that case you will see that calling redraw will scale the nodes to the new size of the viewport.

Why do you (think) you need to call redraw? What do you try to achieve?

**Comment by Blixia** [comment]
I am trying to recreate how the original state of the network was before people start dragging nodes around. Sort to speak you can let people select a node and move them about and show an example and reset back to where everything was and show a new example.

**Comment by AlexDM0** [comment]
Hi,

It seems to me you should just reset the positions of the nodes using the DataSet. Look at the methods: storePositions, getPositions and the dataset itself. You clear the datasets and repopulate them. 

If you're using dynamic edges (default value) then you'll probably want to stabilize a few cycles before showing. 

Regards
