### ISSUE TITLE
[Timeline] Groups are sorted by default, but should'nt according to documentation

### ISSUE THREAD

**Issue by jonaslewin** [almende/vis#1241]
When I send groups to timeline via set data or the constructor, they are sorted. I want them to stay in the order they are in the array of groups.

Example: If I send groups
```
{ "id": "1", "title": "1" },
{ "id": "10", "title": "10" },
{ "id": "2", "title": "2" }
```
then the groups are presented in the timeline like this
1
2
10

I have created a jsfiddle to show the problem.
http://jsfiddle.net/mb1uj0gq/2/

**Comment by josdejong** [comment]
Groups (and items) are stored by their id in an unordered map. By default, groups are ordered by the field `order` (if provided). If the groups do not contain this field, the group order is officially undetermined but in practice will be the ordered by id. 

To enforce an order, have a look into the configuration option `groupOrder`, it can be a field name or a function.

Can you point me to where the docs say that groups are not ordered by default? Then I can clarify the concerning phrases.

**Comment by jonaslewin** [comment]
Thanks for the reply.

I read here:
http://visjs.org/docs/timeline/#Configuration_Options
groupOrder, String or Function, none, Order the groups by a field name or custom sort function. **By default, groups are not ordered**.  

When I read this, I had to ask my colleagues what this means for the sort order, and we concluded that the sort order is not changed. Perhaps we assumed this as we did not see that it said that it might change if you do not supply a sort order function.

Thanks.

**Comment by josdejong** [comment]
Thanks, this is indeed a bit ambiguous sentence, I will change it.

**Comment by josdejong** [comment]
Will be improved in the first next release.

**Comment by 32teeths** [comment]
How do I cancel the default ordering by id ?
