### ISSUE TITLE
[Network] Browser crashing during physics simulation

### ISSUE THREAD

**Issue by mael-morel** [almende/vis#1244]
Hi,

I'm trying to render some rather big graphs (30000 nodes and 40000 edges). I'm clustering most nodes, so in the end the number of node displayed never exceeds 2000, so display is ok.

My problem is physics : the browser crashes while applying forceAtlas2 above 2000 nodes and 500 iterations. I would like to put the physics calculation in a web worker to avoid this crash.

Is there a way to apply physics to nodes and edges before creating a network object?
This way I could give nodes with pre-calculated coordinates to the network object.
like in this example : http://www.kenedict.com/connecting-startups-and-investors-in-mobile-technology/

This would be useful to enable physics calculation serverside too (in nodeJs).

By the way, great library!

Thx, Mael

**Comment by AlexDM0** [comment]
Hi,

Can you send me data that would crash my browser so I can find the bug? It could be that the clustering part is in fact crashing here. There have been many fixes on that in the upcoming version. It is not possible to run the physics without creating the network object, but I do not think it should be required. 

You can run it on nodejs with phantomjs if you want.

We should find out why it crashes, please let me know how I can reproduce this.

Regards

**Comment by mael-morel** [comment]
I don't think the clustering part is a problem here, as I cluster / uncluster without problem, and it's actually pretty fast! From what I measure, the problem is the physics: everything is smooth when I set the iterations to 0, and the more iterations, the more lag. 

You will find my data in dataTest.json here : 
https://www.dropbox.com/s/3xdx5l3kpwswmjq/dataTest.json?dl=0

Thanks a lot for your time

**Comment by mael-morel** [comment]
For people who get performance problems in the positioning phase (not the display phase):

I managed to handle a 5000 nodes 5000 edges graph by calculating the nodes position in a web worker and then display the graph with VisJs (using clusters I really display only 1000 nodes at a time). It's done in less than 10 seconds without any freeze thanks to the web worker doing all the hard work. 

Unfortunatly, I used an other library to do the positioning and the result is not as well arranged as VisJs do, but it's watchable. I will do further tests, but I think I can handle more than 10000 nodes this way.

**Comment by AlexDM0** [comment]
Hi, 

I've not yet had the chance to test your data. I'd be curious to know which library you used. We are always looking for ways to improve the physics. 

Regards

**Comment by mael-morel** [comment]
Hi,

I used sigma.js to compute the positioning. In the last month I worked with three open source libraries: d3, sigma and Vis. Really I found Vis to be the more complete, reliable and easy to use. My big problem was physics:  freezing and crashing the browser after 1000 iterations. To wait for 10 seconds or even a minute is not a big issue, freezing is. If someone could work on implementing the physics model in a web worker, it would be heaven ("baby angels singing"). I tried for half a day, I know it's not a quick win... But with the implementation of forceAtlas2 in VisJs, the result would be awesome

Regards

**Comment by AlexDM0** [comment]
I'll put it on my todo list ;)

**Comment by AlexDM0** [comment]
Hi,

I was not able to reproduce the crash. Could you try again with the new version of vis? It may have been solved there? The speed difference you see is that if you simulate in sigma, the support nodes for the dynamic edges are not there. You can get similar performance in vis if you use any other edge type than static. 

Regards

**Comment by ericvandever** [comment]
Mael,

I spent a couple days and have a working webworker implementation for Barnes-Hut/CentralGravity/SpringSolver that you can check out at #1348.  I'd be interested if it is enough to support your use case (I just haven't tried the other physics algorithms) and if you have any thoughts/suggestions on implementation.

**Comment by Tooa** [comment]
Regarding your first question: Have you tried to calculate the positions of nodes with phantomjs in background? In my application, I precalculate the layout and once the stabilization is done I save the node positions. Works like a charm.

**Comment by cojack** [comment]
@Tooa any example?
