### ISSUE TITLE
Add error message when supplying incorrect values

### ISSUE THREAD

**Issue by MusicalCreeper01** [almende/vis#1245]
I just spent an hour trying to figure out why my data wasn't displaying on the chart. I finally realized that I was accidentally passing my x and y values as strings as I forgot to parse them to ints. 

There really should be an error message/catch for when your supplying the wrong values, instead of just failing and not saying anything.

**Comment by AlexDM0** [comment]
Hi,

The reason this is not done at the moment is that we allow people to add arbitrary data to nodes and edges. If we were to turn on the checker, we'd have to allocate some sort of special data field that would not be checked. 

Maybe we will add a debug option in the future that will be stricter. 

Regards

**Comment by MusicalCreeper01** [comment]
@AlexDM0 But what about in the case where a 3d graph doesn't even show if you accidentally pass it strings?

**Comment by AlexDM0** [comment]
Hi,

I thought you were talking about the network. I suppose the same goes for the other modules. Graph3d is currently behind in features.

Regards

**Comment by mojoaxel** [comment]
@MusicalCreeper01 Is this still an issue?

**Comment by MusicalCreeper01** [comment]
@mojoaxel no idea, I'm no longer employed to the person I was working for when using this library.
