### ISSUE TITLE
hierachical layout doesn't respect hierarchy

### ISSUE THREAD

**Issue by Lakedaemon** [almende/vis#1248]
![bug](https://cloud.githubusercontent.com/assets/103175/9566892/5894304e-4f18-11e5-8208-3eaf5db585c0.png)

node 0 should be at the top with 
var nodes = [
{id: 0, label: '0'},
{id: 1, label: '1'},
{id: 2, label: '2'},
{id: 3, label: '3'},
{id: 4, label: '4'},
{id: 5, label: '5'},
{id: 6, label: '6'},
{id: 7, label: '7'},
{id: 8, label: '8'},
{id: 9, label: '9'},
{id: 10, label: '10'},
{id: 11, label: '11'},
{id: 12, label: '12'},
{id: 13, label: '13'},
{id: 14, label: '14'},
{id: 15, label: '15'},
{id: 16, label: '16'},
{id: 17, label: '17'},
{id: 18, label: '18'},
{id: 19, label: '19'},
{id: 20, label: '20'}
];

var edges = [
{from: 0, to: 1, style: 'line'},
{from: 1, to: 2, style: 'line'},
{from: 2, to: 3, style: 'line'},
{from: 3, to: 4, style: 'line'},
{from: 3, to: 5, style: 'line'},
{from: 1, to: 6, style: 'line'},
{from: 6, to: 7, style: 'line'},
{from: 7, to: 8, style: 'line'},
{from: 8, to: 9, style: 'line'},
{from: 9, to: 10, style: 'line'},
{from: 8, to: 11, style: 'line'},
{from: 7, to: 12, style: 'line'},
{from: 12, to: 13, style: 'line'},
{from: 12, to: 14, style: 'line'},
{from: 0, to: 15, style: 'line'},
{from: 15, to: 16, style: 'line'},
{from: 16, to: 17, style: 'line'},
{from: 17, to: 18, style: 'line'},
{from: 17, to: 19, style: 'line'},
{from: 15, to: 20, style: 'line'},
];

var options = {
layout:{hierarchical:true},
interaction:{multiselect:true},
};

**Comment by AlexDM0** [comment]
Hi,

We have an option actually called level. The hierarchical system is not looking at ids. 

Regards
