### ISSUE TITLE
HiddenDates doesn't work

### ISSUE THREAD

**Issue by littleguga** [almende/vis#1249]
``` javascript
hiddenDates: {
	start: '2014-03-21 00:00:00', 
	end: '2014-03-28 00:00:00'
}
```
Got this:
```
Unknown option detected: "start" in 
options = {
  hiddenDates: {
    start
  }
}
Perhaps it was misplaced? Matching option found at: 
options = {
  start
}
vis.min.js:33 Unknown option detected: "end" in 
options = {
  hiddenDates: {
    end
  }
}
Perhaps it was misplaced? Matching option found at: 
options = {
  end
}
vis.min.js:33 Errors have been found in the supplied options object.
```

What i'm doing wrong?

**Comment by josdejong** [comment]
See this example of hidden dates: http://visjs.org/examples/timeline/other/hidingPeriods.html 

the config option `hiddenDates` should be an array, like:

```js
hiddenDates: [
  {
    start: '2014-03-21 00:00:00', 
    end: '2014-03-28 00:00:00'
  }
]
```

we will see if we can further improve the hints to give a more useful hint in this case.

**Comment by littleguga** [comment]
@josdejong 
I was following [this docs](http://visjs.org/docs/graph2d/#timelineOptions).
>The dates can be supplied as an object ... or as an Array of these objects

But if i supply it as an object:
```javascript
hiddenDates: {
				start: '2015-08-22 23:59:59', 
				end: '2015-08-24 00:00:00'
			}
```
I got this:
```
Unknown option detected: "start" in 
options = {
  hiddenDates: {
    start
  }
}
Perhaps it was misplaced? Matching option found at: 
options = {
  start
}
vis.min.js:33 Unknown option detected: "end" in 
options = {
  hiddenDates: {
    end
  }
}
Perhaps it was misplaced? Matching option found at: 
options = {
  end
}
vis.min.js:33 Errors have been found in the supplied options object.
```
If i supply hiddenDates as array it's ok. 
``` javascript
hiddenDates: [
				{
					start: '2015-08-22 23:59:59', 
					end: '2015-08-24 00:00:00'
				}
			]
```
So, docs are wrong? I can't supply hiddenDates as an object?

**Comment by AlexDM0** [comment]
Jos, could this be something we didn't correctly set in the validator?

**Comment by josdejong** [comment]
@AlexDM0 yes I think so, so both Object and Array should be allowed.

**Comment by josdejong** [comment]
@littleguga sorry, your original code should just work (both Array and Object should be allowed), we will fix this.

**Comment by josdejong** [comment]
This has been fixed in the `develop` branch and will be fixed in the first next release.

**Comment by littleguga** [comment]
@josdejong Great, thank you!
