### ISSUE TITLE
Stored Networks

### ISSUE THREAD

**Issue by abemammen** [almende/vis#1250]
Create Network1
Visualize it
Create Network2 (network1 not destroyed)
Visualize it
How do you go back to visualizing Network1?
network1.redraw() or network1.focus(,,) doesn't do anything.
Just a blank screen.
Using v4

**Comment by AlexDM0** [comment]
Hi,

I have no idea what you're doing. Do you have some code?

In general, you'll need two container divs, each with its own network and hide one using CSS. 

You should read up on memory management in JavaScript to know when you are overwriting things. 

I can't help you without more information. 

Regards

**Comment by abemammen** [comment]
Its pretty simple really and its a fundamental question.

I have a canvas attached to a network I created via a new.
network1 = new vis.Network(container, data1, opts1);
The network displays correctly in the canvas container. No problem.
I want to now render another network to the same canvas.
network2 - new vis.Network(container, data2, opts2);
This network also displays correctly in the canvas container. Again no
problem.
In this particular scenario, I don't want to have to recreate the 1st
network to re-display it. I have an instance of it and I have it stored in
say a variable called network1. I want the ability to have 'network' be
rendered to the same canvas.
How does one make a network an active one?

It doesn't appear that a network is tied to a canvas container as I've
already seen that I can merrily create new network instances and attach to
the same canvas and the rendering is what I expect. What it doesn't appear
to do is to reattach to previously created instance.

Its not a question of overwriting variables and such - all that is not a
problem (don't worry I know enough about memory management - way too much
experience!). There doesn't seem to be a method to 're-attach' or 'make
active' etc a previously created network instance. I want to view a single
container as the the network drawing div and based on modality render
different types of networks into that container. I certainly would like to
optimize the case of 'this network has already been created once' scenario
by caching it and re-attaching it. Clearly, I would prefer to not refetch
the data and recreate a new network. I can see that by dumping out state
for 'network1', it appears whole and has all the previously created data.

Can vis.js do this? Maybe not. That is the confirmation I would like.

Thanks for your help.

On Sun, Aug 30, 2015 at 11:24 PM, Alex <notifications@github.com> wrote:

> Hi,
>
> I have no idea what you're doing. Do you have some code?
>
> In general, you'll need two container divs, each with its own network and
> hide one using CSS.
>
> You should read up on memory management in JavaScript to know when you are
> overwriting things.
>
> I can't help you without more information.
>
> Regards
>
>
>
> > On 31 aug. 2015, at 07:22, Abe Mammen <notifications@github.com> wrote:
> >
> > Create Network1
> > Visualize it
> > Create Network2 (network1 not destroyed)
> > Visualize it
> > How do you go back to visualizing Network1?
> > network1.redraw() or network1.focus(,,) doesn't do anything.
> > Just a blank screen.
> > Using v4
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/almende/vis/issues/1250#issuecomment-136278355>.
>



-- 
_______________________
Abe Mammen
amammen@matterport.com
+1 925-577-5201

**Comment by AlexDM0** [comment]
Hi,

The container is a div, not a canvas. This div is fully cleared of contents when you initialize a network. 

At this line:
> network2 = new vis.Network(container, data2, opts2);

You effectively delete the previous network. It is not a question of reattaching or activating it, it does not work like that. The networks assume you will not externally delete their DOM elements.

You can however do this a different way, with two containers. You can use css to overlay them if you'd like or toggle between them?

If you hide the container, the network is not lost. If you don't hide but if overwrite, you break the DOM connections and this is not the usecase we designed it for.

Regards

**Comment by abemammen** [comment]
Ok thanks.
That seems to explain the behavior.
Its too bad that the idea of binding a network to a container isn't more
dynamic. But now I understand the use case your system was designed for.
In the design we have, there may be many (tens and possibly high tens)
networks. I'll look into the feasibility of toggling between multiple
containers via css but that doesn't appear to be immediately appealing.

Again, thanks for your help.

On Mon, Aug 31, 2015 at 8:53 AM, Alex <notifications@github.com> wrote:

> Hi,
>
> The container is a div, not a canvas. This div is fully cleared of
> contents when you initialize a network.
>
> At this line:
>
> network2 = new vis.Network(container, data2, opts2);
>
> You effectively delete the previous network. It is not a question of
> reattaching or activating it, it does not work like that. The networks
> assume you will not externally delete their DOM elements.
>
> You can however do this a different way, with two containers. You can use
> css to overlay them if you'd like or toggle between them?
>
> If you hide the container, the network is not lost. If you don't hide but
> if overwrite, you break the DOM connections and this is not the usecase we
> designed it for.
>
> Regards
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/almende/vis/issues/1250#issuecomment-136413467>.
>



-- 
_______________________
Abe Mammen
amammen@matterport.com
+1 925-577-5201

**Comment by AlexDM0** [comment]
It's rather easily scripted though.. Just make an object that can create and manage networks. It can have an activate() method that handles the css.

Regards
