### ISSUE TITLE
Timeline: customizing a line height for groups and items

### ISSUE THREAD

**Issue by mast0r** [almende/vis#1251]
Hi, I am trying to set a custom (min) height for the group line and item lines. Here is a screenshot where I've marked areas I want to set a custom height (I want to make it narrower reducing the height).

![timeline-height](https://cloud.githubusercontent.com/assets/9842532/9578752/e7e8a714-4fec-11e5-9e49-d562661c0245.png)

I assume that the height for areas 1 and 3 is the same value. Looking in the code I've found that the height is "hard-coded" to each group "line" (area 1 on the first screenshot):

![timeline-height1](https://cloud.githubusercontent.com/assets/9842532/9578855/b4abced4-4fed-11e5-8d6d-bdc3d4768016.png)

And the same thing happens on the area3 (items line):

![timeline-height2](https://cloud.githubusercontent.com/assets/9842532/9578862/c8ec1cdc-4fed-11e5-8afb-c08a1ec84826.png)

How can I set that height for example to 24px? (I will reduce the font size at the same time because for the worst case I can get tons of the items and groups). 

Additionally I want to set a custom height to all items (area2) and have no idea at the moment how to achieve it :(

Many thanks!

**Comment by josdejong** [comment]
The height is determined from the max value of (a) the height of the group label and (b) the total height of the (stacked) items in the contents pane.

To make the height smaller, you can use CSS to change the padding and font size of items, and use Timeline options `margin.item` and `margin.axis` to change the margins surrounding items.

**Comment by mast0r** [comment]
Thank you Jos, it works well!
