### ISSUE TITLE
Kamada-Kawai layout question

### ISSUE THREAD

**Issue by dragonzone** [almende/vis#1252]
I noticed in the history.md, you noted, "Added KamadaKawai layout engine for improved initial layout." So it this being used by default? If not, how do I try it out? How is it compared to barnesHut or can you use them both?

**Comment by AlexDM0** [comment]
Hi,

The layout is done by default automatically, regardless of the physics used. You can disable it by using the improvedLayout option:

http://visjs.org/docs/network/layout.html

Regards

**Comment by dragonzone** [comment]
I tried w/ 670 nodes (that are icons) and it seems to take about 1+ min. to stabilize. I guess this algorithm does not work in all cases?

**Comment by AlexDM0** [comment]
well you have to understand what it does: it positions nodes initially. After that the physics take over.

Try to disable stabilization and then try with and without improvedLayout to see the effect.

**Comment by dragonzone** [comment]
Yea, I tried disabling stablization and it still takes minutes. However, I did saw that it was faster w/ probably < 100 nodes. It seems that it will not work if I turn off physics. I just create a small circular w/ overlapping nodes like the attached image.

![untitled](https://cloud.githubusercontent.com/assets/10065158/9579869/9c41be5a-4fc3-11e5-8679-8765d7418b63.png)

**Comment by AlexDM0** [comment]
At the moment it will cluster larger networks in order to reduce the amount of nodes to  less than 100, positions them and declusters again.

I'd be interested in the data if it really does not work!

Do you get a message in the console?

Regards

**Comment by AlexDM0** [comment]
It is still in a circle after the improvedLayout is true?

Regards

**Comment by dragonzone** [comment]
Based on the documentation, the improvedLayout is true by default, so I didn't set it. Let me try to manually set it. 

Also, you said vis.js will auto cluster larger network, how is that being done? How do you know what to cluster? What criteria do you use to cluster those nodes together?

**Comment by dragonzone** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10065158/9580105/55ae512c-4fc5-11e5-9340-d7942f9a0ea7.png)

Above is about 1200+ nodes I have, I think it may be the physics that takes it longer to settle. Here are my config for it, can you see any issues w/ it?

```
			physics : {
				stabilization: false,
				barnesHut: {
					gravitationalConstant: -2000,
					centralGravity: 0,
					springLength: 100,
					springConstant: 0.1,
					damping: 0.09
				},
				maxVelocity: 25,
				minVelocity: 1,
	            timestep: 0.75,
			}
```

**Comment by AlexDM0** [comment]
Hi, 

Yes, it should be true by default. If your only option is physics:false, you should see the difference.

We cluster leaf nodes (nodes with 1 edge) to their connected node and we cluster bridge nodes (nodes with 2 edges) to their connected nodes. We do the bridge clustering every 3 cluster iterations.

This is why it's experimental :) If it cannot cluster anything, it will abort and print a message that your network does not work with the improved layout.

There has been a bugfix in the stabilization, before each stabilization iteration was counted double so for each iteration now, you'd have counted 2 before. If you have not changed anything, it will actually stabilize for longer than before.

Regards

**Comment by AlexDM0** [comment]
I'm not sure what's going wrong in the image you've sent? Looks good? There's nothing wrong with the settings perse

**Comment by dragonzone** [comment]
Shouldn't the Kamada-Kawai algo. already haven't taken into account all the physics to best calculate where they nodes should be on the network? Basically, what I am trying to do is spread the nodes out (like the image above, in prev. comments) instead of letting physics stablizing it, which takes is so long. I'm not sure if there a solution to it.

**Comment by AlexDM0** [comment]
The Kamada Kawai algo is currently using it's own physics to provide a good estimate. You're saying that you still get a circle after initialization if it is turned on?

The problem is that it is of complexity O(N^3), which is why I reduce the amount of nodes.

Regards

**Comment by AlexDM0** [comment]
As for your system, using dynamic edges over 500 nodes is usually not a great idea. Each edge will add another support node, so it becomes computationally expensive.

**Comment by dragonzone** [comment]
We are trying to find the maximum threshold vis.js can "properly" work or before the or the browser crashes. :D The users need this feature because they do extreme analytic that varies based on what they search and the nodes/edges that comes in can be in hundreds and 1000s at a time onto the same network, which can grow exponentially.

Anyway, good initial work first cut on the algo.; continue making improvements.

**Comment by AlexDM0** [comment]
Just so I understand whats happening, if you load that network, does it take minutes for the initial layout or including the stabilization?

**Comment by dragonzone** [comment]
I tried a few options with the default value of "improvedLayout". 

1) With physics: false (you will only see a circular layout, like the first image I've pasted in this ticket, you can also try worldCupPerformance.html, turn the physics: false, in your example, you'll see that it just
2) With
```
			physics : {
				stabilization: true,
				barnesHut: {
					gravitationalConstant: -2000,
					centralGravity: 0,
					springLength: 100,
					springConstant: 0.1,
					damping: 0.09
				},
				maxVelocity: 25,
				minVelocity: 1,
	            timestep: 0.75,
			}
```
also setting stabilization: false
It still take 1+ min. (for 1k+, it will be 2+ min) for the nodes to spread out properly. I also have the open the setting hideEdgesOnDrag: true, which will help much faster. But we do not expect the user to do that everytime. it's a hassle.

**Comment by AlexDM0** [comment]
For the worldCupPerformance, the kamada kawai algorithm does indeed not work. There are no leaf nodes to cluster there.

If you also turn off stabilization, all optimizations cannot be applied. The stabilization has an adaptive timestep that greatly helps. Even if you just run 400 iterations or something, maybe add a loading bar? From the sound of it, the issue is mostly the drawing. That is something I cannot optimize...

Regards
