### ISSUE TITLE
Vis.js Event Handler Couldn't access the Node Dataset Object

### ISSUE THREAD

**Issue by vramali1** [almende/vis#1253]
Hello,

I am vis.js object event handler in the following code structure below. When I checked the scope inside the select handler, the scope points to vis graph object. Because of this I couldn't access the dataset object corresponding to the Vis Graph Object. Following is the code. I want to access the Node dataset object inside the event handler. Could you please tell me how can I set the current scope to the event handler. 

this.nodes = new vis.DataSet(null);
var currentNode = {
			id : itemid,
			label : Ext.util.Format.ellipsis(itemname, 15),
			title : itemname,
			shape : 'box',
			allowedToMoveX : true,
			allowedToMoveY : true,
			sbbs : ['Kumar','USA']
};
this.nodes.add(currentNode);

new vis.Network(container, data, me.graphOptions);

this.VisObjectGraph.on('select', function(params) {
//PROBLEM
this.nodes ==== is not accessible.

}

}

Thanks & Regards
-Vijay

**Comment by AlexDM0** [comment]
Hi,

This has nothing to do with vis, this is basic javascript. I'd suggest you read up on scoping, for example here:
http://javascriptplayground.com/blog/2012/04/javascript-variable-scope-this/

This handles your problem.

Regards,

Alex
