### ISSUE TITLE
Network: network.unselectAll() still highlight selected node.

### ISSUE THREAD

**Issue by dragonzone** [almende/vis#1256]
I just noticed this, here is the example: http://jsfiddle.net/mzgdv3we/2/

**Comment by felixhayashi** [comment]
Hi @dragonzone,

I noticed the same. You can use the following workaround until it is fixed: `network.selectNodes([]);`

-Felix

**Comment by dragonzone** [comment]
Yea, I've currently changed to using that but wanted to mention to the vis.js team so they do the fix it.

**Comment by felixhayashi** [comment]
> […] but wanted to mention to the vis.js team so they do the fix it.

makes sense of course :)

**Comment by AlexDM0** [comment]
Hi all,

Thanks for notifying! Any idea when this was introduced? We'll get on this when we have time!

Cheers

**Comment by felixhayashi** [comment]
Hi Alex,

actually this never worked :) When I moved from v3 to v4 I discovered it didn't work and then just used the workaround above and made a TODO comment in my code to remind me to report it to you guys… and then completely forgot about it :neutral_face:

**Comment by AlexDM0** [comment]
Hi,

This should be fixed on develop now. Thanks for reporting! We'll release a bugfix release this week.

Cheers

**Comment by AlexDM0** [comment]
This has been fixed in 4.8.1
