### ISSUE TITLE
When using arrows with icons, the arrows don't appear at the end of the edge

### ISSUE THREAD

**Issue by jwalendowsky** [almende/vis#1257]
http://jsfiddle.net/771fox0o/13/

**Comment by AlexDM0** [comment]
Hi,

This is the intended behaviour. It does the same with certain shapes. 

Unfortunately we have nothing to do intersection checks on with the icons so we place the arrows at the bounding box. Same goes for shapes. Some of them cannot easily be described mathematically so we don't to gain performance. 

Sorry!
