### ISSUE TITLE
selectNodes and selectEdges simultaneously

### ISSUE THREAD

**Issue by kerwitz** [almende/vis#1258]
Both `.selectNodes` and `.selectEdges` remove any previously made selection.
I'd like to be able to select both, nodes *and* edges, at the same time. Any way this is possible?
I can't use `selectConnectedEdges` because that mainly selects edges *after* the node, while I want to highlight the path upwards through my network chart to its root node.

This does not work:

    network.selectNodes(nodeId, false);
    network.selectEdges(edgeId);

**Comment by kerwitz** [comment]
For those interested: while there's no way to select both, edges and nodes, on your own, you can simulate the edge selection by changing their color manually and resetting it when deselecting.
You may use [vis.js DataSets](http://visjs.org/docs/data/dataset.html) to update edges on the fly.

**Comment by AlexDM0** [comment]
Hi,

I think I'll add an option to deselect first to the selectnodes and select edges methods. Since we don't force uniqueness on ids between edges and nodes we can't use a setselection methods. Edge and node could both have id 1

I agree with you that it's a weird setup at the moment. 

We'll work on this. 

Cheers

**Comment by josdejong** [comment]
@AlexDM0 I think we had some discussion quite some time ago for a method `setSelection({nodes: [...], edges: [...]})` to complement the `getSelection()` method. What do you think?

**Comment by AlexDM0** [comment]
Now that you mention it... That could be a better option indeed. 

Cheers

**Comment by kerwitz** [comment]
Another option could be to accept a boolean argument on `selectNodes` and `selectEdges` to let the user decide wether or not a previous selection should be removed or not.
