### ISSUE TITLE
Graph2d tick rounding problem for small y values

### ISSUE THREAD

**Issue by johanfforsberg** [almende/vis#1259]
I'm using Graph2d to plot values changing over time. I have noticed that when the value of the highest data point is so small that the y axis gets some ticks smaller than 1.0, these are sometimes written with too much precision, e.g. 0.5825000000000001 or 0.03749999999999999. It's inconsistent, some tick labels look OK. I've not seen this happen for ticks larger than 1.

**Comment by josdejong** [comment]
Thanks for reporting this. Sounds like we need to fix something in the rounding of the values on the y axis.

**Comment by ludost** [comment]
This should be fixed with commit 257d876e14080d0f0595ac467e0660ca34b2c00a, due next release.
