### ISSUE TITLE
Wrong link in docs on visjs.org

### ISSUE THREAD

**Issue by littleguga** [almende/vis#1260]
[Here](http://visjs.org/docs/graph2d/#timelineOptions) in points 'locale' and 'locales' link on 'localization' is broken. Right now it's: ` http://visjs.org/docs/graph2d/timeline.html#Localization  ` but it should be `http://visjs.org/docs/graph2d/#Localization `

I hope i reported it to the right place.

**Comment by josdejong** [comment]
Fixed by @Tooa via #1261
