### ISSUE TITLE
Collapse groups into one unit? Multiple groups?

### ISSUE THREAD

**Issue by Ma-XX-oN** [almende/vis#1262]
Sorry, this isn't an issue as more than a question.

I have several nodes that have overlapping grouping criteria, some of which are subsets of other groups, others which span across different groups  i.e. logical vs physical representation.  I'd like to know if it is possible to:

1. Change grouping view from one to another.
2. Collapse a subset group of nodes to a single entity / Expand collapsed group to individual entities.

This looks to be a very large and comprehensive library and have some interest in using it to do some analysis.

**Comment by AlexDM0** [comment]
Hi,

Im not sure if you're referring to the network or the timeline. Could you explain this a bit clearer? Maybe a picture?

Cheers

**Comment by Ma-XX-oN** [comment]
Sure.  Well, lets see if I can. :)

So for my item 2, here is an example:

> The following image has 3 groups:

> ![image](https://cloud.githubusercontent.com/assets/10625935/9644606/14578ff0-5195-11e5-8761-9f08ed3c5434.png)

> Group 1 has nodes b and c.
> Group 2 has nodes a, d and Group 1.
> Group 3 has nodes e, f, and g.

> I'd like it so that I can collapse items in Group 1 into one virtual node, or collapse Group 2 items into a virtual node, or collapse items in Group 3 into a virtual node, or any combination thereof.

As for my item 1.  Hmmm.

> Given the same diagram, say that grouping is valid, but there is another different grouping which means something different like:

> 
![image](https://cloud.githubusercontent.com/assets/10625935/9645276/92b61774-5198-11e5-865a-8894e9bf26e7.png)

**Comment by dragonzone** [comment]
For item 2, vis.js that type of grouping is called, "clustering". You can see example here: http://visjs.org/examples/network/other/clustering.html. We use this heavily in our app.

**Comment by AlexDM0** [comment]
Hi,

Dragon is right, clustering is what you're looking for. As for your other item, either the render events that allow you to draw your own rectangles around nodes or no, that's not possible.

Regards

**Comment by Ma-XX-oN** [comment]
Thanks dragonzone.  Alex, I'm not sure what you are saying.  That it is not possible to draw rectangles around nodes?

**Comment by AlexDM0** [comment]
It is if you do it yourself using the render events: 

http://visjs.org/examples/network/events/renderEvents.html

Other than that there is no support for drawing anything around multiple nodes. 

Regards

**Comment by Ma-XX-oN** [comment]
No way to surround multiple nodes.  Got it.  Could this be a feature request?

**Comment by AlexDM0** [comment]
Hi,

It could but given the possibilities with the render events we prefer that these are used for this purpose. 

@Tooa recently tried this in an issue, see #1201. 

Regards

**Comment by Ma-XX-oN** [comment]
Hmmmm. Would it be possible to force a cluster further away from others then?  Like an antigravity setting to push one cluster away from another?

**Comment by AlexDM0** [comment]
Hi,

The physics are based on an inverted gravity model if you're using barnesHut or FA2based. 

All nodes have mass and you can set that value. You can use the clustering methods to set the mass of the cluster either a fixed value or based on the amount of nodes in there, a conservation of mass. 

Higher mass means greater repulsion.  

Good luck!
