### ISSUE TITLE
[Feature request] Git commit topology graph visualization

### ISSUE THREAD

**Issue by FarzadT** [almende/vis#1264]
Hi, how hard would it be to implement a visualization module of a git commit topology. I was looking into http://gitgraphjs.com/ but it does not have the great features that visjs has (hit detection, etc.)

**Comment by AlexDM0** [comment]
It should be easy, position your nodes manually and connect them. 

Cheers

**Comment by AlexDM0** [comment]
Hi,

To be clearer, this is not a feature of vis. You can use vis to draw these networks. We will not implement a method especially for this.

Regards
