### ISSUE TITLE
copypasta error in docs

### ISSUE THREAD

**Issue by SomeKittens** [almende/vis#1267]
http://visjs.org/docs/network/#options

<img width="1047" alt="screen shot 2015-09-03 at 2 07 40 pm" src="https://cloud.githubusercontent.com/assets/1616464/9671099/399083c0-5245-11e5-9b1c-04140f44289f.png">

**Comment by josdejong** [comment]
Thanks, this is fixed now in the develop branch.

**Comment by SomeKittens** [comment]
Awesome, quick fix!
