### ISSUE TITLE
Nodes in a straight line  : Network

### ISSUE THREAD

**Issue by devgitk** [almende/vis#1268]
Hi ,
In the Hierarchical Layout example;
When I input 3 nodes and direction is Left-Right, the nodes get displayed like this below :
![capture1](https://cloud.githubusercontent.com/assets/12658481/9677071/d82af83c-52f2-11e5-9022-7950f89bdca5.JPG)
I want the nodes to be straight (same level) always in a line (Left to Right) irrespective of the number of nodes, any leads on this?!

Thanks :)

**Comment by AlexDM0** [comment]
Hi,

I assume you want 0 -> 1 -> 2

You can use the directed mode or manually assign the levels for this. 

Also, make sure the spring length is equal to the level seperation. 

If there are 2 nodes on the same level (like in your picture) they will not be on the same line. 

You can also just loop over your data and manually set the x and y and fix them in place. 

Regards

**Comment by devgitk** [comment]
Hi Alex,

Thanks for your quick reply!

Exactly, I do want  0 -> 1 -> 2 in a line;

I manually do not want to assign positions as the no of nodes and the type of nodes might increase and I'm loading the data from JSON.    

- Any specific layout that I should use? 

Many Thanks! :)

**Comment by AlexDM0** [comment]
Directed would be easiest but that assumes the direction of the edges is from 0 to 1 etc. 

You would probably be best off looping over your data before you load it into vis. You say you don't want this but that does not really make sense. It is completely independent of where the data comes from and it would give you full control. It would be the best method by far. 

Regards

**Comment by devgitk** [comment]
Hi @AlexDM0 ,

Wanted to know if we will be able to position the network graph on the canvas , like we define it for the  nodes. E.g. if I give (x,y) = (10,10) , the graph  0 -> 1 -> 2 should be initially loaded at this position on the canvas!

Thanks !

**Comment by AlexDM0** [comment]
Hi,

Yes that is possible. There is more to consider though. See #1235 for more information. 

Regards

**Comment by devgitk** [comment]
@AlexDM0  #871 issue did it all !
Used the moveTo method.

Thanks :)
