### ISSUE TITLE
Overlapping edges in hierarchical network

### ISSUE THREAD

**Issue by seemakamble** [almende/vis#1269]
Hi,

We are using hierarchical network.

We observed that the edges are getting overlapped over each other if there are multiple edges between two nodes.

Please see the example on plunker: http://plnkr.co/edit/kaJqM9XxCEZtNYJMpKQH?p=preview

There are four links between Node 0 and Node 1, but those are getting overlapped over each other.

Thanks,
Seema

**Comment by AlexDM0** [comment]
Hi,

in your example they don't overlap?

**Comment by seemakamble** [comment]
Hi Alex,

Please see the screenshot below:
![edge_overlap_issue](https://cloud.githubusercontent.com/assets/14121871/9734191/aad32666-564e-11e5-911a-4bba0c8da2e1.jpg)

There are total four edges between Node 0 and Node 1, but these edges appear to be overlapped and it looks like only single edge is there.

The requirement is to display all these edges in parallel. Is there a way to resolve it?

Thanks,
Seema

**Comment by AlexDM0** [comment]
Hi,

I see two lines in the plunker but yes, there is overlap. There is nothing that can be done about this in the hierarchical layout at the moment, sorry. 

The dynamic smooth edges are made for this but they are not supported in the hierarchical layout.

Regards

**Comment by seemakamble** [comment]
Hi Alex,

Is there any plan to add this feature in upcoming release?

Thanks,
Seema

**Comment by AlexDM0** [comment]
Not at the moment as it requires quite a big change to the backend. We will consider this for future releases but it's not on our immediate todo list.
