### ISSUE TITLE
Display border for the selected state of the node

### ISSUE THREAD

**Issue by seemakamble** [almende/vis#1271]
Hi,

We are using hierarchical network layout with font icons for the nodes. 

We want to display border around the selected node.

Tried to give border width and border color but that is not working with shape: 'icon'. Is there any way to achieve this?

Here is the plunker link: http://plnkr.co/edit/BLuQgGY6e33bUtyDySCd?p=preview

Thanks,
Seema

**Comment by AlexDM0** [comment]
Hi,

Icons can not have borders. 

You could however use the render events to draw a shape around a node manually. 

Take a look at this example. 

http://visjs.org/examples/network/events/renderEvents.html

Regards
