### ISSUE TITLE
Network automatically zooms out

### ISSUE THREAD

**Issue by mlazo** [almende/vis#1273]
When I load any of the network examples and click on a node or edge or even close to the graph the image zooms out, making the graph tiny and moving it towards the upper left hand side of the screen. I have tried this in Safari, Chrome and Firefox.

The example being shown below is examples/network/basicUsage.html

Prior to clicking:
<img width="638" alt="screen shot 2015-09-04 at 6 00 15 pm" src="https://cloud.githubusercontent.com/assets/7219619/9695363/e50932b2-532e-11e5-86e0-d73577e33241.png">

After first click:
<img width="614" alt="screen shot 2015-09-04 at 6 01 36 pm" src="https://cloud.githubusercontent.com/assets/7219619/9695382/08f8f7e8-532f-11e5-8c52-5976c1af80d6.png">

After second click the graph is too tiny to see

**Comment by eranation** [comment]
yep

**Comment by zallek** [comment]
+1

**Comment by lievenmatthys** [comment]
+1
On windows 8.1 in IE 11, I see this behavior, even just moving over graph, on Network and Timeline examples from visjs.org
Problem does not happen on Chrome.

**Comment by AlexDM0** [comment]
Hi All,

We're working on fixing this. Hopefully we can release a fix for this next week.

Sorry for the trouble!

**Comment by AlexDM0** [comment]
Hi,

This should be fixed on develop now. Thanks for reporting! We'll release a bugfix release this week.

Cheers

**Comment by mlazo** [comment]
Great. Thanks

Sent from my Verizon 4G LTE Smartphone

----- Reply message -----

**Comment by AlexDM0** [comment]
This has been fixed in 4.8.1
