### ISSUE TITLE
nodes horizontal spacing in network graphs

### ISSUE THREAD

**Issue by adidegani** [almende/vis#1274]
Is there are to control the horizontal spacing of nodes in a network graph? they seem to run over each other which is very inconvenient.

Thanks

**Comment by AlexDM0** [comment]
Could you elaborate a bit? I assume hierarchical layout? In that case, 
http://visjs.org/docs/network/physics.html

hierarchicalRepulsion.nodeDistance

Regards

**Comment by adidegani** [comment]
Yes, exactly, hierarchical layout.
The thing is, i’m not using the physics option. I turned it off so i can move nodes around with mouse.

Appreciate it! 

Adi

**Comment by AlexDM0** [comment]
Hi,

In that case, no. You could however enable physics but listen to the stabilized event. This will position them for you. At the stabilized event you can call setOptions({physics:false}) to disable them.

Regards

**Comment by adidegani** [comment]
I see….

Thought maybe i’m simply able to style those nodes with something like ‘margin: 5px’…
Oh well...
Guess i’ll stick to no-physics and re-ordering those nodes by hand.

Thanks a million, Alex :)

Adi

**Comment by AlexDM0** [comment]
Hi Adi,

There really is no downside in using the physics and disabling them the first time they are drawn, but it's up to you.

Cheers

**Comment by adidegani** [comment]
you know what? i’ll give it a shot….

Thanks again!

Adi

**Comment by ahmadtausif** [comment]
me too disabled Physics at first...but was looking for horizontal margin....cheers guys!!!
