### ISSUE TITLE
Timeline: limit horizontal drag area to the timeline axis area

### ISSUE THREAD

**Issue by mast0r** [almende/vis#1277]
Hi, I want to limit the area where user can grad the timeline only to the axis area ("vis-top"). And allow only horizontal dragging. Is it possible? 

![timeline_drag](https://cloud.githubusercontent.com/assets/9842532/9719042/31e7c13a-5581-11e5-91ea-1d5a4de3e19a.png)

Many thanks.

**Comment by josdejong** [comment]
This is not supported. You will have to do some hacking in the Timeline to achieve this. The easiest may be to override the [Range.prototype._isInsideRange](https://github.com/almende/vis/blob/master/lib/timeline/Range.js#L589-L597), and change it such that it returns false also when the mouse is clicked outside of the TimeAxis.

**Comment by mast0r** [comment]
Jos, many thans, it works!
