### ISSUE TITLE
Network: selectNode event - nodes ids are casted as string.

### ISSUE THREAD

**Issue by zallek** [almende/vis#1278]
In Network, selectNode event data returns a property `nodes` with the list selected nodeIds **casted as string**

version: 4.8.1

Example: returns `['2']`whereas given node id was `2`

**Comment by AlexDM0** [comment]
Hi,

Yes, I suppose we can fix this. It's a little sloppy after all.

Thanks for notifying us!

**Comment by AlexDM0** [comment]
Ths has been released in 4.12
