### ISSUE TITLE
Network: wrong return type in documentation for getViewPosition()

### ISSUE THREAD

**Issue by kerwitz** [almende/vis#1279]
Where: [http://visjs.org/docs/network/](Network documentation), Methods, "Methods to control the viewport for zoom and animation"

Current return type listed: `Number`

Actual return type: `{Object} { x: {Number}, y: {Number} }`

**Comment by AlexDM0** [comment]
Hi,

Thanks for reporting! We'll update this soon!

Cheers

**Comment by AlexDM0** [comment]
Hi,

I've updated this on develop, it will be added in the next release. Thanks for the update!

Cheers

**Comment by AlexDM0** [comment]
Released in v4.9.0

**Comment by kerwitz** [comment]
:+1:
