### ISSUE TITLE
Network: Phantom links reappearing again in latest v4.8.1

### ISSUE THREAD

**Issue by dragonzone** [almende/vis#1281]
It was also in v4.8.0. Here is example: http://jsfiddle.net/fjvwyvy0/

**Comment by AlexDM0** [comment]
Hi Dragon,

I'll get on this when I can. Sorry, I rewrote the clustering partly for the kamada kawai feature and I tested it a lot. Seems not enough.

Sorry!

**Comment by AlexDM0** [comment]
Hi Dragon,

Luckily this was an easy fix, clearly identified. The larger issue that was behind it previously is still solved. I've pushed a fix to develop for this. We'll release a new version soon.

Regards,

Alex

**Comment by dragonzone** [comment]
When do you anticipate the next release date?

**Comment by AlexDM0** [comment]
Cant say at the moment. Probably within a week or so.

The develop branch is stable now though, the only change so far has been this fix. Temporarily you could also just look which lines have been altered and change them yourself if you'd prefer.

Regards

**Comment by dragonzone** [comment]
How do I generate the source code (that you said you fixed) and output to vis.js file?

**Comment by AlexDM0** [comment]
I think this is all you need:
https://github.com/almende/vis#build

**Comment by dragonzone** [comment]
They block npm here, so I'll just have to wait for the release version instead.

**Comment by AlexDM0** [comment]
We'll check if we can release this week. 

Cheers

**Comment by AlexDM0** [comment]
Just released in v4.8.2
