### ISSUE TITLE
Set any css property to nodes and edges

### ISSUE THREAD

**Issue by jean-morissette** [almende/vis#1282]
At the moment, it's possible to set a few predefined styling properties, thanks to object options. For example:

```javascript
        options:{
            nodes:{
                borderWidth: 1,
                borderWidthSelected: 2           
            }
        }
```

However, it's not possible to set any styling property. What if I want to add padding inside my node? What if I want to use a custom shadow to nodes? Etc...

Instead, we should be able to set any css properties for maximum styling customization.

**Comment by AlexDM0** [comment]
Hi,

the network is not using the DOM. ITS a HMTL5 canvas. Css is not relevant here. 

If you want to change more than currently available, either specify an area that you want more control over and we'll treat it as a feature request or contribute extra styles to the project. 

Regards,

Alex
