### ISSUE TITLE
Icon shape: Clicking the label doesn't select the node

### ISSUE THREAD

**Issue by pheraph** [almende/vis#1283]
If the icon shape is used for nodes in a network, only a click on the icon selects the node but not a click on the label:

http://visjs.org/examples/network/nodeStyles/icons.html

Especially longer titles have a strong incentive to click them and should select the node.

**Comment by AlexDM0** [comment]
Hi,

We disagree actually. The label can very easily overlap with edges or other nodes if it becomes too big, making it very difficult to select items below it.

Regards
