### ISSUE TITLE
Display network nodes in the order of the array

### ISSUE THREAD

**Issue by pheraph** [almende/vis#1284]
I have a DataSet with ~10 elements which are displayed in a network. Can I somehow keep the original order of the elements in the DataSet and arrange them clockwise as nodes in the network? I found out the hierarchical layout respects the order of the DataSet, but this layout doesn't fit my needs here. I also know I can reload the page until I get the desired seed via ````getSeed()````, but there a lot of reloads necessary to get the wanted seed. Any elegant solution for this case?

**Comment by AlexDM0** [comment]
Hi,

You can just specify a x and y coordinate. If you use fixed, they will stay there. You could also disable physics to not allow them to move.

Regards
