### ISSUE TITLE
Network: Shouldn't event, stabilizationProgress, be also called when new nodes/edges has been added to the network?

### ISSUE THREAD

**Issue by dragonzone** [almende/vis#1286]
I notice only the event, stabilized, is called when you added new nodes/edges to the network. Why?

**Comment by AlexDM0** [comment]
Hi,

Thats because there is no progress. The stabilization progress only refers to the 'hidden' stabilization phase. There are no maximum iterations for stabilization when everything is visible. It just goes and goes. You can manually call stabilize() to trigger this phase later on though.

Regards

**Comment by dragonzone** [comment]
Is there a way, once the network is drawn, that later user add lots of nodes & edges (say 100s or 1000s), that when it's being added, hides all the nodes & edges (so it'll be faster) and the stabilizationProgress, is called, showing the status and when done, re-display all those nodes & edges?

**Comment by AlexDM0** [comment]
Hi,

Yes. 

Dataset.update()
Network.stabilize()

Cheers

**Comment by dragonzone** [comment]
Works like a charm, thx! Will let users try out this new feature.

**Comment by AlexDM0** [comment]
Glad it works :)

Good luck!

**Comment by dragonzone** [comment]
When you do, 

```
Dataset.update();
Network.stabilize();
```

Do you only do the physics on ONLY the updated nodes/edges or do you do it again to ALL of the nodes/edges? And is the the Kamada-kawai algo. re-applied?

**Comment by AlexDM0** [comment]
Hi,

You do it on the entire network. The layout algorithm is not applied here. 

Regards

**Comment by dragonzone** [comment]
Then is there any real improvement in performance between doing the update & stabilize instead of re-creating the network with all the nodes & edges?

**Comment by AlexDM0** [comment]
Well that depends on what you do. If you have 50 nodes and you add one, then yes, the perturbation is very small. Especially if you position that node close to where it's parent is (that is something we should look at later on as well).

If you have 1000 nodes which you all delete and then update the dataset then no, physics-wise it's the same as recreating the network.

In general the initial position of the nodes that are already there helps to reduce the amount of iterations required. You can also do network.stabilize(100) to only do 100 iterations without going through the config.

Regards
