### ISSUE TITLE
add style in nodes in the network

### ISSUE THREAD

**Issue by kevindu1993** [almende/vis#1287]
I want to add a style in node in the network, for example add 'cursor:pointer' in nodes style. Is there any way to solve this problem?

**Comment by AlexDM0** [comment]
I don't think so. You could set it on the container? It won't adapt to the node though. 

Regards

**Comment by zallek** [comment]
You can add cursor pointer when a hoverNode event is fired and remove it at blurNode. It should do the trick (didnot test though).

**Comment by AlexDM0** [comment]
That's true, that could solve the issue. Good point!
