### ISSUE TITLE
Changing title of CustomTime bar

### ISSUE THREAD

**Issue by Abrazan** [almende/vis#1288]
Hi all,

First and foremost: thanks for this great library.

I propose to add the possibility to change the title (visible when hovering) of a custom time bar.
Now it shows the current date of the bar by default (Time: 'dddd, MMMM Do YYYY, H:mm:ss'), but there is no option to change this behavior. We could also integrate this feature in the 'current' time bar. 

I do not have much experience (yet) in contributing to these kind of projects but I made a fork and implemented a simple solution to this problem in a branch of the develop-branch (https://github.com/Abrazan/vis/tree/custom-timeline-title). My solution uses an extra method on the timeline called setCustomTimeTitle(title [, id]). I hope this is the way to go, but any advice is always welcome! 

Kind regards,
Arno

**Comment by josdejong** [comment]
Thanks for your suggestion. This title is indeed hard coded right now. Your approach looks like a good solution to me, you could do a pull request to the `develop` branch of vis.js with this new feature :).
