### ISSUE TITLE
Requiremnet May be helpfull  "to display total number of child node as a count just above the parent node"

### ISSUE THREAD

**Issue by manalisha** [almende/vis#1289]
In Network to display total number of child node as a count just above the parent node.

![childcount](https://cloud.githubusercontent.com/assets/4456244/9785561/df805c5c-57d0-11e5-882a-a5aa86263e79.png)

Code to Do this :

Node.prototype.setProperties = function(properties, constants) { ..... ....
write: if (properties.childCount !== undefined) {this.childCount = properties.childCount;}

Node.prototype._drawCircularImage = function (ctx) {
..............
..............
Write : /* code to draw circle above node if child node is present or not./
if(this.childCount>0){
ctx.lineWidth = 1.0;
ctx.strokeStyle = 'white';
ctx.fillStyle = this.options.color.background;
ctx.beginPath();
ctx.arc(centerX+15, centerY-20, radius/2, 0, 2Math.PI, false);
ctx.closePath();
ctx.fill();
ctx.stroke();
ctx.fillStyle = 'white'; // font color to write the text with
var font = radius/2 +"px serif";
ctx.font = font;
ctx.textBaseline = "top";
ctx.fillText(this.childCount, centerX+15, centerY-25);
}

**Comment by AlexDM0** [comment]
Hi,

You can actually do this using the render events. I don't think we'll add this to the main repository. There are too many cases that are not covered for this and a lot of people may want to customize this.

The render event afterDrawing allows you to get the positions of the nodes, then draw your custom things on top of the nodes.

It is a nice usecase though! Looks good!

Cheers
