### ISSUE TITLE
Network: Removing node inside a cluster and then opening cluster throws error

### ISSUE THREAD

**Issue by dragonzone** [almende/vis#1291]
Here is the example: http://jsfiddle.net/umecqna8/

**Comment by AlexDM0** [comment]
Errr... yes. At the moment, dynamic data and clusters don't play nice together. I'll update this in future versions. This is also the reason your other issue does not work at the moment.

Thanks for the heads-up!

Regards

**Comment by dragonzone** [comment]
Which one, I forgot. Can you refresh me?

**Comment by AlexDM0** [comment]
#1218

**Comment by dragonzone** [comment]
The power is really being able to change the data on the fly. Not static data, that's old school. B)

**Comment by AlexDM0** [comment]
Yes, but the book-keeping is not up to speed yet. This will have to be implemented nicely and recursively.

**Comment by hengchu** [comment]
Hi @AlexDM0, for this issue and #1218, I'd like to help fix them if you haven't had the chance to work on them yet. Would you mind letting me know which part of the code base needs to be modified to fix them? Thanks! BTW this is a great library :)

**Comment by AlexDM0** [comment]
Hi,

Its all in the clustering file. It needs to listen to the dataChanged event and cleanly and recursively update the bookkeeping. You'll also need to fix #1315 

Regards

**Comment by AoDev** [comment]
@mojoaxel I was checking the code regarding this today and I actually made the clustering work and support node removal while clustered. But as I read the code, I got many questions and I wonder if it would be possible to speak with someone about it.

**Comment by wimrijnders** [comment]
> But as I read the code, I got many questions and I wonder if it would be possible to speak with someone about it.

@AoDev I only noticed this statement just now. Are you still looking for someone to speak with? I am hereby available.

**Comment by AoDev** [comment]
@wimrijnders Thank you. But since February I am not working with vis. I can not work on it at the moment.

**Comment by wimrijnders** [comment]
@AoDev Yeah, well it *was* a long time ago, from before I became admin. Well, if you ever want to revisit it, notify me.
