### ISSUE TITLE
Edges incoming arrows disappear when selecting triangle shape node

### ISSUE THREAD

**Issue by fedorov** [almende/vis#1292]
Before node is selected:

![image](https://cloud.githubusercontent.com/assets/313942/9818491/e5477778-5876-11e5-8c24-7f288627833b.png)

After node is selected:

![image](https://cloud.githubusercontent.com/assets/313942/9818499/f051a058-5876-11e5-8f71-1a3b89d107c3.png)

I don't see the same problem for other node shapes.

**Comment by AlexDM0** [comment]
Hi,

I've fixed this on develop and it will be released very soon. Thanks for the heads up!

Cheers

**Comment by fedorov** [comment]
:+1:

**Comment by AlexDM0** [comment]
Just released in v4.8.2
