### ISSUE TITLE
Arrow heads not displayed or displayed at wrong place in v4.8.2-SNAPSHOT

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#1294]
Hi @AlexDM0 

When I update from v4.8.0 to the current develop version (4.8.2-SNAPSHOT) some arrow heads are suddenly misplaced or not shown. When I set it back, everything works.

**Before** update to 4.8.2-SNAPSHOT:

![2015-09-11 21 35 08](https://cloud.githubusercontent.com/assets/4307137/9824587/0f39c836-58ce-11e5-91b3-7b7dbacbd593.png)

**After** update to 4.8.2-SNAPSHOT:

![2015-09-11 21 37 58](https://cloud.githubusercontent.com/assets/4307137/9824595/1c254c96-58ce-11e5-95a9-ec14941cc4d8.png)

(With transparency for a better view)

![2015-09-11 21 40 59](https://cloud.githubusercontent.com/assets/4307137/9824605/2be23a90-58ce-11e5-843b-c2eb690f474a.png)

### Some findings

* Seems like this **only** happens when an edge points to a node with an icon (e.g. using Font Awesome). Arrows to images seem to work. (see also screenshots above)
* Middle arrows are correctly displayed in any case.
* In some cases the "to" arrow head is displayed at the beginning of a node. Again, this only happens for icons using the prerelease.

-Felix

**Comment by felixhayashi** [comment]
Maybe related to #1292?

**Comment by AlexDM0** [comment]
Hi Felix,

I'll fix this before release. Thanks for the heads up!

Cheers

**Comment by felixhayashi** [comment]
Thanks Alex!

**Comment by AlexDM0** [comment]
Hi Felix, 

This has been pushed to develop.

Regards

**Comment by felixhayashi** [comment]
Yesss! Just tested it. Very nice.
Thanks Alex!

-Felix

**Comment by AlexDM0** [comment]
Just released in v4.8.2
