### ISSUE TITLE
Timeline: Generated divs include inline style attributes that make CSS styling difficult

### ISSUE THREAD

**Issue by paolovalladolid** [almende/vis#1295]
Timeline now generates divs that include inline styles that override custom CSS.  This makes it difficult to adjust positioning of items, height values etc.  For example, items have a "top: 10px" inline style which causes the items to appear partially positioned in the next group below instead of the group they are supposed to be in.  I used to be able to do something like this and have a "top: 0px" style guaranteed for my items:

.vis-item {

```
// Prevent content from leaking to the right and also prevent it from
// sinking too far from the top
top: 0px !important;
```

  }

**Comment by josdejong** [comment]
All styling of the Timeline is done via CSS. The positioning though is done (and has to be done) via JavaScript: items have to be stacked and positioned at the right place, and positioning changes when you zoom and move the Timeline.

If your items are positioned partially in the next group, I think something else is going wrong. Probably the size of the item is wrongly calculated. Can you explain what happens?

**Comment by yotamberk** [comment]
@paolovalladolid Is this issue still relevant?
