### ISSUE TITLE
Timeline: customTime not draggable

### ISSUE THREAD

**Issue by hdlopesrocha** [almende/vis#1296]
I've some customTimes that are not allowed do be dragged, I just can change them programatically.
Is that possbile?
Thanks ;-)

**Comment by josdejong** [comment]
Maybe you can change the CSS `pointer-events` property of the time bar so that you disable all events: https://developer.mozilla.org/en/docs/Web/CSS/pointer-events

Or else you can listen for the `timechange` event of the bar, and set the time back to the only allowed value with every (attempt) to change.

**Comment by hdlopesrocha** [comment]
Yes, I've set "pointer-events" to "none" and  it worked! Thanks ;-)

**Comment by josdejong** [comment]
Ah, great, thanks for the feedback.

**Comment by dapriett** [comment]
Hello,

I also want to be able to disable dragging customTimes.  Unfortunately "pointer-events" will also disable tooltips as well.  I'll look into the `timechange` event - but maybe we can add an option for the addCustomTime to disable drags?

**Comment by josdejong** [comment]
The basic idea of these custom bars was that the user can drag the bar. Having fixed custom bars looks more like you just want to display some annotation. Maybe it's better to see your bars as regular data items? You could create a new item type "bar" for this.

**Comment by dapriett** [comment]
We're using groups for our timeline, but we're showing a milestone date which goes across all the groups.  Custom bars seems like the best way to do that with the current implementation.  Does the timeline provide a way for items to span across all groups?  The would be cool if you could have a bar type, or even a range bar type, that could do that.

For now, I just do something like this...

```
timeline.addCustomTime(date, id)
timeline.customTimes[timeline.customTimes.length-1].hammer.off("panstart panmove panend");
```

**Comment by josdejong** [comment]
> Does the timeline provide a way for items to span across all groups? 

no unfortunately not.
