### ISSUE TITLE
Type of nodes connection

### ISSUE THREAD

**Issue by LuckyJes** [almende/vis#1297]
Hello.
When I was working, I got a problem.I need to show up specific block when I connect two nodes with the same type.
I need something like this:
When i connect node with type "car" to node with type "car" need to show up specific block.
Can you help me with this?
Thanks!

**Comment by AlexDM0** [comment]
Hi,

I have no idea what you mean :) I would assume you're using the manipulation system
http://visjs.org/docs/network/manipulation.html

The rest sounds like plain old javascript. The addEdge seems to be what you need. Insert your callback and do stuff with it :)

Cheers

**Comment by LuckyJes** [comment]
Hello,
I understand and work with addEdge.But the problem is that this function only takes 2 parameters "from" and "to".
I try to explain again:
I have two nodes, with the same type
![screenshot_1](https://cloud.githubusercontent.com/assets/3456645/9846750/d854fd98-5adc-11e5-9765-3619aae11d4a.png)
and when I connect them, I want to appear a window (much like AddNode)
![screenshot_2](https://cloud.githubusercontent.com/assets/3456645/9846993/c4ce9cb4-5ade-11e5-9b0c-aa3f0fb7880d.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/3456645/9847013/debc3474-5ade-11e5-8873-60b427983365.png)
at the moment I do a window to appear when connecting any Nodes. But can't understand how to do it only for nodes with same type.

Thank you for helping to find a solution!

**Comment by AlexDM0** [comment]
I see. The from and to are IDs. You can use these IDs to look up the full node data in your dataset. Once you have the full node definition you can use that to determine what you need to do.

Regards

**Comment by AlexDM0** [comment]
To add to this, there will be an extra callback soon(ish) that will allow you to abort the dragging before it starts based on the source node.

I cant give an ETA for this though.

Regards

**Comment by LuckyJes** [comment]
Damn. it was so easy, thanks a lot!
Can I still ask about the function deleteEdge?
It returns a connection id like " f7fe3807-3901-4851-b694-afc749fc9091 ",but i need normal id like "1"

Thanks! :)

**Comment by AlexDM0** [comment]
Delete edge is just saying what the id of the edge is. If you want ID 1, you'll have to give it ID 1. That method is not going to lie to you to make it look prettier ;)

**Comment by LuckyJes** [comment]
I mean, I need to remove the edge in the database. For this I need the ID, but it "f7fe3807-3901-4851-b694-afc749fc9091" is not the same with id in database.

**Comment by AlexDM0** [comment]
Did you give your edges the same IDs as in your database?

**Comment by LuckyJes** [comment]
It AI in database, or am I mistaken?
![screenshot_4](https://cloud.githubusercontent.com/assets/3456645/9850091/eb117526-5af8-11e5-98c5-b126d32bc404.png)

**Comment by AlexDM0** [comment]
You realise vis does not have a database right? I have no idea what you put into vis.

**Comment by LuckyJes** [comment]
Oh, damn. sorry
I work with plugin and forgot it.
You can close topic

i`m realy sorry and thank you for help!
