### ISSUE TITLE
Can vis.js be used on mobiles? Can it zoom?

### ISSUE THREAD

**Issue by peterheard01** [almende/vis#1298]
Just wondered if anyone used any zoom functionality with this for use with mobile devices?

**Comment by AlexDM0** [comment]
Yes. It works.

**Comment by peterheard01** [comment]
Thanks Alex I couldn't find any recommendations on the documentation about doing zoom, is this built in?

**Comment by AlexDM0** [comment]
Yes, pick any mobile device and go to http://visjs.org/ and try the examples. Zooming on nearly every touch screen is pinching. Pinch to zoom.

**Comment by satya77** [comment]
The only thing that is not supported is right click!

**Comment by pratimjana** [comment]
> The only thing that is not supported is right click!
Context menu can be used by long press in mobile.
