### ISSUE TITLE
Network: Managing backgrounds behind image nodes without excessive redraws

### ISSUE THREAD

**Issue by CHgsd** [almende/vis#1299]
I am in the process of porting code over from VivaGraphJS and am attempting to draw a background behind some nodes which are image based. I have created an example here:
http://jsfiddle.net/daLaj8bv/1/ (This example leverages the concepts from http://visjs.org/examples/network/events/renderEvents.html )

What I have encountered is that these backgrounds are redrawn MANY times as the stabilization is taking effect along with resize, drag and any other interaction. Is there a better way to achieve this? I seem to be hitting some scaling issues and would ideally like to do this in a more performant manner.

And of course thank you for the awesome library and awesome documentation! I was able to port everything over quite nicely so far!

**Comment by AlexDM0** [comment]
Hi,

The replace and the console log are actually quite heavy operations. Obviously other options are to make a few extra images that already include your background. 

The network works on a canvas, which is redrawn at 60fps. There are no moving objects, just a picture that is cleared and redrawn. 

The size of your image can also affect your performance so try to keep it as close to the actual size of the nodes at scale 1. 

Regards

**Comment by CHgsd** [comment]
Thank you for the feedback! I have attempted without the replace and console.log and do see an improvement as you suspected, however not as much as I was sheepishly hoping for.

The main reason behind not having the images pre-rendered is the desire to dynamicaly represent data in near realtime through various visual queues. This will result in a phenomenal number of permutated pre-rendered images and unlikely to be manageable. That being said I will keep that option in the back of my mind as a fallback.

Thank you again for the feedback and suggestions!

**Comment by AlexDM0** [comment]
Hi,

I've pushed a new feature to develop that allows you to place borders and background color behind an image. It will be released in v4.9.0.

Regards

**Comment by CHgsd** [comment]
Thank you!
