### ISSUE TITLE
Expand Collapse functionality in Network

### ISSUE THREAD

**Issue by sachin-samel** [almende/vis#1301]
Hi,

I am using hierarchical network layout in my application.

I want to add Expand Collapse functionality, where clicking on the nodes will dynamically pull the data from server and will generate its child nodes.

How can I achieve this functionality? Any pointers would be helpful.

Regards

**Comment by AlexDM0** [comment]
Hi,

Look into the dataset, it is our way to handle dynamic data. There are examples available on our website.

Regards

**Comment by sachin-samel** [comment]
Thanks.
