### ISSUE TITLE
Crownstone Kickstarter promo on vis.js

### ISSUE THREAD

**Issue by AlexDM0** [almende/vis#1302]
Hi everyone,

There's a big promotion going on for our colleagues at DoBots. For more information I've made a blog post to explain why we're doing this.

http://visjs.org/blog.html#CrownstoneKickstarter

Join the party at:
https://www.kickstarter.com/projects/dobots/crownstone

And leave a comment at this issue if you back, share or have suggestions for improvements for this project!

Regards,

Alex

**Comment by vijaiaeroastro** [comment]
why was it cancelled ?

**Comment by AlexDM0** [comment]
Hi,

We were aiming at both the US and EU market. While the EU market penetration was quite successful, we failed to get news coverage in the US. Because of this the target would not be made and we made the decision to go for a pre-order system. 

More information here: 
https://www.kickstarter.com/projects/dobots/crownstone/posts/1395613

Regards,

Alex
