### ISSUE TITLE
Network View enable Vertical scrollbar

### ISSUE THREAD

**Issue by vramali1** [almende/vis#1303]
Hello Team,

Could you please tell me how can i enable vertical scroll in the network view. I am creating nodes on click of a button. When the graph becomes very big. It is not visible and I have to Zoom out to view the entire graph and do manipulation.

Thanks,
-Vijay

**Comment by josdejong** [comment]
There is no scrollbar. You can just zoom and move the network around with either mouse or touch. 

There are methods like `fit()` to fit all nodes in the viewport. You could also use a method like `focus()` to move to the just created node.

**Comment by AlexDM0** [comment]
You could make the container div larger than the window or make set the canvas width height larger than the container?

**Comment by AlexDM0** [comment]
I just tested setting the option {height:'1000px'} in a container of 400px an setting the css of the container to overflow:auto and this gives you the scrollbar.
