### ISSUE TITLE
Network hierarchical layout edge issue

### ISSUE THREAD

**Issue by abhishekjangid** [almende/vis#1304]
Hi,

I am using network graph with hierarchical representation.

I want to display multiple edges between nodes.

Somehow, it is not displaying it.

Does anyone knows how to display multiple edges between network hierarchical graph?

Thanks

**Comment by AlexDM0** [comment]
Hi,

At the moment the only way to do this is with the diagonal cross edge type
and make sure the to and from are like a -> b and b -> a. Apart from this,
the edges will overlap I'm afraid. There is no way to dynamically solve
multiple edges between nodes in the hierarchical view.

Regards
