### ISSUE TITLE
Edit edge: TypeError: this.selectedControlNode is undefined

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#1306]
Hi @ dev team,

Spotted a bug:

1. Go to http://visjs.org/examples/network/other/manipulation.html
2. Select an edge and click "edit edge"
3. Left click on a node (any node), hold the mouse button down and move the mouse (=drag).
4. release the button (=drop)

You will see: 

`TypeError: this.selectedControlNode is undefined (vis.js (line 40713))`.

Thanks
-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

isn't this #1300?

Regards

**Comment by felixhayashi** [comment]
Hi Alex

> isn't this #1300?

Yes it is! Before posting this, I searched for the error message in the issue list but #1300 doesn't include it in the description so it didn't come up. Anyway, sorry for the dublication. I'll close it.

--Felix

**Comment by AlexDM0** [comment]
Hi Felix,

This is fixed on develop.

Cheers

**Comment by felixhayashi** [comment]
Much thanks!
