### ISSUE TITLE
how to add css animation in network node 

### ISSUE THREAD

**Issue by kevindu1993** [almende/vis#1309]
I want to make the node has the animation style, so I add svg in node just like the example in HTMLInNodes.html

<svg xmlns="http://www.w3.org/2000/svg">
    <foreignObject x="0" y="0" width="150px" height="150px">
    <div xmlns="http://www.w3.org/1999/xhtml" style="width:80px;height:80px;border-radius:40px;background:blue;animation:warn 2.5s ease-out;animation-iteration-count:infinite;">
    </div>
    </foreignObject>
</svg>

however, the node does not run as I want, so how to solve this problem?
thanks

**Comment by AlexDM0** [comment]
Hi,

Since the network is drawn on a canvas, SVG's are drawn as images and these images are static. There is no clock for the animation.

Sorry to tell you that this is simple not possible with our network.

Regards
