### ISSUE TITLE
Node hiding does not work after drawing a network the first time.

### ISSUE THREAD

**Issue by ttomasini** [almende/vis#1312]
Updating a network node in a dataset with

```javascript
nodesDataset.update({id: 100, hidden: true});
```

does not hide the node in the network canvas.

Which information do you need to have a look at the bug?

> Version: 4.8.2

**Comment by AlexDM0** [comment]
Hi,

If I go to 
http://visjs.org/examples/network/basicUsage.html

and type this in the console:
nodes.update({id:1, hidden:true})

it does seem to work. In order to look at the bug it would be best if you make a jsBin to show your code that is showing the bug.

Regards

**Comment by dragonzone** [comment]
Maybe similar issue that I generated: http://jsfiddle.net/5ccvw1w2/

**Comment by AlexDM0** [comment]
Thats.... odd.. I'll make sure thats fixed for the next release..

**Comment by dragonzone** [comment]
Sorry to intro. so many bugs. :D Our dev env. is down lately (others are trying to fix), so have nothing to do but check out ur stuff :D

**Comment by AlexDM0** [comment]
no thats fine, bugs should be fixed and there's no way for me to check every possible case..

**Comment by AlexDM0** [comment]
seems fixed :) must have missed closing the issue
