### ISSUE TITLE
Map background overlay

### ISSUE THREAD

**Issue by dr-dimitru** [almende/vis#1313]
Hi all,

Any idea how to overlay the background with google maps for example, as it coordinates should be synchronised with visjs coordinates?

**Comment by AlexDM0** [comment]
Hi,

Which module are you referring to?

Regards

**Comment by dr-dimitru** [comment]
In my case is Network.
As vis has it's own coordinates system I believe there is should be a way to synchronise them both.

Currently I'm doing simple example of air routes, so it will be awesome to combine them with map visualisation.

**Comment by AlexDM0** [comment]
I'm not sure why though. The network has it's own coordinates yes, and you change them by zooming and dragging. Syncing these between the google maps and the network would be a mess.

I'm not sure what the network would bring on top of google maps... you're not using the layouting, physics or interaction so you'd only be using the drawing capabilities? I'd imagine you'd be much better off using the google maps API.

Why do you think a network view should work with a geographical map?

Regards

**Comment by dr-dimitru** [comment]
Yes, actually for long time I use only drawing capabilities of vis library - nodes and edges. In real live on every user's monitor we need to show Network in same way, so we store coordinates of each node, and, yes, all physics and animations is turned off. So it will be awesome to have ability to put something under those nodes, it might be not the google maps, but at least static world map (image or SVG for example).

**Comment by AlexDM0** [comment]
You can, just css the div below the container div.

**Comment by dr-dimitru** [comment]
But how attach it to vis coordinates, so it will be zooming and moving within nodes?

**Comment by AlexDM0** [comment]
Use the events and try to sync them as much as you can. There's the dragging and zoom events and methods to get the scale and position.

**Comment by dr-dimitru** [comment]
Okay, got it.
Any plans for build-in support of this kind backgrounds?

**Comment by AlexDM0** [comment]
Hi,

No.

Regards,

Alex

**Comment by dr-dimitru** [comment]
Solved, but not in the way I've expected.
Thank you @AlexDM0 .

**Comment by sawajid** [comment]
@dr-dimitru Hi, I'm also trying to use google maps as background to the network. Could you describe the solution you found for this ?

**Comment by dr-dimitru** [comment]
Hi @sawajid ,
Unfortunately solution was found only for synchronisation nodes coords via DB.
How to use interactive background is still a mystery for me.

Here's [example app](http://neo4j-graph.meteor.com) all code is open source, so you can find something useful for yourself. As you can see in this example app (if you open it in two browser windows side by side) all actions is synchronised.

**Comment by farshadahmadi** [comment]
Hi @dr-dimitru ,
I want to do the same thing you did already. Unfortunately your example application is not working. Could you do me a favor and link me to a workinh one?

**Comment by dr-dimitru** [comment]
@farshadahmadi 
Here you go:
 - http://neo4j-graph.herokuapp.com
 - https://github.com/VeliovGroup/ostrio-neo4jdriver
 - Demo Sources: https://github.com/VeliovGroup/ostrio-neo4jdriver/tree/master/demo
