### ISSUE TITLE
[Feature Request]: Can Image nodes have borders?

### ISSUE THREAD

**Issue by dragonzone** [almende/vis#1314]
Are there any configuration options where once a user select node(s) and/or edge(s) to allow them to change let the font, color, size of the nodes/edges label and border? Instead of listening to events and changing it that way?

**Comment by AlexDM0** [comment]
Hi,

The manipulation API is made for this, but you'll have to manage the popup manually
http://visjs.org/docs/network/manipulation.html
http://visjs.org/docs/network/#method_enableEditMode
http://visjs.org/examples/network/other/manipulation.html

Regards

**Comment by dragonzone** [comment]
Nm, I answered my own question. Thx.

**Comment by dragonzone** [comment]
Actually, to be more specific was this, you have this example: file:///C:/git/vis/examples/network/nodeStyles/circularImages.html

Where you can change the border and color of the nodes. However, if I change from "circularImage" to "image", those attributes doesn't work anymore. Is there another shape for, let say "rectangleImage" to does the same functionality as the "circularImage", which honor the border, color, etc. of the nodes?

**Comment by AlexDM0** [comment]
Hi,

Images currently cannot have borders. There is no version of them apart from the circular one that has borders at the moment.

Regards

**Comment by dragonzone** [comment]
Are you planning to implement a "rectangularImage", which will be similar to the "circularImage" then, which then will have the ability to have border, etc.?

**Comment by AlexDM0** [comment]
Not at the moment. I'm not sure what the best way would be. RecangularImage seems overkill but I'd rather not have the image type have a border by default. Having time image type forcibly set the border to 0 is also ugly.

the cleanest way would be to have the image type have a border, but then all current usecases would have to set borderWidth to 0 for their images. Maybe a shape property?

We've had this request before, I'll see what we can do.

Regards,

Alex

**Comment by dragonzone** [comment]
The reason behind is, that your example w/ nodes & it's shape, although are good, but they missing some realism. We have to replace them w/ our actual icon/picture to make come alive and more meaningful.

**Comment by dragonzone** [comment]
For instance, in your showcase, you have this example: http://www.beergraph.xyz/. Instead of have just the circle shape for it. Don't you think it'll be much better, that for each of those beer, we have an actual image/icon of those bear, where user can quickly recognize rather than reading the name of it?

**Comment by AlexDM0** [comment]
I'm not sure actually. Drawing performance would suffer (on mobile) and in the graphs you've shown me there is pixelation when you zoom out on the images. I think it could become messy with too many pictures.

Allthough I'm not sure how this supports the case for images with borders? ;)

**Comment by AlexDM0** [comment]
Anyway, I've added it just now. It will be in the 4.9.0 release.

Regards

**Comment by dragonzone** [comment]
Exactly what I was looking for, I love this new feature, thx!

**Comment by dragonzone** [comment]
BTW, you should update your network example to reflect this, I'm sure others will want to utilize it.

**Comment by dragonzone** [comment]
With this new option, is there a way to, by default set useBorderWithImage = false for all nodes, but when user select the nodes, then only those selected nodes have border?

**Comment by dragonzone** [comment]
Never mind, I answered my own question. All I need to do is set border: 'transparent'. Working now.

**Comment by AlexDM0** [comment]
You can also just update your dataset ;)
