### ISSUE TITLE
Network: Cannot uncluster nodes when removing a node that has an edge to that cluster

### ISSUE THREAD

**Issue by dragonzone** [almende/vis#1315]
Here is the example: http://jsfiddle.net/oj61w366/

**Comment by AlexDM0** [comment]
Hi,

This is all part of the same shortcoming. It is not possible to use dynamic data around clusters. Once this is addressed, all of these issues will be resolved.

Thanks for reporting.

Regards

**Comment by Tooa** [comment]
"inc" for this feature :+1:

**Comment by wimrijnders** [comment]
FYI I fixed this. However, it's part of a much larger code addition which completely handles the clustering updating due to changing data. It's going to take a while to even it out.
