### ISSUE TITLE
Is there a good way to limit zoom levels?

### ISSUE THREAD

**Issue by denchen** [almende/vis#1317]
Is there a good way to limit zoom levels to, say for example, min = 0.4 and max = 1.0? My use case is that for the data I'm displaying, there's absolutely no need to zoom in beyond 1.0x, as you're seeing only at most 1-2 nodes onscreen. And as for zooming out, again, there's no use zooming further out than the default zoom level that's set during initial render which shows everything.

I know I can capture the new zoom level via:
`network.on('zoom', function (params) {
  console.log('zoom level: ' + zoom.scale);
});`

Can I use that information and do something like, `if (zoom.scale > 1.0)` then don't actually zoom in (like an `event.preventDefault()`), or perhaps manually override scale to whatever value I want?

Right now I have an imperfect workaround where I manually set the scale if it crosses a threshold:

    // Initialize network here...
    network.on('zoom', function (params) {
      if (params.scale > 1.0) {
        network.body.view.scale = 1.0;
      }
    });

The above works, thought the view still scrolls when it hits the limit, so I'm wondering if there's a better solution?

**Comment by AlexDM0** [comment]
There

**Comment by AlexDM0** [comment]
Hi,

At the moment there is not. I'm not sure there will be though. In my experience it's easier for the user if they have full control. If they zoom out too far they'll go back. They want to see the data after all. 

Regards
