### ISSUE TITLE
Browser Compatibility for Network

### ISSUE THREAD

**Issue by devgitk** [almende/vis#1318]
Hi ,

I am using the latest version of Vis; I seem to be having a problem with the browsers!
I am loading data of the network (Nodes and Edges) from JSON, I am able to see the network in Firefox (v 39); but unable to see the same in the latest version of IE (v 11) and Chrome. Nothing gets displayed!
Any clue why?

Thanks

**Comment by josdejong** [comment]
Do the examples of the website of vis.js work fine in your browsers? Or is it just your application giving issues in these browsers? If so, can you post a jsbin demonstrating the issue?

http://visjs.org/network_examples.html

**Comment by devgitk** [comment]
Hi @josdejong 

The example "importingFromGephi" from the http://visjs.org/network_examples.html seems to work! but when I run the example from the explorer, the graph doesn't load. 

Parsing my JSON using the below code : 
//declaring container and options
var json = $.getJSON("jsonFile.json")
        .done(function(data){
            var g = {
                nodes: data.nodes,
                edges: data.edges
            };
var	network = new vis.Network(container, data, options);

and JSON (jsonFile.json) looks like :
{
    "nodes": [
        {
            "id": "1",
            "label": "Node1",
            "shape": "image",
            "image": "img1.jpg",
            "title": "Node1",
            "attr1": "abc",
            "attr2": "def",
            "attr3": "ghi",
            "x": "5",
            "y": "10",
            "level": "0"
        },
        {
            "id": "2",
            "label": "Node2",
            "shape": "image",
            "image": "img2.jpg",
            "title": "Node2",
            "attr1": "abc",
            "attr2": "def",
            "attr3": "ghi",
            "x": "10",
            "y": "10",
            "level": "0"
        }
    ],
    "edges": [
        {
            "id": "Edge1",
            "from": "1",
            "to": "2",
            "label": "",
            "length": "10",
            "dashes": "true"
        }
    ]
}

Thanks !

**Comment by AlexDM0** [comment]
Hi,

Some examples require the website to be served, not just opened. 

If it is run locally without a localhost, xmlhttprequests cannot be done. 

That is the case here. 

Regards

**Comment by devgitk** [comment]
@AlexDM0  : Yeah, I understand that; But what about in this case? any clue? all the other components are loading apart from the vis canvas!

Regards

**Comment by AlexDM0** [comment]
Hi,

I'm not sure you do. Locally opened HTML files cannot use AJAX which is used in the getJSON method. The vis canvas is loading fine but it's crashing at the getting data phase. 

This has nothing to do with browsers, this is just not possible. To solve this, you either have to run a local web server or change the way you get data. Take a look at the worldcup performance example for another way. 

Regards
