### ISSUE TITLE
not setting `theta` parameter in barnesHut seems to set it to 0 while the default is 0.5

### ISSUE THREAD

**Issue by hengchu** [almende/vis#1323]
As described in the title. I also noticed that having `theta` at 0 has a significant performance hit on a graph with hundreds of nodes. It seems that I should not be setting `theta` myself, but if I don't set it, `theta` doesn't have the correct value. Is this a bug?

Thank you!

**Comment by AlexDM0** [comment]
Hi,

You should indeed not be setting theta yourself. What makes you think that theta does not have the correct value if you don't touch it?

Regards

**Comment by hengchu** [comment]
I modified at vis.js source code a little bit (in the physics engine `setOptions` and `init` functions), and `console.log` options out when I don't set any physics options and also `console.log` options out when I set exactly the default parameters as on the documentation page. The only difference is the `theta` parameter, and having `theta` increases the performance significantly

**Comment by hengchu** [comment]
I'm using version 4.8.2

**Comment by AlexDM0** [comment]
Hi,

If you're modifying your code then I can not help you. I tested with the current version, the theta is just working at value 0.5 by default and it's not meant for public usage.

Regards

**Comment by hengchu** [comment]
Hi,

I modified the code only for the purpose of investigating this. The only modification was a few `console.log` statements.

Do you mind trying to set a few `barnesHut` attributes and see if `theta` is working as intended?

Thank you!

**Comment by AlexDM0** [comment]
Hi,

I set a few and yes, it's working.

Regards
