### ISSUE TITLE
Label scaling example is not working

### ISSUE THREAD

**Issue by lalquier** [almende/vis#1324]
I am trying to understand how to scale the label size of nodes along with the node size.

This example should be doing just that according to the list of examples:

http://visjs.org/examples/network/data/scalingNodesEdgesLabels.html

The thumbnail on the example page shows node labels scaled according to the node size but the example itself doesn't scale anything.

Is this feature currently broken? or is something missing in the sample code?

**Comment by AlexDM0** [comment]
Hi,

I'll look into this, thanks for the heads up!

Cheers

**Comment by jtebert** [comment]
I also can't get nodes labels to scale with the value using shapes with the label inside (i.e. box)

**Comment by AlexDM0** [comment]
Hi,

I've pushed a fix for this to develop. It will be released soonish.

Regards,

Alex
