### ISSUE TITLE
Point item icons are not vertically aligned with label

### ISSUE THREAD

**Issue by teddylindsey** [almende/vis#1326]
When events are displayed as "type: point", the vis-dot icon is displayed vertically offset above the label by 4.5px. It appears that the element's style is set to "top:-4px" when it should be set to "top:8.5px". When the event is selected, the style top attribute is set correctly and the icon is aligned correctly.

This problem can be seen on the example site at http://visjs.org/examples/timeline/items/pointItems.html

**Comment by josdejong** [comment]
Thanks for reporting this bug, we will fix it

**Comment by josdejong** [comment]
This is fixed now on the `develop` branch.

**Comment by teddylindsey** [comment]
Thanks, Jos!
