### ISSUE TITLE
Remove padding

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [almende/vis#1329]
![align top](https://cloud.githubusercontent.com/assets/12840136/10154983/16a2911e-6645-11e5-9e54-443fed51270f.png)
Hi, how can I make the nodes start on the top of the canvas?

**Comment by AlexDM0** [comment]
Hi,

The fit method centres the nodes.  To manually control the camera you can use the moveTo method. There are numerous issues on that with more explaination and solutions.

Regards
