### ISSUE TITLE
no property 'locked' in method 'network.focus(String nodeId, [Object options])'

### ISSUE THREAD

**Issue by mael-morel** [almende/vis#1330]
Hello,

In the network api, I'm focusing on a specific node and it's working fine. But then after other interaction actions, the focus is still on the node. So I added the 'options' arguments with property 'locked: false' but it doesn't change anything:

    network.focus(nodeId, {locked: false, scale: 0.5});

I looked in vis.js in the moveTo() function but I can't find any 'locked' property. Is it missing?

**Comment by AlexDM0** [comment]
Hi,

Locked implies that if the node is moving, the camera moves with it. If the user manually moves something, the lock is broken. I'm not sure what you mean by focus is still on the node. Can you make a jsbin to show this?

Moveto does not have a locked option. Locked is also false by default so it would not be different.

Regards,

Alex

**Comment by HassanHashemi** [comment]
it seems to be a bug, when { animation: true } the locked : false is not working.
