### ISSUE TITLE
Positions of root nodes too close

### ISSUE THREAD

**Issue by MarcoG3** [almende/vis#1331]
Consider I have two or more root nodes, when I create a tree of the first root node it becomes complex with multiple nodes. Then I add a new root node (no parent node and no edges), it gets positioned by visjs in the middle of the previous tree. I want those to be separated, how should I do that?

**Comment by stanleyxu2005** [comment]
In the options, you can set the minimal spacing of two nodes. Just check the docs.

**Comment by MarcoG3** [comment]
I don't need to set minimal spacing between generic nodes, just between root nodes.

**Comment by AlexDM0** [comment]
Can you make a jsbin showing the problem?

**Comment by MarcoG3** [comment]
Sure! https://i.imgur.com/28IZ4h6.png

Look, I have two different social medias and I would like to "separate", graphically, the two. Notice that Google+ logo is just in wrong position. I would like to move it to the right, so it won't overlap with Facebook tree even if it has a lot of nodes. Is that possible with visjs? Thank you.

**Comment by AlexDM0** [comment]
Hi, I would suggest you position the first root at 0,0 and fix it there. Then build the tree, the get the size and determine the best place for the second root. Position it on say 800,0 and fix it there. 

That should solve it. 

Regards

**Comment by MarcoG3** [comment]
I've thought that aswell. It might work fine but what if first root nodes overlap with second root nodes? If I have a very complex facebook tree it will surely "break" it. Any advice?
Thanks!

**Comment by AlexDM0** [comment]
If the trees become big enough, they will naturally repel each other. You could use the render events to check on each redraw how far away the other group is and position accordingly?

**Comment by MarcoG3** [comment]
That is right. Thank you for your time, have a great day!
