### ISSUE TITLE
Request to provide keypress events

### ISSUE THREAD

**Issue by stanleyxu2005** [almende/vis#1332]
I'd like to delete selected node/edge by pressing DEL. I do not found a way to hook keypress event. Is there anyway to handle keystrokes?

**Comment by dragonzone** [comment]
I have this feature in our app. To do this, you can try this:

```
	$(document).keyup(function(e){
	    if (e.keyCode == 46) { // delete button pressed
	    	removeSelectedNodes();
	    }
	}) 
```

**Comment by AlexDM0** [comment]
You can also try keycharm. It's the same thing we use in vis.

**Comment by AlexDM0** [comment]
It's exposed actually (secretly ;))

vis.keycharm

**Comment by felixhayashi** [comment]
What @dragonzone referred to but using @AlexDM0's keycharm:

```javascript
  var keys = vis.keycharm({
    container: /** dom node **/,
    preventDefault: true
  });

  keys.bind("delete", function(event) {
    var selection = this.network.getSelection();
    /** remove action **/
  }.bind(this));
```

**Comment by stanleyxu2005** [comment]
Prima! Problem solve.
