### ISSUE TITLE
Request to have a method to remove orphan edges

### ISSUE THREAD

**Issue by stanleyxu2005** [almende/vis#1333]
I have created couple of nodes and edges. Later I remove a node X. All its related edges will be hide, but they are still in `network.data.edges`. I'd like to have a simple way to remove such orphan edges (instead of programatically check the validity)

**Comment by dragonzone** [comment]
Yes, I have the same issue also. As a workaround, before I remove the selected node(s), I have to loop through all the edges "to" and "from" and remove them first. It's a bit of a hassle.

This feature will be very useful in cases where the app tries to save the network and later tries to reload it. If you delete the nodes and leave the orphan edges, the network will not redraw correctly b/c of the missing node(s).

**Comment by AlexDM0** [comment]
Hi,

@Dragonzone, I think the bug causing the network to not draw correctly when there are edges without nodes has been solved?

I do not think there will be a method for this. The validity of your data is fully up to you. 

Regards

**Comment by felixhayashi** [comment]
> I remove a node X. All its related edges will be hide, but they are still in network.data.edges. I'd like to have a simple way to remove such orphan edges (instead of programatically check the validity)

If you are talking about modifications via the manipulation interface, then the easiest way is to create a handler for deletion events (http://visjs.org/docs/network/manipulation.html) and when a node is removed you check with getConnectedEdges (http://visjs.org/docs/network/#methods) which edges to remove. This way your data stays consistent.

-Felix

**Comment by stanleyxu2005** [comment]
@felixhayashi The manipulate interface is more powerful. Thanks for the tip. @AlexDM0 Is there a way to customize the interface? I want to use my own dialog to create/edit node/edge.

**Comment by AlexDM0** [comment]
Hi,

Yes. The buttons are CSS styled and the API is open if you want to make your own physical buttons. It's all in the docs. 

Regards

**Comment by stanleyxu2005** [comment]
No, not the buttons. When I click add node button, it will show a dialog. I want to replace it with my own dialog.

**Comment by AlexDM0** [comment]
Hence the second part of my answer.

**Comment by stanleyxu2005** [comment]
@AlexDM0 You are right. Thanks for the reply. I will do really cool stuff with this feature.
