### ISSUE TITLE
Within a single timeline, is it possible to introduce a divider between groups?

### ISSUE THREAD

**Issue by mg1075** [almende/vis#1334]
Are there any viable options - css, fake data, other? - for introducing what might be called a "divider" between groups within a single timeline?

Perhaps the mock-up below helps illustrate what I am hoping can be accomplished. 

![image](https://cloud.githubusercontent.com/assets/2031435/10184895/cb11ed1c-6707-11e5-886d-b005e6f9022e.png)

**Comment by josdejong** [comment]
You can create two timelines on top of each other, and keep their viewport the same by listening for the `rangechange` event of one and applying the new viewport to the other, and vice versa.

**Comment by brichbe** [comment]
@mg1075 one way would be creating another group that's basically void of any content or standard items.

See simple example here:  http://jsbin.com/walaketavo/edit?html,output

This example is based off the Vis Groups Ordering example (to ensure the order of groups is maintained, thus you control where this spacer group is located relative to the others).  Here you can see I simply created a 4th group to act as a spacer:  it's content is `'<br>'`, it's ordering value ensures it is placed between group "First" and group "Second", and no standard items are added to it so the spacer group appears empty.

To make the spacer appear as a solid bar all the way across, I added to the spacer group a single background item with no content, but with a background color that matches the spacer group's background color.

Obviously this is just a simple example and from here you could further customize the size/style/etc.

**Comment by mg1075** [comment]
@brichbe - Thanks, that looks really promising!
