### ISSUE TITLE
vis dot

### ISSUE THREAD

**Issue by seminice** [almende/vis#1336]
Can I add a vis-dot that is exclusive to the vis box to the vis-range and other timeline types?

**Comment by josdejong** [comment]
I'm not sure what you mean, can you elaborate?

**Comment by seminice** [comment]
I was trying to add vis-dot which is that line that connects the box events (which has no end property) to the timeline.
The room of freedom and configuration in your work is amazing really, it gave more room for creativity in aesthetics and design so thank you so much for that.
What Im trying to accomplish are basically to things
1. Customize the delete button , if I can do that or if I cant (no straight way to do it) how can I override the Item.prototype._repaintDeleteButton or any other prototype in vis.
2. Im using the timeline differently actually , Im building a (flash like) web application for scalable vectors and (in future three.js) so you get an idea of what im trying to do , the only problem with vis js is the time and date limitation, I want to basically have a specific number for the time line which translates to a number not a date range.. I hope the idea is clear.. thank you again your work is appreciated really!

**Comment by josdejong** [comment]
Thanks :)

1. well, by overriding the `Item.prototype._repaintDeleteButton` method... Did you try it? I don't know what you have in mind and if you really need to add different objects to the DOM, if not, it may be enough to adjust the CSS.
2. the horizontal axis indeed only support time, not regular numbers. You could see if you could hack into the Timeline and replace the horizontal time axis with an axis showing just numbers, but that will be quite some work I think.

**Comment by upq** [comment]
@josdejong any suggestions for using the timeline with numbers or at least something close? I'm actually  using the timeline for a similar purpose.
Thanks.

**Comment by josdejong** [comment]
You can zoom in to millisecond scale. That looks like numbers.

**Comment by yotamberk** [comment]
@seminice Can we close this issue?
