### ISSUE TITLE
Short timeline items are unclickable

### ISSUE THREAD

**Issue by ramdyne** [almende/vis#1338]
When creating a timeline item with both start and end datetimes the same value, the item will show in the timeline, but it is impossible to zoom in enough to read the description.

I don't know what is best, change my generating code to detect this situation and make the end datetime larger than the start datetime value. Or having a UI timeline item with a minimal width so it is always possible to  zoom far enough in to show the content of the item.

**Comment by josdejong** [comment]
If the time range has a duration of 0 seconds, it will always have a width of 0. You could maybe display it as a point item instead of a range item, or let the text of the range item overflow like in this example: http://visjs.org/examples/timeline/items/rangeOverflowItem.html
