### ISSUE TITLE
Feature request: Timeline relative height

### ISSUE THREAD

**Issue by cybear** [almende/vis#1339]
For a product I'm building I'd like to be able to create a timeline that can support relative height. 

I would create a new timeline with the `height` option set to `100%`. That would then create a timeline that would fit whatever container it would be placed into. On resize it would ideally still fit without having to run any JS.

Would this be a useful feature? Would anyone be interested in building it?

**Comment by josdejong** [comment]
Actually it works like that, you can apply options `{height: '100%'}` to the Timeline.

**Comment by cybear** [comment]
That's true, however when I do that it gets a height of 0.

Try for instance visiting http://visjs.org/examples/timeline/basicUsage.html and typing `timeline.setOptions({height:"100%"});`.

**Comment by josdejong** [comment]
You will have to give all parent divs a height too, be it 100% or a height in pixels. This is not related to the Timeline but just how HTML works.
