### ISSUE TITLE
Timeline.getVisibleItems() returns wrong count of items

### ISSUE THREAD

**Issue by mast0r** [almende/vis#1340]
The method "getVisibleItems()" returns a count of "visible" items for the current time window. But if you have some groups with items that are currently NOT visible because of the fixed timeline height - that items are counts to the visible array.

Example: http://jsfiddle.net/adtz8og8/6/

**Comment by josdejong** [comment]
Thanks, we could extend the method `getVisibleItems()`, it currently only takes the horizontal position into account, not the vertical position.

**Comment by yotamberk** [comment]
Fixed in v4.17.0
