### ISSUE TITLE
Context menu to show above the Node always in the same position in Networks!

### ISSUE THREAD

**Issue by EugenyPavlenko** [almende/vis#1341]
Hello!

I need to show my own specific div-menu above the node, when clicked.

The problem is, that I want to show it always in the same position (no matter on what part of the node the user clicked).

Because, the div menu is a part of HTML I want somehow to get the coordinates of the node which I can apply to my DOM menu, so, in fact I want to get coordinates of node in DOM system...

Is there any way to do that?

In the images below the menu is shown incorrect, because click event coordinates are used, therefore menu is always in different position.

![img1](https://cloud.githubusercontent.com/assets/1785921/10249944/c79886a2-6930-11e5-9daa-826021d5a2d2.png)
![img2](https://cloud.githubusercontent.com/assets/1785921/10249945/c7991720-6930-11e5-86be-78374618426a.png)

**Comment by EugenyPavlenko** [comment]
If it matter, the code to show menu in the example above:
**onSelectNode**
```javascript
$(menuSel).css('left', params.pointer.DOM.x).css('top', params.pointer.DOM.y);
$(menuSel).removeClass('displayNone');
$(menuSel).WCircleMenu('open');
```

**Comment by felixhayashi** [comment]
> Because, the div menu is a part of HTML I want somehow to get the coordinates of the node which I can apply to my DOM menu, so, in fact I want to get coordinates of node in DOM system...

See the docs: "canvasToDOM" and "DOMtoCanvas" (http://visjs.org/docs/network/index.html)

**Comment by EugenyPavlenko** [comment]
seems to be what I need! thank you!

**Comment by felixhayashi** [comment]
> seems to be what I need! thank you!

Nice :) No problem
