### ISSUE TITLE
Network: Edges not self-adjusting after clustering and changing to heirarchical layout

### ISSUE THREAD

**Issue by dragonzone** [almende/vis#1342]
See example: http://jsfiddle.net/6vo1v7h7/

**Comment by josdejong** [comment]
Looks like the support nodes (hidden nodes located halfway the edges) are positioned in the hierarchy too. Thanks for reporting this.

**Comment by AlexDM0** [comment]
Hi,

Clustering and hierarchical layout are not supported at the moment. 

We'll have to create a proper fix for this and add a warning somewhere in the meantime. Thanks for the heads up.

Cheers

**Comment by dragonzone** [comment]
Welcome back! Hope you've enjoyed your vacation.

**Comment by AlexDM0** [comment]
Thanks :) I can recommend Indonesia to everyone!

**Comment by mojoaxel** [comment]
@dragonzone Is this still an issue?

**Comment by dragonzone** [comment]
I haven't updates our vis.js version lately, so I don't know. But go ahead & close it. If I have issues in future, I'll reopen it.
