### ISSUE TITLE
Deselecting during multiselect doesn't reduce the properties edges-array passed to the handler

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#1343]
Hi Alex,

I discovered a tiny bug :)

When adding handlers to the `deselectNode` or the `selectNode` events, the passed `properties` object shows added or removed nodes correctly with the `properties.nodes` array but the `properties.edges` array is never reduced when multiselected multiple nodes (which also selects the edges) before and then deselecting one or more nodes, even if the edges are not in a selection-state anymore. It always contains the edges that where at one point selected… This only happens in multiselect.

To reproduce, select multiple nodes and deselect one node and observe that the edges array isn't reduced.

-Felix

**Comment by felixhayashi** [comment]
Notice that the edges array length never decreases (only at the beginning where I selected a single node and deselected a single node).

![2015-10-03 13 08 25](https://cloud.githubusercontent.com/assets/4307137/10262615/fabbbf78-69cf-11e5-9c88-019834f608be.png)

**Comment by josdejong** [comment]
Thanks. The connected edges where just not deselected when a node was deselected. The edges remained selected, hence the array with selected edges remained filled.

I think it makes sense to change the behavior: deselect the connected edges when a node is deselected, symmetric with connected edges being selected when you select a node. I've changed this in the `develop` branch.

**Comment by felixhayashi** [comment]
Hi @josdejong 

sorry, didn't mean to exclude you in the salutation of this issue!

> I think it makes sense to change the behavior: deselect the connected edges when a node is deselected, symmetric with connected edges being selected when you select a node. I've changed this in the develop branch.

Yes, makes sense. Thank you very much :)

-Felix

**Comment by josdejong** [comment]
> sorry, didn't mean to exclude you in the salutation of this issue!

I know :)
