### ISSUE TITLE
Prevent nodes leaving boundaries and disabling zoom? (network)

### ISSUE THREAD

**Issue by jtebert** [almende/vis#1344]
Is there a way to prevent the network from being dragged out of the bounds of the container? Is there a way to disable zooming on a network?

I couldn't find either of these things in the documentation, but it seems like the type of thing that might/should exist somewhere.

**Comment by Tooa** [comment]
Here [1] is explained how to disable the zoom.

[1] http://visjs.org/docs/network/interaction.html

**Comment by jtebert** [comment]
I somehow missed that bit of the documentation. One problem, though: when zoom is disabled, if the pointer is over the network div, the page doesn't scroll. It makes sense that with zoom disabled, the mouse wheel should revert to normal scrolling.

**Comment by josdejong** [comment]
For that, you can set the option `clickToUse` to `false`.

**Comment by felixhayashi** [comment]
Hi,

One problem, though: when zoom is disabled, if the pointer is over the network div, the page doesn't scroll.

I have the same issue as @jtebert. I disabled `clickToUse` and disabled the zoom in the interaction setttings but now vis just swallows my page scrolls and does nothing. So when scrolling over a network, I suddenly am stuck. It would be nice if vis would not prevent the default and just allow the event to propagate in this case.

-Felix

**Comment by felixhayashi** [comment]
Not sure why the guys at https://github.com/almende/vis/issues/693 report that this worked for them? Maybe it did in the past?

**Comment by AlexDM0** [comment]
Hi Felix,

This should not happen. I'll look into it. 

Regards

**Comment by AlexDM0** [comment]
I've fixed this at develop

**Comment by felixhayashi** [comment]
Thanks for the quick fix, Alex. Highly appreciated.

Don't want to spam the repo with compliments but you and @josdejong do an outstanding issue management job.

**Comment by felixhayashi** [comment]
Hi @AlexDM0 

seems like the zoom buttons do not work properly anymore after this fix…

**Comment by felixhayashi** [comment]
they just zoom out infinitly

**Comment by felixhayashi** [comment]
But #1344 is fixed :)

Here is a jsbin for the current problem

http://jsbin.com/niwiri/edit?html,output
