### ISSUE TITLE
Legend icon disappears

### ISSUE THREAD

**Issue by foxlis** [almende/vis#1345]
Hi,
I've Graph2d with groups. I dynamically display data by marking checkboxes.
When I enable barChart data, legend icon disappears. Look at attachment - interfaces read/write.
When I set char type to default legend looks good.
![screenshot](https://cloud.githubusercontent.com/assets/3691760/10282355/a585efc2-6b7a-11e5-9fd5-67efa496d050.PNG)

**Comment by foxlis** [comment]
I think that generated order of SVG legend elements is wrong.
wrong
![wronglegend](https://cloud.githubusercontent.com/assets/3691760/10283762/67fe751e-6b81-11e5-8618-ac5d812cd9d3.PNG)
good
![goodlegend](https://cloud.githubusercontent.com/assets/3691760/10283779/7609f110-6b81-11e5-9432-72d966d3ceda.PNG)

**Comment by josdejong** [comment]
Thanks, the issues isn't yet 100% clear to me, can you maybe create a jsbin demonstrating the issue?

**Comment by foxlis** [comment]
Jos thanks for replay, I'm unable to create a jsbin now unfortunately that reproduce this scenario.
It is to time consuming to move code to jsbin.
But definitely order of SVG <path> tag is wrong in scenario that I describe.

**Comment by josdejong** [comment]
Ok then thanks anyway, we will see if we can reproduce it.

**Comment by AlexDM0** [comment]
Hi,

I think this issue will be fixed by the fix in #1461.

It will be released Friday (tomorrow).

Cheers

**Comment by AlexDM0** [comment]
This has been fixed in 4.10
