### ISSUE TITLE
visjs does not work with require.js and play framework

### ISSUE THREAD

**Issue by Tooa** [almende/vis#1346]
Hi,
here [1] is a simple play framework application using require.js and visjs. To deploy such an application one needs to create a binary using the `dist` task [2] e.g `sbt dist`. This task also runs a requirejs optimizer.  

When starting this packaged application the following error occurs in the javascript console: 

`Uncaught Error: Mismatched anonymous define() module: function (){return function(t){function e(n){if(i[n])return i[n].exports;var o=i[n]={exports:{},id:n,loaded:!1};return t[n].call(o.exports,o,o.exports,e),o.loaded=!0,o.exports}var i={};return e.m=t,e.c=i,e.p="",e(0)}([function(t,e,i){e.util=i(1),e.DOMutil=i(7),e.DataSet=i(8),e.DataView=i(10),e.Queue=i(9),e.Graph3d=i(11),e. [...]`

Without the visjs dependency [3] the application runs fine.  Any thoughts? Looks like the require.js configuration of vis.js behaves wrong. 

Edit:

I stumbled over this https://github.com/almende/vis/issues/883. It seems nothing has changed with r.js since then. I will try to replace the pipeline with Webpack like suggested and let you know. Think this is also interesting for others. 

Best Uli

[1] https://github.com/Tooa/visjsproblem
[2] https://www.playframework.com/documentation/2.4.x/Production
[3] https://github.com/Tooa/visjsproblem/blob/master/app/assets/javascripts/main.js

**Comment by josdejong** [comment]
Thanks for the update. Yeah, it's a tricky problem, discussed in detail in #883. Please let us know how it works out.

**Comment by Tooa** [comment]
Hi,
haven't tested the webpack solution, but the other two solutions do work. This seed project [1] explains how to incorporate webpack with play. However, I've hooked the `dist` task to replace `define([], factory);` with `define('vis', factory);` before the package stage starts. Later, I will definitely go with a custom visjs build. You are right, it's quite a tricky problem.  

[1] https://github.com/shouldbee/play-scala.g8
