### ISSUE TITLE
Vis JS Graph plotting of nodes at  exact X and exact Y coordinates instead of relative coordinates

### ISSUE THREAD

**Issue by vramali1** [almende/vis#1347]
Hello Vis Team,

I created a vis js network and plotting the nodes on a world map image and storing the canvas x and canvas y coordinates. I store the x and y coordinates relative to the canvas in Database. I am facing the following issues when the graph is populated with values from DB. When I checked the graph, the  Node is positioned relative to Max(x) and Max(y) coordinates of all the nodes in the graph instead of  positioning the nodes relative to (0,0) coordinates. Could you please tell me how can I avoid this. Because of this the nodes are not plotted in the right location. I tried DomtoCanvas(0,0) but it didn't work and still I am facing the same issue.

Thanks

**Comment by josdejong** [comment]
Not sure, but maybe you asked a similar question on stackoverflow? http://stackoverflow.com/questions/32902720/vis-js-place-node-manually/

I replied there:

> The `x` and `y` position of a node does not mean a position in pixels on the screen, but is a fixed position in the Networks coordinate system. When you move and zoom in the Network, the fixed items will move and zoom too, but they will always keep the same position relative to each other. It's like your home town has a fixed location (long, lat) on earth, but you can still zoom and move your town in Google Maps.

You can fix zooming and moving, and adjust the viewport such that it matches the pixels of the HTML canvas, here is a demo: 

http://jsbin.com/wowuzu/edit?html,output

**Comment by AlexDM0** [comment]
is this still an issue?

**Comment by vramali1** [comment]
No, please close it. Thanks.

On Monday, November 16, 2015, Alex <notifications@github.com> wrote:

> is this still an issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/almende/vis/issues/1347#issuecomment-157085381>.
>


-- 
Thanks,
Vijaykumar
Contact:312-532-4657.

**Comment by ImCharmainejoy** [comment]
Yes . up until now. It's still an issue for me. I still can't position my right and left nodes given the comments above and my prior knowledge to visjs . any help plss.
