### ISSUE TITLE
[FEATURE REQ]: Allow some nodes to be ignored by part of the physics engine (support nodes)

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#1351]
Hi @ devteam,

is there a way to prevent support nodes to react to central gravity? Smooth edges are great because they are sensitive to inter-node repulsion and thus move away from nodes and other support nodes but unlike for *real* nodes it just doesn't make sense to see them getting drawn to the center like in the screenshot below:

![2015-10-07 19 20 19](https://cloud.githubusercontent.com/assets/4307137/10345340/481bd378-6d29-11e5-9778-2fdd5bf00f60.png)

Of course in a static setup, it is possible to prevent this by having (1) a central gravity set at the beginning, (2) wait till visjs fires the stabilize event for the first time and (3) then save positions, (4) set all nodes fixed and (5) set gravity to zero, so support nodes will "jump back". Yet, it looks a bit strange if the edges "jump back" after setting gravity to 0 (it looks like they are "wobbling" for a second when the graph is displayed).

However, when nodes are added to the graph without coordinates (often happens in my case when not the user but the system adds nodes to the graph) the problem is that with central gravity set to 0, the nodes might be positioned pretty far outside when the graph stabilizes. So everytime a node is added without coordinates I would have to repeat steps 1 to 5 (see above) to ensure the node is positioned not too far away the center. If support nodes were not sensitive to central gravity, I could just leave central gravity enabled, instead of switching it on and off when nodes are added.

Hence, my question, whether it is possible to make support nodes insensible to central gravity in the first place. Or does this conflict with existing vis physics mechanisms?

Thanks for an answer :)

-Felix

**Comment by josdejong** [comment]
Thanks, this looks like the same problem as #1342. I'm not sure whether it's the gravity but you may be right. My initial thought was that the support nodes themselves where positioned in a hierarchical layout too.

**Comment by felixhayashi** [comment]
Hi @josdejong 

thanks for responding.

> Thanks, this looks like the same problem as #1342. I'm not sure whether it's the gravity but you may be right.

I would not say that it is a bug in my case, it is just that central gravity affects support nodes. If I turn off central gravity, everything goes back to normal. I was just proposing to make support nodes insensible to central gravity as central gravity doesn't make sense for support nodes imo and has some drawbacks I described above.

> My initial thought was that the support nodes themselves where positioned in a hierarchical layout too.

I think your assumption about #1342 is right. I do not think it is related to gravity. It just looks the same visually :)

**Comment by josdejong** [comment]
>  If I turn off central gravity, everything goes back to normal.

sounds like central gravity is the cause then, thanks for the feedback.

**Comment by AlexDM0** [comment]
Hi Felix,

Your image looks like it is a hierarchical layout. The smooth edges are not supposed to be allowed with hierarchical layout. Once you fix the nodes, do you switch physics models and layouts? 

It looks to me like you have disabled the physics on the edges which also disables the physics on the support nodes. They will be at spawn location resulting in these edges. 

Could you make a jsbin to show what exactly it is you're doing? 

It is not possible for the current physics setup to disable a part of it for a few nodes. I also don't think that should be needed. This issue is caused by a strange combination of settings I think. 

Regards,

Alex

**Comment by felixhayashi** [comment]
Hi Alex,

thanks for responding!

> Your image looks like it is a hierarchical layout. 

No, sorry for choosing this picture, it is forceAtlas2Base but I positioned it manually to look hierarchical.

> Once you fix the nodes, do you switch physics models and layouts? 

I do the following.

1. When a user selects "no floating mode" (i.e. a graph manual positioning / fixed nodes)
1. the network physics solver is always forceAtlas2Base and I set the centralgravity to `0.02`.
1. I load the nodes and edges and call `stabilize()`.
    * New nodes *without a position* will be spawned near the center (due to central gravity)
    * All existing nodes *with a position* will be fixed beforehand by me so they do not move at all
1. Once stabilize fires
    * I fix all nodes
    * and save all positions to my db
    * and set central gravity to 0 so the support nodes are not drawn towards center anymore. This issue asks, whether we could make support nodes insensible to central gravity so it is not needed to call `network.setOptions()` and set central gravity to 0 because this always causes all edges to "wobble" for a 1/2 second as they "jump back".

> It looks to me like you have disabled the physics on the edges which also disables the physics on the support nodes. They will be at spawn location resulting in these edges. 

No, I do not disable physics because I want support nodes to be sensitive to repulsion of other nodes/support nodes, so when I drag a node towards an edge, it tries to move away. Nodes themselves, on the other hand, are fixed by me unless a user drags them.

> Could you make a jsbin to show what exactly it is you're doing?

If the description above is not enough, I will create a bin of course!

> It is not possible for the current physics setup to disable a part of it for a few nodes. I also don't think that should be needed. This issue is caused by a strange combination of settings I think. 

It occurs when nodes are fixed and central gravity has a value greater than zero. Then only support nodes are drawn to the center. 

It is not a bug, so it's fine if you keep it like that. I'll create a bin on sunday so you can still see what I am talking about.

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

I'm on holiday at the moment. I'll be back in November. I can take a look then. 

Regards

**Comment by felixhayashi** [comment]
> I'm on holiday at the moment. I'll be back in November. I can take a look then.

Thanks Alex! Also sorry for forcing your attention towards this central gravity issue while you are on holidays ;)

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

Could you make a jsbin to show this?

Cheers

**Comment by felixhayashi** [comment]
Hi Alex!

Here you go https://jsbin.com/sizayu/edit?html,output

As stated already above, central gravity is needed so nodes spawn near the center when added later to the graph.

**Comment by AlexDM0** [comment]
Hi Felix,

Those nodes SHOULD be affected by central gravity, the issue seems to be that that is the only force they're getting. Normally the springs should keep them in check, which is very weird by itself...

Thanks for the jsBin, I'll see if I can fix this soon.

Cheers

**Comment by AlexDM0** [comment]
I assume you dont normally put the gravity at 30? What's wrong in your jsbin?

**Comment by felixhayashi** [comment]
Hi Alex,

> I assume you dont normally put the gravity at 30?

No, this is an exaggeration for demonstration only.

> what's wrong in your jsbin?

To clarify: Nothing is really "wrong" but the problem is that when using visjs in a static mode (with physics enabled but with fixed nodes). It is unwanted that central gravity affects support nodes because they are drawn to the center which has no benefit and looks weird.

**You may ask:**

* **Why not disabling physics completely?** Because it is nice that support nodes move away from other nodes
* **Why not set central gravity to 0 or close to zero?** If new nodes are added after the graph has been loaded by the system (without having x/y coordinates yet), the need to spawn near the center. With no/small gravity they would quickly move away from the center after the were added to the graph and stabilization would be slow.

Hopefully the issue became clear now.
-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

I see, I thought this was a bug like #1398 but unfortionately we currently do not allow nodes to only get part of the physics. I'm not sure if this will change since we have not built the physics for this.

Sorry to disappoint..

Cheers

**Comment by felixhayashi** [comment]
Hi Alex

> I see, I thought this was a bug like #1398

Sorry for causing confusion.

> I'm not sure if this will change since we have not built the physics for this.

No problem, it's not a big issue, I just thought it is worth asking.
Should I close this issue then?

**Comment by AlexDM0** [comment]
Yes, I don't think we will address this soon as I don't really see how it
would benefit from the added complexity.

Cheers

**Comment by felixhayashi** [comment]
RIP topic :cry:

**Comment by AlexDM0** [comment]
It could be that the bugfix today would stop the wiggle. Try the dev branch ;)
