### ISSUE TITLE
Custom arrowheads

### ISSUE THREAD

**Issue by Izhaki** [almende/vis#1352]
I wonder if vis supports custom arrowhead shapes, like in the following diagram:

![image](https://cloud.githubusercontent.com/assets/880132/10354429/9a2611aa-6d57-11e5-9b7f-203cfcb6fc18.png)

**Comment by josdejong** [comment]
Thanks for your suggestion @Izhaki , this is indeed not supported right now. We'll put it on the wish list.

**Comment by Izhaki** [comment]
Are the correct abstractions in place, or is the current arrowhead iron-clad into the framework design. If the former is the case, I might have a go at this myself.

**Comment by josdejong** [comment]
I think you can quite easily extend the methods which draw the arrows. 

The method which draws one ore multiple arrows on an edge called `drawArrows`, located in Edge.js:
https://github.com/almende/vis/blob/master/lib/network/modules/components/Edge.js#L378-L382

The method for drawing a single arrow somewhere is called `drawArrowHead`, located in EdgeBase.js:
https://github.com/almende/vis/blob/master/lib/network/modules/components/edges/util/EdgeBase.js#L402-L501
