### ISSUE TITLE
[Question Network] Increase minimum node size

### ISSUE THREAD

**Issue by Tooa** [almende/vis#1355]
Hi,
I could need some help with the following problem. Have a look at this network [1].
The layout is really nice, but the node size is too small. Note, that larger nodes
have a higher mass.

I've tried to increase the minumum node size in this example [2]. But it looks like, 
that increasing the scaling min property of the nodes is not enough. I changed the 
physics values too, but with no success. 

Which property is wrong and needs to be changed in order to have the nice result of the 
first version? Alo the node scaling seems to be broken in the second example. It's hard to
find good settings with node values between [0,1]. 

Would be really nice, if you could help with appropriate settings. 

Best Uli

[1] http://jsfiddle.net/bokm6ymy/16/
[2] http://jsfiddle.net/bokm6ymy/17/

**Comment by josdejong** [comment]
Maybe it helps to first set all configuration values in [2] equal to the default values listed in the [docs](http://visjs.org/docs/network/#modules), to verify whether it gives the same result as [1]. If that is correct, you can start changing the config values one by one to see how it changes the result. Does that make sense?

**Comment by Tooa** [comment]
> Maybe it helps to first set all configuration values in [2] equal to the default values listed in the docs, to verify whether it gives the same result as [1].

It doesn't give the same result. It just looks like a big cluttered circle. 
<img src="https://cloud.githubusercontent.com/assets/5375334/10425082/12cf1afe-70d5-11e5-8386-097567f9892a.png" width="200" height="200" />

Then I've tried to adjust the `centralGravity` property. First image `-500` second image `-2000`.

<img src="https://cloud.githubusercontent.com/assets/5375334/10425201/ed6a7938-70d5-11e5-8e04-ba61e1f0aae7.png" width="200" height="200" />

<img src="https://cloud.githubusercontent.com/assets/5375334/10425236/24ddd72a-70d6-11e5-96b3-c4c0b6be97a8.png" width="200" height="200" />

Well, compared to the "gold standard" (next image) the graph structure is absolute worse. 

<img src="https://cloud.githubusercontent.com/assets/5375334/10425274/83c2374a-70d6-11e5-8934-7fef4b361850.png" width="200" height="200" />

I just wanted to have the minimum node size bigger. Not sure, how to achieve the nice result of the "gold standard" with bigger nodes.

**Comment by AlexDM0** [comment]
Hi,

Size of the node and the physics don't actually have anything to do with each other. Unless you have the avoid overlap on but I wouldnt recommend that. 

Uli, you have shown me graphs that where very well laid out. The idea here is not different. Couple the mass to the value and use the size for aesthetic purposes. 

I can't look into detail since I'm on holiday but I can take a look next month if the problem still occurs. 

Regards,

Alex

**Comment by AlexDM0** [comment]
I changed your mass:
```
for (var i = 0; i < nodes.length; i++) {
        nodes[i].mass = Math.ceil(2000* nodes[i].value);
    }
```

and updated the physics:
```
"barnesHut": {
                        "gravitationalConstant": -19050,
                        "centralGravity": 1.3,
                        "springLength": 170,
                        "springConstant": 0.035,
                        "damping": 0.23
                    },
                    "minVelocity": 0.75,
                stabilization: {
                    enabled: false,
                    iterations: 2000,
                    updateInterval: 25
                }
```

seems fine?

**Comment by AlexDM0** [comment]
Can I close this issue?
