### ISSUE TITLE
Timeline: Custom shapes for certain items?

### ISSUE THREAD

**Issue by globegithub** [almende/vis#1356]
Is it possible to specify custom shapes for some of the items? I realize that I can specify custom height and fill for an item. But I am looking to specify a u-shape which spans the lower part of a bar shape. This shape needs to be visible even if there are other overlapping "regular" bar shapes. It might mean that I, essentially, need a line-U shape.

Thank you!

**Comment by josdejong** [comment]
Thanks for your suggestion. I think you can get a long way by writing custom HTML/CSS for your items. Maybe you could make the original background and border of the item transparent, and fill the item contents with this U-shape you need. Using [templates](http://visjs.org/docs/timeline/#Templates) may come in handy here.

**Comment by globegithub** [comment]
That is what I ended up doing; created a class with a height of "U", background:none. I'll look into your suggestion of template. Thank you for your reply and suggestions!
