### ISSUE TITLE
Clustering by zoom issue

### ISSUE THREAD

**Issue by Tooa** [almende/vis#1358]
Hi,
I just discovered an issue with the clustering by zoom example [1]. Zoom out until there's only one cluster left, click "Stabilize when clustering" and zoom in again. You will notice that there are disconnected graph parts. 

Best Uli

[1] http://visjs.org/examples/network/other/clusteringByZoom.html

**Comment by josdejong** [comment]
Thanks for reporting this bug, it's easy to reproduce this.

**Comment by AlexDM0** [comment]
Hi,

I've pushed a fix for this to develop. This was actually a bug in the example, not in vis. We'll release this Friday.

Cheers
