### ISSUE TITLE
Timeline: Is there a method when items become visible?

### ISSUE THREAD

**Issue by tsnolan23** [almende/vis#1360]
I noticed that when the timeline is loaded, only items that are visible within the current date range are added to the DOM on page load.  Then, as you change the range and more items become visible, they are automatically added to the DOM.

Is there a method that can be used to perform a function when those items are added to the DOM? onAdd only seems to work if the user adds something, not when the item is automatically visible.

**Comment by mast0r** [comment]
There is a method `timeline.getVisibleItems()` that returns an array with all visible items.

**Comment by josdejong** [comment]
There is no hook available to know when an item was rendered in the DOM or removed from the DOM. 

Where do you need such a hook for exactly?

**Comment by yotamberk** [comment]
@tsnolan23 Is this issue still relevant? Can we close this issue?
