### ISSUE TITLE
How to create an item on the timeline from drag&drop ?

### ISSUE THREAD

**Issue by cedrouck** [almende/vis#1361]
Hi,

I have external container to the timeline that i want to drag&drop into a group of the timeline.
I would like to do the same issue that is mentioned here : https://github.com/almende/vis/issues/582
I don't really understant the solution of @josdejong 

Does anyone can give me exemple or more precisions please ? :)

Thanks
Have fun !

**Comment by cedrouck** [comment]
Up :)

**Comment by cedrouck** [comment]
Hello,

Does anyone can help me please ? :)

Thanks.

**Comment by josdejong** [comment]
I'm afraid I would explain it in exactly the same way as in #582, I'm not sure what's unclear about the proposed solution.

**Comment by cedrouck** [comment]
When i drop element on timeline (event attached to vis-group class), i just need to call timeline.itemsData.getDataSet().add(item) to add it.

I use the snap function to adjust my elemen position and.... wow, it work ^^

Thank's for you help.

**Comment by faizanfarooq6** [comment]
@cedrouck  is it possible that you can share your solution?
