### ISSUE TITLE
Node in network gets hidden with custom levels

### ISSUE THREAD

**Issue by AlexZeitler** [almende/vis#1362]
This is the result I want to achieve:

![screen shot 2015-10-12 at 20 58 11](https://cloud.githubusercontent.com/assets/287480/10436017/083475a4-7124-11e5-9f26-644aefc7c7c3.png)

This is my code:

```
    nodes.push({id: 0, label: 'Root'});
    nodes.push({id: 1, label: 'Child 1'});
    nodes.push({id: 2, label: 'Child 2'});
    nodes.push({id: 3, label: 'Child 3'});
    nodes.push({id: 4, label: 'Child 2.1'});
    nodes.push({id: 5, label: 'Child 2.1.1'});

    edges.push({from: 0, to: 1});
    edges.push({from: 0, to: 2});
    edges.push({from: 0, to: 3});
    edges.push({from: 2, to: 4});
    edges.push({from: 4, to: 5});

    nodes[5]["level"] = 0;
    nodes[4]["level"] = 1;
    nodes[3]["level"] = 2;
    nodes[2]["level"] = 2;
    nodes[1]["level"] = 2;
    nodes[0]["level"] = 3;
```

The result is:
![screen shot 2015-10-12 at 20 59 36](https://cloud.githubusercontent.com/assets/287480/10436042/2e3d85ba-7124-11e5-89ef-dfdecfd6544a.png)

As you can see, `Child 1` is missing. But it is not missing, it is just hidden by `Child 3`.
If I start dragging `Child 3` down, the network gets re-rendered and `Child 1` appears as expected.

Are there any workarounds?

**Comment by dragonzone** [comment]
If you are making dynamic changes to the nodes/edges and are using the DataSet Object, then you should use the APIs that are available to you. Here is the URL: http://visjs.org/docs/data/dataset.html#Methods

Here is the code example using that APIs based on your example which will produce them the way you wanted. Hope this help.

http://jsfiddle.net/feh98058/

**Comment by AlexZeitler** [comment]
@dragonzone Thanks for your reply.
When running the fiddle, I get this result:

![screen shot 2015-10-13 at 19 07 36](https://cloud.githubusercontent.com/assets/287480/10462221/c185bb8a-71dd-11e5-9736-c0a523781c85.png)

This is very different from what I need.

**Comment by josdejong** [comment]
@AlexZeitler the jsfiddle of @dragonzone is missing configuration for hierarchical layout. I can't get your issue reproduced, can you maybe create a jsbin/jsfiddle which demonstrates the issue?

**Comment by AlexZeitler** [comment]
@josdejong Using this [jsfiddle](https://jsfiddle.net/AlexZeitler/gg8exnfz/) you can see the issue.

**Comment by dragonzone** [comment]
I tweaked your code a little. Here is a workaround. https://jsfiddle.net/gg8exnfz/2/

**Comment by AlexDM0** [comment]
Seems like something in the physics or positioning is broken... Strange that this occurs now...

**Comment by josdejong** [comment]
Thanks for the fiddles, that will make it easy to hunt down this bug.

**Comment by AlexDM0** [comment]
Hi,

I've pushed a fix for this to develop. We'll release Friday to get this to you.

Cheers

**Comment by AlexZeitler** [comment]
Thanks, looking forward to it! :+1:
