### ISSUE TITLE
Hierarchical Layout : Drag node up or down is not working but left or right works

### ISSUE THREAD

**Issue by vramali1** [almende/vis#1363]
Hello,

I am creating node in a vis js network by using Drag and Drop from a grid. I am creating a Hierarchical layout. When I create the nodes, I was able to drag the nodes left or right, but I could not move the nodes up or down inside the network container. The following is the options.I tried using allowedToMoveX & allowedToMoveY true but It didn't work. Could you please help.

Graph Options:
---------------------
			autoResize : true,
			interaction : {
				hover : true
			},
			nodes : {
				shape : 'box'
			},
			edges : {
				arrows : 'to'
			},
			layout : {
				hierarchical : {
					enabled : true,
					sortMethod : 'directed'
				}
			},
			physics : {
				enabled : true,
				hierarchicalRepulsion : {
					nodeDistance : 200,
					centralGravity : 1
				},
				stabilization : {
					enabled : true,
					fit : true
				}
			},
			manipulation : {
				enabled : true,
				initiallyActive : true,
				addNode : false,
				
				},
				deleteNode : function(data, callback) {
					me.deleteButtonHandler(data);
					callback(null);
				},
				editNode : function(data, callback) {
					me.editButtonHandler(data);
					callback(null);
				}
			}

Node Options:
--------------------
var node = {
			id : itemid,
                        x : xcordinate,
			y : ycordinate,
			allowedToMoveX: true,
                        allowedToMoveY:true
		}

Thanks

**Comment by josdejong** [comment]
In hierarchical layout, the vertical position of the nodes is chosen by the layout algorithm, and fixed, so you see the nodes in a hierarchical view. This is expected behavior.
