### ISSUE TITLE
Reducing the vis.js file to only Timeline components.

### ISSUE THREAD

**Issue by mast0r** [almende/vis#1366]
Is it possible to reduce the `vis.js` library only to the Timeline-relevant functions? At the moment the library includes all of the components (Network, Graph, etc). 
I want to reduce the "weight" of the vis.js file.

**Comment by josdejong** [comment]
Yes, you can create your own custom bundle: https://github.com/almende/vis#custom-builds

**Comment by mast0r** [comment]
Many thanks!
