### ISSUE TITLE
Timeline: How can I adjust the alignment of item-label inside an item?

### ISSUE THREAD

**Issue by globegithub** [almende/vis#1368]
The item labels are showing up left-aligned in my timeline and all examples on your documentation. How can I adjust this alignment to be in left, center, or right? I could not figure it out from vis.css.

Thank you.

**Comment by brichbe** [comment]
You can change the `align` option for the timeline itself, which affects the horizontal alignment of the items.

See the documentation at:  http://visjs.org/docs/timeline/#Configuration_Options

**Comment by globegithub** [comment]
That worked.

Thank you!
