### ISSUE TITLE
vis js network drag in particular area or <div>

### ISSUE THREAD

**Issue by tatsat** [almende/vis#1371]
In vis js network dragging we have been trying to get the drag in limited area, it should not go to the hidden place and should not cross the margin,can any one help us with this issue in coding.

here is the sample example of vis js network:
http://visjs.org/examples/network/basicUsage.html.

Thank You.

**Comment by josdejong** [comment]
Network does not support these sorts of boundaries to limit dragging nodes around. If you give network boundaries, you could get a problem when add more nodes: the reserved area can get too crowded then. Instead, you can zoom in and out yourself, and there are methods like `fit()` to zoom the Network such that all nodes are visible in the viewport.

**Comment by vramali1** [comment]
Add options navigationButtons : true which enables a Zoom Extends Button on right hand side. When you click the button, the graph will fit the contents inside the canvas.
var options ={ 
interaction: {
		         navigationButtons : true
		   }
}

**Comment by AlexDM0** [comment]
This is not possible with vis. We have no plans to support this feature. You can manually dig into the source to make it suit your needs. You're looking for the drag handler in the interactionHandler.js

Regards
