### ISSUE TITLE
vis.js 3.11.0 + PhantomJS + runtime constructed SVG images for nodes = "Could not load image: blob:file///"

### ISSUE THREAD

**Issue by DmitriyPogorelov** [almende/vis#1372]
Hi. We use vis.js 3.11.0 to draw network diagrams. We draw each node as an SVG and then use image property of the node to load that generated SVG.

I`m creating test automation at the moment and hit an issue that network is properly displayed in browser (properly means nodes are drawn) after some time, not immediately. I.e., after network creation, only edges are drawn and then, after some time which usually almost immediate for small networks, nodes are drawn as well. I cannot figure out which event or method should I hook in to be sure that at that point of time network is fully drawn on canvas - both nodes and edges.

Are there something like this in library? Thanks in advance!

**Comment by DmitriyPogorelov** [comment]
After deeper investigation, I think the problem is that images are not properly loaded on canvas when run in PhantomJS. We use PhantomJS as a browser engine to execute out tests and I get "Could not load image: blob:file///<GUID>" messages in PhantomJS logs.

Most likely I`m not the first one to do such tests. Are you aware if one can use PhantomJS + vis.js (network where nodes are images constructed on the fly from SVG)?

**Comment by Tooa** [comment]
Hi, 
> where nodes are images constructed on the fly from SVG

Not sure what you mean here. 

I also use visjs and phantomJS and my nodes look like this:
`{"id":1462,"label":"Andreas Lipkow", "shape":"image","image":"images/per.svg"}'`

...,where `per.svg` is an image in the `images` folder next to the simulated `network.html`. This works well with phantomjs. 

Best Uli

**Comment by DmitriyPogorelov** [comment]
We construct SVG at runtime as a string. Something like:
var svg = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" ......'

Then we construct a Blob based on this SVG. Like this:
var svgBlob = new Blob([svg], {type: 'image/svg+xml;charset=utf-8'});
var img = window.URL.createObjectURL(svgBlob);

Then this img is used in visjs node:
node.image = img;
node.shape = 'image';

**Comment by josdejong** [comment]
Not sure if it's related, but we had issues in the past running code in PhantomJS due to PhantomJS using an old browser engine, see https://github.com/almende/vis/issues/1170. Is it a possibility that the engine used by PhantomJS doesn't support `Blob`? Maybe you could first test whether PhantomJS neatly renders such an image outside of Network.

**Comment by DmitriyPogorelov** [comment]
It was a great advise. You are right - the root cause is that PhantomJS is not able to properly create an image out of the Blob with dynamic SVG content. I constructed a very simple repro page and script which shows that (without vis.js and even canvas). I`ll dig deeper into the issue with PhantomJS, but it is obvious that vis.js is not a problem here.

Thanks a lot!
