### ISSUE TITLE
Changing months, and days labels

### ISSUE THREAD

**Issue by OzoneGrif** [almende/vis#1373]
Hello, I can't find a clear answer to this problem.

I want to change the labels display for months and days to different languages. Apparently Vis is based on moment.js so I tried this :

```
 var locales = {
		mylocale: {
			months: "janvier_février_mars_avril_mai_juin_juillet_août_septembre_octobre_novembre_décembre".split("_"),
			monthsShort: "janv._févr._mars_avr._mai_juin_juil._août_sept._oct._nov._déc.".split("_"),
			weekdays: "dimanche_lundi_mardi_mercredi_jeudi_vendredi_samedi".split("_"),
			weekdaysShort: "dim._lun._mar._mer._jeu._ven._sam.".split("_"),
			weekdaysMin: "Di_Lu_Ma_Me_Je_Ve_Sa".split("_"),
		}
	}

	var options = {
		locales: locales,
		locale: 'mylocale',
	};
```

It doesn't work, and I don't find how to achieve this modification.

**Comment by josdejong** [comment]
How to change the locale is described here: http://visjs.org/docs/timeline/#Localization

You can change the format of the labels using the configuration option `format`, see `format` in the table with configuration options: http://visjs.org/docs/timeline/#Configuration_Options

**Comment by OzoneGrif** [comment]
I have read these documentations, but the labels I want to change are not documented anywhere.

'Monday' should become 'Lundi' or something else.

**Comment by mast0r** [comment]
If you want to use a standard localization - download a file named "moment-with-locales.min.js"

    http://momentjs.com/downloads/moment-with-locales.js

and add to your HTML page. Then you will be able to change the Timeline's locale:

```javascript
var options = {
  locale: 'nl'
};
```

Otherwise, in case you want to create your OWN localization - do it like described on the Timeline's page:

    http://visjs.org/docs/timeline/#Localization

**Comment by OzoneGrif** [comment]
Thank you for your answers. I got it to work.
moment-with-locales has to be loaded before vis.js

**Comment by GowrishankarGeek** [comment]
Hi, I can't find a clear answer to this problem i searched lot.
please help me folks
I want to change the labels(AddEdge --> link component) display
var options = {
  locales : {
  sample: {
    edit: 'Edit',
    del: 'Delete selected',
    back: 'Back',
    addNode: 'Add Node',
    addEdge: 'Add Edge',
    editNode: 'Edit Node',
    editEdge: 'Edit Edge',
    addDescription: 'Click in an empty space to place a new node.',
    edgeDescription: 'Click on a node and drag the edge to another node to connect them.',
    editEdgeDescription: 'Click on the control points and drag them to a node to connect to it.',
    createEdgeError: 'Cannot link edges to a cluster.',
    deleteClusterError: 'Clusters cannot be deleted.',
    editClusterError: 'Clusters cannot be edited.'
  }
},
  locale: 'sample',
  layout: {
    randomSeed: 5,
    hierarchical: {
      enabled:false,
      levelSeparation: 70,
      direction: 'LR',   // UD, DU, LR, RL
      sortMethod: 'hubsize' // hubsize, directed
    }
  }

**Comment by charles-tainui** [comment]
thanks a lot @OzoneGrif , i ran into the same issue -_-

**Comment by mojoaxel** [comment]
@GowrishankarGeek Please create a new Issue for your question

**Comment by Robert-Beier** [comment]
I don't get how to make it work. Here is an example I expected to work, but it doesn't. https://jsfiddle.net/e7uodse2/3154/
Can somebody help me solve this and explain why it doesn't work?
