### ISSUE TITLE
[DataSet] Deleted fields not removed after update.

### ISSUE THREAD

**Issue by rjbriody** [almende/vis#1375]
HI,

When I delete the label field of an edge and update that edge via the DataSet the label is still displayed. 

Issue can be seen in action here: http://plnkr.co/edit/4RIOu0MfsWhCxuFQD04M?p=preview
I expect the edge label "BOO" to disappear after the timeout executes. 

Thanks!

**Comment by rjbriody** [comment]
After further experimentation, it appears that this is an issue in the way DataSet handles deleted fields (it doesn't). Example here: http://plnkr.co/edit/UBUDTYyFblA9pSwSRoO8?p=preview

**Comment by josdejong** [comment]
The DataSet doesn't have a nice way to delete properties, the current way is to set such a property to `null`, the visualizations will then ignore this property. 

We should definitely implement a nicer way to delete properties.

**Comment by rjbriody** [comment]
Thanks, and at least now there is an issue that someone might find if they go searching.
