### ISSUE TITLE
Timeline: Create array of items using Object and send over the wire to client

### ISSUE THREAD

**Issue by globegithub** [almende/vis#1376]
I've successfully, pushed an array of items as hashes over a wire using WebSocket from server to client. Now, I'd like to create this array starting from an object, with a constructor, that has id, group, content, start, and end as its fields. I have not been able to create the right string to send over. Is there an client/server example which shows how to do this - or any suggestion?

Thank you!

**Comment by josdejong** [comment]
I'm not sure what you mean. If you use something like socket.io it's very easy as socket.io does the serialization and deserialization of objects for you. If you send a string over the wire, you will simply have to do the serialization yourself using JSON.stringify and JSON.parse.

**Comment by mojoaxel** [comment]
@globegithub Is this issue still relevant?

**Comment by globegithub** [comment]
Not to me as I am not working on the project that was going to use Vis.
Thank you.

On Wed, Nov 2, 2016 at 2:13 AM, Alexander Wunschik [Masked] <
