### ISSUE TITLE
Hierarchical View : Avoid overlapping edges  and Node Connection issue

### ISSUE THREAD

**Issue by vramali1** [almende/vis#1377]
Hello,

I am using Vis JS Network by using Hierarchical View by dragging and dropping items and creating nodes and edges. Could you please help me with the following suggestions and how it can be better.

1) Whenever I create the node, It is always created close to the root node .Please see In the image SBB_ROUTE_MIDCALL is the newly created node. I couldn't move the node up or down. If I want to connect the newly created node from the bottom of the graph it is very tedious as the newly created node is on the top of the graph. Please see attached image. The SBB_ROUTE_MIDCALL is the newly created node. I want to connect "Reject" Node in the bottom of the graph to  SBB_ROUTE_MIDCALL. As you see it is tedious as the nodes are not close to each other. Could you please give me some suggestions how to solve this issue.

2) When I connect the nodes, sometimes the edges overlaps. Please see attached image. SBB_ROUTE_MIDCALL and Play Announcement Edges overlap. Could you please give some suggestion how to prevent overlapping of edges.

![image](https://cloud.githubusercontent.com/assets/7856946/10562564/9664ec6e-7516-11e5-92e8-fb4980a974e8.png)

Thanks & Regards,
-Vijay

**Comment by josdejong** [comment]
I think hierarchic views do not work nicely together with manipulation of nodes (adding/remove nodes). We could improve there I guess.

As for the overlapping edges: yes, that can happen, it's because of the force directed algorithm behind it.

**Comment by AlexDM0** [comment]
There is nothing we can do about this. Try giving the new nodes a position when you add them.

**Comment by TrueFurby** [comment]
Second problem is same as the one I posted (https://github.com/almende/vis/issues/1453).
Here's a jsBin example in larger scale, https://jsbin.com/fovuqefifo/edit?js,output.

I played around with options and realized I don't really require physics in my network view this actually makes the network load almost instantly:
![nophysics_network_view](https://cloud.githubusercontent.com/assets/1229233/11434883/f2662924-94d3-11e5-9b16-cc64590052fd.png)
 However all nodes are aligned to the left. Is there some way to make nodes centered and spread to both sides for all levels symetrically?

**Comment by AlexDM0** [comment]
...yes. Turn on physics. That's what it is there for.

**Comment by TrueFurby** [comment]
Yeah, but physics clearly aren't doing a good job in this setup.

**Comment by vramali1** [comment]
I used Physics and I am facing the same issue that the nodes are not
arranged symmetrically or not balanced on left and right sides.For the
edges overlapping I fixed the issue by creating brand new Vis graph
whenever new edges are added.

On Friday, November 27, 2015, Ondrej Fabry <notifications@github.com> wrote:

> Yeah, but physics clearly aren't doing a good job in this setup.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/almende/vis/issues/1377#issuecomment-160198671>.
>


-- 
Thanks,
Vijaykumar
Contact:312-532-4657.

**Comment by TrueFurby** [comment]
In this [jsBin](https://jsbin.com/fovuqefifo/edit?js,output) they are overlapping even on fresh network instance

**Comment by vramali1** [comment]
I mean destroy the existing graph and create a new Graph with new nodes and
edges.

On Friday, November 27, 2015, Ondrej Fabry <notifications@github.com> wrote:

> In this jsBin <https://jsbin.com/fovuqefifo/edit?js,output> they are
> overlapping even on fresh network instance
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/almende/vis/issues/1377#issuecomment-160201996>.
>


-- 
Thanks,
Vijaykumar
Contact:312-532-4657.
