### ISSUE TITLE
DataSet original data not available

### ISSUE THREAD

**Issue by marcortw** [almende/vis#1378]
Hi there

I'm not sure if this is a bug in the docs or if I just misunderstand the functionality of the DataSet and its events. The documentation at http://visjs.org/docs/data/dataset.html says in the events section:

> The update event has an extra field data containing the original data of the updated items, i.e. the gives the changed fields of the changed items.

If I look at the example on http://visjs.org/examples/timeline/interaction/eventListeners.html, I'd assume that if I for example move "item 3" from Thu 18 to Tue 23 to the right, the properties.data would show the old position. But instead the logEvent displays the current value in the rendered output:

```javascript
event="update", properties={"items":[3],"data":[{"id":3,"content":"item 3","start":"2013-04-23T22:00:00.000Z"}]}
```

Is this a different event? Or am I looking at the wrong place? It would be really nice to have the old data of an item (object before the update) for my specific use case. Thanks for this great library and keep the good work going!

Marco

**Comment by josdejong** [comment]
Thanks, will look into it.
