### ISSUE TITLE
How to 'fit' prior to window.print?

### ISSUE THREAD

**Issue by skinkie** [almende/vis#1379]
I have created a stylesheet which should limit the graph of visjs to 675px on paper. Vis.js usually works very well responsively. But in print preview it does not 'scale the contents back' to the the y-range I want to print. What should be done to achieve this result? Below is a workaround that seems to sometimes work... any tips?

```javascript
    function window_print() {
        $("#vis-weekdag").css("width", "675px");
        graph2d[global_json['key']].fit();
        window.setTimeout(function() {
            window.print();
        }, 100);
        return true;
    }
```

**Comment by josdejong** [comment]
I created a simple jsbin with a print button, it will work fine if you call `network.redraw()` also before calling `network.fit()`. The redraw will change the size of the Network, whilst fit will zoom the contents to the (now updated) size of the network.

**Comment by josdejong** [comment]
Here a jsbin: http://jsbin.com/vofede/edit?html,output

**Comment by skinkie** [comment]
To be honest, I don't feel that the issue is solved. What I would expect is that the fit would be applied when the media type changed.

**Comment by AlexDM0** [comment]
Due to the lack of response I figured it worked. What do you mean by media type?

**Comment by skinkie** [comment]
The media type from the CSS perspective http://www.w3schools.com/css/css3_mediaqueries.asp once Visjs is to be printed I would expect that what is currently in view (x and y axis) will be fitted to the viewbox available prior to printing. When a user would go directly to print found in the menu the canvas is linearly scaled.

**Comment by AlexDM0** [comment]
Are you referring to the network or the graph2d module? Your code says graph2d (though graph was the old name for network) and you refer to canvas, which only exists in the network.

**Comment by skinkie** [comment]
I mean canvas as area where to draw on. Don't press print via de button in the example below, but do it via the Menu. You'll observe the issue directly.

http://output.jsbin.com/vofede

**Comment by AlexDM0** [comment]
We'll have to look into it but I can't promise this will be soon. We do not have a direct need for this enhancement. We're open to pulls though!

Cheers

**Comment by AlexDM0** [comment]
Hi,

After investigation we cannot get this working uniformly across browsers. It's easy to catch the print event but firefox resized the canvas AFTER the print event callback so the redraw is not working. Chrome works fine. 

Your solution to manually set the width to 300px would solve it but I'm not going to force a width when a print event is triggered.

https://www.tjvantoll.com/2012/06/15/detecting-print-requests-with-javascript/

This shows you how to catch the events. It is up to the developers to determine what size they want to make the canvas when printing, we're not going to dictate it or make it configurable. It's so easy to do it yourself that I dont think having it in the options is worth it.

Regards
