### ISSUE TITLE
[FEATURE] build lib as modular for any usage separately

### ISSUE THREAD

**Issue by azimot** [almende/vis#1384]
in most usage of vis.js lib dont need to have all feature (graph2d ,3d,timeline and netword) together 
is possible to build modular "vis" to have smaller js file for example "network.vis-4.9.0.js" for network doing and so on
570KB for vis.js lib is a little heavy
after some comparing i raise up to Vis is best
Thanks for this easy to use and useful graph lib

**Comment by Tooa** [comment]
Duplicate #808
