### ISSUE TITLE
[Graph2d] line chart go behind of bar chart

### ISSUE THREAD

**Issue by amrocs** [almende/vis#1385]
I am using Graph2d, and I want to overlay line chart on bar chart.
But vis.js looks like ignoring group order, and line char always go behind of bar chart.
Is there a way to take line chart to front ? 
I want "order" option like z-index.

**Comment by amrocs** [comment]
I found drawing order codes in vis.js (line 24463 to 24470).
In there, drawing order is fixed with comment "bar needs to be drawn enmasse".

I cut BarFunctions.draw and paste before group.draw, line chart moved to front.

Usually, draw area of bar chart is larger than line chart (line chart is only svg thin path and
 some small circles), so I think bar chart should drawn before drawing line chart.
And in future, best way is groups have drawing order.

**Comment by josdejong** [comment]
Thanks, I changed the drawing order following your suggestion such that lines are drawn on top of bars.
