### ISSUE TITLE
Timeline: Last group ignores fixed height

### ISSUE THREAD

**Issue by Phil2812** [almende/vis#1388]
Hello,
I am using
```
.vis-label .vis-inner {
  height: 2em;
}
```
to fix the height of my groups. This works fine for all groups but the last one, which still gets bigger, unless it is empty.
Example: http://jsbin.com/litabejiso/1/edit?html,output
(last group has to have an item for the problem to occur).

Edit: Adding an empty group at the bottom and setting its height to 0px "fixes" the issue.

**Comment by josdejong** [comment]
Thanks, this has to do with the configured margin between items and axis. If you set that to half the margin between items and items, the height of all groups will be equal:

```js
var options: {
  margin: {
    item: 10,
    axis: 5
  }
}
```
