### ISSUE TITLE
Timeline: adding height option gets rid of vertical scroll bar

### ISSUE THREAD

**Issue by globegithub** [almende/vis#1389]
http://jsfiddle.net/TimunAb/3wt92ksw/

I copied mast0r's fiddle http://jsfiddle.net/o58hcubh/1/ without the synchronized scroll bars.

I am wondering what I am doing wrong! Adding "height" option gets rid of vertical scroll bar and I am not able to scroll vertically. Scroll bar is back if I remove the "height" option!

Thank you!

**Comment by globegithub** [comment]
One correction: I can drag items vertically when the scroll bar is not present. But the main issue remains. Is this an expected behavior? If yes, what do I have to do keep the scroll bar?

Thanks

**Comment by globegithub** [comment]
Once I switched to jquery 2.1.3 on JsFiddle, the scroll bars are working as expected. However, it is not working so in my local installation. Item-section scroll bar is just not appearing irrespective of whether I specify height parameter or not. I'll continue to troubleshoot my local installation.

**Comment by globegithub** [comment]
I am using the following styles. There is a scroll bar on group side. What could be the reason for scroll bar not appearing on the item side?

.vis-center>.vis-content {
    height: 100%;
    overflow-x: hidden;
    overflow-y: scroll;
}
.vis-left>.vis-content {
    height: 100%;
    overflow-x: hidden;
    overflow-y: scroll;
}

Thanks

**Comment by josdejong** [comment]
The Timeline is still missing built-in support for displaying a vertical scroll bar, see #273. There are some workarounds (like the jsfiddle of @mast0r), it could be though that they don't work 100% and you may have to do some experimenting yourself.

**Comment by yotamberk** [comment]
@globegithub a `verticalScroll` option has been added to the `develop` branch.
