### ISSUE TITLE
Mysql with vis.js best experience

### ISSUE THREAD

**Issue by salacoste** [almende/vis#1390]
Hi, guys!
I rendered the Network from mysql data via json request.
The question is about updates of nodes and edges DBs.

At current moment i have the node DB like:
id                  | label | etc...
Primary key
When i create new nodes, the vis.js creates custom ids in DataSet like "9dd19414-73bf-4d5e-a1c6-66898a621dab", but in mySQL i have get natural number.

What the best experience update current node or create new nodes and send the data to MYSQL?

The same question is about edges.

Thanks for future.

**Comment by josdejong** [comment]
If you create a new item in a DataSet without an id, the DataSet will create an id itself, it will generate a uuid. You can simply provide your own id, either create this client side or server side.

**Comment by felixhayashi** [comment]
You can intercept node creation events when the user uses the manipulation bar to add a node. At this stage you can change the id and pass it to the callback.

**Comment by salacoste** [comment]
I need this method:
1) click button which use addNodeMode() function and hearing user click;
2) When user click js get coordinates and open modal form for filling another vars (label, group and so on). Before form isnt filled we dont create an object.
3) When form is confirmed we send ajax to mysql (create object with all data and get its actual id)
4) after get ajax success with actual id we create object with all data.

1 - ok
2 - How intercept node creating but get coordinates of click?
3 - ok
4 - How initiate object creating with all data (x,y,actual id from mysql)

**Comment by felixhayashi** [comment]
1) use `options.manipulation.addNode = function(data, callback) { … };` as callback function where data is passed by vis and contains the x,y coordinates. Read the docs: http://visjs.org/docs/network/manipulation.html?keywords=addNode.

4) Use Dataset as @josdejong said it.
```
    var nodes = new vis.DataSet([
        {id: 1, label: 'Node 1', x: 1, y: 10, fixed: true},
        …
    ]);
```

**Comment by AlexDM0** [comment]
I'd use the events instead of the manipulation api but either will work. The click event gives the position as well.

I think a clear answer has been given to your issue and it can be closed.

Cheers
