### ISSUE TITLE
vis.js: Uncaught TypeError: Cannot read property 'root' of null

### ISSUE THREAD

**Issue by olivia-olivgirl** [almende/vis#1392]
Am using v4.9 of vis.js from the following cdn:
https://cdnjs.cloudflare.com/ajax/libs/vis/4.9.0/vis.js

Am running into the following error when toggling visibility of a group of objects on a Graph2D scatter plot.

    Uncaught TypeError: Cannot read property 'root' of null

Code where the exception occurs:

    graph.setOptions({groups:{visibility:prop}});

The deeper part of the code exception runs into vis.js and a screen grab is placed below.

<img width="590" alt="screen shot 2015-10-23 at 5 12 08 pm" src="https://cloud.githubusercontent.com/assets/15190213/10691828/032f23d6-79aa-11e5-80c2-5ff0adb4f40c.png">

Am unable to debug these even after some concentrated efforts. Any help/pointers/best practices as to how to best solve such scenaiors would be very helpful.

**Comment by josdejong** [comment]
Thanks for reporting this issue, we will fix it.

**Comment by josdejong** [comment]
This has been fixed in one of the latest releases.
