### ISSUE TITLE
Timeline axis sometimes can have no minor lables

### ISSUE THREAD

**Issue by jtraub** [almende/vis#1393]
Consider following page

https://gist.github.com/jtraub/8d62b49554d14a8c5e1b

If you open it and try to change range using mouse wheel you will eventually see that sometimes minor labels on timeline axis can be missing.

![bug2](https://cloud.githubusercontent.com/assets/153191/10700666/a7f8af74-7a02-11e5-8c51-fb262b344036.png)

This happens when display of ante/post meridiem is added using format option.

Debug shows that this behavior is caused by [computations in TimeAxis._repaintLabels](https://github.com/almende/vis/blob/master/lib/timeline/component/TimeAxis.js#L198). It is assumed that minor labels won't exceed 7 characters width which is not true in case of, say, 07:30 AM.

Sorry, I can not provide patch for the bug right now. Going to take a deeper look and try to fix it in the next few days

**Comment by josdejong** [comment]
Thanks for reporting this issue. 

I copied your example to a jsbin so we can immediately try: 

http://jsbin.com/mohuyor/edit?html,output

**Comment by vilchenko** [comment]
I also noticed that minors label sometimes disappear around daylight saving time change date.

**Comment by josdejong** [comment]
This has been fixed in `develop`, the fix will be released today.
