### ISSUE TITLE
feature request: brushable network

### ISSUE THREAD

**Issue by FrissAnalytics** [almende/vis#1394]
Hi,

I'm really exited and happy with the possibilities vis.js provides, great library! I was wondering if it would be possible to add the ability to be able to brush the network to select nodes and edges? A d3.js based example can be seen here: http://bl.ocks.org/mbostock/4560481

kind regards, Herman

**Comment by dragonzone** [comment]
This is probably what you are looking for: https://github.com/almende/vis/issues/977

**Comment by FrissAnalytics** [comment]
thanks! yes that is what I was looking for! Will something like that be incorporated into vis.js in the future you think?

**Comment by dragonzone** [comment]
Alex (who is the owner) will have to decide once he comes back from
vacation. I requested it awhile back but never got a full response. So,
this is the workaround for now.

On Tue, Oct 27, 2015 at 4:18 PM, Herman Sontrop <notifications@github.com>
wrote:

> thanks! yes that is what I was looking for! Will something like that be
> incorporated into vis.js in the future you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/almende/vis/issues/1394#issuecomment-151630610>.
>



-- 
Long "Andy" Do

**Comment by FrissAnalytics** [comment]
thanks!
