### ISSUE TITLE
How to work around VIS Timeline group ordering bug in Chrome?

### ISSUE THREAD

**Issue by parhumm** [almende/vis#1399]
[Vis.js Timeline](http://visjs.org/docs/timeline/) has bug with Chrome Browser(only), Its change ordering of group when Groups(Trucks) are more than 10 groups.

In [this exmaple](http://jsfiddle.net/parhum/rcsrfaka/) in Chrome browser **Truck 11** display in first row and **Truck 2** display after **Truck 10**. In other browser ordering of groups are correct.

**Example:** http://jsfiddle.net/parhum/rcsrfaka/

**HTML Code:**

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vis/4.9.0/vis.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/vis/4.9.0/vis.min.css">
    <div id="js__timeline"></div>

**JS Code:**

    <script>
      /**
       * Get URL parameter
       * http://www.netlobo.com/url_query_string_javascript.html
       */
      function gup( name ) {
        name = name.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");
        var regexS = "[\\?&]"+name+"=([^&#]*)";
        var regex = new RegExp( regexS );
        var results = regex.exec( window.location.href );
        if( results == null )
          return "";
        else
          return results[1];
      }
    
      // get selected item count from url parameter
      var count = (Number(gup('count')) || 1000);
    
      // create groups
      var groups = new vis.DataSet([
        {id: 1, content: 'Truck&nbsp;1'},
        {id: 2, content: 'Truck&nbsp;2'},
        {id: 3, content: 'Truck&nbsp;3'},
        {id: 4, content: 'Truck&nbsp;4'},
        {id: 5, content: 'Truck&nbsp;5'},
        {id: 6, content: 'Truck&nbsp;6'},
        {id: 7, content: 'Truck&nbsp;7'},
        {id: 8, content: 'Truck&nbsp;8'},
        {id: 9, content: 'Truck&nbsp;9'},
        {id: 10, content: 'Truck&nbsp;10'},
        {id: 11, content: 'Truck&nbsp;11'},
        {id: 12, content: 'Truck&nbsp;12'},
        {id: 13, content: 'Truck&nbsp;13'},
        {id: 14, content: 'Truck&nbsp;14'},
        {id: 15, content: 'Truck&nbsp;15'},
        {id: 16, content: 'Truck&nbsp;16'},
        {id: 17, content: 'Truck&nbsp;17'},
        {id: 18, content: 'Truck&nbsp;18'},
        {id: 19, content: 'Truck&nbsp;19'},
        {id: 20, content: 'Truck&nbsp;20'},
        {id: 21, content: 'Truck&nbsp;21'}
      ]);
    
      // create items
      var items = new vis.DataSet();
    
      var order = 1;
      var truck = 1;
      for (var j = 0; j < 21; j++) {
        var date = new Date();
        for (var i = 0; i < count/10; i++) {
          date.setHours(date.getHours() +  4 * (Math.random() < 0.2));
          var start = new Date(date);
    
          date.setHours(date.getHours() + 2 + Math.floor(Math.random()*4));
          var end = new Date(date);
    
          items.add({
            id: order,
            group: truck,
            start: start,
            end: end,
            content: 'Order ' + order
          });
    
          order++;
        }
        truck++;
      }
    
      // specify options
      var options = {
        stack: false,
        start: new Date(),
        end: new Date(1000*60*60*24 + (new Date()).valueOf()),
        editable: true,
        margin: {
          item: 10, // minimal margin between items
          axis: 5   // minimal margin between items and the axis
        },
        orientation: 'top'
      };
    
      // create a Timeline
      var container = document.getElementById('js__timeline');
      timeline = new vis.Timeline(container, null, options);
      timeline.setGroups(groups);
      timeline.setItems(items);
    
      document.getElementById('count').innerHTML = count;
    </script>

**Comment by josdejong** [comment]
As far as I can see you haven't defined any ordering for the groups, leaving their order undetermined.

You can either set the option `groupOrder` to `'id'` to have the groups ordered by their id, or provide your own sorting function there, or give all groups a property `order`.

From the docs on `groupOrder`:

> Order the groups by a field name or custom sort function. By default, groups are ordered by a property order (if set). If no order properties are provided, the order will be undetermined.

**Comment by parhumm** [comment]
Thanks, groupOrder solved my problem but default group ordering in chrome and other browser was different.

**Comment by josdejong** [comment]
The order of keys in an JavaScript Object is undefined, that's why different browsers may come up with a differing order.

**Comment by Kaliph** [comment]
Hi there ...At the moment I am experiencing the same issue. My Chrome Browser shows the groups in the wrong order. Could you please post an example of how to solve this issue. I don´t understand how to set the groupOrder correctly related to the id of the group. Thanks

**Comment by adripanico** [comment]
I'm having this issue (version 4.20.1). In my case I DO have a groupOrder method.

The timeline works perfectly in Firefox but, in Chrome, it changes the order of the elements as the user collapse/expand a group.
