### ISSUE TITLE
Hierarchical Layout :Allow space Between Node Manipulation toolbar and the graph Nodes on Canvas

### ISSUE THREAD

**Issue by vramali1** [almende/vis#1400]
Hello Team,

I have a issue when I created a graph using hierarchical layout. As you see below in the attached image that the node is created immediately ater the network manipulation taskbar. Could you please add the graph canvas after the node manipulation toolbar.

![image](https://cloud.githubusercontent.com/assets/7856946/10773736/5c16547a-7cba-11e5-9708-d1759aeffa21.png)

Thanks

**Comment by josdejong** [comment]
I'm not entirely sure what the problem is. Do you mean that the newly created node is placed outside of the visible viewport?

**Comment by vramali1** [comment]
In the attached image, if you see, there is no space between "Add Edge" toolbar and the top 3 nodes SBB_ROUTE_MIDCALL, Play Announcement, Authorize using XML RPC. If there is litte bit of spacing between the Nodes and Add Edge Toolbar is added by adding increasing the top margin/padding property  then it will look very nice. This issue happens in hierarchical layout.

As the graph Manipulation toolbar is white in color it is not visible. The Manipulation toolbar occupies the height = 5px of the canvas. 
Current Behavior in the vis js graph:
-----------------------
Add Edge| Add Node...(Manipulation ToolBar)
Node1 Node2 Node3

Expected Behavior in the vis :
-------------------
<div vis js container>
Add Edge| Add Node(Manipulation ToolBar)
5px or 10px height --- White Space
Node1 Node2 Node3
</div>

Thanks

**Comment by josdejong** [comment]
So you mean like you don't want the toolbar to overlap with the network itself? Did you try to move the toolbar up this with some CSS?

**Comment by AlexDM0** [comment]
You can also make the bar a bit more transparent. On a side note, hierarchical and manipulation are not officially supported so some strange behaviour may occur. 

Cheers
