### ISSUE TITLE
DataSet does not return item on DataSet.get()

### ISSUE THREAD

**Issue by wolfig** [almende/vis#1401]
Dear experts,

I have a network which I create from a DataSet. If the user clicks on an node I would like to fetch the data of this node from the dataSet. I only always get null...

I implemented the click-event as follows:

  network.on("click", function (params) {
	  if (params.nodes.length == 1) {
		  var elementID = params.nodes[0];
		  var elementClicked = theDataSet.get(elementID);
		  if (1 == 1){};  <---- only for debugging
	  }
    });

My nodes have string-IDs. I do see in vis.js line 6043 (DataSet.prototype._getItem) that the ID of the node is not passed from the interface to the subsequent code.

ID in the interface:
![image](https://cloud.githubusercontent.com/assets/10722208/10825239/63cdba9a-7e64-11e5-84e1-721c470af044.png)

ID in the code:
![image](https://cloud.githubusercontent.com/assets/10722208/10825256/7cdb0bf0-7e64-11e5-8899-1cf2f854e93e.png)

Is this a bug, or am I doing something wring?

Best regards
WolfiG

**Comment by dragonzone** [comment]
Take a look here: http://jsfiddle.net/u0qao0p6/

You may want to read the vis.js documentation for more details. 

http://visjs.org/docs/network/interaction.html#

**Comment by wolfig** [comment]
Hi Dragonzone,

I think I am doing the right thing - I am calling the getter with a, but it
returns NULL. I started exactly as in the jsfiddle-example by passing
params.nodes[0] which didn't work. I debugged this to the point which I
mention in my issue post and I see that the input variable "id" is filled
in the function interface but becomes null inside of the function. To my
understanding the "types" parameter does not play a role.
So having this said I think/hope that I am doing the right high-level
method call.

Cheers WolfiG

2015-10-29 19:42 GMT+01:00 dragonzone <notifications@github.com>:

**Comment by dragonzone** [comment]
You may want to use selectNode/selectEdge event instead of "click" b/c you may or may not be clicking on a node. But it's best if you can recreate the issue on http://jsfiddle.net/.

**Comment by wolfig** [comment]
Hi Dragonzone,

thanks for providing the example in JSFIDDLE. Based on that I changed my code:

old code:

	gephiJSON = JSON.parse(gephiJsonData.responseText);
		
	data = {
	nodes: gephiJSON.nodes,
	edges: gephiJSON.edges
	};
  
	var dataSetOptions = {};
	var theDataSet =  new vis.DataSet();
  	theDataSet.add(data);
...]

**Comment by josdejong** [comment]
Great this is solved. 

I've updated the docs to clarify this behavior (see https://github.com/almende/vis/commit/dc7fdaa67b57d08c9e274ff1734da9c2ab615209). In the future it may make sense to change the behavior of `get` to throwing an error when an item is not found, and introduce a new method `has` or `contains` to check whether some item exists. I'm not sure yet if that would be a more desirable solution.
