### ISSUE TITLE
(Maybe a stupid?) question about network.on("stabilizationProgress")

### ISSUE THREAD

**Issue by LLTommy** [almende/vis#1404]
Hey guys,
I've been using the network part of visjs for the last 3 weeks and I hope to create something nice and useful with it. I solved many problems on the way and came far already, but today I tried to add a loading bar (just like in the example) and it gives me a headache. I can not get it to work and I don't understand why. What am I doing wrong if...

network.on("stabilizationProgress", function(params){}  as well as 
network.once("stabilizationIterationsDone", function(params){} 

is NEVER fired? Do I have to use or turn off any specific options? Why could that happen? Other events like network.on("stabilized", function(params){} or "selectNode" or "click" work fine. But those two (stabilizationProgress, stabilizationIterationsDone) that I really need to implement for any kind of loading bar just don't give me any feedback. Looking at the documentation it might have something to do with the "hidden" stabilization. I still don't get it. I used in css display:none for the network, which means I can not hide the network more than that, the functions still are not triggered. I don't know, maybe somebody can shed some light on this. (Where does the hidden stabilisation is the example happen? Maybe I just have a bad day, I dunno?)

**Comment by AlexDM0** [comment]
Hi,

By default, a network stabilizes without rendering upon load. This can be disabled in the physics options. 

This phase, that is also triggered when using network.stabilize() is doing physics simulations without rendering. Hidden stabilization. 

Only this phase emits the events. 

Regards

**Comment by LLTommy** [comment]
Hi there,
thanks for your answer. I did not solve my issue yet, but your hint about rendering gives me at least an idea where this goes wrong. I am pretty sure it has nothing to do with the options (since I used the same as in the example) but simply with the fact that some rendering occurs right at the beginning of my page load - your answer gave me the idea to look at this stuff using Safari/Timeline.... However, I don't know yet how to take care of this problem, my code is way bigger than the example - I fetch data from a web service, change the data, add stuff dynamically to the page with JQuery...... and well, that leads to rendering I guess - which leads to me not having that stabilizationProgress (=hidden stabilisation) event. I hope to solve this in the near future, but again, thanks for the answer in the meantime.

**Comment by LLTommy** [comment]
Hey, just something else I came across - it's really a small thing so I don't open another issue for that:

I think the documentation about "findNode(String Id)" is wrong. The array that is returned is build up the other way around than said in the doc (e.g. the first element of the array is the node itself the second element is the cluster the node can be found in).
