### ISSUE TITLE
editEdgeMode not always triggering the 'red draggable dots' on both edge ends - redraw fixes

### ISSUE THREAD

**Issue by DoubleTK** [almende/vis#1406]
Hi,
First I'd like to say thank you for the excellent library you have put together. It's been very useful.

I am working exclusively with the Network module, and I have run into an issue with the editEdgeMode functionality. Normally, when you click the 'Edit Edge' button, the canvas redraws with two red dots - one at each end of the edge - that you can drag between nodes. After you have dragged one of those dots (and if you have set up a callback function for options.manipulation.editEdge) the callback function is called with the relevant info.

Unfortunately, I have run into a problem where the two red dots do not appear. I have the manipulation options enabled, but clicking on editEdge does not display the two red dots. Everything else is displayed correctly (like the toolbar changing to the 'back' button), but the dots do not appear. However, any sort of manual redraw will fix this. If I click a button that redraws the network, the dots appear. If I zoom in or out, the dots appear. If I move the graph view, the dots appear. It seems like the editEdge function is not calling redraw all the time, but I checked and it does seem to be getting fired each time. I'm not sure what else may be causing this. 

Any help would be greatly appreciated.

Thanks!

**Comment by AlexDM0** [comment]
Hi,

Can you reproduce this in a jsbin?

Cheers

**Comment by felixhayashi** [comment]
Just wanted to say, I also noticed this in with my setup, but I thought it was a problem related to my code. as @DoubleTK said, the dots appear on the next redraw, e.g. after moving the network. At the moment, I disabled this feature for this reason.

**Comment by DoubleTK** [comment]
Hi @AlexDM0 ,
I've never used jsbin before, so hopefully I did everything right. I was able to duplicate the issue. Here is the jsbin:

https://jsbin.com/muxoqaxiso/edit?html,js

(I'll keep the browser window open just in case. Not sure if the session goes away after a period of time)

Thank you for any help you can provide.

**Comment by DoubleTK** [comment]
I should clarify. It doesn't happen with complete consistency (I have yet to pinpoint the exact cause). Just keep clicking on an edge and selecting edit. Eventually, you will see the red dots do not appear. Seems to happen most often with the edges in the bottom right, although I have duplicated with every edge at some point.

**Comment by AlexDM0** [comment]
Hi,

I cant reproduce this. There is a hard redraw in there as well and everything is synchronous... I'd love more info on how to do this. Maybe OS and browser?

Regards

**Comment by DoubleTK** [comment]
Hi,
Interesting that you can't reproduce. I noticed the hard redraw while looking through the code as well. It gets called every time (as it should) but the dots still don't appear. I'm going to check with some of my co-workers to see if they have the same issue. 

Issue appears in both Firefox and Chrome.

OS is Windows 8.1 Enterprise.

Here is a video screen capture of the problem on my Google drive: https://drive.google.com/file/d/0B4AIPh5c7T8tdFQ2SXFFQWk0eHc/view?usp=sharing 

Thanks!

**Comment by DoubleTK** [comment]
Hi again,
I checked with my co-workers and the issue is present there as well. Browsers are Firefox and Chrome, both up-to-date. And OS is Windows 8.1 Enterprise.

Thanks!

**Comment by AlexDM0** [comment]
Hi,

I can reproduce this now, thanks! We'll see if we can fix this.

Cheers

**Comment by DoubleTK** [comment]
Hi AlexDM0,
Thank you for the update, that's good to hear. Let me know if there is any other information I can provide.

Thanks!
