### ISSUE TITLE
Overlapping node in Network hierarchical view

### ISSUE THREAD

**Issue by sachin-samel** [almende/vis#1407]
Hi,

Please see the example on the JSBin https://jsbin.com/lutikuvela/edit?html,js,output

Each node has different id.

However, node with id "XRVR02-leaf" is getting overlapped over node with id "XRVR01-leaf". (Nodes on level 2 on the extreme right side).

If you move XRVR02 a bit then you can see XRVR01 below it.

Not getting why nodes are overlapping over each other.

Thanks,
Sachin

**Comment by AlexDM0** [comment]
Hi,

this is the same as #1362

We'll look into it.

Cheers
