### ISSUE TITLE
bug fixed:true, not working with improved layout

### ISSUE THREAD

**Issue by diepes** [almende/vis#1408]
Could not attach the html "Attaching documents requires write permission to this repository. ￼ Try again with a PNG, GIF, or JPG."

I have a big network, 750 nodes and 1000+ links, i have 6 nodes i add fixed:true and x, y   it works for two and not for the other four.

If i manually delete all the other html nodes and links, it works for all 6.

**Comment by AlexDM0** [comment]
Hi,

Could you show this in a jsbin?

Regards

**Comment by AlexDM0** [comment]
Do the nodes overlap with other nodes?

**Comment by diepes** [comment]
No the 6 i place do not overlap.
When i delete all the edges from the html, 
the nodes layout in a big circle/sphere, with the 6 nodes in the middle correctly spaced.

Here is the page.
https://jsbin.com/vufisu/edit?html,output

**Comment by diepes** [comment]
Looking at the jsbin https://jsbin.com/vufisu/1/edit?html,output

The two round nodes 604-anon(-200,0)  and 624anon(200,0) seem to placed correctly at the same hight.

the box 232-anon(800,100) and 233-anon(-400,100) seem to be a bit random, and they cover box's 

231-anon(400,100) and 101-anon(-800,100) (Missing ? Covered)

**Comment by diepes** [comment]
https://jsbin.com/vufisu/3/edit?html,output
Deleting all the edges, and then the node layout looks as expected.

**Comment by AlexDM0** [comment]
try turning improvedLayout off, it could be there

**Comment by diepes** [comment]
Yes that worked.
I added, 

    var options = {
         layout: {
             improvedLayout:false
             }
          }

**Comment by AlexDM0** [comment]
Cool, I'll track down the bug causing it. I'll leave this issue open in the meantime if that's ok ;)

**Comment by AlexDM0** [comment]
Hi,

I've pushed a fix for this to develop. It will be released Friday.

Cheers
