### ISSUE TITLE
Manipulation toolbar disappears when keyboard on screen

### ISSUE THREAD

**Issue by UriKatsir** [almende/vis#1410]
Hello,

what i run the manipulation example on my Galaxy S4 device the manipulation toolbar disappears when i use the built-in keyboard.
For example, when i add a new node and label it using the device's keyboard--> press the "save" button--> node is added but the manipulation toolbar disappears from the screen.

Thank you

**Comment by josdejong** [comment]
Thanks for reporting this bug, we'll look into it.

**Comment by AlexDM0** [comment]
I'm not sure this is a bug with vis or a poor implementation of the keyboard on the S4... what are we supposed to do about this?
