### ISSUE TITLE
Timeline bug: on multiple generated timelines, y axis is wrong in each but not the last one

### ISSUE THREAD

**Issue by hboutemy** [almende/vis#1411]
a demo is worth a lot of explanations: https://people.apache.org/~hboutemy/visjs_timeline_1411_bugreport.html
```
<h1>Timeline bug demo</h1>
<p>dynamic addition of same vis.js timeline: only the last one is renderer as expected, previous ones y-axis is wrong.</p>
<div id="timelines"></div>
<script type="text/javascript">
var container = document.getElementById('timelines');
for (i in [0, 1, 2]) {
	var id = "timeline-" + i;
	container.innerHTML += "<p>" + id + "</p><div id='" + id + "'></div>";
	var items = new vis.DataSet([{content: id, start: new Date(2014,05,00), end: new Date(2016,04,29)}]);
	var options = {start: '2013-06-01', end: '2018-12-30', margin: { axis: 5 }, height: '120px'};
	var timeline = new vis.Timeline(document.getElementById(id), items, options);}
</script>
```
timeline-2 is perfectly rendered, but there is a bug in timeline-0 and timeline-1 y axis

**Comment by josdejong** [comment]
Thanks for the clear demo. That looks odd. You also can't move/zoom all Timelines except the last one.

**Comment by josdejong** [comment]
I see what's going wrong in your example: with your `container.innerHTML +=  ...`, you're effectively replacing earlier interactive DOM+JS with static DOM. So instead of replacing DOM, you should use `container.appendChild(...)`.

**Comment by hboutemy** [comment]
thank you for the explanations
I knew innerHTML was not the best API, but never was proved why: now I see a clear difference

I updated https://people.apache.org/~hboutemy/visjs_timeline_1411_bugreport.html to add the fixed version of my code

I'll close this issue, since it's my code that's buggy, not the lib: I don't know if the lib can protect against such wrong user code

Thank you for your great lib and your support

**Comment by josdejong** [comment]
you're welcome.
