### ISSUE TITLE
Feature Request: Timeline: Optimize performance with large number of groups

### ISSUE THREAD

**Issue by globegithub** [almende/vis#1412]
As discussed in issue #1383, Timeline is virtually unusable with large number of groups. Timeline will become usable for many new applications if this performance could be improved. One way to improve this performance has been suggested by mast0r in issue #1383.

**Comment by josdejong** [comment]
do we need a separate issue for this? Maybe it's easiest to keep #1383 open as feature request and keep the whole discussion in a single issue?

**Comment by josdejong** [comment]
I will update the title of of #1383 ok?
