### ISSUE TITLE
Node color reset bug

### ISSUE THREAD

**Issue by bartl-loclet** [almende/vis#1414]
Similarly to the fixed bug  #1220, there seems to be an issue when resetting the color of a Node:
If the "color" property of a given Node is first set to null and then set to a color string again, this new color is used as the highlight color for all other nodes.
Repro: http://jsfiddle.net/ygw1rj49/1/ (when selecting N2 it turns pink, but should be blue)

EDIT: I'm not that much of JS expert, but I did some more digging and I think the issue lies in components/Node.js:
```
    // individual shape newOptions
    if (newOptions.color !== undefined && newOptions.color !== null) {
        var parsedColor = util.parseColor(newOptions.color);
        util.fillIfDefined(parentOptions.color, parsedColor);
    } else if (allowDeletion === true && newOptions.color === null) {
        parentOptions.color = Object.create(globalOptions.color); // this sets the pointer of the option back to the global option.
    }
```
When newOptions.color is null, parentOptions.color is set to be a clone of the globalOptions. This works for the background and border properties, but highlight is an object and I think is not deep-copied, but passed by reference? So when when fillIfDefined sets newOptions.color on the next update, the highlight color of globalOptions are overwritten.

**Comment by AlexDM0** [comment]
Hi,

I've pushed a fix for this to develop. We'll release Friday to get this out to you.

Cheers
