### ISSUE TITLE
Network hierarchical layout: Show highlighted edges after adding edges using dataset

### ISSUE THREAD

**Issue by sachin-samel** [almende/vis#1418]
Hi,

I am using hierarchical layout for network.

I am implementing click and expand functionality on click of node.

When added the edges dynamically using dataset, I want to highlight those edges. [just like when user clicks on the node and edges gets highlighted if those edges already present on canvas]

Is there any method or property through which we can select the dynamically added edges?

Thanks,
Sachin

**Comment by AlexDM0** [comment]
Gee how about selectEdges
