### ISSUE TITLE
showManipulatorToolbar() on cancelled AddNode and AddEdge

### ISSUE THREAD

**Issue by AlexCro** [almende/vis#1420]
Hi all!

Vis.js network not call showManipulatorToolbar() on cancelled event AddNode and AddEdge.

**Comment by AlexDM0** [comment]
Thanks, we'll look into it.

**Comment by AlexDM0** [comment]
Hi,

I'm having trouble identifying the issue. What do you mean by cancelling exactly? If you have not performed the action then the mode will remain active until you go back. Could you clarify?

Cheers

**Comment by AlexCro** [comment]
Hi.

This code good working:

(Edit edge event)
...
```javascript if (confirm("Edit edge?")) {
	callback(data); // ok change
} else {
	callback(); // cancel change
}```


This code not show toolbar:

(Add node event)
...
```javascript if (confirm("Add node?")) {
	callback(data); // ok add node
} else {
	callback(); // cancel add node, not show toolbar
}```
Add edge event same.

Sorry for my bad english.

**Comment by AlexDM0** [comment]
Hi,

Cancelling an operation should not neccesarily mean you leave the mode.. I'm not sure what the bug is..

Regards

**Comment by AlexCro** [comment]
How to manually cancel this?

**Comment by AlexDM0** [comment]
```
// reset edit mode
network.disableEditMode();
network.enableEditMode();
```
