### ISSUE TITLE
Network : Graphical Manipulation of Nodes

### ISSUE THREAD

**Issue by ankushdharkar** [almende/vis#1422]
1. **Detect node dragged-dropped onto another node.**

 How can I drag and drop a node onto another node and detect it? 
 
 E.g. I may want to drag node-1 and drop it onto node-2, and then connect them with an edge programmatically.

2. **Connect Nodes graphically**

 How I can graphically connect nodes by drawing on canvas and track the new connection in the events?

 E.g. I may want to connect "Audi' node with existing "Cars" node to make a connection between the two.

3. **Drag-drop nodes inside other nodes**

 Is it possible to drag and drop nodes inside other nodes. So, Think of "Cars" as a big node which acts as a container to drop other smaller nodes inside it. 

 Something like what these guys do : https://www.youtube.com/watch?v=KIm02QaDfng (1 min video)
 (They use SVG though)

**Comment by josdejong** [comment]
1. You can add your own drag-and-drop listener on the DIV container where you created the Network, and use a method like `getNodeAt` to determine if an item was dropped on a node.  
2. In manipulation mode you have this behavior: you can create new connections between nodes in a visual way.
3. That's not so easy to achieve. I think you will have to hack into the code of Network for that.

**Comment by AlexDM0** [comment]
is this still an issue?

**Comment by ankushdharkar** [comment]
@AlexDM0 : No. @josdejong answered all the questions. Thank you.
