### ISSUE TITLE
Network: hierarchical layout click and expand always moves node to extreme right

### ISSUE THREAD

**Issue by sachin-samel** [almende/vis#1424]
Hi,

I am using hierarchical layout.

I am implementing click and expand functionality using dataset.

When i add a new node to dataset, it is always moved to extreme right OR the last node on the right side along with its edges. So the network looks quite complex.

Any way to display nodes at their default position they are in whenever we collapse and expand it again?

Thanks,
Sachin

**Comment by AlexDM0** [comment]
Hi,

At the moment I don't think so. You could hide the nodes instead of removing them to work around this?

Regards
