### ISSUE TITLE
Locale customization does not work

### ISSUE THREAD

**Issue by UriKatsir** [almende/vis#1425]
Hi

the docs say that i can create my own locale and use it to override the strings.
i tried that and it did not work.
only locales of value 'en' or 'nl' does not cause error. using any other custom locale name causes an error.

Uri

**Comment by josdejong** [comment]
Did you load `moment-with-locales.min.js`, like in [the localization example](http://visjs.org/examples/timeline/other/localization.html)?

See also docs: http://visjs.org/docs/timeline/#Localization

**Comment by UriKatsir** [comment]
I did.
did not resolve the issue.

thank you

Uri

**Comment by josdejong** [comment]
Can you create a jsbin or jsfiddle demonstrating the issue?

**Comment by UriKatsir** [comment]
I go it to work,
the documentation (http://visjs.org/docs/timeline/#Localization) was helpfull.

Thank you

Uri
