### ISSUE TITLE
Calendar View in Timeline Plot

### ISSUE THREAD

**Issue by ibnesayeed** [almende/vis#1426]
It would be nice to have an easy way to show activity like data in a calendar strip view. This is how GitHub shows public contributions of individuals. [Here is the relevant Google Chart documentation](https://developers.google.com/chart/interactive/docs/gallery/calendar) and [here is D3 Calendar View example for the reference](http://bl.ocks.org/mbostock/4063318).

**Comment by josdejong** [comment]
Thanks for your suggestion. Timeline items can contain HTML DOM, so wouldn't this just work already? Did you try?

**Comment by ibnesayeed** [comment]
Thanks @josdejong. I am sure there would be a way to do it with the current version. However, it would require a lot of custom configuration, markup, and styling to get the axis labels, weekly staking, and month boundaries right. Since it's a well known timeline view and many people can benefit from it, that's why I asked for the built-in support where we can adjust a single (or a few) configuration option(s) and get it working.

No, I did not try it myself yet, because I came to know about this library yesterday. And I must say I was impressed by the number of components and customization in each component it offers. A couple of years ago I was looking for a good library that offers network and chart packages for one of my projects. I ended up using two different libraries. I wish this was present at that time.

The motivation behind this request is a project that we are planning these days where we want an interactive timeline that morphs into different views based on the zoom level. For example a a monthly histogram over several years to begin with, when zoomed in, it morphs into calendar view with monthly boundaries, and on further zoom in it changes to discrete events, which can then show thumbnails on further zoom in. Every thumbnail, when clicked, will load something on a separate view.

**Comment by josdejong** [comment]
Wait a second, in first instance I thought you wanted to embed a calendar view inside the items of a Timeline or something. Now I see you really mean a different sort of view. Though both display data in time, this is *really* different sort of view. To create something like this, we could re-use the time axis from the Timeline and simply have to replace the contents with a new view (similar to how Timeline and Graph2d have the same Core but dispay different sort of data).

Implementing a feature like this is not on our own roadmap, but if someone is interested in picking this up please let us know.

**Comment by ibnesayeed** [comment]
The two links in the original post are pointing to examples that show what I meant. However, I think it will be useful to add a sample image here inline to avoid any confusion for the future readers of this thread.

![ca-fire-calendar-map-2006-2007](https://cloud.githubusercontent.com/assets/65147/11128701/815be2f4-8949-11e5-98b6-d1c1a3d9a0c5.png)

**Comment by yotamberk** [comment]
@ibnesayeed This issue is way out of our scope. It's a new view in vis and I really don't see this happening. I think you're better off using the libraries you've supplied to achieve this view.
