### ISSUE TITLE
Timeline: group height fit

### ISSUE THREAD

**Issue by pabloleo** [almende/vis#1428]
Hi I'm Paolo. 
I realized a scenario in my jsfiddle:
https://jsfiddle.net/p2frz0gw/

The problem is that when i move the yellow item from the moto's row, the other items  (pippo,pluto,paperino) invade the other row (Formula) . 
Could you help me to fix it, I'd like to do it without change the css properties?  

Thanks

**Comment by josdejong** [comment]
your jsfiddle only shows one group (moto) and one item (weekend) ?

**Comment by pabloleo** [comment]
sorry this is my jsfiddle updated: https://jsfiddle.net/p2frz0gw/1/

**Comment by josdejong** [comment]
The reason this happens is because you're giving your items an offset. I think you can fix this by giving the group labels the right height (similar to how you give your items a fixed height), so the height of the groups does not collapse when there are no yellow items left.

**Comment by pabloleo** [comment]
ok. But if I set:
 .vis-label.class.{
     height:120px !important;
}
 .vis-group.class{
   height:120px !important;
}

when I remove all the related item. The height of the timeline doesn't resize itself, as default height.

my jsfiddle:
https://jsfiddle.net/p2frz0gw/3/

Thank u 
Paolo

**Comment by josdejong** [comment]
You're very close. It should work if you set the css like this:

```css
.vis-label .vis-inner {
  height: 120px;
}
```

See also https://github.com/almende/vis/issues/1186#issuecomment-131853154

**Comment by pabloleo** [comment]
Thank U Jos. 
With: .vis-label .vis-inner setting, I obtain a timeline with a fixed height. 
I thought would be possible to have a timeline that fit to items content with fix height.
The height default value of the timeline is the minimum height. Do you think would be possible to handle this situation? i'd like to do it with a function that set the height in relation of what i have in my timeline, if i had some items it has to set a fix height, otherwise it has to set the height to default minimum value.
Thanks.

**Comment by oinkspoink** [comment]
From my understanding, using subgroups would totally fit your needs, because their height is dynamic and you don't have to use offset to position your elements.

Example: https://jsfiddle.net/p2frz0gw/4/

note: The subgroupOrder is vice-versa, because you have a bottom axis.

**Comment by josdejong** [comment]
@pabloleo have you had a look at the configuration option `minHeight`?

**Comment by pabloleo** [comment]
@josdejong @oinkspoink thanks guys. I solved my question with the solution proposed by @oinkspoink 
For me the question can be close! 
Have Fun with visjs :)
Paolo

**Comment by josdejong** [comment]
you're welcome
