### ISSUE TITLE
Timeline: Eight times slower response with IE 11

### ISSUE THREAD

**Issue by globegithub** [almende/vis#1429]
The setup is same as in issue #1383 (500 groups with 25000 items). I hope it was ok to open a new issue because this is related specifically to Internet Explorer.

What takes about 7 seconds in Chrome takes over 50 seconds in IE 11! I reset IE to its original settings and disabled most add-ons to no avail. I'm hoping somebody here will have some experience/insight into this.

Thanks

**Comment by josdejong** [comment]
Maybe IE is just slower than Chome? The difference is way bigger though than I would expect. 

Best solution: don't display that many items at once. Even Chrome's 7 seconds is terribly slow.

**Comment by mojoaxel** [comment]
Maybe [GPU rendering](https://msdn.microsoft.com/de-de/hh562071.aspx) was turned of in IE11?

**Comment by yotamberk** [comment]
@globegithub It seems to work fine on my machine. If you still have performance issues, feel free to reopen this issue.
