### ISSUE TITLE
How to combine vis.js with Raphael (and alike)

### ISSUE THREAD

**Issue by wolfig** [almende/vis#1431]
Hi experts.

I'm not sure if this belongs here, but I have a rather general question: is there a way to add custom SVG graphics to a network graph? What I want to do is to highlight parts of a graph by adding e.g. colored areas/boxes around clusters of nodes or to combine a network graph with pie chart slices.
Currently I am trying to combine Vis.js with Raphael.js by overlaying two layers. Still - and this might be due to my lack of experience with Javascript - I am facing many problems.
Do you guys have some approach to do something like this? E.g. I could imagine to draw custom graphics on the vis.js canvas. I searched the Web but did not find answers to make a breskthrough.

I'm grateful for any advice.
WolfiG

**Comment by AlexDM0** [comment]
Hi,

Take a look at the SVG Example and the render events Example. 

Regards

**Comment by wolfig** [comment]
Hi Alex,

thanks a lot for this hint. I was able to find the "render event" example, but not the "SVG" eample you mention (I was looking everywhere in the examples). It would be great if you could provide a link to this example.

Cheers
WolfiG

**Comment by AlexDM0** [comment]
Hi,

Sorry, It's names differently. I remembered the implementation :). 

http://visjs.org/examples/network/nodeStyles/HTMLInNodes.html

Good luck!

**Comment by wolfig** [comment]
Great! Thanks

**Comment by wolfig** [comment]
Hi guys, based on this thread I was able to build a nice visualization tool combining Vis.js and Paper,js. I documented my experiences in a bolgpost of mine:
http://wolfig-techblog.blogspot.de/2015/11/building-data-driven-applications.html

**Comment by AlexDM0** [comment]
Cool post! Thanks for sharing!
