### ISSUE TITLE
Timeline does not adjust height when groups and items are hidden

### ISSUE THREAD

**Issue by hitmanmcc** [almende/vis#1433]
Hello @josdejong,

We've been working with your timeline and we wanted to filter out certain groups and their items according to input provided by users through clicking different buttons. Whilst we can certainly set the style property for the groups and corresponding items to have visibility: hidden or visibility: visible as necessary, doing so hides those elements from the UI but the timeline does not adjust. This results in a strange UI presentation. 

Below you can see the view without filtering
![image](https://cloud.githubusercontent.com/assets/3464842/11152869/0bcc7bfe-8a2d-11e5-8c1b-c5bf35a78780.png)
Here you can see it filtered for a particular set of groups.
![image](https://cloud.githubusercontent.com/assets/3464842/11152920/6b8aabf6-8a2d-11e5-9e49-d584eb127763.png)
The effect we wanted was the one in the following screenshot which is what happens when we actually remove the hidden groups and items from the respective datasets:
![image](https://cloud.githubusercontent.com/assets/3464842/11152904/53ec2150-8a2d-11e5-9705-d7dc5eafe286.png)

Currently it doesn't seem like we can achieve this without actually removing the data from the datasets but when filtering parameters change we want that data to be present again. Either there's something I'm missing or this functionality we want will entail constantly changing the contents of the datasets.

I would appreciate it if you could weigh in on this, please.

Best regards,
André

**Comment by mast0r** [comment]
You can easily use the `filter` method of the DataSet to filter out the groups you don't want see on the timeline:

```javascript
function hideGroupById(id){
	timeline.setGroups( groups.get({ filter: function(item){ 
		return item.id != id; 
    } }) );
}

function showAllGroups(){
	timeline.setGroups( groups.get({ filter: function(item){ 
		return item; 
    } }) );
}
```

Here is a simple example: http://jsbin.com/susureqicu/edit?html,js,output

**Comment by hitmanmcc** [comment]
Thanks @mast0r, that was really helpful. You basically cut my code by a lot.
First I started with code that would change the visibility of the groups and items according to which ones I wanted to see or hide. I did this by changing their style property, then I switched to changing the display. However this still left me with a visual effect I did not want. Then I complicated even further, I was trying to remove stuff from the groups and items datasets, store them in separate datasets not used for rendering and, then I put them back when the affected category was chosen. As you can imagine this was becoming overly complex, when I could just basically have two lines of code.
That was ace mate, thanks. I don't know how I missed the setGroups function in the docs.
