### ISSUE TITLE
Timeline - Limit Range to stay within a background item

### ISSUE THREAD

**Issue by jbraun27** [almende/vis#1434]
I have an interesting problem, I have a timeline with a default type of "range" that has background items representing "Available times". When someone clicks on a background item, the range item that is created needs to be restricted to the start and end of the background item that they clicked. Has anyone considered this feature? Where would you look to implement such a feature?

**Comment by josdejong** [comment]
You can provide callbacks to limit items being created or edited:

http://visjs.org/docs/timeline/#Editing_Items
http://visjs.org/examples/timeline/editing/editingItemsCallbacks.html

**Comment by yotamberk** [comment]
@jbraun27 I'm closing this issue. If you still have a question, feel free to reopen this issue and and elaborate your issue.
