### ISSUE TITLE
HTML in hover title with links

### ISSUE THREAD

**Issue by dev408** [almende/vis#1435]
I am using the Network module and have a chart with several nodes.  Each node has it's own hover title with HTML specific to that node.  Within that popup I have a link to bring the user to another site.  The link is there per the HTML but because the popup/tooltip moves as the mouse moves over the node, it is difficult to click on the link.  Also if the popup is off the edge of the node, it is impossible to click the link.  Is there a way to stop the popup/tooltip from moving with the mouse and is there a way to delay the close so perhaps I could consistently click on the link?

**Comment by AlexDM0** [comment]
Hi,

Not really, though you can use the hover events to implement your own popup. You then have full control over them. 

Regards

**Comment by p1erce** [comment]
Hi, 

Just learned a lot from #952 and http://jsbin.com/neladaqimi/13/edit?html,output there.
Will be glad if that helps you.

**Comment by dev408** [comment]
This is exactly what I needed.  Thanks for pointing me to the example code - that  saved me a lot of time.
