### ISSUE TITLE
Network static legend

### ISSUE THREAD

**Issue by p1erce** [almende/vis#1436]
Hi, 

Any ideas for keeping legend (single node) static with enabling zoomIn/zoomOut interaction?
Have seen the example but it will zoomIn/Out together with other nodes.

What comes into my mind is to get the position the legend should be in DOM, transform into canvas position and put the legend node there. But size would still be a problem.

**Comment by AlexDM0** [comment]
How about using a second network for the legend with zoomable false and overlaying it in CSS?

Cheers

**Comment by p1erce** [comment]
╮(╯▽╰)╭  I'll take that as a compromise.
Similar with my thought about a second canvas.
Anyway, will try it. Thanks.
