### ISSUE TITLE
Visjs does not recognize fixing of nodes after drag & drop of a node

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#1437]
Hi guys,

I tested the dev branch today and dragging and dropping of nodes did not work as usual anymore. The nodes jump back to their original state after dragging them.

I found out that it works again if network.storePositions() is called before/ setting moved nodes to a fixed state. In visjs v4.9 it was not required to set node positions to the dataset, fixing worked regardless. Is this intentional?

For a demonstration see this bin and later uncomment `network.storePositions` in the `setNodesMoveable` function.

https://output.jsbin.com/sizayu

Otherwise, everything seems to work nice in v4.9.1-dev :)

Best wishes
-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

I'll look into it, thanks for letting us know!

Cheers

**Comment by AlexDM0** [comment]
@josdejong this seems to have something to do with the updates to the dataset? There is also a deprication message that should not be there. Could you look into this?

**Comment by josdejong** [comment]
Fixed in `develop`. See #1437 where we introduced this regression.

**Comment by felixhayashi** [comment]
Thanks @josdejong
