### ISSUE TITLE
Change network edge label programmatically - best practice?  

### ISSUE THREAD

**Issue by ccsandrew** [almende/vis#1439]
Thanks for your hard work.  I would like to dynamically change the copy text in a network edge's label on drag events.  After reading the documentation, the only way I see to do this is to find the edge in your initial data, manually re-assign the new label string, and then call network.setData() on the whole 'initial' data object.  

My questions is, is this best way to do this, or is there a more lightweight solution?  On issue #445 I see a reference to a dataset.update() method, but it doesn't appear to exist any longer in the version 4 documentation.

I forked a fiddle to demonstrate what I am doing: http://jsfiddle.net/zafcm4qh/2/

Note that I am using the click event there for simplicity.

**Comment by AlexDM0** [comment]
Hi,

Take a look a the DataSet. We also have an example on this:
http://visjs.org/examples/network/data/datasets.html

There are more examples but this seems like the best way to me :)

Additionally: 
http://visjs.org/docs/data/

Cheers

**Comment by ccsandrew** [comment]
Thank you Alex.  I hadn't realized that the dataset objects were available for use in the network API.
