### ISSUE TITLE
Timeline: default zoom level and zoom controls

### ISSUE THREAD

**Issue by gunjanthesystem** [almende/vis#144]
Hi,

Thanks for this useful library (Timeline). I have two questions/requests. (not sure if this is the right place to ask questions)

 I would like to set the default zoom level when the timeline is loaded. (I am loading the data for several months, I would like the default zoom to be 'hours of a given day')

Sincerely,

**Comment by ebinsleeba** [comment]
Hi,
Is there anyway to show current month on initial loading ?? and user could able to view previous months and upcoming months using zoom in and zoom out function . Is there any property to show the initial loading page as current month??

**Comment by bradh** [comment]
@ebinsleeba Couldn't you just set the required window / period using your code? This ticket is closed, so if you have a new feature request or bug, can you create a new ticket? If you just have a usage question, that would be better on stackexchange.
