### ISSUE TITLE
Can a Graph2d Share X-axis with TimeLine?

### ISSUE THREAD

**Issue by danuzclaudes** [almende/vis#1442]
![screenshot from 2015-11-17 12-06-19](https://cloud.githubusercontent.com/assets/8943359/11218588/d00d5544-8d23-11e5-9a28-9f348662d156.png)
Hi,
I'm wondering is it possible to make Graph2D and Timeline sharing the same horizontal axis of time? It might be similar to the issue [here](https://github.com/almende/vis/issues/385). And I've also attached my desired outcome fyi. Many thanks!

**Comment by AlexDM0** [comment]
Hi,

The solution is exactly the same as the issue you mention. Listen to the
range change events and sync them up!

Cheers

**Comment by danuzclaudes** [comment]
Hi, thank you for your reply. I used the code below to achieve the 'sync' effect between timeline and 2d chart. Thank you!
```
function onChange (range) {
    timeline.setOptions({
        start: range.start,
        end: range.end,
    });
}
```

**Comment by AlexDM0** [comment]
Hi,

While that is fine, the setWindow method is actually designed for that.

Cheers

**Comment by danuzclaudes** [comment]
@AlexDM0 
I tried the following method, but I found out that I really don't need a sliding effect for the timeline, i.e. I'd like to make both `rangechange` occur simultaneously...would `setWindow` have options to do so? Thanks.
```
  function onChange (range) {
    timeline.setWindow({
        start: range.start,
        end: range.end,
        // options: {duration: 0, easingFunction: 'linear',}
        options: {animation: false, },
    });
  }

```

**Comment by AlexDM0** [comment]
The animation false should make it instant. It's still sliding? I can't check at the moment since I'm on mobile. 

Cheers

**Comment by danuzclaudes** [comment]
yep..I set it false but it seems to be sliding on my side using Firefox.

**Comment by amnond** [comment]
Attached is a self contained example showing how to do this. It is based on combining various suggestions I found and some reverse engineering I did. I'm sure there's a better solution to some of the DOM/CSS hacks but at least it get the job done.
 
[htmlContents1.zip](https://github.com/almende/vis/files/672333/htmlContents1.zip)

Also, the issue of "WARNING: infinite loop in redraw?" in the console window appears when zooming on the graph2d window (and does not occur when zooming on the timeline window). I think this is a bug and will report it soon.

**Comment by mojoaxel** [comment]
@amnond Maybe jsbin.com is a better solution to provide code-examples. ZIP-Archives tend to be unsecure ;-)

**Comment by amnond** [comment]
My apologies... I just noticed that all emails from github were filtered
for some reason so I didn't see any of the emails that were sent to me, so
here are my very delayed answers:

Regarding the zip archive of the graph + timeline - you're right, I'll
create a sample on jsbin.com

As for the music map weekend project - sure, no objection at all to display
it on the showcase page, but I recently noticed it doesn't display well on
mobile phones so I'll fix that first.
