### ISSUE TITLE
overlapping nodes in case of long labels

### ISSUE THREAD

**Issue by benjaminaaron** [almende/vis#1446]
My node labels are three lines of up to 50 digits each. Is there an option I can use to make the hierarchical layout algorithm consider the node size (which adjusts automatically to surround the label) so as not to have overlapping nodes?
And a 2nd question; can I use formatting in the label like making some parts of it italic or bold?

**Comment by AlexDM0** [comment]
Hi,

Take a look at the HTML in nodes example for formatting. We only support linebreaks in the normal labels.

There is no support for size specific distances at this time.

Regards

**Comment by benjaminaaron** [comment]
Ok, thanks Alex.

**Comment by LLTommy** [comment]
I just want to add that it would be re really useful. I also struggle with overlapping nodes in the hierarchical layout, and as of now, there seems to be no way to solve this. I guess that many people run into this problem and it would be nice if you could put this on the todo list, if I am allowed to make this suggestion. 

Keep up the good work in the meantime.
