### ISSUE TITLE
how to generate an updated seed?

### ISSUE THREAD

**Issue by sickslives** [almende/vis#1447]
If I generate a network, `getSeed()` returns the seed from when it was originally generated, but continues to return the same value even if nodes are manually dragged around to new positions. 

Is it possible to retrieve the seed that will reproduce the network's current live state? Or is generating a user-designed layout only possible by getting and setting x and y positions on each individual node?

**Comment by AlexDM0** [comment]
Hi, the seed is only relevant for the initially generated layout. It has nothing to do with the user dragging positions. 

The only way to use that is indeed with keeping track of the x and y values. 

Regards
