### ISSUE TITLE
timeAxis step throws error

### ISSUE THREAD

**Issue by YiuriV** [almende/vis#1448]
Hi, I have this code:
var options = {
          width:  "100%",
          height: "250px",
          timeAxis: {
            scale: "year", 
            step: 25
          },
          step: 10,
          editable:false,
          showMajorLabels: true,
          showMinorLabels: true
        };
When running my site, the timeline displays correctly, but I do get an error message in my debugger:
Unknown option detected: "step" in 
options = {
  step
}
Perhaps it was misplaced? Matching option found at: 
options = {
  timeAxis: {
    step
  }
}
vis.js?12774097304482081554:10191 Errors have been found in the supplied options object.
Does anyone have a clue as to why I get this error?

**Comment by AlexDM0** [comment]
Hi, what is the version of vis.js you're using?

Regards

**Comment by YiuriV** [comment]
Version 4.9.0

**Comment by AlexDM0** [comment]
Ah I see:
```
var options = {
  width: "100%",
  height: "250px",
  timeAxis: {
    scale: "year", 
    step: 25
  },
  step: 10,  <-------------------------------- THE PROBLEM
  editable:false,
  showMajorLabels: true,
  showMinorLabels: true
};
```

That option there is not allowed. Though the step behaviour does something strange, we'll look into it.

Regards

**Comment by YiuriV** [comment]
Ah, stupid mistake by me :p, timeline now shows the correct steps, but it does indeed do strange things, e.g. when I zoom out it disappeares

**Comment by AlexDM0** [comment]
I've created an issue for this. It probably won't make it to todays release though..
