### ISSUE TITLE
Arrow heads are falsly displayed

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#1451]
Hi guys,

Visjs shows arrow heads even when arrows are not enabled in the edge styles. The edge style in the demo was created using the visjs configurator (which by the way shows the correct state, i.e. no selected arrow heads). 

Please see this demo: https://output.jsbin.com/limufu

Thanks
-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

The arrowhead is actually supposed to be shown based on your options. The configurator does not show it correctly. I'll fix that.

Regards

**Comment by AlexDM0** [comment]
Hi Felix,

Actually, looking at the code in my IDE, the configurator is only for global settings. If it wasn't, there would be no way to show if 1000 edges have different individual configurations. Globally, the arrows are off. You set the arrow on a single edge.

This is the correct behaviour.

Regards

**Comment by AlexDM0** [comment]
case in point: https://jsbin.com/yaziwu/1/edit?html,output

**Comment by felixhayashi** [comment]
Hi Alex,

thanks for your reply!

It must have been pretty late at night when I worte the issue description and created the bin that I completely messed up my point. Of course you are right here, the configurator is fine!! – I don't know why I included the argument with the configurator but my actual problem is that the edge displays an arrow head even though it is not initialised to do so (json). 

Please have a look at my (updated) example again: https://jsbin.com/limufu/edit?html,output

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

```
"from": {
          "scaleFactor": 1.4
        }
```
this automatically sets enabled to true. This is the case for all options in vis using an enabled field. The idea is that if you configure it, you probably want to use it and typing enabled true as well would be overkill.

Or am I still not understanding the issue?

Regards

**Comment by felixhayashi** [comment]
Hi Alex

> Or am I still not understanding the issue?

Well, on an edge level, you say that the mere presence of an object means that an arrow is enabled (in case `enabled` is not explicitly set to `false`).

```javascript
"from": {
  "scaleFactor": 1.4
}
```

So this will show an arrow head.

But the there is an inconsistency with the global configuration. Because the having the above set on a global level will not result in a display of an arrow.

Have a look again at your provided example https://jsbin.com/yaziwu/1/edit?html,output
Here you also assigned a the from arrow head object set…

```javascript
"from": {
  "scaleFactor": 1.4
}
```

… but it does not result in the display of a from arrow.

-Felix


https://jsbin.com/yaziwu/1/edit?html,output

**Comment by AlexDM0** [comment]
Hi Felix,

In the jsbin I do see a from arrow. It looks like it does what it should do. Maybe browser specific?

Regards

**Comment by felixhayashi** [comment]
Alex, sorry, I completely confused myself having multiple jsbins opened. Everything is fine! FALSE ALARM.

**Comment by AlexDM0** [comment]
;) no worries

cheers!
