### ISSUE TITLE
Javascript error in vis.js

### ISSUE THREAD

**Issue by ianm8** [almende/vis#1452]
Hi

I'm getting the following error with the attached file:
TypeError: D_matrix[edge.fromId] is undefined vis.js:41888:13

Removing the line with the "// ???" after it stops the error being generated.

Any help much appreciated.

Cheers, Ian
University of Tasmania

[vis_test.txt](https://github.com/almende/vis/files/41279/vis_test.txt)

**Comment by AlexDM0** [comment]
Hi,

This bug has been fixed in the develop branch and will probably be released this week. 

In the meantime, disable the improvedLayout. 

Cheers

**Comment by ianm8** [comment]
Hi Alex

That fixed it. Thanks so much!

Cheers, Ian

Ian Mitchell
Research Systems Manager
Research Performance and Analysis
Division of the Deputy Vice-Chancellor (Research)
University of Tasmania
Private Bag 1, Hobart, Tasmania, Australia 7001
03 6226 7457 | ecite.utas.edu.au<http://ecite.utas.edu.au/>
Point your iPhone @ tiny.cc/mecite
CRICOS Provider Code 00586B<http://www.utas.edu.au/cricos/>
