### ISSUE TITLE
Crossed edges in hierarchical layout

### ISSUE THREAD

**Issue by TrueFurby** [almende/vis#1453]
I am using vis to display nodes in hierarchical network. However when the number of nodes is higher, currently I have around 350 nodes, edges of nodes cross each other. To work around this I allowed moving nodes and saving positions, but the network can be displayed in different times in history in which some nodes can have different parent node, then the saved positions are not helpful.

Is there a way to improve this with config or at least without too much of user interaction?

**Config:**
```
var options = {
    layout: {
        hierarchical: {
            levelSeparation: 120,
            direction: "UD",
            sortMethod: "directed"
        }
    },
    edges: {
        smooth: {
            type: "cubicBezier",
            forceDirection: 'vertical',
            roundness: 0.25
        },
    },
    physics: {
        hierarchicalRepulsion: {
            springLength: 70,
            nodeDistance: 100
        },
        timestep: 0.40,
        stabilization: {
            enabled: true,
            iterations: 2000,
            updateInterval: 30,
            fit: false
        }
    }
};
```
**Preview:**

![network_view](https://cloud.githubusercontent.com/assets/1229233/11343980/0305cf72-920f-11e5-9359-bd1a55f1870c.png)

**Comment by TrueFurby** [comment]
Is there any more information I can provide to make finding suitable solution for my problem easier?

**Comment by AlexDM0** [comment]
Hi,

It seems to me that the saving of the positions is in fact the problem. Vis will make sure the lines are not crossed if you load the nodes and edges without positions. 

If you dynamically add nodes afterwards it can mess up the edges. 

Try removing all positions. If it is still crossed, make a jsbin.

Cheers

**Comment by TrueFurby** [comment]
What you see in screenshot is without loaded positions. I will make a jsbin and post it here.

**Comment by TrueFurby** [comment]
I simplified the example to the most essential data. https://jsbin.com/fovuqefifo/edit?js,output

**Comment by TrueFurby** [comment]
What are my options? Is there anything I am now doing incorrectly? Or something useful for this situation to set in config?

**Comment by AlexDM0** [comment]
Hi,

We're swamped at the moment. I'll take a look at the issue as soon as I have time. It could be that the upcoming release fixes your problem but I still have to test it. 

Regards

**Comment by TrueFurby** [comment]
Thank you for your response. I understand. Take your time.

**Comment by AlexDM0** [comment]
Hi,

Try it again with the new version of vis, with and without physics. I've updated the sorting algorithm.

Regards

**Comment by TrueFurby** [comment]
[Looks perfect!](https://jsbin.com/modutazaca/edit?js,output)  Thank you!

**Comment by TrueFurby** [comment]
Do you ignore predefined positions (x, y) for nodes? It seems that the network needs to stabilize even if I use specific positions, saved from last complete stabilization.

**Comment by AlexDM0** [comment]
At the moment these positions are only used for the ordering of the nodes.
They are not copied over. The new sorting algorithm is not supporting
stored positions, maybe thats something to look at in the future.

**Comment by TrueFurby** [comment]
Sorting is now okay but stabilization times increased a lot and without option to use stored positions I cannot make it faster. I tried disabling stabilization but nodes start far from each other and it takes some time to stabilize completely, I played around with some options to make this faster but sometimes the speed messed up node and they were crossed again.

**Comment by AlexDM0** [comment]
Try turning physics off. The layout should be good without physics now.

**Comment by TrueFurby** [comment]
Since the issue we are discussing now is not so related to the title, I created new issue for this.

https://github.com/almende/vis/issues/1536

**Comment by rlyle** [comment]
Yep, agree we are getting crossed edges in the hierarchical layout that we are fighting currently. We did try turning off physics, which doesn't help. We don't provide a position for our nodes either.
