### ISSUE TITLE
Handling 'keyup' of control key when multi-selecting

### ISSUE THREAD

**Issue by Blugh** [almende/vis#1454]
Hi guys

What would be the best way to change when the 'select' event fires while multi-selecting items. The reason I ask is because I need to do batch processing once the user has finished selecting all the items that they want processed.

The issue I currently have is that the 'select' event fires on each and every item select, and not after the user has released the ctrl key (which would act as confirming that this is their selection).

I have been fiddling around in the source code to try and find the best way (was thinking of emitting the key release, but have no idea how to detect the key release within the source code) to get the handling of the key release within the source code as I do not want it to be a quick hack.

Are there any suggestions you guys might have on your side? Any assistance will be appreciated.

**Comment by AlexDM0** [comment]
How about you try the keycharm module that is included with vis. It's the key binding module I made that is used in vis. 

Cheers

**Comment by Blugh** [comment]
Hi @AlexDM0 , thank you for the suggestion, I will give it a go.

**Comment by Blugh** [comment]
Ok, I have attempted this, but am struggling a lot with just getting keycharm to be included/accessible as part of the ItemSet module. Can anyone explain to me how this actually works?

I have done the following in the itemset module and timeline module (as is done with some other modules), but the keycharm function is always undefined, so i cannot instantiate it.

var keycharm = __webpack_require__(41);
if (this.keycharm !== undefined) {
        this.keycharm.destroy();
      }
      this.keycharm = keycharm();

"keycharm()" is always undefined :(

**Comment by AlexDM0** [comment]
I suggest you read the documentation for keycharm (https://github.com/AlexDM0/keycharm) and it is exposed in the vis object: vis.keycharm. You don't need to hack the code of vis for this.

**Comment by Blugh** [comment]
ah, ok, thank you, will give it another go

**Comment by Blugh** [comment]
@AlexDM0 , I need a bit of advice here, my js knowledge is not the greatest and I am also still trying to figure out how the vis library works as whole. 

Where would the best place be for me to add the ctrl key binding? I am currently trying to add this in the _create method of the ItemSet module, but it feels like a very ugly way of doing it. Currently it looks as follows at the bottom of _create:

vis.keycharm().bind('ctrl', this._afterItemsSelected, 'keyup');

the event fires as expected and I do receive the event paramter, however, the context of "this", is now different, and I can no longer emit my event "afterItemsSelected" due to this context change. 

Any ideas as to how I could fix this?

Apologies again, I am very new to this, so your help would be appreciated.

**Comment by AlexDM0** [comment]
Hi, I would suggest NOT putting this inside of any vis code. It will work anywhere. As for the this, read up on scoping, closures and binding.

In your case, this._afterItemsSelected.bind(this) should do the trick. Alternatively:
```
var me = this;
var keycharm = vis.keycharm();
keycharm.bind('ctrl', me._afterItemsSelected, 'keyup');
```

We're here to help out with issues around vis, not as a general purpose JS helpdesk :) I suggest you read all the documentation available for the parts of vis you are using. There should not be any need for you to go into the code of vis.

You can have as many instances of keycharm as you want, just remember you need to clean up after them as well.

Regards

**Comment by mojoaxel** [comment]
Closing because inactivity.
Feel free to reopen if this still is an issue.
