### ISSUE TITLE
Allow vertical swipe/drag to scroll page on touch devices in Timeline

### ISSUE THREAD

**Issue by mourogers** [almende/vis#1455]
If a timeline fills up the viewport on a touchscreen device, the user is unable to vertically scroll the page — they're effectively 'trapped' in place. Could there be a way to have horizontal gestures drag the timeline while vertical ones move the page? Thanks!

**Comment by josdejong** [comment]
The used touch library, hammer.js, allows handle drag events in either vertical or horizontal direction. There where some difficulties getting it working though. If anyone is interested into diving into this problem please let us know.

**Comment by henrye4** [comment]
Yes I'm too interested to enable vertical drag on IPad. My timeline is divided on several groups. On tablet users are not able to drag in vertical mode.

**Comment by josdejong** [comment]
This is fixed now in the `develop` branch.
