### ISSUE TITLE
Freeze a group (in addition to the panel)

### ISSUE THREAD

**Issue by elkouo** [almende/vis#1456]
Hi, first of all, congratulations for this amazing timeline.
I have a request which doesn't seem complicated but be very useful : can freeze a group.
When you define a heigth, the panel is frozen. Great. But, would it be possible to also freeze the first group ?
Thanks in advance.

**Comment by obattalov** [comment]
It would be fine to set the heights and freeze any/all of groups, so and items - not only the panel indeed. Thanks for Timeline.

**Comment by elkouo** [comment]
Thank you but ... that's not what I wanted to explain.
Imagine a first group with school vacation, just below the time axis inside a big timeline with a lot of groups. When you scroll down, the time axis is frozen (because height is defined) but not the group of school vacation. How to freeze it (as the time axis) so it doesn't disappear when I scrolled down ?

**Comment by josdejong** [comment]
There is no feature like this, but you could achieve something like it with the following trick:

- Create one Timeline having a time axis and the groups you want to "freeze".
- Create a second Timeline with the groups that can scroll vertically.
- Position the timelines on top of each other with no space in between
- Keep the visible window of the two timelines synchronized by adjusting the one when the other fires a `rangechange` event and vice versa.
- Maybe some CSS tweaking to let it look like a single Timeline.

**Comment by elkouo** [comment]
Thank you for this tip, it works fine.
Note that the fluidity is not perfect. But in my case, it's enough.
Thanks a lot.

**Comment by josdejong** [comment]
ok great!
