### ISSUE TITLE
Expand and Collapse Network Nodes

### ISSUE THREAD

**Issue by carlskii** [almende/vis#1457]
Hi,

I can't seem to work out how to expand/collapse the sub-nodes within a network graph. Is this possible ?

**Comment by AlexDM0** [comment]
Hi,

What you wanted sounds like clustering. There are a few examples on our website for this. Is that not it? If not, could you explain the difference?

Cheers

**Comment by carlskii** [comment]
This is sort of it. I just want to really set my level when the diagram first loads, then click on the lowest level nodes to expand them individually.

**Comment by AlexDM0** [comment]
You can take a look at the dataset example. It may also do what you want. Other than that, you give me very little to work with. What are you trying to do?
