### ISSUE TITLE
vis.js subgraph

### ISSUE THREAD

**Issue by cstancu** [almende/vis#1459]
Hi,

Is there a way to keep a cluster uncollapsed in vis.js? See this example of a subgraph/cluster in graphviz: http://www.graphviz.org/Gallery/directed/cluster.html. Basically what I need is to group nodes together and add a border with a label around them, but keep the nodes visible.

I also tried converting a cluster from .dot into vis.js with no success. It seems like the cluster properties are ignored. See the code bellow:
```javascript
    var DOTstring = 'digraph G { \
                subgraph cluster_0 \
                {\
                   style=filled; \
                    color=lightgrey; \
                    node [style=filled,color=lightblue]; \
                    1 -> 2 -> 3; \
                    label = "process #1"; \
                }\
                1 -> 2; \
                2 -> 3; \
                2 -- 4; \
                2 -> 1 }';

    var parsedData = vis.network.convertDot(DOTstring);

    var data = {
      nodes: parsedData.nodes,
      edges: parsedData.edges
    }

    var options = parsedData.options;

    // you can extend the options like a normal JSON variable:
    options.nodes = {
      color: 'red'
    }

    // initialize your network!
    var network = new vis.Network(container, data, options);
```

Thanks!

**Comment by cstancu** [comment]
After more digging I found other people asking for the same feature: https://github.com/almende/vis/issues/1201. Any further updates?

**Comment by AlexDM0** [comment]
Hi,

We do not support subgroups and are not likely to any time soon. The issue you referenced has all the relevant information. 

Regards
