### ISSUE TITLE
What might cause 

### ISSUE THREAD

**Issue by BimbleSS** [almende/vis#146]
Fisrt of all, let me say great library, thanks for making it avialable

I have a problem with timeline, when I integrate with Silverstrip content management system

The canvas of the draw area is larger than the container box, if I have a single row of items, then they are cut off and not visible. The only workaround I can find is setting height: 300px in options, but this leaves a lot of empty space above the first row.

I have tried messging around with css and html height sizes, but no success.

Any idea what might be causing this?

**Comment by shivareddy040** [comment]
![cutoff](https://cloud.githubusercontent.com/assets/15839114/11326870/effe937c-9142-11e5-9f59-e624000aa1bf.png)
 

MY box is cutting of . What would be the issue and what will be the solution . 
Thanks in advance

**Comment by josdejong** [comment]
@shivareddy040 please open a new issue if you want to discuss a different topic. Just to be sure: are you using the latest version of vis.js? The Timeline should nicely fit the contents by default, but you can always adjust the window using the method `setWindow`. I can't see from the screenshot what's happening, can you create a jsbin demonstrating this?

**Comment by shivareddy040** [comment]
I was able to fix the issue @josdejong . Thank s for your reply .
