### ISSUE TITLE
Stacking with subgroups workaround..?

### ISSUE THREAD

**Issue by mrmacmusic** [almende/vis#1460]
Hi – new here (be gentle!) and really only scratching the surface of vis but excited about its' potential!

I've integrated vis into my Filemaker database solution to display a nice timeline of event records (using a web viewer) and whilst I've got it working well, I've come across something I'd like to do but I'm not sure that I can... 

To explain, each event record in my database has 3 date ranges – the first is for logistics, the second is for crewing and the third the actual date range of the event itself. I therefore create 3 separate entries into the array for each record – logistics, crewing and working – each of which has the same subgroup and ID.

Using CSS classes I have adjusted the height and opacity of the range bars so that logistics is only 5px high resulting in a thinner line across the top of the date range, and both logistics and crewing are set to a low opacity which makes them distinguishable from the actual working dates of the event. With subgrouping, the 3 date range bars are layered one on top of each other and this is the look I'm after, however I can't then use stacking to remove the white space from the timeline.

I guess having the 'stack' feature work when using subgroups would solve my problem, however I wonder if I'm missing a workaround or another way to achieve what I'm after, i.e. stacking using the longest 'logistics' date range..?

Hopefully that makes sense and I'd appreciate any help or advice you can give!

**Comment by josdejong** [comment]
There isn't really a workaround, stacking with subgroups is just not supported as it is. You would have to do some hacking in the Timeline itself to implement support for it. Which is possible of course, it's an open source project after all and contributions are welcome :).

**Comment by yotamberk** [comment]
@mrmacmusic I'm closing this issue for now. If you are still interested in a feature of this sort, please open a new issue with the detailed feature =)
