### ISSUE TITLE
Legend Icon malformed if group.id is not sorted

### ISSUE THREAD

**Issue by Bernd0** [almende/vis#1461]
Hi,

since 4.9.0 I had a problem with the legend icons. The bug is only occurring if I specify a drawPoint style, i.e. 'circle' or 'square'. If then the group.id is not sorted in an ascending order, the icons are malformed.
For example:
`	var groups = new vis.DataSet([
		        		    		{ 
			        		    		options: {
			        						drawPoints: {
			        							style: "circle",
			        							styles: "stroke:#0000FF; stroke-width:2;fill:#0000FF"
			        						}
			        					}, 		
			        		    		style: "stroke:#0000FF",
			        		    		id: '1_data', 		
			        		    		content: 'Material 0815-0' 
				        		    },
		          		    		{	
			          		    		options: {
			          						drawPoints: {
			          							style: "square",	
			          							styles: "stroke:#FF0000; stroke-width:2;fill:#FF0000"
			          						}
			          					}, 		
			          		    		style: "stroke:#FF0000",
			          		    		id: '2_data',
			          		    		content: 'Material 0815-1'
				          		    }
		        					]);`
will work.

But 
`		var groups = new vis.DataSet([
		        		    		{ 
			        		    		options: {
			        						drawPoints: {
			        							style: "circle",
			        							styles: "stroke:#0000FF; stroke-width:2;fill:#0000FF"
			        						}
			        					}, 		
			        		    		style: "stroke:#0000FF",
			        		    		id: '2_data', 		
			        		    		content: 'Material 0815-0' 
				        		    },
		          		    		{	
			          		    		options: {
			          						drawPoints: {
			          							style: "square",	
			          							styles: "stroke:#FF0000; stroke-width:2;fill:#FF0000"
			          						}
			          					}, 		
			          		    		style: "stroke:#FF0000",
			          		    		id: '1_data',
			          		    		content: 'Material 0815-1'
				          		    }
		        					]);`

wont work. See id: '2_data'/'1_data'.

**Comment by Bernd0** [comment]
Code block added.

**Comment by AlexDM0** [comment]
Hi,

Could you make a jsbin to show this?

Regards

**Comment by Bernd0** [comment]
Correct legend:
http://jsbin.com/yotazeduxu/edit?html,output

Second legend item malformed:
http://jsbin.com/xegexeceze/edit?html,output

**Comment by AlexDM0** [comment]
Thanks for the jsbin. I've pushed a fix to develop.

It will be released tomorrow.

Cheers
