### ISSUE TITLE
Hierarchical layout node overlap

### ISSUE THREAD

**Issue by cstancu** [almende/vis#1462]
When using hierarchical layout nodes can overlap. Please see an example here:
http://jsfiddle.net/qeygw9qd/ 

The effect can of course be avoided by increasing the levelSeparation value, but that is a workaround which will not work in all cases. I suspect that the level separation is computed from the centre of the nodes on the level, and not from the edge of the bounding box. Is this a bug or the intended behaviour?

Thanks!

**Comment by AlexDM0** [comment]
Hi,

this is the intended behavior. 

Regards
