### ISSUE TITLE
Timeline: cancel item move event by pressing escape button

### ISSUE THREAD

**Issue by mast0r** [almende/vis#1465]
Once the user starts moving the item on the timeline it is impossible to cancel this process. I want to cancel the move it the user press escape button on the keyboard. I've tried to pass the callback from the `onMoving` function to the `keypup` event handler and do `callback(null)`, but it is not working. 

Any idea how to achieve this approach? 

Additionally I've tried to access the item that is moved like this:
`timeline.itemSet.touchParams.item`, but there is no `drag`event that could be cancelled...

**Comment by josdejong** [comment]
Would indeed be nice if pressing ESC while dragging an item would cancel the action. This feature is simply not implemented right now. 

A workaround could be to create a key listener for ESC the first time an `onMoving` event occurs, and clean up this listener in `onMove`. Then, you can keep track on whether ESC was pressed or not, and if so, cancel all further changes of the item being dragged.

**Comment by mast0r** [comment]
Thank you Jos for the idea, I will try it! I am just wondering if I could cause the `dragend` event on the item. So as I understand there is no "easy" way to cancel the drag :)

**Comment by josdejong** [comment]
The `onMove` event fires on `dragend`.

**Comment by yotamberk** [comment]
@mast0r the workaround sounds like a good solution. If you still think this feature should be implemented in the library itself, please feel free to open a new issue, or reopen this one =)
