### ISSUE TITLE
[Timeline] Customization of vis-dot (templates, events, styles)

### ISSUE THREAD

**Issue by brenoinojosa** [almende/vis#1466]
Hi,

Right now I'm applying custom CSS properties to "vis-dot"s, but I also need them to listen to click events and define a template for the dots (imagine I want to add a tooltip or have different dot styles). How can I achieve this? I need some way of inserting/replacing the html of the dots only.

Note: I don't want to do that via jQuery/.getElement since that's not recommended in Ember.

Thanks in advance,
Breno

**Comment by josdejong** [comment]
Did you have a look into providing a className to your items? and using that to style your items?

**Comment by brenoinojosa** [comment]
I did, but I'm actually trying to create an Ember component for that particular vis-dot so I can create actions like clicking and doing other stuff with it more than just styling.

My scenario is more like: I'd like to be able to provide a template for the "vis-dot" as a Handlebar (since that's what Ember uses to instantiate a component).

**Comment by josdejong** [comment]
Hm, yes and then the problem is that you can only specify a template for the *contents* of the item and not the item itself I suppose. 

What you can also look into is creating your own item type. You can take [PointItem](https://github.com/almende/vis/blob/master/lib/timeline/component/item/PointItem.js) as example, implement your own class (maybe just extend PointItem), and register it like:

```js
vis.timeline.components.ItemSet.types['mynewtype'] = ...
```

**Comment by brenoinojosa** [comment]
Can you provide more details? I've been trying to do that and yes, I was able to register it (since no errors were logged), but I can't get the redraw or show functions to be overridden. This is what I'm doing:

vis.timeline.components.ItemSet.types['mycustomitem'] = $.extend(vis.timeline.components.ItemSet.types.box, {
            redraw: function(){
                alert('calling redraw');
            },
            show: function(){
                alert('calling show');
            }
        });

**Comment by josdejong** [comment]
Sorry for the late reply.

I think `$.extend` doesn't work as `vis.timeline.components.ItemSet.types.box` is a constructor function with a prototype. You can do:

```js
var BoxItem = vis.timeline.components.ItemSet.types.box;

function MyCustomItem (data, conversion, options) {
  BoxItem.call(this, data, conversion, options);
}

MyCustomItem.prototype = new BoxItem (null, null, null);

MyCustomItem.prototype.redraw = function() {
  console.log('redraw...');
  BoxItem.prototype.redraw.call(this);
};

vis.timeline.components.ItemSet.types['mycustomitem'] = MyCustomItem;

```

**Comment by brenoinojosa** [comment]
No problem :+1: That indeed solved the issue. But it would be nice in the future to be able to provide templates for the dot, the line, etc.

Thanks! You can close this one now.
