### ISSUE TITLE
When css is not loaded error messages are not helpful

### ISSUE THREAD

**Issue by colek42** [almende/vis#1469]
Stupid mistake on my park, but after 6 hours I discovered the css was not loaded.  I was using graph2D in reactjs.  Received an error how the lines couldn't be displayed...nothing to do with css

**Comment by AlexDM0** [comment]
It would be helpful if we had anything to go on here. This sounds like browser or react. We have nothing along the lines of css messages in vis.

**Comment by colek42** [comment]
I'll add more detail later today
