### ISSUE TITLE
Change image on hover

### ISSUE THREAD

**Issue by ricnunes** [almende/vis#147]
Hello wonderful people! 

Yeah, its me again with another request... I've attatched the image again, so you know what I want easyer.

Is there any way that I could make the image of a node change on hover? The intended function is that when a node with a image is hovered, it would change to another bigger image ( see node 1 and node 3 for example).

Would love to provide you with a working link, but unfortunately that is impossible right now..

Thank you!!

![graph](https://cloud.githubusercontent.com/assets/2053111/3149455/95c53b60-ea6b-11e3-984e-72a9326e8b2f.jpg)

**Comment by lagarwal-ptc** [comment]
I am having difficulties make it work to change image of node on hover.
I have used groups for nodes to specify "selected" and "unselected" image. In addition, I also want to change image on mouse hover of node. For hover,  implemented functions like noHover and onHover as suggested above.

Debugging confirms the function is being invoked, however this.nodes.update(node) is having no effect at all. What could be wrong?

//network event handling
    network.on('hoverNode', (params) => {
      if (params && params.node) {
        this.onHover(this.nodes.get(params.node));
      }
    });

//function to perform action on hover event
  onHover(node) {
    node.image = "somegroup_highlighted.svg";
    **this.nodes.update(node);**    
  }

Options group definition sample:
SomeGroup: {
          shape: 'image',
          size: 12,
          image: {
            unselected: 'somegroup_unselected.svg',
            selected: 'somegroup_selected.svg',
          },          
        }

**Comment by insominx** [comment]
I also had to take this approach.  I believe the intention is for properties on the nodes to override those in the group but with this does not work for images.  I made separate groups with different images.
