### ISSUE TITLE
Timeline, make consecutive range appear on same line

### ISSUE THREAD

**Issue by Seiifer** [almende/vis#1474]
How can I make appear 2 items of type range on the same line ?

They are displayed on 2 different lines even if they don't overlap each other.

See here : http://jsfiddle.net/e7uodse2/513/

For the 2 first items P1 and P2, we don't see them on the same line unless we zoom in (a lot).

I would like to make them appear on the same line.
Make everything appear on the same line is also fine for me if there is simple solution for that.

**Comment by mast0r** [comment]
You should set the `stack` option to the `false`:

`
var options = {
    align: 'center',
    stack: false,
};
`

http://jsfiddle.net/e7uodse2/521/

**Comment by Seiifer** [comment]
Thanks mate, I didn't pay enough attention when reading the doc.
