### ISSUE TITLE
Vis network - Physics false - Node coordinate provided - lag between network draw and network event/action

### ISSUE THREAD

**Issue by bauddheya** [almende/vis#1477]
Hi,
I am creating a network of 500 nodes and 1500 edges with physics: false and providing coordinates for each node. I am doing this to make the network static, the moment it loads and no animation or movement of network is allowed while drawing the network. But dragNode is to be allowed on user input.

The issue is that the static network is visible instantly on fetching data, but all ations like dragNode, selectNode, selectEdge etc. donot function for a couple of minutes. Is there any work around where I can do all these actions as soon as network is visible?

Regards
Bauddheya

**Comment by AlexDM0** [comment]
Hi,

Can you make a JSBin to show this?

Regards

**Comment by bauddheya** [comment]
JSBIN will not be possible till tomorrow, but for the time being can you answer if physics: false does network stabilization without the animation being visible to the user? Or could you point in the direction what may be the possible causes for such a delay?(i asked for large networks because the lag reduces as the network becomes smaller and anything below 80 nodes has negligible lag)

**Comment by AlexDM0** [comment]
Hi,

physics:false should just disable physics. Example:
http://visjs.org/examples/network/edgeStyles/smoothWorldCup.html

No delays there.

The only reason for the delay would be if the physics module is not disabled on time. If it were to be disabled in the stabilization process you may ruin the redrawing. This would be a very weird place to do it though.

I'd need to be able to reproduce this in order to fix it.

Regards

**Comment by AlexDM0** [comment]
You can try this in search of a solution:

```
network.emit('_allowRedraw');
```

after that try dragging a node. I'm assuming network is var network = new vis.Network...

**Comment by AlexDM0** [comment]
to be very clear: even if this fixes the issue for you, it should never be required!

**Comment by bauddheya** [comment]
I am passing physics: false as an option before the network starts to draw because I have the coordinates of each node and I want it to be drawn at the provided coordinate. I am doing this so that the user is able to interact with the network as soon as it is visible (while if the physics is true then the network takes a little bit of time to settle down and for the user to acquaint themselves to the network and start interacting).

Yes that is how I am initializing the network. I will update you tomorrow if the fix works.

Regards
Bauddheya

**Comment by AlexDM0** [comment]
Hi,

Is this still an issue/

Regards

**Comment by bauddheya** [comment]
Hi,

No it is not an issue anymore. My apologies for the inconvenience, because it was never a vis issue, it was an implementation issue.
Thanks for looking into it.

Regards
Bauddheya Baliarsingh
