### ISSUE TITLE
Can I set a background image to a Network that moves with the network?

### ISSUE THREAD

**Issue by gdejong** [almende/vis#1479]
Is it possible to set a background image behind a VisJS Network that moves and scales accordingly to the diagram? I would use this to plot nodes onto a map. 
Using a CSS background does not accomplish my goal, also https://github.com/almende/vis/issues/1397 it not really what I am looking for.

Thanks!

**Comment by AlexDM0** [comment]
Hi,

Why is #1397 not what you are looking for? It does exactly what you want.

Vis is not meant for geographical data. If you want to use it still, good luck but render events is all we offer.

Cheers
