### ISSUE TITLE
Feature request: handle multiple properties for node

### ISSUE THREAD

**Issue by hnbeck** [almende/vis#1482]
When editing a node, vis.js / network should handle multiple properties for a node. By the pop up table, the user should be enabled to select which property to show, or change any values.
Rationale: many graph tools or graphdbs allow to use custom properties per node,

**Comment by AlexDM0** [comment]
Hi,

You can set any properties you want on the nodes, its just JSON. Only the global options are typechecked.

Changing values is what the vis DataSet is for.

Regards

**Comment by hnbeck** [comment]
Hi Alex, 
as far as I understand, vis.js can only show the "label".  If you edit a node with data manipluation option, then the popup also shows "label" as title of the input field. Or the other way around: is it really possible to set up the node such that (for example) "title" and "weight" can be shown both beside or in the node and that I can edit "title" and "weight" in the popup window shown if I clock "edit node" ?  Thats really not clear and has implications to my ECGraphEditor, where I have some lines of code to let the user map which property from a neo4j database can will be mapped to "label" of vis.js

**Comment by AlexDM0** [comment]
Hi,

I'm not sure what it is you're asking. If you click edit node you can construct any kind of popup you want. You are supplied with the full options object of that node in the callback. It's up to you to change what you want.

The example on the website only has label and ID, but thats just an example. 

Regards

**Comment by hnbeck** [comment]
Hi Alex, 

ok, know I can understand the thing related to the popup. I've seen some example code. What still is not clear to me is how vis.js handles properties for nodes. Example: I have a graph with nodes including 3 properties: Name, Cost and Complexity. As you indicated and I now understand I can create a popup for editing Name, Cost and Complexity in one Popup window. Cool. And do vis.js show all thee values beside the nodes, or do I have as a user to select which one to show ? 3 textlines beside every node may be harm the readability. Is the solution in this callback what you mentioned ?

**Comment by AlexDM0** [comment]
Hi,

The only thing shown is the label. Any other fields will only be stored in the node. Not shown unless you specifically get and show them. You can use the events to trigger popups to show more information. 

Regards

**Comment by hnbeck** [comment]
Ahhh :) thx !
