### ISSUE TITLE
Changing the color.highlight for nodes at network.selectNodes() does not work

### ISSUE THREAD

**Issue by wolfig** [almende/vis#1484]
Hi experts,

I have a network of something like 800 nodes. I pick a couple of them by filtering the corresponding IDs in a data set. Then I use the selectNodes(nodeIdArray) method to highlight these nodes. As the highlighing color does not fit my need I changed it in the global node options
```
  var options = {
	  interaction: {
		  hideEdgesOnDrag: true
	  },
	  nodes: {
		  shape: 'dot',
		  font: '24px arial black',
		  size: 30,
		  color:{
					highlight: '#FF0000'
			}
	  },
[..]
```
However, when I execute the selectNodes(nodeIdArray) method, only one of the selected nodes becomes (in this example) red, the others do get highlighted, but with the initial styling.
```
function highlightElementsWithTiming() {
		var nodesWithTiming = new vis.DataView(nodeDataSet,{
			fields: ['id'],
			filter: function(item) {
				return (item.accelZone);
			}
		});
		var idsWithTiming = nodesWithTiming.getIds();
		network.selectNodes(idsWithTiming);
	}
```
Any ideas?

Kind reagrds
WolfiG

**Comment by AlexDM0** [comment]
Hi,

Can you make a JSBin to show this?

Cheers

**Comment by wolfig** [comment]
Hi Alex,

I tried to make this work for a while, but I fear that I will not be able to get an example up and running at JSBin. Nevertheless I could send you the required files if you like

Regards
WolfiG

**Comment by AlexDM0** [comment]
Hi,

Im afraid I can't afford to debug your entire code. If I try it in our examples it just works. 

We'd have to be able to reproduce it publicly or we might be solving the same issue over and over. 

Regards

**Comment by wolfig** [comment]
OK, let's see what I can achieve in JSBin. I come back if I can create a sandbox there. I you like you can close this for now

Cheers
WolfiG

**Comment by wolfig** [comment]
Hi Alex,

finally I managed to get it running in JSBin. You can find my example at:
https://jsbin.com/galuti/

To see the symptom click in menu "Control System -> Highlight Nodes with Timing Info". Something like 100 nodes do have this attribute, but only one gets colored red according to JS line 65ff:

```
  var options = {
	  interaction: {
		  hideEdgesOnDrag: true
	  },
	  nodes: {
		  shape: 'dot',
		  font: '24px arial black',
		  size: 30,
		  color:{
					highlight: '#FF0000'
			}
	  },
```
The function calling the highlighting starts at line 144:
```
	function highlightElementsWithTiming() {
		var nodesWithTiming = new vis.DataView(nodeDataSet,{
			fields: ['id'],
			filter: function(item) {
				return (item.accelZone);
			}
		});
		var idsWithTiming = nodesWithTiming.getIds();
		network.selectNodes(idsWithTiming);
	}
```

**Comment by AlexDM0** [comment]
Hi,

It looks like the issue is with the nodes. Because you set 
```
 color: "#3366FF",
```
on a node, vis will use the STRING value instead of the OBJECT that is defined in the global. Basically, a fully defined color object is generated from your string value and overwrites the global option for that node.

If you were to write:
```
color: {background:'#3366FF'}
```
you would only overwrite the background field of the global options.

Regards

**Comment by AlexDM0** [comment]
by the way, if I turn off stabilization, there are a LOT of oscillations in your system. If I change the physics to this:
```
forceAtlas2Based: {
                gravitationalConstant: -0.3,
                centralGravity: 0,
                springConstant: 0.02,
                springLength: 100,
                damping: 0.025,
                avoidOverlap: 0.0
            },
            maxVelocity: 1200,
            minVelocity: 5,
            solver: 'forceAtlas2Based',
            stabilization: {
                enabled: true,
                iterations: 1000,
                updateInterval: 100,
                onlyDynamicEdges: false,
                fit: true
            },
            timestep: 1,
            adaptiveTimestep: true
```
it doubles the stabilization time.

Basically increase damping and maxVelocity and turn off avoid overlap (broken feature im afraid)

**Comment by AlexDM0** [comment]
errr I mean doubles the speed, not doubles the time. halves the time :)

**Comment by wolfig** [comment]
Thanks a lot Alex! I will have a look and come back as soon as I implemented your suggestion.Kind regardsWolfiG                                                                                                                                                                                                                Von: AlexGesendet: Freitag, 4. Dezember 2015 11:34An: almende/visAntwort an: almende/visCc: Wolfgang GeithnerBetreff: Re: [vis] Changing the color.highlight for nodes at network.selectNodes() does not work (#1484)errr I mean doubles the speed, not doubles the time. halves the time :)

—Reply to this email directly or view it on GitHub.

**Comment by wolfig** [comment]
I implemented the suggestions of Alex and it works fine. This case is closed for me.

Thanks again, WolfiG
