### ISSUE TITLE
Keep implicit item added order when zooming

### ISSUE THREAD

**Issue by ktre** [almende/vis#1485]
For timeline:
Without turning on explicit ordering (there's a warning not to do so if more than about 100 items), you can order things by being careful which items you add first.  However, if you then zoom in, so that some items disappear from the screen, and then zoom out, your implicit ordering is lost as those items are re-added.  

I'm not sure what performance effects this change may have, but if negligible, I think it would be nice to have.  Thanks.

**Comment by josdejong** [comment]
The performance issues with explicit ordering are huge. The warning in that example is there for a reason :). Anyway, it's an option that you can configure, so you can see for yourself whether the performance implications are acceptable or not for your particular use case.

**Comment by yotamberk** [comment]
@ktre Is this issue still relevant? Can we close it?

**Comment by ktre** [comment]
You can close it.

Thanks,
Joseph
