### ISSUE TITLE
dataset remove function

### ISSUE THREAD

**Issue by p1erce** [almende/vis#1487]
Hi,

About the function `DataSet.prototype._remove`. 
When I pass in an object like `{id: 0}`, the `var itemId = id[this._fieldId];` will get `0`, and `if (itemId && this._data[itemId])` will short circuit the condition and no longer remove this data. 
Maybe it should be `itemId !== undefined`? Or use `util.isNumber(id)` as above?

**Comment by josdejong** [comment]
Thanks, this should indeed be `itemId !== undefined`. Fixed in the `develop` branch.
