### ISSUE TITLE
Custom label on axis

### ISSUE THREAD

**Issue by khanshakeeb** [almende/vis#1489]
Hi all,

I wanted to change label on x axis, e.g currently it shows Day on x axis, I want to show day count instead of Day. Is it possible to override its default behavior?

Thanks

**Comment by josdejong** [comment]
Please check out the docs regarding configuration options `format` and `timeAxis`.

http://visjs.org/docs/timeline/

**Comment by yotamberk** [comment]
Format for the timeAxis will now accept a function (in the next release).
