### ISSUE TITLE
Timeline: minor add range bugs

### ISSUE THREAD

**Issue by oinkspoink** [almende/vis#1491]
Today, I found two minor bugs of the timeline in edit mode with range items:

1. If you add an item via double click, everything works fine. If you use dragging with ctrl, `DataView.filter` throws an error because `data` is null. 
Example: http://jsfiddle.net/yo5Lppb7/

2. If you set `snap: null`, dragging with ctrl throws an error, too.
Example: http://jsfiddle.net/djjfoyuf/

I don't need them to be fixed. It's just a report.

**Comment by josdejong** [comment]
Of course we want to fix it :). It's fixed in the `develop` branch now. Thanks for reporting!
