### ISSUE TITLE
How to reset the network's options to default?

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#1492]
Hi guys,

I cannot figure out how to reset the options of the network modules to their default state. I need this because Vis `network.setOptions` seems to always merge options, which prevents me from switching to other options because I cannot remove the previous ones…

With nodes and edges, setting properties to null resets them. Maybe this mechanism could also be applied to the network options? Something like

```javascript
  this.network.setOptions({
    nodes: null,
    edges: null,
    interaction: null,
    layout: null,
    manipulation: null,
    physics: null
  });
```

Thanks in advance
Felix

**Comment by AlexDM0** [comment]
Hi Felix, 

What would be the use case? I'd suggest storing positions and recreate the network. 

Cheers

**Comment by felixhayashi** [comment]
Hi Alex,

thanks for the response. The use case is that a user may load different graph options while otherwise everything stays the same.

> I'd suggest storing positions and recreate the network.

Yes, I also thought about removing the whole network instance but wanted to ask first whether there is a way to specifically reset options, as this appeared to me the most pragmatic thing to do.

Anyway, I followed your suggestion which works fine.
Thanks and have a great weekend.

-Felix
