### ISSUE TITLE
Adjust height

### ISSUE THREAD

**Issue by ogdans3** [almende/vis#1493]
Is it possible to adjust the height of a box, database or square element. Without affecting the width of the element?

If so, an example would be awesome. Or a reference to an example. 

Wasnt able to find documentation mentioning that, and all the examples didnt seem to have it.

Thanks!

**Comment by AlexDM0** [comment]
Hi,

No that is not possible. 

Regards

**Comment by ogdans3** [comment]
Any particular reason that makes it hard to achieve?

**Comment by AlexDM0** [comment]
There is nothing in the public API that will do this for you. It would have to be changed in the drawing code of the node types in question. 

Feel free to change the code to suit your needs.

**Comment by ogdans3** [comment]
Will do, thanks alot. 
Awesomly fast response time! Amazing library!
