### ISSUE TITLE
Nodes side by side

### ISSUE THREAD

**Issue by ogdans3** [almende/vis#1494]
Any way to place two sides side by side? Or lowering the distance between two nodes in the same level in the hierarchy? Either with physics enabled or disabled.

Thanks!

**Comment by AlexDM0** [comment]
Hi,

Not in the hierarchical layout. For normal layouts you can specify the exact coordinates of nodes. 

regards

**Comment by ogdans3** [comment]
Alright, then how/where is the x coordinate calculated for the node that is given in the draw function? Especially when the physics module is disabled

Thanks

**Comment by ogdans3** [comment]
Solved it by hacking together some code. 

Thanks
