### ISSUE TITLE
VIS Timeline pagging

### ISSUE THREAD

**Issue by waqas7803** [almende/vis#1497]
Hi,
Can anybody help me to setup paggin within VIS timeline plugin,

I am using group feature, and i have long list of groups so i would like to have pagging at the bottom of graph.

Is it something already available to achieve this ?

Thanks in advance.

Best Regards
waqas

**Comment by AlexDM0** [comment]
What is a pagging?

**Comment by waqas7803** [comment]
pagging means getting data from server on request , not loading all data once. kind of datatable functionality.

**Comment by waqas7803** [comment]
like loading 10 groups per page. how this is possible ?

**Comment by AlexDM0** [comment]
Ok, so you want all groups visible except they only get their data when they are in view?

First load all groups without their data. 

You'll have to write your own mouse listeners to determine when a group is dragged or scrolled into view. 

For each group that is in view do an Ajax call and get the relevant items. 

Then use the vis DataSet to update the timeline. 

On the other hand, if you just load all groups and their data in a time slot, you can use the events to get more data when the user requests to see it by dragging the timeline left or right. 

Regards

**Comment by waqas7803** [comment]
I am very sorry for my bad explanation.
What actually i would like to have is 
"UI controls for filtering the data, and/or for paginating the data"

So i just would like to load limited number of groups and thier data to browser, 
and would like to have ui controls to load more data (groups +  events).

So at a time user will see only limited number of groups and thier events.

Just like simple paging. But i would like to load data (groups and events)  from server with ajax request.

**Comment by AlexDM0** [comment]
Well you'd have to make UI controls using custom DOM elements, on user action make a nice query for your backend, make an Ajax call, put the new data into the dataset and you're done! 

This has not a lot to do with vis. The only vis relevant thing here is the usage of the dataset for dynamic data. There are multiple examples on this on our website. 

Regards

**Comment by waqas7803** [comment]
Thanks, 
May i ask another question here ?

Is it possible to have multiple levels of groups.
Like parent and child groups , but i need this will stack option enabled.

My data is like this

GroupA -> group1  => **** events of GroupA->group1 here ***
              -> group2 =>  ***** events GroupA->group2 here *****

GroupB -> group1  => **** events of GroupB->group1 here ***
              -> group2 =>  ***** events GroupB->group2 here *****

Thanks

**Comment by AlexDM0** [comment]
Not really, the subgroups could be used for this but if you want to use stacking that is not possible.

Regards
