### ISSUE TITLE
Smooth dashes don't work in IE9

### ISSUE THREAD

**Issue by Bethesthel** [almende/vis#1499]
There seams to be a problem with smooth dashed edges in a network in IE9. Smooth lines work fine, straight lines & dashes work fine, but the smooth-parameter is being ignored on dashes in Internet Explorer 9.

my config:
edges: {
  dashes: true,
  smooth: { type: 'continuous', enabled: true }
}

**Comment by AlexDM0** [comment]
Thats is all on IE9 not supporting ctx.setLineDash. There is nothing we can do here.

Regards
