### ISSUE TITLE
Restart

### ISSUE THREAD

**Issue by ogdans3** [almende/vis#1500]
Is there an easy way to "restart" the network? 
I can always load up the data again, but then it resets the zoom and position of the canvas, as it should. But can i just restart the network, reset all the colors and positions.
Or is there a way to reset the nodes and edges?

Thanks

**Comment by AlexDM0** [comment]
Hi,

You can set the values of options of individual nodes and edges to null to set them back to the global settings. 

Other then that, nope. You can of course save the positions and get the position and scale and use moveTo to set the view. 

Regards

**Comment by ogdans3** [comment]
Great that works nicely!

Thanks man
