### ISSUE TITLE
Setting edge color

### ISSUE THREAD

**Issue by ogdans3** [almende/vis#1502]
After using setOptions and redrawing the network the edge colors are not changing. 
Loggin the edge object it shows that the options.color has changed correctly.
If i forcefully do:
`edge.edgeType.color = color`
it will draw the edge black for some reason, even though the color is not black

Am I doing something wrong?

Thanks

**Comment by AlexDM0** [comment]
This is a bug that should be fixed in develop. Can you make a jsbin to show the issue? Never just use internals if you don't know what you're doing. 

Regards

**Comment by ogdans3** [comment]
First time using JSBin, but hope this helps:
http://output.jsbin.com/jotibolara

**Comment by AlexDM0** [comment]
Hi,

The problem here is that you go into the network object. You should never do this.
For dynamic data (including changing options of nodes or edges) we provide the vis dataset. 

I suggest you look into the examples on this to see how you can change options after loading.

Regards

**Comment by ogdans3** [comment]
Thanks
