### ISSUE TITLE
Time tooltip on item drag

### ISSUE THREAD

**Issue by Blugh** [almende/vis#1506]
Hi guys

I have added the following "tooltip" to display above an item when it is being dragged. It displays and updates the start and end time of the booking as the item is being dragged.

![image](https://cloud.githubusercontent.com/assets/9563949/11715616/fd1bdfbc-9f4b-11e5-8a48-b7322e002c59.png)

The background item is "linked" to the selected item and also moves as the selected item is dragged.

I am not sure if this kind of tooltip feature is already in the vis library. And if not, if you would like to have a look at my code and find a better and more efficient way to do it within the library?

Let me know.

**Comment by josdejong** [comment]
Hi, tooltips are not built-in in the Timeline. Would be a nice addition (should allow you to style your tooltips and contents of course). 

Sorry we don't really have time to look into your code but if it works it works, or not?

**Comment by Blugh** [comment]
It works. But i suspect there's probably a better and/or more efficient way to do it.

**Comment by mojoaxel** [comment]
@yotamberk Thanks for that cool new feature!
