### ISSUE TITLE
#Edges of selected Node

### ISSUE THREAD

**Issue by aamerb** [almende/vis#1511]
Dear Alex,
Good day:

Thank you very much for your effort and this amazing library,
I have a question for you :)
How can I get the array of edges that connected to the selected node?
Thanks for your support in advance!

Best Regards
Aamer

**Comment by AlexDM0** [comment]
Hi Aamer,

I'll give you a hint, take a look at the documentation:
http://visjs.org/docs/network/#methods

in the category: 
Methods to get information on nodes and edges.

It should be quite obvious by the name ;)

Cheers

**Comment by aamerb** [comment]
So there is no direct way to get an array of edges once the user click on the node isn't it?
I have to traverse the edges and looking of the id of the selected node and add it right?

**Comment by AlexDM0** [comment]
... no you get a node id with the select event and you can use the getConnectedEdges method to get the edgeIds of the connecting edges.

**Comment by aamerb** [comment]
Thank you very much.
