### ISSUE TITLE
Hierarchical layout not working as expected 

### ISSUE THREAD

**Issue by Almis90** [almende/vis#1512]
Check this http://jsfiddle.net/Almis/vxkx6ok4/ .. The line from a to c it's not visible until you starting moving them around, it's like going from a to b and from b to c. What I can do for this?

**Comment by AlexDM0** [comment]
Hi,

You can use smooth edges: 
http://jsfiddle.net/vxkx6ok4/2/

Regards

**Comment by Almis90** [comment]
The problem is that my data will be dynamic so I don't know when I need to use smooth edges and when not. Is there any other way?

**Comment by AlexDM0** [comment]
No, there isn't. You could set smooth edges globally obviously but that's about it. 

Regards
