### ISSUE TITLE
#Change the value of sub object of Edge

### ISSUE THREAD

**Issue by aamerb** [almende/vis#1513]
Dear Alex,
Good day:

How can I change the font size or the color of the edge? 
this is my code but it doesn't work properly  
```
	  for (var edgeId in allEdges) {
        allEdges[edgeId].color = 'rgba(0,225,225,0.75)';
        allEdges[edgeId].font.size = 20;
        
      }
```
the color is fine but the size of the font doesn't work 
Thank you for support in advance 

Best Regards
Aamer

**Comment by AlexDM0** [comment]
Hi, 

The code you have posted is not enough. Just a loop does not do anything. Are these settings? Is this a preprocessing step in the data?

I'd assume you know that 
```
font.size = 20
```
in the docs means:
```
font: {size:20}
```
when coding?

Take a look at our examples; it's what they are there for.

Regards

**Comment by aamerb** [comment]
I want to change the code in the function not just for one time 
I want to do it every time I call the function

**Comment by aamerb** [comment]
based on the docs 
http://visjs.org/docs/network/edges.html

that what i see
edge.font.size = 14
is that okay?

**Comment by AlexDM0** [comment]
.... Hi Sorry, did you read my reply? 

```
edge.font.size = 14
```
is written in javascript as:
```
edge:{font:{size:14}}
```
which will go into the options object or as the property of an edge.

If you want dynamic data, use the dataset. Take a look at our examples.

Regards

**Comment by aamerb** [comment]
Hi Alex,
in your code to change the color of the node you use this 
allNodes[allConnectedNodes[i]].color = 'rgba(150,150,150,0.75)';
I wonder if I can use the same logic to change the size font of the edge
thanks 
Best Regards
Aamer

**Comment by AlexDM0** [comment]
Hi,

That code by itself does not do anything. The reason it works in the example is because I have a list called allNodes that I get from the dataset, manipulate and update said dataset with it.

It would work fine for edges as well, you just have to follow the entire example, not just that line.

Regards

**Comment by aamerb** [comment]
Dear Alex,
I customize this example 
and I have a question how can I change the font color and size of the edge in this question 
could you help me 
here is the code 
 function neighbourhoodHighlight(params) {
    // if something is selected:
    if (params.nodes.length > 0) {
      highlightActive = true;
      var i,j;
      var selectedNode = params.nodes[0];
	  var selectedEdges = network.getConnectedEdges(selectedNode);

      var degrees = 2;

      // mark all nodes as hard to read.
      for (var nodeId in allNodes) {
        allNodes[nodeId].color = 'rgba(225,225,225,0.5)';
        if (allNodes[nodeId].hiddenLabel === undefined) {
          allNodes[nodeId].hiddenLabel = allNodes[nodeId].label;
          allNodes[nodeId].label = undefined;
        }
      }
	  
	  // mark all edges as hard to read.
	  for(var edgeId in allEdges)
	  {
		  allEdges[edgeId].color = 'rgba(225,225,225,0.5)';
		  if (allEdges[edgeId].hiddenLabel === undefined) {
			  
          allEdges[edgeId].hiddenLabel = allEdges[edgeId].label;
          allEdges[edgeId].label = undefined;
        }
	  }

      var connectedNodes = network.getConnectedNodes(selectedNode);
	  var connectedEdges = network.getConnectedEdges(selectedNode);
      var allConnectedNodes = connectedNodes;
 
      // get the second degree nodes
 

      // all second degree nodes get a different color and their label back
      for (i = 0; i < allConnectedNodes.length; i++) {
        allNodes[allConnectedNodes[i]].color = 'rgba(150,150,150,0.75)';
        if (allNodes[allConnectedNodes[i]].hiddenLabel !== undefined) {
          allNodes[allConnectedNodes[i]].label = allNodes[allConnectedNodes[i]].hiddenLabel;
          allNodes[allConnectedNodes[i]].hiddenLabel = undefined;
        }
      }
	  //
	  for (i=0; i<connectedEdges.length;i++)
	  {
		allEdges[connectedEdges[i]].color = 'rgba(50,50,50,0.75)';

        if (allEdges[connectedEdges[i]].hiddenLabel !== undefined) {
          allEdges[connectedEdges[i]].label = allEdges[connectedEdges[i]].hiddenLabel;
          allEdges[connectedEdges[i]].hiddenLabel = undefined;
        }

	  }
	  
      // all first degree nodes get their own color and their label back
      for (i = 0; i < connectedNodes.length; i++) {
        connectedNodes[i].color = 'rgba(250,150,150,0.75)';
        if (allNodes[connectedNodes[i]].hiddenLabel !== undefined) {
          allNodes[connectedNodes[i]].label = allNodes[connectedNodes[i]].hiddenLabel;
          allNodes[connectedNodes[i]].hiddenLabel = undefined;
        }
      }
	  //
	  
/*	  for (var j=0;j<connectedEdges.length;j++)
	  {
		  connectedEdges[j].color = 'rgba(255,255,0,0.75)';
		          if (allNodes[connectedEdges[j]].hiddenLabel !== undefined) {
          allNodes[connectedEdges[j]].label = allNodes[connectedEdges[j]].hiddenLabel;
          allNodes[connectedEdges[j]].hiddenLabel = undefined;
        }
		  }
*/
      // the main node gets its own color and its label back.
      allNodes[selectedNode].color = 'rgba(50,50,50,0.75)';
/*
	  var counter = 0;
	  for(var i=0;i<allEdges.length;i++)
	  {
		 if(allEdges[i].to == selectedNode.id || allEdges[i].from == selectedNode.id)
		 {
			 connectedEdges.add(allEdges[i]);
		 }
	  }
	  for(var conEdge in connectedEdges)
	  {
		   connectedEdges[i].color = 'rgba(0,255,0,0.75)';
	  }
	  */
      if (allNodes[selectedNode].hiddenLabel !== undefined) {
        allNodes[selectedNode].label = allNodes[selectedNode].hiddenLabel;
        allNodes[selectedNode].hiddenLabel = undefined;
      }
    }
    else if (highlightActive === true) {
      // reset all nodes
      for (var nodeId in allNodes) {
        allNodes[nodeId].color = 'rgba(225,225,225,0.75)';
        if (allNodes[nodeId].hiddenLabel !== undefined) {
          allNodes[nodeId].label = allNodes[nodeId].hiddenLabel;
          allNodes[nodeId].hiddenLabel = undefined;
        }
      }
	  //reset all edges
	  for (var edgeId in allEdges) {
        allEdges[edgeId].color.color = 'rgba(0,125,225,0.75)';
		var myfont = {font: {size:20,color:'red'}};
		//allEdges[edgeId].font = myfont;
        //allEdges[edgeId].font.color =  'rgba(0,225,0,0.75)';
        if (allEdges[edgeId].hiddenLabel !== undefined) {
          allEdges[edgeId].label = allEdges[edgeId].hiddenLabel;
          allEdges[edgeId].hiddenLabel = undefined;
        }
      }
      highlightActive = false
	  }

    // transform the object into an array
    var updateArray = [];
    for (nodeId in allNodes) {
      if (allNodes.hasOwnProperty(nodeId)) {
        updateArray.push(allNodes[nodeId]);
      }
    }
	//transform the object into an array of edges
	var updateArrayEdge = [];
	for (edgeId in allEdges)
	{
		if (allEdges.hasOwnProperty(edgeId)) {
        updateArrayEdge.push(allEdges[edgeId]);
      }

	}
    nodesDataset.update(updateArray);
	edgesDataset.update(updateArrayEdge);
  }

  redrawAll()

Best Regards
Aamer

**Comment by AlexDM0** [comment]
Hi Aamer,

I'm sorry, we're not here to debug your code for you. I'd suggest you start with an easier example and go from there. 

Regards,

Alex

**Comment by aamerb** [comment]
Don't worry 
Thank you Alex
