### ISSUE TITLE
browserify - Network.js parsing error

### ISSUE THREAD

**Issue by ann008** [almende/vis#1517]
$ browserify app.js -t /usr/local/lib/node_modules/babelify/ -o at.js
SyntaxError: Unexpected token (5:4) while parsing ~/node_modules/vis/lib/network/Network.js while parsing file: ~/node_modules/vis/lib/network/Network.js

**Comment by AlexDM0** [comment]
Hi. Isn't this the same as #1516?

**Comment by ann008** [comment]
Hi Alex, thanks for responding! It is not the same as #1516. It is about browserity and Network.js. DataSet is allright. The first 2 lines of app.js are:
var DataSet = require('vis/lib/DataSet');
var Network = require('vis/lib/network/Network');

Taking out babelify, when only running:
$ browserify app.js -o at.js
SyntaxError: Unexpected token (5:4) while parsing ~/node_modules/vis/lib/network/Network.js while parsing file: ~/node_modules/vis/lib/network/Network.js
    at DestroyableTransform.end [as _flush] (/usr/local/lib/node_modules/browserify/node_modules/insert-module-globals/index.js:96:21)
...

Many thanks!

**Comment by AlexDM0** [comment]
Try removing the node_modules folder and doing a npm install. 

> Taking out babelify, when only running:
You cant just take steps out of the build and expect it to work...

Regards

**Comment by AlexDM0** [comment]
is this still an issue?

**Comment by RubenVerborgh** [comment]
Can confirm an incomplete `npm install` causes this. `rm node_modules; npm install` indeed fixes this.

**Comment by ipavlic** [comment]
This still seems to be an issue. `rm -r node_modules; npm install` does not help.

**Comment by josdejong** [comment]
I have no time to dive into this, but this could be related to babel 6 requiring configuration to transform from ES6. Older versions of babel didn't need any config. We may need to update the docs on building with browserify.

**Comment by ipavlic** [comment]
Since Babel doesn't include default presets or configurations since version 6, I've added an `es2015` preset. This got me to line `events.js:154` which threw `Cannot find module './lib/network/Network' from /Users/foo/bar/vis-custom`.

**Comment by ipavlic** [comment]
Okay, I got it. I needed to run the script in the directory where `vis` was built. This seems to work when run with node:

```
var fs = require("fs");
var browserify = require("browserify");
browserify("./custom-build.js")
  .transform("babelify", {presets: ["es2015"]})
  .bundle()
  .pipe(fs.createWriteStream("vis-custom-4.16.js"));
```

**Comment by mmcnl** [comment]
I can confirm this is still an issue; `rm -r node_modules; npm install` did not help.

```
~/dev/vis ❯ browserify custom.js -t babelify -o vis-custom.js -s vis
SyntaxError: Unexpected token (5:4) while parsing /Users/matt/dev/vis/lib/network/Network.js while parsing file: /Users/matt/dev/vis/lib/network/Network.js
    at DestroyableTransform.end [as _flush] (/usr/local/lib/node_modules/browserify/node_modules/insert-module-globals/index.js:96:21)
    at DestroyableTransform.<anonymous> (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at prefinish (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:503:12)
    at finishMaybe (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:511:7)
    at endWritable (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:523:3)
    at DestroyableTransform.Writable.end (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:493:41)
    at Babelify.onend (_stream_readable.js:511:10)
```

and running @ipavlic's code in node produced an empty output file:
```
> var fs = require("fs");
undefined
> var browserify = require("browserify");
undefined
> browserify("./custom.js").transform("babelify", {presets: ["es2015"]}).bundle().pipe(fs.createWriteStream("vis-custom-4.16.js"));
WriteStream {
  _writableState:
   WritableState {
     objectMode: false,
     highWaterMark: 16384,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     decodeStrings: true,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: true,
     bufferProcessing: false,
     onwrite: [Function],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: false,
     errorEmitted: false,
     bufferedRequestCount: 0,
     corkedRequestsFree: CorkedRequest { next: null, entry: null, finish: [Function] } },
  writable: true,
  domain:
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  _events:
   { finish: [ [Object], [Object] ],
     unpipe: [Function: onunpipe],
     drain: [Function],
     error: [Function: onerror],
     close: { [Function: g] listener: [Function: onclose] } },
  _eventsCount: 5,
  _maxListeners: undefined,
  path: 'vis-custom-4.16.js',
  fd: null,
  flags: 'w',
  mode: 438,
  start: undefined,
  autoClose: true,
  pos: undefined,
  bytesWritten: 0 }
```

**Comment by Tooa** [comment]
Have you tested this against the latest version on the `develop` branch?

**Comment by mmcnl** [comment]
Thanks for the tip, @Tooa, using the develop branch did work. However, the process resulted in files that were larger than the files I found in the master branch `dist` folder:
```
-rw-r--r--   1 matt staff 1.1M Jan  8 09:12 vis-custom.js
-rw-r--r--   1 matt staff 618K Jan  8 09:13 vis-custom.min.js
```
vs
```
-rw-r--r-- 1 matt staff 403K Jan  8 09:16 vis-network.min.js
-rw-r--r-- 1 matt staff 1.6M Jan  8 09:16 vis.js
-rw-r--r-- 1 matt staff 621K Jan  8 09:16 vis.min.js
```

```
// custom.js
exports.DataSet = require('./lib/DataSet');
exports.Timeline = require('./lib/network/Network.js');
```

**Comment by Tooa** [comment]
Why should they match? Our `develop` branch is the latest edge version. Once it is stable enough we merge it with master and release. This approach is based on [this](http://nvie.com/posts/a-successful-git-branching-model/) model. Maybe I got you wrong.

**Comment by mmcnl** [comment]
I wouldn't expect them to match exactly, but as my goal was to use the smallest js file possible, the `vis-network.min.js` file already included in the `dist` folder of `master` branch is about 30% smaller than the custom build I was able to make. I'm not sure if that indicates that I was doing something wrong in my build process or just that there is more code in the `develop` branch. In any case, I send many thanks to you and your team for providing this excellent tool!

**Comment by mojoaxel** [comment]
@Tooa wie should kewp an eye in the site. Maybw @mmcnl is right and something is wrong. New issue?

**Comment by mojoaxel** [comment]
I had a look on the file-sizes again. I see no significant change comparing `master` to `develop`.  I also created a simple custom.js as descriped in the [Example 1](https://github.com/almende/vis/blob/develop/README.md#examples-of-custom-builds). I see no unexpected file-sizes there.
