### ISSUE TITLE
Timeline: build an older version

### ISSUE THREAD

**Issue by mast0r** [almende/vis#1518]
Hi, is it possible to build an older version of the timeline? I need the version 4.7.0, and the current one is 4.10.0

Many thanks!

**Comment by AlexDM0** [comment]
Welcome to the wonderful world of github:
https://github.com/almende/vis/tree/955dd25caa276560513c96178a3aad5d313952c6

Regards

**Comment by mast0r** [comment]
Ohhyee, you are right, I've got it! :) Thanks!
