### ISSUE TITLE
Fixed header when scrolling

### ISSUE THREAD

**Issue by unsafecode** [almende/vis#152]
It would be nice to have the timeline header (years/months/dates) to stay fixed and allow overflow scrolling

**Comment by pergamino** [comment]
Is there a JavaScript event to detect vertical scroll on the timeline?

**Comment by peterheard01** [comment]
The link to the example for vertical scrolling is dead. Can you supply another one? Can't see in the documentation how to get vertical scrolling.....Also is it possible to use the browser vertical scrolling?

**Comment by easleydp** [comment]
josdejong commented on 19 Jun 2014:
> Yes, we want to add a vertical scrollbar on the right for a better visual clue.

Is this still on the cards? Currently there is no visual cue to alert the user that some items may be out of view.

**Comment by yotamberk** [comment]
I think what youre taking is a new feature requested. Please open a new issue so we can address this @easleydp

**Comment by easleydp** [comment]
OK, see #2438
