### ISSUE TITLE
How can i add label to group column

### ISSUE THREAD

**Issue by waqas7803** [almende/vis#1520]
I would like to add a label to group column, how can i do that ?
![labeltogroup](https://cloud.githubusercontent.com/assets/7470144/11845966/b1b8a4e0-a416-11e5-8a33-ce9598b4e7a9.png)

**Comment by josdejong** [comment]
I'm not sure how you exactly did the columns in the left panel, but this whole thing is no build in functionality of the vis.js Timeline, so I guess you have to be creative yourself.

**Comment by waqas7803** [comment]
i did those columns with "groupTemplate" option. So i think we should i have feature to set template of group label (means red marked area in above image).

Thanks

**Comment by josdejong** [comment]
Ah, ok. Yeah, maybe we could add some option to put text in the top left area. It's also easy to do yourself: you can just create a relatively positioned div to the container div which lays on top of the timeline, top left, and add your text there.

**Comment by mast0r** [comment]
I've done exactly what Jos has proposed.
I assign a new layer programmatically to the timeline after it was fully loaded:

```javascript
var layer = '<div id="backgroundLayer">Column label</div>';
$('.vis-timeline').first().prepend(layer);
```

And the style for the layer is:

```css
#backgroundLayer {
    width: 200px;
    display: block;
    background-color: green;
    height: 100%;
}
```

**Comment by josdejong** [comment]
Thanks for sharing your solution!
