### ISSUE TITLE
stack issue when we scroll 

### ISSUE THREAD

**Issue by waqas7803** [almende/vis#1522]
Hi,
i have noticed that stack of events get lost when i drag timeline to very left or very right where i see no events and when drag back then events are no more stacked.
this also is case with forllowing demo example
http://visjs.org/examples/timeline/groups/groupsOrdering.html

I am attaching screen shot when it lost stacking of events.

![stack_issue](https://cloud.githubusercontent.com/assets/7470144/11864986/404ba664-a4a1-11e5-9fcc-cae287e272b8.png)

To reproduce it please drag your events area to left or right where you see no events and then back.

**Comment by josdejong** [comment]
Thanks for reporting this, I can reproduce it.

**Comment by yotamberk** [comment]
@waqas7803 Is this issue still relevant? It seems to be fine now.
