### ISSUE TITLE
Fade in and Fade out animation while adding or removing a node

### ISSUE THREAD

**Issue by lakstap** [almende/vis#1526]
Is it possible to have fade in and fade out animation, while adding a node.

**Comment by felixhayashi** [comment]
I think yes. You can adjust the opacity of all colors (background, border, font). If you use images you cannot control the opacity as far as I know (except font awesome icons which relate to the background color). So maybe you could add an interval that updates node color properties (rgba) from 0 to 1. Just an idea, haven't tested this…

**Comment by AlexDM0** [comment]
Felix is right, that is the only way. It should work but the performance in large networks can be a problem for a smooth animation. There is nothing we can do about that though.

Regards
