### ISSUE TITLE
Timeline with empty data - TypeError: range.min is null

### ISSUE THREAD

**Issue by thorstenfleischmann** [almende/vis#1527]
I initialize the timeline with an empty item set and update it after some user actions.

With the recent distribution I get "TypeError: range.min is null" vis.js (row 10495, column 8)

http://jsfiddle.net/a08r4hLn/4/

**Comment by josdejong** [comment]
Thanks for reporting this, this regression was introduced by fixing #1523 and it's only in the latest version (4.11.0). I've fixed it in the develop branch.
