### ISSUE TITLE
4.1 to 4.11 / network

### ISSUE THREAD

**Issue by ppithon** [almende/vis#1528]
Hi,
In 4.1 it's ok...but...
If I try 4.11, I have this error on method dataset.update :
"Ignoring input item, which is not an object at index0"

I use visjs in gwt 2.7 :

public native String updateNodes(String json)/*-{
  console.log("----update----->"+json);
  $wnd.datasetnodes.update(eval('(' + json + ')'));
}-*/;

console :
----update----->[{id: 6271614324834304, label: 'm', group:'grouptext'}]

Problem parse object json with eval ???  or instanceof objet in your code ?

**Comment by AlexDM0** [comment]
Hi,

I don't suppose you can reproduce this in plain js? A JSBin would be great! Why would you use eval? JSON.parse would be much more appropriate.

Regards

**Comment by ppithon** [comment]
Hi,

I found : in 4.11 update method don't work for create new item... (I must use 'add') normal ?

another problem : 
I want to use method storePositions but after this, when I call dataset.get()

**Comment by ppithon** [comment]
Hi,

I found : in 4.11 update method don't work for create new item... (I must use 'add') normal ?

another problem : 
I want to use method storePositions but after this, when I call dataset.get()
id value is a String and not number ! normal ?
example result dataset.get() :
{"id":"6359575255056384", "label":"s", "group":"grouptext", "x":475, "y":469}
normally , the ID should be number without the quotes : {"id":6359575255056384, .... }

I love this application ... long life to visjs !

Regards,
Philippe

**Comment by ppithon** [comment]
Hi,
I use visjs div in center DockLayoutPanel GWT component 
(for visjs css div : width:100% and height:100%)
In v4.11 the position of viewport isn't correct (it's ok in v4.1)
after 2 hours I can't reproduct this problem in plain js...
have you change a concept between 4.1 and 4.11 ????

Regards,
Philippe

**Comment by ppithon** [comment]
Hi,
More information for problem viewport position in gwt : it's ok on v4.3.0 and not in 4.4.0

Regards, 
Philippe

**Comment by AlexDM0** [comment]
Hi,

We're not officially supporting GWT. I have no idea what could cause your issues. Since 4.1, yes there have been many changes but none breaking unless you're working with code other than the public API. As for the stringified Id's, @josdejong do you know something about this?

If you cannot reproduce your problems in normal JS, I cannot help you, sorry..

Regards

**Comment by AlexDM0** [comment]
Did you also update your CSS file to 4.11?

**Comment by ppithon** [comment]
I found a solution in gwt... if I call "fit" method (after add node) the viewport position is correct in 4.11

**Comment by ppithon** [comment]
Hi,
I return to my first problem : If I try 4.11, I have this error on method dataset.update:

If I update this Array :
[{id: 6337585022500864, label: 'xxxxx', group:'grouptext'}]
error : "Ignoring input item, which is not an object at index0"

in line 5499 vis.js, data[i] appears not to be "instanceof Object"
strange because the first element is an object {}
if I remove this test ... the update works

ideas ?

--- 5499 :
 for (var i = 0, len = data.length; i < len; i++) {
        if (data[i] instanceof Object) {
          addOrUpdate(data[i]);
        } else {
              console.warn("Ignoring input item, which is not an object at index" + i + " : " + data[i]);
        }
      }

**Comment by AlexDM0** [comment]
Hi,

What does the print say in the warning if you run it? Try it again like this:

> console.warn("Ignoring input item, which is not an object at index",i,data[i]);
> 

Regards

**Comment by ppithon** [comment]
Hi,
Ignoring input item, which is not an object at index0

**Comment by AlexDM0** [comment]
So there is NO data. The entire thing is empty. Again, if you cannot reproduce this in plain JS we cannot help you. Do not modify the internals of vis to solve your problem, it will only cause issues later on.

You cannot "update" an array. You need to pass it into the dataset. Do you have any JS code that shows the issue?

Regards

**Comment by ppithon** [comment]
in vis.js, I print data[i] -> [object Object]
console.warn("Ignoring input item, which is not an object at index" + i + " : " + data[i]);

console :
Ignoring input item, which is not an object at index0 : [object Object]

Regards

**Comment by AlexDM0** [comment]
Which is why I asked you to print it like this:
console.warn("Ignoring input item, which is not an object at index",i,data[i]);

**Comment by ppithon** [comment]
ok :
Ignoring input item, which is not an object at index 0 Object {id: 6337585022500864, label: "q...", group: "grouptext"}

**Comment by AlexDM0** [comment]
try console.warn("Ignoring input item, which is not an object at index",i,data[i], typeof data[i], data[i].constructor);

**Comment by ppithon** [comment]
Ignoring input item, which is not an object at index 0 Object {id: 6337585022500864, label: "q...", group: "grouptext"} object Object() { [native code] }

**Comment by AlexDM0** [comment]
So it is an object. In other words, (data[i] instanceof Object)  is fine. What do you use to run this code? Browser? Any polyfils or libraries that change native structures?

**Comment by ppithon** [comment]
$wnd.datasetnodes.update(json); -> it run in JSNI native method GWT : http://www.gwtproject.org/doc/latest/DevGuideCodingBasicsJSNI.html

**Comment by AlexDM0** [comment]
Sorry, I'm not going to debug GWT. There is nothing wrong with the line you pointed out as shown by the prints you've posted. The problem is somewhere else and I cannot help you, sorry. We do not support GWT or test against it in our releases, nor do we plan on.

Regards

**Comment by ppithon** [comment]
I have 3 solutions :
- wait... with my vis.js 4.11 modification (ok not good)
- test GWT 2.8 beta 1 (I use GWT 2.7)
- abandon GWT and switch to polymer google

Regards

**Comment by AlexDM0** [comment]
Hi,

1 - Your modifications are not ensured of a secure solution and will break with future releases.
2 - Always ok to test
3 - Seems like a good choice, gwt is often causing issues

Regards

**Comment by ppithon** [comment]
problem : 
I want to use method storePositions but after this, when I call dataset.get()
id value is a String and not number ! normal ?

example :

   network.storePositions();
  
   console.log(nodes.get());

**Comment by ppithon** [comment]
example :
http://jsbin.com/humure/edit?html

**Comment by AlexDM0** [comment]
As I've said:

> As for the stringified Id's, @josdejong do you know something about this?

I don't know, maybe Jos knows?

Regards

**Comment by josdejong** [comment]
@AlexDM0 the id's should indeed not be changed to strings. This does not occur in the DataSet itself but in `storePositions` which updates the items with stringified id's. Alex can you have a look into that?

Here a demo: http://jsbin.com/xuwayit/edit?html,console

@ppithon If you're looking into alternatives to GWT I can recommend you to look at react [React](https://facebook.github.io/react/) too.

**Comment by AlexDM0** [comment]
Right, my bad, sorry. It's addressed. Will be added to the next release.

**Comment by ppithon** [comment]
ok thanks
