### ISSUE TITLE
How can we show/hide all edges after the network is drawn? 

### ISSUE THREAD

**Issue by probaner** [almende/vis#1529]
I want to show/hide all edges when user clicks outside the diagram. This is achievable. I am fetching all the edges and applying: " this.body.edges[myEdge].options.hidden=true/false;"

But when I am using cluster there is issue. Because, after hiding when I am showing the edges again, it makes the edges of nodes in cluster (I am talking about the nodes that constitutes the cluster not the cluster itself) visible. So it looks like edges without nodes as the cluster is yet to open.

Is there any simple way to handle this. Remember I have multiple two-nodes-clusters.

**Comment by AlexDM0** [comment]
Hi,

Stay away from this.body.... these are internals and are not documented nor meant for public use. If you want to update options after initalization, that is what the dataset is used for.

That said, you're right, the opening of clusters forces the hidden flag back on. At the moment there is no check for this. We should add this check in the future. Thanks for the heads up!

Regards

**Comment by AlexDM0** [comment]
You could try setting the color of all edges to rgba(0,0,0,0) to make them invisible but not "hidden". Maybe that fixes your problem? 

Still, edges created for clusters cannot be updated with this..
