### ISSUE TITLE
Background events wrong repositionY when subgroup

### ISSUE THREAD

**Issue by nothor84** [almende/vis#1530]
The Y position of the Events with type 'background' when they are inside subgroups is not correctly calculated. Only it's correct if they are in the first row.
In this example, http://visjs.org/examples/timeline/groups/subgroups.html you can see that the background items are OK, but if you switch the group position 'foo' to 'bar', then the background items (only them) have a wrong Y position. 
![wrongpositiony](https://cloud.githubusercontent.com/assets/16415053/11978312/d2731638-a98a-11e5-8695-37222dfcf6ef.jpg)

It becames worst when the group position is in the lower part of the calendar.

The error is in the following function "BackgroundItem.prototype.repositionY" from "vis.js"

I don't know how to solve it but maybe for next release can be solved.

**Comment by nothor84** [comment]
Well, I have tried to fix it, and for "Orientation = Top" the position is ok if you set var newTop = 0, instead of "this.parent.top"
var newTop = this.parent.top; --> var newTop = 0;

It should be checked but looks better now.

**Comment by yotamberk** [comment]
fixed with #2519
