### ISSUE TITLE
Arrow positions on network

### ISSUE THREAD

**Issue by dev408** [almende/vis#1531]
When the arrows are drawn using arrows:to, the arrows are not always at the end of the line close to the node.  Sometimes they are in the middle of the line.  I created this jsFiddle so you can see an example.

http://jsfiddle.net/fkjj65ya/4/

It may have something to do with the gravity but I have a complex diagram that seems to work best with the configuration I have here.  Is this a bug or is there some way to fix it so they are always close to the node.

**Comment by AlexDM0** [comment]
Hi,

I think images (and circular ones) have rectangular bounding boxes. I'll check it out. 

Cheers

**Comment by felixhayashi** [comment]
My problem is often the other way round, edges are hidden beneath the node objects.

-Felix

![2015-12-23 18 45 35](https://cloud.githubusercontent.com/assets/4307137/11981734/8cdfcf06-a9a5-11e5-99fe-3d955e44a6f0.png)

**Comment by AlexDM0** [comment]
Good point, the radius of the boxes increases its boundary from the normal size. We'll have to take that into  account too.

**Comment by felixhayashi** [comment]
:) Thanks Alex!

**Comment by dev408** [comment]
I also noticed an issue with the labels - If the image is rectangular rather than square, the label is pushed farther down/away from the image than if the image is square.  I updated the JSFiddle to show an example of this.  See Andrea del Sarto in my example.

**Comment by AlexDM0** [comment]
That is because edges go to the center of the node. I'm not sure that will be addressed in future versions. It's much cheaper to do it this way than it is to get the borders all the time.

**Comment by dev408** [comment]
Alex, Is there something I can do to the nodes to make this more consistent in regard to the arrow positions?  Shape, size?

**Comment by dev408** [comment]
Alex, looks like you have fixed this issue with the arrows - Great and thanks.  Do you know when you will release it?   Just trying to determine if I should take your changes as they are or wait for a full release?

**Comment by AlexDM0** [comment]
Hi,

Probably friday

Regards
