### ISSUE TITLE
Dynamically changing edge color in a SIR model

### ISSUE THREAD

**Issue by DGaffney** [almende/vis#1532]
Hey! I'm just getting started with the vis library - it looks great. I am trying to run a SIR epidemiology model on the network, and I've figured out I can change the color of the node while running the model like so: 

```javascript
function updateNode(node_id, state, initial){
	if (state == "infected"){
		initial.net.findNode(node_id)[0].setOptions({color: 'red'})
		initial.statuses[node_id] = "infected"
		initial.net.redraw()		
	} else if (state == "recovered") {
		initial.net.findNode(node_id)[0].setOptions({color: 'green'})
		initial.statuses[node_id] = "recovered"
		initial.net.redraw()		
	}
}

```

And then, calling something like updateNode(16, "infected", initial) would make that node "infected" and the node would now be red. initial is just an object which contains the net along with some other glboal properties for the model. Is there a similar setup for changing the color of the edges connected to node 16? I've been digging around for a while and so far can't figure something out - I can obviously set the colors initially, but I need to change them often while the simulation runs. Thanks in advance for any pointers!

**Comment by AlexDM0** [comment]
Hi,

The way you set your node color should not be possible and it will be removed in the next update. 

You have to use the dataset for dynamic updates. Checkout all our examples on it on the website. 

Regards

**Comment by DGaffney** [comment]
Thanks for getting back to me - which example walks through data manipulation in the context of networks? I saw the demos talking about the DataSet object, but I couldn't quite figure out how to wed it with the network examples...

**Comment by AlexDM0** [comment]
http://visjs.org/examples/network/data/datasets.html

I'd assume "dataset for dynamic data" would cover this area?

**Comment by DGaffney** [comment]
Awesome, that looks like exactly what I need after checking out the source - when I can update this thing to act in not the soon-to-be-deprecated way I'll update it - very excited about this library as an alternative to some cases where I'd use Sigma. It looks great!
