### ISSUE TITLE
Multiple self loops rendering problem

### ISSUE THREAD

**Issue by KristianKarl** [almende/vis#1533]
Hi,

Thanks for a great graph library!

I have an issue, where I have multiple self loop edges. Multiple self loops are rendered upon each other, making it very hard to see them in a rendered graph.

I created an example on jsfiddle: https://jsfiddle.net/kristiankarl/x3w8et2m/4/

Is there anything one can do, configure, to solve this issue? Did I miss something?

Best Kristian

**Comment by AlexDM0** [comment]
Hi Kristian,

It is not possible to have multiple self referencing arrows and not having them overlap. 

Sorry

**Comment by KristianKarl** [comment]
Ok, thanks.

**Comment by AlexDM0** [comment]
Hi,

Sorry, my bad. There is the option selfReferenceSize in http://visjs.org/docs/network/edges.html that you can give to selfreferencing edges. If you set this manually (or by preprocessing step) you can make multiple self referencing edges with different radii.

Regards

**Comment by KristianKarl** [comment]
Ah, I see. 
Thanks for the fast reply.
