### ISSUE TITLE
Fixing header to page

### ISSUE THREAD

**Issue by swesley** [almende/vis#1534]
It's great the library fixes headers now (issue 152), but for us it's halfway there.

Because it's difficult to customise the headers, I added a purpose built row to include some numbers for the month.
Large timelines are painful to scroll vertically, so our users prefer large HTML page they can scroll with, however this of course negates the built in fixed headers.
![image](https://cloud.githubusercontent.com/assets/1445323/12028409/0e48863a-ae12-11e5-81f0-01d27ee25b4c.png)
I've been exploring code to float either the original header or my content on the page, allowing for scrolling, but my CSS is not that strong. 
Any pointers, ideas, suggestions?

**Comment by josdejong** [comment]
You will probably need both JS and CSS adjustments. The TimeAxis is displayed in the top panel. You could try to attach the top panel to your page in some fixed location on the top instead of this top panel.

https://github.com/almende/vis/blob/master/lib/timeline/Core.js#L79

**Comment by swesley** [comment]
Thank you. I worked a solution, info on [stackoverflow](http://stackoverflow.com/questions/34503476/fix-header-on-vis-js-timeline-to-page/34602185#34602185)

**Comment by josdejong** [comment]
Cool, thanks for sharing!
