### ISSUE TITLE
Network: Exporting to other format...

### ISSUE THREAD

**Issue by dragonzone** [almende/vis#1535]
I didn't forget the project that started it all. 

Anyway, good news. One of our customer requirement was to have the pretty vis.js drawing to be exported to PDF. I've been looking at PhantomJS and a variety of other PDF JS generator and still didn't come up with any good solution. All running into all kinds of issues. But finally, I've been playing graphviz (http://graphviz.org) and it's seems to be the perfect solution. With GraphViz, you are able to export vis.js (nodes/edges) and convert them to DOT and it will convert them to a variety of format (e.g. PDF, svg, png, jpg, gif, etc.). You can get the full list from here: http://www.graphviz.org/doc/info/output.html.

With our particular network that is being exported, it needs to support node (with images), edges (with colors) and with the same exact x-y coordinate. So GraphViz was the one project that did it for it and it can tightly integrate with vis.js. I've tried export to over 3000 nodes and it still works perfectly (though the size of the PDF is super large, ~130M), but actual printing size is 10 ft. x 10 ft. :D.

So, as a heads up, if you user who are looking to export to a variety of format, you can refer them to GraphViz.

**Comment by AlexDM0** [comment]
Hi Dragon, 

Noted, thanks!

Happy holidays
