### ISSUE TITLE
Network: hierarchical layout node positioning algorithm

### ISSUE THREAD

**Issue by TrueFurby** [almende/vis#1536]
My problem is that with *physics disabled*, initial node positions are not very optimal for my kind of data, since the nodes can stretch very wide. User has to zoom and scroll too much and it's harder to provide overview of entire network.

![no_physics](https://cloud.githubusercontent.com/assets/1229233/12043812/12b73384-ae89-11e5-98e2-e6b2088d377b.png)

Here it looks pretty optimal and it's easy for user the see whole network at once, even though some information is lost probably by putting the nodes so close to each other.

![long_stabilization](https://cloud.githubusercontent.com/assets/1229233/12043824/260dc330-ae89-11e5-9d87-e2388716bedb.png)

However it took over **95 seconds** to stabilize. I tried to increase some of the *physics options* to speed this up but it resulted in messing up the edges.

I think something in between would be perfect for my use case. Maybe some **further algorithm optimization** could be done by **removing some of the empty space** when neighbor nodes don't collide on the same level and **putting child nodes with fewer children straight under parent** since there are currently many parents with empty space straight under them.

Here's few examples of what I mean:

![optimization_suggestions](https://cloud.githubusercontent.com/assets/1229233/12044001/f0137e3a-ae8a-11e5-9ac2-06f122ef4ce6.png)

[JSBin](https://output.jsbin.com/sinalucoma/1) with sample of my data and *physics disabled*.

**Comment by AlexDM0** [comment]
Hi,

We'll see what we can do :)

Cheers

**Comment by AlexDM0** [comment]
Hi,

I've pushed an updated version to develop, give it a shot and see if it works for you.

Regards

**Comment by AlexDM0** [comment]
Hi, 

I have added a few options to customize the layout of the network if you do not use physics. The whitespace has been nicely condensed and it is very fast.

It will be added to the next release.

Regards

**Comment by felixhayashi** [comment]
> I have added a few options to customize the layout of the network if you do not use physics.

:+1:

**Comment by AlexDM0** [comment]
With the new update, your network will draw in 300ms instead of 95 seconds :)

Regards

**Comment by TrueFurby** [comment]
Amazing work!

My final use going from this
![network_old](https://cloud.githubusercontent.com/assets/1229233/12414659/3920c9ae-be97-11e5-8f18-047123eb705b.png)
to this
![network_new](https://cloud.githubusercontent.com/assets/1229233/12414662/3cc4f5c6-be97-11e5-99eb-150a53e785bb.png)
Much much better!  Thank you very much for help with this.

**Comment by TrueFurby** [comment]
Actually, I've noticed some of the nodes.. without any child nodes to be positioned after nodes with children, causing them to be sometimes confused which parent they really have. I haven't studied your code so I don't know how hard it would be to adjust these nodes.

Here's what I mean:
![network_change](https://cloud.githubusercontent.com/assets/1229233/12414898/d9bfc0d0-be98-11e5-85bb-55ddc2d457a1.png)
As you can see for some of them it's little hard to tell who's their parent because of the very long edges which touch neighboring nodes.

**Comment by AlexDM0** [comment]
Hi,

I cant really see anything in your picture, I dont suppose you can make the edges a bit clearer? One thing my algorithm does not do is interchange nodes. If one is to the left or right of an other, it will not pass it (crossed edges and all that). The order can be defined by giving them an initial position. The initial position will be used for the ordering of the nodes so x = 4 will be to the left of x = 5.

**Comment by TrueFurby** [comment]
I've replaced the picture in the previous post with clearer one.

So I guess I could add some logic to set *x* position of the nodes which don't have child nodes to be zero and others to be less or more than 0.

**Comment by AlexDM0** [comment]
For now, yes. Maybe in future iterations this will be an option for the positioning?

**Comment by TrueFurby** [comment]
Alright, sounds good to me. Still the optimization you've done made it much neater. Thanks!
