### ISSUE TITLE
Trouble/fix for overflow of item text

### ISSUE THREAD

**Issue by netrc** [almende/vis#1538]
Couldn't get text overflow visible to work as per the example

.vis-item .vis-item-overflow { overflow: visible; }

Looking at the code (search for vis-item-range)

.vis-item-range .vis-item-overflow { overflow: visible; } 

worked.

**Comment by josdejong** [comment]
Thanks for reporting this. The example here seems to work just fine though: http://visjs.org/examples/timeline/items/rangeOverflowItem.html

How can I reproduce your issue?

**Comment by yotamberk** [comment]
@netrc is this still a relevant problem?
