### ISSUE TITLE
vis is not defined with requirejs

### ISSUE THREAD

**Issue by admhemed** [almende/vis#1539]
I'm using requirejs and I can't get visjs to load.
I found only one hack to go around,
I change this code 
```javascript
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
        define([], factory);      
	else if(typeof exports === 'object')
		exports["vis"] = factory();
	else
		root["vis"] = factory();
```
to this
```javascript
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
//      define([], factory);      
        root["vis"] = factory();
	else if(typeof exports === 'object')
		exports["vis"] = factory();
	else
		root["vis"] = factory();
```
now it loads fine
But I don't think this is a good solution, 
what do you think?

**Comment by josdejong** [comment]
There is a require.js example here: 

https://github.com/almende/vis/tree/master/examples/timeline/other/requirejs

**Comment by maslick** [comment]
@josdejong I am having the same issue. I admit the require.js example works just fine. But:

I am using requirejs together with angular: ``angular.bootstrap(document, ['demo'])``. And normally we have libraries like d3, ace, etc. in the global namespace. 
When I try to load vis in the same way, it's not present in the global namespace. It works, however, with the fix by @admhemed 
What can you advise to get it work? Perhaps, some shim declarations for vis are missing in my setup?
Thanks.

**Comment by rapitkan** [comment]
@ligadata-alaa Hi! Have you made a pull request about one line your fix? I used the fix and it really works. Thank you.

**Comment by mojoaxel** [comment]
The code [mentioned above](/almende/vis/issues/1539#issue-124557509) is generated by webpack and not part of the vis.js sources. You should not change this! If you have further problems integrating vis.js with require.js please check the [given example](/almende/vis/tree/master/examples/timeline/other/requirejs) or create a new issue.
