### ISSUE TITLE
Question: Callback when vis graphic finishes loading?

### ISSUE THREAD

**Issue by aquadisco** [almende/vis#1540]
Reading through the documentation, I don't see a way to be notified when the graphic finishes loading.  Is there a way to know when the Graph2d or timeline processes are done?

**Comment by AlexDM0** [comment]
Hi,

It's synchronous. The line below the execution should be executed after its finished. 

Regards

**Comment by aquadisco** [comment]
okay, thanks.  maybe what i'm seeing is related to #1541 then?

**Comment by josdejong** [comment]
Yes I think so. Well, at least there is an easy workaround for it until we have fixed it.

**Comment by ludost** [comment]
Since finishing #1592 this is now provided, the "changed" event. The rendering may now be asynchronous without issue.

**Comment by marlosin** [comment]
@aquadisco what I've done for now as workaround for the Timeline is override the _redraw like this:

```js
vis.Timeline.prototype._redraw = function() {
  vis.timeline.Core.prototype._redraw.call(this);
  this.emit('changed');
};
```
