### ISSUE TITLE
Timeline (and others?) do not load synchronously

### ISSUE THREAD

**Issue by josdejong** [almende/vis#1541]
At least the Timeline and Graph2d visualizations should load synchronously, but this is not actually the case. The Timeline is loaded but the items on the Timeline are only loaded on the next tick, i.e:

```js
var timeline = new vis.Timeline(...);
      
alert('The Timeline is visible but the items not yet (this is a bug)');

setTimeout(function () {
  alert('Now everything is loaded!');
}, 0);
```

Here is a jsbin demonstrating the issue: http://jsbin.com/ceresa/edit?html,output

**Comment by ludost** [comment]
With fixing issue #1592, (and #1540) I propose to not consider this a bug.

**Comment by josdejong** [comment]
I marked this a bug because before, things *did* load synchronously and now it *doesn't* and there is no solution for it in the latest released version (except for a workaround). There are two solutions for this bug: introduce an `onload` event like you propose, or fix things so they *do* load synchronous again. 

The `changed` event could be used as an `onload` event, though you need to be careful that this event can trigger multiple times, it's not a "real" one-off `onload` event. It feels a bit like using a side effect, I would prefer an explicit event for it if we go that route.

To keep things simple though I prefer loading synchronously as it was before, and I've [fixed the code](https://github.com/almende/vis/commit/f171328c10dd56f281b8c7e699bc56b968da6c7e) so Timeline/Graph2d do load synchronous again. So there is no need for an `onload` event :)

**Comment by schwaerz** [comment]
Just found this issue. I upgraded to vis 4.21 yesterday. Today I realized that it won't load synchronously. Tried to use the change event as a workaround but this didn't work.
The only thing that worked was the workaround mentioned on top of this page:
```js
setTimeout(function () {
  alert('Now everything is loaded!');
}, 0);
```
Am I missing something or is it again loading asynchronously?

**Comment by s7726** [comment]
Same

**Comment by Viky-zhang** [comment]
why not render in current tick ?
