### ISSUE TITLE
DEPRECATED METHOD warning

### ISSUE THREAD

**Issue by AlexDM0** [almende/vis#1543]
DEPRECATED METHOD: extend
Use `assign`. AT 
 Function.extend (http://localhost:63350/vis/dist/vis.js:11302:19)
propagating (http://localhost:63350/vis/dist/vis.js:11054:16)
Object.__WEBPACK_AMD_DEFINE_ARRAY__ (http://localhost:63350/vis/dist/vis.js:10985:22)
__webpack_require__ (http://localhost:63350/vis/dist/vis.js:57:30)
{anonymous}()@http://localhost:63350/vis/dist/vis.js:10444:16)
__webpack_require__ (http://localhost:63350/vis/dist/vis.js:57:30)
{anonymous}()@http://localhost:63350/vis/dist/vis.js:107:22)
__webpack_require__ (http://localhost:63350/vis/dist/vis.js:57:30)
http://localhost:63350/vis/dist/vis.js:80:10

**Comment by AlexDM0** [comment]
Could you take a look at this Jos?

**Comment by josdejong** [comment]
How can I reproduce this issue?

**Comment by josdejong** [comment]
This should be fixed now in `develop`.

**Comment by josdejong** [comment]
Cause: hammer.js 2.0.6 has deprecated the method `Hammer.extend` (replaced with `Hammer.assign`), which was used by `propagating-hammerjs`.
