### ISSUE TITLE
DataSet feature request - Rename id

### ISSUE THREAD

**Issue by michaelelrom** [almende/vis#1548]
Hello,

I am trying to rename nodes entirely in the nodes dataset.  Can you add a rename method to the dataset so I can rename an id?

Thank you,

Mike

**Comment by josdejong** [comment]
The id of an item is the thing that uniquely identifies an item. It should never change. If you want to "change" the id, you can just remove the old item and create a new item.

**Comment by michaelelrom** [comment]
I agree with the importance of the id which I why I thought this would make a good internal method.  To change id is to build a new node with the same properties, update the edges, and remove the old node.  I can create this myself, but it would be nice to have this wrapped up in a vis dataset method.  

Thank you for your prompt attention. 

Regards,

Mike

**Comment by josdejong** [comment]
We will not implement methods for this in the DataSet itself as it's generally not a good idea to change ids. But you can indeed easily create such a method yourself if you really need it.

**Comment by michaelelrom** [comment]
Thank you for your review.  Best regards

**Comment by valtih1978** [comment]
I do not see how to change labels of the graph. Can you give a reference?

**Comment by valtih1978** [comment]
Ok, I have found the answer, https://github.com/almende/vis/issues/774#issuecomment-93724042
