### ISSUE TITLE
Initial Network Graph Render Has Incorrect Zoom Level

### ISSUE THREAD

**Issue by dmitri-bazz** [almende/vis#1549]
So the first time I render a Network Graph, it has a zoom level of 1 and the nodes aren't fitted (parameter is set to true). When I render a different graph, by clearing the element containing the "vis-network" element and then creating a new instance of the graph. It works fine. If I go back and do the same thing to initial graph, it works fine and has a zoom level of 0.13 and all the nodes fit within the viewport.

I have tried setting an event to fire off when stabilization is finished to manually call the fit function and pass it the ids of all the nodes in the graph, this seems to have no effect.

I have created a temporary workaround by calling the .fit function on a beforeDrawing event. Then unbinding the event (by the way, there is no documentation on how to unbind events, I merely guessed that .off() might work).

Oh, if it makes any difference. The graph's element has a CSS display value of none, when it is first being generated. 

These are the relevant vis options I'm using.
```
              layout: {
                    hierarchical: {
                        sortMethod: 'directed',
                    }
                },
                edges: {
                    smooth: {
                        type: 'vertical',
                        roundness: 1
                    },
                    arrows: {to : true }
                },
                nodes:{
                    mass:2,
                    shapeProperties: {
                        useImageSize: true
                    }
                },
                 interaction: {
                    dragNodes: false,
                    hover: true
                },
                physics: {
                    enabled: true,
                    hierarchicalRepulsion: {
                        nodeDistance: 200,
                        centralGravity: 0.1
                    },
                    stabilization: {
                        fit: true
                    }
                }
```

**Comment by AlexDM0** [comment]
Hi,

Can you reproduce this in a jsbin?

regards
