### ISSUE TITLE
Items Above and Below the Timeline

### ISSUE THREAD

**Issue by danielzmsutter** [almende/vis#1550]
Hi, to start, I want to say thank you for this library and I will contribute and recommend it when possible.
I was trying to find a way to place the items below and above the timeline being able to discriminate or specifically select which elements to place above and which elements below. I attach a picture as a sample, if this is not posible I consider that a possible feature to develop.

![timeline](https://cloud.githubusercontent.com/assets/16313655/12134652/f496b906-b3f6-11e5-8a4e-a8a7274c0ed5.png)

Regards.

**Comment by josdejong** [comment]
Thanks. This layout isn't supported right now but it would be cool to have it, thanks for your suggestion.

**Comment by AlexDM0** [comment]
You can do this with two timelines stacked on top of eachother. Then use the events to sync them. There are some issues on this including solutions on here if you search a bit.

Regards

**Comment by danielzmsutter** [comment]
Thanks @AlexDM0 , how can I make the timeline to display elements below and not above?

**Comment by AlexDM0** [comment]
http://visjs.org/examples/timeline/styling/axisOrientation.html

Like this example

**Comment by danielzmsutter** [comment]
@AlexDM0 thanks I'm working on it, looks like is what I need.

**Comment by danielzmsutter** [comment]
@AlexDM0 with some research and work, it just worked, thanks again.

![timeline](https://cloud.githubusercontent.com/assets/16313655/12323411/a5dc642e-ba80-11e5-8b93-0fc76ca289ce.gif)

**Comment by nk23** [comment]
@danielzmsutter Hi is this layout of items above and beyond timeline is available in the library now?

**Comment by yotamberk** [comment]
@nk23 Nope. But it seems to work with two syced timelines as shown above. Does this not fit your needs?

**Comment by mojoaxel** [comment]
@danielzmsutter Please consider publishing your example code (e.g. on jsbin or as pull-request). Sometimes people search for that kind of layout and it would be a nice contribution to open source!
