### ISSUE TITLE
Reduce timeline's height

### ISSUE THREAD

**Issue by Seiifer** [almende/vis#1553]
I'm trying to make the timeline's height smaller but I'm struggling to find which css properties to edit.

More specificallly, I tried to reduce the size of the line linking an item box to the bottom of the timeline.

Any clue on what css properties I should edit ?
And also what other css properties can I edit in order to make the timeline's height smaller ? (font size, padding/margin etc...)

**Comment by thorstenfleischmann** [comment]
You can change the height with the configuration options
http://visjs.org/docs/timeline/#Configuration_Options

Option "height" defines the height of the whole timeline. 
With the option "margin.axis" you can change the margin between the items and the time axis.
With the option "margin.item.vertical" you can change the margin between items

**Comment by Seiifer** [comment]
Thanks ! It looks like the `margin` option is doing what I want.

However, I can't use the `margin.axis` or  any other 'sub'-options of `margin`.

The only one usable in the options JSON is margin, or is there a special syntax to use ?

I'm doing as following :
```js
var timeLineOptions = {
  align: 'center',
  stack: false,
  selectable: false,
  // syntax issue
  // margin.axis: 10
  margin: 10
};

controllerScope.timeline = new vis.Timeline(document.getElementById('timeLineContainer'), dataItems, groups, timeLineOptions);
```

Also, is it possible to easily change the size of the point on the bottom of the timeline ?

**Comment by Seiifer** [comment]
Thanks !

Also, is there an easy way to change the point's size on the bottom of the timeline ?

**Comment by josdejong** [comment]
You can change all of that with CSS
