### ISSUE TITLE
Question: disabling physics for some nodes?

### ISSUE THREAD

**Issue by bb-play** [almende/vis#1555]
n my application, a graph is loaded initially with the one-net of a particular node. The user can expand the graph by double-clicking any node to add its one-net.

The problem is that every time the user does that, the nodes all jump around, so it's confusing. I don't want to just disable physics, because then the new nodes get jumbled on top of the old ones. For lack of a better explanation, I want to freeze the existing nodes, only using physics to arrange the new nodes (and then freeze them before adding more). I looked at Stop vis.js physics after nodes load but allow drag-able nodes, but that doesn't solve my problem.

I'm pretty clueless about what the various options to the physics solving algorithms mean, and can't find a good description anywhere, so I wonder if there may be tweaks there that would help me.

Thanks!

**Comment by AlexDM0** [comment]
Hi,

It sounds like you'll have to use the dataset to update the existing nodes, setting fixed to true for them. Then load the new nodes. 

Regards

**Comment by bb-play** [comment]
I tried that, and it just stuck the new nodes on top of the old ones, making a horrific mess.  I would like the user to be able to move nodes, too, ideally.

**Comment by AlexDM0** [comment]
Did you fix them or did you disable their physics?

You can use the drag events to enable and disable fixing for user events. 

Regards

**Comment by bb-play** [comment]
I set 'fixed' to true, as per your recommendation.  The way I read the docs, the new nodes should not be stuck on top of them, but they were.

**Comment by AlexDM0** [comment]
Are they now? Can you make a jsbin to show this?

**Comment by bb-play** [comment]
I don't think so.  I"m getting the data from a web service, and it's all
internal and proprietary.

**Comment by AlexDM0** [comment]
In that case I'm not sure what more I can do to help you. If the problem persists, try making a simple example showing the problem and we can fix it!

Regards

**Comment by bb-play** [comment]
I just spent an hour trying to use jsbin, and couldn't get anything to even
display.  https://jsbin.com/lolevebota/edit?html,css,js,console,output

**Comment by AlexDM0** [comment]
https://jsbin.com/nigaxixeza/1/edit

here you go

**Comment by bb-play** [comment]
Thank you, I will try that!

**Comment by bb-play** [comment]
I edited my code as you suggested, and am still seeing undesirable overlap.
(see attached screenshots).

**Comment by bb-play** [comment]
Never mind, I figured out the issue.  I need to un-fix the node where I"m
expanding from...
