### ISSUE TITLE
Vis is slowing page down after upgraded version for timezone. if i don't destroy timeline it causes page to hang

### ISSUE THREAD

**Issue by vinay3206** [almende/vis#1558]
moment:function(date){
                return moment.tz(date,timezone);
            }

I am passing this function as a constructor for timezone change

**Comment by AlexDM0** [comment]
I dont suppose you can provide a jsbin showing this issue?

**Comment by vinay3206** [comment]
i will try to create a jsbin. i am using timeline with ember so extactly it is not possible to replicate everything over their. I only notice performance issue once we are going to a different route which dont have timeline. once i started destrying timeline it is working fine. But i don't want to destroy timeline because recreation of timeline again takes time. let may try and replicate everything over js bin. will let know

**Comment by AlexDM0** [comment]
It sounds like you have a memory leak somewhere..

**Comment by yotamberk** [comment]
@vinay3206 I'm closing this issue. If you are still having trouble, feel free to reopen it.
