### ISSUE TITLE
Additional Event handlers 

### ISSUE THREAD

**Issue by imsganesh** [almende/vis#156]
Hi Alex,
This is not an issue, more like a request or a question. Hence creating a new one.

Graph -
Is there any plan to add additional events like mouse rightclick, mouseover, etc. to the graph? I did read in one of the issues (#147) that you mentioned that you are planning to add the 'mouseover' event. that is great. 
Can you please comment on if there is a plan, way or some documentation that would help us to extend/add javascript events like right-click and so on.

Thanks,
Ganesh

**Comment by andrewjw1995** [comment]
Hi Alex, I also would love to see support for context menu built in. For now I will have to go with manually triggering a click on context
