### ISSUE TITLE
Predictable and consistent assignment to default groups

### ISSUE THREAD

**Issue by jwr** [almende/vis#1560]
I am not sure if I'm doing something wrong here. In a network, I expected the default groups (and their styling) would be applied in a predictable and consistent order. However, it seems that they aren't — I reduced my group naming to "1", "2" and "3" and sometimes group 1 gets colored red, sometimes yellow.

I guess that if I defined my own groups, then I'd get predictability — but I would like to stick to default groups for now, which together with the rest of vis.js give excellent and quick out-of-the-box results.

Am I doing something wrong, or is this an oversight/bug?

**Comment by AlexDM0** [comment]
depends, could you show what you're doing in a JSbin? It sounds like you're removing and adding groups. This will increment the "counter" behind the scenes.

**Comment by jwr** [comment]
Not easily, because this is a ClojureScript+React app. What I'm doing is creating a Network object without any data, and later when the data actually arrives, I call `setData`. Also, when my data changes, I call `setData` again. My groups are always numbered consistently.

**Comment by AlexDM0** [comment]
You'd have to destroy the network to have it consistent. Check the examples for code snippets for this :)

Regards

**Comment by jwr** [comment]
I can do that, although I thought this was suboptimal — it can live longer in a React app. Should I assume the current behavior is intended and work around it, then? (this is not a problem, just asking)

**Comment by AlexDM0** [comment]
There is a case to be made for both scenarios. We have chosen not to reset the group count on setData. If that doesnt work with your case, there are a few ways of solving it. Defining your groups, destroying the network, etc. 

We could argue that it would make sense to reset the network on a setData, if that is the case it would be a breaking change and we could consider it for the next breaking release.

For now, it is intended and you'll have to work around it.

Regards

**Comment by jwr** [comment]
No problem, I will do that. Thanks for the quick response, and thanks for the very, very useful library!

**Comment by AlexDM0** [comment]
You're welcome!

Have fun :)
