### ISSUE TITLE
'fixed' nodes appear to be ignored by physics simulation

### ISSUE THREAD

**Issue by bb-play** [almende/vis#1561]
Once nodes are placed on the canvas, I set their position to fixed.  When the graph is incrementally added to, new nodes are often placed on top of existing nodes.  I've tried both BarnesHut and Repulsion, with and without options, and can't figure out what's going on.

https://jsbin.com/xugicofute/edit?html,output

**Comment by AlexDM0** [comment]
Hi,

Your jsbin does not show the issue. You're not adding nodes. 

Here: https://jsbin.com/zejolemibo/1/edit?html,output

I dont see the problem.

Regards

**Comment by bb-play** [comment]
It's happening here. https://jsbin.com/lasijoxuwo/edit?html,output

**Comment by AlexDM0** [comment]
Hi, 

Well yes. You tell nodes not to move, they will not move. You'll have to have the physics settle down before fixing them.

https://jsbin.com/tilenalebe/1/edit?html,output

**Comment by bb-play** [comment]
That seems to work better, but only if I have no options set in the physics object.  This is an aside, but can you point me to any documentation to better understand how to set up the physics?  The default options leave my nodes too closely spaced, but clearly my choices were poor.

**Comment by AlexDM0** [comment]
Hi,

Turn on the configure physics like in the example
http://visjs.org/examples/network/physics/physicsConfiguration.html

and try different things. Knowing the inner details wouldnt really do much. You seem to have more issues with the event system than anything else.

Regards
