### ISSUE TITLE
How to clear the duplicates edges between 2 edges

### ISSUE THREAD

**Issue by DanielZhangQingLong** [almende/vis#1562]
Thanks for your hard work, I am using vis js happily in my project. However, I want to clear the duplicates edges between 2 nodes, sometimes I think from A to B and from B to A should be the same edge. Thanks in advance

**Comment by AlexDM0** [comment]
Hi,

The data is all yours. If you want to clear it, write a preprocessing step :). 

Regards

**Comment by DanielZhangQingLong** [comment]
Thanks, I mean how I could I use `from` and `to` as a combined id. :).

Regards

**Comment by AlexDM0** [comment]
Hi,

I'm not sure why you'd want to do that but every edge has an id. It's up to you to pick it. If you don't it will get a uuid. 

Just make the id something like to + "_" + from. 

I'm not sure I understand what you want to do though.

**Comment by DanielZhangQingLong** [comment]
Thanks for your answer, it works, but I should check both `to`_`from` and `from`_`to`

**Comment by AlexDM0** [comment]
Not really. There are many ways to do this. I'd use an object to keep track of the nodes with edges since looking up is very fast. 

Good luck
