### ISSUE TITLE
Unable to set border width of a node (Network Graph) when it is hovered or selected

### ISSUE THREAD

**Issue by stanleyxu2005** [almende/vis#1563]
I tried to set a thicker border to a node, but when the node is hovered or selected, the border will be reset to 1px. I assume this is a bug.

**Comment by AlexDM0** [comment]
Can you show it in a jsbin?

**Comment by stanleyxu2005** [comment]
https://jsfiddle.net/q1u73n3u/4/

**Comment by AlexDM0** [comment]
I see, this is a mistake in the docs. If the borderWidthSelected is undefined, 2x the borderWidth will be used. By default it is not undefined but 2.

Sorry, I've updated the docs though. It will be updated int he next release.

**Comment by stanleyxu2005** [comment]
Okay. Anyway I think you might consider changing the options of border like color. E.g.
```
border: {
  width: 1.
  style: 'solid',
  selected: {
    width: 3
    style: 'dashed'
  }
}
```

**Comment by AlexDM0** [comment]
That might be good :) though then we'd probably also would want the color in there.. we'll see what happens.

**Comment by stanleyxu2005** [comment]
Cool. Then I'll wait for the next release. Sounds to be a great release to me.

**Comment by AlexDM0** [comment]
Things like changing the options might be considered for 5.0. There is no timeframe on that yet.
