### ISSUE TITLE
Network: selectNode event not fired when click-dragging a node

### ISSUE THREAD

**Issue by jwr** [almende/vis#1564]
It seems that if I click on a node, but instead of releasing the mouse button, drag the node, the node does get selected (as indicated visually, old selection gets deselected and new node is marked as selected), but selectNode event is not fired.

Perhaps I'm misreading the documentation, but my expectation was that I'd get the usual selectNode event, because a new node was selected.

**Comment by AlexDM0** [comment]
The idea here is that this is a drag event, not a selection event. Yes a node is selected, but the actual event here is the drag.

**Comment by jwr** [comment]
I see. I would suggest that the event mechanism could benefit from some separation of concerns. I have an app where there is a side information window containing information about the currently selected node. I am very interested in what is selected and deselected (ideally I'd get a notification that the set of selected nodes/edges changed and I'd re-render my app). I am, however, not at all interested in *how* or *why* the selection changed. The actual click & drag events are something I leave to the very capable hands of vis, which deals with them wonderfully.

I suspect that there are more ways to select nodes that I haven't anticipated yet, and currently I have to learn about them all and handle them all.

So perhaps in the future you might consider separating the click/drag events from node/edge selection notifications.

Thanks for explaining — I will add handling of drag events, too, for now.

**Comment by felixhayashi** [comment]
@jwr I have the same issue.

> I suspect that there are more ways to select nodes that I haven't anticipated yet, and currently I have to learn about them all and handle them all.

At the moment it's only drag and select which renders the node as selected.

> The idea here is that this is a drag event, not a selection event. Yes a node is selected, but the actual event here is the drag.

@AlexDM0 - I agree with @jwr here. I also think drag should trigger a select event. I mean even if you drag the node, it is rendered as select and when you eventually drop the node, it stays selected (and it is good and right that it stays selected) and may be retrieved with `network.getSelectedNodes()`. So I think it is very reasonable to trigger two event's.

**Comment by AlexDM0** [comment]
Hi Felix,

I agree, it would be fair. I think that'd be a breaking change though. We wil have to consider it for 5.0. I have no timeframe for 5.0 but there are a number of issues outstanding waiting for a breaking change.

Regards

**Comment by felixhayashi** [comment]
Thanks Alex!

**Comment by mojoaxel** [comment]
Should be fixed!?

Closing because inactivity.
Feel free to reopen if this still is an issue.
