### ISSUE TITLE
Edges are to terminate at the border of the nodes

### ISSUE THREAD

**Issue by asbalaji** [almende/vis#1565]
!!! Sorry if it is a duplicate !!!
In all the network module examples given in the visjs.org site using icons, the edges are going to the center of the nodes inside to which they are connected when the nodes use 'icon' property. Is there any way to avoid this.
If none, It would be really helpful if a configuration knob provided which tells if the edge is to terminate at the center of the node or at a given offset from the center of the node.

**Comment by AlexDM0** [comment]
Hi,

This is not possible. It is expensive to calculate the border of the node. For icons it would be a bounding box anyway so your edges would stop in mid-air. For arrows there will be a similar option in the next release though.

What would you expect? Touching the borders of the icons is not an option, we cannot calculate the position..

Regards
