### ISSUE TITLE
single editable item can't update (or add)

### ISSUE THREAD

**Issue by OliverHe** [almende/vis#1570]
I thought this might have something to do with #1127 but after upgrading I still can't edit an item that has been marked editable.
The timeline option editable remains false in my case, since I want to allow only authenticated users to edit their own group.

From #1127 I took the fiddle and create two new ones to demonstrate:
Using timeline option editable I can get all three alert() to popup, so far so good:
https://jsfiddle.net/7dLbkpfh/

Using item option editable I can only get the delete alert() to popup for item 4, but I want the change alert() also to popup.
https://jsfiddle.net/sn9417js/1/

Is this something I'm getting wrong, or is their another bug like the one described in #1127?

**Comment by josdejong** [comment]
You're fiddles just work fine as far as I can see, though you may also want to listen for onMove and onMoving events.

Have a look at the following example:

http://visjs.org/examples/timeline/editing/editingItemsCallbacks.html

if you just add the properties `editable: false` to the items you don't want to allow changing, you're ready I think?
