### ISSUE TITLE
Passing Scope in selectNode method not working

### ISSUE THREAD

**Issue by vramali1** [almende/vis#1571]
Hello,

I have integrated Vis JS inside Ext JS framework code. In the Ext JS controller object I am creating the Vis JS Network object. I want a Ext JS window to popup whenever I select a node. Inorder to do that, want to call the Ext JS controller object function inside the select event handler like.
createGraph : function(){
var me = this;
me.serviceDetailGraph = new vis.Network(container, data, graphOptions);
this.serviceDetailGraph.on('select', function(data){
me.process(data);
}
}
process : function(data){

}

The issue I am facing in the above code. The process function is not called and I am getting the error me is undefined. Could you please tell if I can pass the scope for the select event handler.

Thanks,
-Vijay

**Comment by AlexDM0** [comment]
Hi,

this seems like a plain javascript issue. I dont see how this is a problem with vis.

Regards
