### ISSUE TITLE
Can too many timelines cause browser to hang?

### ISSUE THREAD

**Issue by thsieh123** [almende/vis#1572]
We are using 3.7.2. It seems if we are creating like 1000+ timetlines in a scrollable window, my Chrome freezes for couple minutes and takes up 25% CPU all the time. When pauses it, I can see that it stops at auto refreshing redraw even I don't resize the window. Are all timelines are trying to draw/update even they are not visible? Wonder if this is a limitation for number of timelines or there is something I can fix this in our side? Thanks!

**Comment by AlexDM0** [comment]
That... Seems like a bad idea/design. 

How about lazy loading the timelines or using dynamic data instead?

I can't really help you.. You're using a very outdated version and to be fair you're creating 1000 instances and expect it to be fast. 

We do not optimize for as many timelines on a page as possible.
