### ISSUE TITLE
Regression in vis.js 4.12 - delete edge in network graph

### ISSUE THREAD

**Issue by bjornbak** [almende/vis#1573]
When you delete an edge on the manipulation demo http://visjs.org/examples/network/other/manipulation.html you get JS error:

vis.js:11214 Uncaught TypeError: Cannot read property 'length' of undefined

This worked in 4.11.

The error is thrown after the edge has been deleted from UI.

**Comment by felixhayashi** [comment]
Hi @bjornbak 

I guess this is a dublicate of https://github.com/almende/vis/issues/1556, which has been fixed in develop.

-Felix

**Comment by bjornbak** [comment]
What are the plans for release of 4.13 ?

**Comment by AlexDM0** [comment]
When it's done. Probably next week.

Regards
