### ISSUE TITLE
selectNode not thrown when multiselect replaced by a single select

### ISSUE THREAD

**Issue by bjornbak** [almende/vis#1575]
In examples/network/events/interactionEvents.html I add multiselect by replacing:
var options = {interaction:{hover:true}};
with:
var options = {interaction:{hover:true, multiselect:true}};

If I single-select a node the selectNode event is fired.

If I single-select a another node the selectNode event is fired again for the node.

If I multi-select some nodes the selectNode event is fired for each node.

But if I single-select an unselected node the selectNode event is NOT fired for the new node.

This issue is in both 4.11 and 4.12.

**Comment by AlexDM0** [comment]
Hi,

Sounds like a bug, I'll look into it.

Thanks for reporting!

**Comment by AlexDM0** [comment]
Ive pushed a fix to develop.

Thanks for notifying!

**Comment by ragol** [comment]
The fix introduced another bug. If I multi-select some nodes and then deselect one of them both `deselectNode` and `selectNode` events are fired. That should not happen since only deselection took place.
