### ISSUE TITLE
Timeline – “timechanged” doesn’t fire when I drag the timeline (‘vis-custom-time’)

### ISSUE THREAD

**Issue by arshadabbas** [almende/vis#1579]
vis.js (version: 4.11.0)

Initially on page load, timeline and everything works fine but sometime it stops working.

My Code:
self.timeline = new vis.Timeline(elmTimeline, timelineData, timelineOptions);

self.timeline.on('timechanged', function(properties) {
loadData(request);
});

I tried to debug the vis.js and found, its call the following function but this function doesn’t emit to  'timechanged' method(exist in my code).

Vis.js
this.body.emitter.emit('timechanged', {
id: this.options.id,
             time: new Date(this.customTime.valueOf())
});

Please help me to resolve this issue.

**Comment by AlexDM0** [comment]
Isn't it rangechanged?

**Comment by AlexDM0** [comment]
Sorry, I checked and see timechanged is also a valid event. Can you reproduce your issue in a jsbin?

Cheers

**Comment by josdejong** [comment]
The events `timechange` and `timechanged` are fired when you drag a custom time bar, and the events `rangechange` and `rangechanged` when you move/zoom the viewport. 

So I guess you need to use `rangechanged` instead of `timechanged`?

**Comment by arshadabbas** [comment]
I'm using timechanged event because want to execute my functionality on drag end of custom time bar. So As an event I'm using the correct event.

But some time custom time bar stops working, means I'm able to drag the custom time bar but custom time bar doesn't call the event. I don't know why but seems event destroyed.

**Comment by josdejong** [comment]
How can we reproduce your issue? Can you create a jsbin/jsfiddle?

The events in the custom time bars example seems to work fine: http://visjs.org/examples/timeline/other/customTimeBars.html

**Comment by arshadabbas** [comment]
I don't know how to reproduce this issue because its not consistent for me also.

But sometime I face this issue. 

Seems, sometime event destroys.

**Comment by josdejong** [comment]
hm. Then we can't really do anything here :(

I will close this issue now, if you have more information on how to reproduce please reopen this issue and let us know so we can get it fixed.
