### ISSUE TITLE
Timeline: Custom axis, without dates

### ISSUE THREAD

**Issue by vbermudez** [almende/vis#1581]
Hi,
Is there any way to create a custom axis (bottom) with summary data (like a sum of all values in a determinate date)?
A need to create a grid of tabular data, with dates as columns but also with summary as column footer. Kwoning that timeline is not designed for that pourpose, I want to use it because it solves many other problems and mandatory UI design requirement. The only one that (by now, and by my knlowledge) timline does not fullfill is a "summary axis".
I've uploaded an image as example (sorry, I'm not a great mspaint user ;) )
![tl-example](https://cloud.githubusercontent.com/assets/1035117/12387373/50bff830-bdcc-11e5-8805-e6f0ca1ae208.png)

Thanks in advance and kind regards!

**Comment by vbermudez** [comment]
Hi again,
I've made a little trick: Two timelines synchronized. It works surprisingly well.

![demo](https://cloud.githubusercontent.com/assets/1035117/12413999/0f30b7e8-be93-11e5-80e6-f63fdbd5b3eb.png)

Thanks anyway. You can close this "issue".

Kind regards!

**Comment by josdejong** [comment]
ok great!

**Comment by Jogai** [comment]
If are looping trough dates you can add a row to your dataset and add the sum value to that row:

	var sumId = `${rowId}-${dateInLoopMoment.format("L")}`; //Create unique id for reference
	var existing = items.get(sumId); //Look up if it exist

	if (existing != null) {
		items.update({
			id: sumId,
			content: existing.content + 1 //Calculate & set new value
		});
	} else {
		items.add({
			content: 1,
			group: rowId,
			type: 'background',
			className: "text-center",
			start: currentMoment,
			end: moment(currentMoment).endOf("day"),
			id: sumId //Create an item with the unique reference
		});
	}
