### ISSUE TITLE
Stack items of type standard and background

### ISSUE THREAD

**Issue by waqas7803** [almende/vis#1582]
Hi , Is it possible to stack events of 2 different types ,
I am using both standard and backgroud type events. as shown in following example
http://visjs.org/examples/timeline/items/backgroundAreasWithGroups.html

But stacking is not working , means i dont want to hide background event when in the same range there is standard type event.
Thanks in advance.

**Comment by mast0r** [comment]
It would be just great if we could stack items additionally based on some parameter.

**Comment by josdejong** [comment]
> It would be just great if we could stack items additionally based on some parameter.

That makes sense. Similar to how you can specify for individual items whether they are editable.

**Comment by yotamberk** [comment]
This doesn't make sense to me - stacking is meant to be between items. A background is not a regular item. It's meant to act as a background... If you want an item that stacks and looks like the background, you can do it via css (`height:100%`, `border:none` etc.) It simply doesn't make sense to stack background with items.

In terms of stacking items (that are NOT backgrounds) based parameters, this is a feature request that should be open in another issue. 
Closing this issue. @mast0r If you think there should be the option for stack to accept a function, please open another issue with your specification.
