### ISSUE TITLE
Network: Buttons are broken! Don't work anymore!   

### ISSUE THREAD

**Issue by LLTommy** [almende/vis#1584]
Hey guys, 
something (last update?) did break the navigation/zoom buttons in the network part of vis.js! They are not working (e.g. zooming into infinity) no more - and not only in my example but also here http://visjs.org/examples/network/other/navigation.html in the official part of the documentation. I tested it with different browsers and I have somebody else that confirms this behaviour on an other PC - so I am very sure it is not me or my machine but a visjs problem. And I would call it somewhat critical!

**Comment by AlexDM0** [comment]
Hi,

Seems like there is something wrong indeed. @josdejong could you look at this? Would this be something related to the changes in hammer? Its the only thing I can think of..

Thanks for notifying us!

Regards

**Comment by felixhayashi** [comment]
@AlexDM0 I became aware of this right after your fix: https://github.com/almende/vis/issues/1344#issuecomment-172004115 – so maybe your code change caused this?

**Comment by AlexDM0** [comment]
I see... Could be but the movement keys also do not work as they should. I'll look into it tomorrow

**Comment by felixhayashi** [comment]
Thanks!

**Comment by josdejong** [comment]
This is fixed now in the develop branch.

**Comment by felixhayashi** [comment]
Great thanks :+1: 

So it was actually Hammer-related issue, sorry for hinting in the wrong direction in my previous comments.
