### ISSUE TITLE
Network destroy doesn't release the subscriptions on DataSets if the nodes/edges are a DataSet

### ISSUE THREAD

**Issue by ducky427** [almende/vis#1588]
When I pass nodes and edges to create a Network, on calling the network destroy method, I see that there still are subscriptions in the original dataset. 

This causes issues if I were to resuse the same DataSet.

Also, could this lead to a memory leak?

**Comment by AlexDM0** [comment]
Hi, good catch! I've fixed this over at the develop branch.

Regards

**Comment by ducky427** [comment]
thanks. waiting for the next release!

**Comment by ducky427** [comment]
Thanks. I can confirm that this has been fixed in the latest release.
