### ISSUE TITLE
Network: Double click to open a new web site

### ISSUE THREAD

**Issue by janabala5** [almende/vis#1589]
Hi
I am not a developer.
I link to know how to set a weblink when you double click a item.

eg: node1 = google.ca
node2 = walmart.ca

so if i double click the node1, its opens a new window and open url.

**Comment by felixhayashi** [comment]
> I am not a developer.

That's almost impossible then.

> so if i double click the node1, its opens a new window and open url.

You need something like the code below. Good luck.

```javascript
// create an array with nodes
var nodes = new vis.DataSet([
    {id: 1, label: 'Node 1', url: "http://google.ca" },
    {id: 2, label: 'Node 2', url: "http://walmart.ca" }
]);

// create an array with edges
var edges = new vis.DataSet([
    {from: 1, to: 2}
]);

// create a network
var container = document.getElementById('mynetwork');

// provide the data in the vis format
var data = { nodes: nodes, edges: edges };
var options = {};

// initialize your network!
var network = new vis.Network(container, data, options);

network.on("doubleClick", function(properties) {
  if(!properties.nodes.length) return;
  
  window.open(node.url, "_blank");
  
});
```

**Comment by AlexDM0** [comment]
Hi,

I tend to agree with Felix, vis users are expected to do at least some coding. 

His example is clear and encompasses all you need (thanks btw :)).

I'll consider this issue resolved. 

Regards,

Alex

**Comment by felixhayashi** [comment]
> His example is clear and encompasses all you need (thanks btw :)).

Glad to help out sometimes.

**Comment by janabala5** [comment]
Thanks

I will try it

**Comment by janabala5** [comment]
this is the html page i did, but the code didnt work.

<!doctype html>
<html>
<head>
  <title>Network | Basic usage</title>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vis/4.2.0/vis.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/vis/4.2.0/vis.min.css" rel="stylesheet" type="text/css" />

  <style type="text/css">
    #mynetwork {
      position:relative;
      width: 600px;
      height: 400px;
      border: 1px solid lightgray;
    }
  </style>
</head>
<body>

<p>
  simple test network.
</p>

<div id="mynetwork"></div>

<script type="text/javascript">
  var container = document.getElementById('mynetwork');
  
// create an array with nodes
var nodes = new vis.DataSet([
    {id: 1, label: 'Node 1', url: "http://google.ca" },
    {id: 2, label: 'Node 2', url: "http://walmart.ca" }
]);

// create an array with edges
var edges = new vis.DataSet([
    {from: 1, to: 2}
]);

// create a network
var container = document.getElementById('mynetwork');

// provide the data in the vis format
var data = { nodes: nodes, edges: edges };
var options = {};

// initialize your network!
var network = new vis.Network(container, data, options);

network.on("doubleClick", function(properties) {
  if(!properties.nodes.length) return;

  window.open(node.url, "_blank");

});
</script>
</body>
</html>

**Comment by josdejong** [comment]
There is a little error in Felix' demo:

```js
network.on("doubleClick", function(properties) {
  if(!properties.nodes.length) return;

  window.open(node.url, "_blank");

});
```

should be:

```js
network.on("doubleClick", function(properties) {
  if(!properties.nodes.length) return;

  var node = properties.nodes[0];
  window.open(node.url, "_blank");
});
```

**Comment by felixhayashi** [comment]
Whoops. Thanks @josdejong for the correction here, sorry for the sloppyness, wrote it off the top of my head.

**Comment by janabala5** [comment]
I tried the new code, It does open the new windows, not the site.

for some reason the code dosnt pass the url to the double click.

**Comment by felixhayashi** [comment]
Faster than @josdejong 

```javascript
network.on("doubleClick", function(properties) {
  if(!properties.nodes.length) return;

  var node = nodes.get(properties.nodes[0]);
  window.open(node.url, "_blank");
});
```

**Comment by janabala5** [comment]
this works:)

**Comment by felixhayashi** [comment]
Yay!
