### ISSUE TITLE
Manipulation menu throws an error in browser console when clicked - functionality is fine

### ISSUE THREAD

**Issue by saukap** [almende/vis#1590]
On upgrading to 4.12 when I click on the manipulation GUI, I get the following error in Chrome's dev console. The functionality works fine.
Could this be due to upgrading hammer.js for fixing #1543 ?

Uncaught TypeError: Cannot read property 'length' of undefined
propagatedHandler @ vis.inc.js:11214
Manager.emit @ vis.inc.js:13687
inputHandler @ vis.inc.js:11748
MEhandler @ vis.inc.js:12059
Input.domHandler @ vis.inc.js:11663

**Comment by AlexDM0** [comment]
There has been a fix for this on the develop branch, we'll be releasing it this week.

Regards

**Comment by saukap** [comment]
Thanks, look forward to it!
