### ISSUE TITLE
The examples should be excluded from the bower package

### ISSUE THREAD

**Issue by germansokolov13** [almende/vis#1591]
Ordinarily bower automatically copies files from repository which are not excluded via `bower.json` to the publicly accessible folder. If it copies the `examples` folder, then a php file, called `datasource.php`, or other associated examples can be executed by a user. This might theoretically be a vulnerability. I suggest adding the `examples` folder to the `bower.json`'s `ignore` option.

**Comment by josdejong** [comment]
Thanks for sharing your ideas. 

The examples are hugely important for users of the library to get started and to figure out how things work. I don't think we should remove them.
