### ISSUE TITLE
Emit an `afterRedraw` event to `_redraw()` method in timeline/Core component

### ISSUE THREAD

**Issue by marlosin** [almende/vis#1592]
Emit an `afterRedraw` event to allow the user to run some task.

**Comment by ludost** [comment]
I assume the use-case for this is some custom UI work that needs triggering after the redraw has finished? If that is the case, I would like to implement this as a "changed" event, which indicates that some change has occurred and the rendering has finished for this update.

**Comment by marlosin** [comment]
That's right an fine form me :+1:
