### ISSUE TITLE
Changing edge color launches a restabilization of th whole network

### ISSUE THREAD

**Issue by jfmonteil** [almende/vis#1593]
Hello,

I am updating my 1st degree nodes border as well as edges colors with an edges.update(list of updated edges).

It launches a restabilization of the whole network which is not very cool when trying to focus on a part of the graph...

Any idea ?

Cheers 

Here is the code (I know it's a bit dirty :)

    function neighbourhoodHighlight(params) {
    // if something is selected:
	
	console.log('hoverNode Event:', params);
			if (popupMenu !== undefined) {
			  popupMenu.parentNode.removeChild(popupMenu);
			  popupMenu = undefined;
			  }
	
   
	var t = JSON.parse(JSON.stringify(params));
	var a=new Array();
    a.push(t.node);
	network.selectNodes(a);	
	highlightActive = true;
	var i,j;
	var selectedNode = a[0];
	var degrees = 2;

	// mark all nodes as hard to read.
	for (var nodeId in allNodes) {
		if(!allNodes[nodeId].hidden)
		{
		allNodes[nodeId].color.border = '#FFF';//rgba(200,200,200,0.5)
		}		     
    }
	for (var edgeId in allEdges) {
		if(!allEdges[edgeId].hidden)
		{
		allEdges[edgeId].color = 'lightgray';//rgba(200,200,200,0.5)
		}		     
    }
	
     var connectedNodes = network.getConnectedNodes(selectedNode);
      //var allConnectedNodes = [];

      /* get the second degree nodes
      for (i = 1; i < degrees; i++) {
      for (j = 0; j < connectedNodes.length; j++) {
        allConnectedNodes = allConnectedNodes.concat(network.getConnectedNodes(connectedNodes[j]));
        }
      }
	  */
      for (i = 0; i < connectedNodes.length; i++) 
	  {
        //allNodes[allConnectedNodes[i]].color.border = 'red';//rgba(150,150,150,0.75)';
      
	   
		var edgestohighlightTo =edges.get({
				  fields: ['id','to'],
				  filter: function (edge) {
					return (edge.to == connectedNodes[i]);
				  }
		});
		var edgestohighlightFrom =edges.get({
				  fields: ['id','to'],
				  filter: function (edge) {
					return (edge.from == connectedNodes[i]);
				  }
		});
		edgestohighlightTo=edgestohighlightTo.concat(edgestohighlightFrom)
		
		if(edgestohighlightTo!=null && edgestohighlightTo!=undefined && edgestohighlightTo.length>0)
			{
				for(var u=0;u<edgestohighlightTo.length;u++)
				{
					allEdges[edgestohighlightTo[u].id].color = 'red';
					
				}
			}
	  }
      
	  

      // all first degree nodes get red
       for (i = 0; i < connectedNodes.length; i++) {
		  if(!allNodes[connectedNodes[i]].hidden)
		  {
           allNodes[connectedNodes[i]].color.border = 'red';
		  }
		}  

    // transform the object into an array
    var updateArrayNodes = [];
    for (nodeId in allNodes) {
      if (allNodes.hasOwnProperty(nodeId)) {
        updateArrayNodes.push(allNodes[nodeId]);
      }
    }
    
	
	var updateArrayEdges = [];
    for (edgeId in allEdges) {
      if (allEdges.hasOwnProperty(edgeId)) {
        updateArrayEdges.push(allEdges[edgeId]);
      }
    }
    edges.update(updateArrayEdges);
	nodes.update(updateArrayNodes);

**Comment by AlexDM0** [comment]
Hi,

Can you show this in a jsBin?

Regards

**Comment by jfmonteil** [comment]
I apologize, I am sarting a bit from scratch on everything...

https://jsbin.com/melumo/edit?html,js,output

This is how I create the network

	var container = document.getElementById('network');
				var data = {
					nodes: nodes,
					edges: edges
				};//interaction:{hover:true}
			    var options = {interaction:{hover:true},
                                physics: {"forceAtlas2Based":{"springLength": 100},"minVelocity": 0.75,"solver": "forceAtlas2Based"},
				manipulation: {
				  addNode: function (data, callback) {
					// filling in the popup DOM elements
					document.getElementById('operation').innerHTML = "Add Node";
					document.getElementById('node-id').value = data.label;
					document.getElementById('node-label').value = data.label;
					document.getElementById('addmainentity').value = data.group;
					document.getElementById('saveButton').onclick = saveData.bind(this, data, callback);
					document.getElementById('cancelButton').onclick = clearPopUp.bind();
					document.getElementById('network-popUp').style.display = 'block';
				  },
				  editNode: function (data, callback) {
					// filling in the popup DOM elements
					document.getElementById('operation').innerHTML = "Edit Node";
					document.getElementById('node-id').value = data.id;
					document.getElementById('node-label').value = data.label;
					document.getElementById('addmainentity').value = data.group;
					document.getElementById('saveButton').onclick = saveData.bind(this, data, callback);
					document.getElementById('cancelButton').onclick = cancelEdit.bind(this,callback);
					document.getElementById('network-popUp').style.display = 'block';
				  },
				  addEdge: function (data, callback) {
					if (data.from == data.to) {
					  var r = confirm("Do you want to connect the node to itself?");
					  if (r == true) {
						callback(data);
					  }
					}
					else {
					  callback(data);
					}
				  }
				}
		
				
				};
	             network = new vis.Network(container, data, options);
                     allNodes = nodes.get({returnType:"Object"});
		     allEdges = edges.get({returnType:"Object"});

**Comment by AlexDM0** [comment]
Hi,

Sorry, I cant really reproduce your case. There are many examples of functional JSBins in the current issues. Maybe those can help you along?

Cheers

**Comment by jfmonteil** [comment]
Ok, I'll be travelling for work in 4 days, and prouce a good jsbin right after,

Thank you for your patience !

**Comment by jfmonteil** [comment]
I habe done a propper JSBIN here https://jsbin.com/foweziqexu/, and guess what it doesn't behave the same....
AAARRRFHH, let me check before closing....

many thanks once again

**Comment by jfmonteil** [comment]
Ok,

It's working fine now... Using the latest visjs lib solved the problem.

Many thanks for this fantastic lib.

JFM

**Comment by josdejong** [comment]
Great to hear, thanks for the compliments :)
