### ISSUE TITLE
childnode is undefined (hierarchical, DataSet)

### ISSUE THREAD

**Issue by heinrichmartin** [almende/vis#1594]
HAVING nodes and edges in vis.DataSet with 1sec delay
AND using hierarchical layout
AND pre-existing nodes and edges were cleared with vis.DataSet.clear()
WHEN I add more nodes
THEN I receive an exception: "TypeError: childNode is undefined"

Code to reproduce: https://jsfiddle.net/heinrichmartin/3ku4rct3/ using v4.12.0

Exception:
TypeError: childNode is undefined vis.js:40637:15
_placeBranchNodes() vis.js:40637
_placeNodesByHierarchy() vis.js:40334
setupHierarchicalLayout() vis.js:40292
bindEventListeners/<() vis.js:39993
Emitter.prototype.emit() vis.js:9458
add() vis.js:28662
add() vis.js:28429
DataSet.prototype._trigger() vis.js:5753
DataSet.prototype.add() vis.js:5785
Queue.prototype.flush() vis.js:6684
Queue.prototype._flushIfNeeded/this._timeout<() vis.js:6673

**Comment by heinrichmartin** [comment]
* the linked fiddle worked for me in FF, not in IE
* this is a minimal example to my actual problem: I am adding nodes and edges from asynchronous REST calls and have seen such error messages even without clearing the data in advance.

**Comment by AlexDM0** [comment]
Hi,

We'll look into it! Thanks for reporting!

Regards

**Comment by AlexDM0** [comment]
This was a tricky one, i've pushed a fix to develop.

It will be added to the next release.

Regards
