### ISSUE TITLE
Node shapes not drawing in version 4.12.0.

### ISSUE THREAD

**Issue by rjbriody** [almende/vis#1595]
As you can see in this screenshot, the node shape is missing. The shape is ```box``` and you can see based on the arrow heads where it should go. 

![image](https://cloud.githubusercontent.com/assets/492786/12496128/ba1dad08-c061-11e5-96b7-f86a8116c6d0.png)

I also tried ```dot``` - same thing.

Here is my node config, which might be important because other graphs in the same app draw fine (not sure what the key difference is though).

```
var visjsOptions = {
    nodes: {
        shape: 'box',
        shapeProperties: {
            borderRadius: 0
        },
        labelHighlightBold: true,
        color: nodeColor,
        font: {
            size: 12,
            face: 'sans',
            color: 'white',
            strokeWidth: 2,
            strokeColor: nodeColor
        }
    },
 ```

4.11.0 works fine, btw.

**Comment by AlexDM0** [comment]
Hi,

Can you show this in a jsbin?

Regards

**Comment by AlexDM0** [comment]
Our shapes here seem to work fine:
http://visjs.org/examples/network/nodeStyles/shapes.html

**Comment by rjbriody** [comment]
Some graphs render fine for me as well. I'll try to determine what triggers
the failure and report back.

**Comment by AlexDM0** [comment]
Sound good! I suppose the nodeColor is not rgba(0,0,0,0)?

**Comment by heinrichmartin** [comment]
I've seen this bug on jsfiddle.net, but not in our production environment. (Didn't investigate for that reason.) Maybe that helps.

**Comment by AlexDM0** [comment]
Hi,

Theres a lot of things that can go wrong in a jsfiddle but once it draws it should just work. I'm sorry but without at least the possibility of reproducing I'm thinking it might be something else?

regards

**Comment by AlexDM0** [comment]
Is this still an issue?

**Comment by rjbriody** [comment]
Yes, although I haven't gotten around to reproducing it in a controlled
environment. I have a hunch that it is caused by an incompatibility between
vis and one of my other dependencies, but I have not isolated the problem
yet.

**Comment by rjbriody** [comment]
This problem was caused by height transitions on the parent container - probably not your problem. Sorry for the noise.
