### ISSUE TITLE
Network: enable/disable manipulation bar at run-time doesn't work 

### ISSUE THREAD

**Issue by saukap** [almende/vis#1596]
Using visjs v4.12.0:

We need to enable/disable manipulation in our network based on user-input, for which I use the following function:
```js
var toggleManipulation = function(enable){
  var opt = {manipulation: {enabled: enable}};
  network.setOptions(opt);
};
```
Disable on first run works, but it throws the following error in console. Subsequent enabling/disabling doesn't work:

Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
_removeManipulationDOM @ vis.inc.js:41492
_setup @ vis.inc.js:41325
setOptions @ vis.inc.js:40929
Network.setOptions @ vis.inc.js:27828

This JSBin has the details of the issue I am facing:
https://jsbin.com/quhopowexi/edit?html,console,output

**Comment by AlexDM0** [comment]
Hi,

I've fixed this on the develop branch. It will be added to the next release. Thanks for notifying us!

Regards

**Comment by saurabhkapoor** [comment]
Thanks for quickly addressing this!
