### ISSUE TITLE
borderWidth: 0 fails

### ISSUE THREAD

**Issue by heinrichmartin** [almende/vis#1597]
HAVING borderWidth: 0
WHEN I zoom out
THEN nodes have different border widths > 0

It looks like the border widths are increasing by 1 per node. See screenshot ![capture](https://cloud.githubusercontent.com/assets/2970601/12522404/bf93e762-c150-11e5-857f-543b25e433d2.PNG).
Code to reproduce: https://jsfiddle.net/heinrichmartin/m22Lo6s4/ (Can be observed after zooming out!)

**Comment by AlexDM0** [comment]
STOP screaming at me! :p 

I have pushed  a fix to develop to address the diverging of the size of the borders. Vis has so far assumed that borders would always be there. I have implented support for border width 0.

It will be released today.

Regards

**Comment by heinrichmartin** [comment]
> STOP screaming at me! :p

I didn't mean to. I hoped that a GIVEN-WHEN-THEN-format of the description is less fuzzy.

Thanks for the amazing support!
