### ISSUE TITLE
Network graph layout always random

### ISSUE THREAD

**Issue by linquize** [almende/vis#1600]
I run the example network graph.
But the graph layout is always random. A different graph is generated when I refresh the page.
I expect a constant layout every time I show the graph.
Is there any option to use a constant layout?

**Comment by linquize** [comment]
http://visjs.org/examples/network/edgeStyles/arrows.html

**Comment by AlexDM0** [comment]
Yes, it's called randomSeed in the layout options. Please read the docs for more information.

**Comment by linquize** [comment]
Thanks for the hint. This line works.

`var options = { layout: { randomSeed: 1 } };`
