### ISSUE TITLE
Adding font-weight to a node's label

### ISSUE THREAD

**Issue by sachaudh** [almende/vis#1603]
I wanted to be able to change the font-weight of a label to be able to make it bolder. Is there already a way to manipulate this or can we add this to the package?

**Comment by AlexDM0** [comment]
We're open to pull requests ;)

**Comment by sachaudh** [comment]
If I have the time, i'll try! Could you point me in the right direction?

**Comment by AlexDM0** [comment]
We use the normal html5 canvas for text so it should be relatively easy to do if it is possible. There is a label class that does all the text drawing. 

Regards

**Comment by mojoaxel** [comment]
implemented by @eymiha with #2385
