### ISSUE TITLE
Zoom changes when moving the bar even a bit

### ISSUE THREAD

**Issue by greggilbert** [almende/vis#1606]
Hey. I was just putting together a sample timeline when I noticed that, as I have it set, the zoom starts off as one, but if I move the bar even a little bit, it changes to be more zoomed out. Here's what I'm seeing:

![bar-zoom-change](https://cloud.githubusercontent.com/assets/169482/12603631/6f97fdfe-c482-11e5-8e85-1339b7d15dde.png)

[Here's a JSBin](http://jsbin.com/zesavilocu/edit?html,js,output) that reproduces it. It's better if you take the Output pane and make it much wider. Viewing it in [output mode](http://jsbin.com/zesavilocu) also helps demonstrate it. 

I've been able to reproduce the issue in Firefox 44 and Chrome 47. I've been messing with the data, and I think it has to do with the `hiddenDates` option. Let me know if I can clarify anything!

**Comment by josdejong** [comment]
Thanks for reporting this. It seems to have to do with hiddenDates.

Here is a more minimal jsbin demonstrating the issue of both #1606 and #1607 (best visible on a wide screen):

http://jsbin.com/cipeva/edit?html,output

**Comment by yotamberk** [comment]
This doesn't occur anymore in v0.4.17. If this bug occurs again, please reopen this issue.

**Comment by inDream** [comment]
This issue is still present when using mouse wheel to move timeline.
