### ISSUE TITLE
Time offset jumps when moving the bar off edge

### ISSUE THREAD

**Issue by greggilbert** [almende/vis#1607]
Related to #1606, I noticed that even if the bar starts on the hour, when I move the bar even a little bit, it offsets to :06 after the hour. See the screenshot:

![time-jump](https://cloud.githubusercontent.com/assets/169482/12603708/0b76485c-c483-11e5-8916-340ffdbf85b3.png)

[This JSBin](http://jsbin.com/zesavilocu/edit?html,js,output) should also show it. Line up Apr 21 12:06am right on the left edge, and then move the bar just to the left a bit. Note that the 1am slot also falls off the edge, and it starts with 2 am. This was in both Firefox 44 and Chrome 47.

**Comment by josdejong** [comment]
Thanks, I expect this to have the same cause as #1606, let's continue the discussion there.
