### ISSUE TITLE
Reference Error: point is not defined

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#1608]
Hi devteam.

this happened today. Any ideas?

-Felix

![2016-01-27 16 22 41](https://cloud.githubusercontent.com/assets/4307137/12618004/581bf000-c512-11e5-8dd1-49f2cb13e134.png)

**Comment by felixhayashi** [comment]
Maybe it should be `arrowPoint.t` ?

**Comment by AlexDM0** [comment]
Hi Felix, 

debugging just in my mind against a compiled version of our code with no references.... A jsbin would be very helpful :).

Regards

**Comment by felixhayashi** [comment]
Hi Alex,

I already tried to create a jsbin but couldn't reproduce it there, anyway, I looked at the code and it seems that the variable `point` is not defined in the code. Setting it to `arrowPoint` solved it. I guess a typo.

https://github.com/almende/vis/blob/develop/lib/network/modules/components/edges/util/EdgeBase.js#L464

-Felix

**Comment by AlexDM0** [comment]
Hi Felix, 

Looks like you're right! You can do a pull request and claim the solution if you want? ;)

Cheers

**Comment by felixhayashi** [comment]
Yes, I should quickly claim it before anybody else gets the fame :)

**Comment by AlexDM0** [comment]
Dont forget to add your fix to the history.md to attach your name to the solution ;)

**Comment by felixhayashi** [comment]
> Dont forget to add your fix to the history.md to attach your name to the solution ;)

First I thought "Yeah, I should add my name to the HISTORY.md and enjoy a life in fame". But on second thought, fame is not everything in life…  you know, Eddie Van Halen once said "I'm not a rock star. I'm not in it for the fame, I'm in it because I like to play." So I just added the title of the commit to the history log. Hope that's fine with you.

-Felix

**Comment by AlexDM0** [comment]
It's like you're a part of the team, the loss of going down in the history file is something you learn to live with ;) 

We're actually looking for someone to help out with network issues if you're interested? We can't handle the load given our other duties..

**Comment by felixhayashi** [comment]
> It's like you're a part of the team,

Thanks, Alex, much appreciated.

> the loss of going down in the history file is something you learn to live with ;) 

I guess you are right :)

> We're actually looking for someone to help out with network issues if you're interested? We can't handle the load given our other duties..

Thanks for the offer, but at the moment, I am pretty busy finishing my master thesis. If you are talking about coding, I think I am also too unexperienced with the vis.js code. In case you meant replying to user issues, I'll try to jump in with an answer, when I have the time and know a solution.

**Comment by AlexDM0** [comment]
Hi Felix,

I think this has been released now. I;ll close the issue. Thanks!
