### ISSUE TITLE
Graph without physics

### ISSUE THREAD

**Issue by Krunch** [almende/vis#161]
Is there any way to generate a graph without any physics? As in having the graph nicely drawn and then just move the nodes wherever the users wants it without having physics/collision/repulsion/spring effect. Just normal lines and nodes.

**Comment by stanleyxu2005** [comment]
Once you've added all nodes and edges, you can call `network.freezeSimulation(true);`. After that the graph will be stabilized.

**Comment by geethabadh** [comment]
Hi,

     I wanted to know can we maintain states in force directed graph. What I meant was when I drag nodes can I maintain the last state. And when it reloads again all nodes should come up with the last stored state.

**Comment by una2511** [comment]
Hi,
               I am new to forced directed graph. But I have a requirement which needs to be taken care. Can you please guide me. Can I store the states of the nodes and when I reload it again, the topology graph should come up taking the latest state of the nodes. What I mean by state is that I should be able to pull my nodes and position it wherever possible and that position needs to be stored. When it reloads and come up the current position should be taken.
