### ISSUE TITLE
network tooltip

### ISSUE THREAD

**Issue by heinrichmartin** [almende/vis#1613]
Hi,
this is rather a collection of questions than a "real" issue - I am willing to create separate issues, if the answers suggest to do so.

I have rather big tooltips with full HTML in my network.
- Is there a reason for using white-space: nowrap in css? Unfortunately, vis.css takes precedence over an inline style - I had to hack the library stylesheet (or use js to hack it at runtime).
- The positioning with offset x+3 cuts tooltips in an ungly way when they are as wide as the canvas. My hack is max-width: 90%.
- How can I access links in the tooltip? (I have keyboard interaction disabled.)

TIA,
Martin

**Comment by felixhayashi** [comment]
> Is there a reason for using white-space: nowrap in css? Unfortunately, vis.css takes precedence over an inline style - I had to hack the library stylesheet (or use js to hack it at runtime).

Since it doesn't use `!important` you just need to increase the priority of your css rule to override the visjs defaults

> How can I access links in the tooltip? (I have keyboard interaction disabled.)

You can't with the current implementation. You could create your own popup class. Alex provided a small working example: https://github.com/almende/vis/issues/952. Although you may need to do some adjustments.

**Comment by AlexDM0** [comment]
Is this still an issue?

**Comment by heinrichmartin** [comment]
I hacked the case rules as stated and moved on. However, creating a custom class to enable links in a pop-up seems a bit of an overkill... It is definitely low prio for my current project. Thanks anyway, to both of you!
