### ISSUE TITLE
Set dot size in graph3d

### ISSUE THREAD

**Issue by ben-github** [almende/vis#1615]
Looking at the documentation in http://visjs.org/docs/graph3d/, I can't see how to set the dot size of a 3d graph. If in the graph style is dot-size mode, then the dot size is set by the data in style column. But if the graph is in dot-color mode, then it seems that the dot size is fixed but not adjustable via an option. Is this correct? If so, it would be great to set the dot size since in large data sets, the dots collide. 

Thanks,

**Comment by josdejong** [comment]
I've implemented a new option `dotSizeRatio` in the develop branch for this. It will be available in the next release.

**Comment by ben-github** [comment]
You rock. Thanks!
