### ISSUE TITLE
Endtime of timeitem does not fit with current time (now)

### ISSUE THREAD

**Issue by Heinzelemente** [almende/vis#1616]
Hello vis.js Team,

first of all: great job! 
I recognized a strange behavior with zoomed to max and zoomed to min timelines.
If you zoom in the end of the last item is before the current time.
![zoomin](https://cloud.githubusercontent.com/assets/12995603/12676468/cbcdae7c-c692-11e5-80f8-e86779333f42.png)
 
If you zoom out the end of the last item is after the current time.
![zoomout](https://cloud.githubusercontent.com/assets/12995603/12676470/cecbde82-c692-11e5-8b92-dee1c7801638.png)

Do you know why? Can I fix that by my own?

Best regards,
Alex

**Comment by josdejong** [comment]
Are you sure you're displaying the same data in both cases? Your upper screenshot ends with a green item, the second screenshot ends with a red item.

**Comment by Heinzelemente** [comment]
Yes I am. The timeline get update every 10 seconds so already a red one appeared, but I can show you the same again:
![2016-02-01 15_24_29](https://cloud.githubusercontent.com/assets/12995603/12719870/fe1205b0-c8f7-11e5-9ffa-1dcad2744fd4.png)
![2016-02-01 15_24_40](https://cloud.githubusercontent.com/assets/12995603/12719871/014243b2-c8f8-11e5-9a0f-f6737624659e.png)

**Comment by josdejong** [comment]
Can you create a jsbin/jsfiddle to demonstrate the issue? And are you using the latest version of vis.js?

It probably has to do with paddings that you set in your items, it could be that the items have a width of about zero when zoomed out, but due to some padding they still keep some minimum width. For example, the following item does not have a width of 0, but of 22px (2x padding + 2x border)
```html
<div style="width:0; padding: 10px; border: 1px solid red;"></div>
```

**Comment by Heinzelemente** [comment]
You are absolutely right! 
As you can see in the the screenshots: I set the border to 0px, but forgot to set the padding to 0 to.
Thank you very much!
![2016-02-02 15_29_36](https://cloud.githubusercontent.com/assets/12995603/12753533/d29b8a5c-c9c7-11e5-864d-1b990952d1c1.png)

![2016-02-02 15_29_19](https://cloud.githubusercontent.com/assets/12995603/12753539/d829f706-c9c7-11e5-9f7a-74764d4ebefe.png)

**Comment by josdejong** [comment]
Ok great!
