### ISSUE TITLE
Problem fit with few timelines

### ISSUE THREAD

**Issue by ar53n** [almende/vis#1617]
Hello in our project have one proble with execute **fit()**. For each timeline after add items we call function fit(). And all data dublicate into each timeline. This work incorrect. We have few timelines and one array items.

**_Correct but no fit()_**

![screen2](https://cloud.githubusercontent.com/assets/7085102/12679606/1ca48776-c6b6-11e5-9ab1-a500b76d4405.PNG)

_**After fit()**_

![screen1](https://cloud.githubusercontent.com/assets/7085102/12679607/1cae0ad0-c6b6-11e5-8ed8-d80fda09866c.PNG)

**Comment by josdejong** [comment]
Thanks for letting us know. 

How can I reproduce your issue? Can you create a jsbin or jsfiddle demonstrating the issue?

**Comment by ar53n** [comment]
_You must understand that images changed._

I create demonstrate, but work correct, maybe we use AJAX request.
https://jsfiddle.net/6kz6d8a1/29/

We solved our problem with 

> timelines[i].range.setRange(option.min, option.max, true);

**Comment by josdejong** [comment]
Ok great if you already solved it.

You may want to use public options instead of accessing internal stuff like `timeline.range.setRange`, this can break if the internals change in the future. The public method for this is `setWindow`
