### ISSUE TITLE
How to go to the starting of the graph in vis js

### ISSUE THREAD

**Issue by gouthampratapa** [almende/vis#1623]
i have done the following steps 1.git clone https://github.com/almende/vis.git 2.git checkout 257d876e14080d0f0595ac467e0660ca34b2c00a 3.git checkout bbf04d3489683cf2938e6870d6e307d5c6f945c8

i got the desired graph with the Y values truncated but i have a doubt i have my values of X somewhere but it is showing up some where near seconds and if i want to show from the starting of my graph(Instead searching for the beginning) how can i achieve it
![vis](https://cloud.githubusercontent.com/assets/15155893/12726821/a8573c06-c93f-11e5-8138-035a233a9d05.jpg)
 my desired result is 
![screenshot from 2016-02-01 23 58 46](https://cloud.githubusercontent.com/assets/15155893/12726841/c86c5df0-c93f-11e5-9db9-2582fdf040e1.png)

`<script src="https://gist.github.com/gouthampratapa/c9499e9c4db60b91effb.js"></script>`

**Comment by josdejong** [comment]
What data do you load into Graph2d? Can you create a jsbin demonstrating your issue?

**Comment by gouthampratapa** [comment]
https://jsbin.com/garewi/edit?html,css,js,output

the data i am loading is 
[{"y":0.5344999999999999,"x":"2016-01-07 03:00:06.525036"},{"y":0.4541666666666668,"x":"2016-01-07 04:45:55.669235"},{"y":0.5185000000000001,"x":"2016-01-07 06:08:02.645683"}]

**Comment by josdejong** [comment]
In your jsbin (which is full of errors...) you provide options `start` and `end` like this:

```
var options = {
  start: '2015-06-10',
  end: '2014-06-18'
};
```

That is an empty interval as `end`  is before `start`. Maybe you meant `2015` for the end too. Still, since your data points are in January 2016, you would not see them. If you *don't* provide a `start` and `end`, the Graph2d will automatically fit your data.

**Comment by josdejong** [comment]
Here your fixed jsbin: https://jsbin.com/rojuqo/edit?html,css,output

**Comment by gouthampratapa** [comment]
yea i am sorry for the trouble it worked thanks alot
