### ISSUE TITLE
Change color of node without changing color of edges

### ISSUE THREAD

**Issue by The-Penultimate-Defenestrator** [almende/vis#1624]
Is there a way to update the color of a node *without* updating the color of edges?

**Comment by AlexDM0** [comment]
Hi,

You will need to disable inheritColor. It's all I the docs. 

Cheers

**Comment by The-Penultimate-Defenestrator** [comment]
Thanks a lot. Will *new* edges that are created still inherit color?

**Comment by AlexDM0** [comment]
If you disable it globally, no. If you disable it per edge.. Well it's per edge. New edges have their own settings. Note that individual edge settings overrule the global settings. 

Cheers

**Comment by The-Penultimate-Defenestrator** [comment]
What color will new edges be, then?

**Comment by AlexDM0** [comment]
The default color. Blueish. It's all In the docs.

**Comment by The-Penultimate-Defenestrator** [comment]
Oh, right. That makes sense. I think I'll create edges with an inherited color, then change the inheritance property. Thanks a lot!
