### ISSUE TITLE
The discrepancies in the documentation

### ISSUE THREAD

**Issue by bashkos** [almende/vis#1630]
Hi!
http://visjs.org/docs/graph2d/#Methods - object `Graph2d` does not have method `getItemRange()`, but he have method `getDataRange()`.

http://visjs.org/docs/timeline/#Methods - object `Timeline` have method `getItemRange()`, but it is not mentioned in the documentation.

I spent some time to look into this. Hopefully fixes will make life easier for others.

**Comment by josdejong** [comment]
Thanks for bringing this up, I fixed it in the develop branch.
