### ISSUE TITLE
Overlapped nodes in hierarchical layout 

### ISSUE THREAD

**Issue by atima** [almende/vis#1631]
Some nodes are overlapped after update to v.4.13.0. Please see https://jsfiddle.net/atima/dtmz8otj/
Node 11 appears behind node 12 (try dragging node 12 around and you should see node 11). I also expect node 7,8,9 to be in triangle (try dragging node 8).

I think the problem is in _setPositionForHierarchy (lib/network/modules/LayoutEngine.js). There is no overlapped nodes if I force doNotUpdate = true (that is identical to I roll back just this part to the previous version).

Could you fix this? or any suggestion about how to fix this is appreciated. I don't want to simply force doNotUpdate because it makes network.fit() weird.

Best regards.

**Comment by josdejong** [comment]
That can indeed happen with force directed layouts. You can try to use non-physics based layouts, like in the following example: http://visjs.org/examples/network/layout/hierarchicalLayoutWithoutPhysics.html

**Comment by AlexDM0** [comment]
The full overlap was an older issue, which version of vis are you using?

Regards

**Comment by atima** [comment]
I use the most recent one (v.4.13.0). My problem didn't exist in the previous version (v.4.12.0). I tried disable physics but had no luck. Physics-based layout seems to provide a better graph since they will not overlap again after I dragged the overlapped node out of its initial position.

**Comment by JoeKehr** [comment]
I have the same problem here. 
I've seen that the issue was resolved one year and a half, so I forked the jsfiddle provided by the one who reported the issue and the bug seems to be back. 
[Here is the forked jsfiddle](http://jsfiddle.net/JoeKehr/w3xL0g6t/1/), so you will have several samples for your tests :)

**Comment by AlexDM0** [comment]
Hi all,

I've fixed this on the develop branch. Both your examples allowed me to find two different causes for this so thanks a lot! 

Regards

**Comment by ThaDafinser** [comment]
@AlexDM0 i tried the `develop` branch and some things are fixed there, but not all.

I added an example here with the latest `tag`, but maybe you can try it with develop as well?
https://jsfiddle.net/q2dcnq2p/

With `develop` it looks this way:
![image](https://cloud.githubusercontent.com/assets/533017/13250521/b56708da-da2a-11e5-8e43-002c99942a45.png)

**Comment by AlexDM0** [comment]
Hi,

Thanks for catching this. Guess it was messed up after fixing another bug. Its a tricky system... It should be fixed on develop now. 

Regards

**Comment by ThaDafinser** [comment]
Really awesome @AlexDM0  :+1: 

I can only imagine how complex that was ...

**Comment by mojoaxel** [comment]
This looks fixes in the current version v4.16.1
