### ISSUE TITLE
Network nodes - do not recenter

### ISSUE THREAD

**Issue by michaelelrom** [almende/vis#1632]
Hello,

I'm trying to save nodes in a specific x & y position.  Every time I save and reload they shift slightly.  It appears they are centering based on the div.  Is there a way to load without the centering part?  I've been reading through the documentation and can't seem to figure it out.  I am overlaying the nodes on a background image for the canvas and need them exactly where they were saved.

Thank you,

Mike

**Comment by felixhayashi** [comment]
Hi Mike,

strange, I do not experience this. I also use a canvas background and on `beforeDrawing` I add the image at (0,0) `context2d.drawImage(this.backgroundImage, 0, 0)`. All nodes that have positions assigned stay where they are, also after reload, regardless of whether the canvas or the wrapper div change in size.

Visually, the positions may not be appear to be exact everytime, as the rendering on different canvas sizes causes interpolation of the images, which is likely to produce results that differ by pixels, however this is only optical and should not affect the actually stored position.

-Felix

**Comment by michaelelrom** [comment]
Hi Felix,

Thanks for your prompt response.  I tried playing with a few other items, but still no luck.  I am trying to use a backgroundImage on the div where I draw the network canvas.  Even without the background image when I save the nodes and reload them in the positions the x and y are the same but the screen shows them differently.  I think that may be due to the camera position.  I'm trying to have the node end up at the same visual spot each time regardless of camera position.

Thanks,

Mike

**Comment by felixhayashi** [comment]
> I am trying to use a backgroundImage on the div where I draw the network canvas.

Ah, I see the problem. You are not drawing the image programatically on the canvas but simply used a css background on the div, right? This doesn't work.

You need to use Javascript, add an event handler for the `beforeDrawing` event and draw the image using `context2d`. See this question https://github.com/almende/vis/issues/1397#issuecomment-152298437 and the subsequent answer given by @dragonzone https://github.com/almende/vis/issues/1397#issuecomment-152532344.

Good luck

-Felix

**Comment by michaelelrom** [comment]
Thanks!  That worked great!

**Comment by felixhayashi** [comment]
Glad to hear that. You are welcome.
