### ISSUE TITLE
Open cluster by adding the contained nodes to the cluster node.

### ISSUE THREAD

**Issue by dhruvdatt** [almende/vis#1633]
var clusterNode = network.body.nodes[clusterNodeId];
var containedNodes = clusterNode.containedNodes;
var containedEdges = clusterNode.containedEdges;							
							
for (var nodeId in containedNodes) {
	var containedNode = this.body.nodes[nodeId];
	network.body.data.nodes.remove({id: nodeId});
	network.body.data.nodes.add({
		id:nodeId,
		label:'new'
	});
}

this is what i am trying.to somehow remove all the cluster edges and add the existing edges to the cluster node.

**Comment by AlexDM0** [comment]
You can't. You're messing around in all the wrong places for this. What you want is not supported and is very likely to mess up your network. 

Why would you want to do this?

**Comment by dhruvdatt** [comment]
This is my requirement.
Is there any way to remove the cluster node and then redraw the chart by making a new node and alter the edges from the containedEdges from the cluster to the new node formed.

**Comment by AlexDM0** [comment]
I'm not sure what you want but it sounds like you want to open the cluster. 

If you could elaborate a bit maybe we can see if it is a use case we want to cater to..

You cannot remove nodes or edges that are contained inside of a cluster without breaking the network. 

You can open and recluster if you want to manipulate contained entities.

Regards

**Comment by dhruvdatt** [comment]
Please see this https://jsfiddle.net/dhrdatt/52hhuqtj/3/
When i click on the cluster I want to add the contained nodes to the cluster node itself.

**Comment by AlexDM0** [comment]
The contained nodes are already inside of the cluster. What do you mean by "add the contained nodes to the cluster node itself"? This doesn't really mean anything. 

How do you expect this to work? What would the result be?

**Comment by dhruvdatt** [comment]
The result would be 
1--Connected to--C1
C1--Connected to--the remaining nodes
Something like this https://jsfiddle.net/dhrdatt/52hhuqtj/5/

**Comment by AlexDM0** [comment]
Ok so here is what you do:

Stop using network.body. This is not the public API and we do not support its use. 

On click of the cluster, open the cluster, use the add or update method on the nodes and edges datasets to add your new nodes and edges. Then recluster. Your join condition can judge what to add. 

This is the only way to do this.

**Comment by dhruvdatt** [comment]
Ok. What is the correct way to access the nodes and the edges inside the cluster.
And how can i get around with my requirement.

**Comment by dragonzone** [comment]
I have done clustering extensively in one of my project that uses vis.js. I have modified your example a little to show you how clustering works in vis.js. You are probably trying to hack your way at the lower level. There is no need to since there are documentations that shows you how to cluster them very easily at http://visjs.org/docs/network/#methods. (Alex, you may want to update the README.md to point to your documentations over to visjs.org). But here an example of how to open/close the cluster & getting the connected edges for those cluster (or get child nodes within the cluster), which you have ask in one of the previous issue (https://github.com/almende/vis/issues/1627). 

Take a look: https://jsfiddle.net/52hhuqtj/6/

Hope this helps!

**Comment by AlexDM0** [comment]
... I'm sorry but what I told you directly does what you want, going by what you've told me. I'm not sure what more I can tell you. 

Apart from the methods in the documentation there is no way of interacting with the clusters.

**Comment by dhruvdatt** [comment]
I wanted something like this.This is the best that I have reached.
https://jsfiddle.net/dhrdatt/52hhuqtj/7/

Is there any better way to do it.

**Comment by AlexDM0** [comment]
Try implementing what I told you. Hierarchical layout and clustering are not officially supported together though, it may cause strange behavior. 

Regards

**Comment by dhruvdatt** [comment]
I think i will continue with this for now.Thanks for the help though.
