### ISSUE TITLE
Edge-preview not displayed when 'editing a Edge'  in network/manipulation

### ISSUE THREAD

**Issue by theuerse** [almende/vis#1635]
(in version 4.13 and 4.14)

E.g 
go to http://visjs.org/examples/network/other/manipulation.html
click on 'edit'
select a edge
click on 'edit edge'
(try to) drag one of the end-points to another node

In previous versions, there was a nice preview-edge being displayed, now there is no such indicator.
The assignment of the new node-endpoint works in the end, but while you do the dragging, it doesn't looks like its working.

**Comment by josdejong** [comment]
Thanks for the clear report. I followed your steps, but things seem to work just fine: while creating a new edge, you see an edge and red dot where you're dragging to. 

What browser are you using, and do you maybe see some errors in de developer console of your browser?

**Comment by theuerse** [comment]
First of all, I would like to thank you for your quick reponse.


I am using Firefox (Firebug, deactivated NoScript) / Chrome, the respective developer-consoles show no errors.

Creating/adding new edges works for me too, but 'redirecting' existing edges to connect a different pair of nodes does not provide that 'preview' that previous versions did.
(I think the corresponding API-call would be 'network.editEdgeMode()')

I  hope this helps you recreate that behavior.

**Comment by josdejong** [comment]
ah, indeed, adding a new edge works fine but changing an existing node not. Thanks for the clarification

**Comment by AlexDM0** [comment]
I've pushed a fix for this to develop.

Cheers
