### ISSUE TITLE
Setting to prevent redundant timeline group resizing?

### ISSUE THREAD

**Issue by roypardi** [almende/vis#1636]
Great lib – thanks for making it available!

Once the sorting and stacking has been done for a particular zoom level, it seems to me that the height of groups should not change. I notice however that as items scroll out of view, more stacking attempts take place.

Is this a bug (or a feature :smiley: )?

Is timeline trying to *not* stack items so it keeps trying?
Is there a setting to fix the heights of groups to some minimum? I find it visually distracting that these groups ("channels") grow or collapse when there seems no reason for it.

In the screenshots below, I am scrolling the items off the right side of the screen. 

**1. Everything sorted**
<img width="400" alt="screen shot 2016-02-05 at 6 55 30 pm" src="https://cloud.githubusercontent.com/assets/9053196/12862675/9a4d5862-cc3b-11e5-9e2a-be029f3d85f8.png">

**2. First collapse of groups**
<img width="400" alt="screen shot 2016-02-05 at 6 55 54 pm" src="https://cloud.githubusercontent.com/assets/9053196/12862676/9a4f2fb6-cc3b-11e5-80ed-cd0b64e274ba.png">

**3. Second collapse of groups**
<img width="400" alt="screen shot 2016-02-05 at 6 56 06 pm" src="https://cloud.githubusercontent.com/assets/9053196/12862674/9a4cf336-cc3b-11e5-9fab-c13dac045db3.png">

**Comment by josdejong** [comment]
The Timeline will indeed adjust the height of groups to match the visible items. Items are considered visible in the window plus some margin left and right of the window.

I'm not sure why you don't want to see the height's changing. One thing you can do is ensure the groups have some minimal height, by giving the group label a minimum height with CSS, see #1428

**Comment by yotamberk** [comment]
@roypardi this issue was solved in the current develop branch. If you still have this issue, please reopen it =)
