### ISSUE TITLE
Default function used to color node borders.

### ISSUE THREAD

**Issue by The-Penultimate-Defenestrator** [almende/vis#1638]
It appears there is a function used by default  to color edges and node borders, which produces a darker shade of the node color. If I change the color of a node from blue to orange, the border changes from a dark blue to a dark orange without my having to manually change it. My question is what the name of this function is, so that I can manually access it without rewriting.

**Comment by AlexDM0** [comment]
You can just provide your own colors... why would you want to overwrite the function that handles this if you supply just one color?

**Comment by The-Penultimate-Defenestrator** [comment]
I don't want to override the function, I want to make use of it, to be able to use the color of node borders/edges elsewhere, and have this color change dynamically.

**Comment by AlexDM0** [comment]
I see. Well I cannot guarantee that it will not change/move in future updates but here it is:
https://github.com/almende/vis/blob/master/lib/util.js#L991

**Comment by The-Penultimate-Defenestrator** [comment]
Thanks a lot :smiley:
