### ISSUE TITLE
Support data-binding

### ISSUE THREAD

**Issue by unsafecode** [almende/vis#164]
We're currently dealing with another issue: we're using Vis Timeline as a graphical tool to define a project schedule within a form bound to a KnockoutJS view model and we are struggling to integrate Vis objects with it: every change to the activities array must be synch'ed manually to Vis, and backwards, too: Vis modifications must be propagated back to our view model.

Would it be possible to enable a two-way data binding fo Vis? At least for its inner data structure, so we can listen for its modifications directly.

**Comment by LaundroMat** [comment]
I got a great answer to a similar question I posted on Stackoverflow: http://stackoverflow.com/questions/29607214/using-knockout-js-with-custom-template-engine/29609977

(Mind that it exposes another problem with event hijacking, see the comments on that page).
