### ISSUE TITLE
[Timeline] How should I wrap items, in an item stack, in a div so I can pan/scroll stacks vertically?

### ISSUE THREAD

**Issue by thinkpadder1** [almende/vis#1640]
[Timeline]

Basically, for a group, the current DOM looks like this (simplified for clarity):

```
<div group>
	<div item style="left: 300"/>
	<div item style="left: 303"/>
	<div item style="left: 600"/>
	<div item style="left: 605"/>
<div>
```

I basically want to wrap each item stack in another div that will be pannable/scrollable:

```
<div group>
	<div pannable>
		<div item style="left: 300"/>
		<div item style="left: 303"/>
	</div pannable>
		<div item style="left: 600"/>
		<div item style="left: 605"/>
	</div>
<div>
```

So, instead of panning the entire timeline up and down, I can pan each individual stack. Not asking for an actual implementation, but I was wondering how you would do it so I don't waste too much time doing it in a less maintainable/optimal way. Thank you.

Other notes: I only plan on using a single group for the entire timeline, but I think this would work for any number of groups (does not seem like a good user experience).

**Comment by josdejong** [comment]
I think that will require quite some work. Groups should get support for a height and/or maxHeight option, and then should be made vertically scrollable.

**Comment by yotamberk** [comment]
@thinkpadder1 is this issue still relevant? Can we close the issue?
