### ISSUE TITLE
odd network flickering (bug?) in some networks

### ISSUE THREAD

**Issue by pgoldweic** [almende/vis#1641]
First, I want to thank you for your product, which I've been using for the last several months. I've noticed that on some network graphs (usually with at least 100 nodes, but could be more), there's one or more nodes/edges that continuously flicker (I mean that they move non-stop in a repetitive fashion). I imagine this may be some sort of bug. I've created a short movie that displays one such network graph in which only one edge/2 nodes display this problem (I have another example in which at least 5 sets of nodes/edges are involved). This short movie is at: http://screencast.com/t/9uei87bhc (note that the speed in the movie is much slower than in real life). Thanks in advance for looking into this. (I can provide more information as needed)

**Comment by josdejong** [comment]
Thanks for the clear movie. Looks like this node is jumping between two positions or something. @AlexDM0 do you have an idea where this behavior could come from?

**Comment by AlexDM0** [comment]
Hi,

It could be the physics configuration. Could you make a jsbin to reproduce this? Which version of vis are you using and what are the options you supply to the network?

Regards

**Comment by pgoldweic** [comment]
I'm not familiar with jsbin, is there any other way? BTW, I am not using any explicit physics configuration, so I'm running with the defaults. However, here are the options that I am using:

options = {
  		edges: { smooth: { type: 'continuous' }, }, 
  		groups: { comment: { shape: 'dot', color: '#4ddb94', value: 1 },
		        pin: { shape: 'triangleDown', color: 'blue', }, 
		        board: { shape: 'dot', color: 'darkGreen', },
		        person: { color: 'purple', }
        	},
	  	layout: {
			improvedLayout:false,
			randomSeed: 5, 
		},
		interaction:{
			hover:true,
			hoverConnectedEdges: true,
			navigationButtons: false,
			tooltipDelay: 200,
			hideEdgesOnDrag: true
  		}
	};
Hope the above helps somewhat. Thanks for looking into this!

**Comment by pgoldweic** [comment]
Just a quick note that may help to share: this network graph is displayed as part of a tool that visualizes usage data for a particular social network. I noticed today that the flickering problem in this particular network - which appeared partially in the movie- (and it is now updated with more usage data in the form of additional nodes and edges) is gone. I think this suggests that the particular shape of the network (physics, etc.) is what produces the problem (of course this is what you thought already, but I'm just confirming it :-)). Another (static) instance of this network graph (different usage data fed into the same tool) displays the problem too, in case we need to somehow reproduce it though.

**Comment by AlexDM0** [comment]
Hi,

JSBin is quite easy, maybe you can use this issue's JSBin as a startingpoint?

https://github.com/almende/vis/issues/1578

Regards

**Comment by pgoldweic** [comment]
Looks like you're right on jsbin. However, I don't think I'm able to share my code at this point (although I imagine that it will be eventually shared publicly, but we are not ready to do so yet :-(). Would it help for me to capture the state of the network (of the nodes and edges using your API) so that you can reproduce it on your end? Let me know. Otherwise I'll have to produce somehow a simplified version of the code that produces the network. 
BTW, I've played a little bit more with one of these networks and realized that in some cases I can minimize (or avoid) the problem if I wait long enough to start displaying the network nodes (in this tool I've created, only part of the network nodes display at first, and everything else is hidden until you click on the button toggles which display activity for a particular time frame. By delaying the button clicks I noticed that I seem to be able to avoid the flickering problem in some cases. I am also thinking that this is what actually got me rid of the flickering when I wrote my previous comment above (as opposed to this effect having been produced by the addition of more nodes/edges to the network) .

**Comment by AlexDM0** [comment]
Hi,

I think we can't avoid distilling it to a simple example o reproduce it. We cannot debug pages and pages of custom code :)

Please see if you can make a reduced example. 

Regards

**Comment by pgoldweic** [comment]
Ok, it took me a full day to be able to reproduce one problem network with clean code :-(. Also, it only seems to be reproducible on Firefox for me (although the real network - the jsbin uses a snapshot of this real network- , both browsers present the same problem!). The jsbin url is: http://jsbin.com/qewoci/edit?html,output 
I really hope this will help you debug. BTW, I seem to be unable to reproduce the problem -cleanly- with my other network (which continues to present 4-5 flickering nodes/edges although only on Firefox).

**Comment by AlexDM0** [comment]
Hi,

See my other reply on how you're mistreating your data.

The issue here is that you set your mass to 0. With this you are ruining the physics calculation. This is not possible. Anything below 1 is discouraged.

```
0 Object {hidden: false, size: 0, mass: 0, id: "p_33549", value: 0…}
```
