### ISSUE TITLE
Node Menu

### ISSUE THREAD

**Issue by neolivz** [almende/vis#1642]
I am currently using [Orion DB graph editor](http://orientdb.com/docs/2.1/Graph-Editor.html), Is there any way I can create a menu on the node similar to Orion DB Graph Editor.

Note: I tried to use context menu and able to get it done but since its outside of canvas its not aligning properly and node. Apart from that node does not have a right click, I have do left click and then right click. 
https://plnkr.co/edit/QQYxLr3D1P0idQXUmemS?p=preview

**Comment by josdejong** [comment]
The `oncontext` event (= right click) provides a pointer of the mouse location, both in pixels (DOM location) as well as in the canvas coordinates.

```js
network.on('oncontext', function(params) {
  console.log('pointer', params.pointer);
  params.event.preventDefault();
});
```

**Comment by neolivz** [comment]
@josdejong : It gives you mouse location not the center of the node, which also I can get from network.getPositions. The problem is first i want to right click on node or edge rather than on canvas. Secondly pointer will give me position would be slightly off from the center because if i draw from center of the node, its still slightly off.

**Comment by josdejong** [comment]
Ah ok, makes indeed sense to ues `getPositions` in this case. 

One issue I see now is that the params of the `oncontext` event do not provide the clicked nodes/edges but the (previously) selected ones. That looks like a bug in Network.

What do you mean with "positions are slightly off" ? How large an offset is it?

**Comment by josdejong** [comment]
Ah, I see what you mean with the offset. When I zoom in in your plnkr demo, then left-click a node to select it, then right click it, the menu has an offset of a couple of pixels towards the top left. The offset is larger when you're zoomed in more.

**Comment by AlexDM0** [comment]
If I look at the example here:

http://visjs.org/examples/network/events/interactionEvents.html

I get this:
```
oncontext (right click) event:

{
    "nodes": [],
    "edges": [],
    "pointer": {
        "DOM": {
            "x": 289,
            "y": 241
        },
        "canvas": {
            "x": 5.572460064286929,
            "y": 24.699779250923484
        }
    },
    "event": "[original event]"
}
```

Seems fine to me?

**Comment by josdejong** [comment]
@AlexDM0 no, it should provide the clicked nodes and/or edges. Like hover/blur do.

**Comment by AlexDM0** [comment]
No it shouldnt. 

As the docs state:

>Fired when the user click on the canvas with the right mouse button. The right mouse button does not select by default. You can use the method getNodeAt to select the node if you want.

We could add an additional field but this is not a bug, it could be a feature request. I dont really see the need for it but we should rethink the event data if we want to make breaking changes.

Regards

**Comment by josdejong** [comment]
Ah, I didn't know that the events always provide the *selected* nodes/edges instead of the node/edges under your moue pointer (which I would expect intuitively). Well, we can't just change this behavior, that would be breaking.

Anyway to address your issue @neolivz you can get the `getNodeAt` method to find the clicked node as described the docs that Alex copied.

**Comment by neolivz** [comment]
@josdejong Yes, I can do work around like that but I still need a way to show menu at the center. I still have a couple of pixels off when I draw from the point.

@AlexDM0 : I am still not sure why right click should not select the node, I mean naturally expectation of someone right-clicking will be expecting it to select and a menu pops up, something like you see in finder/explorer.

**Comment by AlexDM0** [comment]
It shouldnt because it is currently designed NOT to do it. Whether that is a good choice in hindsight, I'm not sure. A case can be made for not selecting (and thus also deselecting) on right click. 

For now it will not change. Maybe in future versions, who knows.

Regards

**Comment by neolivz** [comment]
@AlexDM0 : I agree with part it's not designed to do that but the part I am not clear is why it should not.
Any idea how to fix the position issue?

**Comment by AlexDM0** [comment]
The position issue cannot be fixed since the DOM and the canvas handle fractions differently. One fix would be to draw your menu in the canvas using the render events. We can't do anything else for you at this time.

**Comment by neolivz** [comment]
Thanks, @AlexDM0, I'll try to see if I can create functionality for the menu in the code itself. If I am able to fix it, I'll create a pull request. Would that work?

**Comment by AlexDM0** [comment]
Hi,

We can see what we get but vis does not require a built-in menu. Good luck though!

Cheers
