### ISSUE TITLE
Merge event instead of overlapping on zooming in? 

### ISSUE THREAD

**Issue by iislam** [almende/vis#1643]
Hi
Great library and thanks for making it available. 
We are trying to merge event together when they overlap (when occurred in short interval or if user zoomed out) and display the number of the events merged. Please look at the image below. 

![timeline](https://cloud.githubusercontent.com/assets/4976631/12952438/1492d09a-cfdc-11e5-8559-1b0a827db54e.jpg)

I am sure there is a way to do this. Can anyone point me to right direction? Thanks in advance.

**Comment by josdejong** [comment]
This sounds like you want to do clustering, this feature is not yet available in Timeline but for example Network supports it.

What you can do is add a listener to rangechange events, see how large the visible window is, determine sort of a "zoom level". Depending on the "zoom level", you can replace your items with clustered items. You will have to cluster them yourselves, for example loop over your data and group all items which are closer than x milliseconds.

**Comment by iislam** [comment]
@josdejong Thank you for your response. Yes. I think clustering in timeline is what I was looking for. Let me try to see if I can implement your solution and also look at network.
