### ISSUE TITLE
Overlapping Nodes - kindly open the zip in your local

### ISSUE THREAD

**Issue by probaner** [almende/vis#1644]
[visjs_issue_overlap.zip](https://github.com/almende/vis/files/126021/visjs_issue_overlap.zip)

**Comment by josdejong** [comment]
There are quite some issues about overlapping nodes, did you check them out?

**Comment by probaner** [comment]
Yes it seems an old issue, some how came back. I am using  vis/4.14.0/vis.js can you tell which version don't have this issue?

**Comment by josdejong** [comment]
@AlexDM0 can you have a look into this? I thought it should not be possible to get overlapping nodes when using hierarchical layout without physics.

**Comment by AlexDM0** [comment]
It shouldn't. I'll look into it.

**Comment by AlexDM0** [comment]
Hi,

The fix for 1631 also fixed this, additionally, treespacing has been fixed thanks to this issue.Thanks!

Regards

**Comment by probaner** [comment]
Thanks Alex and josdejong. May I know when the next release is planned?

**Comment by AlexDM0** [comment]
Hi,

Probably this week. 

Cheers!
