### ISSUE TITLE
load groups and items via ajax/json

### ISSUE THREAD

**Issue by dborchers87** [almende/vis#1646]
Hi, i´m testing the example
https://github.com/almende/vis/blob/master/examples/timeline/groups/groups.html
and i want to add groups to the timeline but i dont know how to load the groups and how to to add the group name to the data in the basic.json

can someone help me?

**Comment by josdejong** [comment]
http://visjs.org/examples/timeline/dataHandling/loadExternalData.html

**Comment by yotamberk** [comment]
@dborchers87 You can do it via `timeline.setGroups()`
