### ISSUE TITLE
Is it possible to have disabled group items in a timeline?

### ISSUE THREAD

**Issue by rubenbenjamin** [almende/vis#1647]
When displaying items on a timeline, is it possible to have groups with no data? I want to style the row to look different. 

![table](https://cloud.githubusercontent.com/assets/429940/12980223/72c71f2c-d0a9-11e5-897c-ce55fb8b36f6.jpg)

**Comment by josdejong** [comment]
Yes you can do that though it requires a little effort on your end. You can give each group a `className` so you can style them differently. Next, you will have to loop over the groups and count yourself how many items each group has. As soon as you know that, you can give the groups with zero items a special CSS class name.

**Comment by rubenbenjamin** [comment]
yes! that is exactly what I was looking for. thanks for the idea
