### ISSUE TITLE
miniature and escaping nodes in one of my networks: could you help pinpoint the problem?

### ISSUE THREAD

**Issue by pgoldweic** [almende/vis#1648]
A particular vis.js network instantiation is producing extraneous behavior (note: different data fed into the network with equivalent options work fine) in the sense that the nodes/edges created appear to be miniature, and they also move away from the view able area faster than one can drag them back :-(. Could you help me figure out what is wrong with this particular network? I have just been able to reproduce this behavior with clean network creation code in:
http://jsbin.com/yaduziy/1/edit?html,output

Thanks in advance for looking into this.

**Comment by for-sagacity** [comment]
check your edge data
that's problem

2016-02-12 4:53 GMT+09:00 Patricia Goldweic <notifications@github.com>:

**Comment by AlexDM0** [comment]
I'm sorry to say this but this is a terrible way to interact with vis.

First of all:

```
var nodes = new vis.DataSet();
var edges = new vis.DataSet();
network = new vis.Network(container, { nodes: nodes, edges: edges} , options);
network.body.data.nodes.update(updateNodesArray);
network.body.data.edges.update(updateEdgesArray);
network.setData({nodes: network.body.data.nodes, edges: network.body.data.edges});
```

You set the data twice. Revisit the docs on the dataset. Do not use the network.body. This is not the public API and you dont need it. Do it like this:

```
var nodes = new vis.DataSet(updateNodesArray);
var edges = new vis.DataSet(updateEdgesArray);
network = new vis.Network(container, { nodes: nodes, edges: edges} , options);
```

Apart from the roundabout way of constructing the data and not putting most of the common options in the global options (making it a mess to navigate), the problem is your physics. Specifically this one:

```
Object {hidden: false, size: -1, mass: -1, id: "c_93975", value: -1…}
```

Guess why mass -1 and size -1 could be a problem. 

Regards

**Comment by pgoldweic** [comment]
Thanks Alex. BTW,  I may not have been clear on this, but the code you saw is not really what I use in my program to build the network. There's an algorithm that builds the network and incrementally assigns and updates values (and then matching masses) following a particular logic, so I don't assign any of these values explicitly and I did not realize that some of the resulting values were negative. Thanks for noticing this; I promise I will,  from now on,  look carefully at the data produced by the algorithm before posting. 
In terms of the use of setData, I only use it in my program when I want the graph to be redrawn all at once, as opposed to having the user wait for individual updates (which can be visually confusing). Mainly, when the graph has already been displayed, and we suddenly load a bunch more data into it.  This seemed to work well to achieve that effect. If not a best practice for this goal in particular, please let me know. 
And, as to my use of the network.body, I've done it in cases in which I didn't have a pointer to the vis.DataSet objects around, but only to the network itself. Yes, you are right that I could probably avoid using the non-public API -I'll have to keep more pointers-. Thanks again for your help.
