### ISSUE TITLE
Edge arrow does not point to bounding area of node when node is scaled up

### ISSUE THREAD

**Issue by sachaudh** [almende/vis#1649]
I'm trying to have the edge arrow just touch the perimeter of the node, when the node is scaled up. But, for some reason the edge arrow points deeper inside the node. Is there a good fix for this?

**Comment by AlexDM0** [comment]
Hi,

Which version of vis are you using?

Regards,

Alexk

**Comment by sachaudh** [comment]
I am using Version 4.10.0

**Comment by AlexDM0** [comment]
This should have been fixed in (I think) 4.12. Can you try the latest version?

Cheers
