### ISSUE TITLE
Group

### ISSUE THREAD

**Issue by Chroedde** [almende/vis#1650]
Hi,
I am wondering if it possible to group a high number of nodes automatically. In gephi there is the possibility to automatically arrange the nodes so that "networks in the networks" can appear (like facebook -> group of university friends, group of old school friends, group of soccer team, etc) and to give each of these "sub networks" different colors. You can see what I mean when you look at your "World cup" network.

The question is: Is this possible with vis as well? Can it arrange an color a list of nodes that have no groups, no specific size and not color?

Thanks a lot for helping me!

BR Christoph

**Comment by AlexDM0** [comment]
You mean clustering?

**Comment by Chroedde** [comment]
No, it's not teally clustering - I think. For example, when you look at your following example: http://visjs.org/examples/network/exampleApplications/neighbourhoodHighlight.html

Here you can see what I mean: all these differently colored little "sub-groups". When I have a list of nodes where only labels and edges are defined - no size, no color, etc.: is it possible that vis calculates an arrangement like the shown above, i.e. the formation of little, colored groups?

**Comment by AlexDM0** [comment]
Hi,

We do not automatically color the nodes so no. The layout is determined by the physics model. 

Regards.
