### ISSUE TITLE
Timeline items stacking when I don't want them to

### ISSUE THREAD

**Issue by liester** [almende/vis#1652]
I'm running into an issue where I want two timeline entries to run right up against one another but depending on the zoom they stack even when not overlapping times.  
Example:
var items = new vis.DataSet([{
        id: 0,
        group: 0,
        content: 'A',
        start: new Date(2016, 1, 17, 1, 15),
        end: new Date(2016, 1, 17, 1, 24, 59),
        className: 'gold'
    }, {
        id: 1,
        group: 0,
        content: 'B',
        start: new Date(2016, 1, 17, 1, 25, 00),
        end: new Date(2016, 1, 17, 2, 30),
        className: 'green'
    }]);
![stackingissue](https://cloud.githubusercontent.com/assets/6137420/13020715/934dba96-d19c-11e5-87f5-5a95c9ec2bfc.PNG)

Is there a way, besides setting 'stack: false' to get items to only stack when the times actually overlap?  I realize that the behavior I am trying to change may not be the desired behavior for everyone.

**Comment by josdejong** [comment]
You can set the horizontal margin between the items to zero (it's 10px by default)

```js
var options = {
  margin: {
    item: {
      horizontal: 0
    }
  }
}

**Comment by liester** [comment]
That worked perfectly!  Thank you so much for the quick response.  I guess I should read the documentation again.

**Comment by maxsteenbergen** [comment]
I'm still getting weird behavior with this. I'm guessing it has something to do with the zoomable option, since the breakpoint changes with each zoom action. Even setting margin:0 does not resolve this.

**Comment by simo9000** [comment]
Just an FYI to anyone struggling with this issue. Setting the horizontal margin to a negative number prevents stacking at any zoom level as long as there is no overlap in time stamps.
