### ISSUE TITLE
Retrieved positions are not actual

### ISSUE THREAD

**Issue by llowinge** [almende/vis#1657]
Create network (with initial coordinates), call method **getPositions** and you will get the initial positions (but nodes are already on different positions).

You can see that behavior at link [Example](http://jsbin.com/coxotevice/edit?html,output)

Is that correct behavior ? (I spent a lot of time to debug that, and found that with `network.once('initRedraw', function(){
     //here you will get the correct coordinates
});`
it works)

**Comment by AlexDM0** [comment]
getPositions will get you the positions of the nodes. If you move the nodes or if they have moved you will get different values. 

The network's physics start at the next tick. This is by design. The events allow you to determine the position after settling. StabilizationIterationsDone, stabilized etc.

Regards

**Comment by llowinge** [comment]
Thank you for response. I think that it should be mentioned in docs.

**Comment by AlexDM0** [comment]
Hi,

Where in the docs would you expect this?

Regards

**Comment by llowinge** [comment]
I think that it should be somehow connected with section **Methods to get information on nodes and edges.** (because probably all these methods need to wait till the next tick ?)

**Comment by AlexDM0** [comment]
Not at all. The clustering for instance really SHOULD happen BEFORE the next tick.

**Comment by llowinge** [comment]
I thought only the section with nodes and edges, but maybe it would be enough to place some kind of warning (on top of these methods), that some of these methods should be called after settling (otherwise it could not correspond with the view - what user sees).

**Comment by AlexDM0** [comment]
It depends what the user wants... We have events for a reason. There is a big section on them, examples etc. I think some people may just read the methods and skip the rest.. A big warning at the top seems overkill. We could put it at the events since thats where it belongs.

**Comment by llowinge** [comment]
I understand you, as you can see, i figured out how to make it work properly. But for new users (as i was) who see ,,Public API,, methods would be nice to see (e.g. go visit events section first, to make sure your methods will work properly - it doesnt need to be a big warning, small note would be enough).

**Comment by AlexDM0** [comment]
Since you were affected by this, I'd like to invite you to come up with a good solution for this and make a pull request to the develop branch :)
