### ISSUE TITLE
Display nodes as present in data set Network Hierarchical Layout

### ISSUE THREAD

**Issue by sachin-samel** [almende/vis#1658]
Hi,

Please see the [example](http://jsbin.com/mihezisuvu/edit?html,output)

I want to arrange the nodes in sorted manner.

However, it is plotting the nodes in some default manner.

Does anyone having any idea of how to plot the hierarchical network as per data provided for nodes?

Thanks,
Sachin

**Comment by AlexDM0** [comment]
Hi, the order is determined by the position. X = 2 will be to the left of X = 5.

Cheers

**Comment by sachin-samel** [comment]
Can the nodes be displayed in order they appear in data set?

In the example I shared the nodes are displayed in random order. E.g. even if nodes 1,2,3 etc. are present in sequence in data set, those are not getting displayed in sequence.

Regards

**Comment by AlexDM0** [comment]
Yes, so give them an initial position.
