### ISSUE TITLE
The releasefunction to the opencluster does not work

### ISSUE THREAD

**Issue by randomilla** [almende/vis#1659]
Hello,I have been trying to solve my problem for days now.Here is my problem I have a small network with some clusters.I want after the cluster is opened the nodes to go to the places they had before the clustering.I am sure that I am passing the object that is required as the second parameter at the openCluster

**Comment by AlexDM0** [comment]
Hi,

Can you show this in a jsbin? Without code I can't really help you here. 

Regards

**Comment by randomilla** [comment]
Sorry for the late response here it is what I have done : https://jsbin.com/wasevowobi/edit?html,output for some reason it says vis is not defined but at my server runs smoothly except the problem with the cluster

**Comment by josdejong** [comment]
@randomilla your browser probably blocks loading http://visjs.org/dist/vis.js because it's not served over https. Try https://cdnjs.cloudflare.com/ajax/libs/vis/4.14.0/vis.min.js instead.

**Comment by randomilla** [comment]
@josdejong  thank you the script now is running but the problem with the releasefunction is the same
Here is the link again https://jsbin.com/nuvado/edit?html,output .I have follow the example that is within the documentation.Maybe I misread something I do not know.Any help?

**Comment by AlexDM0** [comment]
Hi,

You have indeed misread something.. sort of.. I'm going to guess you're relatively new to JavaScript.

You do this:
```
network.openCluster(params.nodes[0],releaseFunction(params.nodes[0],nodesData));
```

The point is that you pass a callback, youre evaluating a function and returning something whereas the openCluster method looks for an object like:
```
{
  releaseFunction: function (...) {...}
}
```

So what you should do:

```
network.openCluster(params.nodes[0],{releaseFunction: releaseFunction});
```

with:

```
function releaseFunction (clusterPositoin,nodePositions) {
  return nodePositions;
}
```

Regards
