### ISSUE TITLE
How can I avoid an overlapping

### ISSUE THREAD

**Issue by noorbakerally** [almende/vis#1662]
I have two graphs which is overlapping, is there anything like node distance to solve this,

a picture of the problem can be found here, https://dl.dropboxusercontent.com/u/108022472/rdf.png 
thanks

**Comment by AlexDM0** [comment]
I cant see your image. If its the hierarchical layout, it could be fixed on the develop branch.

**Comment by noorbakerally** [comment]
I don't know why when clicking on it, it is not showing, copy it in the browser address bar, you should see it, https://dl.dropboxusercontent.com/u/108022472/rdf.png

**Comment by The-Penultimate-Defenestrator** [comment]
The way I deal with this in my project is just a line wrap function, but that's for data I don't control. It helps  a little with really long titles to limit the line length.

**Comment by noorbakerally** [comment]
No, the problem isn't about lines characters, ok, for e.g. suppose I have two graphs, in Graph1 Node1->Node2 and in Graph2 Node3->Node4, Graph1 and Graph2 are completely disconnected, but when when the nodes are stabilizing after initial load, Graph1 is coming over Graph2, is there anywhere to set a distance between disconnected graphs so that they don't overlap each other ?

**Comment by AlexDM0** [comment]
I'd recommend playing with the physics settings to find a good amount of repulsion to fix the overlap. Additionally you can increase the mass of big nodes, making them more repellant for others.

**Comment by mojoaxel** [comment]
closed due to inactivity
