### ISSUE TITLE
Negative centralGravity

### ISSUE THREAD

**Issue by The-Penultimate-Defenestrator** [almende/vis#1663]
## Problem
If I set in my Network's options:

```
physics: {
  barnesHut: {
    centralGravity:-0.3,
  },
}
```

I get some unexpected behavior: the nodes fly off the screen. 

## Why I want to use negative centralGravity
By default, new nodes are pulled towards the center, in an effort to keep the network localized. I want the network to naturally spread out as it expands. My use case involves frequently adding new nodes to the network, and I'd like these to tend to spread out from the center, instead of staying near the center.

## Reproducing
See [this fiddle](https://jsfiddle.net/luketaylor/51n8eb0c/) for an example. You might need to move one of the nodes a little.

**Comment by AlexDM0** [comment]
if you want it to spread out, fix a single node that is connected to the others. What do you expect to happen if you introduce a repulsive force from the center out?

**Comment by The-Penultimate-Defenestrator** [comment]
I do have a fixed central node. The problem is that when I add new nodes, they're pulled inward sharply before spreading out.

**Comment by AlexDM0** [comment]
Is your central node at 0,0? Maybe show the actual issue then :)

**Comment by The-Penultimate-Defenestrator** [comment]
Compare a before and after of adding new nodes to an existing node. It causes the existing node to be pulled towards the center.

Before:
![](http://i.imgur.com/p66COXv.png)
After:
![](http://i.imgur.com/K1IF6Hr.png)

When nodes are added as connections to it, "Random House Dictionary" is pulled toward the center. I'd like it to be pulled away from the center.

**Comment by AlexDM0** [comment]
Increase the gravitational repulsion. Central gravity is only there for centering. The rest should be done using repulsion.

**Comment by The-Penultimate-Defenestrator** [comment]
OK, thanks.

**Comment by AlexDM0** [comment]
Alternatively, disable central gravity and manually set a position

**Comment by The-Penultimate-Defenestrator** [comment]
Manually set positions for each node?

**Comment by AlexDM0** [comment]
Only the new ones. set the damping up reasonably high and give it a good starting position. If need be place it on top of the node spawning it.

**Comment by The-Penultimate-Defenestrator** [comment]
This sounds like a good idea, I'll look into this. Thanks for your help.

**Comment by AlexDM0** [comment]
You're welcome. Have fun!

**Comment by The-Penultimate-Defenestrator** [comment]
@AlexDM0 I seem to remember you suggesting a specific method by which I could
> set a good starting position

which I remember involving finding the center of gravity by averaging node positions and then spawning the nodes with an initial position out from this node. Was it you who said that? Where was that said? I can't see it here...

**Comment by AlexDM0** [comment]
In your wiki showcase.
