### ISSUE TITLE
Muting object prototype

### ISSUE THREAD

**Issue by mjmcdaniels** [almende/vis#1664]
Encountering a warning that may or may not have impact. Just making the team aware.

mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create vis.min.js:36:21358

**Comment by josdejong** [comment]
Thanks for reporting. This message is given in Firefox. The mutation of __proto__ is done by the class polyfill of babel, we can't do anything about that here.

**Comment by mojoaxel** [comment]
see also https://bugzilla.mozilla.org/show_bug.cgi?id=984146
