### ISSUE TITLE
Network tool tip not working

### ISSUE THREAD

**Issue by shafqatjan** [almende/vis#1665]
Please help tool tip is not working in my site,
[Login](http://mytest.shafqat.tapcrowd.com/site/login)
Please goto link and use U: testlib P: 123456
than please go to [Network](http://mytest.shafqat.tapcrowd.com/user/network )

**Comment by AlexDM0** [comment]
Hi, 

Tooltips are working in our examples. 

http://visjs.org/examples/network/events/interactionEvents.html

Unless you can show the fault is in vis we cannot help you as we're not a general purpose debugging helpdesk.

Regards

**Comment by shafqatjan** [comment]
Therw is no any error showing but tooltip doesnot shows i have configure as shown in example but some shows sometime not shows. What to do?

**Comment by AlexDM0** [comment]
Try setting the delay to 0. Otherwise, debug :)

**Comment by shafqatjan** [comment]
When we zoom it show on particular zoom than it disappear.

**Comment by AlexDM0** [comment]
Well yes. tool tips, by definition, appear when you hold your mouse steady over a node. If you move it, it disappears. That's what it is supposed to do. If you want a different behavior you can make custom tooltips. There are numerous issues on this here, including code. 

Good luck

**Comment by shafqatjan** [comment]
I know it appeara qhen we do mouse hover tool tip appears, problem is not showing . sometime it shows circle tooltip of connector of two circle n some time line toolrtip showa hover circle

**Comment by shafqatjan** [comment]
Can you try one to go to example of website please

**Comment by AlexDM0** [comment]
Fine.

```

var nodes = null;
var edges = null;
var network = null;

function destroy() {
	if (network !== null) {
		network.destroy();
		network = null;
	}
}

function draw() {
	destroy();
	
	// create an array with nodes
	nodes = [{"id":389,"label":"Andreas Nelissen"},{"id":21,"label":"Bart VDH","value":49},{"id":407,"label":"barttestadmin","value":2},{"id":368,"label":"Eddy Stevens","value":2},{"id":387,"label":"Ellen Cooper","value":4},{"id":369,"label":"Hillary Simpson","value":4},{"id":367,"label":"John Deere","value":3},{"id":293,"label":"Shafqat admin","value":9},{"id":235,"label":"Shafqat readonly"},{"id":375,"label":"Shafqat Yahoo","value":13},{"id":401,"label":"Test Supper admin"},{"id":386,"label":"test user pact value"},{"id":441,"label":"testlibrary"}];
	
	// create an array with edges
	edges = [{"from":368,"to":21,"value":8},{"from":369,"to":21,"value":6},{"from":367,"to":21,"value":7},{"from":386,"to":21,"value":1},{"from":21,"to":368,"value":8},{"from":369,"to":368,"value":6},{"from":367,"to":368,"value":5},{"from":235,"to":368,"value":3},{"from":386,"to":368,"value":3},{"from":21,"to":369,"value":6},{"from":368,"to":369,"value":6},{"from":367,"to":369,"value":3},{"from":235,"to":369,"value":2},{"from":386,"to":369,"value":1},{"from":21,"to":367,"value":7},{"from":368,"to":367,"value":5},{"from":369,"to":367,"value":3},{"from":386,"to":367,"value":2},{"from":368,"to":235,"value":3},{"from":369,"to":235,"value":2},{"from":21,"to":386,"value":1},{"from":368,"to":386,"value":3},{"from":369,"to":386,"value":1},{"from":367,"to":386,"value":2}];
	
	// create a network
	var container = document.getElementById('mynetwork');
	var data = {
		nodes: nodes,
		edges: edges
	};
	var options = {
		interaction: {
			hover:true,
			navigationButtons: true,
			keyboard: true
		},
		nodes: {
			shape: 'dot',
		},
	};
	network = new vis.Network(container, data, options);
}
$( document ).ready(function() {
draw();
});
```

I do not see the option title anywhere. Take a look at the data format of the nodes for popups or the documentation. Next time please put your code in a JSBin, I have better things to do then hunt for your code.

Regards
