### ISSUE TITLE
Overlapping bars in 3D bar graph

### ISSUE THREAD

**Issue by Nithish-Bharadwaj** [almende/vis#1667]
Let's say the X-axis represent my nodes, Y-axis represent the last 5 hours and Z-axis represent the value. There can be hours when there are no readings for a node which I want to be represented as empty spaces. This works as expected if the first node has data for all the hours and the consequent nodes have data missing for some hours.
[This](http://jsfiddle.net/xrakvgrw/4/) example fiddle demonstrates it considering only 2 nodes.

Now if the first node is missing data at the second hour, the rendering get's screwed up with bars overlapping each other while rotating the graph.
[This](http://jsfiddle.net/xrakvgrw/3/) fiddle demonstrates the same.

The weird part if that if you modify the data population and instead of skipping the data for the 2nd hour, skip it for any other hour, the graph renders perfectly.
[This](http://jsfiddle.net/xrakvgrw/5/) fiddle demonstrates the same.

I have made a temporary workaround by having an extra dummy node in the beginning where all values for the z-axis are set to 0 and I have modified the _redrawDataBar method to set hue, saturation and value corresponding to white when the point.point.z is 0.

Would like to know if it's indeed a bug.

**Comment by josdejong** [comment]
If not configured, Graph3d automatically detects the bar width based on the distance between the first and second bar. You can configure the bar width manually:

```js
var options = {
  yBarWidth: 1, 
  yBarWidth: 1,
  // ...
}
```

**Comment by Nithish-Bharadwaj** [comment]
Aha! Thanks Jos.
