### ISSUE TITLE
Edge reset problem

### ISSUE THREAD

**Issue by bar4mi** [almende/vis#1668]
I have a problem with edge reset. I'm making a simple path highlight function. I referenced the function neighbourhoodHighlight. It works good before reset update. After undefined nodes' color and edges' color & arrows nodes recover its default color, but edges do not. I tried to fix this problem hardly. Now I don't have no idea why those color and arrows are not recover it's original status. I uploaded a sample code to jsfiddle https://jsfiddle.net/84r00p8b/2/. I need help!

**Comment by AlexDM0** [comment]
Hi,

What am I supposed to see in the fiddle?

Regards

**Comment by AlexDM0** [comment]
http://visjs.org/docs/network/edges.html

look for large bold text for tips

**Comment by bar4mi** [comment]
Dear Alex,

Thank you for your quick reply! Although I read it, I could think it's problem is related with the option, it's description is bold tough. I spent a whole day to solve it. Thank you very much!


Best regards,
Simon

나의 iPhone에서 보냄

2016. 2. 18. 오후 6:07 Alex <notifications@github.com> 작성:
