### ISSUE TITLE
Quality of png image scaling in Network

### ISSUE THREAD

**Issue by antonbagayev** [almende/vis#1672]
Hi,

Thank you for the awesome library!
I am an image rendering noob, so apologies if I am asking a silly question.
I am using png images in my application that are medium-sized (roughly 400x300 or 500x400). 
Here is an example:
![womens 1](https://cloud.githubusercontent.com/assets/3300651/13148328/e7952c14-d62a-11e5-94c1-37254b70f5cf.png)

When this image is scaled by my browser for img tag it looks decent:
![image](https://cloud.githubusercontent.com/assets/3300651/13148382/2267e96c-d62b-11e5-9a1c-4d704bdd14d3.png)

but when the Network is scaling it for a node it looks bad:
![image](https://cloud.githubusercontent.com/assets/3300651/13148416/3f664aa4-d62b-11e5-8659-9c267b28b12a.png)

Anything I can do to tell Network to use the same rendering technique as the browser when scaling down my pngs?

Any help is appreciated
Thanks,
Anton.

**Comment by AlexDM0** [comment]
Hi,

I've looked into this and implemented image interpolation. It should be much nicer now. It will be on by default but naturally it is a little more expensive.

It will be added to the next release.

Cheers

**Comment by antonbagayev** [comment]
Thank you! Looking forward to the next release.
