### ISSUE TITLE
How do i create a timeline chart just of one day ?

### ISSUE THREAD

**Issue by sharathbangera6** [almende/vis#1675]
Hi,

I want to create a timeline chart which just shows the timeline of one full day. I don't want to show any other Dates, like right now when you zoom out on example charts,  it shows from time to day and it goes to month and so on... Is there any way to show range like y'dy 23:00 to today 23:00 only ? may be disable zoom out but keep zoom in, cos i want to zoom in from hour to minutes and so on.

It would be really helpfull if you can help me out here.

**Comment by sharathbangera6** [comment]
Update : to answer my own question i have found **ZoomMax **which can be used for the same purpose, but i have one more question, can i disable the **moveable** i.e set to false when ZoomMax has Reached ? i don't want user to move to previous date.

**Comment by josdejong** [comment]
There are options `zoomMin`, `zoomMax`, `min`, and `max` for this. If you want to have the timeaxis in hours rather than automatically determined, you can do so with the options `timeAxis.scale` and `timeAxis.step`, just check out the docs and examples.

**Comment by aseemgautam** [comment]
You can use the following options to create it for one day with 2 hour time axis - 
```javascript
function getOptions(zoomMax, zoomMin) {
        return {
            groupOrder: 'content',
            start: moment().startOf('day'),
            end: moment().endOf('day'),
            min: moment().startOf('day'),
            max: moment().endOf('day'),
            showCurrentTime: false,
            showMajorLabels: false,
            autoResize: true,
            margin: { axis: 5, item: { vertical: 10, horizontal: 0 } },
            //zoomMax: zoomMax, //milliseconds
            //zoomMin: zoomMin,            
            timeAxis: {scale: 'hour', step: 2},
            type: 'range'
        };
    }
```
