### ISSUE TITLE
Changing group dynamically doesn't redraw the object

### ISSUE THREAD

**Issue by falbuisech** [almende/vis#1677]
Hi, my problem is when creating dynamically networks. If I add nodes I can perfectly select a group for it to be represented (p.e.g. a router icon). It is saved in locale without problem, but when I change the node's group via editNode, it changes in locale but no in the interface, whereas the label or ID changes in both.
I think it's a problem with some redraw.

          addNode: function (data, callback) {
            // filling in the popup DOM elements
            document.getElementById('operation').innerHTML = "Add Node";
            document.getElementById('node-id').value = data.id;
            document.getElementById('node-label').value = data.label;
            document.getElementById('node-group').value = data.group;
            document.getElementById('saveButton').onclick = saveData.bind(this, data, callback);
            document.getElementById('cancelButton').onclick = clearPopUp.bind();
            document.getElementById('network-popUp').style.display = 'block';
          },
          editNode: function (data, callback) {
            // filling in the popup DOM elements
            document.getElementById('operation').innerHTML = "Edit Node";
            document.getElementById('node-id').value = data.id;
            document.getElementById('node-label').value = data.label;
            document.getElementById('node-group').value = data.group;
            document.getElementById('saveButton').onclick = saveData.bind(this, data, callback);
            document.getElementById('cancelButton').onclick = cancelEdit.bind(this,callback);
            document.getElementById('network-popUp').style.display = 'block';
          },

**Comment by AlexDM0** [comment]
Hi,

It would be great if you can show this is a jsbin so we can easily reproduce this. 

Regards

**Comment by falbuisech** [comment]
I simply  modified the example \node_modules\vis\examples\network\other\manipulation.html adding some groups and the option to change them. I attach the file as a .txt
[manipulation - copy.txt](https://github.com/almende/vis/files/139598/manipulation.-.copy.txt)


I'm sorry but I'm pretty new in this so I don't know how to use properly Jsbin

**Comment by AlexDM0** [comment]
I see what you mean now. I've pushed a fix to develop, it should be added in the next release.

Regards
