### ISSUE TITLE
Hierarchical Layout Bug : v4.14

### ISSUE THREAD

**Issue by PatMartin** [almende/vis#1679]
Here is a [jsbin which shows a couple of issues](https://jsbin.com/jacofurohu/3/edit?html,css,js,console,output) with Hierarchical Layout on a larger dataset.

1. The nodes are laid on top of each other and require interaction in order to separate.
2. For some reason, the last hierarchy is rendered way at the bottom of the page.

Love the work you are doing!

Thanks,

- Pat

**Comment by AlexDM0** [comment]
Hi Pat,

There have been a number of these issues and they have been fixed on the develop branch. Could you see if that version also fixed your issues?

Regards

**Comment by PatMartin** [comment]
I am willing, but don't know what to do. What vis.js and vis.css do I point to?

Thanks,

- Pat

**Comment by AlexDM0** [comment]
Hi Pat,

Sorry about that, we sometimes forget not everyone is using git :)

This is the built file from the develop branch:
https://github.com/almende/vis/blob/develop/dist/vis.js

and to use it in JSBin you have to use rawgit:
https://rawgit.com/

which gives you an url that you can use there.

Regards

**Comment by PatMartin** [comment]
The dev branch indeed seems to fix the issue.

https://jsbin.com/lidodeqigo/1/edit?html,css,js,console,output

Thanks Alex!
