### ISSUE TITLE
Unexpected node size and label font size of network graph

### ISSUE THREAD

**Issue by stanleyxu2005** [almende/vis#1681]
I'm trying to upgrade 4.7.0 to 4.14.0. I found existing code is broken. Here is one observation: I have created a graph with two nodes, if I remove `layout` section from option, the node size will be different. **Please use [the demo](https://jsfiddle.net/koxqd0zj/2/) to check. The [previous demo](https://jsfiddle.net/koxqd0zj/) was incorrect.**

In my real application, I have set global node font size to 13, but the text is extremely large. When I create my first node, it uses roughly 50% space of the graph. When I create the second node, it will be put somewhere out of the graph. I have to zoom out to see it. The 4.7.0 version does not have the issue.

**Comment by stanleyxu2005** [comment]
**Image 1: 4.7.0 create first node**
![4 7 0-first](https://cloud.githubusercontent.com/assets/5162687/13212488/8f41bfa0-d97c-11e5-8194-da83a7d96cff.png)

**Image 2: 4.7.0 create second node (the first node will be push to aside but its size is not change)**
![4 7 0-second](https://cloud.githubusercontent.com/assets/5162687/13212489/916a67aa-d97c-11e5-8ea8-7d088502ed84.png)

**Image 3: 4.14.0 create first node (extremely large but the options are the same)**
![4 14 0-first](https://cloud.githubusercontent.com/assets/5162687/13212490/9447c562-d97c-11e5-9bdd-f3079a8c3a42.png)

**Image 4: 4.14.0 create second node after zoom out (You can see the position and size of nodes are different from 4.7.0's result)**
![4 14 0-second_after_zoom_out](https://cloud.githubusercontent.com/assets/5162687/13212493/96590168-d97c-11e5-9d17-9b8adb182c47.png)

**Comment by AlexDM0** [comment]
Hi,

It looks like the size is about the same except the initial zoom is different. 

Since placement is random it can be that the initial layout has changed. Especially since you come from 4.7, there have been many changes to the layout algorithms. You can disable improvedLayout and adaptiveTimestep to not use them. 

Regards

**Comment by AlexDM0** [comment]
I also notice you're using hierarchical layout. That algorithm has also been updated and there are a few bugs that will be fixed in 4.15. 

You cannot go back to the old hierarchical layout algorithms. Take a look at the new example using the new ones, it's really fast!

**Comment by stanleyxu2005** [comment]
The network of the screenshot does not configure physics. Here is the full options:
```
{
          autoResize: true, // The network will automatically detect size changes and redraw itself accordingly
          interaction: {
            hover: true
          },
          width: '100%',
          height: height,
          nodes: {
            shape: 'dot',
            font: {
              size: 13,
              face: fontFace,
              strokeColor: '#fff',
              strokeWidth: 5
            }
          },
          edges: {
            arrows: {
              to: true
            },
            font: {
              size: 11,
              face: fontFace,
              align: 'middle'
            },
            color: {
              opacity: 0.75
            },
            smooth: true
          }
        };
```

**Comment by AlexDM0** [comment]
There are changes to the defaults.

**Comment by stanleyxu2005** [comment]
I tried the options you mentioned in the earlier answer, but they did not change anything. Do you have a clue how to change the default settings?

**Comment by AlexDM0** [comment]
Hi,

You can't always change the default settings. As I told you, hierarchical has changed and will not be changed back. Your images imply different zoom levels not different node sizes and the physics is well documented so play around with it to see what works for you. 

Regards

**Comment by stanleyxu2005** [comment]
Sorry @AlexDM0 I have referenced a wrong demo page. Here is a demo shows the problem. https://jsfiddle.net/koxqd0zj/1/

**Comment by AlexDM0** [comment]
I'm not sure I see the problem?

**Comment by stanleyxu2005** [comment]
The demo will first create node "First". In 2 seconds it will create the second node "Second". But the second node is out of the canvas.

**Comment by AlexDM0** [comment]
its not out of the canvas, its out of the view. You can manually call fit
after you have stabilized the network if you want, or give it a position,
or reduce the max velocity in the physics..

**Comment by stanleyxu2005** [comment]
I have updated my example https://jsfiddle.net/koxqd0zj/2/
It will print some logging messages.

I think the initial font size is not what I have set in the global settings. This is the initial question of the issue. You might check the example and replace the js file with 4.7.0 version. You will understand what I am saying.

**Comment by stanleyxu2005** [comment]
I have updated my example https://jsfiddle.net/koxqd0zj/2/
* It will first create a node (which is sightly larger than it is in 4.7.0)
* It will create a second node in 2 seconds, but it is shown somewhere out of the visible area (I have found no way to fix the problem by tuning options)

It seems the initial font size of node is NOT what I have set in the global settings. You might replace the vis.js with 4.7.0 version to see the difference.

**Comment by AlexDM0** [comment]
It is what you set there. There have been changes since 4.7 but there is no bug here and it will not be adressed. If you dont like the way it looks or behaves, change it.

Regards

**Comment by stanleyxu2005** [comment]
Hmm. Will you give the same answer, if the question is "**When I create a node with size=13 and fontSize=13, its size looks quite different in 4.7 and 4.14. What is node size equals 13 stands for?**"

[4.7](https://cloud.githubusercontent.com/assets/5162687/13212488/8f41bfa0-d97c-11e5-8194-da83a7d96cff.png)
[4.14](https://cloud.githubusercontent.com/assets/5162687/13212490/9447c562-d97c-11e5-9bdd-f3079a8c3a42.png)

**Comment by AlexDM0** [comment]
The size is an arbitrary unit larger values linearly make the node bigger. And yes, the answer is the same.

**Comment by stanleyxu2005** [comment]
Thanks for your answer. And I really appreciate other great improvements since 4.7.

**Comment by AlexDM0** [comment]
Hi,

As I said, the network was zoomed in. You can try to load the network with a single node already there.

Regards

**Comment by stanleyxu2005** [comment]
Oh cool. Instantiate network with one node solves this problem. Thanks.
