### ISSUE TITLE
Support scrolling the items and not the time "bar" for timelines

### ISSUE THREAD

**Issue by Ageris** [almende/vis#1683]
I'd love to be able to set an option so that the timeline scrolls the events and not the red time-"bar" so that you can follow "now" along the timeline without scrolling manually.

For now we are using a timeout and the same calculation used inside to update the scroll position every interval, but this is problematic as we can never really sync our update with the timelines "tick". If it were possible to set an option like this that would eliminate the need for our "hack".

Ideally we'd like to have the option of specifying where in the view to place the "now" marker. For example if we freeze the scale at 24 hours the now marker should be placed one hour to the right of the edge so that most of the viewport shows future events.

Alternatively one could implement an event "onTick" that we can listen for and then fire our re-positioning logic there.

**Comment by josdejong** [comment]
You could override the method of the CurrentTime which schedules these redraws, [CurrentTime.start](https://github.com/almende/vis/blob/master/lib/timeline/component/CurrentTime.js#L119-L138). You could also adjust the logic for it if needed (it maybe heavy to redraw the Timeline with 30fps).

http://jsbin.com/foqocar/edit?html,output

```js
  // override the currentTime.start method
  timeline.currentTime.start = function() {
    var me = this;

    function update () {
      me.stop();

      // determine interval to refresh
      var scale = me.body.range.conversion(me.body.domProps.center.width).scale;
      var interval = 1 / scale / 10;
      if (interval < 30)   interval = 30;
      if (interval > 1000) interval = 1000;

      console.log('tick')
      // me.redraw(); // originally, only the currentTime bar is redrawn
      timeline.moveTo(new Date(), {animation: false});// move the whole Timeline instead

      // start a renderTimer to adjust for the new time
      me.currentTimeTimer = setTimeout(update, interval);
    }

    update();
  }
  timeline.currentTime.start();
```

**Comment by Ageris** [comment]
I thought about doing something like that, but I'd like to avoid overriding anything if at all possible.

I found the event emitter feature and thought I could simply emit a "tick" event or something similar. This appears to work perfectly in local tests.

Here is my modification:
`CurrentTime.prototype.start = function() {
  var me = this;

  function update () {
    me.stop();

    // determine interval to refresh
    var scale = me.body.range.conversion(me.body.domProps.center.width).scale;
    var interval = 1 / scale / 10;
    if (interval < 30)   interval = 30;
    if (interval > 1000) interval = 1000;

    me.redraw();
    me.body.emitter.emit('currentTimeTick');

    // start a renderTimer to adjust for the new time
    me.currentTimeTimer = setTimeout(update, interval);
  }

  update();
};`

**Comment by josdejong** [comment]
Hm, yeah ok. I was just wondering if it's worth creating an event for this (feature creep) but well, it's just one line of code.

**Comment by josdejong** [comment]
It's implemented in the `develop` branch now.

**Comment by Ageris** [comment]
Completely understandable. It all starts with that "one line of code" ;)

Maybe it's just me, but I would have thought an auto-scrolling timeline would be a more common request though.

It might be better to implement this in some other way, but for simplicity this worked just fine for us. We also have a case where any user modifications stop the timeline from scrolling (lock/unlock) and this can be easily achieved if we control the moveTo code in a separate function.

**Comment by josdejong** [comment]
I think this `currentTimeTick` event in combination with `moveTo` is best: it allows you to do things the way you want, maybe you want to see the currentTime in the middle of the screen, maybe at 3/4th, or maybe you want to sync other things on your page as well. This way you have all freedom to do that.

**Comment by pliablepixels** [comment]
Out of curiosity, how does one moveTo 3/4 of the screen easily ?
I'm doing:
```
timeline.on ('currentTimeTick', function () {
                                if ($scope.followCurrentTime)
                                    timeline.moveTo(timeline.getCurrentTime());
```

**Comment by pliablepixels** [comment]
So I looked at the implementation of moveTo and replicated it instead of calling it, so I can change the half way point to another point. But changing 0.5 to say 0.7 below doesn't seem to move the red bar to 70% of the displayable range. What am I missing? Thanks

```
if ($scope.follow.time)
                                {
                                    var w = timeline.getWindow();
                                    var pos =  (moment(w.start) + moment(w.end)) * 0.5;
                                    var diff = pos - moment(timeline.getCurrentTime());
                                    var ns = moment(w.start) - diff;
                                    var ne = moment(w.end) - diff;
                                    timeline.setWindow(ns, ne);
                                    //timeline.moveTo(timeline.getCurrentTime());
                                }
```

**Comment by mojoaxel** [comment]
> What am I missing? Thanks

If you have a question please try [stackoverflow](http://stackoverflow.com/tags/vis.js) or create a new issue. This issue is closed.
