### ISSUE TITLE
 Add a horizontal scrollbar Timeline

### ISSUE THREAD

**Issue by LexaDel** [almende/vis#1686]
Hi! It's not clear that you can scroll timeline chart (to left or right) on iPad. Could you add property for show horizontal scrollbar? Or maybe it's possible to do by myself, so how can I do it? Could you help me?

**Comment by brichbe** [comment]
A horizontal scroll bar doesn't make much sense for the timeline -- especially if your timeline is unbounded.  Sounds like your goal is to make an easy, more obvious way to incrementally shift the visible window of the timeline left and right, so your better option would be using controls/buttons, such as the 'Move left'/'Move right' buttons on the example:  http://visjs.org/examples/timeline/interaction/navigationMenu.html    If your timeline is bounded by a `min` and `max` date, then you could add additional controls/buttons that shift immediately over to those bounds.

**Comment by LexaDel** [comment]
thanks
