### ISSUE TITLE
Error when wrapping timeline in angular directive

### ISSUE THREAD

**Issue by Seiifer** [almende/vis#1688]
So, the following code works fine :
```html
 <div id="dashboardActiveTimeLineContainer"></div>

 <div id="dashboardTimeLineContainer"></div>
```
I got my 2 timelines displayed.

But when I do that, in order to display only one :
```html
<div ng-show="!d.showAllRequests">
  <div id="dashboardActiveTimeLineContainer"></div>
</div>

<div ng-show="d.showAllRequests">
  <div id="dashboardTimeLineContainer"></div>
</div>
```
(Or using `ng-show` or `ng-hide` directly in the container `<div>`)

I'm getting :
```sh
Error: Invalid start "NaN"
    at Component.Range._applyRange (vis.js:14016)
    at Component.Range.setRange (vis.js:13977)
    at Core.Timeline.fit (vis.js:10806)
    at Core.Timeline.setItems (vis.js:10670)
    at Core.Timeline (vis.js:10577)
    at dashboard.js:108
    at deferred.promise.then.wrappedCallback (angular.js:11722)
    at angular.js:11808
    at Scope.$get.Scope.$eval (angular.js:12851)
    at Scope.$get.Scope.$digest (angular.js:12663)
```

Some js :
```js
var dataItems = new vis.DataSet(statusesArray);
var activeDataItems = new vis.DataSet(activeStatusesArray);

if (controllerScope.timeline)
   controllerScope.timeline.destroy();
if (controllerScope.activeTimeline)
   controllerScope.activeTimeline.destroy();

controllerScope.timeline = new vis.Timeline(controllerScope.container, dataItems, groups, controllerScope.timeLineOptions);
controllerScope.activeTimeline = new vis.Timeline(controllerScope.activeContainer, activeDataItems, activeGroups, controllerScope.timeLineOptions);
```
Both timeline are constructed the same way, the active one just got a condition to filter some data applied on `statusesArray` and `activeGroups`

**Comment by josdejong** [comment]
did you have a look at https://github.com/visjs/angular-visjs ?

**Comment by Seiifer** [comment]
At first I tried it, but I had too many issue to solve and switch back to this one since it worked just fine.

Also, in this case, when clicking on the error in the console, the part of the file I'm redirected to is the `controllerScope.timeLineOptions` of the second timeline.
(It is set to `{align: 'center', stack: false}`) Could there be anything to change to the options when using several timelines ?

**Comment by josdejong** [comment]
One thing that pops up in my mind is that this could be related to #1580, which was fixed a month ago in v4.13.0. Are you using the latest version of vis.js?

**Comment by Seiifer** [comment]
You are correct.

I was using 4.10.0 in my package.json (somehow I had 4.12.0 in my node_modules), I just tried it out with the 4.15.0 and it's working fine.

Thanks

**Comment by josdejong** [comment]
awesome :)
