### ISSUE TITLE
stop stabilization?

### ISSUE THREAD

**Issue by admhemed** [almende/vis#1689]
in network, is there a way to stop stabilization grammatically?  thanks

**Comment by AlexDM0** [comment]
like with the options?

**Comment by admhemed** [comment]
yes maybe

**Comment by admhemed** [comment]
I add more nodes to the network on mouse click, and user waits long time until they can click further nodes because it keeps moving for stabilization. 
I wish I could provide a button, (maybe with keyboard shortcut) to stop stabilization

**Comment by AlexDM0** [comment]
Well, you can manually trigger the stabilization using the provided methods. Once its running you cannot stop it. You can do batches with a lower number of iterations.

**Comment by admhemed** [comment]
would you please provide an example on how to trigger stabilization manually?

**Comment by AlexDM0** [comment]
```
network.stabilize(numberOfIterations)
```
Please take a look at the documentation.
