### ISSUE TITLE
Graph2d: Error when y-axis values are equal (updated)

### ISSUE THREAD

**Issue by Noodlewood** [almende/vis#1692]
On a dataset with items, which all have the same value on the y-axis 
the graph isnt plotted and "Error: Invalid value for ..." exception is thrown.

Update:
I was able to find problem in the DataScale.prototype.determineScale function.
If you have the same Values for all Nodes the range is zero.
A logarithm of zero leads to -infinity;

```
DataScale.prototype.determineScale = function () {
    var range = this._end - this._start;
    this.scale = this.containerHeight / range;

    var minimumStepValue = this.majorCharHeight / this.scale;
    var orderOfMagnitude = Math.round(Math.log(range)/ Math.LN10);

    ...
```

Is my observation correct?
Would be nice if this could be fixed.

For example:
````
    if (range > 0) {
      var orderOfMagnitude = Math.round(Math.log(range) / Math.LN10);
    } else {
      var orderOfMagnitude = 0;
    }
```

**Comment by josdejong** [comment]
Thanks for figuring this out, I've fixed the error in the `develop` branch.
