### ISSUE TITLE
Not working on Chrome

### ISSUE THREAD

**Issue by rgrcnh** [almende/vis#1696]
Hello,
I'am using vis.js wrapped by angular-vis.js and angular as a client MVC.
The application I did is working on firefox but is is stucked on Chrome.
This is all versions I am using:
  "dependencies": {
    "angular": "^1.5.0",
    "angular-route": "^1.5.0",
    "angular-resource": "^1.5.0",
    "angular-bootstrap": "^1.1.2",
    "bootstrap-css-only": "^3.3.6",
    "vis": "^4.15.0",
    "angular-visjs": "^4.0.2",
    "angular-animate": "^1.5.0"
  }
And this is the error on Chrome console (the app starts but the network graph does not show up)
TypeError: Cannot create property 'enabled' on boolean 'true'
    at Object.exports.mergeOptions (vis.js:1397)
    at Function.parseOptions (vis.js:32349)
    at EdgesHandler.setOptions (vis.js:31577)
    at Network.setOptions (vis.js:27869)
    at new Network (vis.js:27835)
    at angular-vis.js:136
    at m.$digest (angular.js:16664)
    at m.$apply (angular.js:16928)
    at g (angular.js:11266)
    at t (angular.js:11464)

I can arrange more infos if needed.
Sincerely
Roger

**Comment by josdejong** [comment]
yeah, more information would be welcome. First we have to figure out how to reproduce this issue and see if it originates from the angular directive or from the JS library itself.

**Comment by sawajid** [comment]
you can refer these for additional info
https://bugs.chromium.org/p/v8/issues/detail?id=4929
https://github.com/angular/angular.js/issues/14460

**Comment by Tooa** [comment]
Is this still an issue for you? I successfully used visjs with angularjs and chrome myself in the past.

**Comment by rgrcnh** [comment]
It is working, thx for asking!
