### ISSUE TITLE
Regression: On editing an edge, the red-dot indicator no longer moves and neither does the edge

### ISSUE THREAD

**Issue by saukap** [almende/vis#1700]
On upgrading to visjs 4.13 from 4.12 we find that when interactively moving an edge from one node to another, the user no longer gets visual feedback - the red dot and the edge no longer drag along with the mouse.

**Comment by AlexDM0** [comment]
Hi,

This is fixed in the newer versions. Try 4.15 if youre upgrading anyway.

Regards

**Comment by saukap** [comment]
Thanks, I should have checked with the latest version before filing this. 
On upgrading to 4.15 things are fine.
