### ISSUE TITLE
Any way to make timeline items scale to fit height?

### ISSUE THREAD

**Issue by tuckwat** [almende/vis#1701]
First off thanks for the amazing project, I haven't touched the Network or Graphing components but the Timeline has been a joy to work with.

I'm currently using a timeline in a resizable widget which the timeline fits both horizontally and vertically.  Is it possible to scale the height of items to auto-fit the height of the timeline? For example, if my timeline height is 400px and I've got 4 non-stacking subgroups, each item height would need to be 100px (ignoring margins, axes, etc.).  

Here's an example which needed an item height of roughly 64px to fit.  http://jsfiddle.net/w0xd93d8/.  If the container height increased or decreased in size that would need to change.

**Comment by josdejong** [comment]
Thanks. 

You can create custom types of items for that if you want. Probably background areas come close to what you're looking for (they have 100% height), see this example:

http://visjs.org/examples/timeline/items/backgroundAreas.html

It will require some programming though if you want to create a custom item type.

**Comment by yotamberk** [comment]
@tuckwat Is this issue still relevant? Can we close this issue?
