### ISSUE TITLE
Timeline not working with react js

### ISSUE THREAD

**Issue by RamonBeast** [almende/vis#1704]
I created a quick component to integrate the Timeline into a react js app. This is the component:

```
import React, { Component, PropTypes } from 'react';
import vis from 'vis';

export default class Timeline extends Component {
  constructor(props) {
    super(props);

    this.updateGraph = this.updateGraph.bind(this);
  }

  componentDidMount() {
    this.updateGraph();
  }

  componentDidUpdate() {
    this.updateGraph();
  }

  updateGraph() {
    var container = document.getElementById('vis-timeline');

    // Options
    var options = {
      height: 250, // px
    };

    var items = new vis.DataSet([{
      id: 1,
      content: 'First event',
      start: '2014-08-01'
    }, {
      id: 2,
      content: 'Pi and Mash',
      start: '2014-08-08'
    }, {
      id: 3,
      content: 'Wikimania',
      start: '2014-08-08',
      end: '2014-08-10'
    }, {
      id: 4,
      content: 'Something else',
      start: '2014-08-20'
    }, {
      id: 5,
      content: 'Summer bank holiday',
      start: '2014-08-25'
    }]);

    var timeline = new vis.Timeline(container, items, options);
  }

  render() {
    return (<div id="vis-timeline"> </div>);
  }
}
```

After rendering the page I get this message:

> Something is wrong with the Timeline scale. Limited drawing of grid lines to 1000 lines.

And the timeline doesn't render at all, the first item is simply printed vertically at the bottom of the page. 

Curiously I created an identical component for the Network graph and it works perfectly. Am I doing something wrong? I can't get my head around it and I've been trying for quite a while now.
Thank you so much in advance for any help.

**Comment by josdejong** [comment]
Does the Timeline have a width initially? If the scale is determined from the window width and he configured start/end of the Timeline. If the width is zero the scale cannot be determined correctly.

**Comment by RamonBeast** [comment]
Hi Jos and thanks a lot for your reply, I appreciate.

Whether or not it has a width initially it doesn't matter, I tried both with an unsized container and with a defined width, same result in both cases. I've taken a screenshot, you can find it here: http://imgur.com/CeICmHg

**Comment by josdejong** [comment]
We'll have to set up a jsbin to do some testing&debugging.

**Comment by RamonBeast** [comment]
Jos, I'm deeply sorry to have wasted your time, please disregard, I was creating a jsbin and I noticed that in my project I didn't import the css correctly. Indeedin jsbin is working fine: https://jsbin.com/dapezisepa/edit?html,js,output

sorry for wasting your time, but thanks for your support.

**Comment by josdejong** [comment]
Ah, great to hear it's working now!
