### ISSUE TITLE
Add setCurrentTime method or setCustomTimeMovable option

### ISSUE THREAD

**Issue by mpilone** [almende/vis#171]
The older links Timeline supported a setCurrentTime method which I used to synchronize the time bar to a backend system that was processing data. This method appears to be gone in the new vis Timeline and the current time is always based on the browser's time, not the servers. I'm assuming that the new vis Timeline should be used for any new development but it seems like some of the features of the older implementation haven't been ported over yet.

An alternative to setting the current time would be to add support for a read-only custom time. The current custom time bar is always moveable by the user. While I can synchronize it back to the correct time when needed, it would be nice to prevent the user from moving it in the first place.

Probably another issue/enhancement, but it seems like a nice feature to be able to create multiple vertical time bars and then have options on the time bars like "autoAdvance", "editable", and "setTime". That would solve this problem and provide a lot more flexibility.

**Comment by MBrunoS** [comment]
Well, now the API has changed, and is available only `addCustomTime()`. How can I make the custom bar static, i.e, non-draggable?

**Comment by josdejong** [comment]
Maybe you can set [`pointer-events: none`](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) for the custom bar. Or maybe you can listen for the `timechange` event and set the custom time back to it's fixed time every time again.

**Comment by MBrunoS** [comment]
Oh, thank you.

**Comment by giohappy** [comment]
What about changing addCustomTime second argument to an options object, and set there both the id and a draggable boolean option?

**Comment by Sadi-1992** [comment]
is there any solution, yet? listening for the timechange event is not working...

**Comment by MBrunoS** [comment]
Well, I don't remember exactly, but I think the "pointer-events: none" worked for me
