### ISSUE TITLE
Using a custom icon font

### ISSUE THREAD

**Issue by jithin1987** [almende/vis#1710]
From documentation http://visjs.org/docs/network/nodes.html# `icon.face` has to be either `Ionicons` or `FontAwesome`. Is there a way I can register my own icon font in `vis.js` so that I am not restricted to only these two options ?

**Comment by josdejong** [comment]
You should be able to use any custom icon font.

**Comment by jithin1987** [comment]
Thank you. I didn't realize at first that I can put any font name. One thing I noticed is that without interacting with graph, icons are not getting loaded, I see only squares and I have to always manually redraw.
And is there a way to programmatically redraw? Hooking onto `afterDrawing` did not help.

**Comment by AlexDM0** [comment]
Hi, if you wait for the body to fully load it should be ok. SetTimeout with redraw() also works. Cheers

**Comment by jithin1987** [comment]
Thanks folks for helping out.
