### ISSUE TITLE
Wikipedia map for the showcase

### ISSUE THREAD

**Issue by The-Penultimate-Defenestrator** [almende/vis#1712]
I wrote an app with `vis.js`  which you might want to include in the showcase of projects. It involves loading content dynamically instead of visualizing a pre-defined set of nodes, so I think it might diversify the showcase a bit. It's different. 

The project is at http://luke.deentaylor.com/wikipedia/, and the code is [here](https://github.com/The-Penultimate-Defenestrator/wikipedia-map).

**Comment by AlexDM0** [comment]
Hi,

Looks like a cool project! Well get it added to the showcase when we do our next release!

Maybe small idea, get an estimate for a spawn position based on the position of the other nodes to have it much cleaner on adding nodes :). 

Cheers

**Comment by The-Penultimate-Defenestrator** [comment]
Thanks!

I'm not sure what you mean by your idea, could you elaborate on getting an
"estimate for a spawn position?" Do you mean estimating where a new node
would go before creating it? How would this make it cleaner?

**Comment by AlexDM0** [comment]
Hi, sure let me try to explain. 

If you add a node to the dataset it is added around the center if you do not give it an x and y position. My idea was to calculate the center of mass of all the existing nodes, then get the angle between the parent node and the center of mass, finally, along that angle calculate the x and y coordinates one springLength away from the center of mass. 

This would make the adding a bit less chaotic since nodes might get "tangled" before they find their place. 

Regards

**Comment by The-Penultimate-Defenestrator** [comment]
This sounds really interesting. With my very limited mathematics knowledge
(Nothing useful above Algebra I) this might be hard, but I'll keep it in
mind and see what I can do. Thanks for the input. 👍🏼

**Comment by AlexDM0** [comment]
It's easier than it sounds. First average all the x and y values which gets you a center of mass. Then draw an imaginary line from that point to the node you want to spawn from, extend that line with an edge length and there's your new point!


By the way, it would be REALLY cool if you could crawl Wikipedia and make a map of articles! The amount of nodes and edges would be huge so a filter to select parts of it would be required. If you could show how all of science is interconnected that would be fun!

If you can make a pull req to the gh pages branch you can add your own showcase entry! Would be a big help for us!

Cheers

**Comment by The-Penultimate-Defenestrator** [comment]
Sure, I could make a pull request. I'll also look into your idea, it sounds
reasonably practical. Thanks 👍🏼

**Comment by josdejong** [comment]
Luke I've added your Wikipedia Mapper to the showcases. If you want to change the screenshot or description just let me know.

**Comment by The-Penultimate-Defenestrator** [comment]
@josdejong Thanks a lot. If you could change the image to this that'd be great:
![this](http://i.imgur.com/pPdrHkC.png)
Thanks. The description looks fine.

**Comment by josdejong** [comment]
Sure, can you create a screenshot of 900x400 pixels? Then I will replace the current screenshot with yours.

**Comment by The-Penultimate-Defenestrator** [comment]
Sure. I'll get home in about 3 hours from school, I'll do it then

**Comment by The-Penultimate-Defenestrator** [comment]
[Here](https://www.dropbox.com/s/5u1kzvpo16in2hu/Screen%20Shot%202016-03-08%20at%207.25.02%20AM.png?dl=0)'s a 900x400 crop of that image.

**Comment by josdejong** [comment]
Ok updated on the website
