### ISSUE TITLE
Week Step in Timeline doesn't match

### ISSUE THREAD

**Issue by nothor84** [almende/vis#1715]
Hello!

First of all, congratulations for this super Tool!
Second, sorry for my english i will try to explain it clearly ;)

I'm using this tool to define the milestones for a project and I need to use a "Week Timestep".
I have set my Timeline format options in order to have the following:

When Scale = 'day'
- MinorLabel
  -- Step of 7 days (1 Week) 
- MajorLabel -- month step

But with this i have realized that the step of 7 days in the minorLabel it's restarted every time the major label ends.
For example,
I have a month with 31 days, and this month starts with the first day of a week, then the minorLabel will have the following steps (*\* means wrong):
`day 0, day 7, day 14, day 21, day 28, day 31 (month step), **day 38** (31+7), **day 45** (38+7), ...`
And it should be:
`day 0, day 7, day 14, day 21, day 28, day 31 (month step), day 35 (28+7), day 42 (35+7), ...`
So, the Week step don't fit with the real week steps...

Another visual example:
![weeks_steps](https://cloud.githubusercontent.com/assets/16415053/13597869/1a146b4c-e51b-11e5-8f46-5d0c3e340bd1.png)

There is anyway to fix it?

**Comment by josdejong** [comment]
The Timeline doesn't have a built in scale displaying weeks (repeating every 7 days), so it's not possible to do what you want here. You could change the labels on the axis to display week numbers but not a major grid line every 7 days is not supported.

**Comment by nothor84** [comment]
I see... :(
Well, in fact what I wish is to have an independent scale in the MinorLabel from the MajorLabel. 
For example, I could choose any step in the MinorLabel (for example every 7 days, but also every 3 days, 28 days or whatever) and another in the MajorLabel, and both independent one from the other.
The problem i see here is the followig:
It doesn't matter the scale you have in the MajorLabel, that will be 'forced' in the minorLabel.

This will allow you to have any 'Scale' you want. For example, weeks vs month, lunar month (28days) vs year, or whatever you imagine... But for sure it will also work with the current scales, like days vs weeks, or days vs month, month vs years, etc.

As I said this is a wish but it should be nice! :) 

Anyway thanks for the current work!

**Comment by marcortw** [comment]
Ha! Sounds a bit like [https://github.com/almende/vis/issues/1405](url) which I reported a few months ago.

**Comment by nothor84** [comment]
Yes! "marcortw" at the end the feature we would like to have is, a WeekStep.
I would try to check the TimeStep.js file in order to know how to add this feature... But I'm affraid I have not yet enough Programming Skills to do it correctly. :(

**Comment by marcortw** [comment]
From what I have seen, there's an additional problem that the start of the week is always determined by the user's locale and cannot be overriden (I think because TimeStep creates directly from Date() rather than the overriden moment function provided by the lib). For example, I'm using an English Windows install but would like to have the start of week of the the timeline on Monday rather than Sunday (e.g. to use the CSS vis-current-week). Although Windows is configured like that, the browser don't seem to respect this setting, thus a js Date object in my case always seems to start the week on monday. Additionally, this influences the week number calculation. If the week starts on Sunday (as in the US), the week number is different from the european way of doing things. Complicated stuff, not sure how to approach.

**Comment by yotamberk** [comment]
@nothor84 Is this issue still relevant? Can we close it?

**Comment by nothor84** [comment]
The issue is still relevant, I think the main point here is to have a WeekStep in the TimeStep.

@marcortw To calculate the week depending on the Local there is some Code in Internet. For example:
http://www.epoch-calendar.com/support/getting_iso_week.html

I know it's not an easy issue to implement, but a Timeline without weeks, it's really difficult to use for real Projects.
At least in Germany all the Projects (i have seen) are planned using Weeks.

**Comment by yotamberk** [comment]
@nothor84 Thanks! I'll get working on this.
Give me a few days, hopefully I can find time to take care of it.
