### ISSUE TITLE
Network - blurEdge not always fired

### ISSUE THREAD

**Issue by rjbriody** [almende/vis#1718]
Hi.

I noticed that the blurEdge event is not always fired. To reproduce, load the following example, open the console, and go nuts w/ the mouse. Eventually you will see that the blur and hover count diverge. It seems to get worse when 2 edges are very close to each other.

https://jsfiddle.net/njpazbuz/

Interestingly, the edge thickness is always correct.

**Comment by AlexDM0** [comment]
I don't suppose you can pinpoint which mouse movement causes this?

**Comment by rjbriody** [comment]
I'm not sure what you mean by "mouse movement". Are there different types of mouse movements or are you asking if I can determine when a blurEdge is missed? If the later, then that might be possible since other things are happening correctly - i.e. title popups disappear and edge thickness returns to normal.

**Comment by AlexDM0** [comment]
I meant the latter, what exactly causes the event to miss? Since all you do
to trigger it is move the mouse there has to be a specific combination of
movements (on edge, on node, off node, off edge etc) to cause it.

Regards

**Comment by rjbriody** [comment]
Got it. Let me add some additional logging and checks.

**Comment by rjbriody** [comment]
There is a pattern. It appears in 2 ways but seems like the same thing. 

The first example occurs w/ a very simple "2 node 1 edge" graph. Here is a sequence of the events:
hoverEdge
hoverNode (but notice that we didn't blur from the previous hoverEdge yet)
blurNode
hoverEdge
blurEdge 
...and at this point no more events are fired and we have received 2 hoverEdge but only 1 blurEdge


The second example uses a graph with 2 nodes and 2 edges. The sequence of events is:
hoverEdge
hoverEdge (but again, notice that we didn't blur from the previous hoverEdge yet)
blurEdge
...no more events are received.

It seems like it should not be possible to hover a new element without blurring the last. Maybe this is intentional? If so, then it seems like burEdge should be fired multiple times and include a ```{edge: edgeID}``` event.

**Comment by parthms** [comment]
Any updates on this?

**Comment by mojoaxel** [comment]
Should be fixed with #2124
