### ISSUE TITLE
disable network node tooltip

### ISSUE THREAD

**Issue by admhemed** [almende/vis#1720]
I need to make tooltip optional, disable and enable, 
I add tooltip by giving value to the title attribute of the node, 
but I find no way to disable it in documentation, 
I try to give title values like empty string, undefined or null, but all don't work
Thank you

**Comment by AlexDM0** [comment]
Hi,

Youll have to make your own custom implementation of the tooltips using the
events.

Regards

**Comment by admhemed** [comment]
:) I found an easier solution
visNetwork.setOptions({interaction:{tooltipDelay:3600000}});

**Comment by josdejong** [comment]
good one ;)
