### ISSUE TITLE
Strange behaviour in the time axis bar when hiddenDates setted

### ISSUE THREAD

**Issue by chiarishow** [almende/vis#1723]
Hi, 

here I am again =) 

When I set the scale to "day" and hiddenDates to 

```
[
      {start: '2016-01-01 00:00:00', end: '2016-01-01 08:00:00', repeat: 'daily'},
      {start: '2016-01-02 17:00:00', end: '2016-01-03 08:00:00', repeat: 'daily'},
      {start: '2016-01-02 00:00:00', end: '2016-01-04 00:00:00', repeat: 'weekly'}
]
```

The first day in the time asix scale is not displayed even there's the necessary space.

Here's my demonstration:
http://jsbin.com/hipugus/edit?html,output

in this case even if there is space the 15 day label is not displayed.

Without the  hiddenDates param there's no problem.

Thank you! 
Nikola

**Comment by josdejong** [comment]
Thanks for reporting this bug!

**Comment by chiarishow** [comment]
thank you for accepting the issue, 

if you don't have the time to fix this bug, can you give me some advice on how I can fix it myself?

Have a nice day

**Comment by josdejong** [comment]
Thanks for your offer. 

There is no clear starting point for this, I would look into the code for hiddenDates related stuff, add console.logs to see what's going on, and start debugging.
