### ISSUE TITLE
Feature Request: Fixed Point Item Selector in Timeline

### ISSUE THREAD

**Issue by ericj17** [almende/vis#1724]
Hi there,

Great library :) We are looking for / or to build a timeline slider that can select items at the timeline's center similar to this widget here: https://timeglider.com/widget/kitchen_sink.html
And we have considered to use vis.js timeline as the basis.

Has such a feature been requested before or do you have any plans to build such a feature? I had tried to search the issues, but had not found such a request. I'm not sure what terminology to use to describe such a feature. I'll just call it the "Fixed Point Item Selector" feature for now ;)

We can look into building this feature ourselves in the near future, and would be happy to contribute a pull request if this is something useful for others.

Do you have any suggestions or quick pointers as to where in the source we can review and modify to implement such a feature?

Thanks for your time and great work,
Eric

**Comment by josdejong** [comment]
I'm not entirely sure I understand what this feature is. is it the date label at the bottom center of the timeglider and the vertical bar there? When would such a label be useful?

**Comment by ericj17** [comment]
Hi josdejong,

Apologies, to clarify: we are aiming to have the timeline slider select an item closest to, or at the center point of the timeline. 

For example,
The user drags the timeline to a point where item 6 is near the center of the timeline (the black vertical bar)
![before](https://cloud.githubusercontent.com/assets/4195650/13890212/86f13ac6-ed07-11e5-93d6-6809576f5e67.png)

When the user stops sliding, the slider will automatically snap to set the focus on item 6 to be selected and moved to the center position. (this requirement was not mentioned in my original post..)
![after](https://cloud.githubusercontent.com/assets/4195650/13890213/86f3225a-ed07-11e5-92f5-2ec8028e7c67.png)

We found the "set selection" example to be something close what we'd like to achieve (http://visjs.org/examples/timeline/interaction/setSelection.html). Do you have any recommendations on how to implement the above feature? or let me know if further clarifications is needed on what we are trying to do.

Thanks again,
Eric

**Comment by josdejong** [comment]
Yeah, you can implement this yourself. I don't think there is need to introduce a new feature for this.

You can calculate the center of the window from the start and end returned from `timeline.getWindow()`. Then you can retrieve all your items from the DataSet and loop over them to find the one closest to the center. If you have that, you can simply call `timeline.setSelection` with or without animation.

**Comment by ericj17** [comment]
Thanks for the tips @josdejong :)
