### ISSUE TITLE
Feature request: passing arguments to "on" and "off" events callback

### ISSUE THREAD

**Issue by imCaps** [almende/vis#1727]
Hi to everyone!

I have played with vis.Timeline and have found that can not pass arguments to event callback functions.

For example in next code you can see, that we set "click" event on timeline:
```javascript
this.timeline.on('click', function(event) { 
        console.log(arguments); // Here we can get only get one argument event
});
```
If I need handle this events, I need pass parent object or something else. And good way to add that functionality for events handler in vis.Timeline: 

```javascript
this.timeline.on('click', function(event, _this) { 
        console.log(arguments); // Here we could see other arguments
        _this.object.setPlayerTimeLineValue(event.snappedTime.format("mm"));
}, this);
```

I think it can be added. Or exists other solution?

**Comment by BTMorton** [comment]
In your second example, could you not instead do:

```javascript
this.timeline.on('click', (function(event) { 
        console.log(arguments); // Here we could see other arguments
        this.object.setPlayerTimeLineValue(event.snappedTime.format("mm"));
}).bind(this));
```

That would solve your 'this' problem. I don't know about passing other arguments, but you could also do that with a `bind` call

**Comment by imCaps** [comment]
Thanks a lot for solution. It helps in my case. Using .bind(one, two, three) can resolve all problems. ))
