### ISSUE TITLE
Added rtl (horizontalOrientation) support in timeline 

### ISSUE THREAD

**Issue by yotamberk** [almende/vis#1730]
Hi guys,
I've picked up this feature and sent a pull-request. I've done:
(112) A horizontalOrientation options to support a right-to-left timeline.
you can find it in the pull request [here ](https://github.com/almende/vis/pull/1729) or [in my repository](https://github.com/yotamberk/vis)
solving #112 

Looking forward to feedback!
(first time contributing to open source in github)

**Comment by josdejong** [comment]
Thanks for your PR (#1729), I will close this issue now
