### ISSUE TITLE
Network | On Node Hover | Show Label on Edge

### ISSUE THREAD

**Issue by dapinder-dhillon** [almende/vis#1731]
we have a case where we have too many nodes and edges among them. Its a visual representation of a complex workflow. 
Displaying labels for all edges makes it more weird for user and looks too occupied.
Seems there is no hide property for labels but I can bring the labels in JSON under _labels attribute which in a way hide them but is it possible to show labels of all connecting edges of a node hovered on?
I tried but seems it so far isnt possible. Was able to get all connected edges of a node. Added label property to all selected edges and then set network.setData but as expected it redraw the network.

Just want to show labels of connecting edges of hovered node.

**Comment by josdejong** [comment]
There are different options here. You could use "title" so you see extra information when hovering an edge or node. And you can go crazy with events like hover over a node: when a hover event occurs, update it's connected edges with a label, and on blur remove the labels again (via the DataSet).

**Comment by dapinder-dhillon** [comment]
The DataSet does update the nodes but not edges. 
Tried updating couple of things but works for nodes and not edges. Nothing or no change happens in edges:
var nodes123 = new vis.DataSet(responseData.nodes);
var edges1234 = new vis.DataSet(responseData.edges);
nodes123.update({id: "DRAFT", label:'ABC'});
edges1234.update({'id': '27f0d865-f480-4d17-b757-e6f68e1205be', 'title':'ABC'});

Is this a bug?

**Comment by AlexDM0** [comment]
Hi, title is for mouse over popup labels. Not the text. Set the label if you want to change the label. 

Regards

**Comment by dapinder-dhillon** [comment]
Hello Alex, 
My bad as i pasted the wrong code but i was trying both title and label and none of them were getting changed. I understand title is for tooltip. Things are getting changed for Node but not for edge.

Kindly suggest.

**Comment by AlexDM0** [comment]
Hi can you show the issue in jsbin? I don't know if the ID is correct for instance

**Comment by dapinder-dhillon** [comment]
Thanks Alex... Seems probably i was doing something wrong..
Now I am able to achieve what i desired i.e. on node hover, show edges' labels else hide.

After successfully doing this, I could now see that the tooltip i.e. title has stopped appearing on node hover. Is this bcos i have overidden node hover from default? Do i explicitly need to do something to have even show tooltip on node hover? Below is the JS fiddle

https://jsfiddle.net/8xrcbg0k/

**Comment by dapinder-dhillon** [comment]
Could you please respond

**Comment by AlexDM0** [comment]
You dont include the css

**Comment by dapinder-dhillon** [comment]
Yes.. i did that intentionally? is that the reason?

**Comment by dapinder-dhillon** [comment]
thanks.. that was the reason...

**Comment by yuvraj11** [comment]
@dapinder-dhillon Thanks for the code, made my job much easier! I am new to js and was wondering how I can show the label on only "To" edges in your example as opposed to both the edges. Any hints will be greatly appreciated.

**Comment by dapinder-dhillon** [comment]
If i understand correct that you would like to show only the forwarding edges labels from the hovered node.  You try having a small condtion in showConnectedEdgesLabels method:
```
  if(nodeId === value.from){
	edges.update({id: value.id, label:value.labelC});
   }
```

**Comment by yuvraj11** [comment]
Thanks man, Appreciate it! Did you find this from the documentation? Because I couldn't find it in there

**Comment by amorigoye** [comment]
Pls can anyone help me here?. I am new to coding. However, I tried vis.js network visualization and want nodes to display content of title on mouse hover on nodes. Pls kindly help. Thank you
