### ISSUE TITLE
Editing Nodes & Edges

### ISSUE THREAD

**Issue by SrvrSide** [almende/vis#1733]
Hello, Is it possible to implement the on demand node/edge manipulation functionality similar to the example here : http://visjs.org/examples/network/other/manipulation.html without using the built in buttons and button panel? I'm trying to use an existing interface to handle the user interactions while the visjs renders a network map in a panel within that interface.
Any pointers you may be able to provide would be very welcome
Thanks -SrvrSide

**Comment by josdejong** [comment]
You can programmatically manipulate nodes and edges simply by adding/updating/deleting nodes/edges in their DataSet. The Network will automatically update on changes. There is no API available to do stuff like letting a use create a new edge by dragging from one node to another. If you need that you will have to hack into the code.

**Comment by AlexDM0** [comment]
There is the manipulation API that you can use, its all in the docs:
http://visjs.org/docs/network/#method_enableEditMode
