### ISSUE TITLE
[Timeline] Subgroups overlap

### ISSUE THREAD

**Issue by BTMorton** [almende/vis#1737]
Since I need more control than the stack option provides, I've been using the subgroup option for the items I display in the Timeline. The problem I've been having is that the subgroups overlap each other when they have different values. I verified this by making the items display which subgroup they are supposed to be in. By inspecting the HTML values I can see that they're in the right groupings, but are displayed at the wrong height.

**Comment by josdejong** [comment]
Can you create a [jsbin](http://jsbin.com) to demonstrate the issue?

**Comment by yotamberk** [comment]
@BTMorton Is this issue still relevant?

**Comment by BTMorton** [comment]
We're no longer using more than one subgroup due to encountering this issue, but will be looking to re-add it soon. I'm happy for you to close this issue for now, and then if we are still encountering it later, I will re-open it.

**Comment by yotamberk** [comment]
Can you produce a jsbin so we can help solve this problem?

**Comment by yotamberk** [comment]
Fixed with #2519
