### ISSUE TITLE
Timeline removes items and sets group height to 0 when items is not visible

### ISSUE THREAD

**Issue by ArunSivagnanam** [almende/vis#1739]
Hi.

Timeline removes items and sets group height to 0 when items is not visible. Is there a way to prevent this?

If not, can you guide me to add this as an option? 

Thanks
Arun

**Comment by josdejong** [comment]
You can give groups a minimal height by creating a group label having this height. See:

https://github.com/almende/vis/issues/1428#issuecomment-156361197
https://github.com/almende/vis/issues/1186#issuecomment-131853154
