### ISSUE TITLE
JIRA like Edges

### ISSUE THREAD

**Issue by dapinder-dhillon** [almende/vis#1740]
Hi,

We have a requirement to have visual representation of a complex workflow. .
Can we achieve the edges styles as shown in the below JIRA workflow style?

I have tried using all edges styles but none of them come close to this.
Does VIS JS supports having this style? Also raised another issue #1731 where we want same on hover node show labels else hide.

Please respond.

![jira_vs_visjs](https://cloud.githubusercontent.com/assets/12184239/13905448/097f1df8-eed1-11e5-8f1c-22e2dbec7436.png)

**Comment by AlexDM0** [comment]
Hi,

vis does not support this style. 

Regards
