### ISSUE TITLE
[Network] network.stabilize() does not honor layout.randomSeed

### ISSUE THREAD

**Issue by rjbriody** [almende/vis#1742]
Hello,

In the following example, I switch between normal and hierarchical layout. After switching from hierarchical layout back to normal, I expected the layout result from ```network.stabilize()``` to be identical to the original layout. However, it appears as though the ```layout.randomSeed``` is not being used during subsequent stabilization.

https://jsfiddle.net/d4ex2j30/1/

**Comment by AlexDM0** [comment]
It does but the thing is that the randomseed is used in the initial positioning. You're not repositioning the nodes: it will stabilize from their last positions. You'll have to set the data (setData) to reinitialize it.

Regards

**Comment by rjbriody** [comment]
Thank you for this clarification.
