### ISSUE TITLE
Is there any way to control how the edges are drawn in a network when the physics are disabled?

### ISSUE THREAD

**Issue by SwagMuffinMcYoloPants** [almende/vis#1748]
I've been using the Network module and I have the physics disabled.  When I drag nodes around, it seems like the edges have a tendency to be curved by default even if the shortest path between the edges is a straight line.  Is there any way to make the edges a straight line?

**Comment by AlexDM0** [comment]
Yep. Read the docs in the edge section. You're looking for the smooth
option. Good luck!

**Comment by SwagMuffinMcYoloPants** [comment]
Wow.  Now I feel dumb for asking this question.  Thanks @AlexDM0
