### ISSUE TITLE
limiting move left and move right 

### ISSUE THREAD

**Issue by rubenbenjamin** [almende/vis#1749]
In this example the move left and move right are going far beyond the data. Is it possible to limit move left and right only until available data? I dont want this to span too far ago 

http://visjs.org/examples/timeline/interaction/navigationMenu.html

**Comment by AlexDM0** [comment]
You can use the initRedraw event and the moveTo method together to check if the view goes out of bounds and if so, snap it back. 

Regards

**Comment by rubenbenjamin** [comment]
I dont see the initRedraw event in the docs.
http://visjs.org/docs/timeline/#Events

**Comment by AlexDM0** [comment]
Sorry I assumed you were talking about network. For timeline there is a min and max option. 

Regards

**Comment by rubenbenjamin** [comment]
Thanks Alex. setting min and max worked.
