### ISSUE TITLE
Timeline has limited range when using number instead of date

### ISSUE THREAD

**Issue by seechuenteck** [almende/vis#1754]
When timeline axis is number instead of date, the minor axis always shows 3 digits. The max range is limited to 3 digits ie 999. I think it is impossible to say display min=0, max=1001. It will be truncated as "000" to "999".

**Comment by josdejong** [comment]
The Timeline does not support numbers, it only supports Dates or timestamps. Your limit of 1000 is caused by the the lowest scale of milliseconds: you have 1000 milliseconds in one second.
