### ISSUE TITLE
"Merge" two nodes in a Network

### ISSUE THREAD

**Issue by The-Penultimate-Defenestrator** [almende/vis#1759]
Is there any kind of function to "merge" two nodes? This function would take two nodes, delete one, and transfer all the deleted node's edges to the other node. What's the easiest way to accomplish this?

**Comment by AlexDM0** [comment]
Clustering?

**Comment by The-Penultimate-Defenestrator** [comment]
Is it possible to get an animation while clustering? Some way for the user to get a visual sense of which two nodes are being clustered.

**Comment by AlexDM0** [comment]
Well you could control the node positions manually and do your own animation using the initRedraw event but other than that, no.

**Comment by The-Penultimate-Defenestrator** [comment]
Sure. I'll look into this. Thanks :)

**Comment by The-Penultimate-Defenestrator** [comment]
I wrote the following "permanent" merge function. It assumes you've got your nodes in a dataset named `nodes` and your edges in a dataset called `edges`:

```javascript
// Delete A and move its connections to B. This is more permanant than clustering.
function mergeNodes(a, b) {
  var edge;

  // Move the edges that are coming from the node to be deleted
  var fromEdges = getEdgesFrom(a);
  for (var i=0; i<fromEdges.length; i++) {
    edge = edges.get(fromEdges[i]);
    if (edge.to == b) { // Prevent edges that go from a node to itself
      edges.remove(edge.id);
    } else {
      edge.from = b;
      edges.update(edge);
    }
  }

  // Move the edges that are going to the node to be deleted
  var toEdges = getEdgesTo(a);
  for (var i=0; i<toEdges.length; i++) {
    edge = edges.get(toEdges[i]);
    if (edge.from == b) { // Prevent edges that go from a node to itself
      edges.remove(edge.id);
    } else {
      edge.to = b;
      edges.update(edge);
    }
  }

  // Remove the node
  nodes.remove(a);
}
```

It works well for my purposes, and I feel like it's more animated than clustering (I think clustering automatically re-stabilizes, skipping the animation. I could be totally wrong about that though)

**Comment by AlexDM0** [comment]
Clustering does not restabilize automatically. It is an instant operation though. It also creates new edges instead of rewiring the old ones so it may look more snappy. 

Regards

**Comment by The-Penultimate-Defenestrator** [comment]
Right. That’s probably why mine looks smoother. Thanks for the info.
