### ISSUE TITLE
Timeline, set minimum zoom to days and not hours

### ISSUE THREAD

**Issue by rubenbenjamin** [almende/vis#1760]
![zoom](https://cloud.githubusercontent.com/assets/429940/14085288/fe373972-f4ec-11e5-87b7-8bc1182a1d40.png)

In the timeline, it is possible to limit zoom to days and not let the user zoom to hours?

Can I use onrangechanged event to somehow check the zoomlevel?

**Comment by josdejong** [comment]
You can use options like `min`, `max`, `zoomMin`, and `zoomMax` to limit how far the user can move and zoom.
