### ISSUE TITLE
click on items not working

### ISSUE THREAD

**Issue by YiuriV** [almende/vis#1762]
Hi, I have this project I'm working on, using the timeline: http://histmap.azurewebsites.net/
On the timeline there are multiple chart items. Clicking on such an item places it on the map. 

Clicking on play loops through all the items on the timeline. First the loop goes from left to right. When pressing stop, the loop stops and you can select another item again. At the end of the items on the timeline, the loop changes direction. There the problems start. 

Once the direction is changed, I cannot select any item that lies left of the last item of the loop. The items on the right are selectable. 

I cannot figure out what is going wrong so any help would be greatly appreciated

**Comment by josdejong** [comment]
hm I don't see any play or stop button in your web application.

**Comment by YiuriV** [comment]
The application has changed, meaning that this issue is no longer of an issue for now. However, I have met with another problem that is somewhat related. 
When zooming out 2 levels from the start position of the map, the timeline gets updated, new items are added and the timeline get fitted to the items. When zooming out 2 levels, the first item that gets put on the timeline is a map with the label "1274". However, I can not click on this item. All others are clickable.
When I look in my code behind, I see that this first item in the timeline gets put after the present-layer. Also, if you drag the map even 1 pixel, the timeline gets updated, and then that first item is clickable. This confuses me, as I execute that update method after the site has loaded, so first time execution makes it unclickable, from second execution on the item is clickable?

**Comment by yotamberk** [comment]
@YiuriV please open a new issue with the new issue you're having (if still relevant) with an example.
