### ISSUE TITLE
Problem with svg image rendering using visjs network

### ISSUE THREAD

**Issue by tlland** [almende/vis#1764]
I have two relatively simple, standalone SVG image files.  Each individual svg image file can be rendered successfully when assigned as the node image to any of the node objects defined in the images.html network example distributed with visjs.  However, when I merge the two svg files into a single file, and then reference that composite svg file in the images sample, the composite image fails to render.  Interestingly, the composite image does render successfully outside of visjs (e.g., within an html page or using an svg editor like Inkscape).  I've tested using IE10, FF ESR, and Chrome v49.0.2623.87 (all under Windows 7 Pro 64-bit, SP1).

Attached is a .zip file containing the two individual svg files (before merging), and the composite version (after merging).

Thank you in advance for any assistance.

<note>: not sure if the zip file I created was successfully uploaded.  I've attached the 3 separate .svg files as .txt files instead.
[HTTP1_composite.svg.txt](https://github.com/almende/vis/files/194606/HTTP1_composite.svg.txt)
[re64_HTTP1.svg.txt](https://github.com/almende/vis/files/194604/re64_HTTP1.svg.txt)
[rectangle.svg.txt](https://github.com/almende/vis/files/194605/rectangle.svg.txt)

**Comment by AlexDM0** [comment]
Hi,

We use built in methods to render images so I'm afraid there is no way to help you here. 

If your edited file is not working I assume there is some tag mismatch or header missing or something. I suggest you open them in a text editor and check for differences. 

regards
