### ISSUE TITLE
How to Add Timeline Group

### ISSUE THREAD

**Issue by stephenHartzell** [almende/vis#1765]
I see that the ability to add a group exists with groupEditable.add = true; however, I do not understand how the user creates a new group. Is there a special command to do this (e.g. double click + ctrl)?

**Comment by Menighin** [comment]
Hi there,

You can save a reference to the DataSet of groups and later add a new element to it. [Check this JSFiddle](url)

Best regards,

**Comment by frittola** [comment]
Hi, 
sorry, I do not undestand how i can remove or update an existing group.

Thanks

**Comment by mojoaxel** [comment]
@frittola Here you go: http://jsbin.com/conicu/1/edit?html,js,console,output

![image](https://cloud.githubusercontent.com/assets/600565/18578903/cc5ee2aa-7bf2-11e6-963a-31c2962de048.png)
