### ISSUE TITLE
graph2d Mobile responsiveness

### ISSUE THREAD

**Issue by pliablepixels** [almende/vis#1766]
Hello there, some months ago, I had posted an issue on timeline mobile performance https://github.com/almende/vis/issues/1158 --> since then you have made amazing improvements to its performance. I'm curious if these optimizations would have also been applied to graph2d? I am finding it extremely slow on android devices. Thanks.

**Comment by josdejong** [comment]
You mean the `throttleRedraw` option? Yes that should work for Graph2d too.

**Comment by pliablepixels** [comment]
okay, thanks. For some reason, I am facing the same problem I did with timeline before you fixed it - its getting locked during event detection for long cycles on mobile devices, specifically android. Anyhow, I've switched to a different library for 2d bar charts, so closing this. thanks.

**Comment by gmlevin** [comment]
Has throttleRedraw been removed as an option? I noticed my code started complaining about it and hen I check the documentation, it appears to have been removed. Is there a replacement?

**Comment by yotamberk** [comment]
Yup  it has been removed


בתאריך 21 בדצמ׳ 2016 9:50 אחה״צ,‏ "gmlevin" <notifications@github.com> כתב:

**Comment by mojoaxel** [comment]
@yotamberk If a option has been removed without increasing the MAJOR version number this is an bug. We should check it out. I opened #2511 for that.

**Comment by mojoaxel** [comment]
@gmlevin The option `throttleRedraw` will be available again im v4.18. But it is **not implemented anymore** and will be removed in the next major release.
