### ISSUE TITLE
Is is possible to make nodes/edges hidden by group?

### ISSUE THREAD

**Issue by fanfanpsu** [almende/vis#1767]
Hello,
Thank you very much for making this wonderful vis tool!

I am just wondering if there is a way to make nodes invisible by group. For example, in the network example: http://visjs.org/examples/network/nodeStyles/groups.html
I did 
var options = {
  groups: {
    0: {
    	color:"red", 
    	hidden:true,
	}
  }}

and then, network.setOptions(option)

I can see the nodes of group zero changes their color. However, they are still visible. 

I am wondering what's the correct way to make nodes invisible by group.

Thank you in advance!

Best,
FZ

**Comment by AlexDM0** [comment]
Hi, 

You could set the color to rgba(0,0,0,0) to do it this way or iterate over the nodes and set it per node? 

I'm not sure why the hidden doesn't work as a group setting, we'll look into it but it's very busy at the moment. If you want to look into it that would be great!

Regards

**Comment by fanfanpsu** [comment]
Awesome awesome. Thank you in advance.

The rgb 000 would work. And I will look into this issue. Thank you again!

Regards
