### ISSUE TITLE
Timeline: automatic Title/Tooltip in range?

### ISSUE THREAD

**Issue by Wallenstein61** [almende/vis#1768]
Hello,

I have found a (minor) flaw in the timeline representation.

For each project I have a timeline representation with a single group (the project) and multiple ranges.
e.g.
 `{start:new Date(1458687600000),end:new Date(1493416800000),type: "range",editable:false, "phase": "Sounding", "endDate": "29.04.2017", "title": "Launched Test Deal1", "startDate": "23.03.2016","group":"Launched Test Deal1","className":"timeLineDealEndSounding timeLineNow","content":"zur Zeit: Sounding"}`

Also I have a summary timeline with multiple groups (all projects) and (the same) multiple ranges for each group.

In the first timeline the range is rendered as

`<div title="Launched Test Deal1" class="vis-item vis-range timeLineDealEndSounding timeLineNow vis-readonly" aria-describedby="qtip-1" style="left: 149.35px; top: 5px; width: 416.95px;" data-hasqtip="1" oldtitle="Launched Test Deal1" data-phase="Sounding" data-endDate="29.04.2017" data-title="Launched Test Deal1" data-startDate="23.03.2016"><div class="vis-item-overflow"><div class="vis-item-content" style="left: 0px;">zur Zeit: Sounding</div></div></div>`

In the second timeline (with multiple groups) the range is rendered as
`<div title="" class="vis-item vis-range timeLineDealEndSounding timeLineNow vis-readonly" aria-describedby="qtip-22" style="left: 22.36px; top: 5px; width: 1057.63px;" data-hasqtip="22" oldtitle="Launched Test Deal1" data-phase="Sounding" data-endDate="29.04.2017" data-title="Launched Test Deal1" data-startDate="23.03.2016"><div class="vis-item-overflow"><div class="vis-item-content" style="left: 0px;">zur Zeit: Sounding</div></div></div>
`
although the difference is only marginal (the **title**-attribute is empty in the second case), our customer is complaining, because the application renders its own tooltip (with the qtip-library) and there are now two tooltips visible in the first case (the qtip-Tooltip and the automatic title-tooltip).

So my question is: Is this difference by intention. Is there an option to switch off the title-option?

Thank you for your kind support

Michael

**Comment by josdejong** [comment]
I'm not sure what you mean exactly, when the rendered `title` attribute is empty, then apparently you've not provided a title in the JSON of the corresponding item? 

If you want to render titles yourself with a tooltip library, you simply have to provide items without `title` property.

**Comment by Wallenstein61** [comment]
Hello Jos,

Indeed I had a hard time to provide a simple example. As soon as I tried to reduce the HTML/Javascript to the essence, in order to demonstrate it, the problem disapeared :-( .

So I finally think the source of the problem is not on the vis implementation, but rather on the inclusion of the qtip-implementation.

I have to research futher on our side.

Thank you for your support
