### ISSUE TITLE
Don't show movement of nodes during physics simulation

### ISSUE THREAD

**Issue by Spocer** [almende/vis#1769]
Hi,

I am using your Network library for a project, and I'd like to not see the nodes move during simulation -  only see the resulting placement. I'd like this to stay true if the network changes as well - nodes/links added or removed. I currently have the nodes 'fixed' once they are in their position, so only new ones move.

Is this possible? I have looked through the other 'issues' on here and I have come across some which appear to do this, but I think that is just because they are finishing the simulations before the page/content finishes rendering. It also doesn't seem to be the case when adding new nodes or links.

I apologize if I've missed something, but I've searched all of the key terms I thought were relevant and came up short.

Let me know if I can provide any more info. Thanks.

**Comment by AlexDM0** [comment]
Hi, 

What you're looking for is called stabilization. There is a method called stabilize to trigger it yourself. It will stop once the iterations are finished or the network is stable. 

Regards

**Comment by Spocer** [comment]
Alex,

That seems to do what I needed. Thank you for your help.
