### ISSUE TITLE
TypeError when rendering an Image node

### ISSUE THREAD

**Issue by timlyo** [almende/vis#1772]
I'm adapting my project to use images rather than default nodes, however upon changing the shape I'm getting the error `Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)'` when trying to create an image node.

I've done some digging and it seems that `ctx.drawImage` is being passed an `Image` rather than an `img` for it's `imageObj`.

It seems that the function for loading images is returning the wrong type, but I cannot work out why. I've created a minimal example to try and reproduce the issue, but it's working perfectly. In example the line `var img = new Image()` creates an `img` and in my larger example it creates an `Image`.

The only difference that I can see is that the broken network is inside an ES6 class that is transpiled with babel, whereas the working example is just in plain javascript.

Both examples use the line `nodes.add({id: 50, image: "/static/img/default.png", shape:"image"});` to add the node.

Thanks for any help.

**Comment by AlexDM0** [comment]
I'm not sure whats going wrong for you but our image examples seem to work
fine:
http://visjs.org/examples/network/nodeStyles/imagesWithBorders.html

Any idea what you're doing differently?

**Comment by timlyo** [comment]
I have no idea at all. I can't work out why the same bit of code, with the same parameters, is creating an `Image` rather than an `img`.

I would share the code that's creating it, but it's part of a large project and the small example code that I've created has no issues at all. Is there anything else I can share that might be useful?

**Comment by AlexDM0** [comment]
If I were to guess, the problem is not in the vis code but in the image?
We've never encountered this before nor received an issue from this. The
code you're referring to is very old so if it was a bug in vis I think it
would have surfaced quicker. Good luck!

**Comment by timlyo** [comment]
I'm using the same image in my example and it's working fine. Thanks for the help anyway.

**Comment by timlyo** [comment]
I hate Javascript, so damn much.

Turns out that I had created my own Image class and vis.js was using this one instead of the inbuilt Image class.
