### ISSUE TITLE
[timeline] shift multi select

### ISSUE THREAD

**Issue by Heinzelemente** [almende/vis#1773]
Hi,
I recognized, that when I select multiple entries with shift, then all the entries within the timeframe are selected thru all groups. How can I only select the entries of one single group?
![2016-04-04 12_29_17](https://cloud.githubusercontent.com/assets/12995603/14245325/e704c854-fa60-11e5-8fe0-67b24e348f2e.png)

**Comment by josdejong** [comment]
Yes that's true. Maybe you can listen for the `select` event and deselect all items not in the group you're interested in?

**Comment by Heinzelemente** [comment]
I have currently more than 5000 items inside that timeline... do you thing that would work? 
Isn't the performance decreasing ?

**Comment by AlexDM0** [comment]
Try it

**Comment by hansmaulwurf23** [comment]
I enhanced the timeline (#1354) with the `multiselectPerGroup` (http://visjs.org/docs/timeline/#Configuration_Options) some time ago. That should be what you are looking for, right?
