### ISSUE TITLE
[Network] Edges for dynamically added Nodes not working

### ISSUE THREAD

**Issue by Fabian95qw** [almende/vis#1776]
Good Day.

I've a Strange Issue working with the vis.js for the first time.

I'm trying to create an Editor with the Help of vis.js.

The Editor loads all the Possible Nodes from Different Config files.

I am using DataSet's as described in the documentation.

I Start off with the following two DataSets:

`               nodesArray = [
                {
                    id: 1,
                    label: 'EntryPoint',
                    shape: 'icon',
                    icon: {
                    face: 'FontAwesome',
                    code: '\uf233',
                    size: 50,
                    color: '#f0a0a' }
                },
        ];   
nodes = new vis.DataSet(nodesArray);
edgesArray = [{from: 1 , to: 1}];
edges = new vis.DataSet(edgesArray);
network = new vis.Network(container, data, options);  
`
After that i Import additional Nodes and add them with the function
`function addUserNode(NodeID) {
        nodes.add({id: NodeID, label:NodeID, group: 'users'});
    }  `
Those Appear Correctly in the Network
After that i'm trying to load the Saved Edges for the newly Imported Nodes
And try to add them with the Command

`edges.add({from: val1, to: val2});`

But the added Edges are not showing up, only for the pre-created Node with the ID 1.
The Console is not giving out any information.

If i remove the Edge {from 1: to 1:} from the predefined edgesArray and add id with the command
`edges.add({from: 1, to: 1})` after the network creation the edge will show up.
For example `edges.add({from: 1, to: 600})` is not working.

But if add the Edge via the Manipulation tool and give out the edgedata.from and edgedata.to via
`console.log(edgeData.from + " --> " + edgeData.to);`

The Output is: 1 --> 500

I may be missing something obvious, but i can't get my head around it.

How the network looks:

![github1](https://cloud.githubusercontent.com/assets/2330622/14276660/f99d32e8-fb1f-11e5-8176-afd59860ab3f.JPG)

Mabye somebody has a Tip for me.

Sincerly

Fabian95qw

**Comment by AlexDM0** [comment]
Hi,

I dont see your definition of 
```
data
```

anywhere. Can you make a JSBin to show the issue?

**Comment by Fabian95qw** [comment]
`var data = {
            nodes: nodes,
            edges: edges
        };`

The JSBin:
index.html
[https://jsbin.com/babetofixe/1/edit?html,js,output](url)
configreader.js
[https://output.jsbin.com/pewezefose/1](url)

**Comment by AlexDM0** [comment]
I'm not sure what to do with your jsbin. It doesnt do anything.

**Comment by Fabian95qw** [comment]
@AlexDM0 
I updates the Whole jsbin. I never worked with it before...

**Comment by AlexDM0** [comment]
Hi, usually you take the vis.js version you use from CDN and show in a small example that something you want does not work. We have many users who do exactly what you want to do and there doesnt seem to be a problem. If you can show in a simple example that its not working we can track down the issue.

Regards

**Comment by Fabian95qw** [comment]
Hello again

Sorry for my stupidity

I pasted my code, simplified it, and added a Button AddNodeandEdge function to a button.

Now that i simplified it to Show the Problem, the Problem doesn't exist.

It seems to pe a Problem with the actual reading of the config.

[https://jsbin.com/xelazazeto/1/edit?html,js,output](url)

I just tought about the actual whitespaces and breaks as the issue of the Problem. 
Would it be possible to put those in the ID of a Node?

**Comment by AlexDM0** [comment]
I suppose since it's just a string it doesn't really matter what you put in there, though I wouldnt recommend it. You can always try and see.
