### ISSUE TITLE
[Timeline] force order of items

### ISSUE THREAD

**Issue by remorse** [almende/vis#1780]
Hi! I'm trying to control the vertical order of items in a timeline. I have a set of item (the timeline isn't editable when in use, so the set of items can't change), which come in a particular order. Within each group of items, I want to make sure that the items proceed vertically, even when they don't overlap in time.

I've tried playing around with the 'order', 'subgroup', and 'subgroupOrder' fields in groups and items, but I can't seem to make things work correctly.

How can I control this?

Thanks,
Ricky

**Comment by josdejong** [comment]
If you want to put items on a certain vertical level you could use groups or subgroups.

Using the `order` function you can control the order in which items are rendered and stacked on top of each other.

**Comment by remorse** [comment]
Hi! I understand this; what I'm struggling to figure out it how to make it work.

I already have multiple groups, so I'm trying to figure out how to control the vertical order *within* a group.

Based on my reading of the documentation, the following code should return a timeline with three rows, going "A", "B", and "C" from top to bottom. Instead it return two rows, with "B" on top, and "A" and "C" on the second row. How do I get it to make the three row version? I've played around with all kinds of combinations of subgroup, subgroupOrder, order, etc., but none of them seem to solve the problem.

``````````
	var items = [
		{ id: 1, group: "X", content: "A", start: "2016-01-01", end: "2016-01-31"},
		{ id: 2, group: "X", content: "B", start: "2016-01-15", end: "2016-02-29"},
		{ id: 3, group: "X", content: "C", start: "2016-02-15", end: "2016-02-29"}
	];
	var groups = [
		{ id: "X", content: "X", subgroupOrder: "id" }
	];
	var options = {
		stack: false,
		order: function (a, b) { return a.id - b.id; }
	};

	var el = document.getElementById('tl');
	var timeline = new vis.Timeline(el, items, groups, options);
``````````

**Comment by brichbe** [comment]
@remorse How's [this](http://jsfiddle.net/a8xdhpac/28/) ?

I think you're mixing `order` and `subgroupOrder` when you shouldn't be.  As you can see in the fiddle, you need to specify both the `subgroupOrder` for the group, as well as the `subgroup` property with unique values for all the items within that group, in order to customize the top-to-bottom ordering and to keep each each item within its own horizontal space within the group.

**Comment by brichbe** [comment]
Strange... it didn't save my last edits so try this one.  http://jsfiddle.net/a8xdhpac/30/

**Comment by remorse** [comment]
Thank you! I swear I tried something similar to that, but apparently I never got quite the exact combination. (I think that maybe I never removed the high-level "order" function, even when I had a "subgroupOrder" function.) That does exactly what I wanted!
