### ISSUE TITLE
Timeline examples on website not working on IE11

### ISSUE THREAD

**Issue by minhtam-nguyennhat** [almende/vis#1786]
Hi,

I tried to open the Timeline example on IE11 however they did not seem to render.

Could you please look into that?

Thank
Tam

**Comment by altaweelali** [comment]
same here. also, none of the local examples work in IE 11. 
Thanks

**Comment by stoyanmkd** [comment]
Same here. I tested different versions of IE and the Timeline examples are not working on IE11, 10 and 9. On Edge everything seems alright.

**Comment by AlexDM0** [comment]
Hi, 

Well look into this. @josdejong do you have time to check this?

Regards

**Comment by josdejong** [comment]
It was a regression introduced when fixing #1697. For some reason `.clientWidth` returned 0 on IE. `.offsetWidth` works fine. I remember IE has some "special" behavior of `clientWidth`.

@AlexDM0 can you do a bugfix release?

**Comment by AlexDM0** [comment]
Hi,

We're in the middle of a move, it would be next week...

Regards

**Comment by josdejong** [comment]
I've just released v4.16.1 containing this fix.
