### ISSUE TITLE
Snapping timeline items

### ISSUE THREAD

**Issue by LJack2k** [almende/vis#1788]
Is it possible to make items snap to a nearby item while moving it? And maybe set a snap distance? Or is there another method of making items not overlap another one while moving it?

**Comment by josdejong** [comment]
That's not built-in but should be relatively easy to create: you can use the callback `onMoving` and manipulate the position of the item yourself while it's being dragged. In this callback you will have to filter  nearby items from your DataSet and snap if within a certain distance.

see docs: http://visjs.org/docs/timeline/#Editing_Items

**Comment by yotamberk** [comment]
@LJack2k Is this question still relevant?
