### ISSUE TITLE
CSS styling nodes

### ISSUE THREAD

**Issue by ProbadorGit** [almende/vis#1790]
Is it possible to style nodes with CSS classes?

Currently I can do:

```
groups: {
                    documents: {
                        color: {background: '#ccbde8', border: '#222'}
                    }, .....
```

But I would like to define the style in the CSS. I have seen there is something similar in the timeline examples (`className`).

**Comment by AlexDM0** [comment]
Nope. The nodes are not html, they are canvas drawings. 

CSS is just not possible. You can write a parser for most common CSS styling elements that mirror the nodes style info I suppose?

**Comment by ProbadorGit** [comment]
I see, thanks. It is just because I create a legend of colours, so it was to avoid mismatching (human) errors. A parser could be an idea. Thanks anyway. (By the way, I love the library, just changed from another one I was using and I was not happy with. This one behaves perfectly, at least for the network).
