### ISSUE TITLE
How to add custom attributes to Nodes and edges, and use these attributes in click event ?

### ISSUE THREAD

**Issue by hadjloo** [almende/vis#1791]
How to add custom attributes to **Nodes** and **edges** of **Network** library, and use these attributes in **click event** ?

**Comment by josdejong** [comment]
You can add any property you want to the items (nodes and edges) you add to your DataSet. When a click event happens, you get the id of the clicked node/edge, and you can simply retrieve the corresponding item (with extra properties) from the DataSet using `DataSet.get(id)`.

**Comment by hadjloo** [comment]
Thank you very much, it helped a lot
