### ISSUE TITLE
Network - animated nodes

### ISSUE THREAD

**Issue by MarcelK28** [almende/vis#1792]
Hi Team,

I love your new version of Network. I'm working on a project where I need to be able to use images 'shapes' for nodes which I can easily achieve, however, I would like to use animated SVG files or dynamically insert canvas animation such as rotate each node. Is this achievable with the new version?

Additionally, animated edges flow would be nice too :)

Regards,
marcel

**Comment by dragonzone** [comment]
This topic has been discussed before: https://github.com/almende/vis/issues/323
