### ISSUE TITLE
First month class not properly set

### ISSUE THREAD

**Issue by najdoni** [almende/vis#1798]
When a month start on the timeline, that its first day is not in the view and that it is not the current month, the class of the month label is set to vis-current-month and vis-{currentMonth}.

So for example if we are in April:
- March label will be vis-current-month and vis-april instead of only vis-march
- April label will be vis-current-month and vis-april
![bug_vis_timeline](https://cloud.githubusercontent.com/assets/17692759/14543581/230ed754-0295-11e6-9c4b-6547822e594d.png)

**Comment by yotamberk** [comment]
Hey @najdoni, is this still a relevant issue?

**Comment by najdoni** [comment]
I have not checked if it was solved. I am not using vis timeline anymore (but I might in the future).

**Comment by yotamberk** [comment]
Ok, I'm closing this issue. It seems to be solved. If you see it's still happening, feel free to reopen this issue =)
