### ISSUE TITLE
Timeline point items : display the content before the dot with stack=true

### ISSUE THREAD

**Issue by salmen** [almende/vis#1799]
Thank you for this wonderfull library. I wonder if there is a simple way to print the content at the left of the dot in a point item. I have tryed to set margin-left the contents with CSS but some items gets in collusions.
![test](https://cloud.githubusercontent.com/assets/11051314/14546511/b8b4c522-029d-11e6-964c-93b9501232b4.png)

**Comment by josdejong** [comment]
If you don't use stacking it should be doable with CSS. Else you will have to create a new Item type which is not trivial.

**Comment by salmen** [comment]
thank you for your quick reply. i have fixed my prob by adding some time at the end of the timeline to fit the last point items. I think it would be great if we can add custom item types not only styling the existing ones ;) .

**Comment by josdejong** [comment]
> I think it would be great if we can add custom item types not only styling the existing ones 

You can. It requires some work though. We should add docs and an example showing how to create a new type of item.

Basically, all built-in items are here: https://github.com/almende/vis/tree/master/lib/timeline/component/item
they extend the base class `Item` and require certain methods.

You can create a new Item subclass, and register it in the following map:

```js
vis.timeline.components.ItemSet.types['myitemtype'] = MyItemType;
```

Then you can use the type `'myitemtype'` when creating items in a Timeline.

**Comment by salmen** [comment]
yeah thanks a lot !! greate work !! keep going !!
