### ISSUE TITLE
When is vis.css necessary?

### ISSUE THREAD

**Issue by The-Penultimate-Defenestrator** [almende/vis#1801]
I've got a simple network application, which just uses the network in its simplest form. All controls are done through `vis.js`'s interaction methods, or left at the default. I'm not using the built-in onscreen controls.

In this case, is it at all necessary to include `vis.css`? What is this file doing for me? What actually needs to be styled? I don't really notice a difference if I leave the file out.

**Comment by AlexDM0** [comment]
Popups and manipulation for one. The click to activate functionality as well. 

Regards

**Comment by The-Penultimate-Defenestrator** [comment]
Sorry, what is the "click to activate" functionality?

**Comment by AlexDM0** [comment]
Click to use. Sorry

**Comment by The-Penultimate-Defenestrator** [comment]
Ok, great. I don't think I'm using any of those, so I'll take it out.

**Comment by AlexDM0** [comment]
Your call but we can't guarantee everything works.

**Comment by The-Penultimate-Defenestrator** [comment]
Sure. If I see any strange behavior I'll try re-including the CSS file
before I ask here.
