### ISSUE TITLE
Hierarchical Graph is so stretched that it looks like a line

### ISSUE THREAD

**Issue by jKodian** [almende/vis#1804]
I created a hierarchical graph. It has around 75 nodes and 180 edges. But when the graph is drawn it comes as a really stretched out , really zoomed out (basically we can see a blue line) graph. 

Some info
version : 4.15.1
```
options: {
			interaction: {
				hover: true
			},
			layout: {
				hierarchical: {
					direction: "UD",
					sortMethod: "directed",
				}
			}
	};
```

I will provide the data that I use for the graph if its required.

Thanks in advance for all the help

**Comment by Menighin** [comment]
I had the same problem and I have reported on issue #1735. Still no answer though. The main developers seems to be really busy :/

**Comment by josdejong** [comment]
> The main developers seems to be really busy :/

To be more precise: the main developers (Alex and I) both switched jobs, we're no longer working at Almende. I expect the project to be on the back burner the coming period, as Almende does not have the people right now to actively maintain the project. Help from the community is very welcome, see #1781.

**Comment by jKodian** [comment]
@Menighin Thanks for pointing me to the issue you raised. I went through it and checked if using the version 4.10 will solve my issue and it did. Thanks for the help.

@josdejong Thanks for this awesome project.

**Comment by wimrijnders** [comment]
> The main developers seems to be really busy :/

You have no idea.....any help is welcome!

**Comment by wimrijnders** [comment]
For the bookkeeping: Duplicate #1735.
