### ISSUE TITLE
Edges between nodes being clustered remain as ghosts.

### ISSUE THREAD

**Issue by shockdm** [almende/vis#1805]
Hi folks!

I am having a bit trouble with clustering. If nodes within the cluster are not interconnected, i.e. nodes follow star pattern with heart of cluster being in the middle - no issues. However if any of the star branches have edges to other nodes in the same cluster - upon clustering those edges will remain as ghosting edges, i.e:

**Unclustered**:

![image](https://cloud.githubusercontent.com/assets/18537465/14614985/93c45cce-0571-11e6-8474-b808fea5710d.png)

**Clustered based on test node by connection**: 

![image](https://cloud.githubusercontent.com/assets/18537465/14615004/a65f1298-0571-11e6-8c9e-4f71051070e6.png)

Seems that the code only hides edges that are directly connected to the cluster heart. 
Is there anything I am doing wrong? Simply calling:

``` javascript
function createCluster(id){
    network.clusterByConnection(id);    
}
```

I realize that I can manually fetch the nodes within the cluster and go through, hiding edges that are in-between them. But was wondering if this is a part of clustering login already and I am missing something.

Any help would be highly appreciated!
Amazing project by the way! Wouldn't mind contributing.

**Comment by AlexDM0** [comment]
Hi,

Which version of vis are you using? This is an older problem which I thought we fixed. 

Regards

**Comment by shockdm** [comment]
That would be 4.15.1

**Comment by AlexDM0** [comment]
Damn, thought this would be fixed in 4.9. 

It would greatly help if you could look Into this a bit. We don't have much time to work on vis at the moment. There is a clustering file in he lib/network folder. All methods collect data and are forwarded to the _cluster method. There is a method in there that checks which edges to add to the cluster. Something there is wrong I guess. 

Feel up to taking a look?

Cheers

**Comment by shockdm** [comment]
Right, seems its only considering immediate edges.. Will take a look.

**Comment by shockdm** [comment]
Seems that I was able to fix it along with another bug that was exposed once I did. 

In _createClusterEdges:

Basically, the code is using ```childNodesObj[otherNodeId] === undefined``` as an indication of the outward facing edge - hence edge to be created. However ```otherNodeId``` is not reset iteration to iteration of the for loop, so you may erroneously add things to ```createEdges``` if ```otherNodeId``` was set to a certain value by the previous iteration and has not been reset in the current iteration. I.e. in the previous iteration I had an outward facing edge and otherNodeId was set to a certain value that made ```childNodesObj[otherNodeId] === undefined``` true. In current iteration I have a self referencing edge, so I don't change otherNodeId, letting ```childNodesObj[otherNodeId] === undefined``` resolve to true and as a result edge is pushed into ```createEdges``` array. The edges that are created that way also carry the to and from id values from the previous edge, so they look valid on graph (I.e. not ghosting), but are actually just duplicates of a valid edge.

Will submit soon for a pull request...

Another thing - I noticed that as I form a cluster - if I add new edges to the graph that reference nodes within the said cluster from outside - those edges are left half ghosting. I.e. if the node is hidden within the cluster, newly added edge does not properly identify it as hidden in cluster, and does not reference the cluster as would be expected. 

![image](https://cloud.githubusercontent.com/assets/18537465/14645762/f5adb3e6-0624-11e6-940c-b4528634ea4c.png)


Is this something that has been accounted for and is a bug, or has this not been yet implemented as a feature? Just wondering before I go digging in, otherwise I can go ahead and try to implement it.

**Comment by AlexDM0** [comment]
Hi,

Thats true, you cannot attach edges to clustered nodes at the moment. You'll have to uncluster and recluster if you want to do that. If you're feeling up to it, you can add this functionality as well :). There are events on new data to which you can subscribe (dataChanged) in the clustering module. You can then check if the edges would go to something that is already clustered and automatically process the edge.

Cheers!

**Comment by coeus01** [comment]
Hello, what's the status on this fix? I am also having this issue when I cluster, uncluster and then cluster again, for a dirty fix I am setting the data before each clustering but if I want to only cluster 1 node it breaks every other..

**Comment by AoDev** [comment]
Hi, I have not been able to reproduce this. Here is a pen.
http://codepen.io/AoDev/pen/OWBddY

If I understand well, there is a different issue mentioned here which is updating data (edges) while some nodes are clustered, but that should be a different issue.

@shockdm Do you see anything wrong with that pen and is this still an issue?

**Comment by mojoaxel** [comment]
@AoDev Thx for having a look!
