### ISSUE TITLE
Is it possible to bind actions in multiple visjs?

### ISSUE THREAD

**Issue by ImranBug** [almende/vis#1807]
I want to have 2 visjs in same page but they should react as if they are same .. meaning if I use mouse wheel event to zoom in out in one module it should update the other instance as well and move functionality as well.

**Comment by AlexDM0** [comment]
Hi, thats what events are for. There are numerous issues on this with solutions. Im guessing you're using timeline or graph2d?

**Comment by ImranBug** [comment]
Using Timeline & the actual issue is [this](http://stackoverflow.com/questions/36712705/can-we-do-visjs-graph-group-row-to-be-fixed?noredirect=1#comment61017900_36712705).

To which I am purposing to have 2 timelines with one fixed and another scrollable one below it but to user it should seem as one... maybe there is a way to keep first row sticky?.

**Comment by AlexDM0** [comment]
Nope, your solution should work

**Comment by ImranBug** [comment]
[JSFiddle](http://jsfiddle.net/Ltsf0Lb7/16/)

This is what I have ended up with, however there is an animation delay between the sync of both items which I am not sure how to fix.

Here is the code playing the key role:

    // Sync Position
    timeline.on('rangechange', function (changes) {
        if(changes.byUser){
            timelineTopRow.setWindow(changes.start, changes.end);
        }
    });

    timelineTopRow.on('rangechange', function (changes) {
        if(changes.byUser){
            timeline.setWindow(changes.start, changes.end);
        }
    });

**Comment by AlexDM0** [comment]
At the moment this is the only way. 

Regard

**Comment by ImranBug** [comment]
I just added `{ animation: false }` in setWindow method and animation is gone! I think we can close this thread.
