### ISSUE TITLE
Create a group of unselectable nodes

### ISSUE THREAD

**Issue by feustan** [almende/vis#1808]
Hello, 
In my project i want to create a group of nodes which can't be selected by user and a group in which nodes can be selected. How can i do this? 

Thanks.

**Comment by AlexDM0** [comment]
You can't. You could set the selection setting the same as the non-selected settings like color though

**Comment by feustan** [comment]
Ok, thanks. I have an other solution, but I don't know how to make it work. Can I call a event of deselection of node? 
Like: 
network.on("selectNode", function (params) { 
if (group = A){
deselect(params) // or select();
}}

**Comment by AlexDM0** [comment]
Well these methods are in the documentation so I'd say yes

**Comment by feustan** [comment]
Sorry, I found the event deselectNode which can be used in a listner, but i didn't find how to call an event which deselect a selected node.

**Comment by AlexDM0** [comment]
Events are triggers, what you need to actually DO something are methods.
There's a lot of methods for selecting stuff. Take a look at the docs

**Comment by feustan** [comment]
Thanks for your help, now it works :-)
