### ISSUE TITLE
Showing nodes one by one

### ISSUE THREAD

**Issue by nabrih** [almende/vis#1811]
This is a good library, but I need help to showing nodes one by one like using timer

**Comment by AlexDM0** [comment]
Hi,

SetTimeout, the dataset and the hidden option is all you need for this. 

Regards

**Comment by nabrih** [comment]
Thanks AlexDM0,

Hmmm, where I must define it and could you give an example?

**Comment by AlexDM0** [comment]
Hi,

Well setTimeout is a JavaScript method, so Google. The dataset is used in many of our examples, dynamic data ones specifically and finally hidden is an option in the documentation. 

Everything is available. 

Regards

**Comment by nabrih** [comment]
Okay, Thanks AlexDM0

I will try it

Regards
