### ISSUE TITLE
Hierarchical sortMethod: hubsize not working for complex graphs

### ISSUE THREAD

**Issue by rtong** [almende/vis#1813]
Recently, I bumped visjs version from 4.8.2 to 4.15.1 for my app.
The layout of my graph is broken after the update. I dig a little bit and found it was caused by Hierarchical sortMethod: hubsize.

**Reproduce**: The same data set, same options. Only difference is visjs.js version.
For version 4.8.2
https://jsfiddle.net/gkcggxbf/
For version 4.15.1
https://jsfiddle.net/cd0c1vgz/

**Note**:
The broken graph begins with super long edges, but it keeps shrinking to the center. After some time, it will finally stabilized. If you zoom in, you could see the same graph in version 4.8.2

I believe there is something wrong with the new version. Feel free to contact me (shinichiashin@gmail.com) if you have any concern or question. I hope this could be fix as soon as possible, since hubsize is handy for my app.

Thanks a lot!

**Comment by mojoaxel** [comment]
We should check if this is still an issue.

**Comment by KunalAppensure** [comment]
Is this feature working fine in 4.20 version ?? 
Currently we are using 4.8.2 version and we are facing this same problem

**Comment by wimrijnders** [comment]
I ran it with current version v4.19.1, I get this.

![untitled](https://cloud.githubusercontent.com/assets/769037/24408608/872e9a30-13ce-11e7-88dd-620fcb8c61ce.png)

I believe this is OK.

**Comment by wimrijnders** [comment]
This particular layout works with `vis.js v4.19.1`.

However, this is not to say that the issue has been resolved. There are other layouts in which the 'exploding network' thing still happens.

I'm collecting all duplicates to a single issue, so that the problem can be addressed centrally.

**Comment by wimrijnders** [comment]
Duplicate #1735.
