### ISSUE TITLE
API add setSelected Node style

### ISSUE THREAD

**Issue by jianxia612** [almende/vis#1814]
I hope open API setSelected Node style

**Comment by AlexDM0** [comment]
The selected node style is defined in the node options, this will not be added as a argument in the method. Take a look at the documentation on how the style is defined.

**Comment by jianxia612** [comment]
only borderWidthSelected attribute

**Comment by AlexDM0** [comment]
and color.highlight

**Comment by jianxia612** [comment]
thanks,this style only no image style,I hope selected node lable color change！

**Comment by AlexDM0** [comment]
You can use the dataset to update any of the properties of a node and/or edge. Take a look at the dynamic data example.

Regards

**Comment by jianxia612** [comment]
I want to get through node name or id  select network node，change selected color！
![image](https://cloud.githubusercontent.com/assets/10516256/14739371/b53b1dc0-08b9-11e6-91e6-0e1ab4eb6b1d.png)

**Comment by AlexDM0** [comment]
The select events provide you the ID, from that you can use the dataset. Please take a look at the documentation and our examples before posting issues here.
