### ISSUE TITLE
Timeline not showing in IE9 and 11

### ISSUE THREAD

**Issue by KenBonny** [almende/vis#1816]
I implemented the timeline on a page and it shows nicely with Chrome and FireFox. The problem is (as usual) IE9 and IE11.

The funky part is, it adds it nicely to the DOM, but the visual aspect is not updated. The div where I want to show the timeline is populated with the correct sub elements that should show the timeline just like in Chrome. But it stays a very thin grey line in the browser. It's like the height of the div isn't updated correctly.

I call the timeline as:
```javascript
$(document).ready(function (){
    var options = { }; // defined options
    var data; // ajax call
    var container = document.getElementById('timeline');
    var timeline = new vis.Timeline(container, data, options);
});
```

**Comment by josdejong** [comment]
This issue should be fixed in v4.16.1. Are you using the latest version of vis.js?

See #1786

**Comment by KenBonny** [comment]
I downloaded the latest version a week or so ago. I don't have access to my code at home and I don't have access to GitHub at work (I know, governments). I'll check tomorrow and let you know.

**Comment by KenBonny** [comment]
I was using 4.16.0. Today I updated to 4.16.1 and it works like a charm. You guys have very good support. Cudos to you. :+1:

**Comment by josdejong** [comment]
good to hear!

**Comment by robertop87** [comment]
I have installed vis 4.19.1 and I got "vis is undefined" with IE11, but it works perfectly with Firefox and Chrome
