### ISSUE TITLE
How to get the closest item on click (timeline)

### ISSUE THREAD

**Issue by pliablepixels** [almende/vis#1817]
Hi there,
Is there a way to get the 'closest' item next to a tap? In mobile phones, when you are zoomed out, `` timeline.on('click', function (prop) { var item = prop.item}`` often returns NULL and with very _minute_ movements of the finger returns the item.

For the sake of usability, I'd rather that if item returns NULL, I make a best guess and pick the item thats closest to the touch axis. 

Any suggestions on how I could go about it ?

I know I have ``prop.x`` and ``prop.y`` but don't see how to get x/y of items displayed. I can use ``var visible = timeline.getVisibleItems();`` to return a list of indexes of items that are visible, but can't seem to figure out how to get x/y of each item and compare

thanks

**Comment by pliablepixels** [comment]
So far, I've been cobbling together internal functions (not happy about it, but if it works, good) to a point where I know the X & Y of the point tapped and the "X" of the visible items, but I need Y too 

```
console.log ("Clicked X " +prop.x+ " Y " + prop.y);
var visible = timeline.getVisibleItems();
 for (var x = 0; x < visible.length; x++)
 {
      var _item = timeline.itemSet.items[x];
       console.log (_item.left);
                                           
 }
```

**Comment by pliablepixels** [comment]
Okay problem solved by combining prop.group along with prop.x, 
calling getVisibleItems, iterating using internal itemSet and taking minimal of abs(prop.x - _item.left) where _item.data.group==prop.group

**Comment by AlexDM0** [comment]
Hi,

Id recommend using the click event, get the time, binary search through your dataset (not internal) and using the public API calls to select the item. 

We cannot promise your changes will still work in a next version.

Regards

**Comment by pliablepixels** [comment]
Hi @AlexDM0 - thanks. Quick question - I assume my dataset is not guaranteed to be sorted on time - it would depend on the order I insert the elements? Does the internal itemSet guarantee a sorted order for me to do a binary search?

**Comment by AlexDM0** [comment]
Hi,

It doesn't come out of the box I believe but you have full control over your data so it's up to you :)

Cheers

**Comment by pliablepixels** [comment]
Okay, thanks!
