### ISSUE TITLE
One Node whether contian two image or icon. 

### ISSUE THREAD

**Issue by jianxia612** [almende/vis#1819]
I want position node,node's image add water dripping type image or icon

**Comment by AlexDM0** [comment]
One node CAN be an icon and it cannot be two images. You could try to do this with the rendering events (see example). We will not be adding the possibly to contain multiple images in one node. 

Regards

**Comment by jianxia612** [comment]
I think node has background image and image,this so easy like google map positon. thank you !

**Comment by AlexDM0** [comment]
That's not part of our usecases. The API will be convoluted and I don't think it's required.

**Comment by jianxia612** [comment]
renderEvents whether add image,I see this sample add shape!

**Comment by AlexDM0** [comment]
You get a canvas. Draw on it.

**Comment by jianxia612** [comment]
thanks ,I realize.var imageObj = new Image();
					 imageObj.onload = function() {
						ctx.drawImage(imageObj,xy.x-16, xy.y-20,32,42);
					};
					imageObj.src = 'img/kNetwork/position.png';
