### ISSUE TITLE
Tool Tip is not displaying on hover of Node.

### ISSUE THREAD

**Issue by Raghu-muninanjappa** [almende/vis#1825]
Vaadin version : 7.5.9
visjs-addon version : 1.0.1.0
Tool tip is not displaying on hover of a node.

for( int i = 0 ; i<10;i++){
        	Node node = new Node(i, "Node"+i);
        	node.setFontSize(10);
        	node.setTitle("Node Tool Tip"+i);
}

**Comment by AlexDM0** [comment]
Did you include the CSS?

**Comment by Raghu-muninanjappa** [comment]
Externally have not included any css

**Comment by Raghu-muninanjappa** [comment]
Vaadin version : 7.3.3
visjs-addon version : 1.0.0.4
Tool tip WAS displaying on hover of a node.

**Comment by AlexDM0** [comment]
If you do not include the css, the tooltip does not work.

**Comment by Raghu-muninanjappa** [comment]
css is inluded in both version 
visjs-addon version : 1.0.0.4
visjs-addon version : 1.0.1.0

**Comment by AlexDM0** [comment]
I'm sorry, I cannot do any support on packages we do not publish. The examples on the website show that the popups work.

**Comment by Raghu-muninanjappa** [comment]
Finally able to see tool tip by overiding the style
    .network-tooltip {
		position: absolute  !important;		
	}

**Comment by mojoaxel** [comment]
I think this issue can be closed.

**Comment by rasmusblockzero** [comment]
Not sure if there is an official way of showing the tooltip but @Raghu-muninanjappa 's comment made my day (it seems to be vis-tooltip now though)

**Comment by doloresjoya** [comment]
For anyone else viewing/having this issue. 
The css to include is: **vis-network.min.css in addition to the vis.min.css**.
