### ISSUE TITLE
vis.js network graph testing using selenium

### ISSUE THREAD

**Issue by vipinsingh211** [almende/vis#1827]
Looking for solution to test vis.js based network graph using selenium. More details are at [link](http://stackoverflow.com/questions/36866891/vis-js-network-graph-testing-using-selenium)

**Comment by AlexDM0** [comment]
Well as stated in the docs, there are methods for selecting nodes and events that as published on select. The methods do not fire the events though so you could network.emit(eventname, props) or something?

**Comment by vipinsingh211** [comment]
Thanks Alex for responding back. I have figured out the way to test. Only the thing we must know is X and Y offset for any node, we are interested in. Below is the code snippet:

````javascript
'Click on Graph Node' : function(browser) {
      browser
          .moveTo(GRAPH_CANVAS_XPATH, 5, 198)
          .click(GRAPH_CANVAS_XPATH)
 }
````
