### ISSUE TITLE
documented options refused

### ISSUE THREAD

**Issue by pedefe** [almende/vis#1828]
When setting new network options (options structure has been saved in file from previous valid network and then reloaded), I see lot of messages on console like the following :
"Unknown option detected: "blockShifting". Did you mean one of these: enabled, levelSeparation, direction, sortMethod
Problem value found at: 
options = {
  layout: {
    hierarchical: {
      blockShifting
    }
  }
}"
Are this option (and others, not listed up-there like "edgeMinimization", "parentCentralization", "nodeSpacing"...) obsolete ? Or is it only "bad" log ?

Best regards.

**Comment by AlexDM0** [comment]
I think you're using an old version of vis. The docs are only for the latest version.

**Comment by pedefe** [comment]
Hello.
Now i update to @version 4.16.1,  @date 2016-04-18.
Where can I found an up-to-date online doc ?

**Comment by AlexDM0** [comment]
The online doc is up to date. Is it still not working?

**Comment by pedefe** [comment]
Right, It seems that problem does'nt occurs (in 2 minutes of test ;) 
Thanks.
