### ISSUE TITLE
dragging node doesn't change node { x, y }

### ISSUE THREAD

**Issue by pedefe** [almende/vis#1831]
Hello,
When I end draging a node which has 'x' & 'y' attributes (and no 'fixed' attribute), I want to get the new position.
'dragEnd' event gives me the nodeId. So I get the new node attributes from the dataSet myData.nodes: 
`var newNode = myData.nodes.get( nodeId)`, but I get the previous value of 'x' and 'y';
In my case, physics.enabled = false;
Where is the problem ?
Best regards.

**Comment by AlexDM0** [comment]
Those x and y are options. Not real time values. We have a method to get the position. Please refer to the docs.

**Comment by pedefe** [comment]
Perfect. It works.
