### ISSUE TITLE
Graph2D: Mark regions with background color

### ISSUE THREAD

**Issue by davidhadizadeh** [almende/vis#1833]
Hello,

is there a way to mark regions (by Y-values) with different background-colors in a Graph2D?
Example: mark the area between 0 and 30 in red and 30-60 in blue.
I would not like to do it with more graphs + shadows, because the areas should be infinite to right and left x-values.

Thanks in advance.

**Comment by mojoaxel** [comment]
@davidhadizadeh I don't think this is possible at the time. Feel free to create a new feature-request issue.
