### ISSUE TITLE
Display weeks in timeline

### ISSUE THREAD

**Issue by shaniR** [almende/vis#1837]
Hi, 

I would like to know if there is a way to display weeks in timeline in oppose to displaying the dates by default?  For e.g. I want to display the timeline for 4 months (2 months prior to current date and 2 months after the current date) with a weekly representation. I need the weeks to be displayed within the month saying week1, week2 etc. Is there a way to do this?

**Comment by JesperJohnsson** [comment]
`````
var options = {
  timeAxis: {
    scale: 'day',
    step: 7
  },
  format: {
    minorLabels: {
      'day': '[week] w'
    }
  }
};
`````

If you use the above code you can format the timeline axis with week1, w.eek2 etc.
But i have noticed that the formatting is not perfect in some cases. But if you are ok with the imperfection this should work just fine.

**Comment by yotamberk** [comment]
@shaniR Does this solve your question? Can we close the issue?
