### ISSUE TITLE
Add custom options to edges

### ISSUE THREAD

**Issue by HarDGraD** [almende/vis#1840]
I add custom options to edge object for customize rendering edges. Namely add three types of edges(like normal, dashes, and lightning style) and add custom option (like "lineType") to select type of edge. If I set "lineType" when I add new edge it always render edge with "lineType" which i set as default. And I can not select different "lineType"  when I add new edge.

**Comment by DanielZhangQingLong** [comment]
I think you should write some js code to add your custom options.
