### ISSUE TITLE
can we add sub points in timeline like below attachment ?

### ISSUE THREAD

**Issue by navidaziz** [almende/vis#1842]
![images](https://cloud.githubusercontent.com/assets/9557295/15122187/4c67fe5e-1637-11e6-99f0-c9e4dcc7ad1d.png)

**Comment by brichbe** [comment]
[Yeah](http://jsfiddle.net/a34636h3/3/), that can be done.

Basically for each of those subcategories, you'll use an unselectable 'range' item (or you may prefer to use a 'background' item) to display that colored background bar.  Use 'point' items to display each of those data points inside that bar by configuring them so they belong to the same subgroup as the subcategory they correspond to (so they're displayed at the same vertical level).

**Comment by navidaziz** [comment]
thank u got it :)

**Comment by brichbe** [comment]
Don't forget to close this ticket if that resolves it.
