### ISSUE TITLE
Node with id=0 does not show title property

### ISSUE THREAD

**Issue by tblong** [almende/vis#1843]
**vis.js version**: v3.12.0
**Meteor version**: v1.2.1

I've found that the vis version above seems to play nice with Meteor.  I've come across a weird issue where if a node has been given an `id=0`, then that node on the Network when hovered over, does not show the `title` property given; the act of hovering over the node with `id=0` has the side effect of also breaking the title text when hovering over any subsequent nodes.

Here's a [link to the code in question](https://github.com/tblong/Responsive-Website-Development-and-Design/blob/responsive-website-tutorial-and-examples/05_ResponsiveWebsiteTutorial/Week_04/race_data/client/main.js#L138) along with a snippet:

``` javascript
$.each(results, function (index, driver) {
    var driverName = driver.Driver.driverId;
    var driverPosition = Number(driver.position);
    var fastestLap = driver.FastestLap;
    var avgSpeed = 0.0;
    if (fastestLap) {
        avgSpeed = Number(fastestLap.AverageSpeed.speed);
    }

    // push nodes 
    if (avgSpeed > 1.0) {
        nodes.push({
            id: index,
            value: avgSpeed,
            label: driverName + ":" + driverPosition,
            title: avgSpeed + "kph"
        });
    }
});
```

The `index` coming back from jquery is what I'm using as the `id` for each node.  I've noticed that if I skip the first node, which causes the first `id` to become `id=1`, then the `title` property shows up for every node in the network and does not stop working as opposed when there's a node in the network with an `id=0`.  Perhaps I've missed in the documentation where an `id=0` should not be used but I have yet to find such a description.  The `id` property in the docs reads as follows:

![image](https://cloud.githubusercontent.com/assets/12371929/15128678/448bc8f4-160b-11e6-953e-e153d5e137e2.png)

Thanks for any insight anyone can provide.

**Comment by Tooa** [comment]
Hey, this works for me with the latest version from the `develop` branch. Comment if you still have problems. Thanks for your report.
