### ISSUE TITLE
Example that shows how to change cursor on nodes

### ISSUE THREAD

**Issue by mrchess** [almende/vis#1845]
I was trying to figure out if there is a way to set a cursor on a node. eg, `pointer cursor` on a node, `default cursor` on edge, and `move cursor` on canvas.

I looked through the docs and did not find settings for these options. Is this kind of stuff customizable?

**Comment by karanveerm** [comment]
In case anyone also runs into this, I couldn't find a very clean way of doing this, but the following seems to work for me:

```

network.on('hoverNode', (node) => {
  // If you're using react and your encapsulating div has a `ref='graph'`
  // If you're using jquery, you'll probably want to do something like $("#network")[0].style.cursor
  this.refs.graph.style.cursor = 'pointer'
})

network.on('blurNode', (node) => {
  this.refs.graph.style.cursor = 'move'
})
```

**Comment by mojoaxel** [comment]
@karanveerm Thanks!

I think we should create an example that shows how to change the cursor! 
Changing to an feature-request...

**Comment by yotamberk** [comment]
Added with #2463
