### ISSUE TITLE
[Network] Event "deselectNode" - previousSelection.nodes - incorrect ids list

### ISSUE THREAD

**Issue by Alexthetiger** [almende/vis#1848]
In multiselect mode inside "deselectNode" event I can't get only deselected node id . Example: I set multiselect=true and add few nodes to selection. With control-click I remove one node from selection. In event "deselectNode" in previousSelection.nodes I expect node id of one removed node only, but I got ids of all selected nodes.

**Comment by Tooa** [comment]
I can confirm this issue. See jsfiddle [here](http://jsbin.com/bijoxaluxe/1/edit?html,console,output). This is indeed no expected behavior. I will look into it. Thanks for reporting it.
