### ISSUE TITLE
Question about clustering by CID

### ISSUE THREAD

**Issue by gjslob** [almende/vis#1851]
Hi, could you help me with some vis scripting? I'm trying to make a network visualization based on a small data set containing items in 8 categories (all nodes have a cid:(integer) attribute). I want to cluster the items in the groups by CID when zooming out.
`var nodes = [
 {id: 1, label: 'data file',cid:5 },
 {id: 2, label: 'data',cid:5 },
 {id: 3, label: 'file type',cid:4 },
 {id: 4, label: 'file',cid:4 },
 {id: 5, label: 'html tag',cid:5 },
 {id: 6, label: 'html',cid:5 },
 {id: 7, label: 'information',cid:5 },
 {id: 8, label: 'keywords',cid:6 },
 {id: 9, label: 'metadata',cid:6 },
 {id: 10, label: 'minimal information',cid:6 },
{id: 11, label: 'share data',cid:7 },
{id: 12, label: 'template',cid:7 }, `

How do I cluster the items based on CID when zooming out? I'm trying to customize your [http://visjs.org/examples/network/other/clusteringByZoom.html ](url) but I'm not getting very far because I'm a novice programmer.
Thanks for taking time to answer my question.

**Comment by dragonzone** [comment]
Here is the example based on the nodes you provided:

https://jsfiddle.net/0svyq6pe/

**Comment by gjslob** [comment]
Thank you very much, this helps!
