### ISSUE TITLE
moveTo documentation and/or implementation is wrong

### ISSUE THREAD

**Issue by sgsellmann-miovision** [almende/vis#1852]
According to http://visjs.org/docs/graph2d/#Methods the `moveTo()` method accepts a param with the key `animate` to control animation, however in the [code](https://github.com/almende/vis/blob/bc2bc581aaa16905f2ee15b26d3915648c34cc54/lib/timeline/Core.js#L678) on line 18317 the property examined is `animation`.

**Comment by Tooa** [comment]
I suggest to simply change `animate` to `animation` in the documentation. Timeline and Network documentations are correct.

**Comment by macleodbroad-wf** [comment]
This should be labeled as fixed awaiting release I think
