### ISSUE TITLE
[timeline] suggestion: sub-bars

### ISSUE THREAD

**Issue by raphink** [almende/vis#1860]
It would be useful if inside a bar, more dates could placed. For example, when placing kings on a timeline, the bar would represent the full life, but their reign could be represented as a sub-bar of it (maybe even with another style).

**Comment by brichbe** [comment]
That can be done using subgroups.  See my example in #1842 for something of a similar idea.  Using that same pattern, you could create range items inside other range items that each have different styles.

**Comment by jbraun27** [comment]
If I understand correctly, you could also place Kings on a timeline with a range. Start=birthdate, End=death... or currenttime.

**Comment by raphink** [comment]
Thanks, that is indeed a good option.
