### ISSUE TITLE
Add option for timeline to only show dates with events

### ISSUE THREAD

**Issue by alexxcarvalho** [almende/vis#1861]
hi guys, it would be great if there was an option to just show the dates that actually have an event on it, I'm working on a huge timeline with many random events on it, so it would be a lot easier if the timeline was filtered to show only the dates with events

Thanks a lot.

**Comment by mojoaxel** [comment]
@alexccarvalho What dates do you mean? The one on the timeline axis?

**Comment by yotamberk** [comment]
@alexxcarvalho Is this issue still relevant? I don;t understand this feature request

**Comment by mojoaxel** [comment]
@alexxcarvalho It is possible to hide dates in the timeline. You could simply hide timespans of multiple days without any item.
