### ISSUE TITLE
Stack subgroups but don't stack items within the same subgroup

### ISSUE THREAD

**Issue by Kajvdh** [almende/vis#1863]
Hey all, is it somehow possible to stack subgroups, while items within the same subgroups are not stacked?

The only stack setting I found untill now is within the Options object, but if I set it to true, all items within a same subgroup are stacked as well, while I want the items within the subgroup not to stack.

**Comment by brichbe** [comment]
Can you provide an example of what you have that's not working?  [This](http://jsfiddle.net/a34636h3/3/) example I made for #1842 uses subgroups containing items that don't stack.

**Comment by Kajvdh** [comment]
Sorry for the late response @brichbe. Thanks a lot, this was exactly what I was looking for!
