### ISSUE TITLE
Why are there no dependencies

### ISSUE THREAD

**Issue by Spocer** [almende/vis#1866]
Hi,

While going over modules for my project, I noticed that Vis has no listed dependencies in the package file. This seems odd as I thought and modules or other packages which are packaged with Vis should be noted in the dependencies section, not the devDependencies section. This seems to be the only module I use which is like this.

I know that Vis depends on Hammer, so why for instance is that only listed in devDeps and not deps?

Thanks.

**Comment by AlexDM0** [comment]
Hi,

Thats because the compiled version of vis does not have dependencies. 

Regards

**Comment by Spocer** [comment]
This seems like an odd practice. So far, this is the only library I have come across which distributes itself in this manner. Is there a reason for pre-packaging Vis in this fashion? I see in some older versions (4.8.x) this was not the case. What necessitated this change?

**Comment by AlexDM0** [comment]
As far as I know it has always been this way. Reason being that the dist just works.
