### ISSUE TITLE
Timeline Vis.js

### ISSUE THREAD

**Issue by hero2201** [almende/vis#1867]
Dear!

in my Project i am using Vis.js lib, it is so great on my project but i have issue: I want to show range time from click event button, that is can do? example time range in 2016/05/01 -> 2016/05/31 i want to point to  2016/06/01 -> 2016/06/30.
how can do that? everyboy please help me!

**Comment by mojoaxel** [comment]
[RTFM!](http://visjs.org/docs/timeline/)
