### ISSUE TITLE
"RangeError: Maximum call stack size exceeded" with network clusters

### ISSUE THREAD

**Issue by smndf** [almende/vis#1868]
I get this error when I try to display a network with clusters. I noticed that when the network is very small (one cluster of 3 nodes), the cluster is displayed correctly but when I click to open it, I get the error.
I get the same result with Chrome and Safari. 
Here is a copy of the code: https://jsfiddle.net/7ffs8xs8/1/
The trace is always the same:
![capture d ecran 2016-05-23 a 13 51 06](https://cloud.githubusercontent.com/assets/7221857/15469919/879dbef8-20ed-11e6-9b0c-2166145e16e7.png)

**Comment by AlexDM0** [comment]
Do you also get the error in our example?

**Comment by smndf** [comment]
No I don't. 
I compared the two codes and made changes to see where the problem came from. It appears that it was due to the physics options: the error disappears when I comment the whole thing.
https://jsfiddle.net/7ffs8xs8/1/

**Comment by mojoaxel** [comment]
@AlexDM0 Should be labeled as [Bug] and [Network].

**Comment by AlexDM0** [comment]
I'll label it as such but I;m not sure its a valid issue since changes have been made to the source by the user

**Comment by mojoaxel** [comment]
@AlexDM0 is right. It looks like the customized clustering options have a problem. Running into a recursive loop look like a bug to me anyways.

@smndf Is this still an issue for you? What would you like to achieve with your code (using `group` AND `cid`)?

**Comment by smndf** [comment]
No it is not an issue for me anymore. If I remember correctly, I wanted to cluster nodes according to `cid` and color them with `group`.

**Comment by mojoaxel** [comment]
@smndf Thanks for the quick response! 
I think you can close this issue now. The recursive loop problem seams not to be a real issue for others.
