### ISSUE TITLE
Repeat Items on Timeline

### ISSUE THREAD

**Issue by Lukather1971** [almende/vis#1871]
Hi there

I was in looking for a repeat option in the timeline documentation that you can set for each item of a data set.
Example:

var items = new vis.DataSet([
  {
    start: new Date(2010, 7, 15),
    //no end set!!
    content: 'Job A',
   repeat:{interval_type:'minuts',every:'60'}
  }

]);
I want to visualize scheduled tasks from a application.
Is this possible??

**Comment by mojoaxel** [comment]
@Lukather1971 Thats's not possible at the moment. If this is a feature you need please reopen this issue and we will change it to a feature-request.
