### ISSUE TITLE
The right axis does not draw at the right side.

### ISSUE THREAD

**Issue by SergeyMishkin** [almende/vis#1876]
Graph2d | Both Axis Example

The right axis does not draw at the right side. It appears at the left side instead.

You can see it on examples:
http://visjs.org/examples/graph2d/05_bothAxis.html

**Comment by katastrofix** [comment]
Wasn't this resolved via f516cb0?

**Comment by SergeyMishkin** [comment]
Yes, it was!
Thanx!
