### ISSUE TITLE
Select a node from Node Id

### ISSUE THREAD

**Issue by anirban-rc** [almende/vis#1878]
I am implementing a network diagram using vis.js which consists of around 300 nodes.
I have a text field above which gets the node ID value from the user and once found it will select the node in the network.
Similar to 	
	network.on('select', function(params) {
......
}

Is that possible?

**Comment by dimosr7** [comment]
Yes, selecting a node "programmatically" given its ID is feasible with the existing API.
You can use the method **network.selectNodes()**, providing as argument an array with a single element, the ID, like: 
`network.selectNodes(['nodeID'])`

For further reference, check the [methods documentation](http://visjs.org/docs/network/#methods)

**Comment by anirban-rc** [comment]
Thank you

**Comment by hesingon** [comment]
How can I programmatically select a node if I am using react.js? What object (instead of `network`) should I call the `selectNode()` from?

**Comment by hesingon** [comment]
> How can I programmatically select a node if I am using react.js? What object (instead of `network`) should I call the `selectNode()` from?

Ok, this [post](https://github.com/crubier/react-graph-vis/issues/14) answers that question, as i'm using react-graph-vis.
