### ISSUE TITLE
Graph - Hierarchical Layout - many nodes in one level

### ISSUE THREAD

**Issue by imsganesh** [almende/vis#188]
Hi Alex,
I have a new problem by using the Hierarchical layout in the Graph when there are more than 40 or 50 nodes in one level. The nodes seems to be overlapping with each other regardless of the height of the Canvas (div) or what I use in the Physics configuration (pls refer the screenshot). Could you please guide me if there is a way to space out these nodes through configuration or through the library code?

![image](https://cloud.githubusercontent.com/assets/1565731/3433854/86f6f4c4-0083-11e4-8605-bde67bdc702a.png)

Thanks,
Ganesh

**Comment by mahit777** [comment]
Hi I am using the same hierarchicalResolver options but I'm facing the same issue
![capture2](https://user-images.githubusercontent.com/18370058/44944672-8df5f000-adf8-11e8-8866-b0cb04805f29.PNG)
