### ISSUE TITLE
locale not working

### ISSUE THREAD

**Issue by GowrishankarGeek** [almende/vis#1882]
Hi, I can't find a clear answer to this problem i searched lot.
please help me folks
I want to change the labels(AddEdge --> link component) display
var options = {
locales : {
sample: {
edit: 'Edit',
del: 'Delete selected',
back: 'Back',
addNode: 'Add Node',
addEdge: 'Link Component',
editNode: 'Edit Node',
editEdge: 'Edit Edge',
addDescription: 'Click in an empty space to place a new node.',
edgeDescription: 'Click on a node and drag the edge to another node to connect them.',
editEdgeDescription: 'Click on the control points and drag them to a node to connect to it.',
createEdgeError: 'Cannot link edges to a cluster.',
deleteClusterError: 'Clusters cannot be deleted.',
editClusterError: 'Clusters cannot be edited.'
}
},
locale: 'sample',
layout: {
randomSeed: 5,
hierarchical: {
enabled:false,
levelSeparation: 70,
direction: 'LR', // UD, DU, LR, RL
sortMethod: 'hubsize' // hubsize, directed
}
}

**Comment by Tooa** [comment]
Works for me: https://jsbin.com/yuzetilise/edit?html,js,output
