### ISSUE TITLE
how can i set spring without curve

### ISSUE THREAD

**Issue by GowrishankarGeek** [almende/vis#1889]

**Comment by dimosr7** [comment]
Check the [documentation](http://visjs.org/docs/network/edges.html#) for the edges configuration options:
You can use the attribute "smooth", either providing false as a value (if you want a straight edge), or providing an object with the necessary sub-members (type, roundness etc.) to configure the curve of the edge.

Note that you can set this attribute globally for all edges, providing it in the global settings while creating the network. You can then, override this value for specific edges, by re-providing the attribute when creating a new edge.
So, for the global setting:
```
var options = {
    ...
    smooth: false
    ...
}
var network = new vis.Network(container, data, options);
```
Or for each single edge:
`edges.add({id: <edgeID>, from: <fromNodeID>, to: <toNodeID>, smooth: false})
`

**Comment by GowrishankarGeek** [comment]
thank you

**Comment by GowrishankarGeek** [comment]
I'm using visjs network diagram for one of my cloud project I can't find a clear answer to this problem i searched lot. please help me folks I want to change the labels(AddEdge --> link component) display

var options = {
locales : {
sample: {
edit: 'Edit',
del: 'Delete selected',
back: 'Back',
addNode: 'Add Node',
addEdge: 'Link Component',
editNode: 'Edit Node',
editEdge: 'Edit Edge',
addDescription: 'Click in an empty space to place a new node.',
edgeDescription: 'Click on a node and drag the edge to another node to connect them.',
editEdgeDescription: 'Click on the control points and drag them to a node to connect to it.',
createEdgeError: 'Cannot link edges to a cluster.',
deleteClusterError: 'Clusters cannot be deleted.',
editClusterError: 'Clusters cannot be edited.'
}
},
locale: 'sample',
layout: {
randomSeed: 5,
hierarchical: {
enabled:false,
levelSeparation: 70,
direction: 'LR', // UD, DU, LR, RL
sortMethod: 'hubsize' // hubsize, directed
}
}
Error: TypeError: Cannot read property 'object' of undefined
