### ISSUE TITLE
Different colors to edges

### ISSUE THREAD

**Issue by anirban-rc** [almende/vis#1890]
On selecting a node in a network using vis.js can I set 2 different colours as highlight for edges of that node?

**Comment by dimosr7** [comment]
It's the attribute **_color.highlight_**. It can be set globally for all edges in the options, when creating the network, but you can override the global value for specific edges, by re-defining it when adding a new edge in the network.

Check the [docs](http://visjs.org/docs/network/edges.html)

**Comment by anirban-rc** [comment]
But how will I highlight 2 edges(incoming + outgoing) with 2 different colours at the same time?

**Comment by dimosr7** [comment]
On creation of each edge, you will assign a different highlight color on each edge:
```
edges.add({... , color: {highlight: "color-1"},... })
edges.add({... , color: {highlight: "color-2"},... })
```

**Comment by anirban-rc** [comment]
Thank you

**Comment by wimrijnders** [comment]
@IAmLFish Not sure what you mean by 'relative' here. But for the rest, the following appears to fit to your description:

```js
  // create an array with nodes
  var nodes = new vis.DataSet([
    {id: 1, label: 'Node 1'},
    {id: 2, label: 'Node 2'},
    {id: 3, label: 'Node 3'},
  ]);

  // create an array with edges
  var edges = new vis.DataSet([
    {from: 1, to: 2, width:4, color: { highlight: '#ff0000'}, arrows: {to: true}},
    {from: 3, to: 1, width:4, color: { highlight: '#00ff00'}, arrows: {to: true}},
  ]);
```

Which is what @dimosr said. If you mean something else, I'll hear from you.

**Comment by IAmLFish** [comment]
@wimrijnders Even though I understood this better now (thank you so far), I notice now that I was looking for a global way to set the highlight colors considering "to" and "from" for a selected (highlighted) node.
Thus, by relative I mean I want colors relatively to a selected node which means I want one color for inbound arc and another color for outbound arcs (not individual colors for all arcs as in your example!). Is this more understandable?

Furthermore, I am looking from a different context where I use "jupyter notebook" (an interactive, web-based python environment, see here for the library that embeds vis.js: https://ucsd-ccbb.github.io/visJS2jupyter/). 
I know that issues for this case don't belong here, however, I wanted to see first, if at all vis.js is capable of managing different colors for inbound and outbound arcs of a selected node.

**Comment by wimrijnders** [comment]
Had a think about this, it's not possible as you describe it. This would need some extra code to get working.
