### ISSUE TITLE
Swipe result into the next and prev button ?

### ISSUE THREAD

**Issue by Alex36** [almende/vis#1891]
Hello,
Is it possible to use the swipe result (The fact to go to the next dot in one action) in the next and prev buttton.

I want my nav (prev and next) button when push go automaticly to the next dot in the limeline.

Can you help me ?

**Comment by mojoaxel** [comment]
@Alex36 Is this still relevant or can we close it?

**Comment by yotamberk** [comment]
@Alex36 This can be done easily by going over the items and finding the item with the next closest start time and then setting it as the selected item. If you supply a jsbin we can help you write up the function needed to do this.
