### ISSUE TITLE
Is it possible to have the node ID inside a 'dot' shape?

### ISSUE THREAD

**Issue by aanm** [almende/vis#1892]
As a workaround I can create an svg image with the ID on the fly and use the `circularImage`. I was hoping to see if it was possible to have the ID inside and the label outside.

Thanks!

**Comment by dragonzone** [comment]
Just change to 'circle', since dot & circle are the same. Go here for all the types of shapes.

http://visjs.org/examples/network/nodeStyles/shapes.html

**Comment by aanm** [comment]
@dragonzone Thanks for the reply. However, circle doesn't allow to have an ID inside the circle and a Label outside the circle.

**Comment by dragonzone** [comment]
I created an example for a clearer picutre: http://jsfiddle.net/198yLuk9/

I hope this helps!

**Comment by aanm** [comment]
@dragonzone Just tried it out, it's really cool. One more thing, how can I make it adjustable with the node size? For a node size of, let's say 50, the font size of 10px is really small.

**Comment by dragonzone** [comment]
@aanm - You can set the outer size label the same size as the node. For the inner label, I notice it is ~1/2 size of the node. I updated the example here for you to study: http://jsfiddle.net/198yLuk9/1/

**Comment by aanm** [comment]
@dragonzone Thanks for the explanations. I'll close up this issue. Thanks
