### ISSUE TITLE
Clusters still moving after disabling physics

### ISSUE THREAD

**Issue by smndf** [almende/vis#1893]
I have a network of nodes with some clusters and a button which is meant to freeze the nodes by applying:
`var options = {physics: {barnesHut: {gravitationalConstant: 0,
centralGravity: 0, springConstant: 0}}};`

But a small problem I encounter is that when I click on this button before the stabilization, the nodes stop moving but the clusters still keep moving until they reach some place and stop. It lasts a few seconds. My guess is that these clusters "follow" the nodes they contain with a slight delay.

In my code each cluster's mass is equal to the sum of its nodes masses. If I set the clusters mass = 0 then they don't move anymore but they also don't move when physics are enabled.

Is it possible to fix this? So that clusters move when physics are enabled and stop instantly when clicking on the button?

**Comment by dimosr7** [comment]
Have you tried disabling completely the physics simulation, by using: 
`network.setOptions({physics: {enabled: false}});`
