### ISSUE TITLE
Timeline vertical spacing offset

### ISSUE THREAD

**Issue by Kajvdh** [almende/vis#1895]
Hey all,

I've noticed that when an entry on the timeline is out of the vision of the current scale, a whitespace placeholder is kept untill the entry is x days before the startDate of the current scale.

How much is this x days, and can it be changed?

<img width="1095" alt="timeline-spacing" src="https://cloud.githubusercontent.com/assets/950503/15873064/259fec5a-2cfd-11e6-9b3e-9a9cf1a2191e.png">

**Comment by mojoaxel** [comment]
@Kajvdh Is this still relevant or can we close it?

**Comment by yotamberk** [comment]
This doesn't happen anymore in v4.17.0 (since the items get calculated correctly now for there visibility in view)

**Comment by mojoaxel** [comment]
@yotamberk I think you misunderstood. This is still the default behavior, but I think we can close it anyways.

**Comment by mojoaxel** [comment]
may be a duplicate of #1179
