### ISSUE TITLE
Use Edge Weights to scale force in the force atlas physics algorithm of the networks library

### ISSUE THREAD

**Issue by oussjarrouse** [almende/vis#1897]
Hello,

In Gephi, using the Force Atlas 2, it is possible to include edge weights in the calculation of force, with a scaling factor between 0.0 and 1.0, where 0 is no effect for edge weights and 1.0 full effect of edge weights.

It could be part of the force atlas parameters, with a default value of 0.

The edge weight is described in this paper:
http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0098679

**Comment by wimrijnders** [comment]
Closed due to inactivity. Feel free to reopen if this is still relevant.
