### ISSUE TITLE
Prevent Nodes overlap by setting physics:false

### ISSUE THREAD

**Issue by anirban-rc** [almende/vis#1899]
I have a network diagram having 300+ nodes with multiple edges.
On generating the network I am seeing nodes overlap of different trees. 
Is it possible to prevent overlapping nodes of different trees in the network diagram by setting physics:false ?

**Comment by mojoaxel** [comment]
@anirban-rc Could you provide a demo or a screenshot of this problem?

**Comment by mojoaxel** [comment]
closed due to inactivity.
