### ISSUE TITLE
Graph2D with both axes defined renders badly in Chrome, Firefox, Edged

### ISSUE THREAD

**Issue by davidwhewell** [almende/vis#1900]
This occurs on your given example as well:

http://visjs.org/examples/graph2d/05_bothAxis.html
- the gridlines are above, but the graphs themselves are rendered below, without gridlines
- (minor issue) the axes overlap each other slightly making them unreadable.

Tested in most recent chrome, firefox and edge on Windows 10.  Screenshot of the example above given.

![visjsbothaxes](https://cloud.githubusercontent.com/assets/19840266/15934804/c7b90354-2e5c-11e6-9237-3e05bfce9f94.png)

**Comment by Tooa** [comment]
Hi, can you look at the example again? It works for me using Linux Mint and Chrome Version 55.0.2883.87 (64-bit).

**Comment by davidwhewell** [comment]
My own example I built still has the same issue, in both chrome.  It references vis 4.16.1 (not a static local copy).

The example on the visjs.org site works for me on both Edge and Chrome, so obviously something has changed in the last 6 months in the example, or in visjs, to fix the issue, and I need to identify that and retrofit it into my own example.

This issue can be considered closed.
