### ISSUE TITLE
How to update the timeline with items from a function

### ISSUE THREAD

**Issue by Kaliph** [almende/vis#1904]
Hi there, I have setup a vis timeline in my local webside, which i display in browser. I am using groups. 
At the moment all my items and groups are stored in a local .js file named timeline.js.
Now I would like to expand the functionality of the timeline so it is possible to update the items and maybe later also groups from a server. I was already able to send the data from my server to the webside and I have all the necessery data in the timeline.js file already. At the moment I am calling a function inside timeline.js with the items data... parse it and try to add the data to the timeline.
But as soon as I add the line `items.add({
           id: id,
           group: group,
           start: start,
           end: end,
           content: content
         });` The for loop does only run once and not for all data... also the timeline does not get updated. Can someone point me to the mistake I am doing here.? Do the items have to have unique data? what happens if there are two events having the same data...? Br Kaliph
Also I would like to know how I can set the first and the last row to a fixed size, because like in my fiddle the last row is larger then the other rows. this happens also to the first row, if the last one has no items. Thanks

Here is the js fiddle Link.
https://jsfiddle.net/Kaliph/hzaecmwq/124/

`  function UpdateTimeline2 (data, next){

```
var j = 0
  for (; j < length;) {
```

// Data gets processed here so I can gather id, group, etc...

```
     var items = new vis.DataSet();

   items.add({
       id: id,
       group: group,
       start: start,
       end: end,
       content: content
     });

        j++;
    };
```

};  `

**Comment by roboslone** [comment]
Don't you need to also call `redraw()` after adding items?

**Comment by mojoaxel** [comment]
@Kaliph Can we close this?

**Comment by Kaliph** [comment]
Yes u can. Thx

Von meinem iPhone gesendet
