### ISSUE TITLE
Networks: 2 directed edges into one undirected?

### ISSUE THREAD

**Issue by FoxWhite** [almende/vis#1909]
Hello! Sorry for I haven't found anything in the docs. Say I've got two nodes, A and B. And the way I receive the data I get the connection between A and B as two edges: {from: A, to B} and {from: B, to: A}.
This is rendered as two separate edges. The question is, is there some built-in way to render these as one undirected edge? (or maybe a single edge with arrows on both sides)

**Comment by TheIronDeveloper** [comment]
Don't know if this helps, but you are free to choose how the arrows get rendered for each edge. You might need to do a little manual checking to verify if you have two nodes that point to one another. If you do, you can simply set the arrows to point back and forth.

Check out http://visjs.org/docs/network/edges.html for more info.

**Comment by mojoaxel** [comment]
@FoxWhite Is your question answered? Can we close this issue?

**Comment by FoxWhite** [comment]
@mojoaxel well the issue is not relevant to me anymore (I managed with some hacking), however it might be a thing to improve. So I guess you might consider moving it to the backlog and close the issue here.

**Comment by mojoaxel** [comment]
@FoxWhite Thx for the feedback. 

There is no build-in way to "merge" edges. This can simply be done by hand if needed. If anybody thinks this should be part of the library feel free to open a feature-request issue for that, then we can discuss it.
