### ISSUE TITLE
"selectNode" event only fired on click?

### ISSUE THREAD

**Issue by gossi** [almende/vis#1915]
Hey guys,

I'm working with the `Network` visualization. I do have an event listener on `selectNode`. I realized it is not fired when calling select nodes programmatically, e.g. `network.selectNodes([someId]);`. I am wondering whether this is a bug or the expected behavior. Although this may be intended I'm questioning this in case of consistency of the API, because I'm listening on `selectNode` and not `selectNodeOnClick`.

Thanks for clarification.

**Comment by Tooa** [comment]
Can you check with the latest visjs version? Is this still an issue for you?
