### ISSUE TITLE
Get end date from Event Properties

### ISSUE THREAD

**Issue by SpringsTea** [almende/vis#1921]
I'd like to be able to get the start _and_ end date (if available) when I select an Item.

Right now it looks like: 

    timeline.on('select', function(properties){
      var props = timeline.getEventProperties(properties.event);
      console.log(props.time)//Fri May 27 2016 13:32:23 GMT-0400 (Eastern Daylight Time)
  
    });

But there's no way to get an end date, and I can't figure out a way to work around this.

**Comment by brichbe** [comment]
See the documentation for getting [event properties](http://visjs.org/docs/timeline/#getEventProperties)

The `item` property gives you the ID of the clicked item.  If non-null, use that to get the corresponding Item object from your `DataSet` that's populating your timeline.  From that, you can access its `start` and `end` properties.

**Comment by mojoaxel** [comment]
@SpringsTea You need additional information or can we close this issue?

**Comment by SpringsTea** [comment]
Sorry yeah, that was the answer I needed.
