### ISSUE TITLE
Timeline: video timeline (frame based) with no dates

### ISSUE THREAD

**Issue by adamtal3** [almende/vis#1925]
Is it possible to customize the timeline to the point it doesn't care about dates? (I don't mind having all my data set to 01/01/2001 or something like that).

I want to use the timeline for a video, so the timeline should start at 00:00:00:00 and end at 01:44:15:05 (for example) where the format is Hours:Minutes:Seconds:Frames and the frames are calculated using a configurable fps option.

So I need to display a custom formatted time value (using my own function). Prevent the timeline for too much zoom-out. Don't show anything in the timeline related to days / months / years. And make the vertical lines snap to frames instead of seconds/minutes.

Is all that possible or am I trying too hard to make vis work for me?

**Comment by gabfusi** [comment]
First of all, Great project!
Btw, same issue here!
Tried to play with min/max, start/end options but cannot figure out how to create a frame based timeline.

eg. this will render a 3600000 years timeline!
`var options = {
    min: 0,
    start: 0,
    end: 3600000 // 60*60*1000 = 1h in milliseconds
}`

Is Vis parsing numbers as years?

**Comment by pantaryl** [comment]
@brichbe, this is a similar issue looking to do something that I am.

**Comment by mojoaxel** [comment]
@adamtal3 Is this issue still relevant or can we close it?

**Comment by adamtal3** [comment]
I've chosen a different approach for my needs so I no longer need this functionality from vis.

You can close the issue but it'll be great if you can just specify that this is not achievable "out of the box" with vis (or maybe it is?).

**Comment by mojoaxel** [comment]
Having a number-based timeline (no dates) is a big feature-request! We track it with #92 
I hope some day somebody will find the time to implement it!

_I'm going to label it as duplicate of #92 and close this one._

**Comment by no1youknowz** [comment]
@adamtal3 I'm looking for this same functionality and was hoping that visjs included it.  Sigh.

How did you end up solving this issue?

**Comment by GaneshNimkar** [comment]
> Is it possible to customize the timeline to the point it doesn't care about dates? (I don't mind having all my data set to 01/01/2001 or something like that).
> 
> I want to use the timeline for a video, so the timeline should start at 00:00:00:00 and end at 01:44:15:05 (for example) where the format is Hours:Minutes:Seconds:Frames and the frames are calculated using a configurable fps option.
> 
> So I need to display a custom formatted time value (using my own function). Prevent the timeline for too much zoom-out. Don't show anything in the timeline related to days / months / years. And make the vertical lines snap to frames instead of seconds/minutes.
> 
> Is all that possible or am I trying too hard to make vis work for me?

How you implemented this requirement, I have the same
