### ISSUE TITLE
Roundness of the Edges

### ISSUE THREAD

**Issue by zlaja1983** [almende/vis#1933]
![screen shot 2016-06-29 at 2 03 14 pm](https://cloud.githubusercontent.com/assets/7635374/16463124/5aad3aa4-3e02-11e6-80c7-8b36aa83429b.png)

I am seeing the roundness in the edges.
1. Admin is a box node
2. Dialing is an edge with width 50 that has two nodes (small blue dots)
3. Interact is an edge 

I have set the physics to false for edges, nodes and layout but I am still seeing this roundness issue of the edges.

**Comment by zlaja1983** [comment]
Note Admin node and first blue dot node within Dialing edge is connected via an edge with dashes. If the connection is not made then I do not see this roundness  at all. Is there a way to prevent it from seeing it in the scenario I've described above.

**Comment by zlaja1983** [comment]
Update, if dashes are set to false the roundness goes away FYI. Not sure if this is a bug or not, IMO it should be fixed.

**Comment by mojoaxel** [comment]
I don't think this is a problem but if anybody thinks otherwise please reopen!
