### ISSUE TITLE
Hierarchical nodes drawn on top of each other

### ISSUE THREAD

**Issue by spiffytech** [almende/vis#1935]
![Screenshot](http://i.imgur.com/dpiT2XZ.png)

<hr />

![Screenshot, bigger graph](http://i.imgur.com/711yeUV.png)

My graphs sometimes have nodes stacked on top of each other. It's unpredictable. Below is a small data+code example that replicates the issue, but I've seen it with much larger and more complex graphs, where entire trees are stacked upon each other.

You'll note that it's fragile - if you remove any node, or reorder the array of nodes, they don't overlap anymore.

The bug appears to manifest in `this._condenseHierarchy()`, because several nodes get assigned the same `x` coordinate.

``` javascript
const data = {
    "nodes": [
      {
        "id": "p.2.0",
        "label": "tag: 2.0",
        "shape": "image",
        "image": "images/pod.png"
      },
      {
        "id": "p.1.1",
        "label": "tag: 1.1",
        "shape": "image",
        "image": "images/pod.png"
      },
      {
        "id": "p.0.1",
        "label": "tag: 32d5b4e735d",
        "shape": "image",
        "image": "images/node-up.png"
      },
      {
        "id": "s.cnt-dashboard",
        "label": "RTP RTP RTP RTP RTP RTP RTP RTP ",
        "shape": "box"
      },
      {
        "id": "s.dashboard",
        "label": "Service\nlab",
        "shape": "box"
      }
    ],
    "edges": [
      {
        "from": "s.cnt-dashboard",
        "to": "p.0.1",
        "arrows": "to"
      },
      {
        "from": "s.dashboard",
        "to": "p.2.0",
        "arrows": "to"
      }
    ]
  };
  var container = document.getElementById('mynetwork');
  var options = {
    physics: {
      enabled: false
    },

    layout: {
      hierarchical: {
        direction: "UD",
        sortMethod: "directed"
      }
    },
  };
  var network = new vis.Network(container, data, options);
```

**Comment by spiffytech** [comment]
Is vis.js supposed to support multiple disconnected networks inside the same graph? I've been doing that, and 99% of the time it works fine. Wondering if that 99% is accidental, and this bug is because vis.js expects all nodes in the graph to be connected when it crawls the network to determine the hierarchy levels? 

![img_20160714_161832](https://cloud.githubusercontent.com/assets/77867/16854677/06b4f506-49e0-11e6-854b-6161f1884669.jpg)

I think the bug *may* be related to `crawlNetwork()` assigning the wrong hierarchy levels to the nodes. Some debugging shows what look like incorrect values, but I can't tell yet if I'm interpreting the data correctly.

Anyway, if I manually assign each graph node a level, the problem does not manifest for this particular sample data. I do not yet understand the vis.js network code well enough to say whether that's coincidence or solution.

**Comment by mojoaxel** [comment]
@spiffytech Thanks for the detailed description!! I created a [jsbin](http://jsbin.com/bahuyubogo/edit?js,output) to fiddle around with that issue.

Looks like a bug to me.
You could try the default sortMethod and change the direction:
```js
layout: {
  hierarchical: {
    direction: "DU",
    //sortMethod: "directed"
  }
},
```

**Comment by spiffytech** [comment]
Unfortunately, the `direction` and `sortMethod` are locked by project requirements.

Deadlines move for no man, so I'm trying to track the problem down (very slow going due to my ignorance of the Vis internals). I'm struggling to follow the data flow, since all the calculations change mutable data structures in-place, rather than returning values. Can you offer any guidance as to where a hierarchy level calculation might go wrong?

(Of course, I'd welcome any Vis maintainers fixing this, too. You could do it much faster than me figuring it out.)

**Comment by Ganon-M** [comment]
Any progress on this issue? I have encountered the exact same problem. I would like to look into the issue
myself but don't have time at the moment.

**Comment by wimrijnders** [comment]
I am happy to report that this issue does not occur any more in `vis.js 4.19.1`. This is the result of the jsbin with this version:

![download](https://cloud.githubusercontent.com/assets/769037/25555153/17d844c2-2cdf-11e7-95e4-d8c83717f07c.png)

I'm closing off this issue.
