### ISSUE TITLE
No interaction with timeline in IE10

### ISSUE THREAD

**Issue by siliconalchemy** [almende/vis#1937]
In IE10 on the visjs timeline examples, there is no interaction working with the timeline - cannot select items or drag the timeline.

**Comment by mojoaxel** [comment]
I can **not** confirm this.
I tested the [timeline examples](http://visjs.org/timeline_examples.html) with Internet Explorer 10.0.9 and had no Problems: zoom, pan, select, drag...everything works fine.

**Comment by siliconalchemy** [comment]
Odd, it does seem to be working now.  I had similar problem with fullcalendar where it wasn't rendering/working properly then it started working (in IE10), and others have reported the same problem.

In IE10 on the main timeline examples page, if you open the console, do you see this:
```
HTML1509: Unmatched end tag. 
timeline_examples.html, line 129 character 1
SCRIPT5007: Unable to get property 'nodes' of undefined or null reference 
vis.js, line 33867 character 9
```

**Comment by siliconalchemy** [comment]
I also see 'dancing items'.  For example on the animateWindow.html page, the items shift up and down by a pixel or so about every second.

**Comment by mojoaxel** [comment]
> HTML1509: Unmatched end tag. 
timeline_examples.html, line 129 character 1

This is just some garbage html. Thanks! I'll fix that.

> SCRIPT5007: Unable to get property 'nodes' of undefined or null reference 
vis.js, line 33867 character 9

I think the calling of vis.js on the timeline examples overview page is an error. Thanks! I'll fix that.

> I also see 'dancing items'. For example on the animateWindow.html page

No "dancing" in my IE10 :cry: (Maybe your items just have more fun!?)
