### ISSUE TITLE
[Timeline] Does items in the same group support sorting?

### ISSUE THREAD

**Issue by wmyivy** [almende/vis#1942]
I have a group contains 2 items: item1 and item2.
When I draw timeline, item2 always appears on the top of item1,
is there a way to let items in the same group sorting by their id in the ascending way?

**Comment by brichbe** [comment]
There are a couple Timeline examples related to sorting, and there are numerous tickets related to this topic, too.  Recommend you research more into those things, and if you're still not sure, provide a jsbin example here and describe exactly how it's not working and what you'd like it to be instead.
