### ISSUE TITLE
Print a netWork

### ISSUE THREAD

**Issue by AlexSegna** [almende/vis#1943]
Hi, i realize a network using vis.js.
Now i need to print this network,but i don't try anyway to do it.

**Comment by mojoaxel** [comment]
You could use the print function of your browser (Ctrl+P) or use [server-side rendering](http://www.feedhenry.com/server-side-pdf-generation-node-js/) to generate e.g. a PDF.

**Comment by mojoaxel** [comment]
@AlexSegna Please close this issue if your question is answered. Thanks!

**Comment by mojoaxel** [comment]
You also could export the canvas to a png image and print that. See also https://github.com/almende/vis/issues/1784#issuecomment-217120367)

**Comment by fmassicano** [comment]
Print Canvas to PNG produces a very poor quality image. The right way to do that is vis allow to export to svg.

**Comment by mojoaxel** [comment]
> The right way to do that is vis allow to export to svg.

@fmassicano Because network-charts are rendered in canvas there is no easy way of exporting this as SVG.

**Comment by fmassicano** [comment]
@nevakee716 Can you share some piece of code that describes what you did? I would like to try that.

**Comment by nevakee716** [comment]
https://github.com/nevakee716/cwNetwork/blob/master/src/cwLayoutNetwork.download.js

it's pretty dirty but work, when it's too big chrome doesn't want to download, edge is always ok
