### ISSUE TITLE
TImeline Event when current time touches an item

### ISSUE THREAD

**Issue by surendrans** [almende/vis#1948]
Is there an event when the current time matches the start time of the item ?

**Comment by brichbe** [comment]
No there isn't.

**Comment by mojoaxel** [comment]
Maybe someone is willing to implement such an event!?

**Comment by yotamberk** [comment]
@surendrans Why would you want this?

**Comment by mojoaxel** [comment]
@surendrans I would recommend handling these types of business logic outside of the timeline in your own application.
