### ISSUE TITLE
layout option to have "end date" happen at the end of the day

### ISSUE THREAD

**Issue by jcdecauxna** [almende/vis#1949]
hello,
I want to use the timeline to show date reservations on a calendar. the problem is I can't find an option to see the end date ending at the end of the day instead of the beginning.
If you look at item 4 on this example: [http://visjs.org/examples/timeline/basicUsage.html] 
in the code, it ends on the 19th and it lasts for 4 days (16->19). so we should expect the yellow box drawn on the timeline to show accross 4 days and not 3. Because on the 19th, the day is booked.

![timeline](https://cloud.githubusercontent.com/assets/13948613/16718569/3c4d119c-46ef-11e6-8510-01a4b95c9889.JPG)

right now, I have to add a day to the end date to make it work :-(
thanks for your help

**Comment by brichbe** [comment]
That's not currently an option for the Timeline, nor is it a fault of the Timeline.  The Timeline renders the data you give it -- it's up to you to provide the _correct_ data.

This is not a Timeline question, but a question of how dates work in Javascript.  If you provide a date as a year-month-day String, the "time" portion of that date will be the beginning of that day (12AM 00:00:00).  So if you want the end of your item to be at the end of the calendar day (12 PM midnight) 15 July 2016, you need to specify it as `end: '2016-07-15 24:00:00'`

**Comment by yotamberk** [comment]
@jcdecauxna I think we can close this issue. @brichbe is correct, it should be passed throught the data with an end date set to `end: '2016-07-15 24:00:00'`
