### ISSUE TITLE
Problem with locale

### ISSUE THREAD

**Issue by SchDen** [almende/vis#1952]
I tried use locale from moment.js with `2.14.1` version and i got this result.
`https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.14.1/locale/ru.js`

![bug](https://cloud.githubusercontent.com/assets/1484977/16759907/f1232948-4821-11e6-8f8e-e4a20e8cbd7c.png)

i got correct result only with `2.10.5` (or `2.10.6`) version.

![correct](https://cloud.githubusercontent.com/assets/1484977/16759987/5cb467da-4822-11e6-9fd3-ee066bd96db3.png)

**Comment by mojoaxel** [comment]
@SchDen Is this still an issue or can we close this?

**Comment by SchDen** [comment]
Hi @mojoaxel 
Yes, close
