### ISSUE TITLE
Suggestion: Graph2d always draw bar up to the next datapoint

### ISSUE THREAD

**Issue by BeCracked** [almende/vis#1959]
Hello,

I've been using your library to draw graphs for energyconsumptions of planned productionruns. The energyconsumption though is only really relevant in terms of 15 minute intervals.
The bar-style looks nicer and is easier to handle too, since for the usual drawn line I have to create extra datapoints at the end of an interval for it to sort of properly show the actual value of the interval for the whole interval and not just the beginning where the datapoint is defined.
So I looked for such an option but couldn't find it. It isn't totaly necessary but it would definetly look better if the bars where always sort of 'united', if you know that I mean.

Here is a picture of what it looks atm if you zoom in too much:

![image](https://cloud.githubusercontent.com/assets/11634525/16823548/73396926-4965-11e6-86af-3d35ba48a9a7.png)

and here how I'd like it too look even at quite high zooming stages:

![image](https://cloud.githubusercontent.com/assets/11634525/16823561/88b32652-4965-11e6-9a4e-5b5259541766.png)

If there is a way to do this with width and minWidth, I am sorry, but I couldn't figure it out.

**Comment by mojoaxel** [comment]
[Have a look](http://visjs.org/docs/timeline/#Configuration_Options) at the `zoomMin` option.
If you set it e.g. to 6 hours (1000 * 60 * 60 * 6) you should be fine.

**Comment by BeCracked** [comment]
A bit late but: Yes, worked like a charm. Thanks a lot!
