### ISSUE TITLE
Less than day events to display as a whole day event

### ISSUE THREAD

**Issue by sd101** [almende/vis#1966]
Would like to have any event that is less than a day to display as the entire day.  Currently event shows as a dot

**Comment by brichbe** [comment]
Can you provide an example jsbin?  A dot item implies you're only providing a `start` date/time.

**Comment by yotamberk** [comment]
@sd101 Is this issue still relevant?

**Comment by mojoaxel** [comment]
@sd101 You could provide a time with your `start`and `end` date:
```
start: '2016-12-24 00:00:00', 
end: '2016-12-24 23:59:59'
```
