### ISSUE TITLE
Network module - integration with WordPress/Drupal

### ISSUE THREAD

**Issue by iantic** [almende/vis#1974]
Hi,
has anyone used a CMS (WP/Drupal) to manage vis network data?

I would need a simple network (nodes with images and URLs) and CMS taxonomy would probably be a good source of data, but I don't know where to start from.

Any advice or examples would be much appreciated :)

**Comment by mojoaxel** [comment]
@iantic I think this kind of generic questions is better asked on [stackoverflow](http://stackoverflow.com/questions/tagged/vis.js).

**Comment by iantic** [comment]
You are right, thank you. I posted the question [there](http://stackoverflow.com/questions/38415902/network-module-integration-with-wordpress-drupal), too.

**Comment by mojoaxel** [comment]
@iantic Can you please close this issue here. Thanks.

**Comment by tbaltrushaitis** [comment]
I was doing something like this: http://woh.gsm-center.com.ua/

**Comment by iantic** [comment]
looks very similar to what I am looking for!

How do you load the data? It doesn't look like CMS...

**Comment by tbaltrushaitis** [comment]
Data loaded into vis by AJAX request to server-side PHP script which load it from the mysql directly.
I believe you can easy create such a script but first you should know the DB structure, its tables and what fields to get from them to meet your requirements.

Hope this helps!
