### ISSUE TITLE
Opening "importingFromGephi.html" locally

### ISSUE THREAD

**Issue by kummi87** [almende/vis#1978]
This is probably a very stupid question: I'd like to use "importingFromGephi.html" as the basis for my network. When I open the example on http://visjs.org/examples/network/data/importingFromGephi.html, everything shows up perfectly. However, when I download vis.js and open the local HTML file on my computer, the network doesn't show up. Does anyone have an idea what I am doing wrong?

**Comment by mojoaxel** [comment]
Please make sure you have the following dependencies ([on top of importingFromGephi.html](https://github.com/almende/vis/blob/master/examples/network/data/importingFromGephi.html#L7-L10)) also downloaded an in the right directorie-structure:
```js
  <script type="text/javascript" src="../exampleUtil.js"></script>
  <script type="text/javascript" src="../../../dist/vis.js"></script>

  <link type="text/css" rel="stylesheet" href="../../../dist/vis.css">
```

You also need `http://visjs.org/examples/network/datasources/WorldCup2014.json`.
see [importingFromGephi.html#L97](/almende/vis/blob/master/examples/network/data/importingFromGephi.html#L97)

**Comment by kummi87** [comment]
Thanks for your help and the quick response. I have downloaded the complete ZIP package (http://visjs.org/download/vis.zip) and extracted it. As far as I can see, it includes all dependencies. Could you try if you can reproduce that?

**Comment by mojoaxel** [comment]
Please check for errors in your console (F12).

**Comment by controversial** [comment]
@kummi87 Have you resolved this issue? If so, please close it. If not, might we be able to help further?

**Comment by kummi87** [comment]
I've had a look at it again. It seems to be a security issue in Google Chrome and Microsoft Internet Explorer. Mozilla Firefox worked fine. Thanks again for the help!
