### ISSUE TITLE
Right Axis Not Working in Graph2d for vis.js v4.16.1 and v4.16.0

### ISSUE THREAD

**Issue by ShaneAlderton** [almende/vis#1979]
When using a right Y axis, it is appearing on the left.  On top of the left Y axis if present.
The following Graph2d examples exhibit the problem:
http://visjs.org/examples/graph2d/04_rightAxis.html
http://visjs.org/examples/graph2d/05_bothAxis.html
Problem confirmed present in v4.16.0 and not present in v4.15.1

**Comment by mojoaxel** [comment]
I can also confirm this is an issue since 4.16.0. 
No problem in 4.15.1: [see jsbin](http://jsbin.com/tovuzip/edit?html,output)

@AlexDM0 please mark as [Bug] and [Graph2D]

**Comment by AlexDM0** [comment]
@mojoaxel @ludost is currently the main maintainer of the project. In future issues, please refer to him.

Regards

**Comment by ShaneAlderton** [comment]
I can see there's a change between 4.15.1 and 4.16.0 in lib/timeline/component/DataAxis.js on lines 215 and 219
4.15.1:
    if (this.options.orientation === 'left') {
      this.body.dom.left.appendChild(this.dom.frame);
    }
    else {
      this.body.dom.right.appendChild(this.dom.frame);
    }

4.16.0:
    if (this.options.rtl) {
      this.body.dom.left.appendChild(this.dom.frame);
    }
    else {
      this.body.dom.left.appendChild(this.dom.frame);
    }
  }

Reverting this part of the code to what was in 4.15.1 addresses the issue, but I don't yet know the code well enough to know if that is the right solution.  I'm running with the customisation for a while to see.

**Comment by ShaneAlderton** [comment]
I suspect the correct solution may be:
```
    if (((this.options.orientation === 'left') && !this.options.rtl) || ((this.options.orientation === 'right') && this.options.rtl)) {
      this.body.dom.left.appendChild(this.dom.frame);
    }
    else {
      this.body.dom.right.appendChild(this.dom.frame);
    }

```
However I'm sure there's a more efficient, or at least a more compact way, to address this.
`(this.options.orientation === 'left') !== this.options.rtl`
did not work.  Presumably because this.options.rtl may not be defined.

**Comment by AdamNowaczyk** [comment]
@ShaneAlderton, thanks for reporting this. Just voting for fixing this as we're using he feature. So far I'll stick to 4.15.1 and will wait for the fix.

**Comment by Stexxen** [comment]
Already fixed with https://github.com/almende/vis/commit/f516cb0721248ef5c5792195739aee1bc2e5fb79
