### ISSUE TITLE
Ability to drag (vertically) to reorder Items

### ISSUE THREAD

**Issue by kylerberry** [almende/vis#1985]
I'd like the ability to reorder an item (not within a group) by dragging it vertically in the timeline. I see that there is similar functionality for groups. Is there a systemic reason this hasn't been implemented yet? If not, this is a feature request that I'd be willing to work on.

**Comment by mojoaxel** [comment]
@kylerberry Sorry for the late answer. Items are auto-arranged. You can reorder items manually but the order propably is changed by moving or zooming the timeline. A change would require some major changes, but of course you are invited to try!  Or should we close this issue?

**Comment by kylerberry** [comment]
@mojoaxel The project for which I would have liked the change has hence died. Seeing as there are no other "+1's" it's likely no one else cares. I'm comfortable closing this issue. When I have free time I may revisit in the future to see if I can work this in as a feature request. Thanks.
