### ISSUE TITLE
Show tooltip when hover over node using qTip2

### ISSUE THREAD

**Issue by NV-FIL** [almende/vis#1990]
Hi, I'm developing visualization website using vis.js library (network module). I want to show tooltip using qTip2 when user hover over node but it does not work. Here is my code:

network.on("hoverNode", function(params){
        $(this).qtip({
          content: 'I position myself at the current mouse position',
          position: {
            my: 'top left',
            target: 'mouse',
            //viewport: $(window), // Keep it on-screen at all times if possible
            adjust: {
              x: 10,  y: 10
              }
              },
              hide: {
                fixed: true // Helps to prevent the tooltip from hiding ocassionally when tracking!
                }
                });
      });
Anyone can help me?

Thanks.
Huynh.

**Comment by mojoaxel** [comment]
You should look into the native Tooltip (popUp) support: [live Example](http://visjs.org/examples/network/events/interactionEvents.html)

**Comment by mojoaxel** [comment]
But you also could use qTip2. Here is a working example: [jsbin](http://jsbin.com/foziyaf/edit?js,output)

**Comment by mojoaxel** [comment]
By the way: I really would like to see this type of questions on [stackoverflow](http://stackoverflow.com/questions/tagged/vis.js) and not here ;-)

**Comment by NV-FIL** [comment]
Thanks @mojoaxel .
I can't use native tooltip because i use hierarchical layout and change data in tooltip dynamically. 
In your qTip2 example I can't see tooltip appears :). By the way, now I use [OpenTip ](http://www.opentip.org/)and it works perfectly.

**Comment by mojoaxel** [comment]
@NV-FIL Here is the working example: http://jsbin.com/foziyaf/3/edit?js,output

If you want you could provide a minimal working example with OpenTip for others interested.

I think we can close this issue now :-)

**Comment by ztabassum** [comment]
Hi,
So the tooltip when you hover by the right hand corner of the container will cause the tootltip to reappear there when you use qtip2. Is there any fix to that? Your working example also seems to have this issue.
