### ISSUE TITLE
Showcase project proposal: PT Anywhere

### ISSUE THREAD

**Issue by gomezgoiri** [almende/vis#1992]
New project which you could include in your showcase: http://pt-anywhere.kmi.open.ac.uk/

**Comment by mojoaxel** [comment]
Thanks!
Here is the app: http://forge.kmi.open.ac.uk/pt/app/default.html

**Comment by macleodbroad-wf** [comment]
I am redirected to http://forge.kmi.open.ac.uk/pt/app/default.html#/session-error using Chrome.

**Comment by wimrijnders** [comment]
Confirmed. I get the following message:

> Unavailable PT instances
Sorry, there are no Packet Tracer instances available right now to initiate a session.
Please, wait a little bit and try again.

@gomezgoiri Could you help us to get a demo link for the showcase.....even if the issue is one year old? 😞

**Comment by mojoaxel** [comment]
@gomezgoiri It looks like the app is not functional anymore. Please create a pull request to the gh-pages branch if you still want this in the showcases. Thanks.
