### ISSUE TITLE
Network Graph

### ISSUE THREAD

**Issue by Divyanshu07** [almende/vis#2001]
I am trying to create a view of connections. There would be some source nodes and desitnation node and some middleware nodes in between. The graph works perfectly when I create 1000 connections. I am looking to create about 100-200K connnections. Is there some tweak I can use to visualize those connections? Also, Is there a way I can cluster before rendering and then open the cluster based on zoom position? Can Vis.js handle that many nodes and edges?

**Comment by tbaltrushaitis** [comment]
Hi, Divyanshu07!

You should better look into [examples page](http://visjs.org/network_examples.html) to find answers for your questions.
There are [showcase within tons of nodes and connections](http://visjs.org/examples/network/exampleApplications/worldCupPerformance.html) and [clustering by zoom](http://visjs.org/examples/network/other/clusteringByZoom.html) example can be found.

Hope this helps!
--Tom
