### ISSUE TITLE
vis.js setOptions to change color of network node

### ISSUE THREAD

**Issue by AnadiTaylor** [almende/vis#2004]
Hi all,
I am using vis.js to display network nodes. I am parsing the node data from JSON and storing it in an array:

$.each(jsonObj, function(i, val) {  
		var itemId 		= val.id;
		var itemGroup 	= val.group;
		var itemLabel 	= val.label;
		var itemLevel	= val.level;
		var itemData 	= val.nodeData;
		var itemX 		= val.x;
		var itemY 		= val.y;
		var nodeData 	= JSON.parse(val.nodeData);
nodes[nodeCnt] = { id: itemId, group: itemGroup, label: itemLabel, level: itemLevel, title: itemData, x: itemX, y: itemY, font: { color: colour }, color: { border: colour }};
		nodeCnt++;
}

This works perfectly and I can display my network:

var data = {
		nodes: nodes,
		edges: edges
	};
var options = { ... }
network = new vis.Network( container, data, options );

I use an event handler to take action when a node is clicked; I parse the ID of the clicked node (this is the shorthand version):

network.on("click", function (params) {
 		// parse node id
		var nodeID = params['nodes']['0'];
}

I would like to update the color of the clicked node; I have tried various variation including the following to no avail:

var options = {
	nodes:{
		id: nodeID,
		borderWidth: 20,
		color: {
			border: '#000000',
			background: '#000000',
			border:  '#000000',
			highlight: {
				border: '#2B7CE9',
				background: '#D2E5FF'
			}
		}
	}
}
network.setOptions(options);

I have been round and round trying different ways of doing this. If I remove the "id: nodeID," parameter from the above options I would expect all the nodes to be updated, however none are.

I am using standard id's for my nodes: 595191aa-98c6-4a4b-a0e0-4262df83e0de

Any ideas?

Thank you in advance.

**Comment by brichbe** [comment]
See my answer on [SO](http://stackoverflow.com/questions/38768598/vis-js-setoptions-to-change-color-on-network-node)

**Comment by mojoaxel** [comment]
Thanks @brichbe! Closing this here.
