### ISSUE TITLE
Graphics2d don't take a data null

### ISSUE THREAD

**Issue by marcelote** [almende/vis#2006]
Hello I have this problem, when I use graphics2d and have a value null the vis,js take null like 0. Do you have any configuration to change this?.

![graphic](https://cloud.githubusercontent.com/assets/6392534/17510452/4333f466-5e1f-11e6-80ad-8450ed76db7c.jpg)

[json.txt](https://github.com/almende/vis/files/408553/json.txt)

many thank in advances

**Comment by mojoaxel** [comment]
I think the easiest way is to clean up your data before rendering. 
You could use `filter` for that:
```javascript 
data = data.filter(function(item) {
    return value.y.length
});
```

**Comment by marcelote** [comment]
Thanks Alexander I 'll try an i come back to you.

Marcelo Masri

**Comment by marcelote** [comment]
Thanks Alexander works fine

Marcelo Masri
