### ISSUE TITLE
how to define lable's click event

### ISSUE THREAD

**Issue by jianxia612** [almende/vis#2010]
how to network's lable click event

**Comment by mojoaxel** [comment]
With the [`click`event](http://visjs.org/docs/network/#Events) you get all nodes, that have been clicked. [Here](http://visjs.org/examples/network/events/interactionEvents.html) is an example.

**Comment by jianxia612** [comment]
I want use image‘s style node，lable below image node down！

**Comment by mojoaxel** [comment]
http://visjs.org/examples/network/nodeStyles/images.html

**Comment by jianxia612** [comment]
I want bind lable  click event ,this lable is below image node down,label's event,but network only node click!
