### ISSUE TITLE
Timeline: weekday marks in other zoomlevel

### ISSUE THREAD

**Issue by mokraemer** [almende/vis#2014]
Currently the css-classes for weekends is not available if the timeline is zoomed e.g. to one month. At least if the the classes are evaluated as day-14,day-15 the weekday classes should be available too.

**Comment by mokraemer** [comment]
if you change this, the mark for vis-today should be available in lower zoomlevels as well.

**Comment by mojoaxel** [comment]
Fixed with #2016 an 29f2d98d304da64d71ea0f4eb5706cc58098c5a9

**Comment by chungtinhlakho** [comment]
Do we know when the schedule release is for this fix?

**Comment by mojoaxel** [comment]
We are already planing the next release. I can not give a date yet. But you can simply build your own version at any time.
