### ISSUE TITLE
Timeline: dataserialization bug

### ISSUE THREAD

**Issue by mokraemer** [almende/vis#2015]
The timeline seems to have an issue where the timezone is not utc. See
[http://visjs.org/examples/timeline/dataHandling/dataSerialization.html]
If you save the current values to the textarea and load the data back, each entry is moved (here 2 hours in time).

My solution is to change it to utc, but the option "showCurrentTime" does honor the option  "moment: function(date) {
    return vis.moment(date).utc();
  }"

**Comment by mojoaxel** [comment]
I can confirm this. We should have a look and fix this.

**Comment by yotamberk** [comment]
@mojoaxel I don't see an easy way to solve this... The only workaround I see that works is applying`vis.moment(data.start)' and `vis.moment(data.end)` over all the data every time you load the data... 
I really don't see a legit way to do it except for saving any date object in the dataset as a `moment` date, which requires some breaking changes...

**Comment by mokraemer** [comment]
but don't you agree it is a need for the entire applet that loading a stored dataset gives you the same data as before? It is not quite common all computers use utc time ;-)

The question on breaking changes is - what does it break and who is affected.

**Comment by mojoaxel** [comment]
I can not longer reproduce this issue with the current develop version.
I have provided some improvements for this issue with #2244 but I think we can mark it as fixed :tada:
