### ISSUE TITLE
Network: How to save new positions for each nodes after draging

### ISSUE THREAD

**Issue by JamieZhang2016** [almende/vis#2017]
I'm new to vis, hope someone can help me on my question.

In my codes for drawing the network chart: var network = new vis.Network(container, data, options);
each time re-open the network chart, the nodes positions are randomly set, which is fine for me. (I didn't set fixed for individual node)

But sometimes my user want to re-position the nodes by draging, then how can I save the adjusted position for all nodes? Then after refresh or re-open the page/chart, they can see the nodes in the saved positions.

Thanks.

**Comment by dragonzone** [comment]
Once the dragging event stops, you can do this:

```
_.forEach(nodes, function(item) {
	var positions = network.getPositions(item.id);
	item.positionX = positions[item.id].x;
	item.positionY = positions[item.id].y;
});
```

**Comment by JamieZhang2016** [comment]
Thanks dragonzone, I think I get the idea how to get nodes X and Y. I will save the value in somewhere.

Can you please also advise me how to set x and y when build the nodes? I tired to find some sample codes but I could not. Thanks.

**Comment by dragonzone** [comment]
Here is an example you can check out: https://jsfiddle.net/tsee1ap0/1/

Note: all this information you can get from the documentation here: http://visjs.org/docs/network/

**Comment by Stexxen** [comment]
Another example is here - http://visjs.org/examples/network/exampleApplications/nodeLegend.html

but bear in mind this issue - #1857 which is fixed in the develop branch.

**Comment by JamieZhang2016** [comment]
Thanks dragonzone & Stexxen, very good examples. I will try to finish my assignments.

**Comment by mojoaxel** [comment]
I think we can close this.
@JamieZhang2026 Feel free to reopen if you have more questions regarding saving the position of the nodes.

**Comment by SubashRamaiah** [comment]
Hello Everyone, I'm new to Vis js.  

Is it possible to get dragged nodes only?? If yes can you please share the code.
