### ISSUE TITLE
vis.moment

### ISSUE THREAD

**Issue by mistic100** [almende/vis#202]
Hello

I saw nowhere in the doc something indicating that moment.js is already integrated in "vis" namespace

perhaps this could be done in the Components list http://visjs.org/docs/index.html
## 

also my though is that moment.js should NOT be integrated in the package, but only defined as a required dependency

Personally I'm developping a app where a common minified file containing jQuery + AngularJS + MomentJS is loaded on every page, and another minified file contains librairies only used on this page. So on the page with Vis, I have an overload of 26KB

A good pattern I saw on other librairies is to release two versions: "light" and "standalone"

**Comment by mojoaxel** [comment]
see also #1602
