### ISSUE TITLE
Cannot remove edges

### ISSUE THREAD

**Issue by ProgVal** [almende/vis#2021]
I have the following code:

```html
<html>
    <head>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vis/4.16.1/vis.min.js"></script>
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/vis/4.16.1/vis.min.css" />
        <script type="text/javascript">
            function main() {
                graph = {
                    nodes: new vis.DataSet([{"id": "foo"}, {"id": "bar"}]),
                    edges: new vis.DataSet(),
                };
                var options = {};
                network = new vis.Network(
                        document.getElementById("graph-editor"),
                        graph,
                        options);
                graph.edges.add({"from": "foo", "to": "bar"});
                graph.edges.remove({"from": "foo", "to": "bar"});
            }
        </script>
    </head>
    <body onload="main();">
        <div id="graph-editor">
        </div>
    </body>
</html>
```

I expected it to display two nodes with no edges, but there is an edge between the two nodes.

**Comment by mojoaxel** [comment]
The `remove` function needs one or multiple ids, not an object. 

You can add remove items items this:
```js
var id = graph.edges.add({"from": "foo", "to": "bar"});
graph.edges.remove(id);
```

Here are the [DataSet docs](http://visjs.org/docs/data/dataset.html).
Here is the [working example](http://jsbin.com/defaqu/1/edit?html,console,output) on jsbin.

**Comment by ProgVal** [comment]
Wouldn't it make sense for `remove` to raise an exception, then?

**Comment by mojoaxel** [comment]
Good idea to handle errors better. I looked into it. The following parameters would be allowed:

```js
graph.edges.remove(id); //Number
graph.edges.remove([id]); //Array (of ids)
graph.edges.remove(""+id); //String
```
and even:

```js
graph.edges.remove({
    id: id 
}); //Object (with id)
```

So what to check for?
You could have a look [in the code](/almende/vis/blob/master/lib/DataSet.js#L701) yourself. We are always open for pull requests with improvements!

**Comment by ProgVal** [comment]
Just throwing an exception in an else clause of `if (this._data[id])` and `if (itemId !== undefined && this._data[itemId])`

**Comment by mojoaxel** [comment]
There is already a kind of error handler: The `remove` function returns the id of the removed id(s). If the ids could not be found the function returns `null` instead. If error handling is needed here it should be done in the application:

```js
if (!graph.edges.remove(id)) {
  console.warn("The node with id "+ id + " could not be found and removed!");
}
```
