### ISSUE TITLE
Timeline custome hour range for a day

### ISSUE THREAD

**Issue by wlumetsberger** [almende/vis#2022]
We need a functionality, that one day only shows a custom set of hours. 
It means, that e.g. Monday only has hours 8:00 - 16:00 and after 16:00 next day is shown.

**Comment by mojoaxel** [comment]
Checkout parameter `hiddenDates` in [the timeline docs](http://visjs.org/docs/timeline/). 
@wlumetsberger Is this what you are looking for?

**Comment by wlumetsberger** [comment]
Hi, yes thanks. 
Using this parameter offers another question. 
When I'am using the normal view, the days are seperated with a vertical line, but when i'am using the parameter this line isn't available any longer. See the pictures attached.
![with_parameter](https://cloud.githubusercontent.com/assets/12108914/17728148/1bae884e-645e-11e6-8b37-08595d596dfa.jpg)

![normal](https://cloud.githubusercontent.com/assets/12108914/17728142/115a805a-645e-11e6-81da-5247933c1584.jpg)

**Comment by mojoaxel** [comment]
@wlumetsberger It looks to me like you added the "gray" overlay. This is covering the grid. Its as simple like that. You could use [backgroundAreas](http://visjs.org/examples/timeline/items/backgroundAreas.html) instead.

**Comment by wlumetsberger** [comment]
Thanks for the hint, but it's not in the gray overlayed section. I meant the section on top and footer of the component. As you can see in the first screen the days are shown correct and with a seperator, but in the second the days are not shown.

**Comment by mojoaxel** [comment]
Ah! I see. The day seperator gets hidden together with hour 00:00. That should not be the case. Let's just call it a bug. I created #2024 for that.

I'll try to look into this in the next days but It may be quite complicated...So don't expect a quick fix.

**Comment by wlumetsberger** [comment]
Fine thanks a lot :+1:
