### ISSUE TITLE
Timeline: day-ticks are hidden also if hour 00:00 gets hidden

### ISSUE THREAD

**Issue by mojoaxel** [almende/vis#2024]
If you use `hiddenDates` to hide the hour 00:00, the day-ticks are not shown anymore:

![normal](https://cloud.githubusercontent.com/assets/12108914/17728142/115a805a-645e-11e6-81da-5247933c1584.jpg)

**Comment by mojoaxel** [comment]
Thanks to @wlumetsberger for finding this bug!

**Comment by mojoaxel** [comment]
The current behavior can be seen in the [hidingPeriods example](http://visjs.org/examples/timeline/other/hidingPeriods.html).

**Comment by wlumetsberger** [comment]
@mojoaxel , may its caused by TimeAxis.js 
` var showMinorGrid = (width >= prevWidth * 0.4); // prevent displaying of the 31th of the month on a scale of 5 days` ?

**Comment by yotamberk** [comment]
Doesn't happen anymore in the `develop` branch =)

**Comment by mojoaxel** [comment]
@yotamberk Yes! I have no idea why, but this is fixed :+1:
