### ISSUE TITLE
Timeline: Setting default start end

### ISSUE THREAD

**Issue by cambrennan** [almende/vis#2025]
We have potentially hundreds of data points for our timeline and we'd like to be able to set default start and end values for the timeline, to control the users initial view. 

Ideally, we'd like to set the end date to the date of the last item on the timeline and the start date to (end date - 1 month).

Any thoughts on how to pull this off?

**Comment by brichbe** [comment]
There may be a different/better way for you depending on how you're adding your item data to your DataSet, but the basic solution is simple:  before constructing the timeline itself, you could simply iterate all items of the DataSet, keep track of the time of your earliest item and the time of your latest item, then use those values to set the timeline's `start` and `end` bounds (adding/subtracting a month or whatever delta you want).

**Comment by cambrennan** [comment]
@brichbe thanks for the response. We'll look into that solution.

**Comment by mojoaxel** [comment]
@brichbe Please reopen if ihis is still an issue.
