### ISSUE TITLE
Auto-detect "Right To Left" support

### ISSUE THREAD

**Issue by ZvikaZ** [almende/vis#2027]
Hi.

Currently, if the html doc is an RTL (`<html dir="rtl">`), the timeline isn't rendered 100% correctly - at first glance it looks OK, but as it's zoomed out, the dates are displayed on wrong place.

If it's possible, it'd be great to have the timeline rendered from right to left (to support Hebrew and Arabic) according to `dir` attribute - i.e., the earliest date on the right and later dates go to the left.

Thanks

**Comment by ZvikaZ** [comment]
Well, it appears that there **is** RTL support, but it's just not documented...
Found it in examples section [http://visjs.org/examples/timeline/other/rtl.html](url).
But it should be properly documented with all other options.

Furthermore, please consider making the RTL option automatic - derived of the HTML's `dir`

**Comment by yotamberk** [comment]
Hey @ZvikaZ, I'm not sure the rtl should be derived automatically from the HTML's `dir`.
You might want a left-to-right timeline in a rtl website. Furthermore, I don't think it's fair to enforce rtl with an external attribute. 
I did add an appropriate documentation for the `rtl` option. I hope this satisfies users.

**Comment by ZvikaZ** [comment]
Please read again my original post.
By default, when the timeline is inside an RTL element, it's not rendered as a regular LTR timeline - it's rendered with mistakes...

In the current situation, if the user has an RTL document, and he wants an LTR timeline, he has to wrap it in an LTR div, and don't give the timeline any parameters.
If he wants it to be an RTL timeline, he should give it the correct configuration.
This is cumbersome...

I assume that fixing the initial problem is too complicated, and not every important.

The easiest solution (in my opinion...) is too derive the configuration from the wrapping element.
Anyway, if the user wants an LTR timeline in a RTL doc, he should wrap it in a special LTR DIV .

**Comment by yotamberk** [comment]
Ok i see what you mean.
It can be done.
Do you want to submit a PR or do you want me to take a shot at it?

בתאריך 11 באוק׳ 2016 8:21 לפנה״צ,‏ "Zvika" <notifications@github.com> כתב:

**Comment by ZvikaZ** [comment]
Well, if you can do it it'd be great.
Thanks!

בתאריך 11 באוק׳ 2016 09:20,‏ "yotamberk" <notifications@github.com> כתב:

**Comment by yotamberk** [comment]
I'll give it a go during the holidays. Chag Sameah! ;)

בתאריך 11 באוק׳ 2016 9:22 לפנה״צ,‏ "Zvika" <notifications@github.com> כתב:

**Comment by mojoaxel** [comment]
closed with #2141

**Comment by mojoaxel** [comment]
There is still the issue that `<html dir="rtl">` is ignored. 
@yotamberk Should we do something about this?

**Comment by yotamberk** [comment]
Umm it can be easily done. I'm just still not sure what I think about it. I think it should be done instead of the options but I don't know how to document the support of this.

**Comment by mojoaxel** [comment]
> I think it should be done instead of the options but I don't know how to document the support of this.

I think the "rtl" option should have the default value "auto". If it is set to "auto" we try to guess if the user uses "rtl" e.g. by looking for `dir="rtl"` in the html- or the root-tag, of maybe even by the browser settings.
If the user forces `rtl: false` we disable it and if it is set to `rtl: true` we enable it.

see also 
* https://www.w3.org/TR/html5/dom.html#dom-dir
* https://github.com/shadiabuhilal/rtl-detect

**Comment by mojoaxel** [comment]
Here is wat [the specs](https://www.w3.org/TR/html5/dom.html#dom-dir) say:

> The directionality of the element is the same as the element's parent element's directionality.

I think we have to check every parent element of the timeline for a direction tag.

**Comment by yotamberk** [comment]
The merge request I've add does this. It checks takes the nearest parent's `dir` and uses it (unless specified explicitly in `options.rtl`)

**Comment by mojoaxel** [comment]
> The merge request I've add does this. It checks takes the nearest parent's dir and uses it (unless specified explicitly in options.rtl)

Yes, but it the root element has no direction we have to check its parent elements up to the dom-root. Usually the direction is set in the document's root element the "<html>" tag. See [comment](https://github.com/almende/vis/pull/2235/files#r85286712).

**Comment by yotamberk** [comment]
Finally can be closed with #2237
