### ISSUE TITLE
How to use locale correctly in timeline?

### ISSUE THREAD

**Issue by steffchep** [almende/vis#2029]
How can I get the date format to comply with the locale I chose? 
- I've included moment-with-locales*
- I set "nl" as the locale in my options. I know I must have set it in the right place, because setting anything except "nl" or "en" will cause a script error.
- date is formatted for English :(
- the same happens when I try to add "de" - as per the #Localization part of the timeline Docs
- I do not get any Javascipt errors
- I also tried changing the browser language. Nope.

*I am using requirejs to load both moment and vis - how can I make sure that vis is NOT using its internal moment version because of timing/load issues?

_edit_ it works when I do it without require; so I suspect it has to do with the untimely loading of the moment-with-locales library

**Comment by mojoaxel** [comment]
@steffchep Please see http://visjs.org/examples/timeline/other/localization.html.
If you have further problem with your locale, feel free to reopen this issue.

**Comment by steffchep** [comment]
As I said, without requirejs, as in the example it works okay, so that did not really solve my problem.

The load order when using require is not always fixed, and it can happen that moment-with-locales is loaded too late if you just use the define([array of dependencies], function().... )

By now I do have an idea how to solve it, but it never hurts to be aware of this issue!

**Comment by mojoaxel** [comment]
> The load order when using require is not always fixed

You can define dependencies in require.js using the [shim config](http://requirejs.org/docs/api.html#config-shim).
Another way would be to generate a [custom vis.js](/almende/vis#custom-builds) without moment.js.

**Comment by steffchep** [comment]
Will play around with that, thanks!
