### ISSUE TITLE
Network: How to Select Multiple Nodes in JS function AFTER Network build

### ISSUE THREAD

**Issue by JamieZhang2016** [almende/vis#2031]
AFTER Network build, I'd like to find a solution in my js function , to select multiple nodes. For now I can select one node in my codes, as below:
MyJSFunction = function () {
                    //set selected Nodes
                    try {
                        _network.selectNodes([testNodeId]);
                    }
                    catch (err) {
                        //alert(err);
                        _network.unselectAll();
                    }
                }
            };

Please help, if there is sample codes should be great!

**Comment by tbaltrushaitis** [comment]
Hi!
Follow your code, here is the solution:

```
MyJSFunction = function () {
//set selected Nodes
try {
_network.selectNodes([testNodeId1, testNodeId2, testNodeId3, testNodeId100]);
} catch (err) {
//alert(err);
_network.unselectAll();
}
}
};
```

Hope this helps!

**Comment by mojoaxel** [comment]
Thanks @tbaltrushaitis !

@JamieZhang2016 Can you please close this issue, if your question is answered. Thanks.

**Comment by JamieZhang2016** [comment]
Thanks @tbaltrushaitis ! I will close the issue.
