### ISSUE TITLE
Graph3d - possible to pan/drag?

### ISSUE THREAD

**Issue by chat2joe** [almende/vis#2036]
I am interested in using the Graph3d as it renders much nicer than other 3D graphs I've found. A feature we need though is to be able to pan around the 3D chart as well as rotate. Plotly.js do this by dragging with the right mouse button.

Can this be achieved with vis.js?
I am asking as the docs seem to suggest it might be but I can't manage to configure it. "You can freely move and zoom in the graph by dragging and scrolling in the window" - does this only relate to rotating the 3d graph?

**Comment by mojoaxel** [comment]
At the moment it's only possible to rotate the camera around the chart and zoom.

Moving the chart like you descripted it is not yet implemented. @linuxnotes did some nice work in this direction in #2007, but its not jet production ready. You find his implementation in the [branch 3d-camera-orientation](/almende/vis/tree/3d-camera-orientation).

Feel free to provide improvements!

**Comment by jaredvacanti** [comment]
What adjustments need to be made for any of the 3D examples to pan when zoomed? Currently none of the examples pan for me.

**Comment by wimrijnders** [comment]
None whatsoever. The stable release of `Graph3d` supports this since `v4.18`.

You should be able to pan at any zoom level with control-drag. I just tested this, it's working (chromium and firefox on linux). If it really doesn't work for you, provide some platform details if possible.
