### ISSUE TITLE
need org chart example with vertical and horizontal connectors

### ISSUE THREAD

**Issue by smart987** [almende/vis#2038]
Hi, is it possible to build a tree structure as shown in the figure. I searched through all network examples but I did not come across any such tree structure. Could you please provide an example of this type whic have horizontal and vertical connections between the nodes? ![org](https://cloud.githubusercontent.com/assets/11309381/17887148/bda794fe-6942-11e6-9fa3-e1d61cf535cc.png)

**Comment by mojoaxel** [comment]
Edges with these kind of horizontal/vertical orientation is not possible at the moment. The closest thing would be something like this:

![image](https://cloud.githubusercontent.com/assets/600565/17968510/8e01a686-6acd-11e6-94a5-01d510be0c2a.png)

[Here is the code](http://jsbin.com/meriti/2/edit?html,output).

**Comment by smart987** [comment]
Thanks Mojoaxel for the solution and for this great library. For now this solution would be fine for me.  Another small feature I need here is, when I click any child the path to it is top most parent needs to be highlighted, Is it possible? For example, if I click, Grand Grand Child 1 (assume that left most Grand Grand Child in the figure as Grand Grand Child1), then Grand Grand Child 1 -> Grand Child 2 (assume that the middle Grand Child in the figure as Grand Child2) -> Child2 (assume right most child in the figure as Child2) -> Parent. 

i.e., Clicking Grand Grand Child 1, should highlight :    Grand Grand Child 1 -> Grand Child 2  -> Child2-> Parent

clicking Grand Grand Child 2, should highlight :    Grand Grand Child 2 -> Grand Child 2  -> Child2-> Parent

Both paths (i.e. connecting lines)  and nodes should be highlighted. Is it possible?

Do you have any plan to support vertical and horizontal connectors in future. If you can support this that would be great. For this chart I have gone through many libraries but in every library I have faced some difficulties or others. Supporting this Vertical and Horizontal lines makes this library unique in the area of charts.

**Comment by mojoaxel** [comment]
> Another small feature I need here is, when I click any child the path to it is top most parent needs to be highlighted, Is it possible?

You must implement this yourself. You could listen to the `selectNode` [event](http://visjs.org/docs/network/#Events). And than go through all edges and select the ones you want to be selected.

> Do you have any plan to support vertical and horizontal connectors in future.

As far as I not this is not planed. But feel free to create a new feature-request issue for that. That really would be a nice new edge type!

**Comment by mojoaxel** [comment]
also on [stackoverflow](http://stackoverflow.com/questions/39096205/family-chart-with-horizontal-and-vertical-line-connectors-using-vis-js)
