### ISSUE TITLE
Modify edges path on a network

### ISSUE THREAD

**Issue by capitanjacksparrow** [almende/vis#2040]
Would it be possible (or is it already possible) to modify the edges path on a network in vis.js? In other words, I was wondering if I could chose the path through which an edge moves from one node to the other.

Kind regards,

Lucia

**Comment by mojoaxel** [comment]
There are multiple ways to influence the drawing of the edges. [Here is an example](http://visjs.org/examples/network/edgeStyles/smoothWorldCup.html).

If you want any other ways of drawing edges you relativ easily could create your own Edge implementation. [Here](/almende/vis/tree/develop/lib/network/modules/components/edges) is a good point to start.

**Comment by capitanjacksparrow** [comment]
Thank you very much for great hints!
Best wishes,
Lucia
