### ISSUE TITLE
Subgroup background item overlap

### ISSUE THREAD

**Issue by tuckwat** [almende/vis#2043]
I've encountered a few bugs while trying to create subgroup labels using a background item (may be related).

The first bug occurs when a group collapses (top group if orientation:top), the background items of any subgroups can overlap.  Pan to the left or right (so that no items are visible) to reproduce:

http://jsbin.com/buqeqorahe/1/edit?html,output

The next bug occurs when orientation is bottom and there are multiple subgroups in the bottom group - notice that the background items are misaligned in the bottom group - additionally panning will cause overlap:

http://jsbin.com/meyacivige/1/edit?html,output

**Comment by mojoaxel** [comment]
@tuckwat Thanks for reporting this! Looks like subgroups are not well tester, yet.

**Comment by yotamberk** [comment]
solved with #2519
