### ISSUE TITLE
Timeline subgroup item selection forces overlap of unstacked items

### ISSUE THREAD

**Issue by binloan** [almende/vis#2044]
I've facing this bug in the current version of the vis timeline chart. I have multiple items intentionally overlapping another item. However they are shorter than the overlapped item but need to be selectable. Once I select an item it comes to foreground and thus overlaps the enclosed smaller item. Example:

[http://jsbin.com/fapafamiwo/edit?html,output](http://jsbin.com/fapafamiwo/edit?html,output)

It should be possible to prevent vis to bring an element to foreground even if it's selected. Otherwise it will be really hard for a user to encounter that he has to click to empty space to revert the selection.

**Comment by mojoaxel** [comment]
This could be done by setting:
```css
.vis-item.vis-selected {
    z-index: 0;
}
```
http://jsbin.com/yufupo/1/edit?html,css,output

**Comment by binloan** [comment]
Very nice. Thanks for pointing this out.
