### ISSUE TITLE
How to get the "seed" of the network after moving nodes around?

### ISSUE THREAD

**Issue by pallaviranadek** [almende/vis#2046]
Hi,

I am trying to get to a network layout that I like and that is the same everytime the page is reloaded.  How does one get the "seed" of the network after moving nodes around?

Thanks,
~Pallavi.

**Comment by dragonzone** [comment]
Instead of getting the seed, you want to save the X & Y coordinate of the nodes. This is probably what you are looking for: https://github.com/almende/vis/issues/2017

**Comment by mojoaxel** [comment]
You could try `getSeed()` like [explained in the docs](http://visjs.org/docs/network/layout.html?keywords=getSeed). Let us know if it works!

**Comment by mojoaxel** [comment]
duplicate of #2017
