### ISSUE TITLE
Layout of non-hierarchical networks

### ISSUE THREAD

**Issue by pallaviranadek** [almende/vis#2047]
For non-hierarchical networks, is there a way to lay out a groups of nodes from to bottom in a weighted fashion?

Thanks.

**Comment by mojoaxel** [comment]
@pallaviranadek Could you maybe provide an example or even a drawing of want you want to adjive? Thanks.

**Comment by pallaviranadek** [comment]
Sure @mojoaxel.  The documentation for "Network - layout" suggests "Ideally you try with an undefined seed, reload until you are happy with the layout and use the getSeed() method to ascertain the seed."  But when nodes are added on the fly or there are too many nodes where having to do numerous "reloads" is not practical, **it would be very useful to be able to give certain nodes "weights" where they rise to the top**. So we can achieve an "ordered" look from top to bottom.  Below is an example of a random layout and its equivalent ordered layout.
![randomlayout](https://cloud.githubusercontent.com/assets/15141933/18054518/76eb32b8-6dc1-11e6-8451-120dd0a0e7a3.jpg)
![orderednodes](https://cloud.githubusercontent.com/assets/15141933/18054517/76e8d72a-6dc1-11e6-91d5-9cd5d70eb77c.jpg)

**Comment by mojoaxel** [comment]
I know no way achieving this. There is no concept of up or down in a network chart only layouts.

What you could do is provide fixed x/y coordinates for each node. This way you could implement your own positioning algorithm.

I'm closing this question for now. Feel free to just ask if you need further help.
