### ISSUE TITLE
visjs or chaps?

### ISSUE THREAD

**Issue by ghost** [almende/vis#205]
Hello,

Just a quick question, visjs is based on chaps, I was just wondering what the future holds for both? if I was going to use one, I would assume visjs is the most active, is there any reason why I should use the chaps version over visjs?

Thanks!

**Comment by bsideup** [comment]
We compared Chaps with Vis and discovered that Chap works much faster and nicer:
[1] http://almende.github.io/chap-links-library/js/timeline/examples/example16_performance_grouping.html?count=1000
[2] http://visjs.org/examples/timeline/other/groupsPerformance.html?count=1000


Any idea why? :) Maybe we can tune visjs to make it more like chaps in this ( [1] ) demo?

**Comment by josdejong** [comment]
It's probably mainly because the chap-links-library example you link to applies clustering, which isn't (yet) implemented in the Timeline of vis.js. Setting `clustering: false` in the chap-links-library should give a more fair comparison and they should have comparable performance.

**Comment by bsideup** [comment]
@josdejong ah, ok :) Any ETA of clustering for timeline then?

**Comment by josdejong** [comment]
It's not high on our own internal priority list, but anyone can pick it up. If you're interested to contribute yourself, we can open an issue to discuss on how to implement it exactly.

**Comment by jbraun27** [comment]
I remember that clustering was a very elegant way to handle large data sets, and did help performance significantly. I hope someone has the time to pick this up and run with it.
