### ISSUE TITLE
Bug with arrow in network

### ISSUE THREAD

**Issue by mazzafuccka** [almende/vis#2054]
When using hierarchial directed layout and arrows for edges and having only two connected nodes - having this bug
http://screencast.com/t/iwf1MT4MmBJN

**Comment by mazzafuccka** [comment]
I've noticed that it happens when arrows are rendered strictly vertical

**Comment by mazzafuccka** [comment]
or strictly horizontal

**Comment by mojoaxel** [comment]
@mazzafuccka Thanks for reporting this. Could you maybe create a very minimal example code to clarify the described issue. This would be a big help in reproducing (and fixing) it.

**Comment by mazzafuccka** [comment]
Hey, I've found reason - I've passed string "1" to borderWidth property - that caused the problem. The only thing you can fix - is to add parseInt() to the input if this property. However, borderWidthSelected parses strings ok)

**Comment by mojoaxel** [comment]
Thanks for finding that! I'll keep the issue open until I've fixed that.

**Comment by mojoaxel** [comment]
The [docs](http://visjs.org/docs/network/nodes.html?keywords=borderWidth) state that `borderWidth` has to be a number. I say we are good for now. Maybe we need better type-checks for the parameters but that is something for another issue...
