### ISSUE TITLE
[Timeline] How can I make the group height smaller?

### ISSUE THREAD

**Issue by mengyaow** [almende/vis#2056]
![height](https://cloud.githubusercontent.com/assets/3876784/18117741/58b98b1e-6f83-11e6-9d67-8fd0322d3ee9.png)

How an I make the gap smaller? 
It looks like the group height are computed on the flight

**Comment by mojoaxel** [comment]
You can decrease the margin between items by setting the `margin` option:
```js
margin: {
  item: 2
}
```

Also you could remove the items top/button-margin via css:
```css
.vis-item .vis-item-content {
  padding: 0px 5px;
}
```

[Here](http://jsbin.com/monihe/1/edit?html,output) is an example based on [the basic group example](http://visjs.org/examples/timeline/groups/groupsOrdering.html):

![image](https://cloud.githubusercontent.com/assets/600565/18122438/d6f0ed70-6f69-11e6-852f-e287934bd0ff.png)

**Comment by mojoaxel** [comment]
By the way: I really would like to see this kind of questions on [stackoverflow](http://stackoverflow.com/tags/vis.js)!
