### ISSUE TITLE
Network: performance issue with large number of Nodes and Edges

### ISSUE THREAD

**Issue by JamieZhang2016** [almende/vis#2061]
I build a network chart in my web page using VIS, which has 86 Nodes and 2051 Edges. When I try to drag some nodes, it's really slow. Does anyone can give me some ideas how can we improve the chart performance when has a large number of Nodes or Edges?

ps: Because I cluster some nodes into groups, that's why the number of Nodes < the number of Edges

**Comment by dragonzone** [comment]
We had same issue, you can try to turn on hideEdgesOnDrag option, which will improve greatly. Read here for more detail: http://visjs.org/docs/network/interaction.html

**Comment by JamieZhang2016** [comment]
Thanks dragonzone! I will check the solution
