### ISSUE TITLE
Loading data from database

### ISSUE THREAD

**Issue by Chroedde** [almende/vis#2065]
Hi guys,
I have a problem. I store all the nodes and edges in a MySQL database where the load_network.php gives me all the data in one json. So far, everything works. I do it with:

```
`var nodes = null;
var edges = null;
var network = null;

nodes = new vis.DataSet();
edges = new vis.DataSet();

function get_network_from_database(callback) {
    $.ajax({
        type: "POST",
        url: "load_network.php",
        dataType: "json",
        success: callback,
    }); 
}

get_network_from_database(cb_fktn);

function cb_fktn(data) {
    var data = {
        nodes: data[0].nodes,
        edges: data[0].edges
    };

    function draw() {
    (.......)
    }
draw()
}`
```

As said, so far everything works! Now, within the draw() function I want to notice when some nodes have been changed and want to store them in the database:

```
        `network.on("dragEnd", function (params) {
            var nodes_positions = [];
            for (var i=0;i<data.nodes.length;i++) {
                var node_position = [];
                node_position = [data.nodes[i].id, data.nodes[i].x, data.nodes[i].y];
                nodes_positions.push(node_position);
            }
            nodes_positions = JSON.stringify(nodes_positions);

            $.ajax({
                data: {nodes_positions: nodes_positions},
                type: "post",
                url: "save_positions.php",
                success: function(data){
                    alert("Positions saved: " + data);
                }
            }); 
        });`
```

My problem is now: It doesn't recognize the changed x and y values as it seems to only access the initially loaded data. So it just stores the same positions again even if they are moved in the canvas.

Could you please help me in finding a solution for accessing the new positions?

Thank you very much in advance!

Best regards!

**Comment by Tooa** [comment]
The dataset does not update positions for dragged nodes. So instead, use the nodes provided in the ``params`` parameter of your ``dragEnd`` callback. The parameter provides you with the dragged nodes and the position. See:

```
{
  nodes: [Array of selected nodeIds],
  edges: [Array of selected edgeIds],
  event: [Object] original click event,
  pointer: {
    DOM: {x:pointer_x, y:pointer_y},
    canvas: {x:canvas_x, y:canvas_y}
  }
}
```
 [Source](http://visjs.org/docs/network/)

Best Uli

**Comment by proy87** [comment]
Try to use `network.body.nodes` instead of `data`

**Comment by yotamberk** [comment]
@Chroedde Are the solutions suggested supply your needs? Can we close this issue?
