### ISSUE TITLE
Is there any way to ensure item label is visible?

### ISSUE THREAD

**Issue by roboslone** [almende/vis#2067]
It's about timeline.

Items displayed as points , that are placed at the end of timeline get their labels cut:
![Screenshot](https://api.monosnap.com/rpc/file/download?id=eHrTEL6i219Xfa9nI5AKAIVqQEWWyJ)

And not only points are affected:
![Screenshot-2](https://api.monosnap.com/rpc/file/download?id=ftzUOlUmm8RgnpjA8RSRjf4jWIKUWn)

Is there a way to ensure label is always visible? For instance, it could be printed before items point ( or bar) if it's gonna be cut.

**Comment by yotamberk** [comment]
I'm not sure what you mean. Can you take a picture or simulate how you would like it to act?

**Comment by roboslone** [comment]
I would like labels to be visible at all time. Something like that:
![1](https://cloud.githubusercontent.com/assets/1941275/19518701/2f213e14-9611-11e6-875f-ea6414b9760e.png)

**Comment by yotamberk** [comment]
the simple way to do this is simply adding in your CSS:
```css
.vis-item-overflow {
  overflow: visible!important;
}
```

Try it out and see if that's what you mean. Is this good?

**Comment by mojoaxel** [comment]
> Is there any way to ensure item label is visible?

I don't think there is a way to ensure this. You can make the label left- or right-aligned or centered, but that doesn't ensure that it is visible at all times. For that you would have to automatically scroll and/or zoom. This kind of (strange) behavior is not implemented.

**Comment by yotamberk** [comment]
Oh I see what you mean... I understood wrong what you wanted... Yeah... it's not possible currently for now

**Comment by roboslone** [comment]
Is it possible to implement such feature? I'm not a frontend developer myself, I'm glad to provide any help I can, but it's limited.

I guess aligning labels to left in first half of timeline and to right in the second half would help, but I'm not sure if labels would clench in the middle.

**Comment by mojoaxel** [comment]
No it realy makes no sense to implement this. You could try the following things:
* Reduce the font size
* Break the labels with a `<br>`
* Set the `max` of the timeline to something like "end of last item + 12 hours"

**Comment by roboslone** [comment]
Well, yeah, but it just doesn't seem like a good solution. I guess I would have to use it though. Thanks.
