### ISSUE TITLE
data in editEdge

### ISSUE THREAD

**Issue by Chroedde** [almende/vis#2068]
Hello,
please, could you help me with a little thing? I have the following in the manipulation options:

	`editEdge: function (data, callback) {
		document.getElementById('operationEdge').innerHTML = "Edit Edge";
		document.getElementById('edge-id').value = data.id;
		document.getElementById('edge-label').value = data.label;
		document.getElementById('edge-title').value = data.title;
		document.getElementById('saveEdge').onclick = saveEdgeData.bind(this, data, callback);
		document.getElementById('cancelEdge').onclick = cancelEdgeEdit.bind(this, callback);
		document.getElementById('edgePopup').style.display = 'block';
	}`

My problem is that I want the user also be able to edit the edge label and title. Unfortunately, unlike at editNode, data only consists of id, from and to. No label, no title. Is there a way to get the full edges data at this place?

Thanks a lot in advance.

Best regards!

**Comment by Tooa** [comment]
Hi,

you can use the ``selectEdge`` event that provides you with the id of the selected edge. Then just update the edge in the underlying edge dataset. 

I strongly recommend you to read the [documentation](http://visjs.org/docs/network/). Furthermore, please use [stackoverflow](http://stackoverflow.com/questions/tagged/vis.js) for questions in future. Moreover, close your issues when the answer solves your problem e.g. [here](https://github.com/almende/vis/issues/2065).

Best Uli

**Comment by Chroedde** [comment]
ok, mach ich. :-) Leider funktioniert es mit der selectEdge-Funktion auch nicht. Hier sagt er mir - warum auch immere - "getSelectedEdges is not defined".

**Comment by Tooa** [comment]
Can you provide a JSFiddle of the problem you are facing with ``selectEdge``? It would be also helpful having a JSFiddle for your original problem with the manipulation system. 

I had a look into the [code](https://github.com/almende/vis/blob/10300d90a9c02e981dc640ff4d1723d6a4efaadb/lib/network/modules/ManipulationSystem.js#L1133) and it seems that the ``editEdge`` function does not support a callback with two arguments. It just consumes the [edge data](https://github.com/almende/vis/blob/10300d90a9c02e981dc640ff4d1723d6a4efaadb/lib/network/modules/ManipulationSystem.js#L1117), which looks like:

```
let defaultData = {id: this.edgeBeingEditedId, from: sourceNodeId, to: targetNodeId};
```

Take a look in your javascript console for the error. 

@mojoaxel Should we create a new issue for an enhancement tackling the problem of adding the edge label to the ``defaultData`` parameter? You can alternatively change the label. Looks like it's really just adding the field to the object. What do you think?

Best Uli

**Comment by Chroedde** [comment]
Hi Tooa,

First, thanks for the answer. Yes, it seems that title and label are misssing in this defaultData variable. Would be great if you would add it in a future version.

But for now I seem to be too stupid. Sorry for that. ;-) I give you the parts of my code.

1) New dataset (data comes from a database):
`nodes = new vis.DataSet(data[0].nodes);
edges = new vis.DataSet(data[1].edges);
		
var data = {
	nodes: nodes,
	edges: edges
};`

2) Options -> Manipulation:
`editEdge: function (data, callback) {
	document.getElementById('operationEdge').innerHTML = "Edit Edge";
	document.getElementById('edge-id').value = data.id;
	document.getElementById('edge-label').value = data.label;
	document.getElementById('edge-title').value = data.title;
	document.getElementById('saveEdge').onclick = saveEdgeData.bind(this, data, callback);
	document.getElementById('cancelEdge').onclick = cancelEdgeEdit.bind(this, callback);	
	document.getElementById('edgePopup').style.display = 'block';
},`

Here, data.id is being displayed correctly while data.label and data.title are undefined. I virtually tried everything that came to my mind but I am simply not able to get these two values.

Sorry if you think that you already gave me the answer but everything I tried with it failed. :-(

**Comment by Chroedde** [comment]
BTW, the same is with deleteNode and deleteEdge when you want to make a dialog with the question if one is sure to delete or cancel. -> data.id is accessible, data.title and data.label not. Maybe you could add these to data also to the regarding defaultData variables?

Thank you!! And excuse my maybe stupid questions.

**Comment by sawatsky** [comment]
I most definitely think that this should be a Feature-Request. We can currently get the label information about Nodes in editNode; it makes sense that we should get the label information about Edges in editEdge.

The editEdge event would also need to be fired not just when the edge's links are changed. Sometimes, a user might just want to edit the edges label and shouldn't have to arbitrarily drag the edge's links just to edit the label.

**Comment by mojoaxel** [comment]
@sawatsky Good point! Could you please create a new issue for that. I think this one is already a little too confusing for a clean feature-request :wink: 
Thanks!

**Comment by eymiha** [comment]
It's a simple change. At the beginning of _performEditEdge, include
```
label: ""+this.body.edges[this.edgeBeingEditedId].label
```
in the defaultData. It'll be delivered to the user-supplied editEdge function. I'll make the pull request if folks want me to.
