### ISSUE TITLE
How to store tree state?

### ISSUE THREAD

**Issue by proy87** [almende/vis#2069]
I want to store tree position after dragging.
I'm using the following code (coffeescript):

``` javascript
network.on("dragEnd", ->
      data = {}
      for id, node of network.body.nodes
        data[id] = {
          x: node.x,
          y: node.y
        }
)
```

But when I restore positions, relative node position is preserved, but overall tree tends to be centered.
How to avoid centering?

**Comment by tomzx** [comment]
Hi @proy87,

Are you talking about the camera/view position?

If you look at http://visjs.org/docs/network/#methods, you can use `getScale()`/`getViewPosition()` and `moveTo()` which should allow you to save/restore the camera position.

**Comment by mojoaxel** [comment]
see #2073
