### ISSUE TITLE
Is there any option to display current time of vis-custom-time-bar with attached?

### ISSUE THREAD

**Issue by PalanivelLakshmi** [almende/vis#2070]
User will get the attentation of where the custom time bar is. Please update me if option is already avaliable or let me know any other options.

**Comment by mojoaxel** [comment]
I'm not sure what you mean!? The is a default marker of the current time. Just open e.g. the [basic example](http://visjs.org/examples/timeline/basicUsage.html) and scroll to "today". There is a marker in form of a red line.

You can disable this by setting `showCurrentTime: false` in the options.

**Comment by PalanivelLakshmi** [comment]
I'm asking is there any option to add custom popover message?. Whenever we do mouse over of the customTimeBar, it'll show the time information, the same information I need to show always.

**Comment by mojoaxel** [comment]
@PalanivelLakshmi Sadly I see no way to do that at the moment. We would need a `mousemove` event handler for that and something to get the time of a given x/y position.
