### ISSUE TITLE
Example: save and load the state of network charts

### ISSUE THREAD

**Issue by mojoaxel** [almende/vis#2073]
We get a lot of questions about saving the current position of nodes e.g. to a server and initialize charts with this data. I think a new example would be very helpful!

**Comment by mojoaxel** [comment]
would fix #2069

**Comment by AndrewSpeed** [comment]
Hi, I'm happy to take a look at this, to make sure I understand correctly, you're looking for an example with the ability to import and export the network as JSON?

**Comment by mojoaxel** [comment]
@AndrewSpeed That would be much appreciated!
I'm thinking of a new [network example](/almende/vis/tree/master/examples/network/other) with a simple network, that has a "Save to JSON" button and a "Load from JSON" to demonstrate how x/y positions could be saved and restored.

**Comment by AndrewSpeed** [comment]
No problem, I'll take a look at this later today.

**Comment by mojoaxel** [comment]
fixed with ea859d4c79fed82a426affa2dcc7cf95821e1614
