### ISSUE TITLE
physics Configuration max value of slider

### ISSUE THREAD

**Issue by vshekharjha** [almende/vis#2074]
While customizing the configuration option i found an issues whenever user slide the slider at it max the maximum value increase randomly or with some specific number 
Plz check the link below for reference 

http://visjs.org/examples/network/physics/physicsConfiguration.html

how can i  fix the max value of the slider ?

**Comment by mojoaxel** [comment]
The default configuration is build in a way to increase the range of the value if a very high value is picked (See [here](/almende/vis/blob/0666cb142c1fedaf63580a3cd94cb99f210d4325/lib/shared/Configurator.js#L346)).

The configurator is more for development than for using in production. If you want to make physics settings changeable you should implement your own inputs for the value you want to change.
