### ISSUE TITLE
Prevent the elements from the time axis to be removed based on the current view

### ISSUE THREAD

**Issue by dragos090** [almende/vis#2076]
Hello,

I'm using the vis timeline for a project i'm working on and it's the perfect solution for what i'm trying to achieve. Now i only have one problem:

My timeline is usually one year long or so and the time axis is scaled by month. You can zoom out until you have the whole year in your view and zoom in until you have one month in the view. I want to keep the time axis elements (all the months) in the .vis-time-axis div. So for a timeline from January to December, i want to keep all the class="vis-grid vis-vertical vis-minor vis-{month} vis-{even/odd}" elements inside the div.vis-time-axis. Right now, the time axis is redrawn after every view change and it keeps only the month in the current view.

Is there something i can do to achieve this?

Thank you in advance,
Dragos

**Comment by mojoaxel** [comment]
@dragos090 Is this issue still relevant or can we close it?
