### ISSUE TITLE
network.getPositions

### ISSUE THREAD

**Issue by Chroedde** [almende/vis#2077]
Hi,
with network.getPositions(network.body.nodes.id); I get an json-formatted array like:
```js
{
  "node_id_1": {
    "x": -87,
    "y": 149
  },
  "node_id_2": {
    "x": -24,
    "y": 50
  },
  "node_id_3": {
    "x": 55,
    "y": -32
  }
}
```
It's kind of nasty to get easy access to the x and y values. My question is if it would be possible to change it in a future version of vis so that one gets ist like:
```js
[{
  "id": "node_id_1",
  "x": -87,
  "y": 149
},
{
  "id": "node_id_2",
  "x": -24,
  "y": 50
},
{
  "id": "node_id_3",
  "x": 55,
  "y": -32
}]
```

**Comment by mojoaxel** [comment]
This would be a breaking change. I would prefer to add another function for that.

**Comment by Chroedde** [comment]
Ok, thanks. I did it with a function.

**Comment by mojoaxel** [comment]
I'm closing this, but feel free to reopen and create a pull request for this!
