### ISSUE TITLE
network.getSelectedEdges()

### ISSUE THREAD

**Issue by Chroedde** [almende/vis#2078]
Hi,
is there a way to get the full details of a selected edge, e.g. by using network.getSelectedNodes()? At the moment I only get the id, but not title, no label, etc.
Thanks and best regards!

**Comment by Tooa** [comment]
Why should you use ``network.getSelectedNodes`` to get information about the edge? Here's an [example](http://jsfiddle.net/771fox0o/22/) showing how to get all information about a edge when clicking on it. 

Your question is basically a duplicate of #2068 and I already told you the solution there. Please use Stackoverflow for questions in future and read the documentation!

**Comment by mojoaxel** [comment]
duplicate of #2068
