### ISSUE TITLE
Timeline: degraded performance since 3.12?

### ISSUE THREAD

**Issue by carueda** [almende/vis#2080]
I just upgraded vis from 3.12. (Apr'15) to the latest as of today 4.16.1 (Apr'16) in one of my applications.  The needed adjustments were rather straightforward, basically just by reviewing HISTORY.md and the updated documentation (thanks!). 

The only "major" update I needed to do was to adjust a few vis-related CSS name changes. In particular, **no** changes at all in code (only the updated vis dependency). Although the display of both versions are essentially the same, I do notice some degraded rendering performance while interacting with the mouse/trackpad.

Not sure if the following animated gifs will make the point clear (in both cases using Chrome on a Macbook).  The first one is some repeated zooming in and out on the vis 3.12:

![with-vis-3 12](https://cloud.githubusercontent.com/assets/556505/18371182/38fc8d66-75e7-11e6-9d3c-7c330ff61be7.gif)

In particular, very smooth rendering, no lagging.

And the second gif is the same exercise (approximately at same speed) on the vis 4.16.1 version:

![with-vis-4 16 1](https://cloud.githubusercontent.com/assets/556505/18371241/9f01b492-75e7-11e6-810a-4b650b6c642c.gif)

Lagging is noticeable (although not terrible).

Anyone have noticed something like this?  Any ideas?

I still have to test this on actual timelines in my application that have many more items/groups.

(BTW, I just recently learned that the vis project is undergoing some re-structuring. Best wishes to the vis team to keep the good work.)

**Comment by carueda** [comment]
Ah, in one other test I just noticed this warning in my the console:

![image](https://cloud.githubusercontent.com/assets/556505/18373957/8493d98a-75fd-11e6-9474-0b8452ef318c.png)

Some quick googling points to http://stackoverflow.com/a/39187679/830737 ... Seems like Hammer would have to be updated first ...

**Comment by matikucharski** [comment]
+1 Same with my code. I updated from Jun '15 version to newest and I can see big regression in performance when scrolling and zooming timeline.

**Comment by matikucharski** [comment]
Now I noticed that this "degraded performence" is NOT occurring on Firefox. It is still smooth there for me. Only on Chrome I can see a really bad performance.

**Comment by yotamberk** [comment]
I'm having the same problem...
I'm investigating this now and testing the code - I hope to understand what's causing this majour degraded performance soon...

**Comment by yotamberk** [comment]
Hi again, 
I've done some tests and it seems that in the develop branch there is no performance issue. 
I'm not sure what exactly solved the problem but someone's PR eliminated the jittery behavior!
I suggest  trying the develop branch build in your application and see if that's better.

@mojoaxel - do you know when a release is planned? I think this issue is quite serious and should be fixed ASAP.

**Comment by mojoaxel** [comment]
> do you know when a release is planned? I think this issue is quite serious and should be fixed ASAP.

@yotamberk I've created issue #2155 for that. Let's talk there.
