### ISSUE TITLE
General bug: network.DOMToCanvas is not a function

### ISSUE THREAD

**Issue by garmoshka-mo** [almende/vis#2081]
```
  console.log(network.canvasToDOM({x: 0, y: 0}));
  console.log(network.DOMToCanvas({x: 0, y: 0}));
```

canvasToDOM works, while DOMToCanvas gives: `basicUsage.html:53 Uncaught TypeError: network.DOMToCanvas is not a function`

See `examples/network/basicUsage.html`

[vis (1).zip](https://github.com/almende/vis/files/463669/vis.1.zip)

Documentation says `DOMToCanvas` is a function - http://visjs.org/docs/network/#methods

**Comment by garmoshka-mo** [comment]
For those, who need to get it work - temporary workaround is:

```
    var pos = network.canvasToDOM({x: 0, y: 0});
    network.moveNode(sid, 500-pos.x, 100-pos.y);
```

This will move to DOM's x:500 y:100

**Comment by Tooa** [comment]
This seems to work fine? See [here](http://jsbin.com/qojunijiyu/1/edit?html,console,output). However, I also get this error when I copy your provided string above. Maybe something with the encoding don't know. I close this for now since my supplied example works.
