### ISSUE TITLE
Batch update nodes, delay redraw?

### ISSUE THREAD

**Issue by fgolemo** [almende/vis#2083]
Hi guys,

Question: **Is there any method or trick that would allow me to do 10-20 `nodes.update()` with redrawing the network only once after all the updates or when I explicitly call `redraw()`?**

Background:

I have a large network (3000 nodes, avg 16 edges per node). The drawing itself is smooth, but i'm interacting with the graph: I allow the user to click a node in the network and change it's value. This leads to all connected nodes also changing their value. 

First I tried this:
``` JavaScript
// var node is the selected node;
// var nodes is the Dataset object for the nodes

nodes.update({id: node.id, value: newVal);
otherNodes = getConnectedNodes(node);
for (var i in otherNodes) {
    nodes.update({id: otherNodes[i].id, value: newVal});
}
```
But this is teeeeerribly slow, because as I found out there seems to be a redraw after each nodes.update(); And if a redraw is 1s in a large network and I'm updating 20 nodes...

So came up with this:
``` JavaScript
// var node is the selected node;
// var nodes is the Dataset object for the nodes
var nodesArray = nodes.get();

// 'updateNodesArray" finds the corresponding node in the array and updates its value
nodesArray = updateNodesArray(nodesArray, node, newVal); 
otherNodes = getConnectedNodes(node);
for (var i in otherNodes) {
    nodesArray = updateNodesArray(nodesArray, otherNodes[i], newVal);
}
nodes = new vis.DataSet(nodesArray);
network.setData({nodes: nodes, edges: edges}); // this
```

This is a lot faster and it seems to work quite well so far. Problem I am facing now:

The `setData` method is also resetting all the edges and that takes a lot of time. Aaaand feels kinda hackish. **So the nicer option would be to disable automatic redrawing on node update, then do `nodes.update()` about 20 times, and at the end manually call `network.redraw()`. Is there something like that?**

**Comment by brichbe** [comment]
As mentioned in the [docs](http://visjs.org/docs/data/dataset.html#Data_Manipulation), the DataSet's update() method accepts either a single item, or an **array of items**.  Presumably this will only redraw the graph once after that collection of nodes is updated, so you should try doing this by combining the changed node with its connected nodes into an array and calling update() once.

**Comment by fgolemo** [comment]
Aw, sweet, thanks! :) That's perfect, didn't see that.

**Comment by fgolemo** [comment]
Guys, you can close the issue if you want. That answer by @brichbe totally solved my problem.

**Comment by mojoaxel** [comment]
@fgolemo You opened the issue. You also can close it if your question is answered ;-)
