### ISSUE TITLE
Nodes/Edges update with clusterd nodes make the clustered node visible

### ISSUE THREAD

**Issue by anguila** [almende/vis#2084]
On a network graph with clusters, if you change a property of a node in the network, and you update the data set (node/edge), all the clustered nodes became visibles for no reason.

Is quite annoying, as I wanted to gray down other nodes on click event, and it works fine (based on one of the online examples) if we don't have any cluster, but if you cluster them, once the network is updated all clustered (hidden) appear in the middle of the canvas unlinked.

Cheers,

**Comment by dragonzone** [comment]
I've been dealing alot w/ vis.js clustering and uncluster without any issue. I am not quite sure what you mean, I have example below where you can cluster them, then update the node's value without any issue:

https://jsfiddle.net/4hogk1a7/1/

If you can, modify that code to show your issue, thx!

**Comment by Tooa** [comment]
I close this issue for now. Feel free to create a new issue if your problem still exists. However, make sure you provide a minimal example that shows the problem.
