### ISSUE TITLE
Timeline's "rangechanged" is fired repeatedly on zoom

### ISSUE THREAD

**Issue by roboslone** [almende/vis#2096]
To reproduce, add following event listeners:
```js
timeline.on('rangechange', function() {console.log('rangechange')});
timeline.on('rangechanged', function() {console.log('rangechanged')});
```
And zoom timeline with pinch or mouse wheel.
Console output looks like this:
```
...
rangechange
rangechanged
rangechange
rangechanged
rangechange
rangechanged
...
```

And also (naturally) all changes happen because of user zoom, so `byUser` is always `true`.

Dragging timeline seems okay, `rangechange` fires repeatedly, but `rangechanged` - only once.

**Comment by mojoaxel** [comment]
I see, what you mean: http://jsbin.com/wowiro/2/edit?console,output

Sadly that is not easy to fix. The Mouse Wheel sends single increments if used. There is no way of knowing if the user is planing to using the wheel more in the next milliseconds.
The only way I see is to delay the `rangechanged` event by setting a timeout and wait for other mousewheel events. But "slow" scrolling would than reproduce a similar result. I don't think that's a good idea. That's just how the mouse wheel works, i guess!

If you really need this you also can implement the event delay yourself in your application. It's quits simple: http://jsbin.com/wowiro/3/edit?js,console,output

**Comment by roboslone** [comment]
@mojoaxel , thanks for reply, but your last link doesn't show any solution :(
I've tried to implement event delay yesterday, but with no success (not really a frontend guy here) :(
Could you please provide an example?

**Comment by mojoaxel** [comment]
> Could you please provide an example?

http://jsbin.com/wowiro/4/edit?console,output

**Comment by roboslone** [comment]
@mojoaxel , thanks a lot! That's exactly what I was looking for. Do you think this should be mentioned in docs?

**Comment by mojoaxel** [comment]
@roboslone No I don't think so. This has nothing to do with vis.js. If anybody is searching for this She hopefully finds this issue ;-)
