### ISSUE TITLE
Highlight today (or some other day) column

### ISSUE THREAD

**Issue by gigi81** [almende/vis#21]
This is a feature request!
First of all let me tell you this library is really well designed and easy to use. It's a really nice job. Also the documentation and the examples are comprehensive and clear.

Now let's get to my request: I'm using the timeline with grouping like in the groups example (n. 5). I would like to change the background color for today so that it's clear what is happening today. Unfortunately I couldn't find any css or javascript way to do this at the moment.

Let me know your thoughts about this.
Thanks
Luigi

**Comment by AlexDM0** [comment]
this has been added by Jos in 3.8.0

**Comment by gigi81** [comment]
Well done!

**Comment by nunks** [comment]
I'm sorry if this is a stupid question, but where are the css classes for the days of the week? I searched the repository for "vis-saturday" and all I found is the documentation saying that they exist. Shouldn't they be found on vis.css?

**Comment by josdejong** [comment]
These css styles like `vis-saturday` are dynamically created from JavaScript. The default styling of the Timeline doesn't utilize these css styles, so you will not find them in vis.css.

**Comment by daniel-pfeiffer** [comment]
They work nicely but with a kind of flaw as you change the zoom level.  E.g. if I zoom out to a whole month, day names stop to be displayed, and at the same time their css-class disappears.  But 2015-10-24 is still a saturday, no matter the zoom level.
Zooming in, the same is true, e.g. if I only display 2 days, I'll have hour classes, but no longer the day classes.  It would be great to combine them.  I.e. I use rgba (transparent) background colours that the browser can merge easily.
There should probably be thresholds for that, e.g. when zoomed out to a year, it would no longer make sence to have thousands of divs with hour classes, each less than a pixel wide. ;-)

**Comment by josdejong** [comment]
Yes that's intended behavior. It would be technically *very* expensive to keep rendering all different scales on every zoom level, which would be required if you want to do this sort of stuff. Imagine you've zoomed out to see more than a year at once. The Timeline would have to render all days, hours, etc, as it can't know if you want to colorize all Saturdays and Sundays, or all time blocks between 9:00 and 17:00. Besides that, I think it could easily result in a very noisy, chaotic view. I think it's best to keep the styling of the days/hours/etc per scale. A smooth transition would be cool, but is technically very hard to achieve.

**Comment by lbrdar** [comment]
Hi all,

did anyone manage to highlight a specific day? Let's say that I want to highlight Christmas or any holiday, how would I be able to do it? 

I see that custom classes were added to control for example day of the week or specific hour. But using those classes for highlighting a holiday wouldn't really work. 

Can someone please help me with this?


Thank you,
Leo

**Comment by Jogai** [comment]
Highlighting christmas is as easy as:

```
.vis-day25.vis-december {
    background: red;
}
```

**Comment by lbrdar** [comment]
@Jogai 

Not really, as vis classes are added and removed dynamically, that will work only in case of a certain zoom level where those classes are applied.

**Comment by Jogai** [comment]
That is true, but technically it is not visible anyway.

**Comment by leobrdar** [comment]
It's still visible, though. Maybe it's not displayed as a date on the axis, but it's still visible.

However, my specific use case is - I want to highlight the non-working hours and weekends. But, since weekday classes are removed on zoom, it looks like this: 
![screen shot 2018-07-10 at 15 13 55](https://user-images.githubusercontent.com/39524074/42512077-f0e4ac2a-8453-11e8-9070-f2beb886a040.png)

The correct display would be that all hours on Saturday and Sunday are highlighted. Is there any way to do this?

Why are classes removed anyway? Why not keep all higher classes on all zoom levels? For example on zoom where days are displayed, keep week, month and year?

**Comment by jgorene** [comment]
Hello,

It's not ideal but depending on the needs, I use this approach which works quite well (as much as possible) although it should be able to do better, ideally from a native option with a callback.
if it can help ;)
```
<style>
.specialDayClass {
    background: rgba(255, 0, 0, 0.5);
}
</style>

// javascript
timeline.on('rangechanged', function(s) {
    var start = moment(timeline.getWindow().start).format("YYYY-MM-DD"),
        end = moment(timeline.getWindow().end).format("YYYY-MM-DD");
    var publicHolidays = getPublicHolidays(start, end) // assume have an array containing "special days"
    .map(date => "vis-day" + moment(date, "YYYY-MM-DD").format("D") + " vis-" + moment(date, "YYYY-MM-DD").locale('en').format("MMM").toLowerCase());
    publicHolidays = [...new Set(publicHolidays)];
    console.log(publicHolidays);
    for (var i = 0, lg = publicHolidays.length; i < lg; i++) {
        var specialDayClass = publicHolidays[i];
        var list = document.getElementsByClassName(specialDayClass)[0];
        console.log(list);
        if(list !== undefined) list.classList.toggle("specialDayClass");
    }
 });
```

**Comment by jgorene** [comment]
@leobrdar I also encountered this problem and after working for a while, I finally found a solution to my needs. Even if it's a little far-fetched, it still works pretty well...

Anyway, it's only a workaround because I haven't found any other way to do that yet, indeed. 
In any case, it must be adapted to your needs, of course.

Here a working example https://output.jsbin.com/xatuxeq

**Comment by mojoaxel** [comment]
@jgorene :heart_eyes:  Thanks for sharing!

**Comment by jgorene** [comment]
@mojoaxel Thank you so :wink:
By the way, thanks a lot for your involment here :thumbsup:

That said, I just updated "the bin" to try to get something a little more user friendly.
Nevertheless, it's still some tinkering for now...

**Comment by Anja-R** [comment]
@josdejong Great example - thank you.
Do you have any idea on how to do the same thing when using groups?
