### ISSUE TITLE
Network: Zoom button doesn't work like expected

### ISSUE THREAD

**Issue by nikitakurylev** [almende/vis#2100]
Hi,
Zoom button doesn't work correctly, it zooms to the center of network, not to the center of screen.
It supposed to work like traditional (google) map zoom button.
Not sure if it is bug.

Thanks and best regards

**Comment by tomzx** [comment]
Hello @nikitakurylev, could you provide a link to an example with those zoom buttons? Using the mouse does zoom to where the cursor is, while zoom buttons would need a viewport coordinate to specify where the zoom should occur, none being given would imply the center of the viewport.

**Comment by mojoaxel** [comment]
Here is an example: http://visjs.org/examples/network/other/navigation.html

**Comment by nikitakurylev** [comment]
![tos](https://cloud.githubusercontent.com/assets/21079118/18643751/14d7fd1e-7eaf-11e6-845b-01084b25c3c4.gif)
Firstly I zoom it with mouse wheel, and then with zoom button.
I can get coordinates with `getViewPosition()`, but how can I set them for zoom button?

Thanks
