### ISSUE TITLE
Customize the edge types of vis.network

### ISSUE THREAD

**Issue by lehuyhuan** [almende/vis#2103]
Dear all,

The edge in vis.network is simple, Can anyone show me the way to modify the source code (vis.min.js) to create a new edge type with support 2 color and 2 label at both site. I mean when an edge connected by 2 node (in my scenario is 2 router) So I want to add 2 label in both size to show the interface is connected and the color to show the state of both interface.

I am trying to read vis.min.js to find the place where I can modify but it so difficult at now.

Can anyone experienced this case or have knowledge about this help me. Thanks all!

**Comment by mojoaxel** [comment]
@labianchin Sady this is not possible at the moment. I've created a new feature-request for something similar: #2104

Also if you want to change the source you should never try to change the minified (vis.min.js) version, but the original source.
