### ISSUE TITLE
Timeline: input fields as content in item blocks?

### ISSUE THREAD

**Issue by ArunSivagnanam** [almende/vis#2112]
Hi, is there a way to make input fileds as content in item blocks in timeline? Right now it seams like the events are blocked

**Comment by yotamberk** [comment]
You can use the `template` option. see http://visjs.org/docs/timeline/#Templates

**Comment by mojoaxel** [comment]
@yotamberk Thanks!
@ArunSivagnanam If you have problems with the events please let us know and reopen the issue.
