### ISSUE TITLE
Adding edges between nodes in Timeline? Possible?

### ISSUE THREAD

**Issue by vasadhananjay** [almende/vis#2113]
I'm trying to create a gantt chart with timeline. Need to add lines between various items in the timeline's dataset. Has anybody been able to do something similar?

**Comment by vasadhananjay** [comment]
Nevermind. Looks like someone beat me to the [punch](https://github.com/almende/vis/issues/1699)...

**Comment by mojoaxel** [comment]
duplicate of #1699
