### ISSUE TITLE
Save timeline

### ISSUE THREAD

**Issue by lucasf10** [almende/vis#2117]
Is it possible somehow to save the timeline created into an image or an svg?
I'm working on an interactive timeline maker for an university project and was wondering that.

Thank you.

**Comment by nicolasbd** [comment]
You could use a library like [html2canvas](https://html2canvas.hertzen.com/examples.html)

**Comment by lucasf10** [comment]
Hey Nicolas, thanks for answering. I did it with html2canvas but it doesn't save the full timeline, only whats showing, so if its a really big TL it's not very useful. Any other idea?

**Comment by mojoaxel** [comment]
I see no way of doing that. Nodes get removed, when they leave the visible space. Maybe there is a way to write your own renderer based on the timelines data but that would be complicated. Sorry.
