### ISSUE TITLE
Actual vs estimated visualization in timeline

### ISSUE THREAD

**Issue by ns-nikhilsheth** [almende/vis#2119]
Hi, is it possible to visualize actual and planned/estimated dates (total 4 dates ) as one item?
I tried creating background item for min and max of the 4 dates. It works. Now i would like to plot ranges for delayed start(actual start - estimated start), then progress (actual start to now) for incomplete tasks..and so on.
I am not sure how to do it? I have two questions
- is it possible to achieve this using visjs?
- if yes, then how?

**Comment by yotamberk** [comment]
One way to do it is by defining the two times as one subgroup and set the timeline options with 
`stack: false` - this will cause times to overlap. Unfortunately it is not possible yet to define non-stacking in a subgroup and stacking between subgroups so in this solution the subgroup will only supply some sense to times that belong to the same planned/estimate date pair. 
It might be a good feature request.
