### ISSUE TITLE
do not scale when change size

### ISSUE THREAD

**Issue by lukasw44** [almende/vis#2120]
How can i disable scaling when i change screen size, so basically i wanna scroll my timeline when screen is small but not scale: 

<img width="265" alt="screen shot 2016-09-23 at 17 13 17" src="https://cloud.githubusercontent.com/assets/3924636/18830016/c7d707bc-83d6-11e6-9749-d729b9e18ada.png">

and that how its look like when its scale: 

<img width="228" alt="screen shot 2016-09-26 at 10 49 25" src="https://cloud.githubusercontent.com/assets/3924636/18830066/fc84a492-83d6-11e6-8f84-e91ce0985760.png">

But on mobile phone i wanna look like same as desktop but just scroll 
this is my options :
 `timeAxis: {scale: 'day', step: 1},
        zoomable: false,
        moveable: true,
        autoResize: false, //this one
        stack: false,    ///this one
        zoomMin: 2678400000, //31 days
        zoomMax: 2678400000`

 And `autoResize` works fine until i scroll my timetable then vis redraw and scale my timetable

**Comment by mojoaxel** [comment]
@lukasw44 Is this issue still relevant or can we close it?

**Comment by yotamberk** [comment]
@lukasw44 If this issue is still relevant please reopen
