### ISSUE TITLE
Nodes click, blur, hover events issue

### ISSUE THREAD

**Issue by qazimir** [almende/vis#2121]
I found this issue:

There is a on click, hoverNode and  blurNode functions in my network.

When I place cursor inside node hover is fired, thats OK. 
When I click inside the same node then both click and blur function are fired. 
Still inside the same node, when I move cursor hover is fired again.

You can try it in fiddle: https://jsfiddle.net/ve8cshvh/6/ just open console and click on node.

Q.

**Comment by mojoaxel** [comment]
@Iskander508 Can you have at look at this, please!

**Comment by Tooa** [comment]
@qazimir I've clicked on node 4 and the following messages are logged to the console: ``hover executed``, ``click executed``. Cannot reproduce your issue.

Best Uli

**Comment by mojoaxel** [comment]
> When I click inside the same node then both click and blur function are fired. 

I also **can not reproduce** this in Chrome and Firefox.

**Comment by qazimir** [comment]
Try move with mouse inside the node and then click on the node.

**Comment by mojoaxel** [comment]
@qazimir I don't see an issue here. Please describe in more detail what your problem is.

**Comment by qazimir** [comment]
Hi, I forget to test it in other browsers. It seems to be problem only in chrome. My current chrome version is 53.0.2785.143 m (64-bit).

Problem is that the blur event executes after click on node. If you don't see the problem then it is probably bug in my browser.

Sorry for false alert ;-)

**Comment by mojoaxel** [comment]
I still can not reproduce this with Chrome (50.0.2661.75). I say let's just forget it and reopen if the problem still exists in later browser version.
