### ISSUE TITLE
Disable physics for a node when a user drags it

### ISSUE THREAD

**Issue by ankitgoyal100** [almende/vis#2125]
How do I disable physics for a certain node when a user "interacts" with the node (ex. drags/clicks the node). I am manually adding "physics: false" to the data and reloading it but the graph has to re-stabilize and it's not ideal. What's the best solution?

**Comment by dragonzone** [comment]
You are setting it wrong, therefore, not working correctly for you. You need to read the documentation more carefully. Here it is: http://visjs.org/docs/network/physics.html#

It needs to be something like this:

```
network.setOptions({
	physics: {
		enabled: false // true | false
	}
});
```

**Comment by dragonzone** [comment]
I think this issue can be closed b/c the above solution will work.
