### ISSUE TITLE
Use Map on Image's specific areas..........

### ISSUE THREAD

**Issue by vickyscorpions** [almende/vis#2128]
Hi Team of Great People,

I have created a network graph using Vis. Now, here you can see the image is placed in the center, I want to divide this image into like different parts and want to make those clickable...like e.g if someone clicks the
top left of the image, I want to do hide specific nodes and show the related nodes. Same for other specific areas like we use maps in html. Can you please guide me. I am newbie to this plugin..So far, I am loving this and want to stick to it. Please help

![issue123](https://cloud.githubusercontent.com/assets/22571116/19019223/3590ee32-8899-11e6-82af-9d036c2fb9ac.jpg)

**Comment by vickyscorpions** [comment]
Hello...Is there someone to help :( ??

**Comment by mojoaxel** [comment]
> Hello...Is there someone to help

If you have project specific questions please use [stackoverflow](http://stackoverflow.com/questions/tagged/vis.js).
