### ISSUE TITLE
Participate in Hacktoberfest

### ISSUE THREAD

**Issue by Tooa** [almende/vis#2129]
Hi,

I suggest participating with visjs in the current running [Hacktoberfest](https://github.com/blog/2260-hacktoberfest-is-back). It's really simple: 

```
Submit your open-source project

Apply the label "Hacktoberfest" to issues in your GitHub-hosted project that are ready for new contributors to work on.
```

Such labeled issues can be seen [here](https://github.com/search?l=JavaScript&q=state%3Aopen+label%3Ahacktoberfest&ref=advsearch&type=Issues&utf8=%E2%9C%93). Thereby, we may attract new developers for visjs. Here are some of my favorite issues and enhancements for this label. Feel free to suggest more :+1: 
- https://github.com/almende/vis/issues/2104
- https://github.com/almende/vis/issues/1965
- https://github.com/almende/vis/issues/1717
- More arrow types: https://github.com/almende/vis/issues/1444
- https://github.com/almende/vis/issues/2073
- https://github.com/almende/vis/issues/1315

Best Uli

**Comment by mojoaxel** [comment]
Nice! If anybody wants to suggest an issue, just post it here!

**Comment by mojoaxel** [comment]
Thanks for the idea! 
Hacktoberfest is now over and some of us earned themselves a T-shirt!
