### ISSUE TITLE
Network - Question - How to only allow Horizontally drag for network chart?

### ISSUE THREAD

**Issue by JamieZhang2016** [almende/vis#2130]
I created a network chart using vis.js. In Options -> Interaction, we can set "drawView" to enable or disable the chart dragging. However, is there a way for me to only allow Horizontally dragging the chart?

**Comment by dragonzone** [comment]
Yea it's pretty easy, you can check it out a quick snippet I created here:

https://jsfiddle.net/pfvbmnub/

**Comment by JamieZhang2016** [comment]
Thanks dragonzone! I will check it out.

**Comment by JamieZhang2016** [comment]
Hey dragonzone, I tried your snippet and it locks the vertical drag, but only for the Nodes. Actually I want to  lock vertical drag for the whole canvas, which is the whole network chart. I tried many ways but could not achieve this goal. Thanks a lot.

**Comment by dragonzone** [comment]
I am not quite sure what you mean, if you can create a snippet like I did to view it, that would greatly help. But in the example I had, none of the nodes can be drag vertically, which is the whole network chart. You can also define that option before drawing your network:

```
nodes: {
    fixed: {
        y: true
    }
}
```

**Comment by JamieZhang2016** [comment]
we can use your snippet. If you drag the network chart, try to don't select any node or edge, and move your mouse, you will find the whole chart is moving, both vertical and horizontal.
Then come to my request, I'd like to disable the vertical movement as I described above. What I've tried is doing something on the canvas, or the wrapped div. Because I haven't got a clear idea, so we can use your snippet as a example.

**Comment by dragonzone** [comment]
I see. For that, you will probably have to create a fork & modify vis.js yourself. Basically, inside the vis.js code (which I look at while back), there is a 'dragging' event, which will add/subtract both the x & y from the previous point, hence moving the whole network. All you need is set diffY = 0 (which is the vertical) and only the x-axis will move. Hope this helps.

**Comment by JamieZhang2016** [comment]
Good idea, I will try. Thanks a lot!

**Comment by JamieZhang2016** [comment]
Thanks dragonzone! I tried the idea you provided to create a fork vis.js and set diffY = 0, it achieves my goal.
