### ISSUE TITLE
Allow no "end" for "range" items in timeline

### ISSUE THREAD

**Issue by roboslone** [almende/vis#2132]
This is a feature request for timeline.
#### What?

Allow "range" items to have no `end`.
#### Why?

To correctly display events, that aren't finished at the moment.
#### How?

On `currentTimeTick` set some item attribute representing `end` to `new Date()`, but don't touch real `end`.

I think that could be done using event listeners without any changes to vis.js library, but it seems to me that dropping `end` for unfinished events would be much better and much more simple for end users.

**Comment by yotamberk** [comment]
Sounds like a good idea! Quite useful!

**Comment by yotamberk** [comment]
Hi @roboslone, I'm looking in to this feature and I'm wandering how did you image this. I'd like you thoughts before I apply this: 
- Can an updating ranged item stop updating? How/when does it stop? Can a user stop it manually?
- After an updating item has been stopped and its end item has been set (assuming the above is possible), can a user make it again updating? How would he do it? Will the ranged item forget its end time set before?
 
I'm asking these questions to see if what I think is what you meant and want.

**Comment by roboslone** [comment]
Hi!

In my case timeline updates in real time and users cannot change the data via web interface. So only backend decides when item needs to stop updating. I believe default behaviour should be "if item has no end it updates forever".

Just to clarify things, I'm using timeline in read-only mode and my users do not interact with data directly through timeline in web interface. I think most other cases out there are different and other timeline users may have different interests and opinions about this. But for me "update forever" behaviour would work great.

Right now I have to change item's end time on backend with each request and, to be honest, that's not that big a deal (such items don't poison cache or anything since they're treated differently from items with end time). However "no end" solution would be much more simple and beautiful.

P.S. Sorry it took so long for me to reply. I'm ready to help as much as I can to make this feature happen.

**Comment by yotamberk** [comment]
@roboslone Working at it =) I hope to have something for the next release

**Comment by roboslone** [comment]
@yotamberk Thanks!

**Comment by yotamberk** [comment]
After many thoughts about this feature, I think it's not a good idea... I would simply do the same as you did: updating the items' end date on backend. This feature will cause very problematic bugs with editing, and interaction with these types of items is not mature enough to be implemented at this point...
