### ISSUE TITLE
[printBuffer] Uncaught TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by pjama** [almende/vis#2134]
I'm experiencing this error on a tap event (on a graph node)

![screen shot 2016-10-04 at 10 30 12 pm](https://cloud.githubusercontent.com/assets/306321/19102110/6689eb0c-8a82-11e6-8606-5fec905e85fb.png)

Any advice would be appreciated, thanks.

**Comment by mojoaxel** [comment]
@pjama Could you please provide a simple [jsbin](http://jsbin.com/) dummy to reproduce this. That would help a lot!

**Comment by pjama** [comment]
@mojoaxel, I was mistaken and, in fact, the issue was not with the vis.js library. Apologies for the confusion.
