### ISSUE TITLE
Duplicate UUID in dataset using Safari

### ISSUE THREAD

**Issue by 2dvisio** [almende/vis#2137]
Hello,

I am implementing this: http://jsfiddle.net/jnpwzn3c/1/ as a dashboard for one of our projects. However, although all works in Chrome and Firefox, for some reason two of the graphs are not displayed in Safari.

In Safari the Weight and Step plot are not displayed and I get this error:
"Error: Cannot add item: item with id cc173118-c076-4de0-a1dd-14a343cc9ec4 already exists"

Any clue anyone?

**Comment by Tooa** [comment]
Can you provide a **minimal** example that shows the issue? Your example contains a lot of code. Therefore it is hard to actually focus on the real issue. 

Best Uli

**Comment by 2dvisio** [comment]
I have digged in my own code (here a slimmer version: http://jsfiddle.net/jnpwzn3c/6/ .
Apparently I had a bug in `fillDates` (caused by the `Date.toISOString()` function that duplicated some of the keys in the array that I fed to Dataset.

The new function `fillDatesFixed` used here: http://jsfiddle.net/jnpwzn3c/7/ does not duplicate data, thus no problems in generating the bar chart.

However, this is still weird, the group I generate (group: 0) has the property `stacked` set to `true` and should not have any of this issues right?

Feel free to close this if you feel this is not a bug, but I would keep it open because:

1. The code with the duplicate should work and stack the two bars one on top of the other
2. The code with the duplicate work both in Chrome and Firefox and crashes only in Safari

Thank you.

**Comment by mojoaxel** [comment]
@2dvisio If you think you found a bug please open a new issue.
