### ISSUE TITLE
Hierarchical layout produces very "stretched" networks

### ISSUE THREAD

**Issue by glampr** [almende/vis#2140]
By just modifying the 'nodeSpacing' options of the network, I get really different results for the network.
An example can be found in this plunker https://plnkr.co/edit/QKgaku?p=preview
Initially the network layouts fine, but try to change nodeSpacing from 250 to 260 for example, then the layout seems totally wrong.

**Comment by KunalAppensure** [comment]
Hey, I have found one solution
set **hierarchical.edgeMinimization** as **true**
or
set the combination of **hierarchical.edgeMinimization** and **hierarchical.blockShifting** to
**true** or **false** according to your choice of layout in the layout module .
It worked for me , hope it will help :) .

**Comment by mojoaxel** [comment]
@glampr Was the answer of @KunalAppensure helpful to you? If so please close this issue.

**Comment by glampr** [comment]
The only way to make the second network "kind of" work, is to disable **edgeMinimization** and **blockShifting**, see this example.
https://plnkr.co/edit/Q867VY?p=preview
Seems like this is not yet fixed.

**Comment by wimrijnders** [comment]
Duplicate #1735

**Comment by wimrijnders** [comment]
I'm happy to report that this problem does not occur any more in `vis.js v4.19.1`. It still occurs with other option combinations, though.

I'm closing this, but will use the given data for testing and verification.
