### ISSUE TITLE
Network node `x` and `y` coordinates not working

### ISSUE THREAD

**Issue by ankitgoyal100** [almende/vis#2142]
Hi, when I try to manually set a node's `x` and `y` coordinates, nothing changes and the nodes stay in their default stabilized position. What am I doing wrong? 

Here are the options I'm passing to my network: 
```
 options: {
   nodes: {
     scaling: {
       min: 43,
       max: 85
     },
     size: 20,
     shape: 'box'
   },
   edges: {
     arrows: {
       to: {
         enabled: true,
         scaleFactor:1
       },
       middle: {
         enabled: false,
         scaleFactor:1
       },
       from: {
         enabled: false,
         scaleFactor:1
       }
     },
     color: {
       color: '#000000',
       highlight: '#000000',
       hover: '#000000',
       inherit: false
     },
     scaling: {
       label: {
         enabled: false
       }
     },
     smooth: false,
     width: 0.5
   },
   layout: {
     hierarchical: {
       enabled: true,
       levelSeparation: 90,
       nodeSpacing: 150,
       sortMethod: 'directed'
     }
   },
   physics: {
     hierarchicalRepulsion: {
       centralGravity: 0,
       springLength: 100,
       springConstant: 0.005,
       nodeDistance: 25
     },
     stabilization: {
       enabled: true
     },
     maxVelocity: 50,
     minVelocity: 0.75,
     solver: 'hierarchicalRepulsion'
   },
   interaction: {
     hover: true,
     selectable: true
   }
 }
```

**Comment by dragonzone** [comment]
There is an example here that sets the x & y coord for you to study. Hope this help.

https://github.com/almende/vis/issues/2017

**Comment by ankitgoyal100** [comment]
@dragonzone I am correctly setting the `x` and `y` keys of the node but the pre-defined node locations are not reflected on the graph. Here is my node json: 

```
color:"#607d8b",
font:{...},
id:20,
label:"Filter",
x:-103,
y:180
```

What am I doing wrong?

**Comment by ankitgoyal100** [comment]
@dragonzone it seems to be an issue with `hierarchicalLayout` enabled. I don't think I can preset node locations with this option enabled. Is that correct? If so, how do I work around this?

**Comment by dragonzone** [comment]
Once the hierarchical layout is enabled, it takes precedence over the x & y coord of the node. In you case, if you want to manually set the x & y coord, you should not set anything in the options's layout hierarchical (just leave it blank) and use the default layout.
