### ISSUE TITLE
Network - Question - Is it possible to set interaction zoomView option dynamically. 

### ISSUE THREAD

**Issue by JamieZhang2016** [almende/vis#2148]
I got a new requirement on the Network Zooming function. what I'd like to do is dynamically set Network  Zooming Enable or Disable by clicking a button.
I know when build the network we can set option, in "interaction" we can set zoomView as false or true. However that's before drawing the network chart right?

So my question is, can we dynamically set zooming enable or disable after the chart generated, and without re-draw the chart?
Maybe the code just something like the idea of: {_network.option.zoomView = false;}   I tried to find the solution like the code but I couldn't. Thanks!

**Comment by JamieZhang2016** [comment]
I've tried to disable the network canvas "mousewheel" event, actually it works, just like we disable the Zooming on the network. But the problem is "mousewheel" will be 100% not working on the chart. But I want to keep the scrolling page on network, which by setting build in option zoomView can achieve this goal.

**Comment by dragonzone** [comment]
Almost all the network, nodes & edges options are available in this example here: http://visjs.org/examples/network/other/configuration.html

You should play around with it & at the bottom, it will generate the values of those options that were changed.

To dynamically changed those options, there is a network.setOptions() where you can pass those params in. Here is the example w/ what you are looking for: https://jsfiddle.net/skbthu9v/

**Comment by JamieZhang2016** [comment]
dragonzone, the network.setOptions works great! Thanks a lot for your help!

**Comment by dragonzone** [comment]
NP. You have a few other issues open, if they work, try to close them out so they do not appear to be so many issue in this proj. This would help vis.js team greatly.

**Comment by JamieZhang2016** [comment]
ok, I will close those already fixed.
