### ISSUE TITLE
Network: set initial position for nodes, but let them wander freely afterwards

### ISSUE THREAD

**Issue by randombumper** [almende/vis#215]
Hi,

I'm, working with the Network visualization, and I'm facing a problem: I need to specify the **initial** position of the nodes (the random initialization doesn't work for me), but I don't want them to remain fixed forever.

I have tried this in several ways, to no avail:
- Setting both `x`, `y`, `allowedToMoveX: true` and `allowedToMoveY: true` when defining the node set.
- Setting `x` and `y` and later resetting them to `null` (nothing happens) or `undefined` (infinite recursion occurs, for some reason).
- Setting `x` and `y` at definition, and later setting `allowedToMoveX` and `allowedToMoveY` to true.
- Setting `allowedToMoveX: true` and `allowedToMoveX: true` at definition, and later setting `x` and `y`.

This all result in the same: **whenever I set `x` and `y` for a node, it will stay pinned forever**, no matter what I do or when I do it.

For extra background about my specific needs, I'm trying to define a network formed by three concentric rings (cycles of N nodes):

![network-demo](https://cloud.githubusercontent.com/assets/3001813/3561075/c799ebd2-09a5-11e4-989f-3d44af212939.png)

The definition of the network itself doesn't provide enough information to render it properly, the result being variations of this:

![non-concentric-cycles](https://cloud.githubusercontent.com/assets/3001813/3561085/55b1421c-09a6-11e4-9128-ed1178b1c52e.png)

If I were able to _hint_ an initial `x` and `y` for each node and let them gravitationally wander off thereafter, I'm pretty sure I'd be able to achieve concentricity.

Any ideas? :)

Thanks and regards,

Pablo.

**Comment by nitin0708** [comment]
Hi,

How to stop movable of nodes for hierarchical tree ?

Thanks and Regards,

Nitin

**Comment by AlexDM0** [comment]
Hi Nitin,

I already answered this in the other issue but for completeness I'll copy it here. 

You can use the freezeSimulation(true) method on stabilized to stop the simulation. You could also use the dragNodes option to disable dragging of nodes. 

Alternatively, you could disable the physics simulation with

```
var options = {physics: {hierarchicalRepulsion: {nodeDistance: 0, springConstant: 0}}
```

It is not possible to lock the position of individual nodes in the hierarchical system. 

Regards,

Alex

**Comment by rmasrani** [comment]
Hi Alex.  Thanks for the great work.  I have just started using your application, and have the following (I am afraid simple) problem.  I have a network with 14,000 nodes and about 30,000 edges.  I am able to create the network fine (it takes time).  I saved the x/y coordinates, and created a JSON with these hard coded.  Problem is that the network with the original output looks very different than the network with the x/y coordinates built in.  I have tried various suggestions, but look like I am missing something simple.  Physics is false.  Any suggestions or links to existing docs?  Thanks.

**Comment by AlexDM0** [comment]
Hi,

It could be due to a bug in the improvedLayout. Try turning that off. 

Cheers!

**Comment by rmasrani** [comment]
Hi Alex.  I did that, and I turned off physics.  In fact, I tried practically every combination of manipulation I could think of – no luck.

**Comment by AlexDM0** [comment]
Hi,

It would help a lot if I could see the code. Is it shareable? Or reproducible? Our examples do work with fixed locations. 

Regards

**Comment by rmasrani** [comment]
Can you share your email ID?

__________________________________________________

Roy Masrani l CEO
E:  <mailto:rmasrani@CodeExcellence.com> rmasrani@CodeExcellence.com l T: (403) 875-0809 l W: http://www.CodeExcellence.com <http://www.codeexcellence.com/>

**Comment by AlexDM0** [comment]
I'd prefer to discuss this on github since multiple people may have this issue.

Regards

**Comment by rmasrani** [comment]
Ok – will do. I will try to get the code down to the core and set it up on fiddle. I wonder if it is the volume of nodes that is throwing it off.  But I will experiment and let you know.
