### ISSUE TITLE
Build creates wrong code for moment.js embed

### ISSUE THREAD

**Issue by neolivz** [almende/vis#2163]
When web pack build is happening it is creating 
```
                  !(function webpackMissingModule() { var e = new Error("Cannot find module \"./locale\""); e.code = 'MODULE_NOT_FOUND'; throw e; }());
```
this is due to the build process is repeatdly going through each of the require and embeddin it into the vis.js file. This is fine as long full require is present but in moment.js|

```
function loadLocale(name) {
        var oldLocale = null;
        // TODO: Find a better way to register and load all the locales in Node
        if (!locales[name] && (typeof module !== 'undefined') &&
                module && module.exports) {
            try {
                oldLocale = globalLocale._abbr;
                require('./locale/' + name);
                // because defineLocale currently also sets the global locale, we
                // want to undo that for lazy loaded locales
                locale_locales__getSetGlobalLocale(oldLocale);
            } catch (e) { }
        }
        return locales[name];
    }
```
which causes build to create wrong output.

**Comment by mojoaxel** [comment]
There are multiple things to note using vis with webpack:

1) You should always importing only the vis modules that you use in your application and not the big "all-inclusive" distribution-version.

2) Vis.js is written in ES2015. You need to setup babel for this:
```
{ test: /node_modules[\\\/]vis[\\\/].*\.js$/, loader: 'babel',
	query: {
		cacheDirectory: true,
		presets: ["es2015"]
	}
},
```

3) There is a problem importing moment.js with webpack. [See here](http://stackoverflow.com/questions/25384360/how-to-prevent-moment-js-from-loading-locales-with-webpack). You could fix this by using webpacks "ContextReplacementPlugin":
```
new webpack.ContextReplacementPlugin(/moment[\\\/]locale$/, /^\.\/(de|en)$/),
```

**Comment by neolivz** [comment]
@mojoaxel 
1. npm install vis gives full vis library.
2. I am using typescript/aurelia/webpack when I build it fails because the vis.js file has multiple unreachable codes (which got inserted as part of the build process from the moment.js). Which in turn makes my build failure.

Maybe it would be ideal to pick and select what features you want from visjs but when you want things up and running you would just like to do npm install and run.

**Comment by mojoaxel** [comment]
> Maybe it would be ideal to pick and select what features you want from visjs but when you want things up and running you would just like to do npm install and run.

You could try importing only the part of vis you really use (e.g. `dist/vis-network.min.js`).

I've created a feature request to show how to integrate vis.js in a webpack project: #2186
