### ISSUE TITLE
How to prevent horizontal arrows in a directed (UD) network

### ISSUE THREAD

**Issue by ankitgoyal100** [almende/vis#2164]
I have a directed network and I don't want any horizontal arrows. For instance, if I have this graph: 
<img width="214" alt="screen shot 2016-10-17 at 11 47 14 am" src="https://cloud.githubusercontent.com/assets/3400675/19450769/99318bc8-945f-11e6-88ae-8b1a7d765124.png"> I want node "1" to be at the top level, followed by node "2" at a lower level, followed by node "3" at the lowest level. Is there a way to achieve this configuration?

**Comment by mojoaxel** [comment]
First you must enable hiracical Layout:
```
layout: {
    hierarchical: {
      direction: 'UD'
    }
  }
```
Than you can set a "level" to each node.

Here is an example:
http://jsbin.com/duqasu/4/edit?js,output

**Comment by ankitgoyal100** [comment]
@mojoaxel When there is one node at each level, one of the edges is hidden. How do I force the graph to not hide the edge. 

Here is an example: 
http://jsbin.com/yohawaquwo/1/edit?js,output

**Comment by dragonzone** [comment]
The edges need to have a smooth setting one of the following: 'diagonalCross' OR 'curvedCW' OR 'curvedCCW'. You can go here go get all other types: http://visjs.org/docs/network/edges.html

You can go here to view an example: https://jsfiddle.net/krp3dx1e/

Good luck!
