### ISSUE TITLE
WebWorker + Network

### ISSUE THREAD

**Issue by ClaPro** [almende/vis#2169]
Having to deal with intense calculations, I'd like to use **webworkers** with Networks.
Not being able to pass DOM objects(container) between main thread and webworker, how i can create an instance of network = new vis.Network(container, data, options); in a worker?
I'd like to know if is possibile assign a **container** only later.

Thank you,
C.

**Comment by Tooa** [comment]
Hi,
some time ago someone worked on a webworker version [1]. Maybe you can pick it up and finish. 

[1] https://github.com/almende/vis/pull/1348
