### ISSUE TITLE
Dynamic time scale for timelines

### ISSUE THREAD

**Issue by palra** [almende/vis#2172]
Hello,

I'm looking for implementing a timeline for one of my projects. I would like to know if it possible to use dynamic time scales. For instance, I need to implement a timeline covering 4 years : for the first year, the reference unit would be the trimester, for the second year the time unit would be a semester, and for the two last years the time unit would be an entire year. In other words, a trimester from the first year, a semester from the second year and a year of one of the two last year would have the same length. Is there any ways to achieve this ? If writing a plugin is needed, I think I can do it, but I want to know if Vis.js can handle this by design.

**Comment by yotamberk** [comment]
Hi @palra , 
In the develop branch there is a new function `options.format' which takes as arguments the date, scale and step for the current label. You might be able to use that option to show labels according to date (e.g. in pseudo-code
```javascript
option.format.minorLabels = function(date,  scale, step) {
  if (date< <2 years ago> & <month>%4==0) {return date}
  else return ""  
}
```
)

If you want to play around with this, I suggest you pull the project, checkout to develop and build it. There is an example in the examples>timeline>other>customFunctionLabels

**Comment by mojoaxel** [comment]
@palra Is your question answered? Than, please close the issue.
