### ISSUE TITLE
adding Italian locale language

### ISSUE THREAD

**Issue by federicoco** [almende/vis#2173]
I know that you only have the english and Deutsche locale languages, 
I would like to ask if it was possible to add italian locale language, and I would also
provide the datas translation for italian locale language.
Maybe it would be great to add on your site a form where everyone can insert the date/locale equivalent datas in their language.

if you are interested in adding italian local language,can you please leave a mail ?

**Comment by Tooa** [comment]
Hi, 
sounds great! If you provide the translation for the following two snippets, I can create a pull request.

**1. Network**

```
// English
exports['en'] = {
  edit: 'Edit',
  del: 'Delete selected',
  back: 'Back',
  addNode: 'Add Node',
  addEdge: 'Add Edge',
  editNode: 'Edit Node',
  editEdge: 'Edit Edge',
  addDescription: 'Click in an empty space to place a new node.',
  edgeDescription: 'Click on a node and drag the edge to another node to connect them.',
  editEdgeDescription: 'Click on the control points and drag them to a node to connect to it.',
  createEdgeError: 'Cannot link edges to a cluster.',
  deleteClusterError: 'Clusters cannot be deleted.',
  editClusterError: 'Clusters cannot be edited.'
};
```

**2. Timeline**

```
// English
exports['en'] = {
  current: 'current',
  time: 'time'
};
```

Best Uli

**Comment by federicoco** [comment]
//Italiano
exports['it'] = {
  edit: 'Modifica',
  del: 'Cancella la selezione',
  back: 'Indietro',
  addNode: 'Aggiungi un nodo',
  addEdge: 'Aggiungi un vertice',
  editNode: 'Modifica il nodo',
  editEdge: 'Modifica il vertice',
  addDescription: 'Clicca per aggiungere un nuovo nodo',
  edgeDescription: 'Clicca su un nodo e trascinalo ad un altro nodo per connetterli.,
  editEdgeDescription: 'Clicca sui Punti di controllo e trascinali ad un nodo per connetterli.',
  createEdgeError: 'Non si possono collegare vertici ad un cluster',
  deleteClusterError: 'I cluster non possono essere cancellati',
  editClusterError: 'I clusters non possono essere modificati.'
};

2. Timeline
// Italiano
exports['it'] = {
  current: 'attuale',
  time: 'tempo'
};

is there also some way to x-axis date in italian ?
like  'February' -> 'Febbraio'

Thank you

**Comment by mojoaxel** [comment]
> Maybe it would be great to add on your site a form where everyone can insert the date/locale equivalent datas in their language.

This is a nice idea! Does anybody know a good way to easily add translations? Maybe introducing .po files or something? Suggestions are welcome!

**Comment by Tooa** [comment]
> is there also some way to x-axis date in italian ?

I couldn't find any hard-coded references in the code. Maybe some `Timeline` expert can help here out and point to the respective code listing. If there is no such feature, we might create another ticket tackling this support.

Best Uli

**Comment by mojoaxel** [comment]
> What about this line here.

As far as I can tell this line was not used and wrong anyway.

> It misses the other locales like "ru", etc ... Not sure what it is for.

I created #2188 to fix this. All languages should be now available in the docs and the network manipulation example as well.
