### ISSUE TITLE
Ignore the "dist" folder in the develop branch

### ISSUE THREAD

**Issue by mojoaxel** [almende/vis#2181]
We should find a way of adding the `dist`folder to gitignore, in the develop branch, but keep it version controlled in the master branch.

Anybody a idea how to do that?

**Comment by yotamberk** [comment]
http://stackoverflow.com/questions/1836742/using-git-how-do-i-ignore-a-file-in-one-branch-but-have-it-committed-in-another 

Or 

We can simply add a different `.gitignore` file for the `develop` branch and remember to not push that file to the `master`

**Comment by mojoaxel** [comment]
[I don't think git has a solution for this.](http://stackoverflow.com/a/29583813/722162) :disappointed:

At the moment the best thing would be to ignore the dist folder in all branches. 
In the `master` branch we than add a commit that (re-)adds the dist folder by removing it from `.gitignore`.
We than simple rebase the master-branch before each release on the develop instead of merging the two!!
Because the master-branch normally has no changes (except this one) the rebase should be really easy. I have to think about that a little more...

**Comment by mojoaxel** [comment]
fixed with #2245

**Comment by Rikk** [comment]
What about people that would like to have a compiled js from develop branch? It would be great for testing.

**Comment by mojoaxel** [comment]
@Rikk Just build it yourself. It's really easy!

**Comment by Rikk** [comment]
When someone doesn't have any use for things like npm that person probably doesn't want to install and configure such build environments. And if it is so easy, you shouldn't have trouble keeping /dist folder updated after every commit.
