### ISSUE TITLE
create webpack example (project)

### ISSUE THREAD

**Issue by mojoaxel** [almende/vis#2186]
There should be an example or even an example project that shows how to integrate vis.js in a webpack project.

**Comment by mojoaxel** [comment]
Here is a simple example project that uses webpack to import vis.js:

https://github.com/mojoaxel/vis-webpack-demo

**Comment by wimrijnders** [comment]
OK, that's useful as a reference. Would a similar demo be possible for Ionic/Angular? I'm thinking of #3292.
