### ISSUE TITLE
Timeline not working properly when start date is : Day of the month without leading zeros  

### ISSUE THREAD

**Issue by krishnatejareddy** [almende/vis#2191]
Hi, 
I am new to Vis.js Timeline. 
I implemented timeline into my project but if start date passed as  "Day of the month without leading zeros" which means start day as "(new DateTime($timelineData[$i]->date))->format("Y-n-j H:i:s")"
day as "j" in this case consider a date will be like **2016-10-7 13:15:45** item is populating in 2016-10-1 00:00:00 but if pass like  (new DateTime($timelineData[$i]->date))->format("Y-n-d H:i:s") its working fine.. I can see item in 2016-10-07 place as required. 

Update: I checked with your examples: 
https://jsfiddle.net/krishna0796884/cua3p78s/2/ 

(correct me if I am wrong). 
Thanks 
krish

**Comment by mojoaxel** [comment]
Sorry, but I don't understand what your problem is. Can you please create a jsfiddle that shows your problem?

By the way: This seems not to be a vis.js problem. This kind of questions should be better asked e.g. on [stackoverflow](http://stackoverflow.com/questions/tagged/vis.js).

**Comment by krishnatejareddy** [comment]
Sorry for that, 
Can you go to 
https://jsfiddle.net/krishna0796884/cua3p78s/2/ 
start: '2013-04-9' but item is placing in April 1st 2013 place

**Comment by mojoaxel** [comment]
The date format is wrong. The leading "0" is missing. 
`'2013-04-9'`must be `'2013-04-09'` to get parsed correctly.
Or you can even use `new Date(2013, 4, 9)` instead.
