### ISSUE TITLE
Horizontal Scroll on mouse wheel 

### ISSUE THREAD

**Issue by ihatecodinglikeking** [almende/vis#2193]
Hi, 
Sorry for asking question here... 
Is there any way to do horizontal scroll on mouse wheel, 
I want to Zoom by ctrlKey and mouse wheel but if only mouse wheel i want to have a horizontal scroll. 

Can some one help on this? Its urgent...

**Comment by yotamberk** [comment]
funny you ask this, I'm going to submit a PR with this feature today =) 
it should be in the develop branch the next day or two

**Comment by ihatecodinglikeking** [comment]
thanks for your reply... 
Is there any immediate fix for it ? 
Or should  I wait for release ?

**Comment by yotamberk** [comment]
Ummm, we are working on a release the next few weeks. You can wait for the release or clone the project and build a dist file via the develop branch, and you'll have it sooner =)

**Comment by ihatecodinglikeking** [comment]
Thanks .... one some question :( 

I have a situation here.. that height is fixed and  stack:false so one or more items can place with in 5min time.. so its looking very  bad... So is there any way that I can make items overlap one by one with some top difference  kind off ?

**Comment by yotamberk** [comment]
Can you open another issue with an sample code/image with the problem?

**Comment by yotamberk** [comment]
You now have a new option for this `horizontalScroll`. You can see this in the `develop` branch
