### ISSUE TITLE
CSS Trick if two items has close timings and stack:false 

### ISSUE THREAD

**Issue by ihatecodinglikeking** [almende/vis#2194]
I have a situation here.. that height is fixed and stack:false so one or more items can place with in 5min time.. so its looking very bad... So is there any way that I can make items overlap one by one with some top difference kind off ?

example: https://jsfiddle.net/ihatecodinglikeking/a4t2fLcc/ 
Here  {id: 4, content: 'item 4', start: '2013-04-16 15:30:45'},
    {id: 5, content: 'item 5', start: '2013-04-16 15:40:45'},
has only 10mins difference. So I am missing item 4 from display to user. 

Is there any CSS trick to fix it (Height is fixed)

**Comment by yotamberk** [comment]
It sound the you don't need the `stack:false`. 
Why are you defining it as false?

**Comment by ihatecodinglikeking** [comment]
height is matter for me.. so I thought stack:false will save the height

**Comment by ihatecodinglikeking** [comment]
If items are overlapped its fine in my case... but if stack:true, item 4 is waiting for item5 to fix and then on top of its placing.. In my case I dont have that much space on vertical

**Comment by yotamberk** [comment]
Sorry but i don't see an easy way to do it. I'm trying to hack at it but it seems like you need some kind of stacking margin. It might be a cool feature request!

**Comment by ihatecodinglikeking** [comment]
@yotamberk so cont we achieve it right now ?

**Comment by mojoaxel** [comment]
@ihatecodinglikeking I don't understand. How do you want it to look? Can you please think about what you really want/expect, than we can see if it is possible.

> In my case I don't have that much space on vertical.

If height is a problem why not making all items smaller?

**Comment by ihatecodinglikeking** [comment]
@mojoaxel  thanks for you reply... 
![untitled](https://cloud.githubusercontent.com/assets/22953261/19562814/b53578c2-96ab-11e6-8a83-5384a484621c.png)

In pic I marked it... 
```
{id: 4, content: 'item 4', start: '2013-04-16 15:30:45'},
{id: 5, content: 'item 5', start: '2013-04-16 15:40:45'},
```

item 4 and item 5 has same start date so `stake:true` I need to scroll/drag vertically... so to prevent that I used `stake:false` , In this case I am missing item 4 as shown here : https://jsfiddle.net/ihatecodinglikeking/a4t2fLcc/ 

So I want something like shown in png... 

Can you help me on this ?

**Comment by yotamberk** [comment]
@ihatecodinglikeking Sorry, but it's not possible currently. You might want to add a Feature Request for an options of `stackOffset' or something of sort. It might be a good idea!

**Comment by mojoaxel** [comment]
> You might want to add a Feature Request for an options of `stackOffset' or something of sort. It might be a good idea!

I also looked into this issue but couldn't find a quick fix. And than forgot to answer...
A parameter "maxHeight" maight also be an option!?

**Comment by yotamberk** [comment]
@ihatecodinglikeking I've just found a way to do this: 
set in you options:
```javascript
 margin: {
      item: {
        vertical: -5
       }
  }
```

Works for you?
