### ISSUE TITLE
Can I load timeline with standard minor/major 

### ISSUE THREAD

**Issue by ihatecodinglikeking** [almende/vis#2198]
HI,

Currently timeline is trying to fit into give area with all items visible according to that minor and majors are fitting, But can I  standardized minor block to months, If I zoom, It has to work in current flow.   

So In this case

```
  var items = new vis.DataSet([
    {id: 1, content: 'item 1', start: '2011-03-07'},
    {id: 2, content: 'item 2', start: '2012-09-09'},
    {id: 3, content: 'item 3', start: '2013-04-18'},
    {id: 4, content: 'item 4', start: '2013-04-16 15:30:45'},
    {id: 5, content: 'item 5', start: '2013-04-16 15:40:45'},
    {id: 6, content: 'item 6', start: '2013-04-27'}
  ]);
```

I have one item 1  in 2011, item 2 in 2012 and rest in 2013. 
So I want to only 2013 first, on horizontal scroll I want to see remaining, Is there any way to do like this?

(correct me if I am wrong)

**Comment by yotamberk** [comment]
Not currently. but that is a very interesting Feature Request!

**Comment by ihatecodinglikeking** [comment]
@yotamberk  So no way for now ? I stuck at horizontal scroll...  #2193 but I am trying to work around it but nothing is helping  :(

**Comment by yotamberk** [comment]
Unfortunately not... I'm still working on the horizontal scrolling. Hold you horses, it should be merged by tomorrow =) - it will be in the develop branch so you can find it there when I'll reference the issue in the next PR.

**Comment by yotamberk** [comment]
@ihatecodinglikeking Hi again, I've added `horizontalScroll` to the `develop` branch.
I was wandering about this issue. Did you mean you want to see "2 items remaining" or something of that sort of text  (lets say on  top of the timeline time axis) if you're on the 2013 range and still have 2 items in 2011 and 2012?
If this is not what you mean, an illustration could be very useful =)

**Comment by mojoaxel** [comment]
@ihatecodinglikeking I'm not sure what you want. You can use `min` and `max` to e.g. only show items in 2013. The others can than be reached by scrolling horizontally. Is that what you are looking for?

**Comment by yotamberk** [comment]
@ihatecodinglikeking I'm closing this issue from inactivity. If you still think this issue is relevant and you'd like to elaborate what you mean in this issue, we will reopen this issue.
