### ISSUE TITLE
Couldn't Delete multiple selected Items at once

### ISSUE THREAD

**Issue by sambaheerathan** [almende/vis#2225]
Hi All,

When I select multiple items and try to delete them, onRemoveGroup is not fired but onRemove get fired even though I selected multiple items? Can someone tell me what I'm missing here ?

I have my timeline configuration like below 

```
var container = document.getElementById('visualization');
var options = {
    start: '2014-01-10',
    end: '2014-02-10',
    height: '300px',
    multiselect: true,
    showCurrentTime: true,
    groupEditable: true,
    onRemoveGroup: function (item, callback){
      alert("Group delete clicked");
    },
    onRemove: function (item, callback) {
    alert("Single Item clicked");
    }
};

var timeline = new vis.Timeline(container, items, options);
```

Any help appreciated 

Thanks,
Sam

**Comment by mojoaxel** [comment]
As descripted in the [docs](http://visjs.org/docs/timeline/) `onRemoveGroup` is fired if you delete a group, not multible items.

_Please read the [docs](http://visjs.org/docs/timeline/) and ask general problems at [stackoverflow](stackoverflow.com/tags/vis.js)._
