### ISSUE TITLE
Is the dot language don't support the struct? 

### ISSUE THREAD

**Issue by tedwong** [almende/vis#2236]
For example, I try to import this:

> `digraph structs {node [shape=record];struct1 [shape=record,class="meme",label="<f0> left|<f1> middle|<f2> right"];struct2 [shape=record,label="<f0> one|<f1> two"];struct3 [shape=record,label="hello\nworld |{ b |{<here> d is a very long string}| f}| g |h"];struct1:f1 -> struct2:f0;struct1:f2 -> struct3:here;}`

But the generate result is not correct. Is that have some limitations?

**Comment by yotamberk** [comment]
@tedwong I'm sorry but your question is very unclear... What are you refering to? What are you trying to accomplish?

**Comment by mojoaxel** [comment]
@tedwong The dot language itself is not in our scope! You can test our abilities [with our example](http://visjs.org/examples/network/data/dotLanguage/dotPlayground.html).
