### ISSUE TITLE
Fixed group width

### ISSUE THREAD

**Issue by Piohpizii** [almende/vis#224]
I need to link two timelines with groups, but the problem is, the scale of both time axis do not correspond the other one because of the length of group names. Therefore I need to set a fixed group width for both timelines. The option 'groupsWidth' was available in the previous library, but not in this one. I am quite new to Javascript and don't know how this should be implemented.

Thank you.

**Comment by 46mas** [comment]
I successfully fixed group width, but nestedGroup width is always 9.23px wider than group width. How can i fix nestedGroup width ? 

Thank you.
