### ISSUE TITLE
Is there a way to draw rects in network?

### ISSUE THREAD

**Issue by qubotong** [almende/vis#2240]
I find there is no way to draw rectangles in network even though they are popular. Is there any considerations stop you guys to implement that shape when drawing a node?

**Comment by Tooa** [comment]
Hi,

the `big box``[here](http://visjs.org/examples/network/nodeStyles/shapes.html) almost looks like a rectangle. Is that what you are looking for?

**Comment by yotamberk** [comment]
@qubotong I think what @Tooa showed is what you are looking for. If you're still not satisfied, please add a feature request

**Comment by qubotong** [comment]
@yotamberk As my understanding, the size of big box is decided by the labels inside it. What if I just need to draw a rect without any labels, or what if I need to add same size rects with different labels?

**Comment by qubotong** [comment]
@yotamberk could you please reopen this issue and modify the label to feature request? or do you prefer I add another issues refers to this one?

**Comment by EdAllonby** [comment]
Better late than never! We overcame this problem by setting a minimum width and height to a box shape using widthConstraint and heightConstraint. This allowed us to programmatically create a rectangle without needing label content.

http://visjs.org/examples/network/nodeStyles/widthHeight.html
