### ISSUE TITLE
Make customTime non-draggable

### ISSUE THREAD

**Issue by netbrothers-tr** [almende/vis#2249]
Have I missed a way of making a custom time non-draggable? I wish to add custom time bars to illustrate some limits (thresholds) but prevent the user from dragging them around.

**Comment by mojoaxel** [comment]
Just set `min`, `max` and `zoomable`:
```js
{
    min: "30.10.2016",
    max: "31.10.2016",
    zoomable: false
}
```

[Here](http://jsbin.com/gisatiy/2/edit?html,output) is an example.

**Comment by netbrothers-tr** [comment]
Hi @mojoaxel ! Thanks for taking your time to look into this. I didn't mean the whole timeline to be fixed and non-draggable but rather custom time objects (described in http://visjs.org/docs/timeline/#Methods as

> vertical bar representing a custom time

, see method `addCustomTime` for example) to be fixed and non-draggable. Is there any way to achieve this elegantly?

**Comment by mojoaxel** [comment]
I've looked into it and I don't see a way at the moment of disabling dragging for customTimes. I think this is something we really need and I will look into it. I hope I get it done for the upcoming v4.17 release.

I clean up this issue and change it to a feature-request...

**Comment by netbrothers-tr** [comment]
> I clean up this issue and change it to a feature-request...

Appreciate it very much. Thanks!

**Comment by yotamberk** [comment]
@mojoaxel I'm not sure I understand this feature request. You can add on the item itself `editable: false` and that will make that specific item non-draggable. Is this not what he needs?

**Comment by mojoaxel** [comment]
@yotamberk I had problems understanding it, too at first. The customTime feature adds something like a "marker" in form of a blue line over the timeline:
![image](https://cloud.githubusercontent.com/assets/600565/19999101/c3d9518e-a270-11e6-96da-a30b62f3389d.png)
This marker is always movable. I need this "markers"-feature in a project so I'm going to improve it in the next weeks.

**Comment by yotamberk** [comment]
ahhhhhhhhhh ok! sounds good

**Comment by yotamberk** [comment]
@netbrothers-tr  try adding;
``` css
.vis-custom-time {
    pointer-events: none;
} 
```

**Comment by netbrothers-tr** [comment]
@mojoaxel, thanks for the solution. Would this imply I can't have both draggable and non-draggable bars in the same timeline?

**Comment by mojoaxel** [comment]
That's true. You can't have both draggable and non-traggable custom markers at this time. Feel free to reopen this issue if you need this.
