### ISSUE TITLE
Timeline axis labels disappearing

### ISSUE THREAD

**Issue by aytech** [almende/vis#2251]
Hi, 
This might be a duplicate of #1393, but I can still reproduce the issue (v. 4.16.1). I've created a [bin here](http://jsbin.com/sezatos/edit?html,output).

You have to do a bit of fiddling to reproduce the issue:
1. Resize the width of the output window to make it as wide as possible. 
2. Click on "Run with JS"
3. Grab the far left of the timeline axis and drag it to the right.
At some point all the minor labels disappear.

This is also reproducible in the current examples page, e.g. on http://visjs.org/examples/timeline/other/localization.html. If you grab the far left of the axis and drag to the right as far as it will go, at some point the minor labels will disappear

Couple of screenshots:
Initial state:
![image](https://cloud.githubusercontent.com/assets/3247202/19890140/19855068-a039-11e6-84e0-bd4b399c7946.png)

Same screen, no minor labels:
![image](https://cloud.githubusercontent.com/assets/3247202/19890154/34099e08-a039-11e6-9c86-79737a93c597.png)

Update: I was not able to reproduce the issue in my fork, but after fetching from upstream the issue has appeared. So, probably a regression

**Comment by Tooa** [comment]
Can you test whether the issue also occurs in the 'develop' branch?

**Comment by aytech** [comment]
Yes, sorry I didn't mention, I was testing in develop branch. Now tested in master, the same result, the bug is there

**Comment by aytech** [comment]
Ok, I think I found the commit that introduced this: a9ca766af7d658f7fe42c5f35f2da382ea4e164a (Fixed #24: Implemented support for time zones (see examples/timeline/other/timezone.html)).
This was in v. 4.5.1, 4.6.0 was released with this bug already
I will try to debug, just don't know when yet, a bit tight on schedule, will have to downgrade for now.

**Comment by aytech** [comment]
Just a small note: console shows no errors/warnings when labels disappear

**Comment by mojoaxel** [comment]
@aytech Thanks for reporting this. In which browser does the problem occur?

**Comment by aytech** [comment]
@mojoaxel Hi Alex, so far tested on Chrome 54.0.2840.87 / Firefox 45.3.0 / IE 11 (11.06.36) / MS Edge

**Comment by mojoaxel** [comment]
OK, I can confirm this is a bug.

**Comment by itfourp** [comment]
Not sure this helps since it was mentioned in https://github.com/almende/vis/issues/1393, but this problem is related to the daylight saving time, when there should be more or less than 24 hours.
