### ISSUE TITLE
Issue with mousewheel zoom

### ISSUE THREAD

**Issue by mojoaxel** [almende/vis#2261]
I noticed problems with mouse wheel zoom in current develop branch.
Zoom is not possible at all (examples/timeline/interaction/limitMoveAndZoom.html) or seems to loose events (examples/timeline/other/localization.html).

This must be fixed before the v4.17 release because this was introduced since v4.16.1 :cry:

**Comment by yotamberk** [comment]
Looking at thisissue, I see the zoom does work but only if the mouse is on an item... Weird... Looking in to it.

**Comment by mojoaxel** [comment]
Fixed my @yotamberk with #2262
