### ISSUE TITLE
Graph not centering

### ISSUE THREAD

**Issue by JorricksTU** [almende/vis#2270]
After setting a custom width and height the graph is sometimes completely out of view.
Now after reading through the entire documentation I still have no idea how to fix this.
Can someone please provide me with an example?
I'm using the network code from the 'getting started'. http://visjs.org/docs/network/

**Comment by mojoaxel** [comment]
Could you provide a screenshot or something that shows what exactly the problem is, please.

**Comment by JorricksTU** [comment]
![image](https://cloud.githubusercontent.com/assets/20257392/20036888/7c9d5d28-a415-11e6-9bb4-6017b28581b5.png)

`<div class="regelschema-div an-outer-div" style="display:none; height:85%">
            <div class="row" style="height:100%;">
                <div class="regelschema col-md-9" style="height:100%;">
                    <div class="panel panel-default" style="height:100%;">
                        <div class="panel-body" style="height:100%;">
                            <div class="title">
                                <div class="title-text">Regelschema</div>
                                <div class="title-question">
                                    <span class="title-question-tooltip">Hier zie je de connecties binnen de vereniging.</span>
                                    <i class="icon ion-help-circled" aria-hidden="true"> </i>
                                </div>
                            </div>
                            <div class="content" style="height:calc(100% - 25px);">
                                <div id="mynetwork"></div>`

**Comment by mojoaxel** [comment]
@JorricksTU Sorry, I can not reproduce your issues. Maybe you can create a [jsbin](http://jsbin.com/hibuca/edit?html,output) that shows your problems!?

You also could try calling `network.fit()` after your dynamic layout has rendered.

**Comment by JorricksTU** [comment]
@mojoaxel I just realised something.. I set up the width in percentages as I wanted the screen to be dynamic.
However, in the start the div regelschema-div is hidden and I called network.fit() right after the document is ready. Therefore I called it too early, resulting in an unwanted result. I added a delay for the fitted command and it works way better now! Thanks for the help!
