### ISSUE TITLE
Cannot scroll page when zoomKey is enabled

### ISSUE THREAD

**Issue by matikucharski** [almende/vis#2273]
With newest release on timeline when I specify `zoomKey` or I set `zoomable` to false I cannot scroll page to bottom when mouse cursor is over timeline. The default scroll is `defaultPrevent`ed no matter what.
That wasn't the case with previous releases. Is there a way to allow page scrolling?

See here vis 4.17 (scroll not working): https://jsfiddle.net/matikucharski/6u5pz7jc/
And here previous 4.16 (scroll working): https://jsfiddle.net/matikucharski/6u5pz7jc/2/

I guess it has sth to do with `verticalScroll` and `horizontalScroll` options features.

**Comment by mojoaxel** [comment]
@matikucharski Thanks for reporting this.

**Comment by yotamberk** [comment]
I see the problem. I'll fix it this weekend

**Comment by mojoaxel** [comment]
fixed with #2302
