### ISSUE TITLE
3DGraph disappears when setSize() is called

### ISSUE THREAD

**Issue by Loreno10** [almende/vis#2274]
Hi, I've been experimenting with 3DGraph (bar-style).
It's been great, but i have one issue:
When I call graph.setSize(x, y) (for example graph3d.setSize('400px', '400px');) the graph disappears and i only see its background! In order to see the graph again, I have to move the camera with my mouse a little bit and the graph reappears again.
Here you can see what I just described: http://codepen.io/Loreno/pen/WGmJmz?editors=0010\
In the bottom I've called setSize. if you comment it out - the graph appears normally.

**Comment by wimrijnders** [comment]
OK confirmed. A fix is in the process.

In the meantime, as a temporary measure, you can call `graph.redraw()` right after the call to `setSize()`. This will redraw the graph immediately..

**Comment by Loreno10** [comment]
Yeah, I thought about the same thing, that's what I'm doing.

**Comment by wimrijnders** [comment]
:+1:
