### ISSUE TITLE
Offset in time axes synchronisation of a grouped timeline and 2d plots

### ISSUE THREAD

**Issue by superciccio14** [almende/vis#2276]
Hi there, I'm trying to sync two plots sharing time axes (a timeline and a 2d). I'm listening to `rangechange` and it seems working fine. But I noticed a strange constant offset between "linked" axes (you can see it in this plnkr http://plnkr.co/edit/3v33RSGuz7kzSUlsoH3k?p=preview).

Why is happening and how can I fix?

**Comment by itfourp** [comment]
The offset comes from the groups-list on the left side of the timeline. If both groups have the same width, the timelines will be in sync without any offset.
I'm not sure if there is an option to fox the width of the group. I've always been lucky enough to have very long group names that took care of that problem for me...

**Comment by superciccio14** [comment]
I have suspected something like that :(
