### ISSUE TITLE
Setting 'locale' for timeline doesn't work

### ISSUE THREAD

**Issue by almute** [almende/vis#2279]
Hello, 
for a timeline I have setup in config `locale: 'de'` - but all month are still displayed in English.
Even if I use `moment.locale` to setup the language, all month are still displayed in English. Testing with `alert (moment.month())` shows the month in the correct language.
Why doesn't the text change?

**Comment by mojoaxel** [comment]
Please check out the locale example: http://visjs.org/examples/timeline/other/localization.html

**Comment by almute** [comment]
I have already checked all examples. The examples are working but my timeline not. I did all the same way as in the examples. Is there something to consider? I use my timeline inside of a FileMaker WebViewer on Mac. All other settings are working - only setting the language not.

**Comment by almute** [comment]
Problem is solved: 
In my timeline (based on the example for groups) the vis.js was loaded before moments.js. When I first load moments.js it works.

**Comment by rexhxiao** [comment]
這個問題同樣發生在，如果你是使用 angular-cli ，並利用 typescript 進行 import {timeline} from 'vis' 時，vis 所使用的 momentjs 會因為載入順序( vis 為 vendor 先被載入時，判斷 window['moment'] 不存在，而使用內建的 momentjs )，導致同時使用import * as moment from 'moment' 與 vis 自身的moment，此時2者之間的設定各自不同
