### ISSUE TITLE
Timeline onUpdate no longer working in v4.17.0

### ISSUE THREAD

**Issue by jesalg** [almende/vis#2285]
I just upgraded to v4.17.0 and noticed `onUpdate` callback for the Timeline is not being triggered. Its not working in the example demo either: http://visjs.org/examples/timeline/editing/editingItemsCallbacks.html

**Comment by yotamberk** [comment]
Thanks for reporting this! Will be fixed!

**Comment by jesalg** [comment]
Great, thanks!
