### ISSUE TITLE
Timeline Date breaks on Daylight savings time

### ISSUE THREAD

**Issue by chubaka** [almende/vis#2288]
Hi,
I am using the timeline for a projects of mine and on daylight savings time Oct 30,2016 the timeline dates break...When scrolling it goes from Oct 29th to Nov 1...it skips Oct 30...

I also checked your demo here and found the same issue:
[http://visjs.org/examples/timeline/other/localization.html](url)

I scrolled back to Oct 29th  08:00 ( hrs)...The next day to the right is Nov 1st....It skips Oct 30...
Please, advise. Thanks.

**Comment by yotamberk** [comment]
Thanks for reporting! We noticed this problem in #2251.

**Comment by mojoaxel** [comment]
Closing as duplicate of #2251
