### ISSUE TITLE
Timeline display differently between Firefox and Chrome

### ISSUE THREAD

**Issue by pmfiebig** [almende/vis#2289]
Hi
I think visjs and the work you guys have done is amazing. I recently ran into a little problem.

These Timelines used to be identical on Firefox and on Chrome. Now it seems that Firefox does not display the full start and end date. Here are screen shots
This is how the Timeline looks in Chrome
<img width="1248" alt="screen shot 2016-11-09 at 6 30 31 am" src="https://cloud.githubusercontent.com/assets/852524/20141828/f884f3f0-a646-11e6-8c77-01bc3fbb66fa.png">

This is how the same Timeline now looks in Firefox
<img width="1250" alt="screen shot 2016-11-09 at 6 29 56 am" src="https://cloud.githubusercontent.com/assets/852524/20141827/f8833858-a646-11e6-9d46-728b6a850605.png">

Thanks for your help.

**Comment by mojoaxel** [comment]
@pmfiebig Thanks for reporting this. Could you maybe provide a [jsbin](jsbin.com) with your example?

**Comment by pmfiebig** [comment]
Thanks for the quick response. You can view jsbin here
http://jsbin.com/funipa/edit?html,output

It displays differently in firefox than chrome

**Comment by pmfiebig** [comment]
I figured out what the issue is. If I add a time to the date for example *2014-08-09 23:59:00* then Firefox fails. If I format the date like *2014-08-09* everything is good. I'm not sure why this recently changed. I guess that I can pass a date with time in a different format than Firefox will accept.

**Comment by yotamberk** [comment]
@pmfiebig interesting. Thanks for sharing! This might be something that will require a fix.

**Comment by mojoaxel** [comment]
> If I add a time to the date for example 2014-08-09 23:59:00 then Firefox fails. If I format the date like 2014-08-09 everything is good.

That sounds like a bug. Can we create a very simple jsbin that demonstrated the problem?

**Comment by yotamberk** [comment]
@pmfiebig Can you please supply a simple example so we can solve this problem?

**Comment by mojoaxel** [comment]
> Can you please supply a simple example so we can solve this problem?

There already is an example: http://jsbin.com/funipa/edit?html,output
But here all start dates have been changed to pure dates.

**Comment by mojoaxel** [comment]
I can not see any problems using a time in `start` or `end` in a simple example (Chrome and Firefox): http://jsbin.com/hewegin/2/edit?html,output

@pmfiebig Feel free to reopen this issue if you can provide a simple example that shows the problem.
