### ISSUE TITLE
Icon in Shape

### ISSUE THREAD

**Issue by pdugas** [almende/vis#2291]
I would like to be able to use a glyph icon (i.e. FontAwesome, Ion, etc.) overlaid on a standard shape node like dot or diamond.  The idea is to be able to color the underlying shape to represent the state of the object the node represents while using the glyph to represent the object type.  

I modified the _drawShape() method on the ShapeNode class to add the guts of the _icon() method from the Icon class.  Code below is working for me.  Setting icon.code on a node with shape set to dot, diamond, square, etc. gets the glyph inserted in the center using the border color for the glyph.

    _drawShape(ctx, shape, sizeMultiplier, x, y, selected, hover) {
      this._resizeShape();
 
      this.left = x - this.width / 2;
      this.top = y - this.height / 2;
 
      var neutralborderWidth = this.options.borderWidth;
      var selectionLineWidth = this.options.borderWidthSelected || 2 * this.options.borderWidth;
      var borderWidth = (selected ? selectionLineWidth : neutralborderWidth) / this.body.view.scale;
      ctx.lineWidth = Math.min(this.width, borderWidth);
 
      ctx.strokeStyle = selected ? this.options.color.highlight.border : hover ? this.options.color.hover.border : this.options.color.border;
      ctx.fillStyle = selected ? this.options.color.highlight.background : hover ? this.options.color.hover.background : this.options.color.background;
      ctx[shape](x, y, this.options.size);
 
      // draw shadow if enabled
      this.enableShadow(ctx);
      // draw the background
      ctx.fill();
      // disable shadows for other elements.
      this.disableShadow(ctx);
 
      //draw dashed border if enabled, save and restore is required for firefox not to crash on unix.
      ctx.save();
      // if borders are zero width, they will be drawn with width 1 by default. This prevents that
      if (borderWidth > 0) {
        this.enableBorderDashes(ctx);
        //draw the border
        ctx.stroke();
        //disable dashed border for other elements
        this.disableBorderDashes(ctx);
      }
      ctx.restore();

      // XXX  Added this block
      if (this.options.icon.code !== undefined) {
        var iconSize = Number(this.height) * 0.6;
        ctx.font = (selected ? "bold " : "") + iconSize + "px " + (this.options.icon.face || 'FontAwesome');
        ctx.fillStyle = ctx.strokeStyle;
        ctx.textAlign = "center";
        ctx.textBaseline = "middle";
        this.enableShadow(ctx);
        ctx.fillText(this.options.icon.code, x, y);
        this.disableShadow(ctx);
      }
 
      if (this.options.label !== undefined) {
        let yLabel = y + 0.5 * this.height + 3; // the + 3 is to offset it a bit below the node.
        this.labelModule.draw(ctx, x, yLabel, selected, 'hanging');
      }
 
      this.updateBoundingBox(x,y);
    }

**Comment by pdugas** [comment]
Hmm...  The colors aren't correct when set to something other than the defaults.  Looking for the fix.

**Comment by pdugas** [comment]
This version of that added block appears to be working for me.  YMMV

```
        if (this.options.icon.code !== undefined) {
          ctx.save();
          ctx.font = (selected ? "bold " : "")
                  + (Number(this.height) * 0.6) + "px "
                  + (this.options.icon.face || 'FontAwesome');
          ctx.fillStyle = selected ? this.options.color.highlight.border
                           : hover ? this.options.color.hover.border
                                   : this.options.color.border;
          ctx.textAlign = "center";
          ctx.textBaseline = "middle";
          ctx.fillText(this.options.icon.code, x, y);
          ctx.restore();
        }
```

**Comment by mojoaxel** [comment]
You can just use the unicode symbols e.g. from FontAwsome as `label` in you nodes:
Here is a working example: http://jsbin.com/hiqega/edit?js,output
![image](https://cloud.githubusercontent.com/assets/600565/20169388/8faa268e-a727-11e6-9a35-b017221c87e4.png)
Oh! To the wonders of unicode!

**Comment by pdugas** [comment]
That is pretty cool but it doesn't let me have a separate text label drawn below it. Should have mentioned that requirement.

**Comment by pdugas** [comment]
![image](https://cloud.githubusercontent.com/assets/710928/20175817/ae8630ee-a712-11e6-8210-905e0a1aec5d.png)

**Comment by pdugas** [comment]
I'll work on a fork and merge request if you'd like.  Would like a brief review of the proposed code change before I spend the time to get a build/test setup going.  I've only been editing the vis.js dist file in the npm package I pulled into the project.

**Comment by mojoaxel** [comment]
The only way I see to  achieve this is to use `shape: image`. There are multiple ways to do that:
1. Use colored [images](http://visjs.org/examples/network/nodeStyles/images.html) and labels.
2. Define your own icon-font that has a circle around each symbol and than use the [icon example](http://visjs.org/examples/network/nodeStyles/icons.html) together with labels.
3. Generate a simple [SVG-Image](http://visjs.org/examples/network/nodeStyles/HTMLInNodes.html) on the fly using fontawsome symbols with a circle around it.

**Comment by mojoaxel** [comment]
Here is an example using SVG-images: http://jsbin.com/hiqega/3/edit?js,output
![image](https://cloud.githubusercontent.com/assets/600565/20179188/306f1a8e-a755-11e6-8bf9-886dd370d3b9.png)

**Comment by mojoaxel** [comment]
@pdugas _By the way: Please use [stackoverflow](stackoverflow.com/tags/vis.js) next time! This is not a help forum! I had fun anyway..._

**Comment by pdugas** [comment]
What's wrong with the approach I took?  It's working and doesn't appear to be terribly invasive.
