### ISSUE TITLE
enter dates - ten digits & single digit

### ISSUE THREAD

**Issue by ssabba** [almende/vis#2294]
I write  [new Date(-37,0,1), ,"contents"], [new Date(3,0,1), ,"contents"], [new Date(53,11,1), ,"contents"],  [new Date(373,0,1), , "contents"],

In this case, BC37 & AD373 are no problems, but AD3 & AD53, they are not appear in timeline. 

What should I do? please help me.

**Comment by brichbe** [comment]
What you posted is not even valid JSON.

You need to provide a working example on http://jsbin.com

**Comment by ssabba** [comment]
hmm...I think they are valid type.

I tried examples in official homepage. 

I edited 'examples10_link_two_timelines' in 'http://almende.github.io/chap-links-library/timeline.html'
////////////////
  data1.addRows([
                [new Date(10,7,23), , 'Conversation<br>' +
                        '<img src="img/comments-icon.png" style="width:32px; height:32px;">'],
                [new Date(10,7,23,23,0,0), , 'Mail from boss<br>' +
                        '<img src="img/mail-icon.png" style="width:32px; height:32px;">'],
                [new Date(10,7,24,16,0,0), , 'Report'],
                [new Date(10,7,26), new Date(2010,8,2), 'Traject A'],
                [new Date(10,7,28), , 'Memo<br>' +
                        '<img src="img/notes-edit-icon.png" style="width:48px; height:48px;">'],
                [new Date(10,7,29), , 'Phone call<br>' +
                        '<img src="img/Hardware-Mobile-Phone-icon.png" style="width:32px; height:32px;">'],
                [new Date(10,7,31), new Date(2010,8,3), 'Traject B'],
                [new Date(10,8,1,12,0,0), , 'Report<br>' +
                        '<img src="img/attachment-icon.png" style="width:32px; height:32px;">']
            ]);
//////////////////////
'[new Date(10,7,23)' be the '1910,7,23' at timeline, NOT '10,7,23'.

**Comment by yotamberk** [comment]
@ssabba I'm not sure what you mean... Can you please supply a jsbin with the example that doesn't work?
