### ISSUE TITLE
The size of network box could be changed without depending on text

### ISSUE THREAD

**Issue by qubotong** [almende/vis#2298]
For now, the size of the box is depends on the text inside it. What if people want to show a hiearchical tructure graph with same size of rectangle nodes? What if some of nodes only have few words inside, but the size of it should be really big to reflect some visualization parameters like number of parents?

**Comment by mojoaxel** [comment]
@qubotong Please read the [docs](http://visjs.org/docs/network/nodes.html) !!
Additional to the label nodes also have a `value` and `scaling`.
See http://visjs.org/examples/network/data/scalingCustom.html

**Comment by qubotong** [comment]
@mojoaxel I was talking about the "box", as I know, the width and height of abox depends on its content, right? Can we just set a box to a specific width and length? What I really want is a rectangle node which can only get by box nodes for now.

**Comment by mojoaxel** [comment]
> Can we just set a box to a specific width and length?

You can set `scaling.label.enabled` to scale boxes (labels) by the nodes value: http://jsbin.com/damikat/1/edit?js,output

**Comment by mojoaxel** [comment]
@qubotong Please close this issue if your question is answered!

**Comment by mojoaxel** [comment]
implemented by @eymiha with #2385
