### ISSUE TITLE
Node unselectable

### ISSUE THREAD

**Issue by koukimetal** [almende/vis#2299]
Is it possible to make only nodes unselectable?
I can find unselectable both node and edge in interaction but can't find either option.

Another thing is about node color
color.background = '#D2E5FF'
color.highlight.background = '#D2E5FF'
but doesn't look same color.

thank you

**Comment by koukimetal** [comment]
I'm not sure it's a bug.
I made selectConnectedEdges false, but when I selected node, label of edges connecting the node became bold.

**Comment by koukimetal** [comment]
I'm also not sure it's a bug.
I can't select an edge whose id is 0.

**Comment by koukimetal** [comment]
I use https://cdnjs.cloudflare.com/ajax/libs/vis/4.17.0/vis.js

**Comment by Tooa** [comment]
> I made selectConnectedEdges false, but when I selected node, label of edges connecting the node became bold.

Cannot verify this issue. This works: `var options = { interaction:{  selectConnectedEdges: false }};`

> I can't select an edge whose id is 0.

This is a bug in `4.17.0`, which is already fixed in the `develop` branch (https://github.com/almende/vis/pull/2530).

**Comment by mojoaxel** [comment]
fixed by @lewisjb with #2530
