### ISSUE TITLE
Nested groups in timeline

### ISSUE THREAD

**Issue by roboslone** [almende/vis#2300]
Hi! I'd like to use nested groups in timeline, is there a way to do so?

If it's not possible right now, could it be a feature?
I don't know if implementing infinite depth is necessary, I would personally be happy with max depth of 2 (one child and one parent). Probably setting any parent group as item's group should not be possible.

**Comment by roboslone** [comment]
To clarify, this is what I want to see:
![1](https://cloud.githubusercontent.com/assets/1941275/20212582/095f6654-a815-11e6-93b0-dbf4e75ded2c.png)

**Comment by yotamberk** [comment]
I like this! I need this feature too! 
Are you working on this?

**Comment by roboslone** [comment]
>> Are you working on this?
Sorry, I'm afraid I can't contribute to source code, my JS skills are awful :( I could help with ideas/testing or something like that, though.

**Comment by yotamberk** [comment]
I hope I can get to this feature soon... I have a lot on my plate right now... I'll do my best

**Comment by roboslone** [comment]
@yotamberk, thank you so much!

**Comment by mojoaxel** [comment]
@yotamberk There are already `subgroups`. I think I have seen a timeline were somebody achieved something like this with subgroups.

**Comment by yotamberk** [comment]
I've done something like that in subgroups, but still missing the functionality asked for in this feature

**Comment by roboslone** [comment]
@mojoaxel, I've missed subgroups in docs, I'll try that.
Do you think subgroups should be mentioned in "Groups" section in [docs](http://visjs.org/docs/timeline/)?

Also, as @yotamberk mentioned, subgroups don't completely solve this issue, since they aren't displayed as normal groups.

**Comment by gerardp** [comment]
Please, make it collapsible, something like that:

![Uploading 095f6654-a815-11e6-93b0-dbf4e75ded2c.png…]()

**Comment by yotamberk** [comment]
@gerardp How do you expect the closed group to act? what Items should be shown in the parent? the sum of the items? all of the items of it's children?

**Comment by gerardp** [comment]
@yotamberk 
In my opinion, children are subtasks of the father. If I close the father only has to show the father's timeline, something similar to the gantt attached.

![896px-ganttchartanatomy svg](https://cloud.githubusercontent.com/assets/168353/20727083/5dabcbd2-b678-11e6-8f4b-576496ff2809.png)

**Comment by yotamberk** [comment]
So basically the parent should be the sum of all children but in merged items, agreed?

**Comment by gerardp** [comment]
Not necessarily, i can also imagine some case that does not:

![img3](https://cloud.githubusercontent.com/assets/168353/20728085/747b60c6-b67c-11e6-88ab-e4eb632fa0fa.png)

**Comment by yotamberk** [comment]
But the parent still must be somehow limited to not be smaller than the last item end time. That's why I'm not sure what rules must apply on this parent group. Do we allow the children items to be movable anywhere? does the parent adjust? or are the children limited by the parent?

**Comment by gerardp** [comment]
@yotamberk 
I would do it as simple as possible, without any limitation on the size of the father or the children. It does not matter that the children outnumber the father.
What is your opinion?

**Comment by yotamberk** [comment]
I think for a start I'll make the parent group independent of its children. Any kind of logic will have to be done by the user. Give me a few days. I'm on it.

**Comment by gerardp** [comment]
Great! thank you @yotamberk  !!

**Comment by mojoaxel** [comment]
fixed by @yotamberk with #2416

**Comment by roboslone** [comment]
Thanks!

**Comment by gerardp** [comment]
Thanks !!

**Comment by priyankabinani** [comment]
Hi, 

I was trying to keep all the nested groups collapsed by using showNestedGroups: false. But looks like this is not working. Any pointers?

Thanks!
