### ISSUE TITLE
Timeline 2D does not render an item in json

### ISSUE THREAD

**Issue by federicoco** [almende/vis#2308]
Hello I've my timeline in which I load dynamic data from db.
on the first image, one item is rendered wrong.
My json returned is 
evento_15:
Object content:"vomito verde"
end:"2016-05-08 14:00:00"
group:"23"
id:"evento_15"
start:"2016-06-06 14:00:00"
subgroupOrder:0

which is the one rendered wrong.Why is the width so small ?
In the second on IE8 there are graphics issue. can they be fixed?
I would be more interested in an answer for my first question
![vis2](https://cloud.githubusercontent.com/assets/22914696/20242638/1748b0a0-a936-11e6-8a71-785d3cf6c007.png)
![vis3](https://cloud.githubusercontent.com/assets/22914696/20242637/17480038-a936-11e6-976d-8cf640065037.png)

**Comment by yotamberk** [comment]
I think the problem is the time format. Try converting the time to ISOString and only then set the items for the timeline

**Comment by federicoco** [comment]
I've tried with ToIsoString , Date.parse and new Date....still the problem occurs

**Comment by yotamberk** [comment]
Can you supply a jsbin?

**Comment by federicoco** [comment]
https://output.jsbin.com/tipanunuza/

**Comment by yotamberk** [comment]
the example is not working for me =(

**Comment by yotamberk** [comment]
@federicoco I'm trying to understand this issue. Can you supply a working jsbin please? I can't help you otherwise...

**Comment by federicoco** [comment]
Hello, sorry to not answer but work kept me busy.
I found with other colleagues that it's from the database : if the field which hold start date & end date is set to not null, when you leave it empy, it will be set to `0000-00-00 00:00:00.`
Timeline does not know how to read `0000-00-00 00:00:00`, so that's why timeline Vis graphically render it like in the image.
Maybe could you suggest a pull request for making Vis Timeline handle  `0000-00-00 00:00:00` ?

`**FIX: set to null your field in database which keep the end date and start date**`

**Comment by yotamberk** [comment]
I don't there is a real reason to handle `0000-00-00 00:00:00` specifically. I think it's a data problem that needs to be handled by the user, like in your case. 
Glad to hear you've solved the problem =)
