### ISSUE TITLE
Timeline: verticalScroll bug 4.17.0 - the content area slides downwards

### ISSUE THREAD

**Issue by mast0r** [almende/vis#2312]
Hi, I've found a bug while using a new very cool parameter `verticalScroll : true`. If set to `true` and there is enough space so no scroll bar is rendered - the content area just "slides" to the bottom of the timeline:

![image](https://cloud.githubusercontent.com/assets/9842532/20266907/6f44f8ca-aa78-11e6-993c-1395f7bffea8.png)

Here is a jsfiddle: http://jsfiddle.net/Lkskqz9q/3/

**Comment by yotamberk** [comment]
Wow... that's a big one... Thanks for reporting! I'm on it!

**Comment by dboire** [comment]
Hi. 
Fun part is horizontalScroll have a totally inverted issue :D
work only on the crossed part
