### ISSUE TITLE
Timeline: onUpdate has no effect in 4.17.0

### ISSUE THREAD

**Issue by mast0r** [almende/vis#2314]
Hi, I've just tried the `onUpdate` in the new version 4.17.0 and got no feedback from the function. Does it work differently now?

Here is jsbin. Try to doubleclick any item...
http://jsbin.com/badahuxaba/edit?html,js,output

**Comment by Tooa** [comment]
This is a bug and was introduced with the 4.17.0 release. However, it is already fixed in the `develop` branch. For more information, see #2285. You may close the issue if the fix works for you. 

Best Uli

**Comment by yotamberk** [comment]
Fixed in #2304
