### ISSUE TITLE
Setting the italian locale not working in timeline Vis

### ISSUE THREAD

**Issue by federicoco** [almende/vis#2317]
hello i've saw the localization example on your site and after giving you the translation, I decided to set on it.
 ```
var options = {
            editable: true,
            width: '80%',
            locale: 'it'
}
```
even setting it, the locale is not changed and in the console, it doesn't display errors

**Comment by Tooa** [comment]
Hi,
it works in the [examples](http://visjs.org/examples/timeline/other/localization.html). Does it work when you only provide the locale property and remove the rest?

**Comment by federicoco** [comment]
yes, even taking out **editable** and **width** field, it does not change, look at the image i'm not joking
![visprobl](https://cloud.githubusercontent.com/assets/22914696/20309927/358d7a8a-ab4a-11e6-914f-41ffc6e3c5be.jpg)
![visprobl2](https://cloud.githubusercontent.com/assets/22914696/20309926/35898128-ab4a-11e6-90bf-42ddbfc130be.jpg)

**Comment by Tooa** [comment]
Do you have this line/lib included?

`<script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.1/moment-with-locales.min.js"></script>`

**Comment by federicoco** [comment]
no, I've added it now that you wrote, cleared cache and restarted gulp (the engine that uploads my frontend). It didn't change the locale

**Comment by Tooa** [comment]
Then you need to provide a **minimal** example of your code on [jsbin](jsbin.com).

**Comment by federicoco** [comment]
look, I've been able to reproduce the bug on jsfiddle with a basic example from your timeline : 
http://jsfiddle.net/e7uodse2/912/

**Comment by mojoaxel** [comment]
I imported the local support from moments.js and it seams to work: https://jsfiddle.net/e7uodse2/917/
Here is another axample: http://jsbin.com/guhufe/1/edit?html,js,output

**Comment by federicoco** [comment]
**If you encounter problems with locales, try these things** :
1) Clear Cache
2)If you use Gulp or something similiar to this,be careful that your import of moment-with-locale.js
    is not being rewritten
3)check for syntax mistakes (like you forgot a semicolon);
4) better use 'language' than "language" when you are defining the locale.
