### ISSUE TITLE
Bug in Timeline vis if integrated with Angular JS, Vis timeline rendered twice or more

### ISSUE THREAD

**Issue by federicoco** [almende/vis#2323]
hello,
just found this bug, don't know if it's a noob error or really a bug.
I will explain now the issue
**HTML**
```
<body ng-controller="mainCtrl">
<div id="footer" ng-controller="mainCtrl">
<div id="example-timeline"></div>
</body>

```
**Javascript**
```js
var ngApp = angular.module('ngApp', ['ngRoute','thatisuday.dropzone']).controller('mainCtrl', ['$scope', '$http', '$location', '$timeout', function ($scope, $http, $location, $timeout) {
$scope.init=function()
 { //code where you start your angular js app
       var container = document.getElementById('example-timeline');
// Create a DataSet with data 
var data = new vis.DataSet([{
    id: 1,
    content: 'First event',
    start: '2014-08-01'
}, {
    id: 2,
    content: 'Pi and Mash',
    start: '2014-08-08'
}, {
    id: 3,
    content: 'Wikimania',
    start: '2014-08-08',
    end: '2014-08-10'
}, {
    id: 4,
    content: 'Something else',
    start: '2014-08-20'
}, {
    id: 5,content: 'Summer bank holiday',start: '2014-08-25'}]);
// Configuration for the Timeline as JSON object
var options = {
    width: '100%',
    locale:'it',
    editable: true, /* this option means you can add or remove items by clicking on the timeline */
    margin: {item: 20}};
// Create a Timeline
var timeline = new vis.Timeline(container, data, options);
}
}
```
if you insert more than one time a div with ng-controller ="nameofController", the timeline gets rendered twice or more than twice (loop)

**Comment by yotamberk** [comment]
Can you please supply a jsbin? I've used it in angular and work a fine for me

**Comment by Tooa** [comment]
Just a guess since I cannot see where the `scope.init` is called: The controller is instantiated every time you attach it via `ng-controller`. Thus, the body of the controller is executed multiple times and the timeline is therefore created (and rendered?) multiple times. To give a more elaborate answer, we need a jsbin as @yotamberk mentioned.

**Comment by yotamberk** [comment]
@Tooa I bet you're right with your guess. I've been using timeline with angular and had a similar problem. It works fine for me now with no double rendering.

**Comment by federicoco** [comment]
So what do you think @yotamberk it is a real bug or just some noob error?if you want we can close the issue. Same for me now it works without problems (but a code different from the one supplied)

**Comment by Tooa** [comment]
@federicoco wouldn't call this a "noob error". All of us run into issues every day - especially when you are not used to a library. I'm glad it works for you now. Maybe you can share your (minimal) changes for others here. Someone might run into the same problem.

**Comment by federicoco** [comment]
Ok, so here is a Solution that I've reached so far : 
In angular you can define multiple controllers and multiple directives (the controllers must always be separated in single files, like separated class in separated files FYI),but you cannot inject two controllers into an html because even if the controllers could share the same scope, they would have different instances of the controller.
Angular does not allow that two isolated scopes applies to the same element in order to prevent erratic behaviour. so the only wrong code is the **html**
```
<body ng-controller="mainCtrl">
      <div id="footer" ng-controller="mainCtrl">
        <div id="example-timeline"></div>
</body>
```
Just choose : or you inject `ng-controller` in **body** tag or in another tag but not both

**Comment by yotamberk** [comment]
Cool. Good job!
