### ISSUE TITLE
large nodes overlapping in hierarchical mode

### ISSUE THREAD

**Issue by northwind11** [almende/vis#2326]
Can you please help with answer on question http://stackoverflow.com/questions/40610389/vis-js-large-nodes-overlapping-in-hierarchical-mode

Is it possible to have nodes in vis.js in hierarchical layout without overlaping on X axis?

I tried to add options:

    var options = {
        layout: {
            hierarchical: {
                direction: "UD",
                sortMethod: "directed"
            },
            physics: {
                solver: "barnesHut"
                ,barnesHut: {
                    avoidOverlap: 1
                }
            }
        }
    };

**Comment by mojoaxel** [comment]
@northwind11 You could try playing with `hierarchical.nodeSpacing`. But therefor physics must be off.

**Comment by mojoaxel** [comment]
Answered on [stackoverflow](http://stackoverflow.com/a/40663279/722162).
