### ISSUE TITLE
Vertical drag and drop needs to be horizontal first

### ISSUE THREAD

**Issue by 3xH** [almende/vis#2328]
Hi,

I want to be able to  move my groups, but the group drag and drop doesn't work when following a vertical path. It works fine only if I drag horizontally first.

![group_drag_and_drop](https://cloud.githubusercontent.com/assets/23527463/20396088/566e13ee-ace5-11e6-8014-1b69c32fd259.png)

Thanks for your help.

**Comment by yotamberk** [comment]
Thanks for reporting! I can confirm the bug. Will be fixed!

**Comment by mojoaxel** [comment]
this was fixed by @yotamberk with #2368

**Comment by 3xH** [comment]
Thanks a lot!
