### ISSUE TITLE
Timeline sava data

### ISSUE THREAD

**Issue by Clarence344** [almende/vis#2330]
Hi,

how can I save processed items on my timeline in a mysql database? for examaple with drag and drop or by edit the item which is already present in the timeline?

thanks

**Comment by yotamberk** [comment]
This should be implemented by saving the items you supplied the timeline. It should update the items you supplied so saving those items to the db is an options.
The other option is listening to `onUpdated`, `onAdd` and `onRemove` and manipulate the db with the item updated/added/removed. 
Does this answer your question?

**Comment by Clarence344** [comment]
thank you for the comment. I solve the problem with ajax:

` var options = {
    stack: true,
    itemsAlwaysDraggable: true,
    orientation: 'top',
	margin: 10,
	zoomMin: 1080000,
	zoomMax: 86400000,
	editable: true,  
        onMove: function (item, callback) {
			var group = item.group;
			
			$.ajax({
				 type: "POST",
                    url: "testforajax.php",
                    data:
					{ 
					event34: group
					},
                    success: function(data)
                    {
                        alert("success!");
                    }
				})
     		}
	};`

but I only want to edit the group, not the time. If I change the 

`editable: {
updateTime: false
}`

they do nothing, mhmmmm :)

**Comment by yotamberk** [comment]
So can we close this issue?

**Comment by Clarence344** [comment]
of course
