### ISSUE TITLE
Timeline: Can't zoom with mousewheel in CurrentTime

### ISSUE THREAD

**Issue by Jinkwon** [almende/vis#2336]
I attached this case's demo.
Can't zoom with mouse wheel in time indicator. (It was same current time and custom time)
It makes so hard to zoom and control it. I wanna make it to enable wheel event in time indicator as well. 

Is this bug or has any solution? :)

![mousewheel_status](https://cloud.githubusercontent.com/assets/1798916/20463658/81dbaee0-af7b-11e6-8522-1c6f45b45198.gif)

**Comment by mojoaxel** [comment]
A simple work around would be to disable event-catching for this element:
```css
.vis-current-time {
    pointer-events: none;
}
```

**Comment by Jinkwon** [comment]
@mojoaxel 
I don't think this is a complete solution. :0
Because this "pointer-events" codes even makes prevent customTIme's drag event.

**Comment by yotamberk** [comment]
Another workaround is add `z-index:1` to `.vis-panel.vis-center`. This will make the `customTime` draggable only on the time axis. I'm still trying to fix this... It's more difficult than I expected...

**Comment by Jinkwon** [comment]
@yotamberk Thanks!  👍
