### ISSUE TITLE
Timeline items don't propagate pan events.

### ISSUE THREAD

**Issue by EmanuelOverflow** [almende/vis#2338]
I'm emulating vertical scroll because I need to have on same timeline two sections on which the top section must scroll to show all items and the bottom one have to be fixed. I use pan events to simulate vertical scroll and all works fine while I drag blank area on timeline, unfortunatelly when I try to drag on vis-item it doens't work it emits only one panstart panend event. There is a solution to propagate the pan event from vis-item to background timeline?

Every item is built using templating and tables.

**Comment by yotamberk** [comment]
Thanks for reporting! 
It would be great if you could add a simple example of this so we can see it too and try fixing it.

**Comment by EmanuelOverflow** [comment]
Hi, I partially solved the problem. I reset dataset on each scroll action and if I'm scrolling on a element in the dataset it is cancelled and action binded with it is lost. I solved intercepting the event in panstart action getting its parent vis-group changing the target in the event to vis-group and emitting a new pan start using timeline.hammer.emit on the modified event.

It works well with mouse but doesn't work with touch events. I tried to emit touch events too but without success. Any suggestion?

**Comment by yotamberk** [comment]
It's a bit difficult to help when there is no example... It sounds hackish. If you get the vis-group parent, you can propagate more to reach the Range (vis-centerContainer) and change the target in the event there. Again, kinda hackish but possible.

**Comment by yotamberk** [comment]
@EmanuelOverflow I see this happens only when an item is selected and you try to drag vertically when starting on the selected item. 
An easy solution for this is simply making the items not editable. Does this work for you?

**Comment by EmanuelOverflow** [comment]
The item is not editable yet. The problem seems to be that mobile devices handles pan actions in different way, because actions are emitted but the behavior is different from desktop browser

**Comment by yotamberk** [comment]
@EmanuelOverflow is this still relevant?

**Comment by EmanuelOverflow** [comment]
Sorry, it is not relevant anymore. Thank you for your help!
