### ISSUE TITLE
Force item order inside of a group?

### ISSUE THREAD

**Issue by aseiford** [almende/vis#234]
My implementation of the timeline has various events being assigned different classNames. Is there some attribute similar to value, for items, that I can use, so that my items will always be stacked in a defined order? It seems that initially, they're ordered from top to bottom based on the order they're added into the dataSet. But as you scrub the timeline, and zoom in and out, events can move up and down inside of their group.

**Comment by josdejong** [comment]
There is now a configuration option `order` available since v3.11.0. See [35_item_ordering.html](http://visjs.org/examples/timeline/35_item_ordering.html).
