### ISSUE TITLE
Timeline items disappearing when using groups (_isGroupVisible bug)

### ISSUE THREAD

**Issue by shivpatel** [almende/vis#2345]
I've created a simple Plunker to consistently recreate the issue: https://plnkr.co/edit/SYI1dWuQeTObkLEZ1sPL?p=preview

- There are 3 groups, each with 50 items. All 150 items start on December 21 and end on a randomized date in the future.
- I have enabled verticalScroll in the options, so you can scroll vertically using the group column.
- Using the scroll zoom in the main column, set the date range to December 23 to December 24. A majority of the 150 items will exist in this range.
- Now using the vertical scroll in the group column, scroll to the bottom of the vis to see group 2 and 3.
- All items are now gone in group 2 and 3 (they should be displaying).

I was able to narrow the issue to the _isGroupVisible prototype (https://github.com/almende/vis/blob/88f14a0d42b8af38e0dcd7b9b7d95eaf0df86d67/lib/timeline/component/Group.js#L288). Looks like the conditional is incorrect/incomplete.

Temporary Solution: Manually overriding this function to always return true will get everything working for the time being. However, you'll take a performance hit as all items in the vertical direction are now left in the DOM instead of dynamically adding/removing them.

**Comment by yotamberk** [comment]
Thanks for reporting! We'll take a look at this

**Comment by yotamberk** [comment]
This is solved in the `develop` branch by #2334
