### ISSUE TITLE
One for the showcase

### ISSUE THREAD

**Issue by tsak** [almende/vis#2346]
http://sirius.modeselektor.com/

![siriusmodeselektor](https://cloud.githubusercontent.com/assets/1022521/20503608/47049d5c-b03b-11e6-8288-f0ce176b17f5.png)

**Comment by yotamberk** [comment]
Awesome! thanks!

**Comment by tsak** [comment]
Forgot to add some context:

Siriusmodeselektor was a collaboration of Siriusmo and Modeselektor - two electronic music acts. They played quite a few gigs in 2015 and I came up with the idea to use `Timeline` as the model for the site. I really liked the stacking of nodes when there are too many items in a given interval and that drove the design. The site shows both dates (yellow nodes) and images/videos (nodes with thumbnail). Initially it loaded data from a REST API but has since been made converted to load static JSON files.

**Comment by tsak** [comment]
Added a pull request #2354

**Comment by mojoaxel** [comment]
fixed with #2354
