### ISSUE TITLE
Is it possible to put same width for each step?

### ISSUE THREAD

**Issue by sk29110** [almende/vis#2347]
Is it possible to set up so that each step has 50px wide in timeline? I know by default the width of each step get adjusted depending on the windows size and data but I want to have the width to stay the same no matter the windows size is. I treid with 
```
var options = {
  timeAxis: {scale: 'hour', step:1}
}
```
It displays the way I want but width get adjusted as you change the widow sizes. If I have few hours timeline it works nicely but  time gets squished when I have few days of timeline

**Comment by yotamberk** [comment]
Unfortunately not a way I know... This can be a good feature request.

**Comment by sk29110** [comment]
After reading the doc a couple of times, I see there are options zoomMax, ZoomIn and when I set zoomMax and ZoomIn the same value it does similar thing is what we wanted. I just had to put the right number( I am not sure how people come up with number ) which was 80000000.

**Comment by yotamberk** [comment]
Good! Glad to hear you found a solution =) Can we close this issue?

**Comment by sk29110** [comment]
Thanks
