### ISSUE TITLE
Node overlapping with large labels

### ISSUE THREAD

**Issue by vcamaral** [almende/vis#2349]
![vis_nodes_overlapping](https://cloud.githubusercontent.com/assets/860466/20521417/573e5bac-b092-11e6-89d2-8b5e8fd71298.PNG)

How can I solve this problem?

**Comment by vcamaral** [comment]
@yotamberk can you help me?

**Comment by yotamberk** [comment]
Sorry but I'm not really strong with the network section... I deal mostly with the timeline... 
I think you can maybe have a max-width for a node (with overflow hidden and word-break). That should solve the problem. There might be some kind of min-margin between nodes, I simply don;t know to be honest

**Comment by mojoaxel** [comment]
@vcamaral  Use line breaks or `nodeSpacing`.

**Comment by mojoaxel** [comment]
duplicate of #2326
