### ISSUE TITLE
Cannot read property 'x' of null

### ISSUE THREAD

**Issue by ghost** [almende/vis#235]
I am getting the above error when rendering a network.  It occurs in the Edge.positionBezierNode function.  This seems to be caused by adding an edge for which there is no node, but I am not 100% sure.  I would like to see the option to fail gracefully or simply ignore edges that do not have nodes.  If you have any insight, please let me know.
### Error message from chromium

> Uncaught TypeError: Cannot read property 'x' of null vis.js:18021
### Stack Trace

```
Edge.positionBezierNode vis.js:18021
Network._createBezierNodes vis.js:16899
Network._addEdges vis.js:16216
edgesListeners.add vis.js:14885
DataSet._trigger vis.js:1680
DataSet.add
```

**Comment by ojotoxy** [comment]
I think this might be an issue again in at least 4.3.0.

**Comment by AlexDM0** [comment]
Could you make a jsbin to show this? I've made a lot of networks and haven't had this issue. 

Regards

**Comment by ojotoxy** [comment]
I tried making a small example but couldn't get it to happen. Very sorry. I've only gotten the error to happen within a fairly complex angularJS application. The stack trace clearly shows an error in vis.js, though.
This happens shortly after adding an edge to a nonexistent node. If I add all the nodes first, no error occurs.

Uncaught TypeError: Cannot read property 'x' of undefined_line @ vis.js:31872
_drawLine @ vis.js:31057
drawLine @ vis.js:31047
draw @ vis.js:30425
_drawEdges @ vis.js:34820
_redraw @ vis.js:34697
(anonymous function) @ vis.js:34655

**Comment by AlexDM0** [comment]
These are dynamic smooth curves? Are both nodes non existent?

**Comment by ojotoxy** [comment]
Smooth curves are turned off. At least one node exists.

**Comment by AlexDM0** [comment]
Off as smooth:false? Could you share your options?

**Comment by ojotoxy** [comment]
Here's my options.

edges: { smooth: false },
                             nodes: { shape: "box"},
                             width:  '500px',
                             height: '500px',
                             physics: {barnesHut: {gravitationalConstant: -20000, centralGravity: 1.35, springLength: 500, springConstant: 0.0425, damping: 0.3}}

Each node is created like this ( I stuff some extra properties... didn't seem to be a factor.) :
node = {id: entity.id, entity:entity}
nodes.add(node)

Each edge is created like this:
edge = { id: relation.id + 1000, from: entity.id, to: relation.target_entity_id, value: relation.value, width: relation.value, color: color, relation_class: relation_class };
edges.add(edge)


The data is added like this:
For each entity:
	create and add the node
	for each edge that it needs
		create and add the edge (its destination might not exist)
	
(I know this might not be very efficient!)
