### ISSUE TITLE
Network graph - broken lines edges and arrow color

### ISSUE THREAD

**Issue by chenko47** [almende/vis#2355]
Hey, two issues around here in the network graph : 

1. How can I set network graph edges as broken line ? (not dash or rounded, like some chart flows that not a straight line):
.................... (item2)
(item) **____/**
2.How can I custom the middle arrow? I would like to add some background color, border radius and so .

Thanks.

**Comment by mojoaxel** [comment]
@chenko47 Can you please provide a drawing/screenshow or something that clarifies what you want to achieve.!

**Comment by chenko47** [comment]
![eg](https://cloud.githubusercontent.com/assets/16509369/20563106/b708eb44-b18f-11e6-8b9f-e463896469e9.png)
In short- something like this

**Comment by mojoaxel** [comment]
> 1. How can I set network graph edges as broken line?

Sadly this is not possible at the moment. See also [here](
http://stackoverflow.com/questions/39096205/family-chart-with-horizontal-and-vertical-line-connectors-using-vis-js).

> 2. How can I custom the middle arrow? I would like to add some background color, border radius and so.

[Here is an example](http://visjs.org/examples/network/edgeStyles/arrows.html) on how to use arrow in the middle of the edge. You can also change the color of the edge but no other fancy styles.

So, in short: This is not possible at the moment.

**Comment by chenko47** [comment]
Thank you for the fast answer !
There is any way that can I contribute and implement that ? any suggestions where to start and so on..
or it will be too complicated ? 

thanks

**Comment by mojoaxel** [comment]
> There is any way that can I contribute and implement that ?

I think the new arrow option would not be that hard to implement. You would propably need a [new type of ending](https://github.com/almende/vis/blob/develop/lib/network/shapes.js#L211).

The angeld edges on the other hand would require a new impementation based on [EdgeBase](https://github.com/almende/vis/blob/master/lib/network/modules/components/edges/util/EdgeBase.js). I accept that to be super complicated.
