### ISSUE TITLE
Add pointer positions to zoom event

### ISSUE THREAD

**Issue by yoavdamri** [almende/vis#2356]
Hi, 

currently zoom event  properties include the scale and the direction.
it will be very useful, if the pointer position will be added to.

the change is very simple to implement.
in vis.js file, at the end of the "zoom" value function, 
change it to:
if (scaleOld < scale) {
            this.body.emitter.emit('zoom', { direction: '+', scale: this.body.view.scale**, pointer: pointer** });
          } else {
            this.body.emitter.emit('zoom', { direction: '-', scale: this.body.view.scale**, pointer: pointer** });
          }

Thanks.

**Comment by yotamberk** [comment]
@yoavdamri Are you planning to submit a PR with this addition?

**Comment by yoavdamri** [comment]
thanks @yotamberk.
DONE!

**Comment by yotamberk** [comment]
Closed with #2377
