### ISSUE TITLE
Unsure why I need to build vis

### ISSUE THREAD

**Issue by arvindpdmn** [almende/vis#2358]
The readme file says to build `vis` I have to do the following:
```
$ cd vis
$ npm install
$ npm run build

```

I'm new to using `npm`. I'm not sure why the build is required. I did a clone of the repo. I am able to open the examples in my browser without doing any such build. BTW, I haven't installed `npm` on my Windows 10 laptop.

**Comment by mojoaxel** [comment]
@arvindpdmn You don't have to build the library if you just want to use it. Building is just needed if you want to make changes to the source code of vis.js.
If you download the current [release](https://github.com/almende/vis/releases) you can use the pre-built files in the `dist` folder.
