### ISSUE TITLE
Editing groups

### ISSUE THREAD

**Issue by almute** [almende/vis#2365]
Hi,
is there also a function for editing the groups similar to 
timeline.on('select',  function (properties){} 
using which I can edit the entries (items)?

Thanks, Almute

**Comment by yotamberk** [comment]
Hi @almute, There is no way to do so yet. It's a good feature request though.
A workaround in the meantime could be making the group a groupTemplate with an html element containing an `onClick` event receiving the groupId  and filtering the items belonging to this groupId.

**Comment by almute** [comment]
Hi @yotamberk, thank you for responding. 
I do not have so much experience with HTML and JavaScript, so I unfortunately have no idea how I can implement this.
I use Timeline in a Webviewer in FileMaker. What I want to achieve is that with a click on a group a FM script is started. For the items I got it working.

**Comment by yotamberk** [comment]
Just so I'm clear on this, you want to catch an event that when you click a group, you receive the group properties (group id, name and items that belong to that group)?

**Comment by almute** [comment]
Yes, I want to catch an event when clicking on a group. But I only need to receive the group ID of this group. All other properties are then available for me in my FileMaker database.

**Comment by yotamberk** [comment]
Add this: 
``` javascript
document.getElementById('myTimeline').onclick = function (event) {
  var props = timeline.getEventProperties(event)
  console.log(props);
}
```
The props should contain the group properties when clicking anywhere in the timeline.

**Comment by almute** [comment]
I have tried, but this doesn't work. I also have add an alert to be sure. Nothing happens.

**Comment by almute** [comment]
I have changed the ID to look for to 'visualization'. This is the only ID used in my html. 
Now I get a message:
object Object
But it has no valid information.

**Comment by yotamberk** [comment]
Ummm can you add a jsbin? It works for me fine.
 The props don't contain the groupId. Only the group content btw.

**Comment by almute** [comment]
Sorry, what is a jsbin?

**Comment by yotamberk** [comment]
https://jsbin.com/?html,js,output

basically sharing code to check examples and bugs. copy paste the relevant sections and share your code so I can see if something you're doing is causing the `[object object]`

I've tried what I suggested on one of the website's examples and works fine, so I think something in your implementation is not correct.

**Comment by almute** [comment]
I don't really understand what to do in jsbin. Is there another way to provide you with mit html?
As I already said - I'm not a programmer, I only know to work with FileMaker and a little bit with html.

**Comment by almute** [comment]
I have tried
document.getElementById('visualization').onclick = function (event) {
  var props = timeline.getEventProperties(event)
  console.log(props);
  alert (props);
}
in your group example and I'm getting "object Object" too.

**Comment by yotamberk** [comment]
try switching `alert(props);` with `alert (JSON.stringify(props));`

**Comment by almute** [comment]
Perfect. Now it is working and I'm sure that I will get this connected to my FileMaker database. 
Thank you for providing such a useful timeline solution!
