### ISSUE TITLE
Width/height options for network elements

### ISSUE THREAD

**Issue by eymiha** [almende/vis#2384]
Nodes should have minimum and maximum widths. The node's label should be able to be right- and left-padded if smaller than the minimum, and label's lines should be able to be broken on spaces if larger than the maximum.

Edges should have maximum widths. The edge's label's lines should be able to be broken on spaces if larger than the maximum.

Nodes should have minimum heights. The node's label should be top- and bottom- padded if smaller than the minimum. An alignment flag should be available to top-, middle- or bottom-justify the label when this occurs.

**Comment by mojoaxel** [comment]
implemented by @eymiha with #2385
