### ISSUE TITLE
Data not displaying when i set horizontal scroll bar

### ISSUE THREAD

**Issue by gigglegirl** [almende/vis#2387]
Hi , 

I want the data to be displayed when scrolled horizontally , i have added property "overflow-x : scroll "in css file.
It is displaying data when i drag or mousewheell , but not when horizontally scrolled.
Please tell how can i implement this feature.

Thanks

**Comment by yotamberk** [comment]
Hi @gigglegirl can you please add a jsbin so I can see your example?

**Comment by gigglegirl** [comment]
hi @yotamberk ,  I realised that my timeline is not able to redraw timeline when i scroll it horizontally (correct me if i am wrong) .

So if there will be a way to fire an event (which gets fired on mousewheel or drag and drop)which redraws timeline when scrolled horizontally  may help in implementing horizontal scroll bar .

Thanks

**Comment by gigglegirl** [comment]
and i have one more question , we are firing following function on click of left or right button( Link : "http://visjs.org/examples/timeline/interaction/navigationMenu.html").

 function move (percentage) {
        var range = timeline.getWindow();
        var interval = range.end - range.start;

        timeline.setWindow({
            start: range.start.valueOf() - interval * percentage,
            end:   range.end.valueOf()   - interval * percentage
        });
    }
if i try firing above function on scroll of horizontal scrollbar , will it work??

**Comment by yotamberk** [comment]
Yo can try firing a `timeline.setWindow({... })` as well in `timeline.addEventListener('mousewheel',...)` or maybe `scroll` event...
That might be a good workaround.

**Comment by mojoaxel** [comment]
@yotamberk Is this a duplicate? If so from what?
