### ISSUE TITLE
How to know on which subgroup the item has been placed

### ISSUE THREAD

**Issue by federicoco** [almende/vis#2390]
hello, I was looking for the subgroup editing demo.
If I have to know that item1 has been moved from subgroup bar to subgroup foo, how can I achieve it ?

**Comment by yotamberk** [comment]
Unfortunately it's not possible yet =(

**Comment by yotamberk** [comment]
@federicoco After thinking about this more, the only way I see to do this is by doing this with on item update event. You will have to update the item to have a subgroup corresponding to the mouse position with "what", get the item, and add its subgroup to your item. 
Is this clear?

**Comment by yotamberk** [comment]
@federicoco I'm closing this issue. If this is still unclear, please reopen this issue and I'll help more
