### ISSUE TITLE
Add network Edge labels to physics repulsion

### ISSUE THREAD

**Issue by dockstreet** [almende/vis#2392]
Is it possible to add the labels to the physics so nodes or other edges would not overlay the text? In particular for a hierarchy?

**Comment by dockstreet** [comment]
This a duplicate of https://github.com/almende/vis/issues/1964

**Comment by mojoaxel** [comment]
> This a duplicate

@dockstreet A duplicate of which issue?

**Comment by dockstreet** [comment]
duplicate of 

https://github.com/almende/vis/issues/1964
