### ISSUE TITLE
Italian locale not setting....Again

### ISSUE THREAD

**Issue by federicoco** [almende/vis#2397]
hello,
sorry to re-open this issue but i'm having again this issue :
I've included in my **html**
`<script src="/bower_components/moment/min/moment-with-locales.min.js"></script>`
in **main.js**
  options = {
            editable : false ,
            locale : "it_IT" ,
            width : '100%' ,

options is a global variable never modified.
![italianlocale](https://cloud.githubusercontent.com/assets/22914696/20837063/9d86c668-b8a2-11e6-9f1d-f55a480dce9e.png)
![libraries](https://cloud.githubusercontent.com/assets/22914696/20837062/9d86a61a-b8a2-11e6-965d-c60a28cea656.png)

**Comment by yotamberk** [comment]
Add to the options - `moment:moment'

**Comment by federicoco** [comment]
not working, it just continue to `print WARNING: options.locales['it_IT'] not found. See http://visjs.org/docs/timeline/#Localization` , flushed cache and cookies

**Comment by Tooa** [comment]
Does it work with locale `it` instead of `it_IT`?

**Comment by federicoco** [comment]
With it or it_IT , this is the output : 
![timelinviscrash](https://cloud.githubusercontent.com/assets/22914696/20839053/5c222b28-b8ab-11e6-850c-f7a7a6b87f32.png)

the only month in italian is Ottobre 2016

**Comment by mojoaxel** [comment]
@federicoco moment.js must be loaded before vis.js

**Comment by federicoco** [comment]
Sorry for not answering, thank you @mojoaxel this helped me to fix the problem. Thank you everyone
