### ISSUE TITLE
Firefox bug: Update style of an edge inside a dynamic edges DataSet to 'dash-line'

### ISSUE THREAD

**Issue by TjWallas** [almende/vis#241]
When updating the style of an edge inside an edges DataSet to 'dash-line' in firefox, the entire view disappears.

###### Steps to reproduce
1. Open firefox
2. Open developer's console in firefox
3. Navigate to this visjs example: http://visjs.org/examples/network/16_dynamic_data.html
4. In the developer's console, try this:
```javascript
edges.update({id: 1, style: "dash-line"})
```
###### Expected behaviour
The intended edge style should change to dashed while the entire graph remains intact

###### Actual behaviour
The intended edge style indeed changes to dashed. However all the other elements inside the graph disappear.

**Comment by AlexDM0** [comment]
Hi,

A fix for this has been pushed to the develop branch. Thanks for letting us know!

Regards,

Alex

**Comment by TjWallas** [comment]
:+1:
