### ISSUE TITLE
vis network isn't showing properly in bootstrap modal

### ISSUE THREAD

**Issue by KunalAppensure** [almende/vis#2413]
vis network isn't showing properly in bootstrap modal even if I have provided height and width of modal ,
network doesn't fits in modal its coming large and doesn't appear as whole in bootstrap modal .
Is anyone showing network in bootstrap modal , please help and provide one example if possible.
Thanks

**Comment by Tooa** [comment]
Can you provide us with a minimal example of your problem [here](http://jsbin.com/)? However, I guess the problem is not related to visjs.

**Comment by KunalAppensure** [comment]
[http://jsbin.com/qitumazamu/edit?html,output](url)

**Comment by Tooa** [comment]
You missed to post the link, right?

**Comment by KunalAppensure** [comment]
please look into this
http://jsbin.com/pexarigefa/1/edit?html,output

**Comment by mojoaxel** [comment]
@KunalAppensure You can not draw the network as long the modal is not visible yet. because it has no position. Use a modal-event to trigger the network draw: http://jsbin.com/famenic/2/edit?js,output
Giving the modal-body a fixed size and play around with css might also work.
