### ISSUE TITLE
Timeline onMove callback

### ISSUE THREAD

**Issue by thomasbarone** [almende/vis#2422]
There is a problem with the onMove callback function which causes the dragged item to return to the wrong group when using `callback(null)`.

This bug seems to only occur when the timeline height is restricted so to enable vertical dragging between groups.

I have briefly looked into it, and I believe it may have something to do with the ItemSet._onDragStart() method being called twice. I have included console messages in the 2 following jsfiddles to indicate this. Note that in the fiddle without the restricted height, onDragStart does not call twice and the bug does not occur.

Steps to reproduce bug:
1. Go to the fiddle with the restricted height
2. Open up the javascript console
3. Drag and drop an item onto the **DROP ONTO ME** group
4. May take a couple of tries, but the item should return to the wrong group
5. Also note the console messages indicating the onDragStart method being called twice for each drag operation

[Fiddle with restricted height](https://jsfiddle.net/z9xddu76/2/)

[Fiddle without restricted height](https://jsfiddle.net/war6thLs/1/)

**Comment by yotamberk** [comment]
Hi @thomasbarone, The fix is easy. All that is missing is adding 
`if (this.touchParams.itemIsDragging) { return; }` 
to the beginning of `ItemSet.prototype._onDragStart` function. I'll add a PR with this fix.

**Comment by thomasbarone** [comment]
Thanks for the quick fix @yotamberk!
