### ISSUE TITLE
CodeClimate

### ISSUE THREAD

**Issue by mojoaxel** [almende/vis#2423]
We are thinking of integrating [CodeClimate](https://codeclimate.com/github/almende/vis) into this project. 
Actually the first steps are already done with #2360 #2395 and #2411.

CodeClimate now uses Tools to find ways to improve the code. You can find [sugestions for improvment here](https://codeclimate.com/github/almende/vis/code).

Let's now discuss if we want such a tool and what "rules" make sense for us!

**Comment by mojoaxel** [comment]
I'm not sure about the eslint rule `This function has too many statements. Maximum allowed is 30.`. Maybe we could increase it to 100 or disable it!?

**Comment by mojoaxel** [comment]
The eslint rule `Function X' has a complexity of Y.` makes also not much sense. To fix that we would have to break functions up into smaller functions. This makes no sense it many cases. Should we increase allowed complexity or disable the rule altogether?

**Comment by yotamberk** [comment]
> I'm not sure about the eslint rule This function has too many statements. Maximum allowed is 30.. Maybe we could increase it to 100 or disable it!?

yes... I don;t like that rule in general... 

>The eslint rule Function X' has a complexity of Y. makes also not much sense. To fix that we would have to break functions up into smaller functions. This makes no sense it many cases. Should we increase allowed complexity or disable the rule altogether?

Agreed.

**Comment by yotamberk** [comment]
Hey @mojoaxel , I think this codeclimate is not very useful... I don't find it useful at all. I've tried taking its advise and it simply isn't relevant. I think we should remove it.

**Comment by mojoaxel** [comment]
We should keep an eye on this and improve the usability for us in the future.

**Comment by mojoaxel** [comment]
I say code-climate looks good so far: https://codeclimate.com/github/almende/vis/trends

**Comment by mojoaxel** [comment]
There are still some issues:
https://codeclimate.com/github/almende/vis/issues

Feel free to tackle tham at any time!
