### ISSUE TITLE
Timeline support for higher resolution times

### ISSUE THREAD

**Issue by Spannella** [almende/vis#2424]
I have some use cases where I want to timeline out a series of events that occurred on a system. The entire process is less than 1 millisecond. I was thinking of either a way to raise the resolution that is supported or create a custom axis since applications needing such fine resolution likely do not need to go out as far as a month or a year. 

If you have advice how I could define my own custom axis let me know.

Thanks

**Comment by yotamberk** [comment]
Hi @Spannella, in terms of limiting the zoom, you have a `zoomMax` option you can limit the user. 
In terms of having items smaller than 1ms, we don't support smaller resolution. There is a feature #92 that needs implementing to represent the axis as numeric numbers and not numbers. Once that is implemented, we can achieve what you're looking for.
