### ISSUE TITLE
Moment library

### ISSUE THREAD

**Issue by primozs** [almende/vis#2428]
Is it possible to replace it or remove it?
Is it possible to make it smaller, by using just parts of it?
Cheers

**Comment by yotamberk** [comment]
You can make a custom bundle https://github.com/almende/vis#example-2-exclude-external-libraries
but you will need to include your own momentjs version.

**Comment by primozs** [comment]
@yotamberk Hi, Thank you for your answer. Yes I know this. But I find moment a bit big library compared to alternatives.

**Comment by yotamberk** [comment]
Unfortunately vis depends on momentjs and does not support alternatives for now. 
What alternatives were you considering?

**Comment by primozs** [comment]
I started using this a while ago. https://github.com/taylorhakes/fecha

**Comment by primozs** [comment]
When I am building the application I require only Graph2d and in webpack stats - electrify it seams moment has 429kB with all locales and vis deps 523kB. It does not seam like I would have dependencies duplicates.

**Comment by primozs** [comment]
I know this is not exactly the right place to open this issue but it is still related.
I made example webpack2 project where from moment you require just one function but you get the whole moment with all the locales. https://github.com/primozs/webpack2-local-modules

Maybe anybody here knows how to split moment with locales for each locale into a separate file?
Cheers

**Comment by primozs** [comment]
ok, one option is this

in plugins
new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/), // Ignore all optional deps of moment.js
