### ISSUE TITLE
mousedown mouseup not working on vis

### ISSUE THREAD

**Issue by farso92** [almende/vis#2429]
hi i have a problem with the use of mousedown and mouseup event in vis timeline....this is a simple example of my code....(the timeline is inside the div visualization)

$("#visualization").on("mousedown", function1);
     function function1(e) {
     console.log("mouseDown");
};

the strange thing is that click event works fine and that 1 month ago mousedown events works fine too.
I don't know what do because mousedown and click are differente event and i can't use mouseup with click....please help me to figure out

**Comment by Tooa** [comment]
Maybe related to https://github.com/almende/vis/issues/2421. @yotamberk can you have a look at this too?

**Comment by yotamberk** [comment]
I'll try it out today\tomorrow

**Comment by farso92** [comment]
nobody can help me?

**Comment by yotamberk** [comment]
I think an `event.stopPropagation` is can using the problem. I dont have the time right now to investigate this further. I need a few days to get to it ...

**Comment by farso92** [comment]
i tried to use it but nothing change...i noticed an interesting thing: only the left click doesn't work, if i click with right button mousedown event works...it is very strange

**Comment by yotamberk** [comment]
@farso92 I noticed that the docs don't include `mousedown` and `mouseup` events (http://visjs.org/docs/timeline/#Events)  - which also means that this isn't supported yet.
Luckly for you, I've added a PR now ( #2473) that supports the requested events. 
Enjoy! 
It will be available in the next version update (v4.18.0) or in the `develop` branch once it is approved and merged.

**Comment by farso92** [comment]
thank you so much...that's perfect

**Comment by byalekzzz** [comment]
Already implemented selection zooming and now waiting for those mouse events to be available. Hope soon and thanks a lot!

**Comment by mojoaxel** [comment]
@yotamberk fixed this with #2473
