### ISSUE TITLE
[timeline] item text doesn't stay close to its box

### ISSUE THREAD

**Issue by carueda** [almende/vis#243]
![image](https://cloud.githubusercontent.com/assets/556505/3911316/19954380-2320-11e4-97c3-95d200b0e99a.png)
- item has `text-align: center` (or `right`) for is `div.range` class
- item gets partially hidden on the left while dragging or zooming
- item's text starts moving to right as long as part of the item box is still visible 

![image](https://cloud.githubusercontent.com/assets/556505/3911405/f9352014-2320-11e4-8fcf-f8f04ff7e488.png)
- so far so good; however, the text starts getting too far apart from its box

![image](https://cloud.githubusercontent.com/assets/556505/3911330/36712140-2320-11e4-8a00-888dfe1b3de7.png)

(vis 3.1.0)

**Comment by SirNeuman** [comment]
Is there a way to turn of the sliding content in a range object? I've been trying to get it so the content doesn't slide out of the box when zooming in and out and while sliding, but it's just been causing more problems than it's worth, and I'd like the content to just be centered at all times inside the range object.
