### ISSUE TITLE
How to use epoch for visible range in VisTimeline

### ISSUE THREAD

**Issue by VivekTodur** [almende/vis#2430]
How to use epoch as visible range for vis timeline.
Instead of date min/max range, can I set epoch directly, But while displaying epoch should get transform and display in human readable form.

Is there way which I can achieve...

instead of  [min: new Date(2013, 3, 15) | max: new Date(2013, 3, 30)] to something like [min: new epoch(1481282997)]

Thanks,
Vivek

**Comment by yotamberk** [comment]
I'm not sure what's the difference. Isn't epoch another format of time?

**Comment by VivekTodur** [comment]
Yeah, That's ture. But when I was using like this,
			min: new Date(1365724800),                // lower limit of visible range
			max: new Date(1483142399),                // upper limit of visible range
So it was not working. 

Epoch needs to be converted and did using http://momentjs.com/ plugin.. Working like charm now...

Thanks,
Vivek
