### ISSUE TITLE
Why the 'value' of the nodes Module work unnormal?

### ISSUE THREAD

**Issue by Brancepeng** [almende/vis#2441]
code as following:
nodes = [
        {id: 1,  value: 2,  label: 'Algie' },
        {id: 2,  value: 31, label: 'Alston'},
        {id: 3,  value: 12, label: 'Barney'},
        {id: 4,  value: 40, label: 'Coley' },
        {id: 5,  value: 17, label: 'Grant' },
        {id: 6,  value: 15, label: 'Langdon'},
        {id: 7,  value: 6,  label: 'Lee'},
        {id: 8,  value: 5,  label: 'Merlin'},
        {id: 9,  value: 30, label: 'Mick'},
        {id: 10, value: 18, label: 'Tod'},
      ];
visNodes = new vis.DataSet();
 visNodes.add(nodes);
network = new vis.Network(container, visNodes, options);

And when I change the 'value' property of nodes[3] to 20,the other nodes of the network will change
larger,even though the 'value' property doesn't change ,for eaxmple,the nodes[0].value also is 2.
code as following:
function test (){
nodes[3].value = 10;
visNodes.update(nodes[3]);
visNodes.get(nodes[3].id); //20
visNodes.get(nodes[1].id); //31
  }
I wonder if this is a bug,or maybe I use the API incorrect?

**Comment by Tooa** [comment]
The [documentation](http://visjs.org/docs/network/nodes.html) describes how the scaling is applied. 

```
var scale = customScalingFunction(min,max,total,value);
var diff = maxSize - minSize;
mySize = minSize + diff * scale
```

with customScalingFunction defined as:

```
function (min,max,total,value) {
  if (max === min) {
    return 0.5;
  }
  else {
    var scale = 1 / (max - min);
    return Math.max(0,(value - min)*scale);
  }
}
```

As far as I can tell `min` and `max` don't change in your example i.e. `2` and `40`. The value `total` changes after your update, but is not used in the default scaling function. All other variables stay the same. So based on the documentation the other nodes should keep their size.
