### ISSUE TITLE
Event Position and Asset Position should be in centre

### ISSUE THREAD

**Issue by sunil-prasad-w** [almende/vis#2443]
Hi There,

I am using timeline with group example suggestion. We need to display timeline with start, end date  and one event ( Start date will be always ahead of timeline.) for one group. Currently  I am facing issue in alignment. Timeline and Event does not show in centre and event should be display  after timeline. you can better understand with attached screen.         

![image-1](https://cloud.githubusercontent.com/assets/24523193/21099019/fead032a-c091-11e6-891f-ef6b0f94f9b9.png)

![image-2](https://cloud.githubusercontent.com/assets/24523193/21099025/05376988-c092-11e6-8af6-8e7ddabe76fa.png)

**Comment by yotamberk** [comment]
I'm sorry but i dont understand what you mean

**Comment by yotamberk** [comment]
try adding to the options `stack: false`

**Comment by sunil-prasad-w** [comment]
Thank you @yotamberk for the response.
We are using this code to render multiple events on the timeline. However, the way the vertical alignment of each entry is being done seems to be arbitrary.

For example: In the image below, you'll see (1) and (2) are aligned in a different way and (3) and (4) are aligned in a different way.
![image-1](https://cloud.githubusercontent.com/assets/24523193/21138612/d4ca1494-c154-11e6-8322-17d1004ee7f7.png)


We are not able to identify the logic which allows placement of events on the timeline as depending on the number of records, it keeps on changing their positioning (specifically vertical alignment). There doesn't seem to be any consistency in how the information and its placement being rendered, and hence it is causing us confusion.

If you could guide on how and where the vertical alignment is being configured, we might be able to take it forward from there.

Thank you for creating this wonderful code; it has been very helpful in one of our small project. We look forward to your assistance.

**Comment by yotamberk** [comment]
Hi @sunil-prasad-w , try using the `order` option. you can see an example here: http://visjs.org/examples/timeline/items/itemOrdering.html

**Comment by yotamberk** [comment]
@sunil-prasad-w Does this answer your question?

**Comment by sunil-prasad-w** [comment]
I am still looking issue and working with your suggestion. If I need any help I will let you know.

Thanks for your suggestion.
