### ISSUE TITLE
vis.js is not compatible with YUI Compressor due to use of reserved words

### ISSUE THREAD

**Issue by easleydp** [almende/vis#2445]
Trying to use vis Timeline in a Sencha ExtJS application. The Sencha Cmd build tool uses YUI Compressor by default. It barfs on vis.js due to use of reserved words, e.g. "default" in the following:

`  function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }`

PS. I also tried using the Closure Compiler and this failed for some other reason (can't recall the details).

**Comment by yotamberk** [comment]
Can you submit a PR to allow the support to these tools?

**Comment by yotamberk** [comment]
solved with #2452! Thanks again @easleydp !
