### ISSUE TITLE
edgeSelection to identify the nodes

### ISSUE THREAD

**Issue by jayaprabur** [almende/vis#2447]
Hello All,

When I am selecting edge I wanted to identify the nodes which connected the edges. Is there any feature is available? I have google it for many times but unfortunately I didnt get it.

Any leads?

Thanks in advance.

Regards,
Jay

**Comment by Tooa** [comment]
An edge always connects two nodes i.e. [A] <---> [B]. Ǹot sure, why you are talking about `edges`. However, you could use the `selectEdge` event, which receives the selected edge that provides you with the adjacent nodes. I recommend you to take a look at the [documentation](http://visjs.org/docs/network/). Is this what you are looking for?

**Comment by jayaprabur** [comment]
Thanks for your reply. 
My request is that when I double or single click on edge I should populate the adjacent two nodes in separate DIV.
Ex: [A]<--->[B] when I click on edge in DIV it should display the node names (from there I am connecting PHP to get more info about the nodes and display it on DIV).

**Comment by Tooa** [comment]
Then use the `selectEdge` event mentioned above. Also see [this](http://visjs.org/examples/network/events/interactionEvents.html) example.

**Comment by jayaprabur** [comment]
Yes, I have tried your example, but with that node returns always empty array.

`network.on("selectEdge", function (params) {
        console.log('selectEdge Event:', params);
    });`

The output is:

"nodes": [],
    "edges": [
        "92d73a52-d26a-4c89-9bf2-471418ae1dde"
    ],

**Comment by Tooa** [comment]
Yes, it just returns you the selected edge id. You can look up the edge in the edge dataset using this id i.e. `edges.get('92d73a52-d26a-4c89-9bf2-471418ae1dde')`

**Comment by jayaprabur** [comment]
I have used the following code. But I am receiving null values, Could you tell me where I am wrong.

`      network.on("selectEdge", function (params) {
          edges = new vis.DataSet();
          var edgeIds = edges.get(params.edges[0]);
          console.log(edgeIds);
      });`

**Comment by Tooa** [comment]
You don't need to create the dataset yourself in the event callback - it is already present. 

```
network.on("selectEdge", function (params) { 
    var edge = edges.get(params.edges[0]);
    console.log(edge);
 });
```

**Comment by jayaprabur** [comment]
When I am using the above your code I am getting the following error. 

> TypeError: edges.get is not a function

**Comment by Tooa** [comment]
Are you using the code from the [example](http://visjs.org/examples/network/events/interactionEvents.html) I posted?

**Comment by jayaprabur** [comment]
No. I just took portion of the code from your example. Now I have noticed that you have used nodes and edges in DataSet, which I was wrong.

Its working now! :+1:  :100: 
Great Help 

Thanks a lot :)
