### ISSUE TITLE
Performance on timeline graph

### ISSUE THREAD

**Issue by dmavrin** [almende/vis#2448]
Hello.

I want to thank the creators of this package for good work.

Secondly, I just want to notify people who encountered the same problems.

I had timeline graph with groups and a lot of items (20k+). Performance was soo bad (loading time 20s+). The only thing you need to do is define `start` and `end` date in options and performance boost is to 1s or less loading time. Thats maybe an issue or not. I don't know.

Thanks and keep up the good work.

**Comment by yotamberk** [comment]
@dmavrin Thanks for sharing!
