### ISSUE TITLE
Setting dot color in Graph3d 'dot-color' mode

### ISSUE THREAD

**Issue by ephraimberkovitch** [almende/vis#2451]
Looking at the documentation in http://visjs.org/docs/graph3d/, I can't see how to set explicitly the dot color of a 3d graph. If in the graph style is dot-color mode, then both dot color and dot size are set by the data in style column. But it is unclear for me, by which formula it is being done, and moreover, when creating a number of simultaneously plotted graphs, I have to sync their legends and so have to be able to set each dot's color explicitly 

Thanks,

**Comment by ephraimberkovitch** [comment]
I have already performed this change and submitted it to review, so the issue can be closed

**Comment by gonzalog** [comment]
This is still an issue
