### ISSUE TITLE
Render issues with Firefox 50.1.0 on Ubuntu 16.04 LTS (64bit)

### ISSUE THREAD

**Issue by OACDesigns** [almende/vis#2454]
The latest release of Firefox seems to have introduced a rendering issue on ubuntu (could it be related to https://github.com/almende/vis/issues/1112 ?). 
Chrome is unaffected on the same machine

jsbin:
https://jsbin.com/goquduyuhi/edit?html,js,output

Screenshot
![hardcopy](https://cloud.githubusercontent.com/assets/2932334/21194119/0d7a05ee-c22f-11e6-9e39-1835f47c338f.png)

**Comment by Tooa** [comment]
It works for me on Linux Mint 17.3 (based on Ubuntu 14.04) with Firefox 50.1.0. Have you tried to clear the cache?

**Comment by OACDesigns** [comment]
yes we tried with a clean cache, no change unfortunately.
It's on a colleague's machine by the way. I can also confirm that Ubuntu 14.04 appears fine, so it must be specific to 16.04

The following error appears in the console:
```
error getStackTrace@https://null.jsbin.com/runner:81:7
getOriginatingScriptUrl@https://null.jsbin.com/runner:96:19
trapInstanceMethod/item.obj[item.propName]</<@https://null.jsbin.com/runner:147:28
_drawText@https://cdnjs.cloudflare.com/ajax/libs/vis/4.17.0/vis.js:31969:11
draw@https://cdnjs.cloudflare.com/ajax/libs/vis/4.17.0/vis.js:31875:9
draw@https://cdnjs.cloudflare.com/ajax/libs/vis/4.17.0/vis.js:33137:9
draw@https://cdnjs.cloudflare.com/ajax/libs/vis/4.17.0/vis.js:31683:9
_drawNodes@https://cdnjs.cloudflare.com/ajax/libs/vis/4.17.0/vis.js:39750:15
_redraw@https://cdnjs.cloudflare.com/ajax/libs/vis/4.17.0/vis.js:39664:13
bindEventListeners/<@https://cdnjs.cloudflare.com/ajax/libs/vis/4.17.0/vis.js:39508:13
Emitter.prototype.emit@https://cdnjs.cloudflare.com/ajax/libs/vis/4.17.0/vis.js:10224:9
_onResize@https://cdnjs.cloudflare.com/ajax/libs/vis/4.17.0/vis.js:39926:9
```

**Comment by OACDesigns** [comment]
(btw I updated the jsbin to use the unminified version for a better stack trace: https://jsbin.com/damodevoha/edit?html,js,output )

**Comment by koug44** [comment]
I have the same issue on Firefox 50.1.0 on ArchLinux x64. Manage to fix it by disabling the Privacy Badger addon

**Comment by Tooa** [comment]
Is this still an issue? Have you identified any culprit like the mentioned `Privacy Badger addon`. Does it work with a vanilla Firefox installation?

**Comment by OACDesigns** [comment]
I think it's safe to close this.
The issue seemed to disappear with no action taken as far as I'm aware...it may be due to an update in ubuntu
