### ISSUE TITLE
Network: Getting Node data while selecting an edge

### ISSUE THREAD

**Issue by hardikvasa** [almende/vis#2477]
Hi, this is a great project!

I am developing an application where I would like users to select an edge and receive data about which 2 nodes are connected to it.

Currently this is the response from mouseClick on an edge:
`{
    "nodes": [],
    "edges": [
        "ed9b03df-ae03-46c6-9be5-abde47ca9b5b"
    ],
    "pointer": {
        "DOM": {
            "x": 392,
            "y": 163
        },
        "canvas": {
            "x": -8.780733113799284,
            "y": 21.686473637811282
        }
    },
    "event": "Mouse Click"
}`

In the value of nodes - **"nodes": []**, I would like to be able to populate data on the connected nodes when an edge is clicked. If this is not directly possible yet, is there any workaround for it?

Is this possible?

**Comment by Tooa** [comment]
Yes, this is possible via the [dataset](http://visjs.org/docs/data/dataset.html) of the edges. You can retrieve the edge from the edge dataset using the edge id given above i.e. edges.get('ed9b03df-ae03-46c6-9be5-abde47ca9b5b') - assuming that `edges` represents the edge dataset. The returned edge provides you with the adjacent nodes.

Does this answer your question?

**Comment by hardikvasa** [comment]
Thank you for your quick and precise answer. Yes, that certainly helps! :+1:
