### ISSUE TITLE
Tooltip causes issues when changing node to cluster

### ISSUE THREAD

**Issue by nilsottesen** [almende/vis#2478]
I'm using  version 4.17.0, 2016-11-05
I have a title for my node, and when clicking the node I create a cluster. If the tooltip is showing during this operation, the code in line 41401 (function __checkHidePopup_, statement _overNode.id === this.popup.popupTargetId_) breaks, as overNode is undefined

**Comment by Tooa** [comment]
Can you provide a jsbin showing your error and a description that explains how to reproduce the error using that jsbin?

**Comment by nilsottesen** [comment]
Uli,
I’ve just started look into visjs this weekend, and I like very much what I’ve learned so far. I’m building a product that manages object graphs (Engineering Class Libraries), and have been looking for ways to visualise.

Not sure how to do what you are asking for (jsbin), so instead I made a bare bone examples that shows the issue in action.

To provoke the issue:

·         Using Chrome

·         Open the developer tools

·         Hover the Root node, make sure the tooltip shows

·         Click the Root node, to create a cluster

·         When the cluster node does not get positioned under the mouse pointer, the issue occurs

I’ve included the non-minified library, to see exactly what statement causes the issue.

Cheers,
-Nils

**Comment by Tooa** [comment]
I can confirm this error. Let me see if I can find some time to look into this.

**Comment by mojoaxel** [comment]
Fixed by @Tooa with #2555
