### ISSUE TITLE
Can be implemented 

### ISSUE THREAD

**Issue by arikarik** [almende/vis#2479]
![support_log](https://cloud.githubusercontent.com/assets/24650063/21311167/8e46e918-c5ee-11e6-9a37-66aeb2cb9f20.png)

The number 5.0...
Can be implemented as a badge appears in the picture?

**Comment by wimrijnders** [comment]
You might be able to achieve this by catching the `afterDrawing` event and adding the 'badge' yourself. Take a look at the example code in #3086 as inspiration on how to do that.

**Comment by wimrijnders** [comment]
It definitely can be implemented using `afterDrawing()`, this has become clear to me after progressive understanding due to issue handling.

Even though this issue should be leading due to seniority, I am marking it as a duplicate to a newer issue that has example code on how to do this.

**Comment by wimrijnders** [comment]
Duplicate of #3279.
