### ISSUE TITLE
Another way to add items on Timeline other than doubleClick on timeline.

### ISSUE THREAD

**Issue by aashay0101** [almende/vis#2484]
Is there a way where I use a button to add items to the timeline instead on doubleClicking on the timeline. I need the same functionality but on a Button like a link that when clicked will trigger the timeline onAdd function.

**Comment by yotamberk** [comment]
you can use the `timeline.setItems()` to add items to the timeline

**Comment by yotamberk** [comment]
@aashay0101 does this answer your question?

**Comment by aashay0101** [comment]
Can your solution work with the timeline that has been already initialised?

**Comment by yotamberk** [comment]
Yes

**Comment by aashay0101** [comment]
@yotamberk Can I emulate the "doubleClick" on timeline by clicking on a button. The thing is I have implemented a Dialog which pops up when you doubleClick on the timeline. I want the same to happen when I click on the custom "Add Bullet" button. I know that doubleClick triggers the event with X Y co-ordinates of the mouse to figure out the snapped time where the bullet is to be added. How do I go ahead with this? My Aim is to add item on the timeline without reloading the timeline.

**Comment by aashay0101** [comment]
Okay I think the solution provided by @yotamberk is the best way to do this, where you call `timeline.setItems()` and passing items which the timeline will automatically add. As long as a popup functionality is concerned, I called the popup separately and after the completion of popup it called the `timeline.setIems()` function. This solves the problem. Thanks a lot @yotamberk .

**Comment by yotamberk** [comment]
No problem =)
