### ISSUE TITLE
Customizing css for timeline items

### ISSUE THREAD

**Issue by federicoco** [almende/vis#2485]
hello,
When I generate the items for the timeline I also include className:"orangeBox" and the result is like the attached image.
**My css** is
```
.orangeBox
{
  background-color:#FF832E ;
  border: 1px solid;
  border-color: #FF9852 ;
}
.orangeBox:active
{
  background-color: #FFC7A0;
}
```
The problem I'm encountering is that when you click it apply the css but then I see the yellow background color of vis(see second image).
What I want to achieve is to avoid that yellow color-background (that even after selected it stays the same orange of when it has been clicked).
**how can I do it?**
![timelineissue2](https://cloud.githubusercontent.com/assets/22914696/21356575/748c9240-c6d2-11e6-98e1-b72cea5251a2.jpg)

![timelineissue](https://cloud.githubusercontent.com/assets/22914696/21356471/03b10808-c6d2-11e6-84cd-f6a098301841.png)

**Comment by yotamberk** [comment]
Try adding this to your css:
```css
.vis-item.vis-selected {
   background-color: none;
}

```

**Comment by federicoco** [comment]
It worked , thanks !
