### ISSUE TITLE
allowedToMoveX in hierarchical layouts and onMove callback

### ISSUE THREAD

**Issue by moschlar** [almende/vis#250]
Hi there,

it would be cool to have the possibility to allow nodes in a hierarchical layout move in x-direction and detect that movement in an `onMove` callback.

Is this probably already possible and I've missed it?

Cheers,
Moritz

**Comment by nitin0708** [comment]
Hi,

Can i stop the move x and y direction?

**Comment by AlexDM0** [comment]
Hi Nitin,

You can use the freezeSimulation(true) method on stabilized to stop the simulation. You could also use the dragNodes option to disable dragging of nodes. 

Alternatively, you could disable the physics simulation with

```
var options = {physics: {hierarchicalRepulsion: {nodeDistance: 0, springConstant: 0}}
```

It is not possible to lock the position of individual nodes in the hierarchical system. 

Regards,

Alex

**Comment by nitin0708** [comment]
Hi Alex,

Thanks for the reply..but i want the node should not be moving after network draw..

Thanks and Regards,

Nitin

**Comment by AlexDM0** [comment]
Hi Nitin,

Is that not exactly the result of the mechanisms I described?

Regards,

Alex

**Comment by nitin0708** [comment]
Hi Alex,

its stop the position of the other nodes with respect to selected node but still selected node is moving.I am trying to stop drag or move of the all nodes.

Thanks and Regards
Nitin

**Comment by nitin0708** [comment]
Hi Alex,
There is two property for moving of nodes are allowedToMoveY,allowedToMoveX but it is not working on nodes.
Can you please tell me what is the role of this two properties.

Thanks and Regards,
Nitin

**Comment by AlexDM0** [comment]
Hi Nitin,

Those do not work with the hierarchical layout. I'll append that to the next version of the docs.

Regards,

Alex

**Comment by nitin0708** [comment]
Hi Alex,

Thank You  for quick reply of my queries.

Thanks and Regards,
Nitin

**Comment by AlexDM0** [comment]
Hi Nitin,

Take a look at this:

http://jsbin.com/zufivucera/1/edit?html,output

It should do what you need :)

Regards,

Alex

**Comment by nitin0708** [comment]
Hi Alex,

Wonderful!!! its working.Thanks a lot..

Thanks and Regards,
Nitin

**Comment by nitin0708** [comment]
Hi Alex,

I am getting this issue on particular for this situation. check please this one   

http://jsbin.com/kacigariti/1/edit?html,output

Thanks and regards

**Comment by AlexDM0** [comment]
Hi,

The hierarchical system is built for fully connected systems. The physics solver is specialised for it. 

You could connect the node to the others with an invisible edge to solve this. (Rgba(0,0,0,0))

Regards,

Alex

**Comment by nitin0708** [comment]
Hi Alex,

its nice..Thanks for reply..

Thanks and Regards,
Nitin

**Comment by nitin0708** [comment]
Hi Alex,

Can we disabled a particular node and edge.

Thanks and Regards,

Nitin

**Comment by AlexDM0** [comment]
> Hi,

What do you mean by disable?

Regards,

Alex

**Comment by nitin0708** [comment]
Hi Alex,

Node and edge will be present in data list but they should be disappear.Otherwise this issue will appear in tree draw.

http://jsbin.com/kacigariti/1/edit?html,output

**Comment by AlexDM0** [comment]
> Hi Nitin,

Why does the node have to be in the dataset is you do not show it? You cannot disable it but you could hide it by setting the color to invisible (rgba(0,0,0,0)). 

I would recommend you remove the node from the dataset if you do not want to show it.  There are numerous problems with having an invisible node. Messing up the zoomExtend being the biggest I can think of at the moment.

Regards

**Comment by nitin0708** [comment]
Hi Alex,

Thanks for Reply...i will implement this one.

Thanks and Regards,
Nitin

**Comment by nitin0708** [comment]
Hi Alex,

Can we set the tooltip outside because inside the div its not looking properly.
Check for nitin Node in below example-
http://jsbin.com/cawixapika/1/edit

Thanks and Regards,

Nitin

**Comment by AlexDM0** [comment]
> Hi Nitin,

No that is not possible but you could make your own using the hover events. Could you make a new issue of you have a question that is not related to the topic of this one?

Regards
