### ISSUE TITLE
Invalid type received for "enabled". Expected: bool. Received [boolean] "false"

### ISSUE THREAD

**Issue by eymiha** [almende/vis#2500]
Create a network with `options = { physics: { enabled: false } }` and look at the console output.

This seems to be related to #2452.

**Comment by eymiha** [comment]
The problem stems from the misuse of the ES6 Object Literal Property Value feature.

in `options.js` the declaration
```
let bool = 'boolean';
```
and subsequent use
```
enabled: { bool }
```
is interpreted as
```
enabled: { bool: 'boolean' }
```
not
```
enabled: { 'boolean': 'boolean' }
```

The fix is to replace the shorthand for the bool property
```
enabled: { bool }
```
with
```
enabled: { boolean: bool }
```
and all other such uses in `options.js`.

**Comment by easleydp** [comment]
Concerned that this regresses part of the #2452 fix, i.e. reintroduces use of reserved word _boolean_. When used as an object literal key, 'boolean' must be quoted (as yotamberk did it in 534ad9f)

**Comment by yotamberk** [comment]
What if the key is in quotation mark?Will that solve the problem? 
The problem with the  #2452 fix is that it introduced errors in options with boolean values. It seems that the only way to use your fix without breaking other code is by changing `Validator` to be able to handle 'bool' instead of 'boolean'. Can you take care of that?

**Comment by easleydp** [comment]
Yes, if the key (being a reserved word such as _boolean_) is in quotation marks I believe that will solve the problem. In other words, like you did it in 534ad9f.

If you still think changing `Validator` is necessary please let me know.

**Comment by yotamberk** [comment]
I think we can do without changing `Validator`

**Comment by eymiha** [comment]
If this is an issue then replacing my changes with { 'boolean' : bool } in option.js should fix the problem.

No change to Validator.js should be needed.
