### ISSUE TITLE
Unix Timestamp compression.

### ISSUE THREAD

**Issue by aakashrathore** [almende/vis#2503]
Hey,
 I was wondering if there is a way to compress UNIX timestamps to "Human Readable characters." For eg: compressing 14,000,000,000 to 14B. 
So I am basically designing a timeline which displays dates from the start of the universe to the time you're reading this. Since date datatype cannot display dates at the start of the universe I am using Unix timestamps to display astronomical dates. here is a screenshot.
<img width="1436" alt="screen shot 2016-12-26 at 6 20 07 pm" src="https://cloud.githubusercontent.com/assets/11655317/21488125/fa6cf6f0-cb98-11e6-9545-c01b38ff1796.png">

In the screenshot, as you can see, the numbers are huge and I would like to compress them. like 14,000,000 would be 14M and 13,800,000,000 would be 13.8B.
All I need to know if there is a way to customize the timestamp or an event handler in the library that'd let me handle the times before displaying. By "handle", I mean that the event handler would provide me the timestamp and I could parse it as needed and then return the String which would take place of the original timestamp without disrupting the sequence of numbers.
**Environment:**
browser: chrome(for dev), and OS: Linux based server.

**Comment by yotamberk** [comment]
Hey @aakashrathore, you can use the `format` option with a function and change the label to you format. Checkout the docs: http://visjs.org/docs/timeline/#Configuration_Options

**Comment by aakashrathore** [comment]
I though that would work too, but what the issue is, time is a multiple of 60 (hope you understand what I mean here) whereas years isn't. So labeling doesn't seem to be working for me. 
 Here is a screenshot of what I am trying to achieve. 
<img width="1434" alt="screen shot 2016-12-27 at 3 56 10 pm" src="https://cloud.githubusercontent.com/assets/11655317/21510120/0d30181c-cc4d-11e6-8449-688396b5ac5b.png">
**After Zooming: **
<img width="1189" alt="screen shot 2016-12-27 at 3 56 23 pm" src="https://cloud.githubusercontent.com/assets/11655317/21510121/0d4829ac-cc4d-11e6-8a63-a79ad85cf30c.png">

Any suggestions on what I should be doing? I don't mind editing the source code of the library too, but I need to know what I am supposed to be doing or what changes I need to make.
I'd appreciate any help. 
Thanks

**Comment by aakashrathore** [comment]
Nevermind, I fixed it. Just had to change the minorText labels and "text" in the vis.js file. Let me know if you want me to branch it. 
Thanks.

**Comment by yotamberk** [comment]
That would be great if you submitted a PR
