### ISSUE TITLE
how to link two timelines?

### ISSUE THREAD

**Issue by ssabba** [almende/vis#2505]
Hello, I have a question.

I know "link_two_timelines" example in chap-link timeline.

[http://almende.github.io/chap-links-library/js/timeline/examples/example10_link_two_timelines.html](url)

Maybe, it used the "get(set)VisibleChartRange" function.

But I can't find any methods, options for link two timelines in visjs.

What should I do?

**Comment by yotamberk** [comment]
checkout #2147

**Comment by ssabba** [comment]
thank you yota.

**Comment by yotamberk** [comment]
@ssabba my pleasure :smile:
