### ISSUE TITLE
Draw line to X-axis for type point.

### ISSUE THREAD

**Issue by SergeyBondarenko** [almende/vis#2508]
Is it possible to draw a line to the X-axis for the `item 1`, the same way it is done for the `item 6`?
![screenshot from 2016-12-28 09-49-39](https://cloud.githubusercontent.com/assets/5389745/21517937/2839656e-cce3-11e6-816c-0fdd79344355.png)

**Comment by yotamberk** [comment]
item 6 is a `boxItem` while item 1 is a `pointItem`. Why not simply make item 1's type to a `box`?

**Comment by yotamberk** [comment]
If you want to make it look different than the box item, I suggest you play with the css

**Comment by yotamberk** [comment]
@SergeyBondarenko Does this answer your needs?
