### ISSUE TITLE
rendering vis item range initially

### ISSUE THREAD

**Issue by timelineAxis** [almende/vis#2510]
About rendering vis range : 
Currently we have restricted date range to some extend . Timeline is showing items which are within that date range when user 1st time render on the screen . When user change the date range then items should get increased . In zoom out all items are get displayed which are in new date range . In zoom in all items still are get displayed which are rendered till the date . 
Please see the below link : [http://jsfiddle.net/nrex99jf/](url)
Refer id =3 Wikimania . In this start date & end date are beyond the range so it is not rendered initially but when we zoom out it is get started to display . & when we perform zoom in to previous range items are still visible on the screen . 

We required at the initial level only all items should get displayed  though they are beyond the date range .

**Comment by lewisjb** [comment]
I had a quick look into this and there seems to be a fairly simple solution:

Changing [timeline/component/Group.js:34](https://github.com/almende/vis/blob/master/lib/timeline/component/Group.js#L34) to instead set to `this.checkRangedItems` to `true`, will ensure that the rendering will check for those elements on the first render.

**Comment by yotamberk** [comment]
@lewisjb do you want to add a PR for this?

**Comment by lewisjb** [comment]
@yotamberk It appears that this actually isn't an issue in the develop branch. I haven't found the exact commit that fixed it, but if I try that fiddle's code with a freshly compiled vis.js; it shows Wikimania from the start. Would you be able to confirm this?

**Comment by yotamberk** [comment]
Confirmed!
