### ISSUE TITLE
Timeline option `throttleRedraw` was removed without increasing MAJOR version number

### ISSUE THREAD

**Issue by mojoaxel** [almende/vis#2511]
see https://github.com/almende/vis/issues/1766#issuecomment-268621788

Remove a public (documented) option is a "breaking change". Breaking changes need a Major Version update.

**Comment by mojoaxel** [comment]
This was introduced by #2091 with c130f0b01f91a96dfd215d5c80eb0351dddca62e
WE NEED TO BE MORE CAREFULLY!

**Comment by yotamberk** [comment]
@mojoaxel I agree. We didn't think about that at the time we approved it. We can add a stub `redrawThrottle` saying in the console that this option has been deprecated and will be removed in the next major. What do you think?

**Comment by mojoaxel** [comment]
Fixed with #2514 by re-adding docs for *trottleRedraw*. If used a "deprecated" warning is thrown.
