### ISSUE TITLE
[Timeline] itemover & itemout fired multiple times in HTML items

### ISSUE THREAD

**Issue by lewisjb** [almende/vis#2515]
JSBin: http://jsbin.com/fixegibizu/1/edit?html,console,output

As you can see, the events are fired when you move the cursor around the HTML item.

This also impacts HTML tool-tips from #2498

Explanation of why:
(source) [PR 2498 Comment](https://github.com/almende/vis/pull/2498#issuecomment-269835435)
"The `mouseover`/`mouseout` event is being fired on child elements. In this case it was something like
```html
<div class='vis-item'>
    <h1>HTML</h1>
    Text
</div>
```
So when you hovered over the `<h1>` element, there was a new element under the cursor, which fires `mouseout`, followed by its related `mouseover`. This is expected; however, all the code handling those events don't care about the specific element, only the 'item' which they are in. (Reference: [ItemSet.js:1874](https://github.com/almende/vis/blob/develop/lib/timeline/component/ItemSet.js#L1874) and [ItemSet.js:1896](https://github.com/almende/vis/blob/develop/lib/timeline/component/ItemSet.js#L1896))
So tool-tips will be moved, and 'itemover'/'itemout' will be emitted when the cursor is still over the same item."

**Comment by mojoaxel** [comment]
The easiest way is to disable mouse-events for all elements inside an item. This could be done in css.

Here is the working example with the css hack: http://jsbin.com/neqixoreka/1/edit?html,css,console,output

**Comment by mojoaxel** [comment]
Fixed by @lewisjb with #2539
