### ISSUE TITLE
[Timeline] Add an option to HTML tool-tips to make them follow the cursor

### ISSUE THREAD

**Issue by lewisjb** [almende/vis#2516]
[Feature request]
From: #2498 

It would be nice to have an option like `tooltipFollowMouse`, which when enabled will make the tool-tip follow the cursor.

It might be more beneficial to add a generic `tooltip` option, which accepts an object, and has `followMouse` as an acceptable sub-option. (As this then makes it cleaner if we want to add more options to tool-tips later)

**Comment by mojoaxel** [comment]
Implemented by @lewisjb with #2544
Thanks!
