### ISSUE TITLE
Network - node show input links

### ISSUE THREAD

**Issue by dimaxweb** [almende/vis#2523]
Hi,
In my use case I need to visualize network card with ports , as a part of whole network , where edges to other elements can be connected through those port. Currently I don't find any api / option on nodes ,is it possible ?

**Comment by Tooa** [comment]
Hi, this is not possible at the moment. If you like to, you can pick it up and send us a pull request. Closing in favor of https://github.com/almende/vis/issues/2442 and https://github.com/almende/vis/issues/2450.
