### ISSUE TITLE
mousemove event is not triggered in chrome

### ISSUE THREAD

**Issue by Silobrlst** [almende/vis#2525]
When I press and hold the left mouse button in Network mousemove event is not triggered in chrome, but in firefox all works fine.
Can this be fixed for chrome?

**Comment by Tooa** [comment]
Am I wrong or is there no `mousemove` event mentioned in the network [docs](http://visjs.org/docs/network/)? Can you elaborate on this and provide a minimal example of your problem on [jsbin.com](jsbin.com)?

**Comment by Silobrlst** [comment]
http://jsbin.com/zakojenako/edit?html,console,output

**Comment by Tooa** [comment]
Thanks for your jsbin. I can confirm this issue. However, not sure where to start first to fix this issue.

**Comment by mojoaxel** [comment]
I can not confirm this with Chome 50.0.2661.75 (64-bit) on Linux or 55.0.2883.95 (64-bit) on Mac.
Are you guys on Windows?

**Comment by Silobrlst** [comment]
Yes I'm on windows, chrome 55.0.2883.87 m (64-bit)

**Comment by mojoaxel** [comment]
I also can not confirm this on Windows with Chrome 55.0.2883.87. Strage!
Maybe I'm looking at this the wrong way? I have opend [the jsbin](http://jsbin.com/rutoyuhiyu/edit?html,console,output) and a get a lot of console.logs with the coordinates when moving the mouse over the canvas.

**Comment by Tooa** [comment]
You need to keep the **left mouse button pressed** when moving.

**Comment by mojoaxel** [comment]
> You need to keep the **left mouse button pressed** when moving.

:-) Sorry..My mistake.

:+1:  **Still working for me on:**
* Chrome 50.0.2661.75 (64-bit) on Linux

:-1: **Not working with:**
* Chrome 56.0.2924.51 beta (64-bit) on Linux
* Chrome 55.0.2883.95 (64-bit) on Mac
* Chrome 55.0.2883.87 on Windows

Here is a minimal Canvas-Test-Case: https://jsbin.com/dofiroy/1/edit?html,console,output
This simple test-case works in all chrome version for me. So maybe it's not just a simple Chrome-Bug but something in vis.js!?

**Comment by Tooa** [comment]
> So maybe it's not just a simple Chrome-Bug but something in vis.js!?

Looks like. The Canvas Test-Case example works for me with Chrome 55.0.2883.87 (64-bit) on Linux Mint 17.3.

**Comment by mojoaxel** [comment]
I've found the problem:
https://github.com/almende/vis/blob/develop/lib/module/hammer.js#L7

Maybe @josdejong can fix this!?

**Comment by josdejong** [comment]
@mojoaxel If I find some time I will look into it but I can't make any promises. 

I think [`preventDefault: mouse`](https://github.com/almende/vis/blob/develop/lib/module/hammer.js#L7) is there to prevent selecting text while dragging the mouse, it does not stop propagation so it should not block other event listeners like mousemove. But looking at your [latest jsbin](https://jsbin.com/dofiroy/2/edit?html,console,output) it looks like it's something that you can reproduce with just hammer.js so isn't it an hammer.js issue?

**Comment by Tooa** [comment]
@josdejong The canvas test case shows that it works using only `hammer.js`. Compare the working example to [this](http://jsbin.com/rutoyuhiyu/1/edit?html,console,output). You will notice that when keeping the left mouse button pressed while moving, no more console logs are issued. However, this works in the canvas test case, which does not rely on visjs. Thus, it has to be an error in visjs.

**Comment by josdejong** [comment]
> However, this works in the canvas test case,

ah, now I see. The [jsbin](http://jsbin.com/rutoyuhiyu/1/edit?html,console,output) now indeed keeps working when dragging. Yesterday I tried and it *stopped* working when dragging - not sure what was going on then now it works correctly.

**Comment by knokit** [comment]
I've got a similar problem with the Timeline, that maybe it's connected with this one.

The mouse events stopped working on chrome, but seem to work fine on firefox - [jsfiddle](https://jsfiddle.net/knokit/v217ag47/3/)

**Comment by mojoaxel** [comment]
> I've got a similar problem with the Timeline, that maybe it's connected with this one.

@knokit Please file a new issue linking to you jsfiddle. Thanks

**Comment by xenobytezero** [comment]
I have a similar issue, in regards to native mouse events ('click', 'dblclick') not being fired when attached to timeline items.

When removing the line that @mojoaxel mentioned above (https://github.com/almende/vis/blob/develop/lib/module/hammer.js#L7) the issue disappears. 

Is this going to be an option that can be switched off?

**Comment by sagawater** [comment]
> I think preventDefault: mouse is there to prevent selecting text while dragging the mouse, it does not stop propagation so it should not block other event listeners like mousemove. But looking at your latest jsbin it looks like it's something that you can reproduce with just hammer.js so isn't it an hammer.js issue?

I confirm the `preventDefault: mouse ` in hammer.js in causing the problem. Thus, it is not fixed in 4.20.0 as mentioned in #2605.

As metioned in [W3C Pointer Events Documentation](https://www.w3.org/TR/pointerevents/#intro) Section 11 :

> 3. If the pointer event dispatched was pointerdown and the event was canceled [calling preventDefault()], then set the PREVENT MOUSE EVENT flag for this pointerType.

This will affect the following compatibility behavior:
if pointerdown, then fire a mousedown event.
if pointermove, then fire a mousemove event.
if pointerup, then fire a mouseup event.
if pointercancel, then fire a mouseup event at the window.

It makes the vis components really hard to integrated into an existing behavior, and with other components.

**Comment by wimrijnders** [comment]
I can confirm this is the issue: `preventDefault: mouse` in `hammer.js` is blocking the `mousemove` event.

In fact, I can remove the entire `propagating` module from the chain and the whole thing still works. Thus the line in `hammer.js` can become:

```javascript
  module.exports = Hammer;
```

Can't we just remove module `progagating-hammerjs`?

**Comment by chrisallick** [comment]
just stumbled upon this problem. Trying to use a signature demo i made, but doesn't work in current chrome. this seems to work... http://jsfiddle.net/G5Xr2/ so im simply bypassing p5 and storing x,y values from the mouse event

**Comment by Negmah** [comment]
Hi guys!
Super ultra novice coder here!
I'm learning Canvas and just stumbled on this same problem here.
'mousemove' is not firing when I have the console open. Nonetheless, it does fire correctly when console is not active.

Has anyone reached any conclusion as to how this issue can be bypassed or overcome?

Chrome Version 67.0.3396.99 (Official Build) (32-bit)

**Comment by BasPaap** [comment]
What is the status of this? I'm having trouble getting mouseup and mousedown events using the visjs network. It looks like the containing element simply isn't firing the mouse events. Is the network simply not propagating them up to the containing div? What can be done about this?

**Comment by Silobrlst** [comment]
I removed this line in vis.js:
`preventDefault: 'mouse'`

And this helped for me.
Thank you all for the answers.
Sorry that i didn't answer for a long time)
