### ISSUE TITLE
hover event -not able to show anything on hover which I am writing for particular node inside hoverNode function

### ISSUE THREAD

**Issue by jhabap18** [almende/vis#2532]
network.on("hoverNode", function (params) {
                     nodes._data[params.node].title="ABCD";
                  });

It is not showing "ABCD" on hover on the node on which I  am hovering.

My requirement is like that I can not write hover text at the time of initialization under title field in node.
I have to write in customized manner on hoverNode function only. Please suggest a way.

**Comment by Tooa** [comment]
Can you provide a minimal example of your problem via [jsbin.com](jsbin.com)? Is your `hoverNode` callback executed?

**Comment by LLTommy** [comment]
I agree with Tooa, we need a little more to be able to help. I tried pretty much all other events but 'hoverNode' and they all worked fine with that syntax you posted up there.
