### ISSUE TITLE
3d bar graph data array unsorted

### ISSUE THREAD

**Issue by hawkeyeaz1** [almende/vis#2536]
If you pass Graph3d an array (for data) and the array is not sorted the graphed result breaks visual usability.

Ex: graph = new vis.Graph3d(container, [ {x: 1, y: 3, z: 0}, {x: 0, y: 0, z: 0} ], { style: 'bar' });

**Comment by Tooa** [comment]
This looks like a bug to me. An example to produce can be found [here](http://jsbin.com/moyazaluqe/1/edit?html,output).I'm not really used to the `Graph3D` component. So, how does this order should be defined? Is it enough to sort by the first coordinate? Can you show some more examples? Maybe this one is special?

**Comment by hawkeyeaz1** [comment]
graph = new vis.Graph3d(container, [ {x: 1, y: 1, z: 0}, {x: 0, y: 0, z: 0} ], { style: 'bar' });
graph = new vis.Graph3d(container, [ {x: 1, y: 1, z: 1}, {x: 0, y: 0, z: 0} ], { style: 'bar' });
graph = new vis.Graph3d(container, [ {x: 0, y: 1, z: 1}, {x: 0, y: 0, z: 0} ], { style: 'bar' });
graph = new vis.Graph3d(container, [ {x: 0, y: 0, z: 1}, {x: 0, y: 0, z: 0} ], { style: 'bar' }); // Really interesting

**Comment by wimrijnders** [comment]
Confirmed. The initialization code of graph3d assumes ordering of data. So in the first example, you get a bar width of -1 for the x-coordinate.

There is another hidden assumption here, namely that all bars have the same width. If the bar dimensions are initialized from data, this assumption may explode.

Preparing a PR to tackle them both.

**Comment by wimrijnders** [comment]
To circumvent this with the current version, you can set the default bar widths in the options hash:

    var options = {
      // ...
      xBarWidth: 1,
      yBarWidth: 1,
    };
    // Do further magic here
    
    // ... and pass in the bar defaults in the options:
    graph = new vis.Graph3D(container, data, options);

**Comment by wimrijnders** [comment]
I've added PR #2803 for this.

**Comment by Tooa** [comment]
Thank you @wimrijnders for the fix and welcome back :)
