### ISSUE TITLE
arrows.to.type : Default is arrow. Also possible is circle. Can there be title?

### ISSUE THREAD

**Issue by Alex-Dim** [almende/vis#2537]
Is there possibility to add  type of endpoint on edge to be title so i can write some short text instead of circle or arrow.
Best regards to vis team from Alex.

**Comment by Tooa** [comment]
Do you mean something like [this](https://github.com/almende/vis/issues/2104)?

**Comment by Alex-Dim** [comment]
@Tooa i think this could be very helpfull, i'll try to incorporate this to my test project.On endpoints i need some small portions of text on each side and on hover over edge i need some bigger text and i think this could work.
p.s. Do you have source code of this update and user guidance how to implement this update?
Best regards @Tooa.

**Comment by Tooa** [comment]
@Alex-Dim Sry, I do not have the source code from these experiments. I close this issue in favor of #2104 since it seems to be the same request.
