### ISSUE TITLE
[Timeline] [dev branch] Major axis labels displaying wrong value

### ISSUE THREAD

**Issue by lewisjb** [almende/vis#2538]
This is on the dev branch so I don't have a JSBin, but I do have screenshots.

The below screenshots are for http://visjs.org/examples/timeline/groups/groups.html

This is what it looks like on the website:
![screenshot_2017-01-04_11-55-35](https://cloud.githubusercontent.com/assets/17665267/21629537/16fd715e-d275-11e6-84de-ca6abea6291c.png)

And this is what it looks like locally from dev:
![screenshot_2017-01-04_11-52-41](https://cloud.githubusercontent.com/assets/17665267/21629541/1f635598-d275-11e6-8943-03da68e19169.png)

Note the major axis (the bottom-left text "January 2017" and "00:00:00")

I did some digging and found that the issue stems from this commit: 9f0376e
Reverting the second change (the one for `_repaintMajorText`), makes the major axis act the same as it used to.

@yotamberk, since this is your commit, would you know a nice fix for this?

**Comment by yotamberk** [comment]
@lewisjb Ummm I must admit I have no idea why this is happening... The commit shouldn't have affected this... I'll have to get in to it. Not sure yet how to approach this...

**Comment by lewisjb** [comment]
@yotamberk I had another look into it and found the issue.

You changed `document.createTextNode(text);` to `var content = document.createElement('div');` (and then set the `innerHTML`), but outside that if-statement, you are trying to set the value of that div via `label.childNodes[0].nodeValue`; but, `childNodes[0]` is `content`, not the text node inside `content`. So any changes to the content of major axis doesn't work, they keep the value they were given when they were created.

So it can be fixed by changing it to `label.childNodes[0].childNodes[0].nodeValue`, but I think `label.childNodes[0].innerHTML` would be cleaner (as it is how the text is originally set, and how the text is set for minor axis). And at the same time, line 367 `content.innerHTML = text`, can be removed; as the text is being set a few lines down anyway.

**Comment by mojoaxel** [comment]
Fixed by @yotamberk with #2551
