### ISSUE TITLE
Graph3d axis labels seems floating

### ISSUE THREAD

**Issue by JijDaar** [almende/vis#2540]
Hi,

The axis labels of my graph3d (dot cloud color) seem to be "floating in space" and not attached to the right axis. It is already wrong for the default x,y,z labels. I'm using 4.17.0.

Thanks,
Albert.

**Comment by Tooa** [comment]
Can you provide your problem via [jsbin.com](jsbin.com)?

**Comment by JijDaar** [comment]
Hello,

It's difficult to have the my app, including data, simulated in jsbin.

But I have some more information:

- I'm not setting the axis min/max values. It seems to autoscale, but I can't find it on the manual pages.

- The position of the labels seem to depend on the x,y,z-values of the data. My data values differ a lot between the three axis: x: 44.794 -45.069, y: 0.5766 - 0.61, z: 8.85e-6 - 11.1e-6, style: 8600 - 15919.

- When there is just one datapoint in my dot-color graph (with x=y=z=style=0), the axis labels appear at the right position.

My main question is now: is autoscaling implemented or should I set min/max values?

Thanks,
Albert.

**Comment by wimrijnders** [comment]
Hallo JijDaar,

> My main question is now: is autoscaling implemented or should I set min/max values?

Autoscaling is indeed implemented; if you leave out a default min/max value in the options for any dimension, graph3d will use the corresponding min/max value of the data(*).

> It seems to autoscale but I can't find it on the manual pages.

I scanned the documentation page; fair enough, it is indeed not mentioned. I'm looking at how to add this; do you perhaps have a suggestion? The best I can think of, is to add a short line to the descriptions of `xMin`, `xMax`, `yMin`, `yMax`, `zMin and `zMax`.

_*: (For reference, in the code this happens in `Graph3d._setRangeDefaults()`)_

**Comment by Tooa** [comment]
@JijDaar Does this answer your question?

**Comment by JijDaar** [comment]
Thank you. It's working now and the documentation is extended with info on autoscaling so I will close this issue.
