### ISSUE TITLE
Editing text in a timeline doesn't work for me.

### ISSUE THREAD

**Issue by emiliosalazardonate** [almende/vis#2547]
After trying a lot of browsers and OS (including a Mac with Chrome 55.0), I haven't  been able to edit the item names in this example:
http://visjs.org/examples/timeline/editing/editingItemsCallbacks.html

I don't know if anybody else had this problem???

Thanks,
Emilio.

**Comment by Tooa** [comment]
Updating an entry via double clicking does not work for me either. Are they supposed to be editable via double click? @yotamberk can you have a look at this?

**Comment by yotamberk** [comment]
@emiliosalazardonate When was it editable by double clicking? Was it like that in previous versions?

**Comment by yotamberk** [comment]
Works on `develop` branch. @Tooa can you check again?

**Comment by Tooa** [comment]
Yes, works on the `develop` branch.

**Comment by emiliosalazardonate** [comment]
Does this mean that it will be fixed in the next release?

Thanks,
Emilio.

**Comment by yotamberk** [comment]
Yup :smile:
