### ISSUE TITLE
JavaScript code - Your help needed PLEASE

### ISSUE THREAD

**Issue by salmasalem** [almende/vis#2553]
Hi everyone,

I'm new in JavaScript and I'm in the process of modifying an open source template and I'm stuck in passing the PHP MySQL results to a JavaScript.

I want to replace the lines 34 to 49 in the below link with a MySQL results as the following:

while($row = mysql_fetch_array($retval, MYSQL_NUM)) {
   $data[] = "{id: {$row[0]}, &nbsp;shape: 'circularImage', image: 'img/{$row[4]}', label:'{$row[3]}'},<br>";
   }
   $test = ''.implode('', $data).'';

https://github.com/almende/vis/blob/master/examples/network/nodeStyles/imagesWithBorders.html

I really appreciate your contributions.

**Comment by Tooa** [comment]
Hi,
this is more like a general programming question. Please use [Stackoverflow.com](Stackoverflow.com) for such questions in future. Feel free to create a new issue if you find bugs in visjs you want to report.
