### ISSUE TITLE
syntax tree display

### ISSUE THREAD

**Issue by gbrault** [almende/vis#2563]
Hi!

thanks a lot for this library!

just to provide a usage case

result is here: 

https://github.com/gbrault/railroad-diagrams/blob/gh-pages/live/doc/svg/expression-results.png

And railroad script is used for validation parser generator

https://github.com/gbrault/railroad-diagrams/blob/gh-pages/live/doc/readme.md

I wouldn't have the chance to do this work without vis.js

Thanks again!

Gilbert

**Comment by Tooa** [comment]
Very Cool! Can we use [this](https://rawgit.com/gbrault/railroad-diagrams/gh-pages/live/live.html) for our [showcases page](http://visjs.org/showcase/index.html)? Feel free to create a pull request with the showcase.

**Comment by gbrault** [comment]
I agree of course. How can I manage to do this pull request? Can you guide me?

**Comment by Tooa** [comment]
You need to fork this repository and checkout the develop branch. Then take a look at [this](https://github.com/almende/vis/pull/2101/files) pull request for the files you need to provide/change. Once you did commit the changes to your local repository on a separate branch you can use the Github Web-Interface to create the pull request. Make sure your pull-request is to the `develop` branch. Let me know if you need further help.

**Comment by gbrault** [comment]
Actually, it seems the showcase are in the gh-pages branch, can you confirm?

**Comment by mojoaxel** [comment]
> Actually, it seems the showcase are in the gh-pages branch, can you confirm?

Yes. You'll need to make a pull-request to the gh-pages branch. Please make sure to base it on the current ph-pages branch and not develop. Thx.

**Comment by gbrault** [comment]
I did submit the pull-request! Hope this will work. let me know. You can then close the ticket!

Gilbert

**Comment by mojoaxel** [comment]
merged with #2571 an 3219c5d
