### ISSUE TITLE
Suggestion: Colour for "line" style in grap3d

### ISSUE THREAD

**Issue by ihabadly** [almende/vis#2565]
Thanks for the great effort, is it possible to add style line colour to work with the style "line" in the graph3d.

**Comment by wimrijnders** [comment]
Hi @ihabadly,

In the current version, you can set the line colour with setting `dataColor`. The default setting is:

     dataColor : {
        fill       : '#7DC1FF',
        stroke     : '#3267D2',
        strokeWidth: 1 // px
     }

Of these subfields, `fill` will not do anything for lines, but `stroke` and `strokeWidth` work. To change the line color, set the field `stroke` in your options structure, e.g.

```
// specify options
var options = {

// ...

  dataColor: {
    stroke: '#FF8800'
  }
};
```

Hope this helps; sorry for the delayed reply to what is a simple question; I've been away.

**Comment by Tooa** [comment]
@wimrijnders thanks for the help! @ihabadly feel free to create a new issue or comment in case you still have a problem.
