### ISSUE TITLE
Make certain nodes draggable

### ISSUE THREAD

**Issue by zyu539** [almende/vis#2568]
Hi there,
Is it possible to make some nodes (e.g. nodes with certain id or shape) draggable while others not? If so, how can I make it? Thanks a lot

**Comment by Tooa** [comment]
Sure. See the documentation for the flag `dragNodes` [here](http://visjs.org/docs/network/interaction.html) i.e. `When true, the nodes that are not fixed can be dragged by the user.`. Thus, you just have to put the property `fixed` for the respective [nodes](http://visjs.org/docs/network/nodes.html).

Does this answer your question?

**Comment by zyu539** [comment]
Cool, It works. Thanks a lot.
