### ISSUE TITLE
Toggle the visibility of groups and subgroups

### ISSUE THREAD

**Issue by josdejong** [almende/vis#257]
It would be useful to implement a property `visible` for groups in the Timeline, similar to that of Graph2D, so you can toggle visibility of individual groups.

**Comment by AlexDM0** [comment]
Hi,

Over the last year a lot of feature requests have been made. We have just introduced our new website which has a list of the requested features. We have placed this request on that list. 

The list can be found here:
http://visjs.org/featureRequests.html

An explaination of the new system can be found here:
http://visjs.org/blog.html#New\ website\ for\ vis\.js\!

I would like to stress that this does not mean we abandon this request. Discussion here will continue if needed on this feature but we will close it to keep our Github issue page more of a bug-todo list.

Future feature requests will still be made here and then added to the website by us.

Regards,

Alex

**Comment by mojoaxel** [comment]
Reopening as Feature-Request issue (see #2114). 
Everybody: Please feel free to implement this!

**Comment by simo9000** [comment]
@mojoaxel I just ran into the need for this feature. If you don't mind i'd like to take a shot at implementing this.

**Comment by yotamberk** [comment]
closed with #2315
