### ISSUE TITLE
Is there a cdn for vis?

### ISSUE THREAD

**Issue by Krewn** [almende/vis#2570]
So I have for convenience been referencing vis off of their web site `<script type="text/javascript" src="http://visjs.org/dist/vis.js"></script>` Tho based on the docs here it seems that those maintaining the project would rather see us download the source ourselves. Hence the question, is there any recommended cnd for vis and could we add that information to the readme / website.

**Comment by Tooa** [comment]
What about [this](http://visjs.org/) (link from cdnjs.com)? :D

**Comment by Krewn** [comment]
Cheers.
