### ISSUE TITLE
[Timeline] Tooltip not disappearing on mobile & scrolling.

### ISSUE THREAD

**Issue by lewisjb** [almende/vis#2572]
I have come across two scenarios where the tooltip won't disappear (as `mouseout` isn't triggered).

1. On mobile
2. If you are hovering over an item and scroll

The easiest fix I can think of is to store the current open tooltip in `ItemSet`, as there logically can only be one open, that way we can force the old one to be hidden before displaying a new one.

**Comment by mojoaxel** [comment]
I can confirm that tooltips stay visible at the current position if the user scrolls, moves or zooms the timeline.

**Comment by yotamberk** [comment]
@lewisjb Can you please take care of this issue? It should be quite straight forward

**Comment by lewisjb** [comment]
Would it be more beneficial to only have one tool-tip DOM object, and instead of creating new ones when needed then hiding/showing them, just change it's value etc? Because currently if you have a lot of data in your timeline you can end up with a lot of tooltips in the DOM.

**Comment by yotamberk** [comment]
@lewisjb yes! I think only one tooltip should be available at all times

**Comment by mojoaxel** [comment]
see #2662

**Comment by mojoaxel** [comment]
fixed by @lewisjb with #2662
