### ISSUE TITLE
Network - Node rendering in Chrome sometimes fails

### ISSUE THREAD

**Issue by mkollers** [almende/vis#2575]
Sometimes my network-graph only draws the edges in google chrome (55.0.2883.87). Then it look's like the following:

![image](https://cloud.githubusercontent.com/assets/9371455/21938181/87ff44f8-d9ba-11e6-9183-06852e75a9ba.png)

It always works fine in Edge or Firefox. Anyone else with this problem or any ideas what this can be?

**Comment by mkollers** [comment]
After debugging a little bit, i figured out, that the to fat marked emits are only triggered when the nodes are not rendered:

activate
resize
startSimulation
resetPhysics
_resetData
_dataChanged
_requestRedraw
_dataUpdated
startSimulation
_requestRedraw
_dataLoaded
_repositionBezierNodes
initPhysics
_resizeNodes
_blockRedraw
startStabilizing
stabilizationProgress
**resize**
**_requestRedraw 1**
stabilizationProgress
stabilizationProgress
stabilizationProgress
stabilizationProgress
_allowRedraw
fit
_resizeNodes
_requestRedraw
stabilizationIterationsDone
_requestRedraw
initRedraw
beforeDrawing
afterDrawing
stabilized

**Comment by mkollers** [comment]
Error occured in comination with "position: fixed"!

**Comment by Tooa** [comment]
Can you provide a minimal example showing the problem via [jsbin.com](jsbin.com). Please also let us know how to reproduce the error using the example.

**Comment by mkollers** [comment]
I've tried to reproduce it in jsbin, but i don't get it working...i think it has something to to with my angular slide in animations but i'm not sure. Sorry :-(

**Comment by mojoaxel** [comment]
@mkollers Feel free to reopen if you think its a problem with vis.js
