### ISSUE TITLE
Webpage: Missing Example Screenshots

### ISSUE THREAD

**Issue by mojoaxel** [almende/vis#2584]
I updated the example overview pages in the gh-pages branch. There are still a view screenshots missing.

**Comment by Tooa** [comment]
@mojoaxel Is this still an issue or has this been fixed? For me, all examples seem to have a screenshot.

**Comment by mojoaxel** [comment]
I added the missing the timeline screenshots and updated all existing with 276175e8c41c3ddc7c0aa2a00136aecaac15f1d3.
Some screenshots are still missing for [network](http://visjs.org/network_examples.html)
