### ISSUE TITLE
Expected identifier, string or number

### ISSUE THREAD

**Issue by SoliveauN** [almende/vis#2588]
Hi,
I have this error in IE 11 debug explorer :
```
SCRIPT1028: Expected identifier, string or number
vis.js (14885,81)
```
May you have a solution ? I check issues and stackoverflow tickets with this error type, but nothing found.
It seems throwed on the loading off vis.js in the page between `<head><script>` beacons.
Thanks a lot,
Regards.

**Comment by mojoaxel** [comment]
@SoliveauN Are you using the latest release v4.18.0? What is you configuration?

**Comment by SoliveauN** [comment]
Hi,
Nope, I'm using 4.17.0 version. I have just seen the 4.18.0 version.
I use Hibernate framework, JBoss Server.
I don't have the error on Chrome,Firefox and Edge.
Do you think it will be resolved with 4.18.0 version ?

**Comment by SoliveauN** [comment]
With 4.18.0 version, I have this error :
```
SCRIPT1010: Expected identifier
vis.js (2542,33)
```
An other error, but very similar.
But if I refresh, only with debug explorer opened, I have got the timeline :strange:

**Comment by mojoaxel** [comment]
> Nope, I'm using 4.17.0 version. I have just seen the 4.18.0 version.
Please always use the last version.

> I use Hibernate framework, JBoss Server.
The backend framework has nothing to do with the frontend code.

> I don't have the error on Chrome,Firefox and Edge.
Also not on Edge!? Ok, Than it might be a IE11 bug.

> Do you think it will be resolved with 4.18.0 version ?
We improved the babel support so maybe this problem is fixed, but maybe not.

Please try the un-minifies version "vis.js" again and report the exact error shown in IEs development tools. Thanks.

**Comment by SoliveauN** [comment]
With the restore of 4.17.0 version I have got the first reported error  :
```
SCRIPT1028: Expected identifier, string or number
vis.js (14885,81)
```
Should I downgrade more ?

**Comment by mojoaxel** [comment]
> Should I downgrade more ?

You can try that, but I don't think it will help much.

Does the same error occur if you open the [basic example](http://visjs.org/examples/timeline/basicUsage.html) on your IE11?

It looks to me like a webpack/babel incompatibility with this version of IE.
I think the best chance we have is updating webpack and babel and making sure we have all necessary babel-addons integrated to support IE11.

**Comment by SoliveauN** [comment]
I don't have the error with the example on your website, locally (via the path "C://...") and whenI include the .html file in my workspace.

**Comment by SoliveauN** [comment]
Hi,
Can you explain me what is "webpack" and "babel" ? And can you just tell me how update them ?
Regards.

**Comment by SoliveauN** [comment]
Well, I solved it !
There was a `meta `beacon which forced the compatibility to IE8 in my head beacon. This version of IE doesn't support asynchronous loading of analytics.js librairy (googleAnalytics.js).
Thanks a lot for your help !
Best regards.
