### ISSUE TITLE
Problem with text inside circle ( network )

### ISSUE THREAD

**Issue by maamounkhlifi** [almende/vis#2589]
i can't get the text inside circle to center after updating vis, it look's like the following:

![capture](https://cloud.githubusercontent.com/assets/25162634/22002828/4cd0dabc-dc4f-11e6-9d8e-a87197668954.PNG)

**Comment by bthieurmel** [comment]
Same bug observed after updating to ``vis.js 4.18.0``
![net_1](https://cloud.githubusercontent.com/assets/8750326/22013154/eaebf81a-dc97-11e6-8ce2-3ee590a33494.png)

**Comment by Tooa** [comment]
About which versions are we talking - upgrading from 4.17 to 4.18? Can you tell me in which version this behaviour works as expected?

**Comment by bthieurmel** [comment]
Work fine with ``vis.css 4.17.0`` (label are centered), but not with ``vis.css 4.18.0``.

Simple case : http://jsbin.com/wudaji/edit?html,output

**Comment by Tooa** [comment]
You are right. Works with `4.17.0` and is broken in `4.18.0` :(

**Comment by mojoaxel** [comment]
@bthieurmel Thanks for reporting!
Fixed by @eymiha with #2593
