### ISSUE TITLE
Zoom-in on Timeline using scrollwheel or touchpad when already at max zoom level moves range by 1ms

### ISSUE THREAD

**Issue by tomdcc** [almende/vis#2590]
Hi

**Visible behaviour:**
We are allowing users to zoom the timeline using scroll wheel / touchpad and have not altered the default `zoomMin` value of `10`. If our users scroll in until they are that far in, further zoom-ins seem to move the window to the left by 1ms.

**Expected behaviour:**
Once the zoom level is already at `zoomMin`, further zoom-in actions do nothing, leaving the visible window unchanged.

I've just updated from 4.17.0 to 4.18.0 and this is visible in both versions.

This is visible in the examples, e.g. http://visjs.org/examples/timeline/basicUsage.html - just keep zooming in.

**Comment by mojoaxel** [comment]
Thx. I can confirm problems at the max zoom level. We should look into it.

**Comment by yotamberk** [comment]
fixed with #2646
