### ISSUE TITLE
[Network] self-loop edge not always show with 4.18

### ISSUE THREAD

**Issue by bthieurmel** [almende/vis#2591]
When network have "self-loop" edge (from = 1, to = 1), they are not always showed, depends of movement : 
![net2png](https://cloud.githubusercontent.com/assets/8750326/22013377/f3efe1e6-dc98-11e6-8c44-fe90498afe5c.png)

**Comment by Tooa** [comment]
Can you provide a minimal example showing the problem via [jsbin.com](jsbin.com). Please also let us know how to reproduce the error using the example.

**Comment by bthieurmel** [comment]
Short example :  http://jsbin.com/fipaha/edit?html

Seems to be with dot shape. Edge from node 1 to node 1 is not always visibled (clicking Nodes / moving nodes, ....)

**Comment by Tooa** [comment]
I can confirm this bug. It works with 4.17 and breaks in 4.18. Thus, it was introduced in 4.18 :(

**Comment by bthieurmel** [comment]
Not only for ``dot``, observed same bug with ``diamond``. Don"t have test all shape...

**Comment by eymiha** [comment]
For me, the issue can be seen:

   when opening the network, the link-to-self loop is missing...

   and then simply clicking on the canvas displays the loop.

**Comment by bthieurmel** [comment]
And movving others nodes without loop then loop flash

**Comment by eymiha** [comment]
I've got a fix for this one... I'll be doing a PR shortly.

**Comment by mojoaxel** [comment]
@bthieurmel Thanks for reporting this!
fixed my @eymiha with #2595
