### ISSUE TITLE
Stretch groups height to fit the timeline

### ISSUE THREAD

**Issue by waterplea** [almende/vis#2592]
I have a timeline with multiple groups. Sometimes there's a lot of them and scroll is introduced, sometimes there's not enough of them to fit the height of the time line. It would be great to have an ability to let them stretch vertically to fit the whole timeline. I tried to do that overriding default styles with flexbox model but due to nesting structure of the layout I was unable to make it work with both cases (stretch to fit, scroll when there are too many).

**Comment by waterplea** [comment]
I've managed to override CSS using flexbox to achieve what I wanted. Not sure if my CSS would be helpful to anyone since timeline is pretty flexible and it might only work for my case. Still working on achieving other aspects of layout I want. What are those DIV for though?

`<div class="vis-group" style="height: 0px;">`

`<div style="visibility: hidden;">?</div>`

**Comment by yotamberk** [comment]
@waterplea  
They were added for checking out if there was an initial change in the groups. I don't like this because it feels like a workaround for fixing this case... I'm intending to change this check. Hopefully I'll be able to clean it out for next minor.

Can you supply your CSS you've used?

**Comment by waterplea** [comment]
Hey, here's CSS I used. I think it's all that is relevant, basically I've made things stretch using flex and overwritten the inline top styles for vis-line. I also got rid of 0 height and visibility hidden items:

```
.vis-center .vis-background .vis-group,
.vis-center .vis-foreground .vis-group,
.vis-labelset .vis-label {
  flex: 1;
  min-height: 43px;
}

.vis-foreground .vis-item {
  top: auto !important;
}

.vis-label .vis-inner {
  min-height: 48px;
  line-height: 48px;
}

.vis-left.vis-panel.vis-vertical-scroll,
.vis-panel.vis-center {
  overflow-y: hidden;
  display: flex;
  flex-direction: column;
}

.vis-content {
  min-height: 100%;
  display: flex;
  flex-direction: column;
  flex-shrink: 0;
}

.vis-labelset,
.vis-itemset .vis-background,
.vis-itemset .vis-foreground {
  flex: 1;
  display: flex;
  flex-direction: column;
}

.vis-itemset,
.vis-labelset {
  min-height: 100%;
  flex: 1 0;
}

.vis-group[style="height: 0px;"],
.vis-background .vis-group div[style="visibility: hidden;"] {
  display: none;
}

.vis-foreground .vis-group,
.vis-label {
  display: flex;
  align-items: center;
}

.vis-item.vis-line {
  position: relative;
  height: 100vh;
  top: 50% !important;
  border: none;

  &::before {
    content: '';
    position: absolute;
    width: 1px;
    height: 100%;
    background: inherit;
  }
}
```
