### ISSUE TITLE
Timeline - Uncaught TypeError: Cannot read property 'height' of undefined

### ISSUE THREAD

**Issue by jtissier** [almende/vis#2594]
Hi all,

First I want to say how much I love vis.js library, it saved me months of time to developp a timeline like yours.

I got an error Error on visjs 4.16.1 and 4.18.0 when i try to move a subgrouped item in another group :

```
vis.js:21715 Uncaught TypeError: Cannot read property 'height' of undefined
    at http://localhost:63342/rms/bower_components/vis/dist/vis.js:21715:94
    at Object.exports.forEach (http://localhost:63342/rms/bower_components/vis/dist/vis.js:718:9)
    at Group._calculateSubGroupHeights (http://localhost:63342/rms/bower_components/vis/dist/vis.js:21713:12)
    at Group.redraw (http://localhost:63342/rms/bower_components/vis/dist/vis.js:21635:10)
    at http://localhost:63342/rms/bower_components/vis/dist/vis.js:19374:32
    at Object.exports.forEach (http://localhost:63342/rms/bower_components/vis/dist/vis.js:724:11)
    at ItemSet.redraw (http://localhost:63342/rms/bower_components/vis/dist/vis.js:19372:10)
    at http://localhost:63342/rms/bower_components/vis/dist/vis.js:18495:27
    at Array.forEach (native)
    at Timeline.Core._redraw (http://localhost:63342/rms/bower_components/vis/dist/vis.js:18494:21)
```
If I catch this error I got another one on line 22179 and when I catch the second (in a console.warn) all looks good.

How can i fix it ?

**Comment by blin4444** [comment]
I'm receiving similar errors after upgrading from 4.17.0 to 4.18.0. Needed to downgrade back to 4.17.0.

**Comment by yotamberk** [comment]
@jtissier @blin4444  can you please supply a jsbin with an example with this error popping up?

**Comment by mojoaxel** [comment]
Looking at [the subgroups example](http://visjs.org/examples/timeline/groups/subgroups.html) I can not reproduce this, by tracking any item to another group.
@@jtissier @blin4444 Please provide a way for us to reproduce this. Thx!

**Comment by jtissier** [comment]
I will try to provide you a jsbin soon

**Comment by blin4444** [comment]
It will be a bit difficult for me to do because I am using Vis commercially.

**Comment by yotamberk** [comment]
@jtissier @blin4444 any progress? I want to help but I can't reproduce it. I need your examples

**Comment by blin4444** [comment]
@blin4444 did you receive my emails? Thanks.

**Comment by jtissier** [comment]
Sorry I can not share the whole code and it is very difficult to reproduce this bug for now because I have to finish the project soon.

For now I just add some try/catch to prevent the error when I drag an item between groups and the script failed to calculate height of subgroup (probably because the subgroup has been removed dynamically in my code)

I updated to 4.18.1 and the same error occurs in line 25320 when I tried to show/hide groups depending on the showed items ( based on this code: http://jsfiddle.net/zwwspLnz/ ).

Like the old version, the error appears when the script tries to calculate the subgroup.  The line in vis.js is : 
`me.subgroups[item.data.subgroup].height = Math.max(me.subgroups[item.data.subgroup].height, item.height + margin.item.vertical);`

But this time it occurs during the dynamic load. I think I will try another way to hide groups.

**Comment by santacruzd7** [comment]
Hello everyone,

I believe I've encountered the same problem as you, but in a different use case. I'm currently using the VIS timeline to generate a timeline with groups and subgroups of events. Basically, the thing is that from time to time I need to remove events from the subgroups and rearrange the subgroups consistently

For instance, if I have the following setting:
- Event A (subgroup 0)
- Event B (subgroup 1)
- Event C (subgroup 2)
- Event D (subgroup 3)

And I remove the Event B, the following result is expected:
- Event A (subgroup 0)
- Event C (subgroup 1)
- Event D (subgroup 2)

as opposed to:
- Event A (subgroup 0)
-
- Event C (subgroup 2)
- Event D (subgroup 3)

I'm handling myself the update of the subgroups, but it seems that VIS isn't handling well the update of events, removing and re-adding subgroups and failing sometimes in re-adding deleted groups.

The following example demonstrates the problem. You will be able to see the error logs in the console:
https://plnkr.co/edit/LkRb8w6ndw5ijnPUnupb?p=preview

In addition to failing on the re-calculation of the height (it seems to have removed a group and not re-added it), for some reason, after the second click, the events in the second row (subgroup 1) get moved to the last row (subgroup 8).

Thank you very much for your help!

**Comment by Tooa** [comment]
@jtissier @santacruzd7 blin4444  can you please test the pull request https://github.com/almende/vis/pull/2821 and check if this solves your problems?

**Comment by santacruzd7** [comment]
Dear @Tooa,

I've tested the pull request and it solved my issue. Thank you very much :)

**Comment by blin4444** [comment]
@Tooa, I've tried the pull request and now I get the following error from vis.js line 29767:
`undefined is not an object (evaluating 'fieldId')`

**Comment by yotamberk** [comment]
@blin4444 please open a new issue with a jsbin of your example
