### ISSUE TITLE
Timeline - Zooming while also dragging items

### ISSUE THREAD

**Issue by thomasbarone** [almende/vis#2597]
There is an issue that occurs on the Timeline when using the CTRL key + mousewheel to zoom while simultaneously dragging an item. It causes the item being dragged to move erratically and often causes it to become way out of sync with the cursor. 

This can be seen while using this example:
[http://visjs.org/examples/timeline/editing/editingItems.html](http://visjs.org/examples/timeline/editing/editingItems.html)

Steps to reproduce:

1. Drag an item to the far right of the timeline
2. While continuing to hold down the left mouse button, zoom in by holding CTRL and using the mousewheel
3. Drag around the item some more, it should snap to a different position and be out of sync with the cursor

This problem appears to be more significant when dragging an item further away from the centre of the timeline.

**Comment by yotamberk** [comment]
@mojoaxel I don't think it's a PRIORITY bug. This happened also in older versions of vis. The fix is simple I think. I can call `dragEnd` event when scrolling while dragging.
@thomasbarone What would be the desired behavior?

**Comment by thomasbarone** [comment]
@yotamberk I guess the two simple choices would be to either call the `dragEnd` event to end the dragging when scrolling like you mentioned, or to disable scrolling completely during dragging, perhaps by adding a check to the `mousewheel` event handler.

Either of these would be acceptable I think.

**Comment by yotamberk** [comment]
fixed with #2645
