### ISSUE TITLE
Timeline - Tooltip flickers when dragging item to edge

### ISSUE THREAD

**Issue by thomasbarone** [almende/vis#2598]
This is a minor issue that occcurs when dragging an item with a tooltip across to the edge of the timeline so that its start date is before the visible date. It causes the tooltip to flicker.

This can be seen on the vis timeline tooltip example:
[http://visjs.org/examples/timeline/editing/tooltipOnItemChange.html](http://visjs.org/examples/timeline/editing/tooltipOnItemChange.html)

Steps to reproduce:

1. Select an item from the bottom timeline (under "With groups")
2. Drag it to the left so that the group name overlaps the item and drag it back and forth
3. The tooltip will flicker on each move

It would be better if the tooltip remained in place, similar to how the item's text content remains in place in this situation

**Comment by mojoaxel** [comment]
I can reproduce this:
![peek 2017-01-18 12-05](https://cloud.githubusercontent.com/assets/600565/22061693/77b99bb0-dd76-11e6-9d5c-c4fdc99e346a.gif)

It's really a minor issue!

**Comment by yotamberk** [comment]
Fixed with #2702

**Comment by mojoaxel** [comment]
fixed by @yotamberk with #2702
