### ISSUE TITLE
Can we have two types (box and point) in single timeline ? 

### ISSUE THREAD

**Issue by ihatecodinglikeking** [almende/vis#2607]
I am situation here, 
having type : box for some items,
                     point for some items 

I want to show only point items(No content) on X-axis as red color dot, 
If item is box type(has content) don't show in X-axis show content in timeline space. 

OR 

If No content present show it as point on X-axis with red dot
If Content present show it as general box type

----UPDATED-----

After some research on Timeline examples, If type is point there is no dot on X-axis, I can see dot only for box type, so by using only box can I achieve? 

---- UPDATED----
i tried like this 
`.vis-item.vis-dot {
    	display: none;
    }
    .indicator {
    	border-color: red !important;
    	display: flex !important;
    }`
in data side if no content i am adding this "indicator " but still I can see empty box on timeline with red border box and a line (with color) which is connected dot and container, So I want to remove container on graph so I can achieve, not sure how far its good...
 
Can we achieve this?

**Comment by lewisjb** [comment]
http://visjs.org/examples/timeline/styling/itemClassNames.html (it shows examples of styling each component separately).

Specifically you would want:
`.vis-item.vis-line.indicator, .vis-item.vis-box.indicator { display: none; }`

(With giving the empty ones `className: "indicator"`)

Please remember this for reporting bugs; for general questions, sites like https://stackoverflow.com are better.
