### ISSUE TITLE
Example: Images With Borders throws error

### ISSUE THREAD

**Issue by TrueFurby** [almende/vis#2609]
Official [example](http://visjs.org/examples/network/nodeStyles/imagesWithBorders.html) for **Images With Borders** shows this for me:

![screenshot_2017-01-20_11-33-08](https://cloud.githubusercontent.com/assets/1229233/22146310/7e4a421a-df04-11e6-8eb7-a66e9f07eee7.png)

Console throws this error: ```vis.js:36032 Uncaught TypeError: Cannot read property 'borderDashes' of undefined```

I tested on **ubuntu amd64** and I tried both Firefox and Chrome.

**Comment by Tooa** [comment]
Thanks for reporting this issue. Fixed by @denkiwakame with https://github.com/almende/vis/pull/2599.
