### ISSUE TITLE
[Timeline] Timeline.setGroups converts DataSet into DataView

### ISSUE THREAD

**Issue by hammock** [almende/vis#2612]
Hi there. When i use Timeline.setGroups like this:
```js
timeline.setGroups(new vis.DataSet(array));
```
`Timeline.groupsData` became an DataView instance ([lib/timeline/Timeline.js#L277](https://github.com/almende/vis/blob/master/lib/timeline/Timeline.js#L277)). Looks like an unexpected behavior for me. Is this needs to be fixed?

**Comment by yotamberk** [comment]
@hammock You are correct. We had to do this to be able to use a `visible` property to the group. It probably should be fixed but we currently don;t have a good solution. Do you have a solution?
