### ISSUE TITLE
Network - Navigation Zoom is broken (4.18)

### ISSUE THREAD

**Issue by Kokozzi** [almende/vis#2613]
After #2377 commit to 4.18 Zoom events for Navigation at Network module are broken. Example of it is active at official example page - http://visjs.org/examples/network/other/navigation.html

`Uncaught ReferenceError: pointer is not defined` - when trying to zoom in or zoom out with help of bottom buttons.

**Comment by Tooa** [comment]
I can confirm this issue. There is no pointer in the scope of the button events :/

**Comment by yoavdamri** [comment]
@Tooa, I saw it, in this case i can pass null (since the pointer is not relevant) or the translation x, y.
what do you think?

**Comment by Tooa** [comment]
Thanks for reporting this issue. Fixed by @CapitanMorgan with https://github.com/almende/vis/pull/2615
