### ISSUE TITLE
How to link a node to a url

### ISSUE THREAD

**Issue by Verlaet** [almende/vis#2616]
Hi,

my question would seem stupid but I don't write javascript.
I'd like to link each node to different URL by clicking on the node. How can I do that?

Thank you for your help! Liz

**Comment by CapitanMorgan** [comment]
Assuming you want to open a link on clicking of a single node you could do something like the example I included in this [jsfiddle.](https://jsfiddle.net/m3qrrjL7/6/) This example doesn't take into account multi selection of nodes. If you meant something else by this please clarify.

**Comment by Verlaet** [comment]
Exactly what I need! More over rapid and efficient! So great.
Thank you so much!
