### ISSUE TITLE
nestedGroups don't reorder correctly with AJAX

### ISSUE THREAD

**Issue by jtissier** [almende/vis#2619]
I am trying to dynamically add nested groups in my timeline after an AJAX response but I see two errors :

1. Even if I set the property "showNested: false" to my group the subgroups are still visible (I must click twice to hide them)

2. Nested groups appear AFTER all the main groups (see the screenshot)

![image](https://cloud.githubusercontent.com/assets/7328304/22213723/7ac61572-e195-11e6-8d3f-565306ffb30b.png)

**Comment by yotamberk** [comment]
@jtissier Thanks for reporting!

**Comment by jroetman** [comment]
After tracing through the code some, I was able to get this working by setting the property nestedInGroup on the subgroup AND pushing that group's id to the the parent group. I'm using the code from the dist of the npm install. 
 
Something like:
 groups.add({id : "parent1", content : "parent 1", nestedGroups: []})
 for each subgroup
      groups.add( { id: "sg1", content : "sg 1", nestedInGroup: "parent1"} )
      groups.get("parent1").nestedGroups.push("sg1")

If you just set the nestedInGroup property,  groups seemed to show up in the right place, but collapsing didn't work.

**Comment by yotamberk** [comment]
Cool! Thanks for sharing. I think we can close this issue and refer to the collapsing problem here: #2641
