### ISSUE TITLE
Timeline. Visible: false doesn't work for groups

### ISSUE THREAD

**Issue by waterplea** [almende/vis#2635]
I'm trying to hide empty groups from my timeline. For example, I create groups like that but they all are visible:

```
var groups = [];
for (i = 0; i < 5; i++) {
  groups.push({ id: i, content: 'Title', visible: false });
}
timeline.setGroups(groups);
```

**Comment by yotamberk** [comment]
@waterplea It works perfectly fine for me. Can you please supply a jsbin to show the problem?

**Comment by mojoaxel** [comment]
I also can not confirm this with 4.18.0: http://jsbin.com/tuduru/3/edit?js,output

**Comment by mojoaxel** [comment]
Nonetheless, an option `hideEmptyGroups` could be nicht feature request.
