### ISSUE TITLE
Vis timeline add custom button inside item

### ISSUE THREAD

**Issue by LAffairs** [almende/vis#2636]
I'm working with Vis timeline and I have a [Timeline](http://jsfiddle.net/e7uodse2/1066/)

I don't know if is possible or not but does vis timeline support adding custom button in the right side inside items like item 4 (for example) that only displays a message on click?

**Comment by yotamberk** [comment]
Hi @LAffairs , You can add any html you want to the item itself. Checkout: http://visjs.org/examples/timeline/items/htmlContents.html
