### ISSUE TITLE
Custom class-names not working as expected

### ISSUE THREAD

**Issue by oatesch** [almende/vis#2637]
Supplying classnames like "color-pro-notstarted", have to change
`if (e[6].qNum)`
for
`if (0)`

to work as expected.

**Comment by yotamberk** [comment]
@oatesch This is really unclear... Can you supply an example?

**Comment by oatesch** [comment]
@yotamberk established cause of problem was outside vis, closed issue.

**Comment by yotamberk** [comment]
Okey dokey.
