### ISSUE TITLE
Relative rolling mode timeline

### ISSUE THREAD

**Issue by seantrace** [almende/vis#2638]
Is it possible to create a rolling mode timeline which starts at 00:00:00 and shows time relative to a point in time when it is started rather than being always centred on the current time?

**Comment by yotamberk** [comment]
@seantrace not yet. But this could be a nice feature request!

**Comment by brichbe** [comment]
@seantrace Something like [this](http://jsfiddle.net/6Lcsany1/4/)?

**Comment by seantrace** [comment]
@brichbe This is exactly what I was after. Thanks for the assistance.

**Comment by brichbe** [comment]
Minor update to include a small fix I forgot about before posting yesterday:  http://jsfiddle.net/6Lcsany1/9/

Please close this issue if these examples address your question.

**Comment by seantrace** [comment]
I found and fixed that, but thanks. Am I allowed a supplementary question? I would also like to be able to pause the timeline which I could do by taking away an addition accumulated delta (restart time - pause start time). However there does not appear to be a way to exit rollingMode. _setOptions(options)_ does not appear to work for rollingMode. I tried calling _timeline.range.stop/startRolling()_ which almost does what I am after but this is not part of your public interface! Any pointers on a legitimate way to achieve this?

**Comment by brichbe** [comment]
@seantrace I hadn't tried that before, but I agree that setting `rollingMode` back to `false` via the options is not working as one would expect, so it does indeed appear to be a bug.

@yotamberk Did you test this when `rollingMode` was implemented?  This mode should be able to be toggled back and forth programmatically, not just an initialization setting.

**Comment by yotamberk** [comment]
@seantrace Please open a new issue for the second question and we'll tag it as a feature request.

@brichbe No. It can be added in a feature request. It will be very easy to do.
