### ISSUE TITLE
Radius around node

### ISSUE THREAD

**Issue by Alex-Dim** [almende/vis#2639]
Is there any way to draw radius around some node, for example this radius represent some field of influence around node?
Thank in advance.

**Comment by Alex-Dim** [comment]
What i have done:
first inside function addNode() i added "globalData" global var that collects id of node:

function addNode() {
	globalData = document.getElementById('node-id').value;
            try {
                nodes.add({
                    id: document.getElementById('node-id').value,
                    label: document.getElementById('node-label').value
                });
            }
            catch (err) {
                alert(err);
            }
 }

After i drew node , this on network is called:

	  network.on("afterDrawing", function (ctx) {
	
			if(globalData != "") {
				console.log(ctx);
				nodePosition = network.getPositions([globalData]);
				console.log(nodePosition);
				ctx.strokeStyle = '#A6D5F7';
				ctx.fillStyle = '#e5ffe5';
				ctx.globalCompositeOperation="destination-over";
				ctx.circle(nodePosition[globalData].x, nodePosition[globalData].y,70);
				ctx.fill();
				ctx.stroke();
				globalData = "";
			}
		  });

        }

BUT it don't draw canvas , where is problem ???

**Comment by Alex-Dim** [comment]
I solved this problem :
```

		  network.on("afterDrawing", function (ctx) {
				console.log(nodes);
				/*console.log("nodes._data");
				console.log(nodes._data);
				console.log(nodes._data);*/
				for(i=1;i <= nodes.length;i++) {
					if(typeof nodes._data[i] != "undefined") {
						console.log(nodes._data[i].id);
						idVal = nodes._data[i].id;
						nodePosition = network.getPositions([idVal]);
						ctx.strokeStyle = '#A6D5F7';
						ctx.fillStyle = '#e5ffe5';
						ctx.globalCompositeOperation="destination-over";
						ctx.circle(nodePosition[idVal].x, nodePosition[idVal].y,70);
						ctx.fill();
						ctx.stroke();
					}
				}
			
		  });
```

**Comment by yotamberk** [comment]
Cool! Thanks for sharing!
