### ISSUE TITLE
Issue collapsing the groups

### ISSUE THREAD

**Issue by priyankabinani** [almende/vis#2641]
Hi,

I am using nestedGroups and I am trying to collapse all the nested groups by using showNestedGroups: false. But looks like this is not working. Any pointers?

Thanks!

**Comment by mojoaxel** [comment]
@priyankabinani The [official example](http://visjs.org/examples/timeline/groups/nestedGroups.html) seams to work. Can you please provide your code that causes the problem (e.g. at jsbin.com).

@yotamberk Can you please take a look at this.

**Comment by priyankabinani** [comment]
Hi,

Thanks for your quick reply. Looks like this is part of v4.18.1 I am using 4.18.0 which I got from the official download page: http://visjs.org/#download_install. Can you tell me where can I get the latest version of vis. 

Thanks!

**Comment by priyankabinani** [comment]
Oops.. just saw that would it be ready by - January 29, 2017. I will wait for it then. Hopefully I can download it from the main download page.

**Comment by yotamberk** [comment]
I don't see a problem... I will have to have an example that doesn't work and study it.
@priyankabinani please supply an example jsbin with the problem and we will solve it ASAP

**Comment by brichbe** [comment]
The confusion here may be due to the documentation saying the property is `showNestedGroups`, but the implementation expects `showNested` ...

**Comment by priyankabinani** [comment]
Thanks brichbe! That was exactly the issue the documentation for showNestedGroups says - "Assuming the group has nested groups, this will set the initial state of the group - shown or collapsed."
I used the nestedGroups and works. Thanks for all your inputs. Vis is awesome library!

**Comment by yotamberk** [comment]
@brichbe thanks for the clarification! We will fix this in the docs ASAP

**Comment by mojoaxel** [comment]
@yotamberk Is this fixed? Can you please link the PR number. Thx!

**Comment by tatsujb** [comment]
despite using showNested I can't programatically tell the timeline to reveal or hide nested, for me it can only be done via a click on the category labels  :  https://github.com/almende/vis/issues/3335#issuecomment-380089122
