### ISSUE TITLE
creating data samples for the different or custom timelines

### ISSUE THREAD

**Issue by weedkiller** [almende/vis#2642]
Hi, first this is a wonderful lib, the data format is a little confusing. In my case I cant figure out what/how to format and send, an icon, grouping of events by activity, where the _display content items could change by date._

For e.g. how to handle different goups of information with different icons by date
10/31/2016
-  Alert! 10 robberies 
-  Ozone green level
-  Weather rain

1/1/2017
-  Ozone green level
-  Weather rain
-  Schools closed
-  Puppy day

For someone new it would help if there were a few JSON data samples posted, for styling, and grouping, both on timelines and networks.

thanks

**Comment by brichbe** [comment]
http://visjs.org/timeline_examples.html    All the source code for these examples is available for you to read and learn from.

**Comment by weedkiller** [comment]
I was looking at that, but a sample for clustering dynamic events for timelines was missing, or perhaps I was not able to figure out which one..

so, let me explain, For e.g. every morning user may want to see news, mail and inbox alert items, which are dynamic (alerts show up now, but the actual data in the bubble may relay later, based on available information updated) - I want to show them and only when it occurs or bubble up when user click on them.

**Comment by yotamberk** [comment]
Clustering is not supported yet on the timeline.

**Comment by yotamberk** [comment]
clustering of items has been requested in #242
closing this issue.
