### ISSUE TITLE
How can I retrieve the current status of the showNestedGroups property when a user clicks on it?

### ISSUE THREAD

**Issue by JorisPhilipsen** [almende/vis#2659]
I want to be able save the users UI state in the local storage. I'm currently using something like this:

```
this.timeline.on("click", function (params) {
        if(params.group == 0) {
            //...
        }
});
```

**Comment by brichbe** [comment]
Yeah, unfortunately there is no documented way to do that currently.  This will need to be a feature request so that the visibility state of nested and non-nested groups can be retrieved dynamically and/or emitted during relevant events

**Comment by yotamberk** [comment]
@JorisPhilipsen you have the groups' data. When you toggle a nesting group, the `showNestingGroups` will toggle and if you look at the groups' data you should see the state of the groups and save that to local storage.

**Comment by brichbe** [comment]
@yotamberk can you verify that?  On a click event I'm logging the groups dataset and I see that the nested groups have `visible` and `nestedInGroup` properties that top-level groups do not have, but I'm not seeing the top-level groups' `showNested` property being toggled.

**Comment by yotamberk** [comment]
@brichbe yeah.. you're right... I'll have to check it out. Give me a few days, I have a lot of other things I'm working on.

**Comment by JorisPhilipsen** [comment]
I've currently solved the problem in the following manner.

```
this.timeline.on("click", (params) => {
        if(params.group == 0) {
            //true
        } else if (params.event.target.innerText === "Nameofgrouphere") {
            // false
        }
        
});
```

It works well for my simple use case but it's not an ideal solution. I'm a big fan of the vis.js library and thank you for your quick replies!

**Comment by yotamberk** [comment]
I think we can close this issue. If you want this as a feature request, please open a new issue and describe the feature.
