### ISSUE TITLE
Calculate width of an item being added

### ISSUE THREAD

**Issue by jroetman** [almende/vis#2661]
I'm attempting to create some items using d3js. The only issue I'm having is determining the width of my svg canvas.

Are there methods exposed to calculate the width of an item being added?

I'm adding new items through a template as follows: 

```
 template: function(item, element) {     
   ...
   return ReactDOM.render(<d3Template item={item} />)
   ...
 }
```
Element doesn't seem to be what I want.  Ideally I could do this:
```
 var width = getItemWidth(item)
 return ReactDOM.render(<d3Template width={width} item={item} />)

```

**Comment by mojoaxel** [comment]
@jroetman You know...this is vis.js and not d3.js !?

**Comment by jroetman** [comment]
I shouldn't have mentioned d3, I was just trying to give context. I just wanted to know if there was a way to get the calculated with for a given item.
