### ISSUE TITLE
Change Icon size for each node dynamically

### ISSUE THREAD

**Issue by zheyong91** [almende/vis#2664]
Hi all,

I am putting this question out to the floor because i can't find any solution to this question.

What i need to do is to change the node size of a particular node based on some algorithm. The problem is , setting node.size works when the node's shape is image, but it does not work when the node's shape is an icon. Any work around for this?

**Comment by mojoaxel** [comment]
see
* https://github.com/almende/vis/issues/2082#issuecomment-245913285
* https://github.com/almende/vis/issues/2088#issuecomment-246280457
* https://github.com/almende/vis/issues/2298#issuecomment-259921322
* http://visjs.org/examples/network/labels/labelMargins.html
* http://visjs.org/examples/network/data/scalingNodesEdgesLabels.html

**Comment by zheyong91** [comment]
Thanks @mojoaxel for the links. But j am referring to this issue. https://github.com/almende/vis/issues/989

**Comment by mojoaxel** [comment]
@zheyong91 Ah, I see. Sorry! 
Still a duplicate of #989
