### ISSUE TITLE
Ordering in timeline

### ISSUE THREAD

**Issue by 4integration** [almende/vis#2666]
Hi,

I might be tired or stupid...I want to get timeline items to be ordered by Id with lowest Id on top. Please advise

**Comment by brichbe** [comment]
http://visjs.org/examples/timeline/items/itemOrdering.html

**Comment by 4integration** [comment]
I have tried it:

  function orderById (a, b) {
    // order by id
    return a.id - b.id;
  }	
and 

	var options =  {
		order: orderById,
		start: startTime,
		end: endTime,
		editable: false
	};

I strictly want the item ID =1 at top and ID=2 next etc

**Comment by yotamberk** [comment]
@4integration please supply a jsbin so we can see better

**Comment by 4integration** [comment]
I am not very used to jsbin so cannot it to work at all (not sure if/how to link the JS to HTML or if that done automatically) but here it is:
https://jsbin.com/lalaranimu/edit?html,js,output

**Comment by yotamberk** [comment]
@4integration I don't see the problem... It looks ordered by id

**Comment by yotamberk** [comment]
@4integration You've forgot to include visjs to the jsbin so the example doesn't work.
In the second example, the items are position correctly. The items are not colliding so they shouldn't be higher than `Test 2.3`. 
The first example does seem to be incorrect.

**Comment by 4integration** [comment]
Strange JSBin have 
<script src="https://cdnjs.cloudflare.com/ajax/libs/vis/4.18.1/vis.min.js"></script> on HTML

https://jsbin.com/naruvagisa/1/edit?html,output

Ok, I understand about the second example where they are not colliding. But if I want them to be strictly ordered by Id - is that possible?

**Comment by brichbe** [comment]
Yes, by setting a unique `subgroup` value for each of your items, declaring the group they belong to and specifying its `subgroupOrder`, and setting the timeline to disable stacking (and removed using `orderById`).

I modified your Test 1:  https://jsbin.com/yuyejumelu/1/edit?html,output

**Comment by 4integration** [comment]
@brichbe Thanks that did the trick, thanks

**Comment by bradh** [comment]
Sounds like the OP has a solution. Suggest closing.
