### ISSUE TITLE
Vis Network Manipulation Buttons: change focus on click?

### ISSUE THREAD

**Issue by FilipQL** [almende/vis#2668]
I am creating an app using [Vue.js](https://vuejs.org/) and [Vis.js Network](http://visjs.org/docs/network/). I have one text field (HTML input element) above the graph. When this input element has focus, when I click on any button on the [Manipulation toolbar](http://visjs.org/docs/network/manipulation.html), this text field still has focus:

![ovs mesh google chrome 2017-02-02 00 21 13](https://cloud.githubusercontent.com/assets/18264428/22531120/56c7f98c-e8df-11e6-8abd-c71f9b78e655.png)

I've tried the following:

```
var container = document.getElementById('mynetwork');

container.onclick = function () {
    document.activeElement.blur();
};
```
... but it doesn't work (actually it works for everything but toolbar buttons). I've also tried the following:

```
var visButtons = document.getElementsByClassName('vis-button');
visButtons.onclick = function () {
    document.activeElement.blur();
};
```
... but without success. Do you have any suggestions how I could solve this? Here's the one simple (without Vue) example where you can test and see: https://jsfiddle.net/Filip_Z/pruaeLgq/

**Comment by Tooa** [comment]
[Here](https://github.com/almende/vis/blob/master/lib/network/modules/ManipulationSystem.js#L681) are the relevant parts of the code that create these buttons. CSS is defined [here](https://github.com/almende/vis/blob/master/lib/network/css/network-manipulation.css#L57). Haven't investigated yet. Can you see any problem?

**Comment by wimrijnders** [comment]
Closed due to inactivity. Feel free to reopen if this is still relevant.
