### ISSUE TITLE
[Timeline] Vertical group labels

### ISSUE THREAD

**Issue by fstefani** [almende/vis#2669]
![image](https://cloud.githubusercontent.com/assets/1169746/22558424/e96b3c34-e96d-11e6-92c7-561699f87284.png)

I would like to align group labels like the image above and keep them centered, both vertically and horizontally, if someone adds new items to the group. Is there a way to achieve that right now?

Thank you for your help,
Francesco

**Comment by yotamberk** [comment]
you can do this with Css..
play around with: `transform: rotate(270deg);` and flexbox to get it aligned to the center.
