### ISSUE TITLE
Timeline itemover / itemout do not pass through the original event

### ISSUE THREAD

**Issue by tomdcc** [almende/vis#2672]
Version 4.18.1.

Event callbacks registered for `itemover` / `itemout` do not get the original mouse event as the `event` property on the passed `props` object. Instead they seem to get an object whose value is `{isTrusted: true}`.

This stops us from implementing a more custom hover mechanism using the mouse position to place the hover as we don't have access to the original mouse position.

**Comment by mojoaxel** [comment]
@yotamberk Can you have a look please. We have to be careful with the events!

**Comment by yotamberk** [comment]
Sure. I have a list of thing i need to get to. Hopefully tonight/tomorrow

**Comment by mojoaxel** [comment]
> Sure. I have a list of thing i need to get to. Hopefully tonight/tomorrow

No rush! But i thing you are the master of the timeline events, now ;-)

**Comment by yotamberk** [comment]
solved in #2704
