### ISSUE TITLE
Network clustering: Cannot read property 'font' of undefined

### ISSUE THREAD

**Issue by AoDev** [almende/vis#2677]
Hi, I have basically copied the example of clustering [here](https://github.com/almende/vis/blob/master/examples/network/other/clustering.html).

Just using my own data.

when initiating the graph
```
var container = document.getElementById('#network')
this.graph = new vis.Network(container, {}, graphOptions)
```

When getting the data (before, I add a group property to each node)
```
    this.graph.setData(graphData)

    var groups = ['group1', 'group2', 'group3']
    var clusterOptionsByData
    for (var i = 0; i < groups.length; i++) {
      var group = groups[i]
      clusterOptionsByData = {
        joinCondition (childOptions) {
          return childOptions.group === group
        },
        clusterNodeProperties: {
          id: 'cluster:' + group,
          borderWidth: 3,
          shape: 'dot',
          color: '#000',
          label: 'group:' + group,
          font: {
            color: '#000',
            size: 14
          }
        }
      }

      this.graph.cluster(clusterOptionsByData)
    }
```

My graph config
```
const graphOptions = {
  physics: false,
  edges: {
    arrows: 'to',
    physics: false,
    scaling: {
      min: 1,
      max: 5,
      label: {
        enabled: false
      }
    },
    smooth: {
      enabled: false,
      type: 'cubicBezier',
      forceDirection: 'vertical',
      roundness: 0.5
    }
  },
  nodes: {
    shape: 'dot',
    scaling: {
      min: 10,
      max: 30,
      label: {
        enabled: false
      }
    },
    font: {
      strokeWidth: 2,
      strokeColor: '#fff',
      multi: 'html'
    }
  },
  layout: {
    improvedLayout: true,
    hierarchical: {
      enabled: true,
      levelSeparation: 150,
      nodeSpacing: 200,
      treeSpacing: 200,
      blockShifting: true,
      edgeMinimization: true,
      parentCentralization: true,
      direction: 'UD',        // UD, DU, LR, RL
      sortMethod: 'directed'   // hubsize, directed
    }
  }
}
```

Stacktrace:
```
TypeError: Cannot read property 'font' of undefined
    at Label.propagateFonts (vis.js:34775)
    at Cluster.setOptions (vis.js:34226)
    at Cluster.Node (vis.js:34126)
    at new Cluster (vis.js:43598)
    at NodesHandler.create (vis.js:33809)
    at ClusterEngine._cluster (vis.js:42959)
    at ClusterEngine.cluster (vis.js:42556)
    at Network.cluster (vis.js:33010)
```

I believe it breaks in Label, [here](https://github.com/almende/vis/blob/1af850327f47f15585d0efd496b83da27890acdd/lib/network/modules/components/shared/Label.js#L134)
because for some reason options was not passed / is undefined.

**Comment by mojoaxel** [comment]
@AoDev Thanks for the details problem description. But I can not reproduce this problem with your example-code: http://jsbin.com/foyufig/1/edit?html,js,console,output

Can you please try to reproduce the error in a public jsbin. Thanks.

**Comment by AoDev** [comment]
Thanks, I'll try tomorrow.

What I can say is, by removing the `nodes.font.multi` from my config, which is currently set to `html` currently, then it will render the cluster properly. Mainly because this `propagateFonts` seems to run only when the multi option is set.

**Comment by Tooa** [comment]
Please provide us a minimal example via [jsbin.com](jsbin.com) showing the error and explain how to reproduce the issue.

**Comment by AoDev** [comment]
@Tooa http://jsbin.com/vorozibulo/edit?html,js,console,output @mojoaxel jsbin was missing the grouping.
<img width="960" alt="screen shot 2017-02-16 at 12 56 13" src="https://cloud.githubusercontent.com/assets/1526150/23020421/55248fa0-f447-11e6-8750-377a6ec4c536.png">

**Comment by wimrijnders** [comment]
@Tooa Are you going to pick this issue up again?

**Comment by arunkumarpro1** [comment]
@wimrijnders I am still getting this error? Is this fixed already?

**Comment by wimrijnders** [comment]
@arunkumarpro1 I just scanned the issues; I am under the impression that this was fixed with #3025 and released in `vis v1.20.0`. Are you using this version or later?

If not, the work around is setting option  `options.nodes.font.multi: false`.

Please notify me about the `vis`-version used, and if given workaround works. If this does not solve it, I may need to look at this issue in-depth.

**Comment by arunkumarpro1** [comment]
@wimrijnders I am using vis v4.20.1. 

Yes the given workaround works fine for me.  I can set options.nodes.font.multi to false for now. 
Thanks a lot :+1:

**Comment by wimrijnders** [comment]
OK good. However, it worries me that this still occurs. Will dive into this issue regardless.

**Comment by arunkumarpro1** [comment]
Yes. That would be really great.

**Comment by wimrijnders** [comment]
@arunkumarpro1 No fix yet, I'm on vacation and can not investigate.

As a workaround, have you tried option `nodes.font.multi: false` yet?

**Comment by arunkumarpro1** [comment]
Yes, I have. The given workaround is fine for me.


Arun Kumar Balasubramani

Graduate Student

Masters of Science in Computer Science

The University of Texas at Dallas

Contact: 214-803-6781

________________________________

**Comment by wimrijnders** [comment]
@arunkumarpro1 There is a fix for this issue. Will be in the next release.
