### ISSUE TITLE
Images for nodes

### ISSUE THREAD

**Issue by dponch** [almende/vis#268]
Hi,

I have a question. I put a svg image for a node, but when I zoom in it lost the qualiaty as png images.
Is it normal? Can I do something to avoid this?

Thanks,
Guillermo

**Comment by dponch** [comment]
Hi Alex and Happy New Year,

I'm not familiarized with git and I couldn't do it, sorry :(
Hope this is not a problem.

Thanks,
Guillermo

**Comment by AlexDM0** [comment]
Hi Guillermo,

That's fine, I've put the code in now. It will be included in the next release.

Regards,

Alex

**Comment by JonathanLafey** [comment]
Using the same [jsfiddle](http://jsfiddle.net/Ljow3r2u/12/) dpoch posted, I found that only cached svgs are working. If you run the fiddle in IE or Edge for the first time (or after a cache clear) the svg will not show and you'll need a refresh for them to appear correctly. I don't know if this is a reason to reopen the issue, I just thought that I should report it.
