### ISSUE TITLE
Doubleclick event not fired on a datapoint if timeline.editable is set to true

### ISSUE THREAD

**Issue by terenceyw** [almende/vis#2680]
#1127 said this was fixed but I still have this issue

As title says doubleclick event when you doubleclick a datapoint will only fire if the timeline is not editable. 

A workaround I tried is to set the timeline to non-editable but individual data points editable.  However when editable is true for a data point, updateTime (horizontal dragging) is false,  which I need.

**Comment by yotamberk** [comment]
@terenceyw Can you please supply a jsbin? It would help to isolate the problem with an example

**Comment by terenceyw** [comment]
https://jsbin.com/soqesuguqi/1/edit?html,output

First one is when timeline editable is true, double click event only registered when doubleclicking outside points not on points

https://jsbin.com/nutavodumi/edit?html,output

Second one when timeline editable is false, and item 4 editable is true, updateTime is false which I need to be true.
