### ISSUE TITLE
Timeline: Feature request: zoomIn/zoomOut methods accept same animation options as e.g. setWindow

### ISSUE THREAD

**Issue by tomdcc** [almende/vis#2689]
Could then just pass on to setWindow call. This would occasionally be useful to zoom immediately or slow down the animation (our app has a "slow-animations" mode to help debug rendering issues).

**Comment by tomdcc** [comment]
Alternately, for the second use-case, a way to set the default animation options would be very useful.

**Comment by yotamberk** [comment]
@tomdcc  see #2830
