### ISSUE TITLE
update webpack and babel

### ISSUE THREAD

**Issue by mojoaxel** [almende/vis#2694]
We should change the build process to leverage the new features introduced in webpack v2

**Comment by AoDev** [comment]
Would you ditch `gulp`? it seems rather useless when you have webpack + npm.

**Comment by mojoaxel** [comment]
> Would you ditch gulp?

With gulp everything is in one place at the moment. I have no problem replacing gulp with some nice well-structured npm-scripts, but I'm not investing time in this at the moment.

**Comment by primozs** [comment]
I had no issues with webpack2 versions:
```
    "webpack": "2.1.0-beta.27",
    "webpack-dev-server": "v2.1.0-beta.12",
```

Now with
```
    "webpack": "^2.2.1",
    "webpack-dev-server": "^2.4.1",
```
I am having same problems related to this https://github.com/webpack/webpack/issues/4039
I made simple example if somebody has any idea what could be the problem. 

error:
```
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Object.eval (ItemSet.js:2296)
    at eval (ItemSet.js:2298)
    at Object.../node_modules/vis/lib/timeline/component/ItemSet.js
```
example:
https://github.com/primozs/vis-example-webpack2

**Comment by mojoaxel** [comment]
> I made simple example if somebody has any idea what could be the problem.

Thanks!! I'll check it out after the next release.

**Comment by mojoaxel** [comment]
I've created a branch [webpack2](https://github.com/almende/vis/tree/webpack2). The vis.js build works but shows a deprecation warning at the moment. We should wait until this warning is resolved to prevent tons of bug-reports.

```
(node:21441) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
```

We should monitor the following issues and wait until they are fixed: https://github.com/babel/babel-loader/pull/391 and https://github.com/babel/babel-loader/issues/392

**Comment by mojoaxel** [comment]
By the way the vis.js filesize changed with webpack 2 from 1722353 to 1623284 what is an reduction of 100k or -6%. 
And I'm sure there is still room for optimization.

**Comment by AoDev** [comment]
Hi, please have a look at this issue, which is related: https://github.com/almende/vis/issues/2934

**Comment by wimrijnders** [comment]
With #3262, `webpack v2.0.0` has been added to `package.json` and will be enabled next release.

The depreciation warning mentioned above has been examined and deemed harmless, see the discussion in #3262.

For all intents and purposes, current issue has been resolved and I am therefore closing it.

**Comment by mojoaxel** [comment]
Thanks @wimrijnders 
We should propably update webpack to a even more recent minor version and also update the webpack-config and babel-plugins.
See 8ea9906a46a12222f0ef2a300da0db3198b5ccfa

**Comment by wimrijnders** [comment]
OK, will scan all modules for latest stable versions.

I indeed do the minimal updates necessary for other issues to get a working setup. Might as well go all the way.

**Comment by mojoaxel** [comment]
The [webpack syntax changed a little](https://webpack.js.org/guides/migrating/) since webpack 2. Be aware!

**Comment by wimrijnders** [comment]
@mojoaxel I already fixed the syntax. All works fine right now.

**Comment by mojoaxel** [comment]
LGTM
