### ISSUE TITLE
Timeline groupsData.update() not working in 4.18.1

### ISSUE THREAD

**Issue by stoyanmkd** [almende/vis#2698]
Hi, guys, thanks for improving this wonderful library!

I've just updated from visJs 4.17.0 to 4.18.1 and noticed groupsData.update() in Timeline module's not working  anymore. At the same time itemsData.update() is working like a charm.

Example:
[https://jsbin.com/yomecikila/edit?html,js,output](https://jsbin.com/yomecikila/edit?html,js,output)

Cheers,
Stoyan

**Comment by brichbe** [comment]
https://jsbin.com/jadaparofa/1/edit?html,js,output

You need to use the public/documented APIs, which means using update() of the DataSets you supplied to the timeline.

**Comment by stoyanmkd** [comment]
Thank you!
