### ISSUE TITLE
Numerical Y-Axis in Timeline

### ISSUE THREAD

**Issue by VRspace4** [almende/vis#2699]
Hi, is it possible to configure the Y-Axis to be numerical in the timeline control so that the items can be dragged freely not only horizontally but also vertically?

**Comment by yotamberk** [comment]
@VRspace4 I really don;t understand what you mean. Can you supply an illustration?

**Comment by yotamberk** [comment]
Oh I think I understand what you mean. In the group itself to have control on it's height?
If so, the answer is no. But, you can control the `order` of items. You can give items a value (say "priority") and order it by that value.
Does this help?
If you want something more sophisticated, we can make it a Feature request

**Comment by VRspace4** [comment]
@yotamberk, this is exactly what I was looking for, http://visjs.org/examples/graph2d/07_scrollingAndSorting.html, but instead of the freeform 2d lines, my project requires simple boxes that can be freely dragged around.

Is this possible in the Graph2d? I don't see any examples with the ability to drag and drop graph elements/items around.
