### ISSUE TITLE
Modify the doc to link verticalScroll and maxHeight options

### ISSUE THREAD

**Issue by CharlesNo** [almende/vis#2713]
Hello,

I think you should put on the documentation http://visjs.org/docs/timeline/ that if verticalScroll is true maxHeight should be set. (verticalScroll alone don't do anything without maxHeight).
I know it's obvious but it can save a minute.

**Comment by bradh** [comment]
Do you mean at https://github.com/almende/vis/blob/master/docs/timeline/index.html#L1137 ?

Perhaps you could create a Pull Request for the change you expect to see?

**Comment by CharlesNo** [comment]
Hello,

I hope I did it right, first time I do it. My pull request can be seen on the list of pull requests (I think).

Thanks for the link and advice. :)

**Comment by wimrijnders** [comment]
Closed because related PR's #2717, #2718, #2719 have all been closed.
