### ISSUE TITLE
Q, How do I force redraw of the edges after moving nodes w/o physic

### ISSUE THREAD

**Issue by BTooLs** [almende/vis#2715]
Hello, first of all good job!

I have a small issue, I have nodes (A and B). Between them an edge, is a straight line. 
After I move the node B in the opposite side (180 around A), the edge is curved now.
The physics module is disabled (otherwise this problem wouldn't exists), the nodes are manually positioned.
How do I force the edge to be recalculated/redraw for the new positions after moving nodes (without remove/reaadd it)?

Thanks.

later edit: If I activate the physics, only for edges, it fixes the problem, any other way to force this behaviour?

**Comment by Stexxen** [comment]
I'm not 100% but I think if you recalculate and set the length of the line based on the distance between the 2 nodes after moving, this may solve your problem.

**Comment by wimrijnders** [comment]
If I understand correctly, you have physics disabled but want straight lines between nodes when dragging.

In that case, try this in the options:

```
var options = {
  "edges": {
    "smooth": {
      "type": "continuous",
      "forceDirection": "none",
      "roundness": 0              // <===
    }
  }
}
```
Setting `roundness: 0` forces the lines to be straight.

**Comment by BTooLs** [comment]
![chrome_2017-04-12_13-32-47](https://cloud.githubusercontent.com/assets/830001/24953653/c26f2670-1f84-11e7-8099-e8367408f9c1.jpg)
I meant this happens when no physics and rounded edges. I don't know if is a bug or not.

@wimrijnders yes that fixes it, but I didn't wanted straight lines, but this will do.

**Comment by wimrijnders** [comment]
Ah, OK. In that case `type: 'continuous'` should be enough. Leave param `roundness` out.

**Comment by BTooLs** [comment]
Thanks, that was the flag I was looking for.
