### ISSUE TITLE
Editable issue

### ISSUE THREAD

**Issue by CodeTroopers** [almende/vis#2720]
The css class vis-editable is always applied on items althought the editable property is set to false.
See this [plunkr](http://plnkr.co/edit/faL6epsZ0Tj10lYmGZKx?p=preview)
The property is converted in object in item constructor :
` if (this.data && this.data.hasOwnProperty('editable')) {
      if (typeof this.data.editable === 'boolean') {
        this.editable = {
          updateTime: this.data.editable,
          updateGroup: this.data.editable,
          remove: this.data.editable
        };
      } `

but it used as property in the draw function

**Comment by yotamberk** [comment]
You're right. Will be fixed

**Comment by bradh** [comment]
I've got a somewhat related fix in https://github.com/almende/vis/pull/2737 however after reading this, I'm not sure I really understand how `editable` in the `data` properties is supposed to work with `editable` in the `option` properties.

What is the truth logic that is intended?

**Comment by RealRegatta** [comment]
I think `editable` in the `data` override `editable` in the `option` unless `editable.overrideItems` is set to true.
If editable is an object then each property override each property of object `editable` in the `option`

**Comment by bradh** [comment]
I agree. I've submitted a revised PR with more extensive tests.

**Comment by mojoaxel** [comment]
This was fixed by @bradh with #2743. Thanks!
