### ISSUE TITLE
Vis Timeline: setOptions height is resetting orientation

### ISSUE THREAD

**Issue by Rockson** [almende/vis#2725]
Hello, thanks for your awesome work.
I had problem changing the height of the timeline when orientation.item = 'top'. It looks like it's resetting orientation.item to its default value (bottom).
`timeline.setOptions({height: "400px"})`

**Comment by Rockson** [comment]
Moreover i think that if orientation.item = "top" this css should be applied.
> .vis-background{
> 	bottom: auto !important;
> 	top: 0 !important;
> }

Because if the height of the timeline is higher than the vis-itemset height,  background items that don't belong to a group won't be showed correctly.

**Comment by yotamberk** [comment]
Can you supply a working example? It would be easier to examine

**Comment by Rockson** [comment]
Sure

> Moreover i think that if orientation.item = "top" this css should be applied.
> 
> .vis-background{
> bottom: auto !important;
> top: 0 !important;
> }
> Because if the height of the timeline is higher than the vis-itemset height, background items that don't belong to a group won't be showed correctly.

Remove the CSS fix and you'll se the problem
https://jsfiddle.net/r33j3033/

> I had problem changing the height of the timeline when orientation.item = 'top'. It looks like it's resetting orientation.item to its default value (bottom).
> timeline.setOptions({height: "400px"})

Click the **first** button and you'll see that the vertical alignment of the group has changed.
Moreover after clicking the first button click above group1, the library will throw an error in the console.
While if you click the **second** button( "+ orientation") the alignment won't change.

https://jsfiddle.net/kzy7jgf2/1/

**Comment by yotamberk** [comment]
@Rockson There error occurs because you loaded a huge range of years, and while trying to zoom out, the timeline is trying to draw all the lines of the timescale. because it is limited to 1000 lines, it crashes...

In terms of the bugs: Their seems to be the same bug with previous versions. I'll try to check it out the next few days.

**Comment by Rockson** [comment]
@yotamberk 
https://jsfiddle.net/r33j3033/5/
https://jsfiddle.net/kzy7jgf2/3/

Maybe I misunderstood you, by the way I've changed the range of those examples with a smaller one, the bug persists.

**Comment by yotamberk** [comment]
@Rockson The second example seems to have been solved! (checkout the newest version of vis (v4.18.1)
The first example is a different issue from the original title. But I solved it here: #2831
