### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by adamgalmor** [almende/vis#2726]
Hello

Im using the visjs V4.18.1 timeline graph in my Ionic2 app.
Even though I destroy the graph on my control distractor, I can see a this memory leak (only on my Android device):

![image](https://cloud.githubusercontent.com/assets/2060170/22967122/d0bf568e-f36d-11e6-814d-5d043fb7d564.png)

**Comment by yotamberk** [comment]
Thanks for reporting! Does this happen in other devices? Did this happen to you in previous versions?

**Comment by adamgalmor** [comment]
Yes, after further analysts I did found it happens when I "ionic serve" my app and run it on my PC.
Before, I noticed it on a Samsung Galaxy S5 ruining Android 5.0.1 OS.
As you can see this is a very small leak (~100kb) so my leak is probably related to something else (e.g. the Ionic framework, my code etc...) but I thought you might be interested in my findings to.
