### ISSUE TITLE
Template with editing item

### ISSUE THREAD

**Issue by RealRegatta** [almende/vis#2727]
In the timeline, the template function can not use the editing item to display modifications
In this [plunkr](http://plnkr.co/edit/aE6RLeuJaby4WiFcnmIu?p=preview), I wish display the edited tminus property during the edition phase (it is displayed only after edition).
The template function could use the editing item or could have a second parameter with the editing item

**Comment by yotamberk** [comment]
I don't understand what you're asking. You want to see the time change while moving an item?

**Comment by RealRegatta** [comment]
Yes

**Comment by yotamberk** [comment]
eh. I'm afraid it might be a heavy action but I can try implementing this and see what happens.

**Comment by yotamberk** [comment]
The alternative is to use `tooltipOnItemUpdateTime` option

**Comment by RealRegatta** [comment]
Pull request available here :
#2799
