### ISSUE TITLE
How to get the date time while dropping a file/how to give start date(our own date time) while dropping a file based on mouse move?

### ISSUE THREAD

**Issue by OliveSaikiran** [almende/vis#2728]
I would like to know,

How to give a custom or our own date time while dropping a file in Timeline ?

If we give Start date and End date , before dropping that file it is working fine. But i would like to drop a file based on mouse move.

In Timeline, dropped file is able move from one date time to another date time.

But I need to drop a file based on mouse move.

Please help me in this scenario.

Thanks in advance.

**Comment by yotamberk** [comment]
Take a look at this example (specifically the forth item with the fixed times)
http://visjs.org/examples/timeline/other/drag&drop.html

**Comment by OliveSaikiran** [comment]
Hi yotamberk, 

Thanks for the Suggestion.

But "dragstart" is not woking. It is not calling the respective function.
So am unable to move forward.

Please help me in this scenario.

Thanks in advance.

**Comment by OliveSaikiran** [comment]
Tried to get the startdate with respect to the Mouse move. But angular not supporting the "dragstart" event listener. 
In the url code they have using binding to the function with adding event listener, by using angular directive "ng-drag-start" that event listener not binding to the required function.

**Comment by yotamberk** [comment]
This seems to be an angular problem. Not a problem with vis...

**Comment by mojoaxel** [comment]
@OliveSaikiran This is not a support-forum. If you think you found a bug please create a minimal example demonstrating the issue. For problems in your implementation we recommend [stackoverflow](https://stackoverflow.com/questions/tagged/visjs).
