### ISSUE TITLE
Show vertical scrollbar when contents do not fit vertically

### ISSUE THREAD

**Issue by dapriett** [almende/vis#273]
Hello,

I was wondering if it would be possible to add an option to show a horizonal scrollbar on the groups when the list gets long.  I know currently you allow horizontal drag, but a scrollbar option would be nice too.  It sometimes hard to tell that there are more groups otherwise.

Thanks!

**Comment by AlexDM0** [comment]
Hi,

Over the last year a lot of feature requests have been made. We have just introduced our new website which has a list of the requested features. We have placed this request on that list. 

The list can be found here:
http://visjs.org/featureRequests.html

An explaination of the new system can be found here:
http://visjs.org/blog.html#New\ website\ for\ vis\.js\!

I would like to stress that this does not mean we abandon this request. Discussion here will continue if needed on this feature but we will close it to keep our Github issue page more of a bug-todo list.

Future feature requests will still be made here and then added to the website by us.

Regards,

Alex

**Comment by carueda** [comment]
As [discussion can continue here in the original entry](http://visjs.org/blog.html#The\ 2015\ roadmap\ for\ vis\.js), please accept my :+1:  for this really important usability enhancement request.

BTW, regarding the separate enhancement request list, and as noted in your blog entry above, I vote for reverting "back to the old model." 

Keep up the good work!

**Comment by AlexDM0** [comment]
Then again, you don't really have to manage all the issues now do you? ;)

**Comment by daniel-pfeiffer** [comment]
I played around in the DOM and found that at least the trivial approach of making the whole body a single scrollable block is **very easy** to achieve.  (As opposed to my preferred making each group scrollable individually – I'll check that next.)

What I did was move vis-center & -left up into -horizontal.  Then I patched some heights, which were all in the 9600s, by subtracting 8000 (which fits my portrait oriented screen nicely).  And I turned on scrolling – voilà:

![scrollbar](https://cloud.githubusercontent.com/assets/9517524/9251814/3bd67b6a-41d5-11e5-8d1f-6c9f0532e963.png)

**Comment by josdejong** [comment]
Thanks for sharing your solution!

**Comment by daniel-pfeiffer** [comment]
Ok, what seems to work is to do as above, but then separate it into one vis-horizontal per group and make that scrollable.  Probably the DOM can then be streamlined, e.g. at one element each, there is no longer a real vis-itemset & -labelset.  When scrolling sideways, each vis-horizontal would need to be redrawn.

Each vis-label then has a different width, which can be seen in a gap on the right of the separator line at its bottom.  So a common width needs to be specified.

As for the heights, they might be specified in the group entries.  Or lacking that, everything beyond a minimum height would be distributed relative to each group's unrestrained natural height.

The complexity of this sounds like: make my 1st proposition version 1, and then try this later...

**Comment by mast0r** [comment]
For those, who will need a scrolling on the center (items) of left (groups) panels. I have a simple solution. Modifying some CSS styles and enabling overflow on both panels gives a wished scroll effect. The only trick here is that we need to synchronize both panels while scroll it.
```css
.vis-center>.vis-content {
    overflow-x: hidden;
    overflow-y: scroll;
    height: 100%;
}
.vis-left>.vis-content {
    height: 100%;
    overflow-x: hidden;
    overflow-y: scroll;
}
```
```javascript
$(document).ready(function(){
	$('.vis-center>.vis-content').on('scroll', function () {
	    $('.vis-left>.vis-content').scrollTop($(this).scrollTop());
	});
	$('.vis-left>.vis-content').on('scroll', function () {
	    $('.vis-center>.vis-content').scrollTop($(this).scrollTop());
	});	
})
```
Here is an example: http://jsfiddle.net/o58hcubh/1/

![timeline_with_scrolling](https://cloud.githubusercontent.com/assets/9842532/10274668/6ca069a6-6b40-11e5-9d98-4d90ed8d0410.png)

**Comment by daniel-pfeiffer** [comment]
Hi mast0r, after fixing some timing issues (calling ready later in the AngularJS loading process) this works nicely – thanks!
I don't have many groups, but each of them is huge, so I'm very interested in the opposite mechanism: one scroll-bar per group.  You opened my eyes that this can be much easier than what I wrote above: give a height to each group (ideally proportional to it's content or percentage of total) and only add `.vis-group { overflow-y: scroll; }`.
I'm having a hard time emulating this, because the group heights keep being reset.  But it should be that easy, right?

**Comment by panitw** [comment]
@mast0r, your solution works perfectly for me! 

I adjusted it a little bit by making overflow-y:hidden of vis-left and it looks perfect without double scrollbars.

**Comment by panitw** [comment]
I did this to make the scrolling using mouse wheel works

'''JavaScript
$('.vis-center>.vis-content').off('scroll').on('scroll', function () {
    $('.vis-left>.vis-content').scrollTop($(this).scrollTop());
});
$('.vis-center>.vis-content').off('mousewheel').on('mousewheel', function (e) {
    if (e.originalEvent.ctrlKey !== true) {
        var current = $(this).scrollTop();
        var adjusted = current - (e.originalEvent.wheelDelta / 2);
        $('.vis-left>.vis-content').scrollTop(adjusted);
        $('.vis-center>.vis-content').scrollTop(adjusted);
    }
});
'''

**Comment by josdejong** [comment]
nice @panitw , thanks for sharing.

**Comment by brett1361015** [comment]
@mast0r , @panitw , thanks for nice soulutions. 
But actually, then items without a group, for instance, a background(item) of prohibited area, completely stop working.
I mean this http://jsfiddle.net/o58hcubh/2/

**Comment by BulaSpirit** [comment]
I can see mast0r's solution working in jsfiddle, but when I transfer the code into my page _**$('.vis-center>.vis-content').scrollTop()**_   and LEFT always return "0" ...

Does anyone have any idea why?

I copied the code letter for letter, and when I breakpoint or send the values to console.log they are always "0"

    $('.vis-center>.vis-content').on('scroll', function () {
        $('.vis-left>.vis-content').scrollTop($('.vis-center>.vis-content').scrollTop());
    });
    $('.vis-left>.vis-content').on('scroll', function () {
        $('.vis-center>.vis-content').scrollTop($('.vis-left>.vis-content').scrollTop());
    });`

Thanks!

**Comment by BulaSpirit** [comment]
Works now!.
Sorry my fault .. somewhere along the line I replaced $(this) with a reference to the classes.

**Comment by daniel-pfeiffer** [comment]
While @mast0r's solution works great, I just noticed a glitch:  The scrollbar overlaps into the timeline, obscuring part (about 12px) of it.  This doesn't seem like much, but I have a steering control, where I can click to go to "This Hour", "Next Hour", "Today", "Tomorrow" etc.  Now this means that users navigating that way will never see the hidden strip, in this case maybe 2 minutes worth, in a day or week view much more:
![hidden-by-scrollbar](https://cloud.githubusercontent.com/assets/9517524/13491186/483c4ed8-e131-11e5-9896-22b1930f6e89.png)
There is another annoying thing in FF only: the scrollbar doesn't behave normally.  If I click above or below, it should be scrolling the timeline by (almost) a page full.  But instead it scrolls only by a small random amount, sometimes less than an item height, sometimes a few items.

**Comment by daniel-pfeiffer** [comment]
It turns out that there is nothing hidden.  Instead adding a scrollbar makes the browser squeeze it, such that the scale and the red line don't fit exactly.  A solution might be using the previously unused vis-right for the scrollbar:

```css
    .vis-left>.vis-content, .vis-center>.vis-content {
        height: 100%;
        overflow-x: hidden;
        overflow-y: hidden;
    }
    .vis-right>.vis-content {
        width: auto;
        overflow-x: hidden;
        overflow-y: scroll;
    }
```
```javascript
    var left = $('.vis-left>.vis-content'),
        center = $('.vis-center>.vis-content'),
        right = $('.vis-right>.vis-content');
    left.on('scroll', function() {
        center.scrollTop($(this).scrollTop());
        right.scrollTop($(this).scrollTop());
    });
    center.on('scroll', function() {
        left.scrollTop($(this).scrollTop());
        right.scrollTop($(this).scrollTop());
    });
    right.on('scroll', function() {
        left.scrollTop($(this).scrollTop());
        center.scrollTop($(this).scrollTop());
    });
```

Problem is that `.vis-right>.vis-content` has no height.  It would be cool if Almende could always update that too!

**Comment by josdejong** [comment]
> Problem is that .vis-right>.vis-content has no height. It would be cool if Almende could always update that too!

It doesn't need a height as it's height follows from it's child `.vis-itemset`. I guess you can use that one?

**Comment by daniel-pfeiffer** [comment]
True, I wasn't quite clear.  It doesn't have one, since until now it wasn't being used.  And even if it did, `.vis-right>.vis-content>dummychild` needs to always have the same height as `.vis-right>.vis-content>.vis-itemset` for the scrollbar to make sence.

**Comment by josdejong** [comment]
yeah. or just finally implement a scroll-bar in the Timeline instead ;)

**Comment by daniel-pfeiffer** [comment]
That would of course be the best :-)  If possible, alternately for the whole body or each group individually.  In the latter case there would have to be some way to specify the proportional heights of each group, taking into account that some might be filtered out.  Or make the group-borders a draggable sash, that would be even more user friendly.

**Comment by mojoaxel** [comment]
Thanks to @yotamberk for implementing this!

**Comment by ryancrosser** [comment]
What is the typical timeline for a feature to go from the develop branch to master?
