### ISSUE TITLE
Timeline V4.18.1 Bug with Start/End Time on IE

### ISSUE THREAD

**Issue by Ohng** [almende/vis#2738]
https://jsbin.com/palomoqeri/edit?html,output

It works fine without Time.

Updated: It has no problem on Version 4.15.1

**Comment by bradh** [comment]
Fails for me on IE11, but works OK on Firefox and Edge.

**Comment by bradh** [comment]
Looks like basically the same issue as https://github.com/almende/vis/issues/2696

**Comment by Ohng** [comment]
Just wanna add here, the solution for this is to convert the time to ISOStrings as @yotamberk mentioned in #2696
