### ISSUE TITLE
Timeline Background elements not drawing correctly in firefox

### ISSUE THREAD

**Issue by FoamyGuy** [almende/vis#2742]
Here is an example of a Timeline: http://jsbin.com/nojiyukuja/edit?html,output

This page renders correctly in chrome but not firefox. 

In firefox it seems that the background data items are not getting populated with any style attributes which is causing them to be essentially hidden. 

I noticed that the example page here: http://visjs.org/examples/timeline/items/backgroundAreas.html works fine in firefox and as far as I can tell the only real difference between my example and this one is that I am using times and dates, rather than just dates alone. I found this issue: https://github.com/almende/vis/issues/2289 in which it is discussed that firefox seems to not support both time and date, but it seems it was closed due to not having an example. I am thinking that I am running up against the same thing and I have a self contained example that illustrates the difference between chrome and firefox.

**Comment by bradh** [comment]
Fails even more with 4.18.0

**Comment by bradh** [comment]
Works if you use a ISOString (e.g. `start: '2017-02-14T16:49:41Z', end: '2017-02-14T17:06:53Z'`), including in 4.18.1.

**Comment by mojoaxel** [comment]
I think we can call this a bug :-(
Thanks @FoamyGuy for reporting this so detailed!!

**Comment by bradh** [comment]
I'm not so sure it is a bug. 

Is `'2017-02-14 16:49:41 +00'` a valid date string? It might work in some browsers, but that is different to being valid in a cross-browser (ECMAScript) environment.

**Comment by mojoaxel** [comment]
@bradh I think you are right! Not a bug but user-failure :wink:
