### ISSUE TITLE
for small decimal value surface graph do not get plotted.

### ISSUE THREAD

**Issue by devangnithin** [almende/vis#2753]
Example data.
0.0039062500, 0.0898437500, 0.9140625000
0.0039062500, 0.1835937500, 0.8906250000
0.0117187500, 0.1367187500, 0.9687500000
0.0000000000, 0.1406250000, 0.9296875000
0.0078125000, 0.1289062500, 0.996093750
0-0.0546875000, 0.1367187500, 0.8984375000
0.0156250000, 0.1250000000, 0.8789062500
0.0039062500, 0.1484375000, 0.9648437500
-0.0468750000, 0.1328125000, 0.9335937500
0.0585937500, 0.1328125000, 0.8750000000

**Comment by Tooa** [comment]
Are you referring to the `graph3D` component? Can you provide a minimal example via [jsbin.com](jsbin.com) showing the issue?

**Comment by devangnithin** [comment]
This issue was because of wrong data. So I am closing this issue.
