### ISSUE TITLE
How to get posittions 'getPositions()' with angularjs?

### ISSUE THREAD

**Issue by jirayuth289** [almende/vis#2761]
how to get positions from network by using angularjs #angular-visjs.js

**Comment by Tooa** [comment]
About what positions are you talking about (node, edge, ...)?

**Comment by mojoaxel** [comment]
@jirayuth289 This is not a support forum! Please check out the examples. If you have general problems we recommend [stackoverflow](https://stackoverflow.com/questions/tagged/vis.js).
