### ISSUE TITLE
Create issue- and pull-request-templates

### ISSUE THREAD

**Issue by mojoaxel** [almende/vis#2764]
In github it is possible to create templates for new issues or new pull requests. We should use this feature improve quality:

**issues:**
* Only Bugs and Feature-Requests!
* General Questions on Stack-Overflow
* Please provide jsbin to reproduce bugs or e.g. a simple drawing to demonstrate new feature-requests
* Make clear which component (network, timeline, graph2d, graph3d) you are referring to.

**pull-requests:**
* Newver to `master`branch.
* Always base your changes on the current `develop` branch.
* Rebase regularly to make sure you are not trying to fix old issues.
* Include issue-numbers in your COMMIT message (e.g. "fixes \#1234")
* For new code please provide an example to test ist and demonstrate how this is used.

**Comment by Tooa** [comment]
Duplicate of https://github.com/almende/vis/issues/2418

**Comment by mojoaxel** [comment]
@Tooa I recorded to have seen something like this, but could not find it. Thanks!!
