### ISSUE TITLE
Enable disable image on nodes

### ISSUE THREAD

**Issue by plonknimbuzz** [almende/vis#2766]
**[visjs network]**
Sometimes we want to display image on nodes, but sometimes we want to ignore image too , especially when we display large data. 

i read whole nodes documentation but i dont find it.
i try to read and change network DOM via browser console but still didnt get it.

thanks for help

**Comment by Tooa** [comment]
What about backing up your image as additional node property? In case you want to remove the image just pass undefined for the `image` property. When you want to display the image again you can restore your backup image. Does this answer your question?

**Comment by plonknimbuzz** [comment]
sounds good. i'll try after wake up. so tired today (6:00AM here). thanks bro

**Comment by plonknimbuzz** [comment]
thanks @Tooa , its work for me.
