### ISSUE TITLE
Is there any mobile library for this?

### ISSUE THREAD

**Issue by pallaviMN** [almende/vis#2767]

**Comment by bradh** [comment]
What specific functionality / packaging are you looking for that is not already provided?

**Comment by pallaviMN** [comment]
Takes too much to load, Mousle wheel events

**Comment by pallaviMN** [comment]
etc are there

**Comment by bradh** [comment]
This reads a bit like a rant. Can you try to be more specific (and maybe less emotive) about exactly what you want (or want removed)? Think about what you'd expect a user to provide you for design needs.

**Comment by scottlittle** [comment]
I've noticed that tooltips do not work for Graph3D on mobile (Chrome for Android).

**Comment by mojoaxel** [comment]
> I've noticed that tooltips do not work for Graph3D on mobile (Chrome for Android).

@scottlittle Thanks! Please file a separate issue for that.

**Comment by mojoaxel** [comment]
@pallaviMN To answer your title-question: vis.js should work on mobile. It is not optimized for a small size but you always can package yourself and touch-support for most interaction events is there. 
If you have specific problems on mobile please file a specific bug report. Tester on mobile are always welcomed! Thanks!

**Comment by Tooa** [comment]
> I've noticed that tooltips do not work for Graph3D on mobile (Chrome for Android).

Maybe @p-a can have a look at this issue. That would be cool. However, as @mojoaxel suggested pls discuss this in a new issue.
