### ISSUE TITLE
Increase the size of the network diagram

### ISSUE THREAD

**Issue by VallaiPakkam** [almende/vis#2770]
Hi,

I have used visJS for network diagram using  angularJS. I have an problem that the height is automatically choosen to 150 but i have no isssues with the width.

**Comment by Tooa** [comment]
I'm not sure if this issue is related  `visjs`. Can you provide a [jsbin.com](jsbin.com) showing your issue? Otherwise, it is unlikely that someone can help here. I also recommend/suggest to use StackOverflow for questions of that type since this tracker is actually intended for bugs.
