### ISSUE TITLE
Problem fitting the timeline

### ISSUE THREAD

**Issue by Saaravik** [almende/vis#2772]
Hello,

When i try to fit the timeline with `timeline.fit();` the boxes marker are displaced.
![capture_fitting](https://cloud.githubusercontent.com/assets/25955266/23212338/79c53134-f906-11e6-80cb-4f49dde495c3.PNG)

The problem only ocurrs when i used fit function. With this temporaly solution i have not problem:

`timeline.range.setRange(start, end, true);`

thank you

**Comment by bradh** [comment]
Its hard to see the problem, because we can't see the DataSet / DataView you are using. Can you show a jsbin example, or at least show what you expect it to look like for your particular data?

**Comment by Saaravik** [comment]
The problem ocurrs  when the DataSet information is changed and its needed to fit the timeline in order to show the new information. 
```
function addEvents2Timeline(select){

 // clean the dataSet
  timelineData.clear();

//depend of the Select var we add new events
  if (select==1){
    timelineData.add({id: 1, content: 'APS', start: '2017-03-22T13:15:00Z'});
    timelineData.add({id: 2, content: 'PoB A', start: '2017-03-22T13:30:00Z'});
    timelineData.add({id: 3, content: 'FC', start: '2017-03-22T13:45:00Z'});
    timelineData.add({id: 4, content: 'LC', start: '2017-03-22T13:50:00Z'});

  }else{
    timelineData.add({id: 1, content: 'APS', start: '2017-02-22T13:15:00Z'});
    timelineData.add({id: 2, content: 'PoB A', start: '2017-02-22T13:30:00Z'});
    timelineData.add({id: 3, content: 'FC', start: '2017-02-22T13:45:00Z'});
    timelineData.add({id: 4, content: 'LC', start: '2017-02-22T13:50:00Z'});
  }
  timeline.fit();
}
```

**Comment by mojoaxel** [comment]
This might be because of user-specific-css,
@Saaravik Could you please try to provide a [jsbin](jsbin.com) that shows the problem. Thanks!
