### ISSUE TITLE
Group network edges

### ISSUE THREAD

**Issue by baba2k** [almende/vis#2775]
Hello,
 i want to mark a path in my network. But i cant group edges to draw the edges bigger at once.
Featurerequest or have I understood something wrong?

Thank you!

baba

**Comment by Tooa** [comment]
Do you know the edges or their corresponding ids of that path? In that case, you can select them via a `dataset` and increase their `width`.

**Comment by baba2k** [comment]
I gott the data for some graphs in this format (alchemyjs): http://pastebin.com/g1ebbkGy The edges which should have a bigger width got the attribute type:"greenpath".
I replaced the type attribute to group the nodes. This function were nice for edges two. I think the best solution ist to replace type:"greenpath" with the witdh setting for every node (texteditor replace function)?

Thank you!
