### ISSUE TITLE
Timeline stack and horizontal margin=0

### ISSUE THREAD

**Issue by 3xH** [almende/vis#2776]
Hi,

If I set the option margin:{ item:{ horizontal:0 }}, and then create 2 ranges with "Item 1" finishing when "Item 2" begin, they shouldn't be stacked, but they are since version 4.17.
![margin_horizontal_0](https://cloud.githubusercontent.com/assets/23527463/23252852/8fb5792a-f9b2-11e6-9d29-5c94a21e13d9.PNG)

Thanks for your help.

**Comment by Tooa** [comment]
Please provide a minimal example demonstrating the issue via [jsbin.com](jsbin.com).

**Comment by 3xH** [comment]
Thanks for your answer.

This a jsbin with version 4.18.1
https://jsbin.com/teguyahewi/edit?html,output

If needed, I'll test later on with develop branch.

**Comment by bradh** [comment]
Investigated this a bit. With a very small time offset (e.g. item 2 starting 1ms after item 1finishes), this is scale dependent. As you scale in, it eventually drops into being inline. So the change is likely somewhere on the rendering side.

**Comment by 3xH** [comment]
Sorry, I didn't see that this problem has alerady a workaround by using negative value.
[issues-2318](https://github.com/almende/vis/issues/2318)

**Comment by mojoaxel** [comment]
use option `stack: false`.

this is a duplicate of #2318
