### ISSUE TITLE
Timeline: item.editable is only boolean

### ISSUE THREAD

**Issue by mokraemer** [almende/vis#2778]
the item.editable option is not as finegrained as the main options.

If you generally allow editing & deleting but have a few items that cannot be deleted you can't just disable deleting by setting:

{id: 1, content: 'read-only item', start: '2013-04-20', editable: {remove: false}}

**Comment by bradh** [comment]
Seems like a valid feature request / enhancement, although the interaction with the existing code may get a bit complicated.

**Comment by mojoaxel** [comment]
@jangajack And again a "item editable" topic :-)
Maybe you can have a look at this also!?

**Comment by RealRegatta** [comment]
I think it's already the case.
Saw in Item.js :
`if(typeof this.data.editable === 'boolean') {
        this.editable = {
          updateTime: this.data.editable,
          updateGroup: this.data.editable,
          remove: this.data.editable
        }
}`

**Comment by bradh** [comment]
The code you are quoting is for `editable: false`, and sets everything to the boolean value.

There is support for objects (well, there will be soon), but if you do `editable: {remove: false}` the behaviour is to reset the other editable properties (i.e. `updateGroup` and `updateTime` become undefined and that means not editable (irrespective of the timeline options).

**Comment by bradh** [comment]
@mokraemer Can you retest with 4.19.1 to see if that meets your needs. If not, can you update your request with details of what additional functionality is needed?
