### ISSUE TITLE
Edge highlighting: top layer? Highlight nodes?

### ISSUE THREAD

**Issue by Alex-Vidal** [almende/vis#2779]
My case is an inmense graph which is densely connected. I have managed to change the color of all edges incident in a node when the node is highlighted, but they are still sometimes covered by the other edges. Is there any way to move them to the "top layer"?

Additionally, is there a way to highlight the nodes of an edge when an edge is selected? (Besides getting into select/deselect edge).

Thanks,

**Comment by mojoaxel** [comment]
> Is there any way to move them to the "top layer"?

As far as I know there is no "bring to top" functionality, yet.

> Additionally, is there a way to highlight the nodes of an edge when an edge is selected? (Besides getting into select/deselect edge).

This is easily possible. Please check all the network examples, maybe this helps. if not: stackoverflow!
