### ISSUE TITLE
IE11 problem with date strings including times in Timeline

### ISSUE THREAD

**Issue by netbrothers-tr** [almende/vis#2782]
When modifying the [basic example](http://visjs.org/examples/timeline/basicUsage.html) just a little, items that have specified hours, minutes and seconds in their `start ` and `end ` properties are not rendered properly in IE11.

Watch out for items 3 and 4 in this fiddle adapted from the basic example. Compare it in Firefox and IE11 for example.

https://jsfiddle.net/cx15bj6p/1/

Can you think of any workaround?

**Comment by Saaravik** [comment]
Hi,

Do you try to use ISODate format: -> '2017-02-22T13:15:00Z'

Saaravik

**Comment by netbrothers-tr** [comment]
@Saaravik Thanks very much! It works!

I might add that it also works with a timezone, e.g. '2017-02-22T13:15:00+02:00'.

Now I have to find out how to determine the correct timezone. It's not stored in the database.

**Comment by netbrothers-tr** [comment]
IE will also crash, when settings those kind of date strings, e.g. '2014-04-18 10:00:00', in the timeline options for `start` and `end`. Again, ISO dates (e.g. '2017-02-22T13:15:00Z' or '2017-02-22T13:15:00+02:00') are the solution.

**Comment by mojoaxel** [comment]
duplicate of #2742
