### ISSUE TITLE
Migrate code to es6 or Typescript

### ISSUE THREAD

**Issue by luisvt** [almende/vis#2785]
It would be good if code gets migrated to es6 or Typescript

**Comment by mojoaxel** [comment]
Some (newer) parts of the code uses ES2016.
There are also people working on [Type-Definitions for Typescript](https://github.com/almende/vis/search?q=typescript&type=Issues&utf8=%E2%9C%93).

**Comment by luisvt** [comment]
Could I change old code to use es6 or TS?

**Comment by bradh** [comment]
It makes it harder to test if you can't do unit tests on the source, but have to use the dist instead. Also change for change sake (not to fix bugs or add features) is a source of bugs, since we don't have full unit tests. Maybe starting with adding new tests and examples first?
