### ISSUE TITLE
How to obtain nodes coordinates after simulation

### ISSUE THREAD

**Issue by thedub2001** [almende/vis#2786]
Hello !
I'am looking for a way to get edge lengths or node coordinates **after** the simulation has operated.
I looked into vis.js file and found that something was happening to the coordinates in the function n°206 (line 42205) : 
``` 
function(module, exports, __webpack_require__) {
  "use strict";
  Object.defineProperty(exports, "__esModule", {
    value: true
  });
  var _classCallCheck2 = __webpack_require__(115);
  var _classCallCheck3 = _interopRequireDefault(_classCallCheck2);
  var _createClass2 = __webpack_require__(116);
  var _createClass3 = _interopRequireDefault(_createClass2);

  function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }

  var CentralGravitySolver = function () {
    function CentralGravitySolver(body, physicsBody, options) {
      (0, _classCallCheck3["default"])(this, CentralGravitySolver);

      this.body = body;
      this.physicsBody = physicsBody;
      this.setOptions(options);
    }

    (0, _createClass3["default"])(CentralGravitySolver, [{
      key: "setOptions",
      value: function setOptions(options) {
        this.options = options;
      }
    }, {
      key: "solve",
      value: function solve() {
        var dx = void 0,
            dy = void 0,
            distance = void 0,
            node = void 0;
        var nodes = this.body.nodes;
        var nodeIndices = this.physicsBody.physicsNodeIndices;
        var forces = this.physicsBody.forces;

        for (var i = 0; i < nodeIndices.length; i++) {
          var nodeId = nodeIndices[i];
          node = nodes[nodeId];
          dx = -node.x;
          dy = -node.y;
          distance = Math.sqrt(dx * dx + dy * dy);

          this._calculateForces(distance, dx, dy, forces, node);
        }
      }

      /**
       * Calculate the forces based on the distance.
       * @private
       */

    }, {
      key: "_calculateForces",
      value: function _calculateForces(distance, dx, dy, forces, node) {
        var gravityForce = distance === 0 ? 0 : this.options.centralGravity / distance;
        forces[node.id].x = dx * gravityForce;
        forces[node.id].y = dy * gravityForce;
      }
    }]);
    return CentralGravitySolver;
  }();

  exports["default"] = CentralGravitySolver;

/***/ }
 ```

I understand that I can use "this.body.nodes[Id].x" and "this.body.nodes[Id].y" while I'am inside the function (in debugging mode).
My problem is I don't understand what is "this" and how to invoke it in a home-made function outside  of the vis.js file...

Thanks for your help!

**Comment by Tooa** [comment]
> I'am looking for a way to get edge lengths or node coordinates after the simulation has operated.

Once the simulation has stopped, the `stabilized` [event](http://visjs.org/docs/network/#Events) is called. Inside this function, you can get the node positions with the `getPositions` [function](http://visjs.org/docs/network/). To obtain the node ids use a `dataset` ([reference](http://visjs.org/docs/data/dataset.html)). This dataset provides you with a function called `getIds()`, which returns all node ids of your network. That's it.

> My problem is I don't understand what is "this" and how to invoke it in a home-made function outside of the vis.js file...

`This` refers to the currents [scope](https://en.wikipedia.org/wiki/This_(computer_programming)) object.
To access variables, methods and values of the internal code we use a [concept](https://en.wikipedia.org/wiki/Application_programming_interface) called `API` that gives you access to this information. The documentation for that API is [here](http://visjs.org/docs/network/).

Note that this is not a support forum. The tracker is supposed to be used for bugs. Next time please use `StackOverflow` for your question. Thanks.

**Comment by thedub2001** [comment]
Thanks for your clear and quick answer, it solved my problem!
I will use StackOverflow for questions from now :)
