### ISSUE TITLE
Documentation about network stabilization process

### ISSUE THREAD

**Issue by baba2k** [almende/vis#2788]
Hello, 

is there any documentation or information about the stabilization process of network module (english or german)?

Thank you very much!

Best regards,
Sebastian

**Comment by bradh** [comment]
You have full access to the source code. What specific information are you looking for?

**Comment by mojoaxel** [comment]
@baba2k The network processes are quite complex. Documenting them would probably mean more work then implementing them. So the answer is: No, sorry!
