### ISSUE TITLE
Timeline examples have non-standard times

### ISSUE THREAD

**Issue by bradh** [almende/vis#2790]
#2696 reported problems in the data serialization example not working in IE10 and mobile. That example used non-standard time formats, not ISOString (or a standard Date() constructor), and a change is in work at https://github.com/almende/vis/pull/2789

There are other timeline examples that do this, including:
 - styling/itemTemplates.html
 - groups/subgroups.html
 - item/expectedVsActualTimesItems.html
 - the data/wk2014.json resource

Those should be updated to use ISOString.

**Comment by mojoaxel** [comment]
duplicate of #2791
