### ISSUE TITLE
Alt Rows color + gridlines causing scroll zoom issue

### ISSUE THREAD

**Issue by johnwarre** [almende/vis#2792]
In an attempt to apply a feature ask for alternate row colors, I added the following styles:

        .vis-group:nth-of-type(even), .vis-label:nth-of-type(even) {
            background: #efefef;
        }

        .vis-group:nth-of-type(odd), .vis-label:nth-of-type(odd) {
            background-color: white;
        }

This worked, except it removed the gridelines which I was able to recover with the following:

       .vis-time-axis .vis-grid.vis-vertical {
            z-index: 99;
        }

However, the escalation of the z-index has broke the scroll zoom of the timeline except when the mouse is hovered over one of the items on the timeline.

I have been playing around with different approaches for style applications, especially using different z-indexes but haven't found a valid combination.

Here is a JsBin link: https://jsbin.com/difoteqobo/edit?html,css,js,output

Any suggestions?

**Comment by mojoaxel** [comment]
@johnwarre It really would help if you could create a [jsbin](https://jsbin.com) to demonstrate the problem. Maybe we can improve something to make this easier!

**Comment by johnwarre** [comment]
updated my original post with link to jsBin.

**Comment by mojoaxel** [comment]
You could do the following trick: https://jsbin.com/jevised/2/edit?css,output

**Comment by johnwarre** [comment]
Thanks. Trick works.
