### ISSUE TITLE
Timeline vertical scroll example broken in Explorer (IE11)

### ISSUE THREAD

**Issue by bg** [almende/vis#2800]
My colleague reports the timeline vertical scroll example does not work in Explorer (IE11). Though on another developer's system we confirmed it works fine on Edge. Here is the error:

```
Global code [Line: 78, Col: 3], verticalScroll.html
{exception}	Object doesn't support property or method 'assign'
```

We need to know if verticalScroll is supported under IE11 or not. Is it just the example that's broken, or will this feature not work at all on IE11?

Thanks,
Ben

**Comment by yotamberk** [comment]
The example seems to be using es6 assign syntax which is not supported in ie11. This is not a problem in the code but only a problem in the example. The example will be fixed

**Comment by bg** [comment]
Thanks. I had hoped it was that.
