### ISSUE TITLE
Callback for animations

### ISSUE THREAD

**Issue by henev** [almende/vis#2805]
Hello,

Is it possible to integrate callbacks for functions like `.setWindow()` that have animations? I would like to execute code after the animation ends. Is `setTimeout` the only possible way for now?

Thank you in advice :)

**Comment by bradh** [comment]
Could you just use the rangeChanged event? See http://visjs.org/docs/timeline/#Events

**Comment by henev** [comment]
Yes, I am concern with timeline.

`rangeChange` is also possible but for some things I think it will be better to use a callback which will be executed once.

**Comment by bradh** [comment]
There are two events - `rangeChange` (Fired repeatedly when the timeline window is being changed) and `rangeChanged` (Fired once after the timeline window has been changed).

If you don't want `rangeChanged` behaviour, can you describe how what you want is different from that event?

**Comment by henev** [comment]
I have an event handler that is attached on the `rangeChanged` event. I don't want to use this handler and to do checks there in order to execute code that is relevant only for the context I am calling `.setWindow` from. It will be much easier if I have a callback for that purpose.

**Comment by bradh** [comment]
How would the callback you want differ from `rangeChanged`? I'm not trying to be difficult, I'm trying to understand the requirement.

**Comment by henev** [comment]
If I call `.setWindow` from somewhere and I want after the animation ends to `.focus()` or to `.setSelection` with an item id, how would you achieve this?

**Comment by bradh** [comment]
Can you set up a jsfiddle / jsbin that shows your situation?

**Comment by yotamberk** [comment]
@henev checkout this PR: #2870

**Comment by mojoaxel** [comment]
@henev @yotamberk Can this be closed?
