### ISSUE TITLE
Search and selection

### ISSUE THREAD

**Issue by sonfiree** [almende/vis#2807]
How to search in the box by going to the top of it stood out then if such exists?

**Comment by bradh** [comment]
This question needs much more context and a better explanation. Can you try editing it, including a sample (picture, jsbin) and explaining what you are trying to do, what you've already tried and what happened, plus what you expected to happen instead?

**Comment by sonfiree** [comment]
Well then select a node knowing he was going?

**Comment by bradh** [comment]
I have no idea what you are asking, sorry. I can only ask that you try to address my questions and suggestions.

**Comment by Tooa** [comment]
Please use StackOverflow for questions. This tracker is reserved for bugs and feature requests.
