### ISSUE TITLE
Error in Network Nodes Options

### ISSUE THREAD

**Issue by mdre** [almende/vis#2813]
I'am getting a lot of error when using the full example of [Nodes Options](http://visjs.org/docs/network/nodes.html#). If you run this code, the console log this:

```
Unknown option detected: "chosen" in 

options = {
  nodes: {
    chosen
  }
}


Perhaps it was misplaced? Matching option found at: 

options = {
  interaction: {
    hover
  }
}



vis-network.min.js:29 Unknown option detected: "vadjust" in 

options = {
  nodes: {
    font: {
      vadjust
    }
  }
}


Perhaps it was misplaced? Matching option found at: 

options = {
  edges: {
    value
  }
}



vis-network.min.js:29 Unknown option detected: "multi". Did you mean "color"?

Problem value found at: 
options = {
  nodes: {
    font: {
      multi
    }
  }
}



vis-network.min.js:29 Unknown option detected: "bold". Did you mean "color"?

Problem value found at: 
options = {
  nodes: {
    font: {
      bold
    }
  }
}



vis-network.min.js:29 Unknown option detected: "ital" in 

options = {
  nodes: {
    font: {
      ital
    }
  }
}


Perhaps it was misplaced? Matching option found at: 

options = {
  edges: {
    title
  }
}



vis-network.min.js:29 Unknown option detected: "boldital". Did you mean "align"?

Problem value found at: 
options = {
  nodes: {
    font: {
      boldital
    }
  }
}



vis-network.min.js:29 Unknown option detected: "mono" in 

options = {
  nodes: {
    font: {
      mono
    }
  }
}


Perhaps it was misplaced? Matching option found at: 

options = {
  edges: {
    font
  }
}



vis-network.min.js:29 Unknown option detected: "heightConstraint". Did you mean one of these: borderWidth, borderWidthSelected, brokenImage, color, fixed, font, group, hidden, icon, id, image, label, labelHighlightBold, level, mass, physics, scaling, shadow, shape, shapeProperties, size, title, value, x, y

Problem value found at: 
options = {
  nodes: {
    heightConstraint
  }
}



vis-network.min.js:29 Unknown option detected: "widthConstraint". Did you mean one of these: borderWidth, borderWidthSelected, brokenImage, color, fixed, font, group, hidden, icon, id, image, label, labelHighlightBold, level, mass, physics, scaling, shadow, shape, shapeProperties, size, title, value, x, y

Problem value found at: 
options = {
  nodes: {
    widthConstraint
  }
}

vis-network.min.js:27 Errors have been found in the supplied options object.
```

What is wrong in the page example?
That's property exists?

Thank's
Marcelo

**Comment by Tooa** [comment]
```
options = {
  interaction: {
    hover
  }
}
```
This looks like there is an assignment for `hover` missing such as 

```
hover: {
        border: '#2B7CE9',
        background: '#D2E5FF'
      }
```

**Comment by mdre** [comment]
I have not posted the "full options" listed in the NetworkNodes page. If I use that options as appear in the example "Full options" tab, it throws thats errors.

**Comment by Tooa** [comment]
Ok, then please provide the code as minimal as possible via [jsbin.com](jsbin.com).

**Comment by mdre** [comment]
Here is the code: [example](http://jsbin.com/parawuvaxa/edit?html,output)
The node options are all listed in the documentation section: http://visjs.org/docs/network/nodes.html#
in the "Full options" tab.
I'am making a Wrapper Component to run VisJS as a [Vaadin](https://vaadin.com/home) component and access it directly from Java. Other config options works for now but nodes fails.

**Comment by Bastetoi** [comment]
Some "," are missing in full options 

here is the fix:
`<!DOCTYPE html>
<html>
<head>
  <title>Network | Basic usage</title>

  <script type="text/javascript" src="http://visjs.org/dist/vis.js"></script>
  <link href="http://visjs.org/dist/vis-network.min.css" rel="stylesheet" type="text/css" />

  <style type="text/css">
    #mynetwork {
      width: 600px;
      height: 400px;
      border: 1px solid lightgray;
    }
  </style>
</head>
<body>

<p>
  Create a simple network with some nodes and edges.
</p>

<div id="mynetwork"></div>

<script type="text/javascript">
  // create an array with nodes
  var nodes = new vis.DataSet([
    {id: 1, label: 'Node 1'},
    {id: 2, label: 'Node 2'},
    {id: 3, label: 'Node 3'},
    {id: 4, label: 'Node 4'},
    {id: 5, label: 'Node 5'}
  ]);

  // create an array with edges
  var edges = new vis.DataSet([
    {from: 1, to: 3},
    {from: 1, to: 2},
    {from: 2, to: 4},
    {from: 2, to: 5},
    {from: 3, to: 3}
  ]);

  // create a network
  var container = document.getElementById('mynetwork');
  var data = {
    nodes: nodes,
    edges: edges
  };
  
  var options = {
          nodes:{
            borderWidth: 1,
            borderWidthSelected: 2,
            brokenImage:undefined,
            chosen: true,
            color: {
              border: '#2B7CE9',
              background: '#97C2FC'
              },
              highlight: {
                border: '#2B7CE9',
                background: '#D2E5FF'
              },
              hover: {
                border: '#2B7CE9',
                background: '#D2E5FF'
              
            },
            fixed: {
              x:false,
              y:false
            },
            font: {
              color: '#343434',
              size: 14, // px
              face: 'arial',
              background: 'none',
              strokeWidth: 0, // px
              strokeColor: '#ffffff',
              align: 'center',
              multi: false,
              vadjust: 0,
              bold: {
                color: '#343434',
                size: 14, // px
                face: 'arial',
                vadjust: 0,
                mod: 'bold'
              },
              ital: {
                color: '#343434',
                size: 14, // px
                face: 'arial',
                vadjust: 0,
                mod: 'italic',
              },
              boldital: {
                color: '#343434',
                size: 14, // px
                face: 'arial',
                vadjust: 0,
                mod: 'bold italic'
              },
              mono: {
                color: '#343434',
                size: 15, // px
                face: 'courier new',
                vadjust: 2,
                mod: ''
              },
            },
            group: undefined,
            heightConstraint: false,
            hidden: false,
            icon: {
              face: 'FontAwesome',
              code: undefined,
              size: 50,  //50,
              color:'#2B7CE9'
            },
            image: undefined,
            label: undefined,
            labelHighlightBold: true,
            level: undefined,
            mass: 1,
            physics: true,
            scaling: {
              min: 10,
              max: 30,
            
              label: {
                enabled: false,
                min: 14,
                max: 30,
                maxVisible: 30,
                drawThreshold: 5
              },
              customScalingFunction: function (min,max,total,value) {
                if (max === min) {
                  return 0.5;
                }
                else {
                  let scale = 1 / (max - min);
                  return Math.max(0,(value - min)*scale);
                }
              }
            },
            shadow:{
              enabled: false,
              color: 'rgba(0,0,0,0.5)',
              size:10,
              x:5,
              y:5
            },
            shape: 'ellipse',
            shapeProperties: {
              borderDashes: false, // only for borders
              borderRadius: 6,     // only for box shape
              interpolation: false,  // only for image and circularImage shapes
              useImageSize: false,  // only for image and circularImage shapes
              useBorderWithImage: false  // only for image shape
            },
            size: 25,
            title: undefined,
            value: undefined,
            widthConstraint: false,
            x: undefined,
            y: undefined
          }
        }

  var network = new vis.Network(container, data, options);
</script>

</body>
</html>
`

**Comment by Tooa** [comment]
@Bastetoi I would love to see a pull request that fixes the full options. Feel free to fix it :)

**Comment by mdre** [comment]
Hi. 
I still trying  to solve this problem. It seems that the options showed in the doc page are not working.
Look this:

```
{
autoResize: true,
height: '100%',
width: '100%',
locale: 'es',
clickToUse: false,
nodes: {
    borderWidth: 1,
    borderWidthSelected: 2,
    color: {
        border: '#2B7CE9',
        background: '#D2E5FF',
        highlight: {
            border: '#2B7CE9',
            background: '#D2E5FF'
       },
    },
    fixed: {
        x: false,
        y: false
   },
   font: {
        multi: false,
   },
   hidden: false,
   labelHighlightBold: true,
   mass: 1,
   physics: true,
   size: 25
   },
}
```
Well, with this options, it throw:

```
Unknown option detected: "multi". Did you mean "color"?

Problem value found at: 
options = {
  nodes: {
    font: {
      multi
    }
  }
}

```

If you remove the font config it work well. So, the "multi" option really exist?

Thanks

**Comment by mdre** [comment]
Well, this are the property that are marked as "unknow" when you try to assign them:

nodes.font.vadjust
nodes.font.multi
nodes.font.bold
nodes.font.ital
nodes.font.boldital
nodes.font.mono

Any of this options doesn't work.

**Comment by wimrijnders** [comment]
I also get errors when loading the network with the full options from the doc page. These are different errors though. For example:

```
Invalid type received for "code". Expected: string. Received [undefined] "undefined"

Problem value found at: 
options = {
  nodes: {
    icon: {
      code
    }
  }
}
```
And, indeed, the definitions in `lib/network/options.js` do not declare `undefined` as a legal value:

```
    icon: {
      face: { string },
      code: { string },  //'\uf007',
      size: { number },  //50,
      color: { string },
      __type__: { object }
    },
```

Field `code` should have been defined as:

```
    code: { string, 'undefined': 'undefined' },
```
 _(assuming that the doc's are valid, of course)_

It appears that the option definitions also need some revising.

**Comment by mdre** [comment]
Trying to test only "chosen" option. Look at this options, only :
```
{
autoResize: true,
height: '100%',
width: '100%',
locale: 'es',
clickToUse: false,
nodes: {
    borderWidth: 1,
    borderWidthSelected: 2,
    chosen: true,
    fixed: {
         x: false,
         y: false
    },
    font: '14px arial #343434',
    heightConstraint: false,
    hidden: false,
    labelHighlightBold: true,
    mass: 1,
    physics: true,
    size: 25
    },
}
```
It report: 
```
Unknown option detected: "chosen" in 

options = {
  nodes: {
    chosen
  }
}
```

But in the options.js is defined: 
```
nodes: {
    borderWidth: { number: number },
    borderWidthSelected: { number: number, 'undefined': 'undefined' },
    brokenImage: { string: string, 'undefined': 'undefined' },
    chosen: {
      label: { boolean: bool, 'function': 'function' },
      node: { boolean: bool, 'function': 'function' },
      __type__: { object: object, boolean: bool }
    },
   ...
```
so, where is the error? Perhaps in the validation test?

**Comment by wimrijnders** [comment]
I don't get that error on field `chosen`. I'm using vis.js v. 4.19.1, i.e. latest version. Are you using the same?

**Comment by mdre** [comment]
Sorry guys! The error was mine. I don't understand how I get the .js of version 4.16 and the doc of 4.19. Yesterday, when I study the cloned code, I see that there was no error. So I start to inspect the vis.js that I was using and finally notice that the version was wrong!! 
I update to 4.19.1 and all work fine!!
Thanks for all.
Marcelo

**Comment by wimrijnders** [comment]
:+1: All is well, then!
