### ISSUE TITLE
Css mangled at high zoom levels on timebar

### ISSUE THREAD

**Issue by YayBugs** [almende/vis#2814]
The odd and day classes appear to get mangled together:  
" vis-yesterdayvis-odd"  

I beleive this is because of the trims on the functions:   https://github.com/almende/vis/blob/master/lib/timeline/TimeStep.js#L616  

As when running it in dev console in chrome:  
today(current) + even(current.minutes()).trim() gives me " vis-yesterdayvis-odd"  
but:  
today(current) + even(current.minutes()) gives me " vis-yesterday vis-odd"  
which would appear to be correct to me

I am happy to put in a pull request for this but do not know enough about the library to tell if just removing the trim function is what is needed.

**Comment by Tooa** [comment]
Thanks for submitting the issue. Maybe @yotamberk can have a look at this and guide you for your pull request :)

**Comment by bradh** [comment]
There are more cases like this. I have a unit test in work.

**Comment by yotamberk** [comment]
leaving it to @bradh . I'm more than happy to help if needed.

**Comment by yotamberk** [comment]
@bradh What's the status on this?

**Comment by bradh** [comment]
Have been traveling. Probably another week.On 19 Mar 2017 9:17 AM, yotamberk <notifications@github.com> wrote:@bradh What's the status on this?

**Comment by yotamberk** [comment]
@bradh any update on this?

**Comment by bradh** [comment]
No further progress. I think the fix is OK for now. If you are happy with it, suggest closing.
