### ISSUE TITLE
Set X and Y of First node manualy(in Center).

### ISSUE THREAD

**Issue by shoaiblucideus** [almende/vis#2822]
Hi, I am facing problem while creating network diagram with icon. 

i want to place  node in center and all other node around that one node. and center node will be fixed in center. sohow can i achieve this effect.

Any Help?

**Comment by Bastetoi** [comment]
When you create a node you can set his position with `x:0,y:0` and it should work just fine :)

**Comment by Tooa** [comment]
Thanks for helping out here @Bastetoi.
