### ISSUE TITLE
Vertical alignment on group content

### ISSUE THREAD

**Issue by AndreAlves10** [almende/vis#2823]
Hello,

Is there any way to vertically align a group content in the middle of its container?

For instance, in this example:
![bis](https://cloud.githubusercontent.com/assets/25454839/23560120/3d640d32-0031-11e7-8fbc-9ee43789f1b5.png)

All contents are shown on top of the container but I would like to align them in the middle.

I've trying to change the CSS like this:
```
.vis-inner {
    vertical-align: middle
}
```
However it is not working.

Thank you.

**Comment by brichbe** [comment]
Does this work for you?

```
.vis-label {
  display: flex;
  align-items: center;
}
```

**Comment by AndreAlves10** [comment]
Perfect @brichbe!

Thank you
