### ISSUE TITLE
Group className

### ISSUE THREAD

**Issue by Kaliph** [almende/vis#2825]
Is there a way I can use Group Elements in the timeline like we can do with Items and passing className to
the timeline so I can define different css Values for my groups. 
![feature_group_classname](https://cloud.githubusercontent.com/assets/19877914/23568136/8ba2369a-0059-11e7-8b46-06aa432650ae.png)
So that this becomes available also for group Elements.
![feature_group](https://cloud.githubusercontent.com/assets/19877914/23568278/16741e82-005a-11e7-9424-b61d4a4c83be.png)

**Comment by brichbe** [comment]
[Groups](http://visjs.org/docs/timeline/#groups) support `className` just like Items do, so you can specify different styles that way.  You don't "pass" these class names to the timeline -- you specify the `className` when defining your groups/items, and that name corresponds to the custom style in your CSS.  Does that address what you're asking?

**Comment by Kaliph** [comment]
Ok. Thanks. I think thats what I Need. If I have further issues I will Post them here.

**Comment by brichbe** [comment]
I recommend this ticket be closed.  Use http://stackoverflow.com/ for general questions like this.  These are meant for bugs and feature requests.

**Comment by Kaliph** [comment]
I have opened this question on stackoverflow. Here is the Link. I am missing just a small piece.

http://stackoverflow.com/questions/42596401/vis-timeline-group-label-background-colour-depending-on-classname
