### ISSUE TITLE
If statement with Node Id

### ISSUE THREAD

**Issue by golflv100** [almende/vis#2833]
i am making a network that when i doubleclick node 1 it will open the url and node 2 will open another url. i want something like 

network.on("selectNode", function (params) {
        console.log('selectNode Event:', params);
if (params.node[params]==1){
        window.open("https://www.google.com");
    }
else if (params.node[params]==2){
        window.open("https://www.facebook.com");
    }
});

Is that possible?

**Comment by Tooa** [comment]
Yes, this is possible with the `doubleClick` [event](http://visjs.org/docs/network/#Events). Please note that this is a bug tracker for issues and features requests. Next time please use StackOverflow for questions.
