### ISSUE TITLE
Timeline: Control over the drop event

### ISSUE THREAD

**Issue by gulench** [almende/vis#2834]
The current implementation of drag-and-drop in the Timeline component does not provide a way for an application to **inspect** and **make use of** the _context_ of the **drop event**. I'm looking for an **option** to specify _how to handle drop events_, through which one would be able to do the following:

1. **Inspect properties of target** (item/group) of the drop, and time of the drop.
1. Make use of the **target properties**, and the **dragged item**, to **populate the properties** of the _item to be added_.
1. Use the above information and decide **whether to accept or reject** the _drop event_. Based on the outcome, one would have the opportunity to update the dragged item.

**Comment by yotamberk** [comment]
@gulench did you try using the `onAdd` event? This contains everything you asked for.
There might be a place for an `onDrop` event, but does this satisfy your needs?

**Comment by gulench** [comment]
@yotamberk, `onAdd` gets you to inspect the **item**, not the "point"/"target" where the item is added/dropped. In addition to the item, I would be interested in the following:

- time in the timeline where the item is added/dropped
- target group, if any
- target item, if any
