### ISSUE TITLE
Timeline vertical visibility performance optimization is broken

### ISSUE THREAD

**Issue by thomasbarone** [almende/vis#2835]
The performance optimization where groups/items that are not visible in the timeline window are not loaded to the DOM is currently broken.

See issue #1383 for a discussion of the original feature request, I feel it is best summarised in this sketch:

```
     |                   |
     | "invisible" items | 
     |                   |
 ------------------------------
 |                            |
 |       visible area         | 
 |                            |
 ------------------------------
     |                   |
     | "invisible" items | 
     |                   |
```

The problem can be seen in this [example](http://visjs.org/examples/timeline/groups/verticalItemsHide.html). Zoom in and click _Show current visible items_. It will show the visible items as well as all the "invisible" items (in groups that are above / below the current window).

**Comment by yotamberk** [comment]
The performance  doesn't have an issue. It's a problem of the method `getVisibleItems`

**Comment by mojoaxel** [comment]
This tests from @nathanbennett look like there is room for improvement here:

![fixcomparison](https://cloud.githubusercontent.com/assets/11827402/23735638/ba3d7434-04d6-11e7-8ab0-a99819058356.png)

**Comment by simpleclicks** [comment]
Hi is there a work around for this till this bug is fixed?
