### ISSUE TITLE
"WARNING: infinite loop in redraw?" on normal behavior

### ISSUE THREAD

**Issue by Guiren** [almende/vis#2838]
Hi,
I just noticed that this was in the console when zooming/unzooming with CTRL+scroll wheel on the page. I'm guessing the browser calls redraw events on every change of zoom level.

(I have Firefox 51.0.1)

**Comment by Tooa** [comment]
Does this occur in the latest `develop` branch for you?

**Comment by yotamberk** [comment]
@Guiren Can you supply a jsbin to replicate this? It doesn't seem to happen to me.

**Comment by mojoaxel** [comment]
I don't think we need a new issue for this. See [issues with "infinite loop"](https://github.com/almende/vis/issues?q=is%3Aissue+infinite+loop+label%3ATimeline)
