### ISSUE TITLE
DataSet.get([undefined]) returns [null], should return [] instead

### ISSUE THREAD

**Issue by Head** [almende/vis#2839]
The documentations says:
>When no item is found, null is returned when a single item was requested, and and empty Array is returned in case of multiple id's.

But that's not the case, reading the code at https://github.com/almende/vis/blob/master/lib/DataSet.js#L373 it pushes item to the array no matter what is found.

**Comment by wimrijnders** [comment]
Ah, right. I see what you mean, when id's are not found `null`'s are returned in the Array.

I'll spend some time on this. The fix for this particular issue is easy of course, but I also want to add unit tests as well to catch this and as many similar edge cases as possible.

**Comment by wimrijnders** [comment]
The documentation issue has been resolved by adjusting it to fit the current working.
