### ISSUE TITLE
Vis js timeline - How to stack items of type background?

### ISSUE THREAD

**Issue by abishekhns** [almende/vis#2844]
Vis js timeline - How to stack items of type background?

**Comment by brichbe** [comment]
Background items do not stack by default, but this can be achieved using subgroups.  See this [example](http://visjs.org/examples/timeline/groups/subgroups.html).

This example needs cleanup/improvement, but for now you'll notice the "bar" group contains two background items in the top half, and two others in the bottom half, so you can do something similar to give the appearance of stacking your background items.

**Comment by abishekhns** [comment]
@brichbe brichbe: Does not quite look like what i want.
I already have a some box type items in the group, and there will be some overlapping background items.
Is there a way to prioritize some background items over other if there is a overlap?

**Comment by brichbe** [comment]
You prioritize these things using groupOrder and/or subgroupOrder.  It's difficult to understand the problem you're having without an example, so you'll have to provide one on jsbin/jsfiddle.

**Comment by yotamberk** [comment]
Try using subgroups
