### ISSUE TITLE
Timeline focus() doesn't center vertically

### ISSUE THREAD

**Issue by instacyber** [almende/vis#2851]
When I call focus() on a specific item ID, it centers the timeline horizontally on this item (i.e. by date) as expected. 

However, when constraining a timeline with a maxHeight and rendering a timeline with more groups than can fit in the view window, calling focus() does not pull the vertical scroll in a way that also displays the selected item if it is not currently visible.

Is this expected behaviour? Examination of the function code in vis.js suggests that it doesn't attempt any vertical correction, which I believe would be helpful to completely enact a "focus" on a specific item.

**Comment by yotamberk** [comment]
You're right! Thanks for reporting

**Comment by rbkn** [comment]
Related:  It looks like getVisibleItems() doesn't take into account vertical visibility, only horizontal.

In ItemSet.prototype.getVisibleItems there's a TODO comment to that effect too.

**Comment by Areson** [comment]
I added this to the duplicate, so I'll add this here as well. This is an [example workaround](https://jsfiddle.net/Areson/z2rsyhow/) with jQuery. It's not heavily dependent on jQuery, so depending on what type of modification this requires it could be adapted to fix this issue.
