### ISSUE TITLE
Events 'click', 'doubleclick' and 'select' not working with IE11

### ISSUE THREAD

**Issue by almute** [almende/vis#2859]
I'm using Timeline inside of a FileMaker Webviewer. This is working perfect with Mac and iOS.

Under Windows I'm having problems with events. The events 'click', 'doubleclick' and 'select' for example don't work while for example 'contextmenu' is working perfect.
It looks like the FileMaker Webviewer is emulating IE11 under Windows 8. I have tried to set it to a newer version of IE, but without success.
When opening the HTML file for my timeline directly in IE of my Windows 10 (which is IE13) all is working.

Are there any know issues with the events 'click', 'doubleclick' and 'select' and IE11?
And if so, are there any other ways how I can start a function when clicking on an item?

Thanks for your help, Almute

**Comment by bradh** [comment]
Can you set up a jsbin / jsfiddle that shows the problem?

**Comment by almute** [comment]
I don't know how to do this.
But meanwhile I have found that the events are working in IE11 with Windows 7. It looks like there is a problem with the emulation of the IE in FileMaker Webbrowser.
So, next I will search in the FM Forum. If I don't find a solution there I will come back to you.
Thanks.
