### ISSUE TITLE
External moment.js does not work properly

### ISSUE THREAD

**Issue by mjurenka** [almende/vis#2861]
Hello,

including external moment.js (from window) does not behave identically to one included as a module for Timeline.
The one from the window can not render timeline for local time.

**Comment by bradh** [comment]
Can you describe your specific configuration? Did you rebuild vis.js? Can you show exact versions and a test scenario?

**Comment by bradh** [comment]
@mjurenka Can you please provide the additional information so we have a chance to reproduce the problem?
