### ISSUE TITLE
Custom fields to newly added item

### ISSUE THREAD

**Issue by asgardia7** [almende/vis#2863]
Hello,

I talk about the timeline. It's my first use. I was being able to initate the timeline with `DataSet`. Those items contained custom field in the object for later use in my template function. It works properly.

Now when I create new item through drag and drop, I see the custom field I pass to `e.originalEvent.dataTransfer.setData` disapear on the road. Looking through the code, I've seen that the `_onAddItem` event listener on `ItemSet` create a `newItemData` so my custom fields or lost.
`Line 23 831` on the vis.js generated file in dist.

How could I store custom fields in the newly created item as I use them to generate the content?

Thanks

**Comment by yotamberk** [comment]
@asgardia7 Thanks for reporting! Legit request. I'm on it.

**Comment by yotamberk** [comment]
Solved with #2872

**Comment by asgardia7** [comment]
Nice,

For now, I modified directly the vis.js file for my purpose. Or is there any workaround without modifying this js?

Thanks,
