### ISSUE TITLE
Can we export vis timeline as pdf or image? 

### ISSUE THREAD

**Issue by MAHESHGONDA** [almende/vis#2867]
hi , 
 Can we export vis timeline as pdf or image?

**Comment by bradh** [comment]
That isn't a function of vis.js, but rather of what you are rendering it to. Do it on the browser side.

**Comment by MAHESHGONDA** [comment]
ok , thank you for the reply

**Comment by mojoaxel** [comment]
For future reference, there are several options:

## Server Side
* http://phantomjs.org/screen-capture.html
* https://github.com/mixu/electroshot

## Browser
* https://pbakaus.github.io/domvas/
* https://github.com/jamesu/htmlcanvas
* http://html2canvas.hertzen.com/
* https://github.com/tsayen/dom-to-image

_By the way: This kind of question is better asked e.g. on [stackoverflow](https://stackoverflow.com/questions/tagged/vis.js)._
