### ISSUE TITLE
Setting nestedGroups property of a group does not un-nest groups

### ISSUE THREAD

**Issue by BTMorton** [almende/vis#2876]
Example can be seen at https://plnkr.co/edit/4P62LCFYbBLbGq2WqRmh?p=preview

When the group property `nestedGroups` is set to null, the group nesting does not clear. In the plunkr, the property is set and the objects passed to the DataSet update method are logged in the console. This is fixed by #2852

**Comment by yotamberk** [comment]
merged in #2852
