### ISSUE TITLE
Group click event when collapsing nested group contains null group ID

### ISSUE THREAD

**Issue by BTMorton** [almende/vis#2877]
When a group with nested groups is collapsed, the `click` event that is triggered does not contain the group ID, which makes tracking the toggle of nested group visibility more difficult.

Example can be seen at https://plnkr.co/edit/GdoPTGkda2w0acanUvxL?p=preview. To reproduce, hide the nested group and check printed event log.

I managed to track this down to the `groupIds` property of the `ItemSet` being empty. It's set to an empty array on line 418 of ItemSet.js in the `markDirty` function. I don't know if this is a requirement for something later in the process or not, so I didn't make a PR for it.

**Comment by mojoaxel** [comment]
@yotamberk Bug or Feature-Request?

**Comment by yotamberk** [comment]
I believe it's a problem but not a high priority one

**Comment by BTMorton** [comment]
Fix demo here: https://plnkr.co/edit/fsYp8dujYp4WZloM17Xt?p=preview

PR incoming...
