### ISSUE TITLE
Timeline does not render on safari

### ISSUE THREAD

**Issue by tokyotoys** [almende/vis#2881]
As mentioned in the title, the timeline will not render on safari browser, this is a serious issue since many users rely on safari to browse website.

Thanks in advance,
A.

**Comment by mojoaxel** [comment]
@tokyotoys Please make sure to use the [latest release](https://github.com/almende/vis/releases) version of vis.js.

**Comment by AoDev** [comment]
@tokyotoys It works for me in safari. But it "flickers" all the time. (would need a screencast to show).  (vis 4.18.1)

**Comment by bradh** [comment]
If you are using 4.19.1 from the visjs.org zipfile, or from npm, you may have hit #2912.

**Comment by jgorene** [comment]
Hello,
It works like a charm on Ipad with the latest release ...
Even if there are still some tricks to optimize, really nice !
