### ISSUE TITLE
Dragging CustomTime throws error

### ISSUE THREAD

**Issue by knokit** [almende/vis#2884]
To reproduce the issue drag the custom time bar: http://visjs.org/examples/timeline/other/customTimeBars.html

I found out that `util.elementsCensor()` was renamed to `stringifyObject` (here: f5b43e8518766dc23383417a7c72f438f4a46b17), however it was not renamed in *CustomTime.js*.

**Comment by ilaipi** [comment]
I met this bug. Hope to fix it quickly. thanks

**Comment by yotamberk** [comment]
Will be fixed in the next release
