### ISSUE TITLE
.vis-even / .vis-odd not available on Timeline

### ISSUE THREAD

**Issue by knokit** [almende/vis#2888]
`.vis-even` and `.vis-odd` are not available on **Timeline** when the zoom level is equal to days.

On the following example, zoom out one level and inspect the time-axis elements (vis-even/vis-odd classes disappeared): http://visjs.org/examples/timeline/basicUsage.html

Also, the classes used for days are different from what is described in the documentation: http://visjs.org/docs/timeline/#Styles
Docs say it should be `vis-date1` but the timeline renders `vis-day1`.

**Comment by mojoaxel** [comment]
Two issues:
1. bug in the timeline docs. Should be `vis-day1, vis-day2 ...`
2. classes `vis-even` and `vis-odd` don't get added in some zoom levels.

**Comment by bradh** [comment]
The vis-even / vis-odd should be resolved as part of https://github.com/almende/vis/pull/2909
