### ISSUE TITLE
how to controle the top of items in visjs

### ISSUE THREAD

**Issue by estem** [almende/vis#2889]
Hi, i want to controle the top of the items in the timeline, i mean i want the red item in the bottom and the others on the tob .

**Comment by bradh** [comment]
This makes no sense to me. Can you try explaining what you mean by the "red" item? A jsbin or jsfiddle might help a lot here. Perhaps also a diagram showing what you want?

**Comment by estem** [comment]
take a look here: https://github.com/almende/vis/issues/2890
