### ISSUE TITLE
How to control the top of the items in timeline

### ISSUE THREAD

**Issue by estem** [almende/vis#2890]
Hi guys i want to controle top of my timeline items, i want the red one in the bottom and the others on the top like this one :
![wqas](https://cloud.githubusercontent.com/assets/22663273/24192185/06f896fa-0ee6-11e7-89cd-261994a7f938.png)

heres the code:
```
storyboard.initialisation=function(items){

  // DOM element where the Timeline will be attached
  var container = document.getElementById('visualization');
  //$scope.currentDate
  //$scope.tomorrowDate

  var options = {
    width:'99%',
    min: $scope.currentDate,
    max:$scope.tomorrowDate,
    height:'78px',
    zoomable:false,
    showCurrentTime:true,
    stack:true,  //to fix stack=false i have to change margin-top above
    //zoomMax:10,
    zoomMin:10,
    //type:'background',
    //
    showMajorLabels:false,
    margin: {
      axis:0,
      item:0
    },
    format:{
      minorLabels: {
        minute:'mm',
        hour: "HH[h]"
      }
    }
  };
  // Create a Timeline
  timeline = new vis.Timeline(container, items, options);
}
```
is there way to do that please help???

**Comment by yotamberk** [comment]
use the `order` property to order your items such that red items (have them contain a class of e.g. 'red') are always < than items that don't have a class of 'red'. Understood?

**Comment by estem** [comment]
thank you ser for your answer...actually now i used groupe to put every color in single dev..but is there any better solution..pleasee..explain please..i didnt got you point??

**Comment by yotamberk** [comment]
look here http://visjs.org/docs/timeline/#Configuration_Options under the `order` option.
See example http://visjs.org/examples/timeline/items/itemOrdering.html
