### ISSUE TITLE
Mirroring draw

### ISSUE THREAD

**Issue by levin-kelevra** [almende/vis#2891]
While using draw data for GPS coordinates:
How it should be:
![image](https://cloud.githubusercontent.com/assets/4024330/24195614/735b7464-0f0b-11e7-8cc9-de1dae1da05b.png)

How it work now:
![image](https://cloud.githubusercontent.com/assets/4024330/24195525/2a592fcc-0f0b-11e7-9127-a6bea469d0e3.png)

Why VisJS draw track with mirror view?

version: latest from GIT.
style: dot-color

**Comment by levin-kelevra** [comment]
Graph3D

**Comment by wimrijnders** [comment]
Ага, `Graph3D`. Это моё дело. Попробоваю тебе ответить.

Do you perhaps have example code for me that illustrates the issue? Perhaps something in [jsbin](https://jsbin.com).

**Comment by levin-kelevra** [comment]
https://jsbin.com/hopinaceku/edit?js

**Comment by wimrijnders** [comment]
Thanks. It's not running due to errors, would you mind fixing it?

**Comment by levin-kelevra** [comment]
https://jsbin.com/pafayufafu/edit?js
But w/o data response

**Comment by wimrijnders** [comment]
OK, I can get this to run with some minor changes.
But some data would be useful. Do you mind adding a couple of data points to illustrate the problem?

**Comment by mojoaxel** [comment]
@levin-kelevra Do you want to disable/hide the axis grid?

**Comment by levin-kelevra** [comment]
@mojoaxel How it can help? I'd tried to disable axis grid, but it still not working for me.

**Comment by wimrijnders** [comment]
I did some research, the clearest description I found is [here](http://edndoc.esri.com/arcsde/9.1/general_topics/what_coord_sys.htm).

I think what is happening, is that the coordinates are mixed up:

```
                    var x = response[t].latitude;
                    var y = response[t].longitude;
```

These should be the other way around. From the link:

>  In this case, longitude values are considered the x-coordinate, while latitude values are the y-coordinate.

I hope this help.

**Comment by levin-kelevra** [comment]
@wimrijnders, thank you!
it works for me )
