### ISSUE TITLE
Request for label for breaking changes in API

### ISSUE THREAD

**Issue by wimrijnders** [almende/vis#2895]
_This issue is intended for maintainers_

While reviewing the file `labels.md`, I noticed the following text:

>  ### `Requires breaking change`
>  A lot of code needs to be changed to implement this. This is maybe something for a major release or something for someone with a lot of time on their hands :-)

While I understand the need to label this, this does not fit my understanding of a 'breaking change'.

My definition of 'breaking change' is: 'requires users to change something in their own code to use this'. Hence, something in the outer API has changed.

The given description implies that it's 'a lot of work', i.e. in general internal stuff. I don't agree this is the good description.

I would rather see distinct labels for these. If you want to keep `Requires breaking change` as is, I would suggest e.g. `Breaking change in API` for the former description.

I hope that there is discussion possible over this.

**Comment by wimrijnders** [comment]
For reference, @mojoaxel made the following comment about this:

> Maybe we can merge this and discuss in an seperate issue if we want to introduce 'Major', 'Minor', 'Patch' labels for Pull-Requests. (Instead of the old "Breaking change label).

**Comment by mojoaxel** [comment]
I would like to have labels like `Major`, `Minor` and `Patch` for pull requests. The Label `Requires breaking change`is not very useful in my opinion. We might use it mark `Feature Requests` as "much work" but I think we don't need it.
