### ISSUE TITLE
basicUsage.html example not working or showing.

### ISSUE THREAD

**Issue by pageii** [almende/vis#2896]
Example not working or showing.

Issue:
Running examples>network>basicUsage.html produces a blank canvas. Blank canvas happens for many other example endpoints too.

Seems that the dependency loaded from the dist folder is causing the issue. 
`  <script type="text/javascript" src="../../dist/vis.js"></script>`

Solution:
Use dependency direct from visjs.org
`  <script src="http://visjs.org/dist/vis.js"></script>`

**Comment by bradh** [comment]
It works fine for me (both locally and on the website). Can you provide some more details on the process you used to get to try to run the example? For example, what you checked out or download, what build steps you ran, and how you tried to load the example?

**Comment by pageii** [comment]
the file is downloaded from http://visjs.org/index.html#download_install @ download --> v4.19.1.zip.

The example was run as-is on Chrome.

**Comment by wimrijnders** [comment]
Works for me as well on chromium, both locally and with `visjs.org` link.

I would prefer not to set a link to the site in the examples, because the versions of the download and the site may differ. I'm wondering if this is a chrome issue, as in [blocking loading of local files](http://chrome-allow-file-access-from-file.com/), or a [page refresh not refreshing all files](http://www.code-pal.com/quick-tip-clear-cache-hard-refresh-on-chrome/).

**Comment by pageii** [comment]
Here's some info
===
Chrome-Mac Ver used (updated as per time of writing). Version 57.0.2987.110 (64-bit).
Console error message:
basicUsage.html:27 Uncaught ReferenceError: vis is not defined
    at basicUsage.html:27
===

CORs is not likely the issue.

**Comment by bradh** [comment]
I think it could be the same as #2912 .

**Comment by pageii** [comment]
The same is repeatable on Safari/Mac.  I sidesteped the issue by using a direct download from http://visjs.org/dist/vis.js.

**Comment by bradh** [comment]
Try opening your local vis.js, go to line 3386, and delete the "space" after the `||`.

**Comment by pageii** [comment]
That did it. I'm using VSC. No hidden characters visible though. Thanks.

**Comment by bradh** [comment]
OK, safe to call this another duplicate of #2912.
