### ISSUE TITLE
Network: Save node color

### ISSUE THREAD

**Issue by kowdykung** [almende/vis#2897]
Now I am using saveAndload example file and seem like it doesn't support to save the node color. 
I can get the position for the network but when I update node with this following
`nodes.update({id: idnode2, color: "#f691b2"}); `
the current network color that show was changed But when I export it I only get the position. So, how can I save all of the updated nodes or maybe only the node color?

Here is my export file function.
```
function exportNetwork() {
                var nodes = objectToArray(network.getPositions());

                nodes.forEach(addContextualInformation);

                $.ajax
                        ({
                                type: "POST",
                                dataType : 'json',
                                async: false,
                                url: 'http://localhost/save_json.php',
                                data: { data: JSON.stringify(nodes, undefined, 2) },
                                success: function () {alert("Thanks!"); },
                                failure: function() {alert("Error!");}
                        });
        }
```

**Comment by wimrijnders** [comment]
`network.getPositions()` only deals with the x and y coordinates of the nodes, as the name implies.

I think the best way to have access to the colour, is to use a `DataSet` for your node definitions. Have a look at the code of [this demo](http://visjs.org/examples/network/data/dynamicData.html) to see how it works.

Assuming you have set up the nodes in a `DataSet`:

```
        function draw() {
            // create an array with nodes
            nodes = new vis.DataSet();
            nodes.add([
                {id: '1', label: 'Node 1'},
                ...
            ]);
...
            // create a network
            var container = document.getElementById('network');
            var data = {
                nodes: nodes,
                edges: edges
            };
            var options = {};
            network = new vis.Network(container, data, options);

        }
```
_(Please see example page for more complete code)_

You can then manipulate the node elements directly:
```
nodes.update({id: 1, color: "#f691b2"});
```

And can also read them to access e.g. the colour:

```
nodes.get();
```

Which will return something like:

```
[
    {
        "id": 1,
        "label": "Node 1",
        "color": {
            "background": "#f691b2"
        }
    },
...
]
```

I hope this helps.

**Comment by kowdykung** [comment]
Now I can load the network from JSON file when I directly edit in JSON file 
`{
    "x": 210,
    "y": -41,
    "id": 0,
    "color": "#f691b2",
    "connections": [
      1
    ]
  },`
So how to get nodes.get(); into json file, as I following the demo in saveAndload.html
In export function when it's call `nodes.forEach(addContextualInformation);`

`function addContextualInformation(elem, index, array) {
  					addId(elem, index);
  					//addColor(elem, color);
  					addConnections(elem, index);
  			}`

And continue with call addID, addConnections
So, I create addColor function to export node color to JSON file but I don't know how to get each node color can you give me some hint or another way to do this.

**Comment by wimrijnders** [comment]
I'm not really understanding your example; which way do you want to copy, into the nodes structure or out of it?

In both cases, the path to use is `elem.color.background`. So:
```
  elem.color.background = color;    // set the colour
  color = elem.color.background;    // get the colour
```
I personally feel this is clear enough from the sample struct I gave. But perhaps I misunderstood?

**Comment by kowdykung** [comment]
From your answer, now I can load the network from JSON (with its node color) but I can't save the node color when I'm saving network into JSON.

I want to save the color of each node into JSON.

![image](https://cloud.githubusercontent.com/assets/22632981/24324135/4dd51b5a-11b3-11e7-8ee0-a605be4d0d6c.png)

`function addContextualInformation(elem, index, array) {
  addId(elem, index);
  elem.color = { background : "#ffff00"};     // Add your color here
  addConnections(elem, index);
}`

This elem.color should be the color of each node

**Comment by wimrijnders** [comment]
Is you question how to retrieve the color from the dataset? Then, for example, to access the color of the first node:
```
var data = nodes.get();
var color = data[0].color.background;
```
And you can put this value into your JSON structure.

If your question is how to make this JSON output, see how `JSON.stringify()` is used in function `exportNetwork()`, in the `saveAndLoad` example.

I think this should be enough information so that you can build the required functionality into your application.

**Comment by kowdykung** [comment]
In `saveAndLoad` example, I need to modify the `addContextualInformation` to add node color in JSON but My question is how I can retrieve each node color to add along with this function?

```
function addContextualInformation(elem, index, array) {
  addId(elem, index);
  elem.color = { background : "#ffff00"};     // I NEED TO ADD EACH NODE COLOR TO THIS elem.color
  addConnections(elem, index);
}

```

**Comment by wimrijnders** [comment]
Please see my previous answer. That's really how you do it. I'll edit to remove the second part.

**Comment by kowdykung** [comment]
Thank you very much :)) 
I can do it because of my `nodes.get()` return only "color": "#f691b2"
So, I have to write 

```
var data = nodes.get();
var color = data[0].color;
```

That was the problem 👍

**Comment by wimrijnders** [comment]
:smile: I'm happy you've figured it out!

**Comment by bradh** [comment]
Can this be closed?

**Comment by golflv100** [comment]
yes, please close it.

**Comment by mdre** [comment]
Hi! 
I'am using this to export / load everything in the graph:
```
Network.prototype.exportNetwork = function () {
    console.log("exportNetwork!!\n\n");
    // actualizar las posiciones
    this.nk.storePositions();
    
    console.log("dataSet: ",this.data);
    //recuperar la info desde el dataset
    var nodeData = objectToArray(this.data.nodes._data);
    var edgesData = objectToArray(this.data.edges._data);

    var expData = {
        nodes: nodeData,
        edges: edgesData
    };
    var exportValue = JSON.stringify(expData, undefined, 2);
    console.log("export:", exportValue);

    console.log("-------------------------\n\n");
    return exportValue;
};


function objectToArray(obj) {
    return Object.keys(obj).map(function (key) {
        return obj[key];
    });
}


Network.prototype.setData = function (data) {
    console.log("setData:\n\n", data);
    var jsondata = JSON.parse(data);
    var nodesData = new vis.DataSet(jsondata.nodes);
    var edgesData = new vis.DataSet(jsondata.edges);
    
//    console.log(this.data);
    console.log("json: ", jsondata);
    console.log("nodesData: ", nodesData);
    console.log("edgesData: ", edgesData);

    this.nodes = nodesData;
    this.edges = edgesData;
    
    this.data = {
        nodes: nodesData,
        edges: edgesData
    };

    this.nk.setData(this.data);
    this.nk.redraw();
    this.nk.stabilize();
    console.log("-------------------------\n\n");
};
```
I have extended the object. this.nk is the vis.Network object.
