### ISSUE TITLE
Strange Charater prevents start of script on OSX (Safari / Chrome)

### ISSUE THREAD

**Issue by MarcusMiss** [almende/vis#2898]
In file vis.js is an invisible character in line 3386 before just before the expression _this._ordinalParse_. In BBEdit it is shown as a big dot. When I replace this character with an regular space-character it is working as expected.
I was using version 4.19.1 (downloaded as ZIP).

**Comment by yotamberk** [comment]
What module are you referring to?

**Comment by mojoaxel** [comment]
@yotamberg I think it is our job, to figure this out.

**Comment by bradh** [comment]
Possibly the same issue as #2912
