### ISSUE TITLE
Network - huge network does performance go down

### ISSUE THREAD

**Issue by JMGonzalezR** [almende/vis#2900]
Hi, im working with a huge data and i want to make a tree with that, but the performance go down, arround 10 mins to show the data and take a lot to zoom in.

So what is the limit  for total number of nodes, to have it with a great performance ?

**Comment by wimrijnders** [comment]
I've recently looked at #2906, which is a similar question.

The performance of rendering the layout is best when any of the following conditions holds:

- The network consists of < 100 nodes
- The networks consists of clusters of nodes, where the cluster are connected to each other by a single edge
- More than half of the nodes have the xy-coordinates pre-configured

In these cases, you can use options `layout.improvedLayout: true` to get a better rendering.

For zooming, I am not aware of any option to improve this. I have the suspicion that disabling the physics module with `physics.enabled: false` might improve the performance, but this is an informed guess only.

It might be worthwhile to play around with the `physicsConfiguration` example, to see if a combination of physics options gives you a better performance.

**Comment by wimrijnders** [comment]
You might also consider setting a value for option `physics.stabilization.iterations`.

Based on experience with #2906, this reduces the initial rendering from minutes to seconds, at the expense of having a blank view during that time on initialization.

**Comment by JMGonzalezR** [comment]
Thanks a lot, that works a little bit, in my team decide to use the 3dgraph instead, it can handler huge data and is pretty nice.

**Comment by wimrijnders** [comment]
:+1: Glad your team has found a solution that works for them.

**Comment by shangxinbo** [comment]
I have tried various physics configuration item combinations. In my test, I got a best option for me to display huge data
```
{
impovedLayout: true,
physics: {
  stabilization: {
     iterations:100
  },
  timestep:1
}
