### ISSUE TITLE
Group height and Item Top property

### ISSUE THREAD

**Issue by AndreAlves10** [almende/vis#2901]
Hello,

I´m styling my timeline by changing the group height and each item top property. However the CSS seems not to be used, i.e., the group height is not changing and items' top property is not changing.

The following jsfiddle demonstrates the problem:

http://jsfiddle.net/e7uodse2/1129/

The CSS is the following:
```
.vis-label, .vis-group {
  height: 20px;
}

.vis-item {
  top= 1px;
}
```
Any ideas why this styling is having no effect on my timeline?

Thank you!

**Comment by yotamberk** [comment]
The top and heights are calculated and assigned in the code itself. You should NOT change these properties via CSS. Overwriting these properties is possible using `!important` on the CSS assigning, but again, if you want to change height and top, use timeline options.

**Comment by AndreAlves10** [comment]
Thank you @yotamberk.

Can you give me a hint on which timeline options should I change in order to change the height and top properties?

**Comment by jgorene** [comment]
Hello,
To change or adapt height, some tracks that I practice personally but that one must be able to optimize..
First change margin in timeline options 
`    margin: {
        item: 5
    }
`
You can also add your css rules to adapt according to content (group and item) ...
I also practice like that and it works well for now while waiting for better solutions;)
Below just for example
`.vis-nested-group {
  white-space: normal;
}
.vis-item .vis-item-content {
white-space: nowrap;
box-sizing: border-box;
padding: 2px;
}
`

**Comment by AndreAlves10** [comment]
Thank you for your help @jgorene.

**Comment by jgorene** [comment]
@AndreAlves10, you're welcome ;)
If you think we have answered your question, please close this issue ...
