### ISSUE TITLE
Adding to ExtJs4.1 Rally-App-Builder node deploy just displays rendered code

### ISSUE THREAD

**Issue by cookra** [almende/vis#2902]
All i get is:
"),t.close(),h=t.F;o--;)delete h.prototype[s[o]];return h()};t.exports=Object.create||function(t,e){var i;return null!==t?(a.prototype=o(t),i=new a,a.prototype=null,i[r]=t):i=h(),void 0===e?i:n(i,e)}},function(t,e,i){var o=i(21),n=i(22),s=i(35);t.exports=i(25)?Object.defineProperties:function(t,e){n(t);for(var i,r=s(e),a=r.length,h=0;a>h;)o.f(t,i=r[h++],e[i]);return t}},function(t,e,i){var o=i(36),n=i(44);t.exports=Object.keys||function(t){return o(t,n)}},function(t,e,i){var o=i(31),n=i(9),s=i(37)(!1),r=i(41)("IE_PROTO");t.exports=function(t,e){var i,a=n(t),h=0,d=[];for(i in a)i!=r&&o(a,i)&&d.push(i);for(;e.length>h;)o(a,i=e[h++])&&(~s(d,i)||d.push(i));return d}},function(t,e,i){var o=i(9),n=i(38),s=i(40);t.exports=function(t){return function(e,i,r){var a,h=o(e),d=n(h.length),l=s(r,d);if(t&&i!=i){for(;d>l;)if((a=h[l++])!=a)return!0}else for(;d>l;l++)if((t||l in h)&&h[l]===i)return t||l||0;return!t&&-1}}},function(t,e,i){var o=i(39),n=Math.min;t.exports=function(t){return t>0?n(o(t),9007199254740991):0}},function(t,e){var i=Math

**Platform:**

OSX 10.12.3
Chrome: Version 57.0.2987.110 (64-bit)

**Chart:**

Network

<script>document.F=Object</script>

tried the following

<script>document.F=Object</"+"script>"

------
Anyone even tried this before? I have it kind of working locally but when I run the App.html the above happens...

Might not like ExtJs4???
<img width="170" alt="screen shot 2017-03-25 at 00 27 25" src="https://cloud.githubusercontent.com/assets/5142297/24317702/e62df0e2-10f1-11e7-864c-6a4419692399.png">

------

**Node Deploy:**

<!DOCTYPE html>
<html>
<head>
    <title>nodes</title>

    <script type="text/javascript" src="https://rally1.rallydev.com/apps/2.1/sdk-debug.js"></script>

    <script type="text/javascript">
        Rally.loadScripts(
                [
                      "../../Agile Central Builds/Agile Central Common/vis/vis.js",
                      "App.js",
                ],
        function() {
            Rally.launchApp('CustomApp', {
                name:"nodes"
            });
        }, true);
    </script>

    <link rel="stylesheet" type="text/css" href="../../Agile Central Builds/Agile Central Common/vis/vis.css"/>
    <link rel="stylesheet" type="text/css" href="app.css"/>
</head>
<body>
    <div id="visualization"></div>
<script type="text/javascript">
  // DOM element where the Timeline will be attached
  var container = document.getElementById('visualization');
  // Create a DataSet (allows two way data-binding)
  var items = new vis.DataSet([
    {id: 1, content: 'item 1', start: '2013-04-20'},
    {id: 2, content: 'item 2', start: '2013-04-14'},
    {id: 3, content: 'item 3', start: '2013-04-18'},
    {id: 4, content: 'item 4', start: '2013-04-16', end: '2013-04-19'},
    {id: 5, content: 'item 5', start: '2013-04-25'},
    {id: 6, content: 'item 6', start: '2013-04-27'}
  ]);
  // Configuration for the Timeline
  var options = {};
  // Create a Timeline
  var timeline = new vis.Timeline(container, items, options);
</script>
</body>
</html>

**Comment by mojoaxel** [comment]
This is clearly no vis.js issue!

**Comment by cookra** [comment]
You almost got tl;dr!

But.. having read your one-liner several times (trying to take in the depth, scope, meaning and you full social ) I must conclude you either work for Apple support or don't really understand the problem.. vis.js issue or not it may be interesting to see where people are trying to place this code and from a real world point of view what our trusted community of fellow coders are trying to do.. 

Searching through the web including Tor, this issue has never been raised - so there we are a Eureka moment someone tried to do something with your code that you didn't like...

As you know this will end in Godwin' Law, not so much of Poe's BUT you have already proven Scopie's Law. In danger of myself falling into the trap of Danth's Law (You may know it as Parker's Law - depends on your particular bias - I already see there are many), you should by know be warming up to humanity and dropping the arrogance (this means you are - again I'm wishing here, so stay with me discovering Pommer's Law)..

Interesting paradox though - you by no means follow DeMyer's [second law] (this is good!), I on the overhand, have fallen deep into the trap - (see this is what makes us human).. Mind you I must point out that based on your one line response - taking into account you exclamation mark to word count ratio you my trusted friend (I guess by this point we are friends) are shadowing around the darkside of, wait for it........ you need to read this next bit in a dark, loud and echoey voice... (THE LAW OF EXCLAMATION!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!).

Let's deep dive into your response though, I have two hours free at the moment with little else to do other than Duty Free and eat breakfast with a Spork... (Spork! wtf is it 50% spoon 50% fork (and that's if you are lucky - I wonder who does the R&D and QA for these.. madness).. Had an idea earlier that you could have Sporkfe but quickly disposed of the idea as there would be no practical use of having the knife and fork attached to each other (mind you my friends are still arguing the fact and creating all kinds of prototypes here at Heathrow.. Well blow me (trusted Google) (sorry for the multitasking - but I have a WIP limit of three)  it already exists!

![16662_1](https://cloud.githubusercontent.com/assets/5142297/24321632/de0c6f7c-1148-11e7-9e50-c6dc097da73e.jpg)

[http://www.lakeland.co.uk/16662/Lakeland-Alexandra-Cutlery-4-Stainless-Steel-Buffet-Spork-Forks-?gclid=CPeapfm98dICFdEy0wodJzAFcw&src=gfeed&s_kwcid=AL!49!3!106860758069!!!g!45641261162!&ef_id=WH-P8QAAAAIUOkVT:20170325105000:s](url)

[Retraction] Would be a great item for eating an apple pie as suggested by Mike just know - as you can imagine the ideas about it's usage are coming in thick and fast now;) (Note the Emoticon, this is me reaching out to you and trying to remove the barriers of this faceless mode of communication). Mind you I see you are not faceless as you are you (i hope or that's just odd/governmental) in your avatar.. I on the other hand use a gas mask that i designed years ago, this is because my face face was disfigured by a horrible accident when I was 12 involving a petrol, an opened disposable camera and it's high capacity capacitor (Woooooooof) - think Deadpool (but not the unicorn bit)..

Likewise we obviously have NO practical use for vis.js within our organisation, which is a shame because we believe it to be one of the best out there - Kudos to the whole team and not support.. You may however be interested in the <script>document.F=Object</script> with chrome on some integrations.. To be honest i'm over it now, this is all about us now Majoaxel and how e can better the world together and improve our Anglo German relations (even if you did win the football last week, mind you its a girls game imho [https://www.youtube.com/watch?v=aHkp7SghaPM](url))

Anywho.. Lets keep on track, time for the Sigmund bit, let's retrospectively rip the crap out of your response: 

**This is** = Directive, authoritative, empowering, commanding (these are not good attributes btw)
**This is clearly** = Hey everyone look at this this, you must ALL join me in my opinion..
**This is clearly** = Defining a guild based on your opinion (go Spotify, go Guilds)!
**This is clearly** = Looking for group/herd approval by those who are as clever as you!
**This is clearly** = It's just a dumb thing to write dude...
**This is** = Immediate authoritative tense, could mean you are possessive in nature
**Clearly** = My word this guy is dumb as F* 
**no** = I'm just surprised you didn't ** or capitalise that one up..
**vis.js** = Is what it is I guess..
**issue** = again, is what it is..

! We need to pay more attention to this bad-boy:-
**!** = BOOM, standby we could right a novel on this little mother******. I don't think face to face you would shout at me.. Scrap that - you wouldn't shout at me face to face end of (Rarrrrrrrrgh)..
**!** = Confirms you are an empowering and dominating character full of self importance, opinions and beliefs..
**!** = You don't play well with others..
**!** = This is!! W!thout quest!on the most over and incorrectly used piece of punctuation out there..
**!** = You don't actually give a F about others, although you hang around the issues section of GitHub. this is due to a lack of 'outside' activities and consider the Mists of Pandaria a safer alternative to going outside (been there got the T-shirt, did 100 over 5 toons - not even sure what the lvl cap is now... One sec..... Google time... 110!)
**!** = You are way too overeager - chill-f-out..
**!** = Your understanding of it's use is incorrect..

Anyway joking aside this has kept us amused at the airport this morning, as we are off to beucoup sunshine 'Hola Mexico'!

In the end this may even fall foul to Tabea Rehle - who knows? But, if you didn't tl;dr go for it.. Cohen's Law is the next response you make!

**Comment by cookra** [comment]
But you posted this on twitter... Cohen's Law, instagram next? ROFL LOL YOU MADE MY DAY!

Weather is amazing bti, wish you were here! X
