### ISSUE TITLE
POLL: ESlint coding style

### ISSUE THREAD

**Issue by mojoaxel** [almende/vis#2904]
_This is a poll to find a new coding style for the whole vis.js library._

The rules:
* You can add your own proposal. (Please add a link to a [ESlint shareable-config](http://eslint.org/docs/developer-guide/shareable-configs).)
* No discussions or anything. You can discuss code-style things in #2697.
* Don't add a comment to vote!! Use the :+1:  and :-1: icons on each comment to vote (example below).
* The coding style mostly approve and least opposed will be chosen. 
* The final desition will be done by the [support team](https://github.com/almende/vis/blob/develop/misc/we_need_help.md).

**Comment by mojoaxel** [comment]
[StandardJS](https://standardjs.com)
https://github.com/feross/eslint-config-standard

**Comment by mojoaxel** [comment]
[AirBnB](https://github.com/airbnb/javascript)
https://github.com/jscs-dev/node-jscs/blob/master/presets/airbnb.json

**Comment by mojoaxel** [comment]
[Wikimedia](https://www.mediawiki.org/wiki/Manual:Coding_conventions/JavaScript)
https://github.com/wikimedia/jscs-preset-wikimedia/blob/master/presets/wikimedia.json

**Comment by mojoaxel** [comment]
[Wordpress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/)
https://github.com/jscs-dev/node-jscs/blob/master/presets/wordpress.json

**Comment by AoDev** [comment]
["eslint:recommended"](http://eslint.org/docs/rules/)
Is a simpler code style that could be better to start with.

**Comment by wimrijnders** [comment]
Scanned the list, @AoDev's suggestion is a pretty sane one to begin with.

**Comment by wimrijnders** [comment]
This is to notify that PR #3230 is pending, which will use `eslint:recommended` (@AoDev's suggestion) as a starting point for further linting.

I think that we can close this issue now; feel free to reopen if this is still relevant.
