### ISSUE TITLE
SyntaxError in version 4.19.1

### ISSUE THREAD

**Issue by charger** [almende/vis#2912]
STR:
* `npm install vis@4.19.1`
* index.html
```html
<!DOCTYPE HTML>
<html>
<head>
  <title>Timeline basic demo</title>
  <script src="node_modules/vis/dist/vis.js"></script> 
</head>
</html>
```
* In browser error in console: `Uncaught SyntaxError: Unexpected token this vis.js:3386`
vis.js:3386
```js
          (this._dayOfMonthOrdinalParse.source ||Â this._ordinalParse.source) +
              '|' + (/\d{1,2}/).source);
 ```

I can't understand why there i s character `Â`. In version on CDN is all clear, but install from `npm` is broken for me.

**Comment by bradh** [comment]
I'm not seeing it (at least not yet). That line appears to be coming from moment.js.

**Comment by bradh** [comment]
OK. Its in the zipfile.

**Comment by bradh** [comment]
So workaround is to edit vis.js as shown in #2896.
Open your local vis.js, go to line 3386:
`(this._dayOfMonthOrdinalParse.source || this._ordinalParse.source) +`
and delete the "space" after the `||` and before `this._orginalParse.source) +`.

There is probably a hidden character. How it shows up depends on your editor.

**Comment by charger** [comment]
Also, I can use `vis.min.js` or install a previous version.

**Comment by mojoaxel** [comment]
Has anybody any idea how this could have happened?

**Comment by mojoaxel** [comment]
It seems to be an bug in moment.js https://github.com/moment/moment/pull/3853

**Comment by radames** [comment]
the version 4.19.1 from cdnjs is working well but the version downloaded from  https://github.com/almende/vis/archive/v4.19.1.zip here is not, does anybody know why?

**Comment by wimrijnders** [comment]
@radames I have no clue without further info. All I can say is that the versions of `vis.js` are identical and that they (thus) both have the strange space character as described in this issue.

**Comment by wimrijnders** [comment]
@radames I have no clue without further info. All I can say is that the versions of `vis.js` are identical and that they (thus) both have the strange space character as described in this issue.

**Comment by bradh** [comment]
@radames possibly built from different versions of moment.js

**Comment by wimrijnders** [comment]
@bradh No, identical. Checked with `diff`.
