### ISSUE TITLE
How to change color of vertical grid-line/axis on timeline?

### ISSUE THREAD

**Issue by IsaacHub** [almende/vis#2919]
![chrome_2017-03-27_18-21-19](https://cloud.githubusercontent.com/assets/20126441/24357162/6107950a-131a-11e7-9430-077ea06bc7b5.png)

As you can see, how do I change the color of those vertical lines _(7 in this screenshot)_ ? 
I need this for my project so it can match with my website's base theme color.

I thought it would be border-right or border-left, but I couldn't find the associated css rule.

**Comment by bradh** [comment]
Looks like `.vis-grid.vis-minor` should do it. You may want to do `vis-major` too, depending your your needs. (I just got this from inspecting the elements, I didn't try to build a full example - consider a jsbin if you still need help).

**Comment by IsaacHub** [comment]
`.vis-grid.vis-minor` did the trick, thanks.
