### ISSUE TITLE
How to get the start and end dates of a selected item

### ISSUE THREAD

**Issue by estem** [almende/vis#2921]
I'm using visjs library with angularjs i want to get the start and end dates of a selected item how can i do that ???

timeline.on('select', function (event) {
                  alert('Right click!');
                  var props = timeline.getEventProperties(event)
                  alert(props);
                });

i tried this but it didnt work out

**Comment by bradh** [comment]
http://visjs.org/examples/timeline/interaction/eventListeners.html shows how to get the start date. I think getting the end date for range items would be a valid feature request.

**Comment by jgorene** [comment]
You will find this on the [page of examples](http://visjs.org/timeline_examples.html) really well done
Especially [this one](http://visjs.org/examples/timeline/interaction/eventListeners.html) which speaks of the different listening possibilities for events whose event "select" ...

**Comment by estem** [comment]
thnaks

**Comment by mojoaxel** [comment]
@estem Please close this issue, if your question is answered.

**Comment by jgorene** [comment]
@estem, Hello,  is the answer appropriate for closing this thread ;)

**Comment by bradh** [comment]
@estem Please reopen with additional details if needed.
