### ISSUE TITLE
Physics simulation works only when the tab is active

### ISSUE THREAD

**Issue by maamounkhlifi** [almende/vis#2923]
Hello

I'm using 4.19.1 version, the simulation stops when i change the browser tab (same issue with chrome and firefox), it resumes only when i reopen the tab where the network is active!

**Comment by wimrijnders** [comment]
Hi, this is not a `vis.js` issue. I believe the browser are built so that inactive tabs do not do any javascript execution. Here is a [confirmation for chrome](http://stackoverflow.com/a/22070842/1223531) of this by a Google engineer.

**Comment by wimrijnders** [comment]
Closing this issue now; it's not an immediate `vis.js` problem.
