### ISSUE TITLE
How to scroll to current time in timeline?

### ISSUE THREAD

**Issue by IsaacHub** [almende/vis#2928]
I'm using this plugin with leafletJS.
By default I've set up the timeline slider to playback a GPX in the past time _(Jan-2016)_ 
So the timeline **(the custom playback)** is set up to display the _jan 2016_ and it shows up. 
Sometime later I want to go to current time slider, so I manually zoom-out and drag the slider to get to the current time..

Could you please tell me how to do this programatically through Javascript or jQuery with a click of a button??

**Comment by ilaipi** [comment]
u can call `moveTo` method of the `timeline` instance.

**Comment by IsaacHub** [comment]
@ilaipi 
I have done so, but it gives the following error, while I click a button:

`Uncaught Error: Invalid start "NaN"`

Here is my code:

```
var timeline = new vis.Timeline(document.getElementById('timeline'), timelineData, timelineOptions);

function spotNow(){
  timeline.moveTo("31-03-2017");
}
$(document).on('click','#spotNowBtn',function () {
  spotNow();
});
```

It throws at line `timeline.moveTo` method. What am I missing?

**Comment by bradh** [comment]
@IsaacHub is that a valid date? Try "2017-03-31".

**Comment by yotamberk** [comment]
The date is invalid. What @bradh works
