### ISSUE TITLE
Hierarchical graph rerenders when adding/removing nodes/edges

### ISSUE THREAD

**Issue by Radivarig** [almende/vis#2931]
Hierarchical graph always rerenders. I've opened #2930 for preventing rerendering if the `options.layout` does not change, but adding/removing nodes/edges would require a separate fix.

**Comment by wimrijnders** [comment]
Hi, I'm not sure if I understand this.

> but adding/removing nodes/edges would require a separate fix

If edges or nodes are added or removed, doesn't this imply that the graph _has_ to be rerendered?

Could you describe the scenario that you have in mind? Perhaps give a working example?

**Comment by Radivarig** [comment]
Scenario is to add a new node to the end of some level and not having the existing nodes positions recalculated from scratch (as they were either dragged or aligned by the simulation). I achieved this with `fixed.x` and setting custom x by levels based on edge directions in non hierarchical layout.

**Comment by wimrijnders** [comment]
OK, I understand.
I see that the `saveAndLoad` demo handles this perfectly. However, the calls associated with adding nodes and edges are not exposed in the interface of the `vis.Network` instance.

I'll have to think about this. If you have any suggestions, please let me know!

**Comment by wimrijnders** [comment]
@Radivarig #3096 is a similar issue to this one. Can you check if the supplied workaround there is suitable for your needs?

**Comment by wimrijnders** [comment]
Duplicate of #3096.
