### ISSUE TITLE
Timeline: multiple levels of nested groups

### ISSUE THREAD

**Issue by JGdijk** [almende/vis#2933]
timeline 
version  4.19.1
browser Chrome

When trying to add multiple levels of nested groups the collapsing of groups seems to break. Is multiple levels of nesting not supported or is this a bug?

[link to plunker](https://plnkr.co/edit/5UY8QvpyjzS7dbuntNFs?p=preview)

Opening the groups 1 by 1 goes fine, as does closing them 1 by 1 in the right nesting order. But when all groups are open, and you try to close them all at once (closing group4) it seems to break. Some of the nested groups don't collaps and some suddenly appear at the top.

Also in the docs it says i should use "showNestedGroups" to determine if it should be shown when initiated but I only got this to work with "showNested" (as used in the example).

**Comment by bradh** [comment]
See https://github.com/almende/vis/issues/2846 and https://github.com/almende/vis/issues/1934
