### ISSUE TITLE
[network] getConnectedNodes(edgeId) doesn't return nodeId with 0 value

### ISSUE THREAD

**Issue by KarKarbI4** [almende/vis#2936]
Suppose we have a network containing a node with id equals 0.
Let edgeId be an id of connected to the node edge.
Executing network.getConnected(edgeId) returns list with 1 value instead of 2, consumes 0 nodeId.

Code example: 
http://jsbin.com/voyaludiwo/1/edit?html,js,console

Screenshots:
![image](https://cloud.githubusercontent.com/assets/7318912/24528827/0b549254-15b1-11e7-8433-05ecb2355da9.png)
![console](https://cloud.githubusercontent.com/assets/7318912/24529743/142fd21c-15b6-11e7-9c18-d9532993c233.png)

**Comment by wimrijnders** [comment]
Confirmed.

Thanks for taking the time to report this _and_ to make a PR to solve it. We're swamped as it is.
I would prefer to have a more canonical solution for this:

```
  getConnectedNodes(edgeId) {
    let nodeList = [];
    if (this.body.edges[edgeId] !== undefined) {
      let edge = this.body.edges[edgeId];
      if (edge.fromId !== undefined) {nodeList.push(edge.fromId);}
      if (edge.toId !== undefined)   {nodeList.push(edge.toId);}
    }
    return nodeList;
  }
```

Would you mind redoing the PR? Also, please merge to the `develop` branch this time.

Thanks, really.

**Comment by wimrijnders** [comment]
I've made the PR to fix this, so you're done here. Thanks for reporting the issue!
