### ISSUE TITLE
Updating group of existing items

### ISSUE THREAD

**Issue by rudfoss** [almende/vis#2939]
I'm trying to change the group of an existing item in the timeline. However when I do I get an error:
```
Uncaught TypeError: Cannot read property 'itemSet' of null
    at BoxItem.Item.setData (http://visjs.org/dist/vis.js:26603:18)
    at ItemSet._updateItem (http://visjs.org/dist/vis.js:23317:10)
    at ItemSet.<anonymous> (http://visjs.org/dist/vis.js:23066:14)
    at Array.forEach (native)
    at ItemSet._onUpdate (http://visjs.org/dist/vis.js:23050:9)
    at Object.update [as callback] (http://visjs.org/dist/vis.js:22265:12)
    at DataSet._trigger (http://visjs.org/dist/vis.js:8190:20)
    at DataSet.update (http://visjs.org/dist/vis.js:8286:12)
    at <anonymous>:1:7
```

Can I not just call:
`dataSet.update({id: [itemId], group: [groupId]});`
to update the group of an item? Assuming a group with this id exists of course?

I've reproduced the issue in the example here:
`http://visjs.org/examples/timeline/groups/groups.html`

using this code in the Chrome console:
`items.update({id: 0, group: 1});`

Note: Since the grouping of items are random each time, I checked beforehand that the group exists and that the item I updated was not in that group originally.

Am I missing something or is there no way to update the group of an item without removing and re-adding it?

**Comment by jgorene** [comment]
If I understood what you mean, several ways to do according to what you want to get ... (eg) using the options and onMove method with callback included
It's just an example that allows to see quickly what happens when one moves an item in another group
In options (items) add :
```
onMove: function(item, callback) {
    item.group = (groups.get(item.group)).id;
    console.log('newGroup : ', item.group);
    callback(item);
}
```
You can also use the onUpdate method on the same model as in [this example](http://visjs.org/examples/timeline/editing/editingItemsCallbacks.html) about using callback.
See also "Editing" item on doc

**Comment by rudfoss** [comment]
Not sure that's what I intend to. I don't want to make it editable or handle events from the timeline directly (unless that is the way to do it).

In essence I have an server call that happens regularly (setTimeout-ish) that wants to update the items in the timeline. Some are added, some are removed and some change groups. To do this I thought I could simply call `dataSet.update(item)` and as long as the id property matched the item would be updated. The problem occurs when I try to move an existing item between groups by calling in essence:
`dataSet.update({id: 1, group: 3})`
where the item with id = 1 previously had a group with id = 2

At this point vis fails with the above error which is what I tried to explain by pointing to the example and test code. I can already update all the other properties of an item by calling `dataSet.update` with the correct id and properites so why does it not work for existing group ids?

**Comment by jgorene** [comment]
@rudfoss, Yes indeed, it was not quite what you were looking for and I understand better now.
So, I also did some testing and it is clear that not really obvious as error message!
Strangely, by checking after one update, item was changed group despite the error displayed.
But vis.js is still too new for me and I learn a lot at the same time ;)
Ok sorry, probably a contributor here will be able to provide an answer ...

**Comment by jgorene** [comment]
Finally, I just tested with version 18.1 (I still had this version present on my test file) and it works like a charm after checking that the item id to modify and destination group id exist ;)
Take with "caution", but this seems to resemble a bug on version 19.1...

**Comment by rudfoss** [comment]
Thanks for checking it out! For now I'll just replace the item with a new one with updated group id. Good to know that I'm not completely crazy ;)

**Comment by jgorene** [comment]
Probably not ... or me too =)

**Comment by BTMorton** [comment]
Made a quick plunker to reproduce it https://plnkr.co/edit/ku4L9d?p=preview

Looks like it's caused by the changes in #2821 that remove the item from the group at the start of the item update, and add it back after updating which collides with a call to moveToGroup during the update itself. I'm working on a fix which removes the logic from the itemSet and does the group updating in the item itself.

**Comment by BTMorton** [comment]
Fixed version demo here: https://plnkr.co/edit/r0kEZJ?p=preview

PR incoming...
