### ISSUE TITLE
Timeline destroy method throws exception related to onMoving

### ISSUE THREAD

**Issue by mpilone** [almende/vis#294]
With 3.3.0 I'm seeing the following exception when trying to destroy a timeline using the destroy() operation:

```
Uncaught Error: option onMoving must be a function onMoving(item, callback) vis.min.js:28
(anonymous function) vis.min.js:28
s.setOptions vis.min.js:28
(anonymous function) vis.min.js:32
s.clear vis.min.js:32
s.destroy vis.min.js:32
```

A quick look at the code shows that line 9617 defines the default option for onMoving to be null while all the other default callbacks are defined as valid functions. I'm not sure if this is the exact cause, but it looks suspicious.

**Comment by mojoaxel** [comment]
@mpilone Is this still an issue? If not can you please close this. Thanks!

**Comment by mojoaxel** [comment]
I can not reproduce this anymore with v4.17.0
