### ISSUE TITLE
minor (probably trivial) issue in gephiParser.js

### ISSUE THREAD

**Issue by rretter** [almende/vis#2940]
Lines 48-52 are:
```
    node['title'] = gNode.title;
    node['x'] = gNode.x;
    node['y'] = gNode.y;
    node['label'] = gNode.label;
    node['title'] = gNode.attributes !== undefined ? gNode.attributes.title : undefined;
```
Note that the last line undoes the first one.  This is bad if the first line has meaning, or unimportant if the first line doesn't matter (but probably ought to be deleted just for neatness).

**Comment by wimrijnders** [comment]
I can see the issue, but I'm having difficulty resolving it:

* I can't run the `importingFromGephi` example; applying the googled solutions doesn't help me
* I can't find specifications on any `Gephi JSON` format

So I'm afraid I'm not much use here.
Having said that, I can confirm from earlier issue #1189 that the `gNode.attributes.title` path is valid. I'm in the dark about `gNode.title`.

I propose to use `gNode.title` as the fallback option in the second assignment:

```
    node['x'] = gNode.x;
    node['y'] = gNode.y;
    node['label'] = gNode.label;
    node['title'] = gNode.attributes !== undefined ? gNode.attributes.title : gNode.title;
```

If it doesn't exist, no harm done. Does this sound OK to you?

**Comment by rretter** [comment]
This sounds like a good approach.  Thanks!

**Comment by wimrijnders** [comment]
On closer inspection, this has already been fixed in the `develop` branch. The first assignment has been removed already. No need to make a PR for the change as above.

**Comment by wimrijnders** [comment]
Previous PR was faulty, redoing.
