### ISSUE TITLE
Network: Support to import graphml files

### ISSUE THREAD

**Issue by Paebbels** [almende/vis#2941]
The documentation states that network supports the import of dot (GraphVIZ) and GEXI (Gephi) files.
Is support for graphml (yFiles/yEd or NodeXL) planned?

**Comment by wimrijnders** [comment]
No, it is not planned. However, being an avid `yEd` user myself, I feel sympathetic to this request.

The only assurance I can give you, is that, as of now, `graphml` support is on my personal TODO-list.
