### ISSUE TITLE
Timeline about style, grid background ... a priori "vis-dateNumber" doesn't work...

### ISSUE THREAD

**Issue by jgorene** [almende/vis#2944]
A priori, the documentation is not updated on Styles about "Grid background" or maybe I also misunderstood something ;)
I am struggling with this since this morning to highlight a specific day of the month using
`.vis-time-axis .vis-grid.vis-date+"number" { ... }` but unsuccessfully ?!

I've looked a little bit on issues ... nothing seen about it or I've missed out ?
Finally by testing
 `.vis-time-axis .vis-grid.vis-day+"number" { ... }`... bingo, it works !!

Just for info, if this can help someone else...

**Comment by bradh** [comment]
This was reported in #2888 and fixed in #2911 - it is pending the next release.
