### ISSUE TITLE
How to recover 'from' node by selecting edge when to node is clustered.

### ISSUE THREAD

**Issue by jymy78** [almende/vis#2951]
Hi all

I need to recover from node selecting edge when to node is clustered.

Now i get something like that:  

clusterEdge:c673f3ce-b885-4968-818a-30aa4eaed01b

and i can't get node from to this clusteredEdge. I need it to delete clustered items by deleting the clustered node.

Any idea?

**Comment by Stexxen** [comment]
Is this want you want? 
![image](https://cloud.githubusercontent.com/assets/4494301/24781055/9ff07508-1b34-11e7-9978-522c4ab6863f.png)

from http://visjs.org/docs/network/#methodClustering

**Comment by jymy78** [comment]
I did it accessing clustered edge on vos y properties to get from node.

Thanks
