### ISSUE TITLE
Drag and Drop non vis item from outside onto the timeline

### ISSUE THREAD

**Issue by flom** [almende/vis#2954]
Hello,

I'm not sure if this is a bug or a feature request, but in version 4.18.1 I was able to implement drag&drop of items outside the timeline widget by doing the following:

`<div id="timeline" ondragover="event.preventDefault()" ondrop="onDrop(event)"></div>`

```javascript
function onDrop(evt) {
  var timelineProperties = timeline.getEventProperties(evt);

  // use timelineProperties.group and timelineProperties.time to create or not create new item based on server request
}
```

Updating to 4.19.1 the _onDrop(..)_ function is no longer called. A quick glance at the vis.js code showed that the handle drop function now stops the propagation of the drop event (https://github.com/almende/vis/blob/2b73540022a77c86e9b6aa115f1acafb06cd2c4f/lib/timeline/Core.js#L250).

The following two jsbins shows the difference:

4.19.1:
https://jsbin.com/cotazemegi/edit?html,js,console,output

4.18.1:
https://jsbin.com/yasayudeje/1/edit?html,js,console,output

Is it still possible to receive the group id and time slot of a dropped item without adding it to the timeline immediately or should this be a new feature request?

**Comment by yotamberk** [comment]
@flom Unfortunately not possible yet. It's a duplicate feature request of #2834. I'll close this issue and continue taking care of this request there. FYI, I'll be working on it this week and should solve this for the next version)

**Comment by jmoraltu** [comment]
Hi, Any news related to the non vis items drop event?

**Comment by flom** [comment]
With version 4.20.1 I was able to implement drag&drop from outside like this: 
https://plnkr.co/edit/iBQcQRpVoentzRVAyxf9?p=preview

Basically, the item that is being dragged needs to have a _content_ property and the timeline must be initialized with _editable=true_. After dropping the _onAdd_ event is fired.
