### ISSUE TITLE
Network selectNode Event Fires Before deselectEdge Event

### ISSUE THREAD

**Issue by aaronst** [almende/vis#2959]
Selecting a node while an edge is selected causes these two events to fire:

1. `selectNode`
2. `deselectEdge`

I would expect the `deselectEdge` event to fire first, otherwise this implies that for a brief moment both the edge and the node are selected.  This is also breaking some logic I have for displaying information about nodes and edges when selected, and hiding on deselect.

**Comment by wimrijnders** [comment]
After giving it some thought, I conclude that there is no harm done in changing the order of the event firing.

The new event order will become:

1. `deselectEdge`
2. `deselectNode`
3. `selectNode`
4. `selectEdge`
