### ISSUE TITLE
set item to invisible

### ISSUE THREAD

**Issue by wtjwtjwtj** [almende/vis#2965]
Is it possible to set an item to invisible in timeline?

**Comment by yotamberk** [comment]
yes. the item has a property of `visible: <boolean>`. Try setting it to false

**Comment by wtjwtjwtj** [comment]
thanks. I tried but it does not work.
Is this property for group only, not for item?

**Comment by jgorene** [comment]
@wtjwtjwtj Hello, one track is to play with className when to build an item (see the doc about this;)
Just a suggestion in this example : 
Create a class like below in your css file(eg)
```
.vis-item.invisible {
  display:none;
}
```
and on your code
```
var items = new vis.DataSet();
item.add({
id: "itemId",
className:"'invisible",
...
});
```

**Comment by wtjwtjwtj** [comment]
@jgorene Thanks very much.
But if I need to set the item visibility dynamically, e.g. only shown when the group is nested, can I implemented in my code?

**Comment by jgorene** [comment]
@wtjwtjwtj Ok;)
So just add some conditions depending on what you want using the className...
I think you will find this this by looking the examples on the site, really well done ... because the possibilities are multiple and varied

**Comment by wtjwtjwtj** [comment]
thanks for the reply.

**Comment by Voyz** [comment]
This may be a little more safe version of @jgorene 's code for setting className, in case it already contains something:

```
if(visible){
    if ((item.className.indexOf " invisible") === -1) {
        item.className += " invisible"
    }
} else {
    item.className = item.className.replace(" invisible", "")
}
```

**Comment by Voyz** [comment]
Also @yotamberk, as per [Documentation](http://visjs.org/docs/timeline/#items) , the `visible` flag is available only for groups, not for items, so you answer https://github.com/almende/vis/issues/2965#issuecomment-293380933 may be misleading.

**Comment by yotamberk** [comment]
@Voyz you're right! My mistake! (it should be a property... I'll try to push it to my todo list)

**Comment by Voyz** [comment]
great @yotamberk ! Would love to see this implemented, let me know once it gets out! Thanks :)
