### ISSUE TITLE
Multiline lines overlap with shapes

### ISSUE THREAD

**Issue by AlexDM0** [almende/vis#2968]
If you use the multiline example and change the database to "dot" the text overlays the node. This can be fixed by individual font offsets but its a dirty fix. The text should never overlap the node.

https://jsbin.com/qapudeguxe/edit?html,output

**Comment by ludost** [comment]
Pretty old code already, but can be fixed in ShapeBase.js, by taking the labelHeight into account for determining the y-value. 

See patch below:
[labelPlacementPatch.txt](https://github.com/almende/vis/files/928783/labelPlacementPatch.txt)

**Comment by AlexDM0** [comment]
Is this the same reason the database shape has wrong text positioning? It's at the top now, it used to be in the center?

**Comment by wimrijnders** [comment]
@ludost thanks for diff, works with minor modification. Will post a PR based on this.

**Comment by wimrijnders** [comment]
> Is this the same reason the database shape has wrong text positioning? It's at the top now, it used to be in the center?

@AlexDM0 No this is unrelated.

**Comment by wimrijnders** [comment]
Hereby merged already. Closing this issue.
