### ISSUE TITLE
timeline - maxHeight request

### ISSUE THREAD

**Issue by nigelhorne** [almende/vis#2969]
At the moment maxHeight only supports a number of pixels, it would be great if it were also to support a percentage, where that percentage is of the drawable area.

**Comment by yotamberk** [comment]
use `height: 100%`

**Comment by nigelhorne** [comment]
That doesn't help it makes it too tall.

**Comment by yotamberk** [comment]
Can u supply an illustration \ jsbin?

**Comment by nigelhorne** [comment]
Look at https://genealogy.nigelhorne.com/visjs.html

You can download that file and change it - hopefully that will help you to see what I'm seeing.

**Comment by jgorene** [comment]
@nigelhorne, just for suggestion... if this can help ;)
I often used this tip with some jquery (not just with the timeline vis.js, in fact)
```
// Define height depending the current window
var timelineHeight = Math.round( $(window).height() * 0.85 ) + 'px';
// in timeline options 
height: timelineHeight,
```

**Comment by jgorene** [comment]
Additional suggestion for options to get a better UX, it seems to me anyway and precisely in relation to your presentation. In any case ... a big work this timeline !
You can try this below...
```
// Configuration for the Timeline
var timelineHeight = Math.round($(window).height() * 0.85) + 'px';
var options = {
    zoomKey: 'ctrlKey',
    //zoomable: false, // no need with verticalScroll (normally;)
    //horizontalScroll: true,
    verticalScroll: true,
    //autoResize: true, // this is default
    min: '1500',
    max: '2017',
    height: timelineHeight
};
```

**Comment by nigelhorne** [comment]
Thanks for responding.  I guess I need a bit more because it fails to load now and I am seeing this error:

ReferenceError: $ is not defined

**Comment by jgorene** [comment]
Yes, because you also have to load the jquery library into your page so that it works ... as you do with the vis.js. Add url to the beginning of your code above vis.js
```
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script> // this must be added
<script src="https://cdnjs.cloudflare.com/ajax/libs/vis/4.19.1/vis.min.js"></script> // this already exits
```

**Comment by nigelhorne** [comment]
That works a treat.  Thanks!
