### ISSUE TITLE
Timeline - setting height to percentage removes display

### ISSUE THREAD

**Issue by nigelhorne** [almende/vis#2970]
This works:

` var options = { verticalScroll: 'true', zoomable: 'false', autoResize: true, maxHeight: '800px'};`

But if I do this:

` var options = { verticalScroll: 'true', zoomable: 'false', autoResize: true, maxHeight: '80%'};`

Nothing is displayed.

Also this documentation  	

> The height of the timeline in pixels or as a percentage.

is unclear, since it needs to say what it's a percentage of - the data? the viewable window? the screen?  the container?

**Comment by yotamberk** [comment]
duplicate of #2969
