### ISSUE TITLE
Timeline Tooltip maximum width

### ISSUE THREAD

**Issue by nigelhorne** [almende/vis#2971]
It would be nice if this were configurable.  I got it to work with this hack:

```
  <style type="text/css">
    div.vis-tooltip { font-size:10px; white-space: normal; width: 30em; word-wrap: break-word; }
  </style>
```

**Comment by yotamberk** [comment]
What's happening now?

**Comment by nigelhorne** [comment]
Take a look at https://genealogy.nigelhorne.com/visjs.html and "mouseover" any of the names there and you'll see.

**Comment by yotamberk** [comment]
`max-width: 200px` doesn't work?

**Comment by nigelhorne** [comment]
No, that limits the width of the white box, but not the text that goes in it.

**Comment by jgorene** [comment]
@nigelhorne, max-width works for me ... but I've passed some padding, to trying after all ;)

**Comment by nigelhorne** [comment]
Would you please cut and paste the exact code so that I can check we're doing the same thing?

**Comment by jgorene** [comment]
Yes, of course...
```
<style type="text/css">
  div.vis-tooltip {
      font-size: 10px;
      white-space: normal;
      width: 30em;
      max-width: 150px; // just for test, adapt to your needs
      word-wrap: break-word;
      padding: 5px;
  }
</style>
```

**Comment by nigelhorne** [comment]
That works, thanks!
