### ISSUE TITLE
Network: Connected edges still present when a node is deleted

### ISSUE THREAD

**Issue by Mingscript** [almende/vis#2976]
When I was using visNetwork found that delete a node and it will not be linked to the edges deleted. I can think of is to do a cycle to solve, but the loss of performance, I hope you can give me a way, thank you.

**Comment by Mingscript** [comment]
By the way, if you think this problem exists, I can write a way to solve the problem.

**Comment by Mingscript** [comment]
Add, the canvas on the edge is gone, but you get the entire canvas on the edges, you will find, in fact, still exist.

**Comment by wimrijnders** [comment]
Hi, I have trouble understanding this issue. Would you mind rephrasing?

**Comment by Mingscript** [comment]
when I deleted nodes by some operations, I found the edges connected with the nodes were not shown on the page. However, by using 'getedges', I found those edges, which were supposed to be deleted, could still be found in the network.
I came up with a solution to such problem. It is like: use 'for' loop to find the edges supposed to be deleted, then delete them.However, this solution may cause a slower running speed.
@wimrijnders

**Comment by wimrijnders** [comment]
Thanks for the clarification, will look into it.

**Comment by Mingscript** [comment]
thx  ,if you need, I can give you my solution by doing traversal.
@wimrijnders

**Comment by rasmusblockzero** [comment]
To me it doesn't seem obvious that they should be deleted. Aren't they always added separately, so the lifecycle control is in "the app", right?

It would involve some loop though I guess (I use this.network.getConnectedEdges(nodeIds[i]) ) - but that is probably similar to what otherwise would have to be done in the library I assume (?)

**Comment by Mingscript** [comment]
The problem is that after I try to delete certain 'node', the edges which are connected with the 'node' are not deleted.  I can still find these edges in the table which can display the information of edges. So my question is when trying to delete certain node, should the edges connected with the 'node' also be deleted?
@rasmusblockzero

**Comment by rasmusblockzero** [comment]
RIght, my personal opinion is that they shouldn't always-and-automatically be deleted.

I can add edges without nodes (why is a different matter but maybe that's the order my data works). So then I think that they should be living on when I delete the nodes too. But it would be convenient of course with a shortcut way to make it automatic.

(In my case edges with just one node appeared both initially and after delete and lead me to find a flaw in the data fetching )

**Comment by Mingscript** [comment]
Sorry for not replying in time. 
I get your idea. Then is it possible to add a Booleans Type variable to parameter list of delete function which indicates whether or not the edges will be deleted? of course this requires some modification to the deleting algorithm.
@rasmusblockzero

**Comment by rasmusblockzero** [comment]
I think a boolean is better then flat out changing to always do this - but I am a bit hesitant if this would make for a good API - delete will be done on the dataset ? and the dataset doesn't really know about nodes or edges.

The extra code to delete the edges are pretty slim, so I'm not sure I see the benefit from that perspective. 

something like edgeDataSet.remove(getConnectedEdges(Nodeid)), right?
I'm not sure if the performance is a big thing here but maybe an API that would delete from two datasets at the same time. Or bundle the updates somehow.

**Comment by Mingscript** [comment]
Yes, I agree with your opinion, is only relative to the current situation, I need to delete the edges.
@rasmusblockzero

**Comment by wimrijnders** [comment]
If we can agree that the request is application-specific, here is my suggestion:

```
function draw() {
  // Define the data with DataSets, initialize with own data
  var data = {
    nodes: new vis.DataSet(ownData.nodes),
    edges: new vis.DataSet(ownData.edges)
  }

  // Add event for deletion of node(s)
  data.nodes.on('remove', function(event, info) {
    var deleted_ids = info.items;

    // Find the edges which connect these nodes
    var edges = data.edges.getIds({
      filter: function(item) {
        return (deleted_ids.indexOf(item.to)   !== -1) ||
               (deleted_ids.indexOf(item.from) !== -1);
        }
      });

    // Remove the found edges
    data.edges.remove(edges);
  });

  // Continue as before
...
  network = new vis.Network(container, data, options);
...
}
```

**Comment by Mingscript** [comment]
Sorry to reply late, thank you for your way!
@wimrijnders

**Comment by wimrijnders** [comment]
@Mingscript My pleasure. If it suits your purposes, please close the issue.
