### ISSUE TITLE
Vis.js Timeline: Configuration Options -> Snap

### ISSUE THREAD

**Issue by sabotrev** [almende/vis#2977]
I have already looked through previous issues, but I was no able to find any clarification on this issue. I am currently running macOS Sierra in Safari on the latest version of vis.js timeline (https://cdnjs.cloudflare.com/ajax/libs/vis/4.19.1/vis.js).

I am using the snap configuration option to place each item to the minute:

```
snap: function (date, scale, step) {
    var minutes = 60 * 1000;
    return Math.round(date / minutes) * minutes;
  }
```
When the page is initially loaded all items in the DataSet are not correctly snapped to their corresponding minute. This also holds true when new items are added. Unfortunately, items are only snapped to the minute when clicked and dragged. All items in my DataSet are restricted to integer number minutes; therefore, they should sit flush within the grid. Again, I looked carefully through the documentation so I apologize if I missed something simple that could fix this.

JS Bin: https://output.jsbin.com/xuqozanayo

Thanks in advance!

**Comment by jgorene** [comment]
Hello, 
If I understood your request because it is still a fairly (nice;) advanced example !
I think you have to reset the current time to 0 (hh,mm,ss,ms) before adding your minutes ...
Indeed with vis.js ... time runs fast all the time, hoping that this piece of code can help you a bit ...
```
/* Creates a date and sets the minutes
 * @param {int} time
 */
function setMins(time) {
    var date = new Date();
    date.setHours(0);
    date.setMinutes(0);
    date.setSeconds(0);
    date.setMilliseconds(0);
    date.setMinutes(time);
    return date;
}
```
Note that I prefer to use moment.js, very handy to work with dates (this is also suggested in the doc)

**Comment by sabotrev** [comment]
Hey,
Thanks! That solves my problem exactly. I knew it had to be something on my end, and that makes perfect sense. I really appreciate your help! I will definitely be integrating moment.js into my project very soon.

Thanks again!
