### ISSUE TITLE
Network - add navigation menu

### ISSUE THREAD

**Issue by nigelhorne** [almende/vis#2979]
I love the navigation menu option of Timeline (http://visjs.org/examples/timeline/interaction/navigationMenu.html), but I can't get that code to work with Network.

**Comment by wimrijnders** [comment]
See the [network navigation example](http://visjs.org/examples/network/other/navigation.html).

**Comment by nigelhorne** [comment]
That's even better than the timeline navigation menu (perhaps they should be merged?).  I'll look into it, thanks so much - I must have missed it on the examples page because it's staring me in the face.

**Comment by wimrijnders** [comment]
:smile: If you're happy with the answer, please close this issue.

**Comment by nigelhorne** [comment]
Closed - with an aside of will this also work with the Timeline code?

**Comment by wimrijnders** [comment]
Nope. This is specific to `network`.

**Comment by wimrijnders** [comment]
With 'closing the issue', I mean press the 'Close and Comment' button below. I did it for you now, could you please use that in the future to close issues? Thanks
