### ISSUE TITLE
IE 10 hangs if item and axis margins are both set to 0

### ISSUE THREAD

**Issue by NickG123** [almende/vis#298]
When I test my code on IE 10, if the item and axis margins are both set to 0, it hangs forever.  It works fine on Firefox or Chrome.  Setting the margin to another value works fine.  I am running IE version 10.0.9200.17054.

Code:

``` html
<html>
<head>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/vis/3.2.0/vis.js"></script>
    <link href="http://cdnjs.cloudflare.com/ajax/libs/vis/3.2.0/vis.css" rel="stylesheet" type="text/css" />
</head>

<body onresize="/*timeline.checkResize();*/">
    <div id="mytimeline"></div>
    <script>
        var groups = new vis.DataSet([]);
        var items = new vis.DataSet([]);

        // specify options
        var options = {
            margin: {
                item: 0, // minimal margin between items
                axis: 0   // minimal margin between items and the axis
            }
        };

        // create a Timeline
        var container = document.getElementById('mytimeline');
        timeline = new vis.Timeline(container, null, options);
        timeline.setGroups(groups);
        timeline.setItems(items);
    </script>
</body>
</html>
```

**Comment by DivyashreeMS** [comment]
Hi 

I have a urgent requirement that in Vis.timeLine there bottom line displays the Date and Time, I just wanted to make that time clickable and to read the value in JS. 
Please reply if any one has already implemented that.

![vistimeline_onclickoftime](https://cloud.githubusercontent.com/assets/10521928/5741583/1520495c-9bda-11e4-9d3a-d88566c7ae38.jpg)
![vistimeline_onclickoftime](https://cloud.githubusercontent.com/assets/10521928/5741587/1cb5c372-9bda-11e4-93ad-f3bc99a3c515.jpg)


Thanks & Regards
Divya

**Comment by AlexDM0** [comment]
Hi Divya,

Why are you posting this in this topic? It looks like it has nothing to do with your question. Please make a seperate issue for this.

Regards,

Alex
