### ISSUE TITLE
Wishlist - add the Network navigation to Timeline

### ISSUE THREAD

**Issue by nigelhorne** [almende/vis#2982]
See https://github.com/almende/vis/issues/2979

The http://visjs.org/examples/network/other/navigation.html is great, can it be an option to Timeline?  I realize that there is http://visjs.org/examples/timeline/interaction/navigationMenu.html, but:

1. it's not as seamless
2. it's not as visually appealing
3. it doesn't support scroll up/down

**Comment by yotamberk** [comment]
This can be done with css. We've discussed this issue (I can;t find it right now) and decided this should be implemented by the users.

**Comment by nigelhorne** [comment]
I know very little CSS (in this respect I am a user not a developer) I am clueless on how to do this myself.  Is it documented somewhere?

**Comment by yotamberk** [comment]
Who's using this library? The developer of your app should know CSS to give you the desired look of the navigation control

**Comment by nigelhorne** [comment]
Is it documented somewhere?

**Comment by yotamberk** [comment]
It's basic css. take a look at how http://visjs.org/examples/timeline/interaction/navigationMenu.html is written and simly adjust the CSS to your needs

**Comment by nigelhorne** [comment]
But that doesn't address point 3.

**Comment by yotamberk** [comment]
You can use jquery.scroll/other scrolling libs to scroll vertically with `verticalScroll: true`

**Comment by nigelhorne** [comment]
Yes, but that's not the same, is it?  Does that display the buttons?  I'm sorry but I think you and I are talking about very different things.

**Comment by yotamberk** [comment]
So please supply a gif/illustration of what you mean and explain better what you're asking. It seems to me that what you are asking should be done by the developer of your app and not in the vis itself.

**Comment by nigelhorne** [comment]
I understand that, but without a link to the documentation I'm clueless where to start.

See https://genealogy.nigelhorne.com/visjs.html

**Comment by yotamberk** [comment]
There is no documentation to scrolling vertically. Currently there is no method to so. A feature request asking for this method would be a valid request
