### ISSUE TITLE
How to update color of edge for all given edge ids

### ISSUE THREAD

**Issue by pradeepacc** [almende/vis#2995]
Question 1: I have an array of edge ids for which I need to change the color. Instead of looping through each id and calling dataset.update method, is there a function available to pass in the array of edge ids and the property to set for all those ids? Doing forEach on the edges taking longer time to update the graph.

Question 2: In reference to the above is there an option to update color of all the nodes/edges in the graph without providing the ID by using something like asterisks *. Basically something like dataset.updateAll

**Comment by wimrijnders** [comment]
For question 1, `DataSet.update()` doesn't do exactly what you describe, but it gets close. It can accept an array of configuration objects, each of which updates a specific id.

My suggestion would be to do something like this:

```
// Assuming that data.edges is a DataSet.

function updateEdgesForIds(ids, config) {
  var arr = [];
  for (var n in ids) {
    var obj = {};
    Object.assign(obj, config);
    obj.id = ids[n];
    arr.push(obj);
  }

  data.edges.update(arr);
}

// Example call
updateEdgesForIds(['A', 'B'], {color: '#ee0000'});

```

For question 2, the answer is "no, there isn't". You could collect all id's and pass it to the example function above.

The other alternative I can think of, is to specify the edge colors in the global options for the edges module only, and update that. But I don't think that is what you want.

**Comment by pradeepacc** [comment]
This helps. Thank you.

**Comment by wimrijnders** [comment]
You're welcome. Please close the issue if the answer is satisfactory.
