### ISSUE TITLE
Bug in Week display

### ISSUE THREAD

**Issue by krazziekay** [almende/vis#3002]
By the help from issue #1837, I was able to show the week view in the minor label of the timeline. However, there is a bug when it come to Week 17. The timeline doesn't show week 17 and week 39 in the view.
![image](https://cloud.githubusercontent.com/assets/13076255/25228782/6eeb561c-25ed-11e7-9d83-a8065b7c3527.png)
![image](https://cloud.githubusercontent.com/assets/13076255/25228929/0060bc9a-25ee-11e7-881d-121cc0956a2b.png)

But when I move the timeline, these does show up but kind of messed up as in this pic:
![image](https://cloud.githubusercontent.com/assets/13076255/25228814/8924273e-25ed-11e7-8cca-279694a4d9d8.png)
![image](https://cloud.githubusercontent.com/assets/13076255/25228837/9fb6001c-25ed-11e7-819e-5bfcea965dfb.png)

Can this issue of week view be solved??

**Comment by nothor84** [comment]
Hi!
There are some Tickets already opened regarding the WeekStep, something I think is really mandatory in a Timeline (for Projects).
This is one #1715 and this other is more active #1405
