### ISSUE TITLE
Timeline Item not visible if  it's date range  exceeds  visible date range of timeline

### ISSUE THREAD

**Issue by NagdaParikshit** [almende/vis#3005]
I had set my timeline options as 
`{
    start: Date(2017, 4, 1),
    end: Date(2017, 5, 1)
}`

and i had a timeline item as
`[{
    content: "Content 1",
    start: Date(2017, 1, 1),
    end: Date(2017, 6, 1)
}, {
    content: "Content 2",
    start: Date(2017, 4, 1),
    end: Date(2017, 4, 12)
}]`

When i load my timeline the Content2 visible because it's in the time range of timeline option 

but if Content range exceed timeline visible range (Content2) it is not visible.

**Comment by bradh** [comment]
Can you create a jsbin that shows this problem?

**Comment by yotamberk** [comment]
@NagdaParikshit What's the status? We're waiting for a jsbin

**Comment by yotamberk** [comment]
Closed due to inactivity
