### ISSUE TITLE
Fortify Scan Issue: Cross-Site Scripting: DOM Vis.js file version 4.16.1

### ISSUE THREAD

**Issue by Gaurav-Nayak** [almende/vis#3006]
Hi,
I am using vis.js 4.16.1, on running the Fortify scan tool, i get the following error at:

**Vis.js file Line 15043**
The method _makeRange() in vis.js sends unvalidated data to a web browser on line 15043, which can result in the browser executing malicious code.

I also get the same error in vis-min.js. Is there any workaround / fix that can applied here. If no could this be taken care in the future versions of Vis.js

Thanks!!

**Comment by bradh** [comment]
Can you try with something more recent?

**Comment by yotamberk** [comment]
@Gaurav-Nayak we can't help without a jsbin. Please supply one so we can help.

**Comment by bradh** [comment]
@yotamberk This is a static analysis tool result, not from running code.

**Comment by yotamberk** [comment]
@Gaurav-Nayak  I'm not sure how to approach this problem. What does the Fortify suggest doing? What is the problematic code? (please copy the code and not only the line number)

**Comment by yotamberk** [comment]
@Gaurav-Nayak Can you please help out to understand how to fix this?

**Comment by yotamberk** [comment]
Closed due to inactivity
