### ISSUE TITLE
is it just me -- Timeline start date does not display right

### ISSUE THREAD

**Issue by charbl** [almende/vis#3007]
I am using the timeline (latest version) and I notice that the events are placed on the timeline but not on the date of the event.  All items are displayed just off the date to the left.  Even the samples provided seem to be off ... look at the the basic demo. The dates used for the items are set to a specific date (item 1 is set for the 20th but shows the dot on the 19th).  I have tried the demo page in IE 11 and Chrome and same result.

I have tried the item type of "box" and "point" and same result.

Just seems like there is a bug on calculating position?

**Comment by bradh** [comment]
Perhaps you are seeing some kind of timezone issue. Perhaps you can figure out how far it is off, post a screenshot at the level of hours, and say what your offset from UTC is.

**Comment by charbl** [comment]
Here are some screen shot from the basic demo ...
![image](https://cloud.githubusercontent.com/assets/22121000/25307155/bf5b09f6-2761-11e7-8331-84db0c6365a8.png)

Here is the source for the items:
var items = new vis.DataSet([
    {id: 1, content: 'item 1', start: '2014-04-20'},
    {id: 2, content: 'item 2', start: '2014-04-14'},
    {id: 3, content: 'item 3', start: '2014-04-18'},
    {id: 4, content: 'item 4', start: '2014-04-16', end: '2014-04-19'},
    {id: 5, content: 'item 5', start: '2014-04-25'},
    {id: 6, content: 'item 6', start: '2014-04-27', type: 'point'}
  ]);

See item one ... date is 2014-04-20 but on every computer/browser I look at it plots on TL on the 19th.  Its a date so why would timezone matter?

**Comment by bradh** [comment]
Please answer the questions.

As to why its timezone matters - its not a date (in common language terms), but rather `Date` - a Javascript class instance.

**Comment by GluedToTheScreen** [comment]
I thought it was caused by not declaring a type on the dataset... no.
Perhaps an issue with moment.js?

https://jsbin.com/relikehigi/edit?html,console,output

**Comment by charbl** [comment]
Try out the http://visjs.org/examples/timeline/basicUsage.html basic example on the timeline website.  It shows up wrong .... if it shows up right for you then post images.  There is nothing I am doing to the example.  I understand it a Javascript Date but we are not using time or displaying time ... I could understand it might throw off time/date if the timezone was wrong but the example just uses start: '2014-04-20' but on the example page item-1 has a dot on the 19th.  I would think that the date being 20th would more then likely display with dot on the 20th.  I built a timeline by just using dates for items and not messing with timezone and all the dates were off like the basic demo.  I thought it might be something I did but then i noticed that all the demos seem to be off as well.

**Comment by bradh** [comment]
Did you look at the timezone example? If you can't provide the information I asked for, I can't help you. Sorry.

**Comment by charbl** [comment]
Ok, I am going to try and answer your questions:
Screen shot from the basic demo to the hour zoom:
![image](https://cloud.githubusercontent.com/assets/22121000/25336981/7a88e154-28bf-11e7-9d94-79dd39736941.png)
using the default items for the page source:
var items = new vis.DataSet([
{id: 1, content: 'item 1', start: '2014-04-20'},
{id: 2, content: 'item 2', start: '2014-04-14'},
{id: 3, content: 'item 3', start: '2014-04-18'},
{id: 4, content: 'item 4', start: '2014-04-16', end: '2014-04-19'},
{id: 5, content: 'item 5', start: '2014-04-25'},
{id: 6, content: 'item 6', start: '2014-04-27', type: 'point'}
]);

I am in Central Time Zone (Alabama) UTC/GMT -5 hours

I see that https://jsbin.com/relikehigi/edit?html,console,output is also wrong when it displays the dot for the items.

I looked at the Timezone examples but I am trying to understand how all the examples are displaying wrong when they provide the date to display and they are wrong. I would expect that given a date of 2014-04-20 that the dot displayed would show up on the 20th and then i would need to look at timezone for the time element to factor into the position on the 20th.  but the date is wrong when displaying.  I would appreciate any help that would correct this ... If i need to set timezone then i will but the documentation states "By default, the Timeline displays time in local time" and given just the date "2014-04-20", I would think that the display would point to the 20th.

thank you

**Comment by bradh** [comment]
Does it help to realise that 2014-04-20T00:00:00Z is 2014-04-19T19:00:00-05:00 ? That is, when its just turned to the 20th at UTC, its 7pm where you are?
