### ISSUE TITLE
stabilize instantly - dynamic loading

### ISSUE THREAD

**Issue by dnsBlah** [almende/vis#3014]
Hi all,

I was wondering if it's possible to stabalize a network diagram with the following settings:
```
var network;
var nodes = new vis.DataSet();
var edges = new vis.DataSet();

var locationUrl = '/infra/reload/' + $('#curLocation').html();

var container = document.getElementById('mynetwork');
var data = {
    nodes: nodes,
    edges: edges
};
var options = {
    nodes: {
        size: 20,
        shape: 'image',
        scaling: {
            min: 50,
            max: 50,
            label: {
                min: 8,
                max: 10,
                maxVisible: 40
            }
        },
        font: {
            size: 10,
            face: 'Tahoma'
        }
    },
    edges: {
        width: 1,
        color: {
            color: 'rgba(0,100,102,0.3)',
            highlight: 'rgba(0,0,102,0.7)',
            hover: 'rgba(0,0,102,0.3)'
        },
        smooth: {
            type: 'continuous'
        }
    },
    physics: {
    minVelocity: 0.75,
    maxVelocity: 25,
    solver: "forceAtlas2Based",
    iterations: 100,
    timestep: 0.5,
    forceAtlas2Based: {
            springLength: 100,
            springConstant: 0.03
        }
  },
    interaction: {
        hover: true,
        hideEdgesOnDrag: false,
        zoomView: true,
        dragView: true,
        navigationButtons: true
    },
    layout: {
    }
};
```

I tried network.stabalize(); but it's not doing anything.

With 'bigger' networks it takes ages to stabalize, I don't mind if it's instantly stabalized...

Any advice?

**Comment by wimrijnders** [comment]
Would you mind making an example with data?

**Comment by wimrijnders** [comment]
> I tried network.stabalize(); but it's not doing anything.

Assuming you mean `stabilize`, the way to activate that is by adding following to the options:

```
physics: {
  enabled: true,
  stabilization: {
    iterations: 500     // YMMV; higher value takes longer but results in better layout
  }
},
```

Please try this to see if it satisfies your needs.

**Comment by dnsBlah** [comment]
Hi all,

I tried to create a fiddle with a sample of static data.: [https://jsfiddle.net/jhh1dvkt/8/](https://jsfiddle.net/jhh1dvkt/8/)

BUT it seems like it's stabalized by default already, directly at load!
The reason is, that I'm in the need to automatically load new data from a json file every minute.

I do this using a timer with:
```
...
loadJSON(locationUrl, redrawAll, function(err) {console.log('error')});
...

function loadJSON(path, success, error) {
    var xhr = new XMLHttpRequest();
    xhr.onreadystatechange = function () {
        if (xhr.readyState === 4)
            if (xhr.status === 200)
                success(JSON.parse(xhr.responseText));
            else
                error(xhr);
    };
    xhr.open('GET', path, true);
    xhr.send();
}

function redrawAll(gephiJSON) {
//    hidePopup();
    nodes.clear();
    edges.clear();

    nodes.add(gephiJSON.nodes);
    edges.add(gephiJSON.edges);

    network.fit();
}
```

So as the fiddle worked fine, I used the same data in my live project, and it stabalizes instantly.
Should I create a new ticket, or can we continue here, finding out why it's bouncing and stabalizing slowly when using the redrawAll function?

**Comment by wimrijnders** [comment]
OK, great, so the first hurdle has been taken.

With respect to dynamic loading, just use the current issue. I'll await the changes in the fiddle.

**Comment by dnsBlah** [comment]
Fiddle has been updated :)
https://jsfiddle.net/jhh1dvkt/20/

**Comment by wimrijnders** [comment]
So the easiest  way that I see to stabilize quickly, is to explicitly **reload the data**:

```
function redrawAll(gephiJSON) {
    nodes.clear();
    edges.clear();

//    nodes.add(gephiJSON.nodes);
//    edges.add(gephiJSON.edges);
   nodes.add([...]);
   edges.add([...]);
console.log('load?');
    network.setData(data);    // <== add this, will trigger stabilize
    network.fit();
}
```
*(Assuming stabilization is enabled in the options)*

It may be a tiny bit of a hack, but it's a one-liner. In the ideal world, a change in the DataSet's should be able to rerun stabilization.

**Comment by dnsBlah** [comment]
Hi Wim, my apologies, it's working fine, even without the stabilization in options.
It stabalizes instantly, with stabilization options it'll be wobly again like it was.

Main reason for this is.. I also have 'locations' which have like 200 hosts without a 'parent' and so there is ID 0 ( Monitor ) which gets all the edges. this location does not load, or it takes a real long time.

So I now do:
```
nodes.add([...]);
edges.add([...]);
if nodes.length <= 100 {
   network.setData(data);
}
```

And the smaller networks load like instantly without anoying long time of stabilization, and the stupid big ones... yeah too bad then they should provide better data ;-)

Thanks for your big help! It's a huge improvement (:

**Comment by wimrijnders** [comment]
:+1:  Happy it's working for you!

To round this off: 

No need to apologize. Leaving out the stabilization options means it uses the defaults:

```
      stabilization: {
        enabled: true,
        iterations: 1000,   // maximum number of iteration to stabilize
        updateInterval: 50,
        onlyDynamicEdges: false,
        fit: true
      },
```
and 'big' networks skip `improvedLayout` so they're handled differently.

> Thanks for your big help! It's a huge improvement (:

Sincerely, my pleasure. Have fun!
