### ISSUE TITLE
Network: convertDot doesn't respect \n newlines in dot input

### ISSUE THREAD

**Issue by erikvanzijst** [almende/vis#3015]
A label in a dot file that contains a newline (literal "\n") seems to get interpreted by `convertDot` as the 2-char string "\n", as opposed to the newline character. As a result, the node's label in the graph lack line breaks.

```javascript
vis.network.convertDot('dinetwork {1 [label="new\\nline"];}');
```

http://jsbin.com/wuyayovage/edit?html,output

Platform: Chrome 57.0.2987.133 on OSX 10.11.6

**Comment by wimrijnders** [comment]
Are you sure about the syntax? I'm not, I don't know exactly how the dot format works.

But if I remove a backslash, so that text is `dinetwork {1 [label="new\nline"];}`, I get a newline as expected.

**Comment by erikvanzijst** [comment]
The dot language defines the dyad sequence "\n" (not the single-byte newline control char) as follows:

> the escape sequences "\n", "\l" and "\r" divide the label into lines, centered, left-justified, and right-justified, respectively.

http://www.graphviz.org/content/attrs#kescString

We have an existing dot-based system we are now plugging into visjs for visualization that produces labels with newlines. A snapshot of one of such files shows the use of newline sequences:

```
digraph {
	3 [color="#0d2b7c", label="query:1230:add_q\n0.005283\n6.83%\n(0.0001)\n(0.13%)\n17×"];
	3 -> 7 [color="#0d2a7b", fontcolor="#0d2a7b", label="0.005128\n6.63%\n17×"];
	5 [color="#0d1976", label="urlresolvers:537:reverse\n0.00219\n2.83%\n(0.000193)\n(0.25%)\n29×"];
```

> But if I remove a backslash, so that text is dinetwork {1 [label="new\nline"];}, I get a newline as expected.

For sure. Doing that you insert an actual newline byte into the string. This works on javascript, but it's not valid Dot AFAICT, as the spec only allows actual newlines to be used as an aid for formatting long labels:

> As another aid for readability, dot allows double-quoted strings to span multiple physical lines using the standard C convention of a backslash immediately preceding a newline character2. In addition, double-quoted strings can be concatenated using a '+' operator. As HTML strings can contain newline characters, which are used solely for formatting, the language does not allow escaped newlines or concatenation operators to be used within them.

http://www.graphviz.org/content/dot-language

**Comment by wimrijnders** [comment]
Thanks for the extra info; I am unfamiliar with the dot-parser for `network`. But on scanning the code, I encounter:

```
  // TODO: more precise parsing of numbers/strings (and the port separator ':')
```
I think the parser is not fleshed out to the full dot-specification; this might take some time to fix. Perhaps you can help?

**Comment by wimrijnders** [comment]
I intend to make this issue into a unit test. To be absolutely sure, does this look as a decent representation to you?

Input:
```
dinetwork test_graph {1 [label="new\nline"];}
```
Output:
```
{
        "type": "dinetwork",
        "id": "test_graph",
        "nodes": [
          {
            "id": 1,
            "attr": {
              "label": "new\nline",         # And not "new\\nline"
              "shape": "circle"
            }
          }
        ],
        "edges": [],
        "subgraphs": []
}
```

It's the internal format which comes out of the dot-parser, so there really isn't anything to compare it with. But perhaps you can say if it 'smells' right.
