### ISSUE TITLE
Timeline Items TOP position to same lavel? 

### ISSUE THREAD

**Issue by dmitrirussu** [almende/vis#3028]
Can I have Items on timeline on same top positin? there is a time padding which you allow to have smae level, but I need to be near. Example: Item 1 start: 01 end 02; Item 2 start: 02 end: 03. I need to have them closely and not with padding on time or with incrised possion under ?
How I can do that? thanks

**Comment by bradh** [comment]
I'm not sure I understand what you are asking - perhaps a diagram would help. However maybe you are looking for the `margin.item.horizontal` property, see http://visjs.org/docs/timeline/#Configuration_Options
