### ISSUE TITLE
t.write("<script>document.F=Object</script>") in vis.min.js

### ISSUE THREAD

**Issue by stla** [almende/vis#3029]
Hello, 
 In order to make a standalone html, I copy-paste `vis.min.js` in the `head` of my html:
```
<script>
copy vis.min.js here
</script>
```
This worked with `vis 1.18.1` but this does not work with `vis 1.19.1`. I have found the cause. In `vis 1.19.1`, there is:
`t.write("<script>document.F=Object</script>")`
while in `vis 1.18.1` this part is:
`t.write(n+"script"+r+"document.F=Object"+n+"/script"+r)`

**Comment by bradh** [comment]
If you are copying and pasting, why not just change it to suit your needs?
