### ISSUE TITLE
Timeline: Mousedown and mouseup events

### ISSUE THREAD

**Issue by danny-larsen** [almende/vis#3032]
Is is possible to add in the mousedown and mouseup events again?

I can see that it was in this pull request: #2473 but was removed again.

We are trying to make it so that on mousedown we start a new event. The user then drags over some days and on mouseup we want to create an event for the selected days.

**Comment by yotamberk** [comment]
It's a very simple addition. Can you please submit a PR with this?

**Comment by danny-larsen** [comment]
I will give it a go :)

**Comment by danny-larsen** [comment]
I tried to make it work, but for some reason it does not capture the mousedown on the left mouse button. Any ideas?

Here is the code i tried in Timeline.js:
this.dom.root.onmousedown = function (event) {
        console.log('mousedown');
        me.emit('mouseDown', me.getEventProperties(event))
    };

**Comment by danny-larsen** [comment]
I made it work with this:
`if(window.PointerEvent) {
        this.dom.root.onpointerdown = function (event) {
            me.emit('mouseDown', me.getEventProperties(event))
        };

        this.dom.root.onpointerup = function (event) {
            me.emit('mouseUp', me.getEventProperties(event))
        };
    } else {
        this.dom.root.onmousedown = function (event) {
            me.emit('mouseDown', me.getEventProperties(event))
        };

        this.dom.root.onmouseup = function (event) {
            me.emit('mouseUp', me.getEventProperties(event))
        };
    }`

Does that look right?

**Comment by yotamberk** [comment]
Looks fine to me! Please submit the PR so I can test it out.
