### ISSUE TITLE
Timeline - Items of type 'background' do not align with start and end date

### ISSUE THREAD

**Issue by DavidHessling** [almende/vis#3034]
Hi,

we found that the vis.js timeline has a problem with the items of type "background". They don't align correctly with the start and end date. It seems that they are off by a few pixels which makes it look very odd to the user.

You can find this issue in one of your examples:

http://visjs.org/examples/timeline/items/expectedVsActualTimesItems.html

Here is also a screen shot (you have to look closely as the background color is light blue): 

![image](https://cloud.githubusercontent.com/assets/6764828/25697678/29416258-30bc-11e7-87f0-053268c9695b.png)

We will also have a look into it but I hope you guys can give us some advice.

Cheers and thanks for the good work,

David

**Comment by bradh** [comment]
I'm guessing your current timezone is one hour off from UTC. You need to make sure your timeline and events have the same reference.

**Comment by DavidHessling** [comment]
Hi Brad,

thanks for the quick answer. Indeed, we had a problem with the offset from UTC managed to correct the items' dates to local timezone but that was only part of the problem.

The div contrainer where the "visualization"-div was placed it, caused the vertical lines in the timeline to be off by a few pixels. Solved the mystery. Thanks a lot :+1:

**Comment by bradh** [comment]
Assuming nothing more needed on this.
