### ISSUE TITLE
Can't align group labels vertically and horizontally - vis timeline

### ISSUE THREAD

**Issue by AleSpero** [almende/vis#3042]
Hello. I can't seem to center the group labels. Right now they are [like this](http://visjs.org/examples/timeline/groups/groups.html), and i want to have them centered both horizontally and vertically.
I tried this:

    .vis-inner {
        height:50px;
    }

    .vis-label{
      height:50px;
      display: flex;
      align-items: center;
    }

But it's not working (i have set "height:50px" because i want the rows to have a fixed height). I think i'm missing somehing.

Thanks a lot!

Alessandro

**Comment by jgorene** [comment]
Hello,
To center horizontally, one simple solution with css (based on your example)
```
.vis-panel.vis-left {
    text-align: center;
}
```
To center vertically, more complicated (for me;)
depends on the number of items per group, options chosen, styling of items and even some things further....

**Comment by yotamberk** [comment]
add this: 
``` css 
.vis-label {    
    display: flex;
    justify-content: center;
    align-items: center;
}
```
