### ISSUE TITLE
On which port is the app listening?

### ISSUE THREAD

**Issue by daumann** [almende/vis#3043]
After running npm i && npm run watch-dev, I cannot find where I need to point my browser to...

I tried the default 8000, 8080, 4000, 3000 but no luck. Please add a log entry for that.

**Comment by bradh** [comment]
I'm not sure I understand the question. What application are you referring to?

**Comment by daumann** [comment]
https://github.com/almende/vis#build

**Comment by bradh** [comment]
I still don't understand what you are expecting.

Are you expecting the examples to be a service? If so, you've missed the point. Just open the relevant HTML file for each example in a browser (as a file, not a HTTP connection).

**Comment by daumann** [comment]
On your website you have a nice interface with explanations and example overviews
http://visjs.org/graph2d_examples.html
http://visjs.org/timeline_examples.html
http://visjs.org/graph3d_examples.html

I would have expected this to be in the repo and ready to be served locally.
Nearly all major libraries do that, may I suggest considering doing the same? Especially when you already have it somewhere (where is the code for the above pages?).

**Comment by bradh** [comment]
@daumann  I don't see the value. If you're testing something locally, you probably know what example you want. If you're looking for a range of possibilities, they are all there on the web anyway. You could send a PR if this is important to you.
