### ISSUE TITLE
Get label value of a node

### ISSUE THREAD

**Issue by pradeepacc** [almende/vis#3062]
How to get current label of a node? 

```
var nodes = new vis.DataSet([
        {id: 1, label: 'abc'},
        {id: 2, label: 'abcd'}
    ]);
var node = nodes.get(1);
var label = node.??????
```

I need reset the label of that node based on what it is currently set. For example if (label == 'abc') I want to update the label of that particular node to 'Hello'.

**Comment by wimrijnders** [comment]
Something like this:

```
if (nodes.get(1).label === 'abc') {
  nodes.update({id: 1, label: 'Hello'});
}
```

Hope this helps.
