### ISSUE TITLE
Timeline Doesn't Work With Dates Before Common Era

### ISSUE THREAD

**Issue by sarcanon** [almende/vis#307]
When I attempt to display a Timeline data set containing dates before the Common Era (i.e., B.C.), the results are incorrect and inconsistent, either not being displayed at all, or are displayed as though they were A.D. For example, a data set item with a start date of "-700-01-01" and end date of "-500-12-31" will either not appear, or after some zooming of and moving about of the timeline, may appear, but is rendered as though the dates were 700 and 500 A.D., not B.C.

Does Timeline not support pre-Common Era dates?

Apart from this one issue, this library suits all my needs quite nicely.

**Comment by mohsincynexis** [comment]
Hello Guys,

Can I go back 13.7 billion years ago?

**Comment by josdejong** [comment]
> Can I go back 13.7 billion years ago?

Just try it. I think it should work as long as you don't use ISODates but unix timestamps or Dates

**Comment by mohsincynexis** [comment]
how would i get the unix timestamp for 13.7 billion years?

**Comment by josdejong** [comment]
sorry I mean a timestamp in milliseconds. 

Just google for how timestamps and Dates work.

**Comment by mohsincynexis** [comment]
But its a very long number and vis is not going back after 2 lac 70 k

**Comment by imCaps** [comment]
Use negative integer. But do not forget about 32 and 64bit systems. 
http://unix.stackexchange.com/questions/25361/why-does-unix-store-timestamps-in-a-signed-integer

**Comment by mohsincynexis** [comment]
Can you simply let me know how would I use 13.7 billion BC in this format 
[
  {"id": 1, "content": "item 1<br>start", "start": "2014-01-23"},
]
 
I know for BC i have to use negative years of max 6 length .
My system is 64 bit windows 7. 

Now can any one of you simply let me know the figure to use in start value for plotting 13.7 billion years ago point on the timeline.

**Comment by AlexDM0** [comment]
Its impossible, can't go further than new Date(-8.64e15).

**Comment by imCaps** [comment]
One solution(in specific cases) is correct Timeline format. Instead of years or other time labels use custom time like 'Y billion'.

**Comment by mohsincynexis** [comment]
Can you explain more on this.

**Comment by AlexDM0** [comment]
The label changing is very tricky. If you want an interactive timeline you will get the fractions of the years which will not make sense. I'd suggest @mohsincynexis should experiment a bit. This would be easier when we port the dataaxis of graph2d over to the time axis and have custom labels. Just hide the time axis and insert a datetime label to your items.

**Comment by imCaps** [comment]
This is just one 'backdoor'. Not in all cases it can be used. For example, your timeline consists only "big timestamps". Like 17.3 billion BC, 25 AC, 123AC ... And you do not use "small timestamps"(seconds, minutes). You can bind minutes like a years and years like billion years.
```javascript
var options = {
    end: duration,
    start: 0,
    format: {
        majorLabels: {
            minutes: "mm years", // This is not correctly written
            years: "Y,m billion years" // And this
        }
    }
};
```

This is just idea sketch but I believe it is working solution.

**Comment by mohsincynexis** [comment]
We are using minutes but not seconds

**Comment by mohsincynexis** [comment]
It would be a great help for me if you would post the the complete working example here please.

**Comment by AlexDM0** [comment]
You've been provided with all required information. These issues are not here to do your work for you. If you encounter problems, create a JSBin and show us the issue.

**Comment by mohsincynexis** [comment]
how would it affect the date after changing the labels or do I have to make some calculations.
Like if a user enters date 2 80 000 BC Feb 25 12:30 then how would this be handled.

**Comment by AlexDM0** [comment]
It would crash and there's nothing we can do about it. Or you could just try it and see for yourself.

**Comment by mohsincynexis** [comment]
Hi Imcaps,

I have set the new labels but its appearing strange in the timeline like this -270007, biJun 10, -270007ion y4amr6

here is the format I am using

```
format: {
        minorLabels: {
          millisecond:'SSS',
          second:     's',
          minute:     'HH:mm',
          hour:       'HH:mm',
          weekday:    'ddd D',
          day:        'D',
          month:      'MMM',
          year:       'YYYY'
        },
        majorLabels: {
          millisecond:'HH:mm:ss',
          second:     'D MMMM HH:mm',
          minute:     'ddd D MMMM',
          hour:       'ddd D MMMM',
          weekday:    'MMMM YYYY',
          day:        'MMMM YYYY',
          month:      'YYYY',
          year:       'Y, billion years'
        }
      }
```

**Comment by ssabba** [comment]
very good
