### ISSUE TITLE
Add a click-to-scroll option similar to click-to-use but it should allow dragging all the time, only block the scrolling without activating it.

### ISSUE THREAD

**Issue by AlexDM0** [almende/vis#308]
Atleast for mouse events. So it would not intercept scroll calls when scrolling by but it would be ready to use when you click or touch or drag it.

**Comment by AlexDM0** [comment]
Added to the new website's feature request section. Will be launched soon!

**Comment by mojoaxel** [comment]
Reopening as Feature-Request issue (see #2114). 
Everybody: Please feel free to implement this!

**Comment by yotamberk** [comment]
Closing due to lack of interest. If someone needs this issue, please reopen
