### ISSUE TITLE
how to add a click event?

### ISSUE THREAD

**Issue by ts1404** [almende/vis#3086]
http://visjs.org/examples/network/events/renderEvents.html

I want to add a click event.

In this example, 

I want to add an event to the circle surrounding the ellipse.

**Comment by wimrijnders** [comment]
You mean the outer circle, right? This can't be done in the example, the outer circle is not known within `network`, it's just an artifact drawn in the `beforeDrawing` event.

But you can make the outer circle the node and draw the rest within it. That way, you have a defined node of which you can catch the click event. For example:

```
  // create an array with nodes
  var nodes = new vis.DataSet([
...
    {id: 2,
      shape: 'circle',
      color: {
        background: '#294475'
      },
      widthConstraint: 100,
      heightConstraint: 100
    },
...
  ]);
...
  network.on("afterDrawing", function (ctx) {
...
    var nodeId = 2;
    var nodePosition = network.getPositions([nodeId]);
    ctx.strokeStyle = '#294475';
    ctx.lineWidth = 4;
    ctx.fillStyle = '#A6D5F7';

    var width = 80;
    var height = 30;
    ctx.ellipse_vis(nodePosition[nodeId].x - width/2, nodePosition[nodeId].y - height/2, width, height);
    ctx.fill();
    ctx.stroke();

    ctx.circle(nodePosition[nodeId].x, nodePosition[nodeId].y,20);
    ctx.fill();
    ctx.stroke();
  });
```

*(Note: `ellipse_vis()` is introduced in `vis.js v4.20.0` - for earlier versions, use `ellipse()`)*

And now, you can define a click handler for the outer circle:

```
  network.on("click", function (params) {
    if (params.nodes[0] == 2) {
      console.log('click event on 2!');
    }
  });
```

HTH.

**Comment by ts1404** [comment]
Thank you for your reply.

I want to group one node into one circle.

You want to provide events to each circle as if there were events on each node.

Both nodes and circles require click events.
