### ISSUE TITLE
Cannot set property 'stackDirty' of null

### ISSUE THREAD

**Issue by gossi** [almende/vis#3089]
I was happy to see, that version 4.20 was out, which fixes the error #2939 I was just about to report. I updated and got another one. Stack Trace:

```
ember.debug.js:19822 TypeError: Cannot set property 'stackDirty' of null
    at RangeItem.Item.setData ()
    at ItemSet._updateItem ()
    at ItemSet.<anonymous> ()
    at Array.forEach (native)
    at ItemSet._onUpdate ()
    at Object.update [as callback] ()
    at DataSet._trigger ()
    at DataSet.update ()
    at Class.startChanged ()
    at Object.applyStr ()
```

So, I was looking into at the last mentioned lines `RangeItem.Item.setData()`. [The relevant code here](https://github.com/almende/vis/blob/master/lib/timeline/component/item/Item.js#L67):

```
Item.prototype.setData = function (data) {
    var groupChanged = data.group != undefined && this.data.group != data.group;
    if (groupChanged && this.parent != null) {
      this.parent.itemSet._moveToGroup(this, data.group);
    }
    this.parent.stackDirty = true;
    // ...
}
```

I am wondering two things here:
1) Is it save to rely on a given parent after `_moveToGroup()`
2) in `_moveToGroup()` resp. `Group.prototype.add()` already marks the group as `stackDirty = true` so it's bascially redundant?

**Comment by gossi** [comment]
I guess I just had invalid data which I wasn't aware of at first. Issue is solved.

**Comment by calebadams** [comment]
@gossi can you expand on how you resolved this issue? I'm experiencing the same error and I'm having trouble tracking it down. Could you explain more? It would be greatly appreciated!!

**Comment by gossi** [comment]
IIRC my items and/or groups were empty datasets or had some corruct data, because some was missing on the way from backend into vis.js. Dunno if that helps, but checking the integrity of your datasets may help here, I unfortunately have no further advice to this :/

**Comment by calebadams** [comment]
Thanks! I think I was able to figure out that calling update with a data set containing duplicate IDs will reproduce the error.
