### ISSUE TITLE
How to get parents from node in network?

### ISSUE THREAD

**Issue by sjorsvanheuveln** [almende/vis#3091]
I want to extract the parents from a node in a directed hierachical network graph. I couldn't find a method available in the documents. How to do this?

**Comment by wimrijnders** [comment]
There is no method on `network` itself to return these. You best option is to use `DataSet`s and query the data directly.

Assuming you use `DataSet`s, i.e. your data looks something like this:
```
var data = {
  nodes: new vis.DataSet(data_nodes),
  edges: new vis.DataSet(data_edges)
}
```

Then following gets the parent for a given node id:
```
function getParents(nodeId) {
  // Retrieve the from-id's for the given node id
  var result = data.edges.get({
    fields: ['from'],
    filter: function(item) {
      return item.to == nodeId;
    }
  });

  // Make the return value a simple array of id's
  var parentIds = result.map(function(item) {
    return item.from;
  });

  // Get the nodes with the found id's
  var parentNodes = data.nodes.get(parentIds); 
  return parentNodes;
}
```

HTH.

**Comment by sjorsvanheuveln** [comment]
Thanks Wim, this works excellently. Perhaps for larger networks this iterative approach might not be suitable for speed reasons. Perhaps it could be useful that nodes carry the parents and children as inherit variables.

**Comment by wimrijnders** [comment]
The thing is, the data is already present within `network`, but there currently is no way to get to it. There is the method `Network.getConnectedEdges()`, but it doesn't differentiate between parent and child relations. I'm actually seriously considering adding a parameter to it to allow differentiating from, to, and both type edges.

I think it's worth it; you're not the first to ask this question so there's a need. Also, using the network-internal method will be way more efficient than anything done on the outside.

**Comment by wimrijnders** [comment]
OK, I've added the option to the `network` API. It was a small fix which I think will lead to overall good.

Please close the issue if you're satisfied with the resolution.

**Comment by wimrijnders** [comment]
Closed the issue due to being released in `v.4.20.1`.
