### ISSUE TITLE
Network: Edges disappear when selected if nodes have large coordinates

### ISSUE THREAD

**Issue by Alex585488792** [almende/vis#3093]
http://jsfiddle.net/a4sj79dv/
In the example, when nodes or edges are selected, the edges disappear.
When deselected, zoomed out, or changing the coordinates to smaller values (e.g. removing all the 3s), the bug disappears.
I tested on Google Chrome and Internet Explorer, and the bug only appears on Chrome.

**Comment by wimrijnders** [comment]
OK, I can see it happening. The weirdest thing. Firefox also handles it perfectly fine. 

Will investigate further when I have a spare moment.

**Comment by wimrijnders** [comment]
If I take out the x/y coordinates for the nodes, all is well. Checking now why this is so.

**Comment by wimrijnders** [comment]
I can trace the drawing all the way down to the bare canvas routines. The code within `network` has no problem with this, so it can only be an issue within the Chrome implementation of canvas.

Google informs me of [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=121285), quote:

> There was an issue where a point on the interior of a path wasn't calculated with high enough precision when the path was small but the coords were large.

This pretty much sums up what we're seeing. Thing is, this issue report is 5 years old now. You would expect this to have been released already.

------

So, there's not much I can do about this; it's out of our league. The best advice I can given you, is not to use huge coordinate values. I hope this is of use.
