### ISSUE TITLE
Can we have a label instead of arrow/circle to the ends of edges?

### ISSUE THREAD

**Issue by ptanmay** [almende/vis#3101]
This is a request for enhancement to the edges in networks.
As of now, the ends of edges can only be arrows or circles. Can a feature be added that allows us to choose to put labels at the ends of edges instead of the shapes?

**Comment by wimrijnders** [comment]
I suppose that it's possible. However, it is not as trivial as just changing the arrow-head.

I have noted it for now but I won't be implementing it any time soon. You are more than welcome to try implementing it yourself.

**Comment by wimrijnders** [comment]
Duplicate #2104

**Comment by wimrijnders** [comment]
Closed due to duplicate.
