### ISSUE TITLE
Timeline - 4.20.0 - range items seem to be shifted back in time by almost a month

### ISSUE THREAD

**Issue by madebydavid** [almende/vis#3105]
We noticed an issue with version 4.20.0 of the Timeline where range items seem to be shifted back in time by almost a month.

I have put together a jsfiddle for 4.20.0 here: https://jsfiddle.net/2oxhxurw/1/ You should be able to see a timeline like this:

![visjs-4 20 0](https://cloud.githubusercontent.com/assets/5401249/26471997/1b607fa2-419c-11e7-803b-f2acd81a29da.png)

Here is a fork of the jsfiddle but using 4.19.1: https://jsfiddle.net/cob05xde/1/ You should be able to see a different timeline like this:

![visjs-4 19 1](https://cloud.githubusercontent.com/assets/5401249/26472000/1e0d1b7a-419c-11e7-8f2e-94a6958022f4.png)

Both examples are using the same config and data, just a different version of visjs.

Interestingly, on 4.20.0, if we set the `timeAxis` to `{ scale: 'day', step: 1 }` then we don't see the issue - https://jsfiddle.net/jr2tp5be/2/

Is there a difference in how we need to supply the data for the newer version?

I am testing with Chrome 58.0.3029.110 (64-bit) on Ubuntu

**Comment by bradh** [comment]
Weird! Also happens on Firefox on Windows. 
Looks like it shows up correctly if you scale in a bit, then goes bad again as you scale out. I don't think its the data presentation (because that would show up always, not just at a particular scale).

**Comment by jonathanchrisp** [comment]
Hey All, Just to note this has also been raised on our `react-visjs-timeline` repo. The issue can be found here: https://github.com/Lighthouse-io/react-visjs-timeline/issues/18.
