### ISSUE TITLE
It is not possible to create multi level groups on timline

### ISSUE THREAD

**Issue by nagermen** [almende/vis#3109]
I've tried to implement multi level nested groups but seems vis.js is not supporting that feature

will be really nice to have multi level subgroups, I'm ready to help on this issue.
attaching fidle
https://jsfiddle.net/naka/j9kd2nfx/

**Comment by bradh** [comment]
This is an existing feature request (#1934, with #2846 as a simpler version).

A pull request to implement this would be appreciated. I'd suggest trying to catch @yotamberk on the gitter channel if you need to discuss - he did the original nesting work.
