### ISSUE TITLE
Timeline 4.20.0 - setGroups + setWindow not working

### ISSUE THREAD

**Issue by alexandrasava** [almende/vis#3114]
Hi guys,

I'm using timeline 4.20.0. I noticed that if I have a timeline with groups and items set, when I want to change the window (setWindow), the window doesn't change. If I remove 'setGroups',  setWindow works as expected. Please comment "timeline.setGroups(groups)" line to see that the window changes.

Code: http://jsbin.com/gopifuxeqa/1/edit?html,output

Thanks,
Alexandra

**Comment by yotamberk** [comment]
A simple solution is to either `setTimeout` (extremely hackish), or simply set the timeline options to 
``` javascript
options = {
  start: new Date('2017-05-23'), 
  end: new Date('2017-05-31')
}
```
which is the proper way to do it
