### ISSUE TITLE
how calc group heights in timeline?

### ISSUE THREAD

**Issue by GluedToTheScreen** [almende/vis#312]
I'm working on an application that blends several open-source tools like vis (WHICH IS GREAT!), but have run into an issue with timeline groups changing heights when I switch back and forth.  

If you go here, you'll see podcast episodes for a default show on a timeline, scaled to days/months:

http://podDVR.com

When you click the Play button, the timeline will switch modes (notice highlighted button).  It will now display a timeline for a specific podcast (audio clip), scaled to hours/minutes/seconds and restricted to the duration of that podcast episode.

Note the height of the groups.  It looks pretty good the FIRST TIME, even in different browsers.

If you click back to the timeline showing all podcasts in the series... and then go back to the single podcast timeline, the group heights will change.  And the heights are different in different browsers.

Again, I don't know if it's my code or vis... I've tried redraw() and tinkered with styling, but cannot find the source of the issue.

It does appear that VIS calculates that height since CSS is overridden in Firebug.  How does it go about doing that? Or maybe you can give me a keyword/line# in the source and I can look at it?  If I understand how that happens, maybe I can pinpoint where I am probably stepping on myself.  It's happened before.

Thank you very much for the excellent work on this toolset.  I hope to have a little more time to contribute here in the future as I get near deployment of the site.

**Comment by josdejong** [comment]
Is this still an issue?
