### ISSUE TITLE
Vis.Timeline problem on react js

### ISSUE THREAD

**Issue by dmitrirussu** [almende/vis#3125]
Hi, I have a problem including into react js App Timeline library. I get message "Error: Mismatched anonymous define() module", I do next from define([], factory); to define('vis', factory); but that does not solve all problems, I still have problem of anonym define. that problem appear after I do grunt build.

How I can solve the problem to have it. on live that problem does not appear only after I use grunt to build app I get errors of define module and also get error like "this is undefined"

**Comment by yotamberk** [comment]
Can you supply a jsbin? it doesn't sound like a vis problem

**Comment by yotamberk** [comment]
Closed do to inactivity
