### ISSUE TITLE
Timeline nested groups work incorrect if set them after timeline init

### ISSUE THREAD

**Issue by ildarnm** [almende/vis#3126]
I take an example from http://visjs.org/examples/timeline/groups/nestedGroups.html and initialize the timeline before creating groups and elements
Http://jsfiddle.net/ildarnm/dkfo75f9/

**Comment by yociduo** [comment]
If you not set groupOrder, the order will reference id.
I have change your id, it work.

[
    {
      id: 1,
      content: "Lee",
      nestedGroups: [11,12,13]
    },
    {
      id: 20,
      content: "invisible group",
      visible: false
    },
    {
      id: 30,
      content: "John",
      nestedGroups: [34],
      showNested: false
    },
    {
      id: 40,
      content: "Alson"
    },
    {
      id: 11,
      content: "cook",
    },
    {
      id: 12,
      content: "shop",
    },
    {
      id: 13,
      content: "clean house",
    },
    {
      id: 34,
      content: "wash dishes",
    }
  ]

**Comment by marcortw** [comment]
I just ran into this problem as well. Looking very much forward for a quick fix!

**Comment by bradh** [comment]
@marcortw While we try to fix everything, please understand its volunteer time, and there are a lot of things to address. So it will be dealt with when we are able.

**Comment by marcortw** [comment]
@bradh Of course, I appreciate the efforts!
