### ISSUE TITLE
Hourly Item

### ISSUE THREAD

**Issue by prasetyaputraa** [almende/vis#3127]
How to create a dataset that start and ends within the same day but different hour?

**Comment by bradh** [comment]
Just use a proper ISODate format, which you should be doing anyway, for maximum browser compatibility.

**Comment by bradh** [comment]
@prasetyaputraa Did this resolve your problem? Will mark it as inactive, and close if we don't hear back from you.

**Comment by yotamberk** [comment]
Closed due to inactivity
