### ISSUE TITLE
Network: Use clustering with hierarchical layouts

### ISSUE THREAD

**Issue by wimrijnders** [almende/vis#3129]
This issue investigate the possibility to use clustering with hierarchical networks.

Possible duplicate of #1105; which is currently also actively under investigation.

-----

For reference, a `hierarchical network` will be defined as a network in which *all nodes have at most one parent*.

Hierarchical networks can be efficiently placed and have their branches placed in a non-overlapping manner.

Hierarchical layouts can be used for non-hierarchical networks, but with the limitation that the algorithm for eliminating overlap can not be used. This is what caused the 'exploding network' issue; the gist of #3017 is that the overlap detection algorithm is disabled for non-hierarchical networks.

**Comment by mmcnl** [comment]
@wimrijnders Yes, thank you very much! As you mentioned earlier that clustering can work with hierarchical  layouts with certain constraints, one thought would be to add an example of that to this page: http://visjs.org/examples/network/other/clustering.html

**Comment by wimrijnders** [comment]
This is the communication initiating the current issue, relocated from #1185.

TODO
------

**Comment by wimrijnders** [comment]
@mmcnl OK great, you're here!

As a first step, enable hierarchical layout in said example `network/other/clustering`. I'm hereby assuming that you have access to the repo code (if that is not the case, I'll open a `jsfiddle`).

I hereby also assume you are using latest stable version `4.20.0` of `vis.js`.

Change the options of the example to the following:

```
var options = {
  layout:{
    randomSeed:8,
    hierarchical: {
      enabled: true
    }
  }
};
```

... and see what happens.

What I see, is that the clustering works, but the network moves nervously when a cluster is opened. Also, branches appear to swap sometimes.

-----

What I'd like to know from you now, is:

- Is this a reasonable starting point for your situation?
- What is your use case? What criterium do you use for clustering nodes?
- Is your network pure hierarchical, as defined above?

**Comment by wimrijnders** [comment]
@mmcnl In all honesty, I will report that #1105 was indeed due to a bug, which I have hereby fixed.

If this affects your particular use case, depends on what it entails. Looking forward to hearing from you.

**Comment by mmcnl** [comment]
@wimrijnders Thanks so much for all of the work on this. I've had to switch to another project for a bit but will report back later if I have a chance to implement the clustering as suggested above. I'm not sure however if my ideal use case (being able to click on a hierarchical node and have it automagically collapse/cluster/hide all descendent nodes/edges) would be supported without changing my data structures a bit.

**Comment by wimrijnders** [comment]
@mmcnl I've made a [jsbin](http://jsbin.com/kizepogaxu/edit?html,output) for clustering with hierarchical networks. When you get back to this project, have a look at it to see if it suits your needs.

**Disclaimer:** There is plenty of stuff still wrong in the demo, I did the minimum amount of work to get it working. The intention is to see if you agree with the basic funtionality; after that we can make it right.

**Comment by mmcnl** [comment]
@wimrijnders Thank you! Yes, that's the basic functionality I was looking for in terms of clustering/unclustering. However it appears the project has somewhat complicated logic for determining which parts of the tree to hide/unhide that will require server-side processing. So for now I am just re-rendering the entire tree rather than using client-side clustering.

**Comment by wimrijnders** [comment]
OK, so current issue is moot? Oh well....

In that case, please close the issue and godspeed with the project!

**Comment by mmcnl** [comment]
Yes, for now, I think it's moot. Thanks so much for the awesome support, it's really appreciated.

**Comment by wimrijnders** [comment]
OK to close it then?

**Comment by mmcnl** [comment]
yes, closing seems appropriate, thank you.

**Comment by wimrijnders** [comment]
OK, see you around!
