### ISSUE TITLE
project using vis.js network

### ISSUE THREAD

**Issue by robtex** [almende/vis#3134]
Hello.
Just wanted to know we just started to use vis.js to make DNS graphs on https://www.robtex.com/ . 
I like how it is such an awesome and clean library.

Example:
https://www.robtex.com/dns-lookup/example.com

Work in progress. When we are done we will replace all our old graphs.

Feel free to add us to http://visjs.org/showcase/index.html

Best regards, and keep developing!

**Comment by wimrijnders** [comment]
That's a nice practical use for graphs!

It looks a bit small though:

![untitled](https://cloud.githubusercontent.com/assets/769037/26818072/9bc7988c-4a99-11e7-82d8-3ac7fcec4523.png)

This is on my highest res screen (truth to tell, it's doable). But it's even smaller on my other monitors.

**Comment by robtex** [comment]
Yes, you are correct, it looks too tiny.
The height is currently fixed. I'm planning on making it resizeable in some way. Or simply make it larger, possibly depending on number of nodes actually shown, because it varies a lot.
What I struggle with mostly right now is trying to group the information in a nice way, so the nameservers are together and the mailservers are closer together. I think i'll either try adding an intermediate node or putting hidden edges between them.
visjs is also added in the chrome-plugin btw, where you can also click on the nodes to navigate.
thanks for your feedback

**Comment by wimrijnders** [comment]
My pleasure! I wish you all the best with this project. The site is hereby pipelined to be added to the showcase, thanks for that.

**Comment by robtex** [comment]
Thank you too.
FYI I've added a "toggle zoom" function now that makes it use the entire browser window.

**Comment by wimrijnders** [comment]
@robtex 'toggle zoom': oh yes, nice. That actually looks lovely.

**Comment by amorigoye** [comment]
Hi everyone here I am working on graph or network visualization using visjs. Please if there's anyone who can be of any help to me would be appreciated. I started with node.js but I got stuck but if there's anyone who can guide me how to do it in node.js or any other environment would  be appreciated. Thank you
