### ISSUE TITLE
Using external iconfonts

### ISSUE THREAD

**Issue by gubr123** [almende/vis#3136]
Hi,

I am working with the angular version of vis js.

I created a network, with fontAwesome iconfonts, and it works great.

I want to be able to use custom iconfonts that I created. 

I read somewhere I can do that, so can you please explain how?

Thanks in advance.

**Comment by wimrijnders** [comment]
The canonical example is `network/nodeStyles/icons`.
Just about the smallest example I can derive from that is:

```
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Icons</title>

  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vis/4.20.0/vis.js"></script>
  <link type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/vis/4.20.0/vis-network.css"></script>

  <!-- !! -->
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.css">

  <style>
    #mynetwork {
      height: 400px;
      width: 400px;
      border:1px solid lightgrey;
    }
  </style>

  <script language="javascript">
    function draw() {
      var node = {
        id: 1,
        label: 'label',
        shape: 'icon',          // !!
        icon: {                 // !!
          face: 'FontAwesome',  // !!
          code: '\uf1ad'        // !!
        }                       // !!
      };

      // create a network
      var container = document.getElementById('mynetwork');
      var data = {
        nodes: [node],
        edges: []
      };

      var networkFA = new vis.Network(container, data, {});
    }
  </script>
</head>
<body onload="draw()">
  <div id="mynetwork"></div>
</body>
</html>
```

The lines important for icon usage are marked with double exclamation marks.
This is what you need to do for using fonts in a network. Of course, you will need to define a `css` to make the font available. I suggest following the link to `font-awesome.css` above and see how they do it there. Notably, the definition of `@font-face` at the top is important.

HTH.

**Comment by gubr123** [comment]
Thanks @wimrijnders, but as you noticed, I already used fontAwsome, so the question is, how do I use other icon font rather than fontawesome and ionicons.

Thanks again

**Comment by wimrijnders** [comment]
@gubr123 My answer, as copied from above:

> What I wrote above is my complete knowledge of that subject.

Sorry, I personally can't help you with this. I hope someone else with more knowledge reads your question.

I'd like to point out that your question is not specific to `vis.js`; for this reason I'm putting the `Invalid` tag on. We aim to do bug reports, feature request and questions on usage of this package. How to create a web font does not fit into these categories. I hope you have understanding of this.

**Comment by wimrijnders** [comment]
Perhaps you mean, how to use another iconset within the code? This is exactly the reason I put in the **!!** comment in the example above. Those are the lines you need to change for another iconset. What the values here should be, depends entirely on the iconset you use. I can't help you there.

**Comment by wimrijnders** [comment]
Closed due to `Invalid`.
