### ISSUE TITLE
Network: Style edges as group instead of individual

### ISSUE THREAD

**Issue by ido-ran** [almende/vis#3138]
This is a feature request: I've started to use vis for visualizing network.

The network has nodes of 3 types and edges of 3 types.
On the node side, there are `groups` to help style the nodes according to which group they belong to.

I think it will be helpful if a similar functionality would exist for the edges, that way I could specify which group each edge belongs to and style each group once.

In my use-case, I need to change the style dynamically and without this feature, it means iterating over all the edges I need to change style for and change them one by one.

**Comment by wimrijnders** [comment]
I think the idea has merit. I'll pick it up in due time - or hopefully, someone else will. Just don't expect any short-term resolution.

**Comment by wimrijnders** [comment]
Duplicate of #211.

**Comment by ido-ran** [comment]
thank you for noting the duplication, closing in favor of it.
