### ISSUE TITLE
Vis Network & Webpack - Where & How to Integrate CSS?

### ISSUE THREAD

**Issue by FilipQL** [almende/vis#3139]
I was able to successfully integrate Vis Network directly in my Webpack build by following the documentation example:

**entry (main.js)**:
```
let vis = require('vis/index-network');
```
**webpack.config.js**:
```
            . . .
            {
                test: /node_modules[\\\/]vis[\\\/].*\.js$/,
                loader: 'babel-loader',
                query: {
                    cacheDirectory: true,
                    presets: ["es2015"],
                    plugins: [
                        "transform-es3-property-literals",
                        "transform-es3-member-expression-literals",
                        "transform-runtime"
                    ]
                }
            },
           . . .
```
Everything works fine except the CSS, it is not loaded, images (icons) that are used for the **navigationButtons** and **manipulation** are not integrated into the Webpack build. I have enabled _navigation_ buttons and _manipulation_:
```
. . .
let options = {
    interaction: {
        hover: true,
        navigationButtons: true
    },

    manipulation: {
        enabled: true,
        initiallyActive: true,

        addNode(nodeData, callback) {
            . . .
        },

        editNode(nodeData, callback) {
            . . .
        },

        deleteNode(deleteData, callback) {
            . . .
        }
    },
    . . .
```
![vis](https://user-images.githubusercontent.com/18264428/26855523-b8ebbf24-4b1b-11e7-9b3b-59dfc5c21a60.png)
There are no errors in the browser console, but _navigation buttons_ and _manipulation menu_ are not displayed. I've tried to solve this by requiring _node_models/vis/dist/vis-network.min.css_ in my entry (**main.js**):
```
let vis = require('vis/index-network');
require('vis/dist/vis-network.min.css');
```
and now manipulation menu is shown:

![vis webpack](https://user-images.githubusercontent.com/18264428/26855712-ddf0e3b6-4b1c-11e7-9d58-d55ec8799931.png)

... but images (buttons) are not loaded properly (the problem is with relative paths in CSS???). Is this the right way to integrate CSS? 
```
let vis = require('vis/index-network');
require('vis/dist/vis-network.min.css');
```
Or maybe there is a better way to do it... How would you integrate CSS (of Vis Network) into your Webpack build?

**Comment by wimrijnders** [comment]
I'll admit up front that this webpack thing is all new to me, so really I can't just blurt out the 'obvious' answer. I can see where this comes from; it's the example from the README.md.

Just by eyeballing it, I'd say [this page](https://webpack.github.io/docs/stylesheets.html) looks like a hopeful solution. If you try this, please comment on the results here. If they're good, some  text explaining the process should be added to the readme.

**Comment by FilipQL** [comment]
Setting  publicPath solved the problem.

> In order for assets to maintain correct paths setting output.publicPath property of webpack configuration must be set, so that absolute paths are generated.

https://github.com/webpack-contrib/style-loader

**Comment by Kurren123** [comment]
Hi @FilipQL . Do you happen to have a minimal project that has webpack working with `vis.js` and `vis.css`? It would be greatly appreciated.

**Comment by wimrijnders** [comment]
@Kurren123 Would the unit tests of `vis.js` count as a project example? Look at the tests in the `develop` branch.

**Comment by mojoaxel** [comment]
I created an webpack demo-project for vis. see #2186
