### ISSUE TITLE
Vis + Vue, when addNode all nodes are affected by the last added node

### ISSUE THREAD

**Issue by DanielWLam** [almende/vis#3142]
When I add a node, I expect it's label should be unique, however, when working with vue and Vis(version >= 4.19.1), all the nodes's label would be changed to the last added node's label. Here is an example:
https://jsfiddle.net/348d58jc/1/
It's weired.
But when I search the old issue, I find out this jifiddle didn't have such problem... As you can see, all the node has its own label: 
https://jsfiddle.net/8u84ud3s/

**Comment by wimrijnders** [comment]
I'm sorry, I don't see this happening in the first `jsfiddle`, it appears to be working as expected.

Exactly what should I do in the example to get the behavior you report? Perhaps I have to do something special.

**Comment by DanielWLam** [comment]
Well, please try the ADD NODE button more than twice, could you see those added node's label become the same? As expected, each node's label should be a random number

**Comment by wimrijnders** [comment]
Aaah, ok. It's the labels of the *new* nodes that show this behavior. Thanks for the explanation.

**Comment by DanielWLam** [comment]
How can I resolve this problem?  Turns out that v4.17.0 dosen't have this problem @wimrijnders

**Comment by wimrijnders** [comment]
@DanielWLam To answer that, I'll have to investigate how it happens. I ask for your patience, this is one of many things I need to do.

**Comment by DanielWLam** [comment]
@wimrijnders umm.. maybe these two issues are caused by the same problem, though they are not exactly the same. I solved it with the solution mentioned in #2567 . However, I hope it could be fixed as soon as possible.

**Comment by wimrijnders** [comment]
@DanielWLam I've found the root problem for this; please see the discussion in #2567 for explanation.

**Comment by wimrijnders** [comment]
Related to #2567. Still investigating if it's a duplicate.

**Comment by DanielWLam** [comment]
Thank you very much! @wimrijnders
