### ISSUE TITLE
stabilized event with non-empty queues

### ISSUE THREAD

**Issue by robtex** [almende/vis#3147]
I'm not sure if this is a bug or just a facepalm observation.
I discovered than network fired a stabilized event *before* graph was actually stabilized.
The reason was that for some reason i thought adding {'queue': {'delay': 100}} to the datasets was a good idea when adding stuff dynamically.
I probably don't need that though.
*Maybe* it shouldn't fire a stabilized event until the queues are empty?

**Comment by wimrijnders** [comment]
OK interesting one. I'll need to look a bit deeper into this. Queue usage on `DataSet` is new to me, in the sense that I never had to look at the code till now.

**Comment by robtex** [comment]
Ok full disclosure:
The reason i added a queue was that I have something like
for(x in newnodes) {nodes.add(x);}
for(x in newedges) {edges.add(x);}
And I wanted to make sure I didn't waste cpu on each add until all new nodes and edges had been added. So i assumed a queue would make sure I wouldn't waste cpu.
I probably deeply offended you by assuming that. My apologies for that. I haven't looked at the code at all yet.

**Comment by wimrijnders** [comment]
> I probably deeply offended you by assuming that. My apologies for that.

:confused: And I thought I was the humble one.....
I think it's a perfectly valid question + reasoning. There's absolutely no need to apologize.

I'll have a look when I get the chance; but by all means have a look yourself!

**Comment by robtex** [comment]
Of course you are more humble than I am. My bad. I apologize yet again. :)
I'll have a look at it too. I've only downloaded the minified version, and liked what i saw.
I will download the unminified version anyhows to see if i can closure it together with my stuff.

**Comment by wimrijnders** [comment]
> Of course you are more humble than I am. My bad. I apologize yet again. :)

You have owned me. I hereby acknowledge you as master.

I hope I can put some time in it soon. There's just too much to do here.

**Comment by wimrijnders** [comment]
I looked at the code.

`stabilize()` usually runs on only one occasion, that is when the `physics` module is initialized. In the code: `PhysicsEngine.js roundabout line 199`.
So normally, it is run once on startup. The only ways to force it to run again, are:

- Stop the `physics` module and restart it (can be done through `physics` options)
- Run it explicitly with `network.stabilize()`

I'm afraid there's no connection at all with the updating of data, let alone the usage of queues.

...well, a tiny one: in `physics`, when a big enough change in the positions of nodes is detected, `stabilize()` may be triggered internally. See `PhysicsEngine.js roundabout line 498`. This internal stabilization does *not* emit events. This might actually be what you're witnessing.

So, this is neither a bug nor a facepalm observation; it's just the way it works. Hope this helps.

**Comment by wimrijnders** [comment]
@robtex Was this sufficient answer to your question? If so, please close the issue.

**Comment by robtex** [comment]
@wimrijnders : Sorry, yes, perfectly sufficient. Thank you very much for your time!
