### ISSUE TITLE
Network - Shapes with Image

### ISSUE THREAD

**Issue by dandansoysauce** [almende/vis#3148]
How do you put an image inside a node shape? Like stars, diamonds and square. Other than circularImage.
![samplenodes](https://user-images.githubusercontent.com/25461756/26922597-2a325e52-4c72-11e7-9fbf-b4634e0d436f.png)

**Comment by wimrijnders** [comment]
This is not implemented and hence not supported.

The only possible shapes for images are rectangular and circular.

**Comment by bradh** [comment]
@wimrijnders Would a masked / partly transparent PNG image be possible? It would still be rectangular / circular, but would look like whatever the non-transparent section is.

**Comment by dandansoysauce** [comment]
@wimrijnders I am trying to put an SVG shape with an image background, but I still couldn't show the SVG. Will experiment more. This is from the HTML in Nodes sample.

**Comment by wimrijnders** [comment]
@bradh Transparent backgrounds should work if option `nodes.shapeProperties.interpolation : false`.

@dandansoysauce Try that as well with the SVG. But actually I'm not sure if the SVG with images will work. I'm curious about the result.

**Comment by dandansoysauce** [comment]
Image won't load when I put it inside a pattern and fill the shape with it. But I can show a path inside it, that'll do it for now. I hope shapes with images will be implemented in future versions. Thanks
