### ISSUE TITLE
Network - highlight associated edges defaults intermittently in IE11

### ISSUE THREAD

**Issue by dockstreet** [almende/vis#3151]
Hi - 
With Vis 4.20.0 - it seems as if the first level of edges will sometimes highlight, but not always. Vis 4.19.0 did not seems to have this behavior. Chrome does not have this behavior with Vis 4.20.0 or Vis 4.19.0.

thx

**Comment by bradh** [comment]
Do you have a reproduceable case where it does / does not happen? Does it happen for one of the examples? If not, can you create a case where it does happen?

**Comment by dockstreet** [comment]
Hi , I'm doing it in R through a wrapper. Not sure how to do it in the base JavaScript. 
https://github.com/datastorm-open/visNetwork

**Comment by bradh** [comment]
Sorry, I'm not going to learn R for this...
Hope that someone else can help.

**Comment by dockstreet** [comment]
No worries & I appreciate the response .
I think I came up with a way around it , seemed to be a default in the wrapper for hoverConnectedEdges , I changed it and haven't been able to recreate it . thx and closing this one
