### ISSUE TITLE
TypeError: Cannot read property 'emitter' of null

### ISSUE THREAD

**Issue by ramang16** [almende/vis#3153]
I am using vis to build a timeline chart in my angular js application. Below is my code. I will update my objects.. like adding new object or changing the start and end date of the object. When I do this, I am doing destroy on existing timeline and recreating it. In destroy(), it is throwing TypeError: Cannot read property 'emitter' of null. Screenshot attached below.
```
function displayChart(objects) {
		var id = 1;
		var items = [];
		objects.forEach(function(el) {
			if(el.startDt) {
				var item = {id: id++, content: el.name, start: $filter('calFormat')(el.startDt, "yyyy-MM-dd")};
				if(el.endDt) {
					item.end = $filter('calFormat')(el.endDt, "yyyy-MM-dd");
				}
				items.push(item);
			}
		});
		if($scope.tl) {
			$scope.tl.destroy();
		}
		$scope.tl = basicTL('chartId', items, undefined);
	}

function basicTL (elId, items, options) {
		var container = document.getElementById(elId);
		var items = new vis.DataSet(items);
		var options = options || {};
		var timeline = new vis.Timeline(container, items, options);
		return timeline;
	}
```

Any help would be appreciated.

![vis_null](https://user-images.githubusercontent.com/15015815/26965427-565aaaf6-4d13-11e7-8cd2-d0f9edb0d22f.png)

```

**Comment by ramang16** [comment]
Found the issue.. I am calling destro() on already destroyed timeline, so the error.

I am also calling $scope.tl.destroy(); from other method, I thought $scope.tl will become undefined on destroy().. but it is not. When it invokes destoy() on already destroyed timeline.. it is throwing the error.

**Comment by wimrijnders** [comment]
Just like to say that I appreciate you solving this on your own and closing the issue. I would so much love to see more issue submitters doing that. You've made my day a little better, hope yours is good too!

**Comment by vladanPro** [comment]
`if (this.timeline) {
        this.timeline.destroy();
      }`

Same problem with Angular 6, how i can prevent this. How to check if timeline exist and then call destroy. If you remember, thank you.
