### ISSUE TITLE
Vis js set time scale for one day only

### ISSUE THREAD

**Issue by dkp26** [almende/vis#3155]
I am trying vis js timeline. We have requirement to show data only for one day, basically from start of the day to end of the day.
I have set the zoomMin and zoomMax, this way i cannot zoom out of one day.this works fine.
But when I try to drag the timeline, i can see the dates before this day or after this day.

Please find the jsfiddle here
http://jsfiddle.net/5p0ggwkx/80/

How can I force the timeline to display only one day;'s scale and cannot zoom or drag into more days?

**Comment by bradh** [comment]
Use `min` and `max` as shown in http://visjs.org/examples/timeline/interaction/limitMoveAndZoom.html

This would change your options to be:
```
  // Configuration for the Timeline
  var options = {
    //width: 700,
    min:1496991600000,
    max:1497077999999,
    start:1496991600000,
    end:1497077999999,
    zoomMax: 86399999,

    zoomMin: 10,
    format: {
      minorLabels: {
        hour: 'h:mm A',
      }
    }
  }
```

You can still zoom in and out (within the limits specified).

**Comment by dkp26** [comment]
Thanks
