### ISSUE TITLE
Vis Network - Display the node's title when the user clicks on the node?

### ISSUE THREAD

**Issue by FilipQL** [almende/vis#3156]
Node's title will be displayed when the user hovers over the node. 

![zfdgsdfgsdgf](https://user-images.githubusercontent.com/18264428/27005568-48048de6-4e21-11e7-8bc0-dc0207f2d5bd.png)

```
let nodes = new vis.DataSet([
    {
        id: 1,
        label: 'host1',

        title: `<pre><code>host {
        id = "host1"
		port { id = "p1" }
    }</code></pre>`
    }
 . . .
```
![title google chrome 2017-06-10 21 15 28](https://user-images.githubusercontent.com/18264428/27005591-fa74acf4-4e21-11e7-8e02-ec7b3b420a27.png)

Is there any way to display the title (tooltip, popover) when the user clicks on the node (instead of _hover over the node_)?

If it is not possible, then is it possible to **hide** the title when the user **clicks** on the node? So, when a user hovers over the node - the title will be displayed, but when he clicks on the node - title will be removed.

**Comment by wimrijnders** [comment]
Had a look at it, here is a method showing a popup on click:

```javascript
var options = {
  interaction:{
    tooltipDelay: 3600000      // Set a really big delay - one hour
  }
};

// Intercept the click event
network.on("click", function (params) {
  // Check if you clicked on a node; if so, display the title (if any) in a popup
  network.interactionHandler._checkShowPopup(params.pointer.DOM);
});
```
Note that the popup will disappear in the normal manner when the pointer moves away from a node.

I will really need to add a disclaimer: This uses an internal routine (that's what the underscore in front of `_checkShowPopup()` means). So the official response is: 'we don't support this, use at your own risk'.

I'm currently wondering if this kind of functionality should be added to `network`. I suppose if there is enough demand for it, I will make an API change for this to make an official.

HTH.

**Comment by FilipQL** [comment]
Thank you!

**Comment by seanmcveigh** [comment]
Just another vote to officialize such a feature.  I'm working on a network diagram that I'd like to be able to interact with on a touchscreen like an iPad, which to the best of my knowledge, does not support hovering.  My alternate UX would require me to find somewhere else on screen to display the information.
Thanks!

**Comment by bhagwandas** [comment]
Please do support it. Much needed feature. Helps a lot in making single page graph applications so you don't have to move out.

**Comment by Qmatteo** [comment]
Any news to this thread?
It would be very useful to display the title when the user clicks on the node (instead of hover over the node)!
