### ISSUE TITLE
Vis Network -  How to dynamically set the value of the node's title (tooltip, popup)?

### ISSUE THREAD

**Issue by FilipQL** [almende/vis#3157]
When a user hovers over the node - the `title` (tooltip, popup) is displayed. 
```
let nodes = new vis.DataSet([
    {
        id: 1,
        label: 'host1', 
        ...
        title: 'XXXXXXXXXXXXXXXX'
    }
. . .
```
![title google chrome 2017-06-10 22 31 48](https://user-images.githubusercontent.com/18264428/27006111-9eacfcfe-4e2c-11e7-84e1-539f5842dd46.png)

I need to set the value of the `title` dynamically. First I've tried with `hoverNode` event:

```
network.on("hoverNode", function (params) {
    let node = data.nodes.get(params.node);
    node.title = 'AAAAAAAAAAAAAAA';
    console.log(node);
});
```
![title google chrome 2017-06-10 22 29 58](https://user-images.githubusercontent.com/18264428/27006099-6ed8082a-4e2c-11e7-97b5-be2bb340221d.png)

As shown on the picture above, using `console.log(node)` shows that the `title` is changed, but Vis still displays the old value.

I've also tried with the `showPopup` event:

```
network.on("showPopup", function (id) {
    let node = data.nodes.get(id);
    node.title = DSL.generateNodeScritp(node);
    console.log(node);
});
```
but it's the same. Is it possilbe to dynamically set the value of the node's `title` (tooltip, popup)?

**Comment by FilipQL** [comment]
Just found one solution: `network.canvas.body.nodes[node_id].options.title = ...`

**Comment by wimrijnders** [comment]
The API way of this this is through `DataSet.update()`:

```
data.nodes.update({id: 1, label: 'AAAAAAAAAAAAAAA'});
```
