### ISSUE TITLE
Loading bar progress doesnt start immediately

### ISSUE THREAD

**Issue by gubr123** [almende/vis#3160]
Hi.

I am using the same mechanism as in the example for the loading progress.

The problem is, that it takes some time until the progress start to load. I see the event `stabilizationProgress` is called after some time and that's the problem. how can it be called sooner, or is there any other solution for that?

my options are as follow:

```
ctrl.options = {
            nodes: {
                scaling: {
                    min: 10,
                    max: 30
                }
            },
            interaction: {
                tooltipDelay: 200
            },
            physics: {
                solver: 'barnesHut',
                adaptiveTimestep: true,
                barnesHut: {
                    gravitationalConstant: -8000,
                    springConstant: 0.04,
                    springLength: 95
                },
                stabilization: {
                    iterations: 987
                }
            },
            layout: {
                // improvedLayout: true,
                randomSeed: 191006
            },
            width: '100%',
            height: '100%'
        };
```

**Comment by wimrijnders** [comment]
:+1: Thank you for opening a new issue! I'll remove the text from the other one.

**Comment by gubr123** [comment]
@wimrijnders Any idea why `stabilizationProgress`  dosesn't start immideately?

**Comment by wimrijnders** [comment]
I think this is because it is started by a timer, which causes stabilization to skip many `stabilizationProgress` events. Hence, the stabilization is running are expected but the events are lagging. I'm investigating this now.

**Comment by gubr123** [comment]
@wimrijnders Great, thanks, waiting to hear your opinion.

**Comment by wimrijnders** [comment]
This is what is happening:

- In file `PhysicsEngine.js`, the stabilization is in method `_stabilizationBatch()`.
- `_stabilizationBatch()` is started with a timer. If the stabilization doesn't complete within the current call, it restarts a timer for itself.
- First the loop is run for the stabilization iterations, then the `stabilizationProgress` event is fired.
- The stabilization ends if:
  - The maximum number of iterations, as specified by option `physics.stabilization.iterations`, has been reached.
  - The stabilization code concludes for itself that it is done.

This has the following consequences:

- the `stabilizationProgress` event for start of stabilization (e.g. iteration 0) is never sent.
- the `stabilizationProgress` event for end of stabilization is never sent. 
- the sending any in-between events during stabilization depends on if the stabilization finished within the current call of `_stabilizationBatch()`.

So, the firing of the `stabilizationProgress` event is fickle and undependable.

----
I propose the following:

- Ensure that the `stabilizationProgress` event for start of stabilization (iteration 0) is always sent.
- Ensure that the `stabilizationProgress` event for end of stabilization is always sent. 
- What happens in between is really quite hard to make consistent. I propose to not try to improve this.
- If stabilization is finished before the maximum number of iterations is reached, I propose to just always send the final number of done iterations with `stabilizationProgress`.
- The completion of the stabilizing can be detected by catching event `stabilizationIterationsDone`.

I hope you can agree with this. I will wait for your response and feedback before implementing.

**Comment by gubr123** [comment]
@wimrijnders Ok, so as you mentioned, the first and last iterations indeed are not coming to the `stabilizationProgress`.
About catching the end of the iterations by the `stabilizationIterationsDone` is true, but that won't fix the issue, since the problem is with the start of the progress.

The problem is that until the first iteration the loading bar stuck on 0% because nothing initiates it...

True?

**Comment by wimrijnders** [comment]
> The problem is that until the first iteration the loading bar stuck on 0% because nothing initiates it...

From your perspective, that is true, yes. I understand now that this is your issue.
I can be a bit more precise than that: a progress event is currently sent after every `physics.stabilization.updateInterval` iterations, and only if the stabilization is not completed.

I also take into account the end of the stabilization, though. In my opinion, the progress should also be completed nicely.

**Comment by gubr123** [comment]
@wimrijnders Ok, I agree. so, I will wait for updates from you regarding this issue?

Once again, many thanks!

**Comment by wimrijnders** [comment]
Well, it is totally clear to me what needs to happen. I'm going to make a PR for it right now. The consequence is that it will be officially published in the next release, which may take some time.

The alternatives are:  
- you clone the PR and build it for yourself 
- you just take the diff from the PR, add it to your cloned vis repo and build for yourself.
- I build you a `vis.js` with the change and you can use that in the meantime

The danger with the last is that if you need more fixes, I will need to rebuild again (and again....). I suppose that is more a risk for me than for you :confused:. Can we agree that I only do this for this one issue?

**Comment by gubr123** [comment]
Sounds great, Ill go with the third option.
In addition, if it's not too complicated, Ill be happy to get the build process, to avoid asking you for further builds :)

**Comment by wimrijnders** [comment]
OK! So: this first issue, I build for you, any further issues, you do the build.

Deal! :handshake:

I should be able to get this done pretty quickly. You should get a notification when the PR has been submitted.

**Comment by gubr123** [comment]
Thanks!!!

**Comment by wimrijnders** [comment]
@gubr123 OK nailed it. Grab your interim `vis.js` build [from here](https://github.com/wimrijnders/github_bugs/tree/master/vis/issue3160).

Note that this is the 'bleeding edge' build, containing all fixes since last release. So consider this an alpha-version.

Would appreciate a confirmation that it works for you. Awaiting your feedback!

**Comment by gubr123** [comment]
Many thanks again.

But, I forgot to mention, I am using the angular version of visjs, how can I use your fix in that library?

**Comment by wimrijnders** [comment]
:confused:  I have no clue. I'll do a quick search to see if I can come up with an answer for that.

**Comment by gubr123** [comment]
@wimrijnders I believe you're getting tired of my thanks, but once again, really appreciate it!!

**Comment by wimrijnders** [comment]
Do you mean this [angular-visjs module](https://github.com/visjs/angular-visjs)? It uses `package.json`, so normally, [this fix will work](https://stackoverflow.com/a/38417065/1223531).

But....there is no dependency with `vis.js` defined in that `package.json`, so I think you can get away with just adding a local link to your web page:

```
  <script type="text/javascript" src="path/to/vis.js"></script>
```

If this is not the `angular` module you mean, then I'm clueless and can't help you further. I think you have a better chance of finding a solution than me; I'm totally `angular`-unaware.

HTH.

**Comment by gubr123** [comment]
WORKS!

just replaced your fix files in the vis directory, and the angular-visjs just uses them as a dependency.

Thanks @wimrijnders very much!

**Comment by wimrijnders** [comment]
Please close the issue when you're happy with it. And have a good further day!

**Comment by gubr123** [comment]
@wimrijnders 
Hi again.
Just noticed, for some reason, in your build, the tooltip doesn't work. all my edges has 'title' property, and in the release build it pops-up the tooltip. It doesn't in your build.

Any ideas?

**Comment by wimrijnders** [comment]
Just tested it, tooltips work for nodes as well as edges with that build.

Perhaps some funky opttion? First, run with your console open, and see if any errors or warnings pop up.
If that doesn't result in anything, show me your options. A `jsfiddle` would be even better, but let's see if we can do the easy thing first.

**Comment by gubr123** [comment]
No errors in console.

```
ctrl.options = {
            nodes: {
                scaling: {
                    min: 10,
                    max: 30
                }
            },
            interaction: {
                tooltipDelay: 200
            },
            physics: {
                solver: 'barnesHut',
                adaptiveTimestep: true,
                barnesHut: {
                    gravitationalConstant: -8000,
                    springConstant: 0.04,
                    springLength: 95
                },
                stabilization: {
                    iterations: 987
                }
            },
            layout: {
                // improvedLayout: true,
                randomSeed: 191006
            },
            width: '100%',
            height: '100%'
        };
```

**Comment by wimrijnders** [comment]
Nothing strange there. I'll just examine this for a moment.

**Comment by gubr123** [comment]
Ok thanks

**Comment by wimrijnders** [comment]
Well, far as I can tell it's working just fine.

Here is a [jsbin](http://jsbin.com/nerekec/edit?html,output). See if you can abuse it so it looks more like your case. Your options are already in.

**Comment by gubr123** [comment]
Weird, I can't even see the output in the jsbin..
so it's hard for me to abuse it....

**Comment by wimrijnders** [comment]
Sometimes jsbin takes ridiculously long to load.....Not sure how to make that better, other than to retry later.

**Comment by gubr123** [comment]
Ok, Ill try the jsbin later.

Tried many times - with your build it doesn't work in my case. With the release it does. really weird. Could you direct me to the function that initiate the pop up tooltip?

Ill try to debug it myself..

**Comment by wimrijnders** [comment]
Just a thought: are you using the latest css? e.g.:

```
<link href="https://cdnjs.cloudflare.com/ajax/libs/vis/4.20.0/vis.min.css" rel="stylesheet" type="text/css" />
```

**Comment by gubr123** [comment]
@wimrijnders Am using the latest css.. no tooltip yet..

**Comment by gubr123** [comment]
@wimrijnders Ok, it looks like it has something to do with the order of the files Im uploading to my app. Ill try and fix it myself. thanks anyway!
