### ISSUE TITLE
Hiding nodes From network

### ISSUE THREAD

**Issue by gubr123** [almende/vis#3161]
Yet another question.

I've seen this question here before, but somewhere around 2014.

Wonder if there is any option of visibility of groups of nodes (and its' connected edges of course).

Couldn't find any recent documentaion about it so asking again.

Thanks in advance

**Comment by wimrijnders** [comment]
Perhaps clusters are the thing you need? Have a look at the 'Clustering' example in the [examples page](http://visjs.org/network_examples.html).

**Comment by gubr123** [comment]
@wimrijnders Thanks for your response.
Could you elaborate about using clustring for my use case. 
Cant see exactly how it can help me.

Thanks

**Comment by wimrijnders** [comment]
@gubr123 To give a good answer to that, I need to know your use case first. Please explain it.

But I went on the following in your top comments:

> Wonder if there is any option of visibility of groups of nodes (and its' connected edges of course).

Clusters are a way of combining multiple nodes to a single one. So, the group of nodes and the appropriate edges are hidden, but replaced by a single node (and appropriate edges) representing the group.

This seemed to me relevant to your description.

**Comment by gubr123** [comment]
@wimrijnders Actually, I got through this issue with removing and adding nodes dynamically, so thanks anyway.

**Comment by wimrijnders** [comment]
OK. Always better if you find the solution yourself. Please close this issue it it is not relevant any more.
