### ISSUE TITLE
network.findNode() crashes when incorrect id passed.

### ISSUE THREAD

**Issue by dheerajbapat** [almende/vis#3163]
network.findNode() crashes when incorrect id passed.
Error line: stack.push(this.body.nodes[nodeId].id);
Please can you put a safe check?

**Comment by wimrijnders** [comment]
I'm supposing that you mean the `findNode()` in `Clustering.js`. Is that correct?
I see more occurences of `stack.push()` in this source file, I'll check them all.

**Comment by wimrijnders** [comment]
Confirmed. Preparing a fix for this, also fixing `Clustering.getClusterEdges()`.
