### ISSUE TITLE
Network: moveTo() callback after animation finished

### ISSUE THREAD

**Issue by cityy** [almende/vis#3168]
I think it might be cool to have a callback function added to the view's moveTo() that fires when an animation has finished.

network/modules/View.js:125:
`moveTo(options, callback){....}`

It's probably not so hard to do but I currently don't know how to make it wait for the animation to finish. If there's noone quicker than me I might look into it at some point though.

**Comment by wimrijnders** [comment]
Well, there's the `animationFinished` event; what would your proposed event add to this?

Also, if you haven't done so already, take a look at the [animation example](http://visjs.org/examples/network/other/animationShowcase.html). Isn't there any there that would suit your needs?

**Comment by cityy** [comment]
I was coming from the direction of `animationFinished` not allowing for specifying separate actions for `fit() `and `moveTo()` animations for instance but I guess in most cases people will manage to work around that. 
In my case I used a setTimeout() with the same length as my animation duration to to run a function dedicated to when `moveTo()` was called on a selected node position (while generally doing something else with `on.(animationFinished)`). I figure it might be better to not bloat things with event based callbacks.

**Comment by wimrijnders** [comment]
> I figure it might be better to not bloat things with event based callbacks.

That thought is hugely appreciated!
