### ISSUE TITLE
Timeline: Changing stacking  mode programmatically not working

### ISSUE THREAD

**Issue by pkoesters** [almende/vis#3172]
Hi guys,
it appears that toggling the stack mode at runtime is no longer working in 4.20.0  (Chrome/FF in Windows7). 

We are just using plain groups, no subgroups involved. Up to 4.19.1 everything was working fine.

See https://jsfiddle.net/pkoesters/t3aow3pn/17/ for the non-working 4.20.0-based example 
and https://jsfiddle.net/pkoesters/t3aow3pn/18/ for the working 4.19.1-based example

I also tried to fiddle around with the additional subgroup stack setting, despite of not actually having any subgroups, but that didn't do the trick either. 

Appreciate your work and help, thanks :-)

**Comment by bradh** [comment]
It looks like stack still works, but I don't see toggle working on Firefox on Windows 7 either.

**Comment by pkoesters** [comment]
Yes, exactly that is my problem here. The inital setting of the stack option works fine. Only updating the setting is not working.

**Comment by bradh** [comment]
May be a similar problem in http://visjs.org/examples/timeline/items/itemOrdering.html

**Comment by yotamberk** [comment]
Thanks for reporting! I'll be on it!

**Comment by yotamberk** [comment]
I've located the problem. It's in this PR #3078. 
The problem is that the `ItemSet` doesn't force a restack when setting the options but only when scrolled or zoomed. 
I'm thinking of the most elegant way to solve this. Any suggestions will be great.
