### ISSUE TITLE
oncontext event in Network doesn't pass hovered nodes and edges as arguments.

### ISSUE THREAD

**Issue by shmuely** [almende/vis#3173]
`oncontext` handler function should receive in its two first arguments, arrays of the currently hoevered nodes and edges (as in `onClick` handler function.)
Currently it always receives empty arrays.

**Comment by wimrijnders** [comment]
The reason for the nodes missing, is one of definition: `_generateClickEvent()`, by definition, returns the *selected* nodes and edges in the arrays of the events. A selected node need not be hovered over, and a hovered-over node need not be selected. Yes, I realize it, this is legalese.

Now, I don't feel that we need to adhere strictly to that definition, but I do feel that some thought must be put in how to redefine it. The submitted PR as such will not do. At the very least, the documentation will need to be changed.

**Comment by wimrijnders** [comment]
Closing; aside from non-activity, the code has progressed to the point that this issue is irrelevant.
