### ISSUE TITLE
Asynchronously drawing of the network

### ISSUE THREAD

**Issue by gubr123** [almende/vis#3177]
Hi.

I am loading the network map in the background of my app, in order to avoid waiting time when one wants to take a look at the network.

The thing is, that while it is drawing in the background, it causes some lagging in my app. Is there any way of building the network map Asynchronously? so the drawing wont cause my app to slow down?

Thanks

**Comment by gubr123** [comment]
@wimrijnders Great, exactly what I was looking for, Thanks!

**Comment by wimrijnders** [comment]
@gubr123 The only con is that the asynchronous stabilization routine is called more often, hence a bit more overhead in processing and more time needed to stabilize.

But if your network is big enough (yours obviously is, since you had this issue), this overhead is negligible.
