### ISSUE TITLE
zoom to selected nodes

### ISSUE THREAD

**Issue by dsl101** [almende/vis#318]
Hi again Alex :). Having finally got the node highlighting working properly, I'd like to add a feature to zoom  the network to show just the selected nodes. I've done this so far by grabbing bits of code from the source in the `_getRange()` function and `_zoomExtent()` functions.

Firstly, I _think_ there might be a bug in `_zoomExtent()` if the min / max x and y coordinates are either both negative or both positive - probably this wouldn't occur when showing the whole network, but for a subset of nodes it happens often. At line 14527 (V3.5.0), should this:

	var xDistance = (Math.abs(range.minX) + Math.abs(range.maxX)) * 1.1;
	var yDistance = (Math.abs(range.minY) + Math.abs(range.maxY)) * 1.1;

be replaced with this:

	var xDistance = (maxX - minX) * 1.1;
	var yDistance = (maxY - minY) * 1.1;

assuming maxN > minN, etc.?

My second question is more specifically about how `zoomLevel` is calculated. I found that the scaling of `1.1` above doesn't work well for small sets of nodes - it seems to zoom in far too much. Is there a way to accurately calculate the `zoomLevel` required to put the bounding box of the canvas around the selected nodes, regardless of how many there are? When I say 'selected', I'm meaning selected in the sense of my other post about the actual selected node plus all those a distance of 1 edge away.

Thanks,

Dave

**Comment by AlexDM0** [comment]
Hi Dave,

Sorry for the long silence, a few things came up. I have added a bounding box to the zoomExtent function. Maybe there's something you can use there?

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi Dave,

I have added a getBoundingBox method to the develop branch. That should solve your problem.

Regards,

Alex
