### ISSUE TITLE
Network graph is crammed

### ISSUE THREAD

**Issue by ronnieoverby** [almende/vis#3181]
I'm new to vis.js and need a little guidance on what to do about my first graph being extremely cramped and impossible to read.

I created a codepen that shows what I'm talking about:
https://codepen.io/ronnieoverby/pen/KqaKBV

The javascript follows the basic example in the vis documentation for networks.

Here's a screenshot of the graph:
https://files.gitter.im/vis-js/Lobby/j89N/image.png

![Screenshot of problem graph](https://i.imgur.com/9YPKWCN.png)

Here's the javascript that sets up the network ( minus the data ).

```js
    var nodes = new vis.DataSet(data.nodes);

    // create an array with edges
    var edges = new vis.DataSet(data.edges);

    // create a network
    var container = document.getElementById('mynetwork');

    // provide the data in the vis format
    var data = {
        nodes: nodes,
        edges: edges      
    };

    var options = {
      nodes: {fixed:false},
      edges: {
        arrows:'to',
        smooth: false
      },
      //layout: {              },
      //configure: true,
      //physics: false
    };

    // initialize your network!
    var network = new vis.Network(container, data, options);
```

**Comment by wimrijnders** [comment]
Hi there, I see that this network is suffering from the 'nervous twitch syndrome' (my phrase).

It's a physics thing; the physics parameters interplay to get this effect. Also, that's a huge amount of edges you got there, which also comes into play.

This is my knee-jerk reaction:
- Turn up `damping` to reduce the jiggling
- Increase `springLength` to make the distances between nodes larger.

In cases like these, I enable the physics configuration fields, see the [`physicsConfiguration` example](http://visjs.org/examples/network/physics/physicsConfiguration.html) on how to this.

By doing a quick tuning of given two parameters, I get:

![download](https://user-images.githubusercontent.com/769037/27250783-e65be28a-5337-11e7-8b06-193889127697.png)

With physics options:

```js
var options = {
  "edges": {
    "smooth": false
  },
  "physics": {
    "barnesHut": {
      "springLength": 330,
      "damping": 0.44
    },
    "minVelocity": 0.75
  }
}
```

----

I do note again the large number of edges; this may be problematic in getting a decent overall layout.
Also, I encourage you to try twiddling physics configuration parameters yourself, to see if you can get something better.

**Comment by ronnieoverby** [comment]
Thanks for looking at it.

**Comment by wimrijnders** [comment]
My pleasure; please close the issue if you're satisfied with the answer!
