### ISSUE TITLE
Width constraint does not break words...

### ISSUE THREAD

**Issue by jmvenancio** [almende/vis#3185]
I set the `widthConstraint` to `maximum: 300` and `minimum: 300`.

This is what happens if I write a word that has a bigger "length" than 300.

![image](https://user-images.githubusercontent.com/15384201/27265035-61f6335c-5485-11e7-8dc3-1d09b17ee47c.png)

Is there anyway to overcome this problem?

Thanks in advance!

**Comment by wimrijnders** [comment]
This is how the handling of a single, long word works at the moment. It gets put on a line by its own and the `widthConstraint.maximum` is broken.

I have the following questions:

- Is there a real-live use case for this? Does it actually happen that such a long word is present?
- What would you expect to happen? Is the second image perhaps a representation of what you would expect?

**Comment by bradh** [comment]
An overflow might make more sense.

**Comment by wimrijnders** [comment]
By coincidence, I'm actually working on label break-down into lines, see #3171.

This issue made me ponder a bit; I sort of came to the conclusion that if `widthConstraint.maximum` is defined, it should be respected always. So really, big words should just be broken into lines always.

Here is some test output, what do you think of following?

Without width maximum:
![untitled2](https://user-images.githubusercontent.com/769037/27273648-36acb054-54d0-11e7-9339-422095affd2f.png)

With width maximum:
![untitled](https://user-images.githubusercontent.com/769037/27273654-3b66e128-54d0-11e7-941b-8a6b276d4619.png)

**Comment by wimrijnders** [comment]
> Is there anyway to overcome this problem?

To answer your question, the only way around it now, is to shorten the label yourself.

Otherwise, wait for the fix as described above to be released.

**Comment by jmvenancio** [comment]
Thank you for your answer.

That behaviour is what I was expecting. Do you know when will it be the next release? Should I put my effort on breaking words myself or should I wait for the next release? 

Answering your questions:

The future users of my project can do whatever they want... So, although it is not likely to write a 1000 letters word, they can do it. And of course the word should be broken to the next line (and perhaps adding a `-` in the previous line, even if it does not respect the language rules) what do you think?

**Comment by wimrijnders** [comment]
> Do you know when will it be the next release?

It is planned next weekend (24 jun 2017). However, this will not be in it, it's too late to do the full review cycle.

> Should I put my effort on breaking words myself or should I wait for the next release?

If you need it short term, then yes, put the effort into it. At the earliest, the release it will be in will be done in more than a month.

> ...what do you think?

I agree, see my thoughts above. Big words should be broken always.

**Comment by jmvenancio** [comment]
Hello, can you tell me if there is any progress with this issue?

**Comment by jmvenancio** [comment]
Actually I do not know how to rebuild it. But if someone explain to me I can give a try since I really need this fix.

**Comment by bradh** [comment]
https://github.com/almende/vis#build provides the build instructions. You need to check out the branch that has the changes - see https://help.github.com/articles/fetching-a-remote/ and do google searches. Sorry that I don't have time to provide step-by-step instructions.
