### ISSUE TITLE
Very slow network rendering

### ISSUE THREAD

**Issue by gubr123** [almende/vis#3187]
Hi.

For test purposes, I made a demo network, constructed from 4000 nodes, each connected to one node,
e.g. 1-2, 3-4, 4-5, etc...

The rendering of the network is super slow. How can I make it load faster?

Here are my options:

```
ctrl.options = {
            autoResize: true,
            nodes: {
                scaling: {
                    min: 10,
                    max: 30
                }
            },
            interaction: {
                tooltipDelay: 200
            },
            physics: {
                solver: 'barnesHut',
                barnesHut: {
                    gravitationalConstant: -8000,
                    springConstant: 0.04,
                    springLength: 95
                },
                adaptiveTimestep: true,
                stabilization: {
                    iterations: 987,
                    updateInterval: 100
                }
            },
            layout: {
                improvedLayout: false,
                randomSeed: 191006
            },
            width: '100%',
            height: '100%'
        };
```

Thanks!

**Comment by wimrijnders** [comment]
I'd say, crank up the value of `layout.improvedLayout`; make it orders of magnitude bigger.
This saves up on redrawing the screen on every iteration, which is a huge time saving.

> The rendering of the network is super slow. How can I make it load faster?

But TBH I find this statement a bit ambiguous.
- 'rendering is slow' implies that the actual drawing of the network is slow
- 'load faster' implies that the time till first display of the network is long.

Above, I assumed that you mean the latter, is this correct? Is this a stabilization issue?

**Comment by gubr123** [comment]
1. When I set `layout.improvedLayout` to `true`, The browser prompts an error: 

> This network could not be positioned by this version of the improved layout algorithm. Please disable improvedLayout for better performance.

2. 'load faster' implies that the time till first display of the network is long. The whole stabilization progress takes a lot of time, few minutes. It comes back to the event around every 1 minute.

**Comment by wimrijnders** [comment]
Yes, it does that. There's a check on size using the 'advanced' algorithm. If there are too many nodes in the nework, that algorithm is skipped and the 'regular' algorithm is used instead.

The message is informational, not an error.

> It comes back to the event around every 1 minute.

That sounds like a big-ass complex network. I don't think there's too much off-hand advice I can give you here. If you want more support for this, please make a `jsfiddle` or suchlike.

Some final notes:
- To make the stabilization events short, lower the value of `physics.stabilization.updateInterval`. 100 is a pretty large value. As a test set it to 10 or even lower. This, of course, will not make the total stabilization time shorter.
- The only sure-fire way to improve on stabilization is to precompute the coordinates, so that stabilization can be skipped. If the given network is not static, this might not be an option of course.
- Try another solver instead of `barnesHut`. This is actually the slowest of them all, but truth be told it does give the best results.

**Comment by gubr123** [comment]
Ok, let me see I can work it out myself, Which faster algorithm other than `banesHut` would you suggest?

Let's keep this issue open for a while, if I won't be able to sort it out myself Ill make a `jsfiddle`.

**Comment by wimrijnders** [comment]
I'd go for 'forceAtlasBased', 'hierarchicalRepulsion' is faster but the results for non-hierarchical networks are crummy.

I'll expand on the second point above:

You don't need to precisely fix the coordinates; you can also set the xy-values as crude starting points and let the solver take it from there.
If you roughly know what the network should look like beforehand, this is a big help for the solver.

**Comment by gubr123** [comment]
@wimrijnders I made a jsfiddle with the data and the options.

[jsfiddle](http://jsfiddle.net/566pypny/1/)

Hope you could see whats wrong...

**Comment by wimrijnders** [comment]
Oh man. I see what you mean. This is so slow, it's not funny any more.
Will take a look (but alas, paid work goes first).

**Comment by gubr123** [comment]
@wimrijnders Of course, Thank you very much! waiting for your insights.

**Comment by wimrijnders** [comment]
@gubr123 Quick question during lunch break: Will the smallest elements always consist of two nodes connected by a single edge?

I'm considering laying them out in a grid pattern, but this will only work if these elements follow said pattern.

**Comment by gubr123** [comment]
@wimrijnders True. That's the worst case in my network. If each device has different network. so yes, the smallest elements always consist of two nodes connected by a single edge.

**Comment by wimrijnders** [comment]
I feel I haven't asked the question properly. From the other side:

Will there be 'server' nodes with more than one child attached?

**Comment by gubr123** [comment]
Yes. normally, the network is meant to draw a network map. so in most cases, there will be some networks, and the the 'servers' will be attached to those networks. so a normal case will be one network node, which is attached to multiple 'server' nodes

**Comment by wimrijnders** [comment]
Hokay, that's going to make it tough.

I couldn't resist twiddling with the results (damn you). Switching to hierarchical gives this:

![untitled](https://user-images.githubusercontent.com/769037/27282487-76b8a840-54f0-11e7-9530-94dd87a11641.png)

I'm guessing you're bursting with excitement when you see this. it's all the 'elements' arranged below each other. Zooming in:

![untitled2](https://user-images.githubusercontent.com/769037/27282526-9f81d3f0-54f0-11e7-8e80-dc17fb2b7ec9.png)


This makes for an unexciting representation; however, it is guaranteed to display properly if the elements become more complex.

Would this work for you? And oh yes, worth to mention that this loads in seconds.

**Comment by wimrijnders** [comment]
> so a normal case will be one network node, which is attached to multiple 'server' nodes

Oh wait. So the 'elements' are drawn in the wrong order. Node with IP should be on the left, correct?
Also, can different ip-nodes connect to the same server node? I mean, should these connections be visible in the network?

**Comment by gubr123** [comment]
OK, so the hierarchical attitude won't work.

Here is a screenshot of a normal network, where some 'server' nodes are attached to some 'ip' nodes etc.
with the barnesHut solver:

![capture2](https://user-images.githubusercontent.com/10476634/27283713-41892038-54fe-11e7-9a95-48622ba80b93.PNG)

with the hierarchical solver:

![capture1](https://user-images.githubusercontent.com/10476634/27283716-44d22cbc-54fe-11e7-9fc0-0bd592d8f48e.PNG)

So when it draws a normal map, that won't work well.

**Comment by wimrijnders** [comment]
OK. Here's a quick tweak for the given network: change the edge type to `continuous`. This will look better and also makes the rendering faster.

Keep in mind that, even though you are using the hierarchical solver, this is not a hierarchical layout.

**Comment by wimrijnders** [comment]
Is this BTW the regular view for your networks? So the `problem` dataset is a special case of this? Or is it a completely separate view?

**Comment by gubr123** [comment]
The `problem` dataset is a special case of the same network.

As you can see, for pretty small and "real" networks, it works fine. The problem occured when it has a very big number of nodes and them all are connected to only one other node.

Checking the issue with the continous.

**Comment by wimrijnders** [comment]
> The problem dataset is a special case of the same network.

This makes it very, very hard to create a general solution. At the verge of impossible, I think.

**Comment by gubr123** [comment]
Ok, I am trying to understand, what is the cause of this problem, is it the very big number of nodes (4000+-) or the fact that the network has a lot of disconnect components (component = two nodes connected with an edge) ?

**Comment by wimrijnders** [comment]
Both, but especially the big number of nodes. The physics, is basically O(N^2) where N = number of nodes.

But the lack of shared edges also plays a part. Normally, the physics can find shortcuts when many connections are present, reducing the time needed. This does not happen in the problem-network, so it does the full calculation.

**Comment by gubr123** [comment]
Ok, so Ill try to figure it out, could please explain:
`Keep in mind that, even though you are using the hierarchical solver, this is not a hierarchical layout.
`

**Comment by wimrijnders** [comment]
Hierarchical layout is a view option:
```js
  var options = {
    layout: {
      hierarchical: {
        enabled: true,
      }
    }
  };
```

Here is a random example network:

![untitled](https://user-images.githubusercontent.com/769037/27284880-c966defe-54fa-11e7-9e63-83ea4cb3e404.png)


here is the same network with hierarchical enabled:

![untitled2](https://user-images.githubusercontent.com/769037/27284896-dbceef82-54fa-11e7-8ce6-b4e54e118808.png)


Makes more sense now?

**Comment by gubr123** [comment]
Yes, thats understood, please, could you explain what exactly did you change in the options in order for it to load in seconds?

In addition, I think clustering could be a helpful thing in my situation. However, the problem Im ecountring with clustring is that the node are clustered but the edges arent. so It causes something like this:

![image](https://user-images.githubusercontent.com/10476634/27291299-830738aa-5518-11e7-9874-b03d72146f25.png)

I've seen that disabling physics might help, but I dont want to affect the whole network. Is there any option to replace all the edges in on edge?

**Comment by wimrijnders** [comment]
> could you explain what exactly did you change in the options in order for it to load in seconds?

I converted to the layout to hierarchical and disabled physics. I honestly don't think hierarchical is suitable for your network, but in any case here are the relevant changes in the options:

```js
var options = {
  edges: {
    smooth: {
      type: 'continuous'
    },
  },
  physics: {
    enabled: false,
  },
  layout: {
    hierarchical: {
      enabled: true,
      direction: 'LR'
    }
  },
};
```

Wrt. clustering: can you tell me how te reproduce the image above?

**Comment by wimrijnders** [comment]
I don't think I can help you much more with the first test-network here. It's just a lot to process for the physics.

**Comment by gubr123** [comment]
`I don't think I can help you much more with the first test-network here. It's just a lot to process for the physics.`

Yep, thats understood, any idea about the my clustering question?

**Comment by wimrijnders** [comment]
No idea about the clustering at this moment. Above, I asked how to reproduce the image. Can you give me the info how to do that?

**Comment by gubr123** [comment]
Here is an example [jsfiddle](http://jsfiddle.net/wbo5z5f9/) my question if its possible to leave only one edge between the cluster and its' connected nodes, not by disabling the physics.

**Comment by wimrijnders** [comment]
? This is just a bare bones network, which doesn't illustrate the issue above. Am I supposed to fill in the example code myself?

> if its possible to leave only one edge between the cluster and its' connected nodes....

Well, yes, that's how the cluster is supposed to work. More specifically, one edge per connecting node. So I'm a bit confused by the image above.

> ....,not by disabling the physics.

Clustering and physics should work just fine together. It's not clear to me what you mean by this.

**Comment by gubr123** [comment]
I gave the wrong jsfiddle at first. did you enter the one with the cluster? (try again) [jsfiddle](http://jsfiddle.net/9m433scr/)

If I set the physics to false, so all the edges are lapping and it seems like there is one edge between the cluster and the node.

I would like to leave one edge with the physics still enabled. (e.g. If there are more than one edge between the cluster and a node, replace them with one edge)

**Comment by wimrijnders** [comment]
OK got it now. I'll have a look at itt.

This is a useful callback to add:

```js
network.on("selectNode", function(params) {
      if (params.nodes.length == 1) {
          if (network.isCluster(params.nodes[0]) == true) {
              network.openCluster(params.nodes[0]);
          }
      }
  });
```

I.e. open the cluster. I'm using it for testing.

**Comment by gubr123** [comment]
@wimrijnders Thanks, waiting to hear your thoughts

**Comment by wimrijnders** [comment]
@gubr123 I promise I will look into it. However, real life is getting in the way, I ask for patience.

**Comment by wimrijnders** [comment]
@gubr123  I found the reason for the multiple edges between the cluster and the node. The cluster edge maintains a direct relation with the one single edge it is replacing. This does not work here because multiple edges need to be replaced with the cluster edge.

I'm totally flabbergasted that no-one else has spotted this in the entire history of clustering in `Network`. You deserve a prize for your observational skills :trophy:.

Now that I know what the issue is, I can look for a solution.

----
**Update:** This is actually an entirely different issue. I want to move it out of the current one. Would you mind making a new issue out of it? Not that I can't do it myself, but I think that the credit goes to you. That's the least amount of recognition that you deserve.

**Comment by gubr123** [comment]
@wimrijnders Sure. Opening a new one.
