### ISSUE TITLE
Title attribute of nodes not showing up as a tooltip

### ISSUE THREAD

**Issue by arunkumarpro1** [almende/vis#3192]
Even after providing an attribute named 'title' to each node, tool tip is not showing up when the mouse is hovered on the node.

Here goes my complete code

    import React from 'react';
    import ReactDOM from 'react-dom';
    import registerServiceWorker from './registerServiceWorker';
    import './index.css';
    import vis from 'vis';
    
    var nodes = new vis.DataSet();
        nodes.add([
        	  {id: 1, label: 'Node 1', color: '#e04141', title :'hi'},
    	      {id: 2, label: 'Node 2', color: '#e09c41', title :'hi'},
    	      {id: 3, label: 'Node 3', color: '#e0df41', title :'hi'},
    	      {id: 4, label: 'Node 4', color: '#7be041', title :'hi'},
    	      {id: 5, label: 'Node 5', color: '#41e0c9', title :'hi'}
        ]);
        
    var edges = new vis.DataSet();
        edges.add([
        	 {from: 1, to: 2},
    	      {from: 1, to: 3},
    	      {from: 2, to: 4},
    	      {from: 2, to: 5}
        ]);    
        
    let graph = {
        		  nodes: nodes,
        		  edges: edges
        		};
    
    let options = {
        		    layout: {
        		        hierarchical: false
        		    },
        		    autoResize: false,
        		    edges: {
        		        smooth: false,
        		        color: '#000000',
        		        width: 0.5,
        		        arrows: {
        		          to: {
        		            enabled: true,
        		            scaleFactor: 0.5
        		          }
        		        }
        		      },
        		      interaction :{
        		    	  hover :true
        		      }
        		};
    
    let events = {
        		    select: function(event) {
        		        var { nodes, edges } = event;
        		        console.log("Selected nodes:");
        		        console.log(nodes);
        		        console.log("Selected edges:");
        		        console.log(edges);
        		    }
        		}
        		
    class Network extends React.Component{
    		constructor(props){
    			super(props);
    			this.state = {
    					graph : graph,
    			};
    		}
    		
    		componentDidMount(){
    			var container =  this.refs.nw;
    			console.log(graph.nodes);
    			var network = new vis.Network(container, graph, options);
    		}
    		
    		render(){
    			return (<div>
    			 <div ref="nw" style={{width:'100%' , height: '480px'}}/>
    			 </div>);
    		}
    	}
    	ReactDOM.render(
    	  <Network />,
    	  document.getElementById('root')
    	);
    registerServiceWorker();

**Comment by wimrijnders** [comment]
I can't vouch for the usage of `componentDidMount()` and `render()` in the second source block, but I can verify that the stuff in the first block works perfectly fine. The tooltips pop up as expected.

Please consider the possibility that the cause of the issue is elsewhere.

You seem to be using a framework of some kind, if so which framework is it?

**Comment by arunkumarpro1** [comment]
I am not using any other frameworks. It has been completely done using ReactJs. Is the usage of componentDidMount() method for rendering the network is right?

**Comment by wimrijnders** [comment]
> It has been completely done using ReactJs

`react.js` doesn't qualify as a framework? IMHO this is a positive answer to my question.

My knowledge of `react.js` is non-existent, I really can't comment on that. What I *do* notice is:

```
componentDidMount(){
  var container =  this.refs.nw;
  console.log(graph.nodes);

  // next line: var???? Shouldn't network be held outside of the routine?
  var network = new vis.Network(container, graph, options);
}
```

Other than that, I have nothing useful to say on `react.js`, sorry.

**Comment by arunkumarpro1** [comment]
I assumed react js  to be the default framework for vis. My bad!

Right now, I am not using the network variable anywhere. I am just trying to load the div with the network and watch the tooltip containing the title for each node on hover.

But, I didn't succeed with the tooltip.

**Comment by wimrijnders** [comment]
OK, understood.

BTW I noticed I get similar behavior if I leave out the link to stylesheet `vis-network.min.css`. Can you check perhaps if this link is correctly defined?

**Comment by arunkumarpro1** [comment]
Wow... That is it !!!!
Its working now. Thanks a ton wimrijnders 👍

**Comment by wimrijnders** [comment]
Hooray! I said something smart! Today is a *good* day.

If you're satisfied with the result, please close the issue.

**Comment by arunkumarpro1** [comment]
Yes sure.

You are really smart 👍

**Comment by wimrijnders** [comment]
hehe....you don't know me. I think it was a freak accident. But never mind, I should be happy that you believe it!

**Comment by arunkumarpro1** [comment]
Ha ha.. Be happy :) As you said, today is your good day.

**Comment by arunkumarpro1** [comment]
Hi Wimrijnders. Can you help me with this? [https://stackoverflow.com/questions/44661454/how-to-display-the-graph-after-it-is-stabilized-vis-js](url)

**Comment by wimrijnders** [comment]
Please fix the link.
