### ISSUE TITLE
Vis timeline add more items to timeline after timeline is initiated

### ISSUE THREAD

**Issue by kdipika** [almende/vis#3193]
Hi,

I am trying to use timeline.setItems to add new items to timeline after the timeline has been initialized.But this is not working.
Can you please tell me know the best way to add more items to timeline as i have a requirement to add more items as and when the data comes in. Hence should be able to add new items to already existing items.

I tried the same in this js fiddle which does not work. Uncomment line 42 to see the issue
http://jsfiddle.net/e7uodse2/1248/

**Comment by bradh** [comment]
Set items will replace the existing data set. Just add to it instead - see http://visjs.org/docs/data/dataset.html for the API.

**Comment by kdipika** [comment]
Add works to add to data set but that doesnt update the timeline .
I want the new data to be added to the timeline because i am going to get more data after the timeline is drawn.So have to append the items to existing timeline. Can you suggest how to achieve this?


http://jsfiddle.net/e7uodse2/1249/

**Comment by bradh** [comment]
Looks like the jsfiddle works for me. Are you perhaps expecting it to resize as well?

**Comment by kdipika** [comment]
The fiddle itself works ..But the new data does not get added to timeline

The line data.add(data2) does not seem to have any effect

**Comment by kdipika** [comment]
i need the new data data2 as well to get added to the timeline

**Comment by madebydavid** [comment]
@kdipika - Scroll the timeline along with your mouse - the data has been added to the timeline - it is just not visible until you scroll to it.

**Comment by bradh** [comment]
@kdipika Your second jsfiddle is working for me, in that there are five items in the timeline.  Can you explain your problem further? If it works for you, can you close the issue?

**Comment by kdipika** [comment]
works fine
