### ISSUE TITLE
Timeline vertical scrollbar glitch with firefox

### ISSUE THREAD

**Issue by mikash** [almende/vis#3195]
Tested with Chrome 58 and Firefox 54 & 48 on Windows 10.

Effect is visible in f.ex.
http://visjs.org/examples/timeline/other/verticalScroll.html

If you grab the scrollbar and drag it to scroll, it jumps back and forth between new position and the starting position. 

Works correctly with Chrome.

**Comment by bradh** [comment]
Might be the same issue as #3100
