### ISSUE TITLE
Graph3D Aspect Ratio & Line Color

### ISSUE THREAD

**Issue by noahj96** [almende/vis#3196]
Hi,

I'm working on creating a 3D line from csv coordinate data copy and pasted from a source file that can handle touch interactions on a mobile device. Right now, I have the graph plotted beautifully but I have two main concerns.

1. The z-axis goes up to 500 while the x and y axes only go up to 50, and the plot does not preserve the aspect ratio in the z direction. The verticalRatio is already set to 1.0, and keepAspectRatio only preserves the x and y scaling. I have tried adjusting with the zMin and zMax with no luck. Is there a feature that enables preserving the aspect ratio for the 3rd axis?
2. Is there a way to change the color of the line feature or is dataColor for dot-color and dot-size? Thanks so much for any help.

P.S. here is the [working example on bl.ocks](https://bl.ocks.org/noahj96/cb200fa4a61302c6acd79562f8ec640a)

Best,
Noah

**Comment by wimrijnders** [comment]
Yay! A `Graph3d` issue! I'm going to have fun handling this. I'll get back to you ASAP.

**Comment by wimrijnders** [comment]
1. `verticalRatio` is independent of the x and y. It's just a factor multiplied to the z-values on display. There is no option available to keep the ratio for the z-axis as well; the best workable thing I can think of is to force the dimensions and ratio's in the options:

```
var options = {
...
  xMin: -50,
  xMax: 50,
  zMax: 500,
  verticalRatio: 500/100.0   // i.e. zMax/(xmax - xMin)
};
```

I'm not too happy about the display for this, though. It's always clipped somehow in the viewing area.

2. Yes, like this:

```
var options = {
...
  dataColor: {
    stroke: '#ff0000',
    strokeWidth: 5     // this works also, sets the width of the line
  }
};
```

**Comment by noahj96** [comment]
The first solution works great and isn't clipped at all in my view! Thanks so much. I'm going to follow up your answer to my second question with another question:

Is there a way to color different parts of the line based on their coordinates? It appears that this would require creating as many data sets as there are colors and specifying the color in the options variable, but I am unsure whether multiple data sets can be plotted at once. Thanks again for all your help!

-Noah

**Comment by wimrijnders** [comment]
Sorry no, line graphs are always one color.

And that multi-line thing *sigh*, that's the thing that brought me here to `vis.js` in the first place. If there's anything I want to achieve, it's multiple graphs within a `graph3d` view. It's a long road to get that to work. Sorry, not there yet.

**Comment by noahj96** [comment]
No problem! Can this be achieved using maybe a 3d scatter rather than a line?

**Comment by wimrijnders** [comment]
You *could* do something with `dot-color`, that allows you to add a field to the dataset items that changes the color.

**Comment by noahj96** [comment]
Is there a way to modify the dot-color in a loop or would that also need to be specified in the options variable, meaning I would run into the same problem of needing to plot multiple data sets?

**Comment by wimrijnders** [comment]
Not sure what you're trying achieve here?

If you mean, iterate over the `DataSet` instance and add a color field to the items, sure you can do that. Otherwise, I ask you to be a bit more specific about your intention.

**Comment by noahj96** [comment]
Right now I would like the the model to be split into three different areas, as it is supposed to model a spine. Is there a way that I can iterate over the data set and specify the color based on the data parameters, or must all the scatter points be the same color?

**Comment by wimrijnders** [comment]
Hokay, so, assuming you have `style: 'dot-color'` set, do something like this before initializing the graph instance:

```js
var count = 0;
var value = 0;
data.forEach(function(item) {
  // After a given series of points, change the style value
  if (count % 300 == 0) {
    value = (value + 100) % 256;
  }

  item.style = value;    // This field is used to display with a given color from a palette
  data.update(item);
  count++;
});

```

**Comment by noahj96** [comment]
Thanks!

**Comment by wimrijnders** [comment]
I notice that changing the graph type to `dot-color` affects the drawing performance, due to the large number of points. The drawing speed improves when I set `dotSizeRatio` smaller, e.g. `0.0001`. It also looks more like a line now:

![download 2](https://user-images.githubusercontent.com/769037/27467144-05e0aa80-57e0-11e7-97d1-0248213c4f7a.png)

**Comment by wimrijnders** [comment]
@noahj96 If you're happy with the outcome of the handling of this issue, please close it.
