### ISSUE TITLE
Selection area to select many nodes - "mousemove" and "dragging" does not work with the left button

### ISSUE THREAD

**Issue by amullier** [almende/vis#3212]
Hi !
I want to create the same functionnality as this jsbin (http://jsfiddle.net/kbj54bas/ in #977) but with the left button.
The "mousemove" js event seems to work only with the right button. And the "dragging" event does not work when the dragView is false.
Can you suggest me a solution ?

**Comment by wimrijnders** [comment]
The following changes are needed to make this work:

- Upgrade the `vis.js` used to version `4.20.0`, i.e. most recent. `v4.8.1` is _really_ old.
- Mouse events need to be propagated from `hammer.js` to make this work. Currently they are blocked in `lib/module/hammer.js`:

```js
  module.exports = propagating(Hammer, {
    preventDefault: 'mouse'             // <== this needs to go!
  });
```

There is actually an issue related to that line: #2525. It appears that disabling it also solves that issue.

- `mousedown` and `mouseup` use vis-supplied event handlers, which have their own events. The original even is part of this. So, in the code, the button selection will be:

```
  if (e.originalEvent.button == 0) { 
...
  }
```
 
- Note in previous example code, the button number has been changed to zero, for left button.

-----

Tried this out and, in fact, I'm quite amazed at how well it works. Nice!

One thing I noticed, is that dragging the selection area only works if there is no node movement at all. While playing with it, I realized that this is actually a good feature.

OK, so this is not so hard to get working, but it _will_ need a change in `vis.js`. If you are up to it, you can path it yourself with the above instructions. I'll make a demo when I can find the time.

**Comment by wimrijnders** [comment]
@amullier Can you tell me how you found that demo? Was it connected to an issue here?

**Comment by amullier** [comment]
I change the line from the `hammer.js` file like you write in your last post in #2525 and it works !
Thanks !

**Comment by wimrijnders** [comment]
So we are done? If you're satisfied with the result, then please close the issue.
