### ISSUE TITLE
How do i set background colour of the time-axis where data is present

### ISSUE THREAD

**Issue by SaloniDesai** [almende/vis#3214]
I am implementing a timeline graph using vis.js. I want to highlight the time axis where data is present.
if I apply css style to .vis-time-axis .vis-foreground entire time axis is highlighted. Is it possible to highlight the time axis dynamically(only month,day,year which has data)?
![image](https://user-images.githubusercontent.com/6766619/27660986-8ad04eea-5c26-11e7-9c3f-545d5392aa23.png)

**Comment by bradh** [comment]
You could calculate this yourself by looking over the dataset. There is nothing in vis.js timeline that does this for you. I would note that what highlighting is needed depends on your expectations / business requirements (e.g. June 17 has data, so highlighting the month might or might not be what you need).
