### ISSUE TITLE
edges.font background does not honor vadjust value

### ISSUE THREAD

**Issue by dheerajbapat** [almende/vis#3215]
For edge label if we add background with edges.font.background and use edges.font.vadjust to vertically align label, then only text will be moved as per vadjust value, background does not move.
`edges.font = {
  label: '8',
  vadjust: 15,
  background: 'red'
};`

![image](https://user-images.githubusercontent.com/26622503/27677849-ad4f7cca-5cd0-11e7-8461-96003b0d61e9.png)

**Comment by wimrijnders** [comment]
That is the weirdest thing. Will look at it as soon as I have the opportunity.

**Comment by wimrijnders** [comment]
Confirmed. It happens with the node labels as well.

![download 4](https://user-images.githubusercontent.com/769037/27780367-cb5bfc02-5fc8-11e7-8e86-24b71de50feb.png)

However, I'm not convinced that this is a real bug. From the docs:

Name | Type | Default | Description
--- | --- | --- | ---
font.vadjust 	| String |	0 |	A font-specific correction to the vertical positioning of the base font in the label text. (Positive is down.)

Option `vadjust` is supposed to be used as a *correction to the font alignment* in the label, not to move the label as a whole. This just happens to be a pretty big adjustment to the alignment.

As such, the code is behaving as expected. I don't want to change this. The workaround is, of course, not to set `vadjust`.

What is it that you want to achieve here?

**Comment by wimrijnders** [comment]
@dheerajbapat What is it that you want to achieve here? Is there some feature that you require?

**Comment by dheerajbapat** [comment]
Thanks for looking into this. This is a cosmetic thing. I am using arrows as circle shape in middle for certain kind of edges. So I wan't to place edge label below or above the circle; and to highlight more I wanted to put a background for edge label, then saw it does not move with label. As of now I just removed background for label.

**Comment by wimrijnders** [comment]
OK. Since you have a fix, I hope it's OK if I close the issue (feel free to reopen).

As a parting word, if a circle with text outside is what you want, you could consider the `dot` style node. This places the label below the node.
