### ISSUE TITLE
Storing and redrawing the network with fixed co-ordinates

### ISSUE THREAD

**Issue by ptanmay** [almende/vis#3216]
Hi,

I'm using Network component of VisJS.

I'm trying to store the positions of all the nodes of the current network into a file and later render the network nodes at the exact co-ordinates.
The problem I'm facing while redrawing the network is that the nodes are maintaining their relative positions, but the nodes are not being rendered at the exact position they were before.

I need to make sure that the nodes will be rendered at the exact position that I had stored previously. How can I achieve this?

**Comment by ptanmay** [comment]
These are the options I've used.

options = {
     autoResize: false,
     manipulation: {
          enabled: false
    },
    interaction: {
      zoomView: false
    },
    nodes: {
      fixed: {
        x:false,
        y:false
      }
    },
    physics: {
      enabled: false
    }
    };

**Comment by ptanmay** [comment]
My observation so far has been that the network is automatically zooming out as I increase the separation between nodes, and so even if the co-ordinates are same, the position of the nodes on the screen is different.

So rephrasing my question, "Is it possible to disable to automatic zoom-out of the network?"

**Comment by cityy** [comment]
How are you saving your positions for reloading? I'm using `network.getPositions()` to retrive canvas x and y of all nodes and then posting that to my database. When redrawing the network I just loop through nodes from the database which have canvas x and y set as described. Never had problems with positions not being maintained.

**Comment by ptanmay** [comment]
I'm also saving positions using `network.getPositions()`.
The problem I'm facing is that when I create the network using the same co-ordinates, the whole network is being re-centered in the canvas while the co-ordinates remain the same. That is, the shape of the network is persisted, but the network is moving to a different location on screen.

After I render the network using the saved co-ordinates, the network position on the screen is the same all the time. But the network position on the screen is not the same as I saved, the network is at a different position than what I saved.

**Comment by wimrijnders** [comment]
I've been trying to reproduce this without much success. If I reload a test network, the coordinates are restored exactly and I see no difference.

Is it perhaps the case that you move the network as whole and/or change the zoom factor? In that case, some way to restore the view position and zoom factor is required. I looked in the code, and I'm sorry to say that these can not be preset. This is going to require a code change to make it work.

If previous is not the case, then I don't have a clear picture of what is happening. Could you then prepare a demo on `jsfiddle` or suchlike, to illustrate the issue?

----

To answer you questions:

> "Is it possible to disable to automatic zoom-out of the network?"

No.

> "Is it possible to fix the area in which the network is to be rendered?"

No.

The best advice I can give you is to use the default zoom and view position always for display after restore. I see you took precautions already in the options with `interaction.zoomView: false`.

**Comment by cityy** [comment]
> The problem I'm facing is that when I create the network using the same co-ordinates, the whole network is being re-centered in the canvas while the co-ordinates remain the same. 

So your problem is not the nodes' positioning but the view options of the canvas if I understand it right. What you want to do is save network.getScale() and network.getViewPosition() before calling network.redraw() and then use the `beforeDrawing` event to resetup the previous view using `network.moveTo()`.
Don't think the issue you are facing is options related. If I still didn't get it maybe you could provide a short screen capture video showing the issue.

**Comment by ptanmay** [comment]
Thanks a lot @cityy ! That was exactly what I was looking for!!
