### ISSUE TITLE
Visjs custom timebar gets dragged outside of the scale

### ISSUE THREAD

**Issue by kdipika** [almende/vis#3231]
Hi,

I Added a custom time bar to vis timeline. My timeline has a max and min scale.But I am able to drag the custom time bar outside of the scale and as a result the bar gets lost.Need to refresh the page to see the custom time bar again.
Is there a way to limit the drag of custom time bar within the timeline scale limit?

Please replicate the scenario using this fiddle
http://jsfiddle.net/e7uodse2/1255/

**Comment by bradh** [comment]
You'd need to take the `onMove` event and cancel the move (http://visjs.org/docs/timeline/#Editing_Items) if its outside the valid bounds. If you just want to stop at the ends, `onMoving` will probably be better. See http://visjs.org/examples/timeline/editing/editingItemsCallbacks.html for an example.

**Comment by kdipika** [comment]
OnMove and onMoving gets called only for items move. They do not get called for custom time bar movement.
Can you please re open the issue since this is not solved.

**Comment by bradh** [comment]
Can you create a jsbin / jsfiddle that demonstrates the problem (i.e. no callback)

**Comment by bradh** [comment]
I see you already created a duplicate at #3238. Will followup there.
