### ISSUE TITLE
Vis timeline - Custom zoom in/out options

### ISSUE THREAD

**Issue by kdipika** [almende/vis#3232]
Currently the timeline has an inbuilt zoom option which is very good. But people don't get it right away by seeing that there is a zoom in there. Also the zoom is not very easy without a mouse.

My question is , is there a way to add custom controls like (+/-) to zoom in zoom out manually? If so please re direct me how to do it?

Here is an example to see the current zoom implementation in timeline
http://jsfiddle.net/e7uodse2/1255/

**Comment by bradh** [comment]
There is no custom controls in the timeline code like that, but adding a button to your layout that invokes the `zoomIn` or `zoomOut` methods (see http://visjs.org/docs/timeline/#Methods) should be OK (Note: I'm not going to write that for you). In the end it doesn't really matter how you invoke them, so do whatever makes sense for your UI needs.
