### ISSUE TITLE
Multicolored edges

### ISSUE THREAD

**Issue by 0blu** [almende/vis#3235]
It would be nice to support multiple colors per edge, so we can change the color halfway through.

I even made a small commit but I used bezier-js in my example, maybe someone who knows how to calculate a part of a bezier curve could implement this into viz.
The code is also not tested and **definitely could cause errors**. 

http://htmlpreview.github.io/?https://github.com/0blu/vis/blob/master/examples/network/edgeStyles/doubleColors.html

Side note:
Would also be cool for https://github.com/almende/vis/issues/335

**Comment by bradh** [comment]
I don't think this is a good fit for vis.js, and since its possible (as shown in your example, using aggregation) to do it without making internal changes, I don't see this going ahead. If I've missed something, please reopen with additional details.

**Comment by 0blu** [comment]
> I don't think this is a good fit for vis.js

Unfortunately I don't know what the direction of this project should be.

But I actually had to make "internal changes" (see: https://github.com/0blu/vis/commit/4ae663d0b15ccedd630264462e3165f331940b7a)
.. or what did you mean with "aggregation".

It was just an idea, which I am using in my current project.
