### ISSUE TITLE
Node never stop moving

### ISSUE THREAD

**Issue by msho** [almende/vis#3240]
Hey!

im using network graphs, 
Im using this userAgent Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) aqwirex-ng Safari/538.1, but it happens on latest chrome version as well

here is the example of the bug - http://jsfiddle.net/e7uodse2/1260/
i've tried to make it run as fast as i could. but it is still takes some time to build. (about 8k nodes)

as you can see the edges keep moving and does not stop...
it takes a huge time to build if we add we add improveLayout flag. 

added a text version of js if the jsfiddle delete the my code ...

[vis_bug.txt](https://github.com/almende/vis/files/1127644/vis_bug.txt)

thanks much for the help
NewBee

**Comment by wimrijnders** [comment]
Ah yes, the *restless node syndrome*. It's slowly becoming an acquaintance.

Duplicate of #3020.

This is emergent behavior, about which can't be done much. As with the mentioned request, the best you can do is disable physics after stabilization.

----
Disable physics with `physics.enabled: false` and just do following after init of `network`:

```
network.stabilize(2000);
```

**Comment by wimrijnders** [comment]
> it takes a huge time to build if we add we add improveLayout flag.

The actual time goes into the positioning of the nodes, the building of the network is instantaneous by comparison. I realize that from your viewpoint this is nitpicking.

You are probably referring to this console message:

>This network could not be positioned by this version of the improved layout algorithm. Please disable improvedLayout for better performance.

As a note: `improvedLayout` doesn't run for big networks like this. What runs is a test to see if any improvement can be made with this particular algorithm (called `Kamada Kawai`). So what you're saving on is the time to run the test.

**Comment by wimrijnders** [comment]
Your network is gorgeous by the way:
![download 5](https://user-images.githubusercontent.com/769037/27921896-8a0ee0f8-6279-11e7-8aa9-4fddeae618ff.png)

I just love big networks like these. I'm itching to optimize to make these beasts more performant.

**Comment by msho** [comment]
@wimrijnders  thanks much!
My network is a lot bigger then that. I just made a pilot with little data. 
Also the data would always change. Can you give me advice for how to make it run faster and still look good (node does not overlap each other)? 
Thanks for the disable the physics advice :).

**Comment by wimrijnders** [comment]
> My network is a lot bigger then that. I just made a pilot with little data.

I stand in awe.

> Can you give me advice for how to make it run faster and still look good

That's such a hard question. I've been accumulating empirical observations during usage to increase the performance, such as:

- Doing stabilization is orders of magnitude faster than displaying the network
- Edge type `dynamic` is more computing intensive than the rest
- The `barnesHut` solver is way slower than the other ones
- reducing 'timestep'  in `physics` stresses out the processor less; it also makes for less nervous networks

The thing is that your network is doing these things already. There is  not much more that I can offer you.

These are more guidelines than hard proof. I have yet to find the Golden Bullet for performance increase of big networks. Like I said, I'd love to dive in deep to see what I can optimize.

**Comment by msho** [comment]
OK @wimrijnders thanks again for fast reply and nice words. 
Ill keep track for new performance releases and fixing the restless node issue, I'm sure you guys would find a solution!

**Comment by spnzig** [comment]
@wimrijnders I am facing a similar issue. Can you please tell me where I need to include  `Set option physics.enabled: false and do following after initialization of network: network.stabilize(2000);`
