### ISSUE TITLE
Using vis timeline without dates

### ISSUE THREAD

**Issue by marinah1** [almende/vis#3242]
We would like to use vis for time, but in non-date format and on a smaller time segments. We want simply to have time in base ten digits for number of microseconds (for example) that have elapsed (one scale). Zooming in and out would be simply changing the base ten scale. Any tips for how we could do this would be appreciated.

**Comment by bradh** [comment]
This should be do-able with a custom label function. See http://visjs.org/docs/timeline/#Configuration_Options and note that `format` has a function variant. From the docs:

> You can also use a function format for each label. The function accepts as arguments the date, scale and step in that order, and expects to return a string for the label. 

 There is an example at http://visjs.org/examples/timeline/other/functionLabelFormats.html that is visually quite different to your request, but the implementation approach should be very similar.
