### ISSUE TITLE
How to set the length of edges?

### ISSUE THREAD

**Issue by jochemstoel** [almende/vis#3243]
I require nodes to be further apart, a longer edge (line) between them.  I read through the documentation and tried console logging some properties but I can not find the property of the options object that sets this value.

Is this implemented currently?

**Comment by jochemstoel** [comment]
I'm sorry I just found the answer here. My bad.
https://github.com/almende/vis/issues/3217

**Comment by wimrijnders** [comment]
My favorite kind of issue: one that solves itself in one minute :grinning:. Cheers!
