### ISSUE TITLE
Multiple edges between cluster and connected nodes

### ISSUE THREAD

**Issue by gubr123** [almende/vis#3245]
As @wimrijnders said:

> The cluster edge maintains a direct relation with the one single edge it is replacing. This does not work here because multiple edges need to be replaced with the cluster edge.

Simply, the issue is that when two nodes are connected with more than one edge, the edges remain when clustering, instead of creating a 'cluster edge'.

Here is an example of the issue:

![image](https://user-images.githubusercontent.com/10476634/27992549-b73f2074-649f-11e7-9a5c-6c80e725fce1.png)

Thats I want it to look - (but I want to leave physics enabled):

![image](https://user-images.githubusercontent.com/10476634/27320294-2e25247e-559e-11e7-889f-8757c0dd76de.png)

If I set the physics to false, so all the edges are lapping and it seems like there is one edge between the cluster and the node.

**Comment by wimrijnders** [comment]
Discussion moved from #3187. First post edited with more info from said issue.
Here is [the demo](http://jsfiddle.net/9m433scr/).

----
Additional from @gubr123 previous discussion:

The problem I'm ecountering with clustering is that the nodes are clustered but the edges aren't. So It causes something like this:

![image](https://user-images.githubusercontent.com/10476634/27291299-830738aa-5518-11e7-9874-b03d72146f25.png)

I've seen that disabling physics might help, but I don't want to affect the whole network. Is there any option to replace all the edges in one edge?

**Comment by wimrijnders** [comment]
I've started work on fixing this; I'll continue with this after my final exam on Monday (last minute stress!)

**Comment by gubr123** [comment]
@wimrijnders Good luck!

**Comment by nanialves** [comment]
I want to cluster multiple edges but not with clustered node(s). Is there a solution yet?


I asked [here](https://stackoverflow.com/questions/49626545/cluster-multiple-edges-between-two-nodes) if anyone can help. Thanks.
