### ISSUE TITLE
showMajorLabels to false and scale set to 'week' creates vertical lines display bug

### ISSUE THREAD

**Issue by Franzyval** [almende/vis#3246]
Hello and first, thanks for this really useful tool :),

I think i have identified a bug: when setting both options showMajorLabels to false and timeAxis to  {  	scale: 'week',   	step: 1    },  there is a display bug for vertical lines where months were supposed to be. this seems to just be a display bug.

on version 4.20.0 of the Timeline

Here you can see that the div for week 22 appears two times
![bug-timeline](https://user-images.githubusercontent.com/26770818/28010174-4e75ac74-655e-11e7-9bb1-3d5b7a7bc48a.png)

here is sample code to reproduce : 
var container = document.getElementById('example-timeline');

// Create a DataSet with data 
var data = new vis.DataSet([{
    id: 1,
    content: 'First event',
    start: '2014-08-01'
}, {
    id: 2,
    content: 'Pi and Mash',
    start: '2014-08-08'
}, {
    id: 3,
    content: 'Wikimania',
    start: '2014-08-08',
    end: '2014-08-10'
}, {
    id: 4,
    content: 'Something else',
    start: '2014-08-20'
}, {
    id: 5,
    content: 'Summer bank holiday',
    start: '2014-08-25'
}]);

// Configuration for the Timeline as JSON object
var options = {
    showMajorLabels: false,
    timeAxis: {
    	scale: 'week',
    	step: 1
    },
    width: '100%',
    locale:'fr',
    editable: true,
    margin: {
        item: 20
    }
};

// Create a Timeline
var timeline = new vis.Timeline(container, data, options);

Thanks !
Regards

**Comment by bradh** [comment]
Can you try with 4.20.1? If it still happens, can you create a jsbin or jsfiddle that shows the problem?

**Comment by Franzyval** [comment]
Hi, thanks, for your interest in this problem, 

https://jsfiddle.net/e7uodse2/1269/
this jsFiddle is using vis 4.20.1, error still occurs. Look for week 27 or week 40

**Comment by marcortw** [comment]
Nice to see that people are using the week scale feature! I only saw this issue now and I am not sure if there's a misunderstanding here. The additional vertical line at the month's start is a feature, not a bug. See my comment in https://github.com/almende/vis/pull/3009#issuecomment-297300219 . @yotamberk, do you remember this discussion?

Additionally, this fix seems to break the weekStyling.html example:

![image](https://user-images.githubusercontent.com/6734691/29243001-a09b9260-7f95-11e7-84c1-6bcb83e6d5a1.png)

**Comment by yotamberk** [comment]
@marcortw egh... You're right... The bug in the example is problematic...
I forgot that discussion but I do agree with @Franzyval that the extra line looks funny. 
@Franzyval Can you please fix the problem in the example?

**Comment by marcortw** [comment]
Yes, I agree that the extra line looks funny in the case when the major labels are not used. As it looks like, this fix keeps the extra line when major labels are used, which seems to be a good approach. So if the label bug is fixed, then this seems to be fine.

There's another issue visible in the above screenshot, which I was already aware of: If major labels are used, the following div overlaps the previous week number (here the cut off undefin.. string). This also happens for week numbers sometimes. Should I open another issue for that? Tbh, I wasn't that keen on fixing it initially because the whole TimeStep thing seems to be a bit too unflexible for these kind of things.

**Comment by yotamberk** [comment]
The overlap is due to the div of the major being after the minor label and with a background (hence the overlay), Not much can be done with that.
