### ISSUE TITLE
Customize manipulation bar in network graph with buttons and actions

### ISSUE THREAD

**Issue by kandangit** [almende/vis#3257]
Is it possible to be able to customize the network graph with additional buttons? (Sorry if there is already a solution implemented for this).

I have a network graph with requirements to:

1 add button to export graph to image
2 new button used to drag the edges (as current edit edge functionality does) and use existing edit edge button to call a different function (call back to edit in a popup the edge label and properties).

Don´t see an straightforward  way to customize the bar with additional actions
For example, for the button to export the graph to an image , I am adding a button which is displayed outside the canvas (guess otherwise can be positioned next to the toolbar with CSS, etc)

**Comment by wimrijnders** [comment]
I'm afraid it is not trivially possible to add buttons to the manipulation bar. Aside from the fact that adding buttons is not exposed in the `Network` API, the buttons in the bar are added and removed dynamically, which makes it hard to add custom buttons.

The best advice I can give you here, is to create your own overlay which you can manage yourself. HTH.

**Comment by kandangit** [comment]
Thank you

**Comment by wimrijnders** [comment]
Please close the issue if this answer is sufficient.
