### ISSUE TITLE
Can't output to pdf with wkhtmltopdf

### ISSUE THREAD

**Issue by LiangJ** [almende/vis#3259]
I'm exportting html to pdf with wkhtmltopdf.
But timeline of page can't display in pdf.

**Comment by bradh** [comment]
Hi. To help us understand this problem could you add some more detail? For example, can you explain why you think this is a problem with vis.js? Can you create a reproduction scenario with jsbin or jsfiddle? Do you see no output at all, or is just part of the timeline (say the background) missing?

**Comment by LiangJ** [comment]
>  For example, can you explain why you think this is a problem with vis.js

Sorry,I'm really not sure. Only doubt.
I have exported other js library with wkhtmltopdf, result ok.
ex:
D3 --> https://bl.ocks.org/mbostock/4061502
Google Chart --> https://developers.google.com/chart/

> Can you create a reproduction scenario with jsbin or jsfiddle?

Firest:
I have only downloaded vis.js(https://github.com/almende/vis/archive/v4.20.0.zip).

Next:
 Run it in xampp.
http://127.0.0.1/vis-4.20.0/examples/timeline/basicUsage.html

![c](https://user-images.githubusercontent.com/2550918/28237421-a9849f5a-6971-11e7-9aeb-b1f1032bc86a.png)

Last:
Exported pdf with wkhtmltopdf.
![b](https://user-images.githubusercontent.com/2550918/28237405-40427314-6971-11e7-96ae-fc0ceb924349.png)

> Do you see no output at all, or is just part of the timeline (say the background) missing?

no output at all
![a](https://user-images.githubusercontent.com/2550918/28237390-9e992ab2-6970-11e7-8693-f86cd746ed8e.png)

**Comment by bradh** [comment]
I do see this (on linux it shows a box where the timeline goes, but no inner divs). Oddly, the wkhtmltoimage tool does render OK. Possibly that could be a workaround.

**Comment by LiangJ** [comment]
I have run wkhtmltoimage in win7, no render too.
![c](https://user-images.githubusercontent.com/2550918/28237630-6744384e-6976-11e7-9c69-c31cd9e64174.png)

Result(a.png):
![a](https://user-images.githubusercontent.com/2550918/28237634-763612e6-6976-11e7-9a7e-1586bda8034e.png)

> Possibly that could be a workaround.
Sorry, Didn't understand.
If need export pdf, is there any way to?

**Comment by bradh** [comment]
You could try printing using a browser. Other than that, I don't know where the problem is.

**Comment by LiangJ** [comment]
I have exported pdf using a browser, but have some problem.
puzzled!

**Comment by LiangJ** [comment]
@bradh
Is there any way to show timeline in box(canvas)?
thanks

**Comment by bradh** [comment]
I don't know. As I said - it worked for me with wkhtmltoimage on Linux.

**Comment by LiangJ** [comment]
I think that have a relationship with this warning.

![b](https://user-images.githubusercontent.com/2550918/28357772-18947016-6c9f-11e7-8305-4ddc12693428.png)

**Comment by LiangJ** [comment]
**conclusion:**



Debug with qtweb browser.(http://www.qtweb.net/)
QT haven't support bind method.



Polyfill:
https://cdn.polyfill.io/v2/polyfill.js?features=requestAnimationFrame,Function.prototype.bind&unknown=polyfill
