### ISSUE TITLE
Invalid date when using IE

### ISSUE THREAD

**Issue by vettesem** [almende/vis#3273]
Version 4.20.0 Brower IE Edge 

An item's start time and end time are entered in the format "YYYY-MM-DD HH:mm:ss". This works for Chrome but in IE there is an issue with the calculation where an Invalid Date error is thrown. I have attached an image showing the input value stored in itemsData and the value computed from that in itemSet.items.data. You can still see the correct input value in itemSet when you look at itemSet.itemsData.data.

![ie_invaliddate1](https://user-images.githubusercontent.com/8878664/28370719-f9b9b204-6c68-11e7-9211-5d2a0450b63e.png)
![ie_invaliddate2](https://user-images.githubusercontent.com/8878664/28370732-009baafa-6c69-11e7-98dc-aeb119ad6bbe.png)

**Comment by vettesem** [comment]
Also, possibly related. The values for timeline.range.start and timeline.range.end do not match up between IE and Chrome. Accessing the same database for timeline.range.end values I receive "1500691809808" for IE and "1500492570000" for Chrome.

**Comment by vettesem** [comment]
Non-issue. Resolved by formatting time into ISO-8601.

**Comment by bradh** [comment]
Indeed - you have to use a format valid for the browser, which is best approximated by ISODate.
