### ISSUE TITLE
Possibility to pre-set clusters like nodes and edges on init by using data.

### ISSUE THREAD

**Issue by AndrewMut** [almende/vis#3279]
Would be good to have possibility to pre-set clusters as nodes and edges. I've implements clustering into my app and trying to save it state, but can't handle clusters to pre-set them. And then just hook them whan it's needed.

**Comment by wimrijnders** [comment]
OK, that idea has merit. It's no big deal to initialize the clusters on startup, but I don't think that's what you mean.

It's not too hard, though, to create a json structure from existing state and then later reload it, all with code external to `vis.js`, so I'm wondering what the reason is for following statement: 

> ... but can't handle clusters to pre-set them.

Would you ming elaborating on this? What are the problems you are running in to?

**Comment by wimrijnders** [comment]
Actually, I'm jumping the gun a bit here. What's your use case? What do you want to do with the clusters?

**Comment by AndrewMut** [comment]
Sorry for that english, but will try to explain what I want anyway =) It's not really a big deal to initialize culsters on sturtup and save json. But, I form state of the map on the run, each movement immediately going to API to make it possible for another user see the changes online.
 I made a system of parent-child nodes. When you creating a child-node it will have additional fields like:
    { 
CID: (random generated id),
children: [*id's of all its children*], 
parents: [*id's of all its parents], 
clusterID_*id of it's direct parent*: true, 
clusterID_*and here could be a lot of fields depends of how big is tree of child-nodes*: true
}

    When I right click on node and choose "collapse in to cluster", it's taking CID of particular node adding prefix "clusterID_" and collapsing all nodes with such clusterId_*number*: true - field.

    Due to the lib logic each time collapsing nodes in to cluster we creating new cluster obj with clusterNodeProperties.

    So my idea to keep somewhere in data alredy created cluster objects with unic id's to have possibility just call them without creating new object.

**Comment by AndrewMut** [comment]
And I want to customize
![screenshot capture - 2017-07-21 - 15-58-26](https://user-images.githubusercontent.com/29780771/28464369-8514fb40-6e2d-11e7-9801-47b49e50cc4d.png)
I have this context menu and I want to use it similar with clusters and save their state somewhere

**Comment by AndrewMut** [comment]
The only way I see to handle this right now to keep state of cluster somewhere in my memory and than just use clusterNodeProperties for creating similar cluster object with saved params

**Comment by wimrijnders** [comment]
OK. So in my view, this is an issue of persistence. You want to be able to store a network with clustering information outside of a `Network` instance, and then restore it later on with the same clustering information. Is this correct?

Interesting thought. It's not possible at the moment, of course. But I can image that there is an option per node that indicates it is in a cluster and that the cluster will be shown on initialization. The option would resemble `group` like this. Would this help you?

**Comment by AndrewMut** [comment]
Yup, that's right. Yes, was thought in the same way. Looks like for now I am going to keep few additioal rows in a node that indicates isClustecCollapsed(something like this) and each node will have additional object inside with settings for cluster if that cluster will be called from this node. Thank you for helping and ty for your advice =)

**Comment by wimrijnders** [comment]
I just had a silly thought: I made the comparison before with option `cluster`, why not use that field to assign the cluster to a node? It's a defined field and collapsing from a group is not hard to do. Or do you need more cluster info than just the name?

**Comment by AndrewMut** [comment]
Definitely more than just a name. What I am doing right now - copying the full node info from which will be collapsed tree in to cluster. So my cluster node should looks the same. Like this: clusterNodeProperties: $scope.selectedNodeFullParams. And what i've done just right now, add field "inCluster"  to a parent node and filling it in the moment of network.cluster(clusterOptionsByData). So on map init will be checking if any node have this field "true" and will be collapsing cluster and fill param of cluster with parent node info.

**Comment by AndrewMut** [comment]
And quick question is there any possibility to add custom code to the node, I'd like to show "+" icon near node if it's cluster collapsed and by clicking it open the cluster?

**Comment by wimrijnders** [comment]
Yes, there is, although you'll have to do a lot yourself. I'm too pooped right now to give you a decent example, will have a go at it tomorrow. But the key here is to add custom drawing elements to a node using event handlers `beforeDrawing()` and/or `afterDrawing()`.

**Comment by AndrewMut** [comment]
Thanks in advance, would be cool if you give me some example of that. But will try today by myself. And already solved problem with collecting data for clusters in my way =)

**Comment by wimrijnders** [comment]
I managed not to forget to give you some example code. The following draws a custom icon (circle with a '+' in it) for a given node.

```js
network.on("afterDrawing", function (ctx) {
  var radius = 10;

  var nodeId = 1;  // Just pick a node for testing
  var nodePosition = network.getPositions([nodeId]);
  var xIcon = nodePosition[nodeId].x + 3*radius;
  var yIcon = nodePosition[nodeId].y - 3*radius;

  ctx.strokeStyle = '#294475';
  ctx.lineWidth = 2;
  ctx.fillStyle = '#ffff00';
  ctx.circle(xIcon, yIcon, radius);
  ctx.fill();
  ctx.stroke();

  ctx.moveTo(xIcon, yIcon - radius/2);
  ctx.lineTo(xIcon, yIcon + radius/2);
  ctx.moveTo(xIcon - radius/2, yIcon);
  ctx.lineTo(xIcon + radius/2, yIcon);
  ctx.stroke();   
});
```

This is the drawing part. You will also need to make a click-handler.

**Comment by AndrewMut** [comment]
@wimrijnders I must thank You, that helped a lot.

**Comment by wimrijnders** [comment]
:+1: I hope you can now create a click event handler for the icon. Like I said, there's no support for it within `network` so you'll have to do most of the work yourself.

**Comment by AndrewMut** [comment]
@wimrijnders Thanks again, it was very helpful. If You interested to see the result i'll give a snapshot after done with handlers and all clustering stuff.

**Comment by wimrijnders** [comment]
@AndrewMut Sure, bring it on! I also thoroughly appreciate you comment in #3293. I'm very much of the impression that you're doing fine work.

**Comment by AndrewMut** [comment]
@wimrijnders , hey where did you disappear?
