### ISSUE TITLE
Nested Graph/ Meta Nodes

### ISSUE THREAD

**Issue by B04902047** [almende/vis#3283]
I wish to define meta-nodes by selecting an arbitrary group of nodes, which can be treated as a new node, connected with edges.
Similar functions are in Tulip, but as a node can be added to groups, it should be circled into different meta-nodes as well. (But for clearer layouts, maybe the conditions determining whether a node should be shown should be provided by users.)
Similar to the request #2139, it seems not to appear in recent grouping options.
![hierarchy_orion_meta_simple](https://user-images.githubusercontent.com/17583751/28530865-b41c04be-70c7-11e7-8759-65054c6b656c.png)

**Comment by wimrijnders** [comment]
I....stand aghast. It's going to be networks all the way down....

OK. Well. So, this isn't standard functionality of `Network`, and if I had any common sense in me, I would leave it at that.
*However*, I do see a way to make this work, by using separate `Network` instances and implanting the networks-within-nodes (for want of a better name) by use of custom drawing routines[1].

The question for you then becomes: how extreme do you want your hacking to be? Are you willing to go over the top?

----
[1] A consequence of this is that the networks-within-nodes will not be interactive.

**Comment by wimrijnders** [comment]
There is overlap with #2139, in the sense that nodes are visually grouped. However, this is *not* a duplicate.

**Comment by wimrijnders** [comment]
Is there still a reason to continue this issue? I would appreciate a response. If not, please close it.
