### ISSUE TITLE
[Network] Node still selected when other node is dragged

### ISSUE THREAD

**Issue by rjbriody** [almende/vis#3284]
browser: safari
OS: osx
version: 4.20.1

Steps:
- click node 1
- drag node 2
- dragEnd event is fired w/ both nodes, but should only contain node 2.

This is a tricky one to reproduce as it happens intermittently, so I don't have a demo to reproduce it.

**Comment by wimrijnders** [comment]
Ah, yes. This is more of a definition issue than anything else.

Two things here:

- drag does not select
- mouse events return the *selected* nodes by definition. See the [docs](http://visjs.org/docs/network/#Events)

So, formally, this is entirely correct. I understand how this might be confusing, but this behavior is exactly conform to how it is documented. I would really prefer to keep it as it is now.

**Comment by AndrewMut** [comment]
I handled that problem in that way: 
network.unselectAll();
network.selectNodes([params.nodes[0]]);

Hope that will help

**Comment by rjbriody** [comment]
@wimrijnders thank you for another speedy response! 

Things still get fishy in the following scenario:
* Click node 1. 
  * Node 1 is selected.
* Drag node 2
  * Only node 2 moves.
  * dragEnd event includes node 2. 
* (node 1 was never dragged/moved.)

Most of the time this is exactly what happens. However, sometimes node 1 is incorrectly dragged and also included in the dragEnd event, which seems like a bug. It's almost as if the network thinks I multi-selected node2, but in fact I did not.

> mouse events return the selected nodes by definition

This might be where things are getting confused. My impression is that this is false for the dragEnd event. The dragEnd event only includes the nodes being dragged, and this is independent of what nodes are selected. The docs don't specify this, but it's what happens most of the time.

In any case, the dragEnd event should always contain the same thing for the same sequence of events, but what I'm seeing is sporadic behavior.

**Comment by rjbriody** [comment]
Update: this is a little embarrassing given how long I've been using vis, but I never use it on a mobile device... I just remembered that holding a node will select it. This may be why it seems like node 2 is multi-selected in the scenario I described, and also why it happens so infrequently, i.e. only when the hesitation between click and drag is long enough to trigger a "long click".

I will investigate this. I just wanted to give you a heads up before you spent any more time on this right now.

**Comment by rjbriody** [comment]
Ok, I was able to confirm w/ my users that there was a significant hesitation between clicking and dragging, and that this was causing multiple nodes to be selected.

That definitely makes this issue invalid, and I apologize for all the noise.

I looked for a way to disable the mobile-style interactions, or at least a way to disable "longheld click triggers select" but didn't see any options for this. If someone knows of a way to do this, please let me know.

**Comment by wimrijnders** [comment]
@rjbriody Not a problem at all; thank *you* for taking the time to investigate further and for your candid reply.

Disabling "longheld click triggers select": actually, this is a good question. I'm going to investigate for a moment to see how make this work.
