### ISSUE TITLE
"Hammer.assign is not a function" in Ionic

### ISSUE THREAD

**Issue by badpenguin** [almende/vis#3292]
I'm trying to use vis network with Ionic.
I installed using npm, packages.json shows:
```
    "hammerjs": "^2.0.8",
    "vis": "^4.20.1",
```

Trying to run the minimal example from the doc:
```
import { vis } from 'vis';
[...]
var network = new vis.Network(container, this.data, this.options);
```

But i got this error:
```
Runtime Error
Hammer.assign is not a function
Stack
TypeError: Hammer.assign is not a function
    at propagating (http://localhost:8100/build/vendor.js:126104:16)
    at Object.__WEBPACK_AMD_DEFINE_ARRAY__ (http://localhost:8100/build/vendor.js:126036:22)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:112226:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:119935:20)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:112226:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:112258:24)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:112226:30)
    at http://localhost:8100/build/vendor.js:112246:18
    at http://localhost:8100/build/vendor.js:112249:10
    at webpackUniversalModuleDefinition (http://localhost:8100/build/vendor.js:112199:20)
Ionic Framework: 3.5.3
Ionic App Scripts: 2.0.2
Angular Core: 4.1.3
Angular Compiler CLI: 4.1.3
Node: 6.11.1
OS Platform: Linux 4.10
Navigator Platform: Linux x86_64
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/59.0.3071.109 Chrome/59.0.3071.109 Safari/537.36
```

**Comment by wimrijnders** [comment]
I am entirely not sure what is happening here. Would it be possible to make a minimal working code example?

**Comment by RossMJS** [comment]
Got this today too!

**Comment by wimrijnders** [comment]
I will admit that I'm not to sure as to how this may happen. The only thing that I can think of, it that in some way an old version of `hammerjs` is used in the build. Function `Hammer.assign` was introduced in `hammerjs v2.0.6`, so any previous version will throw the given error.

Is there any possibility on your side to check if an old version (i.e. before `v2.0.6`) is present on your system?

**Comment by wimrijnders** [comment]
Is there any possibility on your side to check if an old version (i.e. before v2.0.6) is present on your system?

**Comment by murraybauer** [comment]
I was having the same problem with ionic 3.  You need to import `hammerjs` aswell. 

`npm install vis hammerjs`

In your page/component:

`import 'hammerjs';
import { DataSet, Timeline } from 'vis';`

I also found if you just did a normal <script> tag in index.html like `<script src="assets/js/vis.js"></script> `. vis.js needs to be referenced before all other ionic script tags - pollyfill.js, vendor.js, main.js otherwise if you put it after you get the hammer error.  But with a normal script tag I didn't need to import hammer separately.

**Comment by badpenguin** [comment]
Sorry guys i'm not interested in using Ionic anymore, too many issues with other stuffs too. I will try it again with a normal angular cli project or react.

**Comment by Don-G** [comment]
For Whoever get stuck in this.

Make sure you initialize your data , edges and nodes in ionViewDidLoad() else you will get an error

**Comment by sebospc** [comment]
@Don-G I have the same issue, but I can't understand what you said, can you explain more?.
