### ISSUE TITLE
Getting long edge in hierarchy layout after few operations

### ISSUE THREAD

**Issue by dheerajbapat** [almende/vis#3298]
I am using hierarchical layout with preset levels and physics off.
After few clustering, declustering, hide and show nodes, some nodes appear very far. Which make network look like a long line.
I guess it happens when there is loop like (a -> b -> c -> a) or there are multiple edges between same nodes (a -> b, a -> b or b -> a, etc)
I tried fixing with options edgeMinimization, blockShifting, parentCentralization, but no luck.
Any other things I can try?
Can you please help me fix it?

![2017-07-26 21_07_23-8 2 4_topology](https://user-images.githubusercontent.com/26622503/28632924-af3b0b46-724f-11e7-837a-db7db7522be3.png)

**Comment by wimrijnders** [comment]
This sounds an awful lot like #1735, but that was fixed two releases ago (`4.20.0`). What version are you using? If not a recent one, please upgrade first.

**Comment by dheerajbapat** [comment]
Ah! My bad. I was using old version.
Upgraded and it is fine now.
Thanks for quick response!
