### ISSUE TITLE
The node revolves around its center

### ISSUE THREAD

**Issue by hackerxiaobai** [almende/vis#3300]

**Comment by wimrijnders** [comment]
It's a very poetic title, eagerly awaiting the next line.

But could you adjust the comment please, by removing the default text and placing your own?

**Comment by hackerxiaobai** [comment]
i want let the node revolves around its center,but i can not how to do,Do you offer an this API？ or what can i do? i am a student. i want to study the vis.js. can you help me? thank you very much.

**Comment by wimrijnders** [comment]
Err....is this for `network`?

It might be possible by calculating your own coordinates and updating them for the network. But there's no internal option for doing that, no.

And please adjust the first comment.

**Comment by hackerxiaobai** [comment]
yes, is network. i just want to the node revolves around itself center

**Comment by hackerxiaobai** [comment]
? ? ? I don't know what meaning of you say. can you offer a code to show me . i am a weak JS。I am sorry.

**Comment by wimrijnders** [comment]
There is no standard functionality for that. It might be possible, but it requires either code external to `vis`, or some serious hacking.

There might be some possibility of adding a rotational transform to the canvas element, but there's no guarantie that that will work. I don't have much options here, perhaps you can explain in more detail what you want to achieve.

> can you offer a code to show me

Well, no I can't, because I wouldn't know how to do it myself, sorry.

**Comment by hackerxiaobai** [comment]
ok. the code is very easy, i just want let the nodeID=1 revolves. now i know there is no properties support this , is right?

function draw2() {
  var nodes = new vis.DataSet([
      {id: 1, label: '1'},
      {id: 2, label: '2'},
      {id: 3, label: '3'},
  ]);

  var edges = new vis.DataSet([
      {id:1,from: 1, to: 2},
      {id:2,from: 2, to: 1},
      {id:3,from: 2, to: 3},
      {id:4,from: 3, to: 1}
  ]);

  var options = {};
  var container = document.getElementById('container');
  var graph = {nodes: nodes, edges: edges};
  var network = new vis.Network(container, graph, options);

network.on("afterDrawing", function (ctx)
  {
      var pos = network.getPositions([1]);
     // how write this code? let nodeid=1 revolves?
  });

**Comment by wimrijnders** [comment]
I honestly don't know. This is just not functionality of `network`. If you find out how to do it, please share.

**Comment by hackerxiaobai** [comment]
ok，thank you.

**Comment by hackerxiaobai** [comment]
thanks, you offer this tool, i have solve that problem, my method is put one <div> cover nodeid=1，then let the div revolves. perfect effect.

**Comment by wimrijnders** [comment]
I'm happy that you have a solution! However, I don't understand how you solved this. Can you give some example code? This might be a useful code snippet for everyone.

**Comment by hackerxiaobai** [comment]
## ok, my English is not good. I am sorry, The effect is this。
![gif](https://user-images.githubusercontent.com/22817243/28707981-fb1d79c8-73ac-11e7-9a7b-da76e947e608.gif)

## my code is this.
nodes.push({id: 'dev'  + '100', shape: 'image', image: DIR + '',size:50});
nodes.push({id: p_id, shape: 'image', image: DIR + 'dpleft-03.png',label:p_type, size:30});
edges.push({id: p_id,from: p_id, to: 'dev' + '100', length: 250});

var data = {
    nodes: nodes,
    edges: edges
  };
  var options = {
  	interaction: {
  		zoomView:false,
  		dragNodes:false,
  		dragView: false
  	},
  	nodes: {
      borderWidth: 2,
      size: 24,
      color: {
          border: '#3598DC',
          background: '#fff'
      },
      font: {
          color: '#FFFFFF',
          size: 16,
      },
      shapeProperties: {
          useBorderWithImage: false
      },
      scaling: {
          min: 10,
          max: 30
      },
      fixed: {
          x: false,
          y: false
      }
      // clickToUse: false
   },
    edges: {
      color: '#3598DC',
      shadow: true,
      length: 100,
      arrows: 'to',
      arrowStrikethrough: true,
      dashes: true,
      smooth: {
          "type": "dynamic",
          "forceDirection": "none",
          "roundness": 0.2
      }
    },

    layout: {
      randomSeed: 1,
      levelSeparation: 200,
      direction: "LR"
    },
    physics: {
      enabled: true
    }
  };
	var network = new vis.Network(container,data,options);
	
  
  network.on("afterDrawing", function (ctx)
  {
    var pos = network.getPositions(['dev'  + '100']);
    console.log(pos['dev'  + '100'].x,pos['dev'  + '100'].y)
    
//  console.log(network.canvasToDOM({x:pos['dev'  + '100'].x,y:pos['dev'  + '100'].y}))
    
    network.moveNode('dev'  + '100', 0,0);
//  network.moveNode(p_id, -200, 0)
  });
}

### finally, I use the div instead of  center node, and the div is a image, let the image run.

### I use this method is not good, but it has a perfect effect. you see the gif, can you offer a another method? thank you.

**Comment by wimrijnders** [comment]
This is....amazing. I tip my hat to you!

Your english may not be so good, but you have just displayed some kick-ass web skills.

> ... can you offer a another method?

No, I can't, because it's otherwise not possible what you made here. Is think your solution is the best possible for the given question.

Thank you for sharing! I believe that this approach will be useful for many others.
I nominate your work for **best hack of the year** 🏆 .

**Comment by brichbe** [comment]
@hackerxiaobai how did you implement those animated edges?

**Comment by hackerxiaobai** [comment]
I use this code。maybe you can use it too.

// Author: Edvin Eshagh
//
// Date: 6/22/2015
//
// Purpose:  animate traffic from one node to another.
//
// Usage: call *.animateTraffic method, passing array of edges to animate
//
// Example:
//
//       var myNodes = new vis.DataSet([  
//         {id: 1, label: 'Node 1'}, {id: 2, label: 'Node 2'}, {id: 3, label: 'Node 3'} ]);
//      
//       var myEdges = new vis.DataSet([
//           {id:1, from:1, to:2}, {id:2, from:2, to:1},
//           {id:3, from:2, to:3}, {id:4, from:3, to:1}]);
//       
//       var container = document.getElementById('mynetwork');
//       
//       var data = {nodes: myNodes, edges: myEdges};
//      
//       var options = {};
//      
//       var network = new vis.Network(container, data, options);
//      
//        function animate() {
//         network.animateTraffic([
//             {edge:1},
//             {edge:2, trafficSize:2}, 
//             {edge:3, trafficSize:5, isBackward: true}
//         ]);
//       }
 //
// Known issue: Does not render traffic animation "on top of" the edges in IE
//


vis.Network.prototype.animateTraffic =
    function(edgesTrafficList,
             onPreAnimationHandler, 
             onPreAnimateFrameHandler, 
             onPostAnimateFrameHandler, 
             onPostAnimationHandler) {

    var thisAnimator  = this;

    var trafficAnimator = {
        
        thisNetwork : this,    

        trafficCanvas : null,
        trafficCanvasCtx : null,
        trafficCanvasWidth : null,
        trafficCanvasHeight: null,

        reportedErrors : {},  // Helps to avoid reporting the same error in multiple setTimeout events
        
        edgesTrafficList : edgesTrafficList ,
    
        onPreAnimateFrame  : onPreAnimateFrameHandler,
        ontPostAnimateFrame: onPostAnimateFrameHandler,
        onPreAnimation : onPreAnimationHandler,
        onPostAnimation : onPostAnimationHandler,
        
        //////////////////////////////////////////////////////////////
        //
		// return object {edge, trafficSize, isBackward}
        parseEdgeTraffic : function (edgeTraffic) {
            var edge;
            if (edgeTraffic.edge) {
                edge =  edgeTraffic.edge.edgeType 
                    ? edgeTraffic.edge
                    : this.thisNetwork.body.edges[edgeTraffic.edge.id] 
                      || this.thisNetwork.body.edges[edgeTraffic.edge]
                    ;
            }
            else {
                edge = this.thisNetwork.body.edges[edgeTraffic];
            }
            
            return {
                edge: edge,
                trafficSize : edgeTraffic.trafficSize || 1,
                isBackward : edge && edgeTraffic.isBackward 
            };
        },

        //////////////////////////////////////////////////////////////
        //
        clearAnimationCanvas : function () {
            this.trafficCanvasCtx.save();
            this.trafficCanvasCtx.setTransform(1, 0, 0, 1, 0, 0);
            this.trafficCanvasCtx.clearRect(0,0, this.trafficCanvasWidth, this.trafficCanvasHeight);
            this.trafficCanvasCtx.restore();
        },

        //////////////////////////////////////////////////////////////
        //
        getNetworkTrafficCanvas : function() {

            this.trafficCanvas = this.thisNetwork.body
                .container.getElementsByClassName('networkTrafficCanvas')[0];
            
            if ( this.trafficCanvas == undefined) {
            
                var frame = this.thisNetwork.canvas.frame;
                this.trafficCanvas = document.createElement('canvas');
                this.trafficCanvas.className = 'networkTrafficCanvas';
                this.trafficCanvas.style.position = 'absolute';
                this.trafficCanvas.style.top = this.trafficCanvas.style.left = 0;
                this.trafficCanvas.style.zIndex = 1;
                this.trafficCanvas.style.pointerEvents='none';
                this.trafficCanvas.style.width = frame.style.width;
                this.trafficCanvas.style.height = frame.style.height;
                // ��������������
//              this.trafficCanvas.width = frame.canvas.width;
//              this.trafficCanvas.height = frame.canvas.height;
                
                //���������Լ��ӵģ��޸ĵ�bug
                this.trafficCanvas.width = frame.canvas.clientWidth;
                this.trafficCanvas.height = frame.canvas.clientHeight;
                
                frame.appendChild(this.trafficCanvas);
            }
            
            return this.trafficCanvas;
        },

        //////////////////////////////////////////////////////////////
        //
        animateFrame : function (offset, frameCounter) {

            this.clearAnimationCanvas();

            var maxOffset = .9;

            var reportedError = {};
            
            if (offset > maxOffset) {
                if (this.onPostAnimation) this.onPostAnimation(this.edgesTrafficList);
                return;
            }
            for(var i in this.edgesTrafficList) {

                var edgeTraffic = this.parseEdgeTraffic(this.edgesTrafficList[i]);
                
                if (!edgeTraffic.edge) {
                    if (!this.reportedErrors[this.edgesTrafficList[i]]) {
                        console.error ("No edge path defined: " , this.edgesTrafficList[i]);
                        this.reportedErrors[this.edgesTrafficList[i]] = true;
                    }
                    continue;
                }
                
                if (this.onPreAnimateFrameHandler 
                 && this.onPreAnimateFrameHandler(edgeTraffic,frameCounter) === false ) {
                    continue;
                }

  //              var s = edgeTraffic.edge.body.view.scale;
  //              var t = edgeTraffic.edge.body.view.translation;
                var p = edgeTraffic.edge.edgeType.getPoint(
                edgeTraffic.isBackward ? maxOffset - offset: offset);

//              this.trafficCanvasCtx.beginPath();
//                  this.trafficCanvasCtx.arc(p.x, p.y, parseInt(edgeTraffic.trafficSize)+1 || 2, 0, Math.PI*2, false);
//                  this.trafficCanvasCtx.lineWidth=1;
//                  this.trafficCanvasCtx.strokeStyle="#000";
//                  this.trafficCanvasCtx.fillStyle = "red";
//                  this.trafficCanvasCtx.fill();
//                  this.trafficCanvasCtx.stroke();
//              this.trafficCanvasCtx.closePath();
                
                
                this.trafficCanvasCtx.beginPath();
                    this.trafficCanvasCtx.arc(p.x, p.y, parseInt(edgeTraffic.trafficSize) || 1, 0, Math.PI*2, false);
                    this.trafficCanvasCtx.lineWidth=1;
                    this.trafficCanvasCtx.strokeWidth=4;
                    this.trafficCanvasCtx.strokeStyle="rgba(57,138,255,0.1)";
                    this.trafficCanvasCtx.fillStyle = "#1262e3";
                    this.trafficCanvasCtx.fill();
                    this.trafficCanvasCtx.stroke();
                this.trafficCanvasCtx.closePath();

                if (this.onPostAnimateFrame 
                 && this.onPostAnimateFrame(edgeTraffic,frameCounter) === false) {
                    if (this.onPostAnimation) this.onPostAnimation(this.edgesTrafficList);
                    return;
                }
                
            }

            setTimeout(this.animateFrame.bind(this), 10, offset+.01, frameCounter++);
        },


        //////////////////////////////////////////////////////////////
        //
        initalizeCanvasForEdgeAnimation : function () {

            this.reportedErrors = {};
        
            if (Object.prototype.toString.call( this.edgesTrafficList ) !== '[object Array]') {
                this.edgesTrafficList = [this.edgesTrafficList];
            }
            
            this.trafficCanvas = this.getNetworkTrafficCanvas();
            
            this.trafficCanvasCtx = this.trafficCanvas.getContext('2d');
            this.trafficCanvasWidth = this.trafficCanvasCtx.canvas.width;
            this.trafficCanvasHeight= this.trafficCanvasCtx.canvas.height;
            
            var edgeTraffic = this.parseEdgeTraffic(this.edgesTrafficList[0]);

            var s = this.thisNetwork.getScale();// edgeTraffic.edge.body.view.scale;
            var t = this.thisNetwork.body.view.translation; //edgeTraffic.edge.body.view.translation;
          
            this.trafficCanvasCtx.setTransform(1, 0, 0, 1, 0, 0);
            this.trafficCanvasCtx.translate(t.x, t.y);
            this.trafficCanvasCtx.scale(s, s);
/*
			if (!this.onPreAnimation)
            this.onPreAnimation = function(edgesTrafficList) {
                // remove the value from the source traffic
                for (var i in edgesTrafficList) {
                    edgeTraffic = this.parseEdgeTraffic(edgesTrafficList[i]);
                    if (!edgeTraffic.edge) {
                        continue;
                    }
                    var fromValue = edgeTraffic.edge.from.getValue()
                    if (parseFloat(fromValue)) {
                    
                        var newValue = fromValue +
                            (edgeTraffic.isBackward ? -1 : 1) * -edgeTraffic.trafficSize;
                    
                        this.thisNetwork.body.data.nodes
                            .update({id:edgeTraffic.edge.fromId, value:Math.max(0, newValue)});
                    }
                }
            };

            //////////////////////////////////////////////////////////////
            // 
			if (!this.onPostAnimation)
            this.onPostAnimation = function(edgesTrafficList) {
                // add the value from the source traffic to target
                for (var i in edgesTrafficList) {
                    edgeTraffic = this.parseEdgeTraffic(edgesTrafficList[i]);
                    if (!edgeTraffic.edge) {
                        continue;
                    }
                    var toValue = edgeTraffic.edge.to.getValue()
                    if (parseFloat(toValue)) {

                    var newValue = (toValue || 0) 
                        + (edgeTraffic.isBackward ? -1 : 1) * edgeTraffic.trafficSize;
                        
                    
                        this.thisNetwork.body.data.nodes
                            .update({id:edgeTraffic.edge.toId, value: newValue});
                    }
                }
            };
            */
        },

    };
    

    trafficAnimator.initalizeCanvasForEdgeAnimation();

    if (trafficAnimator.onPreAnimation 
     && trafficAnimator.onPreAnimation(trafficAnimator.edgesTrafficList) === false) return;

    trafficAnimator.animateFrame( 0.1 /*animationStartOffset*/, 0 /*frame*/);

};


vis.Network.prototype.animateTrafficOnPostAnimation = function(edgesTrafficList) {
	// add the value from the source traffic to target
	for (var i in edgesTrafficList) {
		edgeTraffic = this.parseEdgeTraffic(edgesTrafficList[i]);
		if (!edgeTraffic.edge) {
			continue;
		}
		var toValue = edgeTraffic.edge.to.getValue()
		if (parseFloat(toValue)) {

		var newValue = (toValue || 0) 
			+ (edgeTraffic.isBackward ? -1 : 1) * edgeTraffic.trafficSize;
			
		
			this.thisNetwork.body.data.nodes
				.update({id:edgeTraffic.edge.toId, value: newValue});
		}
	}
};

vis.Network.prototype.animateTrafficOnPreAnimation = function(edgesTrafficList) {
	// remove the value from the source traffic
	for (var i in edgesTrafficList) {
		edgeTraffic = this.parseEdgeTraffic(edgesTrafficList[i]);
		if (!edgeTraffic.edge) {
			continue;
		}
		var fromValue = edgeTraffic.edge.from.getValue()
		if (parseFloat(fromValue)) {
		
			var newValue = fromValue +
				(edgeTraffic.isBackward ? -1 : 1) * -edgeTraffic.trafficSize;
		
			this.thisNetwork.body.data.nodes
				.update({id:edgeTraffic.edge.fromId, value:Math.max(0, newValue)});
		}
	}
};

**Comment by wimrijnders** [comment]
Code for the edge animation is working. Nice!

With the node animation code,  I realized that the part I was interested in, namely the overlay of the image on the network, was missing.

I added the following to make it work. I hope this meets your approval:

CSS + HTML:
```html
<style>
#anim {
  position: absolute;
}
</style>

<div id='anim'>
  <img src="something_animating.gif">
</div>

```

JS:
```js
network.on("afterDrawing", function (ctx) {
  var pos = network.getPositions(['dev'  + '100']);
  var dom_coords = network.canvasToDOM({x:pos['dev'  + '100'].x,y:pos['dev'  + '100'].y});

  document.getElementById('anim').style.left = '' + dom_coords.x + 'px';
  document.getElementById('anim').style.top = '' + dom_coords.y + 'px';
});
```

In fact, this works much better than I would expect. @hackerxiaobai, thank you for your insights!

**Comment by hackerxiaobai** [comment]
yes. If it can help more people, I think it's worth it。i feel very happy. Thank you for your confirmation

**Comment by wimrijnders** [comment]
I'm thinking of adding a demo for `Network` to show how this overlay animation works. I'll make a point of adding credits  for you.

I have the feeling we're done here. I you agree, please close the issue.

**Comment by hackerxiaobai** [comment]
ok。thank you very much.

**Comment by wimrijnders** [comment]
Thank you too!

**Comment by vspinu** [comment]
> I'm thinking of adding a demo for Network to show how this overlay animation works

@wimrijnders. Just wondering if you had time to put something together in this regard. Even a very basic demo would be extremely useful for visjs-newbies like myself.

**Comment by wimrijnders** [comment]
In fact, I do have a working demo, with different ways to use HTML in overlays.
It's pretty rough, but I'll see if I can make this somehow available.

**Comment by wimrijnders** [comment]
[Here you go](http://jsbin.com/behagul/1/edit?html,output)

Notes:
- The HTML overlay will not resize on zooming
- You can drag the overlay way out of the view

And there's probably lots more issues here. But.....this is a working demo and I think enough to get you started.

**Comment by vspinu** [comment]
Great! This is exactly what I was looking for. Thanks a bunch!

**Comment by wimrijnders** [comment]
👍 Cheers!

**Comment by MadhuraKM** [comment]
I need node with child elements, each clickable. Tried HTML overlay option given above, it is rendering, but events/links added in the html are not working.  Can I get help on rendering responsive HTML overlay as node?
