### ISSUE TITLE
Documentation issue for joinCondition + clusterByConnection

### ISSUE THREAD

**Issue by CiaranG** [almende/vis#3316]
When clustering network nodes, the various cluster functions all take an options object which includes a `joinCondition` callback. This is documented (`docs/network`) as receiving a single `nodeOptions` parameter. That's true for most of the cluster functions, but not for `clusterByConnection` where it receives two - one for the parent node and one for the actual candidate (child) node.

**Comment by wimrijnders** [comment]
Confirmed. Well spotted. We'll put someone on this to fix it.
