### ISSUE TITLE
Hierarchy Problem : Network

### ISSUE THREAD

**Issue by mztikz** [almende/vis#3317]
Hey,

I am using the hierarchy option on click ,
Which means layout starts and standart barnhut and when a button is clicked I swap the layout to hierarchy,
The problem is that when ever the user click anywhere on the canvas it makes nodes pop to different layout (seems like another hierarchy seed) if I do like click on canvas and then reclick on the button that set the hierarchy options its doin the problem.
I had this problem before but It was fixed when I set the x,y of node to undefined before I updated them,
now its not working on the hierarchy , and also the nodes are very closed to each other

Any idea?

Thanks alot from advanced.

**Comment by mztikz** [comment]
P.S 
The onclick action doin the neighbours function ( Highlights neighbours)
Soo when ever I click on canvas somewhere I refresh the nodes..

**Comment by wimrijnders** [comment]
Yeah, that's how the hierarchy layout works at this moment. When you enable it, it does a full recalc of the layout. I don't think there's a way to disable that.

The other thing you're describing is slightly different. That's a resetting of all values due to an update.

Actually, I would appreciate an example to fully understand what your intention is.

**Comment by mztikz** [comment]
It will take me a while to re-write the code since my code is typescript-angular ,
Is video is good enough for you?

**Comment by wimrijnders** [comment]
Ah, ok. Well better than nothing. Sure, if you can easily make an animation of some kind, that would be ok.

**Comment by wimrijnders** [comment]
Could you explain why you want to change the layout to hierarchical during runtime?

**Comment by mztikz** [comment]
The graph that I built is used for analyze and sometimes different layouts brings different intells..

**Comment by wimrijnders** [comment]
OK. I really don't think there's a way to block the resetting of the layout due to the switch. But it's definitely a different layout so perhaps it can offer insights anyway?

What would you expect to happen on the layout reset?

**Comment by mztikz** [comment]
Is there a way to skype with you or anything? I will be able to show you more efficient what I mean

**Comment by wimrijnders** [comment]
Sorry, not doing that. I don't feel like doing that and anyhow I'm technically on vacation.

**Comment by mztikz** [comment]
![capture](https://user-images.githubusercontent.com/12010477/28753126-fa761fb6-7537-11e7-889d-812c9c0a7e6d.PNG)
![problem2](https://user-images.githubusercontent.com/12010477/28753127-fa780416-7537-11e7-93d1-8b655c7ce6df.PNG)

This 2 pictures are taken on the same scale same zoom same everything , When I click on the button below(1 of the 3 sets hierarchy) the graph appear on the right side,
when I click on the canvas it moves to left side and reordering a bit tighter..
I can provide each of the clicks code behind the scenes if it will help

**Comment by wimrijnders** [comment]
Wrt layout: It looks like a bunch of grapes, I'm assuming that's not your intention.

To correct this:
- For the non-hierarchical case, see if you can load the graph into the [physicsConfiguration](http://visjs.org/examples/network/physics/physicsConfiguration.html) example and twiddle the options.
- For the hierarchical case, you've got options `levelSpacing` and `nodeSeparation` to work with, under `layout.hierarchical`. `treeSpacing` might also be useful here.

As for the jump in the layout, I don't think there's much to be done here. The view is centered on the nodes, so it's the two-node cluster in this case which makes the big bunch go to the right.

You might have some success with using `Network.focus()`. If you can determine the top node in the big bunch, you can use that to ensure that the view is centered on that node. That would make it jump around a whole lot less.

If you want more feedback on this, supplying a nodes+options example would be useful. The 'clicks code' less so, but still there might be something to be learned from it.

HTH

**Comment by mztikz** [comment]
Thanks for respond , the none hierarchial is not a problem its not tweaking and switching places 
[graphproblem.txt](https://github.com/almende/vis/files/1186599/graphproblem.txt)


I have uploaded a file with the clicks events and the default options i use if i can provide anything else to help you I will be glad to provide it , 
I do not think the focus will help since the nodes are just jumping from side to side like trying to realocate themselves into a better positioning or reordering..

Thanks a lot from advanced.

**Comment by mztikz** [comment]
[nodeslinks.txt](https://github.com/almende/vis/files/1186684/nodeslinks.txt)
This are node and links samples

**Comment by wimrijnders** [comment]
This was a question of tweaking.

The problem with this network is the lone nodes. When switching to hierarchical with physics enabled, they get catapulted away and so make the overall view enormous. The trick to get them close is to increase the `centralGravity`.

I present you these options for the hierarchical view:

```js
  "physics": {
    "hierarchicalRepulsion": {
      "centralGravity": 5,
      "springLength": 75,
      "springConstant": 0.105,
      "nodeDistance": 325
    },
    "minVelocity": 0.75,
    "solver": "hierarchicalRepulsion"
  }
```
Add these to the return value of `this.saveAndLoadService.getHierarchyOptions()`. Note that physics should be enabled, so lose the `physics.enabled: false`in the original.

To stop the nodes from bouncing around on the switch to hierarchical, do this:

```js
this.network.setOptions(this.saveAndLoadService.getHierarchyOptions());  // Order changed
this.graphdataset.nodes.update(nodes);
this.network.stabilize(1000);  // Let physics find a stable configuration
```

In my tests, this looks much better:

![download](https://user-images.githubusercontent.com/769037/28909557-3bd95ea2-7829-11e7-9a62-f4101be106f2.png)

Note that the layout will be different every time.

HTH.

**Comment by wimrijnders** [comment]
And now, I'm off on vacation, so I probably won't be able to answer. If you're happy with the answer, please close the issue.
