### ISSUE TITLE
Incorrect display popup on hover (ng4)

### ISSUE THREAD

**Issue by JaroslavPrt** [almende/vis#3320]
Not sure if this is a bug, or because of the lack of integration with ng 2+ 
popup => in the lower left corner, just text

can i customize it by myself ?
![popup](https://user-images.githubusercontent.com/11339544/28756083-4b6af936-7570-11e7-990a-08a1fdaf45c8.PNG)

**Comment by wimrijnders** [comment]
The popup is the text 'Users: 25'?

Not sure what is happening here, but it could indeed be an interaction with an external component. What do you mean with `ng`? Sounds like something I should be knowing, but I don't, sorry.

Without further examples, I really can't tell what is happening here.

If you mean customizing the tooltip styling, sure. You can use full html in the following tag:

```js
options = {
  nodes: {
    title: "<div><b>Go</b> <h1>wild</h1> <i>here!</i></div>"
  }
}
```

Currently, this is string text. Next release, using DOM-elements for the tag will be enabled.

**Comment by JaroslavPrt** [comment]
ng means angular, 
and in pure js it likes this

![capture](https://user-images.githubusercontent.com/11339544/28762924-e28e5d7e-75c2-11e7-8f40-27e7786622d9.PNG)

**Comment by wimrijnders** [comment]
> ng means angular,...

TIL. I'll do my best to remember that.

> ... and in pure js on hover node it likes this

Is this the way that the tooltip  is displayed when `angular` is not used?

I'm afraid that my knowledge of angular is non-existent - I didn't even know its abbreviation. The best I can do is scan the issues here for something similar. Otherwise, I hope that someone else can help you here.

**Comment by AndrewMut** [comment]
@JaroslavPrt @wimrijnders Guys, I'll be in the office soon and try to replicate on my side. Will see may be figure out something

**Comment by JaroslavPrt** [comment]
fixed!
Copied the style for the ещщдешз into a global style file

**Comment by wimrijnders** [comment]
OK great! Please close the issue if you're done.
