### ISSUE TITLE
tree spacing in network

### ISSUE THREAD

**Issue by JaroslavPrt** [almende/vis#3328]
Points are considered separate networks?
Is there a way to reduce the distance between point and tree? hierarchical.treeSpacing didn't help 
The same situation for the levels (for example, between level 30 and level 72 there are no nodes but whitespace not reducing)

![capture](https://user-images.githubusercontent.com/11339544/28843568-53cedd72-770a-11e7-9dee-333db4f9fa20.PNG)

**Comment by wimrijnders** [comment]
Yes, the separate points will be regarded as a separate tree. If `treeSpacing` isn't helping you, and you have physics enabled, you can also use the following options to reduce the distance:

```
options : {
  physics: {
    barnesHut: {
      gravitationalConstant: 123.4,    // The bigger, the closer all nodes are to each other
      centralGravity: 3.14             // idem
    }
  }
}
```
See if that works for you.

With the levels not reducing, do you mean that there are two points really low? That *is* strange. This could happen if there are invisible edges or predefined levels. If this is not the case, would you care to post the nodes and edges data here? Options might also be a good idea.
