### ISSUE TITLE
Timeline: Show nested groups from code

### ISSUE THREAD

**Issue by danny-larsen** [almende/vis#3335]
I am trying to have a button expand/open all nested groups. Is there something I have overlooked? Have tried to set the showNested on the groups and then updating them, without any luck.

**Comment by danny-larsen** [comment]
No one have any thoughts on this? I am still struggling with this.

**Comment by marcbc** [comment]
Hi @danny-larsen , I was looking for a related question when I saw yours. Did you figure it out?
I implemented the behaviour as you described and it works fine for me:

1. Trigger the expand/collapse all groups from my UI
2. Recompute all groups setting the showNested option accordingly to the new state
3. Provide the new groups in the new state to the timeline (`this.timeline.setGroups(newGroups)`)

**Comment by jgorene** [comment]
Hello,
This issue is already a little bit old and maybe this track will meet your needs;)
I do this on personal achievements and it works pretty well ...
[Here the codepen](https://codepen.io/jean2607/pen/jZWByv) based from "nested groups" on Timeline examples

**Comment by tatsujb** [comment]
that's weird I took some of the code from your codepen but I can't get it to work : 

```
      const th = this;
      this.groups.forEach(function(group) {
        th.groups.update({
            id: group.id,
            visible: true,
            showNested: true
        });
      });
      console.log(this.timeline.groupsData._data._data);
```

log works fine and shows values for show nested and visible have changed on the non-nested groups but the timeline could care less it stays folded..
