### ISSUE TITLE
FR: can i position the label's position of an edge?

### ISSUE THREAD

**Issue by DanielWLam** [almende/vis#3358]
![image](https://user-images.githubusercontent.com/8369212/29205460-9cfaf56a-7eaf-11e7-8637-caa89c67b22e.png)

Now the label is set at the beginning of the edge default, however, i could be cover by the node some time. Is there any way I can set the label's position? I have checked the doc, but i can't find what i am looking for.

**Comment by wimrijnders** [comment]
I checked the code; currently there is no way to set the position of the label. It is fixed at the center of the edge.

The place where this happens is in `Edge.drawlabel()`: 

```js
...
      if (node1.id != node2.id) {
        this.labelModule.pointToSelf = false;
        var point = this.edgeType.getPoint(0.5, viaNode);  // <== 0.5 is significant
        ctx.save();
...
```

It's the '0.5' that fixes the position of the label half-way along the edge.

Right now, I can't offer you an easy way to adjust this value.

**Comment by wimrijnders** [comment]
Does this answer your question? If so, please close the issue.

**Comment by DanielWLam** [comment]
Thanks~!
