### ISSUE TITLE
How to get a nodes object from network?

### ISSUE THREAD

**Issue by sawatts** [almende/vis#3366]
**Is there a mechanism to get the nodes object from the `network` rather than the data set?**

Accessing the node objects from the input dataset does not help me here - I need the merger of the object from the dataset _and_ the defaults defined in the `network` options.

This type of object is provided to the `joinCondition` function during cluster processing. I need to compare propertie of the node and the parent to determine if it should be added to the cluster, and these properties are derived from group defaults.

**Comment by sawatts** [comment]
Another use case I just encountered - I can attach additional data to a cluster's options object during clustering (`processProperties`), and would like to access this information when events are raised on a cluster node, rather than recalculating from its children each time.

**Comment by wimrijnders** [comment]
There is no official API-way to get that information.

If you're willing to go to the dark side and wallow into unsupported territory, you can get the following information:

- `network.body.nodes` contains the dynamic data for the current nodes
- `network.nodesHandler.defaultOptions` contains all the defaults

If you go there, you're on your own and the above might also be subject to change (unlikely but not excludable). I'm not supporting this, but I'm also not stopping you from doing this - this is javascript, I couldn't stop you if I wanted to.

The second question is technically possible given the above, but this is where I really say 'no'. I think your best bet here is to define a separate data structure for the node information, which you access in the relevant event handlers.

**Comment by wimrijnders** [comment]
Does this answer your question? If so, please close the issue.
