### ISSUE TITLE
Disable item deselection on "press"

### ISSUE THREAD

**Issue by Hokyjack** [almende/vis#3375]
Hello I was trying to figure out how to easily change behaviour to disable long mouse press to deselect item, because it's driving me crazy when user wants to fine-adjust item position (so he try to press and move item very slowly) and instead it gets deselected.

I thought I can catch event type "pressed" in timeline.on('select') and somehow prevent the deselection but cannot figure if this is event possible, because I assume this event is fired after the item is deselected?

Any ideas how to disable this? I still want items to be selectable/deselactable with other ways, only this "press" event is really painful.

Many thanks!

**Comment by FrankW76** [comment]
@Hokyjack My users are also having this same issue. Did you found out any workaround for this ?

**Comment by ap--** [comment]
The press is detected by Hammer.js which hardcodes the interval to 251ms. And so it's not really configurable from the vis.js side (or at least I couldn't figure out how.)
On current master it's in line https://raw.githubusercontent.com/almende/vis/master/dist/vis.js#39793

just grep for `time: 251, // minimal time of the pointer to be pressed`

We changed it to 1000 ms and have no issues with accidental deselection on resize anymore.

**Comment by Hokyjack** [comment]
@ap-- thank you!!!! Works as charm!
