### ISSUE TITLE
HTML tooltips

### ISSUE THREAD

**Issue by carueda** [almende/vis#338]
This is about allowing html in token tooltips (complementing what the current 'title' does with only text), and on groups.  I know there are some "tooltip" entries already but I was not sure whether any of them is for the timeline component; feel free to mark this as duplicate if that's the case.  Thanks.

**Comment by AlexDM0** [comment]
Hi,

Over the last year a lot of feature requests have been made. We have just introduced our new website which has a list of the requested features. We have placed this request on that list. 

The list can be found here:
http://visjs.org/featureRequests.html

An explaination of the new system can be found here:
http://visjs.org/blog.html#New\ website\ for\ vis\.js\!

I would like to stress that this does not mean we abandon this request. Discussion here will continue if needed on this feature but we will close it to keep our Github issue page more of a bug-todo list.

Future feature requests will still be made here and then added to the website by us.

Regards,

Alex

**Comment by jasontibbitts** [comment]
I just happened to need this and ran across this closed issue.  I managed to get something that at least works for my use case.  Just pull in jquery and powerTip, do
```javascript
$('.group .item').powerTip({placement: 'se', smartPlacement: true, mouseOnToPopup: true});
```
(or whatever selector you need to get the items you want) and then the title property on every element can be any HTML you want.  I'm doing a little security camera system and the elements on the timeline are videos.  The tooltips display small versions of the videos, with controls and everything.  Seems to work fine, even with zooming and scrolling.

Maybe this is trivial or pointless, since I don't really know what I'm doing, but at least I have something going.

**Comment by jasontibbitts** [comment]
Meh; this for some reason doesn't work if you call setGroups, even if you just initially set up the timeline that way.  It doesn't appear that the structure of the elements changes if you do that, and powerTip attaches the events to all of the items properly, but either the tooltip doesn't fire, or it fires _and_ the title tooltip appears.  Looks like I need to find another way to do what I wanted to do.

**Comment by sekys** [comment]
Hello jason, well this is not working because you are selecting existing items. For you and all, i suggest use "bind" function. Then you are selecting existing and future-existing elements. Good luck

**Comment by jasontibbitts** [comment]
Thanks for the hint.  I'm not sure that powertip code exposes a way to use bind; it appears to traverse the selected elements itself and attaches events with this.on().  Though, it does allow that to be overridden.  I'll have to see why it does appear to attach events to new elements but doesn't manage to get its tooltip magic correct.

**Comment by phamtuananh791994** [comment]
Are any solution for this ?

**Comment by mojoaxel** [comment]
Reopening as Feature-Request issue (see #2114). 
Everybody: Please feel free to implement this!

**Comment by yotamberk** [comment]
Added to the next release with #2498. Thanks @lewisjb!
