### ISSUE TITLE
Not refreshing options(start, end)

### ISSUE THREAD

**Issue by deniz946** [almende/vis#3385]
Hello, im using visjs with angularjs and everything works smooth, but I have a small problem and I can't figure out how to fix it...

In first load I create a timeline with one start and end date config for that timeline, but I have a filter on the page for date, and if I change the given date, I need to change the timeline date, because my timeline just shows the time from 7am from today to 7am tomorrow on the given date.

If I change the date i want to show in the timeline from 7am to 7am for the given date(start,end).

Im using setOptions but no way it refreshes, reloads or redraws the date on the timeline...

```$scope.container = document.getElementById('visualization');
let groups = new vis.DataSet(groups)
let items = new vis.DataSet(items)
$scope.options = {
    orientation: 'top',
    tooltipOnItemUpdateTime: true,
    editable: {
        add: false,             // add new items by double tapping
        updateTime: true,       // drag items horizontally
        updateGroup: false,      // drag items from one group to another
        remove: true,           // delete an item by tapping the delete button top right
        overrideItems: false    // allow these options to override item.editable
    },
    groupEditable: false,
    locale: 'es',
    start: moment('07', 'hh'),
    end: moment().add(1, 'day'),
    min: min,
    max: max,
    stack: false,
    zoomMin: 1000 * 60 * 60 * 10,
    zoomMax: 1000 * 60 * 60 * 24,       
    moveable: true,
    timeAxis: { scale: 'minute', step: 30 },
    showCurrentTime: true
};

$scope.timeline = new vis.Timeline($scope.container, items, groups, options)

$scope.$watch('date', function(newDate){
    $scope.options.start = moment(newDate);
    $scope.options.end = moment(newDate).add(1, 'day');
    $scope.timeline.setOptions(options);
}

I've tried also using .redraw() after setting the new options, and nothing...

Really would appreciate a help, been looking everywhere for a solution and nothing... Thanks

**Comment by brichbe** [comment]
Have a look at the [Timeline Methods](http://visjs.org/docs/timeline/#Methods) you can call, specifically the `setWindow` one.

**Comment by deniz946** [comment]
Nothing... It doesn't change the timeline date, im using this

```
    $scope.$watch('date', function(date){
         let options = {}
         options.start = getStartDate(date);
         options.end = getEndDate(date);
         $scope.timeline.setWindow(options.start, options.end)
    });
```

I've tried using $scope.timeline.redraw(); after the setWindow func and it doesn't work neither... I don't know if I'm doing it wrong or what...

PD: Sometiemes I get a warning in the console saying "WARNING: infinite loop in redraw?" Not sure if it has something to do, but it doesn't appear always. Thanks

**Comment by brichbe** [comment]
The infinite loop warning is not related.

Your last snippet includes the getStart/EndDate functions that you didn't have before, and you didn't show how those are implemented - do those return a moment?  Note the docs say the dates provided to `setWindow` can be a Date, Number or String.

**Comment by deniz946** [comment]
Hello, the getStart/getEnd function just receivs a date parameter and sets it to 7am at today(for getStart) and 7am + 1 day for getEnd and returns Date
```
    function getStartDate(date) {
        let start = angular.copy(date);
        start.setHours(7);
        start.setMinutes(0);
        start.setSeconds(0);
        return start;

    }

    function getEndDate(date) {

        let end = angular.copy(date);
        end.setDate(end.getDate() + 1)
        end.setHours(7);
        end.setMinutes(0);
        end.setSeconds(0);
        return end;
    }
```

**Comment by brichbe** [comment]
Try modifying those functions to return the number of millis, or the date as a String, to see if that makes a difference.  Otherwise it's difficult to help any further unless you can reproduce this issue in a jsbin/jsfiddle.

**Comment by brichbe** [comment]
The other possibility is you're trying to set the start/end window outside the allowable range of the Timeline's min/max... are you sure that's not the problem?

**Comment by deniz946** [comment]
Maybe the max-min stuff, is it possible to change the max-min params adding new options to setWindows? Like .setWindows(start, end, newOptions)?

**Comment by brichbe** [comment]
No, setting options for the timeline is different than specifying method-specific options during a method call.  

If the min/max has been your problem all along, then you'll need to do this in two steps -- first call timeline.setOptions where you specify the new min/max for the timeline (instead of the start/end like you originally had).  After that, do what you have in your latest snippet - call timeline.setWindow with your new start/end.

**Comment by yotamberk** [comment]
@deniz946 Does this answer your question? Can we close the issue?

**Comment by deniz946** [comment]
Yes, thanks you! and sorry for the late answer!
