### ISSUE TITLE
Funky resizing with multiline titles

### ISSUE THREAD

**Issue by michel404** [almende/vis#3395]
I have encountered a bug in the vis.js network component.

When I make a title of a node multiline with the style properties `maxWidth` and `whiteSpace`, I encounter unwanted behavior.

When I hover over a node with a small text, and afterward hover over a node with a long multiline title, the small title-div is reused, and is rendered too small. When I wiggle the mouse over the node, the title grows slowly to the desired width. What I want is a title that has directly the correct size, not after wiggling the mouse over the node.

This bug can be reproduced in this js-bin: http://output.jsbin.com/hobeparusa

I run:
* vis.js 4.20.1 (latest)
* Chrome Version 59.0.3071.115 (64-bit)
* Ubuntu 16.04 LTS

**Comment by wimrijnders** [comment]
Very funky! Now I've got Red Hot Chilli Peppers playing in my head.

Thanks for the great demo, will look into it.

**Comment by wimrijnders** [comment]
Changed label to `source/non-public API` because this is a global component, used in `Timeline` as well as `Network`.
