### ISSUE TITLE
Official website network document  JSON link error

### ISSUE THREAD

**Issue by Chenjiahui88** [almende/vis#3397]
Official website network document  JSON link error

Import data from Gephi

Network can import data straight from an exported json file from gephi. You can get the JSON exporter here: https://marketplace.gephi.org/plugin/json-exporter/. An example exists showing how to get a JSON file into Vis:

https://marketplace.gephi.org/plugin/json-exporter/     404 
please update  thx

**Comment by macleodbroad-wf** [comment]
I believe that this is temporary.

https://marketplace.gephi.org/ is currently displaying a Fedora Test Page which states:
```
If you are a member of the general public:

The fact that you are seeing this page indicates that the website you just visited is either experiencing problems, or is undergoing routine maintenance.
```

**Comment by mbroad** [comment]
Website's plugin url has been changed to https://gephi.org/plugins/#/plugin/jsonexporter-plugin

**Comment by macleodbroad-wf** [comment]
See https://github.com/almende/vis/pull/3414
