### ISSUE TITLE
Can't get working min max params

### ISSUE THREAD

**Issue by deniz946** [almende/vis#3423]
Hello, im trying to set the min max params of the VISJS Timeline options so I can't move an item more than the max hour or min hour but it's not working. I can drag the items far from thoose limits and I'm not sure if I'm doing something wrong with the config, any help will be appreciate, thanks you!

![Options](https://i.gyazo.com/37bc7bb3805d80829f72ee4f5b8c06b6.png)

**Comment by jmoraltu** [comment]
I am not sure you can do this, I think you will have to remove the item and add it back again after you are able to accomplish this rule:
min < item start time < max

**Comment by deniz946** [comment]
Thanks you @jmoraltu, it works!
