### ISSUE TITLE
Rendering issue when items is side by side 

### ISSUE THREAD

**Issue by julienchepa** [almende/vis#3424]
Hi guys,

I have a render issue when items is added side by side (see below) :

![capture d ecran 2017-09-07 a 16 33 50](https://user-images.githubusercontent.com/5547667/30163605-8dbee46c-93ea-11e7-81a0-a737ebd2d1e7.png)

When i separate element, everything is ok at the same line : 

![capture d ecran 2017-09-07 a 16 38 14](https://user-images.githubusercontent.com/5547667/30163703-fb325dda-93ea-11e7-91e3-6e4f850a1bab.png)

I have this behaviour since I've updated from 4.16 to 4.20.

Did i make something wrong ? 

PS : great job for this amazing library !

**Comment by yotamberk** [comment]
a simple solution for this is to set the `options.margin.horizontal: -0.5`

**Comment by julienchepa** [comment]
@yotamberk, thanks ! 

The trick work well.
