### ISSUE TITLE
MS IE and Edge slow when stabilizing is finished

### ISSUE THREAD

**Issue by Head** [almende/vis#3425]
For example, open http://visjs.org/examples/network/exampleApplications/lesMiserables.html on Edge (latest version 40.15063.0.0).
Then move the whole graph: Utterly smooth.
Now wait a bit until all nodes are stabilized in their positions.
Move again and have a bad time.

**Comment by OACDesigns** [comment]
I'm also experiencing this on Edge 15.15063
It becomes virtually unusable as soon as stabalisation has completed.

**Comment by wimrijnders** [comment]
So I've got a Window 10 machine running here now, to check this and other issue on Edge. It's a 1.4GHz Celeron, so not the fastest thing on the planet.

I ran the given example on Edge and in all honesty I have to say it's working quite well. I do notice, however, a difference with the usage of input devices:

- The touch pad on my Logitech keyboard works smoothly as a baby's bottom. I can drag to my heart's content and all is responsive.
- With the USB mouse, however, there is a significant lag while dragging, with the dragged node chasing the mouse cursor in discrete steps. As soon as I stop dragging, everything is smooth again.

Could this perhaps be a driver problem?

I'm wondering now what the symptons are that you are experiencing. Does it look like what I experienced with the USB mouse? Or is it something else more pronounced? What particular experience makes it virtually unusable and/or gives me a bad time?

I've also tried the `worldCupPerformance` example, with is a heavy-weight with about 1000 nodes and 10000 edges. Here, I do see significant difference with my i7. But I think that that can be forgiven with such a big network.

----
Stabilization, as the term is known within `Network`, is the step that is performed *before* anything is shown on screen, to assign decent starting positions for the nodes. I'm assuming you don't mean that, but that the nodes have stopped moving on screen.

**Comment by wimrijnders** [comment]
@OACDesigns, how do I check the Edge version number? Have no clue and Bing isn't helping.

**Comment by Head** [comment]
Yep, the moment the nodes have stopped moving it becomes laggy. Using a normal mouse and a high end gamer PC, latest "everything".

I made a video to demonstrate it (also showing where to find the version no): https://youtu.be/_xSYcFyVnGw

**Comment by wimrijnders** [comment]
Thanks for the video, that helped.

What I'm seeing is that movement is smooth as long as the nodes are moving. When the movement stops, the full network drag is 'stuttering' (to give it a name). There are large pauses between movement and that movement is abrupt.

I also note:
- zoom in/out is responsive
- Drag of individual nodes is responsive
- When the nodes are moving again, the full network drag is also responsive

Does this sum it up? I realize I'm repeating stuff that you both have already mentioned.

And so my Edge version is: 20.10240.17113.0

**Comment by wimrijnders** [comment]
So this looks like a refresh issue in the case that there is no movement of nodes, in combination with the full network drag. That's sort of a hint for where to look; I do wish though that I could reproduce this locally.

Any other symptons I should be aware of, besides the above?

**Comment by Head** [comment]
Chrome is totally fine! And oh my... Firefox is lagging too. That's not that good for our project :(

Chrome: Fine (60 FPS)
Firefox: Bad (2 FPS)
IE: Bad  (1 FPS)
Edge: Worst  (0.2 FPS)

Afaik no other symptons.

**Comment by wimrijnders** [comment]
Right. I intend to make a special build for WIN, meant for testing by you, which disables the request frame animation altogether. By isolating that part, we can see if the problem is there. Will do it this weekend.

**Comment by wimrijnders** [comment]
I'm happy to report that someone else, namely @justinharrell, has picked up the issue. You probably would have noticed that already with the notifications on this issue, but I'd like to use this opportunity to express my gratitude to named @justinharrell.
