### ISSUE TITLE
[vis-network]Translate Chinese

### ISSUE THREAD

**Issue by ritevke** [almende/vis#3428]
vis.js能不能把中文的国际化加进来？
// Chinese
  exports['cn'] = {
      edit: '编辑',
      del: '删除选定',
      back: '返回',
      addNode: '添加节点',
      addEdge: '添加连接线',
      editNode: '编辑节点',
      editEdge: '编辑连接线',
      addDescription: '单击空白处放置新节点。',
      edgeDescription: '单击某个节点并将该连接线拖动到另一个节点以连接它们。',
      editEdgeDescription: '单击控制节点并将它们拖到节点上连接。',
      createEdgeError: '无法将连接线连接到群集。',
      deleteClusterError: '无法删除群集。',
      editClusterError: '无法编辑群集。'
  };
  exports['zh_CN'] = exports['cn'];

**Comment by macleodbroad-wf** [comment]
I ran all of these through google translate and they all look correct, assuming that `cable` is a synonym for `edge` in cn

**Comment by macleodbroad-wf** [comment]
Added in https://github.com/almende/vis/pull/3430

Thank you @ritevke

**Comment by ritevke** [comment]
不用谢，能不能帮我把#3427这个问题看下呢？
