### ISSUE TITLE
vis.js graph constantly spinning and unresponsive 

### ISSUE THREAD

**Issue by saurabhvyas** [almende/vis#3438]
![image](https://user-images.githubusercontent.com/6899784/30316819-078c1a60-97c6-11e7-9f47-7389c52a2fea.png)

I created a graph using input json of edges , it has about 200 edges , on both sides , like if there is an edge (a,b) , there is another edge (b,a) for each node , in such scenario my graph is not working , weirdly enough, it is constantly spinning , I created 2 more graphs with less nodes and edges , they seem to render  the graph fine

**Comment by wimrijnders** [comment]
You can do some tuning with the `physics` options to counter the spinning. See if you can use the [physics configuration example](http://visjs.org/examples/network/physics/physicsConfiguration.html) to find some good values. Good options to try are `damping` and `timestep`, although others may be useful too.

In the worst case, you can disable physics.

**Comment by saurabhvyas** [comment]
@wimrijnders Thanks for providing link to physics configuration example page , I will try tweaking with these settings.

**Comment by saurabhvyas** [comment]
I can confirm, that the spinning issue has been solved  , by those settings , thanks :)

**Comment by wimrijnders** [comment]
OK good luck. That page is the way I always solve these kinds of problems. You're not the first to have them and you won't be the las.
