### ISSUE TITLE
Cannot set the border highlight in shape "Image" only works in "Circular Image".

### ISSUE THREAD

**Issue by jeganwbc** [almende/vis#3446]
I create the **shape:'image'** and set the border,highlight in options. it cannot works. but **shape: 'circularImage'** accessed the border,highlight. how to set the image highlight border in **shape:'Image'**?

Thanks..!

**Comment by wimrijnders** [comment]
I just tried this out. The answer is: in exactly the same way as with `shape: circularImage`, but you will need to enable the borders with images first:

```js
      var options = {
...
        nodes: {
          shapeProperties: {
            useBorderWithImage:true
          }
        },
...
      };
```

**Comment by jeganwbc** [comment]
**Thank You..! It's Working Fine..!**
