### ISSUE TITLE
I cluster the node and call the network.getConnectednodes.but it show wrong node data's

### ISSUE THREAD

**Issue by jeganwbc** [almende/vis#3448]
First I cluster the group of nodes. The cluster is connected with one other node. I get the connection node for this single node.but it shows the one another node in **network.getConnectedEdges(nodeid);** 
**network.getConnectedNodes(nodeid);**

the single node **Jegan** shows two connected edges and two connected nodes.
How to solve it..!

Thank You..!

![1](https://user-images.githubusercontent.com/28730476/30530093-66190bf2-9c61-11e7-8924-e0ee58a58866.PNG)
![2](https://user-images.githubusercontent.com/28730476/30530094-661d9c4e-9c61-11e7-818f-5f1b0d9c549d.PNG)
![capture](https://user-images.githubusercontent.com/28730476/30530095-662596a6-9c61-11e7-990d-c9c2f009fc92.PNG)

**Comment by wimrijnders** [comment]
I don't think I understand your question. Perhaps you are trying to get the edge that connects to the cluster? In that case, have a look at method `network.getClusteredEdges()`.

If that was not the question, please make an example for better understanding.

**Comment by jeganwbc** [comment]
I want to get the jegan's node connected all nodes and clusters.Jegan's node connected only one clustered node.but it shows two nodes.
**3929 and cluster:group_1**

![](https://user-images.githubusercontent.com/28730476/30530094-661d9c4e-9c61-11e7-818f-5f1b0d9c549d.PNG)

**Comment by wimrijnders** [comment]
This sounds familiar. Could you please send a screen shot?

Met vriendelijke groet,

Wim Rijnders
http://axizo.nl

**Comment by jeganwbc** [comment]
connected nodes is one node.
but it's shows in network.getconnectednodes() two nodes.

![4](https://user-images.githubusercontent.com/28730476/30537419-322b12a6-9c87-11e7-919a-fffa375292f0.png)
![2](https://user-images.githubusercontent.com/28730476/30537425-40c4048a-9c87-11e7-9671-68cd77bfe897.PNG)
![3](https://user-images.githubusercontent.com/28730476/30537457-57bc3b62-9c87-11e7-8aaf-052d8bc5dc3f.PNG)

**Comment by wimrijnders** [comment]
OK so four nodes like this:

![download 7](https://user-images.githubusercontent.com/769037/30540640-3edd208e-9c78-11e7-8c7f-e883d863697e.png)
I cluster the top:


![download 8](https://user-images.githubusercontent.com/769037/30540643-434a8bf2-9c78-11e7-835b-f39aeda822a6.png)

And then look at `getConnectedNodes('c1')`: `[4]`.

Which is what I would expect. Would you mind sharing the code with me?

**Comment by jeganwbc** [comment]
Fixed this issue.Thank you sir..!
