### ISSUE TITLE
Funding using OpenCollective

### ISSUE THREAD

**Issue by mojoaxel** [almende/vis#3450]
I want to start a discussion about whether or not vis.js should get on [OpenCollective](https://opencollective.com/) and start receiving funds.

### Pros
- We could fund core maintainer e.g. for making releases, closing big issues or introducing new features.
- The move to OpenCollective could introduce the project to new developers.
- Users of vis.js could make sure the project is sustainable by funding it.
- OpenCollective might be a nice way for almende to still support the project without having to spend expensive developer time.

### Cons:
- vis is officially still an [almende](https://github.com/almende) project. I think it would be best to move the project over to the already existing [visjs](https://github.com/visjs) account and fully manage it by the community. **This is a move almende must be willing to do.**
- Not every developer is able to receive funds. Most developers are employed and are not allowed to take money from other entities like OpenCollective. Who decides who gets which funds?

**Comment by wimrijnders** [comment]
'Con 2' might be a deal breaker. Do you mean to say that it's up the employers to give permission to work on `vis.js`?

Actually, in my case that would be good. I'm self-employed; I'm quite sure I can convince my pointy haired boss, being myself, to do paid work on `vis.js`.

**Comment by mojoaxel** [comment]
> Actually, in my case that would be good. I'm self-employed;
me, too!

But we should be aware: In the beginning there will not be much funding to give away. I think the best way is to vote for bugs that should get fundet. This could e.g. be regular releases, new tests are major bugs. This is up to the community. Time people like us already spend on the project will NOT be paid!

**Comment by yotamberk** [comment]
Hey, I'm very much for this idea. 
I too am employed and cannot receive funds (for the next year).
But I am very much supporting this idea. Splitting this project and getting it run better from the community is a MUST.

**Comment by mojoaxel** [comment]
Thanks everyone for supporting this idea.
I just sent [an open letter](https://gist.github.com/mojoaxel/18c6c0fe04eccc6cc1261dfc0bc8d6d9) to the official almende adress and @ludost . Now we have to wait for an response.

**Comment by mojoaxel** [comment]
The answer from almende: 
> We've finished our internal discussions on this subject. We support your ideas with regard to external funding and modularization. 
We would like to see how we can help you reach the goals of better separated modules, within the Almende github repository (for this moment we would like to retain a single coherent visjs brand connected to Almende).

**Comment by mojoaxel** [comment]
I'm in the process of creating an OpenCollective account. Sadly there was a [bug](https://github.com/opencollective/opencollective-website/issues/772) at there end.

We all should think about how we want to use the money (it there ever will be any).

**Comment by wimrijnders** [comment]
@mojoaxel I have this distinct feeling that you're working in the backward direction, by attempting to create that account. Why not concentrate on splitting first?

**Comment by wimrijnders** [comment]
I hereby suggest making a plan with a checklist for the conversion, in the spirit of the plan used for releases. I really think it's a good idea instead of doing things in an ad-hoc order.

**Comment by mojoaxel** [comment]
> Why not concentrate on splitting first?

I want to create the OpenCollective account as early as possible so that people can start supporting. In the ideal case we got enough money to finance the splitting of the modules.

> I hereby suggest making a plan with a checklist for the conversion

The registration with OpenCollective is not a big thing. We need no Checklist for this. What we need a checklist for ist the Splitting part. This is big! See #2405 #3580 and #3579

**Comment by wimrijnders** [comment]
>  What we need a checklist for ist the Splitting part. 

That's what I meant.

**Comment by mojoaxel** [comment]
🎉 We are now on OpenCollective: https://opencollective.com/vis

**Comment by mojoaxel** [comment]
This is the post install message after #3681:
```
> opencollective postinstall


                            Thanks for installing vis
                 Please consider donating to our open collective
                        to help us maintain this package.

                           Number of contributors: 136
                               Number of backers: 0
                               Annual budget: US$ 0
                              Current balance: US$ 0

               Donate: https://opencollective.com/vis/donate
```
