### ISSUE TITLE
Nodes rotating problem

### ISSUE THREAD

**Issue by morenonir** [almende/vis#3455]
Hi there,

I'm using latest version of vis.js network graph.

Attaching you a link to jsFiddle which demonstrate my problem 
https://jsfiddle.net/mea573a4/

Long story short, while trying to load a bunch of nodes and edges. the network wander around the center.

The problem occurs on Chrome, FF and IE11

Please **help**.

**Comment by wimrijnders** [comment]
Duplicate of #3438. Please follow the suggestions there.

**Comment by wimrijnders** [comment]
Closed because duplicate. Any further work will be done in #3438.
