### ISSUE TITLE
Network: Asynchronous image load causing svg icons to look empty in ie11

### ISSUE THREAD

**Issue by gowti1992** [almende/vis#3457]
In my project we are using network shape 'circularimage' like below.

`image: {
                    unselected: "data:image/svg+xml;charset=utf-8," + encodeURI(svg), selected: "data:image/svg+xml;charset=utf-8," + encodeURI(svgSelected)
                }`

 svg/svgSelected variable mentioned contains circle and image element. The image element is referencing another svg icon something like below which is not getting rendered in IE11.

`<image x="' + oX / 2 + '" y="' + oY / 2 + '" xlink:href="data:image/svg+xml;charset=utf-8,' + encodeURI(iconSVG) + '" width = "' + oX + 'px" height = "' + oY + 'px"/>`

I have noticed following behaviors.

1. The above image element is not visible in IE during the load time. But, if i refresh the canvas the image icon is getting rendered because it loads from cache.
2.  If i disable cache in IE browser. Icons are not loading even if i refresh the canvas.
3. Icons are displaying properly in chrome and firefox.

Can you please help me?

**Comment by wimrijnders** [comment]
I bet it's something which is not entirely supported in IE. In any case, SVG drawing on canvas is limited and not all SVG features are supported.

As for the load on startup, or rather the lack thereof, this is a known problem with no real solution (feel free to help). You can also trigger the drawing after load by just moving a node.

**Comment by wimrijnders** [comment]
I'm actually presuming that with 'icons' you mean an image defined with SVG, not a character from an icon font. Is this correct?

**Comment by gowti1992** [comment]
> I'm actually presuming that with 'icons' you mean an image defined with SVG
Yes. Its svg image.

> You can also trigger the drawing after load by just moving a node.
Ya it will help. You mean re positioning the node or is there any simple api to do such.

**Comment by wimrijnders** [comment]
> ...or is there any simple api to do such.

`network.redraw()` does it. However, you still need to get the timing right, i.e. redraw after all assets have loaded.

I know there's a module somewhere out there which can detect when a font has loaded, perhaps there's something similar for images and/or svg.
I'm also thinking that the simplest solution might be to just do `<body onLoad='init()'>`. That's what it's designed for.
