### ISSUE TITLE
Keep timeline slider centered while zooming

### ISSUE THREAD

**Issue by robertico01** [almende/vis#346]
Is it possible to keep the timeline slider centered while zooming ?

![image](https://cloud.githubusercontent.com/assets/3778759/4409476/c0654a8c-44dd-11e4-91b5-cab89074db02.png)

( I suppose using event="rangechange" )

**Comment by AlexDM0** [comment]
Is this still an issue? Seems to me that all questions have been answered.

Regards,

Alex
