### ISSUE TITLE
Big nodes overlapping vertically in hierarchical view

### ISSUE THREAD

**Issue by Maniae** [almende/vis#3463]
Hi, I'm having an issue using the hierarchical view with big nodes:

https://jsfiddle.net/vv2x5yfy/

Is there a way to increase the distance between the different floors of the view ? We can set a spacing for the free axis, but I didn't find any option to set it for the other one.

**Comment by wimrijnders** [comment]
Yes, there is. Check out the separation options in [the documentation](http://visjs.org/docs/network/layout.html). The one you're looking for is `levelSeparation`, but the other ones may be of use to you as well.

**Comment by Maniae** [comment]
Can't believe I missed it, thanks !
