### ISSUE TITLE
[Network] physics simulation runs multiple times but stabilizationIterationsDone event only fires once

### ISSUE THREAD

**Issue by rjbriody** [almende/vis#3468]
Chrome Version 60.0.3112.113 (Official Build) (64-bit)
OSX
Vis version 4.20.1

This might be easiest to describe w/ an example https://jsfiddle.net/nxs3poo6/, but here's the deal...

- Fire up a network w/ physics enabled.
- graph is displayed. physics animation happens. eventually, graph stops moving.
- `stabilizationIterationsDone` event is fired.
- augment the network (add another node and edge) using the underlying DataSet.
- physics starts again. `startStabilizing` event is fired.
- graph stops moving
- (and this is where the problem occurs) **`stabilizationIterationsDone` is never fired**

**Comment by wimrijnders** [comment]
Confirmed. Looking at the docs, I see this for `stabilizationIterationsDone`:

> Fired when the 'hidden' stabilization finishes. This does not necessarily mean the network is stabilized; it could also mean that the amount of iterations defined in the options has been reached.

Now, I have no idea what is meant by 'hidden', and why it is between quotes. Taking it at face value, I interpret this as meaning 'a stabilization triggered by a data change`, i.e. all stabilizations except the initial one on startup. Which means that current implementation is exactly the wrong way around.

I'd rather get rid of 'hidden' in the docs and just trigger the event always. Will get back to this.

**Comment by wimrijnders** [comment]
I'm having second thoughts on this one. `stabilizationIterationsDone` is meant specifically for the stabilization on startup. If you need an event for the completion of interim stabilization, there is `stabilized`.

I propose that you handle event `stabilize` instead. Closing this issue, if you disagree with this please comment here and we'll discuss further.

**Comment by rjbriody** [comment]
I agree, and in fact have transitioned to using the `stabilized` event. I was originally confused by the docs as it seemed like `stabilized` would only be called when the network was successfully stabilized and not when the simulation stopped early due to reaching the number of max iterations.

A possible docs improvement could be to change...

stabilized
> Fired when the network has stabilized or when the stopSimulation() has been called. The amount of iterations it took could be used to tweak the maximum amount of iterations needed to stabilize the network. Passes an object with properties structured as:
 
to something like this

> Fired when the network has stabilized, **when the amount of iterations defined in the options has been reached,** or when the stopSimulation() has been called. The amount of iterations it took could be used to tweak the maximum amount of iterations needed to stabilize the network. ...

**Comment by wimrijnders** [comment]
Fair enough. I agree that it makes the purpose more explicit. I'll add the doc change in.
