### ISSUE TITLE
Recenter network graph around a particular node

### ISSUE THREAD

**Issue by sumitsuthar** [almende/vis#3469]
Is there any option is vis js library to recenter network graph around a particular node?

**Comment by wimrijnders** [comment]
Sure. Check out method `moveTo()` in [the docs](http://visjs.org/docs/network/).

**Comment by sumitsuthar** [comment]
@wimrijnders Thanks for your answer but moveTo() method just change the camera view. I tried this method but nothing fruitful as per my requirement. My requirement is to make a particular node in center and redraw other node(connected nodes) around it. I want to recenter the whole network around this particular node.

Thanks in advance.

**Comment by wimrijnders** [comment]
OK, but I don't really see the difference; it's just that the coordinates are moved.

How about this: take your center node and fix it to a certain position:

```js
 var nodesData = [
    {
      id: 1,
      label: 'Node 1',
      x: 0,
      y: 0,
      fixed: {
        x: true,
        y: true
      }
    },
...
  ];
```

...and proceed as normal. You might need some trickery with `moveTo()` to get node 1 in the center of the view.

*Note: (This will not work with hierarchical views).*

**Comment by sumitsuthar** [comment]
Yeah, We can do this, but What I want is to readjust all the nodes around this particular node. I am using network.fit method.  
`  var options = {
				    	        position: {x:viewPosition.x,y:viewPosition.y},
				    	        nodes:[Array of nodes],
				    	        scale: 1,
				    	        offset: {x:0,y:0},
				    	        animation: {
				    	          duration: 100,
				    	          easingFunction: "easeInCubic"
				    	        }
				    	      };
				  
				     vm.network.fit(options);`
I tried moveTo() method and for other I set some fixed position for the particular node. But not fruitful.
Is there any method or functionality that can be used to readjust the connecting nodes around that particular node and that particular node must be in center.

**Comment by wimrijnders** [comment]
I'm confused now, not understanding what you mean by 'readjust'. Do you mean move the nodes so that they are around the central node again? This happens automatically when there are edges to the central node.

If you mean something else, I'm afraid you'll have to be more specific. Perhaps an example might help.

**Comment by sumitsuthar** [comment]
Do you mean move the nodes so that they are around the central node again? 
> No, I don't want to re-center around same node again and again, what I want is, i can choose the node to re-center around and the graph should adjust itself that the selected node becomes the center and all the connected nodes and others get adjust themselves around that node.

**Comment by sumitsuthar** [comment]
Ok

**Comment by dragonzone** [comment]
Probably an easier way is to use network.focus(nodeId).

You can read more here:
http://visjs.org/docs/network/#methods

**Comment by wimrijnders** [comment]
Is the question hereby answered? If so, please close the issue.
