### ISSUE TITLE
Node Id to Get the Edges Id

### ISSUE THREAD

**Issue by jeganwbc** [almende/vis#3472]
I have a Large nodes data and large edges data.so any possible to get the two nodes to get connected edge id?

I Give the node id 1 and  2.How to get the edge id for the node 1 and 2. without using nodesArray and edgesArray.

**Comment by wimrijnders** [comment]
Does that mean you don't want to use `DataSet` either for nodes and edges?

Here a way to get the information from `network`:

```js
var edges1 = network.getConnectedEdges(1);
var edges2 = network.getConnectedEdges(2);

var edges = [];
for (var i = 0; i < edges1.length; ++i) {
  if (edges2.indexOf(edges1[i]) !== -1 ) {
    edges.push(edges1[i]);
  }
}
console.log(edges);

```

**Comment by jeganwbc** [comment]
Thank You Sir..! It's Working Fine
