### ISSUE TITLE
How To update all the edges color in dynamically

### ISSUE THREAD

**Issue by jeganwbc** [almende/vis#3473]
I have the large data nodes and edges.
How to update all the edges color in red in programmatically
I use the edgesArray in each function.
But its too slow.how to solve it.

$.each(edgesArray, function (index, item) {
        item.color = {
            color: "green"
        }
       edges.update(item);
});

**Comment by wimrijnders** [comment]
Here, `edgesArray` appears to be an array or and `edges` a `DataSet`. Is this correct? I'll assume it is for now. And I'll also assume that you really want to update `edges` from `edgesArray`.

Do all the updates in one go:

```js
$.each(edgesArray, function (index, item) {
  item.color = {
    color: 'green'
  };
}
edges.update(edgesArray);
```

----
Not tested with jQuery, YMMV. This is how I tested it:

```js
var updateData = edges.get();
for (var i = 0; i < updateData.length; ++i) {
  updateData[i].color = {
    color: 'green'
  };
}
edges.update(updateData);
```

**Comment by jeganwbc** [comment]
Thank You Sir..! It's Working Fine..!
