### ISSUE TITLE
Option image must be defined for node type 'image'

### ISSUE THREAD

**Issue by brunobraga** [almende/vis#3483]
Hi vis.js team,

I think I found a bug with the latest version of the library (4.20.1).

When you render nodes of 'image' shape while leaving the shape definition globally set on options, it results in the error:
Option image must be defined for node type 'image', line 36469.

This happens with more than 150 nodes.

I can confirm this was introduced in 4.20.0. The 4.19.1 works fine, and 4.20.1 is still broken.

Here is the working example (with version 4.19.1):
https://jsfiddle.net/os1zn7qz/

And here is the same with the newer library (4.20.1), which fails to load:
https://jsfiddle.net/b1gc1qe4/

I can get the version 4.20.1 to work if I remove the global setting and place it instead within the node setting:
https://jsfiddle.net/oe9qvLsj/

The code (in case Fiddle fails):

```html
<html>

<head>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/vis/4.20.1/vis.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vis/4.20.1/vis.min.js"></script>
    <style>
    #network_visualisation {
        height: 100%;
        width: 100%;
    }
    </style>
</head>

<body>
    <div id="network"></div>
    <script>
    var limit = 15;
    var nodes = [],
        edges = [];
    for (var i = 0; i < limit; i++) {
        nodes.push({
            "id": "id" + i.toString(),
            "label": "node" + i.toString(),
            // "shape": "image",
            "image": "https://cdn4.iconfinder.com/data/icons/iconsimple-logotypes/512/app_store-128.png",
        });
    }

    for (var i = 0; i < limit; i += 2) {
        var randId = "id" + (Math.floor(Math.random() * 99) + 1).toString();
        edges.push({
            "to": randId,
            "from": "id" + i.toString(),
            "label": "edge" + i.toString()
        })
    }

    var network = new vis.Network(document.getElementById('network'), {
        nodes: new vis.DataSet(nodes),
        edges: new vis.DataSet(edges)
    }, {
        nodes: {
            shape: 'image',
        },
    });
    </script>
</body>
</html>
```

With the sample code above:
- as is - 4.20.1 breaks
- change to 4.19.1 - works fine
- 4.20.1 - add "shape" property to each node and remove it from options

**Comment by wimrijnders** [comment]
Working perfectly fine.

This is on linux+(chrome|firefox). What platform are you using?

**Comment by wimrijnders** [comment]
Err....the weirdest thing 😕. Has nothing whatsoever to do with image loading. Looks like it's happening during layout initialization. Will get back to this in my free time.

**Comment by wimrijnders** [comment]
OK, so I'm bad at letting things go. I'll do the actual fix in my free time, then. 

Workaround, add this to options:
```js
 layout: {
   improvedLayout: false
 }
```

Note the complete absence of any obvious relation to image loading.....

----
Confirmed. Thanks for reporting.

**Comment by brunobraga** [comment]
No worries, thanks for the awesome quick reply!

Confirm that the improvedLayout setting fixes it. I was actually pushing the setting to every node, which also works fine.

**Comment by wimrijnders** [comment]
OK, examined with the debugger. During layout initialization, a clustering step is performed as a preliminary to determining the strategy for calculating the initial layout of the network.

So, cluster nodes are created, used, and then released after the layout has been done - or restored, if the 'improvedLayout' layout strategy is skipped.

The thing here is that the cluster nodes are initialized with `shape: images`, as specified by the nodes options. But then, no associated image is provided (as happens with the nodes, where the `image`  field is set).

In normal operation, I would just inform you that you should supply an image to the cluster as well. However, in this case, the cluster node(s) is actually created behind the scenes as an optimization step. You have no control over it and in fact never requested its presence.

So, the thing to do is ensure that the hidden cluster nodes are not initialized as `type: 'image'`, ever. Thankfully, this is an easy fix. Also, I'm going to be all paranoid about this and check if there are any other options which can cause similar behaviour (I mean grinding the display to a halt).

----
Good catch! Thanks to your input, `Network` will be just that tiny bit robuster - and in fact, this leads to some performance improvement for layout initialization. Here, have an internet beer 🍺.

**Comment by wimrijnders** [comment]
A consequence of the fix is that you may see the following warning in the console:

> This network could not be positioned by this version of the improved layout algorithm. Please disable improvedLayout for better performance.

You can safely ignore this; the workaround supplied above will prevent it. It's kind of ironic that current issue leads to the situation that `improvedLayout`, which caused the error in the first place, is ultimately  not used. Oh well.

**Comment by brunobraga** [comment]
Awesome!

Thanks for the quick fix and the "beer"!!!

**Comment by wimrijnders** [comment]
🍻 !

**Comment by codenoid** [comment]
this doesn;'t work sir
