### ISSUE TITLE
network.getConnectedNodes() direction not working

### ISSUE THREAD

**Issue by jeganwbc** [almende/vis#3484]
I used the **network.getConnectedNodes(nodeid,["from"])** in new vis js version(4.20.1).
but it's not working. 

It gives the result for get all the nodes. Please give any examples for this function.

Thank You..!

**Comment by wimrijnders** [comment]
Did a quick check, working fine. Can you give an example in which it fails?

Call examples:

```js
    console.log(network.getConnectedNodes(1));
    console.log(network.getConnectedNodes(1, 'from'));
    console.log(network.getConnectedNodes(1, 'to'));
```

**Comment by jeganwbc** [comment]
Thanks Sir..!

**Comment by wimrijnders** [comment]
I should have timed that, quickest issue+fix ever.

**Comment by jeganwbc** [comment]
In Vis Website Documentation is not defined correctly.so i wrongly type the code.

**[String direction ]** in array.
 so i wrongly type the code

![capture](https://user-images.githubusercontent.com/28730476/30808072-34717b70-a21a-11e7-8f9a-e5cec59169fe.PNG)

**Comment by wimrijnders** [comment]
Ah. Ok, in the documentation `[....]` means 'optional', so you don't need to give that parameter. I can understand where the confusion comes from.
