### ISSUE TITLE
Edge arrow looks misplaced

### ISSUE THREAD

**Issue by viridium** [almende/vis#349]
When enabling arrows in edges, the arrow ends up not respecting the curvature of the edge, or vice versa, depending on how you look at it. See the attached screenshot.

The arrow should tilt so as to make it look as an extension of the edge.

Even better, the curvature of the edge should change slightly to account for the existence of the arrow.

**Comment by AlexDM0** [comment]
Hi Viridium,,

I have pushed a fix for this to the develop branch.

Regards,

Alex
