### ISSUE TITLE
Timeline: reduce grid width

### ISSUE THREAD

**Issue by nikolasrangel** [almende/vis#3491]
Hi!

How can I reduce the grid width?

![2017-09-27 14_31_50-timeline _ templates](https://user-images.githubusercontent.com/18116811/30928106-f9ba057e-a390-11e7-8822-52c8a0220aae.png)

Thanks,

Nikolas

**Comment by yotamberk** [comment]
I don't understand the question

**Comment by nikolasrangel** [comment]
Hi!
I want to reduce the width between the months. 
Is this possible?
Thx

**Comment by yotamberk** [comment]
Have you tried to define the timeline's width?

**Comment by nikolasrangel** [comment]
Yes. I need this width because I’ll populate the timeline. 
I need to reduce like the zoom out in mouse scroll event.  
Tks

**Comment by nikolasrangel** [comment]
My solution for the problem was use timeline.zoomIn(x) and timeline.zoomOut(x) and works fine!
