### ISSUE TITLE
Font Awesome Stacked Icons support

### ISSUE THREAD

**Issue by KunalAppensure** [almende/vis#3493]
Hi ,
I want to use Font Awesome Stacked Icons in vis js network node icons, can we use them ? If yes plz guide how to write that code into node module.
Thanks

**Comment by wimrijnders** [comment]
Please check the [icon example](http://visjs.org/examples/network/nodeStyles/icons.html).
And please, from now on, resolve to check the examples before asking questions like this.

**Comment by KunalAppensure** [comment]
Hi wimrijnders,
Above mentioned example only illustrates the simple use of Font Awesome Icons,
and I am not looking for this. Stacked Icons  allows us to use two or more icons at same position.
Can we do those stacking of icons in vis js .

**Comment by KunalAppensure** [comment]
Thanks for quick response  :+1:

**Comment by wimrijnders** [comment]
Closed because duplicate. Any further work will be done in #2966.
