### ISSUE TITLE
Edge does not always touch the end of the shape

### ISSUE THREAD

**Issue by viridium** [almende/vis#350]
When the shape is database, connected edges may appear to end unnaturally very close, but without touching the figure. Such edges appear to be disconnected. Consider fixing.

http://imgur.com/D0Fuefq

**Comment by AlexDM0** [comment]
With the last change to the arrow drawing system, this should be better. We will not make a function to connect exactly to all shapes since some are not really mathematically describable.

With that I think we can close this issue.

Cheers!
