### ISSUE TITLE
Edges in dataset may no longer be visible even if valid nodes exist.

### ISSUE THREAD

**Issue by justinharrell** [almende/vis#3500]
Based on internal state changes made in #3330 unconnected edges that later become connected due to node dataset modifications no longer appear on the graph until the edge itself is updated.

This is a change in behavior, previously unconnected / invalid edges, those which the from or to node id does not exist, where not drawn on the graph. However when a node was updated or added that completed the connection it was displayed in the graph without further intervention.

The old behavior allowed out of order operations, such that edges could be added before their respective nodes and nodes could be removed and re-added with edges following them properly. Now the developer must update any affected edge if a node is updated completing the connection or always add nodes before their edges.

Discussion in #3330 determined this as a bug and not intended behavior.

I am working on a fix and will submit a PR.

**Comment by wimrijnders** [comment]
And an extra :+1: for picking it up yourself.

**Comment by justinharrell** [comment]
No problem it allows me to get a better understanding of that area in the code and I happen to have time to devote to it.
