### ISSUE TITLE
widthConstraint no longer has any effect

### ISSUE THREAD

**Issue by justinharrell** [almende/vis#3517]
After PR #3486 widthConstraint no longer seems to have any effect.

I noticed this in our networks after rebasing and confirmed by navigating to: vis/test/network/maximumWidthEdgeCase.html

Before:

![widthconstraint 1](https://user-images.githubusercontent.com/1933008/31096981-c6fdaa92-a78b-11e7-9771-4ea13e211de9.PNG)

After:

![widthconstraint 2](https://user-images.githubusercontent.com/1933008/31096991-cc932040-a78b-11e7-9011-32241e45ec76.PNG)

**Comment by wimrijnders** [comment]
Confirmed. The constraint values were overwritten in the new multifont option handling.
