### ISSUE TITLE
Hierarchical network with sortMethod: "directed" places nodes at the wrong level

### ISSUE THREAD

**Issue by Moghul** [almende/vis#3521]
I have a Network chart with a hierarchical layout and a "directed" sort method.

My data is dynamic and therefore the levels are unknown to me before the creation of the chart. I get my values, and add the nodes and the edges.

Expected behaviour:
The nodes are added in random order and the library sorts out the levels for me.

Actual behaviour:
If a node's level changes, its children/parents are not affected correctly.
[Fiddle](https://jsfiddle.net/Lm9vL2rj/5/)
The level of Five is incorrect.

Moving lines 19-21 to the bottom of the add pile more or less fixes the issue, but at this time, I have no way of knowing which node comes when. The array of nodes and edges comes from the server in pretty much alphabetical order.

**Comment by wimrijnders** [comment]
I swear I've seen this before, only I can't find the relevant issue. I'll leave out the `Duplicate` until I do and treat it separate.

OK, noted. I can verify this is happening, but I'll need to debug to understand why.

**Comment by Moghul** [comment]
No worries, there could be an issue out there that's just phrased similarly.

If it helps, reordering the edges array does 'fix' this. However, I have been unable to find an order that makes sense for more than one or two extra levels.

**Comment by wimrijnders** [comment]
Yeah. It's just that I have this terrible feeling of deja vu. But that somehow implies that I should also know the solution, since I fixed it before. Right? This is probably wishful thinking.....

**Comment by wimrijnders** [comment]
[**This is the issue I meant** ](https://github.com/almende/vis/issues/2311#issuecomment-298223042). I would have never found it if someone didn't just post on it. I'm glad I got that out of my system.

It also explains why it still doesn't work, that fix wasn't good and it wasn't merged. So, this will need a fresh start with a fresh view.

**Comment by wimrijnders** [comment]
The good new is that that commenter is willing to pick up the issue. Do you mind if I mark this issue as a duplicate and use the other as the main one?

**Comment by Moghul** [comment]
Of course not, I'll be watching that one instead.

**Comment by wimrijnders** [comment]
Duplicate of #2311.
