### ISSUE TITLE
How to resize nodes at runtime

### ISSUE THREAD

**Issue by umpani** [almende/vis#3524]
This is not a real bug, but a question. Its a duplicate of [this](https://stackoverflow.com/questions/46472473/vis-js-how-to-resize-nodes-at-runtime):

I would like to resize nodes of a vis.js network at runtime. My goal is to create a slidercontrol to expand all nodes (an labels) or collapse them.

At first, I tryed to manipulate the Scaling values. 
```
var options = {nodes: {scaling: {label: {max: 180 , maxVisible: 180}}}};
network.setOptions(options); 
```

But there are no results.
My second idea was to manipulate the value value of every single node.

```
  function IncNodeSize(Increment) { 
      var CurrentNodes = nodesDS.get() ;
      for (var i = 0; i < CurrentNodes.length; i++) {
          CurrentNodes[i].value = CurrentNodes[i].value + 100;
        }
      }        
      nodesDS.update(CurrentNodes); 
    }
```

But this doesn't work either.

Has anyone an idea how to resize nodes at runtime?

Thx Umpani

**Comment by wimrijnders** [comment]
I would think that the `scaling` set of options would be workable here, surprised it isn't. Do you perhaps have an example network to try it out with?

**Comment by umpani** [comment]
Hi,

use this example [Network | sizing](http://visjs.org/examples/network/data/scalingCustom.html) and insert tis code by using the browser console. It change the max scaling value from 150 to 500.

```
      var options = {
        nodes: {
          shape: 'dot',
          scaling: {
            customScalingFunction: function (min,max,total,value) {
              return value/total;
            },
            min:5,
            max:500
          }
        }
      };
network.setOptions(options);
```

This one is working (changing the shape of the nodes)
```

      var options = {
        nodes: {
          shape: 'dot'
        }
      };
network.setOptions(options); 
```

**Comment by wimrijnders** [comment]
OK. so the `scaling` options set the extremes of the allowable scaling values. You still need to change the `value` fields of the nodes to change the sizes. In effect, you need to combine the two things you tried.

In the [given example](http://visjs.org/examples/network/data/scalingCustom.html), change to the following:

```js
...
      nodes = new vis.DataSet([
...
      ]);
...
      edges = new vis.DataSet([
      ]);
...
```

Now, find a way to scale a node. Here's a silly example:

```js
function resize() {
  var prev = nodes.get(1);
  nodes.update({id:1, value: prev.value*1.2});
  setTimeout(resize, 1000);
}

resize();
```

**Comment by umpani** [comment]
Hi,

thank you very much. The combination of both is working.

Umpani

**Comment by wimrijnders** [comment]
Great! Please close the issue if you're done.
