### ISSUE TITLE
Change color of nodes in groups option

### ISSUE THREAD

**Issue by DaTebe** [almende/vis#3526]
Hello,

I know that usually there's no room for questions here. But I'm not sure if the behavior of _vis. js_ could possibly be a bug. I have created groups to which I can assign nodes. I have also added icons from Fontawesome to them.

I took this example as a starting point: [vis.js icons](http://visjs.org/examples/network/nodeStyles/icons.html)

I would like to change the `hover` and `highlight` color as well as the standard color.
The documentation says that I can use all options of nodes in the groups option that make sense ([Documentation Groups](http://visjs.org/docs/network/groups.html#)). And I think `color` makes sense.
I've tried this:

```
var options={
  groups: {
    table: {
      shape: 'icon',
      icon: {
        face: 'FontAwesome',
        code: '\uf0ce',
        size: 50
      },
      color: {
        background: '#008CBA',
        border: '#008CBA',
        highlight: {
          border: '#5BC0DE',
          background: '#5BC0DE'
        },
        hover: {
          border: '#5BC0DE',
          background: '#5BC0DE'
        }
      }
    }
  }
}
```
and this:

```
var options={
  groups: {
    table: {
      shape: 'icon',
      icon: {
        face: 'FontAwesome',
        code: '\uf0ce',
        size: 50,
        color: {
          background: '#008CBA',
          border: '#008CBA',
          highlight: {
            border: '#5BC0DE',
            background: '#5BC0DE'
          },
          hover: {
            border: '#5BC0DE',
            background: '#5BC0DE'
          }
        }
      }

    }
  }
}
```

Am I doing something wrong? Is the feature not wanted at all? Is it a bug?

**Comment by wimrijnders** [comment]
Option `color` and its children are not supported for icons. It has to do with them actually being characters in a font, so you are actually setting a font color for them. As in the example:

```js
        groups: {
          usergroups: {
            shape: 'icon',
            icon: {
              face: 'FontAwesome',
              code: '\uf0c0',
              size: 50,
              color: '#57169a'   // <=== The usual way to set.
            }
          },
...

```

But still, there is no `hover` and `highlight` for them. Yet. Sorry.

**Comment by wimrijnders** [comment]
Duplicate of #2608.

**Comment by DaTebe** [comment]
Thank you for the feedback and related issue!

I think [#2608](https://github.com/almende/vis/issues/2608) is the right place to discuss further details.

Many Thanks!
