### ISSUE TITLE
I want to add a new node label name.Can I do it ?

### ISSUE THREAD

**Issue by cloudyshine** [almende/vis#3540]
Excuse me,I am learning to use this js,and I want to realize that after clicking a node,I will make a new label name above the node.Can you implement it?

**Comment by wimrijnders** [comment]
There are two parts of this question:

- Click on a node to change the label - this is possible, and yes you can do it. Have a look at the `click` event in the [documentation](http://visjs.org/docs/network/) to figure this out.
- Set a label above the node - This is not current functionality; depending on the node type, you can set the label within the node or below it. Would this be acceptable?

Setting a label *above* a node is possible if you're willing to put some extra work in it. Consult event `afterDrawing`, again in the [docs](http://visjs.org/docs/network/). It comes down to drawing the label yourself at the right moment.

**Comment by wimrijnders** [comment]
> Can you implement it?

No, not right now. Multiple labels per node is something I do intend to add, but it's a really long-term thing. With the current code, this is not trivial.

**Comment by AndrewMut** [comment]
```
      network.on("afterDrawing", function(ctx) {
        var fullListOfVisibleNodes = Object.keys(network.getPositions());

        fullListOfVisibleNodes.forEach(function(value) {
          
          var nodePosition = network.getPositions(value);
          var customlabel = "Label That You Need";
          var boundingBoxSize = network.getBoundingBox(value);

          var labelX = nodePosition[value].x;
          var labelY = boundingBoxSize.top - 10;

          ctx.fillStyle = '#fff';
          ctx.font = 12 + "px Arial";

          ctx.fillText(customlabel, labelX, labelY);
        });
      });
```
This is how you can add custom label. And then just as said @wimrijnders use click events.

**Comment by cloudyshine** [comment]
It worked, Thank you very much
