### ISSUE TITLE
The node display order varies from one browser to another

### ISSUE THREAD

**Issue by melody00713** [almende/vis#3542]
the same data,but in different browser,the node display order is difference

chrome 
![image](https://user-images.githubusercontent.com/19607191/31367996-87c8f46c-adad-11e7-872e-faa00c74eb26.png)

firefox:
![image](https://user-images.githubusercontent.com/19607191/31368012-94317f58-adad-11e7-9f2e-9c0c23822f1a.png)

**Comment by wimrijnders** [comment]
I'm not sure if this is a question or a problem. Can you clarify a bit further?

**Comment by melody00713** [comment]
Why are the same data displayed differently in different browsers? I want different browsers to display the same effect

**Comment by wimrijnders** [comment]
Fair question. Would you mind making an example for this network? The data definition + used options will do.

**Comment by melody00713** [comment]
`
var res = {
  "code": "200",
  "data": {
    "host": [
      {
        "hostName": "dev.easted.aio",
        "id": "69b113f3-87b8-4a49-80e3-4ae394a8ee50",
        "name": "dev.easted.aio",
        "network": [
          {
            "id": "network4",
            "name": "vserverm"
          },
          {
            "id": "network1",
            "name": "net-vlan3"
          },
          {
            "id": "network2",
            "name": "net-vlan199"
          }
        ],
        "storage": [
          {
            "id": "1521e11f-77ed-47da-a232-405599268358",
            "name": "13-SSD-01"
          },
          {
            "id": "e27f36f7-e40e-4c75-af31-628abc98cba0",
            "name": "13-SSD-02"
          },
          {
            "id": "ff6493ab-6d90-43ef-8303-33206218ddd3",
            "name": "13-SATA-03"
          },
          {
            "id": "b389fb22-e066-44a2-a2d7-5e14fcb318d1",
            "name": "13-SATA-02"
          },
          {
            "id": "0a78077f-cd3c-4733-ad66-aa897bdfca67",
            "name": "13-SATA-01"
          }
        ],
        "vm": [
          {
            "id": "ac0b12b6-c378-472f-92b8-a53f69453b16",
            "name": "yangwu"
          },
          {
            "id": "d11fcaef-487c-45b3-89b8-f376607ed87d",
            "name": "weizoujianUbuntu"
          },
          {
            "id": "4a0b00b8-991d-4b1f-a291-aa6b2c346034",
            "name": "wanghao-linux"
          },
          {
            "id": "1dc173bd-de60-414f-807e-a59c8c7bb841",
            "name": "CI-linux-node"
          },
          {
            "id": "d773884d-76e9-469f-89d8-7fc22c6df084",
            "name": "000-DEV-Y"
          },
          {
            "id": "440f6d6b-1f64-44c2-988c-67155b105d4a",
            "name": "CI-master"
          },
          {
            "id": "3380623a-2480-450a-9ee9-7eebc112eed3",
            "name": "000-13-1"
          },
          {
            "id": "cb885cdf-2d12-4fd0-8b75-0176d7bf36c0",
            "name": "wanghao-1"
          },
          {
            "id": "f6a39af0-56cd-4d85-8945-c33688c18649",
            "name": "yinyongy"
          },
          {
            "id": "49445b33-33fa-4141-a31a-c69c3eefc2fb",
            "name": "liuyatao"
          },
          {
            "id": "8b60bee6-8d4c-4a22-a10b-3cd83cd3c6b9",
            "name": "yiny"
          },
          {
            "id": "79776528-7257-4369-b43c-39cf4658ecd7",
            "name": "CI-maven"
          },
          {
            "id": "8c5a6e5f-34c6-4d91-9ee7-7705881a4db4",
            "name": "weizoujianCentOS"
          },
          {
            "id": "edd4b8bf-89a6-494a-9cdb-373b15bc2cb0",
            "name": "Linux-Dev"
          }
        ]
      },
      {
        "hostName": "aio14.easted.vs",
        "id": "37af668f-3105-4437-b0ea-1f3db1eae110",
        "name": "local_host",
        "network": [
          {
            "id": "network4",
            "name": "vserverm"
          }
        ],
        "storage": [
          {
            "id": "60863280-2247-481e-92da-63347c22d5cf",
            "name": "资源池14-SATA01"
          },
          {
            "id": "df6b00b4-27ea-4f21-ac36-44506c9e0ed0",
            "name": "资源池14-SSD01"
          },
          {
            "id": "805c3464-0ef4-4e18-b9bf-80385b1e65c3",
            "name": "资源池14-local_storage"
          },
          {
            "id": "05d956a1-9cf8-4477-8e83-c62f0a9425e1",
            "name": "资源池14-SSD02"
          }
        ],
        "vm": [
          {
            "id": "6df209a2-353b-4739-9526-faca1d2dc3d6",
            "name": "auto123-2"
          },
          {
            "id": "9bbdf450-a5ab-438e-b845-9a63b948f250",
            "name": "win10x64test001"
          },
          {
            "id": "83f80bac-b85a-483e-9201-5f7bec9465b7",
            "name": "Fuc123-3"
          },
          {
            "id": "7bb30c73-ab0a-45e7-94df-2377e5ec8277",
            "name": "EDM-client"
          },
          {
            "id": "493defeb-df16-4cfb-92b7-828e8d6918df",
            "name": "auto123-1"
          },
          {
            "id": "7862886d-9009-4830-b603-73de7f14a267",
            "name": "auto123-3"
          },
          {
            "id": "ea692551-3f28-4188-9d4e-3f6abb23a26d",
            "name": "Fuc123-1"
          },
          {
            "id": "1fa435e2-2adb-404e-a9ba-9a0deb9e3b25",
            "name": "win7ent32test002"
          },
          {
            "id": "a4ff94c1-2317-489b-a821-a179ecf4492c",
            "name": "A_xiao_win7ent64"
          },
          {
            "id": "fdfb586e-8d2d-4a9e-aa4d-70fbfbd34ec9",
            "name": "guoxn02-1"
          },
          {
            "id": "3b387a32-f88d-456e-97f4-a65c4213eb65",
            "name": "Fuc123-2"
          },
          {
            "id": "a40bba7c-5fa6-4744-8c7f-507a1aa9e362",
            "name": "Win7Ultra64ForWinRDP-1"
          }
        ]
      }
    ],
    "network": [
      {
        "id": "network5",
        "name": "testingby"
      },
      {
        "id": "network2",
        "name": "net-vlan199"
      },
      {
        "id": "network1",
        "name": "net-vlan3"
      },
      {
        "id": "network4",
        "name": "vserverm"
      }
    ],
    "storage": [
      {
        "id": "0a78077f-cd3c-4733-ad66-aa897bdfca67",
        "name": "13-SATA-01"
      },
      {
        "id": "1521e11f-77ed-47da-a232-405599268358",
        "name": "13-SSD-01"
      },
      {
        "id": "b389fb22-e066-44a2-a2d7-5e14fcb318d1",
        "name": "13-SATA-02"
      },
      {
        "id": "e27f36f7-e40e-4c75-af31-628abc98cba0",
        "name": "13-SSD-02"
      },
      {
        "id": "ff6493ab-6d90-43ef-8303-33206218ddd3",
        "name": "13-SATA-03"
      },
      {
        "id": "05d956a1-9cf8-4477-8e83-c62f0a9425e1",
        "name": "资源池14-SSD02"
      },
      {
        "id": "60863280-2247-481e-92da-63347c22d5cf",
        "name": "资源池14-SATA01"
      },
      {
        "id": "805c3464-0ef4-4e18-b9bf-80385b1e65c3",
        "name": "资源池14-local_storage"
      },
      {
        "id": "df6b00b4-27ea-4f21-ac36-44506c9e0ed0",
        "name": "资源池14-SSD01"
      }
    ]
  },
  "msg": "success"
}
       var nodesOpt = []
        var edgesOpt = []
        res.data.storage.forEach((v, k) => {
          nodesOpt.push({
            id: v.id,
            label: v.name,
            image: storageImg,
            shape: 'image',
            level: 3,
            group: 'storage',
            widthConstraint: {
              maximum: 20
            }
          })
        })
        res.data.network.forEach((v, k) => {
          nodesOpt.push({
            id: v.id,
            label: v.name,
            image: networkImg,
            shape: 'image',
            level: 4,
            group: 'network',
            widthConstraint: {
              maximum: 20
            }
          })
        })
        res.data.host.forEach((v, k) => {
          nodesOpt.push({
            id: v.id,
            label: v.name,
            image: hostImg,
            shape: 'image',
            level: 2,
            group: 'host',
            widthConstraint: {
              maximum: 20
            }
          })
          v.storage.forEach(n => {
            edgesOpt.push({
              from: v.id, to: n.id, color: '#fc9295'
            })
          })
          v.network.forEach(n => {
            edgesOpt.push({
              from: v.id, to: n.id, color: '#5db8dd'
            })
          })
          v.vm.forEach(n => {
            nodesOpt.push({
              id: n.id,
              label: n.name,
              image: vm,
              shape: 'image',
              level: 1,
              group: 'vm',
              widthConstraint: {
                maximum: 20
              }
            })
            edgesOpt.push({
              from: v.id,
              to: n.id,
              dashes: true,
              color: '#001c83'
            })
          })
        })
        var nodes = new vis.DataSet(nodesOpt)
        // create an array with edges
        var edges = new vis.DataSet(edgesOpt)
        // create a network
        var container = document.getElementById('topological')
        var data = {
          nodes: nodes,
          edges: edges
        }
        var options = {
          groups: {
            storage: {},
            network: {},
            host: {},
            vm: {}
          },
          layout: {
            hierarchical: {
              direction: 'UD',
              sortMethod: 'directed',
              nodeSpacing: 150
            }
          },
          interaction: {dragNodes: false},
          physics: {
            enabled: false
          },
          configure: {
            filter: function (option, path) {
              if (path.indexOf('hierarchical') !== -1) {
                return true
              }
              return false
            },
            showButton: false
          }
        }
        var network = new vis.Network(container, data, options)
`
this is my code , u can run it, if my code have some question please tell me

I want the same type of nodes together and have a background color, similar to the figure below, but I don't know how to set them  ,tks

![qq 20171010135558](https://user-images.githubusercontent.com/19607191/31371427-41389c1c-adc3-11e7-97c9-9494be684c2a.png)

**Comment by wimrijnders** [comment]
I managed to get this to work, sort of. While the networks I'm getting on firefox and chrome (linux) are not the same in layout to your first example, they *are* identical to each other.

Which version of `vis.js`  are you using? And which OS?

**Comment by melody00713** [comment]
i used vis v4.20.1 and os is Windows

**Comment by wimrijnders** [comment]
Right. Windows sometimes insists on integer values for pixel coordinates, it might the the problem is in that direction. I mean that, due to small differences in coordinates, the layout turns out to be slightly different.

@justinharrell, any chance that you can look into this? If required, I can supply you the code that made the image above.

**Comment by melody00713** [comment]
hi，I just tested it on Linux, the same to Windows. How did you do before?tks

**Comment by wimrijnders** [comment]
I took all the code you posted and verbatim plunked it in a demo page. Since the images were missing, I added one I had at hand:

![bartender-icon](https://user-images.githubusercontent.com/769037/31376197-669cbd0e-ada4-11e7-8d97-a09fc416581e.png)

This implies that there are still differences between your and my code. Rather than blunder along, would you mind making a demo in `jsfiddle` or suchlike that reproduces your problem? I think now is a good time.

**Comment by melody00713** [comment]
hostImg
![host](https://user-images.githubusercontent.com/19607191/31377951-5be7689a-addc-11e7-812d-8e199e77cd2d.png)
networkImg
![cloud](https://user-images.githubusercontent.com/19607191/31378542-388708f4-adde-11e7-950c-b276952c4918.png)
storageImg
![storage](https://user-images.githubusercontent.com/19607191/31378550-3e52b530-adde-11e7-8ced-e136c7fc0cb4.png)
vm
![vm](https://user-images.githubusercontent.com/19607191/31378531-32a8af14-adde-11e7-9727-91ad04a0e9a0.png)

These are the pictures I use, and you can try them again, which is more convenient for you to see，tks

**Comment by melody00713** [comment]
`
var res = {
  "code": "200",
  "data": {
    "host": [
      {
        "hostName": "dev.easted.aio",
        "id": "69b113f3-87b8-4a49-80e3-4ae394a8ee50",
        "name": "dev.easted.aio",
        "network": [
          {
            "id": "network4",
            "name": "vserverm"
          },
          {
            "id": "network1",
            "name": "net-vlan3"
          },
          {
            "id": "network2",
            "name": "net-vlan199"
          }
        ],
        "storage": [
          {
            "id": "1521e11f-77ed-47da-a232-405599268358",
            "name": "13-SSD-01"
          },
          {
            "id": "e27f36f7-e40e-4c75-af31-628abc98cba0",
            "name": "13-SSD-02"
          },
          {
            "id": "ff6493ab-6d90-43ef-8303-33206218ddd3",
            "name": "13-SATA-03"
          },
          {
            "id": "b389fb22-e066-44a2-a2d7-5e14fcb318d1",
            "name": "13-SATA-02"
          },
          {
            "id": "0a78077f-cd3c-4733-ad66-aa897bdfca67",
            "name": "13-SATA-01"
          }
        ],
        "vm": [
          {
            "id": "ac0b12b6-c378-472f-92b8-a53f69453b16",
            "name": "yangwu"
          },
          {
            "id": "d11fcaef-487c-45b3-89b8-f376607ed87d",
            "name": "weizoujianUbuntu"
          },
          {
            "id": "4a0b00b8-991d-4b1f-a291-aa6b2c346034",
            "name": "wanghao-linux"
          },
          {
            "id": "1dc173bd-de60-414f-807e-a59c8c7bb841",
            "name": "CI-linux-node"
          },
          {
            "id": "d773884d-76e9-469f-89d8-7fc22c6df084",
            "name": "000-DEV-Y"
          },
          {
            "id": "440f6d6b-1f64-44c2-988c-67155b105d4a",
            "name": "CI-master"
          },
          {
            "id": "3380623a-2480-450a-9ee9-7eebc112eed3",
            "name": "000-13-1"
          },
          {
            "id": "cb885cdf-2d12-4fd0-8b75-0176d7bf36c0",
            "name": "wanghao-1"
          },
          {
            "id": "f6a39af0-56cd-4d85-8945-c33688c18649",
            "name": "yinyongy"
          },
          {
            "id": "49445b33-33fa-4141-a31a-c69c3eefc2fb",
            "name": "liuyatao"
          },
          {
            "id": "8b60bee6-8d4c-4a22-a10b-3cd83cd3c6b9",
            "name": "yiny"
          },
          {
            "id": "79776528-7257-4369-b43c-39cf4658ecd7",
            "name": "CI-maven"
          },
          {
            "id": "8c5a6e5f-34c6-4d91-9ee7-7705881a4db4",
            "name": "weizoujianCentOS"
          },
          {
            "id": "edd4b8bf-89a6-494a-9cdb-373b15bc2cb0",
            "name": "Linux-Dev"
          }
        ]
      },
      {
        "hostName": "aio14.easted.vs",
        "id": "37af668f-3105-4437-b0ea-1f3db1eae110",
        "name": "local_host",
        "network": [
          {
            "id": "network4",
            "name": "vserverm"
          }
        ],
        "storage": [
          {
            "id": "60863280-2247-481e-92da-63347c22d5cf",
            "name": "资源池14-SATA01"
          },
          {
            "id": "df6b00b4-27ea-4f21-ac36-44506c9e0ed0",
            "name": "资源池14-SSD01"
          },
          {
            "id": "805c3464-0ef4-4e18-b9bf-80385b1e65c3",
            "name": "资源池14-local_storage"
          },
          {
            "id": "05d956a1-9cf8-4477-8e83-c62f0a9425e1",
            "name": "资源池14-SSD02"
          }
        ],
        "vm": [
          {
            "id": "6df209a2-353b-4739-9526-faca1d2dc3d6",
            "name": "auto123-2"
          },
          {
            "id": "9bbdf450-a5ab-438e-b845-9a63b948f250",
            "name": "win10x64test001"
          },
          {
            "id": "83f80bac-b85a-483e-9201-5f7bec9465b7",
            "name": "Fuc123-3"
          },
          {
            "id": "7bb30c73-ab0a-45e7-94df-2377e5ec8277",
            "name": "EDM-client"
          },
          {
            "id": "493defeb-df16-4cfb-92b7-828e8d6918df",
            "name": "auto123-1"
          },
          {
            "id": "7862886d-9009-4830-b603-73de7f14a267",
            "name": "auto123-3"
          },
          {
            "id": "ea692551-3f28-4188-9d4e-3f6abb23a26d",
            "name": "Fuc123-1"
          },
          {
            "id": "1fa435e2-2adb-404e-a9ba-9a0deb9e3b25",
            "name": "win7ent32test002"
          },
          {
            "id": "a4ff94c1-2317-489b-a821-a179ecf4492c",
            "name": "A_xiao_win7ent64"
          },
          {
            "id": "fdfb586e-8d2d-4a9e-aa4d-70fbfbd34ec9",
            "name": "guoxn02-1"
          },
          {
            "id": "3b387a32-f88d-456e-97f4-a65c4213eb65",
            "name": "Fuc123-2"
          },
          {
            "id": "a40bba7c-5fa6-4744-8c7f-507a1aa9e362",
            "name": "Win7Ultra64ForWinRDP-1"
          }
        ]
      }
    ],
    "network": [
      {
        "id": "network5",
        "name": "testingby"
      },
      {
        "id": "network2",
        "name": "net-vlan199"
      },
      {
        "id": "network1",
        "name": "net-vlan3"
      },
      {
        "id": "network4",
        "name": "vserverm"
      }
    ],
    "storage": [
      {
        "id": "0a78077f-cd3c-4733-ad66-aa897bdfca67",
        "name": "13-SATA-01"
      },
      {
        "id": "1521e11f-77ed-47da-a232-405599268358",
        "name": "13-SSD-01"
      },
      {
        "id": "b389fb22-e066-44a2-a2d7-5e14fcb318d1",
        "name": "13-SATA-02"
      },
      {
        "id": "e27f36f7-e40e-4c75-af31-628abc98cba0",
        "name": "13-SSD-02"
      },
      {
        "id": "ff6493ab-6d90-43ef-8303-33206218ddd3",
        "name": "13-SATA-03"
      },
      {
        "id": "05d956a1-9cf8-4477-8e83-c62f0a9425e1",
        "name": "资源池14-SSD02"
      },
      {
        "id": "60863280-2247-481e-92da-63347c22d5cf",
        "name": "资源池14-SATA01"
      },
      {
        "id": "805c3464-0ef4-4e18-b9bf-80385b1e65c3",
        "name": "资源池14-local_storage"
      },
      {
        "id": "df6b00b4-27ea-4f21-ac36-44506c9e0ed0",
        "name": "资源池14-SSD01"
      }
    ]
  },
  "msg": "success"
}
var nodesOpt = []
        var edgesOpt = []
        res.data.storage.forEach((v, k) => {
          nodesOpt.push({
            id: v.id,
            label: v.name,
            image: storageImg,
            shape: 'image',
            level: 3,
            group: 'storage',
            widthConstraint: {
              maximum: 20
            }
          })
        })
        res.data.network.forEach((v, k) => {
          nodesOpt.push({
            id: v.id,
            label: v.name,
            image: networkImg,
            shape: 'image',
            level: 3,
            group: 'network',
            widthConstraint: {
              maximum: 20
            }
          })
        })
        res.data.host.forEach((v, k) => {
          nodesOpt.push({
            id: v.id,
            label: v.name,
            image: hostImg,
            shape: 'image',
            level: 2,
            group: 'host',
            widthConstraint: {
              maximum: 20
            }
          })
          v.storage.forEach(n => {
            edgesOpt.push({
              from: v.id, to: n.id, color: '#fc9295'
            })
          })
          v.network.forEach(n => {
            edgesOpt.push({
              from: v.id, to: n.id, color: '#5db8dd'
            })
          })
          v.vm.forEach(n => {
            nodesOpt.push({
              id: n.id,
              label: n.name,
              image: vm,
              shape: 'image',
              level: 1,
              group: 'vm',
              widthConstraint: {
                maximum: 20
              }
            })
            edgesOpt.push({
              from: v.id,
              to: n.id,
              dashes: true,
              color: '#001c83'
            })
          })
        })
        var nodes = new vis.DataSet(nodesOpt)
        // create an array with edges
        var edges = new vis.DataSet(edgesOpt)
        // create a network
        var container = document.getElementById('topological')
        var data = {
          nodes: nodes,
          edges: edges
        }
        var options = {
          groups: {
            storage: {},
            network: {},
            host: {},
            vm: {}
          },
          layout: {
            hierarchical: {
              direction: 'UD',
              sortMethod: 'directed',
              nodeSpacing: 150
            }
          },
          interaction: {dragNodes: false},
          physics: {
            enabled: false
          },
          configure: {
            filter: function (option, path) {
              if (path.indexOf('hierarchical') !== -1) {
                return true
              }
              return false
            },
            showButton: false
          }
        }
        var network = new vis.Network(container, data, options)
`
Sorry, I just found that there was a problem with the code I posted earlier. You can test it again

**Comment by justinharrell** [comment]
>ight. Windows sometimes insists on integer values for pixel coordinates, it might the the problem is in that direction. I mean that, due to small differences in coordinates, the layout turns out to be slightly different.

I don't think it is related to that the layout is based in pure JS, the integer issue was related to a canvas drawing API after the node position is determined.

Just a quick look at the hierarchical layout code it may have something to do with how browsers handle object property order differently. Chrome seems to be different here I think, and vis.js looks to be using Object.keys for ordering I think:

https://github.com/almende/vis/blob/bc6330d612ef1b5e13156eee4ef8b129d01013f6/lib/network/modules/LayoutEngine.js#L1044

https://bugs.chromium.org/p/v8/issues/detail?id=164

**Comment by wimrijnders** [comment]
@melody00713 That's better, I can reproduce now. This is a good starting point for investigation.

----
Pro tip:

<pre>
```js
  // Your javascript code here.
```
</pre>

Use this to have a syntax-colored javascript code block.

**Comment by wimrijnders** [comment]
@justinharrell good find. So a way has to be devised to guarantee that the order is consistent. Thanks for looking into it.

**Comment by wimrijnders** [comment]
I'm doing a double debugging session with chromium and firefox. Findings:

- Interestingly, the difference is not in what `Object.keys()` returns, these are actually identical for both browsers.
-  What *is* different, is the order in which the nodes are handed in the sorting of the nodes:

https://github.com/almende/vis/blob/develop/lib/network/modules/components/DirectionStrategy.js#L158-L164

From the very first call, two different nodes are passed for sorting.

**Comment by wimrijnders** [comment]
Duplicate of #3403. Will be in the next release.

@melody00713 I have no workaround for you at the moment; however, the building of the next release is effectively in progress, so if you can hold out just a little bit longer, you will be OK.

**Comment by wimrijnders** [comment]
I think we're done here. Please close to confirm.

**Comment by justinharrell** [comment]
>How did you set up the code reference in your comment? can't seem to manage it.

Sorry I didn't repro it and find the issue there, it was just a quick look and remembered Chrome had some different sorting behavior on properties, didn't mean to waste your time on that one.

**Comment by wimrijnders** [comment]
That is not a waste of time, it looks truly useful for referencing code. Would like to know how to do it for future use.

**Comment by justinharrell** [comment]
Just one of those things I have seen cause problems before, using js objects as ordered dictionaries when the spec defines them as unordered. The browsers are free to internally optimize them for key access which may change their iteration order. 

The way forward are js maps: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

**Comment by wimrijnders** [comment]
Agreed. I was looking at Map myself until I discovered that the actual problem was in the sorting - which BTW may be related. And then I discovered I had already solved that elsewhere but just had forgotten. And then I felt old.

----

But what I meant is, how did you get the reference to display like this (copied from above)?


https://github.com/almende/vis/blob/bc6330d612ef1b5e13156eee4ef8b129d01013f6/lib/network/modules/LayoutEngine.js#L1044

**Comment by justinharrell** [comment]
Ah yes just click on the line number in Github and a ... will popup to the left, click that and copy permalink, very useful.

**Comment by wimrijnders** [comment]
https://github.com/almende/vis/blob/a3f9bef2c34881f51d1be0b0c0cffdf281c9e611/lib/network/modules/LayoutEngine.js#L1231-L1234

Ha! TIL 'Copy Permalink'. Thanks.

**Comment by wimrijnders** [comment]
@melody00713 this is to notify you that `4.21.0` has just been released. This should fix your issue.

**Comment by melody00713** [comment]
I downloaded the new version, it's work，the problem has been solved, thank you very much

**Comment by melody00713** [comment]
@wimrijnders hi, today I tried, and there were differences，I've upgraded to version `4.21.0`
firefox
![image](https://user-images.githubusercontent.com/19607191/31591842-21f4bde4-b256-11e7-839c-718a085962ab.png)
chrome
![image](https://user-images.githubusercontent.com/19607191/31591847-31e9b740-b256-11e7-9c97-2d0b50cf6d48.png)

**Comment by wimrijnders** [comment]
Yeah 🙁 . The fix wasn't good enough, the other person with the sorting order problem [noticed it as well](https://github.com/almende/vis/issues/3403#issuecomment-336665321). Sorry about that. I'm looking for a better solution.

**Comment by wimrijnders** [comment]
FYI, the next fix for this is in the pipeline: #3576.

**Comment by melody00713** [comment]
okay
