### ISSUE TITLE
[Graph2D] Any option to automatically adjust actual curve height to fit maxHeight ?

### ISSUE THREAD

**Issue by ostrebler** [almende/vis#3552]
Hey,

I'm using Graph2D to draw a progress curve, and I'm wondering if there is any easy or option-set way to make the height of the curve adjust itself to the graph's maxHeight ? Not setting maxHeight gives me a too high graph, but setting maxHeight masks a good part of it, instead of making the graph fit (which would be in most cases I guess an expected behaviour).

Thanks for your further response.
Olivier

## **EDIT : options.graphHeight seems to solve the issue. Sorry for that, I should have dig a little bit more.**

**Comment by wimrijnders** [comment]
Glad you found a resolution; please close the issue if you're done!
