### ISSUE TITLE
Drop external item into timeline is not working since 4.20.1

### ISSUE THREAD

**Issue by Kandarp143** [almende/vis#3558]
I have timeline web component using polymer and vis - 4.18.0 . 
I have attached event to timeline , when external drag-able item drop to the container, new item should create. 
It was working good. however for this version of vis I am unable to edit item time by moving it  so 
I have changed version to 4.20.1 , which make item editable but drop external item is not working

```
 <!-- EXTERNAL ITEM DROP WORKING , ITEM TIME EDIT NOT-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/vis/4.18.0/vis.js"></script>
  <!-- EXTERNAL ITEM DROP NOT WORKING , ITEM TIME EDIT WORKING-->
 <script src="https://cdnjs.cloudflare.com/ajax/libs/vis/4.20.1/vis.js"></script>
```
[Plunker demo](http://plnkr.co/edit/X8H41g7I9OPwOrsVblpC?p=preview)

Please help.

**Comment by mojoaxel** [comment]
I can confirm this also for 4.21.0

**Comment by yotamberk** [comment]
you now have an option in timeline for adding items. see: 
http://visjs.org/examples/timeline/other/drag&drop.html

Is this good enough?

**Comment by yotamberk** [comment]
Closed due to inactivity
