### ISSUE TITLE
Timeline: is rollingMode an object or a boolean 

### ISSUE THREAD

**Issue by bill-philip** [almende/vis#3567]
rollingMode seems to work if set to true, however the documentation suggests it is an object with follow as a boolean and offset as a number. Is there a way to set the offset for rollingMode? I don't want it to always be in the centre.

**Comment by brichbe** [comment]
Have you tried setting the `rollingMode.offset` to a non-default number value and it didn't work as you expected?

**Comment by bill-philip** [comment]
Turns out I had an earlier version that didn't work. The latest version works exactly as expected.

**Comment by brichbe** [comment]
Great, then please close this issue.
