### ISSUE TITLE
Set height of container dynamically

### ISSUE THREAD

**Issue by wapt49** [almende/vis#358]
Hi,

Is it possible to set height of div container dynamically depends on the number of network?
Instead of the node become smaller while the network getting bigger, I prefer to set my div container to be higher but the node always the same big. 

Is it possible in vis.js?

Many Thanks :)

**Comment by amithit** [comment]
I have a graph component in React app,

```
<Graph
   graph={this.state.graph}
   options={graph_options}
   events={this.events}
/>
```
I hope to make it automatically zoom in/out when the graph changes, just like in vis.js document use network.fit()
