### ISSUE TITLE
Graph theory algorithms support

### ISSUE THREAD

**Issue by avrahamcool** [almende/vis#3584]
Hello.
Do you plan to add Graph theory algorithms support?

Thanks.

**Comment by wimrijnders** [comment]
Seeing that I'm totally ignorant on what you mean, the answer has to be 'no'. But you made me curious; can you explain what you mean? Share a relevant link perhaps?

**Comment by avrahamcool** [comment]
thank you for your quick reply.

here some examples of Graph theory algorithms:
assuming I constructed a vis `DataSet` with nodes and edges that describe my graph:
`var dataSet = new DataSet(...)`

I would like to call some functions on the `DataSet` itself without the need to write complex logic.

shortest path between two nodes:
`var shortestPath = dataSet.findShortestPath(node1ID, node2ID);`

all neighbors with degree less or equal to N (I saw that there is a function to find direct neighbors):
`var neighbors = dataSet.findNeighbors(someNodeId, degree);`

more algorithms (from another similar library):
http://js.cytoscape.org/#collection/algorithms

**Comment by wimrijnders** [comment]
OK, clear. Thanks for the info. I still don't think that this will be added any time soon.

The reason for this, as I see it, is that `vis.Network` is a graph visualization module, and as such it does its best to render these graphs. It is not meant for graph analysis in any way. I feel the mentioned functionality is outside the scope of the module, it should be done elsewhere.

I hope you can understand this.

**Comment by avrahamcool** [comment]
Ok, thank you again.

for the completeness of the question (although it don't changes the answer):
this functions belong in the `Network` and not in the `DataSet`. (I edited the original question)
