### ISSUE TITLE
Add test coverage reports to Pull Requests using Code Climate

### ISSUE THREAD

**Issue by mbroad** [almende/vis#3601]
After finishing https://github.com/almende/vis/pull/3575 , it is not much more effort to make use of a 3rd party service that hosts per-build code coverage reports, and compares current coverage against an incoming PR's code coverage.

See code climate https://codeclimate.com

**Comment by mojoaxel** [comment]
We already use code climate: https://codeclimate.com/github/almende/vis

**Comment by mbroad** [comment]
@mojoaxel excellent! I've edited the issue to reflect that. Thank you,

**Comment by mojoaxel** [comment]
To enable new features in codeclimate we would have to change our [.codeclimate.yml](https://github.com/almende/vis/blob/master/.codeclimate.yml).
