### ISSUE TITLE
timeline 4.20.1: 'orientation' is reset to default in setOptions

### ISSUE THREAD

**Issue by pkoesters** [almende/vis#3611]
Hi guys, 
I'm using timeline 4.20.1 and ran into an issue regarding the 'orientation' option. 
 
Setting the 'orientation' with setOptions works fine in general. The issue is that every subsequent call to setOptions that does not contain an orientation param overwrites the previous setting. 

The reason for this issue can be easily identified in the code of setOptions, right before an optional param 'orientation' is evaluated, the orientation of the instance is set to { item: undefined, axis: undefined }, thus overriding any previous value.

Thanks for the help and your awesome work!

**Comment by lewisjb** [comment]
Nice spotting! However, this was already fixed in #3405. Updating your version of vis should resolve the issue.

**Comment by yotamberk** [comment]
What he said :point_up:
