### ISSUE TITLE
Any Easy method for get all the parent nodes in vis js

### ISSUE THREAD

**Issue by jeganwbc** [almende/vis#3618]
In  **Red squared Node**(jegan), has many parent nodes.

How to **get all the parents nodes** for Red squared Node(Jegan).

![capture](https://user-images.githubusercontent.com/28730476/32051454-4d78fc72-ba72-11e7-8ede-b74dd6f4381a.PNG)

**Comment by jeganwbc** [comment]
Any simple Method for get all the parent nodes in **jegan node?**

**Comment by dheerajbapat** [comment]
I think you have to traverse by getting getConnectedNodes()

**Comment by jeganwbc** [comment]
S i will do with that..! Thanks..!
