### ISSUE TITLE
timeline and graph combine

### ISSUE THREAD

**Issue by yxuecheng** [almende/vis#3620]
hello i saw the issue attention but i have to ask a problems 

i want to draw a chart like this [link](http://almende.github.io/chap-links-library/js/timeline/examples/example19_bar_graph.html)

it looks like  timeline and histogram combine together , how can i draw it with vis.js

who can help me .thank you

**Comment by yotamberk** [comment]
Not possible yet. Excellent feature request

**Comment by yxuecheng** [comment]
may be i can achieve it like this see [jsfiddle](https://jsfiddle.net/923mdkr6/6/)

**Comment by yotamberk** [comment]
Cool! thanks for sharing
