### ISSUE TITLE
Center current date on timeline ?

### ISSUE THREAD

**Issue by taimaiduc** [almende/vis#3623]
How to set current view timeline in the current date. Not Min date dataset 

![screenshot-localhost-8000-2017-10-27-22-36-52-272](https://user-images.githubusercontent.com/10907980/32112965-fbcba5e4-bb68-11e7-8d3c-c5a061ed0a86.png)

**Comment by yotamberk** [comment]
in the options: `rollingMode: true`.
Is that what you meant?

**Comment by brichbe** [comment]
I think @taimaiduc is wanting to use the [timeline method](http://visjs.org/docs/timeline/#Methods) `moveTo`.  After constructing the timeline with your initial data/options, then call `timeline.moveTo()`, passing the current time as a parameter.  If you want the timeline to stay centered on the current time, looking into rollingMode as mentioned above.

**Comment by yxuecheng** [comment]
read the doc carefully

**Comment by brichbe** [comment]
@taimaiduc  can this issue be closed?
