### ISSUE TITLE
Network app using vis.js

### ISSUE THREAD

**Issue by safreita1** [almende/vis#3635]
Hi,

I wanted to share a project I've been working on to analyze network connectivity using seed nodes in large scale datasets. The front-end uses the vis.js library for all the dynamic network visualizations. 

Let me know if you're interested in showcasing the web application. There's a couple of sample images on the website, [PathFinder](http://path-finder.io/gallery.html), and another visually interesting one I attached to the issue:

![visualization4](https://user-images.githubusercontent.com/16739132/32156721-4a2adbf8-bcfc-11e7-94cc-c1fd9d8c8420.png)

Best regards, really enjoyed working with the library!

**Comment by mojoaxel** [comment]
@safreita1 Nice! Feel free to create a pull request for this to be added to the showcases: https://github.com/almende/vis/blob/gh-pages/showcase/index.html
