### ISSUE TITLE
the graph2d problems of timeline

### ISSUE THREAD

**Issue by yxuecheng** [almende/vis#3636]
i saw the [graph2d example](http://visjs.org/examples/graph2d/02_bars.html), when the mouse scroll, the chart was zoomed, but  the timeline doesn't zoomed,  it relally can not zoomed?

**Comment by yotamberk** [comment]
We are currently having problems maintaining Graph2d due to lack of maintainers and interest.

**Comment by yxuecheng** [comment]
so sad .... 加油！
