### ISSUE TITLE
Pie chart feature

### ISSUE THREAD

**Issue by aspersieman** [almende/vis#364]
I am not sure if it's possible, and have already consulted the docs, but I need to be able to generate pie charts. Is it possible to do this? If so, how?

Thanks in advance,
Nicol

**Comment by Puffton** [comment]
+1

Most charting libraries provide either network/graph capabilities or basic charts like pie/bar/scatter, forcing users to go with multiple charting solutions. A pie chart would bridge the gap, and it seems like the only basic feature missing in vis.js at this point.

**Comment by josdejong** [comment]
With vis.js we don't aim to be "yet another visualization library" offering a full suite of common visualizations. We build the visualizations out of need for our own business, and only develop visualizations for which we can't find a satisfying existing solution. So far, we haven't needed/missed a pie chart, therefore we don't have plans to build one. We're open to contributions from the community though, so if anyone is interested in picking this up please let us know.

**Comment by AlexDM0** [comment]
It's not necessarily difficult to make a pie chart, though I'm not sure community contributions for a full module would be a good idea. Don't get me wrong, I greatly appreciate community contributions but I feel they are more suited for features and or bug fixes of existing modules. 

We have quite a bit of backend architecture (util, domutil, dataset, validation, configurator etc) and I'm not sure if a standalone pie chart would really make vis better. After the merge, we are responsible for maintaining, documentation, explanation and examples. 

A more promising way to go would be to get a graphing library to support the vis datasets and vis could support their data format in exchange. 

Regards,

Alex

**Comment by josdejong** [comment]
You're right Alex, thanks. Maybe we could release the DataSet separately from vis.js as it's  powerful solution on it's own.

**Comment by Puffton** [comment]
Without knowing the inner workings of vis, would it have to be an entire module, couldn't it be a small addition to graph2d, just hiding the axes? If it's only a matter of hours or a day, I might be interested in doing it.

Though it may not benefit you directly, a small addition with the potential of increasing your user base could also mean that the rest of your code gets tested better, it might even lead to more community contributions overall. However, I understand as the project grows it might be hard to keep all code maintained and in line with your internal coding guidelines...

**Comment by AlexDM0** [comment]
It's would be so so much easier to build from scratch. I don't think graph2d is suited for this. 

I think you could build a pie chart in less then a day but there are many already doing so....

**Comment by NitinBuzz** [comment]
I miss the Pie Chart in Vis.

**Comment by wolfen351** [comment]
Is this still the case in 2019?

**Comment by mojoaxel** [comment]
@wolfen351 This is definitely far out of scope of this library. But there are many other libraries than can create pie-charts.

**Comment by wolfen351** [comment]
OK, thanks for the feedback :)
