### ISSUE TITLE
dragging and dropping eleements  between vis js groups

### ISSUE THREAD

**Issue by rolatilu** [almende/vis#3643]
Not sure who can assist with this but I added to an element in one of the groups of the timeline draggable="true" and also added handler for dragstart event in the html. But for some reason I cannot drag the element in IE  nor Chrome. I see that the -webkit-user-drag: none exists in a parent element and not sure whether this is the culprit. Has anyone encountered this issue?

**Comment by yotamberk** [comment]
Timeline takes over drag events. Can I ask what's the usage for your d&d?

**Comment by rolatilu** [comment]
For groups we have rooms with their associated personnel. For items we have the schedules for that room. What we want is to be able to drag and drop staff members from one group (i.e room) to another. Is there a way to override this for specific elements? Note we use timeline's drag drop for the item schedules but need something special for a element within the group (i.e staff member list).

**Comment by yotamberk** [comment]
I think everything you need is shown in this example: 
http://visjs.org/examples/timeline/other/drag&drop.html
 + add the `editable:true` (take a look at the docs http://visjs.org/docs/timeline/#Configuration_Options)

Does this solve your issue?
