### ISSUE TITLE
vis memory leak with angular2/4

### ISSUE THREAD

**Issue by eyho** [almende/vis#3645]
Hey there, first of all thank you for making and working on this project, it's still great!

I've got a little problem here though, probably my last issue. I'm working with Angular2/4, and vis (yes, I'm using vis as an imported script in index.html). I implemented a component, where I have to use it like: declare var vis: any; on the top of the component file, so I can use the vis functions.
With this method it works great, except one thing, every time I reload the component (not with f5, with like normal routing, imagine the following: I use vis to redraw subnetworks, and I've got like 300 subnetworks, with different routes / URLs), my whole application gets laggy more and more because there's a common bug in vis, if you reload initialize a new network, the previous one get stuck in the memory. So if I check out like 5-6 different subnetworks on my application, the result is a laggy app in the end, because the components reload, with the new initialized vis (because of the different URLs). Do you have any idea what might cause the memory leak problem?

Thank you in advance.

**Comment by mbroad** [comment]
Do you have a minimal code example? Are you explicitly destroying old instances of the network when your component is re rendered?

**Comment by eyho** [comment]
`declare var vis: any;

export class MousePointer {
	x: number;
	y: number;
}

@Component({
	selector: 'vis-cmp',
	templateUrl: 'vis.component.html',
	styleUrls: ['vis.component.css', 'vis.component.add.css']
})`

Not much to show though, in ngOnInit() I just call: `this.network = new vis.Network(container, this.dataSet, options);`

Whenever I change route, ngOnDestroy runs, but I'm not sure what I should call here. Now it's just: `if (this.network != null) {
    this.network = null;
}`

It doesn't have any effect though.

**Comment by mbroad** [comment]
Setting to null will not be enough, call `this.network.destroy()` first, then set it to null. Also, to troubleshoot, log when network is already null.

**Comment by eyho** [comment]
I did as you told, called destroy function and then set it to null, but it has no effect. What exactly should I log?

**Comment by macleodbroad-wf** [comment]
I would log when you hit the destroy path, just to ensure that it's actually being called.

I don't know angular very well, but I'd start by adding console logging to each piece of the [content lifecycle](https://angular.io/guide/lifecycle-hooks), and verifying how often the content is actually being destroyed or re-rendered.

If it's re-rendering the network with every `ngOnChanges()`, then it may make sense to either circumvent that re-rendering, or call `network.destroy()` prior to allowing it to re-render.

Also, if you believe that this issue exists within vis and is outside of the scope of angular+vis, it might be worth putting together a minimal code example, and profiling using techniques described [here](https://developers.google.com/web/tools/chrome-devtools/memory-problems/) or [here](https://developers.google.com/web/tools/chrome-devtools/memory-problems/heap-snapshots).

**Comment by mbroad** [comment]
I would log when you hit the destroy path, just to ensure that it's actually being called.

I don't know angular very well, but I'd start by adding console logging to each piece of the [content lifecycle](https://angular.io/guide/lifecycle-hooks), and verifying how often the content is actually being destroyed or re-rendered.

If it's re-rendering the network with every `ngOnChanges()`, then it may make sense to either circumvent that re-rendering, or call `network.destroy()` prior to allowing it to re-render.

Also, if you believe that this issue exists within vis and is outside of the scope of angular+vis, it might be worth putting together a minimal code example, and profiling using techniques described [here](https://developers.google.com/web/tools/chrome-devtools/memory-problems/) or [here](https://developers.google.com/web/tools/chrome-devtools/memory-problems/heap-snapshots).
