### ISSUE TITLE
Access Label in node dataset

### ISSUE THREAD

**Issue by barrycullenireland** [almende/vis#3655]
Hi Alex,

My apologies for posting a design question on Vis.js but I cant get an answer on stackoverflow.com

I have two very simple questions relating to your excellent vis.js library.
1. I simply need a way to access the the label parameter in a dataset node when I click on it.
2. I need a way to search for a list of node ID's  in a dataset that have a label value of "xzy".

Here's my code snippet for problem 1.
 var nodes = new vis.DataSet([
            {id:1, label: "Lisbon",shape: 'circularImage', image:'1.png'},
			{id:2, label: "Old Town"}.....

var edges = new vis.DataSet([
	      {"from":13,"to":9,"arrows":"to","label":"Is a type of"},.....

  var data = {
    nodes: nodes,
    edges: edges
    };

Option 1.....
if (params.nodes.length > 0) {
	
	//Can get Node ID using this Code						
	var nodeId = params.nodes[0];//Math.floor(Math.random() * 10);
	
	//Thought this would give me the Label parameter of the node but shows "not defined"
	var nodeLabel = params.nodes[1];
	   alert(nodeLabel);
	   
Options 2...
//This gives me the total Node Parameters 
//0: {id: 2, label: "Old town"}

   var ids = params.nodes;
    var clickedNodes = nodes.get(ids);
    console.log('clicked nodes:', clickedNodes);

I am a novice programmer. 
Any help greatly appreciated.

**Comment by mbroad** [comment]
When you create a node, why not set the id of the node to the same cake value as the label, instead of a number?

**Comment by barrycullenireland** [comment]
Hi,

That worked a treat!

Again, many thanks for your help on this and I do apologies for contracting
you directly instead of using StackOverflow.

Barry.
