### ISSUE TITLE
[Timeline][Feature] getVisibleGroups

### ISSUE THREAD

**Issue by MeTaNoV** [almende/vis#3658]
In a way similar to getVisibleItems(), it would be nice to have a getVisibleGroups() functions which return the set of group currently visible vertically when height is fixed and scrolling is possbile.

One use-case is to implement a diagonal scrolling on a Gantt view (that we have implemented), by adding a fit() call to the element contained on all visible groups on the scroll event.

**Comment by MeTaNoV** [comment]
Thanks @yotamberk  for the merge!

**Comment by yotamberk** [comment]
Thank you for the PR!
