### ISSUE TITLE
TimeLine editing missing certain mouse events Chrome and Firefox

### ISSUE THREAD

**Issue by FrankW76** [almende/vis#3667]
This can be reproduced using the examples on the vis.js webpage.

For example on : http://visjs.org/examples/timeline/interaction/eventListeners.html

Resizing items not always registers the mouse eventds, and resizing the item does not work.

Steps to reproduce : 
- Click in the middle on an item to select it (it turns yellow)
- Now move your mouse to the left of the item, but not all the way. Just move the mouse until the pointer changes to the resize cursor
- Press down the mouse button and move the mouse. This should resize the item but this is (not always) working in Chrome and firefox. If you then just try again it moslty works.

I have attached an animating gif displaying the issue. The first time trying to resize fails, the 2nd time it succeeds. Many of our users having trouble with this issue.

![visjs-timeline](https://user-images.githubusercontent.com/4488423/32949229-5fa99834-cba2-11e7-91b4-128718221eb2.gif)

**Comment by FrankW76** [comment]
This may be related/duplicate of #3387 ?

**Comment by yotamberk** [comment]
I'm sorry but I don't seem to have any issues with this. It seems to work fine for me no matter how many times I try to fiddle with it.
The only known issue I know about regarding presses of items is prolonged static presses which cause items not to move (as mentioned #3375)

**Comment by FrankW76** [comment]
@yotamberk This is indeed the same issue as described in #2098 

I have also added a comment to #2098 about how I think this can be fixed. My JavaScript knowledge however is to limited to implement this myself.

**Comment by FrankW76** [comment]
Closing this issue as this is a duplicate
