### ISSUE TITLE
[Timeline] setWindow ± 3 days does not redraw

### ISSUE THREAD

**Issue by lndetrick** [almende/vis#3669]
This is a very obscure and specific problem, but if a timeline is initialized with no items and setWindow is called using ± 3 days as the params, the timeline does not automatically redraw until setWindow is called with anything except ± 3 days. I believe this is because when the Range object is made, it's defaults are set ± 3 days without invoking events and therefore setRange will not perform any changes and no redraw happens until initialRangeChangeDone is set to true via the rangechanged event.

https://jsbin.com/cirusakini/edit?html,console,output

If you click the button the first time, no redraw occurs.

My solution was to called setWindow with start as + 3 days and end as - 3 days - 1 second.

**Comment by ugurozturk** [comment]
@Indetrick i think its moment js problem. I fixed your code and everything runned very well. Make like this

```
var startDate = moment().subtract(3, "days");
var endDate = moment().add(3, "days");
```

**Comment by lndetrick** [comment]
I believe you're right. That worked perfectly! Thank you!
