### ISSUE TITLE
Showcase projects

### ISSUE THREAD

**Issue by jbigdata-git** [almende/vis#3689]
Hi,

Add my app [http://jbigdata.fr/webapps/10-dataviz03/](http://jbigdata.fr/webapps/10-dataviz03/)  to the showcase if interrested.

JB.

**Comment by mojoaxel** [comment]
Nice 😃 
This would be the first 3D-Chart showcase. Feel free to create a pull request to the `gh-pages` branch.

**Comment by jbigdata-git** [comment]
Hi,

I do the pull request to the _gh-pages_ banch (with warning).
Is it ok  ?

**Comment by jbigdata-git** [comment]
Hi,

I do the pull request to the _gh-pages_ banch (with warning).
