### ISSUE TITLE
Show Hidden Div With JQuery Not Work Properly

### ISSUE THREAD

**Issue by japita-se** [almende/vis#3691]
It seems that when the canvas is hidden and then shown by  jquery show(), the readraw sometimes works, sometimes doesnot.
[https://jsfiddle.net/esahhp9f/](url)

**Comment by katjasmin** [comment]
This sounds like this particular confirmed bug (https://github.com/almende/vis/issues/3616), if your using the current version of vis. Try adding start and end to your timeline options to avoid that.
