### ISSUE TITLE
Can i draw multi lines between nodes?

### ISSUE THREAD

**Issue by aHyunjaePark** [almende/vis#37]
Thanks for the awesome js lib :)

The tiny little thing i want is two lines between nodes.

if i put the edge like this,

edges.push({
                    from : 1,
                    to : 2,
                    length : LENGTH_MAIN,
                    color : 'red',
                    label : "bad",
                    style : "arrow"
                });
                edges.push({
                    from : 2,
                    to : 1,
                    length : LENGTH_MAIN,
                    color : 'green',
                    label : "ANOTHER",
                    style : "arrow"
                });

it only shows one :(

**Comment by TheHtmler** [comment]
My version is 4.0+, same issues showed in my project.
