### ISSUE TITLE
Timeline option height does not scale up properly

### ISSUE THREAD

**Issue by sudesh1234** [almende/vis#370]
Hi, 
While trying to set height option using groups, the height appears to only apply to the first group instead of the entire timeline. This issue was first encountered back here https://github.com/almende/vis/issues/8  and was said it was fixed in version 1.0.0, however I am still having this issue while using the most recent version. I am pasting both the code and the screenshot below and was wondering if I am missing something or if this is an issue with vis js. Here is also a fiddle illustrating the issue http://jsfiddle.net/Ltsf0Lb7/

     <style>
        body, html {
         font-family: arial, sans-serif;
         font-size: 11pt;
         height: 100%;
        }

     #visualization {
       box-sizing: border-box;
       width: 100%;
      height: 100%;
       }

     </style>

     <body>
     <div id="visualization"></div>
    
      <script>
     // create visualization
      var container = document.getElementById('visualization');
      var options = {
       height: '95%',
       groupOrder: 'content'  // groupOrder can be a property name or a sorting function
        };
       </body>
      </script>

![screen shot 2014-10-06 at 2 29 47 pm](https://cloud.githubusercontent.com/assets/2567417/4531120/ec23e032-4d86-11e4-9666-fec6baca7ca8.png)

**Comment by phil294** [comment]
@josdejong How would this be achieved today? These classes do not exist, there is only a configurable `groupTemplate` function.
