### ISSUE TITLE
How to get Timeline control base on Id or class 

### ISSUE THREAD

**Issue by MostafaEakram** [almende/vis#3706]
hi 
I have two  time line in the same page and i want to get each timeline by its Id or Class is that possible?

some thing like 
var time1=vis.getTimelinebyId("Timeline1");

**Comment by yotamberk** [comment]
```
var time1=vis.getTimelinebyId("Timeline1");
var time2=vis.getTimelinebyId("Timeline2");
var time3=vis.getTimelinebyId("Timeline3");
```

will work.

What are you trying to do that you are having trouble with?
