### ISSUE TITLE
timeline: selectable option as false does not work

### ISSUE THREAD

**Issue by matt-dejavu** [almende/vis#371]
I have a link in my box template for my timeline. I have my timeline options set with selectable = false since selection isn't necessary and I want the link to work. However, even with the option set, items on the timeline can be selected, which interferes with the clickable items inside the template.

**Comment by Kaliph** [comment]
Is selectable also avaialable as an option for my item. I can define selectable for the whole timeline, but if i pass "selectable"=false into my items, they are still selectable. if  i use editable=false I can define this for every item as well.
