### ISSUE TITLE
Timeline: Feature Requets, Unbounded range

### ISSUE THREAD

**Issue by Tukks** [almende/vis#3735]
Hi,

I would want to add unbounded range with no end.
Aks : When we put the value 'unbounded' on end properties, I want vis to draw a range with a start and an unlimited end, always drawing when user scroll on right.

Is it possible?
Thank's for this great Lib

**Comment by brichbe** [comment]
As a reasonable workaround, try setting the Timeline option `max` to some future date that your users never need to scroll beyond, for example today +100 years, or whatever makes sense for your app.  Then whenever you create one of these "unbounded" items, set it's `end` property to match the Timeline's max.

**Comment by Tukks** [comment]
Actually I made this : 
 ```
var container = document.getElementById('visualization');
    var options = {
      editable: true,
      rollingMode: {
        follow: true,
        offset: 0.5
      },
      onInitialDrawComplete: function() { logEvent('Timeline initial draw completed', {}); },
    };
    var items = new vis.DataSet([
      {id: 4, content: 'item 4', start: '2017-04-16', end: '2017-04-17'},
    ]);

   
    var timeline = new vis.Timeline(container, items, options);
  timeline.on('rangechange', function (properties) {
      logEvent('rangechange', properties);
      data.update({id: 5, end: properties.end});
    });
```

**Comment by yotamberk** [comment]
Looks good! Seems like a legit solution
