### ISSUE TITLE
Show % completed in timeline project Bar

### ISSUE THREAD

**Issue by sunilepms** [almende/vis#3772]
Hello Team,

We want to show project progress in the timeline bar. Can we add a  internal bar to each project bar for showing  %Complete.

Please check the below screenshot for reference.
![image](https://user-images.githubusercontent.com/34532840/34974341-77fb79b8-fab2-11e7-9167-d1cf5df56198.png)

Please give your suggestion if it is possible to achieve above result.

**Comment by katjasmin** [comment]
There's already an example for your specific problem, using CSS-Templates. 
Here's the link: http://visjs.org/examples/timeline/items/visibleFrameTemplateContent.html
