### ISSUE TITLE
Additional events

### ISSUE THREAD

**Issue by Xflofoxx** [almende/vis#378]
Good morning,
I'd like to know if there is a way to intercept some additional events, like "onDrawComplete" or something similar.

Many thanks and keep on the great work!
Dario

**Comment by josdejong** [comment]
I've removed the `finishedRedraw` event in v4, as I can't find a usage for it: creation and updating data in the Timeline works synchronously. Immediately after a call to update data or create a Timeline, it's updated. We tested by putting a blocking `alert('ready?')` after creating/updating a timeline, and it seems always up to date.

**Comment by Xflofoxx** [comment]
Ok, thanks a lot!

*Please consider the environment before printing this e-mail*

2015-05-04 11:23 GMT+02:00 Jos de Jong <notifications@github.com>:
