### ISSUE TITLE
Timeline: selecting item name

### ISSUE THREAD

**Issue by Kyps** [almende/vis#3780]
Is it possible to get the item name(or content) when selecting an item on the timeline? In the docs there is an example on how to listen for an item selection but that alert box returns the timeline item id. 
```
timeline.on('select', function (properties) {
  alert('selected items: ' + properties.items);
});
```

**Comment by katjasmin** [comment]
You can use the id to grab the specific item and it's values from your DataSet. 

```
var item = items.get(properties.items[0]);
var content = item.content;
```

**Comment by Kyps** [comment]
Had to modify your answer a little bit but I got it to work. Thanks
