### ISSUE TITLE
The Network's container must have a fixed height in Firefox 

### ISSUE THREAD

**Issue by zouabimourad** [almende/vis#380]
Hi,

The graph's container must have a fixed a height in pixel ( can't use % )  in Firefox .. otherwise it will by 200px by default. 

It's ok with the others navigators.

**Comment by AlexDM0** [comment]
Hi Zouabimourad,

Is this in any firefox or on a specific OS? 

http://visjs.org/examples/network/08_mobile_friendly.html seems to work fine with 100%?

Regards

**Comment by AlexDM0** [comment]
Hi,

We have tested this on a number of different browsers and OS's. I think the problem is that you have to give your body and html a height of 100% using CSS.

Regards,

Alex
