### ISSUE TITLE
Displaying tooltips and pop-ups via the title attribute

### ISSUE THREAD

**Issue by rayaqin** [almende/vis#3834]
Greetings.

I've been trying to achieve what some of the examples in the vis.js documentation have. The pop-up when you hover over a node. I have the hover option enabled, my nodes have titles and I have the tooltipDelay set to 30. To my understanding this should result in the hover event displaying the pop-up after 30 milliseconds that would contain whats in the title. Which in my case is "Hover". Yet this doesn't happen, even though there is no more information as to how I should be doing this ( if not this way ) in the documentation.

My options include:
```    
     	interaction: {
    		dragNodes: true,
    		hover: true,
    		tooltipDelay: 30,
    		selectable: true
    	},
     	edges: {
    		color: {
    			color: '#848484',
    			highlight: '#848484',
    			hover: '#848484',
    			inherit: 'from',
    			opacity: 1.0
    		},
    		arrowStrikethrough: false,
    		smooth: {
    			type: 'cubicBezier'
    		},
    	},
    	nodes: {
    		shape: 'circularImage',
    		title: 'Hover'
        	}
```
I request some data from the database based on which my nodes are drawn, and the title attribute is hardcoded for testing purposes, so that part in my .tsx file looks like this:
```
private _skillTreeRequestCallback(graph: {
		nodes: ISkill[],
		edges: IEdge[]
	}) {
		graph.nodes = graph.nodes.map(skill => ({
			...skill,
			title: "Hover",
			hidden: skill.Hidden,
			image: skill.Image,
			label: skill.Label,
			id: skill.Id
		}));
		graph.edges = graph.edges.map(edge => ({
			...edge,
			from: edge.From,
			to: edge.To
		}));
		this.setState({ graph, isLoading: false });
	}
```

I have tested it separately by console.log-ing, and the nodes all have their title set to "Hover", and the hover event does work because the nodes do get recoloured as it is described in options for the case of hovering,
yet the tooltip does not show, displaying the title as a pop-up.

The documentation says thet it "can be" displayed, but doesnt say how. I assumed that if the tooltipDelay is set and the hover event is set to true and there is a defined title, then the tooltip shows, because thats what the documentation led me to believe, but it seems like there is some other way I should be aware of, that isn`t in the docs.

Please let me know if I misinterpreted or didn`t find something. Any help is appreciated.

Thank you,

Balint

**Comment by mojoaxel** [comment]
Please make sure to **read the following list** before creating a new issue:

* This issue tracker is not supposed to be used for questions on how to use visjs. It is intended to be used for bug reports and feature requests! In case you face yourself with a usage question, then post your question e.g. on [stackoverflow](https://stackoverflow.com/questions/tagged/vis.js) tagged with "vis.js".
* Have you already used the [github search](https://github.com/almende/vis/issues), read the [documentation](http://visjs.org/) and looked at the [examples](https://github.com/almende/vis/tree/develop/examples)?
* Make sure to mention which vis-component (network, timeline, graph2D, graph3d) you are referring to.
* Make sure to use the [latest version of vis.js](https://cdnjs.com/libraries/vis) for bug reports.
* Make sure to mention which browser and OS you are using when creating a bug report.
* Please provide a minimal code example that demonstrates your issue. We recommend using [jsbin](jsbin.com) for that.

**Comment by veronikinator** [comment]
I had the same problem before,  pop-ups don't work without explicit import of `vis.min.css`
I hope that helps
