### ISSUE TITLE
Fast horizontal scrolling

### ISSUE THREAD

**Issue by GluedToTheScreen** [almende/vis#384]
Maybe I missed an option, but the old chap/links timeline had a nice feature where SHIFT-mousewheel scrolled the timeline horizontally... fast.

With vis, it seems you get zoom with or without the shift key +wheel

Is there a way to re-enable that functionality?

thanks again.

**Comment by AlexDM0** [comment]
Hi,

Over the last year a lot of feature requests have been made. We have just introduced our new website which has a list of the requested features. We have placed this request on that list. 

The list can be found here:
http://visjs.org/featureRequests.html

An explaination of the new system can be found here:
http://visjs.org/blog.html#New\ website\ for\ vis\.js\!

I would like to stress that this does not mean we abandon this request. Discussion here will continue if needed on this feature but we will close it to keep our Github issue page more of a bug-todo list.

Future feature requests will still be made here and then added to the website by us.

Regards,

Alex

**Comment by mojoaxel** [comment]
Reopening as Feature-Request issue (see #2114). 
Everybody: Please feel free to implement this!

**Comment by yotamberk** [comment]
@mojoaxel I've implemented a `verticalScroll` option, so I think this can be closed. It doesn't have a `ctrlKey` but that's another feature. No?

**Comment by mojoaxel** [comment]
> I've implemented a verticalScroll option, so I think this can be closed.

You are write! This is implemented!

**Comment by yotamberk** [comment]
@mojoaxel I'm rereading this feature request and I think we can still improve what is in the `develop` branch. I should add `horizontalScrollKey` and `verticalScrollKey` and maybe `scrollSpeed` could be cool. Anyways, lots of additions can be added to this

**Comment by mojoaxel** [comment]
>  I should add horizontalScrollKey and verticalScrollKey and maybe scrollSpeed could be cool. Anyways, lots of additions can be added to this

:+1: Feel free to reopen and add additional functionality!
