### ISSUE TITLE
Vis js tooltip title popup linebreak

### ISSUE THREAD

**Issue by amandacarbonne** [almende/vis#3860]
Hi,
I´m using the tooltip title for the nodes. So actually I would like to do a linebreak like "\n". 
But if I do it for the title, it doesnt work. So a example is "title: test\ntest". But the popup doesn´t do a linebreak. How can I do it?
Thanks :)

**Comment by katjasmin** [comment]
If networks also allows styling the tooltip with html like the timeline component then you could simply use the corresponding <br> element.

**Comment by amandacarbonne** [comment]
Thanks a lot :) <br> works perfectly!
