### ISSUE TITLE
How to exclude holidays from dates range in vis.js

### ISSUE THREAD

**Issue by infosms** [almende/vis#3878]
Hi
I have timeline in vis.js for example from 04.09.2017 to 20.03.2018
Now i need  to remove from this timeline all holidays and some dates.
I need to not show them in timeline how to do that?

**Comment by katjasmin** [comment]
You can add time spans as objects to the hiddenDates option in the timeline configuration. 
Something like this:
```javascript
  var options = {
      hiddenDates: [ {start: '2014-03-21 00:00:00', end: '2014-03-28 00:00:00', [repeat:'yearly']},
                     {start: '2014-05-18 00:00:00', end: '2014-05-20 00:00:00'} ]
  }
```
The repeat statement is optional.

**Comment by infosms** [comment]
You are a goddamn Guddini)
Big thank you)
It would be better if it was subscrided in documentation

**Comment by katjasmin** [comment]
You're welcome. FYI it is actually described in the documentation and there is even an example on the website. ;) 

http://visjs.org/docs/timeline/#Configuration_Options/
http://visjs.org/examples/timeline/other/hidingPeriods.html
