### ISSUE TITLE
Network: How to show mutliple edges between two nodes?

### ISSUE THREAD

**Issue by alanchenchen** [almende/vis#3905]
#### browser:  chrome 64.0.3282.119
 Hi! I found a problem that when there are more than one edge between two nodes,the latter one edge would override the former one.
I wanna it  to show the total edges but it always show one. Here are my options codes below:
``` javascript
const options = {
                interaction: {
                    hover: true,
                    hoverConnectedEdges: false
                },
                edges: {
                    smooth: {
                        enabled: false
                    },
                    selfReferenceSize: 20,
                },
                nodes: {
                    size: 16
                },
                physics: {
                    enabled: false,
                }
            }
```
Well,i try to resolve this problem with a kind of option and it works. Like this:
``` javascript
const options = {
                interaction: {
                    hover: true,
                    hoverConnectedEdges: false
                },
                edges: {
                    smooth: {
                        enabled: true,
                        type: 'dynamic'
                    },
                    selfReferenceSize: 20,
                },
                nodes: {
                    size: 16
                },
                physics: {
                    enabled: true,
                }
            }
```
It only works if i enabled the smooth mode and physics mode.However it's not suitable for my program.
So how can i show multiple edges between two nodes without enableing  smooth mode and physics mode?

**Comment by Menighin** [comment]
Hi @alanchenchen,

[This JSBin](http://jsbin.com/mayopoceze/edit?html,js,output) created by @wimrijnders on #1957 shows how you can do it. So far there is not a simple option to be set, so basically you have to set a different `roundness` value for each edge in order to not overlap them.

Regards

**Comment by alanchenchen** [comment]
Thanks for your so fast reply,i set the option roundness  and it works.But i wanna the single edge between two nodes to be straight.. well,i will try to set the option roundness only for multiple edges and maybe it will wrok.   hahahha...

Best wishes!

**Comment by Menighin** [comment]
You can set the roundness to `0.0` and then it will be straight! :)

Then for nodes with more than one edge between them you can have some routine that starts putting the roundness on `0.0` and then oscillates around it: `0.2`, `-0.2`, `0.4`, `-0.4` [...]
I had done it myself but cant find it... 
Good luck!

**Comment by alanchenchen** [comment]
yeap! I just done it like what you said and it worked. Thanks so much . 

Best wishes!
