### ISSUE TITLE
Feature: Timeline Inline editing on update.

### ISSUE THREAD

**Issue by tatsujb** [almende/vis#3921]
I find that inline editing is something that is made difficult to implement by vis js timeline.

I'd like to double-click on an item and their content would have an input be overlayed on it or replace it  with focus and ready to be edited. The enter key would of course finalize the onUpdate.

Right now the only arguments being passed to onUpdate is item and callback.

This means I'll have to hack this in with a listener on the whole timeline for double clicks, temporarily save x and y pixels on each double click and use the latest to date x and y to place an input there.

Or instead of using coordinates, I'll use the double-click listener to save the target @ $event and edit the innerHTML and edit again upon onUpdate completion.

If you have some better ideas I could really use them right now.

But for me, timelineJS forces us to hack to get inline editing kinda working.

It could be facilitated by timelineJS at least delivering the html target/ $event to the user in the onUpdate arguments.

**Comment by tatsujb** [comment]
for the sake of helping people out here's what I came up with : 
```
options = {
  dataAttributes: ['id'],
  onUpdate: (item, callback) => {
    const i = this._element.nativeElement.querySelector('[data-id="' + item.id + '"]');
      const element = $(i).children('.vis-item-content');
      const text = element.text();
      
      element.html('<input class="edit-item" type="text">');

      element.children('.edit-item').focus(); 
      element.children('.edit-item').val(text);

      let finalValue = '';
      element.children('.edit-item').focusout(() => { //catch click outside
        finalValue = text;
        element.html(finalValue);
        callback(null);
      });
      element.children('.edit-item').keydown(e => {
        if(e.which === 13) { //catch enter keys
          finalValue = element.children('.edit-item').val().toString();
          element.html(finalValue);
          callback(item);
        }
        if(e.which === 27){ //catch esc
          finalValue = text;
          element.html(finalValue);
          callback(null);
        }
      });
  }
}
```

**Comment by murraybauer** [comment]
@tatsujb thanks for sharing your solution. I need to do the same for my Angular app and just saw this.

But, what about creating a normal angular component, and using co-ordinates to position as you say.

Can't you just keep your current on click function (avoiding listening on the window) and once you have a reference to the element in jquery:
```
const i = this._element.nativeElement.querySelector('[data-id="' + item.id + '"]');
      const element = $(i).children('.vis-item-content');
```

Get it's screen co-ordinates using [.offset()](https://stackoverflow.com/questions/1002934/jquery-x-y-document-coordinates-of-dom-object) and re-position the angular component's top/left over the top?

Am I missing something?

**Comment by tatsujb** [comment]
@murraybauer , yes the fact that positioning should be timeline's responsibility and according to the gate and row, and it you want it that way because otherwise when you have 100 rows and you scroll up and down it won't follow suit and it also won't follow suit when you go backwards and forwards in time.

But not only that : it won't follow suit if you decide to edit the item's start date at the same time, which with my, solution I can do, I can start updating an item, then move it around and then hit enter and it will have saved both.

here's the changes I made : 
```
if(e.which === 13) { // catch enter keys
     finalValue = element.children('.edit-item').val().toString();
     element.html(finalValue);
     item.content = finalValue;
     if(this.movedItem) if(this.movedItem.id === item.id) item.start = this.movedItem.start;
     if(isNew) item.id = uuid();
     this.items.remove('dragNdropping');
     resolve(item);
}
```

the local value `this.movedItem` gets hydrated everytime onMove is called.

Notice I now use the update method both for updating items and creating items. 

I fool timeline by first giving it an item initiated with an Id equal to "dragNDropping", (that's the return given as callback of my onAdd function) then I return as a (second time) callback the return of the update function which as you can, takes also care of deleting what is now an unneeded temporary item.
