### ISSUE TITLE
Is there a way to add custom buttons inside the network and adjust their positions?

### ISSUE THREAD

**Issue by Yingli40604345** [almende/vis#3925]
Hi guys! I want to add some custom buttons inside visjs network graph. The buttons are currently outside the graph.When I toggle fullscreen, the buttons will be gone because only everything on the graph will be shown on fullscreen. Is there a way to embed and adjust custom buttons inside the graph? Thank you so much!

**Comment by JohnwMoody** [comment]
This isn't an issue. I would suggest posting a question on StackOverflow with the [visjs] tag.

**Comment by Yingli40604345** [comment]
Sure. Thank you!

**Comment by brichbe** [comment]
@Yingli40604345 Once you've posted your question on SO, please close this issue here.
