### ISSUE TITLE
Placing visjs-network in external javascript file and render in pug/jade

### ISSUE THREAD

**Issue by scukras7** [almende/vis#3927]
I have a node server serving a pug/jade template that calls an external javascript file.  I took the tutorial code: https://github.com/almende/vis/blob/master/examples/network/other/manipulation.html#L12

and placed it into my external js file and wrapped it in a function.  External js file looks like this:

var vis_build_network = function() {//code from tutorial}
// render after pug page loaded
window.addEventListener('load', vis_build_network, false);

When I go to the page in Chrome everything renders nicely and I can add/delete nodes fine, but I cannot edit node labels or connect edges between nodes.  I am able to select Add Edge but when I click on the second node to connect it to, it fails.

When I run the tutorial's code inline in my pug file everything works as intended.  Does visjs need to run inline only?

**Comment by kriegsmaschine** [comment]
I've been working on it hours and I thought it was pug not letting visjs read/edit the DOM from the external js file.  I found the issue, I had a malformed pug file.
