### ISSUE TITLE
Error when node's image cannot be loaded and no 'brokenImage' option is set

### ISSUE THREAD

**Issue by glampr** [almende/vis#395]
If I try to create a network like so:
```coffeescript
nodes = new vis.DataSet()
edges = new vis.DataSet()
nodes.add([{
  id: "an_id", value: 10, label: "node1",
  shape: "image", image: "http://www.images.com/node.jpg"
 }])
data = {nodes: nodes, edges: edges}
options = {}
graph = new vis.Network(document.getElementById("canvas"), data, options)
```
and the image url cannot be resolved, and I have NOT supplied a ```brokenImage``` url, then I get repeated AJAX calls (endless loop?) to my application running on the same domain, and the graph never gets displayed.

**Comment by AlexDM0** [comment]
Hi Glampr,

Sorry for the (long) delay. I have pushed  a fix to the develop branch. It will be included in the next release.

Regards,

Alex
