### ISSUE TITLE
 Implement recurring events (similarly to the way the hidden dates are implemented?)

### ISSUE THREAD

**Issue by hydroplane** [almende/vis#398]
How can I set the dates for a recurring event?
I have an event which ran from September to July, every day Mon - Fri. Do I have add every single item manually in json or is there a better way?

**Comment by AlexDM0** [comment]
Hi,

Over the last year a lot of feature requests have been made. We have just introduced our new website which has a list of the requested features. We have placed this request on that list. 

The list can be found here:
http://visjs.org/featureRequests.html

An explaination of the new system can be found here:
http://visjs.org/blog.html#New\ website\ for\ vis\.js\!

I would like to stress that this does not mean we abandon this request. Discussion here will continue if needed on this feature but we will close it to keep our Github issue page more of a bug-todo list.

Future feature requests will still be made here and then added to the website by us.

Regards,

Alex

**Comment by mojoaxel** [comment]
Reopening as Feature-Request issue (see #2114). 
Everybody: Please feel free to implement this!

**Comment by yotamberk** [comment]
Reoccurring items should be implemented by the user. I advise to do it using a loop with @josdejong suggestion and add a property for the item to indicate it's a reoccurring event (add an icon to the event using this property).

Closing this issue unless we are convinced this should be implemented on vis side

**Comment by Jogai** [comment]
Other existing libs that could help are @jakubroztocil's [rrule](/jakubroztocil/rrule) @bunkat's [later](/bunkat/later).

In my case I'm looking to port a solution that is currently using [SyncFusion's scheduler](http://js.syncfusion.com/demos/web/#!/default-theme/schedule/resourcegrouping/timelineview) which has the recurring part built in.

**Comment by Jogai** [comment]
There is a whole class made to support hiddenDates feature. It seems more logical to me to let this be handled by a dependency and expose it at some more points to support recurrence. Even the hiddenDates would be more flexible that way.
