### ISSUE TITLE
timeline - initializing with empty dataset for late-append does not display even you add the data later.

### ISSUE THREAD

**Issue by tolgaulas** [almende/vis#3986]
I wanted to initialize the timeline and then add data(ajax, script etc) ; however it did not work.  It does not display the defaults in case the Dataset is empty. Adding the data afterwards is not displaying it later on.

```
<p>Below is not displayed:</p>
<div id="noVisual"></div>
<button id="add" onclick="addItem()">Add</button>

<p>Below is displayed:</p>
<div id="yesVisual"></div>

<script type="text/javascript">
var containerNo = document.getElementById('noVisual');
var containerYes = document.getElementById('yesVisual');

var options = {};

var noItems = new vis.DataSet();
var yesItems = new vis.DataSet([{id:1,content:"item 1",start:"2010-01-01"}]);

var noTimeline = new vis.Timeline(containerNo, noItems, options);
var yesTimeline = new vis.Timeline(containerYes, yesItems, options);

function addItem(){
  noTimeline.setItems(new vis.DataSet([{id:1,content:"item 1",start:"2010-01-01"}]));
}
</script>
```
as seen in : https://jsfiddle.net/tolgaulas/qvfhoj8w/21/

**Comment by javdome** [comment]
Hi
You can try to create the timeline with one Item, and remove it once you have create the timeline.

`
......
var noItems = new vis.DataSet([{id:1,content:"item 1",start:"2010-01-01"}]);
.....
var noTimeline = new vis.Timeline(containerNo, noItems, options);
noItems.remove(1);
`

**Comment by katjasmin** [comment]
If the idea above does not work you could also try to refresh your timeline after setting your items.

**Comment by tolgaulas** [comment]
@katjasmin : 
> try to refresh your timeline after setting your items.

Did not work on my attempt.

>  which version of Vis you are currently using

It was directly from CDN, so most recent should be.

**Comment by tolgaulas** [comment]
@javdome : Thanks, I am almost certain I've tried this one but it did not work. But your fiddle proves me wrong.

**Comment by javdome** [comment]
Great!! Can you close the issue, please?

**Comment by katjasmin** [comment]
Falk I would suggest opening an new issue for that, if you could provide a code sample or a jsfiddle that would be awesome.
