### ISSUE TITLE
Item width changes when moving. Possibly lock item width? 

### ISSUE THREAD

**Issue by baarmanj** [almende/vis#401]
Hi, 
First of all, thanks you for this great library, it really is powerful.  I haven't really found anything else that fills my need better considering visualizing and planning workorders on a timeline. 

One enhancement I would be really greatful of would be the possibility to lock an items width. Currently when moving items of type range the width (difference between start- and endtime) of the item might change. I've noticed this behaviour more when the scale is less detailed (zoomed out) and less when the scale is more detailed. I'm using the timeline for scheduling workorders where start- and endtime should be on a 30 minutes accuracy and now when the item width changes the start and endtime are a bit hard to manage. 

Another approach could be if one could set the scale more detailed without having it printed too detailed.

Thanks for any replies, suggestions how to overcome this one.

Br, Johan

**Comment by iphar** [comment]
I ran into the same problem!

I'm not so much into github to provide a patch. But I solved the issue with the following hack according to your suggestion jos:

in function ItemSet.prototype._onDragStart:
if ('start' in item.data && 'end' in item.data)   props.duration = item.data.end.valueOf()-item.data.start.valueOf();

in function  ItemSet.prototype._onDrag:
if ('duration' in props) {
        	newProps.end = new Date(newProps.start.valueOf() + props.duration);
        }

Could you include sth. like this in your next release?

**Comment by josdejong** [comment]
This should be fixed now in the develop branch, see https://github.com/almende/vis/commit/1d7982f5916d08f6756092bc44cc54c54b2c2969

**Comment by iphar** [comment]
version 3.10.0 is working fine! thanks!
