### ISSUE TITLE
How to change the grid for drag and resize of items?

### ISSUE THREAD

**Issue by Reollyn** [almende/vis#4034]
Hello,

is there any way to change the grid for the drag and the resize when dragging and resizing items in vis.js. Or is it possible to turn off the grid for the drag and the resize?

Thanks.

**Comment by yotamberk** [comment]
I'm not sure what yo're asking. Do you want not to see the lines of the grid? 
You can do this with CSS adding a style rule when the drag and resize item event is emitted and done

**Comment by Reollyn** [comment]
I made it what i want. It's the `snap` option in `vis.js`. I thought they call it `grid` or something like that. Thanks for answering.
