### ISSUE TITLE
Moving network manipulation/edit buttons to DOM 

### ISSUE THREAD

**Issue by jmlevin78** [almende/vis#4048]
Just to clarify, I am not talking about the navigation buttons.

I was wondering if it would possible to move the manipulation-specific edit buttons off the canvas and into a sidebar on the DOM. In my specific example, I have added a right hamburger menu sidebar and would like to move the buttons there so they can be hidden without having to exit out of edit mode.

![screen shot 2018-07-24 at 4 29 49 pm](https://user-images.githubusercontent.com/8312367/43164457-2f29f0b0-8f5f-11e8-9aa1-dfea317dc210.png)

I've played around with the css a bit, and have been able to get a lookalike button in the right side menu, but have been unable to nail down the click event listener, and was wondering if there would be a manageable way to do so?

**Comment by ndinh31** [comment]
have you tried looking at the documentation in the layout section?
http://visjs.org/docs/network/
