### ISSUE TITLE
'dash-line' style on edge - firefox bug

### ISSUE THREAD

**Issue by pkoretic** [almende/vis#405]
http://visjs.org/examples/network/13_dashed_lines.html

Opening this in firefox (33.0) doesn't work as expected:
![2014-10-28-114829_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1131063/4807043/010005ca-5e90-11e4-9317-ebdde2f28fe1.png)

I've came to this after the same problem I had. Whenever there is dash-line as style this happens.

**Comment by AlexDM0** [comment]
Hi,

A fix for this has been pushed to the develop branch. Thanks for letting us know!

Regards,

Alex
