### ISSUE TITLE
Event 'rangechange' and 'rangechanged' fired in any case

### ISSUE THREAD

**Issue by deStrO** [almende/vis#406]
Hello,

According to the documentation:
rangechange: Fired repeatedly when the user is dragging the timeline window.
rangechanged: Fired once after the user has dragged the timeline window.

The event is fired also when the function "moveTo" is used.

Any chance to get a fix for this?

**Comment by AlexDM0** [comment]
Hi,

I have added an byUser flag to this event. This should solve the problem. It has been pushed to the develop branch and will be included in the next release.

Regards,

Alex
