### ISSUE TITLE
How to make current time not overlap major label

### ISSUE THREAD

**Issue by jknapp25** [almende/vis#4078]
![image](https://user-images.githubusercontent.com/3934326/43978781-4d82d19e-9c9d-11e8-834f-4ef9d9e90b8b.png)

It's not currently, but at the start of the month, the red current time was behind the major label of "August 2018". How can I show the current time above major label so that they don't overlap?

**Comment by jgorene** [comment]
As far as I know, it is not possible to pass over time axis but you can try to pass between "minorLabels" and "majorLabels" or still just below the time axis.
As the screenshot shows, you probably created a label attached to the time bar by giving it an ID
In this case in the stylesheet if the ID is "labelCurrentTime" (e.g)...  you can do something like to adapt to your needs ;)
```
#labelCurrentTime {
  margin-top: 15px;
  margin-left: 5px;
  color:red;
  font-size:12px;
  width:200px;
  white-space: nowrap;
}
```

**Comment by jknapp25** [comment]
Between the minor and major labels would be ideal. Adding margin-top just moves it down on the bar.
Do you know what to apply styles to so that space is created between minor and major labels? I am having trouble targeting the correct element.

**Comment by jgorene** [comment]
This is an interesting question and I would also like an answer about this;)
Anyway, It's probably not the "optimal setting" and I think we can do better than that, but I couldn't find a better one at the moment. Otherwise, I get pretty much what I'm looking for by playing around the style this way.
Here a [working example](https://codepen.io/jean2607/full/gWeyzB)...
```
#labelCurrentTime {
  margin-top: 20px; // adapt to your needs
  margin-left: 5px;
  color:red;
  font-size:12px;
  width:200px;
  white-space: nowrap;
}
.vis-time-axis .vis-text {
    position: absolute;
    color: #4d4d4d;
    padding: 8px; // adapt to your needs (5px for the initial setting)
    overflow: hidden;
    box-sizing: border-box;
    white-space: nowrap;
}
```

**Comment by jknapp25** [comment]
This is exactly what I was looking for. I'll test when I'm in the office. Thank you Jean.

**Comment by jgorene** [comment]
@jknapp25 Nice, you welcome ;)

**Comment by jknapp25** [comment]
This worked. This is what I ended up with...

![image](https://user-images.githubusercontent.com/3934326/44864758-5428bc00-ac35-11e8-94df-621c37c0bf00.png)

I have to say though, this is not ideal. Being able to increase the distance between the month and the day numbers would be best. We have up to 30 people sitting in a room reading this everyday, so making it very clean would be the best solution.

Thank you Jean!
