### ISSUE TITLE
Where is the DONATE BUTTON?!

### ISSUE THREAD

**Issue by davidhbigelow** [almende/vis#4093]
This library is AWESOME (once you learn it's quirks).

Where is the DONATE BUTTON?!  :)

Dave

**Comment by javdome** [comment]
Hi, if you are interested in how is the development of this library, you can see the issue https://github.com/almende/vis/issues/4015 
There also you can see a link to opencolective for donations https://opencollective.com/vis

**Comment by davidhbigelow** [comment]
THANK YOU -- Kicked in $100!
I highly recommend others also support this project - very useful and well done.
