### ISSUE TITLE
Network node to be positioned correctly 

### ISSUE THREAD

**Issue by jhabap18** [almende/vis#4147]
Hi Vis experts, 
I have a vis network attached in the image
![visnetwork](https://user-images.githubusercontent.com/9780404/46466369-bc486000-c7e8-11e8-9e42-e268a654f404.jpg)

Here I have two groups of nodes -
One with Dot and one with triangle
I want the node with yellow highlighted color to be positioned where arrow points to. It also seems logical if you'll see the neighborhood nodes and edges of this node. How can I achieve this. Please suggest. 
If it's possible, I'll share the code also.
Let me share the options field I am using-
options = {
                        interaction: {
                            hover: true,
                            keyboard: {
                                enabled: true,
                                   bindToWindow: false
                            }, 

                        },
                        layout: {
                            hierarchical: {
                                direction:"LR",
                                sortMethod: "directed",
                                levelSeparation: 300
                                //sortMethod: "hubsize"
                            }
                        }
                    }

**Comment by softwareCobbler** [comment]
The "in" edge into your yellow circle is the only edge going "backwards", suggesting to me that you need to manually set your node levels.
