### ISSUE TITLE
I want to build a video player timeline by using vis.js and have some questions

### ISSUE THREAD

**Issue by BerlyMei** [almende/vis#4152]
Hey guys, 

I am now using vis to build video player timeline. I added customline and want this customline to be auto move to currenttime when I dragged to some specific location, which is very similar to video replay functions. Could someone give me an idea how to achieve it?

**Comment by mojoaxel** [comment]
> This issue tracker is not supposed to be used for questions on how to use visjs. It is intended to be used for bug reports and feature requests! In case you face yourself with a usage question, then post your question e.g. on stackoverflow tagged with "vis.js".
