### ISSUE TITLE
Locale uses Moment global scope (soon to be deprecated)

### ISSUE THREAD

**Issue by mvzen** [almende/vis#416]
My project is set up using RequireJS and AMD loading. I'm in a non-english speaking country and use MomentJS for date formatting in the correct language (french).

MomentJS recommends setting the { noGlobal: true } flag in the RequireJS config, and is soon to be deprecated. If I do this, vis no longer translates my dates.

For the moment, I have opted to not use noGlobal in my config, but I am presented with a console warning: `Deprecation warning: Accessing Moment through the global scope is deprecated, and will be removed in an upcoming release. `. So it seems it is only a matter of time before this stops working and we lose locale support altogether.

Is there a way to pass the moment variable to vis during initialization ?

**Comment by josdejong** [comment]
Is this still an issue?
