### ISSUE TITLE
Arrow has a gap towards the Node

### ISSUE THREAD

**Issue by sarahm7** [almende/vis#4163]
hope you can help, i'm struggling to move the arrow closer to the node here below. i can't seem to make it look better at this point

![image](https://user-images.githubusercontent.com/27810542/45343180-ba68f380-b5d2-11e8-98ec-d45b7899be18.png)

here's my settings
```js
     edges: {
        smooth: {
          type: 'cubicBezier',
          forceDirection: 'vertical',
          roundness: 0.9,
          enabled: true
        },
        arrows: {
          to: { enabled: true, scaleFactor: 0.5 },
          middle: { enabled: false, scaleFactor: 1 },
          from: { enabled: false, scaleFactor: 0.5 }
        },
        color: {
          color: '#ffab40',
          highlight: '#2B7CE9'
        },
        width: 2,
        selectionWidth: 2
      },
      layout: {
        hierarchical: {
          direction: 'UD',
          sortMethod: 'directed',
          levelSeparation: 200,
          nodeSpacing: 200,
          treeSpacing: 150
        }
      }
```

**Comment by mojoaxel** [comment]
> This issue tracker is not supposed to be used for questions on how to use visjs. It is intended to be used for bug reports and feature requests! In case you face yourself with a usage question, then post your question e.g. on stackoverflow tagged with "vis.js".

> Please provide a minimal code example that demonstrates your issue. We recommend using jsbin for that.
