### ISSUE TITLE
Can we consider this library abandoned?

### ISSUE THREAD

**Issue by JHeinzde** [almende/vis#4170]
Since there are so many issues, and the last commit is ~1 year ago, can I consider this abandonware?

**Comment by clayt85** [comment]
Bump for this question. I hope not, but I fear this is the case.

I am an intermediate-level user of the network sub-library.  I haven't done much (any?) development for the project, but I am thinking of [forking](https://github.com/clayt85/vis) unless the project picks back up...

**Comment by Jogai** [comment]
See https://github.com/visjs-community and https://github.com/yotamberk/timeline-plus

**Comment by JHeinzde** [comment]
Hello Jogai, thanks for the hint! This is really great, since this library is much easier to use than for example d3, and come with things like clustering out of the box!
