### ISSUE TITLE
Groups and filter

### ISSUE THREAD

**Issue by fredlavoine** [almende/vis#4171]
Hello,
  Is-it possible to do a data filter with checkbox ?
![groups](https://user-images.githubusercontent.com/44341622/47268382-7f9e9780-d550-11e8-9cd2-ecaf5a9b2a6e.jpg)
Thank you

**Comment by Loxxe** [comment]
If you mean to hide/show nodes, yes its possible. You can filter by group on your DataSet and update your nodes with hidden true/false

**Comment by Loxxe** [comment]
Yes you can hide/show nodes if thats what you mean.
`DataSet.update({id: nodeId, hidden: true/false}); //or an array of objects`
And you can get the nodeIds of a specific group with:
`DataSet.get({filter: function(item) { return item.group === groupName }})`
