### ISSUE TITLE
how to uses HTML svg for rendering.

### ISSUE THREAD

**Issue by kang558** [almende/vis#4187]
how to uses HTML svg for rendering ? 
Like this
[https://ialab.it.monash.edu/webcola/examples/SucroseBreakdown.html](https://ialab.it.monash.edu/webcola/examples/SucroseBreakdown.html)
l have to use svg rendering in some special cases

**Comment by mojoaxel** [comment]
> This issue tracker is not supposed to be used for questions on how to use visjs. It is intended to be used for bug reports and feature requests! In case you face yourself with a usage question, then post your question e.g. on stackoverflow tagged with "vis.js".

> Have you already used the github search, read the documentation and looked at the examples?
