### ISSUE TITLE
on node mouse hover need to show a popup to add new node

### ISSUE THREAD

**Issue by NabaSD** [almende/vis#4190]
I am trying to show a popup on node mouse hover. To add and remove a node

**Comment by mojoaxel** [comment]
> This issue tracker is not supposed to be used for questions on how to use visjs. It is intended to be used for bug reports and feature requests! In case you face yourself with a usage question, then post your question e.g. on stackoverflow tagged with "vis.js".

> Have you already used the github search, read the documentation and looked at the examples?
