### ISSUE TITLE
Click on node and it zooms out to the center of screen

### ISSUE THREAD

**Issue by amorigoye** [almende/vis#4191]
Hi, I am working on network visualization using vis.js. However, after creating my network with nodes I want to click on a node then it will zoom out to occupy the center of the screen alone.
someone help me do this. Thank you for your help. Appreciated in advance
[visdoc.docx](https://github.com/almende/vis/files/2576267/visdoc.docx)

**Comment by mojoaxel** [comment]
> This issue tracker is not supposed to be used for questions on how to use visjs. It is intended to be used for bug reports and feature requests! In case you face yourself with a usage question, then post your question e.g. on stackoverflow tagged with "vis.js".
