### ISSUE TITLE
How to do a node search in visjs network visualization

### ISSUE THREAD

**Issue by amorigoye** [almende/vis#4195]
Hi. Please I want to customize a network visualization and include a search button so that i can search for any node by label or id. Kindly guide me do this if it is possible. Thank you 
[NODAL.docx](https://github.com/almende/vis/files/2596221/NODAL.docx)

**Comment by mojoaxel** [comment]
@amorigoye Please use e.g. stackoverflow.com to ask these questions. Thx.
