### ISSUE TITLE
switch to develop as the default branch

### ISSUE THREAD

**Issue by DanielRuf** [almende/vis#4198]
Every contributor who forks this repo gets `master` as default so we have to recreate our PRs.

Please change the default branch in the project settings to `develop`.

**Comment by mojoaxel** [comment]
@DanielRuf Thanks for your idea to improve this project.
The decision to use a separate development branch and a stable master branch is in vis from its beginning. It was a decision by the almende-core team.

I'm also not a big fan of that but It makes sense for big projects to keep the public version as bug-free as possible. This of course only works if bug-fixes are merged and released in a timely manner. This is no longer the case!!

So I'm with you on that. But we should not just switch and break everything but do this together with the splitting of modules (#2405).

**Comment by DanielRuf** [comment]
I think you misunderstood my point. We have to switch to `develop` in the repo settings as default instead of `master`. Both branches will still exist.

**Comment by DanielRuf** [comment]
Because If you create a PR, the template says `develop` should be used otherwise the PR is closed. Changing branches then produces issues.

**Comment by mojoaxel** [comment]
@mojoaxel The problem is, that the default branch in github also defines the default sources view and the default branch if cloned (as far as I know). I'm not willing to make this decision.

**Comment by DanielRuf** [comment]
Well, why not? As stated in my issue, new contributors will create branches from the wrong branch (master).

**Comment by mojoaxel** [comment]
> Well, why not?

1. This project is based on the [Gitflow-Workflow](https://medium.com/@devmrin/learn-complete-gitflow-workflow-basics-how-to-from-start-to-finish-8756ad5b7394). Not everybody may like this (including me) but this is just how the creators of this project (many years ago) decided it for good reasons!
2.  Because the develop branch is untested and quite unstable at the moment.
3.  Because the `develop` branch has no `dist` folder. This folder is very much needed for the examples, the web-page and users that just want to use vis.
4. The package release process is based on `master`. No if this would work out-of the box with `develop`.

> As stated in my issue, new contributors will create branches from the wrong branch (master).

That contributors should use the `develop` branch is not intuitive but [well documented](https://github.com/almende/vis/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

@DanielRuf Maybe you want to take your time to read up on all the existing issues discussing this topic and many more concerning the release process.

To make one think clear: It's not my project, but I have write access and I'm willing to execute community decisions. But only if a minority of the community stands behind a decision and not one person.

What do others think?

**Comment by mojoaxel** [comment]
@DanielRuf You are really(!) very welcome to help with this project. I'm more than willing to simplify things but you have to acknowledge that this project is not a simple library but a real big monster with a long history and a muddled source base. If we can make sure nothing makes I'm the first person to get rid of the `develop` branch and make a release after every pull-request!

**Comment by DanielRuf** [comment]
> develop branch is untested and quite unstable at the moment

master too in general

> make a release after every pull-request!

Never saw this, not a great idea imho.

> This folder is very much needed for the examples, the web-page and users that just want to use vis

Dist files should not be tracked. And there is gh-pages as npm project and often used in CI.

> That contributors should use the develop branch is not intuitive but well documented.

Not well documented and a bit too late. It should be (also) documented in CONTRIBUTING.md.

**Comment by DanielRuf** [comment]
> develop branch is untested and quite unstable at the moment

master too in general

> make a release after every pull-request!

Never saw this, not a great idea imho.

> This folder is very much needed for the examples, the web-page and users that just want to use vis

Dist files should not be tracked. And there is gh-pages as npm project and often used in CI.

**Comment by DanielRuf** [comment]
> develop branch is untested and quite unstable at the moment

master too in general

> make a release after every pull-request!

Never saw this, not a great idea imho.

> This folder is very much needed for the examples, the web-page and users that just want to use vis

Dist files should not be tracked. And there is gh-pages as npm project and often used in CI. npm can store other files than in the GitHzb repo.

**Comment by techtonik** [comment]
Looking at the front page I thought that the project died year ago.

![image](https://user-images.githubusercontent.com/515889/50545688-70ac2380-0c2a-11e9-88ca-981455b8a036.png)

Keeping active development in `master` will prevent such confusion.

**Comment by DanielRuf** [comment]
Or by just switching the default branch to the `develop` branch in the GitHub repo settings.

**Comment by techtonik** [comment]
@DanielRuf so why you would need `master` then?

https://www.endoflineblog.com/gitflow-considered-harmful#the-master-develop-split-is-redundant

**Comment by DanielRuf** [comment]
In general master is for merging develop into it when creating a release (what we do in many big repos). It is not redundant.

**Comment by DanielRuf** [comment]
Not sure who writes this blog but not every commit is tagged. I think the person never used GitFlow in bigger projects where you have things like dev and release branches.

**Comment by DanielRuf** [comment]
You can also ignore merge commits in the history or filter them out + there is `--ff` and `--no-ff`.

**Comment by DanielRuf** [comment]
https://github.com/almende/vis/issues/4198#issuecomment-441274898

Release process and how zsers can use vis would be untouched by the change as you can use `only` in Travis CI and others to specify the build tasks based on the branch name.

**Comment by techtonik** [comment]
> In general master is for merging develop into it when creating a release (what we do in many big repos). It is not redundant.

https://yourlogicalfallacyis.com/bandwagon

Jumping on that train, some popular repos from Python ecosystem abandoned that practice. Popular != big.

> Not sure who writes this blog but not every commit is tagged.

https://yourlogicalfallacyis.com/strawman

Common, it is not that hard to understand what does he mean - take a look at current `master`. Eight last comments are tagged, and the rest do not affect the source code. https://github.com/almende/vis/commits/5563fc616885578ad51b2dfa6ccf70ccebf06126 There is no reason to isolate those untagged commits into separate branch. If you find one - link it here and we can continue.

> Let's not discuss about the pros and cons of the GitFlow model but make decisions here. The easiest is to change the default branch in the repo settings.

https://www.youtube.com/watch?v=-1CE4P8qqPE :D Sorry, couldn't resist.

**Comment by techtonik** [comment]
> Every contributor who forks this repo gets master as default so we have to recreate our PRs.

I agree with the problem, and your problem statement is awesome and I'd +1 that, but I don't like the solution that still requires too much git kung fu.

**Comment by DanielRuf** [comment]
> Jumping on that train, some popular repos from Python ecosystem abandoned that practice. Popular != big

Sorry but I'm also active contributor at such big projects.

> too much git kung fu

Not sure what you mean. A simple rebase is often sufficient. Or recloning the repo.

As it is not planned to change the default branch, let's close this duscussion.

**Comment by techtonik** [comment]
I opened a separate ticket to discuss OneFlow.
