### ISSUE TITLE
[timeline] 2 successive items should not be stacked

### ISSUE THREAD

**Issue by invitu** [almende/vis#4214]
In graph2D, we have 2 successive items (ie. date_end of the 1st one = date_start of the 2nd one)
Actual behaviour : 
- the items are stacked
Expected beheviour : 
- the items should not be stacked as they are successive

Note : 
- using the stack option to false is not a solution because we would like to see the items that really overlap
Tested with Google Chrome Version 68.0.3440.106 (Build officiel) (64 bits) (Linux Fedora 28)

**Comment by mpf82** [comment]
Have you tried to fiddle with ``options.margin.item.horizontal``? You could set it to 0 or -1 (default is 10).

**Comment by invitu** [comment]
@mpf82 Thank you it did the trick
