### ISSUE TITLE
How to show bar in one line

### ISSUE THREAD

**Issue by sunilepms** [almende/vis#4216]
Hello Team,

Our requirement is to show only one project timeline bar in the one line.

Also, when we are moving timeline bar using mouse the bar is auto adjusting with the other bar for fit. So how can we disable this feature.

We created plnkr and jsbin for reference. Please check and give you suggestion.

https://jsbin.com/zipoxozuji/edit?html,output
https://next.plnkr.co/edit/PgmO95OHodzKqKuN

When height is less and items are more, we are not able to see the focus on current moving bar.

**Comment by mojoaxel** [comment]
> This issue tracker is not supposed to be used for questions on how to use visjs. It is intended to be used for bug reports and feature requests! In case you face yourself with a usage question, then post your question e.g. on stackoverflow tagged with "vis.js".
