### ISSUE TITLE
⚠️ Vis.js - End of Live

### ISSUE THREAD

**Issue by mojoaxel** [almende/vis#4259]
_I'm thinking about opening this issues for many month now. Today the time has come_:

**This is the beginning of the end of vis as we know it - and hopefully a new beginning.**

### Current status
* There are still a lot of issues opened every week and even more issues are still open.
* vis has currently no real maintainer. I and some other people still have admin-access but nobody has the time to review pull-requests, commend on Issues or fix bugs.
* almende, the company that created vis is no more willing to spend any time or money on this project.

**This project can not go on like this!**

### Future steps
1. We, the current maintainers of this project have decided to archive this project what makes the project read-only. This means that no more issues or pull-requests can be created. The source-code and all releases are still available.
2. We want to invest one last boost of energy to merge as many pull-requests as possible/usefull and seperate the library in multiple components (network, timeline, grahp3d ...). This new libraries will find a new home in the already existent [visjs community](https://github.com/visjs) account. You can open new issues and pull-requests there, after we've moved.
3. We will try to move the existing [open-collective](https://opencollective.com/vis) to this new community to give every collaborator a chance to be reimbursed by the community.
4. We invite everybody interesting in supporting this project to start helping maintaining the seperate projects. It depends on you guys to give these new projects a new life by improving the code base and maintaining the new modules. In future, hopefully, this will become much easier as the projects are much smaller and more manageable.

This is propably going to happen in March 2019.

![phonenix by Andrés Montesinos, https://commons.wikimedia.org/w/index.php?curid=11875439](https://user-images.githubusercontent.com/600565/53044423-3c671d80-348b-11e9-901b-315f9414b529.png)
**vis.js is dead, long like visjs!**

**Comment by avrahamcool** [comment]
hi @mojoaxel 
you should pin this issue, so it'll be visible above all others.

**Comment by yotamberk** [comment]
The timeline has been separated to my fork here:
https://github.com/yotamberk/timeline-plus

It is maintained actively every week.
Soon it will move to visjs-community. Feel free to use it in the meantime until I can move it to the community.

**Comment by jgorene** [comment]
It would be cool to be able to leave this last version as operational as possible as @mojoaxel suggested on [#4197](https://github.com/almende/vis/issues/4197)

In fact and to take an example, if someone can make graph2d work properly from the latest version or even on the branch develop, good deal... 

Otherwise and in general if we can't fix this type of bugs,  wouldn't it be better down to an earlier version when the currently broken functionality was still working properly... until 4.20.1 for example?

I'm just wondering... and what do you think about that ?

**Comment by micahstubbs** [comment]
The network module lives on in our community fork here:
https://github.com/visjs-community/visjs-network

It is actively maintained, with multiple contributors from the visjs community ☺

We also publish regularly to npm https://www.npmjs.com/package/visjs-network

you can start using the latest visjs-network features & bug fixes today with the command:

`npm install visjs-network`

or

`yarn add visjs-network`

**Comment by micahstubbs** [comment]
like @yotamberk says, I do think it would be nice to have https://github.com/yotamberk/timeline-plus and https://github.com/visjs-community/visjs-network under a common github org, to make it easier visjs users to discover the projects and collaborate.

**Comment by mojoaxel** [comment]
@yotamberk @micahstubbs Feel free to move your projects to the [visjs community account](https://github.com/visjs) whenever you want!

**Comment by micahstubbs** [comment]
@mojoaxel I think that could make sense once vis itself migrates to https://github.com/visjs github org.  Do you know if there are plans to do that?

**Comment by mojoaxel** [comment]
> @mojoaxel I think that could make sense once vis itself migrates to https://github.com/visjs github org. Do you know if there are plans to do that?

The plan is not to migrate the whole project. Instead I'm planning of splitting it up into its modules (network, timeline..) and find a team of maintainers for each modules. (Looks good already!)
We than cloud create a meta-projects that includes all modules and releases one single _visjs.min.js_ for users who need this.

I'm planning to do this Mar/Apr 2019 as soon as I find the time.

**To anybody who wants to support/speed-up the migration: please consider funding the development using our opencollective: https://opencollective.com/vis**

**Comment by s7726** [comment]
https://github.com/almende/vis
https://github.com/visjs-community/
https://github.com/visjs
https://github.com/yotamberk/timeline-plus

This fragmentation is tough to sort through.

**Comment by mojoaxel** [comment]
> This fragmentation is tough to sort through.

Yes, it is! :disappointed: 
I hope we can merge all this into one organization again within the coming weeks.

**Comment by oussjarrousse** [comment]
Time to merge/move guys! How can i help?

**Comment by tronin** [comment]
You have to archive the project as soon as possible. Hope is not a solution.

**Comment by mojoaxel** [comment]
> You have to archive the project as soon as possible.

Finding time is not easy but I have scheduled the transfomation fom the `almende` to the `visjs` account for the 8-9.06.2019.

**Comment by WhitecastlePT** [comment]
Well i'm sad this awesome plugin is going to end...i have been using mainly because of timeline.
Since TimeLine is going to be separate project, will it have a migration documentation from vis.js timeline to timeline-plus from https://github.com/yotamberk/timeline-plus ? @yotamberk

Btw i made a 5 dolar contribution https://opencollective.com/vis#budget

**Comment by mojoaxel** [comment]
I'm starting the process of moving [alemde/vis](https://github.com/almende/vis) to the [visjs community](https://github.com/almende/vis) NOW.
If you have questions you can reach me here: https://gitter.im/vis-js/Lobby

**Comment by mojoaxel** [comment]
Here i'm going to track the progress of the transformation and document what I did (for future maintainers maybe!?)
- I have forked [almende/vis](https://github.com/almende/vis/) to [visjs/vis](https://github.com/visjs/vis) for further development.
- Updated repository details
- created a new Webpage for the community: https://github.com/visjs/www.visjs.org

**Comment by hypery2k** [comment]
> > This fragmentation is tough to sort through.
> 
> Yes, it is! 😞
> I hope we can merge all this into one organization again within the coming weeks.

Any news on the merge? ;)

**Comment by mojoaxel** [comment]
> Any news on the merge? ;)

I'm happy to say that I managed to leap a giant step forward yesterday: I removed gulp/webpack in favor of rollup and can now start to split the [vis-charts](https://github.com/visjs/vis-charts) library in separated projects - saving the git commit history :-)

If everything works out like I planned it I can release the new libraries this weekend or next week.

After that this repository finally gets archived and the new libraries can be used...

After I delivered what I promised I hope that @yotamberk and the others will (again) join the visjs community :pray:

**Comment by drscotthawley** [comment]
Help?  I just discovered vis.js and graph3d over the weekend and was quickly able to do *almost* what I needed but still need to (learn how to) make a few changes..
After reading the web pages and then this thread, I'm confused about how to ask questions and/or contribute.  

I've read the [How to help](https://github.com/almende/vis/blob/develop/misc/how_to_help.md) post, but then when I go over to [visjs community](https://github.com/visjs) I don't see graph3d on the list, and when I go inside [vis_original](https://github.com/visjs/vis_original) there's some graph3d stuff but there's no Issues or Pull Requests tabs. 

Can someone advise, re. which account or repository I should be looking at?    

Literally, all I want to do is plot a bunch of points in 3D, except make some the markers not all circles (e.g. make some of them squares or crosses or something). 

Thanks!

**Comment by mojoaxel** [comment]
> I'm confused about how to ask questions and/or contribute.

@drscotthawley You have every reason to be confused!
At the moment we are moving everything to the visjs community, but this is not finished, yet.

There is a very good chance that a `vis-garph3d` repository will pop up in the visjs community during the next days. Than you are very welcome to contribute.

> For now I've started my own fork 

This is probably not the best thing to do...already so much confusion.

**Comment by yotamberk** [comment]
Hey guys.
I plan to move https://github.com/yotamberk/timeline-plus  to vis-community this Saturday.
I hope the confusion with the timeline will be cleared up with the transfer

**Comment by mojoaxel** [comment]
> I plan to move https://github.com/yotamberk/timeline-plus to vis-community this Saturday.

@yotamberk [visjs-community](https://github.com/visjs-community) or [visjs comunity](https://github.com/visjs) ?

**Comment by mojoaxel** [comment]
@drscotthawley I just publishes [vis-graph3d](https://github.com/visjs/vis-graph3d). Feel free to use try it.

**Comment by yotamberk** [comment]
I understand what you're saying. To be fair, there were many legitimate reasons why I copied the project and not forked it in the first place, mainly due to having a real hard time trying to advance timeline without a lot of noise and restrictions of the project, whilst disagreement of the owners to separate the modules in the first place.
I'm glad the separation was done at the end - though a little too late since now the continues work done in the copy and merging them in visjs-community will be much much more difficult....

I did said I will be willing to work on re-merging the work done in my copy starting on Saturday.
I have no idea how much work will actually need to be done to achieve this goal but I will definitely give it a try for the sake of reason!
Since this will be probably a lot of work, I will ask to receive part of the open-collective funds. I will assess the work and discuss openly how much work, time and effort I'm willing to do and for the portion of the funds.

I'm also willing to continue as the main maintainer of this module as long as I have full access and ownership on it.

**Comment by mojoaxel** [comment]
> I understand what you're saying...

I'm really happy that you understand. Also I'm sorry that this took me so long! I'm looking forward working with you again!

> I have no idea how much work will actually need to be done to achieve this goal but I will definitely give it a try for the sake of reason!

:+1: Great! I'll help if I can.

> Since this will be probably a lot of work, I will ask to receive part of the open-collective funds. I will assess the work and discuss openly how much work, time and effort I'm willing to do and for the portion of the funds.

This sounds reasonable! I also hope to get some of the funds for doing the separation into modules. I'm sure we will figure this out!!

**I really hope that some people here read what we are saying and consider becoming a [sponsor](https://opencollective.com/visjs/contribute) to support further development! We think we have proven that we are willing to keep this project going, but we need funds to finance all this work.  :pray:**

> I'm also willing to continue as the main maintainer of this module as long as I have full access and ownership on it.

I just released the new [vis-network](https://github.com/visjs/vis-network) module. The timeline is the only one still missing. I'll finish the separation this week and and than we can try to update it together. As soon as the repository exists I'll give you full access (of course!)

**Comment by richardeaxon** [comment]
Glad to see that the new https://github.com/visjs/vis-network has been released. Works great as a replacement for almende vis. Are there any plans to merge the pull requests left behind on almende vis into the new community vis?

**Comment by micahstubbs** [comment]
hi @richardeaxon, we've already done this 😄 

We have merged all of the active, working network-related PRs from almende/vis - you can see the list here https://github.com/visjs-community/visjs-network/pulls?q=is%3Apr+is%3Aclosed

Install via yarn:

```
yarn add visjs-network
```

Install via npm:

```
npm install visjs-network
```

**Comment by micahstubbs** [comment]
I'm not sure what the status of @mojoaxel's fork is wrt to including open PRs from almende/vis. He probably knows more about that.

**Comment by mojoaxel** [comment]
> Glad to see that the new https://github.com/visjs/vis-network has been released. Works great as a replacement for almende vis. 

Thanks! It was a peace of work! But I'm olso happy that we are finally getting somewhere..

> Are there any plans to merge the pull requests left behind on almende vis into the new community vis?

I'll contact the original contributors and ask them if are willing to reopen theirs pull request at the new repository. If they don't we will properly move them one by one. But to be honest I would prefer the original contributors to provide their code. This way they get attribution an maybe feel more responsible to fix bugs in "their" code and maybe even get more involved.

**Comment by hypery2k** [comment]
one question: What do you think about merging my [angular-integration](https://github.com/hypery2k/ngx-vis) to [vis org](https://github.com/visjs)? I would still maintain it there.

**Comment by mojoaxel** [comment]
> one question: What do you think about merging my angular-integration to vis org? I would still maintain it there.

[ngx-vis](https://github.com/hypery2k/ngx-vis) Looks very promising! 
I would love it if you would consider moving it to the [visjs community](https://github.com/visjs). Maybe the best way would be to also seperate it into a timeline and a network part or even add the new ngx-classes directly into the new libraries. I'm not sure what the best way is at the moment. Also we already have someone moving everything to typescript. We should discuss this nice idea further!!

I think the best way would be to open an issue at [vis-network](https://github.com/visjs/vis-network) and discuss the best way to approach this over there.

**Comment by mojoaxel** [comment]
I'm happy to announce that vis.js is now fully managed by the community:
* [x] The homepage www.visjs.org is now maintained in a separated repository: [/visjs/www.visjs.org](https://github.com/visjs/www.visjs.org)
* [x] The library has been spit up into multible modules:
   * [vis-network](https://github.com/visjs/vis-network)
   * [vis-timeline](https://github.com/visjs/vis-timeline)
   * [vis-graph3d](https://github.com/visjs/vis-graph3d)
   * [vis-data](https://github.com/visjs/vis-data)
* [x] There is now a [awesome list of vis.js ressources](https://github.com/visjs/awesome-visjs).

**Please feel free to contribute to the new repositories and/or [sponsor further development](https://opencollective.com/visjs/contribute).**

![pinya-dance](https://user-images.githubusercontent.com/600565/61700481-134e0000-ad3d-11e9-8e62-44e8e504cbd4.gif)
