### ISSUE TITLE
Military time to standard time

### ISSUE THREAD

**Issue by SciGno** [almende/vis#427]
Hello and thank you for such a great visualization tool.

I was wondering if there was a way to change the time in the timeline from military to standard.  The reason for this is that a lot of my clients are older people and I need to make the timeline more user friendly for them.  Believe it or not, it is hard for some people to convert military time to standard.  :(

I'm not sure how it is being done but since military time is a consistent 5 character string __00:00__, I think that maybe you can add 3 more strings __12:00 AM__ and recalculate the spacing between them.  This is just a suggestion that would greatly appreciate.

Or maybe you can provide me to the location in your code where I can play with this and see if I can make it work.

Thanks in advance for any input.

**Comment by AlexDM0** [comment]
Hi,

Over the last year a lot of feature requests have been made. We have just introduced our new website which has a list of the requested features. We have placed this request on that list. 

The list can be found here:
http://visjs.org/featureRequests.html

An explaination of the new system can be found here:
http://visjs.org/blog.html#New\ website\ for\ vis\.js\!

I would like to stress that this does not mean we abandon this request. Discussion here will continue if needed on this feature but we will close it to keep our Github issue page more of a bug-todo list.

Future feature requests will still be made here and then added to the website by us.

Regards,

Alex

**Comment by josdejong** [comment]
This feature is implemented in v3.8.0.

**Comment by DivyashreeMS** [comment]
Hi 

I had a small requirement in vis.Timeline that is how to make the timeslot that is shown at the bottom clickable. For instance if I click at 6:30 i should be able to get that value in JS. please help as this is a urgent requirement 

Regards
Divya

**Comment by josdejong** [comment]
@DivyashreeMS your question seem not related to this issue, please create a separate issue next time. What you can do is add an `onclick` handler to the container DIV holding the Timeline, and when clicked, figure out whether the `event.target` is a time axis label and if so, do something.
