### ISSUE TITLE
Can vis.js support hundreds of thousands of nodes?

### ISSUE THREAD

**Issue by zhaodagang** [almende/vis#4272]
Can vis.js support hundreds of thousands of nodes?

**Comment by JoshuaWalsh** [comment]
Which vis.js module are you using? [Here's](http://visjs.org/examples/network/exampleApplications/worldCupPerformance.html) an example of using Network with over 9000 edges, you can see the performance is not great. And [here's](http://visjs.org/examples/timeline/other/performance.html) an example of Timeline with as many items as you want. Timeline can have very large numbers of items loaded, but having more than a few hundred visible at once will cause lag.

If you're talking about another module, take a look at the examples for that module. I think most (all?) modules have some kind of performance example.

**Comment by zhaodagang** [comment]
ok, thank your for your suggestion
