### ISSUE TITLE
Git flow chart

### ISSUE THREAD

**Issue by IsaacHub** [almende/vis#4281]
I want to build exactly as in this image, how can I achieve this?

![Screenshot from 2019-04-10 18-42-52](https://user-images.githubusercontent.com/20126441/55942201-85547a80-5c61-11e9-851c-7f86a57672b9.png)

Each and every row must hold an id and those must be clickable, and upon clicking it I need to console log the id of the row which was clicked.

Right now I have this:

![gitgraph](https://user-images.githubusercontent.com/20126441/55943289-ef6e1f00-5c63-11e9-9b86-947b3ece2783.PNG)

**Comment by mojoaxel** [comment]
> * This issue tracker is not supposed to be used for questions on how to use visjs. It is intended to be used for bug reports and feature requests! In case you face yourself with a usage question, then post your question e.g. on [stackoverflow](https://stackoverflow.com/questions/tagged/vis.js) tagged with "vis.js".
> * Make sure to mention which vis-component (network, timeline, graph2D, graph3d) you are referring to.
