### ISSUE TITLE
Github Pages site for visjs.org down

### ISSUE THREAD

**Issue by errnoh** [almende/vis#4297]
Getting 404 `There isn't a GitHub Pages site here.`

( While waiting for the site to come up https://htmlpreview.github.io/?https://raw.githubusercontent.com/almende/vis/master/docs/network/index.html is a good way for reading the documentation. )

**Comment by jgorene** [comment]
Yes, I'm confused because it's due to my mistake, I'm sorry.
Thank you for this temporary link.

That it should be back to normal soon...

Special thanks to team vis !
Fortunately, the team remained united and very effective to solving this problem.

**Comment by mojoaxel** [comment]
I contacted almende today and I'm waiting for new access rights to solve this problem as soon as possible.

**Comment by mojoaxel** [comment]
Thanks to @ludost from almende.
http://visjs.org is back online.
