### ISSUE TITLE
network: fix/unfix node position

### ISSUE THREAD

**Issue by klmdb** [almende/vis#430]
Hi,

An idea for a feature: instead of just setting allowedToMoveX and allowedToMoveY on a node, which not only fixes the node's position in the stabilization process but also disables drag functionality, let us set options like 'node.disableMove' and 'node.disableDrag'.

For now I implemented this behaviour like this:

			priv.enableNodeMoveFactory =function(node){
				return function(nodeIds){

					// enable move
	        		node.allowedToMoveX = true;
	        		node.allowedToMoveY = true;

	        		publ.updateNode(node);
				};
			};
			priv.disableNodeMoveFactory =function(node){
				return function(nodeIds){

					// disable move
	        		node.allowedToMoveX = false;
	        		node.allowedToMoveY = false;

	        		publ.updateNode(node);
				};
			};
	        // fixes a node's position while preserving drag functionality
	        publ.fixNode = function(node){

	        	// fix node
        		node.allowedToMoveX = false;
        		node.allowedToMoveY = false;

        		// create drag eventHandlers
				node.eventHandlers = node.eventHandlers || {};
				node.eventHandlers.enableNodeMove  = priv.enableNodeMoveFactory(  node );
				node.eventHandlers.disableNodeMove = priv.disableNodeMoveFactory( node );

				// set drag handlers: enable move on dragStart, disable move on dragEnd
        		priv.network.on('dragStart', node.eventHandlers.enableNodeMove );
        		priv.network.on('dragEnd'  , node.eventHandlers.disableNodeMove);

        		publ.updateNode(node);
	        };
	        publ.unfixNode = function(node){

        		node.allowedToMoveX = true;
        		node.allowedToMoveY = true;

        		publ.updateNode(node);

        		priv.network.off('dragStart', node.eventHandlers.enableNodeMove );
        		priv.network.off('dragEnd'  , node.eventHandlers.disableNodeMove);
	        };

**Comment by AlexDM0** [comment]
Hi,

Over the last year a lot of feature requests have been made. We have just introduced our new website which has a list of the requested features. We have placed this request on that list. 

The list can be found here:
http://visjs.org/featureRequests.html

An explaination of the new system can be found here:
http://visjs.org/blog.html#New\ website\ for\ vis\.js\!

I would like to stress that this does not mean we abandon this request. Discussion here will continue if needed on this feature but we will close it to keep our Github issue page more of a bug-todo list.

Future feature requests will still be made here and then added to the website by us.

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi, 

This is now available in 4.0.

Regards,

Alex

**Comment by sukhmel** [comment]
I can't find anything except for `Node.fixed` nor in docs, neither in code. Could you point out to where is this implemented or a relevant doc/example?

**Comment by wimrijnders** [comment]
It's in [the docs](http://visjs.org/docs/network/nodes.html).  Scroll down to option `fixed`.

In the code, it's hard to pinpoint an exact position, because it's used in many places, mostly as a condition.

You take see an example of its usage in the [nodeLegend](http://visjs.org/examples/network/exampleApplications/nodeLegend.html) demo.

**Comment by sukhmel** [comment]
@wimrijnders this is not really what is described in opening post, so I thought, this is not what meant by `this is now available`. Seems like there is no other way to fix nodes other than modifying its properties.

**Comment by wimrijnders** [comment]
@sukhmel I thought I was answering your question here. I sort of missed the 'except for'....

I agree that @AlexDM0's comment is very terse. Also, in [the history](https://github.com/almende/vis/blob/master/HISTORY.md) under version 4.0.0, the option to disable dragging is not mentioned explicitly.

However, I do think that option `fixed` is meant as a solution for this issue. There are no other options available to disable the dragging of a particular node. Do you think this is not an adequate solution?
