### ISSUE TITLE
Localization issue (I tested fr and de)

### ISSUE THREAD

**Issue by seb49** [almende/vis#431]
Hello,

I discover http://visjs.org/examples/graph2d/13_localization.htmland I have discovered a bug when I change localization to fr and de.
After I change localization, the graph is not "synchronize" with the grid when I zoom into the graph. The points are not a the good position

![localize_error_1](https://cloud.githubusercontent.com/assets/2581756/4918420/3bab599c-64f1-11e4-8024-9db87d9eeddf.png)
![localize_error_2](https://cloud.githubusercontent.com/assets/2581756/4918453/72c9056e-64f1-11e4-975a-ebc2f45e5c3f.png)
![localize_error_3](https://cloud.githubusercontent.com/assets/2581756/4918463/7cbb1648-64f1-11e4-8f55-75903cf8fdc4.png)

Regards

**Comment by amelnikoff** [comment]
> If you specify it: http://jsfiddle.net/48Lpsk4e/1/ everything works.
I last version 4.2.0 it not working and throws exception

Uncaught TypeError: Cannot read property 'object' of undefinedcheckFields @ vis.js:22269check @ vis.js:22243parse @ vis.js:22223checkFields @ vis.js:22282check @ vis.js:22249parse @ vis.js:22223validate @ vis.js:22208Timeline.setOptions @ vis.js:10026Timeline @ vis.js:9995window.onload @ (index):64

**Comment by amelnikoff** [comment]
Strange.
Without options.locales everything works.

**Comment by josdejong** [comment]
@amelnikoff see https://github.com/almende/vis/issues/950

**Comment by sexposit** [comment]
hello,

can someone help me with vis.js??

I have to change the language from the timeline to spanish.

First, I try to change the language to Dutch with this code "locale:'nl'" but don't work.

I don't know why it  don't work.

var options = {
       
        dataAxis: {showMinorLabels: false},
        dataAxis: { left: { range: {min:0, max:180} }, right: { range: {min:0, max:20} } },
        legend: {left:{position:"bottom-left"}},
        start: '2016-06-09',
        end: '2016-06-17',
        locale:'nl'
    };

regards

**Comment by josdejong** [comment]
Check out this localization example http://visjs.org/examples/timeline/other/localization.html

**Comment by sexposit** [comment]
Thak you very much Jos.

it's working :)

**Comment by josdejong** [comment]
Ok great, have fun.

**Comment by GowrishankarGeek** [comment]
Hi im working with visjs network really i have to thank for visjs team its very useful for us. i have one doubt i want change text edit to ->>>> edit component like that..i tried lot of example i couldn't able to find please help me.
Getting this error: (TypeError: Cannot read property 'object' of undefined)

 var options = {
        locales: {
     my: {
    edit: 'Edit',
    del: 'Delete selected',
    back: 'Back',
    addNode: 'Add Node',
    addEdge: 'Add Edge',
    editNode: 'Edit Node',
    editEdge: 'Edit Edge',
    addDescription: 'Click in an empty space to place a new node.',
    edgeDescription: 'Click on a node and drag the edge to another node to connect them.',
    editEdgeDescription: 'Click on the control points and drag them to a node to connect to it.',
    createEdgeError: 'Cannot link edges to a cluster.',
    deleteClusterError: 'Clusters cannot be deleted.',
    editClusterError: 'Clusters cannot be edited.'
  }
  },
        locale: 'my',
}

**Comment by josdejong** [comment]
The `options` you post are correct, so this error probably comes from somewhere else
