### ISSUE TITLE
vis.util.randomUUID() does not produce standard compliant UUIDs

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#432]
I think there is a problem with the UUID generation. Your ID looks like an RFC 4122 UUID Version 4 (random) (see http://en.wikipedia.org/wiki/Universally_unique_identifier)
which has to have this format: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx

x .. hex digit random generation
y .. has to be: 8, 9, a, b

eg: 540618a7-ab80-4cbc-b634-6c809fc3575a

Your IDs are ok, if you don't care about the standard, but it will be confusing if 3rd party SW has to work with your ID. Imo some users will expect a standard compliant id.

Since it's easy to change, maybe you should consider making your ID mechanism standard compliant?

maybe consider this approach:
http://chat-plugins.tiddlyspace.com/#UUIDPlugin

Regards
Felix

**Comment by AlexDM0** [comment]
Hi all, 

I've updated v4 to use the uuid library uuid v4 uuid's.

https://www.npmjs.org/package/uuid

I have put a pull req in with the author to have it working on browsers but for now I've copied it over into our codebase with minor changes (browsers dont use the global variable, they have the window variable..)

Regards,

Alex

**Comment by felixhayashi** [comment]
Nice thanks

**Comment by AlexDM0** [comment]
With the launch of v4, this issue can be closed.
