### ISSUE TITLE
Dragging subgroups (up/down) to change the order.

### ISSUE THREAD

**Issue by nsconde** [almende/vis#435]
It would be great if it would be possible to not only drag events, but also groups and sub groups.  Right now, I have a button the user presses on each lane that selects the children and drags all the events at the same time. However, I think it would be a useful feature to be able to drag a subgroup, whether it be a background or a sub group, and drag its children.  I hope that makes sense.

**Comment by AlexDM0** [comment]
Hi,

Over the last year a lot of feature requests have been made. We have just introduced our new website which has a list of the requested features. We have placed this request on that list. 

The list can be found here:
http://visjs.org/featureRequests.html

An explaination of the new system can be found here:
http://visjs.org/blog.html#New\ website\ for\ vis\.js\!

I would like to stress that this does not mean we abandon this request. Discussion here will continue if needed on this feature but we will close it to keep our Github issue page more of a bug-todo list.

Future feature requests will still be made here and then added to the website by us.

Regards,

Alex

**Comment by mojoaxel** [comment]
Reopening as Feature-Request issue (see #2114). 
Everybody: Please feel free to implement this!

**Comment by yotamberk** [comment]
With #1109 it is possible to drag and reorder groups. To reorder items, you can use the multiselect and drag multiple items between groups. It doesn't make sense to drag all the content from group to group within the timeline. It should be implemented by you.
