### ISSUE TITLE
Move item to other group with touch gestures

### ISSUE THREAD

**Issue by AlexanderDaniel** [almende/vis#443]
When using [Timeline | Order Groups example](http://visjs.org/examples/timeline/09_order_groups.html) on a desktop browser with a mouse items can be moved to another group.

On a touch device items can be moved horizontally within a group but moving items vertically to a different group does not work.

Tested with
- iOS 8.1 Safari & Chrome
- iOS 7.1.2 Safari & Chrome
- Android 4.4.2 Chrome

**Comment by josdejong** [comment]
This should be fixed now in the `develop` branch. Was a tough one, turns out `event.target` behaves different on mobile devices...

**Comment by AlexanderDaniel** [comment]
@josdejong Thanks for the fix!
