### ISSUE TITLE
No user support for, or lack of programmer documentation for configuring, the editing the label of a node

### ISSUE THREAD

**Issue by shannon-morahan** [almende/vis#445]
It may be a "feature request", but most other user focused operations are already available.

Allowing the graph to out-of-the-box edit labels is essential to complete what is an awesome implementation would complete the comprehensiveness of out-of-the-box behavior.

A simple text input on double click and update the node label property on the client would give developers the out-of-the-box solution to, say, creating a mind-map.

**Comment by AlexDM0** [comment]
I'll close this issue due to inactivity and I feel the question is adressed. If you do not agree, please let me know so we can continue the discussion.
