### ISSUE TITLE
Timeline: Backgrounds are editable (movable/draggable) wenn defining a "height" of the timeline

### ISSUE THREAD

**Issue by mast0r** [almende/vis#454]
If creating an item of type "background" it should not be editable at all:

From documentation:
"Configuration Options: type -> Items of type 'background' are not editable. "

But wenn the height of the timeline is set then all backgrounds are movable / draggable.

Example like from the vis: http://jsfiddle.net/za36ec6d/
After the timeline is completely loaded you need first click on on the "background" element. The you will be able to drag it around.

**Comment by janat08** [comment]
http://jsfiddle.net/u0wLpyx6/
Isn't as editable as I would've liked.
