### ISSUE TITLE
widthMin and widthMax issue

### ISSUE THREAD

**Issue by JesseLivingston1** [almende/vis#457]
Greetings,

I am working on a project that uses the Network graph and am having issues controlling the size of the node images. I've used PNG and SVG files and neither respond to the widthMin and widthMax properties. The only way I can control the size is to use a PNG image and change the native file size, which results in some very blurry images. I do have "shape" set to "image".

Any ideas why this is happening? Thanks in advance,

Jesse

**Comment by AlexDM0** [comment]
Hi, 

Is this still an issue?

Regards,

Alex
