### ISSUE TITLE
Network Rendering

### ISSUE THREAD

**Issue by superman3275** [almende/vis#473]
I can't seem to get networks to render correctly. Here's what I've tried:

1) Default settings for everything, just add in my nodes and edges.
PROBLEM: Everything overlaps, and it looks really bad. Nodes stick together. It's just plain weird.

2) Hierarchical Layout:
PROBLEM: Normal hierarchical layout doesn't work, so I wrote a custom BFS algorithm to go from the start node and assign levels to everything. This works great! Except VisJS somehow manages to position the nodes on a level in just the right way so that there's the maximum amount of edge overlap. Also, when it's first rendered, EVERYTHING ON THE SAME LEVEL IS RENDERED TOGETHER! All the nodes on one level will render as one node, and you have to move one of them for the graph to render properly.

3) Hierarchical Layout Redux:
This time I played with the physics a little bit. The graph still had ALL of the problems above no matter what I did.

I'm converting a generic graph rendering application (using NetworkX and Python) into a web-application. NetworkX graphs look better, but the terrible positioning / rendering engine is making me consider switching to a different framework. At least the old application made sure edges didn't overlap.

Any insight into how I can prevent all of the nodes rendering on top of each other / edges colliding? I have read through the entire Network documentation page a couple times, and I can't find anything on this issue. It's baffling to me that a problem this flagrant hasn't even been mentioned in the documentation.

**Comment by AlexDM0** [comment]
There have been some releases since, is this still an issue?

**Comment by superman3275** [comment]
I ended up just writing a custom BFS algorithm to assign the levels. I'll
check tonight to see if there's still an issue using the default rendering.
