### ISSUE TITLE
Bug in network node coloring on hover events

### ISSUE THREAD

**Issue by vpodpecan** [almende/vis#477]
It seems that the shape **'box'** can cause a problem for hover events.
For example, if this is defined for a node group:

     .... 'color': {'hover': {'background': 'red', 'border': 'red'}, 'highlight': 'green'}, 'shape': 'box'   ....

then it does not work as it should (on hover only the border gets red color).
But if I omit the shape or use any other shape, it works (the background and the border are red on hover).
For example, this works:

     .... 'color': {'hover': {'background': 'red', 'border': 'red'}, 'highlight': 'green'},  ....

It does not help either if I move the shape definition from the group to each node.

**Comment by AlexDM0** [comment]
Hi,

I have pushed two fixes for cases 1 and 3 (as 2 is not a bug :)) to the develop branch. Groups now extend the default settings, not replace.

Regards,

Alex
