### ISSUE TITLE
timeline item content links broken on android devices

### ISSUE THREAD

**Issue by GluedToTheScreen** [almende/vis#480]
I was thinking the problem was in my app, but discovered that links do not appear to work in android.  I've tried this example using both a tablet and phone with both Chrome and Firefox browsers:

http://visjs.org/examples/timeline/04_html_data.html
Try the link in item 7.

EDIT:  forgot to check... it's the same on ipad, too... Chrome and Safari.

The item does get selected but the link fails to respond.  I also tried a class event click handler with the same results.  Any ideas?

**Comment by GluedToTheScreen** [comment]
I was hoping I'd missed something in the new release but this problem persists.  

While you can select timeline items themselves, HTML links inside them still doesn't work on Android and, in many cases, Ipad.
http://visjs.org/examples/timeline/04_html_data.html
Try the link in item 7.

You had mentioned that maybe Hammer was at the root of the issue.  I've gotten lost trying to find a clue inside vis.  Seems like it should be pretty basic but is actually quite confusing.

The new website is great.  If I can make one suggestion, please consider having the top nav bar present on all pages... I've sometimes ended up at a place and didn't quite know how to get to another section.

**Comment by AlexDM0** [comment]
I think it is now present everywhere, except the docs. This was changed yesterday. If you find some place where it is not, please let me know! 

As for the issue, I don't think it's solved at the moment. @josdejong could probably shed some light on this.

Regards,

Alex

**Comment by josdejong** [comment]
This issue is indeed still open and unresolved.

**Comment by josdejong** [comment]
This was resolved in v4.x
