### ISSUE TITLE
Timeline item - include id?

### ISSUE THREAD

**Issue by MojoDK** [almende/vis#490]
A timeline item looks like this...
`<div class="item range" style="left: 106.354166666667px; width: 276.520833333333px; top: 1px;"><div class="content" style="left: 0px;">Bla bla</div></div>`

Is it possible to include the id (data-id) - like this...
`<div class="item range" data-id="1" ....`

Thanks

**Comment by josdejong** [comment]
I suppose this is solved? Will close this issue now
