### ISSUE TITLE
Command click for Mac users

### ISSUE THREAD

**Issue by mcshaman** [almende/vis#495]
Its great that you can `shift` click to select a rang of elements. `control` click, as you would expect on a Windows platform, allows you to select multiple individual elements. However, on a Mac platform, the `command` key is used for this selecting technique. `control` clicking brings up a contextual menu (like right mouse clicking).

For the sake of inclusiveness it would probably be good if vis detected what operating system the user was using an mapped the right key respectively.

**Comment by josdejong** [comment]
This was resolved in v4 (see https://github.com/almende/vis/commit/626d4b9b8b95353370fe0e1481c75c5482340738)
