### ISSUE TITLE
Graph2d, non-zero origin shown in y axis with small numbers and showMinorLabels

### ISSUE THREAD

**Issue by bhspencer** [almende/vis#501]
When using small numbers and using the option showMinorLabels the origin on the y axis is a small non-zero number. In the below case the origin is 6.9389e-18 rather than zero.

See the following jsFiddle for an example.
http://jsfiddle.net/5L9kpL4t/1/

**Comment by AlexDM0** [comment]
Hi Spencer, 

Jos fixed this in the develop branch. We'll release a new version soon(ish).

Regards,

Alex
