### ISSUE TITLE
Physics options are Duplicated when a graph is drawn

### ISSUE THREAD

**Issue by qazimir** [almende/vis#502]
Hi,
I found an issue when the graph is drawn with option ```configurePhysics:true```
I used your example 25_physics_configuration and just added button with ```onclick="draw();"``` function.
Plunker: http://plnkr.co/xJiD5Lb3gSPAJlA8qn8q
Click the Draw graph button and you will see that some tables with physics options will be duplicated.

Q.

**Comment by AlexDM0** [comment]
Hi Qazimir,

I have pushed a fix to the develop branch.

Regards,

Alex
