### ISSUE TITLE
Graph2d data points move with respect to the x axis as the browser window is resized.

### ISSUE THREAD

**Issue by bhspencer** [almende/vis#509]
As you resize the browser window horizontally the devisions on the x axis get closer together as you would expect, however the data does not rescale. As a result of this you end up with the data shifting to the right and no-longer correctly aligns with the x axis.

You can see this with the first Graph2d example.
http://visjs.org/examples/graph2d/01_basic.html

Load the above example with the browser window filling the screen and all is well. Now drag the right edge of the browser window making it narrower and you will see the data move to the right with respect to the x axis. I could reproduce this issue in both Chrome and Firefox.

Screen shot 1 shows the graph before the browser window is resized. Note that the first data point is correctly shown on "Wed 11". Now look at screenshot 2 where the window has been made smaller. The first data point is now incorrectly shown on "Fri 13".

![screen shot 1](https://cloud.githubusercontent.com/assets/1049160/5404352/5e1f6d9e-8164-11e4-8ae4-2b8b33a5d26a.png)

![screen shot 2](https://cloud.githubusercontent.com/assets/1049160/5404351/5e1e0a30-8164-11e4-90b2-0b9ff69e701b.png)

**Comment by AlexDM0** [comment]
Hi Spencer,

As noted in #534, this is now solved in the develop branch. We'll release a new version soon.

Regards,

Alex
