### ISSUE TITLE
Graph2d setting the dataaxis.width option causes the data to be offset on the x axis on the first rendering

### ISSUE THREAD

**Issue by bhspencer** [almende/vis#510]
See the following jsFiddle 
http://jsfiddle.net/5L9kpL4t/3/

The first datapoint has an x value of "2014-06-12" and is rendered in the correct position.

Now in this second jsFiddle I have set the dataaxis.width in the Graph2d options. That is the only change made.
http://jsfiddle.net/5L9kpL4t/2/

All of the data points have been shifted to the right. The first datapoint now looks to be rendered on the 14th rather than the 12th.

The first manual interaction with the graph, scrolling or zooming and the datapoints jump back to the left and are correct. Explicitly calling Graph2d.redraw() does not fix the issue.

**Comment by AlexDM0** [comment]
Hi Spencer,

I have pushed a fix for this to the develop branch. Hopefully we'll do a new release soon(ish).

Regards,

Alex
