### ISSUE TITLE
Network localization documentation is outdated

### ISSUE THREAD

**Issue by anzeljg** [almende/vis#513]
Network localization documentation (at http://visjs.org/docs/network.html#Localization) is outdated. Some keys in mylocale array have been obviously changed. These are: add => addNode, link => addEdge and linkDescription => edgeDescription

Here is the version that works for me - and Slovenian translation at the same time :)

locales: {
    // slovenian locale
    mylocale: {
        addNode: 'Dodaj vozli\u0161\u010De',
        edit: 'Uredi',
        addEdge: 'Dodaj povezavo',
        del: 'Izbri\u0161i',
        editNode: 'Uredi vozli\u0161\u010De',
        editEdge: 'Uredi povezavo',
        back: 'Nazaj',
        addDescription: 'Za dodajanje vozli\u0161\u010Da klikni na prazen prostor.',
        edgeDescription: 'Klikni vozli\u0161\u010De in povleci povezavo do drugega vozli\u0161\u010Da.',
        editEdgeDescription: 'Klikni kontrolno to\u010Dko in jo povleci do drugega vozli\u0161\u010Da.',
        createEdgeError: 'Ne morem povezati povezave z gru\u010Do.',
        deleteClusterError: 'Gru\u010De ne morem izbrisati.'
    }
},

**Comment by AlexDM0** [comment]
Hi Anzeljg,

Thanks for letting us know. I have updated it on the develop branch. We'll update it on de website with our next release.

Regards,

Alex
