### ISSUE TITLE
Node Spread

### ISSUE THREAD

**Issue by SteveLillis** [almende/vis#519]
Hiya, I'm sure this is something I'm doing wrong with the settings, but I can't figure out how to get the little island of nodes on the right to stop drifting so far from the main clump.

![image](https://cloud.githubusercontent.com/assets/9628407/5497697/125ece06-870c-11e4-82ea-5ae8cfde77dd.png)

Can you point me in the right direction?  (fantastic library btw!)

**Comment by AlexDM0** [comment]
Hi Steve,

Is this still an issue?

Regards,

Alex

**Comment by SteveLillis** [comment]
Hi Alex, your advice completely resolved it. Thanks very much!
