### ISSUE TITLE
Long node names are cut off with ZoomExtends

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#520]
Hi,

it would be nice if zoomExtend() could ensure that all nodes fit in the canvas (maybe optionally with a given padding - just a thought). The point is that node names  ~10 characters are often cut off (when too far left/right). 

I created a bin for this issue: http://jsbin.com/lajic/1/edit

Here is a screenshot.

---

![selection_384](https://cloud.githubusercontent.com/assets/4307137/5514811/9922aa48-884c-11e4-862d-d2d6e8e7813a.png)

---

Thanks!

Felix

**Comment by AlexDM0** [comment]
Hi Felix, 

A fix has been pushed to develop.

Cheers

**Comment by felixhayashi** [comment]
Hi @AlexDM0,

great job! works like a charm!

-Felix
