### ISSUE TITLE
Listeners remain after container is removed producing akward situations

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#521]
Hi guys,

another problem spotted: The listeners remain after the container object is removed.

Please see a demo of the problem here.

http://jsbin.com/ligaku/1/

A fix would be to attach all your listeners only to the container object and not to the window. Then if the container is removed, also the listeners are gone.

For any listeners that necessarily have to be attached to the window and cannot be attached to the container by any means you could do:

    var handleEventX = function(event) {

      if(!document.body.contains(this.container)) {
        window.removeEventListener("...eventType...", this.handleEventX);
        return;
      }
     
     ... otherwise code
     
    };

Because we use vis in our tiddlywiki system, where entries with embedded graphs get opened and closed frequently, this is a problem.

Regards
Felix

**Comment by AlexDM0** [comment]
Hi Felix,

I have perfected the destructor and embedded it is a lot of our examples (2 for instance) on the dev branch. I does not seem to be possible to bind keycharm to the container div.. this could be due to a conflict of event propagation between hammer and keycharm. We are planning to move to hammer 2.0, which might (or might not) solve the problem.

I'm afraid you'll have to use the destroy function to be sure (and set the reference to null).

Regards,

Alex

**Comment by felixhayashi** [comment]
Hi Alex,

thanks for the effort. I have created a registry that keeps track of the various graphs and makes routine checks if a graph container is removed to eventually call the destructor.

If you have any updates on this topic, it would be great if you could drop a short message in this thread.

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

You cannot just remove the container, you need to call the destroy function. The reason is that if you destroy the container, the canvas is orphaned, but not deleted. This keeps network in memory.

I really do not think there is a way around this.

Regards,

Alex

**Comment by felixhayashi** [comment]
Hi Alex

> You cannot just remove the container, you need to call the destroy function

Yes, of course, I am doing that.

    TiddlyMapWidget.prototype.destruct = function() {
      window.removeEventListener("resize", this.handleResizeEvent);
      this.network.destroy();
    };

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

But you do that BEFORE you delete the container right? The current implementation of the destroy sort of depends on that.

Regards

**Comment by felixhayashi** [comment]
Hi Alex,

unfortunately no, I have no control over when a container is removed. The user of the wiki may open and close content (which includes graphs) as he/she pleases. I get no chance to react on that as the wiki does not call a destructor when content is closed. So my only chance is to check if a container is removed from the dom tree. 

But it all works fine because the container is not removed from memory as still pointers exist that reference the container. So the container node is still present, however not in the main dom tree.

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

We have released a new version. From your edit I see that destroy does not work for you anymore. Are there console error messages?

Regards

**Comment by felixhayashi** [comment]
Hi @AlexDM0,

> Edit: You call a function called destruct? It's called destroy :)

I know. As posted above `graph.destruct();` then calls `network.destroy()`. Probably you didn't notice as I posted so much code :)

> From your edit I see that destroy does not work for you anymore.

No, and if you look at the original fiddle (http://jsbin.com/xoyugopegu/1) I posted to describe the problem it doesn't work there either!
(fiddle library changed to 3.8.0).

> Are there console error messages?

Well no, its not actually an error its just an unwanted behavior...

> But you do that BEFORE you delete the container right? The current implementation of the destroy sort of depends on that.

The point is, in many setups that is not possible. Often (mostly in dynamic websites) the container is destroyed and the api user has no chance to react on that (also see my post above). Doing something like `document.body.contains(graph.getContainer())` is my only chance to see if a graph has been removed.

I would be really(!) glad if you could make `network.destroy` work, even if the container is already removed!

Regards
Felix

**Comment by AlexDM0** [comment]
Hi Felix,

Could you add a button or two to our first basic example on the vis website that delete the elements the way you do it so I can see what cases I have to cover? I don't want to specifically taylor a destroy function to your case but I think this would be a great start to make the destroy more robust. 

I want to have a destroy that always works so well work on it until it does. 

Regards

**Comment by felixhayashi** [comment]
> I want to have a destroy that always works so we'll work on it until it does. 

It's great to hear that!

> Could you add a button or two to our first basic example on the vis website that delete the elements the way you do it so I can see what cases I have to cover?

Yes I will do that. By the way, congratulations for this new nice looking website! :)

**Comment by AlexDM0** [comment]
Hi Felix,

I have updated your bin: http://jsbin.com/puxuso/2/edit?html,output

It seems that while the destroy function DOES remove the listeners, it is not removed from memory. Can you verify that the listener is removed? The old destroy function should not have removed it from memory either so I'm surprised that the new one does not work for you.

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi Felix, 

It seems there were some bindings left in the manipulation system. I have changed this in the develop branch. If you follow the bin as I've changed it (with the develop branch code) it will be removed from memory when calling destroy, even if you have deleted the container beforehand.

Please let me know if this works for you.

Regards,

Alex

**Comment by felixhayashi** [comment]
Hi @AlexDM0,

It tested it after your latest commit thoroughly in with our wiki system and I couldn't produce any situation where the listeners remain. Great job.

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

From the next release on, Keycharm will only listen on the div if you use the bindToWindow = false option. Maybe that can also help in your case, though the destroy is still recommended.

Cheers

**Comment by felixhayashi** [comment]
Hi @AlexDM0. That's great news. Are there any negative effects enabling that option? In any case, if you recommend going with destroy, I think I will continue using it.

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

Depends what you mean by negative. The keyboard shortcuts will require you to 'enable' the network div, which is done for you on a mouseover. There is a highlighted border around it but you can style it away. Other than that, there is no negative impact.

It will allow you to use the keyboard arrows in input fields whereas you couldnt before. If you only have one graph, its not really worth it. So if you have multiple and you all want them to be moved individually by the keys, this new option it the way to go. 

The things I have mentioned here are the reasons this option is implemented. It's not ment to make destroy obsolete.

Cheers

**Comment by felixhayashi** [comment]
Ah, I get it, sounds great :) Thanks for explaining it to me, I will experiment with it.

-Felix
