### ISSUE TITLE
Layout of some visjs.org examples crashes at start on linux machines with firefox

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#526]
Hi,

just wanted to inform you, with some of the visjs.org examples I experience a complete crash of the layout using different linux-machines and browsers.

I experienced this (see screenshots) in Firefox 30 and 34 running on Linux Mint and Debian (tested on three separate computers). Doesn't happen when using Chrome. 

Some screenshots:

![selection_395](https://cloud.githubusercontent.com/assets/4307137/5564112/e941d4d2-8ea9-11e4-8680-5fa47cae011d.png)
![selection_396](https://cloud.githubusercontent.com/assets/4307137/5564113/ee608da0-8ea9-11e4-99ab-613139bc164a.png)
![439a53c2fc8dbb626e888b417f1ef9c6](https://cloud.githubusercontent.com/assets/4307137/5564114/f38787b6-8ea9-11e4-943a-1f2ffa87d74a.png)
![selection_398](https://cloud.githubusercontent.com/assets/4307137/5564115/f82eb050-8ea9-11e4-9435-f9dca9be9edb.png)

Using browserstack.com to test Windows and Mac with Firefox 30 and other browsers makes me assume that this is a problem with firefox on linux only.

![selection_402](https://cloud.githubusercontent.com/assets/4307137/5564175/d3d768d8-8ead-11e4-8130-7b5578580475.png)

Maybe this information is useful to you somehow.

Regards
Felix

**Comment by AlexDM0** [comment]
I have redone the dashed lines a while back (long while). Maybe the current implementation is to blame?

**Comment by AlexDM0** [comment]
@josdejong could you check this on your system? It could be in the function _drawDashLine in the Edge.js file.

Cheers!

**Comment by AlexDM0** [comment]
Hi,

A fix for this has been pushed to the develop branch. Thanks for letting us know!

Regards,

Alex

**Comment by felixhayashi** [comment]
:+1:
