### ISSUE TITLE
3D tooltip only display for first 3D chart if multiple 3D charts were printed in a same page

### ISSUE THREAD

**Issue by rsaungc** [almende/vis#535]
Hi,
I printed multiple 3D charts in a single web page and tooltip only display for the first chart, not other 3D charts printed in a same page.  Not sure why tooltip didn't print in other charts beside the first one.  Please advise.

Thanks in advance.

**Comment by AlexDM0** [comment]
Hi,

I'll look into it.

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi,

A fix has been pushed to the develop banch and will be added in the next release.

Regards,

Alex
