### ISSUE TITLE
Ordering items inside a group

### ISSUE THREAD

**Issue by gigi81** [almende/vis#538]
I just upgraded my code to use the latest version of vis.
Before I was using an option of the timeline object called "order" to sort the items inside a group.
This was to solve the problem that when the data is grouped by the timeline the original order is lost.

The problem can be clearly seen with one of the examples provided with the library, this one:
http://visjs.org/examples/timeline/09_order_groups.html

In the example the order in the first group should be 0, 1 and not 1, 0. The same for the third group where the order should be 2,3,4 and not 3,2,4.

The "order" option was useful because it was an easy workaround for the problem and also useful for other purposes. Anyway when trying to use it I now get an exception: "Option order is deprecated. There is no replacement for this feature.'".

Is it possible to reintroduce the "order" option. And, if not, can you please fix the grouping function so that the original order of the items is preserved?

Thanks

**Comment by josdejong** [comment]
See #234

**Comment by gigi81** [comment]
Hi Jos,
I understand your concern about performance, but I don't feel like it's a good reason to remove a functionality.
My suggestion would be to reintroduce the functionality specifying in the documentation that there can be performance issues when there are a lot of items.
In my case, for example, there are not a lot of items in the timeline and I never experienced performance issues. I'm pretty much sure I'm not the only one here.

The suggested workaround works (thanks @aseiford), anyway there are flickering problems when scrolling, because of the item drawn and then redrawn in a different position after the reordering.

Thanks

**Comment by josdejong** [comment]
Thanks for the feedback @gigi81 and @Blugh. I think you are right, we can indeed introduce a second, more "brute force" mechanism.

**Comment by josdejong** [comment]
I've implemented a configuration option `order`, which you can use to define a custom, fixed ordering for the items. You can try it out in the `develop` branch, see example [35_item_ordering.html](https://github.com/almende/vis/blob/develop/examples/timeline/35_item_ordering.html).

**Comment by Blugh** [comment]
Hi Jos

Thank you so much. I will give it a go and give you feedback asap.

**Comment by josdejong** [comment]
The configuration option `order` is now available in v3.11.0. Please let me know how it works out :)
