### ISSUE TITLE
Calling network.setData with options including clickToUse makes the network unusable

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#540]
Hi guys,

When instanciating a network with a set of options including `clickToUse = true` and later calling `network.setData(..., options);`. Another overlay is created and prevents the user from selecting any node, navigating or editing. Calling `setData` five time will create five times an additional overlay:

    <div class="overlay" style="-webkit-user-select: none; touch-action: pan-y; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);"></div>

Fiddle here
http://jsbin.com/fucipoduci/1/

Regards
-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

You're actively spotting bugs! Seems like our codebase is in dire need of a rework :).

I'll look into it.

Cheers

**Comment by AlexDM0** [comment]
Hi Felix,

I pushed a fix to develop. We expect a new release soon(ish).

Cheers!

**Comment by felixhayashi** [comment]
> You're actively spotting bugs! Seems like our codebase is in dire need of a rework :).

I am actually pretty amazed by all your work. It's just that I am using vis to the limit :)

-Felix
