### ISSUE TITLE
Is there an event when an edge is selected (network data manipulation)

### ISSUE THREAD

**Issue by dailez** [almende/vis#543]
I'm looking for a way to edit the label or title of an edge. It seems that there is no event assigned to it that would allow to edit them. There is only "onEditEdge", but it will only be fired when I re-connect the edge. Am I right?

**Comment by AlexDM0** [comment]
Correction, the select event. http://visjs.org/docs/network.html#Events

I think this answers the question. If there's anything else, please let me know.

Regards,

Alex
