### ISSUE TITLE
Timeline: Subgroup background and subgroup order issues

### ISSUE THREAD

**Issue by jbraun27** [almende/vis#544]
In Timeline example 30, Subgroups, if you delete all items (the range in this example) from the top subgroup in a group, the group collapses, but the subgroup background ranges stay the same height, and bleed into the lower group.

Also, when adding items, only the last item added to the subgroup affects the subgroupOrder. In the example, the 3 subgroup: 'sg_1' items have a subgroupOrder, but only the last item added determines if it above or below subgroup: 'sg_2'. Ideally, subgroups and their order should be defined as an array in the groups DataSet, or in a separate DataSet for subgroups, and the subgroupOrder of the subgroups defined there instead of in the item. 

Thank you and keep up the great work!

**Comment by andrew-codes** [comment]
We are seeing similar spacing issues when adding new items and backgrounds to subgroups; however it does not appear to be consistent.
![2015-01-08_16-26-37](https://cloud.githubusercontent.com/assets/1578436/5671094/57edf81e-9753-11e4-876d-0d08afdb1105.png)

**Comment by andrew-codes** [comment]
We discovered that our issue was not actually with the visjs library.

**Comment by AlexDM0** [comment]
Hi,

Is this still an issue?

Regards,

Alex
