### ISSUE TITLE
Custom html as labels

### ISSUE THREAD

**Issue by Lakedaemon** [almende/vis#548]
It would be nice to be able to use custom html for node and arrow label : 
that way, we could use that library for maths... (probability trees, ...)

Apparently, vis uses canvas to render the nodes, 
wouldn't it be possible to render html nodes or (TeX string rendered to svg by MathJax) to a svg image and to use this image for the node ? 

it seems like someone managed to do just that with D3.js thanks to this function
https://gist.github.com/chrisbrich/3391642

For my use case (displaying mathematical proof with mathematical labels, using title tooltips is not feasible (android app))

**Comment by AlexDM0** [comment]
Hi,

Interesting you ask this. We'll be putting an example for this (for the node images at least) online tomorrow.

Regards,

Alex

**Comment by Lakedaemon** [comment]
On 01/11/2015 01:24 PM, Alex wrote:
>
> Hi,
>
> Interesting you ask this. We'll be putting an example for this (for 
> the node images at least) online tomorrow.
>
> Regards,
>
> Alex
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/almende/vis/issues/548#issuecomment-69492731>.
>
Wow, this would be marvellous. Thanks.

I have been playing with vis.js and really wanted to use it in my 
software (really nice lib).
Yet being able to display custom labels (for math) was an absolute 
requirement.

Best regards,
Olivier

**Comment by josdejong** [comment]
@AlexDM0 I guess you are hinting at the trick to use html2canvas to turn HTML into an image which can be displayed in the Network? 

http://jsbin.com/hahubu/edit?html,output

**Comment by AlexDM0** [comment]
Yes, I think it would make a nice addition as an example.

**Comment by josdejong** [comment]
It's a *trick* though with an unfortunate drawback: for html2canvas to work, the HTML must be visible on screen in order to render correctly into a canvas image.

**Comment by josdejong** [comment]
Maybe the way to go is drawing SVG's in canvas. We may be able to draw HTML DOM inside an SVG.

https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Drawing_DOM_objects_into_a_canvas

**Comment by AlexDM0** [comment]
Hmm seems it was a hasty conclusion on my side. We'll have to experiment with this. I'll look into it.

Regards,

Alex

**Comment by Lakedaemon** [comment]
On 01/12/2015 10:28 AM, Jos de Jong wrote:
>
> @AlexDM0 <https://github.com/AlexDM0> I guess you are hinting at the 
> trick to use html2canvas to turn HTML into an image which can be 
> displayed in the Network?
>
> http://jsbin.com/hahubu/edit?html,output
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/almende/vis/issues/548#issuecomment-69545154>.
>
Wow, this output really  looks awesome.

Being visible on a screen (and not in a tooltip) is what I was asking 
for in the first place.
So that might not be such a handicap for my use case.

This snipet does exactly what I was looking for

**Comment by Lakedaemon** [comment]
Would it be possible to allow image for edges too ? 
(the conditional probabilities go on the edges in probability trees)

**Comment by AlexDM0** [comment]
Hi,

This is currently not possible. I'm unsure if it would be added in the future. You could ofcourse put a node in between. 

Regards

**Comment by AlexDM0** [comment]
Hi,

I have changed the example to show normal HTML in vis by:

http://htmlpreview.github.io/?https://github.com/almende/vis/blob/develop/examples/network/36_HTML_in_Nodes.html

Additionally, I've put in a request at MathJax for an API that will allow us to simplify this:
https://groups.google.com/forum/#!topic/mathjax-users/RhWayOM8t_A

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi, 

The example is live, the question answered and we'll have to wait on mathjax to get a nice api to play with. 

I'll add a feature request to make labels images so this would work on edge labels.

Regards,

Alex

**Comment by Lakedaemon** [comment]
Many thanks. 
I haven't had time lately to play with this but I'll start using it one android app starting next week.
I'll follow this closely and hope for the best for  the edge label thing
Best regards, 
Olivier
