### ISSUE TITLE
timeline.redraw() not recalculating item size after css update

### ISSUE THREAD

**Issue by jladbury** [almende/vis#550]
I want to provide an interface giving different views of a timeline. The underlying data in each is identical, the difference in views being achieved by different css rules being applied to each container. Moreover, I want the user to be able to dynamically update the css rules using the **jss** library at https://github.com/Box9/jss. (Note: this library updates css rules, not the DOM. An advantage of this is that off-screen items are also affected by the change, which can be seen when scrolling them back into view. Contrast this behaviour with using jQuery to manipulate the DOM, which only affects on-screen items (discovered thanks to investigating Jos's comments in closed issue #532).

This approach is mostly working fine (for example, to change text colours and backgrounds), but does not quite work when a dynamic rule change is used to hide or show the event content. In that case, the event content is hidden or shown  as required, but the item height is not updated. If the timeline includes groups, the group height is left unchanged, presumably as a knock-on effect.

The failure to change height is merely of aesthetic importance when hiding content, but results in invisible text when showing it.

I have produced a couple of bins to illustrate the problem, both of which include further description.

http://jsbin.com/qujudo/44/ uses grouped timelines.
http://jsbin.com/qujudo/45/ uses non-grouped timelines.

Both examples run timeline.redraw() after the css update, but it does not have any effect.

**Comment by mcshaman** [comment]
I too have been experiencing this problem. It would be good it the redraw function recalculated the CSS properties of each element.

**Comment by AlexDM0** [comment]
Hi,

> I too have been experiencing this problem. It would be good it the redraw function recalculated the CSS properties of each element.


If we did that, performance would go down the drain. It was the case initially and it was horrible. As @josdejong pointed out in the other issue you (@jladbury) started: #532, there are ways to do this and since you are still using external libaries to modify the styling without telling the timeline it will not work.

The solution as stated is (and I copy paste from the old issue):

>To solve this, you should do updates in the contents and styling of the items by updating their data via a DataSet: updating and items content and className fields.

>To force the timeline to recalculate an items size, you could create an update sequence field in the items data and increment that. When the data of an item changes, the Timeline marks it as dirty and will recalculate and update its size and contents.

Regards,

Alex

**Comment by jladbury** [comment]
@AlexDM0,
To say *using external libraries to modify the styling without telling the timeline [it] will not work* is not quite true. Updating the css rules works perfectly except as far as size is concerned.

Would it be possible to add a parameter to force the redraw to update size? Thus general use would go unchanged, but if the overhead were thought to be worth it a caller could say so. This would also be cleaner than forcing an update by manipulating otherwise unneeded data (as per Jos' proposal, which Incidentally  I could not get to work).

Performance and tidiness of my application are involved here, as well as the performance of the timeline. To quote and paraphrase a little from my previous issue:

> ... my application adds a number of classes to each item as it populates a vis dataset from a JSON file, and then allows the user to alter the display of the items on a number of timeline displays by manipulating the underlying CSS for those classes. 

>I have done it this way for two reasons. Firstly I assume that for a large dataset it will be more efficient to update the CSS than to recalculate the HTML content of every item (maybe I am wrong about this). The second reason for doing it this way is that when the user updates an item, I only have to reflect that in a single dataset. It would be unwieldy to have to update separate datasets for each display

**Comment by AlexDM0** [comment]
Hi,

Yes, there naturally is a visible response. You modify the CSS and the browser reacts. Except it is not the way the timeline is configured to handle changes, that is the [it] I refer to. We could look into having a method that makes the timeline 'dirty', hence recalculating everything. @josdejong what do you think?

Regards,

Alex

**Comment by jladbury** [comment]
@AlexDM0 @josdejong ,
Gentlemen,
I will put together an example use case to inform your deliberations. 
Julian

**Comment by jladbury** [comment]
Here is the promised 'use case'.

I want to use the timeline as part of a more general package to help people analyse a trail of events. A critical part of this analysis is that, once a timeline has been drawn, people should have the ability to highlight any events they choose. It is useful for them to create different sets of highlights and switch between them quickly

I have a reasonable clue about the sort of things they will be looking for - let's say 'people' of various ages, who have 'hats', 'cars', and 'pets'. In my real application, there could be several hundred of these 'event characterisations', and a few thousand events. Each event includes information that can be used to build a list of its relevant characterisations.

Now, when constructing the timeline, I decide on a css class for each characterisation - e.g. 'hat' corresponds to class 'c3'. As I build the HTML for the event content, I add every class that is relevant for the event. 

Suppose I have four events to display. I give them classes as follows:
```
event 1: c1 c2    c4
event 2: c1 c2 c3 c4
event 3: c1 		   c6
event 4: c1 c2       c5 
```
Suppose I have timelines in several containers. Each container has a different css id (say *#container1, #container2* etc)

I can now easily manipulate each container with css, for example:

`.c1 {...}`     selects all events in all containers (not much use really)
`#container1 .c1 {...}`  selects all events in container1
`.c2 {...}`    selects event 1, 2 and 4 in all containers
`.c2.c3 {...}`    selects event 2 in all containers
`#container2 .c2.c3 {...}`  selects event 2 in container2

The **jss** library allows me to update these css rules on the fly as the user desires.

This approach means that my app only has to analyse the data once. The vis.timeline has only to do its work once. The css manipulation achieves exactly what I want extremely quickly. As I have said, it works fine when the css updates do not affect the item size. I have only experienced limitations when it does.

Bear in mind that the sort of thing a user might want to do is 'show in red every event in which there is a person aged over 3 who has a cat. In view 3 do the same, but if the person also has a car and is wearing a hat show it in blue'.

With my approach, I simply update the css, something like:
`.c2.c3 {color:red}` 
`#container2 .c2.c3.c8.c99 {color:blue}`   
 
Contrast that with rebuilding the DOM, which must surely be less efficient. Not only that, but for me a most unfortunate consequence would be that I would have to do some fancy data analysis logic that would have to be worked afresh every time the user changed his mind.

I hope this makes sense!

**Comment by josdejong** [comment]
We can adjust the *public* `redraw` method such that it marks all items as dirty, forcing them to recalculate their size. Makes sense to me. 

We should of course not do this for the internal redraws, as that would indeed kill the performance. Typically, you only need to call `Timeline.redraw()` occasionally in special cases like the tab where the Timeline is becomes visible, window is resized, and possibly css styling has been changed.

**Comment by jladbury** [comment]
Jos, that's great news. Thank you. Any idea when you might find time to do it?

**Comment by josdejong** [comment]
Sorry for the late reply. I've fixed this in the `develop` branch, will be in the first next release (will be this week).

**Comment by jladbury** [comment]
Working perfectly now. Many thanks!
