### ISSUE TITLE
Getting imageObj error when I switched from 3.7.2 to 3.8 version

### ISSUE THREAD

**Issue by netigen** [almende/vis#552]
Any idea what may be causing this? Works fine with 3.7.2 version.

TypeError: this.imageObj is undefined vis.js:20067
TypeError: this.imageObj is undefined vis.js:20067
TypeError: this.imageObj is undefined vis.js:20067

**Comment by AlexDM0** [comment]
Without code it's very hard to guess.. Put up a jsbin?

Regards

**Comment by ericvandever** [comment]
Ran into the same issue today.  Not sure why it was reverted, but there is a fix posted here.
https://github.com/almende/vis/commit/7f6068159663df326796c9952eeef18f33ce0f4a

**Comment by netigen** [comment]
solved using the fix 7f60681

**Comment by AlexDM0** [comment]
Hi,

Could either of you give me an example where this occurs? 

Regards

Alex

**Comment by ericvandever** [comment]
I should be able to mock up a case sometime this week, but the issue is when changing the data through network.setData.  For my case, the first set of data appropriately populates the images, but any following set of data results in broken images.

**Comment by AlexDM0** [comment]
Hi Eric,

Nevermind, I've reverted that part of the commit on the dev branch. It seems I've overlooked something when I changed it. Thanks anyway.

Regards,

Alex
