### ISSUE TITLE
Hierarchical network layout with loops causes edge label overlap

### ISSUE THREAD

**Issue by therji** [almende/vis#555]
Hi, first of all, thanks for the great framework!

I'm using a hierarchical layout with directed edges with arrows. I want to label both edges, but I'm noticing that the two edges overlap right on top of each other, which also causes the labels to overlap and be cut off on the lines. Here is a jsfiddle: http://jsfiddle.net/nwzheskn/

These problems don't exist when not using the hierarchy layout: http://jsfiddle.net/qkwf85n5/

**Comment by AlexDM0** [comment]
Hi,

I guess your example is simplified, though is it really required that you have two edges between these nodes? If they were on different levels you could use static smooth curves to see the difference. The dynamic or static smooth curves in the normal layout also solve this problem. 

It would be useful if we could see the whole network to see if there is a clean way around this. 

Would it be a solution to have one edge with arrowheads on both ends?

Regards,

Alex

**Comment by AlexDM0** [comment]
If you disable smoothCurves you get this: http://jsfiddle.net/nwzheskn/1/

You could alter the labels to reflect what it is you want it to say.

**Comment by therji** [comment]
Thanks for the quick response! I've thought about this more, and I think the underlying issue is that I'm looking for the type of layout that Graphviz does internally, which I think is different than the hierarchical layout engine in vis.js? My example also doesn't the labels I want on each edge. If it makes it clearer, I'm trying to create some sort of Markov structure, so you can imagine each edge will have a different value.

Here is a real dataset, in DOT, done in Graphviz: http://goo.gl/W3jlBK
Here is the same dataset in vis.js, using hierarchical layout: http://jsfiddle.net/mu6kp620/

So I think one issue is that for nodes on the same level, edges in between them overlap. And perhaps a different issue is whether there's a way to hierarchically layout the nodes as how Graphviz would do it? Thanks.

**Comment by AlexDM0** [comment]
You're right, vis does not have the same layout engine used by Graphviz in this case. You could try the directed method, see if that gives you better results. 

Additionally, you could manually supply the levels.

We could always consider implementing additional algorithms for sorting. Do you have a specific on in mind?

Regards,

Alex

**Comment by AlexDM0** [comment]
closed due to inactivity

**Comment by Trolomoll** [comment]
Hi,

I have a similiar problem with the hierarchical directed layout.
My issue is that the algorithm sorts some of the nodes in the wrong level.
You can see what I mean in the screenshot below.

![example](https://cloud.githubusercontent.com/assets/4364299/12147710/9bc05bee-b49a-11e5-9cd7-dbc0725936f6.png)

Even if the options might not are causing my issue, here they are:
options =  {
                                        interaction:{
                                                 hideEdgesOnDrag: true,
                                                 hideNodesOnDrag: false
                                        },

                                        layout: {
                                                hierarchical: {
                                                        sortMethod: "directed",
                                                        direction: layouttype,
                                                        "levelSeparation": 280
                                                }
                                        },
                                        edges: {
                                                smooth: {
                                                        type: "straightCross",
                                                        forceDirection: "none",
                                                        roundness: 0
                                                }
                                        },
                                        physics: {
                                                enabled: true,
                                                hierarchicalRepulsion: {
                                                        centralGravity: 0,
                                                        springLength: 50,
                                                        nodeDistance: 200
                                                },
                                                minVelocity: 0.75,
                                                solver: "hierarchicalRepulsion"
                                        },

                                                                                tooltip: {
                                                                                                delay: 1000,
                                                                                                fontColor: "black",
                                                                                                fontSize: "9px",
                                                                                                fontFace: "verdana",
                                                                                                color: {
                                                                                                        border: "#666",
                                                                                                        background: "#FFFFC6"
                                                                                                }
                                                                                }

                        };

I also set the physics on false as soon as the stabilizationIterationDone fires.
What can cause this issue ? 
The "from - to" combinations in the Edges Array should be correct... I mean the arrows are in the right direction, but not all of the nodes are in the proper level.

 Thanks in advance.

**Comment by AlexDM0** [comment]
Hi,

If the levels are not to your liking you should allocate the levels yourself. I can't really know what the "proper" level is for your case. 

Regards

**Comment by Trolomoll** [comment]
Hi and thanks for repling,

I think the directed option should sort them in a A-->B Schema where A is on a higher level than B, because A points to B.. from A to B. 
The nodes with an arrow pointed to them (B) are the ones which should be on a lower level than the nodes which points to them (A). As you can see that didn't happen consistently in my case. Some A-->B relations are on the same level. In one case, as you can also see in the screenshot, B is on a higher level as A, although its described as "from A to B" in the Edges DataSet.
So it's quite obvious what the "proper" level is in my case :-) 

How can I allocate the levels by myself ? I can't find anything about that in the documentation.
Another question is: Is it possible to enable the dragging of the nodes on the y-Axis while the hierarchical layout is selected ?

Thanks and Regards

**Comment by AlexDM0** [comment]
Hi,

Edges do not add up. It gets allocated a level once so if there turn out to be more edges connecting to a node it will not affect it. 

Look in the docs for nodes. There is an option called level. There is also an example on this. 

Regards

**Comment by Trolomoll** [comment]
Thanks, this information is helpful !

To my other question: Is it somehow possible to enable the node dragging on the y-axis ? I know there is a option with which you can enable it, but it seems to has no effect while the hierarchical layout is setted.

Thanks !

**Comment by AlexDM0** [comment]
When you're using the hierarchical layout horizontally, you cannot drag on the Y axis. If you want to drag in both x and y axis you'll need to either use a different layout or unlock the node on the drag events and allocate a new level to it based on the release position.

**Comment by Trolomoll** [comment]
Thanks Alex !
I build a loop which allocates the levels for the Nodes correctly for my case :)
