### ISSUE TITLE
TypeError thrown when dragging ManipulationDiv

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#557]
Hi,

Bugreport:

Sometimes, a node is partly hidden under the manipulation div and it occurs that instead of dragging the node, I accidentally do mouse down on the manipulation div and move my mouse over the canvas.

This causes a big fat error on my screen.

To reproduce the error: http://jsbin.com/femogaxucu/1/

    Open browser console
    Click down on the manipulation bar
    While holding left mousekey down move over the canvas
    See TypeError thrown by Network._handleOnDrag

-Felix

Seems like `drag.pointer` is not initialized because the manipulation overlay prevents it.

**Comment by AlexDM0** [comment]
Hi Felix,

Fixed on develop.

Cheers!

**Comment by felixhayashi** [comment]
Wow thanks, that was super fast @AlexDM0

**Comment by felixhayashi** [comment]
Hi @AlexDM0, maybe this is related.

http://jsbin.com/leqeza/1/edit

Click edit edge, the try to go back
