### ISSUE TITLE
Bug updating/adding nodes. Version 3.8.0

### ISSUE THREAD

**Issue by dponch** [almende/vis#558]
Hi,

I'm getting a javascript error with the version 3.8.0 when I click on a node to add dynamically more nodes. Example: http://jsfiddle.net/Ljow3r2u/27
But it's also happening if I update the label color when clicking http://jsfiddle.net/Ljow3r2u/28/
I'll keep looking and let you know my findings. Hope you can help too.

Thanks,
Guillermo

**Comment by josdejong** [comment]
Probably the same issue as #552, I get errors "Uncaught TypeError: Cannot read property 'width' of undefined" on the line `width = this.imageObj.width;`.

**Comment by AlexDM0** [comment]
Hi,

That looks to be the case, and when testing on the develop branch this is already fixed.

Regards,

Alex
