### ISSUE TITLE
Updating a network via Dataset.update removes existing properties

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#561]
Hi guys,

Working with the current testing branch 3.8.1-SNAPSHOT (but might also affect master 3.8.0) I noticed that node values are overridden. This worked in 3.7.2 (If I swap versions everything works fine).

Check this out: http://jsbin.com/sabonukejo/1

Setting a color property and using this DataSet to update some information will remove the red color.

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

I have fixed this in develop. Cause was an oversight on my part when handling another issue.

Regards,

Alex

**Comment by felixhayashi** [comment]
Thanks :+1:
