### ISSUE TITLE
Cannot go back when editing edge

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#563]
Hi @AlexDM0, maybe this is related to #557

http://jsbin.com/leqeza/1/edit

Click edit edge, the try to go back. `TypeError: this.constants is undefined`

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

This was introduced when altering the destroy.. thanks for noticing! Fixed in develop.

Regards,

Alex

**Comment by felixhayashi** [comment]
@AlexDM0 Thank you too
