### ISSUE TITLE
Editing edges without callback call produces strange behavior

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#564]
Hi,

under some circumstances, the api user doesn't want to allow a manipulation action to complete. For example think of the case where an api user overrides `options.onEditEdge` to be able to make a check if a connection is allowed (something like "A is only allowed to connect to B if !B.isParentOf(A)"). If the connection is not allowed, the operation should be aborted. For me, aborting means calling a callback with no parameters or not calling it at all.

In this case, the "connect edge action" should be reset to the state as it was when the user first pressed "add edge" or "connect edge". With `options.onConnect` this works perfectly, I mean it does not seem to be mandatory to call the callback and the whole process is reset if no callback is called.

The following bin shows what will happen, if the callback has a null parameter.

http://jsbin.com/titeza/1/edit

![selection_435](https://cloud.githubusercontent.com/assets/4307137/5730323/64509952-9b79-11e4-9083-fbe7ba152712.png)

Is there a way to revert or prevent a manipulation action?

Regards
Felix

**Comment by AlexDM0** [comment]
Hi Felix,

I have made some tweaks to the control node system. Now you either do NOT use the callback and everything is reset or you DO use the callback and everything is propagated. 

Additionally I have improved the positioning of the nodes using the new code for the arrow edge styles and styled them a bit differently.

Everything has been pushed to develop.

Regards,

Alex

**Comment by felixhayashi** [comment]
Thanks!
