### ISSUE TITLE
Spring length and overlapping edges

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#565]
Hi,

having a physics setup with repulsion and larger spring lengths, edges connecting the same nodes will often overlap, hiding the other edge(s).

For an example, please refresh this example a few times and see the results:
http://jsbin.com/kakohi/1/edit

You will see that in the majority of the cases, the edges overlap. Only if I quickly bring one node close to the other, the edges separate. Is my physics setup bad? I prefer repulsion with a large spring length (to allow larger edge labels).

-Felix
![selection_437](https://cloud.githubusercontent.com/assets/4307137/5731687/d222a77e-9b86-11e4-8d53-82bd781a564c.png)
![selection_436](https://cloud.githubusercontent.com/assets/4307137/5731688/d22361aa-9b86-11e4-9db4-05496560a6bf.png)

Should look like:

![selection_438](https://cloud.githubusercontent.com/assets/4307137/5731686/d221a70c-9b86-11e4-92dd-36e3182d005b.png)

Thanks and regards
Felix

**Comment by AlexDM0** [comment]
Hi Felix,

I have tweaked the physics to avoid this situation, similar to it is in the BarnesHut setup. It has been pushed to develop.

Cheers!

**Comment by felixhayashi** [comment]
:+1:
