### ISSUE TITLE
Hierarchical network node overlap with long labels

### ISSUE THREAD

**Issue by ChrisHarding-KPMG** [almende/vis#567]
I have a hierarchical network using levels to show data in a column format. If i simply use a small number as the label for a node, all is good. However, if I use a longer word or multi-line text the nodes will overlap in the resulting network.

Please see my fiddle for an example: http://jsfiddle.net/7z5vn41g/1/

**Comment by AlexDM0** [comment]
That what the levelSeparation is for:
http://jsfiddle.net/7z5vn41g/2/

**Comment by ChrisHarding-KPMG** [comment]
Thanks for the quick reply. Level separation will work to a degree but is it possible to be dynamic based on the size of the node/label? I ask this as I will be injecting labels which could have variable length labels?

http://jsfiddle.net/7z5vn41g/3/

**Comment by AlexDM0** [comment]
You can dynamically alter this by using the setOptions when you inject a very large label. I would recommend you put linebreaks in labels and have it set to a value that is aesthetically pleasing..

Regards,

Alex

**Comment by mmotamimi** [comment]
hi,
is there other "Separation" for the nodes in the same level?
for the same problem

**Comment by AlexDM0** [comment]
Hi, 

You can play with the physics (the nodeDistance) to do this horizontally.

Regards,

Alex
