### ISSUE TITLE
Vis.timeLine with TimeLine clickable

### ISSUE THREAD

**Issue by DivyashreeMS** [almende/vis#569]
Hi

I have a urgent requirement that in Vis.timeLine there bottom line displays the Date and Time, I just wanted to make that time clickable and to read the value in JS. 
Please reply if any one has already implemented that.
![vistimeline_onclickoftime](https://cloud.githubusercontent.com/assets/10521928/5742619/9279626a-9be1-11e4-8713-85d963b68acf.jpg)

**Comment by AlexDM0** [comment]
Hi,

Hows this? http://jsbin.com/qosoz/2/edit?html,output

Regards

**Comment by DivyashreeMS** [comment]
Hi Alex,

Thank you for the quick reply, I am unable to open the link. Please can you copy paste the code here.

Thanks 
Divya

**Comment by AlexDM0** [comment]
```
window.onclick = function (event) {
    alert(event.srcElement.innerHTML)
  }
```

**Comment by DivyashreeMS** [comment]
Thank you Alex it is working fine!!

**Comment by AlexDM0** [comment]
Not everything has to come out of vis :) Javascript is broader than vis alone.

Regards,

Alex
