### ISSUE TITLE
How do I get a timeline item type?

### ISSUE THREAD

**Issue by mcshaman** [almende/vis#570]
This seems like it should have a simple answer but I am having trouble.

I can select all visible items 

    var itemIds = myTimline.getVisibleItems();

I can process each visible item

    for( i = 0; i < itemIds.lenght; i++ ) {
        item = myTimeline.itemSet.items[i];
        // process item
    }

But how do I work out what type of item (e.g. PointItem, RangeItem, etc) and item is?

**Comment by josdejong** [comment]
Each item can have an optional field `type` with the desired type. You can also globally set a default item `type`. From the [docs](http://visjs.org/docs/timeline.html) on the global `type` option:

> Type
> Specifies the default type for the timeline items. Choose from 'box', 'point', 'range', and 'background'. Note that individual items can override this default type. If undefined, the Timeline will auto detect the type from the items data: if a start and end date is available, a 'range' will be created, and else, a 'box' is created. Items of type 'background' are not editable.

**Comment by josdejong** [comment]
btw I wouldn't use internals like `item = myTimeline.itemSet.items[i];`. You can access and manipulate the items via a DataSet.

**Comment by mcshaman** [comment]
Thanks for your responses Josdejong. I was hoping not to rely on the data entered by the user to test what type of object is displayed. As you mentioned, it is an optional field so it could be blank or the user may make a spelling mistake. It would be good if I could test exactly what data type the timeline is treating each item as instead of having to predict it.

**Comment by AlexDM0** [comment]
Hi,

Since you have the ID from the select event, or the getVisibleItems() and you have access to the data since you loaded that in yourself... why not just cross reference??

Regards,

Alex

**Comment by mcshaman** [comment]
Thats what I am saying. Consider this example:

	data = new vis.DataSet( [
		{ content: 'item 1', start: '2013-04-20' },
		{ content: 'item 2', start: '2013-04-16', end: '2013-04-19' },
		{ content: 'item 3', start: '2013-04-14', type: 'blox' }
	] );

Lets say I have loaded this dataset into a new timeline object and I have all the IDs from the select event or get getVisibleItems() method. How do I test what item type the timeline object is treating each item as?

As I mentioned to Josdejong, do I have to write logic to predict how the timeline object should be interpreting it? Do I have to do logic like this for each item?

	for( var i = 0; i < items.length; i++ ) {
	
		item = items[i];
		
		var itemTypes = [ 'range', 'background', 'box', 'point' ],
			type = -1;
			
		if( item.type ) { // Type provided in data
			type = itemTypes.indexOf( item.type ); // type variable will be -1 if no instance found in array, possibly because its misspelled
		}
		
		if( type < 0 && timeline.itemSet.options ) { // Default type provided in options
			type = itemTypes.indexOf( timeline.itemSet.options ); // Once again will be -1 if not found in array
		}
		
		if( type < 0 ) { // Emulate libraries automatic type selection, range type if end date provided, otherwise box type
			type = item.end ? posibleTypes[ 0 ] :  posibleTypes[ 2 ];
		}
		
		// Logic based on the type
		
	}

This seems like overkill to get an answer that the timeline object can provide. Is there another solution to this I am not seeing?

**Comment by josdejong** [comment]
> As I mentioned to Josdejong, do I have to write logic to predict how the timeline object should be interpreting it?

Yes. For items without type, the Timeline chooses a default type as explained in the docs. If your items do not have a type specified, you will have to infer the applied type yourself following the same rules as the Timeline.

If you want to retrieve the type info from the Timeline itself, you would have to access its internals, which I don't recommend. There is no internal "type" field added to items, you would have to type check what instance an item is exactly. You can do it but it may break some day in the future, and it would require a similar amount of code as you need for inferring the type of an item yourself.

I don't know about your use case, but maybe you can add a `type` field to the items when missing *before* you load the data in the Timeline. That way, you can follow your own rules for types, and you can't have a discrepancy between inferred types.

Can you explain more about *why* you need the item type externally?

**Comment by AlexDM0** [comment]
Sort of. Try this:

http://jsbin.com/gopuho/5/edit?html,output

You really stop using the internal itemSet. It's not ment for public use and can change without warning in new releases, breaking your code.

Of course vis can provide anything but in order to minimize the amount of required options and/or methods, we provide the events with the data required for you to do what ever you want. In this case, get the type. If you think it's an ugly solution, then wrap it in a function and put the function in another file than the one you're working in.

Alternatively, you can use the classes but this is a very ugly solution:

http://jsbin.com/gopuho/7/edit?html,output

Regards,

Alex

**Comment by AlexDM0** [comment]
sorry, I didnt see your answer Jos. I was editing this one when you sent yours in :). It is directed at @mcshaman

**Comment by mcshaman** [comment]
Thanks for your time guys. I will follow your advice an avoid the internals. @AlexDM0 thanks for taking the time to provide a coded solution.

@josdejong I like your idea of adding the type field or fixing it at the initial run time. Once I have my core JS to a point that I am happy to share it I will provide it. Maybe when you see how I am using it you can tell me if there is a better approach.

**Comment by josdejong** [comment]
You're welcome. Good luck with it.
