### ISSUE TITLE
How to anchor the timeline format when page first loading

### ISSUE THREAD

**Issue by kaiyu22** [almende/vis#571]
Hi,
By default, timeline can zoom out/in by mouse wheel to fit user format.
I want to set second as time unit and following is my setting:
```js
  var options = {
    start: new Date(),
    end: new Date(1000*60*60*24 + (new Date()).valueOf()),
    editable: true,
    margin: {
      item: 10, 
      axis: 5
    },
    orientation: 'buttom',
    min: new Date(date.setSeconds(date.getSeconds())),
    max: new Date(date.setSeconds(date.getSeconds() + 60)),
    zoomMin: 1000 ,
    zoomMax: 1000 * 60 * 120	// two hours
  };
```
  
After page loading, it looks like this:
https://www.dropbox.com/s/gk05aeg2rsq6tqj/test1.jpg?dl=0

The following is my desired format when **page first loading**:
https://www.dropbox.com/s/8aa8rgxi6m94qx8/test2.jpg?dl=0

Does anyone know how to do it?
It will be appreciated!

PS:
Sorry, I have tried to use Markdown to embedded photo. But it is failed. 
So I used dropbox.

**Comment by josdejong** [comment]
Can it be that the `start` and `end` that you configure conflict with the configured `min` an `max`?

**Comment by kaiyu22** [comment]
Thanks Jos.
After fine tuning the parameters you described. It has been fixed.

 var options = {
    start: new Date(),
    **end: new Date()**,
    editable: true,
    margin: {
      item: 10, 
      axis: 5
    },
    orientation: 'buttom',
    min: new Date(date.setSeconds(date.getSeconds())),
    max: new Date(date.setSeconds(date.getSeconds() + 60)),
    **zoomMin: 1000 * 10**,
    zoomMax: 1000 * 60
  };
