### ISSUE TITLE
Graph2D Blinking left title text when using streaming data in Firefox 35 

### ISSUE THREAD

**Issue by bhspencer** [almende/vis#573]
I just updated to Firefox 35 on OS X and the left title text on a Graph2d when streaming data, as in your streaming data example, blinks with each update. This does not happen in Chrome or earlier versions of Firefox.

Here is a JsFiddle that shows the issue. 
http://jsfiddle.net/vjtjsc2m/4/

**Comment by AlexDM0** [comment]
Hi,

I cannot reproduce this.. has this been patched in firefox since?

Regards,

Alex

**Comment by bhspencer** [comment]
Hi Alex

Thanks for getting back to me. Seems like the issue was with Firefox and a recent update has fixed the issue. I cannot reproduce it with the latest version of Firefox.

**Comment by AlexDM0** [comment]
Sorry it took so long, we've been very busy with v4 lately..

Glad to hear it's fixed now :), truth be told I wasn't sure if this was fixable on our side.

Regards
