### ISSUE TITLE
Problem with declustering when smooth curves = false

### ISSUE THREAD

**Issue by qazimir** [almende/vis#574]
Hi, I found one bug. 
When clustering option is true and smooth curves false. Then when I try to open some cluster it only expel one node from this cluster.
Here is plunker: http://plnkr.co/edit/nfFM1sjtwpTLMlLbYKsC?p=preview
Try to zoom out and then doble click on some cluster to open it.

**Comment by AlexDM0** [comment]
Hi Qazimir, 

I'll look into it. Seems it just missed the release today though.. 

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi Qazimir,

I have fixed it on the develop branch.

Regards,

Alex

**Comment by qazimir** [comment]
Hi Alex,
thank you for fast response and the fix.
Q.
