### ISSUE TITLE
Nodes that spread vertically are cut off

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#575]
Hi @AlexDM0,

sorry to raise this issue but there seems to be the opposite of #520 occurring now.

See this: http://jsbin.com/jepexa/1/

![selection_447](https://cloud.githubusercontent.com/assets/4307137/5777957/7cd46d08-9d97-11e4-94b4-700feca66ad6.png)

Regards
Felix

**Comment by AlexDM0** [comment]
Hi Felix,

I pushed a fix to develop. It missed the release we did today. You're being a great QA team-member, though sorry you seem to have to take the role. Thanks for letting us know (again :)).

Regards,

Alex

**Comment by felixhayashi** [comment]
Hi @AlexDM0

>  You're being a great QA team-member, though sorry you seem to have to take the role.

Hehe, I have a "go-live" for a university project soon so I have to do a lot of testing at the moment. :) Thanks for picking the issue up so quickly.

Regards Felix

**Comment by felixhayashi** [comment]
@AlexDM0 could you bump the dist/vis.js?

**Comment by AlexDM0** [comment]
By bad, my push dialog was still open :)

**Comment by felixhayashi** [comment]
Really, looks great :sunglasses: :+1:
