### ISSUE TITLE
item range with text that exceeds width can not be viewed

### ISSUE THREAD

**Issue by GradyD** [almende/vis#579]
It is very simple, if I create a range and the the text that goes inside of this range is long there is no way to view the entire text. This could be huge if you are using the text to label the items. 

![image](https://cloud.githubusercontent.com/assets/994964/5786361/b5ee3668-9db1-11e4-806d-9173a90bdbbc.png)

I feel the best way to fix this and will make it look nice is to create scrolling text. So if the text is to long it will scroll continuously, http://www.quackit.com/html/codes/scrolling_text.cfm

**Comment by brichbe** [comment]
Is range overflow not sufficient for your case?  http://visjs.org/examples/timeline/18_range_overflow.html

**Comment by aDroidman** [comment]
I was not aware that this even exited. Does not look the best but I think it will work for what we are doing. I still feel the scrolling text will offer a better UI look and feel and create a more polished framework. 

Thanks for this answer, someone can make the decision if this should be closed or flagged as a feature request.

**Comment by josdejong** [comment]
Maybe you could also look into creating a popup with more information when you hover an item or select it.
