### ISSUE TITLE
Network - support for multiple edges between two nodes

### ISSUE THREAD

**Issue by netigen** [almende/vis#580]
Does the network support displaying multiple edges between the same nodes. I am not able to make this work.

**Comment by AlexDM0** [comment]
Hi,

With (dynamic) smoothCurves on ( the default setting ), this works perfectly. If you turn them off, then no. If you can't get it to work, please post a code example showing the problem. 

Hope that helps. 

Regards,

Alex

**Comment by netigen** [comment]
thanks, worked
