### ISSUE TITLE
DataSet.update() causes group styles to override styles on node level.

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#581]
Hi guys,

Calling update() on the nodes dataset somehow gives the group style a higher priority that the node style. The properties are however not overridden (maybe this is somehow related to #561?).

See: http://jsbin.com/neheba/1

Node should be red.

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

This is fixed in develop now.

Cheers!

**Comment by felixhayashi** [comment]
it works. thanks.
