### ISSUE TITLE
How to create a item by dragging object on the timeline?

### ISSUE THREAD

**Issue by kaiyu22** [almende/vis#582]
Hello,

User can create a new item by double tapping on an empty space.
If it possible to drag a object on the timeline to create a item.
**This effect is equal to 'double tapping' on the timeline.**
Please refer the below pictures.
[Action1] https://www.dropbox.com/s/1fgyfrlggvejnst/drag_1.png?dl=0
![Action1](https://www.dropbox.com/s/1fgyfrlggvejnst/drag_1.png?dl=0)
[Action2] https://www.dropbox.com/s/g41tlxwczq7pw05/drag_2.png?dl=0
![Action2](https://www.dropbox.com/s/g41tlxwczq7pw05/drag_2.png?dl=0)

My idea is to trigger 'double tapping' event when dragging the object on the timeline.
I study the relation code for 'doubletap' in vis.js:

Line 11165:
    // add item on doubletap
    this.hammer.on('doubletap', this._onAddItem.bind(this));
	
    // add item on droppable to receive object dragging on timeline
    this.hammer.on('droppable', this._onAddItem.bind(this));
	
But I know this is not enough.
Does anyone can give me the tips?
I will appreciate your help with this situation.

**Comment by josdejong** [comment]
Drag and drop isn't supported, but would be very nice (both ways: dropping an item onto the Timeline, and dragging an item outside of the Timeline)

I haven't tried this out, but for dropping an item into the Timeline it may just work to attach a drop event (for say a jQuery draggable or native `ondrop` event) to the container holding the Timeline, and then add the dropped event to the Timeline. 
You may need to add some code to calculate at which time the event was dropped (convert horizontal mouse position to time, based on window width, start, and end, and the mouse x).

**Comment by kaiyu22** [comment]
Thanks Jos!
I will have a try.

**Comment by jankdiss** [comment]
is this implemented ?, I have urgent requirement that need to create item by drag and drop

**Comment by mojoaxel** [comment]
@jankdiss I don't think there is a reference  implementation of drag&drop yet. But feel free to provide one ;-)

**Comment by jankdiss** [comment]
@mojoaxel cool thank you very much , can you provide me some reference. it is very urgent work

**Comment by jankdiss** [comment]
can I get work around for following in vis time line

1. Smooth animation on drag item, instead of click and drag. ( i.e. network animation)
2. Drop item in to time line from external component
3. Change the time bar line potion ( make centre, currently using two time line )

**Comment by JMazzucco** [comment]
@jankdiss take a look at what I have so far. 

In my app, there is a div with an ID of 'incoming' that contains a bunch of draggable cards.
When a card is dropped within the Timeline, the card is removed and a new timeline item is created. 

      $( "#incoming" ).sortable({
        items: ".card",
        cursor: "move"
      })

      $( ".vis-group" ).droppable({
        accept: '.card',
        drop: function (event, ui) {

           //remove the card when dropping it in the timeline
           $('#'+ ui.draggable[0].id).remove()
           var id = ui.draggable[0].id
           var dateDroppedOn = timeline.getEventProperties(event).snappedTime

           //add item to timeline
           newItem = {id: id, content: 'test '+ id, start: dateDroppedOn}
           timeline.itemsData.getDataSet().add(newItem)
           
        }
      })
