### ISSUE TITLE
Milliseconds in Timeline Items

### ISSUE THREAD

**Issue by san-bil** [almende/vis#584]
Is there support to store the milliseconds of a timelime item? 

At the moment, if you create an Item in the Timelime, the milliseconds aren't stored. So if you have an event shorter than 1 second, the Item collapses to 0 length when the page containing the Timeline is reloaded. Or events that are not lined up with second boundaries are snapped to the nearest (boundary).

**Comment by josdejong** [comment]
Yes the Timeline does store milliseconds, See this example: http://jsbin.com/namayoyoho/3/edit?html,output

If you drag items while zoomed out, the start/end of items will indeed snap to nice values, depending on the zoom level.

**Comment by san-bil** [comment]
Yes, it seems so. The truncation must be somewhere between sending the serialized Dataset using jquery, and receiving with node.js. 

When inspecting the array returned by Dataset.get() (before sending via $.ajax()), each objects "start date" field returns the right millisecond value (using getMilliseconds()). 

But when I print the values received at the server, there is no sign of the millisecond data...

**Comment by san-bil** [comment]
RTFM as usual. If you call Dataset.get() with the fieldnames you want, and that you want the start and end fields as ISODate strings, the milliseconds get stored:

    `  ds = {
      "annos": dataset.get({
        fields: ['content','end','start','id', 'date'],
        type: {
          start: 'ISODate', 
          end: 'ISODate'       
        }  `

**Comment by josdejong** [comment]
Ok great to hear you solved it!
