### ISSUE TITLE
Network Hover Not Working when Content Loaded in AJAX Call

### ISSUE THREAD

**Issue by lucare** [almende/vis#585]
Hi,

I am using an AJAX call to return some html which contains the network javascript and div. The network loads, but the titles I added to the nodes do not show when I hover. If I load this same network on the page load and not over AJAX the title hovers work. I assume this has something to do with html elements and binding to ones that are also created later on.

Thanks,
-Bill

**Comment by AlexDM0** [comment]
Hi Bill,

Can you show me the code you're using to do this?

Regards

**Comment by AlexDM0** [comment]
Hi Bill,

If your problem is also due to the bug reported in #596 it should be fixed in the release later today.

Regards,

Alex

**Comment by AlexDM0** [comment]
Has this been fixed?
