### ISSUE TITLE
Is it possible to override the "timespan" logic for rendering the background timeaxis vertical separator?

### ISSUE THREAD

**Issue by Gugarion** [almende/vis#587]
Hi,

I am zoomed into the "month" level where each month has a vertical separator. I was hoping to be able to instead have a separator for each week (preferably allowing me to define which day to start the separation). Is that currently possible?

Moveable will be set to false in my use case.

**Comment by josdejong** [comment]
This behavior is hard coded in the [TimeStep](https://github.com/almende/vis/blob/master/lib/timeline/TimeStep.js) class. 

I just implemented a new option allowing you to set a fixed, custom scale and step size for the time axis, see #590. Does that solve your issue? If not, I guess the only way is to override the relevant functions in the TimeStep class such that you get the desired behavior.

**Comment by Gugarion** [comment]
This does satisfy a large portion of what I was hoping for, thank you very much!
