### ISSUE TITLE
Fractional levels do not work in hierarchical layout

### ISSUE THREAD

**Issue by AngledLuffa** [almende/vis#588]
If you have levels which are fractionally close to each other, this does not work well in the hierarchical layout.  The nodes which are close to each other wind up overlapping.  If the levels are exactly the same, they are spread out.

This is true even if the X or Y coordinates on the nodes are set.  The X and Y coordinates actually appear to be ignored in the hierarchical layout.

http://jsbin.com/sinemimajo/1/edit?html,output

**Comment by AlexDM0** [comment]
Hi,

That's right. It doesn't work like that by design. 

Levels are integers, manual positions are ignored. 

You can use the settings of the hierarchical layout to tweak this. 

Regards,

Alex

**Comment by AngledLuffa** [comment]
Thanks for letting me know.  When you say the settings of the hierarchical layout can tweak this, what would be the best way to set up both horizontal and vertical positions?  Should I just use X and Y with some other layout format?

**Comment by AlexDM0** [comment]
Hi,

You can't set both x and y values. You can however use the levelseperation to determine the distance between levels. 

If you want to set both x and y values... Well then you don't really need a layout algorithm :). 

Regards=

**Comment by AlexDM0** [comment]
Hi,

I've reviewed your code, the levels DO seem to work with fractions. You have your levelSeperation set to a certain value. 0.1 of that is too close to the node. As you want the distance between them to be 100, that would imply a levelSeperation of 1000.

Turn on the configurePhysics options and play with the sliders to see what everything does.

If you want to manually position nodes you can use the other physics systems/layout solvers.

Regards,

Alex

**Comment by AngledLuffa** [comment]
It was the vertical positioning causing me problems.  I'll look at the
other layouts to see how well they can handle this particular problem.

Thanks!

**Comment by AngledLuffa** [comment]
Concretely, I'm looking for some way to give each node a vertical level, but to also enforce that a certain set of nodes are visually ordered left to right.  I'm trying to visualize a parse tree representing natural language text, such as you would get here:

http://nlp.stanford.edu:8080/parser/

The words are the leaves of the tree, but they might be at different distances from the root, so their levels might be different.  If I don't supply any layout information other than level, this means that sometimes words might visually be out of order left to right.  A constraint for left to right behavior of the leaves would be a big improvement for my visualization.

Here is an example of how some words are not horizontally aligned:

http://jsfiddle.net/AngledLuffa/g9ngs54d/

I would prefer "This" to be to the left of all the other words, for example.

Certainly this is now a question on how to use the library rather than a bug report.  Is there a better resource than this for issues like this?

Thanks again!

**Comment by AlexDM0** [comment]
Hi,

I'd recommend you give all nodes an x y position. You seem to know beforehand how you want it ordered. 

Vis' layout algorithms and physics solvers are not designed with this specific usecase in mind. 

By setting all the x y positions and disabling the physics I think you're good to go. 

As for the issue, we try to keep everything (questions, bugs, issues) in one place. Here :). 

Regards,

Alex

**Comment by AngledLuffa** [comment]
Interesting, I wasn't aware it was possible to turn off the physics
entirely.  I can't find the option for that in the network documentation,
either.  What options would I want to use?

Thanks!

**Comment by AlexDM0** [comment]
You can configure the physics, so you can also turn it off. Not everything needs its own name :)

Try:

```
var options = {physics: {barnesHut: {gravitationalConstant: 0, centralGravity: 0, springConstant: 0}}};
```

**Comment by AngledLuffa** [comment]
Thanks, that makes sense.  I will give that a try.
