### ISSUE TITLE
Timeline: loading more items asynchronously (not an issue)

### ISSUE THREAD

**Issue by losttheplot** [almende/vis#589]
Sorry to trouble you guys, but I'm wondering if you could point me in the right direction please? I have a nicely working timeline that loads items dated one week either side of a selected day, but I now want to change it such that as the user changes the range, new data is grabbed and the timeline is asynchronously updated accordingly, for the next year and beyond, if so required.

I've had a go at coding this (see below) but my JS skills are lacking. If the range is changed, all existing items disappear and the range resets itself! My date formula are correct, but I'm clearly either using the wrong function ( timeline.setItems(data.items) ), or in the wrong place, or the wrong way, or I'm just being thick!

```
<script>
	$.ajax({
		url: "ajax/ajax_shift.php?ac=getShifts&day=1421841600&start=1421193600&end=1422489599",
		dataType: "json",
		success: function (data) {
			document.getElementById("loading").style.display = "none";
			container = document.getElementById("visualization");
			groups = [snip]
			items = new vis.DataSet(data);
			var min = new Date(1421193600000);
			var max = new Date(1422489599000);
			var options = [snip],
				onAdd: function (item, callback) { [snip] },
				onMove: function (item, callback) { [snip] },
				onMoving: function (item, callback) { [snip] },
				onUpdate: function (item, callback) { [snip] },
				onRemove: function (item, callback) { [snip] }
			};

			var timeline = new vis.Timeline(container);
			timeline.setOptions(options);
			timeline.setGroups(groups);
			timeline.setItems(items);

			timeline.on("rangechanged", function (properties) {
				$.ajax({
					url: "ajax/ajax_shift.php?ac=getShifts&day="+Math.round(((properties.end.valueOf()-properties.start.valueOf())/2)+properties.start.valueOf())+"&start="+Math.round((properties.start.valueOf()/1000)-(60*60*24))+"&end="+Math.round((properties.end.valueOf()/1000)+(60*60*24)),
					dataType: "json",
					success: function (data) {
						timeline.setItems(data.items);
					}
				});
			});
		},
	});
</script>
```

**Comment by AlexDM0** [comment]
Hi,

I'd construct the timeline outside of the AJAX call. Start out with just console.logging the data you want to stream in. 

We're not a JS helpdesk :), there's forums for that (stackoverflow etc.)

Build a normal timeline, do AJAX calls, print the data, if it looks ok, go from there.

Regards,

Alex

**Comment by losttheplot** [comment]
Many thanks for responding, Alex. I realise this isn't a help forum, but as well as helping me, I thought my question would highlight what I imagine might be a common real-life use scenario. That is to say, a coding example of an asynchronous update might be useful to lots of people if it were added to the excellent examples list. Just a thought :)

**Comment by AlexDM0** [comment]
Like example 30 for the network and example 26 for the timeline?

**Comment by AlexDM0** [comment]
I just found out shift enter is submit.. here are the examples.

http://visjs.org/examples/timeline/26_external_data.html
http://visjs.org/examples/network/30_importing_from_gephi.html

Regards

**Comment by losttheplot** [comment]
Hi Alex. I based all my use of vis.js on the Timeline examples 26 (external data) and 08 (edit items). I didn't look at the network examples because I have not used the network functionality, and even now I cannot relate network example 30 to my circumstances, probably because I don't understand JS like you do. By my reckoning, timeline example 26 (external data) shows the timeline being constructed ( var timeline = new vis.Timeline(container, items, options); ) within the ajax call, which is what I thought I had done myself. Not to worry, I'll take your advice and figure out how to construct the timeline outside of the ajax call. Thanks for your patience :)
