### ISSUE TITLE
Customize the Time gap

### ISSUE THREAD

**Issue by DivyashreeMS** [almende/vis#590]
Hi 

I had a small concern the time gap in the Vis timeline is for 10 min. can this be customized to 5 min gap.
Like it is now 05:10,05:20,05:30...
How can I make it as 05:05,05:10,05:15...

![vistimelinemodification](https://cloud.githubusercontent.com/assets/10521928/5837907/4a8e7a24-a151-11e4-89e9-0b3146640497.jpg)

**Comment by kaiyu22** [comment]
You can try to use option 'zoomMin':
[Here is the description](http://visjs.org/docs/timeline.html#Configuration_Options)

**zoomMin**
Set a minimum zoom interval for the visible range in milliseconds. It will not be possible to zoom in further than this minimum.

For example:
    zoomMin: 1000 * 10 * 60 * 5

**Comment by DivyashreeMS** [comment]
Hi kaiyu,

zoomMin: This did not solve my purpose.

**Comment by josdejong** [comment]
@DivyashreeMS you cannot directly control the scale, it's automatically determined based on the window width and the visible time window (interval start - end).  A workaround is to zoom in such that you hit the desired step of the time axis.

We could reintroduce setting a fixed scale and step size for the timeaxis, as was available in the libraries predecessor. Something like `Timeline.setScale('minute', 5)`.

**Comment by josdejong** [comment]
I've implemented a new option which you can use like `var options = {timeAxis: {scale: 'minute', step: 5}}`. It's in the `develop` branch right now, you can check out the docs to see what values are supported.

**Comment by DivyashreeMS** [comment]
Thank you Josdejong for the valuable information.

**Comment by DivyashreeMS** [comment]
Hi Josdejong,

I have downloaded vis.js from below location (3.9.1)
http://visjs.org/#download_install

Will it be available in the mentioned version, if not when this will be available.

Thanks
Divya

**Comment by josdejong** [comment]
It't not yet available in 3.9.1, will be in the first next version (see [HISTORY.md](https://github.com/almende/vis/blob/develop/HISTORY.md) in the develop branch)

**Comment by DivyashreeMS** [comment]
Thank you Josdejong, when will be new version with timeAxis scale will be released?

**Comment by josdejong** [comment]
I expect within a few days

**Comment by DivyashreeMS** [comment]
Thank you Josdejong, I took the latest 3.10.0 version and timeAxis scale is working fine.
I had one more concern that I am using orientation: 'top' for showing the timeline in Top level as well but I am not sure on how to make the timeAxis scale for top level.
Please let me know if there is any way to sync up the time scale for both Top and Down for X axis.

 var axisOptions = {
		    orientation: 'top'
		  };
		  var axis = new vis.timeline.components.TimeAxis(newTimeline.body, axisOptions);
		  newTimeline.components.push(axis);

![timegap](https://cloud.githubusercontent.com/assets/10521928/6268525/84870e9a-b81b-11e4-998f-9b0bfad7bdfc.jpg)

**Comment by josdejong** [comment]
What do you mean with "how to make the timeAxis scale for top level."?

**Comment by DivyashreeMS** [comment]
Hi Josdejong,

Thank you for the reply.. To make it more simpler, you could see the timeframe from the image attached, for lower x axis that is 06:00,06:10,06:20 with 10 min gap, but in upper x-axis it is still 06:00,06:05,06:10.. 
The Upper x-axis is shown by using
var axisOptions = {
orientation: 'top'
};
var axis = new vis.timeline.components.TimeAxis(newTimeline.body, axisOptions);
newTimeline.components.push(axis);

So I just wanted to make both side x-axis timeframe values same. Hope I am clear now.
Highly appreciate your help.

Thanks 
Divya

**Comment by josdejong** [comment]
The two axes should use the same time scale and step, and it just works as expected in this jsbin: 
http://jsbin.com/tayugu/1/edit

Did you configure a fixed scale for one of the two axes?

**Comment by DivyashreeMS** [comment]
Hi Josdejong,

Thank you for the solution, It is working as expected now.

Code goes like this:

timeAxis: {scale: 'minute', step: 15},
    orientation: 'bottom'
    

 var axisOptions = {
    timeAxis: {scale: 'minute', step: 15},
    orientation: 'top'
  };
  var axis = new vis.timeline.components.TimeAxis(timeline.body, axisOptions);
  timeline.components.push(axis);

**Comment by josdejong** [comment]
ok great!

We want to implement a new orientation option `'both'`, that will make your life even easier I hope.

**Comment by ShawnMercado** [comment]
Is there any support for choosing the gaps between major labels as well?  I was trying to have it break on weeks, sort of like:

__________________________________
|m  | t  | w  | r  | f  | s  | u | m  | t  |
| week 5                           | week 6

**Comment by ShawnMercado** [comment]
Is there any option to customize where or at what intervals the major labels are placed?  I was hoping to have it divided by weeks and then days, sort of like this:  https://imagebin.ca/v/3Q6hlRXMzdjo
