### ISSUE TITLE
Negative level in hierarchical layout turns off that layout style

### ISSUE THREAD

**Issue by AngledLuffa** [almende/vis#592]
If you add a node with a negative level, it sets the layout style so it is no longer hierarchical.  For example:

http://jsfiddle.net/AngledLuffa/uhmobssr/

I was trying to do this as an attempt to work around issue 578 while waiting for it to be integrated

https://github.com/almende/vis/issues/578

I can still use the workaround by increasing all levels by +1, but this seemed like a bug worth reporting.

**Comment by AlexDM0** [comment]
Hi,

I'm not sure it's a bug.. I mean that's just not the way it's supposed to be used :/ it will also crash if you give it a letter. 

I'll revise the docs to more clearly state that the levels are positive integers. 

We'll probably release the new version Friday. In the meantime you can use the vis.js from the dev branch to continue your development. It should be stable but no promises :). 

Regards

**Comment by AngledLuffa** [comment]
Well, positive fractions have their uses, even if they weren't originally
intended.

**Comment by AlexDM0** [comment]
I suppose. It's a bit of a hack to use them really, but it doesn't crash vis.

**Comment by AlexDM0** [comment]
I have updated the docs. We will release the new version with the fix for 578 today.

Regards,

Alex
