### ISSUE TITLE
network edge widthMin seems to have no effect

### ISSUE THREAD

**Issue by AngledLuffa** [almende/vis#593]
Here is an example where the widthMin property doesn't change the thickness of the edges.  The edge properties are set at the very bottom of the javascript.

http://jsfiddle.net/AngledLuffa/u8omd81w/

If you set the width to be very high and then set widthMax, that also doesn't have an effect.

**Comment by AlexDM0** [comment]
Width min and max are used when you give edges a value. If you don't, they are not used. 

Regards

**Comment by AngledLuffa** [comment]
Got it.  I thought "value" from the documentation included a per-edge width setting, but that was a misreading on my part.
