### ISSUE TITLE
How to tune the scale in timeline when item is extending?

### ISSUE THREAD

**Issue by kaiyu22** [almende/vis#595]
Hi,

This phenomenon is hard to describe.
If item type is range, extend the item which length will change by moving with each **half scale** in timeline.
Please see below pictures
[Before Extending] https://www.dropbox.com/s/bap935d71j96kli/scale1.png?dl=0
![Before Extending](https://www.dropbox.com/s/bap935d71j96kli/scale1.png?dl=0)

[After Extending] https://www.dropbox.com/s/fi89ybibmjftcsp/scale2.png?dl=0
![After Extending](https://www.dropbox.com/s/fi89ybibmjftcsp/scale2.png?dl=0)

Does anyone know how to change the length by moving with **each scale (not half scale)** in timeline when extending the item?
[Desired] https://www.dropbox.com/s/uuyk6tzajo880zm/scale3.png?dl=0
![Desired](https://www.dropbox.com/s/uuyk6tzajo880zm/scale3.png?dl=0)

I will appreciate your help with this situation.

**Comment by josdejong** [comment]
The Timeline determines "snapping" depending on the current zoom level. If you zoom in or out, you will have a different points for snapping. If you zoom in you can position an item with more precision.

If you want have a different behavior, you can use the options `onMove` or `onMoving` as [described here](http://visjs.org/docs/timeline.html#Configuration_Options) to override the date selected by the Timeline while dragging an item.

**Comment by kaiyu22** [comment]
Thanks Jos,
Let me have a try.
