### ISSUE TITLE
If you scroll down to view a network, then hover, the hover is offset incorrectly

### ISSUE THREAD

**Issue by AngledLuffa** [almende/vis#596]
Here is a sample where you might need to scroll down to view the network.  If you do so, then try to hover over the nodes, the location of the hover is offset vertically.  Instead of registering a hover that is directly where the cursor is, it seems to register hovers as if the window had been scrolled even further than it was actually scrolled.  This happens on my Mac on both Safari 8.0 and Firefox 35.0.

```
<body>

foo<br>
foo<br>
foo<br>
foo<br>
foo<br>
foo<br>
foo<br>
foo<br>
foo<br>
foo<br>
foo<br>
foo<br>
foo<br>
foo<br>
foo<br>
foo<br>
foo<br>
foo<br>
foo<br>
foo<br>
foo<br>
foo<br>
foo<br>
foo<br>
foo<br>
foo<br>

<div id="mynetwork"></div>

    <link href="http://visjs.org/dist/vis.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="http://visjs.org/dist/vis.js"></script>

<script type="text/javascript">
    // create an array with nodes
    var nodes = [
        {id: 1, label: 'Node 1'},
        {id: 2, label: 'Node 2'},
        {id: 3, label: 'Node 3'},
        {id: 4, label: 'Node 4'},
        {id: 5, label: 'Node 5'}
    ];

    // create an array with edges
    var edges = [
        {from: 1, to: 2},
        {from: 1, to: 3},
        {from: 2, to: 4},
        {from: 2, to: 5}
    ];

    // create a network
    var container = document.getElementById('mynetwork');
    var data = {
        nodes: nodes,
        edges: edges
    };
    var options = {
        width: '400px',
        height: '400px',
        hover: true,
        zoomable: false,
    };
    var network = new vis.Network(container, data, options);
</script>

</body>
```

**Comment by AlexDM0** [comment]
Hi,

Good point, I'll fix this. Could you edit your posts and make them into jsbins instead of the big slab of code?

Cheers!

**Comment by orel360** [comment]
Hi,
same problem. Hovering over the nodes doesn't work when the scrollbar is scrolled down,  consequently titles displaying doesn't work (related to that issue: https://github.com/almende/vis/issues/585 ?).

Thank you for this library :)

**Comment by AlexDM0** [comment]
Hi,

There seems to be something wrong with the dist in our current release. We'll try to fix this today. It does not occur on the develop branch. There is a good chance that this fixes the #585 as well.

Regards,

Alex

**Comment by AlexDM0** [comment]
This has been fixed, we will release a new version today.

Regards

**Comment by orel360** [comment]
thank you, tested and it works well.

Aurélien

2015-01-22 14:13 GMT+01:00 Alex <notifications@github.com>:
