### ISSUE TITLE
Timeline + TUIO touch

### ISSUE THREAD

**Issue by treborrr** [almende/vis#597]
I'm having some problems with using the vis js timeline in combination with touch coming from a TUIO source. I get a "Uncaught RangeError: Maximum call stack size exceeded" from "Range._onDrag" op line 8073.
It seems that "var interval = (this.props.touch.end - this.props.touch.start);" on line 8057 doesn't receive any values. 

Did anyone get a TUIO source (in combination with some library for conversion to W3C touch) with vis js working?

**Comment by josdejong** [comment]
Can you test whether hammer.js (touch library) works correcty with TUIO touch? 

http://hammerjs.github.io/

**Comment by treborrr** [comment]
I tested this and it did not work. I skipped TUIO and am using Windows Touch Events right now.

**Comment by josdejong** [comment]
Ok thanks, then it's likely that the problem originates in either TUIO or or hammer.js, and not in vis.js itself. 

Good to hear you found a way around it. Can we close this issue?

**Comment by josdejong** [comment]
Is this still an issue?
