### ISSUE TITLE
Network display Performance

### ISSUE THREAD

**Issue by Kacius** [almende/vis#598]
Hi,

First of all, a big thanks for your great lib! 

My question is about the dynamic display of network (about 500 nodes) performance. 
When the network is drawing, it take a lot time and my browser becomes very busy.
(By dynamic display, I mean that no node positions provided, just the node groups)

Is there any way to have a fluid display of 500 nodes network?

Thanks a lot.

I'm using these options:

smoothCurves: false,
physics: {
  barnesHut: 
    {gravitationalConstant: -4000, springConstant: 0.04, springLength: 300, centralGravity: 0.2}
  },
hideEdgesOnDrag: true,
stabilize: false,
navigation: true,
keyboard: true

**Comment by AlexDM0** [comment]
Hi Kacius,

To solve this we have the option to store the positions. It's a tough problem and unfortunately it just has to calculate a lot. Chrome does a LOT better than firefox. There really isn't a way to speed it up I'm afraid.

You have already disabled the smoothCurves, you're already using barnesHut which is pretty fast. How many edges do you have? Edges are a bit hard to draw (see examples 27,28,29,30) but the calculation is fast.

You could turn stabilize on and use a stabilizationIterations value of 200 so it will atleast do 200 cycles without rendering.

Hope that helps.

Regards,

Alex

**Comment by Kacius** [comment]
Hi Alex,

Thank you for your reply. 

I'm using the lib to draw social networks, so the number of edges in practically equals to the number of nodes (number of edges is small)

I tried to turn stabilize on and use stabilizationIterations value 200, it is better with these options, but nodes don't stop moving when network is displayed, is there any way to turn off move of nodes when the network is drown? 

(I have other question about edge hover, can I ask it here or should create new issue?)

Thanks for your help,

Kacius.

**Comment by AlexDM0** [comment]
Hi Kacius,

Of course they don't stop moving as we have aborted the stabilization after 100 cycles. It is not stabilized at that point. You could manually disable the physics with a setTimeout (ugly, but there's no event that tells you when the drawing starts(yet)) and setOptions with these options:

```
var options = {physics: {barnesHut: {gravitationalConstant: 0, centralGravity: 0, springConstant: 0}}};
```

I cannot really recommend this though.. just keep it moving. You could maybe write an algorithm that does an initial layout and sets x and y values that could be good for your type of data to speed up the simulation further.

Please make a new issue for a question on a different topic, it will be easier for others to find.

Cheers

**Comment by Kacius** [comment]
Thank you Alex!
It's not very important, I can keep the nodes moving.

Kacius.
