### ISSUE TITLE
visjs-timeline, "timeSize" for resizing event with mouse

### ISSUE THREAD

**Issue by kjandrew** [almende/vis#599]
Hi, first overall sorry for my poor english.

To fix ideas, suppose a visjs-timeline that displays tasks on a daily time band between 08:00 am and 06:00 pm.
![img01](https://cloud.githubusercontent.com/assets/10656809/5860028/e88413ca-a25e-11e4-9838-1a9fd2b2d367.png)

The problem is: when I resize a task with mouse, then it seems that the task is auto-resized with the tick of 30 minutes. I wish I had the ability to resize the task freely.
For example for the TaskB I'd set with the mouse its "end" at 9:40.
How do I set up a possible step / snap to zero?

I saw that zooming I have a chance, but I can NOT enable zooming since it must be visible the entire span of time [08:00 am, 6:00 pm]

Thank You.

**Comment by josdejong** [comment]
The snapping of items start and end is hard coded, and depends on the current zoom level. If you can't zoom in to get a finer grained snap interval, you can use the functions `onMove` and `onMoving` to override the start and end of an item while dragging. See [docs](http://visjs.org/docs/timeline.html#Configuration_Options) and [08_edit_items.html](http://visjs.org/examples/timeline/08_edit_items.html)

**Comment by kjandrew** [comment]
Hi, I have followed the issue # 590 that could (?!) solve my problem; and I hope that version 3.9.2 is released soon.
Thanks for your help and congratulations for the excellent work on the timeline: it is a wonderful component.

**Comment by NemitkoIvan** [comment]
I use 
timeline.timeAxis.step.__proto__.snap = function (date) { return date };
to disable snapping.

**Comment by kjandrew** [comment]
Three times thanks NemitkoIvan, it works!
However: since I'm not skilled in jscript/jquery etc., then I had to change "directly" the source code of vis.js. This is because if I write your line "in the sense" of my code:
<pre>
this.tml = new vis.Timeline (divContainer, this.items, this.groups, this.options);
this.tml.timeAxis.step.proto.snap = function (date) {return date; };
</pre>
then Chrome (console) show:
<pre>Uncaught TypeError: Can not set property 'snap' of undefined</pre>

NemitkoIvan: thanks again for the help!

**Comment by AlexDM0** [comment]
@Josdejong maybe introduce the option to disable snapping? Or to set a distance or insert custom function?

**Comment by josdejong** [comment]
Yes, makes sense to create an option for this, an overridable function.
