### ISSUE TITLE
network navigation via keyboard disables use of cursor other keys

### ISSUE THREAD

**Issue by Gregoor** [almende/vis#600]
I didn't fully grasp how you/keycharm do the key binding, but as far as I get it, this is my view on how it is now, and how it should be:

The key events are attached via keycharm page-globally. Some events listen to keydown and all of them prevent the default which renders the cursor keys useless for example in text field.

Imo vis should either not listen for event page-globally (or have that as an opt-in) or differentiate on the basis of what is focused, so that you don't execute network navigational actions when input/textareas are focused. I'd go for no 1.

Thanks for the awesome work!

**Comment by AlexDM0** [comment]
Hi,

You're right, keycharm listens on window. I have added an option to the network to disable this:

- Added option bindToWindow (default true) to choose whether the keyboard binds are global or to the network div.

It has been pushed to develop and will be added in the next release.

Regards,

Alex

**Comment by Gregoor** [comment]
Awesome, you're the best. Thanks!
