### ISSUE TITLE
feature request: event between 'network constructor' and stabilized

### ISSUE THREAD

**Issue by b-pos465** [almende/vis#601]
Sometimes it takes a lot of time for the event 'stabilized' to be called. Actually it would be useful to have an option that makes it possible to call this event (or a new one) earlier, even if the nodes are still shaking a bit.

**Comment by AlexDM0** [comment]
Hi,

You can just reduce the stabilizationIterations if you want the stabilization process to have a maximum amount of cycles. It defaults at 1000, stabilization is essentially off if you choose 0.

Regards,

Alex
