### ISSUE TITLE
Items order changed when dragging and using moveable=false

### ISSUE THREAD

**Issue by caumons** [almende/vis#603]
I need to display some timelines as "read only", without allowing the user to move, zoom nor edit any item. I also want to remove the undesired default alphabetical order. To achieve all this, I've set the following options:

    var options = {moveable: false, zoomable: false, groupsOrder: false};

However, if the user drags the timeline, the items lose their order as described in #234, but the `rangechanged`, nor `rangechange` events aren't triggered. If I remove the `moveable` option, then I can move the timeline, the items loose their order too, but the the events are triggered propperly.

When using moveable=false and trying to drag, no event is triggered and the items lose their original order. But, as no event is fired, we can't react on this to reorder the items manually!

I've tried using the options timeChangeable=false and groupChangeable=false but they don't work neither.

The point here is, if we set moveable to `false`, then the items shouldn't loose their order as nothing will be modified at all.

Tested on Firefox 35.0 and Chrome 40.0 on Ubuntu 14.04 x64 machine.

Cheers.

(Note: This behaviour has been detected using amende chap-links displaying timeline charts).

**Comment by AlexDM0** [comment]
Hi,

Just to clarify, is this also happening in vis.js? Chap-links is no longer supported. Vis.js is in fact the second iteration of Chap-links.

Could you make a JSbin showing the problem?

Cheers

**Comment by caumons** [comment]
I'm using chap-links (I haven't used vis). But, as the same ordering issue still happens on vis and I've seen that vis is the continuation of chap-links I reported the issue here and wrote a note saying that I've experienced the issue on the older lib, but it's very likely to happen here too.

Cheers.

**Comment by AlexDM0** [comment]
Hi,

Vis is a complete rewrite of chap links. We do not support the old libraries anymore. I'd really recommend you move to vis.js. If the issue still persists in vis, please let us know. As far as I know, the issue has been resolved (the one you referred to is closed).

Regards

**Comment by caumons** [comment]
It that lib is not supported anymore, then it's OK. Thank you for your response and regards! :)
