### ISSUE TITLE
circularImage Display

### ISSUE THREAD

**Issue by Kacius** [almende/vis#604]
Hi,

I'm using dot to display my network nodes. Using groups to display same color for nodes of the same group. And to highlight some nodes, I'm using 'circularImage' as shape. Result is great and pretty!

My problem is: when displaying the network, the 1, 2 or 3 first seconds the nodes with 'circularImage' are displayed as 'dot' with the color of the group and then images are displayed correctly. It seems as a bug, is that normal?
Is there any way to directly display images without display as dot first?

Thank you,
Kacius.

Used conf:
var options = {
	nodes: {
            shape: 'dot',
	    borderWidth: 2
	},
	edges: { 
           inheritColor: "from" 
        },
	smoothCurves: false,
	physics: {
	   barnesHut: {
              gravitationalConstant: -4000, springConstant: 0.04, springLength: 300, centralGravity: 0.2
           }
        },
	hideEdgesOnDrag: true,
	hover: true,
	stabilize: true,
	stabilizationIterations: 200,
	navigation: true,
	keyboard: true
};
						
An this property on certain nodes:
  shape:'circularImage'

**Comment by AlexDM0** [comment]
Hi, 

That's actually normal. The images take time to load. You could preload the images to avoid this. You can use normal preloading techniques, it's not a feature of vis. So embed it in the Dom in a hidden div, stuff like that. Use a setTimeout to start vis or check if the images have been loaded with js. 

Cheers

**Comment by Kacius** [comment]
Thanks Alex,

My problem comes from image borken urls (when image url is not valid, and then it try to use the brokenImage one). I added in my code to test and insure that my image url is valid otherwise I put my default image url on the 'image' property. Now, it works and the display is great.

Thx,

Kacius.

**Comment by AlexDM0** [comment]
Hi Kacius,

Glad to hear it works! The circularImages assumes you want circles, filled with images. If that is not possible, just the circle remains. I can imagine other people would solve that differently but it can be worked around quite easily (as you did :)).

Cheers!
