### ISSUE TITLE
Multiselect on shift/ctrl click instead of hold-click

### ISSUE THREAD

**Issue by valtih1978** [almende/vis#606]
I would like to know why did you prefer the non-standard, mouse long-click, for multiselect? This seems counterintuitive and counterproductive (I can do much faster with Shift+mouse click). Actually both features are counterproductive. Can I reconfigure your graph to support Shift key for multiselect?

**Comment by valtih1978** [comment]
Ok, I had to replace `this._handleTap(pointer)` with 

```javascript
	event.gesture.srcEvent && (event.gesture.srcEvent.ctrlKey || event.gesture.srcEvent.shiftKey)
		? this._handleOnHold(pointer)
		: this._handleTap(pointer);
```
in `Network.prototype._onTap = function (event) {`

It seems that this is not possible without rewriting your code.

**Comment by AlexDM0** [comment]
Because touch devices don't have a shift key. We were still planning to add more hotkeys in future releases but different systems have different default hotkeys. Control click in windows vs cmd click on Mac. 

It's free, it's open, rewrite it.=

**Comment by josdejong** [comment]
@AlexDM0 the Timeline actually supports both shift+click and ctrl+click, would be interesting to add this to Network too.

**Comment by no1youknowz** [comment]
@josdejong I've looked at the code, where is it for timeline?  I wanted to add multi-select ability to network and unable to do so.

**Comment by josdejong** [comment]
@no1youknowz thanks, that would be great. The multiselect is in the `ItemSet._onMultiSelectItem` method: https://github.com/almende/vis/blob/master/lib/timeline/component/ItemSet.js#L201. The touch library hammer.js interprets ctrl+click as a `hold` event, and inside the method is a check to see whether the shift key is down (select a range of items) or not (add/remove clicked node to the selection).

**Comment by xogeny** [comment]
I'm confused.  This issue is open, but shift-click selection is implemented.  Shouldn't this be closed?  Or am I missing something.

**Comment by AlexDM0** [comment]
@josdejong  mentions the timeline where it is already implemtented. Valtih has implemented this himself in his own fork of our code. It is not in the official release.

**Comment by xogeny** [comment]
Ah...I totally missed that this was about network and not timeline.  My mistake.  Thanks for clarifying that.

**Comment by AlexDM0** [comment]
Hi,

This is now in the v4 that we have released today. There is an option for multiselect that has to be enabled first.

Regards
