### ISSUE TITLE
Graph Requirement in Vis

### ISSUE THREAD

**Issue by DivyashreeMS** [almende/vis#607]
Hi,

I have a  requirement to draw the graph as shown below, So can some one please suggest the right one to proceed further. 

![image](https://cloud.githubusercontent.com/assets/10521928/5958738/e959d456-a795-11e4-8b0b-ff5fd6aa565a.png)

Thanks & Regards
Divya

**Comment by AlexDM0** [comment]
Hi,

I don't think the vertically oriented date labels are possible at the moment, @josdejong do you know a css trick for this?

As for the rest, I don't think it should be too hard. Is there anything specific you can't get working?

Cheers

**Comment by DivyashreeMS** [comment]
Hi Alex,

 I am in fact planning to proceed with graph2d basic but I had a concern with curvy representation of graph, the requirement i have got is of straight line, so just wanted to get confirmed to proceed with graph2d in Visjs.
http://visjs.org/examples/graph2d/01_basic.html


![image](https://cloud.githubusercontent.com/assets/10521928/5959134/8c0f7950-a799-11e4-9408-860ed0ed70f8.png)

**Comment by AlexDM0** [comment]
How about this: 

http://visjs.org/examples/graph2d/06_interpolation.html

You can do straight or interpolated in a few different ways.

**Comment by AlexDM0** [comment]
Also, you can use this: 
http://visjs.org/examples/graph2d/09_external_legend.html
to do the legend. The rest is CSS styling and setting different groups.

Cheers

**Comment by DivyashreeMS** [comment]
ok. Thank you Alex.. I am planning to go for 06_interpolation, 

Regards
Divya
