### ISSUE TITLE
one more event registration in the doc

### ISSUE THREAD

**Issue by valtih1978** [almende/vis#608]
The [major doc says](http://almende.github.io/chap-links-library/js/network/doc/#Events)

```javascript
function onselect() {
  var sel = network.getSelection();

  var info = 'selected row(s): ';
  for (var i = 0; i < sel.length; i++) {
    info += sel[i].row + ' ';
  }

  alert(info);
}

google.visualization.events.addListener(network, 'select', onselect);
// Or, when not using the Google API:
//   links.events.addListener(network, 'select', onselect);
```

It is weird to hear that graph has some `rows`. Anyway, I have figured out that there is more concise event listener registration:

```javascript
network.on('select', function(params) {
	console.log("params.nodes: " + params.nodes.join(',') + ", network.sel.nodes: " + network.getSelection().nodes.join(','))
```

You may add it into the docs. Loading google libs was a hell.

**Comment by AlexDM0** [comment]
You do realize that docs for chap links do not apply to vis.js right?

There's a website with docs, examples and everything: www.visjs.org
