### ISSUE TITLE
Cannot drag the nodes after `edge mode` has failed

### ISSUE THREAD

**Issue by valtih1978** [almende/vis#610]
If you let onHold event to occur while connecting a node to void, your [example 21]
(http://almende.github.io/vis/examples/network/21_data_manipulation.html) seems to suck in edge-add mode so that when you you close it with "Back" navigation button, it behaves wierdly.

I think that the the issue is more easy to reproduce with [mine editor](http://valtih1978.github.io/VisualDict/almende-vis.html) when you enter a hundred words. You then reload the page, use browser search to find some word in the list and click it to locate in the graph. And this often ends up with graph stuck, often in edge-connection because browswer search is activated by Ctrl+F whereas I use Control for entering connection mode. But the problem is that it is stuck in some intermediate mode when exist from edge drawing.

Another issue is that you leave the edge mode once one connection has finished. This is much more productive to not to do that, as mine editor demonstrates.

**Comment by valtih1978** [comment]
Well, entering connections mode and leaving it, unstacks the engine.

**Comment by valtih1978** [comment]
It helped to cancel the edge mode as soon as another key is pressed over the control key. This prevented stucking in the edge mode and calling graph operations while in this delicate/vulnerable mode. Seems was my fuss. Your engine is perfectly smooth so far.

**Comment by AlexDM0** [comment]
I managed to reproduce this and pushed a fix to the develop branch.
