### ISSUE TITLE
[network] Please add support for dashed edges with arrows

### ISSUE THREAD

**Issue by mitya57** [almende/vis#613]
Dear vis.js developers,

In our project we visualize graphs with two types of edges: “parent → child” and “friend → friend”, and we would like edges of the former type to be drawn dashed. However, the vis documentation says:

> Choose from `line` (default), `arrow`, `arrow-center`, or `dash-line`.

It will be really nice if there was a `dash-arrow` style.

Thanks for the great library, btw!

**Comment by felixhayashi** [comment]
I agree! I also missed this combination :) Maybe it is also - at some point - possible to separate the line style from the arrow style to allow freely combining the two?

**Comment by AlexDM0** [comment]
Hi,

We're planning to go along the route described in #351 

I can't give an ETA on this but it will be in the 4.0.0 release. This release (by definition) will be breaking compatibility with the old versions because we really need to clean up the options structure.

Regards,

Alex

**Comment by felixhayashi** [comment]
> I can't give an ETA on this but it will be in the 4.0.0 release. This release (by definition) will be breaking compatibility with the old versions because we really need to clean up the options structure.

Sounds exciting. Thanks for the information.

**Comment by mitya57** [comment]
Great, having bi-directional arrows will be awesome as well.

**Comment by stanleyxu2005** [comment]
I agree with you all. I'm a bit greedy to see, if it can be possible in v4 or v5 to have animation on edges.  Here is an example http://echarts.baidu.com/doc/example/map12.html#-en

**Comment by AlexDM0** [comment]
I'm actually working on decoupling the dash and arrowheads from styles so they can be mixed and matched. As for the animations, there is no concrete plan to implement this. (your example URL does not seem to do anything so I have not seen the example).

It may be easier after 4.0 for the community to implement an animation so we'll see what happens.

Regards,

Alex

**Comment by stanleyxu2005** [comment]
@AlexDM0 Thanks for your quick reply. The example link will show a nice glow keeps moving along an edge. I hope you can finally see what I mean on the example. By the way visjs is awesome!

**Comment by felixhayashi** [comment]
> (your example URL does not seem to do anything so I have not seen the example).

the website took quite some time (20 sec) to load but it is a nice effect.

**Comment by AlexDM0** [comment]
Hi,

I tried the url again, the effect is nice and after 4.0 all the functions required for it are essentially available so who knows :)

Regards,

Alex

**Comment by AlexDM0** [comment]
I'm going by all things marked for v4 and checking if they are in yet. This one has been added. I'll mark it as done and close it on release of v4.

**Comment by AlexDM0** [comment]
With the launch of v4, this issue can be closed.
