### ISSUE TITLE
Wrong stacking with positive and negative bars

### ISSUE THREAD

**Issue by pavlos256** [almende/vis#616]
Hi. I think there's a small problem with the "stack" overlap handling when the data includes both positive and negative values. Here's a picture to better illustrate the problem:

![bar-stack-2directions](https://cloud.githubusercontent.com/assets/311595/6026173/2bf6568c-abe1-11e4-8cc1-abc004fd982a.png)

The first graph shows the data side by side. The second shows what I would like to achieve, while the third shows the current behaviour. (Note that I've manually set the Y min/max on the last two images).

Is this a bug or is it working as intended? If it is a bug, any hints on how it should be fixed? I tracked it down to Bargraph.draw(), where the height offset is calculated and accumulated but I'm not sure what else has to be changed (i.e. calculating the view port).

**Comment by AlexDM0** [comment]
Hi Pavlos,

This might be tricky.. When I designed this for my usecase I had no negative numbers, hence there is no sorting for positive and negative values. This is mostly in bargraph.draw() and could also be in the pipeline before that.

As for now, I'm afraid this is not supported with negative numbers and not (very) easily fixed. I'll look into this when I have time. If you want to chase after this yourself that would be great! The bar.js file has all the functions used by the bargraph. You might need to look into the range function too.

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi Pavlos, 

This has been fixed in 4.0 and will be released soon.

Regards,

Alex

**Comment by AlexDM0** [comment]
With the launch of v4, this issue can be closed.
