### ISSUE TITLE
Using hierarchical view with dataSets

### ISSUE THREAD

**Issue by wmleler** [almende/vis#618]
We are trying to use Vis to render a diagram showing nodes in a computer network. We are using a Network in hierarchical mode. The nodes and edges are stored in a DataSet because they come in over time.

The problem is that even for relatively small Networks, less than 100 nodes, Vis completely locks up the browser in a very tight loop. I cannot even cancel the webpage.  It locks up for several minutes, eventually causing the browser to put up a dialog saying the page is unresponsive.

If we reduce the number of nodes to around 50, it still locks up the browser as they come in, but eventually it becomes responsive again.

My guess is that there is some kind of interaction between the DataSets and the layout for the hierarchical view that is causing it to thrash in a tight loop.  Other than using DataSets (and filling them over 30 seconds or so), we aren't doing anything complex.  We have hover and smoothCurves set to false.

Interestingly, if we load exactly the same DataSets, but not using a hierarchical view, they load quickly.

If you have any questions, feel free to contact me at wmleler@google.com

**Comment by AlexDM0** [comment]
Hi,

On a dataset update the network has to recalculate the layout of all nodes and restabilize. If you keep adding a node every second, you keep repeating the loop. 

The reason for the calculation is that nodes are assigned levels based on properties of the network. These levels affect the position. Positions affect the physics. Etc.

In this case hierarchical layout may not be the best approach.

Regards

**Comment by wmleler** [comment]
It would be helpful if you warned developers to not use datasets with the hierarchical network view. And at the very least put in some setTimeout calls to give control back to the browser. The loop was so tight I couldn't even close the browser window.

**Comment by AlexDM0** [comment]
It's fine with datasets, In your specific case you push too many updates to it for the network to keep up. We'll improve on this in the future.
