### ISSUE TITLE
XML - Network

### ISSUE THREAD

**Issue by Kritika688** [almende/vis#619]
Hi,

I have an XML file of the format:
<node id="n0"/>
<node id="n1"/>
<edge id="e1" source="n0" target="n1"/>

I am trying to parse this xml file and display nodes and edges on browser with the following code:
var my_xml_object;
var request = new XMLHttpRequest();
request.open("GET", "sample.xml", false);
request.send();
my_xml_object = request.responseXML;
var nodes = my_xml_object .nodes;
var edges = my_xml_object .edges;

I have tried different methods to retrieve data in vis.js format, however unable to do it.
Is there any example or sample code that could help me proceed?

Thanks & Regards,
Kritika

**Comment by josdejong** [comment]
Your nodes and edges have to be JSON, not XML. So you will have to convert your XML data into JSON before feeding it to Network. There are quite some libraries out there to do this for you, you can google for it.

**Comment by Kritika688** [comment]
Thank you for your response.My data set would be of the format in an external json file:
{"nodes":[{"id": "1"},{"id": "2"}],"edges":[{"id":"e1", "from": "1", "to": "2"}]} 

Would i need to use Gephi parser or could i do it directly?

**Comment by josdejong** [comment]
If you have a graph in Gephi and you want to render it in the vis.js Network, you can export the data using the [json-exporter plugin](https://marketplace.gephi.org/plugin/json-exporter/) of Gephi, see this example: http://visjs.org/examples/network/30_importing_from_gephi.html.

If your data is already in the right (JSON) format for the vis.js Network, there is no need to use any special parser.

**Comment by Kritika688** [comment]
Thanks !
