### ISSUE TITLE
Stacking options for groups/subgroups/items

### ISSUE THREAD

**Issue by billbither** [almende/vis#620]
I would like to specify more stacking options. For example some items (or group of items) I'd like to stack, while others I would not. 

As you can see with the below image, the bottom row shouldn't stack as it represents continuous time of different conditions, while the subgroup above are single events that I'd like to stack.
![image](https://cloud.githubusercontent.com/assets/5885418/6074663/73aaa0a8-ad91-11e4-9e21-47cfd071329d.png)

**Comment by AlexDM0** [comment]
@josdejong maybe we could look into setting stacking per group?

**Comment by josdejong** [comment]
@AlexDM0 I guess you mean stacking per *subgroup*, stacking works already fine for groups ([see example](http://visjs.org/examples/timeline/05_groups.html)). Yes, that makes sense.

**Comment by AlexDM0** [comment]
Hi,

I think you misunderstood, I ment to select on a group to group basis if you want to use automatic stacking OR the subgroups.

Regards

**Comment by josdejong** [comment]
Ah ok, so you can choose per group whether you want stacking or subgroups or no stacking. Sounds good.

**Comment by bbseven** [comment]
Thanks, that will be a great enhancement!

**Comment by carueda** [comment]
:+1:

**Comment by Atala** [comment]
@josdejong did you have time to work on this?
@bbseven did you found a solution/hack for this ?

**Comment by josdejong** [comment]
I haven't yet worked on it, it's still on the list. Unless we want a hacky solution, it will involve a serious refactoring of the subgroups.

**Comment by Atala** [comment]
Thanks, I will have a look a little bit later.

**Comment by simo9000** [comment]
I just ran into the need for this feature. Can't wait until it's added.

**Comment by odick** [comment]
Hi all, not sure if this would help
I got the solution from [stackoverflow] (http://stackoverflow.com/questions/33310120/vis-js-timeline-dont-stack-items-with-no-time-overlap)
```
var options = {
    margin: {
        item : {
            horizontal : 0
        }
    }
};
```
result:

![pale moon 2016-01-04 22 48 43](https://cloud.githubusercontent.com/assets/1612324/12092180/72f1b5b0-b336-11e5-930d-6205451e3292.png)

**Comment by simo9000** [comment]
I just tried this and it is a perfectly acceptable solution for my specific
problem.

Thanks.

**Comment by scipilot** [comment]
A workaround I've just implemented is to turn stacking off (globally) but then create "fake" subgroups for the items you do want to stack within a group. Just increment or randomise a subgroup ID as you add items in the "stacked group" - or use something unique from the item data to separate them. You could get clever and limit the stacking to say four rows max (then of course this is starting to sound like properly sub-grouping and ordering them with some item semantics).

I would like this stackable-per-group feature too, but find this workaround so simple to implement it suffices.

**Comment by emillykkejensen** [comment]
Any news on if and when this feature will be implemented?

**Comment by yotamberk** [comment]
This can be done with what @scipilot suggested. see : http://visjs.org/examples/timeline/items/expectedVsActualTimesItems.html
Closing this feature unless someone thinks that the current solution is not enough

**Comment by Reollyn** [comment]
This is not working for me when i set it in options.

```
var options = {
    margin: {
        item : {
            horizontal : 0
        }
    }
};
```

Does anyone know maybe why?

**Comment by webwakko** [comment]
I love this feature, but...it would be nice if it had some kind of binding to the item that is on top. 
meaning.. when moving the upper layer item, the one below should move along with it.
Not breaking the separate resizing posibility offcourse...
