### ISSUE TITLE
Unzoom with browser cause graphical issue

### ISSUE THREAD

**Issue by FloLach** [almende/vis#622]
Hi

When unzooming with the browser (ctrl+wheel on most browser) with a network graph on the current page.
After refreshing the page their is graphical issue on a part of the network graph.
Screenshot made using  demo at http://visjs.org/examples/network/06_groups.html 
![network-graphic-issue](https://cloud.githubusercontent.com/assets/10884481/6082198/973e5f6c-ae1f-11e4-956a-3a36fabf6db8.png)

**Comment by AlexDM0** [comment]
Hi,

That's.... kinda cool :)  even so, I have pushed a fix for this to the develop branch. Thanks for reporting it!

Cheers
