### ISSUE TITLE
Graph2d / Barchart: Sorting groups broken with string ids

### ISSUE THREAD

**Issue by pavlos256** [almende/vis#624]
Hello. There are two small issues when using string ids for the groups instead of numeric.

* If I'm not mistaken, the group ids are used to sort the groups in the legend. This doesn't seem to work when using strings; the groups are kept in the order they are given.

* A day's items appear in random order and are changing order when zooming in or out. This can be seen by using example 11 (barsSideBySideGroups) and using string group ids. This is probably because of [these](https://github.com/almende/vis/blob/c397262c1fcd8286214a3b1f7f2cbbd6ad44bc24/lib/timeline/component/graph2d_types/bar.js#L71) [two](https://github.com/almende/vis/blob/c397262c1fcd8286214a3b1f7f2cbbd6ad44bc24/lib/timeline/component/graph2d_types/bar.js#L188) sorting functions.

This issue seems to be similar to #538. I wasn't aware that there used to be an "order" field but I think this is exactly what's needed in this case, instead of using the group id to sort.

Thanks.

**Comment by AlexDM0** [comment]
Hi,

It seems like I have indeed assumed group id's are integers when I built the graph2d. I'll see if we can clean that up. Thanks for notifying us!

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi,

This has been fixed in the v4. We hope to release it soon. Thanks for the update!

Regards,

Alex

**Comment by AlexDM0** [comment]
With the launch of v4, this issue can be closed.
