### ISSUE TITLE
On Cell time range 

### ISSUE THREAD

**Issue by DivyashreeMS** [almende/vis#627]
Hi,

I had a small requirement, If I click on the horizontal bar only the selected cell time range need to be fetched, as per the screen shot if I click on 06:50 Cell I need to get the time range of that cell ie from 06:50 - 06:55. Can someone please share the code for this.

But now currently I am getting all the slot time range ie from 6:10 - 7:43
Code goes like below: 

timeline.on('select', function (properties) {
      logEvent('select', properties);
    });

 function logEvent(event, properties) {
   	 var id=properties['items'];
        console.log('id>>'+id);
        var item1 = items.get(parseInt(id));
        console.log("item Content>"+item1.start);
  }

![oncellevent](https://cloud.githubusercontent.com/assets/10521928/6148763/232fdd42-b1d2-11e4-918e-69ae7cd4ffc7.jpg)

**Comment by AlexDM0** [comment]
Hi,

To solve this, @josdejong could (or should) we bring the _toGlobalTime and _toGlobalScreen functions to the public API? You could just transform the x position of the cursor to a time in the timeline and the other way around.

Cheers!

**Comment by DivyashreeMS** [comment]
Hi Josdejong,

To put my problem in simple sentences here it goes:
Every event (represented above in the picture with a horizontal color bar) has a time span greater than 1 unit of the time represented in the chart.
When I click on any of the event bar, I get the detail of the events for the entire time period. 
For example if I click on the yellow horizontal bar anywhere against 'Used Memory' (Y-axis), the detail is fetched for the entire event period beginning from 6:10 to 7:43.

Now what I need is to get the time unit where the mouse is clicked.
For example if I click anywhere on the cell that represents 6:45 to 6:50 I should be able to get the exact time value of the point where the mouse is clicked.

Hope I am more clear on the problem that I'm facing. I've not been able to find any api or method to get the specific data I'm looking for. I'm sure I'm missing something either silly or am not able to get hold of the right api.

Any help on this would be quite helpful and appreciated.

Thanks & Regards
Divya

**Comment by DivyashreeMS** [comment]
Hi Alex,

Please let me know if there is any work around for the issue.. I would Appreciate your help if you could suggest a plugin to solve the issue.

Thanks 
Divya

**Comment by AlexDM0** [comment]
Hi Divya,

At the moment this is not possible with the current API. What you could do is listen for the click event on window, calculate the x position relative to the timeline upper left corner and call the function 

```
var time = network._toGlobalTime(xpos);
```

This is using our internal functions and there are no guarantees this will keep being functional in the future. In general Id recommend you'd wait until this is possible with the public API. As I suggested to @josdejong, it may be useful to bring this functionality to the public API. 

Regards,

Alex

**Comment by DivyashreeMS** [comment]
Hi Alex,

Thank you for the quick reply, I started working as per the given suggestion, but I am getting  
"Uncaught ReferenceError: network is not defined", So do I need to add any other package to support or in simple how do I get this error resoloved.
Appreciate your help!!

Thanks & Regards
Divya

**Comment by AlexDM0** [comment]
Hi Divya, 

My bad, I've been working wiht the network a lot so I just assume any vis instance is called network.
It should just be the variable that holds the timeline like so:

```
var timeline = new vis.Timeline(...);

var time = timeline._toGlobalTime(xpos);
```

If you'd like more help with this I'd prefer you make a JSBin so I can see the code and help out.

Regards,

Alex

**Comment by DivyashreeMS** [comment]
Hey Alex,

Thank you I am getting the values but it is not accurate as expected. So certainly I would like to  share my piece of code. Please suggest how I can proceed to keep my code in JSBin.
You can reach me at 9738746397, New Jersey.

Thanks
Divya

**Comment by AlexDM0** [comment]
Hi Divya,

I'm not planning to call to the US from the Netherlands.

www.jsbin.com

Regards,

Alex

**Comment by DivyashreeMS** [comment]
Thank you Alex the solution provided is working fine!!

**Comment by josdejong** [comment]
> To solve this, @josdejong could (or should) we bring the _toGlobalTime and _toGlobalScreen functions to the public API? You could just transform the x position of the cursor to a time in the timeline and the other way around.

@AlexDM0 yes, makes sense to work on opening up these functions. Together with event handlers for events like click and hover which are still missing.

**Comment by DivyashreeMS** [comment]
Hi Alex/Josdejong,

Thanks for the solution provided.
I am trying to use pixel values for xpos, is there a way of making it responsive through pixel to percent conversion?
This doesn't work for different resolution/orientation monitors? 

when do you think this functionality(_toGlobalTime) will be opened up.

Thanks & Regards
Divya

**Comment by josdejong** [comment]
The just released v3.11.0 contains event handlers `click`, `doubleClick`, and `contextmenu`. These events give back information about the clicked location. 

Does that solve your issue?

**Comment by DivyashreeMS** [comment]
Hi Josdejong,

Thank you for the best solution provided. It is working perfectly as per the expectation. 
Highly appreciate for your help!

Thanks 
Divya

**Comment by josdejong** [comment]
Ok great, thanks for the feedback.
