### ISSUE TITLE
2DChart stack graph - Random groups order on Chrome

### ISSUE THREAD

**Issue by OzoneGrif** [almende/vis#628]
I'm using 2D stacked Charts with groups.

On FireFox, it works fine
![image](https://cloud.githubusercontent.com/assets/10961896/6150514/353480e0-b210-11e4-85e5-7eb4d9f6a83a.png)

On Chrome, the groups are sorted randomly, leading to display weirdness.
![image](https://cloud.githubusercontent.com/assets/10961896/6150542/539c1f7a-b210-11e4-96cb-a1718bb1fd8a.png)

Note how the blue and orange bars aren't always in the same display order.
It gets worse with more groups.

This is on Chrome : 40.0.2214 and Vis 3.9.1 and 3.10.0

**Comment by josdejong** [comment]
Thanks for your report. Do you maybe have a simple jsbin or jsfiddle demonstrating the issue? (it doesn't happen for example in example [11_barsSideBySideGroups.html](http://visjs.org/examples/graph2d/11_barsSideBySideGroups.html))

**Comment by AlexDM0** [comment]
Hi,

I think this is the same issue and the other recent one posted here on the graph2d. I'm not in the office now so I can't look it up. 

The problem is that the Id of the groups are strings, and the ordering function assumes numbers. 

It's on my "to-fix" list. 

Cheers

Alex

**Comment by OzoneGrif** [comment]
There you go :

http://jsfiddle.net/vm9both3/

**Comment by AlexDM0** [comment]
Hi Ozone,

Glad to hear it works for you now! The issue I referenced was #624. We'll fix the string issue soon(ish), when I get some time.

Cheers

**Comment by AlexDM0** [comment]
Hi,

This has been fixed in the v4. We hope to release it soon. Thanks for the update!

Regards,

Alex

**Comment by AlexDM0** [comment]
With the launch of v4, this issue can be closed.
