### ISSUE TITLE
Ability to add labels to points on Graph2D

### ISSUE THREAD

**Issue by tobeee** [almende/vis#630]
Hi,

Does anyone know if there might be a way to add labels to points on a graph, and display them?

I'd love to be able to add brief descriptions at certain timeframes, ie "Data input error at this point"

Alternatively - does anyone if one could add a label below the time axis which could also do the same function? Obviously it wouldn't be the same as having it on a per-point basis but would also be super useful.

Best,

Toby

**Comment by josdejong** [comment]
This isn't yet supported. Would be nice to have support for annotations in graphs.

**Comment by tobeee** [comment]
I wonder if it might be possible to add to the code myself? I assume the points on the graph are just DOM elements, so perhaps adding to them either with CSS or adding a second element should be reasonable.

Does anyone know the exact lines where in the graph2d where the item array is turned into DOM? I suppose it would also be good to pinpoint the zoom code which works out which elements to render....

Any help would be great :)

Thanks

**Comment by josdejong** [comment]
Sure, contributions are very welcome :)

bar.js, line.js, and points.js are a good starting point:
https://github.com/almende/vis/tree/master/lib/timeline/component/graph2d_types

**Comment by tobeee** [comment]
Thanks I will take a look. Quick question, where can I investigate DOMutil.drawPoint

**Comment by josdejong** [comment]
It's here: https://github.com/almende/vis/blob/master/lib/DOMutil.js

Where the script is coming from is [defined on top of the script](https://github.com/almende/vis/blob/master/lib/timeline/component/graph2d_types/line.js#L4), using commonjs modules.

If you use an IDE like WebStorm, you can just Ctrl+Click or Ctrl+B to go to the definition of methods/classes.

**Comment by tobeee** [comment]
Thanks :) I'll take a look today

On Fri, Feb 13, 2015 at 10:11 AM, Jos de Jong <notifications@github.com>
wrote:

> It's here: https://github.com/almende/vis/blob/master/lib/DOMutil.js
>
> Where the script is coming from is defined on top of the script
> <https://github.com/almende/vis/blob/master/lib/timeline/component/graph2d_types/line.js#L4>,
> using commonjs modules.
>
> If you use an IDE like WebStorm, you can just Ctrl+Click or Ctrl+B to go
> to the definition of methods/classes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/almende/vis/issues/630#issuecomment-74231639>.
>



-- 
Toby Green

**Comment by AlexDM0** [comment]
Hi Tobeee,

Thanks for wanting to contribute! We have had issues on this and it is listed in the feature requests. Could you take a look at the referenced issues on the topic as listed on the featre request page?

http://visjs.org/featureRequests.html

If possible it would be great if the solution would fulfill the usecases shown there :).

Cheers!

**Comment by tobeee** [comment]
Thanks guys will take a look as the issues.

My initial idea didn't work out. It was a *bit* hacky to start with, but it
seems SVG's styles are not completely the same as HTML.

I tried to add a "content" CSS rule to the Group CSS style (both the class
itself, and using a pseudo CSS after class).
The idea here was if it worked for the group I would have added support for
individual points to use custom-classes. Then we could have generated
custom classes as needed and apply them to select points when drawing.

I think to do this properly one would have to add a second text svg element
near the point itself



On Fri, Feb 13, 2015 at 10:44 AM, Alex <notifications@github.com> wrote:

> Hi Tobeee,
>
> Thanks for wanting to contribute! We have had issues on this and it is
> listed in the feature requests. Could you take a look at the referenced
> issues on the topic as listed on the featre request page?
>
> http://visjs.org/featureRequests.html
>
> If possible it would be great if the solution would fulfill the usecases
> shown there :).
>
> Cheers!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/almende/vis/issues/630#issuecomment-74235508>.
>



-- 
Toby Green

**Comment by AlexDM0** [comment]
Hi Tobeee,

If it helps, I was planning to do a div element on top of the SVG to make the label and only an SVG line to the datapoint.

Regards

**Comment by tobeee** [comment]
OK guys, I've done it. It's quite raw (I mean I was editing the compiled JS
file on my live server) but I think it would serve as a good initial guide
to how this might work. Plenty of room for expansion but I think it could
also serve to work on some of the more advanced functionality like tooltips.

I've uploaded my changeset here:
https://gist.github.com/tobeee/85d4e299fbb829f78016

Now all you need to do is add a label parameter on to each item if you want
it displayed. ie

var itemBPM = {x:x, y: y ,group:"group", label:"test" };

You could add a mouseover to show a tooltip, or perhaps even use some way
of testing visibility to decide if you want to render it at all. Could
expand and reduce font size depending on zoom level etc

I'd be very happy to talk this over a bit more when someone has time as I
wasn't super happy about editing LineGraph.prototype._convertYcoordinates


On Fri, Feb 13, 2015 at 2:25 PM, Alex <notifications@github.com> wrote:

> Hi Tobeee,
>
> If it helps, I was planning to do a div element on top of the SVG to make
> the label and only an SVG line to the datapoint.
>
> Regards
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/almende/vis/issues/630#issuecomment-74260623>.
>



-- 
Toby Green

**Comment by AlexDM0** [comment]
Hi Toby,

You can add me on skype if you'd like, using the chat there might be faster than using the git board. My skype is alexdemulder

Cheers

**Comment by tobeee** [comment]
I added my changes in pull request @ https://github.com/almende/vis/pull/635
