### ISSUE TITLE
Invalid label css classes

### ISSUE THREAD

**Issue by y-lohse** [almende/vis#631]
Hi, not a big issue, but according to [the CSS spec](http://www.w3.org/TR/CSS21/syndata.html#characters)

> In CSS, identifiers (including element names, classes, and IDs in selectors) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); they cannot start with a digit, two hyphens, or a hyphen followed by a digit.

Some minor labels in vis create classes like `0-4h` which are not valid. Those selectors are unusable & generate compiling errors in sass. [There are workarounds](https://github.com/sass/sass/issues/255) so again it's not a big problem, but maybe they should be renamed :-)

**Comment by josdejong** [comment]
Thanks, I've fixed this in the `v4` branch as this will be a breaking change.
