### ISSUE TITLE
Custom cluster nodes in network graph

### ISSUE THREAD

**Issue by noVerity** [almende/vis#632]
Is there a way to specify a custom image for a node that is used for clustering? It looks like it is just using a stacked version of the node the text is clustering around. I'd like to use a custom svg image I'd generate based on the nodes that are being moved into the cluster.

Alternatively is it possible to specify nodes that will be favoured in the clustering process or limit clustering to those nodes? 

Based on the documentation, clustering seems to be only based on the maths around the graph.

**Comment by AlexDM0** [comment]
Hi Noverity,

No, that is not possible at the moment. I do plan to do a complete rewrite of the clustering soon(ish) because of multiple reasons. We also want to make the network more modular and extendable so this will be possible in the future. 

Regards,

Alex

**Comment by noVerity** [comment]
Thank you for the answer.

**Comment by valtih1978** [comment]
I would customize the cluster giving it the name of the most important node (highest degree of connections) rather than simply the number of merged nodes!

**Comment by josdejong** [comment]
@valtih1978, a tip in order to help you communicating in a more constructive, respectful way (see https://github.com/almende/vis/issues/623#issuecomment-74483916). You could replace:

> I would customize the cluster giving it the name of the most important node (highest degree of connections) rather than simply the number of merged nodes!

with something like:

> It would be great to have a way to customize the text displayed on a cluster node. For example instead of displaying the number of merged nodes in the cluster, you could display the name of the most important node in the cluster (the one with the highest degree of connections).

**Comment by valtih1978** [comment]
You have got my point. If you want it to the depth, the point clarifies that customization needs to be collapsed network aware/specific. Current document says that collapsed network is removed from the graph, that it is not available. This creates impression that you cannot pick appropirate name for the cluster. If you do not know what is being/was collapsed, you do not have enough information for the customization. Might be there needs event/callback that would notify which nodes are about to collapse and request approval/customization in response, as it is done for onDelete.

**Comment by valtih1978** [comment]
Apart from customisation, removing collapsed subnetwork makes it impossible to select specific node within collapsed subnet. I have a list of nodes and I want to select it or navigate to it by id. If node is within collapsed cluster then navigation fails. How do you expand the collapsed cluster if you have the index/subnet removed?

**Comment by AlexDM0** [comment]
Hi,

We just launched v4 with the new clustering system. This new system is exactly what is described in this issue, thereby solving it.

Cheers
