### ISSUE TITLE
Question regarding timeline item placement when previous item ends on next item start date.

### ISSUE THREAD

**Issue by Gugarion** [almende/vis#637]
I would like to render items next to each other in the case that they start and end at the exact same time. Is this possible? If so, I don't see any obvious way to do so. Any help would be appreciated.

(When using range)

**Comment by y-lohse** [comment]
Setting the `stack` option to false would do that, but would also makes ranges that overlap... well, overlap visually.

**Comment by AlexDM0** [comment]
Hi,

I think the problem in this case is the margins. You should set the margins to 0 in order to avoid the stacking with the range.

http://visjs.org/docs/timeline.html#Configuration_Options

Regards,

Alex

**Comment by Gugarion** [comment]
@y-lohse - thank you, I do still want to maintain stacking in this case, I should have mentioned that.

@AlexDM0 Oh, that's spiffy! Thanks. For some reason I made the (lazy) assumption that the margin didn't relate to the timescale and it was purely CSS related. But now I see that you even take into consideration padding and allow us to define that in the config options as well to ensure they line up with the timescales. I'm so impressed with the consideration that's gone into this library. I'll be sure to present my end product to possibly add to the showcase.

**Comment by AlexDM0** [comment]
Hi Gugarion,

Sounds good! Can't wait to see what you came up with!

Cheers
