### ISSUE TITLE
Timeline Scrolltop question

### ISSUE THREAD

**Issue by y-lohse** [almende/vis#640]
Hi, i've been using vis and tinkering around with the code and overall it works really well, and the loose coupling makes it quite easy to dive in… so good job :-).

I have a question regarding the scrollTop handling in timelines. Honestly, it doesn't seem to do anything for me, but I'm not sure what it was designed for. In my mind, it could be used to vertically scroll timelines that overflow, such as this one:

![vis-scroll](https://cloud.githubusercontent.com/assets/2261445/6226110/648d3e64-b692-11e4-9c4a-1ee4edc07058.png)

Is this correct? If so, i don't think it's working. Basically [this line](https://github.com/almende/vis/blob/master/lib/timeline/Core.js#L869) will always set `scrollTop` to `scrollTopMin` which is always computed to 0. If it is indeed a bug, I can probably fix it & do a PR if you're interested.

If i'm wrong, how is vis supposed to handle the situation in the image above?
Thanks!

**Comment by y-lohse** [comment]
Darn guys, sorry — I totally missed the `height` option. When using that the scrolling works perfectly.and solves the case.

**Comment by AlexDM0** [comment]
Glad you solved it :) Have fun!
