### ISSUE TITLE
Timeline-background item tooltip

### ISSUE THREAD

**Issue by ebuyuk** [almende/vis#642]
Hi,
I need to give tooltip to my background items but It does not work.Could you advise me how can I add?
My options : 
var options = {
                           dataAttributes: ['all'],
                            editable: true,
                            orientation:'top',
                            stack: false,
                            type: "range",
}
var item ={
        'tooltip': 'This is item 1',
}
I add screenshot green colors are my background item, blue is my normal item.

Thank you for your support.
![image](https://cloud.githubusercontent.com/assets/11030721/6230579/91ab1042-b6c9-11e4-805e-80d7781b8f64.png)

**Comment by brichbe** [comment]
Set the item's 'title' property instead of 'tooltip'.

http://visjs.org/docs/timeline.html#items

**Comment by AlexDM0** [comment]
Hi Ebuyuk,

I think Brichbe is right. That should solve the issue.

Regards,

Alex

**Comment by ebuyuk** [comment]
Hi All,
Thank you for your quick response.
I test at vis 3.10.0 and vis examples,24_all_data_attributes.
I used 'title' property at item 1,It works normal items I test at examples 24.(IMAGE1)
But If I used at background item (item 6's type is background)it does not work.(IMAGE2)
I figure that if I change this item's z-index,I can see tooltip.(IMAGE3)



![image](https://cloud.githubusercontent.com/assets/11030721/6248354/6f146452-b787-11e4-811c-10e96ea0e6d0.png)
![image](https://cloud.githubusercontent.com/assets/11030721/6248390/d1697926-b787-11e4-9a4e-964664771c85.png)
![image](https://cloud.githubusercontent.com/assets/11030721/6249246/9bb05262-b78e-11e4-826a-26903e63be11.png)

**Comment by josdejong** [comment]
This has to do with the Timeline using two layers: the background items are displayed in the background layer, and regular item in the foregound layer. 

A single `z-index` on the background items will not really work: then we get layout issues where the background items are drawn before the regular items.

There may be ways to fix this, that will at least require re-organizing the DOM tree of the Timeline. Lets think about it.

**Comment by mojoaxel** [comment]
@ebuyuk Is this still an issue? If not can you please close this. Thanks!
