### ISSUE TITLE
Not able to redraw after changing options to hiearchical layout.

### ISSUE THREAD

**Issue by whalliburton** [almende/vis#643]
As I'm new, I'm thinking this is probably a misunderstanding, but the two following lines do not redraw the graph using the hierarchical layout.

    network.setOptions({ hierarchicalLayout : true });                                                                 
    network.redraw();

**Comment by AlexDM0** [comment]
Hi,

Could you make a jsbin showing this? Im not sure what it is you're expecting. Have you looked at our examples?

Regards,

Alex

**Comment by whalliburton** [comment]
Sorry, I should have written a more descriptive explanation. Let me write more. I have never used jsbin and generate all my javascript from lisp, but if the following does not suffice I will put up an example.

I have looked at the examples, but there is not an example of toggling between a non-hierarchical and hierarchical view on the same data. 

I create a network using the default options (non-hierarchical) and it draws fine. I wish to have a toggle that switches between the standard layout and the 

    var data = createVisGraph(graph);                                                                                  
    var nds = new vis.DataSet(data['nodes']);                                                                          
    var eds = new vis.DataSet(data['edges']);                                                                          
    var network = new vis.Network(container, { nodes : nds, edges : eds }, { width : container.offsetWidth, height : container.offsetHeight });                                                                                              

I then attempt, later, to toggle the view into a hierarchical layout using

     network.setOptions({ hierarchicalLayout : true });                                                                 
    network.redraw();                                                                                                  

And this does not seem to work for me, although I think it should. Note that in the docs  the "hierarchicalLayout" is only listed for the initial options and not for setOptions. So maybe this is not prossible and I need to create a new network in-order to toggle?

Thank you very much,
Will

**Comment by AlexDM0** [comment]
Hi Will,

I see what you mean. I have pushed  a fix to the develop branch to allow for this.

Cheers!

**Comment by whalliburton** [comment]
I really appreciate this push, but it is not complete yet. The reverse is not working. I cannot 

  network.setOptions({ hierarchicalLayout : false });                                                                 
  network.redraw();                                                                                                  

and have it revert to the concentric view.

**Comment by AlexDM0** [comment]
We get emails on all messages on here so no worries :).

I'll see if I can get to this issue next week. In the meantime, try using the configurePhysics. That allows you to switch back and forth :).

Regards

**Comment by thraxst** [comment]
Any update on this?

**Comment by AlexDM0** [comment]
Not yet. 

The next release will be 4.0. I'll add this to the release then. We plan the release around april.

Regards

**Comment by AlexDM0** [comment]
I'm going by all things marked for v4 and checking if they are in yet. This one has been added. I'll mark it as done and close it on release of v4.

**Comment by AlexDM0** [comment]
With the launch of v4, this issue can be closed.
