### ISSUE TITLE
Draw something on the main canvas element except the network ?

### ISSUE THREAD

**Issue by rasti90** [almende/vis#645]
hi
I use network with hierarchical option to show some kind of tree with three levels. What I just want to do is to create a box around each level of the tree and some text or labels with it. but it seems that i can not draw anything except the normal network nodes and edges.
now I want to know if there is such a functionality in the library or anything else I can do for my problem.
thanks a lot.

**Comment by AlexDM0** [comment]
Hi Mohammad,

This is not supported in vis. If you are proficient with JavaScript I could help you to hack this in yourself though. You could overload the redraw function and inject draw operations based on the position of the nodes. Naturally this is not supported by our public API but as this is an open source project you can do anything you want with it. 

Regards,

Alex

**Comment by rasti90** [comment]
thanks a lot for your answer. I just thought it might be supported by the API.
but anyway that would be cool if I can hack that in myself.

**Comment by AlexDM0** [comment]
In that case, clone the project and open the network.js file. You can insert your logic in the _redraw function just past the clearing of the canvas. 

Be warned that this function is ofcourse subject to change in future releases.

Have fun! If you make it work Id be interested to see the result in action :)

Cheers

**Comment by rasti90** [comment]
It would be a challenge of course for me. bu that would be nice.
thanks again.

**Comment by knyazhe1** [comment]
similar question:
i have timeline visualisation to events with same props on another levels (another groups). it would be great if i can join center of its item box (on back plane) via smart bezier line like graph2d module make it.

**Comment by AlexDM0** [comment]
Hi,

This is not possible with easy changes like it is in the network. The timeline is shown in the DOM whereas the network is all canvas. 

For the timeline you'd have to hijack a lot of different things and I can't really recommend it. 

Regards,

Alex

**Comment by knyazhe1** [comment]
@AlexDM0 
don't use "hijack" anywhere, please! :) usually this term related to virii soft and cracks :))
you means a hacking tricks, i think. 
now i use next trick: top visualisation with timeline and sinchronised (via events) timeline axe in low visalisation with graph2d. 
maybe better way (instead of your way): move low visalisation with graph2d as "background" item in the top with timeline visualisation. some kind of google "material design" :))) its easy rather than rewrite a full component, i think. and nicely too ;-)
