### ISSUE TITLE
Not able to toggle between hierarchical layout and standard layout. Related to #643

### ISSUE THREAD

**Issue by whalliburton** [almende/vis#647]
Hello. Issue #643 was closed but it only addresses one side of the question. You can now switch to the hierarchical layout and redraw, but the reverse does not seem to work.

**Comment by AlexDM0** [comment]
Hi, 

Sorry for not reopening the other issue, was a busy day :). I agree that the situation has not been fixed. I'd like this to remain in the other issue if that's ok with you.

Regards,

Alex

**Comment by whalliburton** [comment]
Alex, No worries. I just didn't know if you saw the other message because the issue was closed. I am very impressed with your responsiveness and willingness to help out. Will
