### ISSUE TITLE
OnMove function returns wrong item ID

### ISSUE THREAD

**Issue by SirNeuman** [almende/vis#648]
I'm having a problem with the onMove function for the timeline. When I print my dataset I get this:

![screen shot 2015-02-19 at 12 49 33 pm](https://cloud.githubusercontent.com/assets/6912634/6272463/cc4232a4-b835-11e4-8064-6c5104651b6f.jpg)

but when i call the onMove function in my options, which looks like this: 

![screen shot 2015-02-19 at 12 53 27 pm](https://cloud.githubusercontent.com/assets/6912634/6272532/568de35e-b836-11e4-8cf5-a2830217bbb9.jpg)

and I move an item in my timeline the console prints something like this: 
![screen shot 2015-02-19 at 12 55 21 pm](https://cloud.githubusercontent.com/assets/6912634/6272573/9e0da37c-b836-11e4-9dbf-acca88a70219.jpg)

so I end up getting the wrong ID in the callback from onMove. This seems like a bug to me but I'm not sure, since I am pretty new to this (hence the pictures and not the usual markup that most people use). Any time I move an item i get the wrong ID (just the first id in the dataset) from onMove. However the rest of the information that is returned is correct (including group, start, end, and content) when I move an item.

**Comment by SirNeuman** [comment]
umm I feel stupid... I did  "=" in the if statement instead of "==". Is there some way to delete an issue? You can delete this one if you want to/are able to.

**Comment by AlexDM0** [comment]
We've all been there :) no worries. 

Cheers!
