### ISSUE TITLE
Need cdn url for visjs

### ISSUE THREAD

**Issue by aravinds03** [almende/vis#650]
Hi,
I need cdn url for visjs.js file.

**Comment by aravinds03** [comment]
Got it.
It's //cdn.rawgit.com/almende/vis/master/dist/vis.js

**Comment by josdejong** [comment]
vis.js is available on http://cdnjs.com. This wasn't mentioned on the website of vis.js though sorry for that. I've added links on the website now: http://visjs.org/#download_install

**Comment by arulrajnet** [comment]
Here is the all version links in one place http://cdnjs.com/libraries/vis
