### ISSUE TITLE
dataManipulation toolbar buttons not touchable

### ISSUE THREAD

**Issue by mattsouth** [almende/vis#653]
The  buttons on the manipulation toolbar do not respond to touch events, see http://visjs.org/examples/network/21_data_manipulation.html for demo (on ipad and android). I can see onclick events bound to the buttons (e.g. lib/network/mixins/ManipulationMixin.js line 197) but no explicit touch handling.

**Comment by AlexDM0** [comment]
Hi Matt,

I've pushed a fix for this to the develop branch. Thanks for letting us know.

Regards,

Alex

**Comment by mattsouth** [comment]
Looks good to me, the buttons now work on touch screens.  The develop branch seems to have lost two useful behaviours though on adding an edge:
1. visible "partial edge" as you connect two nodes
2. unfreeze after edge is connected

**Comment by AlexDM0** [comment]
Hi Matt, 

Yes, these have been fixed. I'll push them to develop.

Cheers

**Comment by AlexDM0** [comment]
It's on develop now. 

Cheers

**Comment by mattsouth** [comment]
Yep that's done it.  

thanks Alex

**Comment by mattsouth** [comment]
Hi Alex, I noticed something else with the touch interface now, not sure if it needs a new issue or not.  It now takes two touches to place a node or an edge.  The first touch does nothing and the second places the node or starts the edge.

**Comment by AlexDM0** [comment]
Hi Matt,

I'll look into it. Is this only on touch devices or also on pc?

Regards,

Alex

**Comment by mattsouth** [comment]
Only on touch devices. I've seen this on an ipad (safari) and a windows tablet (chrome).

**Comment by AlexDM0** [comment]
Hi Matt,

I'll see what we can do. We're doing a full rewrite of the network with Hammer 2.0 and rechecking all the behaviour. I'm not sure if this will make it in the 3.x versioning but we'll see what we can do.

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi Matt,

This has been fixed in v4 which we just released today!

Regards,

Alex

**Comment by mattsouth** [comment]
Hey thanks for the heads up Alex.  Excellent news.  I only just checkd github earlier this week to see how you were getting on. I'll check it out.
  
 Matt
  
  
  

----------------------------------------
