### ISSUE TITLE
hammer dispose not found when using via npm and browserify

### ISSUE THREAD

**Issue by vasya10** [almende/vis#655]
Using vis 3.10.0 in a ReactJS project, installed via npm and using browserify.

var Vis = require('vis');
componentDidMount: function() {
var graph = new Vis.Network(this.getDOMNode(), {nodes: datasetNodes, edges: datasetEdges}, this.state.defaultOptions);
}

When the component is rendered, I get an error in browser's console:
Uncaught TypeError: undefined is not a function (in Network._bindHammer) when trying to call this.hammer.dispose(). When I put a debug at that point, I see the hammer object but no dispose() method. I can also see the dist/vis.js uses Hammer 1.1.3 and it appears to have the dispose() method. Still it doesnt seem to contain the reference to the method.

Anyone having the same issue?

**Comment by vasya10** [comment]
Update: I dont see this particular dispose() issue in a previous version (eg in 3.6.0 I can see the graphs being rendered), but I do see other problems with them (eg. if i click on the graph, I get an error "cannot read property center of undefined"). I tried all the way back to 3.2.0, and still see the center property issue.

**Comment by josdejong** [comment]
Hammer 1.1.x contains this `dispose` function ([see code](https://github.com/hammerjs/hammer.js/blob/1.1.x/hammer.js#L1408-L1430)). In hamme.js v2 this is renamed to `destroy`. 

Are you using hammerjs v1.1.x?

**Comment by vasya10** [comment]
I didnt include the hammer.js separately, just letting the vis.js use its own version, which is 1.1.3. Im wondering if its because of browserify (not sure how) or using within React is preventing some dom changes. Let me dig more.

**Comment by AlexDM0** [comment]
Is this issue still open?
