### ISSUE TITLE
HTML content for nodes

### ISSUE THREAD

**Issue by ignjat** [almende/vis#656]
It would be super useful if the contents of a node in network could be HTML. The workaround I use now is programmatically generated SVG but it doesn't work in Safari and it's not really optimal.

**Comment by AlexDM0** [comment]
Hi,

Since we use the canvas for drawing, we simply cannot use html without the SVG workaround as we have shown in our examples. 

I'm afraid there is nothing that can be done here. 

Regards,

Alex
