### ISSUE TITLE
Redraw network chart

### ISSUE THREAD

**Issue by milheiros** [almende/vis#658]
Hi,

I'm pretty new using vis.js framework. I don't now if this is the best place to put this question
I have a network graph that I need to update frequently with a different dataset. Basically, when I click in a node the graph must be redraw with a new dataset.

I've tried using the redraw() function but with no success. The best way I got is empty the container and made all calculations again and then, using: var network = new vis.Network(container, data, options);

I can't find in the internet examples or tips to do this using vis.js. Is there any simpler and better way to do this, using smooth transitions?

Thanks in advance,
Filipe

**Comment by AlexDM0** [comment]
Hi,

You can use the vis.Dataset to dynamically update the data in the Network. There are a few examples on the website: http://visjs.org/examples/network/16_dynamic_data.html

Regards,

Alex

**Comment by milheiros** [comment]
Thanks Alex,

But what I need is to redraw the chart using a new dataset (possibly with some nodes and edges that are equal to the first dataset). In your example, I need to remove and add all nodes and edges, one by one.

I'm looking for for something more direct. Something like this:
var visnodes = new vis.DataSet();
var visedges = new vis.DataSet();
// nodes and links are arrays with my first data
nodes.forEach(function (node) {
		visnodes.add([{
					id : node.index,
					label : node.name,
				}
			]);
	});

links.forEach(function (link) {
		visedges.add([{
					from : link.source,
					to : link.target
				}
			]);
	})

var data = {
		nodes : visnodes,
		edges : visedges,
	};
// First draw
var network = new vis.Network(container, data, options);

network.on('doubleClick', function (properties) {

                //My function to get new nodes and links
                configData(visnodes._data[properties.nodes].label);
                
               // How can I construct new data??

                //How can I call back again the network chart??
                var network = new vis.Network(container, data, options);
});


Regards,
Filipe

**Comment by AlexDM0** [comment]
Hi Filipe,

how about:

```
network.on('doubleClick', function (properties) {

                //My function to get new nodes and links
                configData(visnodes._data[properties.nodes].label); // assuming {nodes:nodesArray, edges:edgesArray}?

               // How can I construct new data??
               visnodes.clear();
               visedges.clear();

               visnodes.add(configData.nodes);
               visedges.add(configData.edges);

                //How can I call back again the network chart??
                // var network = new vis.Network(container, data, options); -- not needed
});

**Comment by milheiros** [comment]
Thanks Alex,

It works. With a couple of modifications but it works.
Thanks a lot!

Regards,
Filipe
