### ISSUE TITLE
Using vis.js with Hammer v2.x?

### ISSUE THREAD

**Issue by canweriotnow** [almende/vis#659]
I've been using vis.js successfully in a project for a while now and recently needed to introduce some other libs that depend on Hammer 2.0.x... As pointed out in #655 various fns have been renamed or modified between Hammer v2 and the old 1.x Hammer vis includes...

Is there a good way to either encapsulate the dependency to avoid conflict, or a branch working toward migration to a current version of Hammer?

**Comment by canweriotnow** [comment]
nm, just found the `hammerjs2` branch. :smiley_cat:

**Comment by AlexDM0** [comment]
Hi Jason,

That's a develop branch. It's not ready yet for release so we cannot guarantee any quality on that branch. Please keep that in mind :)

Regards,

Alex
