### ISSUE TITLE
Hierarchical Layout fails to render disconnected graph.

### ISSUE THREAD

**Issue by thraxst** [almende/vis#661]
I am using the hierarchical layout to for the initial layout of my graph, then I disable it and lock all the nodes in position and allow the user to drag the nodes around to modify the graph. I added the ability to reset the layout using the hierarchical layout to undo the user changes. This all works fine except if the user disconnects a node or set of nodes from the graph.

This only seems to happen with the "direction" layout which is the preferred layout method for my data.

Here is a quick example.
http://jsfiddle.net/uoq3knfx/

**Comment by AlexDM0** [comment]
Hi,

The hierarchical layout does not support an unconnected system. The physics are not made for this.

Regards,

Alex

**Comment by thraxst** [comment]
This seems inconsistent. The hierarchical layout appears to support disconnected graphs with the "hubsize" layout.

**Comment by AlexDM0** [comment]
I can see why that would be confusing. The reason here is because of the different way to determine the levels based on the geometry. The hubsize method does draw something but it is not officially supported that way. This will be added to future docs. I apologize for the confusion.

Regards,

Alex
