### ISSUE TITLE
Resetting of end time on event move

### ISSUE THREAD

**Issue by alishahm** [almende/vis#664]
When returning null via confirm() on moving items into the future, clicking the Cancel returns only the start time of item to the beginning, leaving the end time where it was moved to. Makes the event longer.

Can be replicated in http://visjs.org/examples/timeline/08_edit_items.html by moving Item 4 forward and clicking cancel on the confirm box.

**Comment by josdejong** [comment]
Thanks, this is fixed now on the development.
