### ISSUE TITLE
Timeline 'both' orientation?

### ISSUE THREAD

**Issue by MattyDub** [almende/vis#665]
On tall timelines, it would be useful to show the time axis both on the top and bottom. Is that possible?

**Comment by josdejong** [comment]
Yes, makes sense to add this as an option. 

Right now there it's possible via a relatively simple hack, see this jsbin: http://jsbin.com/tayugu/1/edit

**Comment by MattyDub** [comment]
Jos, that's a big help, thanks! This is good enough for me - if you'd like me to mark this closed, let me know.

**Comment by josdejong** [comment]
I've just added a new orientation option `'both'` to the `develop` branch.
