### ISSUE TITLE
How to increase spacing between timeline boxes

### ISSUE THREAD

**Issue by deepika087** [almende/vis#668]
I have a timeline- attached screenshot. Can you please tell how can I make these more align. Since the text is huge box tries to take dimension along the vertical axis rather than horizontal axis. Can you please help.
![capture](https://cloud.githubusercontent.com/assets/6492488/6388790/92c129d4-bdc3-11e4-9aeb-8a0851950cc7.PNG)

**Comment by AlexDM0** [comment]
Hi Deepika,

It looks like you're using a range type. These are defined by the start and end dates, and the box has to be in between. If you'd make it wider, you are actually disregarding what the range object is made for. If you want your items to act like what you draw, you can use a type that does not have a end date.

Regards,

Alex

**Comment by josdejong** [comment]
By default, the text content of range items does not wrap like in your screenshot, but overflows in a hidden way (and will be hidden) when it doesn't fit the box (see [14_group_performance.html](http://visjs.org/examples/timeline/14_group_performance.html)). Can it be that you altered the css here?

**Comment by deepika087** [comment]
Yes I changed the css such that overflow doesn't occur. So is there a way that I display complete text and somehow box get adjusted so that they are not elongated along vertical axis.

**Comment by deepika087** [comment]
@AlexDM0 yes true. the display is much better in case of range type. But I need to keep box. Because the information inside each timeline box is a person'e designation and company. and on x-axis the quantity is the time for which the person was  associated with a company

**Comment by deepika087** [comment]
I think that this issue can be resolved if somehow I can increase pixel used with in 2 year gap. Right now i have used scale of 2 years. Is there a way that the scale remains 2 years but the distance between say 2010 and 2012 can be increased from 20px to 40px ?

**Comment by AlexDM0** [comment]
Hi, 

I suppose I could mention the obvious and say: double the width of the timeline?

Regards,

Alex

**Comment by deepika087** [comment]
/yes that is what I want to do. But my question is which css element controls that ?

**Comment by josdejong** [comment]
The spacing between gridlines of the time axis are dynamically calculated, and currently not configurable. It's calculated in JavaScript such that the width is about 7 characters width, see code: https://github.com/almende/vis/blob/master/lib/timeline/component/TimeAxis.js#L187

**Comment by AlexDM0** [comment]
Is this not done with the width option? http://visjs.org/docs/timeline.html#Configuration_Options

Regards

**Comment by deepika087** [comment]
@AlexDM0 Width options increases the overall size of grid, not the spacing between the vertical lines. I thought the same too but then width increased the overall size of timeline div tag keeping the height same.

**Comment by deepika087** [comment]
@josdejong okie so any plans to make it configurable any time soon ?

**Comment by AlexDM0** [comment]
Hi Deepika,

I'm not exactly sure I know what you mean. From what I understand, you want to increase the width of a range object. This object is defined by the start and end date, thus you want to increase the amount of pixels between two date points.

There are two options: 
- either you zoom in, using more of the screen real estate for a certain start and end date, thus having more pixels
- you increase the total width of the timeline, keeping the start and end dates of the timeline the same, but increasing the total pixel count.

Is there any reason you cannot show the dates in between 2012 and 2014? Is this the issue here?

Regards,

Alex

**Comment by deepika087** [comment]
@AlexDM0 
Yes you are right, I want to increase spacing between two consecutive years. Say in the screenshot attached above, 2007 and 2008.
second, I cann't increase the entire timeline's width because this timeline's div will be part of other div tags in the page and I can provide only this much space for the timeline. However, I was hoping if somehow I can increase size between two consecutive years/steps.So that users can drag the timeline to see various designations held by person till present day, keeping the overall width of timeline same

Makes sense now ?

**Comment by AlexDM0** [comment]
Not really. Where would this space come from? From what I understand, all we can do here is zoom in. Is there any reason that is not acceptable?

Regards,

Alex

**Comment by theromulanz** [comment]
Maybe range overflow can help.
http://visjs.org/examples/timeline/items/rangeOverflowItem.html

Otherwise, as mentioned, set zoom levels:
var options = {
    zoomMin: 1000 * 60 * 60 * 24,             // one day in milliseconds
    zoomMax: 1000 * 60 * 60 * 24 * 31 * 3     // about three months in milliseconds
  };

**Comment by mojoaxel** [comment]
@deepika087 Is this still an issue? If not can you please close this. Thanks!
