### ISSUE TITLE
Hover text in v3.10.0 of vis.js

### ISSUE THREAD

**Issue by GeoffThorpeFT** [almende/vis#669]
I'm not seeing any hover text now I have upgraded to v3.10

**Comment by GeoffThorpeFT** [comment]
v3.9 does work - but has the issue with the hover points moving after a scroll.
I have been using the network graphing option.

**Comment by AlexDM0** [comment]
Hi,

Could you post a jsBin to show this issue? I'll assume you refer to the pop-ups. Have you also updated the css to 3.10? There has been a change there so the css of 3.9 will not work with 3.10.

Regards,

Alex

**Comment by GeoffThorpeFT** [comment]
Looks like it was the css issue. Thanks.
