### ISSUE TITLE
Using DataView with network update issue

### ISSUE THREAD

**Issue by jmzucco** [almende/vis#670]
I use a DataView as input data for a network (version 3.10.0). I found it convenient to filter the orginal Dataset to hide/show distinct nodes by using a node's attribute like 'visible : boolean' in filtering function.
During update, I found a problem in `DataView.prototype._onEvent`, on updated this function does not pass params to listeners.
```      
if (updated.length) {
        this._trigger('update', {items: updated }, senderId);
      }
```
I change the trigger to add original data of updates, and it seems fine.
```      
if (updated.length) {
        this._trigger('update', {items: updated, data: params.data }, senderId);
      }
```

Hope it serves.

**Comment by josdejong** [comment]
I'm not sure how you want to put this issue, is it a bug report or meant to suggest an improvement?

**Comment by josdejong** [comment]
Ah I see the problem, this is indeed a bug

**Comment by josdejong** [comment]
This is fixed now in the develop branch, though the files in `/dist` aren't yet updated
