### ISSUE TITLE
How to set default zoom level

### ISSUE THREAD

**Issue by anik786** [almende/vis#671]
I'm creating a simple 2d line graph using vis and would like to know how to set the default zoom option. This is because I am using the time axis scale as 'seconds' and all the labels seems squashed unless you zoom in. Unfortunately I could not find a zoom method or option to change this. Only zoomMax and zoomMin.

Please Help!

http://visjs.org/docs/graph2d.html#graph2dOptions

**Comment by josdejong** [comment]
You can use options `start` and `end` to set the initial window, and use `zoomMax` and `zoomMin` to limit how far you can zoom in/out. You can adjust the visible window later on using `setWindow(start, end)`.

**Comment by anik786** [comment]
The issue is that I don't mind how much the user zooms in or out. I just want to set the default zoom level. Thats all. Hence, the zoomMax and zoomMin does not help me. I could set a zoomMin or zoomMax, but that then means the user can not zoom further than those boundaries.

**Comment by AlexDM0** [comment]
Hi, 

In that case, as Jos said, use the start and end options. 

Regards

**Comment by anik786** [comment]
Got it Thanks!

**Comment by ugurozturk** [comment]
(Timeline) Anyone if looking for this. i made good solution by using "moment js"

// Create a Timeline
var timeline = new vis.Timeline(container, items, options);
timeline.setWindow(moment().subtract(5, 'minutes'), moment().add(5, 'minutes'));

**Comment by mistryhiren94** [comment]
thanks @ugurozturk
