### ISSUE TITLE
network with multiple parent vertical edge problem 

### ISSUE THREAD

**Issue by mmotamimi** [almende/vis#672]
i'm using this library for my graduation project
but one small problem i'm facing when a node have 2 parents and using the hierarchical Layout like the following example 
nodes = [
		{id: 1, label: 'Node 1'},
		{id: 2, label: 'Node 2'},
		{id: 3, label: 'Node 3'},
		{id: 4, label: 'Node 4'}
      ];
      edges = [{from:1, to :3},
				{from:1, to :2},
				{from:1, to :4},
				{from:3, to :4}
      ];

the result will be as follows in level 2

(node 3) === (node 2) ===>(node 4) 
and the edge from node 3 to node 4 will pass behind node 2 which is my problem
is there a way to lower the level of node 4?

**Comment by mmotamimi** [comment]
i just knew that if i put attribute "level" to the nodes that give the node the level
but, can i do something like " if ( ###) {node.level = calculated level +1}"??

**Comment by AlexDM0** [comment]
Hi,

This is not possible. If you'd like to have the node 4 on another level, you'd have to write your own levelling algorithm and supply the nodes with level information to the network.

Regards,

Alex

**Comment by mmotamimi** [comment]
ok
thank you
