### ISSUE TITLE
Manipulation bar hides nodes

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#674]
Hi guys,

calling zoom extend (or pressing the zoom extend button) the nodes are zoomed to fit the canvas however the manipulation div often hides the nodes at the top. When the manipulation bar is enabled per default, this is not so pretty.

http://jsbin.com/xegeyu/1/

![selection_511](https://cloud.githubusercontent.com/assets/4307137/6438330/494332cc-c0c8-11e4-99d4-c06fd5bdae99.png)

 Any ideas? If this cannot be fixed on vis' site, I would try to fix this with some css somehow...

Thanks
-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

we could set the transparency of the manipulation bar or you could shift it up so it does not overlap with the network.

Also, you should try to match the vis.css version with the dist version of vis. There can be changes in the css that a new dist version depend on.

We do take some margins for the zoomExtent but these cannot be customized at the moment.

Regards,

Alex

**Comment by felixhayashi** [comment]
Hi @AlexDM0,

thanks for your suggestions

> we could set the transparency of the manipulation bar

I used to do that and this is how I actually discovered https://github.com/almende/vis/issues/557 :) So it would irritate the user if he/she couldn't click/drag a node since the click does not get through the invisible bar.

> Also, you should try to match the vis.css version with the dist version of vis. 

I tried that with a github raw url but it didn't work. Do you have a server where you automatically upload the dist css and keep it up to date so it is easier to create bins that reference the correct css?

> We do take some margins for the zoomExtent but these cannot be customized at the moment.

Ok, I understand that.

> or you could shift it up so it does not overlap with the network.

Yes, this is what I wanted to do next using `position: relative` and moving the bar up a bit. Just thought I bring this topic up before doing some css tricks since this problem affects everybody using a manipulation div per default. Maybe there is a good native vis solution at some point in the future...

-Felix

**Comment by AlexDM0** [comment]
Hi Felix, 

I always use the http://www.visjs.org/dist/vis.js, but there is a CDN listen on the website http://visjs.org/

I think it would be a good idea for us to move the manipulation bar up on top of the canvas in general but we'd have to handle the edge cases where the canvas is fullscreen etc. maybe we should subtract the height of the toolbar from the canvas but that would appear jumpy when enabled. 

Is this issue only really an issue for the zoomExtent? We could also look into handling the case there.

Regards,

Alex

**Comment by felixhayashi** [comment]
Hi Alex,

> I always use the http://www.visjs.org/dist/vis.js, but there is a CDN listen on the website http://visjs.org/

Good to know.

> I think it would be a good idea for us to move the manipulation bar up on top of the canvas in general but we'd have to handle the edge cases where the canvas is fullscreen etc.

Ah, I see the problem.

> maybe we should subtract the height of the toolbar from the canvas but that would appear jumpy when enabled. 

I agree, I like the way the bar currently collapses and extends. It's very seamless. I personally wouldn't mind the jumpiness though but I understand the problem. In any case it is important for the vis api user that the height of the container stays predictable and does not change during runtime.

> We do take some margins for the zoomExtent but these cannot be customized at the moment.

Yes, instead of changing the height of the canvas it would be great to make the zoomExtent recognize a (user) defined margin (left,right,top, bottom) that is acknowledged by zoomExtent. Then when the manipulation bar is extended, vis could fire an event and the user/vis could change the zoomExtent-margin and perform the zoom with a nice easing so it still looks smooth. But I understand it is not possible now...

> Is this issue only really an issue for the zoomExtent? We could also look into handling the case there.

Imo yes. Because when the graph is automatically positioned (via zoomExtent during initialization or when calling the function or button press) then the user expects the graph to be visible as a whole (at least at the beginning, if nodes float away into a non-visible area, it is fine). In any other case, it is acceptable if the graph is partly hidden: e.g. if the user dragged the network or moved the node by him/herself then he/she is well aware that nodes will be hidden, just like when reaching the end of the canvas.

Regards
Felix

**Comment by AlexDM0** [comment]
How's this for a solution: http://jsbin.com/guyiheluzo/1/edit?html,output

Regards

**Comment by felixhayashi** [comment]
Hi @AlexDM0,

> How's this for a solution: http://jsbin.com/guyiheluzo/1/edit?html,output

Wow, I never thought of semi-transparent as a solution. Really clever. While I still think zoomExtent should produce a result that makes it possible to select all nodes, I think this is a great compromise for now. Thanks!

-Felix
