### ISSUE TITLE
empty timeline

### ISSUE THREAD

**Issue by DivyashreeMS** [almende/vis#675]
Hi Alex and josdejong,

Firstly I would like to thank that Vis.org is a great library,
Looks silly but I am now not able to handle the empty timeLine
 That is what if items is empty
  items = new vis.DataSet([]); 
the screen looks wierd

![emptyscreen](https://cloud.githubusercontent.com/assets/10521928/6443616/ec3e2ad4-c0c5-11e4-9761-bbf587ec86d8.jpg)

But I am expecting something which showcase the below screen with no time bar

![toshowemptytimeline](https://cloud.githubusercontent.com/assets/10521928/6443619/f2ff0712-c0c5-11e4-9311-e75873081d64.jpg)

Highly appreciate  your help!!

Thanks & Regards
Divya

**Comment by josdejong** [comment]
You can set an initial window by providing configuration options `start` and `end` (or apply via `setWindow(start, end)`.

Looking at your first screenshot, it looks like you've fixed the scale of the timeline, that would explain the large amount of grid lines.

**Comment by DivyashreeMS** [comment]
Hi josdejong,

Thank you for the quick reply. Its working fine after providing configuration options start and end.
