### ISSUE TITLE
Dates on time axis

### ISSUE THREAD

**Issue by jrviz** [almende/vis#677]
(Vis.js 3.10) 
I have a timeline with all the item dates declared using the  new Date(.... format.

The timeline date axis shows the dates incorrectly as exactly one month ahead of the specified dates.

The same behaviour can be seen in the examples using the same form of date declaration e.g. 08_edit_items.html. In this example dates are declared as being in March but the timeline shows April.

**Comment by josdejong** [comment]
The months of JavaScript's Date object are zero based...

http://www.w3schools.com/jsref/jsref_getmonth.asp
