### ISSUE TITLE
Network Graph node positioning

### ISSUE THREAD

**Issue by vijaytv** [almende/vis#679]
I have a requirement to display hundreds of nodes  with multiple edges connected across different nodes similar to the world cup example. I noticed that the world cup example has the x and y values set.  I want to know if it's possible to render the network graph and then  drag and drop the nodes to the desired positions and then   read the x and y values using the getpositions / storepositions methods.  Note that my requirement is to display  network topology map for intranet network traffic along with the traffic between nodes as edges color coded based on the ports they communicate through.  

Is there a way to drag and drop nodes and read x,y positions?

Thanks,
VJ

**Comment by vijaytv** [comment]
I think I figured this out by setting the physics settings to zero and then dragging the nodes and then read the x and y positions of the nodes using the getpositions method.

**Comment by AlexDM0** [comment]
Hi,

You could also use the dataset and call storePositions once you have everything the way you want it. 

Alternatively, maybe some physics setup could do the work for you :)

Regards
