### ISSUE TITLE
Question about changing padding values dynamically

### ISSUE THREAD

**Issue by jrviz** [almende/vis#680]
i have a timeline where I need to change the item padding value while it is running. I can use the set options method but also need to change the matching CSS value but I can't see how to address the element in JavaScript. How would I do that?

Apologies if this is a really simple question but I am new to JavaScript.

**Comment by josdejong** [comment]
Changing css stylesheets on the fly is not so trivial. Have a look here: 

http://davidwalsh.name/add-rules-stylesheets
http://www.quirksmode.org/dom/changess.html

**Comment by mojoaxel** [comment]
@jrviz Is this still an issue? If not can you please close this. Thanks!
