### ISSUE TITLE
HiDpi Support

### ISSUE THREAD

**Issue by JesseLivingston1** [almende/vis#682]
Hi all,

After the latest release, I am unable to get the network graph to display on a HiDPI device (220 PPI or higher). No errors. The network graph simply doesn't display. When I change the resolution to a normal PPI (127 or so) and refresh the page, it displays fine. I tested this on multiple HiDPI devices and found the issue consistent. Note - this is not on issue in Firefox. I have only noticed it in Chrome and Safari.

I also tested this by connecting an external monitor (with a standard DPI) to my laptop. When I loaded the network graph with the browser window on my laptop (HiDPI), it did not display. After dragging the browser onto the external monitor and refreshing the page, it displayed fine. 

Thanks,

Jesse

**Comment by AlexDM0** [comment]
Hi Jesse,

Could you test something for me? Can you call te zoomExtent method on the highDPI screen that does not render anything? Please let me know what happens. 

Regards,

Alex

**Comment by JesseLivingston1** [comment]
Hi Alex,

Thanks for the quick response. Nothing happens after I call the zoomExtent method. The graph still doesn't display. 

Thanks,

Jesse

**Comment by AlexDM0** [comment]
Aw that's a shame. I encountered a problem there during the huge refactor to 4.0 today.

I'll take a look tomorrow.

Cheers

**Comment by JesseLivingston1** [comment]
Ah OK. Great. Thanks for your help, Alex!

Jesse

**Comment by AlexDM0** [comment]
Hi Jesse,

I have tested this with my phone (iPhone 5) which has a high DPI screen but it seems to work fine. How do I reproduce this? Is there a specific example on the vis site that does not work?

Regards,

Alex

**Comment by JesseLivingston1** [comment]
Hi Alex,

Let me get back to you soon on this. None of the vis examples on the website give me issues. It's only with our app. It's not a public site so I can't give a link, but let me see what I can come up with.

Thanks,

Jesse

**Comment by AlexDM0** [comment]
Hi Jesse,

Any news on this?

Regards,

Alex

**Comment by JesseLivingston1** [comment]
Hi Alex,

Sorry for the delay. We are working on getting you a temporary username and
password to have access to an online demo version of our web app. We should
have that for you soon. Thanks again!

Jesse

**Comment by AlexDM0** [comment]
Hi Jesse,

I'm not really here to debug your code for you... If you cannot reproduce it in a simple JSbin and if all our examples work fine, it does not sound like it's a fault in the vis library. I can take a look but if it's not clear immediately, I will not be running over miles of custom code.

Regards,

Alex

**Comment by JesseLivingston1** [comment]
Hi Alex,

Understood. We don't really need you to look through our code. We just want
you to see what happens on the interface on a HiDPI monitor.

Thanks, and I'll be in touch,

Jesse

**Comment by JesseLivingston1** [comment]
Hi Alex,

Fixed the issue. There was some layout issues on our end. Once fixed, the network graph displayed no problem.

Thanks,

Jesse

**Comment by AlexDM0** [comment]
Good to hear :) have fun using vis!

**Comment by JesseLivingston1** [comment]
Thank you Alex!
