### ISSUE TITLE
Alignment for range content off.

### ISSUE THREAD

**Issue by SirNeuman** [almende/vis#683]
Hi,
I'm having a problem with the alignment of content inside range items in my timeline. 
I originally had my items align to default, which is dynamic, however the content kept sliding out of the range item when it scrolled to the left, off the screen. So I changed the alignment to center, and then it looked like everything was aligned to the right. See following:
![screen shot 2015-03-03 at 5 14 09 pm](https://cloud.githubusercontent.com/assets/6912634/6473666/d1f64874-c1c8-11e4-832b-8bc628875ff0.jpg)
Then i tried align left, and it looked the way i wanted with align center: 
![screen shot 2015-03-03 at 5 17 40 pm](https://cloud.githubusercontent.com/assets/6912634/6473729/4156fccc-c1c9-11e4-8591-f6bf0f05278f.jpg)
However, as the range went off to the left the content would disappear (rather than stay in place and remain visible like I wanted/expected): 
![screen shot 2015-03-03 at 5 19 23 pm](https://cloud.githubusercontent.com/assets/6912634/6473764/7e114fb4-c1c9-11e4-9e3d-cde3c237e41b.jpg)
I then realized that if i zoomed out enough, what was really happening was that the content wasn't disappearing, but rather it was moving to the left when the range item reached the end of the page.
Here's the timeline zoomed out:
![screen shot 2015-03-03 at 5 21 59 pm](https://cloud.githubusercontent.com/assets/6912634/6473813/d51ebc92-c1c9-11e4-98ff-dc53cbd83514.jpg)
and here's the timeline moved over by just a little bit:
![screen shot 2015-03-03 at 5 22 41 pm](https://cloud.githubusercontent.com/assets/6912634/6473830/f0c90916-c1c9-11e4-9407-cbb110cdb58f.jpg)
Notice the leftmost item in the timeline. Do you know what would/could be causing these alignment issues? Also, something I might as well note. When I had it set to dynamic it would be aligned to the center of the range item, and then move to the right when the range item scrolled out of the timeline. It should have been positioned to the left according to the docs however, which probably means that dynamic would work for me (and most likely be ideal) if was properly aligned to the left and not to the center.

**Comment by josdejong** [comment]
The `align` option itself seems to work fine: http://jsbin.com/hoxora/5/edit

Something like this could be caused when accidentally overriding some css styles used by the Timeline items.

**Comment by SirNeuman** [comment]
ahh yes. I put a "text-align:center;" in the wrapper for the entire page, which was causing the issue. I would have assumed that the vis stylesheet would have overridden the page wrapper's text-align but I guess not.
