### ISSUE TITLE
Timeline: start/end options as long?

### ISSUE THREAD

**Issue by czellweg** [almende/vis#684]
Hey guys,

Thanks so much for your awesome work - it's been a pleasure to use vis.js in our project.

We have a question regarding the type of the ```start```/```end``` options which now has to be of type ```Date```. In our use case, we simply have a ```long``` value that we need to have displayed, i.e. the mapping onto the timeline would simply be a number and not necessarily a date.

We understand that it might be a bit counter-intuitive and possibly not what you intend to achieve with a 'timeline' (hence the name ;)). We are still curious though if something like that could be achieved relatively easy?

**Comment by josdejong** [comment]
hm, I see the docs are not accurate at this point. 

The `start` and `end` of items can be a Date, number, ISOString, or Moment. Same with configuration options.

I've update the docs.

**Comment by josdejong** [comment]
o wait, I thought you meant using numeric unix timestamps instead of Dates. 

Well, yes, it's a Timeline. We don't have plans our selves to create a horizontal axis with numbers instead of dates. It could be done but will be a lot of work.

**Comment by czellweg** [comment]
Hey, thanks for your quick answer.
I see, well, we'll have to work around that limitation then.

Thanks again!
