### ISSUE TITLE
Displaying additional data upon selection of a node or an edge

### ISSUE THREAD

**Issue by funpluscharity** [almende/vis#689]
I couldn't find a forum or discussion group link on vis.js so posting it here.

I couldn't find a way to show additional data (key/value pairs specific to my domain) for a node or an edge. I went through the documentation http://visjs.org/docs/network.html and the demos as well. How do you suggest we display addition information upon selection?

Regards.

**Comment by josdejong** [comment]
Do you mean like listening for the select event? On selection, you get a trigger which you can use to do whatever you like, for example display extra information on the selected node in a side bar or something.

**Comment by AlexDM0** [comment]
There is an example called importing from gephi that shows additional information on nodes. 

You can add whatever fields you want to the nodes or edges as long as they don't conflict with the ones used by the network. On select you could ask the dataset to provide you with the node and read out the fields. Or without datasets, just match the ID of the select event to the node from your data. 

Cheers

**Comment by funpluscharity** [comment]
Thank you @josdejong and @AlexDM0. I will this and update you the status

**Comment by funpluscharity** [comment]
@josdejong  @AlexDM0  I am able to retrieve the additional info now. Thank you.
