### ISSUE TITLE
Zoom in and Zoom out in canvas image

### ISSUE THREAD

**Issue by nitin0708** [almende/vis#690]
Hi Alex,

Can we add zoom in and zoom out button in canvas image of vis js?

Thanks,

Nitin

**Comment by AlexDM0** [comment]
> Hi,

You can do this with the animation methods. Take a look at http://visjs.org/examples/network/33_animation.html

Regards,

Alex

**Comment by nitin0708** [comment]
Hi Alex,
can we replace the zoom event from mouse wheel to click event if we use two button for zoom in and zoom out?

Thanks,
Nitin

**Comment by AlexDM0** [comment]
Hi,

Just listen to the click event and trigger a zoom animation. I'm not sure what you mean by "we use two button for zoom in and zoom out?"?

Regards

**Comment by nitin0708** [comment]
Hi Alex,

Can we add like this-
(https://cloud.githubusercontent.com/assets/10219173/6500670/bfcc4230-c334-11e4-8f2b-c714f9e3088b.png)

Thanks
Nitin

**Comment by AlexDM0** [comment]
> Like this?

http://visjs.org/examples/network/20_navigation.html

**Comment by nitin0708** [comment]
Hi,

Yes but in this case button is not working.

Thanks,
Nitin

**Comment by AlexDM0** [comment]
> Hi,

The icons in the network are working here. What does not work? You can move them around and style them using css. 

Regards

**Comment by nitin0708** [comment]
Hi Alex,

Awesome its working...it was need to add navigation:true and images in application. thanks a lot..

Thanks,
Nitin

**Comment by AlexDM0** [comment]
Great to hear it's working! Make sure to check the examples and docs first if you have any more questions :)

Cheers!
