### ISSUE TITLE
Question about side effects of using timeline top orientation

### ISSUE THREAD

**Issue by brichbe** [almende/vis#691]
Using today's new 3.11.0 build I wanted to try using the new timeline orientation option 'both', so the user can dynamically choose between top, bottom, and both.  Using 'both' works well as expected, but the 'top' orientation is the one I have a question and/or issue with.

It seems that the layout of items is tied to which time axis orientation is being used.  For example, I have background items that span across all groups (similar to 31_background_areas_with_groups).  Using either 'bottom' or 'both' orientation, the content label for these items is located in the top-left area where I want it.  But for the 'top' orientation, the background item's content label is moved to the bottom-left away from the time axis, which was an unexpected side-effect to me.  Top orientation also has the unfortunate side effect of reversing the top-to-bottom ordering of my subgroups.

Is this the intended behavior?  I do understand this may be intentional for cases such as box items, in which case you don't want the background item's content to conflict with a box item's line connecting upwards to the time axis.

So if this behavior is intentional, I'm curious if this could be made an option?  I'm probably not the only one who'd prefer that the positioning of items and their content within the timeline be de-coupled from the time axis orientation, such that changing the orientation does not affect the layout of all the internal components in the timeline.  If doing so would require major changes, I don't mind giving my user only the 'bottom' and 'both' options to avoid this issue, but I'd recommend at a minimum you consider supplementing the documentation for using 'top' orientation to explain this side effect so others don't stumble on the same question in the future.

**Comment by josdejong** [comment]
Right now, the orientation of the items is coupled with the orientation of the axis. With this new orientation option `both`, the need to separate these two has become more urgent. 

We could extend the current `orientation` option such that you can either specify the orientation for either of the two:

```js
var options = {
  // a string, applies orientation to both axis and items
  orientation: 'top' | 'bottom' | 'both'

  // an object, specify separately for either axis or items
  orientation: {
    axis:  'top' | 'bottom' | 'both',
    items: 'top' | 'bottom'
  }
}
```

Does that make sense?

**Comment by brichbe** [comment]
Yes, I like your suggestion here - it gives the most flexibility.  Should subgroups also allow specifying 'top' or 'bottom' orientation like items?  Or were you thinking subgroup orientation is determined by the orientation of items?

**Comment by josdejong** [comment]
I was thinking about a single configuration for *all* items in a Timeline, not per group or subgroup. I'm not sure there would be need for that.

**Comment by josdejong** [comment]
This is now implemented in the `develop` branch. You can specify:

```
  orientation: {
    axis: 'top' | 'bottom' | 'both',
    item: 'top' | 'bottom'
  }
```

**Comment by brichbe** [comment]
This new orientation control works as expected and resolves this issue for me -- I can dynamically change the time axis without affecting the layout of items.  :+1:
