### ISSUE TITLE
Nodes gravitate together after moving and setting coordinates

### ISSUE THREAD

**Issue by no1youknowz** [almende/vis#692]
Hi,

I want to be able to move nodes to a particular set of (x,y) coordinates and for it to stay there.  This is particularly useful for me, when I have many nodes under a parent node and want to arrange them.

Here is a js fiddle, with 2 nodes not connected.  I'm retrieving the coords after drag end and setting it to the node, but if you do move it a few times, the functionality seems to go away and they end up drifting back together.

http://jsfiddle.net/bczgxe9c/

What do I need to do, so that when I move a node.  It stays put! :)

Thanks

**Comment by no1youknowz** [comment]
I achieved the desired result by amending xFixed for the nodes.

Now I can place them on any coordinate I wish and they don't gravitate back.

Network.prototype._handleDragStart...

Line: 16899

    var s = {
            id: object.id,
            node: object,

            // store original x, y, xFixed and yFixed, make the node temporarily Fixed
            x: object.x,
            y: object.y,
            xFixed: false, //object.xFixed,
            yFixed: false //object.yFixed
          };

Network.prototype._handleDragEnd...

Line: 17008

    selection.forEach(function (s) {
        // restore original xFixed and yFixed
        s.node.xFixed = true; //s.xFixed;
        s.node.yFixed = true; //s.yFixed;
      });

**Comment by josdejong** [comment]
Does this mean that your issue is resolved?

**Comment by AlexDM0** [comment]
I think you could just disable the physics and it will do what you want. Also you can use the dataset to set an x and y position for a node. 

Regards

**Comment by no1youknowz** [comment]
Yes, this issue is now closed.  I will close it.
