### ISSUE TITLE
Disabling zoom using mouse in network diagram

### ISSUE THREAD

**Issue by ramdyne** [almende/vis#693]
Hi,

Is there a way to disable zoom with the scroll "wheel" when the pointer is over a network graph? In our website it appears that when going to the page containing the diagram the mousepointer has a large chance of being over the diagram. When wanting to scroll the page, the user instead zooms the diagram. 

-- 
Andreas

**Comment by josdejong** [comment]
Hi, check out the docs: http://visjs.org/docs/network.html and search for the terms "zoomable" and "clickToUse".

**Comment by ramdyne** [comment]
How did I miss that? I've been looking for something like zoomable for ages last week. Thanks!

-- 
Andreas

**Comment by josdejong** [comment]
you're welcome :D

**Comment by pheraph** [comment]
Helped me, too. :-)

**Comment by LegoStormtroopr** [comment]
As of 2017 the correct page is - http://visjs.org/docs/network/interaction.html
