### ISSUE TITLE
Internet Explorer Intranet Zone - Issue

### ISSUE THREAD

**Issue by uwi77** [almende/vis#694]
I've done some testings with vis.js within an Intranet Zone.
When I remove the Website (which integrated vis.js) from Internet Explorers Intranet Sites then it works and can fully load vis.js.

Within the Intranet Zone it gives me the following errors:

SCRIPT438: Object doesn't support property or method 'create'
File: vis.js, Line: 12472, Column: 3

SCRIPT5009: 'vis' is undefined
File: Test.html, Line: 80, Column: 7

Is there anything special why it does not work within the local intranet sites?

Best wishes
Urs

**Comment by josdejong** [comment]
This error means that your browser doesn't know the method `Object.create`, which is supported by IE9 and newer. So it looks like you are running on an old version of Internet Explorer (IE8 or older), or run your browser in an old compatibility mode or something like that.

**Comment by uwi77** [comment]
Whow, thanks for the very quick answer.
I'm tested it on IE9 and IE11, so it is supporting Object.create.

I'll check the compatibility mode settings.

Thank you very much

**Comment by uwi77** [comment]
Yes, you knew it!!!!
Tickbox "compatibility view" for intranet site was by default ticked.

Happy Weekend
