### ISSUE TITLE
Network: get node programatically and change it's meta

### ISSUE THREAD

**Issue by no1youknowz** [almende/vis#697]
Hey,

So spending a few days with this, I just want to say THANK YOU for putting this together.

It's exactly what I need and also, the code.  It's so organised and readable!  If I dont see something I need, then I add it myself.  Amazing, great job!

I'd love to see the ability to select nodes programmatically and then change them outside of the current dynamic data you have provided.  I like having my own methods and as close to the api as possible.

For now, I added another method to network.

    Network.prototype.spring_back = function(dnode) {
        var selection = this.drag.selection;
        selection.forEach(function (s) {
            // restore original xFixed and yFixed
            s.node.x = dnode.x; //s.xFixed;
            s.node.y = dnode.y; //s.yFixed;
          });
      }

Essentially what I have hacked together, is a drag and drop ability to create edges.  You drag one node ontop of another and bam the edge is there.  So then I wanted the dragged node to move back to its original position.

So in a round-about way.  If the ability to select a specific node and then change it's meta, like x.y, image, whatever on the fly.  Would be really great.

Seriously, thanks for this.  It's definitely done what I needed!

Thanks

**Comment by josdejong** [comment]
Thanks, good to hear that it's working out nicely :). 

There is no API right now to adjust the nodes properties directly, so you will need to do some hacking here too: before dragging read the internal x, y from a node like `network.nodes[id].x`, and after the drop overwrite the x, y of the node. This is no "official" way though so in the future this may break.

We are working a large refactoring for the Network, to enable you to work "closer to the metal", make it easier to hook into the Network API and extend it to your own needs. You can check out the [`v4`](https://github.com/almende/vis/tree/v4) branch already but please note that this branch is not stable.

**Comment by no1youknowz** [comment]
Good news on version 4.  I will definitely be looking out for it when it's released.

I don't mind if things break after an upgrade.  I've only done minor changes so far and made notes.

Thanks
