### ISSUE TITLE
Timeline Enhancement request for items to span groups

### ISSUE THREAD

**Issue by jrviz** [almende/vis#698]
Is it possible to declare (range) items with no subgroup to span the whole height  of a group in the same way that backgrounds can span a group? I am trying to achieve the effect shown in the picture (where I have used backgrounds). If it were possible to have  range item with a group (but no subgroup, e..g task 15 in the picture) that would help as I would have a regular item that I could process events on in the normal way.

alternatively, events triggered (and hover) on background items!

![image](https://cloud.githubusercontent.com/assets/11279475/6546900/b501f120-c5bd-11e4-8542-e8f5d39cecd5.png)

**Comment by josdejong** [comment]
Is the problem here that background items do not fire events? Or do you need a special type of item with 100% height?

What comes closest to your 100% items is applying options `{margin: 0}` and some css like
`.vis.timeline .item.range.mySpecialItem {height: 100%}`, but I doubt if that is what you mean. 

Can you explain what the idea of these 100% height items is? Why do the need to be displayed like this and not as a regular item?

**Comment by jrviz** [comment]
The reason for displaying like this is just that is what people who will use this item are used to – previous practice on what was a manual timeline. Easy to see where single vs parallel activity taking place.

 

Would I give the items a class of mySpecialtem with your example?

 

Of course, the new click event in 3.11 helps me with the click activities. I just wanted to see if there was sense in having a “spanning (optional?)” task for items with no subgroup, or “subgroup all”.

**Comment by jrviz** [comment]
I have tried similar css settings before (and the css above) . What happens, after the timeline has been zoomed in and out a few times, is that successive redraws make the total group height grow in size so it gets bigger and bigger with "empty" subgroup lanes. In some way this sort of change seems to upset the height calculations.

For example, with the css above, the results after a few timeline zoom in and outs:

![image](https://cloud.githubusercontent.com/assets/11279475/6560344/4b9440f2-c681-11e4-9154-5f1b841cd589.png)

**Comment by josdejong** [comment]
> Easy to see where single vs parallel activity taking place.

That makes sense: having an item span multiple subgroups. 

The Timeline currently doesn't provide support for this, so the only option right now is to make something that sort of mimics it. The 100% height css is indeed tricky. How about giving the parallel tasks a fixed height of like 4 times higher than regular tasks? Something like:

```css
.vis.timeline .item.range.parallelActivity {
  height: 70px;
}
```

**Comment by jrviz** [comment]
I can have a look at that. In the interim (maybe while waiting for a spanning item in the future!) using backgrounds would work for me if the click event could return an Id from the (background) item, which it does not do right now. Is that possible?

**Comment by josdejong** [comment]
Getting events from background items is not possible right now, sorry. 

There is a new event handler `click` which may be of help here. You can use it see where the user clicked and get additional info (like x,y, time, where, etc), see docs: http://visjs.org/docs/timeline.html#Events. The click event also doesn't recognize whether clicked on a background item, but you could deduce this by looping over all your background items and check whether the clicked `time` is between the items `start` and `end`.

**Comment by jrviz** [comment]
The click handler does recognise a click on a background item (in the what field) but not a item Id. Normal items return an item type in the what field and an item Id. Is there no way to populate an Id for the background in the click object?

**Comment by josdejong** [comment]
Unfortunately it doesn't, the what field says `'background'` when you click an empty space, no matter if there is a background item or not.

Background Items are displayed in a background layer, regular items in a foreground layer. The foreground layer overlays catches the events, and is not aware of this background layer. So there is no easy way to detect whether clicked on a background item, but it would be nice if this works.

**Comment by AlexDM0** [comment]
I suppose you could match the time and group you get to your dataset?

**Comment by josdejong** [comment]
> I suppose you could match the time and group you get to your dataset?

Yes, I explained that the [comment before](https://github.com/almende/vis/issues/698#issuecomment-78047733) :)

**Comment by AlexDM0** [comment]
Right :) missed that one.

**Comment by josdejong** [comment]
here is an example: http://jsbin.com/dapade/15/edit

**Comment by jrviz** [comment]
This is really helpful. You can see in my picture above I have used backgrounds to create spanning item tasks across multiple groups. To target the click selection properly I have added "&& item.group === props.group" to the filter function returning matches from your example. Does that make sense?

**Comment by josdejong** [comment]
Yes that's indeed required to distinguish background items in the right group.

**Comment by jrviz** [comment]
The object returned by the click event on a background item can return the incorrect group. For a large timeline where the window has been scrolled down (no height or max height options) I get a null or group number towards the top of the timeline returned. It looks like the group is being evaluated from the window coordinates  rather than the whole div

**Comment by josdejong** [comment]
Thanks. This has probably the same cause as https://github.com/almende/vis/pull/708

**Comment by jrviz** [comment]
Yes, that makes sense. The PageY value in the object seems to be correct just the group evaluation is incorrect

**Comment by josdejong** [comment]
Is this still an issue or can we close it?

**Comment by jrviz** [comment]
I got what I needed by having a background event and matching the click
event to the group and time position.  It would be nice to have items which
span a group but I have a solution for the moment even though it uses a
background for this specific "span" item.

**Comment by josdejong** [comment]
Ok thanks. I think this is something we can have a look at when reworking and extending the group/subgroup functionality
