### ISSUE TITLE
Overlap Nodes label

### ISSUE THREAD

**Issue by nitin0708** [almende/vis#699]
Hi Alex,

I checked in all example and docs but i did not find any solution of node label overlap.
Please see the below link-

http://jsbin.com/yafogivope/1/edit

Thanks,
Nitin

**Comment by josdejong** [comment]
The Network uses a physics simulation which does not reckon with the actual size of nodes. If some nodes contain a very wide text, the resulting network would probably not be very readable even when the Network would neatly position them aside. 

What you could do is:
- spread the text over multiple lines (see this example: http://visjs.org/examples/network/10_multiline_text.html)
- play around with the physics to tune the nodes such that they are displayed with a wider distance (like configure a larger node distance). See http://visjs.org/examples/network/25_physics_configuration.html

**Comment by AlexDM0** [comment]
Hi Nitin,

Jos's solution is the only one here. There is no way to take the size of the node into account at the moment. In a non-hierarchical system you could increase the mass but the physics of the hierarchical do not take this into account. 

Regards,

Alex

**Comment by Willliamm** [comment]
Hi,
The link http://visjs.org/examples/network/10_multiline_text.html is broken.

How can I implement multline feature?

**Comment by AlexDM0** [comment]
Hi,

We recently overhauled the examples. 

You can find it here:

http://visjs.org/examples/network/labels/multilineText.html

Regards,

Alex

**Comment by Willliamm** [comment]
Great! Thanks Alex!

Can you tell me if the overlap problem has been fixed?

**Comment by ThaDafinser** [comment]
Overlaping is currently also one of the problems i'm facing.
Some texts can't be moved to another line, so the node gets wider and finally overlap.

Dunno how i can solve it.

I will try `scaling.label.enabled` or something with `physics` ..
