### ISSUE TITLE
Persist the Network 

### ISSUE THREAD

**Issue by nitin0708** [almende/vis#702]
Hi,

Can we do persist a network after zoom and reposition of the Node in the hierarchical graph?

Thanks,
Nitin

**Comment by felixhayashi** [comment]
I noticed the same thing. The hierarchical layout does not consider node positions. It would be nice if the hierarchy would consider either x or y directions depending on the direction in use.

**Comment by nitin0708** [comment]
if we zoom a network of hierarchical graph and reload the  page then it is possible or not to draw same zoomable network.

**Comment by josdejong** [comment]
Network uses a physics simulation to find stable positions for nodes, this works sort of random. If you want to have a fixed view which is the same every time again, you can provide the nodes with fixed positions (x, y). After stabilization you could automatically retrieve the nodes positions using `network.storePositions()`.

**Comment by AlexDM0** [comment]
This is not possible with the hierarchical system at the moment. Though I think that you get the same network as long as you keep the input the same (in the hierarchicalLayout at least)

Regards

**Comment by nitin0708** [comment]
Thanks for the reply..

**Comment by AlexDM0** [comment]
In 4.0 we'll take the positions of the nodes into account, it should make it easier to work with the hierarchical system as well as unify the API

**Comment by stanleyxu2005** [comment]
I have a similar use case of hierarchical graph. I define nodes and edges once in constructor. And then I call `freezeSimulation(true)` to disable force calculation. And then I try to drag and move a node. Even if I change a node's label, all nodes will go back to their initial positions. I hope I can keep nodes position unchanged. 

Maybe add a boolean flag in onchange event. E.g. `function onChange(resetLayout) {}`

**Comment by AlexDM0** [comment]
Hi Qian,

It does not really work like that I'm afraid. The resetting of the layout actually has a purpose other than annoying the developers :). It will be better in 4.0 though, I'll try to limit the times it actually has to redeploy the nodes.

Regards,

Alex

**Comment by AlexDM0** [comment]
I'm going by all things marked for v4 and checking if they are in yet. This one has been added. I'll mark it as done and close it on release of v4.

**Comment by AlexDM0** [comment]
With the launch of v4, this issue can be closed. Remember depending on your projection (ud, du, lr, rl) either the x or y coordinate are overwritten, the other can be used for positioning. Alternatively you can set the randomSeed so it will be initialized the same way over and over.
