### ISSUE TITLE
Using an custom handler to add and delete Nodes

### ISSUE THREAD

**Issue by Chaos-t** [almende/vis#703]
Hello,

is there a way to use custom handlers to add Nodes and Edges?
For Example: I want to create a Node per Drag&Drop from my Nodelist.
Like this:

![unbenannt](https://cloud.githubusercontent.com/assets/7325584/6576807/fe3a8d98-c739-11e4-9515-3e985ce40c80.PNG)

Then "Vis.js" should add a Node with the same name.

**Comment by josdejong** [comment]
This isn't supported in Network, but you could attach your own drop handler to the container element where you have created the Network. On drop, you can add the dropped item to the Network yourself (`nodes.add({...})`).

**Comment by AlexDM0** [comment]
Is this still an issue?

**Comment by Chaos-t** [comment]
No, it is not an issue anymore. Thank you very much.
