### ISSUE TITLE
select nodes without edges

### ISSUE THREAD

**Issue by wiggisser** [almende/vis#704]
While it is possible to select only nodes without edges programmatically via selectNode(...), clicking (and touching) on a node will always highlight all incoming and outgoing edges for this node. It would be nice if this was configurable like it is when selecting via the API.

**Comment by funpluscharity** [comment]
It would be even better if we can select if we need any one of the three: incoming, outgoing or both

**Comment by AlexDM0** [comment]
Hi, 

In 4.0 we'll try to open up the behaviour a bit more, whether those will be options or injection funcitons I'm not sure yet but we'll keep this in mind.

Regards,

Alex

**Comment by valtih1978** [comment]
> `It would be even better if we can select if we need any one of the three: incoming, outgoing or both`

I think that I have requested something like that before https://github.com/almende/vis/issues/623. Namely, I have noticed that there are great onConnect/onDelete filters prompting that the same filtering could be applied for the onSelect.

**Comment by AlexDM0** [comment]
In 4.0 we have an option that allows you to disable selecting connected edges when clicking on a node. You can then use the new selectNode event to manually select any edges you'd like with the selectEdges method. This limits option bloating and I think this is the cleanest way.

**Comment by AlexDM0** [comment]
With the launch of v4, this issue can be closed.
