### ISSUE TITLE
event handler for just edges

### ISSUE THREAD

**Issue by funpluscharity** [almende/vis#705]
We currently have only one event handler for handling select events for both node and edges as shown below. It would be good if visjs can either provide separate handlers for each or provide a flag to differentiate between the two.

network.on('select', function (selectedElementsArray)

**Comment by josdejong** [comment]
I'm not sure whether more (specific) event handlers will make Network easier to use, it would also complicate and bloat the API. I think it's better to stick with one simple select event, from which you can specialize for your specific case at hand.

With the current select handler you can easily distinguish what is selected: the event is fired with an object containing properties `nodes` and `edges`. If you are only interested in an edge being selected, you can just check whether `props.nodes.length === 0` and `props.edges.length > 0`.

**Comment by AlexDM0** [comment]
I agree with Jos here, the check is so tiny that it's not really worth making a seperate event. There is one case though where there is a multiselect and you want to ascertain the last clicked element.. I'll see what I can do.

Regards,

Alex

**Comment by valtih1978** [comment]
Might be you just preserve the selection order? Currently, whether I select nodes 2 and 5 or 5 and then 2, I always get selection list '2','5'. Maintaining the order would be helpful and easy implement, I believe. The order however cannot be preserved among edges and nodes since you create two separate lists in your onSelect. But such total order is much less demanded.

**Comment by AlexDM0** [comment]
I'm going by all things marked for v4 and checking if they are in yet. This one has been added. I'll mark it as done and close it on release of v4.

**Comment by AlexDM0** [comment]
With the launch of v4, this issue can be closed.
