### ISSUE TITLE
Issue when the network is loaded in a zoomed in chrome/firefox browser

### ISSUE THREAD

**Issue by AlMathews12** [almende/vis#706]
When I try to load a network in chrome/firefox browser which has already been zoomed in , the network is not being rendered properly . The colors are all being spilled behind the trailing edges and nodes.
It seems to be working fine when the browser is zoomed out ( zoom >= 100%)

**Comment by josdejong** [comment]
How can I reproduce this issue? I tried on Chrome, reload an example when zoomed in or zoomed out, but everything seems to work just fine.

**Comment by AlexDM0** [comment]
Hi,

Could it be that you're using an older version of vis? This has been an issue before and it was fixed as far as I know. Does this also happen with the examples on the visjs page?

Regards,

Alex

**Comment by AlMathews12** [comment]
Hi,
Its working fine with the new version . I was using an old version which i had downloaded two months back in Jan. Thank you for quick reply.

Regards,
Al
