### ISSUE TITLE
Feature request: Alternative Edge arrow style

### ISSUE THREAD

**Issue by stanleyxu2005** [almende/vis#709]
Arrow styled edge represents how data goes from source node to sink node. It would be nice to draw an edge with different width on both side. Currently I configure edge.width=3. I expect to configure edge.width.from=5, edge.width.to=1.

A not exactly example is http://www.nytimes.com/interactive/2012/11/02/us/politics/paths-to-the-white-house.html?_r=0

**Comment by josdejong** [comment]
That looks indeed nice. This is not so trivial to implement though. There are plenty of different kinds of "special" arrow styles we can think of. We can't implement them all, that would completely blow up the library. It would be great if we can adjust Network such that you can easily extend it yourself with custom arrow styles.

**Comment by AlexDM0** [comment]
Hi Stanley,

The new release lets you specify arrows individually for from to and middle. This should solve your problem.

Regards
