### ISSUE TITLE
clickToUse .overlay

### ISSUE THREAD

**Issue by wiggisser** [almende/vis#713]
Maybe you could consider to choose a different classname than 'overlay' in your activator, as this is a very common name and likely to be used by app-developers. I just debugged your code for 2h to find out why 'clickToUse' does not work with my app. In the end I found, that my own 'overlay' class (to simulate a modal dialog)  interfered with your 'overlay' class, thus my network was never displayed as active.

**Comment by josdejong** [comment]
Yes good point. I suppose this holds for both of us ;)

For v4 we want to rename all class names with a prefix `vis-` or something like that to prevent conflicts with for example bootstrap.

**Comment by AlexDM0** [comment]
This should be fixed by the v4 release
