### ISSUE TITLE
"Freeze" date div for tall timelines

### ISSUE THREAD

**Issue by MattyDub** [almende/vis#714]
I'd like to have the date panel always be visible even when scrolling down on tall timelines. Is there a way we could "freeze" it, something like on this jsfiddle: http://jsfiddle.net/austinbv/2KTFG/ ?
   Thanks,
-Matt

**Comment by josdejong** [comment]
Yes, you can apply configuration options `maxHeight`, `height`, and `minHeight`. All can be in pixels or in percentage (like `'100%'`). When the contents of the Timeline doesn't fit, it will become vertically scrollable.

**Comment by MattyDub** [comment]
Jos, thanks for your quick reply! This is very good. One more quesiton: Is there any way to get it to work with scrolling instead of dragging?

**Comment by josdejong** [comment]
There is currently no support for that. On laptops we could introduce something like shift+scroll. And for mobile devices I hope that switching to hammer.js v2 allows for these kind of things (v2 offers more options in this regard).

**Comment by MattyDub** [comment]
OK, thanks for the reply.

**Comment by AlexDM0** [comment]
Weren't there plans to add a custom scrollbar to the timeline?

**Comment by teeena** [comment]
Is issue https://github.com/almende/vis/issues/273 for the custom scrollbar?

**Comment by AlexDM0** [comment]
Yes, among others but that is the one we try to refer to. Thanks for looking it up :)
