### ISSUE TITLE
onSelect function runs just once

### ISSUE THREAD

**Issue by Kritika688** [almende/vis#715]
Hi,

I am currently working on vis.js network data visualization. I have my data in MySql DB, I have written a php script to convert the data to json and populate the network graph. Once the entire graph is displayed, i am trying to select a particular node and query only its neighbors. My code works fine for the first selection (does not work recursively). When i repeat the same process of selecting another node, the selection does not happen. How can i get it working continuously for every node selection?

I hope i made my issue clear. Here is my code.

	
	$.getJSON('http://localhost/test1.php', function(data) {
        var nodes = data.nodes;
		var edges = data.edges;
		
		var container = document.getElementById('mynetwork');
		var data = {
		nodes: nodes,
		edges: edges
		};
		var options = {
        stabilize: false,
        navigation: true,
        keyboard: true
      };
		var network = new vis.Network(container, data, options);	
		
		var selectednode;
		function onSelect(properties) {
		selectednode = properties.nodes;
		console.log(selectednode);
		var url = "http://localhost/test2.php";
		$.post(url,{node: selectednode},function(data) {
		var data = JSON.parse(data);
		var nodes = data.nodes;
		var edges = data.edges;
		
		var network = new vis.Network(container, data, options);
		
		});
		}		
		network.on('doubleClick', onSelect);		
		});
	

Thanks & Regards,
Kritika

**Comment by wiggisser** [comment]
You create a New network in the callback of your post to test2.php. As it is created in the same container as the first one, I suppose, the first is destroyed, ans with it its event handlers.

**Comment by Kritika688** [comment]
I dint get it! 
The code posted above works perfectly well for one iteration (when i double click on a node once). However when i doubleclick on the subgraph "generated by test2.php" it does not work. 
Thanks !

**Comment by wiggisser** [comment]
You create one network = new vis.Network() in the callback of test1.php. This is the instance, the doubleClick handler is bound to. In the onSelect() function you create a new network = new vis.Network() into the same container as the other one. I don't know, how vis handles this, but I assume the first instance of the network (the one with the handler) is destroyed. But you don't bind the doubleclick event to the new network instance, thus the doubleclick does not work any more.

**Comment by Kritika688** [comment]
Thank you for you response! I understand what you mean. That could possibly be the issue. Any suggestions on how I could resolve this? I am trying out variations in my code, however stuck at the same point.

**Comment by AlexDM0** [comment]
Hi All,

The correct way to do this is by using the vis.DataSet. That allows you to dynamically alter the data in the network. You now bind a click and double click event to a network that you overwrite, thus it will not have any event handlers anymore.

Take a look at our documentation and examples, specifically this one:
http://visjs.org/examples/network/16_dynamic_data.html

If you'd like any more help with the code, please create a JSBin to facilitate this.

Regards,

Alex

**Comment by Kritika688** [comment]
Thank you so much Alex ! Using vis.DataSet worked like magic !

I have another question regarding the DataSet. In my DB i hav several attributes like firstname, lastname, age etc. I noticed that adding these attributes in my json file gives me error. 
"firstname": "abc", "lastname": "xyz"

In the 27 World Cup Example they use Title to display the information "title: 'Country: ' + 'Costa Rica' + '<br>' + 'Team: ' + 'Club Brugge'" 
Is this the only way to go about it ?

**Comment by AlexDM0** [comment]
Hi,

If there is a problem, could you please make a JSbin to show it? If you want a popup then yes, the only way to do this is with the title attribute.

Regards,

Alex

**Comment by Kritika688** [comment]
Thank you for your assistance.

Here is a sample of my data:
{"nodes": [{"id": "1", "lastname": "Gyllenhaal", "title": "Jake"}]}

I can get the first name in title, is there no way i can display the last name separately? 

A part of my code where I am trying to fit it in:

network.on('select', function (properties) {
								selectednode = properties.nodes;
								console.log(selectednode);
                                                                // I get the ID in console, but no other information
								//var test = properties.lastname;
								//console.log(test);
                                                                }

Here is the link to my project and code (I am not sure how else I can share the code, please let me know if you are unable to view, Thanks!):
https://github.com/Kritika688/Visualization_Project/tree/master/Version2

Thanks & Regards,
Kritika

**Comment by AlexDM0** [comment]
Hi,

With the ID you can look in the data you fed into the network and obtain the last name. You cannot use the title popup for anything other than showing the title. You can use the data you get from the select event to do anything you want though.

If you want to show code, I suggest www.jsbin.com

Regards,

Alex

**Comment by Kritika688** [comment]
Thank you!
