### ISSUE TITLE
dataAxis.customRange.left.min = 0, value 0 not visible

### ISSUE THREAD

**Issue by AdamNowaczyk** [almende/vis#716]
Hi,

I have problem with dataAxis.customRange.left.min = 0 setting for my Graph2d. Data items with value 0 are not visible on the graph. In cases where there is no 'activitiy', so all values are 0 for given period of time, no lines are visible. When I started playing with the CSS, I can see that they get rendered, but just 'under' the view content. How can I solve this problem?

--
Thanks,
Adam

**Comment by AlexDM0** [comment]
Hi Adam,

Sorry, must have missed this one. The problem also shows in the jsBin you made in your other issue. I'm afraid I'll have to postpone fixing this until 4.0. I expect 4.0 around April.

Regards,

Alex

**Comment by AdamNowaczyk** [comment]
Hi Alex,

I think this jsBni represents the issue better: http://jsbin.com/qeyewihidu. It looks that the problem is height parameter, which I was hoping to use. My project is still in development and probably be going through QA in April/May. Do you think it's possible to have a fix for this issue by then? 

--
Thanks,
Adam

**Comment by AlexDM0** [comment]
Hi Adam, 

If everything works out we'll get 4.0 released at the first of April. I could quickly take a look if there's something to be hacked around for now though.

Let me check.

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi, 

I'd suggest to solve is as shown here in the meantime: 
http://jsbin.com/wuyevipevo/1/edit?html,js,output

It's a bit sloppy but I don't really have time to go further into this at the moment.

Regards,

Alex

**Comment by AdamNowaczyk** [comment]
Alex,

Thanks for suggestion, but that won't work. I cannot assume max value for the graph. I would have to recalculate it for each dataset (dataset is updated depending on the time period and zoom user is previewing). 

I'll wait for proper fix. Just let me know if you're going to work on it. For now I have other development tasks to finish, but if I have some spare time, I'll try to look into visjs code and maybe propose PR for this.

--
Thanks,
Adam

**Comment by AlexDM0** [comment]
Hi Adam,

I have fixed this in the v4 branch. We expect to release v4 in a few weeks.

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi, 

I was mistaken, it seems to be a rather deep-nested issue. We'll look into it. We will fix it before the v4 launch though.

Regards,

Alex

**Comment by josdejong** [comment]
This should be fixed now in the `v4` branch.
