### ISSUE TITLE
Get group Ids displayed in Timeline

### ISSUE THREAD

**Issue by teeena** [almende/vis#717]
Is there a way to get the Ids of the groups that are currently viewable in a timeline with more rows than the set height?

I modified the 14_group_performance.html example to display 500 groups, 1000 orders, and set the height to 400px.  In the screenshot, Trucks 7 to 16 are currently viewable.  Trucks 1 to 6, and Truck 17 to 500 are not viewable.  Is there a way to get the ids of Trucks 7 to 16?  

My timeline will potentially have a large number of groups and items and as the number of groups and items increases, the timeline appears to slow down.  I'm looking for ways to improve the performance, so I'm thinking a solution would be to display only the items for the groups currently in view.  As the user pans vertically, the items will be filtered by groupId.

![groupsinview](https://cloud.githubusercontent.com/assets/11321631/6673505/e7bfb890-cbd0-11e4-9acc-066395ea82f4.JPG)

**Comment by josdejong** [comment]
There is no support for getting visible groups or something like that. 

Ideally, the Timeline should hide non-visible groups itself to improve performance, like it does horizontally for non-visible items. 

Isn't 500 groups too much anyway to make sense to present to a user? Shouldn't you add a filter/search field on top of your Timeline such that the user can filter groups that he is looking for rather than having to scroll endlessly down?

**Comment by teeena** [comment]
Thanks for your response.  Are there plans to implement a feature to hide non-visible groups?  

With horizontal items, the time range is used to determine if it's visible or not, but how would you determine if a group is visible or not?

There is a filter available and a search feature would be a good idea.  500 groups is an extreme case and there usually won't be that many.  I wanted to see how the timeline performed as the number of groups and items increased and was seeing performance degrade.  Another extreme case that I tried was 100 groups with 35000 items and it was slow too, so I thought if there's a way to display only the items for the groups currently in view, then the problem would be solved.

**Comment by teeena** [comment]
I found a solution.  To find out what groups are in the viewable area I do some calculations using the group's dom top, timeline height, and timeline container's top.  Then I used the DataView's filter to include only those group Ids.

**Comment by josdejong** [comment]
>  Are there plans to implement a feature to hide non-visible groups?

Well, that sounds like a nice performance improvement. We don't plan on implementing in on short term, but if anyone can pick this up would be great.

**Comment by yotamberk** [comment]
Solved by #2062
