### ISSUE TITLE
Empty groups in timeline are shorter than non-empty groups

### ISSUE THREAD

**Issue by MattyDub** [almende/vis#718]
Is there any way to force them to all be the same, so the group height is uniform?

I tried doing so by adding a class to the group rows, and setting their height via css; however, vis.js didn't know about this, and prevented me from being able to drag down to the bottom few groups. (I infer that vis.js calculates the total height of the timeline, under the assumption that empty groups have a certain height. If so, external changes to the empty group height like mine will break dragging behavior.)

**Comment by josdejong** [comment]
The total height of a group is determined by the maximum stacking height of the items and the height of the group label on the left side. You could give the group labels a fixed or minimum height using CSS.

**Comment by MattyDub** [comment]
If I set a height in my css on .vlabel, the corresponding rows in the timeline don't line up. Should I use a different selector?

**Comment by josdejong** [comment]
Yes, you should give the div inside `.vlabel` a fixed or minimal height (`.vlabel` height itself is changed by the Timeline to the calculated group height):

```css
.vis.timeline .vlabel .inner {
  min-height: 100px;
}
``` 

Here a demo: http://jsbin.com/zoyete/edit

**Comment by MattyDub** [comment]
Jos, that's great. Thanks so much.
