### ISSUE TITLE
Cluster by group and open cluster on animation (zoom in)

### ISSUE THREAD

**Issue by hawoosin** [almende/vis#720]
On you own example 33_animation you can zoom out and focus node (zoom in). I just tried to add clustering and somehow the camera still zooms but the clusters don't open on zooming in. Apparently they just open by scrolling with the mouse wheel. Is there any possibility to open cluster and cluster nodes with zooming in and out by animation?

Also I noticed nodes who are connected will cluster together even though they have different groups. Is it possible to set options on how nodes will cluster? Like I want nodes to just cluster as they do now, if two big chunks of nodes are not connected they will cluster separately but also if they have individual groups in each chunk they will prioritize the groups and cluster by groups first.

**Comment by AlexDM0** [comment]
Hi Felix,

No.  Clustering is not really allowing any of that. The good news though is that it has had a complete overhaul and will be released with 4.0. That will give you all control over all aspects of clustering. We expect 4.0 around April. 

Regards,

Alex

**Comment by hawoosin** [comment]
Okay, that's what I thought but I wanted to be sure about it. Thank you a lot!

**Comment by AlexDM0** [comment]
I'm going by all things marked for v4 and checking if they are in yet. This one has been added. I'll mark it as done and close it on release of v4.

**Comment by AlexDM0** [comment]
With the launch of v4, this issue can be closed. There are examples on this on the new website.
