### ISSUE TITLE
Provide util functions

### ISSUE THREAD

**Issue by stanleyxu2005** [almende/vis#721]
I believe visjs uses many util functions to render a chart. For instance calculate the max and min value or an array, to get colors from pre-configured color palette. It would be great to expose such functions. Like d3 https://github.com/mbostock/d3/wiki/Arrays https://github.com/mbostock/d3/wiki/Colors

Currently I include d3 in my visjs project as a helper library. I hope I should include only visjs. ;-)

**Comment by AlexDM0** [comment]
Hi,

you can take a look in vis.util to see if there is anything you'd like to use. We do not plan to expose and document these as the API. 

Regards,

Alex
