### ISSUE TITLE
Edge removal during reconnection process (edit edge) causes error

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#722]
Hi @visjsdevteam,

Steps to reproduce (http://jsbin.com/yekuti/2/):

1. Select an edge
2. Edit edge (connect it to another node)
3. If the edge is removed in the course of the edit process, clicking anywhere on the canvas or on the "back button" will produce an error.

Maybe vis should abort the edit edge operation if the underlying data (that is related to the operation) changed?

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

I'm almost tempted to say then don't delete it in the middle of the process :p. I'll make sure this will just work in 4.0 as I don't plan any more fixes for the 3.x version. I can't merge them in anymore due to the full rewrite.

Regards,

Alex

**Comment by felixhayashi** [comment]
Hi @AlexDM0,

> I'm almost tempted to say then don't delete it in the middle of the process :p.

Yes, I know... I wish I could dictate the program flow. It is a love/hate relationship with asynchronous operations :)

>  I'll make sure this will just work in 4.0 as I don't plan any more fixes for the 3.x version. I can't merge them in anymore due to the full rewrite.

Thanks. Good luck on the rewrite!

-Felix

**Comment by AlexDM0** [comment]
Hi Felix, 

I have put a few safeguards in 4.0 for this behaviour. I'll mark the issue as done and close it on release of 4.0. If you find any bugs in v4 I hope you'll be reporting them again :)

Regards

**Comment by felixhayashi** [comment]
Hi Alex

> I have put a few safeguards in 4.0 for this behaviour. I'll mark the issue as done and close it on release of 4.0. If you find any bugs in v4 I hope you'll be reporting them again :)

Sure, can't wait to test it :)

-Felix

**Comment by AlexDM0** [comment]
With the launch of v4, this issue can be closed. Have fun :)
