### ISSUE TITLE
Border on Image Nodes.

### ISSUE THREAD

**Issue by thraxst** [almende/vis#724]
Is it possible to add a border to image nodes? I am trying to get the selected node to stand out better, currently the only difference I can see is the text is bold and the associated edges are thicker.

Thanks.

**Comment by AlexDM0** [comment]
Hi,

A border around images is not supported at the moment though you could try to use the select event to increase the size of the node. 

Basically, on select, width = width * 1.5. 

You can use the vis dataset to dynamically update the data. 

Regards,

Alex

**Comment by thraxst** [comment]
Okay thanks, I am doing something similar on hover, so I will just do that on select too.
