### ISSUE TITLE
Get canvas 2d context and draw

### ISSUE THREAD

**Issue by ivangfr** [almende/vis#725]
Hi,

I am trying to get the Vis Network canvas 2d context, after it is stabilized, and then draw a circle on a specific node.
Is it possible? If so, what is the method that I must use in order to get the node position on canvas

An example: http://jsfiddle.net/7yswrt92/7/

Thanks.

**Comment by AlexDM0** [comment]
Hi Ivan,

This is not possible at the moment. From 4.0 onwards you can do this. We expect 4.0 around april. As for the method you can use to get the position: 
http://visjs.org/docs/network.html#Methods

Hint: it sounds like get position :)

Regards,

Alex

**Comment by AlexDM0** [comment]
I'm going by all things marked for v4 and checking if they are in yet. This one has been added. I'll mark it as done and close it on release of v4.

**Comment by AlexDM0** [comment]
With the launch of v4, this issue can be closed. There is an example on this in the new website.

**Comment by ivangfr** [comment]
Nice! Can you post the link for the new website? Thanks!

**Comment by AlexDM0** [comment]
We were in the process of updating the website, I didnt expect people to jump on it just like that.

Here you go: 

http://visjs.org/examples/network/events/renderEvents.html

Have fun :)

**Comment by ivangfr** [comment]
Hi, there is a bug in this part of the code:

      key: 'adaptAllOptions',
      value: function adaptAllOptions(allOptions) {
        if (this.options.hierarchical.enabled === true) {
          // set the physics
          if (allOptions.physics === undefined || allOptions.physics === true) {
            allOptions.physics = { solver: 'hierarchicalRepulsion' };
            this.optionsBackup.physics = { solver: 'barnesHut' };
          } else if (typeof options.physics === 'object') {
            this.optionsBackup.physics = { solver: 'barnesHut' };
            if (options.physics.solver !== undefined) {
              this.optionsBackup.physics = { solver: options.physics.solver };
            }
            allOptions.physics['solver'] = 'hierarchicalRepulsion';
          } else if (options.physics !== false) {
            this.optionsBackup.physics = { solver: 'barnesHut' };
            allOptions.physics['solver'] = 'hierarchicalRepulsion';
          }

Instead of "options.physics" it should be written "allOptions.physics"

**Comment by AlexDM0** [comment]
Hi,

Thanks, I've fixed it in develop. We'll probably have a bugfix release next week. There's bound to be some small things that went wrong. 

I'll go kick my IDE in the nuts for not letting me know about this one.

Regards,

Alex
