### ISSUE TITLE
graphviz mode support {rank} option ?

### ISSUE THREAD

**Issue by kdszh** [almende/vis#726]
Hi,

I want to use {rank} option in graphivz mode to show my map,but it seems it do not work.
here is my code ( a little change from examples\network\graphviz\data\fsm.gv.txt, add rank in the bottom):

digraph finite_state_machine {
	rankdir=LR;
	size="8,5"
	node [shape = doublecircle]; LR_0 LR_3 LR_4 LR_8;
	node [shape = circle];
	LR_0 -> LR_2 [ label = "SS(B)" ];
	LR_0 -> LR_1 [ label = "SS(S)" ];
	LR_1 -> LR_3 [ label = "S($end)" ];
	LR_2 -> LR_6 [ label = "SS(b)" ];
	LR_2 -> LR_5 [ label = "SS(a)" ];
	LR_2 -> LR_4 [ label = "S(A)" ];
	LR_5 -> LR_7 [ label = "S(b)" ];
	LR_5 -> LR_5 [ label = "S(a)" ];
	LR_6 -> LR_6 [ label = "S(b)" ];
	LR_6 -> LR_5 [ label = "S(a)" ];
	LR_7 -> LR_8 [ label = "S(b)" ];
	LR_7 -> LR_5 [ label = "S(a)" ];
	LR_8 -> LR_6 [ label = "S(b)" ];
	LR_8 -> LR_5 [ label = "S(a)" ];

        {rank=max;LR_0;}
        {rank=same;LR_1;LR_2;}
        {rank=same;LR_3;LR_4;LR_5;}
        {rank=min;LR_6;LR_7;LR_8;}
}

**Comment by AlexDM0** [comment]
Hi,

Sorry for the late reply. We do not support the rank option in vis. 

Regards,

Alex

**Comment by josdejong** [comment]
@AlexDM0 it may be possible to support rank, as Network supports a hierarchic view. Not sure how easy or complicated that will be to implement.
