### ISSUE TITLE
click VS. doubleClick

### ISSUE THREAD

**Issue by majedoms** [almende/vis#727]
Hi, 

It looks like whenever I double click a node, not only the doubleClick event is fired, but the click event as well. 

Your input would be much appreciate it!
Majed

**Comment by AlexDM0** [comment]
Hi,

What module are you referring to? For the network there are a LOT of issues here with all kinds of fixes.

Regards,

Alex

**Comment by majedoms** [comment]
Yes, I'm referring to the network module. Can you please point me to a fix? 

thanks
Majed

**Comment by majedoms** [comment]
I found it! https://github.com/almende/vis/issues/203

Thanks alot for your replay, and sorry, I should have searched github and not just google
