### ISSUE TITLE
Eucledian distance to activeAreaBoxSize

### ISSUE THREAD

**Issue by valtih1978** [almende/vis#729]
Let me ask a short question. You say [Imagine a square with an edge length of activeAreaBoxSize pixels around your cursor. If a cluster is in this box as you zoom in, the cluster can be opened in a seperate sector. This is regardless of the zoom level.](http://visjs.org/docs/network.html#Clustering). This is totally fine except using rectangular distance 

```javascript
  exports._nodeInActiveArea = function(node) {
    return (
      Math.abs(node.x - this.areaCenter.x) <= this.constants.clustering.activeAreaBoxSize/this.scale
        &&
      Math.abs(node.y - this.areaCenter.y) <= this.constants.clustering.activeAreaBoxSize/this.scale
      )
  };

```
rather than simple radius

```javascript
	network._nodeInActiveArea = function(node) { return (
		Math.pow(Math.pow(node.x - this.areaCenter.x,2) + Math.pow(node.y - this.areaCenter.y,2), 1/2) 
			< this.constants.clustering.activeAreaBoxSize/this.scale
	)}
```

Your measure is completely unnatural and even longer to code. Is computational complexity a concern?

**Comment by AlexDM0** [comment]
I guess both solutions would be fine. I don't remember why I chose for this approach. In the next release all of this will be removed though as the clustering has been completely redone.
