### ISSUE TITLE
Tooltips cause error when node is removed as index ceases to exist

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#731]
Hi guys,

sorry to disturb your refactoring. I spotted the following bug.

0. Use JSbin not in edit mode as it swallows key events
1. Hover node 1 till the tooltip appears
2. Delete the node via delete key while the tooltip is active
3. Now move with the mouse

Please see http://jsbin.com/nesoku

![selection_564](https://cloud.githubusercontent.com/assets/4307137/6788361/2ce8995a-d199-11e4-8112-2099e22c1587.png)

**Comment by AlexDM0** [comment]
Hi Felix,

I keep on being surprised how you come up with these :). Large user base or are you really testing A LOT?

There won't be a new release of vis for the network (one for timeline is on its way though) but I'll see if I can fix this in 4.0. I haven't gotten around to updating the tooltip yet anyway :). It should also become a whole lot easier to manage these things in 4.0. 

Thanks for the heads up!

Alex

**Comment by felixhayashi** [comment]
Hi Alex

> I keep on being surprised how you come up with these :).

I have a talent of running into trouble ;) But yes, I do a lot of testing since I change my own code often and the TiddlyMap project is still in beta. The user base is not that large as I try to keep the project somewhat hidden till I feel comfortable enough to make the first stable release.

> There won't be a new release of vis for the network (one for timeline is on its way though) but I'll see if I can fix this in 4.0.

Yes, I am aware of that. I just keep posting bugs so you might get a chance to consider them in 4.0.

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

I hope I won't introduce many more with 4.0 but we have a lot of in house testing planned for it. Then again... Big rewrites... Thanks for the heads up! Keep them coming :)

Regards,

Alex

**Comment by AlexDM0** [comment]
I'm going by all things marked for v4 and checking if they are in yet. This one has been added. I'll mark it as done and close it on release of v4.
