### ISSUE TITLE
fontFill only support 1 line on edge #network

### ISSUE THREAD

**Issue by Lukather1971** [almende/vis#732]
Hi,

If i use a "Edge" label with font Fill (background color behind the label) and the label contains more than 1 line , the background color only fill the first line.

See attachment 
![fontfill](https://cloud.githubusercontent.com/assets/8628365/6789474/d5935728-d1a0-11e4-815d-80ba8e5559d0.PNG)

**Comment by AlexDM0** [comment]
Hi,

This will be addressed in the 4.0 release. 

Regards,

Alex

**Comment by AlexDM0** [comment]
Additionally, you may want to look into the edge label stroke. There is an example on our website. I personally prefer that effect over the background fill. 

Thanks for letting us know by the way :)

Regards

**Comment by Lukather1971** [comment]
OK i will check the example
thanks in advance

**Comment by AlexDM0** [comment]
Hi, 

A small update, I just tried in 4.0 and it's fixed there. I would not recommend using the 4.0 branch yet due to extreme instability though.

Regards,

Alex

**Comment by Lukather1971** [comment]
Ok thanks for updating me
I will wait until the stable version is released :+1:

**Comment by AlexDM0** [comment]
With the launch of v4, this issue can be closed.
