### ISSUE TITLE
timeline: selectable=true plus shift-clicking also selects background items

### ISSUE THREAD

**Issue by carueda** [almende/vis#733]
- Background items are **not** selectable directly -- and this is just fine
- But they are selected when shift-clicking regular items: the screenshot below is right after clicking the "dev" item, then shift-clicking the "test" item;  note the background item (under days 26 and 27) also being selected.

![image](https://cloud.githubusercontent.com/assets/556505/6789595/b05c5dfc-d15e-11e4-8f9f-593e4a79c6ee.png)

I think the default behavior should be to skip any involved background items in the selection. But this implies some sort of more elaborate `selectable` option besides the Boolean value. 

Perhaps better to enter a separate request, but the `selectable` could be also an object (like in the `editable` case), possibly also allowing to indicate the type of desired selection (eg., "multiple", "single")... Thanks.

**Comment by josdejong** [comment]
Ah, a trick to get the background items selected anyway ;)

Indeed selecting a range of items with shift should skip background items. Thanks for bringing this up.

**Comment by josdejong** [comment]
This is now fixed in the source code on the `develop` branch.
