### ISSUE TITLE
Setting the locale does not seem to have any effect

### ISSUE THREAD

**Issue by NotSqrt** [almende/vis#736]
I've seen the code in :
https://github.com/almende/vis/blob/a3b89a4cd003fc7043327c404fff976cb10e1e49/lib/timeline/component/TimeAxis.js#L78

I expected the language used in the axis to change, but it doesn't seem to.

cf example http://visjs.org/examples/graph2d/13_localization.html which doesn't change.

**Comment by josdejong** [comment]
Thanks, looks like a bug.

This works fine for the Timeline (which uses the same axis): http://visjs.org/examples/timeline/19_localization.html

**Comment by josdejong** [comment]
The url loading moment.js with locales was broken in that example. I've fixed it: https://github.com/almende/vis/commit/09752230417043e1e9f5253087ae75825df45ce5

**Comment by NotSqrt** [comment]
OK, I see that it works on the timeline example with that fix.

But on my 2dgraph, the axis stays desperately in English, despite trying to use "nl", or adding 
```javascript
{
	locales: {
		// create a new locale
		"fr": {
			current: "heure",
			time: "actuelle"
		}
	},
	locale: "fr"
}

``` 
and using ``moment-with-locales.js``

Any idea that I can try to debug this ?

**Comment by NotSqrt** [comment]
Additionally, the div representing the current time is, with locale "nl":
```html
<div class="currenttime" title="Undefined tijd: Wednesday, March 25th 2015, 10:12:18" style="position: absolute; top: 0px; height: 100%; left: 581.331666666667px;"></div>
```

We can see that vis used the locale translations in the title (it also works with my "fr" locale), but the date is in English.

For the "undefined": 
```js
  // Dutch
  exports['nl'] = {
    custom: 'aangepaste',  // should be "current"
    time: 'tijd'
  };
```

**Comment by NotSqrt** [comment]
If need be, it is possible to locally change the moment locale whenever there is a need for a localized representation  : http://momentjs.com/docs/#/i18n/instance-locale/

cf TODO on https://github.com/almende/vis/blob/a3b89a4cd003fc7043327c404fff976cb10e1e49/lib/timeline/component/TimeAxis.js#L77

This would probably save me.
I've tracked the calls to ``moment.locale(name)``, I see calls with ``name="en"``, then ``name="fr"`` then ``name="en"``

**Comment by josdejong** [comment]
@NotSqrt can you create a jsbin with your non-working locale? This example works just fine: http://jsbin.com/dapojuk/1/edit

I will fix the `undefined tijd` issue, thanks.

**Comment by NotSqrt** [comment]
It does work on some pages, so the impossibility to view some timelines in French is probably a problem in the rest of my code.

Thanks.
