### ISSUE TITLE
Specify className for only .dot div in point item

### ISSUE THREAD

**Issue by vinny75** [almende/vis#739]
I'm replacing the dot for a point item with a Font Awesome icon; however, I can't use the standard className option for an item because it applies the "fa fa-star" class to both the item.point and item.dot div resulting in the FA icon being displayed twice. I've gotten around this by placing the FA css in .point namespace using less but this is a clunky work around. Is there a better way to do this? Would there be interest in specific configuration options for the .dot div in the item?

![capture](https://cloud.githubusercontent.com/assets/324551/6823906/0b234806-d2ed-11e4-9218-fe7b09da5ad6.PNG)

**Comment by josdejong** [comment]
What is the CSS that you use right now?

**Comment by vinny75** [comment]
the portion relevant to this is 
``` CSS
.vis.timeline .item.dot {
border: 0;
background: transparent;
}
```
I add the "fa fa-star" classes to the item className

**Comment by vinny75** [comment]
This is what I get without using less with fa css.
![capture](https://cloud.githubusercontent.com/assets/324551/6825219/30c77684-d2f9-11e4-8c5a-cc1091ac816b.PNG)

**Comment by josdejong** [comment]
> I add the "fa fa-star" classes to the item className

Can't you add the `fa fa-star` classes to a more specific class, like

```css
.vis.timeline .item.point.myClassName .item.dot {
  /* ... your styling here ... */
}
```

**Comment by vinny75** [comment]
The problem is that when I add the fa fa-start classes to an item like so
``` javascript
        var visData = [];
        _.each(results, function(e, i, l) {
            var type = (e.EventDate.getTime() === e.EndDate.getTime()) ? 'point' : 'range';
            var n = {
                id: e.Id,
                group: _.indexOf(uniqueGroups, e[grouping]),
                content: e.Title,
                start: e.EventDate,
                end: e.EndDate,
                //style: "background:" + colorBrewer_Set3[_.indexOf(uniqueColors, e[coloring])],
		className: (type != 'point') ? "cb" + _.indexOf(uniqueColors, e[coloring]) : "cb" + _.indexOf(uniqueColors, e[coloring]) + " fa fa-star fa-lg",
                type: type
            };
            visData.push(n);
        });
```
I end up with an HTML element that looks like this

    <div class="item point cb1 fa fa-star fa-lg" style="left: 233.56px; top: 14.5px;">
        <div class="content" style="margin-left: 34px;">SDNY</div>'
        <div class="item dot cb1 fa fa-star fa-lg" style="left: 8.5px; top: 7px;"></div>
    </div>

the fa fa-star classes are applied to both the point and dot causing the double icon.

I've gotten around this by wrapping the font awesome classes in a .point so it applies only its children (hence .dot) to get around this but I feel this is a bit of work around. 

``` css
.point {
	@import 'fa/less/font-awesome.less';
	@fa-font-path: "fa/fonts/";
}
```

Not sure if there is another option I've missed or if adding an option to each item for classes just applied to the .dot div is warranted.

**Comment by josdejong** [comment]
The className is attached to both outer box and inner dot. And font awesome then attaches an icon to every element with this class. There isn't really a solution here as far as I can see.

I think the most neat solution would be to make the original dot of the item invisible, and create a special `span` or `i` element with the font-awesome icon in the items *contents* (like `content = '<i class="fa fa-star fa-lg">SNDY'`). This element should be relatively positioned such that it's center corresponds with the center of the now invisible dot.

**Comment by vinny75** [comment]
brilliant. I think this css does the trick.

``` css
.vis.timeline .item.point .content {
	margin-left: 0px !important;	
}
.vis.timeline .item.point .content .fa {
	margin-right: 5px;
}
.vis.timeline .item.dot {
	display: none;
}
```

**Comment by josdejong** [comment]
Great to hear this works for you. 

Just another idea: you could use templates to generate your item contents: http://visjs.org/examples/timeline/27_templates.html, where you create this font awesome icon.

**Comment by vinny75** [comment]
Adding the icon to the content works brilliantly except that the width of the item doesn't take the icon into account when calculating position... see attached screen shot.... I haven't really dug into this and don't really think it's your problem but just putting this out there for anyone else attempting the same thing

![capture](https://cloud.githubusercontent.com/assets/324551/7062800/132b7478-dea1-11e4-9972-44431badd9b4.PNG)

**Comment by josdejong** [comment]
Great to hear it works. Looks like you need more CSS tweaking here, apparently the Timeline does not correctly calculate the width of the contents here.

**Comment by vinny75** [comment]
Actually... the problem was unrelated to the icons. 


I didn't like the way content was hidden on overflow but I also didn't want really long content shown either so I used 

``` CSS
.vis.timeline .item.range .content {
	text-overflow:ellipsis;
}
``` 
this worked except it gave only '...' for the content of smaller items, still not quite what I wanted so I used
``` CSS
.vis.timeline .item.range .content {
	text-overflow:ellipsis;
	min-width: 5em;
}
``` 
which works great except vis.js uses an overflow property in repositionX to space items horizontally and this is calculated in redraw as
``` javascript
this.overflow = window.getComputedStyle(dom.content).overflow !== 'hidden';

```
and since my overflow is still technically hidden, the was being set to false instead of true.

not sure of the best solution here but this seems to work
``` javascript
this.overflow = (window.getComputedStyle(dom.content).overflow !== 'hidden') || (window.getComputedStyle(dom.content).textOverflow !== 'clip');

```

**Comment by AlexDM0** [comment]
If you're using the templates, wouldn't this be solved by putting the icon in a separate div or span with a predefined width? It seems the width calculation is done before the icon is loaded, which messes up after it loads..

**Comment by vinny75** [comment]
Alex,

The overlapping ranges were unrelated to the icon.
