### ISSUE TITLE
Timeline options.format not applying when using options.timeAxis

### ISSUE THREAD

**Issue by Gugarion** [almende/vis#740]
I'm seeing a bug where using timeAxis appears to be prevent options.format from being applied. If I remove the timeAxis, the formatting is working..

```javascript
timeAxis: {
	scale: 'day',
	step: 7
},
format: {
	majorLabels: {
		month: 'MMM'
	},
	minorLabels: {
		year: 'yy',
		month: 'MMM'
	}
}
```

**Comment by josdejong** [comment]
The properties that you provide under `majorLabels` and `minorLabels` correspond with one particular scale. In your example you fix the scale to `day`, which means that it makes only sense to provide custom formatting for the scale `day`, like:
```
  timeAxis: {
    scale: 'day',
    step: 7
  },
  format: {
    majorLabels: {
      day: 'MMM YYYY'
    },
    minorLabels: {
      day: 'MMM'
    }
  }

**Comment by Gugarion** [comment]
Thanks @josdejong 
Much appreciated!
