### ISSUE TITLE
Timeaxis scaling issue with start and end date on timeline

### ISSUE THREAD

**Issue by bondseid** [almende/vis#741]
Hello,

I am using the timeline and would like to set the time axis to step of 15 minutes when i have a start and end date on my timeline. Here is how i am constructing the timeline

items = new vis.DataSet([
          {id: 4, content: 'item 4', start: "2015-03-22T20:41:29.201Z", end: "2015-03-22T20:41:29.237Z"},
        ])

        timeAxis = {}

        options = {
            orientation: "top",
            start: "2015-03-10T04:00:00.000Z",
            end: "2015-03-26T04:00:00.000Z",
            timeAxis: {scale: 'minute', step: '15'}
        }

        timeline = new vis.Timeline($element[0], items, options)

        timeline.on "click", (properties) ->
            console.log properties

There seem to however b scaling issues as the timeline does not resize to fit the axis. See image attached:
![screen shot 2015-03-26 at 1 47 42 pm](https://cloud.githubusercontent.com/assets/11668422/6853023/ba7633b4-d3be-11e4-8ffb-b92a09e6de18.png)

If i remove the timeaxis option from the options object: 

![screen shot 2015-03-26 at 1 48 32 pm](https://cloud.githubusercontent.com/assets/11668422/6853043/d3355966-d3be-11e4-9529-b75f90990330.png)

Perhaps i am missing something.

Thanks a lot!

**Comment by josdejong** [comment]
If you set a fixed scale of 15 minutes, and your window covers 16 days, that's 4 * 24 * 16 = 1536 quarters of an hour visible -> The Timeline needs to draw 1536 grid lines and labels. There is a safety limit of 1000 grid lines, therefore the Timeline in your first example stops drawing more grid lines at about 2/3 of the window width.

If you enforce a fixed scale, you need to be careful not to zoom out too much...

**Comment by bondseid** [comment]
I appreciate the reply.

I am actually implementing the vis timeline into an angular project. I installed it via bower and just noticed that when initiating a very basic timeline, none of the drag, zoom functionality is working whatsoever. 

This is odd because i had previously been using the links timeline before finding vis and when i had put that in it worked perfectly. Do you have any idea why the library would not work out of the box within an angular project?

**Comment by josdejong** [comment]
Are use using just vis.js, or the [angular directive](https://github.com/visjs/angular-visjs)?

**Comment by bondseid** [comment]
I built my own very simple directive just for the timeline.

Also i used the directive to see if that would work and the same thing is happening, the timeline or any other graph is not picking up when i try and drag or click. Do i need to manually define these events?

**Comment by bondseid** [comment]
Btw when clicking on the tineline this error is thrown : 

Uncaught TypeError: Cannot read property 'srcEvent' of undefined 
vis.js:13917

**Comment by josdejong** [comment]
It's hard to guess what's going wrong here. I suppose the regular examples on the website work fine for you. Can you create a [jsbin](http://jsbin.com) demonstrating the issue?

**Comment by bondseid** [comment]
Sadly (for me) i created the jsbin and it worked perfectly even with the code i used. So there must be a conflict with something else in my angular application.

http://jsbin.com/roxexasawo/1/edit?html,js,output

**Comment by bondseid** [comment]
I finally figured it out.

I had installed the bower package hammerjs for use in another context and when i removed it, vis began working correctly.

**Comment by josdejong** [comment]
Ok great. I guess this was hammerjs v2 then (as vis.js still uses v1.x)?
