### ISSUE TITLE
network repositioning

### ISSUE THREAD

**Issue by kenansalloum** [almende/vis#742]
how can i align network to left or right??

**Comment by AlexDM0** [comment]
Hi, 

What do you mean by align?

Regards

**Comment by kenansalloum** [comment]
i want to animate all nodes on page load to left or right

**Comment by AlexDM0** [comment]
I am not really sure what you mean. You could animate the view to 'move' the nodes to a side? Could you elaborate a bit?

Regards

**Comment by kenansalloum** [comment]
yes i want to animate the view, how can i do this?

**Comment by AlexDM0** [comment]
Like so:
http://visjs.org/examples/network/33_animation.html
