### ISSUE TITLE
Feature Request: Context Menu for Network

### ISSUE THREAD

**Issue by michaelelrom** [almende/vis#743]
Hello,

A context menu binding would be very helpful for vis.js in the Network area.

Thank you

**Comment by AlexDM0** [comment]
Hi,

Why wouldn't you just bind the context menu on the container div? I'm not sure what you'd think vis should do here. 
http://stackoverflow.com/questions/4909167/how-to-add-a-custom-right-click-menu-to-a-webpage

Regards,

Alex

**Comment by michaelelrom** [comment]
Hi Alex,

It was a while since I tested that so I just re-did that and it seems that I need vis to support a rightclick binding on nodes and edges for the context menu to trigger and have selected data.  Am I on the right track there?

Thanks,

Mike

P.S. vis rocks!

**Comment by AlexDM0** [comment]
Hi Mike,

You could do this:

http://jsbin.com/qeyumiwepo/5/edit?html,output

I dont think I'll put it in vis, but I'll supply a method to get a node at a position so this can do exactly what you want. This will be in 4.0.

Regards,

Alex

**Comment by michaelelrom** [comment]
Thanks for the prompt response.  That sounds great.

Mike

**Comment by AlexDM0** [comment]
I've put the methods in v4.0 and an rightClick event. I'll mark this as done and close it on launch of 4.0.

Regards

**Comment by michaelelrom** [comment]
Thanks so much!

**Comment by AlexDM0** [comment]
With the launch of v4, this issue can be closed. The event is called oncontext.

**Comment by Tooa** [comment]
Hi Alex,

I'm trying to build such a context menu, but I wonder how to prevent the regular browser context menu from showing up. In your provided [JsBin](http://jsbin.com/qeyumiwepo/5/edit?html,output) this is the case. However, looking at the current examples from visjs [here](http://visjs.org/examples/network/basicUsage), there is a context menu. I can't see the difference. What prevents the browser context menu inside the render area.

**Comment by AlexDM0** [comment]
Hi Uli,

It's the prevent default called on the event. The example in jsbin was not meant for this version of vis as that has an event for this. I think you can still use the event supplied by the context menu event to call prevent default though. 

Regards

**Comment by Tooa** [comment]
Thanks! The call `params.event.preventDefault()` where params is the argument from the oncontext event solved it indeed. Best Uli

**Comment by Joyfred** [comment]
Is it possible to achieve this kind of context menu in vis.js
![image](https://user-images.githubusercontent.com/39043611/59963787-b4b31d80-9515-11e9-83d0-9c3366287fbf.png)
