### ISSUE TITLE
edit range item without having to activate it first

### ISSUE THREAD

**Issue by eyeworkers-manuel** [almende/vis#744]
Hello developers,
first of all we want to thank you for your great plugin.

In our project we have two timelines. The first timeline is quite normal and has several different items.
The second timeline is used as an overview of the first timline and is made up of a single range item. We use this single range item to manipulate (zoom, pan...) the first timeline.

Is there a way to edit this range item without having to activate the item first?

Thank you in advance for your help.
Regards,
Manuel

**Comment by josdejong** [comment]
Thanks. Nice idea using a range item in a secundary timeline to manipulate the range of your main timeline :)

In this case you need to make sure this range item stays always selected. You can select beforehand using the method `setSelection`, and you can listen for changes in the selection using the `select` event (like when the user clicks somewhere in the empty space of the Timeline), and if the range item is unselected, select it again using `setSelection`. 
You could adjust the CSS styling of the range item such that it looks the same when either selected or is unselected for a couple of milliseconds, so the user will never see any flickering.

**Comment by eyeworkers-manuel** [comment]
Thank you very much for your quick answer. This is exactly what we are lokking for.
Somehow I oversaw this method in the documentaion. Sorry for that...

Best regards

**Comment by josdejong** [comment]
you're welcome
