### ISSUE TITLE
timeline: item update to a brand new subgroup triggers TypeError

### ISSUE THREAD

**Issue by carueda** [almende/vis#745]
* open http://visjs.org/examples/timeline/30_subgroups.html

EDIT 2016-09-08:  The example is now located at http://visjs.org/examples/timeline/groups/subgroups.html 

* using browser's console adjust a item to update its subgroup to a brand new subgroup
* Uncaught TypeError: Cannot read property 'index' of undefined

Screenshot shows a successful update with "sg_2", which has already been used during the setup of the items; and a failure when trying to update the item with a brand new subgroup.

![image](https://cloud.githubusercontent.com/assets/556505/6873013/77db19dc-d46a-11e4-811b-1e67ca88818c.png)

**Comment by brichbe** [comment]
Interesting.  Adding a *new* item using either `DataSet.add()` or `DataSet.update()` does allow a new subgroup to be specified without problem.  
`items.update({id: 345, start: '2014-01-17 12:00:00', group:'bar', subgroup: 'sg_NEW'});`

It seems the issue only occurs when updating an existing item.

@carueda you probably already know you can work around this issue right now by calling `timeline.setItems(items)` after you've updated your existing item in the DataSet.

**Comment by josdejong** [comment]
I've partly fixed this issue (see https://github.com/almende/vis/commit/4f47608a278905ece2b6b59bd8104bc2e108f437), but there is still an issue with the new group having a height zero or something. Besides that, it looks like groups are not cleaned up (nor items from their previous subgroup). @AlexDM0 can you have a look at this?

**Comment by AlexDM0** [comment]
I'm not sure when I'll be able to get around to this, maybe we should reevaluate the implementation of the subgroups as a whole. They were a bit hacked in in the first place...

**Comment by carueda** [comment]
All: Thanks for the discussion. I do have a workaround for my case (basically simply pre-add the subgroups that will be exercised later on during editing), so this is not pressing for me. But I'm just curious about any progress or perhaps your concrete plans for re-doing the subgroup handling in this amazing library.

**Comment by carueda** [comment]
After a long while I just tried to reproduce this..

The example is now located at http://visjs.org/examples/timeline/groups/subgroups.html. I opened it on Chrome Canary (Version 55.0.2853.0 canary) and followed the steps. No TypeError anymore.  

Wanted to close this entry but seems like there may still be failing cases (mentioned by @josdejong ).

**Comment by mojoaxel** [comment]
> maybe we should reevaluate the implementation of the subgroups as a whole. They were a bit hacked in in the first place...

There are quite some [open subgroup issues](/almende/vis/search?q=subgroups&state=open&type=Issues&utf8=%E2%9C%93), but I'm not sure somebody will find the time to fix the implementation as a whole!?

But this one we can close I think.
