### ISSUE TITLE
Additional points generated in Graph 2d - time change?

### ISSUE THREAD

**Issue by dell640** [almende/vis#749]
Today was shown fancy error, probably in connection with time change (summer/winter):

Here is hard copy of php generated page:
http://err.imasik.cz/

All of my graphs made this error between 3-4h morning 29 march.

Thanks

**Comment by dell640** [comment]
OK guys, now I understand, Vis Graph handles time change like ignoring one hour in timeline where time change was happened. But when I'm putting points to this missing hour, they are rendered into next hour. Why its like that?
If is that hour ignored on timeline, why are not ignored values aimed into this non-existing hour?

**Comment by josdejong** [comment]
I don't think it's a good idea to hide items in non existing hours, it's up to you to sanitize the data you feed to the Graph2d ;). I think it would be nicest if the points would be displayed all at 3:00 instead of being shifted into the next hour.

**Comment by dell640** [comment]
Yes, of course, data should be prepared properly. But when are not, its not pretty smart to offset them to next hour. As you written, best solution will be keep all these point at one position 3:00.

**Comment by josdejong** [comment]
> But when are not, its not pretty smart to offset them to next hour

There is *no* logic handling this in the Timeline, this is the default behavior of converting Dates to a numeric timestamp. This actually makes sense: if you say 2:30 but this hour is skipped, then in reality is 3:30 at that moment. But displayed on the Timeline like that is not so nice.

**Comment by AlexDM0** [comment]
is this still an issue? The problem seems in the data source, vis is just putting the points at the right time.
