### ISSUE TITLE
Edge - dynamic changing parameters

### ISSUE THREAD

**Issue by rafal-software** [almende/vis#750]
Hi,
do you know example of dynamic changing edge look properties?
Additionally according to me it would be much more easy to setup all properties if all 
properties would be only one level eg. replace color.highlight to highlight.

Kind regards!

**Comment by AlexDM0** [comment]
Hi,

If you are referring to colors then no, but it's very easy to make one yourself. If you are referring to the smooth curves see example 26. 

As for the options, I disagree. It would be easier to type yes, but for understanding and documentation it is easier to group them. 

Regards

**Comment by AlexDM0** [comment]
Additionally, in the upcoming 4.0 release you can use an editor for node and edge options.
