### ISSUE TITLE
afterTimelineDragged

### ISSUE THREAD

**Issue by Blugh** [almende/vis#752]
Hi Guys

I have an interesting scenario that I am hoping you can help me solve. My users want to be able hold down the mouse and drag the timeline to whatever date, and when they stop dragging, the events must be populated / loaded. Now, I know we have the timechanged event for the timeline, and loading the events after this event has fired is very easy. 

My issue comes in when the user zooms in/out on the timeline, as the timechanged event will now also fire, but will fire rapidly as the user scrolls. Now, because of this rapidly firing event, it results in just as many requests for the data i need to load.

Is there any way I could prevent the timechanged event from firing when the timeline is being zoomed in/out?

**Comment by josdejong** [comment]
You could for example implement a short delay (say 100ms) of inactivity before you start loading items after `timechanged` has fired. 

A trick to distinguish whether the timeline has been zoomed or moved is to compare the visible window (end-start) with the previous window. If the same interval is visible, the timeline has been moved. It would be useful to extend the `timechange` and `timechanged` events with information whether it is caused by a drag or a zoom event.

**Comment by Blugh** [comment]
Hi @josdejong 

Thanks for the speedy reply.

Please excuse my naivety, but what would the best way to implement the delay be? I have tried using setTimeout, but it is not reliable from my experience (or I am doing it wrong).

How would I compare to the previous window?

I agree with extending the timechange and timechanged events, could it be done just like the click implementation, where it returns the "what" etc properties?

**Comment by josdejong** [comment]
For a delayed execution, you can do something like:

```js
var DELAY = 200; // ms

function fetchData() {
  // ... fetch the data
}

function delayedFetchData () {
  clearTimeout(fetchTimeout);                  // clear any running timeout
  fetchTimeout = setTimeout(fetchData, DELAY); // create a new timeout
}
var fetchTimeout = null;

timeline.on('timechanged', delayedFetchData);
```

To see whether the width has changed, you can do something like this: http://jsbin.com/pesovo/edit?html,output

**Comment by Blugh** [comment]
ah, cool, i see what I was doing wrong. I was missing this bit " clearTimeout(fetchTimeout);".

Thank you, much appreciated.

**Comment by josdejong** [comment]
you're welcome!
