### ISSUE TITLE
Callback function when the whole timeline has been loaded?

### ISSUE THREAD

**Issue by eyeworkers-manuel** [almende/vis#753]
Hi all,

is there a callback function when the timeline has been loaded?
Didn´t see one in the documentation.

Thank you in advance,
Manuel

**Comment by josdejong** [comment]
The timeline is normally loaded completely directly after creating it. To test this, you can put a blocking `alert('foo')` right behind `var timeline = new vis.Timeline(...)` and see if the Timeline is displayed correctly.
