### ISSUE TITLE
Is it possible to change the style of the Item's title?

### ISSUE THREAD

**Issue by almusawi** [almende/vis#755]
I need to Use the 'title* to show a discription to the items. Is it possible to change the style of the Item's title? 
and also it is possible to use another library with the vis timeline to show the discription like a ballon on top of the items of the timeline, when moving the muse over the item?

Thanks alot

**Comment by josdejong** [comment]
This title cannot be styled and can only contain plain text (style is determined by the browser). 

For more advanced tooltips, you could use some tooltip library and attach tooltips to the contents of your items (the items can contain HTML). Using [templates](http://visjs.org/docs/timeline.html#Templates) here may be convenient here.
