### ISSUE TITLE
DataManipulation: buttons that aren't used

### ISSUE THREAD

**Issue by michaelelrom** [almende/vis#756]
Hello,

The documentation for Vis Network Data Manipulation states:
"If there is no injected function supplied for the edit operation, the button will not be shown in the toolbar".

That doesn't seem to work for me.  The buttons still appear without injected functions.  I have an application where I want users to use Data Manipulation, but I don't want them to do all of the functionality available (i.e. Add/Delete Nodes and Edges, but don't edit them).  

In testing I've added options (see below) that show the buttons on default or hide them if set to false:
        addNode:false,
        addEdge:false,
        editNode:false,
        editEdge:false,
        deleteSelected:false,

Example:
        if (this.constants.editEdge != false) {
            this.manipulationDiv.appendChild(this.manipulationDOM['seperatorLineDiv3']);
            this.manipulationDiv.appendChild(this.manipulationDOM['editEdgeSpan']);
        }

Is this a bug or should I fork and submit my code?

Thanks,

Mike

**Comment by AlexDM0** [comment]
Hi Mike,

> "If there is no injected function supplied for the edit operation, the button will not be shown in the toolbar"

This refers to the edit node button. This does not hold for the rest of the buttons.

All buttons have a class. Just use display:none to hide them.

Finally, in 4.0 there will be an option to toggle these.

Regards,

Alex

**Comment by michaelelrom** [comment]
Thanks Alex!
