### ISSUE TITLE
Issue in using multi-color  for an item in VIS TimeLine

### ISSUE THREAD

**Issue by DivyashreeMS** [almende/vis#757]
Hi Alex/Josdejong,

I am trying to set multiple className in vis.DataSet as shown below

items = new vis.DataSet([
                            {id: 0, group: 0, content: 'UM 0', start: new Date(2014, 9, 17, 6, 10, 0, 0), end: new Date(2014, 9, 17, 6, 30, 0, 0), 'className': 'highRed'},
                            {id: 1, group: 0, content: 'UM 1', start: new Date(2014, 9, 17, 6, 45, 0, 0), end: new Date(2014, 9, 17, 7, 20, 0, 0), 'className': 'highRed'},
                            {id: 2, group: 0, content: 'UM 2', start: new Date(2014, 9, 17, 7, 30, 0, 0), end: new Date(2014, 9, 17, 7, 40, 0, 0), 'className': 'red'}]);

I know that I cannot set more than one className, is there any option of setting multiple classNames as a array/List

![cellcolor](https://cloud.githubusercontent.com/assets/10521928/6948401/9958868e-d87b-11e4-99fd-521d55e0b6b8.jpg)

for example: in the provided screen shot, it is Red color from 06:10 to 06:30 for "Used Memory" , so I am looking for is to have this block in different colors for 5 min time interval. Is it possible?

Thanks & Regards
Divya

**Comment by AlexDM0** [comment]
Hi,

I'm not sure what you want. You want one block, in different colors for each 5 minute interval? 20 minutes makes 4 colors?

What would this look like? Like this maybe?
http://jsbin.com/vowujesutu/1/edit

You could use the style option for each item to set it's own background gradient.

If you want to give your items their individual class, then do so. Docs say you can give a classname per item: 
http://visjs.org/docs/timeline.html#items

Regards,

Alex

**Comment by DivyashreeMS** [comment]
I've a set of data represented as a contiguous block on a graph. I'm using vis framework. Is there any way of using multiple colors in a single classname per item ? something like this
{id: 25, group: 1, content: 'BT 2', start: new Date(2014, 9, 17, 6, 20, 0, 0), end: new Date(2014, 9, 17, 6, 30, 40, 0), 'className': 'red, yellow, orange'}

**Comment by AlexDM0** [comment]
Did you look at the jsbin I posted? I have shown there that you can use css gradients for that.

**Comment by DivyashreeMS** [comment]
Hi Alex,

Thank you so much for the solution provided, After referring code in the jsbin, I am able to achieve what I required (UM0 and UM1 in the screenshot attached). There's a small problem though. The bar (UM0 and UM1) is vertically elongated. I need to keep the bar of the same height (as BT2, BT3, GCS4, GCS7,...). Can you please suggest me where and how to specify the height and width of the bar for UM0 and UM1?

Thanks again for your valuable time and suggestion.

![cellcolorwithevenwidth](https://cloud.githubusercontent.com/assets/10521928/7027687/dcb9df20-dd1e-11e4-86d3-0d7dfd02f84f.jpg)

**Comment by AlexDM0** [comment]
Hi,

It would really help if you could show code. How about jsfiddle?

Regards

**Comment by DivyashreeMS** [comment]
hi Alex,

I have shared the code in jsfiddle as per your request.

https://jsfiddle.net/Divyashree/oezL4hkt/5/

Thanks
Divya

**Comment by AlexDM0** [comment]
Hi Divya,

Please make sure your fiddle works next time. I have fixed it here:

http://jsfiddle.net/zzqk29dq/1/

As for your question.. Take a look a the CSS you use:

```

.vis.timeline .item.colorRBO{
width:400px;
  height:100px;
  background: rgb(255,0,0); /* Old browsers */
  background: -moz-linear-gradient(left,  rgba(255, 153, 0,1) 0%, rgba(255, 153, 0,1) 33%, rgba(255,0,0,0.5) 34%, rgba(255,0,0,0.5) 66%, rgba(255,0,0,1) 67%, rgba(255,0,0,1) 100%); /* FF3.6+ */
background: -webkit-gradient(linear, left top, right top, color-stop(0%,rgba(255, 153, 0,1)), color-stop(33%,rgba(255, 153, 0,1)), color-stop(34%,rgba(255,0,0,0.5)), color-stop(66%,rgba(255,0,0,0.5)), color-stop(67%,rgba(255,0,0,1)), color-stop(100%,rgba(255,0,0,1))); /* Chrome,Safari4+ */
background: -webkit-linear-gradient(left,  rgba(255, 153, 0,1) 0%,rgba(255, 153, 0,1) 33%,rgba(255,0,0,0.5) 34%,rgba(255,0,0,0.5) 66%,rgba(255,0,0,1) 67%,rgba(255,0,0,1) 100%; /* Chrome10+,Safari5.1+ */
background: -o-linear-gradient(left,  rgba(255, 153, 0,1) 0%,rgba(255, 153, 0,1) 33%,rgba(255,0,0,0.5) 34%,rgba(255,0,0,0.5) 66%,rgba(255,0,0,1) 67%,rgba(255,0,0,1) 100%); /* Opera 11.10+ */
background: -ms-linear-gradient(left,  rgba(255, 153, 0,1) 0%,rgba(255, 153, 0,1) 33%,rgba(255,0,0,0.5) 34%,rgba(255,0,0,0.5) 66%,rgba(255,0,0,1) 67%,rgba(255,0,0,1) 100%; /* IE10+ */
background: linear-gradient(to right,  rgba(255, 153, 0,1 0%,rgba(255, 153, 0,1) 33%,rgba(255,0,0,0.5) 34%,rgba(255,0,0,0.5) 66%,rgba(255,0,0,1) 67%,rgba(255,0,0,1) 100%;/* W3C */
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ff0000', endColorstr='#10ff00',GradientType=1 ); /* IE6-9 */}
```

Don't you think the HEIGHT entree there might be causing this?

To extend on this: I would suggest you use the style element of an item to supply it with a custom gradient background. You can use javascript to determine which browser specific version you need (if needed at all).

Regards,

Alex

**Comment by DivyashreeMS** [comment]
**Hi Alex,

Thanks for your  earlier help, the issue which i am facing now  is for using multicolor css for single item, but at present the api allows use of only one css per item,  the requirement is to show 5 min interval  dynamic data of an item  in different colors(css). Please see the attachment for better understanding. I hope I am clear with the explanation.
item :
 {id: 22, group: 8, content: 'DS 22', start: new Date(2014, 9, 17, 7, 00, 0, 0), end: new Date(2014, 9, 17, 7, 28, 40, 0), 'className': 'orange'},

![image](https://cloud.githubusercontent.com/assets/10521928/7107015/197419aa-e173-11e4-8cbf-4a9de964c957.png)-

**Comment by AlexDM0** [comment]
Hi Divya,

What you want simply is not possible. CSS does not work that way. You cannot stack css classes and assume it puts them next to each other. This is not our API, it's the basics of CSS. 

As a workaround, you can use the gradients with the item style option or just make it 5 different range item with a single color per item. 

Regards,

Alex

**Comment by AlexDM0** [comment]
Why do you think you need multiple CSS classes? There should be no need for this.

**Comment by DivyashreeMS** [comment]
The requirement in our project is to support  multiple feature. If you could suggest any other library that support this feature should be helpful.

**Comment by AlexDM0** [comment]
Hi,

Is there any reason the gradient method or splitting the item up into smaller items is not a good option?
They can both be used to get the same visual effect. 

If for any reason your client NEEDS to supply multiple colors in your API, just make a preprocessor for the data. 

Regards,

Alex

**Comment by Piu257** [comment]
how can we add label for each item if we want the label to be just above but outside the item box?
