### ISSUE TITLE
Style changes required for neighbour nodes

### ISSUE THREAD

**Issue by mmcsivakumar** [almende/vis#759]
I need to change the font color of neighbour nodes for the example 29_neighbourhood_highlight.

**Comment by AlexDM0** [comment]
Hi,

The options for the nodes have a fontColor argument. Feel free to use it. 
http://visjs.org/docs/network.html#Nodes_configuration

Regards,

Alex

**Comment by mmcsivakumar** [comment]
Below copied onclick method. In this method, to change the background color for neighbour node is

allNodes[nodeId].color = 'rgba(200,200,200,0.5)';

like wise i tried with  allNodes[nodeId].fontColor = 'rgba(200,200,200,0.5)'; is not working.

This is what i exactly asked in this thread. Please provide the solution for this.



function onClick(selectedItems) {
    var nodeId;
    var degrees = 2;
    // we get all data from the dataset once to avoid updating multiple times.
    var allNodes = nodes.get({returnType:"Object"});
    if (selectedItems.nodes.length == 0) {
        // restore on unselect
        for (nodeId in allNodes) {
            if (allNodes.hasOwnProperty(nodeId)) {
                allNodes[nodeId].color = undefined;
                if (allNodes[nodeId].oldLabel !== undefined) {
                    allNodes[nodeId].label = allNodes[nodeId].oldLabel;
                    allNodes[nodeId].oldLabel = undefined;
                }
                allNodes[nodeId]['levelOfSeperation'] = undefined;
                allNodes[nodeId]['inConnectionList'] = undefined;
            }
        }
    }
    else {
        var allEdges = edges.get();

        // we clear the level of separation in all nodes.
        clearLevelOfSeperation(allNodes);

        // we will now start to collect all the connected nodes we want to highlight.
        var connectedNodes = selectedItems.nodes;

        // we can store them into levels of separation and we could then later use this to define a color per level
        // any data can be added to a node, this is just stored in the nodeObject.
        storeLevelOfSeperation(connectedNodes,0, allNodes);
        for (var i = 1; i < degrees + 1; i++) {
            appendConnectedNodes(connectedNodes, allEdges);
            storeLevelOfSeperation(connectedNodes, i, allNodes);
        }
        for (nodeId in allNodes) {
            if (allNodes.hasOwnProperty(nodeId)) {
                if (allNodes[nodeId]['inConnectionList'] == true) {
                    if (allNodes[nodeId]['levelOfSeperation'] !== undefined) {
                        if (allNodes[nodeId]['levelOfSeperation'] >= 2) {
                            allNodes[nodeId].color = 'rgba(150,150,150,0.75)';
                        }
                        else {
                            allNodes[nodeId].color = undefined;
                        }
                    }
                    else {
                        allNodes[nodeId].color = undefined;
                    }
                    if (allNodes[nodeId].oldLabel !== undefined) {
                        allNodes[nodeId].label = allNodes[nodeId].oldLabel;
                        allNodes[nodeId].oldLabel = undefined;
                    }
                }
                else {
                    allNodes[nodeId].color = 'rgba(200,200,200,0.5)';
                    if (allNodes[nodeId].oldLabel === undefined) {
                        allNodes[nodeId].oldLabel = allNodes[nodeId].label;
                        allNodes[nodeId].label = "";
                    }
                }
            }
        }
    }
    var updateArray = [];
    for (nodeId in allNodes) {
        if (allNodes.hasOwnProperty(nodeId)) {
            updateArray.push(allNodes[nodeId]);
        }
    }
    nodes.update(updateArray);
}

**Comment by AlexDM0** [comment]
Hi,

Well no, as shown below  allNodes[nodeId].color = 'rgba(200,200,200,0.5)'; we remove the label from the node so there is nothing to be seen. Which labels do you want to change?

You can update this part to give the neighbour fonts a color

```
if (allNodes[nodeId]['levelOfSeperation'] >= 2) {
     allNodes[nodeId].color = 'rgba(150,150,150,0.75)';
     allNodes[nodeId].fontColor = '#ff0000';
}
```

Regards,

Alex

**Comment by mmcsivakumar** [comment]
i want to display the label, so i removed  allNodes[nodeId].label = ""; this line... In this case i need to change the lable color.

**Comment by mmcsivakumar** [comment]
Sorry Alex... It is working... Sorry for waste your time.

Thanks You Very Much
