### ISSUE TITLE
timeline: groups with locale doesn't work

### ISSUE THREAD

**Issue by chupascz** [almende/vis#761]
Combine timeline example "**05_groups.html**" with locale settings
```
locale: 'cs',
```
gives me error in **vis.js** on line **10713** "*TypeError: locale is undefined*".

Timeline is working (scroll, zoom etc), also **is properly translated to defined CS lang**, but **without** any data.
moment.js is properly linked. 
Without grouping, timeline works normal.

**Comment by josdejong** [comment]
This locale `cs` is supported by moment.js but not by vis.js. vis.js should not throw an error though. I've fixed this by giving a descriptive error here. When a locale is missing, you can provide it via the options as described here: http://visjs.org/docs/timeline.html#Localization

**Comment by AlexDM0** [comment]
Is this still an issue?
