### ISSUE TITLE
Hierarchical layout ordering

### ISSUE THREAD

**Issue by SpiderSnake** [almende/vis#762]
Hi Alex,

Your product is excellent so thank you very very much for that.

I have ran into a small issue however and not sure how to deal with it. 
I don't know if it is a bug or I'm missing something.

I have created a jsfiddle here: http://jsfiddle.net/SpiderSnake/f0yks75a/

I would like the nodes on level 1 in the follow order : 3 4 5 6 

Is there a way around this?

Thank you so much.
Yann

**Comment by AlexDM0** [comment]
Hi Yann,

That's not possible at the moment. In 4.0 it is could be done though, we expect 4.0 soon(ish).

Regards,

Alex

**Comment by SpiderSnake** [comment]
Ok thank you Alex.

**Comment by AlexDM0** [comment]
To expand upon this a little, in 4.0 the predefined x positions are left untouched. That means the simulation would respect the initial positions (only in the X direction for a top-bottom layout or only the Y position for a left-right layout) which could be used to order the points.

**Comment by AlexDM0** [comment]
With the launch of v4, this issue can be closed. Have fun :)
