### ISSUE TITLE
Network example broken on visjs.org.

### ISSUE THREAD

**Issue by vgm64** [almende/vis#763]
[Network example #1](http://visjs.org/network_examples.html) at visjs.org is broken. The source on the left cannot display the graph on the right. The id of the html div is "visualization" and the id used when attempting to select that div is "mynetwork".

**Comment by AlexDM0** [comment]
Yes... It's not exactly the same :). Though the id is a bit sloppy. I'll fix it.

Cheers

**Comment by AlexDM0** [comment]
fixed :)
