### ISSUE TITLE
Network onEdit() gets called 3 times when using dataManipulation

### ISSUE THREAD

**Issue by AndrewSpeed** [almende/vis#764]
When using the toolbar provided by the dataManipulation option for vis.Network, the edit option gets called 3 times.

I'm wondering if this is intended behaviour, as currently in my onEdit function I'm creating a form to take in user input, but this is being created 3 times due to this issue.

**Comment by AlexDM0** [comment]
Hi Andrew,

That shouldn't happen. I'll fix this in 4.0.

Regards,

Alex

**Comment by AndrewSpeed** [comment]
Alex, thanks for the update.

I've also discovered this bug with the onDelete option as well.

**Comment by AlexDM0** [comment]
I'm going by all things marked for v4 and checking if they are in yet. This one has been added. I'll mark it as done and close it on release of v4.

**Comment by AlexDM0** [comment]
With the launch of v4, this issue can be closed.
