### ISSUE TITLE
Draggable time range

### ISSUE THREAD

**Issue by aytech** [almende/vis#765]
Hi,
Since multiple custom time bars were introduced, it's possible to have time ranges on the timeline. Even the visual representation of the time ranges can be adjusted using the existing methods. And it would be nice to have the possibility to drag the selected time ranges by grabbing the defined area (between two time points). 
I believe this could be enabled by defining a time range (e.g. with a method), where the start and end of the time range would be indicated by 2 custom time bars (added if not on timeline already).

Do you think this can be added to the functionality list? I'd be happy to try to implement it myself. 

The possible use case is when another application uses the provided timechange / timechanged events to dynamically update the presented data. This way the range of events can be displayed with improved granularity.
Also, it can be used to limit the events displayed to improve performance, i.e. when there're lots of events to be shown on the timeline axis, the DataSet can be configured to display only those within the specified time range (using the existing functionality)

**Comment by aytech** [comment]
@AlexDM0: Hi Alex, do you think this can be added to the feature list? I pushed the changes to show what I meant, if you agree, I'll update the docs too

**Comment by AlexDM0** [comment]
Hi,

I'll leave this one up to Jos to decide. Timeline is his module after all. He's more familiar with the best ways to approach this.

We appreciate the enthusiasm though :)

Regards,

Alex

**Comment by aytech** [comment]
@AlexDM0 perfect, thanks! Waiting for Jos comment then :)

**Comment by josdejong** [comment]
Instead of extending the custom time bars for this, wouldn't it make more sense to use either BackgroundItems, or create a new type of item for this? BackgroundItems are not yet editable, but if they are, that would address this issue right?

**Comment by aytech** [comment]
Hi Jos, 
Why touch the background items? This feature is essentially a handle to move the range (2 parallel custom lines) without having to move each vertical bar individually.

**Comment by josdejong** [comment]
The functionality that you describe, coupling two custom time bars to form draggable range, sounds *very* similar to what RangeItems/BackgroundItems already do, that's why I was thinking whether this would be easier/cleaner to implement as a new type of item for this rather than extending the functionality of the custom time bars.

**Comment by aytech** [comment]
Hm, I'll try to tinker with the RangeItems/BackgroundItems, see if that can be done this way

**Comment by josdejong** [comment]
Is this still an issue or can we close it?

**Comment by aytech** [comment]
Not an issue anymore, can be closed

**Comment by josdejong** [comment]
Thanks!
