### ISSUE TITLE
Timeline Items content

### ISSUE THREAD

**Issue by almusawi** [almende/vis#766]
Hi all,
Is it possible to format the content of an item of the timeline in way that I can put part of the content depent on the scale time of the timeline?
for example,
the Item period is one month (sport activities) and I want to show inside this item for each week how many time has done this activites. but this need to know the timeline scale current time and use it to show the content at the end of each week.

in another word, I need to get specific date from the timeline scale and use it inside the item to show specific content for this item.

I hope this is clear for you and thanks  for help

**Comment by josdejong** [comment]
What you can do is create a listener for the `rangechange` (or `rangechanged`) event of the Timeline. If the visible window changes, you can replace the contents of all items in the timeline depending on the current scale (only if the contents of the items would actually change of course, to prevent unnecessary updates of all items on ever move/zoom action).
