### ISSUE TITLE
Custom time bar

### ISSUE THREAD

**Issue by almusawi** [almende/vis#769]
Hi,
would it be possible to change the shape of the custom time bar? to make it not only vertical line bar , but vertical line and small circle on the bottom? If it possible could you help me with that?

Thanks

**Comment by josdejong** [comment]
You can style the css of the time bar (`.vis.timeline .customtime). To add a small circle on the bottom you could give it a background image which is positioned at the bottom.

**Comment by almusawi** [comment]
Hi again,
I tired to do it like what you siad but the problem is the width of div for the customtime is small so you can not show the pic, but I found the solution by using the div inside the customtime and put the img in the div.  
.vis.timeline .customtime div:first-child{  }

thanks

**Comment by josdejong** [comment]
ah, ok nice!
