### ISSUE TITLE
How Can I place label inside Square Shape?

### ISSUE THREAD

**Issue by jmgarciamari** [almende/vis#770]
Hi! I've read this..

When a property label is provided, this label will be displayed inside the shape in case of shapes box, circle, ellipse, and database. For all other shapes, the label will be displayed right below the shape. This shape can be overridden by a group shape, or by a shape of an individual node.

But in graphviz, label is placed inside square.

Can I do this with vis.js?

Thanks a lot

**Comment by AlexDM0** [comment]
Hi,

At the moment no, but it will be a lot easier to make your own node type for this after the 4.0 release. 

Regards

**Comment by hbaderhold** [comment]
Hi Alex, 
Does the "make your own node type" feature also support re-positioning the text label beside a dot? (Currently only label position is below the dot; Would be nice to position it also right; left; top of the dot). Thanks a million!

**Comment by AlexDM0** [comment]
Hi,

This is not referring to the API but an easy way for users to extend on the source. You can do whatever you want :)

Regards

**Comment by AlexDM0** [comment]
Additionally, the alignment of the fonts with regards to the nodes is planned for 4.1.

Regards

**Comment by AlexDM0** [comment]
Hi, 

We just released v4 today. You can take a look at the new implementation and it should be easy to see what would be required for a custom node shape. 

I do want to do font alignment like so (eventually): above, below, left, right, inside

The plan is to have this for ALL shapes, but we're not there yet.

At the moment you can either implement your own shape and rebuild or use the renderevents to draw custom shapes behind a text node.

http://visjs.org/examples/network/events/renderEvents.html

Regards,

Alex

**Comment by hbaderhold** [comment]
Hi Alex, Thanks a lot! The renderevents feature is really awesome and a great help.

For this I have a follow up question : I would really like to have the custom shape scale the same way your labels do. Can you tell me were exactly in the code the 'this.body.view.scale'-scaling-steps-algorithms are implemented for label position, label font size. I would like to use these for the custom shape but I can't seem to find the right reference.

Thanks a million! Best,

Hanns

(Screenshots below are my current situation; The right tag is the custom shape and I would like to scale it in the same way as the label below the dot). Thanks!

![screen shot 2015-06-22 at 12 47 02](https://cloud.githubusercontent.com/assets/10381145/8280425/701d6dfa-18dd-11e5-9af5-b4de0f099ba8.png)
![screen shot 2015-06-22 at 12 47 16](https://cloud.githubusercontent.com/assets/10381145/8280430/811cbce6-18dd-11e5-8547-dfb82ec09bd1.png)
![screen shot 2015-06-22 at 12 47 22](https://cloud.githubusercontent.com/assets/10381145/8280438/8a7dd572-18dd-11e5-8f12-119fe7af07c4.png)

**Comment by AlexDM0** [comment]
Hi Hanns,

We do not scale the fonts based on the zoom level, that is done by the canvas. 

You may want to take a look at the label file:
https://github.com/almende/vis/blob/master/lib/network/modules/components/shared/Label.js

As for the position, you seem to be using dots, in that case the dot , which is a shape does this
https://github.com/almende/vis/blob/master/lib/network/modules/components/nodes/util/ShapeBase.js#L45

It would help if you were to post some code in a jsbin so I can see what you're doing.

Scaling seems fine?
http://jsbin.com/foxokubige/edit?html,output

Regards

**Comment by hbaderhold** [comment]
Hi Alex thanks a lot for your super fast comment – I will have a look at the part you sent, update some of my code, and then post it on JS-Bin. 

Actually the example you postet illustrates exactly the challenge i am having: The custom object text doesn't scale like the label does. I would like it to scale exactly like the labels (I do believe you have a font resizing method implemented- So you don't have huge text at zoom).

I will check the sources out, update, and get back to you. Thanks!

![screen shot 2015-06-22 at 13 14 09](https://cloud.githubusercontent.com/assets/10381145/8280762/f2f2cdee-18e0-11e5-9e4a-6c62a7e82f51.png)
![screen shot 2015-06-22 at 13 14 15](https://cloud.githubusercontent.com/assets/10381145/8280763/f312e340-18e0-11e5-8f0c-bcec6bfb624e.png)

**Comment by AlexDM0** [comment]
Ah I see what you mean. I thought you ment the size remained static

Here you go:
http://jsbin.com/juperowedo/1/edit?html,output

It's from:
https://github.com/almende/vis/blob/master/lib/network/modules/components/shared/Label.js#L61
https://github.com/almende/vis/blob/master/lib/network/modules/components/shared/Label.js#L114

Regards

**Comment by hbaderhold** [comment]
Thanks a lot Alex and best Regards to Rotterdam.
-Hanns

**Comment by hbaderhold** [comment]
Hi Alex, one more follow up if you have a free minute; I just realized that the canvas rescales the view to fit a larger network completely on the canvas; This way nodes and edges do not have the original sizes on pageload because they are scaled down. (Once you zoom in a bit the original size). 

Is there a way to deactivate the auto resize/zoom in such a way that the complete graph doesn't necessarily fit on the canvas but such that the nodes and edges are in their default, set sizes? Thanks for the amazing work and regards to the Almende team! - Hanns

**Comment by AlexDM0** [comment]
Hi Hanns,

I think you're looking for the physics:stabilization:fit option.

I'd recommend you'd actually keep it enabled and listen to the stabilizationIterationsDone event to do a network.moveTo({scale:1.0})

Could you make a new issue for a new question next time? It would be helpful for others if they search the issues for answers.

Regards

**Comment by hbaderhold** [comment]
Thanks, and will do next time. Best (again)
