### ISSUE TITLE
Dimensions of circular images apparently weird ...

### ISSUE THREAD

**Issue by redskate** [almende/vis#771]
Hi - thank you very much for letting use your nice graph lib!

For a node setting node.shape=cirtularimage and giving in node.image=http:/... displays a circular image with the image path provided.

I tried with several images and every time the lib "seems" to figure out what dimensions should have the image.

1) http://upload.wikimedia.org/wikipedia/commons/c/c5/UBC_SUB.jpg (2560 × 1120)
2) http://upload.wikimedia.org/wikipedia/commons/f/f6/Planet_sizes.svg (1053 × 745) 
3) http://upload.wikimedia.org/wikipedia/commons/f/fc/Maple_Leaf_(from_roundel).svg (305 × 343)
4) http://upload.wikimedia.org/wikipedia/commons/0/05/Vesta_symbol.svg (50 × 50)
5) http://upload.wikimedia.org/wikipedia/commons/8/8d/San_Diego_Skyline_Day_JD111107.jpg (very big)

Now: despite of the question whether or not give large images (I have thumbnails with an smaller size), why is visjs displaying a huge pic like in 5) smaller than a very tiny pic like in 4) ???

How can I influence the effective dimensions of the displayed pic??? I tried withMin and withMax with no success...

Thanks a lot in advance
Cheers

Fabio

**Comment by AlexDM0** [comment]
Hi,

Could you show me the code you use with a jsbin? I'd like to check what you feed into vis.

Regards,

Alex

**Comment by AlexDM0** [comment]
The widthMin and widthMax only relate to using a value, you can set value:1 to all your nodes (not globally!) to have it apply. There is no width to be set per node. This will be rectified in v4.0.

Regards

**Comment by redskate** [comment]
Hi Alex the relevant code is
 
                node.shape='circulatingImage',
 		node.image=src;
		node.widthMin=50;
		node.widthMax=70;

The dimensions seems to apply if the shape is "image" - what I am currently using, since circulatingImage is currently apparently not usable (by me).

Cheers
Fabio

**Comment by AlexDM0** [comment]
Hi, 

As stated above, add 
```
node.value=1;
```

It's a bad fix, agreed. It will be fixed properly in 4.0.

Regards

**Comment by redskate** [comment]
Hi Alex

thanks for this workaround.

I added node.value=1; and even node.value=2; or 3; 
The pics have still different dimensions when shown as circles.

It does not run.
Regards
Fabio

**Comment by redskate** [comment]
It does not run and you close the issue?

**Comment by AlexDM0** [comment]
Right, my bad. It seems to be because of the aspect ratio's.  A common scale factor is decided based on your settings. Some images are higher than others with the width you have defined. Since the circles are taking the height, you get differently sized circles.

You can play with the values and the min max settings to equalize it. There's nothing to be done about this at this point.

**Comment by AlexDM0** [comment]
I have fixed this in the 4.0 branch. It will be released somewhere around the end of april.

Regards,

Alex

**Comment by redskate** [comment]
Super! Thank you Alex.
