### ISSUE TITLE
Width of edges apparently weird ...

### ISSUE THREAD

**Issue by redskate** [almende/vis#772]
Hi - 

I am having some issues setting the attribute "value" in edge with integer values ranging from 1 to 15. Very often the thickness of the edge is ***not*** the value, but is so thin as under 1.

Why is this so?
What can I do to assure the thickness I wish?

Thanks a lot in advance

Cheers
Fabio

**Comment by AlexDM0** [comment]
Hi,

The value is limited by the widthMin and widthMax. If you want to set the thickness, just use the width. It would help if you could show your code so we can see where it goes wrong without guessing. 

Regards,

Alex

**Comment by redskate** [comment]
hi Alex

thank you for your msg.
I followed your suggestion and made

var edge = {
						id: fromid+"-"+toid,
			            from: fromid,
			            to: toid,
			            color: edgecolor,
			            fontColor: edgelabelcolor,
			            title: "Correlation ranking",
			            style: "line",
			            label: rdata.rank, // +" -> "+arcval, 
			            value: 1,
			            minWidth: arcval,
			            data: {expandable:false, type:"rank", rank:rdata.rank}
			          };
                   data.edges.add(edge);


But althaugh the value arcval varies from 1 to 15 I see no variation of the thickness of an arc.
What is missing please?

**Comment by AlexDM0** [comment]
Hi,

Did you read the documentation? To set the width, you can use the width option. The widthMin and widthMax (not minWidth!) are used to bound the width when varying the value.

http://visjs.org/docs/network.html#Edges_configuration
http://visjs.org/examples/network/09_sizing.html

Regards,

Alex

**Comment by redskate** [comment]
Hi

why should I?
Thank you for your hint - now it ist with "width"

Regards
Fabio

**Comment by redskate** [comment]
Actually this is still OPEN. But you are the owner ;)

**Comment by AlexDM0** [comment]
I figured that based on your last comment this was closed. That and the docs and the example show how to set the width in multiple ways. Why is this not closed? 

If you can't be bothered to read the docs, I am not going to put any more effort into trying to find out why your code is not working for you.

Regards,

Alex

**Comment by redskate** [comment]
ok, thanks for that Alex.
of course I read the doc - It was just the "right" answer to your question "did not read the doc?" - diplomatically improvable ;) You as the developer/supporter/owner of the one and only thing knows all of it, every screw. That is why it can happen that some users read the doc (quite nice) but did not understand it well. 

I did not ask you to debug my code - you wanted to see.  Anyway ... I can live well with what visjs is - thank you again :)

Regards
Fabio

**Comment by AlexDM0** [comment]
Hi Fabio,

You'd be surprised how many people do have the 'Why should I?' attitude.. Believe me, there is a reasonable number of people that come in wanting us to write their code for them. In general it is a lot easier if you can show a jsbin with the problem. The problem often resides in small things like misnamed options for instance. If I get a small snippet that would not show the problem there can be a lot of back and forth. So for next time ;) provide a small example in jsbin. Usually just copy pasting our examples can make a good base for us to reproduce and fix any issues.

It's been a long week, sorry for taking that out on you. If you still can't get it to work I either misunderstood your issue or something's wrong somewhere. Feel free to reopen en provide an example if that is the case.

Regards,

Alex

**Comment by redskate** [comment]
Thanks Alex :) everything OK :) 
Have a nice weekend
Fabio
