### ISSUE TITLE
Would it be possible to hide a group in the time line?

### ISSUE THREAD

**Issue by almusawi** [almende/vis#776]
Hi,

I would like to hide (not delete) the group from the timeline when this group does not have items in the current veiw (hiding it instead of showing an empty row), but will show again when the user changes the current view of the timeline and this group contains items in this veiw. 

Thanks in advance

**Comment by josdejong** [comment]
The subgroups already have support for hiding them, but the groups itself still miss this feature. It's on the to-do list.

**Comment by josdejong** [comment]
Sorry I was mistaken, neither groups nor subgroups do support hiding them right now.

**Comment by jrviz** [comment]
It is possible to hide groups if you do some of the work yourself. I have a large timeline where double clicking on a group label sets up a new groups DataView. When this DataView is set for the timeline it will only show the data for that group. I do this to allow the user to drill down into the detail of the timeline and not be distracted by the other groups around it. To select a subset of groups you would need to go through the data and exclude from the groups those which are not referenced in the data items using a filter.

An extract of my code is:
'
timelineD.on('doubleClick', function (selected) {
switch ( selected.what ) {
    case 'group-label':
		var targetGroup = new vis.DataView(groups,{ filter: function (item) { return (item.id == selected.group); } }); 
		timelineD.setGroups(targetGroup);
		timelineD.fit();
        break;
	default:
    }
});
'

You would need to change the filter function to just select the groups with data. My Javascript isn't very strong so it would take a bit of thinking for me to work it out but it is probably easy for some of the other wizards here!

**Comment by mojoaxel** [comment]
See also #415
