### ISSUE TITLE
Node/edge context menu 

### ISSUE THREAD

**Issue by redskate** [almende/vis#777]
Hi Alex

I am using your visjs for semantic network vis. 
I was wandering whether and how a node (edge) context menu could be popped up for undertaking further actions.

The use of a context menu is sometime useful to choose among interaction actions on one node/edge.

Thanks in advance
Regards
Fabio

**Comment by AlexDM0** [comment]
Hi Fabio,

This has been discussed before. Please refer to #743. I'll close this issue as a duplicate, any further discussion on the subject can continue in #743.

Regards,

Alex
