### ISSUE TITLE
Require Box shadow

### ISSUE THREAD

**Issue by mmcsivakumar** [almende/vis#779]
Is it possible to give the box shadow like radius, color, highlight, font size? 

groups: {
                                                  broot: {
                                                    // defaults for nodes in this group
                                                    radius: 0,
                                                    color: {
                                                      background: '#CB75FF',
                                                      highlight: {
                                                        background: '#CB75FF'
                                                      }
                                                    },
                                                    fontSize: 10,
                                                    shape: 'box'
                                                  }
}

**Comment by AlexDM0** [comment]
Hi,

No. I'll see if I can add it in v4.0.

Regards,

Alex

**Comment by mmcsivakumar** [comment]
Thanks Alex....

Expecting this enhancement on 4.0.....:)

**Comment by AlexDM0** [comment]
Its in 4.0 now for all shapes.

**Comment by mmcsivakumar** [comment]
Thanks for the update Alex
