### ISSUE TITLE
Require Label displayed middle & center of the Image

### ISSUE THREAD

**Issue by mmcsivakumar** [almende/vis#780]
Is it possible to display the label in middle & center of the Image node?

**Comment by AlexDM0** [comment]
Hi,

No. Font alignment is planned in 4.1.

Regards,

Alex

**Comment by mmcsivakumar** [comment]
Thanks Alex..

Can you update when we can expect 4.0 & 4.1

**Comment by AlexDM0** [comment]
Hi,

We expect 4.0 around the end of the month, 4.1 is still unknown.

Regards

**Comment by mmcsivakumar** [comment]
Thank You.
