### ISSUE TITLE
Is it possible to move the item on the timeline programmatically?

### ISSUE THREAD

**Issue by mast0r** [almende/vis#781]
Hi, 

I have a simple question: is it possible to manipulate the item on the timeline after it was drawn? 
Some items in my scenario could be changed in background after they were added to the timeline. So I want to move those items to the new time/group or remove/create using some javascript. 

Is there some native timeline functions I could use for that? Like a `moveTo(time [, options])` function of the timeline object.

**Comment by AlexDM0** [comment]
Hi,

You can use the vis dataset to dynamically update the data. Just update the item with a new start / end time.

http://visjs.org/docs/dataset.html

Regards,

Alex

**Comment by mast0r** [comment]
Thank you Alex, I will try it! 
(at the moment I am using timeline.setItems(items) to see an updated item info on the timeline)

**Comment by AlexDM0** [comment]
Take a look at timeline example 2, there a dataset is used to put in the data.

Regards,

**Comment by mast0r** [comment]
I've just tried it - works like a charm!

For others who faced the same challenge:

	items.update({id:     itemId, 
				  param1: value1,
				  paramX: valueX});

And the item will be updated "on the fly" on the limeline!
Thank you again :)

**Comment by AlexDM0** [comment]
Glad to hear it works!

Have fun using vis!
