### ISSUE TITLE
Hijacked events when using DOM element templates

### ISSUE THREAD

**Issue by LaundroMat** [almende/vis#782]
When using the timeline component of vis.js with a custom template that returns DOM elements (instead of a pure string) events on the form elements in the editable containers (that are rendered using the custom template) of the timeline are being hijacked.

Comments on [the related question on stackoverflow](http://stackoverflow.com/questions/29651781/how-to-prevent-the-vis-js-timeline-component-from-hijacking-events-while-using-d?noredirect=1#comment47487171_29651781) show that the problem lies with the way the template is [being compared to its previous state](https://github.com/almende/vis/blob/4514e8f2640623d0a41a68bf4f702c7753b7d12e/lib/timeline/component/item/Item.js#L180). 

Is this by design, or are you open to suggestions for improvement? There are two suggestions already (check [this comment on the same page](http://stackoverflow.com/questions/29651781/how-to-prevent-the-vis-js-timeline-component-from-hijacking-events-while-using-d?noredirect=1#comment47487171_29651781)).

Thanks for considering,

Mathieu

**Comment by josdejong** [comment]
Thanks, this should be fixed now on the `develop` branch

**Comment by LaundroMat** [comment]
On first sight this seems to be solved; thanks!
