### ISSUE TITLE
Possible inconsistency in Barnes Hut calculation

### ISSUE THREAD

**Issue by andymc33** [almende/vis#783]
Possibly an issue in BarnesHutMixin.js; the comments suggest that lines 57 and 78 should be duplicate code, but actually have different implementations:

57: distance = 0.1*Math.random();
78: distance = 0.5*Math.random();

I haven't fully fathomed the Barnes Hut simulation yet, so the above may be correct, just wanted to make sure.

**Comment by AlexDM0** [comment]
Hi, 

They are ment to be the same but essentially it really does not matter. That part is there to avoid division by 0 with distance is 0. That is not part of the official barnesHut algorithm, more of a practical fix. If you want to learn about barnesHut you could look at http://arborjs.org/docs/barnes-hut which I used to implement the algorithm.

Also for fun, you should look into uncommenting
https://github.com/almende/vis/blob/master/lib/network/Network.js#L2051

to see the quadtree.

Regards,

Alex

**Comment by andymc33** [comment]
Thanks for the link (and the hidden graphics!) - it really helped me with Barnes Hut.
I've been playing with the layout algorithm in .Net to try and leverage parallel processing - will let you know if I have something worth sharing - could be useful for anyone wanting to build a back-end "stabilisation service".

Andy

**Comment by AlexDM0** [comment]
You could just do that with phantom js ;) but a c implementation would be fun to speed it up.
