### ISSUE TITLE
Visible content in range-box

### ISSUE THREAD

**Issue by artaxa** [almende/vis#785]
When a range-box is not large enough to display all of it's content you only see the left part of the content, but when a range-box begins out of visible range you only see the right part of the content.

Is it possible to make the left part of the content be the longest visible part in both cases?

![schermafbeelding 2015-04-20 om 16 06 41](https://cloud.githubusercontent.com/assets/9129757/7233047/42cfc620-e77f-11e4-8646-06fb05406e9c.png)

**Comment by josdejong** [comment]
Makes sense to me to change the behavior to how you describe it.

**Comment by artaxa** [comment]
That would be awesome!
Do you know when you have time to do that?

**Comment by josdejong** [comment]
I think it's best to do this for v4, where we still have to do some changes/improvements related to this. I guess it will be done in "weeks" but I can't do any promise.

**Comment by josdejong** [comment]
This behavior has been changed as proposed by @artaxa in the `v4` branch of the project.

**Comment by artaxa** [comment]
Many thanks!!
