### ISSUE TITLE
Architectural Overview

### ISSUE THREAD

**Issue by lgrkvst** [almende/vis#786]
Hi,

I want to make a contribution to the timeline addon, however I find myself bumping into a motivational threshold as I'm unable to find an architectural overview of the code base. Surely I could spend 8 hours browsing through code, taking notes, but I would rather spend that time coding.

You wouldn't happen to have a simple SAD lying around? Any kind of logical view/sequence diagram would be helpful...

Keep up the good work!

**Comment by josdejong** [comment]
Thanks. We don't have any schematic overview of the code, sorry. Is there any specific question you have right now to get you on track?

**Comment by o-o-** [comment]
Hi again, thanks for quick response.

Ok, bear with me: I want to visualise events in which two parties interact — one party above the timeline and one party below the timeline. Consequently, the timeline would have to be centered in the chart.

The connections will intersect (behind) the timeline.

One such event affords multiple interactions between the two parties, and I want to visualise multiple such events.

The two parties could for instance be a client and a server passing messages between each other. If I were to get this far, the next step would be to add two line graphs of streaming data: One graph above the timeline 'bottom aligned', and one graph under the timeline 'top aligned' (they would consequently 'grow out' from the timeline), denoting for instance CPU load on each of the two parties.

For the record, never having seen such a graph, I think of it as a new way to visualize interaction.

**Comment by AlexDM0** [comment]
Hi,

I'm having a little trouble picturing this. What exactly needs to be added to the timeline for this to work? With graph, do you mean a graph2d graph? What role does the timeline play in this? I'm not sure I see where the timeline's items come into play. The top and bottom alignment are already in there and most of what you describe sounds like clever css work. If you're after merging the graph2d and the timeline, that's something we want to implement in the future and it would be awesome if you could pick that up!

Regards,

Alex

**Comment by o-o-** [comment]
This is what I'm looking for:

![Imgur](http://i.imgur.com/8Fflbyw.jpg)

**Comment by o-o-** [comment]
(oops, accidentaly clicked Close...)

**Comment by josdejong** [comment]
Thanks for the explanation, I get the picture now. 

Your use case is quite different from what Timeline/Graph2d offers. You can at least reuse the Core and TimeAxis (shared by both Timeline and Graph2d), but you will have to implement representation of your data (both items as well as the filled graphs) yourself, and do some adjustments such that the TimeAxis is displayed in the middle of two (new to build) data representation components. If you inspect the DOM that the Timeline creates, you will see that it contains 5 main panels (center, left, right, top, bottom) and three additional background panels. You could put your client data representation in the top panel, put a TimeAxis in the center panel, and create the server data representation in the bottom panel.

**Comment by o-o-** [comment]
Clever. If we disregard the filled graphs for a minute, what do you think about using groups for dividing between client and server data, having group1 drawn in the top panel and group2 in the bottom panel? 

That way everything would hang together when scrolling/updating, and also from a data structural point of view.

In that case, could you give me a quick start by pointing me to the files of interest?

**Comment by josdejong** [comment]
Hm, I think that `Group` is too coupled with `ItemSet` and with displaying a group label in the left panel, and contains way too much stuff not relevant for your case.

It should not be hard to create your own component here though. Every component created in the Timeline get a shared object `body` passed from the core (see [for example here](https://github.com/almende/vis/blob/master/lib/timeline/Timeline.js#L85)), this body object contains the dom elements of the panels (so you can add your own component to one of the panels), an event emitter (passing around events like user actions), and functions like `body.util.toScreen` and `body.util.toTime` to convert a date to a position in pixels on screen and vice versa. The base prototype of all components is here: [Component.js](https://github.com/almende/vis/blob/master/lib/timeline/component/Component.js), you need to implement for example a function like `redraw`.

**Comment by o-o-** [comment]
Thanks - I'll dive into it.

Out of curiosity - is there any reason in particular you're not basing vis on d3js?

**Comment by josdejong** [comment]
If you have more questions just let us know.

There is no special reason for not using d3. When we started these visualizations 4.5 years ago d3 wasn't the defacto standard that it is now though. Actually some time ago we discussed whether we could use d3 as drawing API instead of the HTML Canvas API, that could for example allow switching to SVG.

**Comment by AlexDM0** [comment]
Although canvas is faster for the network, as for the timeline, DOM gives more styling control than SVG.
