### ISSUE TITLE
Arc width varies with hovering or click

### ISSUE THREAD

**Issue by redskate** [almende/vis#788]
Hi Alex
Finally I deployed my app containing visjs (this is a demo app).
Unfortunately I have still some strange effects on the width of a line.
The with of an arc should signal a kind of "importance" for that arc. 
The width is set and renders without problems. BUT: When you hover on the arc, the arc gets very thin, then after clicked to the same arc, the arc gets quite bigger - and this without changing the attribute "width" - but just the color of the arc.

Here the snippet with my construction code (works well):
var edge = {
				  id: fromid+"-"+toid,
			            from: fromid,
			            to: toid,
			            color: edgecolor,
			            fontColor: edgelabelcolor,
			            title: titleedgeCorrelationRank,
			            style: "line",
			            label: rdata.rank + " ("+rnodes.length+"c)", // +" -> "+arcval, 
			            width: arcval,
			            data: {expandable:false, type:"rank", rank:rdata.rank}
			          };
data.edges.add(edge);

The app is under http://semweb.ch/leistungen/rdfservices/en-entitylinking/ - just start a correlation and click on one arc.
Any ideas? 

Thank you 
Fabio

**Comment by AlexDM0** [comment]
Hi Fabio,

Your app does not seem to work (or takes more than 5 minutes to analyse?). Maybe try increasing widthMax?

Regards,

Alex

**Comment by redskate** [comment]
Hi Alex

(thank you )
the app should be working (but still some things to fix).


Take the following text to be entity linked:
"Joseph Mallord William Turner 23 April 1775  19 December 1851 was an
English Romantic landscape painter, watercolourist and printmaker, whose
style can be said to have laid the foundation for Impressionism.
Although Turner was considered a controversial figure in his day, he is
now regarded as the artist who elevated landscape painting to an
eminence rivalling history painting."

Then go to Correlation Graph and press the button "Start Correlations".
In 42 seconds you get the graph.

Regards
Fabio



Am 22.4.15 um 11:09 schrieb Alex:

**Comment by AlexDM0** [comment]
Hi Fabio,

I think you need to add:

```
hoverWidth: arcval
```

to the edge options. Nice app btw :), it took me a while to understand why the network was changing all the time but the mouse over the words was the trick. Maybe a timeout there ;)?

Regards

**Comment by redskate** [comment]
Hi Alex 

thank you very much for hoverWidth. I did not catch that.
Thank you for your compliment. (nice) graphs should be used to represent graph information...

Regards
Fabio
