### ISSUE TITLE
How to create double click event and right click event? Need to display a popup on right click and double click.

### ISSUE THREAD

**Issue by shibdas2011** [almende/vis#790]
How to create double click event and right click event? Need to display a popup on right click and double click.

Any right click and double click event available like to select?

network.on('select', function(properties) {
				
});

**Comment by AlexDM0** [comment]
Yes there is a double click event. 
http://visjs.org/docs/network.html#Events

As for the right mouse menu, look at #743. Any discussion on the right mouse events can be done there. I'll close this issue as a duplicate. 

Regards
