### ISSUE TITLE
select item issue

### ISSUE THREAD

**Issue by almusawi** [almende/vis#791]
Hi,

I am trying to show and hide tooltip on each item. when the user select the item the tooltip will show, and if he selected again will hide the tooltip.
this is part of the code:

```js
function onSelect (properties) {  
			  $('.tooltip').tooltipster();
			}
			// add event listener
			timeline.on('select', onSelect);
```
with this code, when I select one of the items. the tooltips started to show on all the items by hover on them.

could you help me with that ?
Thanks in advance

**Comment by josdejong** [comment]
I'm not familiar with tooltipster. Can you make a jsbin demonstrating the issue?

**Comment by josdejong** [comment]
Is this still an issue?
