### ISSUE TITLE
Uncaught error when creating edge from non-existent node

### ISSUE THREAD

**Issue by dmayo3** [almende/vis#792]
1. Go to: http://visjs.org/examples/network/21_data_manipulation.html
1. Open Developer Tools and view the console
1. Click the 'Edit' button on the top of the canvas area
1. Click 'Add Edge'
1. Start dragging an edge from an empty spot in the canvas instead of from a node

You should see numerous errors appear in the developer console as you drag across the canvas. It seems to think you're trying to pan the canvas view to a different position.

It's no big deal if you ignore these errors, but it's not ideal if you're detecting and reporting these issues using a window.onerror handler.

Error trace:

    Uncaught TypeError: Cannot read property 'x' of undefined
    Network._handleOnDrag                                               vis.js:16973
    Network._onDrag                                                     vis.js:16914
    triggerEvent                                                        vis.js:29782
    dragGesture                                                         vis.js:29941
    triggerGesture                                                      vis.js:29491
    each                                                                vis.js:28717
    detect                                                              vis.js:29488
    doDetect                                                            vis.js:29184
    onTouchHandler                                                      vis.js:29119

**Comment by AlexDM0** [comment]
Hi,

In the upcoming 4.0 release the whole of the network has been rewritten. I tested it there and it is fixed. Thank you for notifying us!

Regards,

Alex

**Comment by dmayo3** [comment]
Hi

Thanks for the extremely quick response

I look forward to v4!

Cheers,
Dan

**Comment by AlexDM0** [comment]
With the launch of v4, this issue can be closed.
