### ISSUE TITLE
node style

### ISSUE THREAD

**Issue by vmeno** [almende/vis#793]
is it possible to have a diamond style node or rotate the square style

**Comment by AlexDM0** [comment]
You're in luck! V4.0 has the diamond shape. It will be released soonish. 

Regards,

Alex

**Comment by vmeno** [comment]
cool  soonish days or weeks ?

**Comment by AlexDM0** [comment]
We expect it in May.

**Comment by AlexDM0** [comment]
With the launch of v4, this issue can be closed.

**Comment by vmeno** [comment]
thanks alex -- is there a page on your site that tells the features added
in the v4 -- i could not find it


On Fri, May 22, 2015 at 7:57 AM, Alex <notifications@github.com> wrote:

> With the launch of v4, this issue can be closed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/almende/vis/issues/793#issuecomment-104653579>.
>



-- 
Vichu Menon

(314) 630 1104

**Comment by AlexDM0** [comment]
Hi, there is a history.md on our repo that lists most of it. There is also a blog post on our website with the changelog.

It has been a full rewrite so I may have forgotten some of the new things.
http://visjs.org/blog.html#V4Release

Regards
