### ISSUE TITLE
vetical scroll bar on timeline

### ISSUE THREAD

**Issue by Blugh** [almende/vis#794]
Hi guys

I know this has been asked for many times, where the timeline can display a scroll bar instead of the shadow in order to make scrolling more obvious and faster for a desktop user, as dragging with the mouse is cumbersome and slow. Is this enhancement still within the possibility of happening and if so, roughly when?

**Comment by AlexDM0** [comment]
Hi, 

It is still on the to-do list but at the moment we're prepping v4 which takes a lot of time. I cannot give an estimate for this. Feel free to do a pull req and help out :)

I'll close this issue as a duplicate.

Regards
