### ISSUE TITLE
Draw something above network graph use original canvas API?

### ISSUE THREAD

**Issue by rwu823** [almende/vis#795]
```js
network.on('stabilized', function (props){
    var canvas = $('#vis canvas')[0];
    var ctx = canvas.getContext('2d');
    setTimeout(function(){
        ctx.fillRect(25,25,100,100);
    }, 500)    
 });
```

Fine now. but when mouse hover on network, the rect was disappear. What is best practice for this case?

**Comment by AlexDM0** [comment]
This is not supported at the moment. It will be in 4.0. The problem here is that every time you do something to the network, zoom, drag, mouseover etc, the entire thing is redrawn.

**Comment by rwu823** [comment]
Hi Alex

Thanks, look forward to 4.0 release

**Comment by AlexDM0** [comment]
With the launch of v4, this issue can be closed. There is an example on this on the new website.
