### ISSUE TITLE
When the timeline with grouping is being scaled by a user dynamically, events are reordered without grouping blocks reordering

### ISSUE THREAD

**Issue by BurstX** [almende/vis#796]
This makes events move to other groups' lines.

**Comment by josdejong** [comment]
Thanks. Can you make a jsbin demonstrating the isssue? (I don't see this happening in examples like this one: http://visjs.org/examples/timeline/05_groups.html)

**Comment by BurstX** [comment]
I'm sorry. There was an error in my code. The component works perfectly.
