### ISSUE TITLE
Timeline Stacking tolerance

### ISSUE THREAD

**Issue by Svish** [almende/vis#797]
I'm making a timeline using visjs and a lot of the periods have close, but not overlapping, start and end dates. For example one item ends `2013-01-31` and the next begins `2013-02-01`. Currently the stacking feature places these on different lines, which makes the timeline very jumpy, like this:

    XXXX   XXXXXX       XXXXXX
        XXX      XXXXXXX

Is there a way, or could there be a way, to make the stacking feature only put periods on different lines if they are *actually* overlapping time periods?

**Comment by AlexDM0** [comment]
Hi,

I think you need to set the margins to 0.
http://visjs.org/docs/timeline.html#Configuration_Options

Regards,

Alex

**Comment by Svish** [comment]
Ah, tried that already, but it worked when I removed `overflow:visible` from the css class `.item.range`. Thanks!
