### ISSUE TITLE
Resetting the color attribute will produce an error

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#798]
Hi @ devteam,

I know you guys are all about 4.0 at the moment :) Still wanted to inform you, I discovered a bug using the current dist (3.12.0)

JSBin: http://jsbin.com/tutori/1

0. A color is assigned to the node. The assigned value is not an object but a rgbhex-color value.
1. Updating the node in the dataset: setting its color to null will cause an error as vis regards color as an object that also has a property background...
2. Result (console): Uncaught TypeError: Cannot read property 'background' of null

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

You can't set the color to null. I'm not sure if it's even possible to 'unset' a color once you've set it.
http://visjs.org/docs/network.html#Nodes_configuration

This is because the way javascript objects work. We inherit the prototype of the global option object but when you set your own key in that point, I dont think it can be deleted. (delete is forbidden in strict mode).

We currently do not support reverting back to the global value. You'll have to set it back yourself.

Regards,

Alex

**Comment by felixhayashi** [comment]
Hi Alex

> We currently do not support reverting back to the global value. You'll have to set it back yourself.

Thanks for being clear about that.

For some cases setting the property to null worked (e.g. the `fontColor` jumps back to black when setting it to null) so I thought you would support it for color as well.

I know color is interpreted vis-internally as object and not as string (unlike fontColor), but I thought you would somehow delete the subproperties and restore the original when I set it to null...

I guess I have to do as you say and *replace* the value with a default.

Thanks
Felix

**Comment by AlexDM0** [comment]
Hi Felix,

I would assume that the canvas default color for font is black so if the color is null it gracefully gives you black :).

Regards

**Comment by felixhayashi** [comment]
> I would assume that the canvas default color for font is black so if the color is null it gracefully gives you black :)

I guess I was mislead then :) I solved this problem now by always specifying a default to prevent an error if the user decides to remove his color for the wiki article (which, annoyingly, may always happen even when the graph is already drawn).

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

In 4.0 you will be able to use undefined and null to revert back to the default value.

Regards,

Alex

**Comment by felixhayashi** [comment]
Yay! :D Thanks for informing me @AlexDM0
