### ISSUE TITLE
[Suggestion -  feature request] Collapse / expand child nodes

### ISSUE THREAD

**Issue by tinchox5** [almende/vis#799]
Hi, I believe that it is not possible to expand or collapse child nodes on click, but It would be a nice feature tu implement. 
Thank you

**Comment by AlexDM0** [comment]
Hi,

What do you mean with collapse and expand? Could you elaborate?

Regards,

Alex

**Comment by tinchox5** [comment]
Sorry, If I have a network graph with one visible node, I want to click on that node and then their child nodes appear. If I click again in the original node then thier child nodes collapse again.

**Comment by AlexDM0** [comment]
Hi,

This is already possible. The technique is using a vis Dataset to contain the data. 

Listen to the click event (or select). When this happens, push the required nodes into the dataset and you're done. 

Regards

**Comment by tinchox5** [comment]
Thank you very much Alex!!!

**Comment by tinchox5** [comment]
Alex I think it would be nice to add this kind of example to the network gallery

**Comment by AlexDM0** [comment]
Hi,

Take a look at the dynamic data example. That's pretty much it. 

Regards

**Comment by tinchox5** [comment]
Alex, I saw that example, but that explain how to add new elements and what I really want is show or hide nodes that already exists. This example is what I need to implement with vis.js http://bl.ocks.org/mbostock/1062288 . I sure that it is possible. Thank your very much for your time!

**Comment by AlexDM0** [comment]
Hi,

in psuedo code:
```
nodes = new vis.DataSet([ array of node objects]);
edges = new vis.DataSet([ array of edge objects]);

data = {nodes:nodes,edges:edges}

network = new vis network(data)

network.on('select',function (data) {
 if (data.nodes.length > 0) {
  var nodeid = data.nodes[0];
  var connectedNodes = network.getConnectedNodes(nodeid);
  nodes.remove(connectedNodes);
 }
}
```

That should do it. You may need to fiddle with the datatypes a little but that should do exactly what you want. If you want to show them on click as well, keep a seperate dataset to update the nodes dataset with the nodes you want to add again.

In v4 you'll get a hidden and physics boolean which will be a lot easier to work with.

Regards,

Alex

**Comment by tinchox5** [comment]
Thank you I'll try!
