### ISSUE TITLE
Request a new feature 

### ISSUE THREAD

**Issue by mojtabashahi** [almende/vis#80]
Hi

I am using vis.js in Qml, writing a wrapper on vis.js in qml.
A feature that i need here is some like Groups but i need to have a boundary around my node groups.

![group](https://cloud.githubusercontent.com/assets/2108850/2627848/7e63e444-be15-11e3-9d59-29e2a15c5d7e.png)

Thank you
moji

**Comment by mvnagy** [comment]
Hi

Could you please reconsider implementing this feature?
Both myself, and others would see this very useful.
(http://stackoverflow.com/questions/26703717/bordered-group-of-nodes-in-a-network-graph)

I really like VisJS and would prefer to not switch entire framework for just having the option of a drawn boundary.

Best,
Martin
