### ISSUE TITLE
getGroup issue?

### ISSUE THREAD

**Issue by Blugh** [almende/vis#800]
Hi guys

not sure if this is an actual bug, or just because of the where I have added the timeline in my UI. but here is my explanation:

1. When I double click to add an event, it appears a few groups above the group I actually clicked on.
2. I noticed that this happens when there is a vertical scroll bar for the page.
3. I found the line of code which is causing the "issue" for me. It the line:
var clientY = event.gesture ? event.gesture.center.clientY : event.clientY;
in the method:
 ItemSet.prototype.groupFromTarget = function(event) {
4. I changed the first line to be:
var clientY = event.gesture ? event.gesture.center.pageY : event.pageY;

Things are now working again, but I am worried this is more an issue of my page layout (my timeline is embeded in quite a few elements) than an actual bug in vis?

Let me know your thoughts.

**Comment by josdejong** [comment]
This sounds like the same issue as #708, which was fixed in v3.12.0. 

Is this issue still the case in your app using v3.12.0?

**Comment by josdejong** [comment]
Is this still an issue?

**Comment by Blugh** [comment]
not an issue any more, version 12 is correct.
