### ISSUE TITLE
Cant display timeline in my nodejs

### ISSUE THREAD

**Issue by ufukgarip** [almende/vis#803]
I am quite new on web applications so sorry if i asked any silly things but i generate a nodejs project and i installed visjs module on my project and i want to display timeline but when i run it timeline doesnt seem.I follow this http://visjs.org/docs/index.html

**Comment by josdejong** [comment]
node.js is server side javascript, it has no user interface. You can only create a Timeline in a browser.

**Comment by ufukgarip** [comment]
thanx for your answer,i got some data from nodejs project and i want to display this data in timeline how can i achieve this do you have any suggestion?

**Comment by josdejong** [comment]
You can use for example [express.js](http://expressjs.com/) to create a node.js web application. There is plenty of documentation and tutorials on the internet about this but I guess you have some learning to do. It's fun though :)

**Comment by ufukgarip** [comment]
thank you for your suggestion and help

**Comment by josdejong** [comment]
You're welcome
