### ISSUE TITLE
Directive for Graph3d with AngularJS 

### ISSUE THREAD

**Issue by guesmiTalan** [almende/vis#804]
Good morning , i'm trying to create a new angularJS directive  to attach a vis Graph3d chart 
http://visjs.github.io/angular-visjs/ here i didn't find what i need , any help to get it ?

**Comment by josdejong** [comment]
Graph3d is indeed still missing in angular-visjs. You can open a feature request for this at https://github.com/visjs/angular-visjs/issues .
