### ISSUE TITLE
Error with Drawing The dataSet with graph3d 

### ISSUE THREAD

**Issue by guesmiTalan** [almende/vis#805]
This is the result but i dont understand what is the issue unless my correct dataSet structure 
![error](https://cloud.githubusercontent.com/assets/11075994/7337854/a8935a66-ec30-11e4-97ba-d1eb8c57d2d6.PNG)

**Comment by AlexDM0** [comment]
Hi,

You give us nothing to go on. Could you provide the code with a jsbin?

Regards

**Comment by guesmiTalan** [comment]
Good Morning Alex , i found the error this is the result 
![success](https://cloud.githubusercontent.com/assets/11075994/7345327/79569f88-eccb-11e4-99d0-fa2a9eab5a4b.PNG)
But how can  i modify the Y axis to be bigger , and an other question does the dataSet support more than 5000 items? I'm working on financial values

**Comment by josdejong** [comment]
The DataSet can contain as many items as you like, but at some point drawing everything on screen becomes slow (also depending on the computer and browser that you use). This example shows in the order of 2600 data points: http://visjs.org/examples/graph3d/example02_camera.html

In the docs you can find how to adjust the axes: http://visjs.org/docs/graph3d.html#Configuration_Options

**Comment by guesmiTalan** [comment]
Thank you i found the solution this is the result, it's a financial graph for Implied Volatility
![finalsuccess](https://cloud.githubusercontent.com/assets/11075994/7367711/70ae3066-ed99-11e4-9422-10da0a00e4bb.PNG)

**Comment by josdejong** [comment]
So you found the option `keepAspectRatio` :)

Great it's solved now.

**Comment by guesmiTalan** [comment]
Yess thank you very much Sir
