### ISSUE TITLE
How can I save Network as an image?

### ISSUE THREAD

**Issue by Deceiv** [almende/vis#806]
Is there way to save the entire graph as an image file, regardless of the current zoom?

**Comment by josdejong** [comment]
In browsers like Chrome and Firefox, you can right click on a Network and click "Save image as...". 

If you mean whether you can save it as a vector image, that's not possible as Network uses HTML Canvas (bitmap based), unlike for example SVG.

**Comment by Deceiv** [comment]
No, "Save image as..." not what I meant. 
I work with a large graph, and if I press "Save image as...", I get a small picture ([1] for example) in which nothing is visible. I need to graph nodes in the image were readable, as in the picture ([2]). 
If I zoom image in the browser, it will save only the part that is visible at the moment on the screen, but I need the whole graph.
P.S. Sorry for my english.

![1](https://cloud.githubusercontent.com/assets/12132051/7370642/30b94bf0-edc4-11e4-827f-1a02c2471c95.png)
![2](https://cloud.githubusercontent.com/assets/12132051/7370645/34d0d9ce-edc4-11e4-89af-cffc96372367.png)

**Comment by AlexDM0** [comment]
That is not possible at the moment. Though I suppose you could just make the network very very large before doing a save as?

Regards,

Alex

**Comment by Deceiv** [comment]
Ok, thank you for your answers.
