### ISSUE TITLE
Multiple BandInfo

### ISSUE THREAD

**Issue by EnergyTeam** [almende/vis#807]
Hello,

I need a multiple-band info  selections at different times in TIMELINE.
For example, a grouping monthly and an annual

Below is the link to which I refer:
http://www.simile-widgets.org/timeline/examples/jfk/jfk.html

Is it possible?

Thank you for the attention.

**Comment by josdejong** [comment]
Yes this is possible, though it's no build in feature. 

You can just create two timelines, and couple moving/zooming in the two timelines by listening for `rangechange` events and update the other timeline accordingly. You could provide both timelines with the same or with a different DataSet, the annual one could show a more course grained view of the data, whilst the montly one could show all details.

**Comment by almusawi** [comment]
Hi all,
Josdejong thanks for this library.
EnergyTeam, you have a great timeline:). I have a question for you. would it be possible to tell me which library you have used to make these nice tooltips for your time line and how you use it?
Thanks in advance,

**Comment by AlexDM0** [comment]
Hi,

The tooltips used in vis are just DOM objects and JavaScript. There is no library being used. 

In short on the technique, you make a div using JavaScript, assign it a CSS class, position it where you want (CSS position is absolute) and fill it with the required content. 

Almost all of the vis functionality is custom made, without libraries. 

The ones we do use are:
Hammerjs for touch events
Keycharm for keyboard events
Momentjs for handling dates. 
Emitter for events 
UUID for ids

Regards,

Alex
