### ISSUE TITLE
Feature Request: differentiate the rangechanged() event between manual range changed and scripted range changed

### ISSUE THREAD

**Issue by AntoniusGolly** [almende/vis#809]
I would like to capture interactions with the timeline by using the rangechanged() event when users interact with the timeline directly. However, the same event is fired when I have some auto advance function running that updates the position automatically. Is there a way to differentiate between these to types of range change?

**Comment by AlexDM0** [comment]
Hi,

Is the byUser boolean not precisely what you mean?

http://visjs.org/docs/timeline.html#Events

Regards,

Alex

**Comment by AntoniusGolly** [comment]
Oh, genius. Thanks so much, that improves the user experience alot!
Sorry for not noticing.

BTW: this is a great plugin. I am absolutely fascinated of the speed of plugin. Also with many items it's still fast! Thank you so much.

**Comment by josdejong** [comment]
Thanks, great to hear you like it :)
