### ISSUE TITLE
resize container

### ISSUE THREAD

**Issue by uniserpl** [almende/vis#810]
I increase the size of the Network's container by jQuery-animating and get a blurred image.
Also network.redraw() does not see this changes

**Comment by AlexDM0** [comment]
Hi,

This could be fixed in the 4.0 branch but without a code example I cant be sure.

Regards,

Alex

**Comment by uniserpl** [comment]
code example: http://jsfiddle.net/Uniser/7t4xd9rm/2/

**Comment by AlexDM0** [comment]
Hi,

Actually, by uncommenting the code redraw,  the code works as required, except it isn't really what you may expect. So what is happening here? You increase the size of the canvas. Let's for the mental picture do this instantly. You now have added "more space" for the visualization. Like if you have a small image and add white space right and bottom. 

The nodes have a size. When zoomed to scale 1.0, this size is the same in canvas units as it is in pixels. If you increase the size of the canvas and you want to also increase the size of the nodes, you'll have to zoom in. Restore the ratio between canvas space and screen space. In our API we give screen space the name DOM space. 

Here is your fiddle fixed (only one way, I'm on mobile and coding on mobile is tricky :))

http://jsfiddle.net/7t4xd9rm/3/

We could argue whether this is the preferred situation but I think it's use case dependent. 

Regards,

Alex

**Comment by uniserpl** [comment]
Many thanks!

**Comment by AlexDM0** [comment]
Youre welcome :) have fun using vis!
