### ISSUE TITLE
Network, Hierarchy view. Not all nodes are initially visible in view

### ISSUE THREAD

**Issue by DmitriyPogorelov** [almende/vis#812]
Hi,

We use network graph in hierarchy view mode with "direction" option. We use SVG to draw nodes. Hierarchy levels are assigned manually. When there are few nodes with no connection to each other and all of them are on level 0 (so they are stacked vertically), than, depending on the screen size, only the central node is visible and others are not. However other nodes are actually partially in the view. So, when do some minimal changes to layout - like, for example, drag the canvas a bit - than those nodes suddenly appear (they fit partially). It looks like library is not able to determine properly that node is partially in the view and should be visualized.

Here are our options:

   var options = {
            stabilize: true,
            smoothCurves: false,
            dragNodes: false,
            hover: true,
            width: container.clientWidth + 'px',
            height: container.clientHeight + 'px',
            edges: {
                style: 'arrow',
                fontFill: '#F4F4F4',
                fontSize: 18,
                hoverWidth: 2,
                widthSelectionMultiplier: 3
            },
            hierarchicalLayout: {
                levelSeparation : 450,
                nodeSpacing: 200,
                direction: 'LR',
                layout: 'direction'
            },
            physics: {
                hierarchicalRepulsion: {
                    nodeDistance: 200,
                    centralGravity: 0,
                    springConstant: 0.1
                }
            }
        };

Thanks!

**Comment by AlexDM0** [comment]
Hi Dmitriy,

This should be fixed by the 4.0 release. If you manually call a zoomExtent does it also not show it correctly?

The options here are not the issue, it is likely the SVG images. As the size options have been revamped with the 4.0 rewrite I think it should be fine there.

We expect 4.0 within one or two weeks.

Regards,

Alex

**Comment by DmitriyPogorelov** [comment]
Thanks for reply! Unfortunately, zoomExtent is not an option for us as we want to display with 100% zoom by default. If there are too many nodes and they do not fit into the view with 100% zoom - we are fine with that, user has to navigate or zoom himself.

This is how we do that:

        var network = new vis.Network(container, {edges: edges, nodes: nodes}, options);

        network.moveTo({
            position: {
                x: network.getCenterCoordinates().x,
                y: network.getCenterCoordinates().y
            },
            scale: 1
        });

**Comment by AlexDM0** [comment]
Hi,

I see, I misunderstood your issue. The viewable area coud be an issue here with certain nodes. I'll see if this is still the case in 4.0.

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi Dimitriy,

In 4.0 we use a bounding box instead of the measurements of the node object, which should be more accurate. If you still experience this problem after the release of 4.0, please let me know.

Regards,

Alex

**Comment by DmitriyPogorelov** [comment]
Thanks for help!

**Comment by say8425** [comment]
I have similar issue, and it's not solved yet.

**Comment by AlexDM0** [comment]
Hi Cheon,

I assume you removed your comment because the issue is solved? If not,
please make a new issue.

Regards,

Alex

**Comment by say8425** [comment]
Sorry I mistook.
It works well. Thanks.


펭귄 좋아하는 개발자
Cheon Park
010-2834-5105
