### ISSUE TITLE
Are there a possibility to navigate nodes in network graph with use of only keyboard?

### ISSUE THREAD

**Issue by DmitriyPogorelov** [almende/vis#815]
Hi,

We are looking for a way to traverse nodes in network graph with keybord. I.e. pressing "Up" should select a node on top of currently selected node. Not just moving a view, but selecting a node on top of current one.

Are there something like that in library already? That would be awesome!

Thanks.

**Comment by AlexDM0** [comment]
Hi Dimitriy,

That is not possible. The simple explanation would be that any developer can have any idea on what to do with which key. That makes it not possible for us to facilitate this. You can however use keycharm (https://www.npmjs.com/package/keycharm) yourself to listen for keyboard events. We use it in vis as well. You can then bind your own behaviour to the keystrokes. 

For your example you can listen to the event of the up arrow and do the following (in pseudo code):

```
function selectUp() {
 var selection = network.getSelection();
 var selectedNodeId = get selected node from the selection var
 var connectedNodes = network.getConnectedNodes(selectedNodeId);
 var nodePositions = network.getPositions(connectedNodes);
 for all node positions in nodePositions {
   var heighestNode = get highest node
 }

 network.selectNodes([heighestNode]);
}

```

Cheers

**Comment by DmitriyPogorelov** [comment]
Thanks a lot for help. It is amazing how helpful and fast your responses are.

**Comment by AlexDM0** [comment]
You're welcome! Enjoy using vis!
