### ISSUE TITLE
Option to disable scientific notation of numbers on y axis

### ISSUE THREAD

**Issue by Golovior** [almende/vis#816]
I'm working with the graph2d part.
Now i do not want scientific notations of numbers on the y axis. As far as I could find, there are no options to disable this.

Is this possible (in the future)? If not (now), what is the best place to make a small adjustment to the code?

**Comment by AlexDM0** [comment]
Hi,

This will be possible in the 4.0 release. We will release 4.0 in the next 1 - 2 weeks.
If you really want a quick fix, 

https://github.com/almende/vis/blob/master/lib/timeline/DataStep.js#L194

remove the toPrecision with something suiting your usecase.

Regards,

Alex

**Comment by Golovior** [comment]
Thank you very much. For the fast and right answer, and the fact you just made multiple people very happy.
