### ISSUE TITLE
Moving selected range items and hiddenDates.

### ISSUE THREAD

**Issue by AdrianNowik** [almende/vis#817]
Hi,
I have set hiddenDates option and when i'm moving range item between one day and next one, when hiddenDates are set for example from 5th may 20:00 to 6th may 8:00, I can still move item to dates:
start: Wed May 06 2015 05:00:00 GMT+0200 (CEST)
end: Wed May 06 2015 09:30:00 GMT+0200 (CEST) 
But half of this range item is hidden. I just wanna to ask You, if it is possible to make range items to move    only on shown on timeline dates/hours ?

**Comment by josdejong** [comment]
Thanks, we should indeed improve on this. Would be nice if the range items would "jump" over hidden periods, while keeping their width.

**Comment by AdrianNowik** [comment]
Thanks for Your reply, till this time i was working to convert these dates by calculated offset by my backend, and in my database it works fine, but when i send these dates by json to my javascript and want assign them item in my javascript, like this:
item.start = data['start']
item.end = data['finish']
Item's dates are changed but when i call callback(item) it is drawing on timeline with old, not converted dates. I assume that drawing item after move, does not take dates from 'item' sent in callback ?

**Comment by josdejong** [comment]
Yes that should work. You can use event listeners `onMove` or `onMoving` for that. The example http://visjs.org/examples/timeline/08_edit_items.html demonstrates this (moving items is limited within the month April).

**Comment by AdrianNowik** [comment]
Yeah, I used that already, thanks for help.

**Comment by josdejong** [comment]
There is only the method `timeline.redraw()` which forces a redraw of all contents in the Timeline.
