### ISSUE TITLE
Is it possible use Font-Awesome on edge's label?

### ISSUE THREAD

**Issue by rwu823** [almende/vis#819]
```js

var options = {
  // ...
  edges: {
    fontFace: 'FontAwesome'
  }
};


var edges = {
  from: 1,
  to: 2,
  label: '\f000'
}
```

[Font-Awesome] (http://fortawesome.github.io/Font-Awesome/)

Or some ways generator icon on edges?

**Comment by AlexDM0** [comment]
Hi,

As long as you say that your fontFace is 'FontAwesome', I don't see why not :).

http://jsbin.com/gamonimufe/1/edit?html,output

Regards,

Alex

**Comment by AlexDM0** [comment]
edited:

the settings you supplied actually just work, did you try it? :)

http://jsbin.com/lobifomake/2/edit?html,output

It could be that the css is not loaded (you will have to include the fontawesome css!!) and you will see []. Thats why I put the redraw in the jsbin.

Cheers
