### ISSUE TITLE
[Network] Does have API Documentation for new vis.DataSet()?

### ISSUE THREAD

**Issue by rwu823** [almende/vis#820]
as the title

**Comment by josdejong** [comment]
Yes, sorry it's a bit hard to find:

http://visjs.org/docs/
http://visjs.org/docs/dataset.html
http://visjs.org/docs/dataview.html

**Comment by AlexDM0** [comment]
Here you go.

http://visjs.org/docs/dataset.html  from http://visjs.org/docs/index.html

We will remove the http://visjs.org/docs/index.html and put the dataset on the homepage soon
