### ISSUE TITLE
color.highlight doesn't work for edge 

### ISSUE THREAD

**Issue by nathalizator** [almende/vis#822]
Hello
i have trouble to set the color.highlight of my edge in var_option, the thing i want is to set the edge of my group 'realite augmente' in 'red' color.
More over, even when i try to put that color.highlight:'red', in edges:{}, is not even working, nothing even appear. 

Here is my code : 
var options = {
  
edges: {
    color: '#9c9b9b',
    style: 'arrow-center',  
    width: 1,
    length: 50,
  },
  
  nodes: {
    fontFace: 'maisonneue-demi',
    fontColor:'#000000',
    fontSize:'6',
    }, 
    
    
  groups: {	
  realite_augmente: {
    fontColor: '#4160f4',
    color:'#4160f4',
   color.highlight:'red',
  },
      },

Am i doing something wront?

**Comment by AlexDM0** [comment]
Hi,

The groups are for nodes only. We currently do not use groups for the edges. 

Regards,

Alex

**Comment by nathalizator** [comment]
Thanks you for your answer, is there anyway to set the color of the edge in my group?

**Comment by AlexDM0** [comment]
Hi,

Well no, the edges do not look at the groups. You can use the inheritColor option to colour the edges according to the border color of the nodes. Alternatively you can just give the edges individual colours. 

Regards,

Alex

**Comment by nathalizator** [comment]
thanks you for your answer. i'm going to use the second option.

**Comment by AlexDM0** [comment]
You're welcome :) have fun
