### ISSUE TITLE
set color of svg icon node

### ISSUE THREAD

**Issue by nathalizator** [almende/vis#823]
hello,
is there any possibility to set the color of the node icon ( svg ) ?

**Comment by AlexDM0** [comment]
Hi,

I'll assume you're using an SVG image with the shape 'image'. If that is the case then no, full definition of the color and the shape are in the SVG file and vis just uses it as a color. 

If you are referring to shape 'icon', then yes, there is a color option for that called iconColor. I see this is mistakenly called color in the docs. Well fix that. 

For more information take a look at the icon example on our website. 

Regards,

Alex

**Comment by nathalizator** [comment]
Yes i'm using the shape 'image' sadly... 
Is there any possibility to set my own icon with shape 'icon' ? Because, what i understand is that i need to use icon from FontAwesome or Ionicon ?

**Comment by AlexDM0** [comment]
That's right although in principle it should work with similar packs as well. Include the CSS and set the fontFace. 

We cannot change the image naturally (by definition of 'image') but you could preprocess them and inject the color tag.

Cheers

**Comment by nathalizator** [comment]
Thanks you for your answer :)
