### ISSUE TITLE
Vertical labels are misaligned when printing on several pages

### ISSUE THREAD

**Issue by laurentopprecht** [almende/vis#825]
When printing on several pages the alignment between vertical labels and content is lost.
This starts on the second page.

Version 3.5.0
Tested on chrome
Component timeline

**Comment by AlexDM0** [comment]
Hi,

We're on version 3.12 at the moment... Is it also the case there?

Regards,

Alex

**Comment by laurentopprecht** [comment]
Hi,
I checked with the latest version. 
It looked fine now.

**Comment by laurentopprecht** [comment]
I tried with a different set of data and unfortunately the problem still exists

**Comment by AlexDM0** [comment]
I don't suppose you could provide said data? Truth be told I dont really think there is anything we can do about this. It's not like there is a onPrinting event and it's not our usecase to provide static modules. Can this be reproduced in a browser without printing?

**Comment by josdejong** [comment]
This may be related to how the print functionality of the browser mangles the HTML page to make it suitable for printing. I don't think there is anything we can do about it in the Timeline itself.

You could have a look at http://phantomjs.org/ to export an HTML page to pdf, png, or other image formats.

**Comment by laurentopprecht** [comment]
I am afraid I cannot provide the data but it seems the problem appears when there is a mix of lines with one item and lines with several items. You can reproduce in chrome through print preview. Note that emulation with css media = print does not work.

The issue seems connected to the HTML structure with both labels and data being divided in columns rather than rows. Honestly I am not sure this bug but would warrant a change in the data structure just for the sake of printing. 

As for phantomjs I am afraid this is a bit of an overkill.

**Comment by josdejong** [comment]
I don't think we can do anything about this in vis.js.

One last option would be for you to create your application in a paginated way, but besides that I'm out of ideas.

**Comment by yotamberk** [comment]
@labianchin Is this problem still relevant?
