### ISSUE TITLE
How can make group network like network example 27[world cup network]

### ISSUE THREAD

**Issue by say8425** [almende/vis#826]
Hi. I made a group network and it's huge mess.

But the group [example 27-world cup network](http://visjs.org/examples/network/27_world_cup_network.html) looks pretty clean. So I look into the source, but the x,y position of each nodes is manually inputed.

So I have a question. How can calculate this x,y position? The vis.js have that feature? Or I must get some external library? Thank you for reading.

**Comment by AlexDM0** [comment]
Hi,

You can play with the physics settings to change the way the network behaves and moves. Example 27 was exported from gephi by a member of the community. The nodes have been positioned there. 

Regards

**Comment by say8425** [comment]
Thanks. Gephi is good tool.
But I can not understand how can I get that positioned node with only changing physics settings.
I know that physics setting can not position the nodes and groups. Please more explain to me?

**Comment by AlexDM0** [comment]
Hi,

You can turn on the configuration with configurePhysics:true in the options. 

With this you can tweak the interaction. That does not mean you get the exact same result. It could be that you have to alter the mass of certain nodes to give them a higher gravitational repulsion, for instance the nodes with a lot of edges can be heavier?

Gephi uses forceAtlas2 to solve the network, we use barnesHut. I wouldn't recommend the other solvers for a large network. 

Regards,

Alex

**Comment by AlexDM0** [comment]
I've just added an extra solver that takes some of the force distributions from forceAtlas2, maybe that will help you getting the result you want. It'll be available with the next version of vis.

Cheers

**Comment by say8425** [comment]
Thanks! I'll expect it.

**Comment by AlexDM0** [comment]
Hi,

we have released v4 today. Have fun playing with the new physics solver :)

I'll close this issue as you ahve a very similiar one also open. If there's anything else on this specific subject, please let me know on that issue.

Cheers
