### ISSUE TITLE
[Network] How to disable edge's hover color and node's font bold?

### ISSUE THREAD

**Issue by rwu823** [almende/vis#827]
But still enable `hover` event.

I had set the same color, but still different.
```js
var options = 
{
    edges: {
        color: {
            color: '#666',
            hover: '#666',
            highlight: '#666'
        }
    }
}
```

**Comment by AlexDM0** [comment]
Hi,

For the edges I assume it is the hoverWidth option that would do it for you?

The nodes bold font cannot be disabled. 

Regards

**Comment by rwu823** [comment]
Hi Alex, `hoverWidth` is helpful for me. but still wish get an option to disable node's font bold.

**Comment by AlexDM0** [comment]
Hi,

In your case I'd actually disable hover. You can set the tooltip delay to 0 and use that for the hover. In 4.0 tooltips also generate events so you can use those. 

Would that solve the problem?

Regards

**Comment by rwu823** [comment]
Sorry, I can't understand how tooltip uses? any examples? And is 4.0 stable?

**Comment by AlexDM0** [comment]
Hi,

Tooltips are being used in this example for instance:
http://visjs.org/examples/network/12_scalable_images.html

If you hide the tooltip with css, you will get an event on mouse over where the tooltip WOULD have come up.

4.0 is not stable at the moment. We hope to release it around next week.

Regards,

Alex

**Comment by ryoqun** [comment]
> 4.0 is not stable at the moment. We hope to release it around next week.

wow! I'm really looking forward to it. :)

**Comment by AlexDM0** [comment]
You can look through the documentation on the v4 branch if you want, we could use some proofreading on the new format :) Network, timeline and graph2d have been updated, allthough it still needs some unifying css.

**Comment by rwu823** [comment]
Hi Alex,  Thanks for eager to answer :D

**Comment by AlexDM0** [comment]
You're welcome, good luck with the tooltips :)

**Comment by AlexDM0** [comment]
With the release of v4 I think this can be solved by my suggestion. 

Cheers
