### ISSUE TITLE
Custom Node order in hierarchical or other layouts

### ISSUE THREAD

**Issue by Ratbew-Webstars** [almende/vis#828]
Visjs Dev Team,

We used the visjs for an hierarchical family tree. The graph features simplified the implementation of family tree relations and develop us wrapper function for find various relations ship queries ( All fathers in  a generation, all hierarchical childs to a node like many)
The only constraint, now we face in arrangement of nodes. 

For a Case A is father and has B,C are childs
1.A->B,C
Now we add a spouse D and want to position it in between B and C like
2.A->B-D,C
If there is any solutions already avail, kindly suggest it.

Thanks.

**Comment by AlexDM0** [comment]
Hi,

In the next version you can specify the x and y position and one of them (depending which direction your layout is) will be taken into account. With that you can do this. At the moment this is not possible.

We expect the next 4.0 release around next week.

Cheers

**Comment by AlexDM0** [comment]
We have just released v4, which allows you to specifiy the position of the new node.

regards
