### ISSUE TITLE
Network problem Mootools.

### ISSUE THREAD

**Issue by aristotle8** [almende/vis#829]
Hi, thank you for great library.
Please help, i have problem with Network when mootools is loaded. Edges are invisible. when you zoom +/- they are visible again. but after animation they disappear again.

**Comment by aristotle8** [comment]
![g1](https://cloud.githubusercontent.com/assets/6046875/7593917/2a61d592-f8ff-11e4-8a88-55638fbb04f5.jpg)

**Comment by AlexDM0** [comment]
Hi,

Could you make a jsbin to show this? I do not know mootools..

Regards

**Comment by aristotle8** [comment]
http://jsbin.com/simemo/1/edit?html,output

**Comment by AlexDM0** [comment]
Hi,

Thanks for the jsbin! On my phone I see the edges, are they hidden on your device when viewing the jsbin?

This makes it seem like a browser issue, could you give me details on your device/os/browser?

Regards

**Comment by aristotle8** [comment]
i have checked with Mozilla Firefox(37.0.2), and Chrome(42.0.2311.135) browsers

**Comment by aristotle8** [comment]
if i remove Mootools from header, everything works perfect.

**Comment by aristotle8** [comment]
PC, Windows 7, Mozilla Firefox(37.0.2), and Chrome(42.0.2311.135) browsers

**Comment by AlexDM0** [comment]
Hi,

I've looked into this.. and I feel kind of violated. Mootools alters nearly ALL native objects which is pretty much on the top of the "do not ever do" bad practices list.

It (and appearently only the compat version) ruins something in the native javascript function bind mechanism.

You can fix this like so:
http://jsbin.com/tugeqipabi/1/edit?html,output

Alternatively you can use:
https://cdnjs.cloudflare.com/ajax/libs/mootools/1.5.1/mootools-core-full-nocompat.js

I do not plan to alter vis to fix their vile alterations of native objects. 

Regards,

Alex

**Comment by AlexDM0** [comment]
On the up side, it seems to be working with the upcoming v4 release.

Regards,

Alex

**Comment by aristotle8** [comment]
Thank you very much Alex.

 I have put this code before drawing graph:

Function.prototype.bind = function(oThis) {
      if (typeof this !== 'function') {
        // closest thing possible to the ECMAScript 5
        // internal IsCallable function
        throw new TypeError('Function.prototype.bind - what is trying to be bound is not callable');
      }

      var aArgs   = Array.prototype.slice.call(arguments, 1),
        fToBind = this,
        fNOP    = function() {},
        fBound  = function() {
          return fToBind.apply(this instanceof fNOP
              ? this
              : oThis,
            aArgs.concat(Array.prototype.slice.call(arguments)));
        };

      fNOP.prototype = this.prototype;
      fBound.prototype = new fNOP();

      return fBound;
    };

**Comment by AlexDM0** [comment]
Hi,

I... really don't know why you would want to custom implement your bind function. Just leave it as - is. Take the native one. This seems like a very ugly solution... but hey! if it works for you, do your thing :)

Regards
