### ISSUE TITLE
Hiding time axis

### ISSUE THREAD

**Issue by AdrianNowik** [almende/vis#830]
Hi again,
i don't know if it is right place to ask, but i'm wondering if it is possibility to hide time axis ? I know that i can use orientation with arguments: 'top', 'both', 'bottom', but i want to hide it, is it possible ?

**Comment by AdrianNowik** [comment]
I just made that with css,   
.timeaxis.foreground{
    display: none;
  }
did what i wanted. After that timeline is resizing well also, btw. thanks for very good, useful library ;)

**Comment by AlexDM0** [comment]
Hi Adrian,

I'm glad you managed to fix it! @josdejong wasn't there another way to hide the time axis? I couldn't find it in the docs. 

Regards,

Alex

**Comment by josdejong** [comment]
@AlexDM0 yes you can do:

```js
timeline.setOptions({
  showMajorLabels: false, 
  showMinorLabels: false
});
```
