### ISSUE TITLE
[Timeline] Selection lost when end time added/removed

### ISSUE THREAD

**Issue by rs017991** [almende/vis#831]
Hej,

I've noticed that my items become deselected whenever the end date is added or removed.

This doesn't happen when other properties (content, etc...) are changed.

I've thrown together a fiddle to demonstrate this issue:
http://jsfiddle.net/jddagev2/2/

I have observed this behaviour in the v4 branch as well.

Thanks for everything you do! =D

**Comment by josdejong** [comment]
Thanks for your clear jsfiddle, that helped a lot. This has been fixed in the `v4` branch (though the files in `./dist` aren't yet updated)
