### ISSUE TITLE
Height of groups

### ISSUE THREAD

**Issue by AdrianNowik** [almende/vis#834]
Just wondering and want to ask You about that, i have problem that first from bottom group is always higher than other. Is there any simple solution for that? Or maybe i need to modify _calculateHeight method ? Here are two examples:
![image](https://cloud.githubusercontent.com/assets/3201675/7630386/c921c5b6-fa35-11e4-944d-7d742c33b1f8.png)
![image](https://cloud.githubusercontent.com/assets/3201675/7630457/6ebd405e-fa36-11e4-868d-7ecd93ac511a.png)

**Comment by josdejong** [comment]
I think this will be solved when you set option `{margin: {axis: 0}}` (this has a value of 20 px by default).

**Comment by AdrianNowik** [comment]
Thank You, this option helps a lot !
