### ISSUE TITLE
[Timeline] [v4-branch] css class rename on the timeline axis labels

### ISSUE THREAD

**Issue by toxix** [almende/vis#836]
Just tested the ```v4``` branch and woundered why my axis labels are dancing.  Found out that the css classes ```1h```, ```2h```, ```3h```… got renamed to ```h1```, ```h2```. I'm using twitter bootstrap styling and the css-class ```h1``` is defined to use as alternative to the ```<h1>``` html-tag. Maybe it is better to use a bit more verbose class like ```hour1```? Or also prefix it with ```vis-h1```,  ```vis-h2```… To be consistent, to the other class-name changes happened in ```v4```.
Not sure what the intention for the change was?

**Comment by AlexDM0** [comment]
Hi,

That's odd, the idea was to prefix vis- to all classes we use. This must have slipped through. Thank you for letting us know on an unreleased version! We'll fix this before the release. @Josdejong could you look at this?

Cheers,

Alex

**Comment by toxix** [comment]
thanks for fixing and providing this awesome lib.

**Comment by AlexDM0** [comment]
Has this been changed already?

**Comment by toxix** [comment]
don't think this has already fixed, because there are no new commits. My comment was related to the plan to fix it.

**Comment by AlexDM0** [comment]
:) ok just checking if I missed something

**Comment by josdejong** [comment]
Thanks, I hadn't prefixed these css classes as I assumed they where exotic enough not to conflict with others. But apparently Bootstrap pervades every possible corner of CSS classes. Should be fixed now. Looks ugly, but it's functional.

**Comment by toxix** [comment]
But now it is fixed. :)
