### ISSUE TITLE
Timeline - Groups by "name" rather than "numerical index"

### ISSUE THREAD

**Issue by damionpaulhart** [almende/vis#838]
For the timeline data, groups are referenced by their index.

 It would be easier to make changes to groups if we could reference by their value. 

Here is an example object for the timeline, note group "1" is referenced.
  {
    "start": "-000138-01-01T05:00:00.000Z",
    "end": "-000129-01-01T05:00:00.000Z",
    "content": "Antiochus VII Sidetes",
    "id": 4,
    "group": 1
  },

The groups for the above object are:

var groupNames = ['none', 'Seleucid', 'Jewish', 'Nabateans'];

The problem I have is that the group is "Seleucid" not "1".

INSTEAD of using the group index, I would like to use the value that IS the group name.

So instead of 

"group": 1

it would be 

"group": "Seleucid"

I do not have the programming skill to make the change, yet if someone can offer suggestions or help, I can attempt to implement it as it is probably not too far above my understanding.

**Comment by AlexDM0** [comment]
Hi,

I think that all you need to do is use the same values for the group ids as you do for the group names. Groups are referenced by their ID, which is not an index necessarily. 

Regards,

Alex
