### ISSUE TITLE
Network graph resize incorrectly

### ISSUE THREAD

**Issue by stanleyxu2005** [almende/vis#839]
I've created a network graph (visjs 3.12.0). The height is specified by concrete pixels. The width is set to 100% to fit a Bootstrap grid cell. When the page width is changed, the network graph will be resized in horizontal direction automatically. But the nodes and their labels will be stretched. Is it possible not to stretched any element of the graph?

**Comment by AlexDM0** [comment]
Hi,

You'll need to call redraw to redraw the network after resize. 

Regards,

Alex

**Comment by stanleyxu2005** [comment]
Thanks. Can we have a property `auto-resize` for that?

**Comment by AlexDM0** [comment]
Yes, it's already in the v4 branch. We hope for a release this Friday. 

Regards

**Comment by stanleyxu2005** [comment]
Great news. Looking forward to it.
