### ISSUE TITLE
[Timeline] [v4-branch] getEventProperties() does not return group

### ISSUE THREAD

**Issue by toxix** [almende/vis#841]
I'm using  ```getEventProperties()``` to know where to add an doped element to the timeline. This is working well in the current release, but on the ```v4``` branch the ```group``` is always ```null```. Not 100% sure if this is related to passing an jquery.event but don't think so, because all other properties do have their expected values.

**Comment by josdejong** [comment]
Thanks. `getEventProperties` was wrongly falling back to the use of `pageY` instead of `clientY` in case of "foreign" events like from jquery. Should be fixed now in the v4 branch.

**Comment by toxix** [comment]
jep, seems to work now. :)
