### ISSUE TITLE
Links in groups

### ISSUE THREAD

**Issue by jason-green-io** [almende/vis#842]
Can't click on them on iOS like web browsers. Desktop is fine.

**Comment by AlexDM0** [comment]
Hi,

Im going to assume you are referring to links in items in a group in timeline. If so, it is fixed on the v4 version that we plan to release next Friday. 

Regards,

Alex

**Comment by jason-green-io** [comment]
Yup and woohoo!

**Comment by jason-green-io** [comment]
Actually, to be clear, links in the group content, not the items themselves.

**Comment by AlexDM0** [comment]
I see. I should think the fix carries over be it'd be awesome if you'd test it in the v4 branch. You'll need the new CSS and the new docs are also on there. 

Cheers

**Comment by jason-green-io** [comment]
Will do

**Comment by jason-green-io** [comment]
Tried it, doesn't work. Is it me?

http://barlynaland.greener.ca

Those social media icons are achors.

**Comment by AlexDM0** [comment]
Seems this works on andriod but not on iOS, well look into it.

**Comment by jason-green-io** [comment]
Any progress on this?

**Comment by josdejong** [comment]
> Any progress on this?

not yet

**Comment by josdejong** [comment]
I'm not sure when what fixed this, but the bug seems not to appear anymore. I will close this issue.
