### ISSUE TITLE
Clustering and Hierarchical Layout

### ISSUE THREAD

**Issue by mturok** [almende/vis#844]
Is there a way to have clustering work with hiearchical layouts?   In my case, I prefer the hierarchy, but have some nodes that should logically be clustered together.

Regards,
Michael

**Comment by AlexDM0** [comment]
Hi,

This should be possible in v4 which we want to release this Friday. 

Regards,

Alex

**Comment by AlexDM0** [comment]
On second thought, the level allocation could be messed by the clustering. You'd have to try it but It's not designed for it necessarily. 

You could use the datasets to dynamically update the set on a click event?

Regards

**Comment by AlexDM0** [comment]
Hi,

We just released v4 today and I'll be curious to hear if the new clustering system works for you.

Cheers

**Comment by dragonzone** [comment]
I have used clustering and changing on my project since version 3. I've upgraded to v4.3 now and it still seems to work. You can test it out here: https://github.com/dragonzone/JsSamplerApp with my linkAnalysis.htm
