### ISSUE TITLE
changing shape in network through options

### ISSUE THREAD

**Issue by mmotamimi** [almende/vis#845]
i got code with giving the shape by the group

options = {
		navigation: true,
        keyboard: true,
        stabilize: true,
        smoothCurves: true,
		groups: {
			'pass':{
				shape:"square",
				color: "green"
			},
			'fail': {
				shape: "dot",
				color: "red"
			},
				'notYet': {
				shape: "star",
				color: "black"
			}
		},
        hierarchicalLayout: {
            direction: 'UD',
            layout: 'hubsize',
            levelSeparation:150,
		},
			keyboard: {
				speed: {
					x: 10,
					y: 10,
					zoom: 0.02
				},
				bindToWindow: true
			},
        edges: {
			style:"arrow"
			//color.highlight: "red";
        }
    };

at the console, when i try changing or putting the options and do " network.setOptions(newOptions)"
every thing may change as the new change but the shape stays as is

**Comment by AlexDM0** [comment]
Hi,

Could you make a jsbin? I don't know what it was before so I don't know what you changed. 

Regards

**Comment by mmotamimi** [comment]
http://jsbin.com/kecigupuqo/1/edit
i guess it won't work since i should load json files
this code works just fine and gives me the network i need
but when i do this on the console
options.groups.pass.color = "yellow";//options is set as grobal
network.setOptions(options); // the color of pass group changes to yellow
but when i do this
options.groups.pass.shape = "star";
network.setOptions(options); // the shapes does not change
i think it's a problem since i tried making new options, changing the shape on the "nodes" options without using the groups
and it's the same result

**Comment by AlexDM0** [comment]
Hi,

The nodes do not individually update the group options when the groups are updated. I'll address this in v4 which we plan to release this Friday. 

Regards

**Comment by AlexDM0** [comment]
I have fixed this in v4.

Regards,

Alex
