### ISSUE TITLE
Network with hierarchicalLayout, changing root node manually

### ISSUE THREAD

**Issue by mmotamimi** [almende/vis#846]
i use visJs for my graduation project
i noticed that when using the "hierarchicalLayout", "UD" for instance, the node at the top will be the node that has the largest number or edges connected to it
i'm wondering if there is an option that can specify the upper node neglecting the number of edges?

**Comment by AlexDM0** [comment]
Hi,

You can use directed mode or specify the levels manually. There are examples on both on our website. 

Regards,

Alex

**Comment by AlexDM0** [comment]
Just to clarify, your issue is in fact unrelated to the issue title? If so, could you update the title to correspond with the content of the issue?

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi,

Did this solve your issue?

Regards,

Alex

**Comment by mmotamimi** [comment]
Not yet
Could you please provide me a link to example or documentation for the directed mode?

**Comment by AlexDM0** [comment]
We are currently migrating to v4. I'll send a link to the new system once it's running

**Comment by mmotamimi** [comment]
Waiting for it
Thank you

**Comment by AlexDM0** [comment]
In the meantime, you might as wel take a look at these:
http://visjs.org/examples/network/32_hierarchicaLayoutMethods.html
http://visjs.org/examples/network/24_hierarchical_layout_userdefined.html

It's not like they're hiding

**Comment by mmotamimi** [comment]
Will do

**Comment by AlexDM0** [comment]
New examples: 
http://visjs.org/network_examples.html
http://visjs.org/examples/network/layout/hierarchical_layout_userdefined.html
http://visjs.org/examples/network/layout/hierarchical_layout_methods.html

**Comment by mmotamimi** [comment]
Problem solved
Thank you

**Comment by AlexDM0** [comment]
Glad to hear that. Have fun using vis!
