### ISSUE TITLE
Timeline `fit` does not fit all items visually

### ISSUE THREAD

**Issue by mmacaula** [almende/vis#847]
When I call `fit()` on my timeline visualization, the timeline fits the start and end just perfectly.  However, the items I am displaying have some text that makes the text boxes a little wide
![timeline_example](https://cloud.githubusercontent.com/assets/3186250/7732796/f60ef6e8-feef-11e4-9e27-ae4b16a2be54.PNG)

This happens on both the beginning of the timeline and the end of it (as pictured). 

Is there any way to tell `fit` to give a buffer of some pixel amount?  I know I can manually fit to specific dates.  Is the best solution to get the range, find a scale, and then expand my start and stop times by a padding for that scale?  

I guess this issue is a request to have this behavior done by default by `fit`.  If that isn't a good idea, feel free to close this issue. Thanks for the great library!

**Comment by josdejong** [comment]
Thanks. Right now the `fit` method only takes into account the start and end date of items, not the actual width. Should be relatively easy to improve this though.

**Comment by josdejong** [comment]
The function `fit()` should now take into account the actual width of items, you can try the `develop` branch.

**Comment by josdejong** [comment]
This issue was fixed in v4.2.0
