### ISSUE TITLE
Network with hierarchicalLayout root node

### ISSUE THREAD

**Issue by mmotamimi** [almende/vis#848]

**Comment by AlexDM0** [comment]
...? is there a question of some sort corresponding to this issue?

**Comment by mmotamimi** [comment]
No
Made it by mistake

**Comment by mmotamimi** [comment]
Is there a way to delete this?

**Comment by AlexDM0** [comment]
No but we'll leave it closed as is. If you have a question we could edit this issue to suit that purpose?

**Comment by mmotamimi** [comment]
No. But ill change the title to indecate that its empty issue
