### ISSUE TITLE
export the Graph

### ISSUE THREAD

**Issue by nitin0708** [almende/vis#849]
Hi Allen

Can i generate a pdf of a graph in Vis js.

Thanks

Nitin

**Comment by AlexDM0** [comment]
Hi Nitin,

You could right click the network and save as image, you could print your webpage as pdf or you can use phantomjs for this. There are a lot of issues on this, please search around a bit :). 

Regards,

Alex

**Comment by nitin0708** [comment]
Thanks Allen for quick reply

Thanks & Regards

Nitin

**Comment by AlexDM0** [comment]
My name is Alex ;)

Cheers

**Comment by nitin0708** [comment]
Sorry for the last reply
