### ISSUE TITLE
A behavior of label of Graph2D is completely strange.

### ISSUE THREAD

**Issue by H-Nishida** [almende/vis#850]
Please try zoom-in to formal example:

http://visjs.org/examples/graph2d/19_labels.html

Suddenly the label is shown near the a dot without label.

**Comment by AlexDM0** [comment]
Hi,

we just released a new version, is it still the case? I cant reproduce it now.

Regards,

Alex

**Comment by H-Nishida** [comment]
I confirmed that is solved.
Thank you.
