### ISSUE TITLE
Tooltips are not displayed since 4.0.0

### ISSUE THREAD

**Issue by MathieuViossat** [almende/vis#852]
Hi,
Since the new version, the `title` attributes are not called to display tooltips.
Mathieu

**Comment by AlexDM0** [comment]
Hi,

What do you mean exactly? It seems to work:

http://visjs.org/examples/network/events/interactionEvents.html

Regards,

Alex

**Comment by MathieuViossat** [comment]
It's ok. Sorry, my browser cache wasn't update...

**Comment by MathieuViossat** [comment]
Another problem it's the mouse is moved quickly over a tooltip, this tooltip stay displayed without moving with the mouse.

**Comment by AlexDM0** [comment]
I think the second part is by design. If you move the mouse off the tooltip and somewhere where there is no node it disappears right?

**Comment by MathieuViossat** [comment]
Yes.

**Comment by AlexDM0** [comment]
Hi Mathieu,

I fixed both the problems you have reported in the develop branch. Come to think of it the tooltip should not have caught mouse events.

Thanks for reporting these :) keep them coming if you find them!

Cheers

**Comment by MathieuViossat** [comment]
It's perfect. Thanks!

**Comment by AlexDM0** [comment]
Ill open these bug reports until release of the 4.0.1
