### ISSUE TITLE
Filterd dataview not working

### ISSUE THREAD

**Issue by yearsy** [almende/vis#853]
Thanks for the update, looks great so far. 

After aplying a filter on the dataview, the network is not drawn correctly.

Also javascript gives the following error "Uncaught TypeError: Cannot read property 'id' of undefined"
vis.js:39232

 // fix weird behaviour
        if (this.from.id === this.to.id) {
          this.via.setOptions({ physics: false });
        } else {
          this.via.setOptions({ physics: true });
        }

If filter returns all objects, it works fine.

Can you help me with this?

**Comment by AlexDM0** [comment]
Hi,

could you make a jsbin for this? Without any context I have no idea if this fix safe.

Regards,

Alex

**Comment by yearsy** [comment]
Not sure how jsbin works,

http://jsbin.com/hidiyocida/1/edit?html,js,output

But i added my code after some privacy masking.
I could get the javascript working, i hope this helps?

Greetings

**Comment by AlexDM0** [comment]
I have it reproduced in our test environment. I'll take a look at it next week. 

Aww and here I was thinking the v4 release was stable after months of work haha.

Regards,

Alex

**Comment by yearsy** [comment]
I know the feeling ;) good luck and thanks

**Comment by AlexDM0** [comment]
Hi,

I've fixed the bug over in the develop branch. Turns out that dynamic edges didnt correctly handle nodes that did not exist. Thank  you for reporting it :)

Regards,

Alex

**Comment by AlexDM0** [comment]
Ill open these bug reports until release of the 4.0.1

**Comment by yearsy** [comment]
Thanks for the fix, keep up the good work :)
