### ISSUE TITLE
zoom bug

### ISSUE THREAD

**Issue by klmdb** [almende/vis#854]
http://visjs.org/examples/network/basic_usage.html

1) open in chrome or firefox
2) resize your browser window so you have a vertical scrollbar
3) scroll down on your page so that you can still view some of the canvas
4) zoom into a node

You'll see the zoom isn't fixed on the cursor position. I'd guess it needs to be corrected for the scroll hieght.

**Comment by AlexDM0** [comment]
Hi, 

Good point, we'll include it in the bugfix release next week.

Thanks for letting us know!

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi, 

I've fixed this in the develop branch. 

Regards,

Alex

**Comment by AlexDM0** [comment]
Ill open these bug reports until release of the 4.0.1
