### ISSUE TITLE
cdnjs.com links not working for 4.0.0

### ISSUE THREAD

**Issue by thiagomarzagao** [almende/vis#855]
Great update!

I couldn't get it from cdnjs.com though. Both links give 404 Not Found:

https://cdnjs.cloudflare.com/ajax/libs/vis/4.0.0/vis.min.js

https://cdnjs.cloudflare.com/ajax/libs/vis/4.0.0/vis.min.js

Links to 3.12.0 are working fine.

**Comment by AlexDM0** [comment]
Hi,

We released just today, I think they still need to sync up. Let's give it a week. 

Cheers

**Comment by AlexDM0** [comment]
Ill open these bug reports until this has been resolved.

**Comment by josdejong** [comment]
https://github.com/cdnjs/cdnjs/issues/3015#issuecomment-105509555
