### ISSUE TITLE
Add new nodes, modify edge directly onto the page

### ISSUE THREAD

**Issue by nathalizator** [almende/vis#857]
Hello,
i would like to know if its possible to interact directly on the webpage where the network is display, i have creat a network with nodes and but i would like to change the edge, add new nodes or delete nodes directly on the webpage. Is this possible to set those kind of interaction?

**Comment by AlexDM0** [comment]
Hi,

I was wondering if you have seen our example page. 
http://visjs.org/network_examples.html

Here are a few examples on this:
http://visjs.org/examples/network/data/datasets.html
http://visjs.org/examples/network/data/dynamic_data.html
http://visjs.org/examples/network/other/manipulation.html

And ofcourse the documentation explaining all the modules.
http://visjs.org/docs/network/

Specifically
http://visjs.org/docs/network/manipulation.html
http://visjs.org/docs/data/

Regards,

Alex

**Comment by nathalizator** [comment]
Thanks you ! ive missed this part ! this is great ! Thanks you !

**Comment by nathalizator** [comment]
I'm sorry, i don't seems to understand how i'm supposed to add my own id and edge here  on this exemple : 

http://visjs.org/examples/network/other/manipulation.html

'   var nodes = null;
    var edges = null;
    var network = null;
    // randomly create some nodes and edges
    var data = getScaleFreeNetwork(5);
    var seed = 2;


    function destroy() {
      if (network !== null) {
        network.destroy();
        network = null;
      }
    }

    function draw() {
      destroy();
      nodes = [];
      edges = [];'

Where am i supposed to add my id ' {id: 1, label: 'start', shape: 'image', image: 'icona/start.svg'  },
 {id: 2, label: 'end', shape: 'image', image: 'icona/start.svg'  },'
and edges '{from: 1, to: 2,  },'

**Comment by AlexDM0** [comment]
Hi,

The getScaleFreeNetwork creates the data in this example. All you really need from this example is the options. It is being fed into the network here:

https://github.com/almende/vis/blob/gh-pages/examples/network/other/manipulation.html#L117

Try reading the docs:
http://visjs.org/docs/network/manipulation.html

You can use those options with your own graph and you'll get the toolbar.

Regards,

Alex

**Comment by GowrishankarGeek** [comment]
Hi, 
i would like to know if its possible to trigger "click edit button" event in manipulation network diagram

**Comment by AlexDM0** [comment]
Hi,

There is an option called initiallyActive that may be just what you need. 

http://visjs.org/docs/network/manipulation.html

Regards

**Comment by janet3** [comment]
Hi,i wanted to know if duplicate nodes can be added in a network?
