### ISSUE TITLE
destroy() vis.Graph2d

### ISSUE THREAD

**Issue by Hutschi** [almende/vis#858]
In the new Version 4.0, destroying an vis.Graph2d object throws the following error on actual chrome version:

"Uncaught Error: DataSet.unsubscribe is deprecated. Use DataSet.off instead."

Any suggestions?

**Comment by AlexDM0** [comment]
Hi,

This is sloppy on our side. We depricated the subscribe method but did not remove all its usages. 

We'll launch a bugfix release next week with this fixed.

Regards,

Alex
