### ISSUE TITLE
Svg get distorted with new vis.js v4

### ISSUE THREAD

**Issue by nathalizator** [almende/vis#859]
I have replaced the old version of vis.Js (  v3)  with this new version 4, but all my svg get distorted.

http://visjs.org/examples/network/nodeStyles/HTML_in_Nodes.html
Is this example i see the svg image distorted too ( chrome and firefox = same ) its only when i click onto each svg that its not getting distorted anymore but when i reload the page it still distorted again.

Am i doing something wrong? This issue appear only with this v4 :(

**Comment by AlexDM0** [comment]
Hi,

This seems to be a bug. I'll look into it.

Cheers

**Comment by nathalizator** [comment]
Thank you so much :) The fontsize of my nodes seems to not working too...

**Comment by AlexDM0** [comment]
Hi,

I fixed the bug with the images (or svg in this case). it has been pushed to develop. There will be a bugfix release next week.

The labels seem to work fine:

http://visjs.org/examples/network/labels/label_color_and_size.html

If you found a bug with the labels, please make a new issue for it so we keep all issues straight to the point :)

Thanks for reporting!

Cheers

**Comment by AlexDM0** [comment]
on a sidenote, the font options have changed. I'll assume you set the font sizes per node. If you did so globally, the validator would have warned you in the console.

Cheers

**Comment by nathalizator** [comment]
Haa yes ! Its working now :)  Thank you

**Comment by AlexDM0** [comment]
Ill open these bug reports until release of the 4.0.1

**Comment by nedel** [comment]
hallo, 
i have still problems with firefox (version 42.0 on Ubuntu 64bit)

the html nodes are not displayed correctly: http://visjs.org/examples/network/nodeStyles/HTMLInNodes.html

![auswahl_118](https://cloud.githubusercontent.com/assets/516584/11057514/f4c8f3e0-878b-11e5-8a29-36b40204ccee.png)

**Comment by josdejong** [comment]
It's just an experimental example, showing SVG in canvas. So, yes, it can fail (see also the big red warning in your screenshot ;) ). If you know ways to get this experimental thing better working in more browsers please let us know, then we can improve the example.

**Comment by nedel** [comment]
i tried the same fix for Image.js (just adding this.imageLoaded = false; ) 
don’t know if this is the right way. but it works for me.
