### ISSUE TITLE
Manipulation menu fails after Edit Node

### ISSUE THREAD

**Issue by BorisKingma** [almende/vis#860]
Dear madam/sir,

I noticed the manipulation menu goes blank after the operation: "Edit Node".

This is also happening in the demo: http://visjs.org/examples/network/other/manipulation.html

Please advise on how to solve this.

Regards,
Boris

**Comment by AlexDM0** [comment]
Hi Boris,

This is a bug, I'll fix it and we'll add it to the bug fix release that's going to be released next week. 

Regards,

Alex

**Comment by BorisKingma** [comment]
Thanks

**Comment by AlexDM0** [comment]
I've pushed the fix to the develop branch. Thanks for reporting!

**Comment by AlexDM0** [comment]
Ill open these bug reports until release of the 4.0.1
