### ISSUE TITLE
brokenImage only works for one node

### ISSUE THREAD

**Issue by BorisKingma** [almende/vis#861]
Dear Alex,

as in the title, if I have multiple nodes with a broken image, only the first one shows a broken image. The rest shows no image at all (I tried up to three).

below is the code example excerpt to clarify:

this.nodes = new vis.DataSet([]);
this.edges = new vis.DataSet([]);
      	
this.nodes.add({id: 2, value: 1, label:"a", group:"alfa",  shape: 'image', brokenImage: IMAGE_DIR + 'logo.png', image: 'notexisting.png'});
this.nodes.add({id: 3, value: 1, label:"b", group:"beta",  shape: 'image',brokenImage: IMAGE_DIR + 'logo.png', image: 'notexisting.png'});

regards,
Boris

**Comment by AlexDM0** [comment]
Hi Boris,

Thank you for reporting this. I'll look into it. 

Cheers

**Comment by AlexDM0** [comment]
Hi Boris,

I cannot seem to reproduce this. Could you make a jsbin to show it?

Cheers

**Comment by BorisKingma** [comment]
Hi,

I am not familiar with jsbin, but maybe it is helpful to know that the case
I had was that all images had broken links.

Regards,
Boris

**Comment by AlexDM0** [comment]
Hi Boris, 

I managed to reproduce it. I'll make sure it's fixed for our release next week. 

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi Boris,

This is fixed in develop. I think this bug has been there for a long long time. Thanks for catching it :)

Cheers
