### ISSUE TITLE
Constrain timeline timespan

### ISSUE THREAD

**Issue by ReneHollander** [almende/vis#862]
Hello!

Is it possible to use `start` and `end` options for `vis.Timeline()` as a hard stop? I want to constrain the timespan to a single day.

- Rene Hollander

**Comment by ReneHollander** [comment]
I came up with the following:
I use the rangechange event to check if the rangestart is smaller then my hard limit. If it is, I use `setWindow()` and set the start to my hard limit and the end to `hardLimitStart + (currentrange.end - currentrange.start)`. If the current range end is bigger then my hard limit I use `setWindow() and set the start to  `hardLimitEnd - (currentrange.end - currentrange.start)` and the end to my hard limit.
This works if I zoom in a bit and scroll to the right. If I scroll to the left it buggs out completely. Also zooming out is breaking everything...

Here is a jsfiddle: http://jsfiddle.net/nghto3mc/

**Comment by AlexDM0** [comment]
Hi,

That's creative but isn't this exactly what the min and max option are for?

http://visjs.org/docs/timeline/

Regards,

Alex

**Comment by ReneHollander** [comment]
Okay. Your solution is easier... :D
