### ISSUE TITLE
Permissions issue in distribution

### ISSUE THREAD

**Issue by leondanielking** [almende/vis#863]
Easy fix:   Directories should have a permission of o=x.  Noticed this problem in 4.0 and likely was in 3.12 as well.  Otherwise files in these directories not visible on a server.

**Comment by josdejong** [comment]
Do you mean like when extracting the zip file from the website?

**Comment by leondanielking** [comment]
Yes.   The regular files are OK.  The subdirectories need to be executable (navigable) by others.   I was trying something based on an example and it didn't work - after an hour or so I figured out the problem was accessibility to the file.   (Something like this could turn someone off the package quickly.)


________________________________

**Comment by josdejong** [comment]
I don't know much about zip but it seems like zip doesn't store any file permissions. Which means it's up to you to adjust permissions when unzipping the file.

http://superuser.com/questions/603068/unzipping-file-whilst-getting-correct-permissions
http://stackoverflow.com/questions/10735297/maintain-file-and-folder-permissions-inside-archives

**Comment by leondanielking** [comment]
It does store file permissions in subdirectories.    You may be looking at the top level directory which is created fresh.  Files and directories in subdirectories retain the permissions specified.

If you look at the example I’ve attached, on a Unix system, it should unpack with different permissions on the subdirectories do and dah.   However if you are building the zip file in Windows.

The version of zip I have is 3.0 (July 5, 2008), and I’m running on Redhat 5.9

**Comment by josdejong** [comment]
There is no example attached to your post.

What I've done to create the zip file is (on linux):

```
zip vis.zip -r dist docs examples README.md HISTORY.md CONTRIBUTING.md LICENSE* NOTICE -r
```

**Comment by AlexDM0** [comment]
is this still an issue?
