### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by leondanielking** [almende/vis#864]
I'm quite new to vis - less than a  week.  Liked the visual gallery of examples on the web page and this is what attracted me as at a glance it showed the possibilities of each library section.    With 4.0 there's only text listing.

**Comment by AlexDM0** [comment]
Hi,

We want to get images back in there eventually but we did not yet have time to make new screenshots. The number has also increased from 40 to 50 examples and while pretty, it was difficult to really find an example on what you were doing. We still have to find a solution for this. 

Regards,

Alex
