### ISSUE TITLE
Disable overlapping without stacking

### ISSUE THREAD

**Issue by ToasteR1032** [almende/vis#865]
Hello!

Is it possible to disable the overlapping of items without using the `stack` option?

Thanks in advance!

**Comment by AlexDM0** [comment]
Hi,

If you don't want to stack, it is up to you to make sure they do not overlap.  

That's what the groups and subgroups can be used for.  Take a look at the MIDAS showcase item for usage of subgroups. 

http://visjs.org/showcase/index.html

Regards,

Alex
