### ISSUE TITLE
v4 manipulation enabled = false produces error

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#866]
Hi @ dev team

my first error for v4 :blush:

Using

    var options = {
      manipulation: {
        enabled: false   // <- true works
      }
    };

will result in 

    Uncaught TypeError: Cannot read property 'hasChildNodes' of undefined

-Felix

**Comment by felixhayashi** [comment]
http://output.jsbin.com/saqefo/1

**Comment by AlexDM0** [comment]
Hi Felix, 

Thanks for reporting :) I've pushed a fix to develop. We'll release a bug fix version next week. A lot of small things have popped up so far. Are you guys going to migrate to v4?

Regards,

Alex

**Comment by felixhayashi** [comment]
Hi @AlexDM0 

> Thanks for reporting :) I've pushed a fix to develop. We'll release a bug fix version next week.

Nice, many thanks.

> Are you guys going to migrate to v4?

Another community member now also published a timeline plugin for TiddlyWiki (using the vis timeline module) and of course we want to upgrade to 4.0 soon but we will wait a month or so before pushing any upgrades. In the meantime, I will of course experiment with v4 and work on the migration. Quite a lot changed for v4, I also noticed you guys changed the css classes so they are properly prefixed with "vis-" which is nice :) As always, I'll report any bugs I find ;)

Best wishes
Felix

**Comment by jam1123** [comment]
Just to mention that this might be related? Using
```javascript
var options = {
  clickToUse: true
};
```
generates the error "Cannot read property 'appendChild' of undefined". Setting clickToUse to false removes the error.

JSBin (essentially same as OP, with 'options' as mentioned): http://jsbin.com/vopivibase/1/

_Great_ work on vis.js BTW.

Best Regards,

Jamsheed

**Comment by AlexDM0** [comment]
Hi Jamsheed,

Thanks for reporting this. I've pushed a fix to the develop branch.

Regards,

Alex

**Comment by jam1123** [comment]
> Thanks for reporting this. I've pushed a fix to the develop branch.

Great, thanks!

-J

**Comment by AlexDM0** [comment]
Ill open these bug reports until release of the 4.0.1

**Comment by Meboolean** [comment]
hi,can you help me?
RelationComponent_Host.html:1 ERROR TypeError: this.body.container.hasChildNodes is not a function
    at Canvas._create (Canvas.js?e797:186)
    at new Network (Network.js?9a65:138)
    at RelationComponent.ngOnInit (relation.component.ts?11be:75)
    at checkAndUpdateDirectiveInline (core.es5.js?de3d:10836)
    at checkAndUpdateNodeInline (core.es5.js?de3d:12332)
    at checkAndUpdateNode (core.es5.js?de3d:12271)
    at debugCheckAndUpdateNode (core.es5.js?de3d:13132)
    at debugCheckDirectivesFn (core.es5.js?de3d:13073)
    at Object.eval [as updateDirectives] (RelationComponent_Host.html:1)
    at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js?de3d:13058)
