### ISSUE TITLE
Graph duplicated on Android Browser

### ISSUE THREAD

**Issue by maurizioce** [almende/vis#87]
On Android Browser (I've tested on version 4.3) it seems like graph is drawn twice and 
when I drag it only one instance move.

Probably it's a canvas problem with Android Browser.

![screenshot_2014-04-11-10-20-05](https://cloud.githubusercontent.com/assets/1258032/2677516/b372f59a-c152-11e3-95dd-54c0bb7ed009.png)

**Comment by AlexDM0** [comment]
There is nothing we can do to fix this.
