### ISSUE TITLE
what's happened to 'long press' in V4?

### ISSUE THREAD

**Issue by thiagomarzagao** [almende/vis#870]
I'm porting my code to V4. Back in V3 I could use long press to select multiple nodes in a network, but now that doesn't seem to work anymore. I couldn't find anything in the docs. What am I missing?

**Comment by AlexDM0** [comment]
Hi,

This is an oversight on my part, I've updated the docs on develop to include the multiselect. The multiselect is a new option that is disabled by default. You can use it like so:

```
var options = {interaction:{multiselect:true}};
```

If you turn it on, the long press as well as a control-click will now add to selection. We'll release a bugfix release next week, including multiselect in the docs.

Cheers

**Comment by AlexDM0** [comment]
Ill open these bug reports until release of the 4.0.1
