### ISSUE TITLE
Set node position relative to the top left corner of the container

### ISSUE THREAD

**Issue by FarzadT** [almende/vis#871]
Is it possible to draw the `Network` starting at the top left corner instead of the middle of the container?

**Comment by AlexDM0** [comment]
Hi,

You can use the moveTo function with an offset. 

Regards,

Alex

**Comment by FarzadT** [comment]
would the offset be `network.view.targetTranslation`?

**Comment by AlexDM0** [comment]
No, the offset is an option property of the moveTo method. 

http://visjs.org/docs/network/

You can imagine the canvas is a piece of paper with a camera above it. MoveTo moves that camera. 

Regards

**Comment by FarzadT** [comment]
Sorry I should have been more clear in my response.

I meant to say:
Does `network.view.targetTranslation` signify the offset relative to the origin of the DOM element (top left corner). In otherwords, is this what I'm looking for?
```
    var translation = network.view.targetTranslation;
    network.moveTo({
      position: {
        x: 0,
        y: 0
      },
      scale: 1.0,
      offset: translation
    });
```

**Comment by FarzadT** [comment]
I don't quite understand how `moveTo` works:
```javascript
network.moveTo({
  position: {x: 0, y:0},
  offset: {x: 0, y: 0}
})

network.once('afterDrawing', function(){
  network.getViewPosition(); // Why doesn't this return {x: 0, y: 0}???
});
```

**Comment by AlexDM0** [comment]
Because the camera is not centered on 0,0. It starts out at 0,0 but as the nodes move it may be centered on another point to keep everything in view. It is then centered at something else. The camera has moved to fit all nodes on screen. 0,0 in canvas space is an arbitrary centre point from which the positions of the nodes are determined. It has nothing to do with the DOM position. 

You should not use the internals and no, the targetTranslation has nothing to do with it. 

You should use the initRedraw event for your moveTo to save a second redraw but both should work.

All you have to do is call moveTo with only the offset of half your container width and height (positive or negative is something you'll have to try). Turn on the animation so you see what's happening. If you understand you can turn it back off. 

Regards

**Comment by AlexDM0** [comment]
Hi,

Sorry, there has been a bug in the getViewPosition() method. I'll look into it and push a fix to develop.

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi,

I've fixed the bug in getViewPosition and the moveTo function on the develop branch. When released you can do:

```
network.once('initRedraw', function() {
    network.moveTo({offset:{x:- (0.5 * width of container),y:- (0.5 * height of container)})
  })
```

to shift the center point to top left.

Regards,

Alex

**Comment by djangosdk** [comment]
@AlexDM0  ```network.once``` is missing brackets ?
When this fix will be released since I also need top Left Node anchor

**Comment by AlexDM0** [comment]
Hi, 

Yes I missed a bracket. I edited my reply to correct this.

The bug should be fixed and released already.

Regards

**Comment by djangosdk** [comment]
@AlexDM0  
Thankx for fast response. If Possible make example of this at showcase area as it can be helpful for some people and is a very useful scenario.
This literally saved my day as I had to fix a point at top left to force it as staring point

**Comment by AlexDM0** [comment]
You mean an example of the vis network that shows the examples? Seems a little ironic? ;)

**Comment by djangosdk** [comment]
:)
something like http://jsfiddle.net/bababalcksheep/771fox0o/8/ 
It enables me to define a starting point ..OtherWise Root Node could b placed at any position ..

**Comment by AlexDM0** [comment]
There's a lot of examples that have static positions of the nodes, I'm not sure what makes that example anything special?

**Comment by djangosdk** [comment]
sorry I Just started using visjs like 5 hours ago. Have not gone through complete examples yet.

**Comment by vaishnavibadam** [comment]
using below code ,diagram is aligned in center in mozilla firefox,but it seems not aligned properly in google chrome.


network.once('initRedraw', function() {
    network.moveTo({offset:{x:- (1.5 * width),y:- (1.5 * height)}, position: {x:10, y:25}})
  })
