### ISSUE TITLE
setGroups throws 'DataSet.unsubscribe is deprecated. Use DataSet.off instead.'

### ISSUE THREAD

**Issue by AdamNowaczyk** [almende/vis#872]
Hi,

I've just updated to 4.0 to check if I should upgrade. I have this problem when trying to updated groups for the graph:
'DataSet.unsubscribe is deprecated. Use DataSet.off instead.'
Shouldn't Depreciation just log the message and not throw the error? Additionally it's visjs native code.

--
Thanks,
Adam

**Comment by AlexDM0** [comment]
Hi Adam,

This is a bug and I believe it's already fixed on the develop branch. 

You're referring to graph2D right?

Well release a bug fix release this week. 

Regards

**Comment by josdejong** [comment]
This error was affecting both Timeline and Graph2d. I've fixed it on the `develop` branch.

**Comment by AlexDM0** [comment]
Wasn't it already fixed?

**Comment by josdejong** [comment]
Yes, turns out it had the same cause as #858 but I hadn't seen your fix.
