### ISSUE TITLE
network title doesn't work well

### ISSUE THREAD

**Issue by hys564219** [almende/vis#873]
Hi,

I'm now trying the latest vis.js (4.0.0).

I want to show the title of nodes but I can only show it when I put cursor much above the node
and title doesn't shows when I put cursor just on the node.
The situation is like this below.

       ●cursor

┌─────┐
│       node    │
│     image     │
└─────┘
    label

It even happens in examples.
Just give title to all nodes in this example http://visjs.org/examples/network/nodeStyles/images.html
and replace <body> like this
&lt;body onload="draw()"&gt;

&lt;div id="vis" style="height:400px;width:100%;border: 1px solid lightgray;"&gt;&lt;/div&gt;
&lt;div id="mynetwork">&lt;/div&gt;
&lt;/body&gt;

I hope this bug can be solved as soon as possile.

**Comment by AlexDM0** [comment]
Hi,

Thanks for reporting this. It has already been fixed on the develop branch, we'll release a bug fix release this week. 

Cheers
