### ISSUE TITLE
Can't bundle as part of application

### ISSUE THREAD

**Issue by Gillingham** [almende/vis#874]
When trying to run browserify I end up getting:
```
SyntaxError: Unexpected token (4:7) while parsing /rampage_django/node_modules/vis/lib/shared/Configurator.js while parsing file: /rampage_django/node_modules/vis/lib/shared/Configurator.js
    at DestroyableTransform.end [as _flush] (/rampage_django/node_modules/browserify/node_modules/insert-module-globals/index.js:73:21)
    at DestroyableTransform.<anonymous> (/rampage_django/node_modules/browserify/node_modules/readable-stream/lib/_stream_transform.js:135:12)
    at DestroyableTransform.g (events.js:180:16)
    at DestroyableTransform.EventEmitter.emit (events.js:92:17)
    at prefinish (/rampage_django/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:450:12)
    at finishMaybe (/rampage_django/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:458:7)
    at endWritable (/rampage_django/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:469:3)
    at DestroyableTransform.Writable.end (/rampage_django/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:436:5)
    at DestroyableTransform.onend (/rampage_django/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:537:10)
    at DestroyableTransform.g (events.js:180:16)
    at DestroyableTransform.EventEmitter.emit (events.js:117:20)
    at /rampage_django/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:934:16
```

Using gulp to call browserify , but I am using the babelify transform. A note is that there's no mention of that transform in the Example 3 under README.md but I assume there should be.

**Comment by Puffton** [comment]
Same here!

**Comment by josdejong** [comment]
I've checked whether this [custom build Example 3](https://github.com/almende/vis#example-3-bundle-visjs-as-part-of-your-commonjs-application) works, and that works ok. @Gillingham you are right that the browserify command is missing `-t babelify`, I've added that to the readme now.

The error seems to point to an ES6 import statement: [Configurator.js](https://github.com/almende/vis/blob/master/lib/shared/Configurator.js#L3-L4). Are you sure you are bundling using the babelify transform? If so, how can I reproduce this issue? (Running Example 3 example works fine).

**Comment by Puffton** [comment]
Why aren't babelify and moment included as dependencies in npm? Possibly also uglifyjs, if that's really required (I prefer minifyify, it compresses better).

**Comment by Gillingham** [comment]
@josdejong are you running this with vis under node_modules or actually in the local path?

Digging into this I've noted that babelify says by default it does NOT parse things under node_modules, which if vis is installed in, as I think it is for myself and @Puffton then it won't be transformed. See: https://github.com/babel/babelify#why-arent-files-in-node_modules-being-transformed

**Comment by Puffton** [comment]
Thanks @Gillingham, the fix in your pull request works.

To avoid installing module "moment" separately (if it has breaking changes it might cause issues, since it is then updated separately from vis), I would suggest in the tutorial to not install moment separately and instead do: var moment = require('vis/node_modules/moment');

**Comment by josdejong** [comment]
@Puffton it's just a little example, you can do whatever you like in your own application. I have to check though whether following Example 3 wouldn't bundle `moment` twice if there are two different versions.

**Comment by Puffton** [comment]
Of course, it would just make it a little more clear and less prone to future issues for the people setting it up.

When I had moment installed it didn't bundle moment twice, i.e. it skipped moment in your node_modules dir, and IIRC I have setup npm with default settings.

**Comment by josdejong** [comment]
Could be because the two versions of moment are compatible? I suppose then the newest of the two is taken. Would be interesting to see what happens with two incompatible versions, like installing moment v1.x whilst vis.js uses moment v2.x.

**Comment by Puffton** [comment]
In the tutorial you require the local moment, not vis's moment, so it should pick the local moment and not vis in that case. Within vis, if you require moment, then it would logically pick vis's own moment, resulting in both being used at the same time?

**Comment by josdejong** [comment]
Yes that's how npm modules work if I'm not mistaken. This makes npm so powerful: it allows you to use multiple versions of the same module (of course you try to prevent this but sometimes there is no alternative).

**Comment by Puffton** [comment]
Yes, maybe I'm an oddball, since my background is not in JS. I try to have as few external dependencies as possible, and in turn let them manage their own dependencies. Since I rely mostly on open source software, I worry that if I get too many dependencies, it will be hard to maintain the project long-term since som of them will undoubtedly end up not being maintained.

**Comment by josdejong** [comment]
Well, it's a good thing to pay attention to keeping your dependencies minimal :)
