### ISSUE TITLE
[Network] v4 hoverNode event?

### ISSUE THREAD

**Issue by rwu823** [almende/vis#875]
Does `hoverNode` event it removed?

**Comment by AlexDM0** [comment]
Hi,

No it seems like it's missing from the docs. I've just tested it and it seems that it's firing too much as well. I'll fix it and add it to the docs for our bugfix release tomorrow.

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi, 

I've fixed this on the develop branch. We'll release it tomorrow.

Regards,

Alex
