### ISSUE TITLE
licences information in bower.json 

### ISSUE THREAD

**Issue by pawelantczak** [almende/vis#876]
Hello.
Please add explicit information about licences in bower.json.
Now, we cannot create webjar for newest vis version.
Thanks.

**Comment by josdejong** [comment]
I've added the license information to bower.json.

**Comment by pawelantczak** [comment]
Thanks.

**Comment by stanleyxu2005** [comment]
Dual license `"license": "(Apache-2.0 OR MIT)",` is not supported by webjars.org... Maybe `"license": ["Apache-2.0", "MIT"]`?

**Comment by AlexanderRay** [comment]
+1

**Comment by josdejong** [comment]
Argh. For multiple licenses, npm requires to use SPDX license expressions, whilst bower doesn't support that, well, let's try an Array then for bower.

**Comment by AlexanderRay** [comment]
thnx -)

**Comment by AlexDM0** [comment]
Shouldn't we just put MIT on there as it is the least restrictive? We can comment Apache behind that. 

Regards

**Comment by josdejong** [comment]
We have to put both, not all licences are compatible with each other. And it's meant to be read by a machine so adding it as a comment won't work. The issue is already solved though.
