### ISSUE TITLE
[timeline] multiselect on mac

### ISSUE THREAD

**Issue by toxix** [almende/vis#877]
The Multiselect with ```<strg>```/```<cmd>``` on mac is not working. Multiselect with ```<shift>``` is working as expected.

Sry, but can't further debug this, because I don't have a mac.

**Comment by josdejong** [comment]
> I don't have a mac.

Me neither... 

There is a possible solution posted here: http://stackoverflow.com/a/5500536/1262753

For now, you can always use long-press to do multi select (mainly useful for touch devices, but works on desktop too).

**Comment by AlexDM0** [comment]
I can see if I can add this to keycharm so we can use it in future releases. Isn't there a control key on macs as well?

Regards

**Comment by josdejong** [comment]
But this is related to meta keys of mouse events, not with keyboard events.

**Comment by toxix** [comment]
There is a command key (not control), that is also used to do multiselect within table-calculations. Not sure how to catch it. Maybe code from this solution can be adapted: https://github.com/MichaelZelensky/jsLibraries/blob/master/macKeys.js
But seems like we have to wait for a real mac user, to get things fixed.

@josdejong: thanks for the tip with long-press.

**Comment by josdejong** [comment]
@toxix did you try to load this `mackKeys.js` in your application? It may just work out of the box.

**Comment by josdejong** [comment]
I've added support for pressing the [metaKey](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/metaKey) (⌘ on macs, ⊞ on windows) to select multiple items.

**Comment by toxix** [comment]
tested and it works. :) thx for fixing.

**Comment by josdejong** [comment]
Ok great
