### ISSUE TITLE
Select/hover node without changing colors

### ISSUE THREAD

**Issue by FarzadT** [almende/vis#878]
I would like to know if it is possible to select/hover a node (trigger the selection/hover events) without modifying its styling.

**Comment by AlexDM0** [comment]
Hi,

You could set the styling the same for selected and unselected state. The color object as well as the borderWidthSelected can be configured. The text will still be bold though but not for the hover, only for the selection.

So hover can directly be done by setting the hovercolor the same as the normal color, selection the same except currently we do not support to configure the bold font when selected. You could use the option selectable:false and use the getNodeAt method to get the node without selecting it.

Regards,

Alex
