### ISSUE TITLE
"Clingy" sorting

### ISSUE THREAD

**Issue by Ne0nx3r0** [almende/vis#881]
I'm running into a display issue where items I've added become unsorted depending on the zoom level because they cling to the lowest available spot, for example:

Correctly sorted:

![Sorting Example 1](http://i.imgur.com/G854lXf.png)

One item ("A Meeting 3") is off:

![Sorting Example 2](http://i.imgur.com/uO60aeo.png)

Two items ("A Meeting" 2 & 3) are off:

![Sorting Example 3](http://i.imgur.com/Ylw4vc8.png)

Here's an example that generates this output:

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vis/3.12.0/vis.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/vis/3.12.0/vis.css" type="text/css" />
</head>
<body>
<div id="vis"></div>
<script type="text/javascript">
var container = document.getElementById('vis');

var events = [
		{id: 41,  group: 0, content: 'Standalone Meeting', start: '2013-04-23', type: 'point'},
		{id: 42,  group: 0, content: 'A Project', start: '2013-04-23', end: '2013-05-10'},
		{id: 43,  group: 0, content: 'A Meeting 1', start: '2013-04-24', parentId: 42, type: 'point'},
		{id: 44,  group: 0, content: 'A Meeting 2', start: '2013-04-28', parentId: 42, type: 'point'},
		{id: 45,  group: 0, content: 'A Meeting 3', start: '2013-05-09', parentId: 42, type: 'point'},
		{id: 46,  group: 0, content: 'B Project', start: '2013-04-23', end: '2013-05-10'},
		{id: 47,  group: 0, content: 'B IPR', start: '2013-04-23', parentId: 46, type: 'point'},
		{id: 48,  group: 0, content: 'B MPR', start: '2013-04-25', parentId: 46, type: 'point'},
		{id: 49,  group: 0, content: 'B FPR', start: '2013-05-02', parentId: 46, type: 'point'}
	];

var data =  new vis.DataSet(events);

// Configuration for the Timeline
var options = {
	selectable: false,
	order: function(a,b){ return b.id - a.id;}
};

// Create a Timeline
var timeline = new vis.Timeline(container, events, options);
</script>
</body>
</html>
```
Is there a way I can remedy this so the items will stack while staying in order?

I've seen there are groups, but if possible I'd prefer the items didn't occupy an entire horizontal space just for themselves, especially when they are not on the screen.

I'm not so much asking for anything to be fixed in the code set here as for advice, so I'll apologize for that.

**Comment by josdejong** [comment]
You mean like the option `order` to give items a custom, deterministic ordering? 

http://visjs.org/examples/timeline/items/itemOrdering.html

**Comment by Ne0nx3r0** [comment]
Well, yes that's precisely the problem I'm encountering. 

The custom deterministic ordering (emulated for succinctness by manually presorted IDs in the example code I posted) via the option `order` is not displaying items visually in the expected order.

**Comment by josdejong** [comment]
Ah, sorry, I didn't see you where already using `order`.

Unfortunately, the `order` function does not order things from top to bottom, it is only used to determine the order in which the items are rendered and stacked. And an item is still stacked at the first empty place it finds, starting from the bottom.

What you're creating looks quite a bit like a gantt chart, but the Timeline isn't really suitable for that (yet?). See also #329.

**Comment by Ne0nx3r0** [comment]
That's understandable, I appreciate your time and the reference material though.

Thanks!

**Comment by josdejong** [comment]
You're welcome!
