### ISSUE TITLE
vis.js has more than one anonymous define

### ISSUE THREAD

**Issue by sebestenyb** [almende/vis#883]
I have the error in the title when trying to use with requir.js
Wonder if  the code below should be
```javascript
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define(factory);
	else if(typeof exports === 'object')
		exports["vis"] = factory();
	else
		root["vis"] = factory();
})
```

the following:

`define("vis", factory);`

Cheers, Sebi

**Comment by josdejong** [comment]
There is this example loading vis.js using require.js, which seems to work just fine:

http://visjs.org/examples/timeline/other/requirejs/requirejs_example.html

How to repeat your issue?

**Comment by sebestenyb** [comment]
To be honest, I'm not 100% sure that it's vis.js, we have a wee bit complex setup, but eventually the optimiser complains about vis.js, and changing that particular line fixes the issue.

We use something like below:

```javascript
({
    appDir: '.',
    baseUrl: '.',
    dir: '../../cms/static/cms/js',
    removeCombined: true,
    fileExclusionRegExp: /^app\.rjs$/,
    noBuildTxt: true,

    paths: {
        requirejs: '../vendor/requirejs/require',
        jquery: '../vendor/jquery/dist/jquery',
        jquerycookie: '../vendor/jquery.cookie/jquery.cookie',

        'foundation': '../vendor/foundation/js/foundation',
        'foundation/accordion': '../vendor/foundation/js/foundation/foundation.accordion',
        'foundation/tab': '../vendor/foundation/js/foundation/foundation.tab',

        modernizr: '../vendor/modernizr/modernizr',
        domReady: '../vendor/domReady/domReady',

        vis: '../vendor/vis/dist/vis'
    },

    modules: [
        {
            name: 'base',
            include: [
                'requirejs',
                'domReady',

                'jquery',
                'jquerycookie',

                'foundation',
                'foundation/accordion',
                'foundation/tab',

                'modernizr',

                'vis'
            ],

            // exclude for debugging
            excludeShallow: [],
            optimize: true
        }
    ]
})
```

`r.js -o app.rjs`

**Comment by josdejong** [comment]
So it looks like it's related to bundling an application using `r.js`. Maybe you could try to bundle just vis.js itself with `r.js` and see if that gives the same problem too. 

Difficulty here is that vis.js is bundled as a regular UMD module using WebPack, so we can't directly change this. Besides that, following the [docs of require.js](http://requirejs.org/docs/api.html#modulename) itself it's best to leave modules unnamed in order to keep them portable.

**Comment by sebestenyb** [comment]
Same error.
Even if I remove everything but `requirejs` and `vis.js`, the error message is the same:

```
/Users/sebestenyb/Sites/cms/static/vendor/vis/dist/vis.js has more than one anonymous define. 
May be a built file from another build system like, Ender. Skipping normalization.
```

**Comment by josdejong** [comment]
Is this an error or a warning? The message you posted looks like a warning (`[...] Skipping normalization`)

I've almost zero experience with `r.js` (and hope to keep it that way ;) ), so I'm affraid I cannot be of much help here.

**Comment by josdejong** [comment]
It looks like an issue of `r.js`. Maybe related to https://github.com/jrburke/requirejs/issues/883?

**Comment by sebestenyb** [comment]
Yes, exactly the same error, like in that bug.
Warning during optimisation, error when running.
Found similar reports, that's why I suggested putting that string prefix in the define, which actually solves this issue: `define("vis", factory);`

Other suggestion is like this? https://github.com/jrburke/r.js/issues/558#issuecomment-33546625

**Comment by sebestenyb** [comment]
There's another anonymous define in the vis.js, for me it's line 28460.
Adding a name to ANY of the two helps.
The issue happens only if both are anonymous.

**Comment by josdejong** [comment]
I understand the issue with `r.js`, it's not capable of handling multiple anonymous modules. I would say `r.js` needs to be fixed here.

There is a recent issue at WebPack about this: https://github.com/webpack/webpack/issues/989 that could prevent this issue from occuring.

To solve this issue for you now, you could:
- add a transformation step where you simply replace the first `define(factory);` with `define('vis', factory);` in vis.js.
- maybe there is a way to create a named wrapper around vis.js and use that.
- create your own bundle of vis.js ([see readme](https://github.com/almende/vis#custom-builds)), where you exclude moment.js (the other anonymouse define) from vis.js and load it externally.
- dig r.js and use WebPack for your project

**Comment by sebestenyb** [comment]
I went with step 3, the other is kinda out of my scope, we have our pipeline, I can't modify it only for one project. Step 3 is not completely ideal either, it makes receiving updates of vis.js a bit harder.

Thanks for you help!

**Comment by josdejong** [comment]
It's indeed not ideal but great that you have a working solution now.
