### ISSUE TITLE
[Network v4] Get confused for selectNode event

### ISSUE THREAD

**Issue by rwu823** [almende/vis#884]
The `selectNode` event only trigger when didn't select any nodes. I'm not sure whether that is correct?

Work fine:
select one node(triggered) -> deselect node (click canvas) -> select one node(triggered)

Work fail:
select one node(triggered) -> select other node(no trigger) -> select other node (no trigger)

Please check the example:
http://jsfiddle.net/0552q6nx/

**Comment by aristotle8** [comment]
I have same problem. 
Also deselectNode event doesn't return Deselected Node, it returns empty nodes.

**Comment by AlexDM0** [comment]
Hi Guys,

Thanks for reporting. I'll fix both today and the release will be later this day. 

Sorry v4 wasn't as stable as I thought it was going to be!

Regards,

Alex

**Comment by AlexDM0** [comment]
@aristotle8 deselect is actually behaving as it should. 

Take a look at the docs. 

http://visjs.org/docs/network/

This is the content of the event:
```
{
  nodes: [Array of selected nodeIds],
  edges: [Array of selected edgeIds],
  event: [Object] original click event,
  pointer: {
    DOM: {x:pointer_x, y:pointer_y},
    canvas: {x:canvas_x, y:canvas_y}
    }
  },
  previousSelection: {
    nodes: [Array of previously selected nodeIds],
    edges: [Array of previously selected edgeIds]
  }
}
```

Since multiselect is possible, this format is actually correct.

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi, 

this has been fixed on the develop branch. We'll release this today.

Regards,

Alex
