### ISSUE TITLE
Change timeline point color programmatically

### ISSUE THREAD

**Issue by fedosejev** [almende/vis#886]
Is there a way to change timeline point color programmatically when it's not known in advance? Timeline item could have custom styling property for point, just like it has `style` for text.

**Comment by josdejong** [comment]
Well, what you can do is give items a `className` property ([see example](http://visjs.org/examples/timeline/styling/itemClassNames.html)). With CSS you can then style the items with this className. So what you could do here is dynamically generate CSS based on your data [as described here](http://stackoverflow.com/questions/1720320/how-to-dynamically-create-css-class-in-javascript-and-apply). It's a bit of a hack but it works.

**Comment by fedosejev** [comment]
@josdejong thanks for the suggestion. I am looking for a way to avoid this hack, because in my case I can have hundreds of points each having it's own unique color.

**Comment by josdejong** [comment]
What you could do too is design your items yourself. 

One way is to just make the default points invisible, and give the items an HTML contents with your own text and point. This point should be relatively positioned such that it's center lies on the place of the original point. For easily generating this HTML contents you can use Templates. 

Another way would be to override the `redraw` function of `PointItem` like:

```js
var PointItem = vis.timeline.components.items.PointItem;

// override the redraw method of PointItem
PointItem.prototype.origRedraw = PointItem.prototype.redraw;
PointItem.prototype.redraw = function () {
  // first invoke the original redraw
  this.origRedraw(); 
  
  // apply our custom color to the dot
  // supposes you've provided a color property for the items
  this.dom.dot.style.color = this.data.color;  
}
```

**Comment by fedosejev** [comment]
@josdejong thank you so much, overwriting `redraw` worked for me with a tiny change:

```js
this.dom.dot.style.borderColor = this.data.color;
```

**Comment by josdejong** [comment]
ah, yes, you are right that should have been `borderColor`.

ok great, I will close this issue.
