### ISSUE TITLE
Custom edge smoothing algorithms

### ISSUE THREAD

**Issue by FarzadT** [almende/vis#887]
This is a 2 part question.

1) Is it possible to write our own custom curve smoothing algorithm?

2) Is it possible to set a different algorithm per edge?

**Comment by AlexDM0** [comment]
Hi,

You cannot (with the public api) use your own algorithm. 

You can set smooth per edge, yes. 

Vis is open source so if you fork the project you can customise whatever you want :). If you come up with a cool new algorithm for the edges were always open for contributions. 

Regards,

Alex

**Comment by FarzadT** [comment]
Thanks for the quick reply! I would love to contribute. If you could point me out where in the code the algorithms are used that would be a good start for me.

**Comment by AlexDM0** [comment]
You can look in the lib/modules/components/edges map for all types of edges. I'd be curious to know what you have in mind that is not already in there? There's a lot of types :). 

Regards

**Comment by FarzadT** [comment]
Basically an algorithm that looks like this
![screen shot 2015-05-28 at 3 23 34 pm](https://cloud.githubusercontent.com/assets/1079013/7868977/9620606e-054d-11e5-80c7-83e3dd3958d6.png)

**Comment by AlexDM0** [comment]
Those are not possible with the quadratic beside curves. For those you'll need cubed Bézier curves with means you'll have to implement a new edge type with matching equations for the cubed Béziers. 

It is possible but a bit more work and a bit more math. 

http://www.w3schools.com/tags/canvas_beziercurveto.asp

You can do this with static smooth curves meaning you can copy that type and implement it. Look at the edge.js file for edge types.

Have fun :)

**Comment by AlexDM0** [comment]
Hi,

Any luck on this?

Cheers

**Comment by AlexDM0** [comment]
Hi,

I've added these edges. They'll be released either today or next week. I hope you haven't spent too much time on it. I needed them for something so I added them myself.

Regards

**Comment by FarzadT** [comment]
Awesome! I didn't have time to work on these. When is the next release?

**Comment by AlexDM0** [comment]
It has been added in v4.7.

Regards
