### ISSUE TITLE
External Legend Points don't match graph

### ISSUE THREAD

**Issue by Gillingham** [almende/vis#889]
![screen shot 2015-05-28 at 9 13 36 am](https://cloud.githubusercontent.com/assets/385396/7864999/79765352-051a-11e5-8e9f-46ba1a7b3589.png)

is there a way to make sure this isn't the case?

I noticed on http://visjs.org/examples/graph2d/09_external_legend.html some of the legends have inner coloring, although it seems to behave differently on the legend and on the graph. For example the line shows through the inner circles background color on the points on the graph but not the legend. Even more odd is if you toggle the CircleShaded group then the box line shows up through the inner circle on the BarGraph but only when you have CircleShaded disabled

**Comment by AlexDM0** [comment]
Hi,

I'll look into this next week. It should match.

Regards,

Alex

**Comment by AlexDM0** [comment]
I've reviewed the examples, it seems they do match on my computer. Could you give me your browser and os information?

Regards

**Comment by Gillingham** [comment]
Chrome 43.0.2357.81 (64-bit) on OS X

**Comment by AlexDM0** [comment]
Is this also the case on other browsers?

**Comment by Gillingham** [comment]
Also happens in Safari 8.0.6 and Firefox 38.0.1

**Comment by AlexDM0** [comment]
Could you make a jsbin with the example you show above?

Regards,

Alex

**Comment by Gillingham** [comment]
I haven't had time to duplicate my own example, but this is already duplicated in some ways http://visjs.org/examples/graph2d/09_external_legend.html as the far right dots do not match those in the legend, it may be the same underlying issue.

**Comment by ludost** [comment]
This has been fixed in the 4.11 release.
