### ISSUE TITLE
network.getConnectedEdges(nodeID) missing?

### ISSUE THREAD

**Issue by Twanks** [almende/vis#891]
I'm having trouble using the getConnectedEdges method as described in the vis.js documentation. After a quick glance at the code I found no mention of getConnectedEdges. Is this a documentation error or am I missing something extremely obvious? I'm trying to delete a node and any associated edges. Which I'm also curious if there is a direct deleteNode method where I can specify the ID.

**Comment by AlexDM0** [comment]
Hi,

Are you sure you have the v4.1 release? The 3.x does not match the docs as they are for 4.x. The version number is on top of the JS file. 

I just checked the code and it seems to be fine. If you got this off the cdn link then you'll have to get it from our website. The cdn guys have not synced up with the latest version. 

Regards,

Alex

**Comment by Twanks** [comment]
Yes that seems to have been the case in regards to having the wrong version. Makes a bit more sense now. As far as manual deletion of nodes, is there a way to do that without selecting the node first? I have background code deleting nodes/edges after a certain amount of inactivity but I would still like to be able to select other nodes while they are being deleted without my selection being reset. Thanks for this awesome project.

**Comment by AlexDM0** [comment]
Hi,

Take a look at the vis dataset for this. There is an example doing exactly this. 

Cheers

**Comment by Twanks** [comment]
Oh wow, fantastic. Staring me right in the face. Thanks!
