### ISSUE TITLE
Group visibility in 4.1.0 

### ISSUE THREAD

**Issue by AdamNowaczyk** [almende/vis#892]
I've updated to 4.1.0 and I'm getting this error when trying to set visibility (functionality works), but I see this in the console log:

Invalid type received for "visibility". Expected: any. Received [object] "[object Object]"

Problem value found at: 
options = {
  groups: {
    visibility
  }
}

vis.js:22698 Errors have been found in the supplied options object.

**Comment by brichbe** [comment]
According to example 14, http://visjs.org/examples/graph2d/14_toggleGroups.html, `groups.visibility` is an object for specifying the visibility of one or more of the groups.  You've left that part out of your `groups` options.

**Comment by AdamNowaczyk** [comment]
Well, not exactly. I'm setting this as in the example. It was working fine with 3.x and now reporting error with 4.x. Once again, groups are shown/hidden correctly.

         var groupsVisibility = {
            groups: {
              visibility: {
                0: false,
                1: false,
                2: false,
                3: false,
                4: false,
                5: false,
                6: false,
                7: false,
                8: false,
                9: false,
                "__ungrouped__": false // default group hidden
              }
            }
          };

**Comment by AlexDM0** [comment]
Hi Adam,

This is a problem with the validator lookup options overview. I'll get on it :).

Cheers

**Comment by AlexDM0** [comment]
This has been fixed on the develop branch. We will probably release another bugfix version this week.

Regards
