### ISSUE TITLE
v4 clickToUse Graph2d

### ISSUE THREAD

**Issue by AdamNowaczyk** [almende/vis#893]
I've spotted strange issue. When I create a graph and html input, that input is not clickable when for the graph clickToUse is true. 
Example:
http://jsbin.com/daqudemopu/1/

Try clicking input. You shouldn't be able to edit it. When changed to clickToUse: false, everything seems to be working fine.

--
Thanks,
Adam

**Comment by josdejong** [comment]
Thanks, we will have a look into it.

**Comment by ewjoachim** [comment]
It's probably related, I just switch to v4 and experienced the following : when clickToUse was true, I couldn't use a nearby bootstrap datepicker (clicks on it wouldn't be caucght by the datepicker). Switched to false and now it works.

**Comment by josdejong** [comment]
Should be fixed now on the `develop` branch.

**Comment by ewjoachim** [comment]
Thank you :)

--
 Joachim Jablon
