### ISSUE TITLE
OHLC+candlesticks support.

### ISSUE THREAD

**Issue by Losiara** [almende/vis#894]
Hello! 
Would like to use vis. Like it very much. It's highspeed and elegant. And smooth scaling out of the box is very nice. But I can't use it without candlestick or OHLC support. I saw someone opened simillar issue, and one of maintainers added this to "4.0 roadmap todo" and closed the issue. But now as I see there is no support. Is it stiil in plans or you refused the option? 
Is there any guide how to extend functionality? Or may be UML diagramm of library, which could ease adding this feature by efforts of non-maintainers?

**Comment by josdejong** [comment]
This feature request is on the list here: http://visjs.org/featureRequests.html

If you want to dive into this I think you can start here: https://github.com/almende/vis/tree/master/lib/timeline/component/graph2d_types

**Comment by AlexDM0** [comment]
Hi,

I've looked back in the issues but I can't find where I've labelled this as 4.0 specific? We collect feature requests on our website instead of them clogging up the git issues. This does not mean they are disregarded. 

Regards,

Alex
