### ISSUE TITLE
Edges Disappears after stabilization

### ISSUE THREAD

**Issue by filipnis** [almende/vis#895]
When my network is stabilized all edges disappears (they appears only during dragging). 

I'm using jquery+jqueryUI, and some of my own libraries.

What is wrong here ?

You can view it online at
http://infosys1.elfak.ni.ac.rs/tasordraw/?project=TasorProjects:Languages

![visjsproblem](https://cloud.githubusercontent.com/assets/911092/7878227/ec6fb040-05e4-11e5-9d95-f3bac64785fb.png)

**Comment by AlexDM0** [comment]
Which version of vis are you using? This happened with the 3.x version with mootools. V4 didnt have this problem. 

Regards

**Comment by filipnis** [comment]
Tanks or quick response.

 * @version 4.1.0
 * @date    2015-05-28

I have tried minified version and not minimified it is the same.

**Comment by AlexDM0** [comment]
Hi,

It seems this is the problem in Tagleen.js:

```
Function.prototype.bind = function (a) {
  var b = this;
  return function () {
    return b.apply(a, arguments)
  }
};
```

Why would you do this?

Ugly fix:
```
<script>
			var temp___bind = Function.prototype.bind;
		</script>

		<!--STANDARD JS-->
		<script type="text/javascript" src="./Tasor Draw_files/config.js"></script>
		<script type="text/javascript" src="./Tasor Draw_files/jquery-1.11.2.min.js"></script>
		<script type="text/javascript" src="./Tasor Draw_files/jquery-ui.min.js"></script>
		<script type="text/javascript" src="./Tasor Draw_files/Tagleen.min.js"></script>
		<script>
			Function.prototype.bind = temp___bind;
		</script>
```

Regards,

Alex

**Comment by filipnis** [comment]
Thanks a LOT.

That fix solve the problem (I'm aware it is not the best solution, but it works for now).

Which means it is problem in my libraries.

Function.prototype.bind did not exists in JS when this method has been defined in my libraries. This method is introduced in JavaScript 1.8.5, which has been released Jul 27, 2010 (according to WWW).

I will further look into my code and see how to deal with this.

Thanks again!!!

**Comment by AlexDM0** [comment]
I've also made the code robust against this as you are the second person to post this issue. The first was using Mootools which is quite large (and rapes all native objects). 

In general, do not touch what isn't yours goes a long way in avoiding these kind of issues ;). 

Basically what went wrong is the following:

```
foo.bind(this, true);

//should do
function foo(hide) {
  // hide = true and this = this
}
```

Whereas your code didn't exactly adhere to this spec. 

Regards
