### ISSUE TITLE
options is not defined error when layout is defined and physics is type object

### ISSUE THREAD

**Issue by redlehnewo** [almende/vis#896]
Environment :  version 4.0.0 of Network

Using the options object below, it produces a null exception.
                var options = {
                    width: '100%',
                    height: '600px',
                    autoResize : true,
                    groups : {
                        gates : {
                            shape : 'diamond'
                        }, prescriptive : {
                            shape : 'box',
                            color : '#CDFFC3'
                        }
                    },
                    edges:{
                        smooth : false,
                        arrows : 'to'
                    },
                    physics: {
                        hierarchicalRepulsion: {
                            centralGravity: 0.0,
                            springLength: 100,
                            springConstant: 0.01,
                            nodeDistance: 200,
                            damping: 0.09
                        },
                        solver: "hierarchicalRepulsion",
                        stabilization: {
                            enabled: true,
                            fit: true
                        }
                    },
                    layout : {
                        hierarchical: {
                            enabled:true,
                            levelSeparation: 150,
                            direction: 'LR',   // UD, DU, LR, RL
                            sortMethod: 'directed' // hubsize, directed
                        }
                    }
                }

Actual Result  : 
ReferenceError: options is not defined
    at LayoutEngine.adaptAllOptions (http://localhost:8000/js/build/vendor.js:89181:29)
    at LayoutEngine.setOptions (http://localhost:8000/js/build/vendor.js:89162:25)
    at Network.setOptions (http://localhost:8000/js/build/vendor.js:78678:35)

**Comment by AlexDM0** [comment]
Hi,

These options work for me, do you have the latest version of vis (4.1)?

Regards,

Alex

**Comment by redlehnewo** [comment]
Hi,

Sorry, I think this bug is just in version v4.0. I'm currently using v4.1 and it is working fine. Thanks.
