### ISSUE TITLE
Option "snap: null" of Timeline problem

### ISSUE THREAD

**Issue by kLm8** [almende/vis#897]
Setting option "snap" of the Timeline to null causes bug :

```
Invalid type received for "snap". Expected: fn, nada. Received [null] "null"

Problem value found at: 
options = {
  snap
}
```

My code :
```javascript
var options = {
    snap: null
};
```

**Comment by josdejong** [comment]
Thanks for reporting this issue, this is fixed now on the `develop` branch (though `/dist` isn't rebuild yet)
