### ISSUE TITLE
graph2d, v4 vertical scale

### ISSUE THREAD

**Issue by ewjoachim** [almende/vis#898]
Hello, 

Under v3.latest, my graph was properly scaled. Now with v4.1.0, it uses less that 1/2 of the available vertical space.

We can note that :
 - My data is between -5 and ~350 000 (it's a stacked bar graph, ~350 000 is the sum of all elements at the maximum, this value is both confirmed visually in vis and what I can see in other tools for the same data)
 - Vis choses a scale that goes from 0 to 800 000
 - my options say :

```javascript
dataAxis: {
  left: {
    range: {
      min: 0
    }
  }
}
```

I've noted that if I remove that option, the graph goes from -200 000 to 800 000 and it's probably well centered. I'm not sure at all, but maybe vis would be guessing the best scale and then clamping to my min-max, instead of trying to find the best max given the min ?

**Comment by ewjoachim** [comment]
From exploring the code, I find that ```Bargraph._getStackedYRange()``` finds a maximum of 660 000 which is then multiplied by 1.2 so that's how I get to 800 000.  ```Bargraph._getStackedYRange()``` uses the results from ```intersections```, which is computed in ```Bargraph._getDataIntersections```([here](https://github.com/almende/vis/blob/43b2fb5b9107c7fc9d9eeca69cd353a80bc58582/lib/timeline/component/graph2d_types/bar.js#L80)) (as far as I can tell)

I don't understand what the ```intersections``` are, so I'm clueless as to what's happening here and where does this 660 000 come from.

**Comment by ewjoachim** [comment]
Yup, confirmed, so that's my bug. vis will not stack bar over lines (that's normal) but it will consider the sum of both for the maximum.

**Comment by ewjoachim** [comment]
The problem can be reproduced easily from example 11 with modifications : just have one group as a line, others as bars and you'll notice that :

 - even though the line is not stacked the maximum is computed as if the line was indeed a stacked bar
 - the "stack" option when applied directly to the group options has no effect.

**Comment by AlexDM0** [comment]
Hi,

The stack option is not per group at the moment. I'll append the docs to reflect this. I see a piece of code was still active that would be part of the stacking lines system. This system is not finished and actually waiting on a big refactor of the graph2d. I did not expect people using stacked bars together with lines but I see that was an oversight on my part.

Could you make a jsbin to show your problem? We'll release a bugfix version this week to fix this and several other issues.

Thank you for getting to the bottom of this.

Regards,

Alex

**Comment by ewjoachim** [comment]
[Sure thing !](http://output.jsbin.com/saneqavugo/1) :smile:

**Comment by AlexDM0** [comment]
Hi,

thanks for sharing this easy example :) I've tested it with the updated codebase and the issue seems to be fixed now.

It'll be released around the end of this week.

Regards,

Alex
