### ISSUE TITLE
Network edges label with font align set will not float along with edges when edge points to itself

### ISSUE THREAD

**Issue by dragonzone** [almende/vis#899]
When an edge points to itself with a font setting:

font: {align: 'middle'} - FAILS!
font: {align: 'top'} - FAILS!
font: {align: 'horizontal'} - WORKS!
font: {align: 'bottom'} - FAILS!

    {
      "id": "abc", 
      "label": "relates to", 
      "from": "abc", 
      "to": "abc", 
      "font": {
        "align": "horizontal"
      }
    },

**Comment by AlexDM0** [comment]
Hi,

I've pushed a fix for this to develop. The label will always be horizontally aligned when the edge has the same node in from and to.

Thank you for reporting this.

Regards,

Alex
