### ISSUE TITLE
Example of how to use getEventProperties(event)

### ISSUE THREAD

**Issue by badzster** [almende/vis#901]
Hi,

I have spend hours trying to figure out how to use the getEventProperties(event) method in order to retrieve the date from where on the timeline the mouse is clicked.  I cannot find any examples.  Could you please direct me where there may be an example?  I must be missing something simple...I am sorry for the hassle and thank you in advance.

As per the example below I am trying to set customDate as the year on the timeline where the mouse was clicked...

__

    var customDate = new Date('2015-01-01')
    
    document.getElementById('visualization').onclick = function () {
        try {
            customDate = new Date(customDate.getFullYear());
            var barId = '12';
            timeline.addCustomTime(customDate, barId);
            document.getElementById('barId').value = '12';
        }
        catch (err) {
            console.log(err);
            alert(err);
        }
    };
___

Baden

**Comment by josdejong** [comment]
```js
document.getElementById('visualization').onclick = function (event) {
  var props = timeline.getEventProperties(event)
  console.log(props);
}
```

note that the timeline contains a built in `click` event which you could use too ([see docs](http://visjs.org/docs/timeline/#Events)), it gives you these event properties directly.

**Comment by badzster** [comment]
Thank you very much Jos – that has saved me hours

**Comment by woleEkanola** [comment]
`document.getElementById('visualization').onclick = function (event) {
  var props = timeline.getEventProperties(event)
  console.log(props);
}`

I am using in a drag event however it gives error saying timeline.getEventProperties is not a function
