### ISSUE TITLE
Cant come up with options{} that will work for my SNMP scanner ..  

### ISSUE THREAD

**Issue by sunscreen** [almende/vis#902]
there are some 200-300 nodes + the edges in my simulation every permutation I have tried always ends the same .. slow, cluttered, edges crossing all over even with diabolical spring length defined in physics and node data, the physics are making every thing illegible with it and with out it,  is there magic bullet set of options{} that will layout my network with a reasonable amount of space between each edge/node with out bouncing, juddering, moving, and generally being a pain the back side.. I have had it close but I lost those settings as when you go to tweak any thing it just radically messes up again and as theres so many options it becomes unclear which one breaks things once I had it working fairly nice but when I then when you expanded the clustered nodes its like it changes the physics settings internally and screws it all up again .. and thus end up going round and round and round...

I had to bring you this questions because I am thinking about changing to a different javascript graph api right about now and I would prefer not to do that as I quiet like visjs.js :+1: 

also "avoidoverlap" causes a stack space problem which i thought was going to be my ticket out of this but apparently not 

var options = {
  "edges": {
    "smooth": false
  },
  "physics": {
    "forceAtlas2Based": {
      "gravitationalConstant": -46160,
      "centralGravity": 0.045,
      "springLength": 80,
      "springConstant": 0.03,
      "damping": 0.98
    },
    "solver": "forceAtlas2Based",
    "timestep": 1
  }
}

with the above options when  you zoom in the whole sim is moving and unusable 
![2222](https://cloud.githubusercontent.com/assets/1124068/7901805/2a602e66-0793-11e5-9743-e3b4662c4956.png)

any advise would be appreciated 
thanks

**Comment by AlexDM0** [comment]
Hi,

If you could make a Jsbin or share your node setup I could take a look. 

There is no magic combination as it is greatly influenced by the data. I can see if I can come up with a good set of options. Without the data I really can't say anything. 

As for the clusters, it's up to you to ensure that the new cluster node has the same mass as the nodes you group into it. There is an example on our site doing this. 

You should make a layout without clusters and then start the clustering so all nodes have a stableish defined positions when you open the cluster. 

Avoid overlap is indeed broken. It was an experiment and I think it may have backfired. I'll see if I can remove it or disable it until there is a proper implementation. 

Regards,

Alex

**Comment by sunscreen** [comment]
ok will do AlexDM0  :)

**Comment by sunscreen** [comment]
hey Alex can i communicate with you directly as I don't want to share the scan data publicly as it is after all a map with ip address's etc  of our entire infrastructure and would not want it to fall into the wrong hands

**Comment by AlexDM0** [comment]
Hi,

I understand your data may be private. I would suggest however that you just anonymise the labels. Just nodes and edges without identifying labels should be fine. Keep in mind that the number of characters could matter depending on your nodeshape so if there is an ip like 192,168.32.03 just make it aaa.aaa.aa.aa or something. 

This should be easily automated with 5 lines of code. 

If needed I could give you my email but I'd prefer to have this open as this is a problem a lot of people face 

Regards,

Alex

**Comment by sunscreen** [comment]
yeah no worries I'll tweak the scanner to generate random ips/macs as the js code uses the ip's to build some connections

**Comment by AlexDM0** [comment]
It'd probably be easier if you generate a node edges setup, then save the dataset, anonymise and print the data. You can then use a simple network with your nodes, edges and option without support. 

That would be the easiest to set up and iterate on. 

Regards

**Comment by sunscreen** [comment]
Hi alex I tried to create a version that falsified the facts but it wont build the network coherently as every thing is effectively randomized so I'm not sure how to make the data/edges short of doing it manually by hand but that would be a bit to much time 

I have actually been fiddling with the options{} again and found  that by setting physics:false on the core switches nodes that it helps a great deal.. they get layed out in a nice inner circle - great for the ring topology that we are sporting in our network, even though its not strictly "ring"  some of it is infact "fully connected" never the less it looks way better.. but still these nodes over lap each other and the simulation still moves when you zoom in .. If I could just get it to stop moving when zoomed down and not have the switches overlaping and reduce the springyness but with out mangling crushing the layout all together 

it would be a step in the right direction for now

**Comment by AlexDM0** [comment]
Hi,

Let me try to understand. You generate your data and put it into network correct? Before you put it in, run a processing loop to anonymize all data. Then print the data row by row, finally send it to me.

Regards,

Alex

**Comment by sunscreen** [comment]
unfortunately this is the best I can get in Jsbins sandbox as its to wayward to behave it self .. it wont cluster the ports as something in anonymizing the data is upsetting it ... so it looks totally messed up but the data is there :( 

http://jsbin.com/vocicorifa/1/edit?js,output

**Comment by AlexDM0** [comment]
Hi,

I've had a look at the data and it seems to me like you're trying to do something like this:

http://bl.ocks.org/mbostock/4063550

You are severely crippling the physics simulation by setting physics to false on many nodes and manually setting edges very long.

I came up with something like this:
http://jsbin.com/nilowawaci/1/edit?html,output

Depending on what your network means you could change the values and have the font size adapt to the importance of the network.

Regards,

Alex

**Comment by sunscreen** [comment]
Hi alex thanks allot your a living legend both of those look very useful the first going back to what I was saying about ring / fully connected caters for both topologies and the second link solves the original problem nicely 
so thank you very much hopefully this will be helpful to others as well 
fantastic job :+1:

**Comment by AlexDM0** [comment]
You're welcome :) Have fun using vis
