### ISSUE TITLE
Expose DisablePhysics/RestorePhysics

### ISSUE THREAD

**Issue by ericvandever** [almende/vis#905]
Looking at the documentation/implementation of start/stop Simulation does not provide my desired behavior of a user controlling whether physics is running or not from a button.  I did see that you have a very nice implementation within the Physics module that listens for disable/restore Physics.  Do you have plans to expose this beyond the current use in manipulation?

Thanks for all the hard work that went into v4, it working really nicely.

**Comment by AlexDM0** [comment]
Hi,

How about setOptions({physics: true}) and setOptions({physics:false})? If this problem cannot be solved without expanding the API we can think about it but I believe this should be possible with the current implementation.

Regards,

Alex

**Comment by ericvandever** [comment]
I had considered that briefly before I saw the existing events, but didn't realize that I could just pass in a single change without having to resend all options every time.

Your solutions works for me.  Thanks again

**Comment by AlexDM0** [comment]
You're welcome. Have fun :)
