### ISSUE TITLE
Network Graph's (4.0) double click doesn't fired expectedly 

### ISSUE THREAD

**Issue by stanleyxu2005** [almende/vis#908]
While trying to upgrade from 3.1.1 to 4.1.0, I noticed that the `doubleClick` event behaviors differently than the older version.

In 3.1.1, if no node is selected and then I double click on a node:
1. The `nodes` in event object is one node. 
2. The node will be selected

In 4.1.0, I do the same thing:
1. The `nodes` in event object is empty
2. The node will NOT be selected.
If I select the node first and then double click on it, it behaviors correctly.

Is this a bug?

**Comment by AlexDM0** [comment]
Hi,

The answer would be: not really. 

The second click deselected the node. I agree however that this is confusing and I'll revert the behaviour to the old way. 

Regards,

Alex

**Comment by stanleyxu2005** [comment]
@AlexDM0 Thanks.

**Comment by AlexDM0** [comment]
I've pushed a fix to the develop branch.  We'll release it this week.

Regards,

Alex

**Comment by stanleyxu2005** [comment]
@AlexDM0 I tried out the develop branch. It works. By the way, my network graph (hierarchical layout) looks totally different after switching to the develop branch. I maybe wait for the next official release and try again.

**Comment by AlexDM0** [comment]
Hi,

Could you describe what you mean by different? There have not been changes to that part of the code as far as I know. 

Regards

**Comment by stanleyxu2005** [comment]
@AlexDM0 I have raised an issue #946 here.
