### ISSUE TITLE
Visjs.org Usability Feedback

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#909]
Hi guys,

I really like the new structuring of the (network) docs at vis.js! Also many thanks for investing a big amount of time in the docs!

Just wanted to give you some feedback (after I did quite a bit of option-lookup for v4):

**Navigation**
When navigating to network "modules" like "interaction" or "groups" there is no link (or breadcrumbs) back to the overview (http://visjs.org/docs/network/). I need to click on Modules (http://visjs.org/index.html#modules) and Network -> view docs again.

**Search**
Before 4.0 all config was on one page. While this often made it hard to find a setting. It was also easy to "globally" search for options (ctrl+f). Maybe it is possible in the future to implement a search over all options and link to the page where a particular option is described.

**Page Titles**
When I open some of the option pages as tabs, they all have the same window title ("vis.js - A dynamic, browser based visualization library") which makes it hard to distinguish which tab contains which infomation.

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

Thank you for the feedback! Good point about the breadcrums, I'll put a big button at the top.

We want to do some sort of search but we're not sure what the best way would be.

I'll update the titles as well, good catch!

Regards,

Alex

**Comment by felixhayashi** [comment]
Thanks! :+1:

**Comment by AlexDM0** [comment]
Hi Felix,

Since you got the hang of the pull reqs to the website, feel like picking this up? 

;) Worth a shot

Cheers

**Comment by felixhayashi** [comment]
Hi Alex,

I'll have a look at it :)

-Felix

**Comment by felixhayashi** [comment]
I added a pull for the breadcrumbs now. Once I find the time, I'll also have a look at the search ("tipue" looks promising for this).

**Comment by felixhayashi** [comment]
Hi Alex,

To complete this I integrated a searchbar this morning.

It is only implemented for the network/layout section and only scans the network section.

At the moment tipue does not show an extract of the result are like google but I had a look at their issue list and they plan to implement it in the next release (https://github.com/Tipue/Tipue-Search/issues/20)

I designed it with bootstrap elements and use a panel for the results. The resultspanel is contained in the navbar so it doesn't visually mix with the content.

A question: In case you guys like it, where should I do the pull request?  The devolp branch only contains the docs section. Should I do two pulls one for gh_pages and one for develop?

Demo (go to network/layout module): http://bit.ly/vis_site_demo

Hope you like it

One Issue is that fork me at github overlaps with certain screen sizes.

![selection_399](https://cloud.githubusercontent.com/assets/4307137/8595602/e3ecbe1a-2649-11e5-8b2d-bec719b5eadc.png)

![selection_400](https://cloud.githubusercontent.com/assets/4307137/8595604/e76804fa-2649-11e5-924b-43cfa398ad52.png)

![selection_401](https://cloud.githubusercontent.com/assets/4307137/8595609/ed34a2bc-2649-11e5-8ff6-d0f9e83f9b56.png)

![selection_402](https://cloud.githubusercontent.com/assets/4307137/8595611/f1b59cce-2649-11e5-8f22-2a1cf4704eb0.png)

![selection_403](https://cloud.githubusercontent.com/assets/4307137/8595612/f50d466a-2649-11e5-8adc-bd5ef960f047.png)

**Comment by josdejong** [comment]
Awesome, a search bar :)  I think this will work better if we split the docs in more and smaller pages, and remove tabs containing more hidden information (all docs should be as flat as possible).

**Comment by AlexDM0** [comment]
Hi Felix,

Looks good! Would this also work with anchors on the pages? We're thinking about removing the tabs (but keeping the categories) for clarity. Would that affect your implementation?

As for where to pull, only to develop is good. We don't usually hotfix the documentation and the releases are frequent.

Regards

**Comment by felixhayashi** [comment]
Glad you guys like it :)

> Looks good! Would this also work with anchors on the pages?

Tipue only seems to reference on a page level and anchors are not used by the search. So what Jos said about smaller pages would be an idea to improve search result. The drawback of smaller (more modulized) pages is, however, that you don't have all related information on one site and the pages might be harder to maintain.

Because the search is static, all relevant pages need to be added to a hashmap first and tipue then does ajax requests to get the page content.

> We're thinking about removing the tabs (but keeping the categories) for clarity. Would that affect your implementation?

That's fine. Since tipue doesn't know about tabs and just scans the whole html content it doesn't matter whether or not tabs are used. Per default the whole body is scanned but we could narrow this to a certain div with a certain class, not sure if this is needed.

> As for where to pull, only to develop is good.

Just to be sure: Then the searchbar will only exist for the docs section, correct? Otherise it will not be shown (e.g. start page).

**Comment by AlexDM0** [comment]
Hi Felix, 

Yes the search will have to be embedded in all the docs html files.. We are in dire need of a builder for this but we haven't gotten around to it.

Could tipue give an argument to the static page that can be read by javascript and forwarded to the relevant anchor so it would snap to the item?

Regards

**Comment by felixhayashi** [comment]
> Could tipue give an argument to the static page that can be read by javascript and forwarded to the relevant anchor so it would snap to the item?

No that's not possible in "live mode". I created an issue for that: https://github.com/Tipue/Tipue-Search/issues/21.

Another solution is to use "static mode" where you use a big json object in which you store keywords and text and the urls to display. But this is very hard to maintain and produces a big overhead.

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

Can we generate the JSON as a build script for static mode or is there manual effort required?

Regards

**Comment by AlexDM0** [comment]
Additionally, what do you think about a big friendly arrow below the search bar saying search the docs?

The docs are a bit of information overload and a pointer could help.

**Comment by felixhayashi** [comment]
Hi Alex

> Can we generate the JSON as a build script for static mode or is there manual effort required?

Hmm the format is JSON of the following structure and it needs to be saved in a javascript file that is included from the html document.

```javascript
var tipuesearch = {"pages": [
     {"title": "", "text": "", "tags": "", "url": ""},
     ...
```

See this site for example (http://www.tipue.com/search/demos/static/tipuesearch/tipuesearch_content.js).

> or is there manual effort required?

The manual effort is writing this script :D 

If you don't mind, I would suggest another approach that keeps things dynamic:

1. A user enters a keyword (e.g. "method barneshut") and clicks "go"
1. Since the search keyword is still accessible after the search was executed, I will use jquery to attach the keywords to the result links using a getter in the url (url.com/bla/blub?keywords=key1,key2)
1. then when a result link is clicked, and after the page reloads, I extract the keywords and I will highlight (http://bartaz.github.io/sandbox.js/jquery.highlight.html) all occurences e.g. yellow and use javascript to jump to the first occurence of a term. Or maybe highlighting is enough...

This method works better if there is no hidden content (no tabs).

> Additionally, what do you think about a big friendly arrow below the search bar saying search the docs?

Ok. I'll include it in the PR then.

I'll Also remove the "Go back" button in the docs as breadcrumbs solve this now, ok? It consumes much space.

**Comment by AlexDM0** [comment]
Hi Felix, 

Sounds good! We plan to stop the tabs anyway so this should solve the issue then!

Thanks so much for the effort!

Regards,

Alex

**Comment by felixhayashi** [comment]
> Sounds good! We plan to stop the tabs anyway so this should solve the issue then!

Great.

> Thanks so much for the effort!

You are welcome :)

I just finished implementing it and it works reeeaaallly nice!!
I'll upload it tomorrow after I am done with some last minor tweaks.

-Felix

**Comment by felixhayashi** [comment]
Hi @AlexDM0 and @josdejong 

Ok, I am done.

Demo:

1. **Visit the demo: http://bit.ly/vis_site_demo**
1. **go e.g. to the network docs**
  * you will see the searchbar appear.
    * I really think the searchbar would also be useful outside the docs section but since you wished to only implement it in the docs, it will only appear there.
1. **search for `timestep`**
  * after the page reloads the results are displayed in a panel
  * they keywords are appended to the href in the result-links
1. **click on the first result**
  * the page will open and all keywords will be highlighted
  * cannot directly see any highlighted keyword?
     * see the message in the navbar which says: "Click here to jump to the first keyword occurence!"
     * clicking it will jump to the first occurence
     * since scrolling to hidden elements is not possible I programmatically open the full options tab.

That's it, hope you like it

-Felix

**Comment by felixhayashi** [comment]
Hmm, I hope tipue will support narrowing the search in the next release. Created a ticket for that at their repo...

**Comment by AlexDM0** [comment]
Hi Felix, 

What do you mean by narrowing? Tipue is not a lot of code, modifying shouldn't be that hard :)

Regards

**Comment by felixhayashi** [comment]
Hi Alex

> What do you mean by narrowing?

What I meant was this: https://github.com/Tipue/Tipue-Search/issues/22

> Tipue is not a lot of code, modifying shouldn't be that hard :) 

I know, but too much hacking the lib means it won't be upgradeble anymore. Anyways, if the most relevant keyword is returned (as answered by tipue), then its probably fine.

-Felix

**Comment by josdejong** [comment]
@felixhayashi and @AlexDM0 it looks like tipuesearch blocks the page while fetching all (!) doc pages. The function `vis.initSiteSearch()` typically lets my browser hang for 2-3 seconds, which is quite annoying. Is there some configuration option for Tipue to load the files asynchronously instead?
