### ISSUE TITLE
Click-to-use deactivation with multiple graphs doesn't work

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#910]
Hi guys,

1. Click the first graph to activate.
2. Click outside to deactivate - doesn't work. Only clicking into the second graph will activate overlay for graph1 again.
3. Works only for the last graph addded (in this case graph2)

JSBIN
http://output.jsbin.com/sogoro/1

-Felix

**Comment by josdejong** [comment]
This was fixed with https://github.com/almende/vis/commit/ba5cf07b089eb64f0e3fc5a04cd0a63e5434bbc4

**Comment by felixhayashi** [comment]
Thanks
