### ISSUE TITLE
Network Graph's (4.0) AutoResize works different than I expect

### ISSUE THREAD

**Issue by stanleyxu2005** [almende/vis#915]
I put a network graph in a grid cell and set width to 100%; height to 400px; autoResize to true. The graph is layout as hierarchy. I resize the browser window, I can see `resize` event is fired. But the nodes will not re-calculate their positions, so that some nodes will be out of the visible area. Have I missed something?

**Comment by AlexDM0** [comment]
Hi,

There is no fit called to recenter at the moment. The idea is that you change the window from which you view the nodes, not freeze and scale it. 

Like looking outside through a window and changing the window, not shifting and scaling the outside view. 

I'm not sure which is the preferred result as both cases have their arguments. We'll discuss this internally.

Regards

**Comment by stanleyxu2005** [comment]
I'm curious if there is a conclusion available?

**Comment by AlexDM0** [comment]
Not yet, is quite busy over here so we wont get around to this for a little while. You can manually listen for the resize event and just call the fit function though?

**Comment by stanleyxu2005** [comment]
@AlexDM0 My current workaround is that:
```
network.on('resize', function(args) {
  network.fit();
});
```
So far it works fine to me.

**Comment by AlexDM0** [comment]
Hi,

I have fixed this properly on the develop branch.

Regards

**Comment by stanleyxu2005** [comment]
@AlexDM0 I can confirm it is fixed. Very appreciated!

**Comment by stanleyxu2005** [comment]
I'm sorry I need to reopen the issue. I noticed the resizing algorithm is buggy. When I resize the network graph, the size of node and text is incorrect.

![size1](https://cloud.githubusercontent.com/assets/5162687/9791137/27ce16d0-580c-11e5-8a1f-4a8a5cb1f390.png)
[Pic 1: Correct]

![size2](https://cloud.githubusercontent.com/assets/5162687/9791142/32488104-580c-11e5-8558-ffe89a6649a0.png)
[Pic 2: Incorrect]

**Comment by AlexDM0** [comment]
Hi,

4.8 was broken in this feature. 4.8.1 should have fixed this. 

Could you make a jsbin to show this?

**Comment by stanleyxu2005** [comment]
@AlexDM0 I'm using 4.8.2-snapshot (actually someone else's example) to make a demo. You just keep browser not maximized and then maximize your browser. Some nodes will be clipped by the border.

**Comment by AlexDM0** [comment]
Hi,

I see, I'm only using the width as a scale indicator here.. I'll take both width and height into consideration in the next release.

Cheers

**Comment by stanleyxu2005** [comment]
@AlexDM0 Cool for so quick response. Ciao~

**Comment by AlexDM0** [comment]
Just released in v4.8.2

**Comment by AlexDM0** [comment]
Sorry, wrongly labeled. I'll address this in the future release.

**Comment by AlexDM0** [comment]
Hi,

This has now really been fixed on develop. I'll add it in the next release.

Cheers

**Comment by stanleyxu2005** [comment]
Cool. Looking forward to the new release.
