### ISSUE TITLE
manipulation api questions

### ISSUE THREAD

**Issue by ericvandever** [almende/vis#916]
First, thanks for exposing the manipulation methods to allow adding/editing using the configured handlerFunctions without having to use the built in toolbar.  

I'd like to have a manipulation buttons within my ui styled based on the current edit mode.  Do you have any thoughts on  the recommended way to determine the active edit mode? 
 - poll internal variable network.manipulation.inMode - not great from an API perspective.
 - set flag when calling manipulation api, unset flag when I call callback within the handlerFunctions - are there other ways to exit manipulation / exceptional exit paths?
 - other ideas?

2nd, I was surprised at the behavior of deleteEdge and deleteNodes handlerFunctions.  When deleting a node (and the associated edges), I would have expected to get callbacks on both handler functions with the respective items as parameters.  Instead if a node is included, all items will be reported in the deleteNodes handlerFunction.  I don't have any particular issue with the behavior, just don't understand the use-case for splitting them out since I have to handle both in the deleteNode function anyway.  (I just pointed them both to a single onDelete handler).

3rd, all the manipulation API calls cause the physics to be reenabled regardless of setting before entering edit mode.  I'm pausing the physics engine as you suggested earlier this week (#905), but anytime I make calls to add nodes/edges, it begins to run again.

**Comment by AlexDM0** [comment]
Hi Eric,

I'll handle your points one by one. 

First, let's get this clear, you can style the manipulation bar anyway you like because it's all CSS. 

Now, assuming you want something really different, you can put the manipulation:enabled false to not use the manipulation GUI but can still use the methods as well as the handler functions. The edit button will also not be drawn. This means it's up to you to show your manipulation buttons and determine when to hide or activate them. Don't use internals. If you want to make the manipulation UI manually, don't partially use the edit button. You don't need to be in edit mode in order to use the methods. 

Second point. The delete handler functions are split because it also determines when the delete button is shown. You could want to allow deleting edges but not nodes. 

The handler methods should be supplied with the items they want to delete, is this not the case? If not, I'll fix that today. 

I'll take a look at the physics. 

Regards,

Alex

**Comment by ericvandever** [comment]
Alex,

Thanks for the assistance.  I've generated a small fiddle to help explain what I'm doing https://jsfiddle.net/34wtqr6c/2/.

1
I concur that it would be possible to style the existing bar. I had previously chosen to create my own toolbar with calls into vis in order to add buttons that I wanted, use alternative html (angular directives) and isolate interaction with the remainder of my app for things such as checking user permissions.

I believe that my standalone implementation does exactly what you suggested in the your second paragraph.  My primary question lies in the in ability for an external manipulation UI to know the state of the Vis manipulation service.  I feel that my sample would catch the majority of use-cases, but I'm concerned about reliably recognizing edge cases such as your comment on the delete function (// if for whatever reason the mode has changes (due to dataset change) disregard the callback)).   I don't think I communicated that very well this morning, hopefully the example will help.

2 
Thanks for the additional clarification.  From the [documentation](http://visjs.org/docs/network/manipulation.html), I didn't get that the boolean was for the display of manipulation components, I understood it to disable the ability to perform those actions.  I would recommend changing the phrases such as "When you supply a boolean, you only toggle the adding of nodes." to "When you supply a boolean, you only toggle the display of the add nodes button within the manipulation toolbar."  or something similar.

As another documentation enhancement, add the variables of the function for the deleteNode/deleteEdge since they are not simply properties of (Node|Edge) and a callback.  Basing off the addNode document: 
"This function will receive two variables: an object containing arrays of the nodes and edges to be deleted and a callback function"

3
Thanks.  Let me know if you need anything else.

-Eric

**Comment by AlexDM0** [comment]
Hi Eric,

I've pushed an update to the develop branch to fix the physics issue. Physics will now have an enabled field just like all the other modules.

When using the API with the methods while keeping manipulation:enabled at false, it will automatically handle the edit state for you. Basically, 'edit mode' does not matter if the manipulation gui is not showing. 

Once triggered, the callback will not be invalidated if the dataset is updated externally, although the mode will be disabled when the dataset is changed externally. 

There is no way to check which mode the manipulation system is in through the public API at the moment however. If you only want to add nodes and delete items, it may be safer for you to just use the click event and influence the dataset manually. The edit and add edge functionalities are specific to the manipulation module however. 

You could also listen to the (internal) _dataChanged and _resetData events which will reset the manipulation mode. I do not recommend using internals though! We could see if we want to implement a 'getMode' but it seems a little messy. If you develop your network and your manipulation API, hold off on the updating of the dataset until your operation is complete.

I have also updated the docs in the develop branch. If you still feel the docs do not accurately describe the behaviour, we welcome pull requests for clarification (to the develop branch :) ).

We'll release it tomorrow.

Regards,

Alex

**Comment by AlexDM0** [comment]
As far as I can tell, this issue is solved. If not please reopen it.
