### ISSUE TITLE
Center and resize network graph

### ISSUE THREAD

**Issue by oriko** [almende/vis#917]
Hi

Is there a way to put the vis network graph always in the center of it's wrapper div and to resize it, so the all network graph will be visible no matter how big it is?

Thanks,

**Comment by AlexDM0** [comment]
Hi,

It sounds like you're referring to the fit() method?

add:

```
window.onresize = function() {network.fit();}
```
to your code and you seem to be done.

Regards

**Comment by oriko** [comment]
Hi 

I got this error.... network.fit is not a function, but I can see that network is not null. 

 $scope.network = new vis.Network($scope.container, $scope.data, $scope.options);
                if($scope.network){
                    $scope.network.fit();
                }
              window.onresize = function() {
                    if($scope.network){
                        $scope.network.fit();
                    }
               }

maybe I need to wait that network is ready?

**Comment by AlexDM0** [comment]
Which version of vis are you using?

**Comment by oriko** [comment]
3.12

**Comment by AlexDM0** [comment]
Back then it was called zoomExtent(). I'd recommend you upgrade to the new version. There is an angular directive available as well.

https://github.com/visjs/angular-visjs

Regards

**Comment by oriko** [comment]
OK... thanks, I will try

**Comment by oriko** [comment]
Hi 

after upgrading vis js I got this error on my edges
TypeError: Cannot read property 'id' of undefined
    at BezierEdgeDynamic.setOptions (vis.js:39170)
    at BezierEdgeDynamic.EdgeBase (vis.js:40151)
    at BezierEdgeDynamic.BezierEdgeBase (vis.js:40008)
    at new BezierEdgeDynamic (vis.js:39155)
    at Edge.updateEdgeType (vis.js:35844)
    at Edge.setOptions (vis.js:35795)
    at new Edge (vis.js:35754)
    at EdgesHandler.create (vis.js:21028)
    at EdgesHandler.add (vis.js:20945)
    at Object.add [as callback] (vis.js:20696)

What can cause it ?

**Comment by AlexDM0** [comment]
I don't know what you're doing. I'll need some code that produces this to check. All our examples work fine so if I were to guess, you're doing something wrong :p

**Comment by AlexDM0** [comment]
Are you making an edge without any properties? 

```
var edges = [{}];
var data = {nodes:nodes, edges:edges};
var network = (container, data, options);
```

That could be whats going wrong?

**Comment by oriko** [comment]
Hi 

I handled it, there was a problem with the id.
but now for some reason x  and y locations for node are not working

**Comment by AlexDM0** [comment]
In 4.0 they are not fixed by default. You will need to supply fixed:true to fix them in place.

Regards

**Comment by nipunarora** [comment]
I have a similar issue, I use the following for generating the vis graph, and the graph is often outside the parent div. What is the best way to make sure it is centerd and zoomed out such that the entire graph is visible. :


```

                         var label = dataArray[i]['label']

                        var divHeader = document.createElement("div")
                        divHeader.innerHTML = '<h4 align="center">Type 6 Model for Source: ' + label + ' </h4>'

                        var div = document.createElement("div");
                        div.id = label + '-type6';
                        div.style.width = "100%";
                        div.style.height = "400px";
                        div.style.border = "1px solid lightgray";

                        type6Body.appendChild(divHeader);
                        type6Body.appendChild(div);

                        var nodes = new vis.DataSet(dataArray[i]['type1']);
                        var edges = new vis.DataSet(dataArray[i]['type6']);
                        var container = div;
                        var data = { nodes: nodes, edges: edges };
                        //var options = { physics:{enabled:false}, layout:{randomSeed:undefined}};
                        var options = { physics:{enabled:false},layout:{ improvedLayout:true, hierarchical:{ enabled:false, levelSeparation: 150, direction: 'UD', sortMethod: 'hubsize'}}};

                        var network = new vis.Network(container, data, options);

                        network.on("click", function (params)
                        {
                            if((params.edges.length!=0)&&(params.nodes.length==0))
                            {
                                var id = parseInt(params.edges[0]);
                                visEdgePopup(id,label,'6');
                            }
                            if(params.nodes.length>0)
                            {
                                var id = parseInt(params.nodes[0]);
                                visNodePopup(id,label,'6');

                            }
                        });
```

**Comment by nipunarora** [comment]
I am using version 4.8.1

**Comment by JorricksTU** [comment]
Did you manage to fix it nipunarora?

**Comment by alotan** [comment]
having the same problem, using version 4.9.
the chart is also circling around her self and i can't stop it

my code:
var nodes = new vis.DataSet(nodes_array);
// create an array with edges
var edges = new vis.DataSet(edges_array);

 // create a network
 var container = document.getElementById(target);
 var data = {
      nodes: nodes,
      edges: edges
};

    var options = {
	  "physics": {
	    "forceAtlas2Based": {
	      "gravitationalConstant": -138,
	      "centralGravity": 0.02,
	      "springLength": 100
	    },
	    "minVelocity": 0.75,
	    "solver": "forceAtlas2Based",
	  }
	}
    var network = new vis.Network(container, data, options);
    network.fit();

**Comment by mojoaxel** [comment]
@alotan Please use version 4.17.

**Comment by alotan** [comment]
did not help

**Comment by alotan** [comment]
http://be-strategic.solutions/Untitled-1.jpg

**Comment by mojoaxel** [comment]
@alotan It would be much easier to figgure out your problem if you could provide an simple example e.g. at jsbin.com

**Comment by dmc2015** [comment]
I think the initial subject has change but, I was having a similar issue.

I decided to wrap the network.fit method into a setInterval and then that into a window.resize event.
Works for me.

window.onresize = function() {
  setInterval(function() {
    network.fit();
  }, 2000);
};

Still having issues with the height being responsive though:
https://github.com/almende/vis/issues/1832

**Comment by jhabap18** [comment]
Hi @AlexDM0 ,
thanks for the solution.  network.fit() solves the issue. But what it does is, it fits to the container. So it zooms out the network (puts scale 1). 
If I want graph to always comes at center and also remains zooms in (doesn't matter if some part of network gets hidden in container), the what can I do.
Not sure issue #1908  addresses same problem or other.

**Comment by evictor** [comment]
Found this via Google. Is it possible to create a responsive Network graph? What I mean is, I have a tree/downward hierarchical network graph with an initial height that I want to be able to expand in height 'as needed' as nodes are clicked and further levels are introduced.

I've been trying to fake it by adjusting its container's height in accordance with the displayed depth, but it is highly irregular and unreliable because nodes get smaller with zoom out.

It would be ideal if the current height of the chart could be known somehow—i.e. the bottom coord (y + height) of the bottommost node minus the top coord of the topmost node. With that, I could wire up my own mechanism to resize the container appropriately by binding various events (e.g. "on stabilized").

**Comment by wimrijnders** [comment]
As a possibly simple solution, can I suggest disabling zoom? In the options:

```js
	interaction: {
 		zoomView:false,
 	},
```

Perhaps this has the desired effect.

As to the height of a network:

```js
function networkHeigth() {
  var min;
  var max;

  var positions = network.getPositions();
  for (var n in positions) {
    var pos = positions[n];

    if (min === undefined || min > pos.y) {
      min = pos.y;
    }
    if (max === undefined || max < pos.y) {
      max = pos.y;
    }
  }

  console.log('height: ' + (max - min));
  return max - min;
}
```

This, of course, works with node coordinates only. Adjusting for the node dimensions is left as an exercise for the reader.

**Comment by evictor** [comment]
Thanks for the pointers and encouragement. I managed to finagle together a solution that is rather complex but works a treat (see [example screen cap](https://gfycat.com/gifs/detail/AcidicPeacefulInganue)—note the white box expanding and contracting to the appropriate height against the grey page background).

I should probably bundle this into a pull request or plugin, but I'll admit I don't have a great deal of time at the moment to do that.

Note the code below with copious explanatory comments:

```
let yMin = Number.MAX_SAFE_INTEGER;
let yMax = Number.MIN_SAFE_INTEGER;
nodes.forEach(node => {
  // Using bounding box takes node height into account
  const boundingBox = network.getBoundingBox(node.id)
  if(boundingBox.top < yMin)
    yMin = boundingBox.top

  if(boundingBox.bottom > yMax)
    yMax = boundingBox.bottom
})

// Accounts for some node label clipping
const heightOffset = 50

// "Natural" aka 1.0 zoom height of the network
const naturalHeight = yMax - yMin + heightOffset

// container is a <div /> around the network with fixed px height;
// the child network <canvas /> is height 100%
container.style.height = naturalHeight + 'px'

// Lets the network adjust to its new height inherited from container,
// then fit() to zoom out as needed; note `autoResize` must be DISABLED for the network
network.redraw()
network.fit()

// Sometimes the network grows too wide and fit() zooms out accordingly;
// in this case, scale the height down and redraw/refit
container.style.height = network.getScale() * naturalHeight + 'px'
network.redraw()
network.fit()
```

**Comment by wimrijnders** [comment]
Ah, got it. You're resizing the div around the network, not the network to the div. Nifty, I can image other people having a use for this. Thanks for sharing!

**Comment by wimrijnders** [comment]
Closing because I believe this issue has been sufficiently addressed.

**Comment by amithit** [comment]
I have a graph component in React app,

<Graph
   graph={this.state.graph}
   options={graph_options}
   events={this.events}
/>
I hope to make it automatically zoom in/out when the graph changes, just like in vis.js document use network.fit()

But how I can call this fit method?

**Comment by amithit** [comment]
I have a graph component in React app,

<Graph
   graph={this.state.graph}
   options={graph_options}
   events={this.events}
/>
I hope to make it automatically zoom in/out when the graph changes, just like in vis.js document use network.fit()

But how I can call this fit method?
