### ISSUE TITLE
Timeline customisations 

### ISSUE THREAD

**Issue by yacineFantoussi** [almende/vis#918]
Hi everyone , we would like to use your timeline with a lot of customisation 
let's start with the stacking with grouping timeline example http://almende.github.io/chap-links-library/js/timeline/examples/example29_stacking_with_grouping.html
In order to achieve this , we need to have a vertically scrollable content (to display the several lines / contents with trucks but keeping the timeline displayed without having the page scroll displayed  )
The events must be draggable editable and removable too 
several events can occur a the same time and we want te capability to modify the order of events (eg : event 1 after event 2 then event 2 after event 1 ....) using drag and drop .
How can I achieve this easily sine I am not a JS expert  ?

Regards

Yacine

**Comment by AlexDM0** [comment]
Hi,

That example does not apply to vis.

http://visjs.org/timeline_examples.html
http://visjs.org/examples/timeline/groups/groups.html

As for dragging:
http://visjs.org/examples/timeline/editing/editingItems.html

You can set the height of the timeline independent of the height of the container, allowing you to drag up and down in the timeline.

Take a look at the docs:
http://visjs.org/docs/timeline/

Regards,

Alex

**Comment by yacineFantoussi** [comment]
Hi Alex I think that It is not the right project since we are still using chap links library
I 've posted the same question in chap-links-library 
Regards

Yacine

**Comment by AlexDM0** [comment]
Ok, good luck :)

Regards,

Alex
