### ISSUE TITLE
[Network] Suggestion: configure to disable text's bold when select or hover 

### ISSUE THREAD

**Issue by rwu823** [almende/vis#920]
Hi Alex

Now that is no ways to disable text's bold style when select or hover but still keep event triggers.

Currently one way to disable text's bold style but also disable event :(
```js
var options = {
  interaction:{
    hover: false,
    selectable: false
  }
}
```

I think the text's bold should not be provided by the library itself. release it let developers have more flexible custom style control.
I going the big project with network library, our Visual Designer don't like that and this problem perplex for me :(

**Comment by AlexDM0** [comment]
Hover does not bold the text:

http://visjs.org/examples/network/nodeStyles/colors.html

As for select, you can change the line of code that does this yourself until a better solution comes along. It's in the label class. 

In the calculate label size just add selected = false; at the first line here:
https://github.com/almende/vis/blob/master/lib/network/modules/components/shared/Label.js#L214

and the same here:
https://github.com/almende/vis/blob/master/lib/network/modules/components/shared/Label.js#L54

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi,

I've just added the labelHighlightBold option to nodes and edges on develop. This will be included in the next release.

Cheers

**Comment by rwu823** [comment]
Sounds great. thanks :)

**Comment by AlexDM0** [comment]
Added in release v4.4.0
