### ISSUE TITLE
Layout immediately, just like after moving a node

### ISSUE THREAD

**Issue by mariusschulz** [almende/vis#921]
I'm using vis to visualize nodes and edges of a program control flow graph. This is how the visualization looks like after initializing the network:

![before](https://cloud.githubusercontent.com/assets/947523/7962487/e7786848-0a0d-11e5-9e7c-edd041153d4d.PNG)

And this is how it looks like after grabbing one node and moving it minimally:

![after](https://cloud.githubusercontent.com/assets/947523/7962486/e773649c-0a0d-11e5-9d08-80f89138a8b6.PNG)

Is it possible to have the network look like the second version right from the get-go, layouted and spaced out, without having to drag nodes first? That graph is a lot prettier to look at. :)

I'm using the following settings:

```js
var options = {            
    width: "100%",
    height: "100%",
    
    layout: {
        hierarchical: {
            levelSeparation: 85,
            direction: "UD",
            sortMethod: "directed"
        }
    },
    
    edges: {
        smooth: true
    }
};
```

**Comment by AlexDM0** [comment]
Hi,

You should position your nodes x's position manually in order to do this. Something like:
```
var nodes = [
{id:1, x:0},
{id:2, x:1},
{id:3, x: 0}
]
```

Your initial position is 0,0,0 and technically, that is stable but very volatile.

Regards,

Alex

**Comment by mariusschulz** [comment]
Hi Alex,

thanks for your quick reply.

I'm aware I can set the x positions manually. However, I was looking for a method I can call that does the same layouting that is triggered when moving an arbitrary node by a single pixel. Am I correct in assuming that there's no way to invoke this sort of method through the API?

Best,

Marius

**Comment by AlexDM0** [comment]
Hi Marius,

You're right, there isnt. You could just use Math.random() to give them a random x offset? It should be sufficient.

```
var nodes = [
{id:1, x:Math.random()},
{id:2, x:Math.random()},
{id:3, x:Math.random()}
]
```

Regards

**Comment by mariusschulz** [comment]
I'm going to try that then, and if it doesn't yield the results I'd like, I'll probably have to position the nodes myself.

Any chance we're going to see the auto-layout-invoking method in the future? ;)

Thank you!

**Comment by AlexDM0** [comment]
Well no. Technically the solution is correct. 

Good luck!
