### ISSUE TITLE
Add the the 'event' parameter to the 'select' timeline event.

### ISSUE THREAD

**Issue by xsebas21** [almende/vis#923]
When firing the 'select' event on the timeline, add the 'event' parameter as well, along with the existing 'items' object.

**Comment by josdejong** [comment]
Hm, that may make sense. Why do you need the event exactly?

**Comment by micmeemac** [comment]
I would like the event for easy access to the dom node that triggered the event

**Comment by josdejong** [comment]
And why do you need the DOM element?

(just trying to figure out your use case)

**Comment by micmeemac** [comment]
I'm showing a popup with further data that I would like to position relative to the element.

**Comment by josdejong** [comment]
Makes sense. I've added the property, will be available in the first next release.

**Comment by micmeemac** [comment]
Great :) Very much appreciated!
