### ISSUE TITLE
Timeline - Anyway to set groups so items cannot overlap?

### ISSUE THREAD

**Issue by supertemp** [almende/vis#924]
Love the library, just came across it yesterday. One question, we are looking to use the timeline as a scheduler, and everything is great except I haven't found any way to set the items in the group to not overlap, is there any way? 

We are wanting to use it to schedule a set of factory machine's up times, and they cannot overlap. So the user will drag and drop start/stop times to set the times the machines is available to use. Each group will be a different machine.

So no stacking and no overlapping, the end time of a previous item cannot go past the start time of the next one. Also we have to prevent the adding of new items on a slot where the machine is already scheduled as on.

**Comment by josdejong** [comment]
Yes you can do this by by creating handlers `onMoving`, `onAdd`, etc and writing your own logic to prevent overlap there.

Example: http://visjs.org/examples/timeline/editing/editingItemsCallbacks.html
Docs: http://visjs.org/docs/timeline/#Editing_Items
