### ISSUE TITLE
The 'timechanged' event doesn't fire when the mouse cursor has dragged outside the timeline bounds

### ISSUE THREAD

**Issue by micmeemac** [almende/vis#925]
This can be reproduced at http://visjs.org/examples/timeline/other/customTimeBars.html as follows:
• put a breakpoint inside the 'timechanged' handler
• start dragging the custom time
• ensure the mouse cursor leaves the timeline area while dragging
• on drag end, the breakpoint is not hit

I am using this event on a mini timeline to set the window of another timeline. Using the 'timechange' event is too expensive. Is there perhaps a workaround in the mean time?

Thank you :)

**Comment by micmeemac** [comment]
Using 'timechange' continuously, it turns out there's no performance issue. Is this a result of the switch to v4? Cool

**Comment by josdejong** [comment]
Thanks for reporting this bug.

A browser may fire tens to hundreds of drag events while dragging the custom time bar. Whether you can use 'timechange' continuously depends on what you do during the callback. You could of course throttle this event yourself.

**Comment by micmeemac** [comment]
Yes, I would prefer to have access to 'timechanged' :) Thank you Jos

**Comment by josdejong** [comment]
We'll fix it

**Comment by micmeemac** [comment]
Excellent :) Thanks

**Comment by josdejong** [comment]
I've fixed this in the `develop` branch. We expect to do a release of vis.js tomorrow.

**Comment by micmeemac** [comment]
Thank you for your speedy and excellent work. Really great

**Comment by josdejong** [comment]
You're welcome :)
