### ISSUE TITLE
How to set an initial scale for network?

### ISSUE THREAD

**Issue by josdejong** [almende/vis#926]
How can I set an initial scale for a network? There are no configuration options for this, and `moveTo` doesn't work when applied directly after creating the network. We could call `moveTo` after the network has been stabilized, but that will show the network with the wrong initial view 

```js
network = new vis.Network(container, data, options);
network.moveTo({scale: 2, animation: false});  // Does not work
```

See this jsbin: http://jsbin.com/xazeve/1/edit

**Comment by AlexDM0** [comment]
Im not sure what the usecase is but you can disable the fit after stabilization. The scale will not be changed then. 

http://jsbin.com/zonupacugu/2/

**Comment by AlexDM0** [comment]
To do it correctly (use the center of view you get from the fit), you'll have to put the moveto in the stabilizationIterationsDone event:

http://jsbin.com/kebabojago/3/edit

The basic process of the network is:

init
start stabilization (async)
stabilizationProgress (async) (x times)
(if fit is enabled, fit and request render, but not render yet)
stabilizationIterationsDone 
(if stabilized, stabilized)

RENDER START
initRedraw
beforeDrawing
afterDrawing

Regards,

Alex

**Comment by josdejong** [comment]
thanks!
