### ISSUE TITLE
In the event 'dragStart' does not include current selected id of node

### ISSUE THREAD

**Issue by AlexCro** [almende/vis#927]
In the event 'dragStart' does not include current selected id of node.

function visDragStart(items) {
    items.nodes.length; // 0

function visDragEnd(items) {
    items.nodes.length; // 1

Why?

**Comment by Peter-Gabel** [comment]
Hi -
Thanks for an excellent library!

I noticed this also. In addition, getSelectedNodes does not return the node being dragged but rather the node (if any) that was previously selected.

 A work around is to use the getNodeAt method using the event location:
		myGraph.on('dragStart', function(params) {
			console.log('dragStart', params.nodes);      // incorrect node returned in array
			var x = params.pointer.DOM.x;
			var y = params.pointer.DOM.y;
			console.log('pos', x, y, myGraph.getNodeAt({x:x, y:y}));   // correct node returned
                        ....
                })
Peter Gabel

**Comment by AlexDM0** [comment]
Hi all,

I'll fix this tomorrow before the release. 

Regards

**Comment by AlexCro** [comment]
Thanks for an excellent library! :)

**Comment by AlexDM0** [comment]
Hi,

This has been fixed ont he develop branch, I'll release it later today. I'd prefer to keep the issue open until the fix has been released to avoid duplicates.

Thank you both for reporting!

Regards,

Alex

**Comment by AlexCro** [comment]
Hi,
In release 4.2.0
When dragging view (the cursor is not on the node), in event 'dragStart' included previous selected id node. Array of nodes must be empty. Sorry for my bad English.

**Comment by AlexDM0** [comment]
Hi,

Sorry, sloppyness on my part. I've pushed a fix to develop for it. I noticed this was also the case for the dragging and dragEnd events. This is also been fixed on develop.

Regards

**Comment by AlexDM0** [comment]
This has been fixed in 4.3
