### ISSUE TITLE
Not able to turn off simulation entirely by checkbox

### ISSUE THREAD

**Issue by mvnagy** [almende/vis#928]
I'm making a "toggle gravity"-checkbox. On checked it fires network.startSimulation(), and on unchecked it fires network.stopSimulation().

When the checkbox is unchecked, and a node is pulled to a new position, it automatically fires a startSimulation() again. I want the nodes not to move in this situation. How can I prevent this?

I have tried adding a startStabilizing-event which immediately fires a stopSimulation(), but it does not work as intended.

Using VisJS 4.1.0.

**Comment by AlexDM0** [comment]
Hi,

You'll need to call setOptions({physics:false}) to disable the physics. StopSimulation really just stops the simulation if it's running. 

Regards

**Comment by mvnagy** [comment]
Thank you! Hehe, how did I not see this.
Amazing library btw!

Best,
Martin

**Comment by AlexDM0** [comment]
You're welcome :).

In the release I'll do later today, the physics will have an enabled field just like the other modules. The effect would be the same but it's a bit clearer then.

Regards
