### ISSUE TITLE
Dynamic graph clusters

### ISSUE THREAD

**Issue by yamini16** [almende/vis#930]
I am using vis network module. I am trying to expand the graph dynamically by clicking on its nodes. The only node part works fine but when I include clusters, things get messy. Assuming I have a cluster in my existing graph. Now I would like to expand the graph using the selected node's data. In this case, if one of the edges from this node has its destination as one of the nodes in the cluster, the graph simply shows some edges without the nodes. When I expand the cluster, the graph seems fine. Is there any way to integrate the clusters in graph updates?

**Comment by AlexDM0** [comment]
Hi,

At the moment no, you cannot preconfigure clusters. That means you cannot load clusters as data. They have to be formed afterwards. On the upside, clustering is fast so you could expand the clusters, update the data and cluster again. Maybe turn off physics in the mean time.

Regards,

Alex
