### ISSUE TITLE
Node Radius feature removed in 4.X

### ISSUE THREAD

**Issue by mmcsivakumar** [almende/vis#931]
Hi,

please let me know whether Node Radius feature removed in 4.1 release. I'm using the the box style node with 0 radius like Rectangle.

Is any other way to display the Rectangle shape. FYI, I  need to display the label inside the rectangle. Please help me to out from this.

**Comment by AlexDM0** [comment]
Hi,

I just checked back to the old versions and I see what you mean. It was never in the docs so I was not aware that this actually was a feature. Because of that, I did not port it over to the 4.x versions. 

I'd rather not have specific options for one node type so we'll think about how we can customize node types in a clean and future proof way.

For now, it's not possible to have rectangle shapes with the label inside the rectangle. 

If you'd like, you could modify the source to do what you want right now. It's on line 28271 of the 4.2.0 which is now on the website.

Regards,

Alex

**Comment by mmcsivakumar** [comment]
To clear, i have mentioned the snippet below for the shape box, i used the radius. 

bapp: {
                                                radius: 5,
                                                color: {
                                                    background: '#87B242',
                                                    highlight: {
                                                        background: '#87B242'
                                                    }
                                                },
                                                fontSize: 10,
                                                shape: 'box'
                                            }

As you suggested, i ll look on the source and will change accordingly. Thanks for your suggestion.

It seems i'm using 4.1 version. Well Is 4.2 released, what is the delta w.r.t network.

**Comment by AlexDM0** [comment]
Hi,

Bugfixes mostly:
https://github.com/almende/vis/blob/master/HISTORY.md

Improved robustness against people molesting the Function.prototype.bind()
Fixed few functions including storePositions().
Added beginnings of unit testing for network.
Fixed #904, correctly parsing global font options now.
Fixed dataView support for storePositions.
Second click on node is no longer unselect.
Added releaseFunction to openCluster.
Fixed bug where the network could flicker when the pixelRatio is not integer.
Added enabled property to physics.
Fixed #927, dragStart event didnt contain node that was being dragged

Regards,

Alex

**Comment by mmcsivakumar** [comment]
Thanks Alex. I changed the source and working as expected.

If possible, bring the rectangle shape and radius support in your feature releases.

I'm closing this thread. Once again thanks.

**Comment by AlexDM0** [comment]
you're welcome :)

I'll reopen the issue until a solution has been found.

Regards

**Comment by AlexDM0** [comment]
Hi,

I've added this in the release that will be done today.

It's called {nodes:{shapeProperties:{borderRadius:6}} and only applies to box shapes.

Regards

**Comment by AlexDM0** [comment]
This has just been released in v4.6.0
