### ISSUE TITLE
[Feature req] Event for hover over edges

### ISSUE THREAD

**Issue by redskate** [almende/vis#932]
Hi Alex

I was wondering wether visjs 4.0 allow to trigger a function on hovering an edge or a node.

Thank you

**Comment by AlexDM0** [comment]
Hi,

We try to avoid suppliant functions in options in favour of events. There is a hoverNode event available for this. 

Please refer to the docs for more information. There is no hover edge available at the moment although you could use the tooltips for this. 

Regards,

Alex

**Comment by redskate** [comment]
Hi Alex

ok, no hoverEdge .... hence.

Thank you

Fabio




Am 5.6.15 um 18:28 schrieb Alex:
> Hi,
>
> We try to avoid suppliant functions in options in favour of events.
> There is a hoverNode event available for this.
>
> Please refer to the docs for more information. There is no hover edge
> available at the moment although you could use the tooltips for this.
>
> Regards,
>
> Alex
>
>
>

**Comment by AlexDM0** [comment]
I might just make it hover. Or just add hover like select event. 

Let's keep it as a feature request (I think it's already in the requests as well)

Regards

**Comment by AlexDM0** [comment]
Hi,

I have added a blurEdge and hoverEdge event to the develop branch. It will be added to the next release.

Regards

**Comment by AlexDM0** [comment]
Added in release v4.4.0

**Comment by redskate** [comment]
Hi

nice!!! good to know
thx

Cheers
F

Am 30.6.15 um 17:13 schrieb Alex:

**Comment by felixhayashi** [comment]
Hi @AlexDM0

Could it be that the events are not triggered? Other events (e.g. select) work fine.

Please see: http://output.jsbin.com/yumawa

Thanks

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

Well yes, it needs to be enabled, just like with nodes: interaction:{hover:true},

Regards

**Comment by AlexDM0** [comment]
I'll add that to the docs

**Comment by felixhayashi** [comment]
Hi Alex,

ah ok. However, in the docs it says for hover:
> When true, the nodes use their hover colors when the mouse moves over them.

But actually don't want any color changes, I am just interested in the events. Is there a way to have the events fired without provoking a color change?

**Comment by AlexDM0** [comment]
You could put the same color in the hover color option?

**Comment by felixhayashi** [comment]
> You could put the same color in the hover color option?

True :+1: I forgot that I can control the hover color :)

Thanks solved.
