### ISSUE TITLE
Prevent redrawing after clicking on an edge

### ISSUE THREAD

**Issue by redskate** [almende/vis#933]
Hi Alex, 

with Version 4.2 ( I just made the change from 3.0.3 ) now clicking on a (selectable) edge causes redrawing the graph. This is very unwanted... how can I avoid redrawing the graph?

Thanks a lot in advance!
Fabio

**Comment by AlexDM0** [comment]
Hi Fabio,

We have to redraw, we have always redrawn on clicking an edge. 

We cannot show it is clicked on otherwise. This was also the case in 3.x. 

If I misunderstand what you mean, please make a Jsbin to show it. 

Regards

**Comment by redskate** [comment]
Hi Alex

Am 5.6.15 um 18:29 schrieb Alex:
> Hi Fabio,
>
> We have to redraw, we have always redrawn on clicking an edge.
Not at all (sorry) - you changed now something here  - see please my
demo on http://semweb.ch/leistungen/rdfservices/en-entitylinking/, put
some English text ("The library is designed to be easy to use, to handle
large amounts of dynamic data,") and let correlate (button).

Than click on an edge - nothing moves ...

Fabio

>
> We cannot show it is clicked on otherwise. This was also the case in 3.x.
>
> If I misunderstand what you mean, please make a Jsbin to show it.
>
> Regards
>
>
>

**Comment by redskate** [comment]
Hi again Alex

You do not have to redraw the whole graph once a user clicked (not
moved) an edge ...
Clicking on the edges reorganizes (now) the graph. With 20 - 30 graph nodes.
This is not acceptable to me since it brings unrest in the scene - I
will have to reconsider the older version 3.0.3 ...

But I am confident you maybe find a workaround ....?

Cheers
Fabio



Am 5.6.15 um 18:53 schrieb Fabio Ricci:
> Hi Alex
>
> Am 5.6.15 um 18:29 schrieb Alex:
>> Hi Fabio,
>>
>> We have to redraw, we have always redrawn on clicking an edge.
> Not at all (sorry) - you changed now something here  - see please my
> demo on http://semweb.ch/leistungen/rdfservices/en-entitylinking/, put
> some English text ("The library is designed to be easy to use, to
> handle large amounts of dynamic data,") and let correlate (button).
>
> Than click on an edge - nothing moves ...
>
> Fabio
>
>>
>> We cannot show it is clicked on otherwise. This was also the case in
>> 3.x.
>>
>> If I misunderstand what you mean, please make a Jsbin to show it.
>>
>> Regards
>>
>>
>>

**Comment by AlexDM0** [comment]
Hi Fabio,

Yes we do have to redraw the graph to show the thicker edge. There is no workaround here an this is the way it's always been. It is simply not possible to not redraw if we want to show the edge thicker on selection. 

I just tried and I don't see anything out of the ordinary. There is a network, it's stabilized, I tap an edge and it becomes thick, nodes remain still. That is the intended behaviour. What am I looking for?

Regards,

Alex

**Comment by redskate** [comment]
Hi Alex

yes, this is the behavior I would need:
1. Let the graph stabilize (this works super)
2. Click on an edge
2.a the edge changes thickness/color
2.b the graph nodes remain at their position

Right now on step 2) the graph nodes are scrambled on edge click. I
suppose this was not intended...


Below I added how I init the graph.
Maybe this is a hint - what is wrong ... ?

Cheers
Fabio


Am 5.6.15 um 19:09 schrieb Alex:
> I just tried and I don't see anything out of the ordinary. There is a
> network, it's stabilized, I tap an edge and it becomes thick, nodes
> remain still. That is the intended behaviour. What am I looking for?

var options = {
            width: default_w+'px',
            height: default_h+'px',
            interaction: {tooltipDelay: 700},
            nodes: {
                color: {
                  background: '#eee',
                  border: '#eee',
                  highlight: {
                    background: '#E76000',
                    border: 'black'
                  }
                },
                font: "12px arial black",
                shape: 'dot'
            },
            interaction: {tooltipDelay: 700},
            navigation: false,
            dataManipulation: false,
            hover: true,
            stabilize: true,
            clickToUse: false,
            clustering: false, // sfalsa click events
            hideEdgesOnDrag: true,
            initialMaxNodes: 8,
            physics:{barnesHut:{springLength:75,springConstant:0.015}}
        };

**Comment by AlexDM0** [comment]
Look in your console, some of these option are not in v4. 

Look at our examples. Can you reproduce the behaviour there?

I can't debug like this. Reproduce it somewhere simple and I can fix it or you'll find your issue when attempting to reproduce.

**Comment by redskate** [comment]
Hi Alex

ok - I looked once again and corrected the init options.
Then I looked into the code.

It happens that on the call data.edges.update(edge) - needed to color
the edge on click - the whole graph nodes are scrumbled, the graph
restabilize (I hope to use the terminology in an exact way).

I also tried a fiddle http://jsfiddle.net/redskate/Lmvmvxcy/14/ - which
I would prepare for you with this example but it is somehow not running
- not showing any graph - this was taken 1:1 from one of your examples -
so I stuck.

Regards
Fabio



Am 5.6.15 um 19:28 schrieb Alex:
> Look in your console, some of these option are not in v4.
>
> Look at our examples. Can you reproduce the behaviour there?
>
> I can't debug like this. Reproduce it somewhere simple and I can fix
> it or you'll find your issue when attempting to reproduce.
>
>
>

**Comment by redskate** [comment]
Hi Alex

it seems that you reworked the lib 4.2 completely with respect to 3.

I thaught I could simply substitute 3.0.3 through 4.2 and have a happy
life.
Instead of that I need to reengineer parts of my javascript code and
this will take some time...

It seems that functions like  *data.edges.get*(evtproperties.edges[0]);
- working with 3.0.3 - be no longer available.

Sorry for my long mailing.

Have a nice weekend
Fabio





Am 5.6.15 um 19:28 schrieb Alex:
> Look in your console, some of these option are not in v4.
>
> Look at our examples. Can you reproduce the behaviour there?
>
> I can't debug like this. Reproduce it somewhere simple and I can fix
> it or you'll find your issue when attempting to reproduce.
>
>
>

**Comment by AlexDM0** [comment]
Hi,

Yes it has been a full rewrite :). I think it's worth it though. Code was getting a mess. 

You didn't tell me you use internals, those may change without notice. If you use your own dataset you don't have to use the one in the network. 

Good luck!

**Comment by redskate** [comment]
Yes internal may change without notice...

Anyway - updating an edge ***color*** should ***not*** scramble the
nodes positions ... what do you think?

Fabio


Am 5.6.15 um 20:57 schrieb Alex:
> Hi,
>
> Yes it has been a full rewrite :). I think it's worth it though. Code
> was getting a mess.
>
> You didn't tell me you use internals, those may change without notice.
> If you use your own dataset you don't have to use the one in the network.
>
> Good luck!
>
>
>

**Comment by AlexDM0** [comment]
It doesn't. If you make a fiddle I can show you what's going wrong. 

Regards

**Comment by redskate** [comment]
Hi Alex

As I said - I tried in http://jsfiddle.net/redskate/Lmvmvxcy/14/
but stopped ... beacouse apparently visjs does not work there ... (no
errors, nothing happens)...

It is just an edges.update({di:xxx, color:"red"}) which caused the
scrambling.

Regards
Fabio





Am 5.6.15 um 21:25 schrieb Alex:
> It doesn't. If you make a fiddle I can show you what's going wrong.
>
> Regards
>
>
>

**Comment by redskate** [comment]
Hi Alex

I switched back - meanwhile - to 3.11.0.

I would like to have bigger dots (bigger circles) than now

where is please the documentation for 3.11.0 ?

Thanks
Fabio

**Comment by redskate** [comment]
I think the current fiddle is http://jsfiddle.net/redskate/Lmvmvxcy/17/
but ... same thing...
Cheers
F
PS: "radius" was the answer to the previous question


Am 5.6.15 um 21:39 schrieb Fabio Ricci:
> Hi Alex
>
> As I said - I tried in http://jsfiddle.net/redskate/Lmvmvxcy/14/
> but stopped ... beacouse apparently visjs does not work there ... (no
> errors, nothing happens)...
>
> It is just an edges.update({di:xxx, color:"red"}) which caused the
> scrambling.
>
> Regards
> Fabio
>
>
>
>
>
> Am 5.6.15 um 21:25 schrieb Alex:
>> It doesn't. If you make a fiddle I can show you what's going wrong.
>>
>> Regards
>>
>>
>>

**Comment by AlexDM0** [comment]
Hi,

The jquery function was wrong:

```
$(document).ready(function () {  
    draw();
}   // needs a closing ) !
```
So the function did not fire. 

Once we fix that we get the error that you define vis.js shoudl be here: www.visjs.org/vis.js whereas it is here www.visjs.org/dist/vis.js

Vis js works fine in jsfiddle. Check your console.log for errors :).

I prefer jsbin so here: http://jsbin.com/huvafacuku/1/edit?html,output

You can look here for how the dataset works and that it does not need to restabilize after a change (edges are exactly the same):

http://visjs.org/examples/network/data/datasets.html

We do not suppot the 3.x branch anymore nor is the documenation online. You can however download the packages on git and the docs are included there:

https://github.com/almende/vis/releases

If you do setData, it restabilizes. The dataset is ment for this with the update, add, clear etc functions.

Regards
