### ISSUE TITLE
Tooltip in 4.2

### ISSUE THREAD

**Issue by redskate** [almende/vis#934]
Hi Alex 

in my old implementation 3.0.3 I had as option the spec

tooltip: {
			    delay: 700,
			    fontColor: "black",
			    fontSize: 8, // px
			    fontFace: "Arial,sans-serif",
			    color: {
			      border: "#aaa",
			      background: "red"
			    }
}

Now it seems this spec be not taken, I cannot change the tooltip - and since there is not a search function in the doc, I have to click all over the links to get to the (nice) content.

Thank you for any hint (anybody).

Regards
Fabio

**Comment by Peter-Gabel** [comment]
Redskate,
Some things are different in V4.x.  For example, the documentation at http://visjs.org/docs/network/interaction.html states: "When nodes or edges have a defined 'title' field, this can be shown as a pop-up tooltip. The tooltip itself is an HTML element that can be fully styled using CSS. The delay is the amount of time in milliseconds it takes before the tooltip is shown." 

The option for setting the delay is now
interaction: {tooltipDelay: 700}

And Alex - Thanks for your great library!
Peter Gabel

**Comment by AlexDM0** [comment]
Hi All,

Peter, thanks for helping out :) you're absolutely right! The styling we had in v3 was legacy because the tooltip used to be in the canvas. Since it's a Dom element now (in 3.x too) that does not make much sense, especially since CSS is much more powerful than the option we supplied. 

As for the search in the docs, we do want to make one available but we don't have the time at the moment. We're always open for pull reqs to improve the docs though! 

Regards

**Comment by redskate** [comment]
Thank you Peter!!!
And of course: Thank you Alex :)

I would like to style the tooltip in CSS - cannot get to its specs and I
cannot grasp the element while already 3 mm before the mouse ;)

Where is the spec for styling this? Any idea please?

Thanks again
Fabio


Am 5.6.15 um 18:23 schrieb Peter Gabel:

**Comment by AlexDM0** [comment]
It's something like vis-tooltip. I'd suggest control f the CSS for tooltip. I'm on mobile now so can't check. 

Regards

**Comment by redskate** [comment]
ok, Alex

Thank you!
Regards

F


Am 5.6.15 um 18:47 schrieb Alex:
> It's something like vis-tooltip. I'd suggest control f the CSS for
> tooltip. I'm on mobile now so can't check.
>
> Regards
>
>
>

**Comment by redskate** [comment]
div.vis-network-tooltip

found and corrected - thank you :)

Fabio



Am 5.6.15 um 18:47 schrieb Alex:
> It's something like vis-tooltip. I'd suggest control f the CSS for
> tooltip. I'm on mobile now so can't check.
>
> Regards
>
>
>
