### ISSUE TITLE
Left panel subitems support (mapped to subgroups)

### ISSUE THREAD

**Issue by xsebas21** [almende/vis#935]
I could not find an example of it, so I think it is not supported.

In the timeline, it would be nice to have subitems in the left panel, that could be mapped with the item's subgroups. Maybe with a small indentation, but in the same 'block' as the group.

Many thanks.

**Comment by josdejong** [comment]
Do you mean like: https://github.com/almende/vis/issues/660 (duplicate?)

**Comment by xsebas21** [comment]
Yeah, that's right. The functionality would be the same from #660. I think
it can be useful in many scenarios where items / tasks / processes are
broken down into smaller pieces.

S.

**Comment by josdejong** [comment]
Ok thanks. I will close this issue and we can continue the discussion in #660
