### ISSUE TITLE
problem with storePositions()

### ISSUE THREAD

**Issue by sunscreen** [almende/vis#937]
Hi Alex I cant get this to work I disabled any clustering code, although my nodes still have there cid's but not all nodes have cid's any way .. and no x,y values get written to the data set??

also just as a side note html/svg in nodes also wont work with storePositions() ;( 
Perhaps store the resultant img as a base64 url to fix this when you do storePositions.. not sure 

So I think I am stuffed any way unless I stored the nodes x/y in a manual fashion and dumped the data in a proprietary manor and then rebuild the network as you would normally but including x/y values from the separately stored data

any ideas on the? 

thanks

ps ...
also other side note, when using network.fit() and network.focus  it flickers the map/graph before it does the network.fit if you want me to elaborate on this I will happily make a new issue for it

**Comment by AlexDM0** [comment]
Hi,

You don't actually supply any code. What can't you get to work?

Regards

**Comment by sunscreen** [comment]
Hey Alex.. you like to reply quickly :) top man.. um yeah sorry and much obliged :)

/* some time earlier in global scope */

    var jsonData=[];
    var visjsdata = {nodes: nodes,edges: edges};


/* some time later in document.ready */

	    $('#savemap_btn').click(function(e) {
		network.storePositions();
		var jqxhr = $.post( "syncmapdata.php",{data: JSON.stringify(visjsdata)}, function(retdata) {
		console.log(visjsdata);   /* x y values did not update :( */
		});
 
		});


	    $('#loadmap_btn').click(function(e) {
		mapdatafile = "mapdata/storedmapdata.json";
		$.getJSON( mapdatafile, function( data ) {
		delete(visjsdata);
		jsonData=data;
		visjsdata=jsonData;
		

		});
		draw();
                });

**Comment by sunscreen** [comment]
hey Alex!!!!

Dont rack you brain to much mate I realized that it is working in a actual DATASET but not in just a plain array mode..  as the docs did in fact make clear so my bad ;( ...

but now  the problem I have now is how to convert the JSON interpretation of the nodes/edges array that gets stored as a string on the server back to a DATASET and of course I should be using network.setData in hand with this just not sure how .. 

/* Changed code to use actual DATASET */

	    $('#loadmap_btn').click(function(e) {
		mapdatafile = "mapdata/storedmapdata.json";
		$.getJSON( mapdatafile, function( data ) {
		delete(jsvisdataset);
		jsonData=data;
		jsvisdataset=jsonData;
	
		network.setData(jsvisdataset);
		console.log(jsvisdataset);

		});
		});

sorry my brain is refusing to  co-operate with it self tonight

**Comment by sunscreen** [comment]
Hmm out of the blue!

network.storePositions(); 

now generates:
Uncaught TypeError: Cannot read property 'items' of undefined

**Comment by AlexDM0** [comment]
Hi,

You can use dataset.get() (double check the docs for exact options, I'm on mobile ;)) to get an array of objects that you can use in a new dataset. 

JavaScript provides the functions JSON.stringify() and JSON.parse() to convert them into string and back into JSON. These functions work on JSON as well as an array of JSON objects

I'm not sure why you closed the issue? If you can reproduce that error we can solve it. 

Regards,

Alex

**Comment by AlexDM0** [comment]
I see you added code, I think the cause is the way you send and interpret the new data. Please try the JSON functions and print the results in the meantime.

**Comment by sunscreen** [comment]
hi Alex I closed it as I got my self v.confused the items related error was not from storePositions() but from $.post *when you dont JSON.stringyfy it* .. and the issue started to seem confusing I should of just built a test case in the first place .. so alas I will make a test case in jsbin when I get in later today.. I have the actual dataset storing and retrieving fine now but when I setData(data.nodes,data.edges); the map is not redrawing unless I manually redraw it ... and then it draws it with gravity enabled again so I think i just need to options["physics"]=false; before I setData but we can see more clearly later

**Comment by AlexDM0** [comment]
Hi,

Maybe because setData expects an object instead of two separate datasets?

Regards

**Comment by AlexDM0** [comment]
Is this still an issue?
