### ISSUE TITLE
Node border style: double border possible?

### ISSUE THREAD

**Issue by mariusschulz** [almende/vis#938]
I'm currently using Network to visualize a finite state machine. To denote accepting states, I'd like to follow the convention of rendering those nodes with a double border, like in this image:

![finite-state-machine](https://cloud.githubusercontent.com/assets/947523/8019281/ae0f3592-0c46-11e5-9d72-a69a0ddc5521.png)

I saw that we can specify background and border colors for nodes. Is it possible to configure the border style as well?

**Comment by AlexDM0** [comment]
Hi, 

This is not possible at the moment but you could look into the renderEvents example that allows you to draw anything on be canvas. 

Regards

**Comment by mariusschulz** [comment]
Hi Alex,

Thanks, this will probably work :)
