### ISSUE TITLE
3 Issues in one jsbin: recursion error, strange drag behavior and nodes ignoring "fixed"

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#939]
Hi guys,

sorry to bring all this up on a saturday evening.

I created a JSBIN to demonstrate the following three issues:
http://output.jsbin.com/pejohi

The code may look somewhat unorganized - that is because I took snippets from my tiddlymap project and pasted it to the bin. Please excuse.

    Issue 1:
      
    1) Bring your cursor over a node, e.g. "Kill the Dragon" without clicking!
    2) Now try to drag it straight downwards (fast and straight!). It seems that nodes only(!) move when they are at one point also moved on the x axis, otherwise when trying to move them up or down initially they keep standing still. I tested this in chrome and ff on linux. If you cannot reproduce it on the first drag, please go to another node and try dragging it straight downwards (or alternatively upwards)

    Issue 2:

    After dragging a node far to the outside, move the canvas (viewport). The node you just moved will start swirling around again even though it is "fixed".

    Issue 3:

    1) Please go to a node in the jsbin (the actual code).
    2) Remove x and y specification from one of the json node objects (JSON). But leave (!) the "fixed" property.
    3) Reload the bin and you'll get a "too much recursion" error (console).

Thanks!

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

Your first issue is a strange one and I see this in all other examples too. We'll fix it.

Your second issue is a bug in the dragStart event #927. This has been fixed on develop.

The final one, I'll look into. I guess I didnt guess you'd fix somethihg without coordinates :)

Cheers

**Comment by felixhayashi** [comment]
Hi @AlexDM0 

Thanks for picking this up!

> The final one, I'll look into. I guess I didnt guess you'd fix somethihg without coordinates :)

Hehe, expect the unexpected :) This happens because I do not check whether x or y exist nodes beforehand because I load them from a different store and assign them in a later step. In v3.12.0 setting allowedToMoveXY on nodes without XY was not a problem and was simply ignored I guess...

-Felix

**Comment by felixhayashi** [comment]
Hi @AlexDM0 

I locally tested the current snapshot and *problem 2* became worse. Before, when a dropped node was fixed after dragging it only moved after dragging the viewport, but now, it completely ignores that the fixed property is set (in my local environment).

Before creating a bin for this, is there an official way to reference the *develop* branch for `dist/vis.js` in a bin?

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

I'm not sure. We don't host them anywhere else than GitHub. I haven't looked into this issue in full yet, it seems to me that the problem was that the drag start always returned the selected node, even if you dragged the view. That means your temporarily setting fixed is false would fire. 

I'll have to look into the code for this but I'll have some time after the 18th. 

Regards

**Comment by felixhayashi** [comment]
Hi @AlexDM0 

with 4.3.0 having been released, you can now clearly see what I was talking about. In the original bin http://output.jsbin.com/pejohi (which now references the 4.3.0 vis.js) You can now see that after dragging and releasing a node the fixing is completely ignored.

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

This release was a little unexpected for me, hence the history information is missing. I'll look at this next week.

Cheers

**Comment by felixhayashi** [comment]
Ok, thanks Alex!

**Comment by josdejong** [comment]
@AlexDM0 Sorry for the unexpected release. I was in the supposition that you didn't have anything open (after asking last Monday) and thought everything was ready for a release from your side.

**Comment by AlexDM0** [comment]
Thats fine :) just didnt have the history updated. There are no half fixes in there at the moment.

**Comment by AlexDM0** [comment]
Hi Felix,

I've pushed a fix for this to the develeop branch. On a sidenote, maybe what you want is in fact disable the physics of the nodes AFTER stabilization. This ensures that they can only be moved by the user. This is a new feature in v4 and it basically just excludes a node or edge from the physics.

Regards

**Comment by felixhayashi** [comment]
Hi @AlexDM0 

> I've pushed a fix for this to the develop branch.

Many thanks

> On a sidenote, maybe what you want is in fact disable the physics of the nodes AFTER stabilization. This ensures that they can only be moved by the user. This is a new feature in v4 and it basically just excludes a node or edge from the physics.

Thanks for the hint! This makes all the node-position-fixing at dragstart and dragend unnecessary, correct? That would be great! 

But does this mean the node is not recognized as "obstacle" anymore by support-nodes when I set `physics: false` on the node? I mean I still want dynamic edges to "move away" from another node.

-Felix

**Comment by AlexDM0** [comment]
Ah yes that is true, the dynamic edges would avoid each other but not the nodes because they will be taken out of the physics model...

in that case.... you'll have to stick with the current setup.

**Comment by felixhayashi** [comment]
> in that case.... you'll have to stick with the current setup.

That's ok, everything works fine with the current setup anyways.

**Comment by AlexDM0** [comment]
Hi Felix, 

Fixes for these issues have been pushed to develop.

Cheers

**Comment by felixhayashi** [comment]
Hi Alex, just tested it and it works fine! thanks

**Comment by AlexDM0** [comment]
Added in release v4.4.0
