### ISSUE TITLE
Specifying callback for configuration object

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#940]
Hi @ dev guys,

is it possible to specify a callback that receives the configuration object (which is captured via the configuration form/interface) instead of using the "generate options button"? I looked at the hidden  code in the example....

    generateButton.onclick = function () {
      _this._printOptions();
    };

...and it would be nice if I could receive the output by callback to process it and store it in the db. 

Thanks!

-Felix

**Comment by AlexDM0** [comment]
Hi Felix, 

I suppose that's possible, we'll take a look at it. 

Regards

**Comment by AlexDM0** [comment]
Hi Felix,

I have added a getOptionsFromConfigurator method. I figured that if you want to use it, you do not want to use the button from the configurator so it'd be better if this was a method compared to an option.

Cheers

**Comment by AlexDM0** [comment]
Added in release v4.4.0

**Comment by felixhayashi** [comment]
Very nice Alex! Many thanks!
