### ISSUE TITLE
Graph2d: Calling destroy or clear can cause exception

### ISSUE THREAD

**Issue by cdjackson** [almende/vis#941]
In the angular directive, I create the chart when the directive is instantiated, and then clear, or destroy when the data is changed. The initial instantiation is only called with an element ID (ie only the first parameter) - I think this is how the directive was originally written when I picked it up, so I left it this way.

Now, in version 4, calling destroy or clear will cause an exception if there is no data.

You might want to consider that this isn't a bug - up to you. I'll probably change the directive to work differently, but reporting the issue in case you want to resolve it.

**Comment by cdjackson** [comment]
In fact graph2d.clear() is throwing an error saying clear() isn't a function. This can be replicated using the examples (at least the 03_groups example) and adding graph2d.clear() after the graph is instantiated.

**Comment by AlexDM0** [comment]
Hi Chris,

We'll look into this. Thanks for letting us know.

Keep up the good work :)

Cheers!

**Comment by josdejong** [comment]
I think we dropped function `clear` from the Timeline and Graph2d on purpose, but I can't remember when and why exactly. I guess because this functionality was duplicate with either clearing the DataSet or just destroying a visualization. So if we keep it that way we should remove the function from the Graph2d docs.

**Comment by AlexDM0** [comment]
Ah yes. I remember now, we wanted to make sure people are aware of what the dataset does and not hide this behind the graph2d. We should remove it from the docs.

**Comment by AlexDM0** [comment]
I have removed it from the documentation.
