### ISSUE TITLE
4.2.0 bug when data is empty

### ISSUE THREAD

**Issue by ewjoachim** [almende/vis#942]
[This changelog](https://github.com/almende/vis/blob/0242a35b32418b53b510e0d1bbdfa117ce7a27e5/HISTORY.md#timeline) talks about changes made by [this commit](https://github.com/almende/vis/commit/16486044019d1fa8e013837ab54b96528ef1108b#commitcomment-11562806) which introduces a bug proved by [this JS Bin](http://jsbin.com/duqawofihu/1/edit?js,console,output)

The link to the commit above also explains the fix.

I would like to do a pull request but I can't right now. If you can solve the problem, thank you in advance. (that might be something we want to test...)

**Comment by AlexDM0** [comment]
Hi Joachim,

Thanks for notifying us. If you want to do a pull that would be great, otherwise we'll fix it for the next release. I don't know when this will be though. 

Regards,

Alex

**Comment by josdejong** [comment]
Thanks for the detailed bug report, this is fixed now in the `develop` branch.
