### ISSUE TITLE
[Network] Problem with editing edges with hierarchical layout on

### ISSUE THREAD

**Issue by micek13** [almende/vis#943]
Hi Alex,

I  think there is a bug in vis.js. When trying to edit edge (move from one node to another) using the built-in GUI - I get the following JS error:
Error: To use the hierarchical layout, nodes require either no predefined levels or levels have to be defined for all nodes.

I can create and delete edges - problem exists only with editing (and only in hierarchical layout).
// Edit
I added sample jsbin:
http://output.jsbin.com/baxasegala

Regards,
Maciej

**Comment by AlexDM0** [comment]
Hi,

The hierarchical layout is actually not supposed to work with the manipulation... It didn't occur to me to use these side by side. I'll put this in the documentation.

Sorry for the inconvenience.

Alex

**Comment by tbaltrushaitis** [comment]
Hi!

This hook fix hierarchical layout issue for version 4.6.1:
Open vis.js in any editor, at line 38182 change:
} else {
to this:
} else if (undefined == node.parentEdgeId) {

Hope this helps!
-Tom

**Comment by mojoaxel** [comment]
@micek13 @tbaltrushaitis Is this still an issue?

**Comment by tbaltrushaitis** [comment]
@mojoaxel, don't know if this actual for the latest version. Will check and back with results, but not earlier than next week.
Thank you!

**Comment by mojoaxel** [comment]
I don't think I can reproduce this with this jsbin: https://jsbin.com/gotawol/2/edit?html,js,console,output
