### ISSUE TITLE
Tooltips should be restored to old behavior of snapping to Node

### ISSUE THREAD

**Issue by ckane** [almende/vis#944]
In previous versions, when a tooltip was displayed, it would snap to the node and remain displayed on-screen if either of the following were true: The mouse remained within the node, or the mouse remained in the tooltip window/rect. Now the tooltip seems to constantly refresh and follow the mouse cursor, which renders it useless for including external hyperlinks within the tooltip window.

I'd like to request we restore the old behavior of keeping the tooltip window displayed and unmoved while the mouse remains inside either the node circle or the tooltip window, or passes between the two within the defined tooltip hide interval. This enables us to display various links within the tool tip, enabling the user to navigate from the graph to data referenced by the nodes.

**Comment by AlexDM0** [comment]
Hi,

I found the old way to be very restrictive when using large networks. Your use case is unexpected but valid though, we'll take it into consideration. You could relatively easily use the tooltip event to make your own tooltip Dom element though, all methods required to get the node through the dataset and get its Dom coordinates are available. 

Regards

**Comment by AlexDM0** [comment]
There's an example on #952 

http://jsbin.com/neladaqimi/5/

Regards

**Comment by AlexDM0** [comment]
I feel the built in tooltips are sufficient for simple information and that the example shows how easy it is to implement one yourself.

Based on this I think the tooltips will not be changed or expanded.

Regards,

Alex

**Comment by ckane** [comment]
I ended up taking the approach of creating another DIV in the same webpage and shrinking down the graph window. I now just use this DIV's innerHTML attribute to render more detailed information and get the work done. As it turns out, this approach ends up being much more effective for our analysts anyways, so in the end I was forced to find an even better way!

**Comment by ckane** [comment]
BTW - events api is really nicely done.
