### ISSUE TITLE
How to make a *balanced* network graph

### ISSUE THREAD

**Issue by stanleyxu2005** [almende/vis#946]
After I have upgraded from 3.x, I noticed the options have been totally refactored. I managed to make my graph work, but I found the node position of network graph is not quite readable. 

![vis-4 2 0](https://cloud.githubusercontent.com/assets/5162687/8051212/59a5ac12-0eac-11e5-9a0b-7556b5cbb8b8.png)

In my case, I don't much care about the physics (gravity calculation) but more about the readability. Is it possible to position nodes as they are in the following screenshot? The 3.x version positions quite similar to the screenshot below.
![expected](https://cloud.githubusercontent.com/assets/5162687/8051216/5f54742c-0eac-11e5-8e07-2cae0ea6102e.png)

Here is my configuration. All nodes will be assigned with a propery `level`.
```
var graphOptions = {
          autoResize: true,
          interaction: {
            hover: true
          },
          width: '100%',
          height: '300px', // actually the value will be calculated at runtime in my real application
          layout: {
            hierarchical: {
              sortMethod: 'hubsize',
              direction: 'UD',
              levelSeparation: 85
            }
          },
          nodes: {
            shape: 'dot',
            font: {
              size: 13,
              strokeColor: '#fff',
              strokeWidth: 5
            }
          },
          edges: {
            arrows: {
              to: true
            },
            font: {
              size: 11,
              align: 'middle'
            },
            color: {
              opacity: 0.75
            },
            smooth: true
          }
        };
```

**Comment by AlexDM0** [comment]
Hi,

Could you make a jsbin to show this? Our examples look fine and centred. 

Regards

**Comment by stanleyxu2005** [comment]
@AlexDM0 http://jsbin.com/pipavi/1/edit?html,output It looks good.

My fault. In 3.x there is a `freezeSimulation` and is removed in 4.x. I do not want nodes to be repositioned, when user drag a node, so I add the following code, which is wrong.
```
            network.once('stabilized', function() {
              network.setOptions({physics: false});
            });
```

**Comment by AlexDM0** [comment]
Hi,

So I take it this issue is closed now or did you have a question on the last part? It should work although maybe you're looking for stabilizationIterationsDone?

Regards

**Comment by stanleyxu2005** [comment]
Thanks for you reply. Now I write such code:
```
function updateGraph(data) {
  network.setOptions({physics: true});
  network.setData(data);
  network.once('stabilizationIterationsDone', function() {
    network.setOptions({physics: false});
  });
}
```
So if data is updated, the network will recalculate the position and after that the position is fixed, unless the data is changed again.
