### ISSUE TITLE
Network background image

### ISSUE THREAD

**Issue by KebiainWoods** [almende/vis#947]
A Network background image would be good, that is specified in the options. I need a background (comprising of 3 different coloured areas) to help group nodes visually. Adding it as another node doesn't work because it's selectable and also dictates the initial scale if larger than the canvas. And adding one with css obviously doesn't move around when I change scale to zoom and focus on nodes.

**Comment by AlexDM0** [comment]
Hi,

Take a look at the render events example. You can use that for what you want. 

Regards

**Comment by KebiainWoods** [comment]
Thanks, this looks just the ticket. Would I add the image like a canvas image into that beforeDrawing function?


On 9 Jun 2015, at 09:38, Alex <notifications@github.com> wrote:

> Hi,
> 
> Take a look at the render events example. You can use that for what you want. 
> 
> Regards
> 
> 
> 
> > On 9 jun. 2015, at 10:32, KebiainWoods <notifications@github.com> wrote:
> > 
> > A Network background image would be good, that is specified in the options. I need a background (comprising of 3 different coloured areas) to help group nodes visually. Adding it as another node doesn't work because it's selectable and also dictates the initial scale if larger than the canvas. And adding one with css obviously doesn't move around when I change scale to zoom and focus on nodes.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> > 
> —
> Reply to this email directly or view it on GitHub.
> 

Kevin Woods
07720716792
XYi Digital Solutions Ltd
www.xyidigital.com

**Comment by AlexDM0** [comment]
I'd recommend drawing ctx.rect in the before drawing. If you want an image, thats possible too but you sound like you just want colored areas. Just draw rectangles :)

Cheers

**Comment by KebiainWoods** [comment]
:) Very true!

Ok last question then I’ll hopefully be able to leave you alone!

I actually need a circle and 3 rectangle. I’ve stumbled at the second though. I have this, which kinda works, only the colour of both ends up being the  #9f0069?! 

Thanks, really appreciated you holding my hand :)


network.on("beforeDrawing", function (ctx) {
    var nodeId = 1;
    var nodePosition = network.getPositions([nodeId]);
    ctx.fillStyle = '#ff00a8';
    ctx.circle(nodePosition[nodeId].x, nodePosition[nodeId].y +10,250);
    ctx.fill();
  });
  
  network.on("beforeDrawing", function (ctx2) {
    ctx2.fillStyle = '#9f0069';
    ctx2.rect(500, 20, 500, 500);
    ctx2.fill();
  });



On 9 Jun 2015, at 11:15, Alex <notifications@github.com> wrote:

> I'd recommend drawing ctx.rect in the before drawing. If you want an image, thats possible too but you sound like you just want colored areas. Just draw rectangles :)
> 
> Cheers
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Kevin Woods
07720716792
XYi Digital Solutions Ltd
www.xyidigital.com

**Comment by KebiainWoods** [comment]
I found the solution! hooray me. Just needed to close then reopen the path.


On 9 Jun 2015, at 11:15, Alex <notifications@github.com> wrote:

> I'd recommend drawing ctx.rect in the before drawing. If you want an image, thats possible too but you sound like you just want colored areas. Just draw rectangles :)
> 
> Cheers
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Kevin Woods
07720716792
XYi Digital Solutions Ltd
www.xyidigital.com

**Comment by AlexDM0** [comment]
Congrats :) glad it works now!

Regards
