### ISSUE TITLE
v4.2.0 timeline - problem with animation and locales configuration option

### ISSUE THREAD

**Issue by AmadejSI** [almende/vis#950]
There seems to be an issue with using 'animation' and 'locales' as part of the configuration options. Using 'animation' throws a console warning - unknown option detected.

Passing a locales object to define the 'current' and 'time' localized values via properties causes an uncaught typeError: Cannot read property 'object' of undefined.

Example:
```
var options = {
 animation: true,
 locales: {
    en: {
      current: 'Current time',
      time: 'Time time'
    }
  }
};
```

**Comment by josdejong** [comment]
The Timeline does not have an option `animation` (you can only pass this as an option to methods like `fit`, `moveTo`, `setWindow`, etc).

There is indeed a bug in the configurator, which fails to validate the `locales` setting. This same issue is the case in Graph2d and Network. @AlexDM0 can you maybe have a look at this?

**Comment by AlexDM0** [comment]
I can take a look at it after the 19th. I think you refer to the validation instead of the configurator?

**Comment by josdejong** [comment]
You are right, this is about the validator, not the configurator.

**Comment by josdejong** [comment]
I've fixed this in the `develop` branch (dist is not up to date)
