### ISSUE TITLE
Small Nodes in Big Nodes

### ISSUE THREAD

**Issue by chase1991** [almende/vis#954]
Hi,

Is there any way to add a node in an existing node? Specifically, it is like concentric circle where a big circle contains another smaller one. Furthermore, if we can do that, can we guarantee that small node will be moved with bigger node when user drags the bigger one?

Thanks. 

Shi Cheng

**Comment by Tooa** [comment]
Hi, 
take a look at [this](http://visjs.org/examples/network/events/renderEvents.html) example. You can basically draw everything around your node. Does this help and fit for your use case?

**Comment by chase1991** [comment]
Hi @Tooa thank you for your help, that's very helpful:)

**Comment by AlexDM0** [comment]
Hi Shi,

Does that solve your issue? I'm afraid what you mention initially is not possible. We do not support dynamically pairing of nodes. The physics would interfere for starters. 

If you disable the physics (momentarily) the process could be:
listen to the release event, see if there is a node below the pointer using getNodeAt, cluster the node you have and the node under the pointer using the clustering and use the renderEvents to draw them in your preferred style. 

Regards,

Alex

**Comment by chase1991** [comment]
hi alex,

yes, you are right. instead of what i am thinking at first, i use group and cluster as a walk around. they works fine and my manager is satisfied with that. even though i did not show that to my customer, that is still a good way for my current project.

thanks.

shi
