### ISSUE TITLE
[Network] Problem with deleting edges

### ISSUE THREAD

**Issue by micek13** [almende/vis#955]
Hi All,

When trying to prevent from deleting edges in the following way as descibed in docs (I know this is a silly case - in real code in only prevents from deleting in some cases):

manipulation: {
            enabled: true,
            deleteEdge: function (deleteData, callback) {
                alert(deleteData);
                callback();
            }
        }

The manipulation GUI disappears after this code is executed. There is something wrong with callback call - I tried passing null and not executing this function yet that didn't help.

I found a workaround though - you need to "clean" deleteData - set nodes and edges to empty array and pass it to callback. Then the UI reappears.

You can check at (press Run with JS):
http://jsbin.com/naduteciku/7/edit?html,output

Regards,
Maciej

**Comment by AlexDM0** [comment]
Hi,

Is this the same as #949 ?

Regards

**Comment by micek13** [comment]
Right - it's the same issue.

**Comment by AlexDM0** [comment]
I'll close this one so we can continue the discussion there. Thanks for the elaborate explanation and the example though :)

Cheers
