### ISSUE TITLE
Network Angled Edges

### ISSUE THREAD

**Issue by MarcelK28** [almende/vis#956]
Hello there. Thank you so much for creating such an amazing library. It does everything that I need for my purposes.

I know that the Edges can be configured so that they are either smooth curved or straight. However, I'm working on a project where all the nodes are stabilised with X an Y co-ordinates hence they don't move but the Edges are always straight and crossing each other.

Is there a way to create the Edges/connections more Angled so it almost looks like the flow chart?

Example (see the orange egdes): http://www.erp5.com/graphic-Javascript.Flowchart.js.graph.it.screenshot?format=png

Many thanks.

Marcel

**Comment by AlexDM0** [comment]
Hi Marcel,

This is not really possible. The only way to fake this is to have invisible nodes (hidden:true or color:rgba(0,0,0,0)) at the corner points and to just use straight edges.

Regards

**Comment by MarcelK28** [comment]
Hi Alex,

thank you for your reply. Your solution seem like a good hack. Lot of manual work though as I have quite a few nodes.

Thanks anyway.

Marcel

**Comment by AlexDM0** [comment]
Hi Marcel,

I would suggest you give the invisible nodes this color:
```
color:{
  background:'rgba(0,0,0,0)', 
  border:'#ff0000', 
  highlight:{
    background:'rgba(0,0,0,0)', 
    border:'#ff0000'
  }
}
```

That way you can see them and drag them around. You'll also need to give the edges a color instead of the normal inherit (inheriting invisible colors yields no edges).

Regards

**Comment by MarcelK28** [comment]
Hi Alex that makes sense. Thank you so much.

I should probably open a new issue/request for this question: 
"Imagine you hover the node and you nicely see the highlighted edges connected to the desired nodes, which is perfect. It would be nice to have a feature that when you hover the node, you get only the highlighted edges and the nodes and everything else gets faded out or given opacity 0.5. So that the highlighted relationships would stand out?"

**Comment by AlexDM0** [comment]
So you want this:
http://visjs.org/examples/network/exampleApplications/neighbourhoodHighlight.html

on a hover event. We have a hoverNode event, the rest of the code can be used for doing what you want.

**Comment by MarcelK28** [comment]
Oh yes yes - perfect, let me try to use it with my project. I'm still on version 3 hope thats ok and also using image shapes, hope they will greyed out too.

**Comment by AlexDM0** [comment]
We do not support v3 anymore and the example will not work with v3. We have redone pretty much everything in network so the examples are only ment for v4.

**Comment by MarcelK28** [comment]
Oh I see. Ok, before I migrate to v4, could you please confirm that 'Neighbourhood Highlight' will work with "image shapes" as well?

**Comment by AlexDM0** [comment]
We do not support opacity in images. Never have. You could work around it though. Change the shape for instance?

I cannot stress this enough, neighbourhood highlight is not an feature, it's an example of what you can do with the events and methods provided by vis. 

Regards

**Comment by MarcelK28** [comment]
Sure, thank you very much for your help.
Kind regards,
Marcel
