### ISSUE TITLE
Define groups clearly and label groups

### ISSUE THREAD

**Issue by Bashima** [almende/vis#957]
I was wondering if it is possible to label groups in network. 
In my case I have more than 30 groups. So, coloring them to differentiate is not a good option. 
Moreover, I have scores for each group which I want to show. 
Is it possible to show the groups using circle at zoom-out view? And with zooming in we can show the edges and the nodes. 
I actually want the network graph to be clear at all zoom levels. Like - Google Map.

**Comment by AlexDM0** [comment]
That sounds like the clustering module. Just cluster by group.

http://visjs.org/examples/network/other/clusteringByZoom.html

Regards,

Alex

**Comment by Bashima** [comment]
Thanks a lot. It was really helpful.
