### ISSUE TITLE
Network: connect 2 nodes by 2 edges?

### ISSUE THREAD

**Issue by mariusschulz** [almende/vis#958]
Let's assume we have two Network nodes, A and B. Is it possible to draw two edges (with different labels) from A to B?

**Comment by AlexDM0** [comment]
... Yes?

**Comment by mariusschulz** [comment]
Let me clarify my question: Is it possible to have the two nodes connected by two edges and have both edges be visible in the rendering?

<img src="https://cloud.githubusercontent.com/assets/947523/8095057/7177ff28-0fcb-11e5-80b6-9908ea40c899.png" width="122" />

**Comment by AlexDM0** [comment]
Yes :)

http://jsbin.com/vokosototi/1/edit?html,output

But I think the problem here is that you disable the dynamic smooth edges. The edges need to by set to dynamic to 'avoid' eachother. This is also the default setting.

Regards,

Alex

**Comment by AlexDM0** [comment]
Sorry, I sent the wrong link. here is the working one
http://jsbin.com/qaxuwuwedu/3/edit?html,output

**Comment by mariusschulz** [comment]
Ah, I see. I would've been a little surprised if that weren't possible. ;)

The problem is probably that I'm using the hierarchical layout. Setting the edge type from my current setting (`"curvedCW"`) to `"dynamic"` doesn't change the rendering. I guess that's a limitation of the hierarchical layout, isn't it?

**Comment by AlexDM0** [comment]
Yes, the hierarchical layout cannot use the dynamic smooth edges.. This is because the physics model behind it. In your case I'm afraid there is nothing we can do for this at the moment.

**Comment by mariusschulz** [comment]
I see. Well, I'll have to avoid this constellation, then.

Thanks for your help and the JS Bin, though!
