### ISSUE TITLE
Add Button on Node

### ISSUE THREAD

**Issue by chase1991** [almende/vis#959]
Hi,

Is there any way I could add button on a node? By "add", I mean the button should be moved with node when user drags it.

Thanks.

**Comment by AlexDM0** [comment]
Hi,

You can do a few different things. You can make a node look like a button and use the select or click event to use it. You can use an image or HTML through svg for this. There is an example on HTML in svg on our website. 

You can also overlay a DOM element with a button on top of the node and use the initRedraw event to reposition it. You'll have to use CSS to pass the mouse events though if you want it to be dragged. 

Regards,

Alex

**Comment by chase1991** [comment]
hi alex,

thanks for your reply!

could you show me the link to the example on html in svg? thanks.

sincerely,

Shi

**Comment by josdejong** [comment]
http://visjs.org/examples/network/nodeStyles/HTMLInNodes.html

(go to http://visjs.org/network_examples.html, search for "HTML")
