### ISSUE TITLE
Cluster Labels (Network Module)

### ISSUE THREAD

**Issue by yamini16** [almende/vis#960]
IS it possible to define the labels and some information for hover function when creating clusters?

**Comment by yamini16** [comment]
I got the label thing. Not sure about hover().

**Comment by AlexDM0** [comment]
Hi, 

I'm not exactly sure what you mean for the "hover function". You can give the cluster colours to show on hover or if you are referring to the tooltip, you can give the cluster a title property. Take a look at the examples on our website. 

You can configure the cluster just like any other node. 

Regards

**Comment by yamini16** [comment]
Thanks. I have one more thing to ask. I need to configure the size of the cluster node depending on the number of nodes it has inside. I was trying to use the value field of node but could not gather how to get the number of nodes in cluster. I thought of using the length of getNodesInCluster() but this property is materializes only after a cluster is already made. Is there any way to solve this issue?

**Comment by AlexDM0** [comment]
Hi,

The processProperties function in the cluster method is designed for this. It gives you all nodes and edges that will be in the cluster and allows you to set the properties of the cluster node based on them. 

Regards

**Comment by yamini16** [comment]
It worked. Thanks.

**Comment by AlexDM0** [comment]
Glad to hear it works. 

If for any reason the documentation or examples did not make the questions you posed clear for you initially, we welcome suggestions for improvements in order to help others also having these problems. 

Regards,

Alex
