### ISSUE TITLE
Transparent Clusters

### ISSUE THREAD

**Issue by SenthilKumarasamy** [almende/vis#962]
Presently, the clusters are not transparent. We cannot see all the internal nodes and edges of a cluster. Is it possible to make the cluster transparent?

**Comment by AlexDM0** [comment]
Hi,

As I've stated in your other issue, no. I don't think this duplicate is required. 

Regards

**Comment by AlexDM0** [comment]
I see now that the other issue was a closed old one. It's not always clear when replying to the emails :). 

You could look into #867 which has some example code with the renderevents to draw a border around a group. 

Regards
