### ISSUE TITLE
Don't run stabilize() on empty data-sets

### ISSUE THREAD

**Issue by ludost** [almende/vis#963]
Hi All,

In the following use-case for the network visualisation, the stabilization is not always effective:

1) Create empty datasets for nodes and edges
2) Setup the network visualisation with these datasets
3) Quickly run update on the datasets with actual data. (like in a separate ajax load cycle)

In this case the stabilization can fail to work, because it starts to run on the empty sets, and doesn't run on the update. Many times it does run however, because the update is done earlier than the stabilize is being scheduled. But there is no guaranteed order. 
Expected behavior: Stabilization only runs once after the first update() of the data.

Greetings,
Ludo.

**Comment by AlexDM0** [comment]
Hi Ludo,

This is fixed on the develop branch. We'll include it in the next release.

Regards,

Alex

**Comment by felixhayashi** [comment]
I have to say many many thanks @ludost for spotting this!!! (and @AlexDM0 for fixing of course)

I have always(!) run the network with an empty dataset and only afterwards populated it. This is why stabilization iterations where not taken into account and the graph never really to stabilized and I took it for the natural behavour of vis. 

Now everythink works so perfectly!! Being aware of the danger that this will make me appear like a total programming nerd I still feel the need to say that this bugfix *really* made my day :)

-Felix

**Comment by AlexDM0** [comment]
Added in release v4.4.0
