### ISSUE TITLE
ColorPicker broken on IE9

### ISSUE THREAD

**Issue by josdejong** [almende/vis#964]
The Timeline (and I expect Network and Graph2d too) are broken on IE9.

Stackoverflow: http://stackoverflow.com/questions/30676840/vis-timeline-is-not-getting-rendered-in-ie9

The cause seems to be that `ColorPicker` creates an HTML input element and gives this a type `range`:

```
this.opacityRange = document.createElement('input');
this.opacityRange.type = 'range';
```
Code: https://github.com/almende/vis/blob/master/lib/shared/ColorPicker.js#L342

So we should 

1. make the ColorPicker working on IE9 too, and
2. possibly lazy load the `ColorPicker` or the `Configurator`, it's now always loaded event if you don't use the `Configurator`.

**Comment by AlexDM0** [comment]
Lazy loading and a try catch would probably be for the best. Do you want to look at this?

**Comment by josdejong** [comment]
Yeah can do that though it's a bit hard to test when running linux ;)
