### ISSUE TITLE
Timeline: items from different groups when selected and moved on timeline jumps to one group automatically

### ISSUE THREAD

**Issue by matikucharski** [almende/vis#965]
When I'm selecting two items on timeline from two different groups and I start moving them the second one automatically jumps to the group of item I started dragging. I thinks it is not supposed to be. If I'm using onMoving callback I can see that first argument for second item from very beginning shows me a wrong group id.

**Comment by josdejong** [comment]
Thanks, it's on the feature list to improve this behavior, see also https://github.com/almende/vis/issues/192

**Comment by matikucharski** [comment]
Thx for the quick reply. Is there some workaround for this for now? Maybe disabling multiselect from different groups? When can we expect this feature done? - more less of course :)

**Comment by josdejong** [comment]
Maybe you can do something with the `onMoving` handlers: these allow you to manipulate items while dragging them.

**Comment by yotamberk** [comment]
@matikucharski seems to be solved in v4.17.0! If still happens to you, please reopen this issue =)
