### ISSUE TITLE
Lose Hierarchy After Unclustering

### ISSUE THREAD

**Issue by chase1991** [almende/vis#967]
Hi,

Just as the title said, could someone give me a hint on how to maintain the hierarchy after unclustering nodes? Basically I want to restore the node to their original level and group after unclustering.

Thanks.

**Comment by AlexDM0** [comment]
Clustering is not really ment for the hierarchical system at the moment. What you could try is use the releaseFunction of the openCluster method to restore the positions?

You'll have to make a jsbin to show what exactly is going wrong in order for me to help you further.

Regards,

Alex

**Comment by chase1991** [comment]
hi Alex,

due to the company policy, i could not make a jsbin for you:( even though i really wish i could do that. However, could you tell me about the release function of openCluster method? I know the openCluster method but i have no idea what is the release function.

Thanks.

**Comment by AlexDM0** [comment]
Hi,

You don't have to share your code, you can make an example. Anyway I'd recommend you read the docs, it's all in there. 

Regards
