### ISSUE TITLE
Tangled support nodes

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#968]
Hi,

it is great that vis comes with a dynamic edge mode where invisible support-nodes are added to ensure the edges move away from obstacles (as nicely demonstrated in the smooth curves example http://visjs.org/examples/network/edgeStyles/smooth.html).

The problem is that the support-nodes often become interlocked:

![selection_357](https://cloud.githubusercontent.com/assets/4307137/8112692/d1e92e6a-1069-11e5-8790-e3f4ac61d69a.png)

Where it should look like this.

![selection_358](https://cloud.githubusercontent.com/assets/4307137/8112696/d7265be6-1069-11e5-905f-c5e9a01edbcc.png)

Is there a way to (partially) avoid this?

Thanks
-Felix

**Comment by AlexDM0** [comment]
I'm afraid not...

It's just the physics simulation. I don't make edge cases (pun not intended). 

Regards

**Comment by felixhayashi** [comment]
:cry:

**Comment by josdejong** [comment]
> It's just the physics simulation.

well, yes and no: the physics simulation is now initialized semi random positions of the nodes right? Isn't that the reason that network can stabilize into different layouts when you run it a couple of times? I mean, if we would make the initialization of the nodes deterministic, wouldn't the network always result in the same predictable layout?

**Comment by felixhayashi** [comment]
Hi @josdejong 

Thanks for your reply :) I think making it deterministic doesn't work in my case because nodes are added and removed dynamically so I cannot "plan" the layout beforehand :(

I thought about an algorithm that checks in which way support-nodes are tangled and whether the respective endpoints of the edges are displayed in the opposite way and in this case simply switch support-node positions to loosen the "knot". But this is just an idea which might not really work...

In any case, I still hope this will somehow get optimized in the future because for dynamically assembled graphs with labels and support nodes it happens quite often. But I completely understand that it is not possible at the moment and I respect the workload you guys have to deal with!

-Felix

**Comment by AlexDM0** [comment]
The physics simulation is deterministic at the moment, but it is determined by the randomSeed. 

This does not help the Felix but you are right. The cause is the initialization. The random
initialization is something I want to improve in the future but that's a lot of work. You could also initialize with dynamic edges off and on stabilisation turn them on and stabilize again. 

The algorithm you propose would be close to O(N^2) for edges so I'm not sure that would be feasible. You could limit it to edges from the same node but there will still be edge cases. Even then it is very expensive. We could implement a stabilization that will enable dynamic smooth edges halfway to improve this though?

Regards

**Comment by AlexDM0** [comment]
I'll reopen this issue, come to think of it there are numerous reasons to enable dynamic smooth curves only at the halfway point (performance as well but maybe only for the initial stabilization). 

Would you like to contribute code for this? I'm not sure when I'll get around to it. The new setup is quite clean and you could use the event messaging to notify the edge module of the start and the halfway point. 

Regards

**Comment by felixhayashi** [comment]
Hi @AlexDM0 

> […] to enable dynamic smooth curves only at the halfway point

That sounds like a great idea.

> Would you like to contribute code for this?

Sure I do, my problem at the moment is that I am so caught up in all my work that I think it is not realistic that I could produce quality code for vis.js :( 

Anyways, I had a look at `EdgesHandler.js` and discovered a handler that allows to disable dynamicness of the support nodes (`_forceDisableDynamicCurves`). So maybe just for my understanding, you suggest that support nodes start off non-dynamic and an antagonist function like `_forceEnableDynamicCurves` is called at the point when in a simulation step (https://github.com/almende/vis/blob/0242a35b32418b53b510e0d1bbdfa117ce7a27e5/lib/network/modules/PhysicsEngine.js#L224) we reached half of the `stabilizationIterations`?

I feel better contributing after I have a better understanding of the vis internals and after working a bit with v4 and having had a deeper look at the code. Hope that's ok with you. At the moment, I believe I can support you guys better by testing and filing reports :D

-Felix
