### ISSUE TITLE
Request to show label both above or below a node

### ISSUE THREAD

**Issue by stanleyxu2005** [almende/vis#969]
Vis will show label below a node. I do see some other network graph library on a presentation that can show set label position to [top] or [bottom] or [top,bottom]. I'd like to know, if you can make the position flexible in Vis?

**Comment by AlexDM0** [comment]
This feature is planned but I cannot give a time frame for it at this time. At the moment this is not possible. 

Regards

**Comment by stanleyxu2005** [comment]
Attached a screenshot with label at top and bottom in different colors. Another interesting feature is a map view at bottom right.
![dag](https://cloud.githubusercontent.com/assets/5162687/8155453/03cd8664-1377-11e5-9653-0504a6191ca5.png)

**Comment by AlexDM0** [comment]
Hi,

What we want to implement is to have to option to choose either top bottom left right or inside positions for the label. I do not think we'll implement multiple labels per node.

Regards,

Alex

**Comment by stanleyxu2005** [comment]
@AlexMD0 If label can be top/bottom/left/right/inside a node, it will be very powerful, to have label at multiple position. Or could you provide some alternative way to let user extend the functionality?

**Comment by AlexDM0** [comment]
You could use the render events to do this manually:
http://visjs.org/examples/network/events/renderEvents.html

**Comment by AlexDM0** [comment]
Did you manage to do this with the render events?

**Comment by stanleyxu2005** [comment]
@alexdm0 No, not yet. I assume the injectable event is `afterDrawing`. But my application manages a complex network graph. It has a lot of nodes. Every node has two labels and the label content is dynamic. If content is updated every 5 seconds. It can be quite a lot redraw work.

**Comment by AlexDM0** [comment]
Yes but that would also be the case if vis did it for you. The beauty of the render events is that you piggyback on a normal redraw cycle. 

Regards

**Comment by stanleyxu2005** [comment]
@alexdm0 thanks for the input. please close the issue, if it is not on the list of request features.
