### ISSUE TITLE
color-graph3d

### ISSUE THREAD

**Issue by nithingit** [almende/vis#970]
Include a option for changing color of the bars in bar chart according to our requirements

**Comment by josdejong** [comment]
Thanks for your suggestion. Good idea to make the coloring customizable, shouldn't be very complicated to implement.

**Comment by nithingit** [comment]
Thanks, when can i expect it?

**Comment by josdejong** [comment]
Well, there is no priority for this on our side (and we're kind of busy at the moment), so it depends a lot of whether someone from the community can pick this up, or whether we can do this in-between something.

**Comment by AlexDM0** [comment]
Hi Nithin, 

You're free to implement this yourself as we don't particularly need this feature at the moment. I'd like to remind you to watch your attitude, we do not work for you. 

Regards

**Comment by nithingit** [comment]
Hi,

Sorry you misunderstood me.I found your js very suitable for my requirement ,so just out of anxiety I asked.I thought you may be working on this.I am very sorry.

**Comment by josdejong** [comment]
@nithingit I've just implemented options `dataColor`, `axisColor`, and `gridColor` for Graph3d, you can give it a try already on the `develop` branch (docs and builds are up to date).
