### ISSUE TITLE
timeline - is it possible to display items above and below a central timeline?

### ISSUE THREAD

**Issue by andrewtennison** [almende/vis#971]
I have a case with 2 different sorts of related data, and I want to be able to display one sort under the timeline and one above. Selecting one under will highlight the related items above.

Is the positioning possible without serious modification?

**Comment by josdejong** [comment]
I don't know exactly what you are creating but this sounds like something which you can do without any modification, the built-in events and methods.

**Comment by andrewtennison** [comment]
what i want to achieve is a visual change, with the dates running horizontally in the middle with one data type above and another below, both connected to the date. 

Is this already possible in the settings?

**Comment by josdejong** [comment]
Sorry I don't understand what you're building.

**Comment by andrewtennison** [comment]
Hopefully this image shows what I mean. You can see the axis is in the middle, with items above and below representing the different data types, income and expense.

![chart example](https://cloud.githubusercontent.com/assets/790628/8181721/6e160f24-1420-11e5-9d96-619ee6e23adc.png)

**Comment by josdejong** [comment]
Ah ok, I get it. Thanks for the clear picture.

One thing you can try is putting two timelines on top of each other, and synchronize their visible window by listening for the `rangechange` event and adjusting the other window accordingly using`setWindow`. For one timeline you hide the axis by setting option `orientation: {axis: ''none'}`.

An other way is to grab the [`Timeline.js`](https://github.com/almende/vis/blob/master/lib/timeline/Timeline.js) constructor and create an extended version where you change construction such that you load an ItemSet, then a TimeAxis, then another ItemSet ([here in the code](https://github.com/almende/vis/blob/master/lib/timeline/Timeline.js#L94-L105)), and adjust the relevant methods such that you can pass two DataSets with items.

**Comment by andrewtennison** [comment]
thanks for the help. I will have a play and create a pull request if i get something working

**Comment by andrewtennison** [comment]
got the styling working so by extending orientation setting I can centre align with boxes above or below. Trying to get 2 dataSets loading is next challenge, there seem to be two options
1. create a new .vis-content container so there are two on the page which can be positioned independently 
2. use extend the group functionality, so one is positioned under, but not effected by the scaling of the first group when zooming

Any thoughts which would be preferable / simpler?

**Comment by josdejong** [comment]
Can't you just add an extra ItemSet? Like the Timeline can create two TimeAxis components?

**Comment by josdejong** [comment]
Ah, no that won't work, sorry. 

You will have to do some experiments, you could go either way with the two options you mention. If you don't use groups, it may be possible to put a second ItemSet in the bottom panel of the Timeline.

Andy it will be valuable for us to get feedback on how we can make the Timeline better componentized, such that you can just grab the parts that you want and put them together the way you want. We have made a start there but still some iterations to go. So if you have ideas in this regard please let us know.

**Comment by andrewtennison** [comment]
No probs, will do

**Comment by mojoaxel** [comment]
@andrewtennison Is this still an issue? If not can you please close this. Thanks!
