### ISSUE TITLE
Using Nodes.update() for Cluster

### ISSUE THREAD

**Issue by chase1991** [almende/vis#972]
Is there any way to change the style of cluster nodes, for instance, using nodes.update()?

Thanks

**Comment by AlexDM0** [comment]
No, this is not possible at the moment. It may be possible in future releases but for now I cannot promise anything.

Regards

**Comment by chase1991** [comment]
thanks, Alex.

**Comment by dragonzone** [comment]
The way to work around this is to open up the cluster, and re-cluster it with the style you want, but make sure when you re-cluster it that your cluster ID is not the same b/c you'll get a phantom link from https://github.com/almende/vis/issues/1055, which i being fixed. I've done this on my project.

**Comment by mojoaxel** [comment]
Since 996298793e06e45c21d9d362fe603a1d8925367c there is a function `updateClusteredNode` for that.

fixed with #2055
