### ISSUE TITLE
Request: HTML labels

### ISSUE THREAD

**Issue by hookdump** [almende/vis#973]
Or alternative, ability to have multiline labels (deciding when to break the line).
If you're open to pull requests, I can try implementing this myself.

**Comment by AlexDM0** [comment]
Hi,

While we are open to pull requests, I think you may want to look at the example page:

http://visjs.org/examples/network/nodeStyles/HTMLInNodes.html
http://visjs.org/examples/network/labels/multilineText.html

Regards,

Alex
