### ISSUE TITLE
Exception when setting focus in network graph

### ISSUE THREAD

**Issue by ndupreez** [almende/vis#976]
I get the following exception when setting the focus in a network graph (ver 4.2.0)

```
vis.js:35532 Uncaught TypeError: Cannot read property 'canvas' of undefined
n.value @ vis.js:35532
o.emit @ vis.js:8905
n.value @ vis.js:34613
n.value @ vis.js:34565
```
We have about 253 nodes and 299 edges.

Called with:
```
                    this.graph.focus(sNodes[0].id, {
                        scale: 1.3,
                        locked: true,
                        animation: {
                            duration: 1000,
                            easingFunction: 'linear'
                        }
                    });
```

**Comment by josdejong** [comment]
Can you create a jsbin demonstrating the issue? The method `focus` seems to work fine in this example: http://visjs.org/examples/network/other/animationShowcase.html

**Comment by ndupreez** [comment]
OK.

BTW, only seems to happen if the graph is still stabilising and also when locked is set to true.

Nick.

**Comment by AlexDM0** [comment]
Hi Nick, 

Is this still an issue? We have not been able to reproduce this..

Regards

**Comment by ndupreez** [comment]
I believe so, but unfortunately don’t have time right now to try and come up with the minimum gist that illustrates the problem. I have worked around it by turning off the locked mode - which does;t seem to cause the issue. 

Will keep you posted. You can close the issue if you want.

Nick.
