### ISSUE TITLE
Graph2d e notation over 100000 number y axis

### ISSUE THREAD

**Issue by web-programmer** [almende/vis#978]
Hi,

The  y axis of Graph2d flips to e notation when range is over 99999 ( min:99999, max:100001 4 example)

**Comment by AlexDM0** [comment]
That is true. 

Assuming this is a question on how to change this instead of a statement, you can format it yourself with the dataAxis format function.

http://visjs.org/docs/graph2d/#Configuration_Options

Regards,

Alex
