### ISSUE TITLE
Network: Multiple edges between two nodes

### ISSUE THREAD

**Issue by Deschamin** [almende/vis#981]
When I make multiple edges between 2 nodes (that have a static position aka no physics) in Vis 4, the edges are over the top of each other.  I'm even making sure that the smooth type is "dynamic", here are the options that I use:

```js
var options = {
		width: "100%",
		height: "100%",
		interaction: {
			dragView: false,
			dragNodes: false,
			zoomView: false,
			selectable: true
		},
		edges: {
			smooth: {
				enabled: true,
				type: "dynamic",
				roundness: 0.5
			}
		},
		nodes: {
			shape: "box",
			font: {
				size: 11
			}
		},
		physics: {
			stabilization: {
				onlyDynamicEdges: true,
				fit: false
			}
		}
	}
```

**Comment by josdejong** [comment]
The dynamic edges do not work in without physics: the invisible support nodes of a dynamic edge needs a physics simulation to find a stable configuration.

**Comment by AlexDM0** [comment]
Hi,

Could you make a jsbin to show me what you are doing exactly?

Regards

**Comment by AlexDM0** [comment]
I would like to point out that a static position is IN NO WAY the same as no physics.

**Comment by AlexDM0** [comment]
Is this still an issue or can we close this?
