### ISSUE TITLE
Doubleclick Event

### ISSUE THREAD

**Issue by chase1991** [almende/vis#984]
I noticed that in visjs, if i double click on one node, then both the events for single click and double click will be triggered. Is there any way to "hide" single click event? 

Thanks

**Comment by AlexDM0** [comment]
Hi,

A double click is two clicks so you get two click events and a double click event. 

There are numerous issues on this and we're debating whether or not this should be handled (and configurable) in vis or just let vis state the ground truth and let the developers do with this what they want. 

You can use a maximum time between two clicks in the click event to check whether or not you want to process the event. In the other issues on double click there is code for this. #203

Regards,

Alex

**Comment by chase1991** [comment]
Thank you so much Alex. I have confirmed that it is OK to show single-click event when user double clicks the node. I'll try to set the time between 2 clicks if I need it in the future.

**Comment by AlexDM0** [comment]
If you want continue this discussion, I propose we do this on the other issue.

Regards
