### ISSUE TITLE
Empty string as node image causes exception

### ISSUE THREAD

**Issue by Tooa** [almende/vis#985]
Hi,

not sure, if this is expected behavior but the following yields an error:

    nodes = [{id: 1,  shape: 'circularImage', image: ''}, ...

with error

    Uncaught TypeError: Cannot read property 'src' of undefined

Sure, you could remove the image attribute, but the question is rather if it should yield an error when not.

**Comment by AlexDM0** [comment]
Hi,

It didn't occur to me someone would willingly pass an empty string into the image attribute. I am poised to leave the error in to remind people that an image url field should not be empty for obvious reasons but I suppose the graceful failing policy ruling JavaScript forces me to add (yet another) exception to the image system. 

Thanks for reporting this, though I wonder how on earth you came across this?

Regards

**Comment by Tooa** [comment]
Hi, 

> Thanks for reporting this, though I wonder how on earth you came across this?

I was porting my d3.js visualization code to visjs, where no image was modeled as an empty string. Anyway, changed the behavior, but I wanted to report this problem. 

cheers.

**Comment by AlexDM0** [comment]
Hi,

A fix for this has been pushed to develop.

Cheers

**Comment by AlexDM0** [comment]
Added in release v4.4.0
