### ISSUE TITLE
Is there any ways to keep the edges "straight" not rounded

### ISSUE THREAD

**Issue by idrissou** [almende/vis#986]
Hello Guys, 

Is there any way to keep the edges straight. They always turn rounded, no matter what size I specify.

edges.push({from: 1, to: 104, length: 2});

I've also tried the roundness option, part of the edges, but alas not working.

Any help on this?

**Comment by AlexDM0** [comment]
Hi,

You sound like you want to disable smooth curves. There is an option for edges called smooth. Disable it. 

The roundness is for static smooth curves whereas you are using (presumably) the dynamic type which is on by default. 

You also don't want to put the length at 2 I think, normal length is around 100. It may cause strange behaviour. 

Regards,

Alex

**Comment by idrissou** [comment]
Tried that earlier, but did not work. 
For the length, I've tried many values and even removing this attribute but did not work.

Check the following images out for reference:

Anyways, thanks for your swift answering.

![graph example](https://cloud.githubusercontent.com/assets/12066194/8200742/ac7054c4-14c9-11e5-8898-f6869c09800e.png)
![graph example 2](https://cloud.githubusercontent.com/assets/12066194/8200743/b09384fe-14c9-11e5-82de-64133662eef8.png)

**Comment by AlexDM0** [comment]
Hi,

I'm going to go out on a limb here and say you're not using v4.x. If you are, look in the developer console for details on how you are misplacing all options.

in v4 this would have to be:

```
var options = {
interaction: {multiselect: true},
manipulation:true,
edges:{smooth:false}
}
```

If you are using the 3.x version, please download the documentation here:
https://github.com/almende/vis/releases

**Comment by idrissou** [comment]
True, I had the 3.9 one, it worked after forking the last 4.x one.

Thanks a lot Alex. Appreciate that!
