### ISSUE TITLE
Viewport doesn't fit when "fit button" is pressed

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#987]
Hi Guys,

I am proud to announce another addition to the great list of strange bugs discovered by me.

Here is the jsbin: http://output.jsbin.com/yibigu

```
Once the first graph is displayed

1. move the viewport (not the nodes)
2. zoom out
3. press the "fit" button (which used to be zoomExtent) - works fine!

Now 

1. click the "click me" button (at the very bottom below navigation buttons)
2. the datasets will be cleared and a second graph will be displayed
3. Maybe wait a few seconds before the stabilization event is fired and the graph is fit again (actually this step is not necessary)
4. press the "click me button again to switch to the first graph
5. try to fit the graph by pressing the "fit" button (which used to be zoomExtent)
6. Neither does it correctly centerize nor is it zoomed (streched) correctly!
```

I think this might be related to the *clear* operation of the dataset, but please make your own judgement.

As always, thank you!

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

I have fixed this on the develop branch. The cause was improper cleaning of the support nodes. 

Mind you, I've also fixed the stabilization which will now not trigger on an empty set. This means that you have to manually call network.stabilize() if you want to stabilize after a complete replacement of the dataset.

Regards,

Alex

**Comment by felixhayashi** [comment]
Hi Alex,

> I have fixed this on the develop branch. The cause was improper cleaning of the support nodes. 

that is great news!

Thank you especially for the hint regarding the `stabilize()` call!

-Felix

**Comment by AlexDM0** [comment]
Thanks for finding these things :) there's really no testing we can do on our side to find all of these..

**Comment by felixhayashi** [comment]
Hi Alex. Everything works fine now! Thanks
-Felix
