### ISSUE TITLE
Constrain timeline range

### ISSUE THREAD

**Issue by nlwillia** [almende/vis#990]
Is there a way to limit the user's ability to change the range displayed in the timeline?  The event handlers don't expose an actual event, so vetoing the rangechange event doesn't seem to be an option.

I have two use cases.  One is setting a hard stop at bounding points to keep the user from scrolling past where there is available data.  The other is to limit how many items they can scale into view at once.

**Comment by josdejong** [comment]
Challenge: check out the configuration options in the docs and see if you options for this...

http://visjs.org/docs/timeline/#Configuration_Options

**Comment by nlwillia** [comment]
Sorry, I was looking at it from an event perspective and didn't notice the min/max configuration options.

**Comment by josdejong** [comment]
You're welcome :)
