### ISSUE TITLE
Fitting Issues.

### ISSUE THREAD

**Issue by irumgodil** [almende/vis#992]
Hi,

I posted this qs. on stack-overflow, but running into some other issues. 

Basically, at the end of stabilization, I want my chart to fit and stay fitted till someone clicks somewhere on the chart.

These are my issues:

1) I am calling the "_fit" and just fit should work, but it does not
2) I am constantly calling "the fit api" to keep the chart fitted - but there must be something better out there?

3) When I click on one of the navigation controls/zoom, until the 'release' event is called - it keeps fitting (due to code below). I want to catch the event of click on any button on the chart. I cannot figure out what that event is. Can someone please let me know. Is there a bug with the 'click' event?

 This is what I am doing:
```

These are my options:

this.options = {
        nodes: {
            shape: 'dot',
            scaling: {
                label: {
                    min: weve.cg.view.ChartVisual.minFont_largeGroup,
                    max: weve.cg.view.ChartVisual.maxFont_largeGroup
                },
            }
        },

        edges: {
            smooth: {
                enabled: true,
                type: "dynamic",
                //   roundness: 0.5
            },
        },

        interaction: {

            multiselect: false,
            navigationButtons: true,
            selectable: true,
            selectConnectedEdges: true,
            tooltipDelay: 100,
            zoomView: true
        },
        physics: {
            stabilization: {
                enabled: true,
                iterations: 250, // maximum number of iteration to stabilize
                updateInterval: 5,
                onlyDynamicEdges: false,
                fit: true
            }
        }
    };

this is the call to stabilize:

   var g = this;
    
    g.fitOnDone = true;

    // Get total node size here. 
    var stabilizationFactor = 400;

    if (nodeLength <= 25) {        
        this.options.nodes.scaling.label.min = weve.cg.view.ChartVisual.minFont_smallGroup;
        this.options.nodes.scaling.label.max = weve.cg.view.ChartVisual.maxFont_smallGroup;
        console.log("font small");
    }
    else {
        this.options.nodes.scaling.label.min = weve.cg.view.ChartVisual.minFont_largeGroup;
        this.options.nodes.scaling.label.max = weve.cg.view.ChartVisual.maxFont_largeGroup;
        console.log("font large");
    }
    g.network.setOptions(this.options);
    g.network.stabilize(stabilizationFactor);
    
and this is what I am setting on my network:

    this.network.on("startStabilizing", function (params) {
               g.viewModel.updateStatus("Starting Stabilization" + " - (60% Done)...");
        console.log("started")
    });
    this.network.on("stabilizationProgress", function (params) {

        var percentStabilizationComplete = params.iterations / params.total;
        var totalPercent = g.startpercentage + percentStabilizationComplete * 40;
        g.viewModel.updateStatus("In Stabilization Iteration number: " + params.iterations + " - (" + totalPercent.toFixed(2)+ "% Done)...");
      //  console.log("progress:", percentStabilizationComplete);
    });
    this.network.on("stabilizationIterationsDone", function (params) {        
        g.network.interactionHandler.navigationHandler._fit();       

        g.viewModel.updateStatus("Loading Complete" + " - (100% Done)...");
        g.viewModel.hideLoading();
        console.log("100% Complete...");

        //viewModel.hideLoading();
    });

    this.network.on("afterDrawing", function (params) {
        if (g.fitOnDone) {
            //    g.fitOnDone = false;            
            g.network.interactionHandler.navigationHandler._fit();            
            g.fitOnDoneIterations++;            
        }
        else {
            console.log("Finshed drawning false", params);
        }
    });   
    this.network.on("click", function (params) {
        console.log("click event");
       g.fitOnDone = false;
    });
    this.network.on("release", function (params) {
        console.log("release event");
        g.fitOnDone = false;
        
    });
    this.network.on("zoom", function (params) {
        console.log("zoom event");
        g.fitOnDone = false;

    });
    this.network.on("stabilized", function (params) {
        console.log("Finshed Loading", params);
    });
```

Thanks.

**Comment by AlexDM0** [comment]
Hi,

Why are you using the internals? You are really not using the API. You should really stick to the normal network.fit() method. I think you just need to set zoomView and dragView to false to avoid the user messing with the view instead of moving it back all the time.

http://visjs.org/docs/network/interaction.html

So by your issues: 
1) thats not a supported function, use network.fit()
2) I assume you dont want the view to move? disable zooming and dragging.
3) whats wrong with the click event? http://visjs.org/examples/network/events/interactionEvents.html

I'm not sure I understand what you're trying to do.. I dont think the after drawing is what you want.

Regards

**Comment by irumgodil** [comment]
1) The network.fit() method does not do anything for me, so I had to call the internal method. the internal method actually works.

2) I want the simulation to keep the chart w/I bounds of the div. I do not want it to stop-simulation, as it is still cleaning up, but I want it to keep fitted. I do not want to disable zooming/dragging - just the nodes/edges to not get out of bounds. 

3) The click works if I click on the canvas. If I click on the "Interaction handler" buttons - no event is raised for "Click".

**Comment by AlexDM0** [comment]
The navigation buttons are DOM elements, you'll have to bind a click handler to those yourself if you want to catch it. 

I don't know why the fit method does not work for you, nor can I check/fix this without the code that causes it.

If you want to keep everything in view, I'd recommend you use the initRedraw event instead of the after event.

**Comment by irumgodil** [comment]
Thanks a lot. Using the initRedraw and keeping a flag to keep things fitted (During my display) is working like a charm. I have removed all other extra code. 

The only thing not working now is that if I render a chart and then render a new chart, the new chart is using the zooms from last chart. the network.fit() there on start/finish is not working. Any ideas how can I start on a clean slate?

thanks so much!

**Comment by AlexDM0** [comment]
Hi,

As I have mentioned in the issue you made specifically for that question, and here, the fit function should work. It is made for this. 

In all my tests it works. If you could show me the code in which it does not I can try to address the issue. 

Let's continue discussion in #991. It's made for this topic after all. 

Regards
