### ISSUE TITLE
Edge scaling is poorly documented

### ISSUE THREAD

**Issue by Tooa** [almende/vis#993]
Hi,

Consider the following [JsBin](http://jsbin.com/koyucuzere/edit?html,output). The values for the edges are logarithmic. I wonder, why not all edges have the same width. Excerpt of the docs:

    function (min,max,total,value) {
      if (max === min) {
        return 0.5;
      }
      else {
        var scale = 1 / (max - min);
        return Math.max(0,(value - min)*scale);
      }
    }

The term `value - min` is negative and scale is something positive with the values provided in the JsBin (Note `min: 10`). So the product is negative and the function returns zero. 

    var scale = customScalingFunction(min,max,total,value);
    var diff = maxWidth - minWidth;
    myWidth = minWidth + diff * scale;

Hence, the `customScalingFunction` yields zero for all given values the partial term `diff * scale` will be zero and the assignment is `myWidth = minWidth`. This means every edge should get the <b>same</b> `minWidth`. This is my expectation, but the real world looks different. Also, what is this `minWidth`? It isn't a config parameter, isn't it?

**Comment by AlexDM0** [comment]
Hi,

Those min max are NOT the ones you supply in the options. Those are the minimum and maximum values of the edges (in your case, 0 and 3.8).

The minWidth and maxWidth (which are wrong in the docs, thanks for that) ARE the min max you put int he options.

Does that explain it for you?

Regards

**Comment by AlexDM0** [comment]
If you want to contribute, we're open to pull requests (to the develop branch) with improved documentation ;)

**Comment by Tooa** [comment]
Hi Alex, 
this makes a lot more sense :+1: 

> If you want to contribute, we're open to pull requests (to the develop branch) with improved documentation ;)

Good point! Will prepare a pull request tomorrow. This will be also my very first one, so I hope I won't do any rookie mistakes. Have a nice evening.

**Comment by AlexDM0** [comment]
Hi Uli,

I was wondering if you were still planning on making the pull req. I'd like to do a release Friday and it would be nice if these clarifications are in there. The request should be to the develop branch :)

Regards

**Comment by Tooa** [comment]
Hi,

I should make it before Friday. How do you prefer the correction:

1. Replace `minWidth` and `maxWidth` in the provided snippet by `scaling.min` and `scaling.max`
2. Add an additional comment, which mentions that e.g `minWidth` is given by `scaling.min`

Best Uli

**Comment by AlexDM0** [comment]
Hi Uli,

Probably the second one. I'll leave it up to you to elaborate the explaination as you see fit. After all, I may not be the best judge for this due to my knowledge of the codebase. 

Thanks!

**Comment by AlexDM0** [comment]
Added in release v4.4.0
