### ISSUE TITLE
hiddenDates not hiding

### ISSUE THREAD

**Issue by drwho22** [almende/vis#994]
I have sets of statistical data for the month, and I'm trying to display just Monday-Friday as line graphs, ignoring the weekends. I'm feeding visjs the data without the weekends, and enabled hiddenDates, but it is still including the weekends, resulting in regular plateaus in the lines. Here is what I am including in the options: 

    hiddenDates: 	{ 
        start: '2015-01-03 00:00:00', 
        end: '2015-01-04 23:59:59', 
        repeat: 'weekly'
    }

**Comment by AlexDM0** [comment]
Hi,

Did you solve this issue?

Regards
