### ISSUE TITLE
Y-axis data overlapping

### ISSUE THREAD

**Issue by rsaungc** [almende/vis#995]
Hi,

Not sure why my y-axis shows so many numbers and overlapping.   Any help is appreciated.  Thanks.

![capture](https://cloud.githubusercontent.com/assets/10384065/8248538/14e867ca-1615-11e5-96f5-e4312d9726e8.PNG)

<dataset>

[{"x":"2015-06-18 15:00","y":"1"},{"x":"2015-06-17 23:00","y":"2"},{"x":"2015-06-17 19:00","y":"2"},{"x":"2015-06-17 15:00","y":"2"},{"x":"2015-06-16 19:00","y":"2"},{"x":"2015-06-16 15:00","y":"2"},{"x":"2015-06-15 23:00","y":"2"},{"x":"2015-06-15 19:00","y":"2"},{"x":"2015-06-15 15:00","y":"2"},{"x":"2015-06-14 23:00","y":"2"},{"x":"2015-06-14 19:00","y":"2"},{"x":"2015-06-14 15:00","y":"2"},{"x":"2015-06-13 23:00","y":"2"},{"x":"2015-06-13 19:00","y":"2"},{"x":"2015-06-13 15:00","y":"2"},{"x":"2015-06-12 23:00","y":"2"},{"x":"2015-06-12 19:00","y":"2"},{"x":"2015-06-12 15:00","y":"2"},{"x":"2015-06-11 23:00","y":"2"},{"x":"2015-06-11 19:00","y":"2"},{"x":"2015-06-11 15:00","y":"2"},{"x":"2015-06-10 23:00","y":"2"},{"x":"2015-06-10 19:00","y":"2"},{"x":"2015-06-10 15:00","y":"2"},{"x":"2015-06-09 23:00","y":"2"},{"x":"2015-06-09 19:00","y":"2"},{"x":"2015-06-09 15:00","y":"2"},{"x":"2015-06-08 23:00","y":"2"},{"x":"2015-06-08 19:00","y":"2"},{"x":"2015-06-08 15:00","y":"2"},{"x":"2015-06-07 23:00","y":"2"},{"x":"2015-06-07 19:00","y":"2"},{"x":"2015-06-07 15:00","y":"2"},{"x":"2015-06-06 23:00","y":"2"},{"x":"2015-06-06 19:00","y":"2"},{"x":"2015-06-06 15:00","y":"2"},{"x":"2015-06-05 23:00","y":"2"},{"x":"2015-06-05 19:00","y":"2"},{"x":"2015-06-05 15:00","y":"2"},{"x":"2015-06-04 23:00","y":"2"},{"x":"2015-06-04 15:00","y":"2"},{"x":"2015-06-03 23:00","y":"2"},{"x":"2015-06-03 19:00","y":"2"},{"x":"2015-06-03 15:00","y":"2"},{"x":"2015-06-02 23:00","y":"2"},{"x":"2015-06-02 19:00","y":"2"},{"x":"2015-06-02 15:00","y":"2"},{"x":"2015-06-01 19:00","y":"2"},{"x":"2015-06-01 15:00","y":"2"},{"x":"2015-05-31 23:00","y":"2"},{"x":"2015-05-31 19:00","y":"2"},{"x":"2015-05-31 15:00","y":"2"},{"x":"2015-05-30 23:00","y":"2"},{"x":"2015-05-30 19:00","y":"2"},{"x":"2015-05-30 15:00","y":"2"},{"x":"2015-05-29 23:00","y":"2"},{"x":"2015-05-29 19:00","y":"2"},{"x":"2015-05-29 15:00","y":"2"},{"x":"2015-05-28 23:00","y":"2"},{"x":"2015-05-28 19:00","y":"2"},{"x":"2015-05-28 15:00","y":"2"},{"x":"2015-05-27 23:00","y":"2"},{"x":"2015-05-27 19:00","y":"2"},{"x":"2015-05-27 15:00","y":"2"},{"x":"2015-05-26 23:00","y":"2"},{"x":"2015-05-26 19:00","y":"2"},{"x":"2015-05-26 16:00","y":"1"},{"x":"2015-05-26 15:00","y":"2"},{"x":"2015-05-25 23:00","y":"2"},{"x":"2015-05-25 19:00","y":"2"},{"x":"2015-05-25 15:00","y":"2"},{"x":"2015-05-24 23:00","y":"2"},{"x":"2015-05-24 19:00","y":"2"},{"x":"2015-05-24 15:00","y":"2"},{"x":"2015-05-23 23:00","y":"2"},{"x":"2015-05-23 19:00","y":"2"},{"x":"2015-05-23 15:00","y":"2"},{"x":"2015-05-22 23:00","y":"2"},{"x":"2015-05-22 19:00","y":"2"},{"x":"2015-05-22 15:00","y":"2"},{"x":"2015-05-21 23:00","y":"2"},{"x":"2015-05-21 19:00","y":"2"},{"x":"2015-05-21 15:00","y":"2"},{"x":"2015-05-20 23:00","y":"2"},{"x":"2015-05-20 20:00","y":"1"},{"x":"2015-05-20 19:00","y":"2"},{"x":"2015-05-20 15:00","y":"2"}]

**Comment by AlexDM0** [comment]
Hi,

Thats.... odd. I'll look into it.

Cheers

**Comment by AlexDM0** [comment]
Ah, the items values (y values) have to be numbers, not strings.

I'll make the graph more robust against this but its good practice to make numbers in fact, numbers.

Cheers
