### ISSUE TITLE
Cannot delete elements with del key anymore

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#997]
Hi @ dev team,

back in the days when vis.js v3.12 was around. I could use the del key for node/edge deletion. Now it is not possible anymore. This feature is really important if you do mind mapping or brainstorming and constantly change the map. Could you please active this again or add an option?

Many thanks
-Felix

**Comment by AlexDM0** [comment]
Hi,

I don't think so.

The reason for this is that the entire manipulation API is now also available in methods. You can use keycharm (also used by vis, and made by me (yeah! shameless self promotion!)) to listen to any key you want and fire the appropriate method. I would prefer no extra options if it is really simple to implement this manually. We already have 250 options and counting!

Regards,

Alex

**Comment by felixhayashi** [comment]
Hi Alex,

I totally agree! I just wasn't sure if this is a bug or not.
I'll go with keycharm then! :)

-Felix

**Comment by felixhayashi** [comment]
Hi @AlexDM0 

is there a way to access the keycharm lib that comes with vis.js? I mean I do not want to import the whole library again if it is already contained in vis...

-Felix

**Comment by AlexDM0** [comment]
Hi Felix,

At the moment no, but I've just added it to the exports. In the next release you'll be able to call it with vis.keycharm.

Keycharm is tiny though, importing it twice shouldnt be a problem :).

Cheers

**Comment by felixhayashi** [comment]
> At the moment no, but I've just added it to the exports. In the next release you'll be able to call it with vis.keycharm.

Thanks Alex!

> Keycharm is tiny though, importing it twice shouldnt be a problem :).

I know but I would need to create a wrapper package so I can use it in tiddlymap's plugin mechanism and this would create a huge overhead. But `vis.keycharm` is great!

-Felix

**Comment by felixhayashi** [comment]
Hi @AlexDM0 

sorry to ask but I just cannot manage to get this to work.

I use keycharm on form input fields and everything works well but I cannot trigger key events that were bound to the canvas

```javascript
  this.network = new vis.Network(this.graphDomNode, this.graphData, this.graphOptions);


  var canvas = this.graphDomNode.getElementsByTagName("canvas")[0]; 
  console.log("canvas", canvas);  // correctly returns the canvas element

  var keys = vis.keycharm({ container: canvas, preventDefault: true });

  keys.bind("delete", function() {
    console.log("hi");
  });
```

do I need to set the focus on the canvas before or something like that? what am I missing?
I had a look at https://github.com/almende/vis/blob/0242a35b32418b53b510e0d1bbdfa117ce7a27e5/lib/network/modules/components/NavigationHandler.js#L155 but I do not see the difference to my code.

Many thanks
Felix

**Comment by AlexDM0** [comment]
Hi Felix,

You need to listen to the div container inside the main container (the one with the tabindex).

Canvas elements cannot have key listeners. Only items with a tabindex I believe ( thats why its there)

Regards

**Comment by AlexDM0** [comment]
more info: https://github.com/AlexDM0/keycharm/blob/master/test/test.html

I'll append it to the readme once I have time and think about it. Feel free to do a pull with the extended readme :)

**Comment by felixhayashi** [comment]
-.- The moment you said it I also noticed you do not use canvas as container but `canvas.frame` which points to the vis-network div. Time for a programming break!

**Comment by felixhayashi** [comment]
But thanks for the help, much appreciated
