### ISSUE TITLE
Chart still not fitting properly.

### ISSUE THREAD

**Issue by irumgodil** [almende/vis#999]
Hi, 

I am not sure if I can reopen #992, so starting a new issue. 

I have published code here, basically, you will notice that some nodes at bottom keep drifting away from the edges of the div still. I really want the chart to stay fitted. Can you please let me know which other APIs need to be called?

Thanks so much!

http://jsbin.com/xavivicezu/1/edit?html,output

**Comment by AlexDM0** [comment]
Hi,

In your code, g.fitOnDone is false in the initRedraw. If I take the fit out of that if statement, it works and keeps everything fitted.

Regards,

Alex

**Comment by irumgodil** [comment]
Great, I should have picked that up. I have removed that bool completely! thanks.

**Comment by irumgodil** [comment]
Hi,
There is another problem, if I remove this check altogether, then each time after my chart has returned, and I am zooming/navigating the chart tries to fit itself. If I add a flag like above, then I am not sure at what point do I activate/de-activate the flag. 
How can I do it so that the chart fits on the first render, but does not try to keep fitting if the zoom/nav are clicked?
thanks. 


     On Monday, June 22, 2015 3:41 AM, Alex <notifications@github.com> wrote:
   

 Hi,In your code, g.fitOnDone is false in the initRedraw. If I take the fit out of that if statement, it works and keeps everything fitted.Regards,Alex—

**Comment by AlexDM0** [comment]
That depends what really is the user experience you want to provide. How would this go? The network keeps fitted but then the user pushes the navigation buttons. What happens? The moment he lets go it snaps back? That seems annoying from a user perspective. They want to zoom in on a node, think they are close, release the button and boom, everything was for naught. 

Then there is the possibility where the automatic fitting is used until the user interacts with it. You could bind listeners to the Dom buttons for this and listen to the dragStart and zoom events to turn off your Boolean. 

So what is the experience you're going for?

You can look for the children of the container and addEventListeners to all divs?

Regards
